### ISSUE TITLE
unbindVideoElement not working

### ISSUE THREAD

**Issue by timanderson** [aws/amazon-chime-sdk-js#1000]
I am calling  MeetingSession.audioVideo.unbindVideoElement from my JavaScript. Verified that the tileId is valid and no error is reported, but the video continues to play in the bound video element.

Expected: that the video would stop playing in the video element.

**Comment by michhyun1** [comment]
@timanderson Please refer to this issue: https://github.com/aws/amazon-chime-sdk-js/issues/627
