### ISSUE TITLE
realtimeSubscribeToAttendeeIdPresence() Observer is Providing Wrong Status Value

### ISSUE THREAD

**Issue by Anisubhra** [aws/amazon-chime-sdk-js#1001]
[log.txt](https://github.com/aws/amazon-chime-sdk-js/files/5794112/log.txt)

**Meeting and attendee IDs:**
List the meeting and attendee IDs that the attached logs apply to.
Meeting ID: 09e195a5-77c6-4cdc-b6e2-464b1a3e0c08
Attendee ID: 4170e1fd-85b7-81ad-ab38-f712c96cc936

**Describe the bug**
We are running into a weird scenario with Chime SDK.

Scenario: User A joined and muted himself. Then User B joined, but User A is showing unmuted to user B, which is unexpected.
Reason Observed: Roster observer is getting called twice and providing different values each time for the same attendee. The first time it's providing the muted value as true, and then immediately the next time mute value is null for the same attendee. This is happening automatically through the observer; we are not calling any function or observer explicitly.
Attached Screenshot Of roster console log.

It would be great if you can shed some light on this.
Thanks.

**Platform**
 - OS: Windows 10
 - Browser: Google Chrome
 - Browser Version: Version 87.0.4280.141 (Official Build) (64-bit)

**Comment by nicklera1** [comment]
HI @Anisubhra,

Looking at the logs I see there are some disconnection happens prior to rejoining at which points the initial state of "muted" attendee is reset when attendee rejoins again. 

For me it's hard to debug what could be causing that, but maybe full log for session for each users could help and if you could record the session video that would help to understand context.  Looking at your hosted solution I also see that you trying to store via a cookie video and audio states and pass along user choices, however not sure if you do anything with them upon meeting join step I would assume its to persist user choice for video/audio (on/off) upon joining meeting.  Have you tried  https://github.com/aws/amazon-chime-sdk-js/tree/master/demos/browser to see if the same issue exists?

**Comment by vidya-mohan** [comment]
Resolving as no response. Please cut a new issue or reactivate if this persists
