### ISSUE TITLE
No Audio IN on Safari on iOS devices

### ISSUE THREAD

**Issue by matteobombardi** [aws/amazon-chime-sdk-js#1004]
Hello,

I'm facing a strange issue on Safari for iOS (14.2) device: the mic seems muted

- I start a 1 to 1 call
- the video works fine
- the audio output works fine on all devices
- the iOS device does not send audio
- the same page on Android works fine

`let x = await this.meetingSession.audioVideo.chooseAudioInputDevice (audioInputDevice [0] .deviceId)`

x == undefined

Could you please advice?

**Comment by ellismarte** [comment]
Did you enable mic?

**Comment by nicklera1** [comment]
Hi @matteobombardi,

Are you running your test using our Demo App Example? If not could you please try getting our Demo Example working and test again. I just tried number of iOS devices and can't seem to replicated this.
I only come close to this sort of case when I disable Mic on iPhone (click on Safari Mic Icon to cross off) and another when mic selected as "None" as seen on screenshoot bellow.
<img src="https://user-images.githubusercontent.com/20075335/104392829-d14be780-54f7-11eb-863d-5c267c27495a.PNG" alt="drawing" width="250"/>
based on your example 
```
 let x = await this.meetingSession.audioVideo.chooseAudioInputDevice (audioInputDevice [0] .deviceId)
``` 
 ```x ``` is going to ```undefined``` all the time as [this function ](https://github.com/aws/amazon-chime-sdk-js/blob/63f4e61c0ace5d6b38dcb0abbfbc756d79367f7e/src/devicecontroller/NoOpDeviceController.ts#L31)won't return anything, as its only setting device within meetingSession context.

**Comment by nicklera1** [comment]
Resolving! Feel free to re-open if more help needed!

**Comment by thaithanhdhv** [comment]
@nicklera1  I got this issue. Can you help to fix?
