### ISSUE TITLE
Question: better support for recording meetings

### ISSUE THREAD

**Issue by Aarondorn2** [aws/amazon-chime-sdk-js#1011]
The recording demo provides great documentation on building an always-on bot running on an EC2 instance.  This approach is very costly for infrequent recordings.  Other options include scaling containers on Fargate or something similar to only request hardware as needed, but this has the negative effect of requiring several minutes of provisioning.  There does not seem to be a cost effective way of scaling recording via a bot without a poor user experience.

has this been discussed?  Are there any plans to potentially offer the bot recording as an amazon service so that we don't need to provision our own resources for this task?

**Comment by tindevelopers** [comment]
This would be useful for our application as well.

**Comment by gustavofamorim** [comment]
Would be very useful for my application as well.

**Comment by RidipDe** [comment]
Thank you for your interest in the Chime JS SDK. 
Since this is not a feature that we currently support, will keep this issue active.

**Comment by tenge-amzn** [comment]
Hi there, 
We launched a service to capture the content of the meeting. Check out if you are interested in using our service to capture the SDK meeting. You won't need to provision your own infrastructure to do the job.
[What's new?](https://aws.amazon.com/about-aws/whats-new/2021/07/the-amazon-chime-sdk-adds-media-capture-pipelines-to-enable-capture-of-meeting-video-audio-and-content-streams/)
[Blog post and demo](https://aws.amazon.com/blogs/business-productivity/capture-amazon-chime-sdk-meetings-using-media-capture-pipelines)

Closing this issue, while feel free to reach out if you see any issue.

**Comment by Aarondorn2** [comment]
This is amazing, thank you so much!

**Comment by shanmugavel28** [comment]
@vidya-mohan @tenge-amzn  This is really interesting feature that removes operation overhead to record the media stream. Dumping stream to S3 is great, I am looking for an option to import chime media stream directly to Kinesis / sagemaker for analytics in real time (to avoid read and write operation to S3). the previous method of always on bot EC2 is the only way to get the stream?
Thanks!

**Comment by tenge-amzn** [comment]
Not yet, but we're planning it.. no timeline yet.

**Comment by vidya-mohan** [comment]
@shanmugavel28 please open a community request for a new feature suggestion. We have a template for it
