### ISSUE TITLE
Microphone access on web view implementation 

### ISSUE THREAD

**Issue by amirvatani** [aws/amazon-chime-sdk-js#1014]
Because of bad quality of audio in react native chime sdk ; we are going to implement an audio conference in react native application using web view & Amazon chime , but there is two problem :
1- we can not access microphone in web view
2- some devices built in browser does not support Amazon chime
Please help

**Comment by rnewman** [comment]
Which platforms are you using?

Versions of iOS prior to 14.3 do not allow webviews to use WebRTC, and thus cannot run the Amazon Chime SDK.

Our support matrix is listed here:

https://docs.aws.amazon.com/chime/latest/dg/meetings-sdk.html#mtg-browsers

You might find that newer versions of the SDK support more browsers; for example, we recently added support for Samsung Browser on Android.

Have you filed issues or contacted AWS support about the problems you're seeing with audio in the native SDK?

**Comment by vidya-mohan** [comment]
@amirvatani please follow https://github.com/aws/amazon-chime-sdk-js/issues/1070 as its sounds more pertinent to your question

**Comment by michhyun1** [comment]
FYI - the Chime SDK for Javascript now support WKWebViews. https://aws.amazon.com/about-aws/whats-new/2021/05/wkwebview-now-supported-with-amazon-chime-sdk-for-javascript/
