### ISSUE TITLE
unable to join in meeting in iOS safari

### ISSUE THREAD

**Issue by ashok-work** [aws/amazon-chime-sdk-js#1015]
We are using aws chime js sdk(2.741.0) for meetings.

It was working in windows(Chrome,firefox browsers).

But we are facing issue in iOS safari, especially on join meeting. 

We already given audio and video permissions. 

In console its showing {isTrusted: false} issue and unhandled Rejection: Not Allowed Error.

i am attached screenshot for reference.

<img width="1676" alt="Screen Shot 2021-01-11 at 7 40 31 PM" src="https://user-images.githubusercontent.com/23274570/104979327-07262a00-5a2a-11eb-91c9-2b84dd3057a7.png">

**Comment by rnewman** [comment]
Could you expand the promise rejections there to show the stack?

My off-the-cuff suspicion is that you're joining a meeting without any user interaction (no tapping required), and Safari won't let your page play audio without it.

**Comment by ashok-work** [comment]
Hi Thank for your reply.

I will provide you an entire logs. I will also check the user interaction flow for join meeting.

**Comment by simmkyu** [comment]
`NotAllowedError: The request is not allowed by the user agent or the platform in the current context`

**Comment by simmkyu** [comment]
In your screenshot, the following error comes from `playAudio()` that does not exist in Chime SDK for JavaScript.

```
NotAllowedError: The request is not allowed by the user agent or the platform in the current context
```

Based on [the official Safari doc](https://developer.apple.com/documentation/webkit/delivering_video_content_for_safari) and [this StackOverflow answer](https://stackoverflow.com/questions/65127756/safari-error-when-playing-video-in-react-app), the error might occur when you play an unmuted video without a user gesture. Note that Chime SDK for JavaScript automatically enables the muted property to a video element.

Also, you successfully joined a Chime SDK meeting based on the last log message `session started` from `AudioVideoObserver.audioVideoDidStart`.

Please check if the error happens from SDK. If yes, reopen with full `INFO`-level logs. Thanks!
