### ISSUE TITLE
Unable to test using git fetch --tags https://github.com/aws/amazon-chime-sdk-js, files not getting fetched

### ISSUE THREAD

**Issue by agnel0410** [aws/amazon-chime-sdk-js#1016]
**Important:** Please attach INFO-level logs with timestamps to the report from *before* the session started up until the point at which the unexpected behavior occured. For multi-participant calls, attach a log file for each participant if possible.

**Meeting and attendee IDs:**
List the meeting and attendee IDs that the attached logs apply to.

**Timeline**
Outline the main actions the user performed and when:

* <timestamp> <action>
* <timestamp> <action>

**Describe the bug**
Describe the bug and the timestamp at which it happened relative to the timestamp in the log file.

**Screenshots**
If applicable, add screenshots to help explain the problem.

**Platform**
 - OS: 
 - Browser: 
 - Browser Version: 
 - Amazon Chime SDK GitHub Commit:

**Comment by anuranduttaroy** [comment]
Hey @agnel0410, I tried to run the same command inside the git parent directory, and it worked fine for me.

```
From https://github.com/aws/amazon-chime-sdk-js
 * branch            HEAD                      -> FETCH_HEAD
 ! [rejected]        amazon-chime-sdk-js@2.0.0 -> amazon-chime-sdk-js@2.0.0  (would clobber existing tag)
 * [new tag]         amazon-chime-sdk-js@2.1.0 -> amazon-chime-sdk-js@2.1.0
 * [new tag]         amazon-chime-sdk-js@2.2.0 -> amazon-chime-sdk-js@2.2.0
 * [new tag]         amazon-chime-sdk-js@2.2.1 -> amazon-chime-sdk-js@2.2.1
 ! [rejected]        v2.0.0                    -> v2.0.0  (would clobber existing tag)
 * [new tag]         v2.1.0                    -> v2.1.0
 * [new tag]         v2.2.0                    -> v2.2.0
 * [new tag]         v2.2.1                    -> v2.2.1
 * [new tag]         v2.3.0                    -> v2.3.0
 * [new tag]         v2.4.0                    -> v2.4.0
 ```
 
The only time this failed for me if I am out of the parent git directory.
 
 ```
git fetch --tags https://github.com/aws/amazon-chime-sdk-js
fatal: not a git repository (or any of the parent directories): .git
```

Let me know if this helps.

**Comment by nicklera1** [comment]
Resolving! Please feel free to re-open if needed!
