### ISSUE TITLE
Cannot create a meeting with regions other than us-east-1

### ISSUE THREAD

**Issue by asc0910** [aws/amazon-chime-sdk-js#1020]
```js
const chime = new AWS.Chime({ region: 'ap-northeast-1' });
```
When I define the chime with this region, 
```js
chime.createMeeting
```
function returns this error.

```
Credential should be scoped to a valid region, not 'ap-northeast-1'
```

Do we need to use 'us-east-1' always?

**Comment by nicklera1** [comment]
Hi @asc0910 Please[ checkout this](https://aws.github.io/amazon-chime-sdk-js/modules/gettingstarted.html#meeting-service) doc where you will find a little bit more information. 
In short You must currently use ```us-east-1``` as the region when constracting an Chime object: ``` const chime = new AWS.Chime({region: 'us-east-1'});```. once you actually create a meeting you can select a  "Media" region where the meeting will be hosted! 

```
const requestId = uuidv4();
const region = 'ap-northeast-1'; // specify media placement region
try {
  const meeting = await chime.createMeeting({
    ClientRequestToken: requestId,
    MediaRegion: region,
  }).promise();
} catch (err) {
  // handle error - you can retry with the same requestId
}
const meetingId = meeting.Meeting.MeetingId; // meeting ID of the new meeting

```

Hopefully this helps!

**Comment by asc0910** [comment]
Hi @nicklera1 , Thank you for the help.
