### ISSUE TITLE
CI workflow badge reports 'failing' despite CI being green

### ISSUE THREAD

**Issue by rnewman** [aws/amazon-chime-sdk-js#1022]
On the front page of https://github.com/aws/amazon-chime-sdk-js.

**Comment by michhyun1** [comment]
Confirmed that the url is correct, and the latest run of CI Workflow passed. Following up with Github support

**Comment by michhyun1** [comment]
Decided to remove this badge, as the status of the workflow can be seen in the PR, and there is no way to set the badge to report the status of all runs, not just the runs in a specific branch. https://github.community/t/failing-badge-status-for-passing-runs-and-filters-not-working-correctly/141536/6
