### ISSUE TITLE
Reconnect Timeout Sync #P43741720

### ISSUE THREAD

**Issue by tylerlot** [aws/amazon-chime-sdk-js#1024]
Not so much a bug as a feature request, but I noticed that the duration for the system to attempt reconnect on Web clients is set to 2 minutes, however, on mobile clients reconnect seems to time out around 3 minutes (based on my testing, couldn't find exact line of code where this timeout is set). I was wondering if it would be possible to either a) allow the user to configure this max reconnect timeout duration or b) sync the durations across sdk implementations. Either way the goal would be to enable consistent meeting "contracts" across clients. (For example, how long to wait from when a peer drops to determine they are not returning to the meeting session)

**Comment by nicklera1** [comment]
@tylerlot Thank you for your observations and feedback. I have created backlog item for this request. Will keep this ticket updated with progress!

TT#P43741720

**Comment by nicklera1** [comment]
@tylerlot However, you can override default timeout and build your own custom version of SDK, here is the code pointers
  MeetingSessionConfiguration.connectionTimeoutMs.
https://github.com/aws/amazon-chime-sdk-js/blob/7d764d431bf489ae65ca3480d1ca62a2c3104081/src/meetingsession/MeetingSessionConfiguration.ts#L40

And provide the custom health configuration
https://github.com/aws/amazon-chime-sdk-js/blob/7d764d431bf489ae65ca3480d1ca62a2c3104081/src/meetingsession/MeetingSessionConfiguration.ts#L62

**Comment by tylerlot** [comment]
Isn't [this](https://github.com/aws/amazon-chime-sdk-js/blob/7d764d431bf489ae65ca3480d1ca62a2c3104081/src/meetingsession/DefaultMeetingSession.ts#L29) the line I would want to tweak? The definition of the connectionTimeoutMs you linked, based on the defintion in the docs, sounds more like the allotted time from invoke` audioVideo.start` to seeing the `realtimeSubscribeToAttendeeIdPresence` callback resolving with our own connection

**Comment by simmkyu** [comment]
> Isn't [this](https://github.com/aws/amazon-chime-sdk-js/blob/7d764d431bf489ae65ca3480d1ca62a2c3104081/src/meetingsession/DefaultMeetingSession.ts#L29) the line I would want to tweak? The definition of the connectionTimeoutMs you linked, based on the defintion in the docs, sounds more like the allotted time from invoke` audioVideo.start` to seeing the `realtimeSubscribeToAttendeeIdPresence` callback resolving with our own connection

Correct. Chime SDK or JavaScript performs the "start" and other actions up to `MeetingSessionConfiguration.connectionTimeoutMs`. For example, if the "start" action fails to finish in 15 seconds (default), SDK stops and restarts the "start" action for up to two minutes. We have not exposed this `RECONNECT_TIMEOUT_MS` option in the configuration.

**Comment by tylerlot** [comment]
Any update on if/when this item would be included in the roadmap?

**Comment by ltrung** [comment]
@tylerlot I have raised PR #1221 to expose the reconnection configuration in meeting session configuration. If it is approved, it will be released in the next NPM publish.

**Comment by ltrung** [comment]
The PR is merged to master so closing this issue.
