### ISSUE TITLE
How to change Video Codec from H264 to VP8?

### ISSUE THREAD

**Issue by chandruchiku** [aws/amazon-chime-sdk-js#1036]
### What are you trying to do?

We would like to use VP8 codec instead of default H264 which is getting used.

### How can the documentation be improved to help your use case?

Include a section on how to configure codec to be used for Audio and Video. 

### What documentation have you looked at so far?

Searched through the available documentation.

**Comment by simmkyu** [comment]
Unfortunately, Chime SDK does not support overriding the video codec.

Feel free to reopen if you have additional comments and questions.

**Comment by vidya-mohan** [comment]
Reopening as feature request

**Comment by vidya-mohan** [comment]
@chandruchiku could you please add more details on what use cases you are trying to enable with this feature?

**Comment by chandruchiku** [comment]
@vidya-mohan  This would give us ability to switch to codec which customers are comfortable using in their environment. 

Another user has similar requirement #963

**Comment by vidya-mohan** [comment]
Right - i will mark this as duplicate of the older issue: https://github.com/aws/amazon-chime-sdk-js/issues/963 . Please post any user scenarios in that SIM
