### ISSUE TITLE
How can I handle event disconnected session case

### ISSUE THREAD

**Issue by Sujin1135** [aws/amazon-chime-sdk-js#1037]
### What are you trying to do?

  - I've found event handling for disconnected case. but I couldn't find it.

### How can the documentation be improved to help your use case?

  - It's difficult to find what Information do I need from time to time. I think this documentation look like AWS SDK documentation.

### What documentation have you looked at so far?

  - https://aws.github.io/amazon-chime-sdk-js/classes/defaulteventcontroller.html

**Comment by simmkyu** [comment]
You can implement the `audioVideoDidStop` method to handle disconnected cases.

```
import { MeetingSessionStatusCode } from 'amazon-chime-sdk-js';

const observer = {
  audioVideoDidStop: sessionStatus => {
    // This method is called when your meeting ends.
    // You can handle the following status code listed in
    // https://aws.github.io/amazon-chime-sdk-js/enums/meetingsessionstatuscode.html

    const sessionStatusCode = sessionStatus.statusCode();
    if (sessionStatusCode === MeetingSessionStatusCode.Left) {
      /*
        - You called meetingSession.audioVideo.stop() or
        - When closing a browser window or page, Chime SDK attempts to leave the session.
      */
    }
  }
};

meetingSession.audioVideo.addObserver(observer);
```

For more information, please review the following usage examples.
- https://github.com/aws/amazon-chime-sdk-js#stopping-a-session

**Comment by simmkyu** [comment]
If you want to collect client metrics about meeting failures, you can subscribe to the `eventDidReceive` method. Then, handle `meetingStartFailed` and `meetingFailed` events.

```
const observer = {
  eventDidReceive(name, attributes) {
  switch (name) {
    case 'meetingStartFailed':
      console.error(`Failed to start a meeting: ${attributes.meetingErrorMessage} in `, attributes);
      break;
    case 'meetingFailed':
      console.error(`Failed during a meeting: ${attributes.meetingErrorMessage} in `, attributes);
      break;
    default:
      break;
  }
}

meetingSession.audioVideo.addObserver(observer);
```

See https://aws.github.io/amazon-chime-sdk-js/modules/meetingevents.html for all available events and attributes.

**Comment by simmkyu** [comment]
Please reopen if you have any questions about specific disconnected cases you want to handle.
