### ISSUE TITLE
Compilation issues with angular

### ISSUE THREAD

**Issue by EricBoudreau72** [aws/amazon-chime-sdk-js#1038]
Hi,

I'm trying to integrate chime into our angular app and run into a plethora of compilation errors (listed below).

angular 8.3

chime 2.4.1

Thanks

17 import type VolumeIndicatorCallback from '../realtimecontroller/VolumeIndicatorCallback';
               ~~~~~~~~~~~~~~~~~~~~~~~
node_modules/amazon-chime-sdk-js/build/audiovideofacade/DefaultAudioVideoFacade.d.ts:17:37 - error TS1005: ';' expected.

17 import type VolumeIndicatorCallback from '../realtimecontroller/VolumeIndicatorCallback';
                                       ~~~~
node_modules/amazon-chime-sdk-js/build/audiovideofacade/DefaultAudioVideoFacade.d.ts:17:42 - error TS1005: ';' expected.

17 import type VolumeIndicatorCallback from '../realtimecontroller/VolumeIndicatorCallback';
                                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
node_modules/amazon-chime-sdk-js/build/realtimecontroller/DefaultRealtimeController.d.ts:4:13 - error TS1005: '=' expected.

4 import type VolumeIndicatorCallback from './VolumeIndicatorCallback';
              ~~~~~~~~~~~~~~~~~~~~~~~
node_modules/amazon-chime-sdk-js/build/realtimecontroller/DefaultRealtimeController.d.ts:4:37 - error TS1005: ';' expected.

4 import type VolumeIndicatorCallback from './VolumeIndicatorCallback';
                                      ~~~~
node_modules/amazon-chime-sdk-js/build/realtimecontroller/DefaultRealtimeController.d.ts:4:42 - error TS1005: ';' expected.

4 import type VolumeIndicatorCallback from './VolumeIndicatorCallback';
                                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~
node_modules/amazon-chime-sdk-js/build/realtimecontroller/RealtimeController.d.ts:3:13 - error TS1005: '=' expected.

3 import type VolumeIndicatorCallback from './VolumeIndicatorCallback';
              ~~~~~~~~~~~~~~~~~~~~~~~
node_modules/amazon-chime-sdk-js/build/realtimecontroller/RealtimeController.d.ts:3:37 - error TS1005: ';' expected.

3 import type VolumeIndicatorCallback from './VolumeIndicatorCallback';
                                      ~~~~
node_modules/amazon-chime-sdk-js/build/realtimecontroller/RealtimeController.d.ts:3:42 - error TS1005: ';' expected.

3 import type VolumeIndicatorCallback from './VolumeIndicatorCallback';
                                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~
node_modules/amazon-chime-sdk-js/build/realtimecontroller/RealtimeControllerFacade.d.ts:3:13 - error TS1005: '=' expected.

3 import type VolumeIndicatorCallback from './VolumeIndicatorCallback';
              ~~~~~~~~~~~~~~~~~~~~~~~
node_modules/amazon-chime-sdk-js/build/realtimecontroller/RealtimeControllerFacade.d.ts:3:37 - error TS1005: ';' expected.

3 import type VolumeIndicatorCallback from './VolumeIndicatorCallback';
                                      ~~~~
node_modules/amazon-chime-sdk-js/build/realtimecontroller/RealtimeControllerFacade.d.ts:3:42 - error TS1005: ';' expected.

3 import type VolumeIndicatorCallback from './VolumeIndicatorCallback';
                                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~
node_modules/amazon-chime-sdk-js/build/realtimecontroller/RealtimeState.d.ts:4:13 - [39m[91merror TS1005: '=' expected.

**Comment by simmkyu** [comment]
To import Amazon Chime SDK for JavaScript, your application should use TypeScript 3.8.0 and above; however, Angular 8 (`@angular/cli@8.3.29`) strictly requires TypeScript >=3.4.0 and <3.6.0.

Angular 9 (`@angular/cli@9.1.13`) depends on TypeScript ~3.8.3. I was able to import the latest version of Chime SDK for JavaScript in the Angular 9 app. Recommend upgrading to Angular 9 and above.


Chime SDK for JavaScript specifies TypeScript ~4.0.0 in `package.json`, but I had no issue importing SDK in Angular 9.
https://github.com/aws/amazon-chime-sdk-js/blob/05ecc1c79dd3afce33c18dd8f827c6b990089d24/package.json#L71

**Comment by simmkyu** [comment]
Please try Angular 9 and above, and reopen if you have any questions. Thanks!

**Comment by EricBoudreau72** [comment]
Thanks very much
