### ISSUE TITLE
Add unit tests for ScreenShareViewFacade, ScreenShareFacade and DefaultDeviceController

### ISSUE THREAD

**Issue by vidya-mohan** [aws/amazon-chime-sdk-js#104]
**Describe the bug**
Add unit tests for the following classes: 
> ScreenShareViewFacade - (https://github.com/aws/amazon-chime-sdk-js/blob/dd65d7f153c010208c10e03a072259aede542651/test/screenshareviewfacade/DefaultScreenShareViewFacade.test.ts#L5)
> ScreenShareFacade - (https://github.com/aws/amazon-chime-sdk-js/blob/dd65d7f153c010208c10e03a072259aede542651/test/screensharefacade/DefaultScreenShareFacade.test.ts#L5)
> DefaultDeviceController

**Screenshots**

**Platform**
 - OS: 
 - Browser: 
 - Browser Version: 
 - Amazon Chime SDK GitHub Commit:

**Comment by aburnson** [comment]
No longer necessary since these facades are deprecated and will be removed in v2.
