### ISSUE TITLE
`realtimeSubscribeToVolumeIndicator` doesn't fire on Safari

### ISSUE THREAD

**Issue by adambyer** [aws/amazon-chime-sdk-js#1043]
This works fine on Firefox and Chrome but doesn't fire at all on Safari.

 - OS: MacOS Catalina 10.15.7
 - Browser: Safari
 - Browser Version: 14.0.2

**Comment by simmkyu** [comment]
I just tested the [Amazon Chime SDK serverless demo](https://github.com/aws/amazon-chime-sdk-js/tree/master/demos/serverless) in Safari 14.0.3 macOS Catalina 10.15.7. The callback passed to `audioVideo.realtimeSubscribeToVolumeIndicator` was invoked as expected. Could you ensure the following?
- You or other attendees are not muted.
- You or other attendees select the audio input device.

![GitHub 1043](https://user-images.githubusercontent.com/36240708/106942519-1f0fd600-66d9-11eb-91ec-f9791e6685fa.gif)


---

You can verify the `realtimeSubscribeToVolumeIndicator` API using the Chime SDK serverless demo.

1. Follow [this link](https://github.com/aws/amazon-chime-sdk-js/tree/master/demos/serverless) to deploy the Chime SDK serverless demo. At the end of the deployment, you get the URL.
2. Open the demo URL in Safari.
3. Join a meeting.
4. Open a Safari console and run the following code to check if the `realtimeSubscribeToVolumeIndicator` is called. Note that the serverless demo exposes the "audioVideo" object (`app.audioVideo`) for debugging.
    ```
    app.audioVideo.realtimeSubscribeToVolumeIndicator(
      app.audioVideo.audioVideoController.configuration.credentials.attendeeId,
      (attendeeId, volume, muted, signalStrength) => {
        console.log(`${attendeeId}'s volume data: `, {
          volume, // a fraction between 0 and 1
          muted, // a boolean
          signalStrength // 0 (no signal), 0.5 (weak), 1 (strong)
        });
      }
    );
    ```

**Comment by adambyer** [comment]
Thanks @simmkyu! That was my mistake. Sorry for wasting your time.
