### ISSUE TITLE
Voip audio call

### ISSUE THREAD

**Issue by SpurtiB** [aws/amazon-chime-sdk-js#1049]
Hi,
In my react native mobile application registered user A needs to do initiate only **normal voice call** to another registered user B by clicking a button and user B phone should get a ring(sound). Normal conversation will go on between these two users. Is this feature possible using this sdk? 

In the demos I did not found how to initiate immediate call by clicking on a button and how does receiver gets notified by a ring.

**Comment by simmkyu** [comment]
Amazon Chime SDK for JavaScript (this repository) is for building a web API-based meeting application.

Chime SDK offers iOS and Android client libraries.
- https://github.com/aws/amazon-chime-sdk-ios
- https://github.com/aws/amazon-chime-sdk-android

We also have the React Native demo using iOS and Android SDKs. Please ask your question in the React Native repo for help from the Chime mobile SDK teams.
- https://github.com/aws-samples/amazon-chime-react-native-demo
