### ISSUE TITLE
Video tile update can happen before attendee presence

### ISSUE THREAD

**Issue by vidya-mohan** [aws/amazon-chime-sdk-js#105]
**Describe the bug**
It has been reported that the video tile update for an attendee can occur before the realtime controller reports that the attendee is present. We should look into why this can happen and see if there is an opportunity to strictly sequence these either within the SDK or on the server.

**Screenshots**
If applicable, add screenshots to help explain the problem.

**Platform**
 - OS: 
 - Browser: 
 - Browser Version: 
 - Amazon Chime SDK GitHub Commit:

**Comment by vidya-mohan** [comment]
@XHatan comment "The race could happen because when user A joins a meeting where there are already video seng attendees, user A subscribe to audio and video in one round of negotiation. This is different from conventional media client logic where user always joins with audio only first and then subscribes to video in the next round if there are videos to subscribe."

Fixed by #76

**Comment by vidya-mohan** [comment]
aburnson commented on Nov 5, 2019 •

@aburnson :Are we guaranteed to receive audio stream id info before video starts subscribing? It seems like this could also race. Perhaps we should wait until we receive the first stream id info before subscribing video?
@XHatan: It is safer to ensure the receipt of audio stream id. I will add that logic too. Thanks for the suggestion.

**Comment by aburnson** [comment]
Effectively fixed by #286 since we wait for the real-time state to update
