### ISSUE TITLE
Speaker Test in Demo App is unreliable on iOS 14.4

### ISSUE THREAD

**Issue by chuckntaylor** [aws/amazon-chime-sdk-js#1051]
**Timeline**
Outline the main actions the user performed and when:

1. Ran `npm run start` to start up the demo meeting application.
2. Used ngrok to make port 8080 accessible on my phone
3. Opened the app with Safari on an iPhone 12 pro max running iOS14.4
4. Provided meeting information on the first screen (meeting name, username, etc).
5. On the 'select devices' screen, there is a 'Test' button for checking the audio output. The audio tone barely works. It sometimes plays, sometimes doesn't. And always, after enough use, it simply stops playing any tone.

On my laptop macOS 11.2 running Chrome version 88, there is absolutely no problem whatsoever. Plays beautifully. It is repeatable, and has no bugs.

Further Question:
Is there a reason why the audio test doesn't simply play an audio file? Is there a reason for generating a tone using the `AudioContext` API?

As far as I can gather, the issue must be in here (part of the `TestSound` class:

```
...
const audioMixController = new DefaultAudioMixController(this.logger)
    if (new DefaultBrowserBehavior().supportsSetSinkId()) {
      try {
        await audioMixController.bindAudioDevice({ deviceId: this.sinkId })
      } catch (e) {
        this.logger?.error(`Failed to bind audio device: ${e}`)
      }
    }
    try {
      await audioMixController.bindAudioElement(new Audio())
    } catch (e) {
      this.logger?.error(`Failed to bind audio element: ${e}`)
    }
    await audioMixController.bindAudioStream(destinationStream.stream)
    new TimeoutScheduler((this.rampSec * 2 + this.durationSec + 1) * 1000).start(() => {
      audioContext.close()
    })
...
```

**Platform**
 - OS: iOS 14.4
 - Browser: iOS Safari
 - Browser Version: cannot see
 - Amazon Chime SDK GitHub Commit: V2.4.1

**Comment by chuckntaylor** [comment]
I would like to add that the speaker test in the `meetingReadinessChecker` app works without any issue on my iPhone. I believe in that app's situation, it works a bit differently in that we call `meetingReadinessChecker.checkAudioOutput()` to get the tone.

**Comment by ltrung** [comment]
@chuckntaylor Thanks for reporting. I have been able to reproduce the issue on my iphone 12.

**Comment by chuckntaylor** [comment]
@ltrung Thanks for looking into it! I just checked out the changes made in the merge and tried it out on my end. Works perfectly!
