### ISSUE TITLE
Chrome - VoiceFocus - The AudioContext was not allowed to start.

### ISSUE THREAD

**Issue by peili** [aws/amazon-chime-sdk-js#1062]
Steps to reproduce:

Connect to an AWS Chime Meeting (VoiceFocus) enabled, without any user gesture on the page.
Common use case, e.g. page refresh.

`
const voiceFocusDevice = await transformer.createTransformDevice(deviceId)
meetingSession.audioVideo.chooseAudioInputDevice(voiceFocusDevice)
`

This will show a warning, but also entire meeting audio fails.
`DefaultDeviceController.js?66c1:1156 The AudioContext was not allowed to start.`
See: https://developers.google.com/web/updates/2017/09/autoplay-policy-changes#webaudio

Selecting a deviceId without creating transform device, works without any issues. 
`meetingSession.audioVideo.chooseAudioInputDevice(mediaDevice.deviceId)`

It would be an improvement if either `createTransformDevice` or `chooseAudioInputDevice` throw an error in such a case (because entire media will fail).
Current workaround is to create your own user gesture listener to detect if `createTransformDevice` can be used.

**Comment by michhyun1** [comment]
Hi @peili, could you please clarify what you mean by user gesture? Also, could you please specify the SDK version that you are using? Thanks

**Comment by rnewman** [comment]
Hi @peili,

Thanks for filing an issue.

In general it's expected that audio input and output configuration occurs after a user gesture — this restriction also applies to `getUserMedia` calls and playing output audio, so I'm a little surprised that you report that `chooseAudioInputDevice` is working without a gesture.

Is there any reason you think that resuming the `AudioContext` is insufficient here?

**Comment by peili** [comment]
> In general it's expected that audio input and output configuration occurs after a user gesture
Agree in general, however on a page refresh I think it's reasonable to skip the previous user gesture requirement and get right back into the meeting. That has been working so far without using VoiceFocus.  So I thought I'd report the inconsistent behaviour when enabling VoiceFocus. Feel free to close this ticket, if you think that browser policy is communicated clearly. It wasn't obvious to me first.

**Comment by rnewman** [comment]
Browser policy here is not only not communicated clearly, but it also [continues to evolve over time](https://developers.google.com/web/updates/2018/11/web-audio-autoplay), so I definitely want to get to the bottom of what you're seeing and find out if there's something we can smooth over in the Chime SDK, either through documentation or code.

Autoplay restrictions are supposed to apply equally to Web Audio, and some kinds of navigation are supposed to preserve autoplay: if you can reload your page and, without clicking, make your page play audio, then in theory Web Audio (which includes Amazon Voice Focus) should work too.

Three questions for you, @peili:

1. Do you see the same behavior in Chrome, Firefox, and Safari Tech Preview (release Safari isn't able to use Amazon Voice Focus)?
2. Do you have a repro case (even if it's not narrowed down) that you can share with me?
3. Does everything start working if you poke at DefaultDeviceController's context right after creating the transform device?

You will need to circumvent some TypeScript barriers, but the last is essentially

```typescript
DefaultDeviceController.audioContext.resume();
```

**Comment by peili** [comment]
> 1. Do you see the same behavior in Chrome, Firefox, and Safari Tech Preview (release Safari isn't able to use Amazon Voice Focus)?

Yes -> Chrome, I only get the warning "The AudioContext was not allowed to start." Then Chime never recovers and media is missing.
No -> Firefox and Safari Tech Preview (Also Safari always required a user behaviour -> "Allow "website" to use your microphone", even I tried to set it permanent)

> 2. Do you have a repro case (even if it's not narrowed down) that you can share with me?

Enable VoiceFocus by default. 
And connect to a Chime Meeting on page load without any user interaction/gesture. 
(Having another user already in the room will make it easier to observe that no audio is flowing for the chrome device)

> 3. Does everything start working if you poke at DefaultDeviceController's context right after creating the transform device?

Great suggestion. Yes, that fixed the issue on Chrome.
`
await chooseAudioInputDevice(voiceFocusDevice);
DefaultDeviceController.audioContext.resume();
`

However I am worried this fix will not be permanent, also seeing that such Browser policies are still evolving.



![image](https://user-images.githubusercontent.com/1823148/108047016-97658800-7045-11eb-9186-d064f6c80827.png)

**Comment by rnewman** [comment]
Resuming a suspended audio context after selecting a device should be safe — indeed, it's safe enough that I will submit a PR for this.

It's possible that Chrome is misbehaving here, but it's an easy enough workaround for us.

**Comment by rnewman** [comment]
@peili if you're willing, I'd love for you to test the change in that PR and see if it fixes the issue you've seen.

**Comment by peili** [comment]
@rnewman Thank you. I can confirm this PR fixes the issue I have seen.
