### ISSUE TITLE
[ERROR] MyLogger - navigator.mediaDevices is not supported

### ISSUE THREAD

**Issue by gsudhanshu** [aws/amazon-chime-sdk-js#1063]
The demo is working fine on my localhost. But when I host it on server it gives the error  navigator.mediaDevices is not supported

Logs:

Angular is running in development mode. Call enableProdMode() to enable production mode.
ConsoleLogger.js:68 2021-02-12T06:40:40.572Z [INFO] MyLogger - DefaultDeviceController video dimension 960 x 540
**ConsoleLogger.js:59 2021-02-12T06:40:40.572Z [ERROR] MyLogger - navigator.mediaDevices is not supported
log @ ConsoleLogger.js:59**
error @ ConsoleLogger.js:37
DefaultDeviceController @ DefaultDeviceController.js:70
join @ app.component.ts:132
AppComponent_Template_button_click_4_listener @ app.component.html:304
executeListenerWithErrorHandling @ core.js:15193
wrapListenerIn_markDirtyAndPreventDefault @ core.js:15228
(anonymous) @ platform-browser.js:582
invokeTask @ zone-evergreen.js:402
onInvokeTask @ core.js:28500
invokeTask @ zone-evergreen.js:401
runTask @ zone-evergreen.js:174
invokeTask @ zone-evergreen.js:483
invokeTask @ zone-evergreen.js:1596
globalZoneAwareCallback @ zone-evergreen.js:1622
meetings.service.ts:18 createMeeting
meetings.service.ts:19 {sdkResponseMetadata: {…}, sdkHttpMetadata: {…}, meeting: {…}}
meetings.service.ts:32 createAttendee
meetings.service.ts:33 {sdkResponseMetadata: {…}, sdkHttpMetadata: {…}, attendee: {…}}
app.component.ts:142 Sudhanshu
app.component.ts:143 {sdkResponseMetadata: {…}, sdkHttpMetadata: {…}, meeting: {…}}
app.component.ts:144 {sdkResponseMetadata: {…}, sdkHttpMetadata: {…}, attendee: {…}}
app.component.ts:150 MeetingSessionConfiguration {meetingId: "fbab435f-277f-4f2f-8a36-362406b58b4e", externalMeetingId: "Meeting1", credentials: MeetingSessionCredentials, urls: MeetingSessionURLs, connectionTimeoutMs: 15000, …}
ConsoleLogger.js:68 2021-02-12T06:40:43.008Z [INFO] MyLogger - browser is edge-chromium 88 (88.0.705)
ConsoleLogger.js:68 2021-02-12T06:40:43.009Z [INFO] MyLogger - WebRTC unified plan for Chromium-based browsers is enabled
ConsoleLogger.js:68 2021-02-12T06:40:43.037Z [INFO] MyLogger - adding meeting observer

**Comment by p-foucht** [comment]
Are you accessing your site through HTTP? Browsers don't typically allow support those APIs on unsecure domains. You will need to use HTTPS, or manually modify your chrome build

[Related ticket with potential HTTP workaround](https://stackoverflow.com/questions/46299723/navigator-mediadevices-getusermedia-with-http-server)

**Comment by gsudhanshu** [comment]
Yes I was accessing through HTTP. able to resolve the issue by changing to HTTPS
