### ISSUE TITLE
Implement breakout rooms using amazon Chime

### ISSUE THREAD

**Issue by Dudelsb** [aws/amazon-chime-sdk-js#1064]
How do we implement breakout rooms functionality using  amazon chime javascript  sdk

**Comment by timanderson** [comment]
I just start a new meeting for each breakout room.

**Comment by Dudelsb** [comment]
Hi @timanderson ,
How would we link each room with the main meeting from which breakout rooms are created.
Like in Zoom  we can create a breakout room  from a meeting

**Comment by timanderson** [comment]
The way we do this, our application has a group defined by us, let's call it BigMeeting. If BigMeeting is meeting all together than that is one Chime meeting. Then a sub-group splits off into LittleMeeting. From a Chime perspective that is a new and different meeting. 

Tim

**Comment by Dudelsb** [comment]
Hi @timanderson ,
Thanks for replying ,
so the grouping functionality is not created using chme sdk ?
Also do we need to create Enterprise account to get chime account ID .

**Comment by timanderson** [comment]
Correct, the grouping is in our application. I don't know what you mean by an Enterprise account, but if it is an AWS thing then we don't have one!

Tim

**Comment by vidya-mohan** [comment]
@timanderson @Dudelsb - this may interest you - https://aws.amazon.com/blogs/business-productivity/breakout-room-amazon-chime-sdk-react-component-library/
