### ISSUE TITLE
bindVideoElement should not alter the DOM node

### ISSUE THREAD

**Issue by jrowny** [aws/amazon-chime-sdk-js#1069]
**Describe the bug**
bindVideoElement as well as startPreviewForVideoInput add a CSS style transform to mirror the video.
My application does not want the video mirrored and Chime shouldn't make the assumption for me without an option to override.

In the case of bindVideoElement, I can easily override the behavior, although I also need to add an observer on videoTileDidUpdate because I guess it's also applied again internally somewhere.

In the case of startPreviewForVideoInput, it returns immediately while it's still acquiring the video. This means I don't know WHEN to override the CSS style. Because you're setting the style directly on the HTML input and not with a class, I can't even use `!important` to override. 
So I think startPreviewForVideoInput should return a promise with an error if the video fails and also either accept a parameter to disable mirror or don't mirror for us at all.
IMO, It's easy enough for people to set their own CSS transform if they want mirrored video.

**Comment by p-foucht** [comment]
Hi @jrowny 

You should be able to use CSS to override the transform, as `!important` styles takes precedence over inline styles -- [MDN doc](https://developer.mozilla.org/en-US/docs/Web/CSS/Specificity#How_!important_can_be_used), [JSBin example](https://jsbin.com/vogegilale/edit?html,css,js,output)

Mirror local video is often the desired behavior, but I can understand your sentiment. I will leave this ticket open for others to input as well, but potentially adding a flag to opt out of the mirroring seems reasonable.

**Comment by jrowny** [comment]
ah, thanks, I forgot !important would override local style.

**Comment by devalevenkatesh** [comment]
We do not plan to have the mirroring feature soon. As suggested the CSS could be used to override the styling here. Please feel free to re-open in case you still face the issue.
