### ISSUE TITLE
Circular dependencies WARNINGS with Angular CLI

### ISSUE THREAD

**Issue by vidya-mohan** [aws/amazon-chime-sdk-js#107]
**Describe the bug**
We run into the following circular dependency warnings when running ng serve with the Angular CLI.:

    WARNING in Circular dependency detected:
    ../chime-sdk/chime-src/dist/src/maybe/Maybe.js -> ../chime-sdk/chime-src/dist/src/maybe/None.js -> ../chime-sdk/chime-src/dist/src/maybe/Maybe.js

    WARNING in Circular dependency detected:
    ../chime-sdk/chime-src/dist/src/maybe/None.js -> ../chime-sdk/chime-src/dist/src/maybe/Maybe.js -> ../chime-sdk/chime-src/dist/src/maybe/None.js

    WARNING in Circular dependency detected:
    ../chime-sdk/chime-src/dist/src/maybe/Some.js -> ../chime-sdk/chime-src/dist/src/maybe/Maybe.js -> ../chime-sdk/chime-src/dist/src/maybe/Some.js

**Platform**
Node: v10.15.3
Project: TypeScript, but specifically within Angular
Bundler: Angular CLI internally uses webpack IIRC

**Comment by vidya-mohan** [comment]
@simmkyu - I cannot reproduce this warning in the demo app, but I can see the circular dependency between maybe classes.
JS circular  dependencies depend on how module loaders handle them at runtime, so the   TS compiler does not throw any warning or error. We'll investigate tools or sample apps for detecting circular dependencies.

**Comment by aburnson** [comment]
Closing for now since there is not a clear way to repo this error.
