### ISSUE TITLE
Support WKWebView RTC Implementation (iOS 14.3 and up)

### ISSUE THREAD

**Issue by ian-luca** [aws/amazon-chime-sdk-js#1070]
### Feature Request
Since the iOS 14.3 Release we are able to use WebRTC in the WKWebView. I tested the functionality with Chime but unforunately it did't work out as I got a timout error everytime on `audioVideo.start();`

moreover iOS doesn't seem to provide any `deviceId`s or `label`s for its `MediaDeviceInfo` when calling `navigator.enumerateDevices` which doesn't play well with the `DeviceController.listAudioInputDevices`/`DeviceController.listVideoInputDevices` implementations in the Sdk.

I think it would be a great step to adapt to possible shortcommings of the iOS implementation and finally provide a viable solution, as getting WebRTC working with WKWebView is a hold up for many people.

**Comment by michhyun1** [comment]
@ian-luca thanks for the feedback. We are currently tracking this, and basic support WebRTC on WLKWebView should be part of our next release. I'll go ahead and close this, please reopen if the next release does not fit your use case. Thanks!

**Comment by michhyun1** [comment]
@ian-luca, we've just merged in changes that should enable support for WKWebViews. You should be able to create an iOS that uses a WKWebview and load/join the SDK meeting demo. It will be part of our next release, but feel free to work off of the Github master branch if you'd like to use the feature.

**Comment by michhyun1** [comment]
FYI - the Chime SDK for Javascript now support WKWebViews. https://aws.amazon.com/about-aws/whats-new/2021/05/wkwebview-now-supported-with-amazon-chime-sdk-for-javascript/
