### ISSUE TITLE
unbindVideoElement API does not remove MediaStream

### ISSUE THREAD

**Issue by p-foucht** [aws/amazon-chime-sdk-js#1076]
**Describe the bug**
The `unbindVideoElement` API does not remove the MediaStream from the video element. Since the `bindVideoElement` is responsible for attaching the stream, the `unbindVideoElement` call should remove it.

This is needed when moving video elements around the DOM. Currently, unbinding and rebinding the same `VideoTile` will create two videos playing the same stream.

**Workaround**
You can workaround this by manually remove the `srcObject` of the video element, or disposing of the video element altogether.

```
const videoEl = document.querySelector(...);
audioVideo.unbindVideoElement(3);
videoEl.srcObject = null;
```

**Fix**
To not break backwards compatability, allow passing some optional config when calling `unbindVideoElement` that will detach the `MediaStream`.

**Platform**
- All platforms

**Comment by michhyun1** [comment]
We want to invlude this change in the next major version update - it would be a breaking change to the current api definition.

**Comment by michhyun1** [comment]
unbindVideoElement now sets the srcObject for the video element to null.
