### ISSUE TITLE
deploy on Serverless Framework

### ISSUE THREAD

**Issue by Devo-React** [aws/amazon-chime-sdk-js#1086]
I did run the amazon-chime-react-native-demo using serverless code with SAM CLI it and  worked well.

I am implementing same meeting feature in my react native project. 
using  Amazon Chime Mobile SDK and  AWS service APIs.

For this I am writing serverside code using Serverless Framework.

I have installed:  npm install serverless -g

$ mkdir < my-serverless-dir > && cd < my-serverless-dir >

serverless create --template aws-nodejs --path < my-path > 

opened this project in vs code editor and **copied the code from template.yaml in to my serverless.yml and 
created src/handler.js and copied the code.**

after running the command **sls deploy**  got below output.

```
Serverless: Configuration warning:
Serverless:   at root: unrecognized property 'Transform'
Serverless:   at root: unrecognized property 'Description'
Serverless:   at root: unrecognized property 'parameters'
Serverless:   at root: unrecognized property 'Conditions'
Serverless:   at root: unrecognized property 'Globals'
Serverless:   at root: unrecognized property 'Resources'
Serverless:   at root: unrecognized property 'Outputs'
Serverless:  
Serverless: Learn more about configuration validation here: http://slss.io/configuration-validation
Serverless:  
Serverless: Packaging service...
Serverless: Uploading CloudFormation file to S3...
Serverless: Uploading artifacts...
Serverless: Validating template...
Serverless: Updating Stack...
Service Information
service: <my-service>
stage: dev
region: us-east-1
stack: <my-service-dev>
resources: 2
api keys:
  None
endpoints:
  None
functions:
  None
layers:
  None
Serverless: Removing old service artifacts from S3...


```

But I am expecting it to run perfectly and provide endpoint url  which I can use in my React-Native project to create meetings and communicate further.

**Comment by devalevenkatesh** [comment]
Just to better understand your issue, if it is relating to mobile SDKs or JS SDK.

1. Are you trying to use Amazon Chime mobile SDK (iOS or Android) or Amazon Chime JS SDK? 
2. Also could you please let us know if you have checked or followed [this guide](https://github.com/aws-samples/amazon-chime-react-native-demo#how-to-integrate-the-amazon-chime-sdk-into-your-existing-react-native-application) from the react native demo?

**Comment by Devo-React** [comment]
Hi @devalevenkatesh,
My application is related to  mobile SDK.
1. Yes I am using Amazon Chime mobile SDK (iOS or Android).
2.  Yes I have followed the  [all the steps](https://github.com/aws-samples/amazon-chime-react-native-demo#how-to-integrate-the-amazon-chime-sdk-into-your-existing-react-native-application) here.

**Comment by Devo-React** [comment]
Now I have to write Server side code so that when I create meetings in my mobile application and trigger this code [server side code](https://github.com/aws/amazon-chime-sdk-js/blob/master/demos/serverless/src/handlers.js) .

**Comment by devalevenkatesh** [comment]
Sorry but, this repository is for JS SDK and not the mobile SDKs. Could you please create a new issue in the react native demo repo and mention this issue link. You will get required support in that repo itself.

Closing this issue now.
