### ISSUE TITLE
chime metting. Counterparty Screen Delay issue

### ISSUE THREAD

**Issue by choyounggon1** [aws/amazon-chime-sdk-js#1087]
**Meeting and attendee IDs:**

**Timeline**

Amazon chime meeting Camera quality delay issue

The counterpart screen delay occurs only in the Mac book.
me -> Camera quality. Clear.  
choyounggon -> Camera quality delay occurred 

but All screens shown in the choyunggon notebook are OK. ( Samsung note-pc np750 )

![image](https://user-images.githubusercontent.com/79495511/108803354-cfd50b00-75dd-11eb-87bc-f29ffcb3b67d.png)
![Screen Shot 2021-02-23 at 13 47 53](https://user-images.githubusercontent.com/79495511/108803419-f7c46e80-75dd-11eb-8154-69a0568055b0.png)

**Platform**
 - OS: Mac OS catalina  / Big Sur
 - Browser: safari
 - Browser Version: 13.1.2
 - Amazon Chime SDK GitHub Commit: 
 - web chem : Logitech me- c922 / cho younggon - c930e 

If the person in charge is different, please connect me.

thank you

**Comment by devalevenkatesh** [comment]
Hello thank you for reporting this issue. Could you please answer below questions for clarifications?

1. Are you using Amazon Chime JS SDK in your app? It looks like you are facing issues with the Amazon Chime app and not the JS SDK. If that is the case request you to close this issue and check or file your issue at https://answers.chime.aws/.

**Comment by choyounggon1** [comment]
hello... 

Do not use the Chime JS SDK app..  

amazon chime 
Build #1.0.210991.0
Version: 4.37.8279

Is there a way to check the delay time, etc. for the other person's screen? ( help -> send diagnoatic log ??? )
https://answers.chime.aws/ Too much content...

thank you

**Comment by devalevenkatesh** [comment]
Sorry, but we do not support the Amazon Chime app and hence in-order to better support your issue request you to follow the below links:
https://docs.aws.amazon.com/chime/latest/ug/chime-getting-support.html
https://answers.chime.aws/articles/139/free-trial-support.html

Closing this issue now.
