### ISSUE TITLE
Clarify multi participant join on local demo

### ISSUE THREAD

**Issue by vidya-mohan** [aws/amazon-chime-sdk-js#109]
### What are you trying to do?

Join users on different machines to the local server.

### How can the documentation be improved to help your use case?

Add a "limitations of the local app" section to README to explain that meetings created by different local servers are different meetings even if they use the same meeting name.

### What documentation have you looked at so far?

README.md

**Comment by PeterAronZentai** [comment]
Could this approach be actually changed so `server.js` isnt using an inmemory array for storing meetings at all? Its a very bad pattern to educate - even though I guess the intention is just to give a simple solution.

Instead, meetings created via the demo user interface could have two tags added: a name - which should hold the meeting name as passed in by the user, plus an additional tag value that is unique to the aws demo application (like for instance: { "Key": "aws-chimes-demo-application", "Value": "Browser" }...
Then lookup could just go for a meetings list and pick based on tag value. 

It would add some complication to the code - but overall you would win cross machine trial, plus also the pattern is much more production-like than memory arrays.

I'd be happy to implement this change along with some others (which I am outlineing in a different ticket)

**Comment by ltrung** [comment]
Closing this for now. For multi-party, we suggest to to deploy to Lambda using our serverless demo. Adding a backend layer to local demo is nice but is not currently our priority at the moment. Feel free to re-open if you think otherwise.
