### ISSUE TITLE
Recording Audio Lag

### ISSUE THREAD

**Issue by ellismarte** [aws/amazon-chime-sdk-js#1091]
In the recording demo, there's a comment in the code that adds a second to fix an audio video syncing issue. 

I posted a question on that repo but I'm reposting here in case no one really checks that one. 

Does anyone know how I can resolve audio video syncing issues?

https://github.com/aws-samples/amazon-chime-sdk-recording-demo/issues/71

**Comment by michhyun1** [comment]
Hi @ellismarte, sorry for the delay on replying to your issue. There is a issue that you can reference here - https://github.com/aws-samples/amazon-chime-sdk-recording-demo/issues?q=is%3Aissue+-label%3ATriaged+is%3Aclosed

This is currently the solution we recommend, but please do let us know if that doesn't work for you. Thanks

**Comment by michhyun1** [comment]
closing this issue, but please re-open if you have any further questions.
