### ISSUE TITLE
amazon-chime-sdk-js with react-native-webrtc

### ISSUE THREAD

**Issue by e-nouri** [aws/amazon-chime-sdk-js#1092]
### What are you trying to do?
Can i ran the SDK inside my react native app with the global scope populated by the necessary WebRTC methods ?

The example given in the react native demo require writing a bridge, which I favor this solution over the bridge/mobile SKD if that works.
### How can the documentation be improved to help your use case?
Add a react native section with the react-native-webrtc module if that is possible.

**Comment by michhyun1** [comment]
@e-nouri thanks for using our SDK! We haven't tried this use case before but we want to encourage builders to try these type of uses cases themselves and any feedback you can give us would be greatly appreciated.

**Comment by michhyun1** [comment]
I'll close this issue for now, but please feel free to comment or reopen the issue if you have other questions.

**Comment by AliBaig-xD** [comment]
> ### What are you trying to do?
> Can i ran the SDK inside my react native app with the global scope populated by the necessary WebRTC methods ?
> 
> The example given in the react native demo require writing a bridge, which I favor this solution over the bridge/mobile SKD if that works.
> 
> ### How can the documentation be improved to help your use case?
> Add a react native section with the react-native-webrtc module if that is possible.

heyy i know it's been some years since you posted this but did it work out? using webRTC?
