### ISSUE TITLE
Need support for passing HTTP headers to MeetingSessionPOSTLogger.ts 

### ISSUE THREAD

**Issue by khastation** [aws/amazon-chime-sdk-js#1093]
The current implementation of the MeetingSessionPOSTLogger.ts doesn't support passing HTTP headers from the meetingV2.ts sample demo. This is an inconvenience for implementing backend APIs which required AWS signed headers (AWS_IAM).

**Comment by RidipDe** [comment]
Unfortunately, we do not support passing HTTP headers to MeetingSessionPOSTLogger as of now. 
Have put this as an enhancement idea to the team.

**Comment by stackyism** [comment]
@RidipDe Can I take this up ?
We can accept a header in constructor in parallel to `name`, `url` and pass it to *fetch*.
Will that work ?

**Comment by RidipDe** [comment]
Thanks for suggesting this.
https://github.com/aws/amazon-chime-sdk-js/pull/1208 adds the header to the MeetingSessionPOSTLogger.
Closing the ticket for now.
