### ISSUE TITLE
Error running serverless demo deployment script

### ISSUE THREAD

**Issue by adambyer** [aws/amazon-chime-sdk-js#1095]
I am getting the following error when attempting to run the serverless demo deployment script from https://github.com/aws/amazon-chime-sdk-js/tree/master/demos/serverless

I am on step `npm run deploy -- -r us-east-1 -b <my-bucket> -s <my-stack-name> -a meeting`

```
Command npm failed with exit code 1 signal null
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: aws-embedded-metrics@2.0.2
npm ERR! Found: jest@24.9.0
npm ERR! node_modules/jest
npm ERR!   dev jest@"^24.8.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer jest@">=26 <27" from ts-jest@26.5.2
npm ERR! node_modules/ts-jest
npm ERR!   dev ts-jest@"^26.1.1" from the root project
```

- macOS Catalina 10.15.7.
- npm 7.5.4
- node v14.15.5

Thanks.

**Comment by michhyun1** [comment]
Hey @adambyer, thanks for trying out our serverless demo deployment. I would suggest double checking that you've built the demo/browser demo and then trying again. Please let us know if you are running into more issues.

**Comment by adambyer** [comment]
Thanks @michhyun1. I'm still getting the same error. Are you referring to https://github.com/aws/amazon-chime-sdk-js/tree/master/demos/browser? I have run `npm run start` which results in `server running at http://127.0.0.1:8080/` but I still get the error when trying to deploy the serverless demo.

**Comment by michhyun1** [comment]
@adambyer Okay, I just want to double check that you've followed the instructions [here](https://github.com/aws/amazon-chime-sdk-js/blob/master/demos/serverless/README.md)

I just did a fresh clone and was able to deploy the demo fine, but please let me know if these steps still dont work for you.

**Comment by adambyer** [comment]
Hi @michhyun1. I tried starting from scratch but still not having any luck. Here are the steps I'm doing...

- git clone git@github.com:aws/amazon-chime-sdk-js.git
- cd amazon-chime-sdk-js/demos/browser
- npm run start
- that seems ok... I get `server running at http://127.0.0.1:8080/`
- cd demos/serverless
- npm install
- npm run deploy -- -r us-east-1 -b chime-demo.mydomain.com -s chime-demo -a meeting

That's when I get the error. Let me know if I'm missing anything.

Thanks again.

**Comment by michhyun1** [comment]
Interesting, I just cloned the repo and followed the exact steps as you and I was able to deploy still. I'm not sure why node_modules/jest was found in your logs, since we dont have a dependency on it

**Comment by adambyer** [comment]
It looks like serverless has a dependency for `aws-embedded-metrics` and that has a dependency for `jest`.

**Comment by michhyun1** [comment]
Hmm @adambyer I followed your steps again but Im not able to repro that issue. The only thing I can think of is maybe the npm vserion, since I am on 6.12.1, node version - v12.13.1

**Comment by adambyer** [comment]
Yes it looks like it's due to a change in npm v7 in the way it handles peer dependencies...

https://github.blog/2021-02-02-npm-7-is-now-generally-available/#peer-dependencies
