### ISSUE TITLE
How to select No audio output device

### ISSUE THREAD

**Issue by baj84** [aws/amazon-chime-sdk-js#1096]
I'm trying to make it so the participants are only sending their audio and not receiving any from other participants. 
I've tried specifying `await meetingManager.audioVideo.chooseAudioOutputDevice(null);` but this just selects the default output device.

Is there a way to 'turn off' the audio output altogether?

Thanks!

**Comment by michhyun1** [comment]
Hey there @baj84, thanks for your question. Just for some context, could you briefly explain what your use case is? Also, the chooseAudioOutput device will select the default audio device when passed the 'null' param. If you dont want to choose any audioOutput device, then perhaps you can omit the call to chooseAudioOutputDevice. Please let me know if I am misunderstanding your use case.

**Comment by baj84** [comment]
@michhyun1 Thanks for getting back to me. We want to participants mics to be on, but for them not to hear any other participants. For others with the same use case we managed to achieve this by unbinding the audio element, like so:
```
     const observer = {
        audioVideoDidStart: () => {
          console.log('Chime audio connected');
          console.log('unbinding audio element');

          meetingManager.audioVideo.unbindAudioElement();
        },
      };

      meetingManager.audioVideo.addObserver(observer);

      await meetingManager.start();`

**Comment by michhyun1** [comment]
@baj84 Would omitting the call to chooseAudioOutput device fit your use case?

**Comment by devalevenkatesh** [comment]
Hello, the code you posted should work since `unbindAudioElement` will actually remove the audio element bound to the speaker output. Closing this issue as it looks like resolved as of now. Please feel free to file a new one or re-open this if you are still facing the issue.
