### ISSUE TITLE
subscribe ack is null in iOS webview

### ISSUE THREAD

**Issue by ian-luca** [aws/amazon-chime-sdk-js#1098]
**Log:**
[amazon-chime-sdk-js-logs.txt](https://github.com/aws/amazon-chime-sdk-js/files/6069697/amazon-chime-sdk-js-logs.txt)

**Meeting and attendee IDs:**
AttendeeId: ee397571-6dd6-9201-1fcb-e97f84f8ba1c
(so I guess the MeetingId is: 8e79d703-e964-4d15-96f9-ab6dc385100d)

**Describe the bug**
When I try to join a meeting in iOS webview I get an `Timeout15000ms/UpdateSession/SubscribeAndReceiveSubscribeAckTask error: null is not an object` error. The webview is used inside a cordova application.

**Screenshots**
![Screenshot 2021-02-25 at 17 04 20](https://user-images.githubusercontent.com/31305145/109180878-a4901e80-778b-11eb-88be-2ffa2d8425af.png)

**Platform**
 - OS: iOS 14.4
 - Browser: ios-webview
 - Browser Version: 605 (605.1.15)
 - Amazon Chime SDK GitHub Commit: https://github.com/aws/amazon-chime-sdk-js/commit/2b275e263d8f322ee286b9ccb87e4cc8ccc22864

**Comment by michhyun1** [comment]
Hey @ian-luca, thanks for reaching out. I see that you are using ios-webview, we recently added support for ios chrome and ios firefox, it looks like we have to add the 'ios-webview' user agent to the list of supported browsers.

**Comment by michhyun1** [comment]
@ian-luca I've gone ahead and triaged this support story. I'l keep this ticket open in the meantime, maybe you can give us a brief explanation of what your use case is. Thanks!

**Comment by ian-luca** [comment]
@michhyun1 the sdk is used inside a Cordova app. Cordova uses the webview to display the application contents.

I have attached a log file with debug loggings. I wonder if `[Debug] 2021-03-02T15:12:40.931Z [DEBUG] ChimeMeetingLogs - received: {"timestampMs":"1614697961051","type":"SUBSCRIBE_ACK","error":{"status":500,"description":"failed to subscribe"}} (cordova.js, line 1413)
` is issued from the client itself because the server seems to deliver no response as far as I can tell from the network tab

**Comment by RidipDe** [comment]
Since ios-webview is not an officially supported browser, we are closing this issue for now. 
We will continue to track the issue internally and update here if we have any updates.

Feel free to re-open the issue if you wish to add more details to the issue in the future.

**Comment by vidya-mohan** [comment]
JS SDK supports 'ios-webview' now. https://aws.amazon.com/about-aws/whats-new/2021/05/wkwebview-now-supported-with-amazon-chime-sdk-for-javascript/
