### ISSUE TITLE
Firefox Only - Screen sharing view is not stopped when shared application is closed

### ISSUE THREAD

**Issue by vidya-mohan** [aws/amazon-chime-sdk-js#110]
**Describe the bug**
Issue was reproduced on browser sample application be following these steps.

User A and B are joined to a meeting session

User A starts screen share view
User B starts screen sharing and share an application
User A can see the screen share
Now User B closes the application
User A can still see the screen share

**Screenshots**
If applicable, add screenshots to help explain the problem.

**Platform**
 - OS: Windows 10
 - Browser: Firefox
 - Browser Version: 71.0 (64-bit)
 - Amazon Chime SDK GitHub Commit:

**Comment by vidya-mohan** [comment]
From @agowatch :
this looks like a Firefox bug.  seems that when quitting  the application no callbacks are invoked and so the viewer continues to  display the last captured frame (this does not affect Chrome)

**Comment by aburnson** [comment]
Does not look like there is anything that can be done here and is likely a browser bug.
