### ISSUE TITLE
ReceiveAudioInputTask error: undefined is not an object (evaluating 'track.label.indexOf')

### ISSUE THREAD

**Issue by TheAnkurPanchani** [aws/amazon-chime-sdk-js#1103]
**Important:**
INFO-level logs with timestamps.
[AmazonChimeLogs(iOS).txt](https://github.com/aws/amazon-chime-sdk-js/files/6057361/AmazonChimeLogs.iOS.txt)

**Meeting and attendee IDs:**
meeting ID:1b3c7be7-525a-4f3a-b3c6-77ffdd3e7516
attendee ID: 18db81d7-b13a-b410-d332-0a5cda75fdec

**Timeline**
* Just started and joined the meeting.

**Describe the bug**
[Info] 2021-02-28T17:19:31.067Z [INFO] SDK - serial group task AudioVideoStart/1b3c7be7-525a-4f3a-b3c6-77ffdd3e7516/18db81d7-b13a-b410-d332-0a5cda75fdec was canceled due to subtask AudioVideoStart/1b3c7be7-525a-4f3a-b3c6-77ffdd3e7516/18db81d7-b13a-b410-d332-0a5cda75fdec/ReceiveAudioInputTask error: undefined is not an object (evaluating 'track.label.indexOf')

**Screenshots**
No Screenshots.

**Platform**
 - OS: iOS 14.4
 - Browser: ios-webview
 - Browser Version: 605 (605.1.15)
 - Amazon Chime SDK GitHub Commit: [v2.5.0](https://github.com/aws/amazon-chime-sdk-js/releases/tag/v2.5.0)

**Comment by michhyun1** [comment]
@TheAnkurPanchani Hi there, could you specify what device you are using? We'll try to reproduce this on our end and give you an update. Thanks

**Comment by michhyun1** [comment]
@TheAnkurPanchani I noticed that you are using 'ios-webview' as your browser, which is currently not a platform that we are supporting right now, hence the issue you are seeing. I've taken note of this, and I've created a task on our end to add support for WKWebView browsers.

**Comment by TheAnkurPanchani** [comment]
@michhyun1 : I know it is not supported yet, but I have an application running on cordova which is using amazon-chime-sdk-js for video calling feature. So I tried running it using [cordova-plugin-iosrtc](https://github.com/cordova-rtc/cordova-plugin-iosrtc). I stuck at this issue hence raised it. Later I was able to pinpoint the code causing the issue, and after fixing it, everything seems to be working. So I've raised a PR #1104  with the fix. It's just a null check, I don't think it will have any other side effects.

**Comment by michhyun1** [comment]
@TheAnkurPanchani I saw your PR and I created my own PR to fix this. Our DefaultBrowserBehaviour doesnt specify that we support 'ios-webview' type browsers yet, but this issue should be fixed now. I've linked the pull request fix to this issue. Please pull from this repo, or you can wait until our next release. Thank you! Closing this issue, feel free to reopen if needed.

**Comment by michhyun1** [comment]
FYI - the Chime SDK for Javascript now support WKWebViews. https://aws.amazon.com/about-aws/whats-new/2021/05/wkwebview-now-supported-with-amazon-chime-sdk-for-javascript/
