### ISSUE TITLE
Default resolution for video preview is 4:3 only on firefox

### ISSUE THREAD

**Issue by vidya-mohan** [aws/amazon-chime-sdk-js#111]
**Describe the bug**
This seems to be caused by Firefox's limitation for getUserMedia API, for example, on my MacOS, getUserMedia request can only return a video of resolution 1280x720 or 640x480 on Firefox.

What resolution do you choose for the video preview ?

**Screenshots**
If applicable, add screenshots to help explain the problem.

**Platform**
 - OS: 
 - Browser: 
 - Browser Version: 
 - Amazon Chime SDK GitHub Commit:

**Comment by vidya-mohan** [comment]
@XHatan :
For HTMLVideoElement element, element.srcObject.getVideoTracks()[0].getSettings() could retrieve the settings of  first video track (most likely the only video track) bound with the element.  https://developer.mozilla.org/en-US/docs/Web/API/MediaTrackSettings. Maybe that could be helpful when applying CSS styles ?
This is not a bug but an enhancement

**Comment by aburnson** [comment]
It is up to the application to style the video tag according to the aspect ratio they want to achieve, such as with the `object-fit` property.

https://developer.mozilla.org/en-US/docs/Web/CSS/object-fit
