### ISSUE TITLE
Integrate  Amazon's Chime service with Expo react native app

### ISSUE THREAD

**Issue by rigalpatel001** [aws/amazon-chime-sdk-js#1113]
### Integrate  Amazon's Chime service with Expo react native app
I have built an app using Expo and was amplified. I want live event functionality when users host live events and other attendees participate in these events. 

### How can the documentation be improved to help your use case?

*I checked documentation but didn't find any information to integrate chime service with Expo.

### What documentation have you looked at so far?

*Documentation for how to Integrate Chime with Expo and example demo

**Comment by RidipDe** [comment]
We have the [amazon-chime-live-events]( https://github.com/aws-samples/amazon-chime-live-events/).
Perhaps is that what you are looking for?

**Comment by rigalpatel001** [comment]
@RidipDe 
Yes, I checked it but I want to Integrate with Expo. 
https://docs.expo.io/

I checked the demo available for react-native.
https://github.com/aws-samples/amazon-chime-react-native-demo 

I want demo Integration for Expo.


Thanks

**Comment by RidipDe** [comment]
@rigalpatel001 may we request you to please open this issue with the https://github.com/aws-samples/amazon-chime-react-native-demo team? They will be able to help you better in this regard.

**Comment by devalevenkatesh** [comment]
Currently we do not have a path forward here, hence closing this issue. Please feel free to create new issues if you face any problems.

**Comment by djbuch** [comment]
Hello,
Now that EAS is out, do you plan to add any expo config plugin to your bundle (https://docs.expo.dev/guides/config-plugins/) ?

Regards,
David

**Comment by ddennis** [comment]
Any news on how to use with Expo and eas-build?

**Comment by nonsoo24** [comment]
Any news on integration of amazon chime with expo?

**Comment by kapekost** [comment]
+ 1 the above :)

**Comment by BBopanna** [comment]
+1

**Comment by Rickynunez123** [comment]
+1

**Comment by ekpono** [comment]
+1

**Comment by ekpono** [comment]
+1

**Comment by sergey-king** [comment]
+1

**Comment by ekpono** [comment]
I have been able to implement this with Expo Module API :)

I can create a repo and link the steps if you want

**Comment by sergey-king** [comment]
> I have been able to implement this with Expo Module API :)
> 
> I can create a repo and link the steps if you want

That would be great! Thank you @ekpono

**Comment by fjsj** [comment]
Here's a Expo + Chime demo project that may help some of you in this thread: https://github.com/vintasoftware/expo-chime-demo/
