### ISSUE TITLE
no attendee found for track track_video_E9BF0A28-135F-4264-98B5-EF77BBD291AD

### ISSUE THREAD

**Issue by TheAnkurPanchani** [aws/amazon-chime-sdk-js#1116]
**Important:** Log files from both attendees:
[4f41daca-ec6a-e58d-60a7-7a05d6abf109.log](https://github.com/aws/amazon-chime-sdk-js/files/6090137/4f41daca-ec6a-e58d-60a7-7a05d6abf109.log)
[201579ae-4002-c22c-db25-9627ac805ee0.log](https://github.com/aws/amazon-chime-sdk-js/files/6090136/201579ae-4002-c22c-db25-9627ac805ee0.log)

**Meeting and attendee IDs:**
**meeting ID:** 964af340-16a6-46a0-95d8-17edea70f3a4
**attendee IDs:** 
4f41daca-ec6a-e58d-60a7-7a05d6abf109 (android webview)
201579ae-4002-c22c-db25-9627ac805ee0 (ios-webview)

**Timeline**
[Warning] 2021-03-05T06:31:35.031Z [WARN] SDK - no attendee found for track track_video_E9BF0A28-135F-4264-98B5-EF77BBD291AD
in file **201579ae-4002-c22c-db25-9627ac805ee0.log**

**Describe the bug**
I know `ios-webview` is not supported platform at the moment, but thought to report this issue anyway.
Stream id is indexed with key `track_video`. Track event is coming with id `track_video_E9BF0A28-135F-4264-98B5-EF77BBD291AD`. Hence the error, `SDK - no attendee found for track track_video_E9BF0A28-135F-4264-98B5-EF77BBD291AD`

**Repro steps:**
- Join meeting from ios-webview client and one other client
- When both client successfully joined, start video from the other client
- ios-webview should be able to see the video tile of the other client, but not due to mentioned issue.

**Screenshots**
No Screenshots.

**Platform**
 - OS: iOS 14.4
 - Browser: ios-webview
 - Browser Version: 605 (605.1.15)
 - Amazon Chime SDK GitHub Commit: [84d132ab7f4122e541a7bad57cfe17f1fc9430ca](https://github.com/aws/amazon-chime-sdk-js/commit/84d132ab7f4122e541a7bad57cfe17f1fc9430ca)
 - cordova-plugin-iosrtc: v6.0.18
 - webrtc-adapter: v7.7.0

**Comment by RidipDe** [comment]
Thanks @TheAnkurPanchani for opening the issue.

Can you please provide us with the repro steps?
Is it a 100% repro ?
How often do you encounter this on the ios-webview?

**Comment by TheAnkurPanchani** [comment]
@RidipDe : I've added repro steps in the description. And yes, it is a 100% repro. I encounter it every time.

**Comment by RidipDe** [comment]
Thank you for adding the steps. Will follow up on this.

**Comment by RidipDe** [comment]
Since ios-webview is not an officially supported browser, we are closing this issue for now. 
We will continue to track the issue internally and update here if we have any updates.

Feel free to re-open the issue if you wish to add more details to the issue in the future.

**Comment by vidya-mohan** [comment]
JS SDK supports 'ios-webview' now. https://aws.amazon.com/about-aws/whats-new/2021/05/wkwebview-now-supported-with-amazon-chime-sdk-for-javascript/
