### ISSUE TITLE
Pixel devices send wrong video height

### ISSUE THREAD

**Issue by cgandhi22** [aws/amazon-chime-sdk-js#1117]
### What are you trying to do?

I was trying to test SDK demo app with video resolution of 1080p on Pixel 3 device. Found in console logs that video tile height shows up as "1088" instead of "1080".

Log snippet:
`[INFO] SDK - requesting new video device with constraint {"video":{"deviceId":{"exact":"b35ad84683cb345dbaf26b016a8964b81fb08dd9a62527b0d935feffb68627fc"},"width":{"ideal":1920},"height":{"ideal":1088},"frameRate":{"ideal":15},"googCpuOveruseDetection":true,"googCpuOveruseEncodeUsage":true,"googCpuOveruseThreshold":85,"googCpuUnderuseThreshold":55}}`

### How can the documentation be improved to help your use case?

Documentation update will help create awareness on this known issue.
### What documentation have you looked at so far?

*For example: README.md, Amazon Chime SDK Developer Guide, etc.

**Comment by ltrung** [comment]
This is intentional changes for Pixel 3 devices to fix striped video rendering in #588
