### ISSUE TITLE
Have Remote Mute State in own event

### ISSUE THREAD

**Issue by vidya-mohan** [aws/amazon-chime-sdk-js#113]
**Important:** Please attach INFO-level logs with timestamps to the report from *before* the session started up until the point at which the unexpected behavior occured. For multi-participant calls, attach a log file for each participant if possible.

**Meeting and attendee IDs:**
List the meeting and attendee IDs that the attached logs apply to.

**Timeline**
Outline the main actions the user performed and when:

* <timestamp> <action>
* <timestamp> <action>

**Describe the bug**
This is more of a feature request.

Currently, we can only get the muted state of a remove participant by passing in a callback function into realtimeSubscribeToVolumeIndicator.

It'd be good if the remote muted/unmuted stated was handled separately, considering the audio streams are all being consolidated into 1 audio stream, there are use cases where the consuming app would not have a need to subscribe to individual volume events.

**Screenshots**
If applicable, add screenshots to help explain the problem.

**Platform**
 - OS: 
 - Browser: 
 - Browser Version: 
 - Amazon Chime SDK GitHub Commit:

**Comment by aburnson** [comment]
This can be achieved by ignoring events which do not contain a mute change.

**Comment by vishalsoftvan** [comment]
Muting and unmuting remote user is highly important and demanding feature for any video conferencing solution, every customer ask for such feature as top on priority list. 

Customer always back steps when they see such features are not existed, Do you have any ETA on this?
