### ISSUE TITLE
How to use audioDownstreamMetricMap Jitter?

### ISSUE THREAD

**Issue by camilosegura** [aws/amazon-chime-sdk-js#1135]
I'm trying to get audio, video and screen sharing jitter, and don't know how to get them using Amazon Chime SDK for Javascript.

Include an example of audioDownstreamMetricMap jitter, please.

I have looked at.
README.md, Amazon Chime SDK Developer Guide and source code.

**Comment by ltrung** [comment]
@camilosegura There are two ways to retrieve webRTC metrics in JS SDK:
- Subscribe to `metricsDidReceive` (as seen here https://github.com/aws/amazon-chime-sdk-js/blob/master/demos/browser/app/meetingV2/meetingV2.ts#L955). Unfortunately, we do not expose jitter metrics at this point.
- Call [AudioVideoFacace.getRTCPeerConnectionStats](https://github.com/aws/amazon-chime-sdk-js/blob/master/src/audiovideofacade/DefaultAudioVideoFacade.ts#L61) and parse out the stats yourself. An example code to retrieve audio downstream jitter value would be:
  ```
  stats = await app.audioVideo.getRTCPeerConnectionStats();
  stats.forEach(report => { 
    if (report.type='inbound-rtp' && report.kind === 'audio') { 
      console.log(report.jitter)
    }
  });
  ```

**Comment by anuranduttaroy** [comment]
Hey @camilosegura, feel free to re-open this issue if you still have questions.

**Comment by camilosegura** [comment]
Hi, do you know where I can find the meaning (doc...) of the data returned by 
`stats = await app.audioVideo.getRTCPeerConnectionStats();`
the **report** returns a different object every time, for example

![Screen Shot 2021-04-05 at 5 05 36 PM](https://user-images.githubusercontent.com/1218509/113633197-1f254700-9632-11eb-89b1-b2c0f20e4747.png)
![Screen Shot 2021-04-05 at 5 06 55 PM](https://user-images.githubusercontent.com/1218509/113633211-23e9fb00-9632-11eb-9878-01e8a7367c9b.png)
![Screen Shot 2021-04-05 at 5 07 19 PM](https://user-images.githubusercontent.com/1218509/113633226-29474580-9632-11eb-8398-0a5cc9d9b15f.png)
![Screen Shot 2021-04-05 at 5 07 38 PM](https://user-images.githubusercontent.com/1218509/113633232-2cdacc80-9632-11eb-968f-eefc1878b33f.png)

I'd like to know the meaning of those properties and why they are different.

**Comment by devalevenkatesh** [comment]
The `audioVideo.getRTCPeerConnectionStats()` relies on the WebRTC's RTCPeerConnection getStats API. For more information on the attributes of the report check the MDN Docs below:
https://developer.mozilla.org/en-US/docs/Web/API/RTCPeerConnection/getStats

**Comment by camilosegura** [comment]
Hi @devalevenkatesh in the stats report are you reporting all the [RTCStatsType](https://developer.mozilla.org/en-US/docs/Web/API/RTCStatsType)?  Or what are the ones that you are reporting?
