### ISSUE TITLE
Serverless demo stuck on "Deploying serverless application"

### ISSUE THREAD

**Issue by aagoath** [aws/amazon-chime-sdk-js#1140]
I was able to successfully run the demos/browser on both Mac and Linux, and then moved to demos/serverless. However the script gets stuck on step "Deploying serverless application". No change after 45 minutes...

It is also observed that while S3 bucket is created, I can't see cloudformation stack in the console. Could someone tell what's the next step. 

```
aws-cli/2.1.30 Python/3.8.8 Linux/3.10.0-1160.15.2.el7.x86_64 exe/x86_64.rhel.7 prompt/off

SAM CLI, version 1.21.1

up to date in 0.127s

Verifying application meetingV2
Using region us-west-1, bucket chime-serverless-demo-corp-bckt-1, stack chime-serverless-demo-corp-stk-1, endpoint https://service.chime.aws.amazon.com, enable-termination-protection false, disable-printing-logs false
Creating S3 bucket chime-serverless-demo-corp-bckt-1
added 12 packages from 58 contributors in 14.567s

1 package is looking for funding
  run `npm fund` for details


up to date in 27.166s

up to date in 16.91s


Successfully packaged artifacts and wrote output template to file build/packaged.yaml.
Execute the following command to deploy the packaged template
sam deploy --template-file /home/aag/amazon-chime-sdk-js/demos/serverless/build/packaged.yaml --stack-name <YOUR STACK NAME>


Deploying serverless application
```

**Comment by aagoath** [comment]
Executing `sam deploy` command throws up this, if this helps

```
sam deploy --template-file amazon-chime-sdk-js/demos/serverless/build/packaged.yaml --stack-name chime-serverless-demo-corp-stk-1 --region us-west-1

	Deploying with following values
	===============================
	Stack name                   : chime-serverless-demo-corp-stk-1
	Region                       : us-west-1
	Confirm changeset            : False
	Deployment s3 bucket         : None
	Capabilities                 : null
	Parameter overrides          : {}
	Signing Profiles             : {}

Initiating deployment
=====================
ChimeSdkIndexLambda may not have authorization defined.
ChimeSdkJoinLambda may not have authorization defined.
ChimeSdkEndLambda may not have authorization defined.
ChimeSdkBrowserLogsLambda may not have authorization defined.
ChimeSdkBrowserMeetingEventLogsLambda may not have authorization defined.
ChimeSdkBrowserCreateLogStreamLambda may not have authorization defined.
ChimeSdkBrowserCreateBrowserEventLogStreamLambda may not have authorization defined.
ChimeSdkBrowserFetchCredentialsLambda may not have authorization defined.
Error: Failed to create changeset for the stack: chime-serverless-demo-corp-stk-1, An error occurred (ValidationError) when calling the CreateChangeSet operation: Stack:arn:aws:cloudformation:us-west-1:xxxxx:stack/chime-serverless-demo-corp-stk-1/yyyyyyy is in ROLLBACK_FAILED state and can not be updated.
```

**Comment by simmkyu** [comment]
I pulled the latest repo and successfully deployed the demo in less than 10 mins. The deploy script logs that the lambda "may not have authorization defined."

```
Initiating deployment
=====================
ChimeSdkIndexLambda may not have authorization defined.
ChimeSdkJoinLambda may not have authorization defined.
ChimeSdkEndLambda may not have authorization defined.
ChimeSdkBrowserLogsLambda may not have authorization defined.
ChimeSdkBrowserMeetingEventLogsLambda may not have authorization defined.
ChimeSdkBrowserCreateLogStreamLambda may not have authorization defined.
ChimeSdkBrowserCreateBrowserEventLogStreamLambda may not have authorization defined.
ChimeSdkBrowserFetchCredentialsLambda may not have authorization defined.

Waiting for changeset to be created..

CloudFormation stack changeset
------------------------------------------------------------------------------------------------
Operation                        LogicalResourceId                ResourceType                   
------------------------------------------------------------------------------------------------
* Modify                         ChimeSQSQueueLambda              AWS::Lambda::Function          
* Modify                         ChimeSdkBrowserCreateBrowserEv   AWS::Lambda::Function        
...
```

⠀

> Error: Failed to create changeset for the stack: chime-serverless-demo-corp-stk-1, An error occurred (ValidationError) when calling the CreateChangeSet operation: Stack:arn:aws:cloudformation:us-west-1:xxxxx:stack/chime-serverless-demo-corp-stk-1/yyyyyyy is in ROLLBACK_FAILED state and can not be updated.

According to the AWS SAM issue (https://github.com/aws/aws-sam-cli/issues/2081), this error happens when the initial deployment failed with corrupted files. Could you try again after deleting the stack on the AWS CloudFormation console? Or you can deploy with new bucket and stack names.

**Comment by aagoath** [comment]
Retried again with new names, and this time as soon as the script reached `Deploying serverless application` line, I executed the below from command line 

`sam deploy --template-file amazon-chime-sdk-js/demos/serverless/build/packaged.yaml --stack-name chime-serverless-demo-corp-stk-2 --region us-west-1`


I got follwoing error 
```
	Deploying with following values
	===============================
	Stack name                   : chime-serverless-demo-corp-stk-2
	Region                       : us-west-1
	Confirm changeset            : False
	Deployment s3 bucket         : None
	Capabilities                 : null
	Parameter overrides          : {}
	Signing Profiles             : {}

Initiating deployment
=====================
ChimeSdkIndexLambda may not have authorization defined.
ChimeSdkJoinLambda may not have authorization defined.
ChimeSdkEndLambda may not have authorization defined.
ChimeSdkBrowserLogsLambda may not have authorization defined.
ChimeSdkBrowserMeetingEventLogsLambda may not have authorization defined.
ChimeSdkBrowserCreateLogStreamLambda may not have authorization defined.
ChimeSdkBrowserCreateBrowserEventLogStreamLambda may not have authorization defined.
ChimeSdkBrowserFetchCredentialsLambda may not have authorization defined.

Waiting for changeset to be created..
Error: Failed to create changeset for the stack: chime-serverless-demo-corp-stk-2, ex: Waiter ChangeSetCreateComplete failed: Waiter encountered a terminal failure state Status: FAILED. Reason: Requires capabilities : [CAPABILITY_IAM]
```

I am not sure what does [CAPABILITY_IAM] means? Please advise.

**Comment by simmkyu** [comment]
The `CAPABILITY_IAM` indicates that the template creates AWS IAM resources. For example, before deploying the template in the AWS CloudFormation console, you need to enable the `I acknowledge that AWS CloudFormation might create IAM resources` option.

![image](https://user-images.githubusercontent.com/36240708/111543858-dfed8f80-8730-11eb-8122-88358f132dcf.png)

⠀

When using the AWS SAM CLI tool, you need to pass the `--capabilities CAPABILITY_IAM` parameter. Could you try again after adding the `--capabilities CAPABILITY_IAM` option?

I recommend rerunning the Chime SDK deploy script. The Chime SDK deploy script adds the parameter here:
https://github.com/aws/amazon-chime-sdk-js/blob/0bc46928411f417b551196d03e0a1646133fcc56/demos/serverless/deploy.js#L178

**Comment by aagoath** [comment]
To clarify, I am indeed running the deploy script through the npm command line as mentioned in README
```
npm run deploy -- -r us-west-1 -b chime-serverless-demo-corp-bckt-4 -s chime-serverless-demo-corp-stk-4 -a meeting
```

This script is getting stuck at `Deploying serverless application`

Is there any specific cloudformation policy that needs to be enabled?

**Comment by simmkyu** [comment]
> Is there any specific cloudformation policy that needs to be enabled?

No, the `npm run deploy ...` command already adds the `--capabilities CAPABILITY_IAM` option when deploying the template. Please also ensure that your AWS account has permission to provision AWS resources though you'll see an explicit error message for permission issues.

When the script is getting stuck at `Deploying serverless application`, do you see any ongoing event in the **Events** tab of the AWS CloudFormation console? 

![image](https://user-images.githubusercontent.com/36240708/111552596-e800fb80-873f-11eb-81f3-facad990d62b.png)

**Comment by aagoath** [comment]
Interestingly, I don't see any trace of stack in the Cloudformation console. Nothing in "Active", "Failed", "Deleted" or other dropdown.

**Comment by aagoath** [comment]
ran the commandline `sam` with debug on, and do see the errors for missing policies, see below screenshot. The deploy script silently consumes it and hangs on the DELETE actions after rollback the stack. The diagnostics for deploy script can be improved. Further as a suggestion, it will be helpful if there is a single policy pre-defined with all necessary accesses included for serverless demo. Running, debugging and adding one policy at a time is inefficient process. It took multiple runs to  identify all the missing policies. 

Another question, I don't see CF stack in the console. What could be the reason?

![image](https://user-images.githubusercontent.com/42678749/111565343-649fd400-8758-11eb-9844-296fa3705460.png)

**Comment by simmkyu** [comment]
> The diagnostics for deploy script can be improved. Further as a suggestion, it will be helpful if there is a single policy pre-defined with all necessary accesses included for serverless demo.

Thanks for the suggestions. Based on logs in the screenshot, the account doesn't have permission to create AWS resources. We can also add the "debug" flag as an option.

⠀

> Another question, I don't see CF stack in the console. What could be the reason?

Could you ensure that you have selected `us-west-1` or the region you specified in the CLI tool? You can change the region at the top-right corner of the AWS console.

<img src="https://user-images.githubusercontent.com/36240708/111698559-366fd200-87f4-11eb-8a63-f447060474a4.png" width="300"/>

**Comment by aagoath** [comment]
> Could you ensure that you have selected us-west-1 

Thanks, I did notice that earlier and was able to track the CF stacks.

**Comment by devalevenkatesh** [comment]
Closing this issue as no more action is required. We have taken an action item to have a debug option functionality in our deployment capabilities.
