### ISSUE TITLE
Issue with call "audioMixController.bindAudioDevice"

### ISSUE THREAD

**Issue by bershek** [aws/amazon-chime-sdk-js#1147]
Hi, I have issue in testing audio.
When I do call on this methods like in doc "await audioMixController.bindAudioDevice({ deviceId: sinkId });" I have error in console. Could you help me with this issue.

https://monosnap.com/file/9VZBb3xfUQUwdQoxW6bKTR32Rvvsdk
https://monosnap.com/file/zjZKLt7KqpZhZ0uA2QfgBkF1jg1o0X

**Platform**
 - OS: macOs Big Sur 11.2.1
 - Browser: Google Chrome
 - Browser Version: 88.0.4324.192
 - Amazon Chime SDK GitHub Commit:

**Comment by simmkyu** [comment]
"Requested device not found" is an error from the Web API [getUserMedia](https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getUserMedia). Could you ensure the following?
- You have an audio output device.
- You pass the `MediaDeviceInfo.deviceId` as a `sinkId`.
  ```
  const audioOutputDevices = await app.audioVideo.listAudioOutputDevices();
  const deviceInfo = audioOutputDevices[0]; // Assume that you have at least one audio output device.
  await app.audioVideo.audioMixController.bindAudioDevice({ deviceId: deviceInfo.deviceId });
  ```
- You can also use `supportsSetSinkId` to check if your environment supports the `sinkId` API.
  https://github.com/aws/amazon-chime-sdk-js/blob/cf473e32770fd82bd1dda9a3e64081f16276cf8e/demos/browser/app/meetingV2/meetingV2.ts#L170-L178
