### ISSUE TITLE
403 forbidden request when trying to create channel for messaging session

### ISSUE THREAD

**Issue by gsudhanshu** [aws/amazon-chime-sdk-js#1148]
createChannel called with 
appInstanceArn : 
arn:aws:chime:us-east-1:424226399790:app-instance/25436422-3292-4aca-b494-f1f97cb946ee

I am simply getting appInstanceARN from server chime client and trying to create a channel. but I am getting following error:

ERROR Error: Uncaught (in promise): Forbidden: An invalid app instance user ARN was supplied for the input parameter.
extractError@http://localhost:4200/vendor.js:10240:27
extractError@http://localhost:4200/vendor.js:9479:8
callListeners@http://localhost:4200/vendor.js:35618:20
emit@http://localhost:4200/vendor.js:35590:10
emit@http://localhost:4200/vendor.js:70454:14
transition@http://localhost:4200/vendor.js:69788:10
runTo@http://localhost:4200/vendor.js:8979:12
runTo/<@http://localhost:4200/vendor.js:8991:10
transition/<@http://localhost:4200/vendor.js:69804:13
emit/<@http://localhost:4200/vendor.js:70456:12
callListeners@http://localhost:4200/vendor.js:35628:18
emit@http://localhost:4200/vendor.js:35590:10
emit@http://localhost:4200/vendor.js:70454:14
transition@http://localhost:4200/vendor.js:69788:10
runTo@http://localhost:4200/vendor.js:8979:12
runTo/<@http://localhost:4200/vendor.js:8991:10
transition/<@http://localhost:4200/vendor.js:69804:13
emit/<@http://localhost:4200/vendor.js:70456:12
callListeners@http://localhost:4200/vendor.js:35628:18
callNextListener@http://localhost:4200/vendor.js:35608:12
onEnd@http://localhost:4200/vendor.js:93213:13
MM+g/EventEmitter.prototype.emit@http://localhost:4200/vendor.js:23858:17
finishRequest@http://localhost:4200/vendor.js:22770:13
handleRequest/<@http://localhost:4200/vendor.js:22685:14
invokeTask@http://localhost:4200/polyfills.js:503:31
onInvokeTask@http://localhost:4200/vendor.js:64835:33
invokeTask@http://localhost:4200/polyfills.js:502:60
runTask@http://localhost:4200/polyfills.js:275:47
invokeTask@http://localhost:4200/polyfills.js:584:34
invokeTask@http://localhost:4200/polyfills.js:1697:14
globalZoneAwareCallback@http://localhost:4200/polyfills.js:1723:27
    Angular 2
    rejected tslib.es6.js:74
    Angular 13

**Comment by gsudhanshu** [comment]
@ltrung Can you help regarding this?

```
async createChannel(appInstanceArn : string, name : string, mode : string, privacy : string, userId : string) {
  console.log('createChannel called with appInstanceArn: ' + appInstanceArn);
  const params = {
    AppInstanceArn: appInstanceArn,
    Name: name,
    Mode: mode,
    Privacy: privacy
  };
  console.log("params"+params);

  const request = this.chime.createChannel(params);
  const appInstanceUserArnHeader = 'x-amz-chime-bearer';
  request.on('build', function() {
    request.httpRequest.headers[appInstanceUserArnHeader] = `${appInstanceArn}/user/${this.userId}`;
  });
  console.log("under log")
  const response = await request.promise();
  console.log('response create channel'+response);
  return response.ChannelArn;
}
```

**Comment by ltrung** [comment]
@gsudhanshu As the error point out, the userArn is invalid. Have you created [AppInstance user](https://docs.aws.amazon.com/chime/latest/APIReference/API_CreateAppInstanceUser.html) yet?
You would have to do that before calling createChannel.

**Comment by gsudhanshu** [comment]
@ltrung I tried creating app instance user but got following error:

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://identity-chime.us-east-1.amazonaws.com/app-instance-users. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing)

**Comment by gsudhanshu** [comment]
I used aws php sdk to create app instance user arn and passed it back to js

now when I try creating channel, with these values, I get following error:

ERROR Error: Uncaught (in promise): Unauthorized: An invalid app instance user ARN was supplied for the x-amz-chime-bearer HTTP header.

I am using appInstancerUserARN value received from server in x-amz-chime-bearer header:

```
request.httpRequest.headers[appInstanceUserArnHeader] = `${this.appInstanceUserARN}`;
```

**Comment by anuranduttaroy** [comment]
> @ltrung I tried creating app instance user but got following error:
> 
> Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://identity-chime.us-east-1.amazonaws.com/app-instance-users. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing)

Thanks for reporting the CORS issue @gsudhanshu. The team is actively looking into this issue and we will update here once we have an update.

**Comment by dpwspoon** [comment]
The CORs issue has been fixed for https://identity-chime.us-east-1.amazonaws.com/app-instance-users.  It now supports all domains

**Comment by ltrung** [comment]
@gsudhanshu Could you retry and let us know whether it works for you?

**Comment by gsudhanshu** [comment]
@ltrung I do not have the code now, as we took a different approach and used chime's realtime messaging feature

**Comment by ajuthomas** [comment]
I can confirm that this issue still persists.

**Comment by ajuthomas** [comment]
For anyone who is having the issue, here's how we resolved this:
The Chime app instance was created but that was not enough. We assumed that the user will be automatically added to the chat instance.
You would need to add the user to the app instance by using the identity id of the user. Something like:

`const chimeCreateAppInstanceUserParams = {
        AppInstanceArn: [YOUR APP INSTANCE ARN],
        AppInstanceUserId: [YOUR USER IDENTITY ID],
        Name: [YOUR USERNAME]
      };
      const chime = new Chime({
        region: [YOUR APP REGION],
        credentials: [YOUR USER CREDENTIALS (accessKeyId, authenticated, identityId, secretAccessKey, sessionToken)]
      });
      const request = chime.createAppInstanceUser(chimeCreateAppInstanceUserParams);
      const response = request.promise();`

**Comment by Mazuh** [comment]
Thanks, @ajuthomas, it also worked for me.
