### ISSUE TITLE
meetingV2 demo 'activeSpeakerLayout' field does nothing

### ISSUE THREAD

**Issue by richnew10** [aws/amazon-chime-sdk-js#1156]
It should be possible to disable active speaker layout, _or_ that field should be removed and appropriate cleanup done.

**Comment by p-foucht** [comment]
Related to "demo code that does nothing" -- probably all instances of `AsyncScheduler` should be removed from the demo. AFAICT, they aren't adding any value while making the code look more complex to builders than is necessary

Piggybacking because I don't think this deserves its own ticket :D

**Comment by xuesichao** [comment]
Removed the `activeSpeakerLayout` field in the above PR. We can add it back when we have the logic. Close the Issue.
