### ISSUE TITLE
Handle BitrateFrame received from signaling client

### ISSUE THREAD

**Issue by XHatan** [aws/amazon-chime-sdk-js#116]
Defined in [SignalingProtocol.proto L114](https://github.com/aws/amazon-chime-sdk-js/blob/master/protocol/SignalingProtocol.proto#L114), BitrateFrame contains the information of average bitrate of video streams available, we should use this information during re-subscription.

**Comment by aburnson** [comment]
This is being done as part of ongoing work to support simulcast.
