### ISSUE TITLE
Palo Alto App-ID - Chime categorized as evil internet-communication-and-telephony

### ISSUE THREAD

**Issue by peili** [aws/amazon-chime-sdk-js#1160]
We had multiple enterprise organization reporting the following:

"We allow Chime by Palo Alto App-ID and it looks like this connectivity is not being identified by app-id. I see a lot of blocks to the URL of signal.m1.ue1.app.chime.aws because it is categorized as evil internet-communication-and-telephony."

This accumulation of reports we're receiving, indicate that there is a general problem with the AWS Chime signaling urls/wss connections and Palo Alto App-ID or other firewalls.

**Comment by anuranduttaroy** [comment]
Hey @peili

Someone from the Amazon Chime team has reached out to Palo Alto Networks.

Please let me know if there is anything else we can help with. 

Thanks,
Anuran

**Comment by anuranduttaroy** [comment]
Hey @peili feel free to re-open this issue if you have any further questions.
