### ISSUE TITLE
browser demo - unable to change camera in some android devices

### ISSUE THREAD

**Issue by shriyajuneja** [aws/amazon-chime-sdk-js#1163]
**Bug**
2021-03-30T06:56:39.881Z : [ERROR] SDK - failed to get video device for constraints {"video":{"deviceId":{"exact":"a4520e0820c31686eea2b5401c144f8912555848122953064a541627f3c7d3a9"},"width":{"ideal":960},"height":{"ideal":540},"frameRate":{"ideal":15},"googCpuOveruseDetection":true,"googCpuOveruseEncodeUsage":true,"googCpuOveruseThreshold":85,"googCpuUnderuseThreshold":55}}: NotReadableError: Could not start video source

Unable to change camera in some devices like Samsung Galaxy M31s, Motorola one power, one plus 7 pro

**Screenshot**
<img width="1578" alt="Screenshot 2021-03-30 at 12 28 10 PM" src="https://user-images.githubusercontent.com/14612003/112949877-4f16ab00-9157-11eb-83a1-a5dcbb3f5481.png">

**Logs:** 

meetingV2.ts:1879 [DEMO] video input device is changed
meetingV2.ts:1879 [DEMO] Switching to: a4520e0820c31686eea2b5401c144f8912555848122953064a541627f3c7d3a9
ConsoleLogger.js:76 2021-03-30T06:56:39.592Z [INFO] SDK - API/DefaultAudioVideoFacade/434926dc-1954-4ad7-a134-b084af19bd33/dd471197-81c1-02ea-edd2-c06b208f0968/chooseVideoInputDevice "a4520e0820c31686eea2b5401c144f8912555848122953064a541627f3c7d3a9"
ConsoleLogger.js:76 2021-03-30T06:56:39.594Z [INFO] SDK - requesting new video device with constraint {"video":{"deviceId":{"exact":"a4520e0820c31686eea2b5401c144f8912555848122953064a541627f3c7d3a9"},"width":{"ideal":960},"height":{"ideal":540},"frameRate":{"ideal":15},"googCpuOveruseDetection":true,"googCpuOveruseEncodeUsage":true,"googCpuOveruseThreshold":85,"googCpuUnderuseThreshold":55}}

ConsoleLogger.js:67 2021-03-30T06:56:39.881Z [ERROR] SDK - failed to get video device for constraints {"video":{"deviceId":{"exact":"a4520e0820c31686eea2b5401c144f8912555848122953064a541627f3c7d3a9"},"width":{"ideal":960},"height":{"ideal":540},"frameRate":{"ideal":15},"googCpuOveruseDetection":true,"googCpuOveruseEncodeUsage":true,"googCpuOveruseThreshold":85,"googCpuUnderuseThreshold":55}}: NotReadableError: Could not start video source
log @ ConsoleLogger.js:67
error @ ConsoleLogger.js:37
error @ MultiLogger.js:25
eval @ DefaultDeviceController.js:917
rejected @ DefaultDeviceController.js:8
Promise.then (async)
step @ DefaultDeviceController.js:9
eval @ DefaultDeviceController.js:10
__awaiter @ DefaultDeviceController.js:6
chooseInputIntrinsicDevice @ DefaultDeviceController.js:830
eval @ DefaultDeviceController.js:242
eval @ DefaultDeviceController.js:10
__awaiter @ DefaultDeviceController.js:6
chooseVideoInputDevice @ DefaultDeviceController.js:225
chooseVideoInputDevice @ DefaultAudioVideoFacade.js:255
eval @ meetingV2.ts:1629
fulfilled @ meetingV2.ts:7
Promise.then (async)
step @ meetingV2.ts:9
eval @ meetingV2.ts:10
__awaiter @ meetingV2.ts:6
openVideoInputFromSelection @ meetingV2.ts:1606
eval @ meetingV2.ts:432
eval @ meetingV2.ts:10
__awaiter @ meetingV2.ts:6
eval @ meetingV2.ts:429

meetingV2.ts:259 Ignoring fatal Error: Error fetching device.
    at DefaultDeviceController.handleGetUserMediaError (DefaultDeviceController.js:804)
    at DefaultDeviceController.eval (DefaultDeviceController.js:939)
    at Generator.throw (<anonymous>)
    at rejected (DefaultDeviceController.js:8)

meetingV2.ts:1879 [DEMO] failed to chooseVideoInputDevice a4520e0820c31686eea2b5401c144f8912555848122953064a541627f3c7d3a9 Error: Error fetching device.
    at DefaultDeviceController.handleGetUserMediaError (DefaultDeviceController.js:804)
    at DefaultDeviceController.eval (DefaultDeviceController.js:939)
    at Generator.throw (<anonymous>)
    at rejected (DefaultDeviceController.js:8)

ConsoleLogger.js:76 2021-03-30T06:56:39.885Z [INFO] SDK - stopping video track

ConsoleLogger.js:76 2021-03-30T06:56:39.891Z [INFO] SDK - API/DefaultDeviceController/startVideoPreviewForVideoInput "video-preview"

ConsoleLogger.js:76 2021-03-30T06:56:39.892Z [INFO] SDK - API/DefaultAudioVideoFacade/434926dc-1954-4ad7-a134-b084af19bd33/dd471197-81c1-02ea-edd2-c06b208f0968/startVideoPreviewForVideoInput "video-preview"

meetingV2.ts:1879 [DEMO] Received an event: {"name":"videoInputFailed","attributes":{"attendeeId":"dd471197-81c1-02ea-edd2-c06b208f0968","browserMajorVersion":"89","browserName":"Chrome","browserVersion":"89.0.4389.105","deviceName":"Samsung SM-M317F","externalMeetingId":"Test-flip","externalUserId":"4c431f2c#Abcd","meetingHistory":[{"name":"audioInputSelected","timestampMs":1617087358018},{"name":"videoInputSelected","timestampMs":1617087360733},{"name":"videoInputFailed","timestampMs":1617087399881}],"meetingId":"434926dc-1954-4ad7-a134-b084af19bd33","osName":"Android","osVersion":"11","sdkVersion":"2.6.0","sdkName":"amazon-chime-sdk-js","timestampMs":1617087399881,"videoInputErrorMessage":"NotReadableError: Could not start video source"}}

**Meeting and attendee IDs:**
attendeeId: "dd471197-81c1-02ea-edd2-c06b208f0968"
meetingId: "434926dc-1954-4ad7-a134-b084af19bd33"

**Timeline**
* 2021-03-30T06:55:57.184Z : Meeting Started
* 2021-03-30T06:56:39.592Z : Changed video input device

**Platform**
- OS: Android version 11
 - Browser: Chrome
 - Browser Version: 89.0.4389.105
 - Amazon chime sdk version: 2.6.0

**Comment by devalevenkatesh** [comment]
Thanks for reporting this issue. Could you please try the below workaround and see if that unblocks you?
In the demo where, [openVideoInputFromSelection](https://github.com/aws/amazon-chime-sdk-js/blob/master/demos/browser/app/meetingV2/meetingV2.ts#L504) is called rather call below given function and check if that works?
```js
private async handleVideoPreviewSelection(device: VideoInputDevice): Promise<void> {
    this.audioVideo.stopVideoPreviewForVideoInput(
      document.getElementById('video-preview') as HTMLVideoElement
    );
    await this.audioVideo.chooseVideoInputDevice(device);
    this.audioVideo.startVideoPreviewForVideoInput(
      document.getElementById('video-preview') as HTMLVideoElement
    );
}
```

**Comment by shriyajuneja** [comment]
Provided workaround does not update VideoTileState ( audioVideo.getLocalVideoTile()?.state() ). Its not binding new videoStream with videoTile

**Comment by devalevenkatesh** [comment]
Hi @shriyajuneja ,

We have an duplicate issue #1316  with possible problem discussed. We are closing this one to track the progress there.

**Comment by devalevenkatesh** [comment]
@shriyajuneja could you please check update on #1316 which mentions a PR with the fix? We would appreciate if you try it out and let us know if it works out of the box without any workaround. Just commenting here for you to get an update. It would be great if you update in the #1316 issue once tested.

**Comment by shriyajuneja** [comment]
Hi @devalevenkatesh, it works after updating to 2.15.0. However I'm still facing issue in a particular scenario in updated version, added that in [#1316](https://github.com/aws/amazon-chime-sdk-js/issues/1316) issue. Thanks.
