### ISSUE TITLE
Stop Content share Not working.

### ISSUE THREAD

**Issue by muralivenkatesh** [aws/amazon-chime-sdk-js#1164]
when we stop content share the attendee's videos, not showing.

Example:
A and B having a video call.
A share the screen and stop the screen share to B
B local video not able to see A system.

when screen stop share code
   meetingSession.audioVideo.stopContentShare();

This my observer code below.

  const observer = { 
                videoTileDidUpdate: (tileState) => {  
                    const videoElement = tileState.localTile ? 'desk-local-video' : 'desk-remote-video';  
                    console.log(videoElement)
                    if(videoElement != null && videoElement != undefined){
                        var elementcheck = document.getElementById(videoElement);
                        if(elementcheck != undefined){
                          meetingSession.audioVideo.bindVideoElement(tileState.tileId, document.getElementById(videoElement) ); 
                        } 
                    }   
                },
                videoTileWasRemoved: tileId => {  
                },
                contentShareDidStart: () => {
                  console.log('Screen share started');   
                },
                contentShareDidStop: () => { 
                  console.log('Screen share stopped');
                }   
            };

I don't have any idea. I am doing correctly or not
Please help me resolve this issue.

**Comment by simmkyu** [comment]
You use a single video element (`desk-remote-video`) for displaying both remote and content tiles. Instead, I recommend binding a content tile to a separate video element. For example, the following code binds the content tile to a new video element (`content-share-video`).

```
const observer = {
  videoTileDidUpdate: (tileState) => {
    var elementId;
    if (tileState.isContent) {
      elementId = 'content-share-video';
    } else if (tileState.localTile) {
      elementId = 'desk-local-video';
    } else {
      elementId = 'desk-remote-video';
    }

    var videoElement = document.getElementById(elementId);
    meetingSession.audioVideo.bindVideoElement(tileState.tileId, videoElement);
  }
};
```

Note that this sample code works when one attendee enables content sharing in the 1-to-1 meeting. Please review the [Usage examples](https://github.com/aws/amazon-chime-sdk-js#usage) for supporting multiple remote and content-share videos.

**Comment by muralivenkatesh** [comment]
the above code used. but still the same issue.

When content share time it is showing the share screen both video elements. but local elements working correctly.

Please help me.
My Project is in the final stage.
it is pending this issue only.  

Attached screenshot
 
![FireShot Capture 013 - Hastra - localhost](https://user-images.githubusercontent.com/11347690/113099568-c6ac0f00-9217-11eb-8dfc-a5bcbfe2831d.jpg)

**Comment by muralivenkatesh** [comment]
Hi @simmkyu 

The above issue fixed.

one to one video calls it is working well. 
but screen sharing start and stop not working perfectly for only one to one video.

we can resolve using multiple video title for only remote videos,

is the correct way of doing the below code. but working perfectly.

videoTileDidUpdate: tileState => {  
                        var elementId; 
                        if (tileState.localTile) {
                          elementId = 'desk-local-video';
                        } else {   

                          var videoIndex = videoTiles.indexOf(tileState.tileId);
                          console.log(videoIndex)
                          if(videoIndex < 0){
                              var getVideoTiles = videoTiles; 
                              getVideoTiles.push(tileState.tileId);
                              setVideoTiles(getVideoTiles);  
                              console.log(videoTiles)
                              var lengthvalue = videoTiles.length-1;
                              console.log(lengthvalue)
                              elementId = 'desk-remote-video-'+lengthvalue;

                              console.log(elementId)
                              var videoElement = document.getElementById(elementId);
                              console.log(videoElement)
                              showVideoTile(videoElement)
                          }
                         
                        } 
                    
                      if (elementId) { 
                        var videoElement = document.getElementById(elementId);
                        meetingSession.audioVideo.bindVideoElement(tileState.tileId, videoElement);
                      } 
                },
           videoTileWasRemoved: tileId => { 
                    var videoIndex = videoTiles.indexOf(tileId);

                    var getVideoTiles = videoTiles;
                    getVideoTiles.splice(videoIndex, 1);
                    setVideoTiles(getVideoTiles); 

                    hideVideoTile(videoIndex)
                },


  const showVideoTile = (tileElement) =>  {  
          tileElement.classList.remove('desk-remote-video-hide');
          tileElement.classList.add('desk-remote-video-active', 'desk-remote-video');  
      }

      const hideVideoTile = (tileIndex) => {
          const tileElement = document.getElementById(`desk-remote-video-${tileIndex}`);
          tileElement.classList.remove('desk-remote-video-active' ,'desk-remote-video'); 
          tileElement.classList.add(`desk-remote-video-hide`); 
      }

**Comment by simmkyu** [comment]
Yes, the code looks okay to me.
- Handling remote video only in the `videoTileWasRemoved` method is okay unless you call `meetingSession.audioVideo.removeLocalVideoTile` API. If you stop your local video using `meetingSession.audioVideo.stopLocalVideoTile` API, `videoTileWasRemoved` will not be called. Your code should work as expected.
- Since you do not handle a content-share separately, the content-share video will appear in one of your remote video tiles.
- If you want to show the content-share video in another HTML element, you can use `tileState.isContent` to identify the tile type and bind it to a corresponding HTML element. See the [use case 22](https://github.com/aws/amazon-chime-sdk-js#screen-and-content-share) for an example.

**Comment by devalevenkatesh** [comment]
Closing this issue as we no further action is needed. Please create new issues / re-open this if need any further help.
