### ISSUE TITLE
VideoStreamIndex should keep stream allocation information

### ISSUE THREAD

**Issue by XHatan** [aws/amazon-chime-sdk-js#117]
[DefaultVideoStreamIndex](https://github.com/aws/amazon-chime-sdk-js/blob/master/protocol/SignalingProtocol.proto#L114) "lazily" computes media stream mappings. It is also responsible for computing the streams that client wants to subscribe. 

It's better that the subscription calculation algorithm is componentized to allow dynamic configuration of subscription algorithm. 

VideoStreamIndex should also keep stream allocation information for consistency with server.

**Comment by aburnson** [comment]
Closing for now since this may be addressed in related ongoing work. If there is a clear independent case for this, we can re-open.
