### ISSUE TITLE
Switch a camera to front/back.

### ISSUE THREAD

**Issue by konstantin-tarasov-clearscale** [aws/amazon-chime-sdk-js#1174]
Trying to implement the camera switching to front/back with a toggle button.

Currently, SDK provides the list of devices. 
We can determine the camera type by prefixes front/back (rear possibly?).
Pressing the button, we can determine current camera type (e.g. front).
Then try to find opposite camera (any camera with back prefix).
And select a new device.

Do you have a best practice/recommendations regarding the camera switching?

Shouldn't we have methods like 
- `canSwitchVideoInputDevice()`
- `switchVideoInputDevice()`

**Comment by devalevenkatesh** [comment]
Hello, currently we do not have these methods as there can be multiple video inputs to choose from. For example, users may have extra camera devices plugged in with the default webcam in laptops or the front and back camera in the mobile phones. So, we provide the `chooseVideoInputDevice` API to choose a video device. 

You can call the `chooseVideoInputDevice` API with the device you want to select. Please let us know if there is any error you are running into there. Regarding the camera switching you could pre-populate the devices using `listVideoInputDevices()` and then upon selection pass in the device's `deviceId` to select that device. That is the genral recommendation.

Request you to check our browser meeting [demo](https://github.com/aws/amazon-chime-sdk-js/tree/master/demos/browser) and our [README](https://github.com/aws/amazon-chime-sdk-js#video) which goes through these cases as well.

**Comment by devalevenkatesh** [comment]
Please feel free to re-open or create new issue. Closing this as no further action is pending.

**Comment by anandsingh1606** [comment]
Hi @devalevenkatesh, We have the same requirement. Is this still not supported?
