### ISSUE TITLE
Call to getRTCPeerConnectionStats() is not returning any stats for screen sharing

### ISSUE THREAD

**Issue by bpelland** [aws/amazon-chime-sdk-js#1178]
**Meeting and attendee IDs:**
Meeting ID: 541cb292-3397-416e-ab46-1560ea766935
Attendee ID: db01df6c-a3ab-cf6b-cc2f-9e27cb604a6a

**Timeline**
The user starts sharing his or her screen.
The user clicks on a settings button to display a settings panel, which calls this method to display audio/video/share stats:
```
async getConnectionStats() {
        const rtcStatsReport = await this.audioVideo.getRTCPeerConnectionStats();
        if (!rtcStatsReport) return;

        return this.rtcStatsReportParser.perform(rtcStatsReport);
}
```

**Describe the bug**
The stats for screen sharing are not returned from `getRTCPeerConnectionStats()`. It returns a `"-"` for all screen sharing 'send' stats when I would expect to see actual statistics.

**Screenshots**
![image](https://user-images.githubusercontent.com/6759414/113621293-783cad00-9629-11eb-8ab6-26a5643fbf1b.png)
![image](https://user-images.githubusercontent.com/6759414/113621351-88548c80-9629-11eb-9b61-f4d2b729b673.png)

**Platform**
 - OS: macOS
 - Browser: Chrome
 - Browser Version: 89.0.4389.90

**Comment by ltrung** [comment]
@bpelland By `screen sharing 'send' stats`, do you mean the outbound-rtp stats for content share? If so, it is not available right now. Content Share joins as a different attendee (content attendee) and thus, has a different peer connection.
Could you try to use `this.audioVideo.contentShareController.contentAudioVideo.getRTCPeerConnectionStats()`?

**Comment by camilosegura** [comment]
hi @ltrung that method only returns an object with this shape `{ size: 53 }` do you know what is the meaning of that info?

**Comment by bpelland** [comment]
@ltrung Yes, I do mean the outbound-rtp stats for content share. I tried your suggestion of replacing `const rtcStatsReport = await this.audioVideo.getRTCPeerConnectionStats();` with `const rtcStatsReport = await this.audioVideo.contentShareController.contentAudioVideo.getRTCPeerConnectionStats();` but it still gives me just audio and video stats, and no share stats.

**Comment by ltrung** [comment]
@bpelland, content share is actual just video. In other words, the video stats from the content attendee is for the content share video stream.

**Comment by ltrung** [comment]
@camilosegura getRTCPeerConnectionStats() just returns the statistic data collected by webRTC. You can find more info here: https://developer.mozilla.org/en-US/docs/Web/API/RTCPeerConnection/getStats

**Comment by ltrung** [comment]
Closing this issue for now. Please re-open or create a new one if you have any more question :)
