### ISSUE TITLE
Having problem setting chooseAudioInputDevice while initiating a meeting

### ISSUE THREAD

**Issue by iamibrahimkholil** [aws/amazon-chime-sdk-js#1194]
### To summarize
I am trying to set audio input device via chooseAudioInputDevice method. But i am constantly getting logs on the console which is saying stopping audio track and requesting new audio device with constraint.

### What are you trying to do?
I am trying to initiate a call and for that, I am setting up an audio input device but failing to do that.

**Screenshots**
![Capture](https://user-images.githubusercontent.com/79884206/114497405-e09c1780-9c43-11eb-8d5b-ac64c58ebd21.PNG)
![Capture](https://user-images.githubusercontent.com/79884206/114497905-e6462d00-9c44-11eb-8107-e631e86b0805.PNG)
![Capture1](https://user-images.githubusercontent.com/79884206/114497909-e8a88700-9c44-11eb-85c1-73695456cfc1.PNG)
![Capture3](https://user-images.githubusercontent.com/79884206/114498111-518fff00-9c45-11eb-9544-04ae0098aaac.PNG)

**Platform**
 - OS: Windows
 - Browser: Google Chrome
 - Browser Version: Version 89.0.4389.114

**Comment by ltrung** [comment]
@iamibrahimkholil Can you let us know what chime js sdk version you are using? It seems to be similar to these issue $1136 and #1143. 
Can you let us know what the value of the deviceId you passed in is?

**Comment by iamibrahimkholil** [comment]
We solved the problem. As it turned out we were calling  `meetingSession.audioVideo.listAudioInputDevices` wrong way. We fixed it now it's working fine. I will close the issue.
