### ISSUE TITLE
Very low upstream bandwidth on Android resulting in bad video quality

### ISSUE THREAD

**Issue by ElielCohen** [aws/amazon-chime-sdk-js#1197]
**Describe the bug**
On Android, when using the web sample application, the upstream bandwidth remains very low, resulting in many various artifacts (checkerboard style). This does not reproduce on iOS or desktop environment.

**Screenshots**

<img width="1792" alt="Screen Shot 2021-04-14 at 12 30 04" src="https://user-images.githubusercontent.com/10059928/114693466-478ffe00-9d22-11eb-8109-3c37a239ec86.png">

You can see in that screenshot that the incoming bandwidth is extremely low, resulting in artefacts in the video stream sent from the android phone.

**Platform**
 - OS: Android checked and reproduced on Pixel 3, Galaxy A11, ...
 - Browser: Chrome, or using a WebView (does even seem to reproduce on native SDK for android)
 - Browser Version: 89.0
 - Amazon Chime SDK GitHub Commit: f1eea815f5f0b0804cd4619854ca1563062dbca0

Thanks,

Eliel Cohen

**Comment by XHatan** [comment]
Hey @ElielCohen 
thanks for reporting this, could you provide meeting id and console logs of both attendees, so we could take a look at what happened in the meeting ?

**Comment by ElielCohen** [comment]
Hy Xhatan, 

I have identified the root cause of this, it's due to these contraints :

googCpuOveruseDetection
googCpuOveruseEncodeUsage

I've set them both to false in the DefaultDeviceController.ts, and now all works well.

Looks like that in android, on some device, the cpu is not powerful enough so that the webRTC engine feel confident enough to use the normal resolution/quality.

This was as well reported in stackOverflow here :
https://stackoverflow.com/questions/32046025/how-can-i-maintain-hd-resolution-with-webrtc-on-android-mobile

By the way I've tried initially to find the attendees id but could not find this information easily, how should I proceed to find this info ?

Thanks,

Eliel Cohen
WebRTC Technological Lead
TytoCare

**Comment by ElielCohen** [comment]
Ok correction, this is not the sole root cause, the cause of this are a mix of :

googCpuOveruseDetection
googCpuOveruseEncodeUsage

and 

Settings of the ABR, namingly choice in resolution / fps and bandwidth, that trigger this bad behavior on some android devices.

If you can test on a Pixel3 for example, you will see that using the default settings, or any of the proposed settings from the sample app, you will get a bad quality of the video stream, only configuring manually theses settings allowed me to overcome the issue on the Pixel3, but did not solve it on another device (a PocoPhone F1).

I believe that the fact that I need to play try/miss with the settings to obtain a normal quality is a problem.

Thanks,

Eliel

**Comment by ElielCohen** [comment]
Ok after more testing, it happens that what solves it , is setting manually the bandwidth/fps/resolution settings, and that the cpu overuse detection is not helping it so much.

Here is the configuration I am now using and that seems to work with any android device so far.

private static defaultVideoWidth = 1280;
private static defaultVideoHeight = 720;
private static defaultVideoFrameRate = 30;
private static defaultVideoMaxBandwidthKbps = 4800;

Don't know why I need to put such a high max bandwidth value.

For info, I am then into the call not using of course that much of bandwidth, but if don't put such a high value, the bandwidth on android stays in the very low range (around 300 kbps) and therefore the quality suffers from it.

Changing the other settings, meaning framerate or resolution does not change much of it.

Thanks,

Eliel

**Comment by vidya-mohan** [comment]
thanks for sharing your observations @ElielCohen . We have a technical guide on this subject: https://aws.github.io/amazon-chime-sdk-js/modules/qualitybandwidth_connectivity.html
