### ISSUE TITLE
Infinite Loop (chooseAudioInputDevice) - Revisited

### ISSUE THREAD

**Issue by chuckntaylor** [aws/amazon-chime-sdk-js#1201]
About a month ago, I reported a possible bug in issue #1136 

In that issue, I had my app hang when I went to start a meeting and set `audioVideo.chooseAudioInputDevice(DEVICE_ID_STRING)`. The problem went away if I downgraded to v2.5.0

The issue seemed to be resolved when using the demo chat app. Over the past month, I had kept my project at v2.5.0 while working on other aspects of the application. Yesterday, I upgraded to the latest release v2.7.0

Again, I experienced the same hangup, where setting `audioVideo.chooseAudioInputDevice(DEVICE_ID_STRING)` would cause an inifinite loop to trigger. However, this time, I was able to resolve my issue, and I believe I can better explain it now.

I am using Vue and Vuex for my project. In my device setup screen, I create a DeviceController, get a list of devices, use deviceChangeObserver, etc. At this point, all the calls to choose a device are on the deviceController and not AudioVideoFacade - `deviceController.chooseAudioInputDevice(DEVICE_ID_STRING)` The device setup screen has no issues.

Using Vuex in my project, I stored the deviceController, a list of devices, and the currently selected devices, etc.

Then, when navigating to the chat screen, when I would create a `new DefaultMeetingSession(meetingSessionConfiguration, logger, deviceController)`, Instead of reusing the deviceController that I created for the setup screen, I was creating a **new** `DefaultDeviceController` to pass to the `DefaultMeetingSession` at this time. Please note I was also taking the step to replace the deviceController reference in my Vuex store with this new one being made for the defaultMeetingSession.

While all of this worked fine in v2.5.0, on later versions it causes an infinite loop when I go to assign the selected audioInputDevice I have maintained in the vuex store and choose it with the AudioVideoFacade. The loop gets stuck on `ChimeMeeting - checking whether existing audio device can be reused` `ChimeMeeting - requesting new audio device with constraint`

## INFO Logs:
```
2021-04-15T13:46:43.994Z [INFO] ChimeMeeting - browser is chrome 89 (89.0.4389)
ConsoleLogger.js:76 2021-04-15T13:46:43.994Z [INFO] ChimeMeeting - WebRTC unified plan for Chromium-based browsers is enabled
ConsoleLogger.js:76 2021-04-15T13:46:44.024Z [INFO] ChimeMeeting - adding meeting observer
ConsoleLogger.js:76 2021-04-15T13:46:44.026Z [INFO] ChimeMeeting - Starting devicechange listener.
ConsoleLogger.js:76 2021-04-15T13:46:44.027Z [INFO] ChimeMeeting - API/DefaultAudioVideoFacade/d1a4f576-078e-40c3-848b-abd2e368104d/add3c9e4-e187-e4e4-c275-0a113f0e5477/chooseAudioOutputDevice "default"
ConsoleLogger.js:76 2021-04-15T13:46:44.028Z [INFO] ChimeMeeting - API/DefaultAudioVideoFacade/d1a4f576-078e-40c3-848b-abd2e368104d/add3c9e4-e187-e4e4-c275-0a113f0e5477/hasStartedLocalVideoTile null -> false
ConsoleLogger.js:76 2021-04-15T13:46:44.028Z [INFO] ChimeMeeting - API/DefaultAudioVideoFacade/d1a4f576-078e-40c3-848b-abd2e368104d/add3c9e4-e187-e4e4-c275-0a113f0e5477/realtimeIsLocalAudioMuted
ConsoleLogger.js:76 2021-04-15T13:46:44.029Z [INFO] ChimeMeeting - API/DefaultDeviceController/chooseAudioOutputDevice "default" -> null
ConsoleLogger.js:76 2021-04-15T13:46:44.030Z [INFO] ChimeMeeting - API/DefaultAudioVideoFacade/d1a4f576-078e-40c3-848b-abd2e368104d/add3c9e4-e187-e4e4-c275-0a113f0e5477/chooseVideoInputDevice "84708eceb56c7548a706bf8ba0638bd2d4686db3f63d1bc0c4419b48420cda5d"
ConsoleLogger.js:76 2021-04-15T13:46:44.031Z [INFO] ChimeMeeting - requesting new video device with constraint {"video":{"deviceId":{"exact":"84708eceb56c7548a706bf8ba0638bd2d4686db3f63d1bc0c4419b48420cda5d"},"width":{"ideal":960},"height":{"ideal":540},"frameRate":{"ideal":15},"googCpuOveruseDetection":true,"googCpuOveruseEncodeUsage":true,"googCpuOveruseThreshold":85,"googCpuUnderuseThreshold":55}}
actions.js:116 Going to setActiveAudioInputDevice with what is in the vuex store
actions.js:214 Going to set chooseAudioInputDevice on audioVideo {deviceId: "default", kind: "audioinput", label: "Default - Internal Microphone (Built-in)", groupId: "01eb5b3d0a1c520f842962ecb67a12af05d41df1c5378be8f542fcd92c5c6ff1"}
actions.js:215 Typeof device.deviceId string
ConsoleLogger.js:76 2021-04-15T13:46:44.032Z [INFO] ChimeMeeting - API/DefaultAudioVideoFacade/d1a4f576-078e-40c3-848b-abd2e368104d/add3c9e4-e187-e4e4-c275-0a113f0e5477/chooseAudioInputDevice "default"
ConsoleLogger.js:76 2021-04-15T13:46:44.033Z [INFO] ChimeMeeting - requesting new audio device with constraint {"audio":{"echoCancellation":true,"googEchoCancellation":true,"googEchoCancellation2":true,"googAutoGainControl":true,"googAutoGainControl2":true,"googNoiseSuppression":true,"googNoiseSuppression2":true,"googHighpassFilter":true,"deviceId":{"exact":"default"}}}
ConsoleLogger.js:76 2021-04-15T13:46:44.123Z [INFO] ChimeMeeting - got video device for constraints {"video":{"deviceId":{"exact":"84708eceb56c7548a706bf8ba0638bd2d4686db3f63d1bc0c4419b48420cda5d"},"width":{"ideal":960},"height":{"ideal":540},"frameRate":{"ideal":15},"googCpuOveruseDetection":true,"googCpuOveruseEncodeUsage":true,"googCpuOveruseThreshold":85,"googCpuUnderuseThreshold":55}}
ConsoleLogger.js:76 2021-04-15T13:46:44.123Z [INFO] ChimeMeeting - API/DefaultDeviceController/chooseVideoInputDevice "84708eceb56c7548a706bf8ba0638bd2d4686db3f63d1bc0c4419b48420cda5d"
ConsoleLogger.js:76 2021-04-15T13:46:44.137Z [INFO] ChimeMeeting - got audio device for constraints {"audio":{"echoCancellation":true,"googEchoCancellation":true,"googEchoCancellation2":true,"googAutoGainControl":true,"googAutoGainControl2":true,"googNoiseSuppression":true,"googNoiseSuppression2":true,"googHighpassFilter":true,"deviceId":{"exact":"default"}}}
ConsoleLogger.js:76 2021-04-15T13:46:44.138Z [INFO] ChimeMeeting - checking whether existing audio device can be reused
ConsoleLogger.js:76 2021-04-15T13:46:44.138Z [INFO] ChimeMeeting - requesting new audio device with constraint {"audio":{"echoCancellation":true,"googEchoCancellation":true,"googEchoCancellation2":true,"googAutoGainControl":true,"googAutoGainControl2":true,"googNoiseSuppression":true,"googNoiseSuppression2":true,"googHighpassFilter":true,"deviceId":{"exact":"default"}}}
ConsoleLogger.js:76 2021-04-15T13:46:44.160Z [INFO] ChimeMeeting - got audio device for constraints {"audio":{"echoCancellation":true,"googEchoCancellation":true,"googEchoCancellation2":true,"googAutoGainControl":true,"googAutoGainControl2":true,"googNoiseSuppression":true,"googNoiseSuppression2":true,"googHighpassFilter":true,"deviceId":{"exact":"default"}}}
ConsoleLogger.js:76 2021-04-15T13:46:44.160Z [INFO] ChimeMeeting - checking whether existing audio device can be reused
ConsoleLogger.js:76 2021-04-15T13:46:44.161Z [INFO] ChimeMeeting - requesting new audio device with constraint {"audio":{"echoCancellation":true,"googEchoCancellation":true,"googEchoCancellation2":true,"googAutoGainControl":true,"googAutoGainControl2":true,"googNoiseSuppression":true,"googNoiseSuppression2":true,"googHighpassFilter":true,"deviceId":{"exact":"default"}}}
ConsoleLogger.js:76 2021-04-15T13:46:44.183Z [INFO] ChimeMeeting - got audio device for constraints {"audio":{"echoCancellation":true,"googEchoCancellation":true,"googEchoCancellation2":true,"googAutoGainControl":true,"googAutoGainControl2":true,"googNoiseSuppression":true,"googNoiseSuppression2":true,"googHighpassFilter":true,"deviceId":{"exact":"default"}}}
ConsoleLogger.js:76 2021-04-15T13:46:44.183Z [INFO] ChimeMeeting - checking whether existing audio device can be reused
ConsoleLogger.js:76 2021-04-15T13:46:44.184Z [INFO] ChimeMeeting - requesting new audio device with constraint {"audio":{"echoCancellation":true,"googEchoCancellation":true,"googEchoCancellation2":true,"googAutoGainControl":true,"googAutoGainControl2":true,"googNoiseSuppression":true,"googNoiseSuppression2":true,"googHighpassFilter":true,"deviceId":{"exact":"default"}}}
```

If instead, I reuse the same deviceController that was established during the device setup screen, and pass this same instance to `new DefaultMeetingSession`, the problem goes away. `ChimeSetup - reusing existing audio device` `ChimeSetup - API/DefaultDeviceController/chooseAudioInputDevice "default" -> "success"`

```
2021-04-15T13:51:49.357Z [INFO] ChimeMeeting - browser is chrome 89 (89.0.4389)
ConsoleLogger.js:76 2021-04-15T13:51:49.357Z [INFO] ChimeMeeting - WebRTC unified plan for Chromium-based browsers is enabled
ConsoleLogger.js:76 2021-04-15T13:51:49.386Z [INFO] ChimeMeeting - adding meeting observer
ConsoleLogger.js:76 2021-04-15T13:51:49.388Z [INFO] ChimeMeeting - API/DefaultAudioVideoFacade/d1a4f576-078e-40c3-848b-abd2e368104d/eef86999-3426-99c4-49b3-c26a2210cb83/chooseAudioOutputDevice "default"
ConsoleLogger.js:76 2021-04-15T13:51:49.389Z [INFO] ChimeMeeting - API/DefaultAudioVideoFacade/d1a4f576-078e-40c3-848b-abd2e368104d/eef86999-3426-99c4-49b3-c26a2210cb83/hasStartedLocalVideoTile null -> false
ConsoleLogger.js:76 2021-04-15T13:51:49.390Z [INFO] ChimeMeeting - API/DefaultAudioVideoFacade/d1a4f576-078e-40c3-848b-abd2e368104d/eef86999-3426-99c4-49b3-c26a2210cb83/realtimeIsLocalAudioMuted
ConsoleLogger.js:76 2021-04-15T13:51:49.391Z [INFO] ChimeSetup - API/DefaultDeviceController/chooseAudioOutputDevice "default" -> null
ConsoleLogger.js:76 2021-04-15T13:51:49.391Z [INFO] ChimeMeeting - API/DefaultAudioVideoFacade/d1a4f576-078e-40c3-848b-abd2e368104d/eef86999-3426-99c4-49b3-c26a2210cb83/chooseVideoInputDevice "84708eceb56c7548a706bf8ba0638bd2d4686db3f63d1bc0c4419b48420cda5d"
ConsoleLogger.js:76 2021-04-15T13:51:49.391Z [INFO] ChimeSetup - requesting new video device with constraint {"video":{"deviceId":{"exact":"84708eceb56c7548a706bf8ba0638bd2d4686db3f63d1bc0c4419b48420cda5d"},"width":{"ideal":960},"height":{"ideal":540},"frameRate":{"ideal":15},"googCpuOveruseDetection":true,"googCpuOveruseEncodeUsage":true,"googCpuOveruseThreshold":85,"googCpuUnderuseThreshold":55}}
actions.js:116 Going to setActiveAudioInputDevice with what is in the vuex store
actions.js:214 Going to set chooseAudioInputDevice on audioVideo {deviceId: "default", kind: "audioinput", label: "Default - Internal Microphone (Built-in)", groupId: "ab845b1d33c1cc70e47108544f888a42a96de851779fc2caaba5c1a210c3516d"}
actions.js:215 Typeof device.deviceId string
ConsoleLogger.js:76 2021-04-15T13:51:49.393Z [INFO] ChimeMeeting - API/DefaultAudioVideoFacade/d1a4f576-078e-40c3-848b-abd2e368104d/eef86999-3426-99c4-49b3-c26a2210cb83/chooseAudioInputDevice "default"
ConsoleLogger.js:76 2021-04-15T13:51:49.394Z [INFO] ChimeSetup - reusing existing audio device
ConsoleLogger.js:76 2021-04-15T13:51:49.394Z [INFO] ChimeSetup - API/DefaultDeviceController/chooseAudioInputDevice "default" -> "success"
actions.js:217 Finished
ConsoleLogger.js:76 2021-04-15T13:51:49.396Z [INFO] ChimeMeeting - API/DefaultAudioVideoFacade/d1a4f576-078e-40c3-848b-abd2e368104d/eef86999-3426-99c4-49b3-c26a2210cb83/realtimeSubscribeToAttendeeIdPresence
ConsoleLogger.js:76 2021-04-15T13:51:49.396Z [INFO] ChimeMeeting - API/DefaultAudioVideoFacade/d1a4f576-078e-40c3-848b-abd2e368104d/eef86999-3426-99c4-49b3-c26a2210cb83/bindAudioElement "" -> {}
ConsoleLogger.js:76 2021-04-15T13:51:49.398Z [INFO] ChimeMeeting - transitioning from NotConnected to Connecting with Connect
ConsoleLogger.js:76 2021-04-15T13:51:49.403Z [INFO] ChimeMeeting - running task AudioVideoStart/d1a4f576-078e-40c3-848b-abd2e368104d/eef86999-3426-99c4-49b3-c26a2210cb83
ConsoleLogger.js:76 2021-04-15T13:51:49.404Z [INFO] ChimeMeeting - serial group task AudioVideoStart/d1a4f576-078e-40c3-848b-abd2e368104d/eef86999-3426-99c4-49b3-c26a2210cb83 running subtask AudioVideoStart/d1a4f576-078e-40c3-848b-abd2e368104d/eef86999-3426-99c4-49b3-c26a2210cb83/MonitorTask
ConsoleLogger.js:76 2021-04-15T13:51:49.404Z [INFO] ChimeMeeting - running task AudioVideoStart/d1a4f576-078e-40c3-848b-abd2e368104d/eef86999-3426-99c4-49b3-c26a2210cb83/MonitorTask
ConsoleLogger.js:76 2021-04-15T13:51:49.405Z [INFO] ChimeMeeting - adding meeting observer
ConsoleLogger.js:76 2021-04-15T13:51:49.405Z [INFO] ChimeMeeting - adding a ping-pong observer
ConsoleLogger.js:76 2021-04-15T13:51:49.406Z [INFO] ChimeMeeting - adding meeting observer
ConsoleLogger.js:76 2021-04-15T13:51:49.406Z [INFO] ChimeMeeting - Starting DefaultStatsCollector
```

So I don't know if this is a bug per se, or an edge case, or if I was simply doing things incorrectly. I only point it out as it worked previously with versions v2.5.0 and below, but no longer does.

**Comment by ltrung** [comment]
@chuckntaylor Just for confirmation, did you pass in deviceId string or some other object?
After selecting the device, SDK will try to restartLocalAudio which will try to pick up the audio input stream https://github.com/aws/amazon-chime-sdk-js/blob/01167e5466fb7b6cfd0585e4396a61e218808d9d/src/devicecontroller/DefaultDeviceController.ts#L1623
What caused the infinite loop was it failed the logic in `matchesDeviceSelection` https://github.com/aws/amazon-chime-sdk-js/blob/01167e5466fb7b6cfd0585e4396a61e218808d9d/src/devicecontroller/DefaultDeviceController.ts#L1297, 

Could you print out the value of DeviceController.activeDevices so we could check why it failed?

**Comment by chuckntaylor** [comment]
@ltrung thank you for revisiting this. I recalled last time you asked me about whether or not I was passing in an id string, so I made sure to confirm this.

There are two lines in the original logs I pasted above, which are the result of console logs generated by me. I placed these directly before calling chooseAudioInputDevice. These are:

```
actions.js:214 Going to set chooseAudioInputDevice on audioVideo {deviceId: "default", kind: "audioinput", label: "Default - Internal Microphone (Built-in)", groupId: "01eb5b3d0a1c520f842962ecb67a12af05d41df1c5378be8f542fcd92c5c6ff1"}
actions.js:215 Typeof device.deviceId string
```
The first line there outputs the device object as a whole, which has the deviceId "default". I only pass that deviceId string to chooseAudioInputDevice. The second line there is a log to confirm that typeof device.deviceId is indeed a string.

# Logging DeviceController.activeDevices
I will log this immediately before calling await chooseAudioInputDevice, and immediately after.

## Broken Version - Creating a new deviceController when going from the device setup screen to the chat screen.
Just a reminder, I was creating a new `DefaultDeviceController` to pass to the `DefaultMeetingSession`.

### Device Setup Screen - Before call
```js
{"audio":null,"video":null}
```

### Device Setup Screen - After call
```js
{"audio":{"groupId":"aaf9a6799bc9d87636f41acb75a5c485c2f7098d28b3442fec3f21164db08688","stream":{},"constraints":{"audio":{"echoCancellation":true,"googEchoCancellation":true,"googEchoCancellation2":true,"googAutoGainControl":true,"googAutoGainControl2":true,"googNoiseSuppression":true,"googNoiseSuppression2":true,"googHighpassFilter":true,"deviceId":{"exact":"default"}}}},"video":null}
```

### Chat Screen - Before Call
```js
{"audio":null,"video":null}
```

### Chat Screen - After Call
Never reach the log immediately after chooseAudioInputDevice.


## Working Version - Reuse the deviceController that was used during device setup screen.

### Device Setup Screen - Before call
```js
{"audio":null,"video":null}
```

### Device Setup Screen - After call
```js
{"audio":{"groupId":"c612bd8aae838720274022791f0e646396a2793baf4a47e3775b14781055da9e","stream":{},"constraints":{"audio":{"echoCancellation":true,"googEchoCancellation":true,"googEchoCancellation2":true,"googAutoGainControl":true,"googAutoGainControl2":true,"googNoiseSuppression":true,"googNoiseSuppression2":true,"googHighpassFilter":true,"deviceId":{"exact":"default"}}}},"video":null}
```

### Chat Screen - Before Call
```js
{"audio":{"groupId":"c612bd8aae838720274022791f0e646396a2793baf4a47e3775b14781055da9e","stream":{},"constraints":{"audio":{"echoCancellation":true,"googEchoCancellation":true,"googEchoCancellation2":true,"googAutoGainControl":true,"googAutoGainControl2":true,"googNoiseSuppression":true,"googNoiseSuppression2":true,"googHighpassFilter":true,"deviceId":{"exact":"default"}}}}}
```

### Chat Screen - After Call
```js
{"audio":{"groupId":"c612bd8aae838720274022791f0e646396a2793baf4a47e3775b14781055da9e","stream":{},"constraints":{"audio":{"echoCancellation":true,"googEchoCancellation":true,"googEchoCancellation2":true,"googAutoGainControl":true,"googAutoGainControl2":true,"googNoiseSuppression":true,"googNoiseSuppression2":true,"googHighpassFilter":true,"deviceId":{"exact":"default"}}}}}
```

**Comment by ltrung** [comment]
@chuckntaylor Thank for helping out. Could you modify this code https://github.com/aws/amazon-chime-sdk-js/blob/master/src/devicecontroller/DefaultDeviceController.ts#L1293 to print out the value of device, selection, and proposeContrainst if `kind === audio`? That would help us identify why that check failed and caused the device selection to happen again.

**Comment by chuckntaylor** [comment]
@ltrung sorry I misread your earlier request regarding what you wanted logged. I can certainly do this. Could you help me clarify the steps I need to take? I tried going into my `node_modules` folder to `aws-chime-sdk-js/build/devicecontroller/DefaultDeviceController.js`. However, I know this isn't what you intend for me to do.

To clarify, do I need to:
1) Fork this repo
2) Add those logging changes
3) Is there a build script I run?
4) Change my package.json to use the modified forked version of the repo.

Is this correct?

**Comment by ltrung** [comment]
@chuckntaylor That would work. However, If you can run your app locally, can't you modify the DefaultDeviceController.ts code in node_modules/aws-chime-sdk-js?

**Comment by chuckntaylor** [comment]
@ltrung I don't mind going in there to add the logs, but I was unable to find the file/lines you were referring to.
Here is the directory structure of `amazon-chime-sdk-js/`
<img width="263" alt="Screen Shot 2021-04-16 at 10 58 04 AM" src="https://user-images.githubusercontent.com/17050325/115044477-8d280480-9ea3-11eb-8469-a63feaf8384f.png">

Here are the contents of `aws-chime-sdk-js/build/devicecontroller/`
<img width="285" alt="Screen Shot 2021-04-16 at 10 59 17 AM" src="https://user-images.githubusercontent.com/17050325/115044479-8dc09b00-9ea3-11eb-9746-7c31b2e31cd4.png">

The only DefaultDeviceController typescript file in the build folder is `DefaultDeviceController.d.ts`, which is only 152 lines
I had gone into the `DefaultDeviceController.js` to make changes, but after transpiling, it looks quite a bit different than the code you pointed to at [https://github.com/aws/amazon-chime-sdk-js/blob/master/src/devicecontroller/DefaultDeviceController.ts#L1293](https://github.com/aws/amazon-chime-sdk-js/blob/master/src/devicecontroller/DefaultDeviceController.ts#L1293)

For example, there is no mention of `selection` in the transpiled version. I think, it ends up being this section in the js file around line 1072, since it is in here that the log
```js
this.logger.info(`requesting new ${kind} device with constraint ${JSON.stringify(proposedConstraints)}`)
```
is made, which is seen in the looping INFO logs.

### DefaultDeviceController.js
```js
const proposedConstraints = this.calculateMediaStreamConstraints(kind, device);
            // TODO: `matchesConstraints` should really return compatible/incompatible/exact --
            // `applyConstraints` can be used to reuse the active device while changing the
            // requested constraints.
            if (this.activeDevices[kind] &&
                this.activeDevices[kind].matchesConstraints(proposedConstraints) &&
                this.activeDevices[kind].stream.active &&
                this.activeDevices[kind].groupId !== null &&
                this.hasSameGroupId(this.activeDevices[kind].groupId, kind, device)) {
                this.logger.info(`reusing existing ${kind} device`);
                return;
            }
            if (kind === 'audio' && this.activeDevices[kind] && this.activeDevices[kind].stream) {
                this.releaseActiveDevice(this.activeDevices[kind]);
            }
            const startTimeMs = Date.now();
            const newDevice = new DeviceSelection_1.default();
            try {
                this.logger.info(`requesting new ${kind} device with constraint ${JSON.stringify(proposedConstraints)}`);
                const stream = this.intrinsicDeviceAsMediaStream(device);
                if (kind === 'audio' && device === null) {
                    newDevice.stream = DefaultDeviceController.createEmptyAudioDevice();
                    newDevice.constraints = null;
                }
                else if (stream) {
                    this.logger.info(`using media stream ${stream.id} for ${kind} device`);
                    newDevice.stream = stream;
                    newDevice.constraints = proposedConstraints;
                }
                else {
                    newDevice.stream = yield navigator.mediaDevices.getUserMedia(proposedConstraints);
                    newDevice.constraints = proposedConstraints;
                    if (kind === 'video' && this.lastNoVideoInputDeviceCount > callCount) {
                        this.logger.warn(`ignored to get video device for constraints ${JSON.stringify(proposedConstraints)} as no device was requested`);
                        this.releaseMediaStream(newDevice.stream);
                        return;
                    }
                    yield this.handleDeviceChange();
                    const track = newDevice.stream.getTracks()[0];
                    newDevice.endedCallback = () => {
                        // Hard to test, but the safety check is worthwhile.
                        /* istanbul ignore else */
                        if (this.activeDevices[kind] && this.activeDevices[kind].stream === newDevice.stream) {
                            this.logger.warn(`${kind} input device which was active is no longer available, resetting to null device`);
                            this.handleDeviceStreamEnded(kind, this.getActiveDeviceId(kind));
                            delete newDevice.endedCallback;
                        }
                    };
                    track.addEventListener('ended', newDevice.endedCallback, { once: true });
                }
                newDevice.groupId = ((_a = this.getMediaTrackSettings(newDevice.stream)) === null || _a === void 0 ? void 0 : _a.groupId) || '';
            }
```

**Comment by ltrung** [comment]
@chuckntaylor, this is the block of code to check whether we should quit from your DefaultDeviceController.js. 
```
if (this.activeDevices[kind] &&
    this.activeDevices[kind].matchesConstraints(proposedConstraints) &&
    this.activeDevices[kind].stream.active &&
    this.activeDevices[kind].groupId !== null &&
    this.hasSameGroupId(this.activeDevices[kind].groupId, kind, device)) {
    this.logger.info(`reusing existing ${kind} device`);
    return;
}
```

My guess is it failed in hasSameGroupId check which basically compared the groupId from the current selected audio input in activeDevices['audio'] with the groupId of the input deviceId. And now I think I might know whats going on. In your case, did you call listAudioInputDevice with the new DefaultDeviceController object? 
https://github.com/aws/amazon-chime-sdk-js/blob/869ac26eee5c129bdfdb3addb77140bbf084c756/src/devicecontroller/DefaultDeviceController.ts#L1024

If not, the check hasSameGroupId will fail since there is no way to find the groupId of the input DeviceId: 
https://github.com/aws/amazon-chime-sdk-js/blob/869ac26eee5c129bdfdb3addb77140bbf084c756/src/devicecontroller/DefaultDeviceController.ts#L1157

**Comment by chuckntaylor** [comment]
Ah! You guessed right. In the device setup screen I call the listAudioInputDevices, and keep this in my vuex store. When the new deviceController is created for the meetingSession in the chat screen, I first check the store to see if I already have a list of devices in the store, and if one has been 'selected' during the setup stage.

If I do, I simply call the chooseAudioInputDevice with the selected device - without calling listAudioInputDevices again.

In the working version, where I am reusing the original deviceController, I of course had previously made the call to listAudioInputDevices.

Do you still want me to try and log out that info, or does this answer everything now?

**Comment by ltrung** [comment]
You don't need to log out that info anymore. Glad it is resolved for you. I will close this issue then.

**Comment by chuckntaylor** [comment]
@ltrung Thank you kindly for your time in troubleshooting this. I can confirm that making a new call to listAudioInputDevices on the new deviceController does indeed resolve the issue, and no infinite loop occurs.
