### ISSUE TITLE
Unable initializing the video-source in UWP webview

### ISSUE THREAD

**Issue by husaindevelop** [aws/amazon-chime-sdk-js#1203]
**Important:** 
Please attach INFO-level logs with timestamps to the report from *before* the session started up until the point at which the unexpected behavior occured. For multi-participant calls, attach a log file for each participant if possible.
The meeting never started, so cannot provide any meeting logs.

**Meeting and attendee IDs:**
19a59ee4-bb53-43fb-876e-39e8d52e27fb

**Timeline**
We downloaded the amazon-chime-sdk single js and deployed it in browser both in android and desktop and its working but unfortunately it FAILED to initialize in (Universal Windows Platform) UWP Javascript Webview environment

**Describe the bug**
The amazon-chime-sdk single js demo is working in android web browser and desktop web browser, but FAILED to initialize in (Universal Windows Platform) UWP Javascript Webview environment. All the required permissions are enabled in uwp webview code.  In uwp webview app, the self video source and remote video source both are blank without any activity. 

**Screenshots**
![screenshot_amazon](https://user-images.githubusercontent.com/62126860/114979592-c747d500-9ea8-11eb-81fb-8b2f25b15108.png)

**Platform**
 - OS: 		Windows 10
 - Browser: 	Microsoft EDGE equivalent (UWP Webview)
 - Browser Version: 
 - Amazon Chime SDK GitHub Commit: Latest

**Comment by XHatan** [comment]
@husaindevelop Hey thanks for reporting this.
Do you have the log for this issue so we could take a look ?

**Comment by husaindevelop** [comment]
Thanks for reply.  Using visual studio debugging console, we were only able to get just a single line of log on initialization of  app:
"'WWAHost.exe' (Script): Loaded 'Sourcemap (https://mbracecloud.com/amazon-chime-sdk-js/demos/singlejs/build/amazon-chime-sdk.min.js)'. "

Other than this, unable to find any log files of this particular process.

**Comment by husaindevelop** [comment]
Any development ? Hearing from you is the development. Awaiting

**Comment by rnewman** [comment]
The UWP webview uses Edge for compatibility reasons.

The Amazon Chime SDK does not support Edge: see [our compatibility matrix](https://docs.aws.amazon.com/chime/latest/dg/meetings-sdk.html#mtg-browsers).

You might be able to use Microsoft's "webview2", which I believe uses Edge Chromium:

https://docs.microsoft.com/en-us/microsoft-edge/webview2/

**Comment by husaindevelop** [comment]
Thank you so very much. Your suggestion did lead to building the process implementing Amazon Chime SDK JS

**Comment by devalevenkatesh** [comment]
Thanks for your confirmation. Closing this issue now.
