### ISSUE TITLE
Browser and Device compatibility issues

### ISSUE THREAD

**Issue by gsudhanshu** [aws/amazon-chime-sdk-js#1204]
We have integrated Chime in our application using AWS-chime-js-sdk. We are using it for video call and chat features.

On testing we found some issues wrt. browser compatibility and device compatibility:
1. On Computer: audio not working in Firefox (ubuntu/windows) and edge(windows)
2. Working ok on Chrome(windows) and Chromium(ubuntu)
3. Mobile browsers (chrome): audio not working

**Comment by RidipDe** [comment]
Hi @gsudhanshu,
In order to investigate further, can you please provide us with the following information:

1. Browser Versions
2. OS Versions
3. Are you able to repro the issue using our [JS SDK Demo app](https://github.com/aws/amazon-chime-sdk-js/tree/master/demos)?
4. If so, what are the repro steps - in which case is the audio not working?

**Comment by gsudhanshu** [comment]
Hi @RidipDe ,

Not Working in desktop
Browser Versions :- Firefox 87.0v , Edge 88.0.705.81v & chrome 89.0.4389.128v
OS Versions :- window 64-bit operating system, x64-based processor

Not Working in Mobile
chrome 89.0.4389.128v

Working in mobile
Firefox 87.0v

Not working in Ubuntu desktop
OS Version: ubuntu 18.04
browser version: firefox 87.0 (64-bit)

Thanks

**Comment by RidipDe** [comment]
Can you please elaborate on what exactly is not working?

Are you able to successfully join and start meeting in our [JS SDK Demo app](https://github.com/aws/amazon-chime-sdk-js/tree/master/demos)?

We have integration tests running on the latest versions of the FF and Chrome browsers. For eg: https://github.com/aws/amazon-chime-sdk-js/blob/master/integration/configs/meeting_end_test.config.json
They does not seem to be throwing any error so far.

Can you please let us know the repro steps for the issue you are running into?

**Comment by gsudhanshu** [comment]
@RidipDe 
elaborate steps to reproduce on our demo app:

1. initiate meeting on firefox: https://chime-demo.evareg.com/?userId=755
2. MeetingId, an integer will appear on the screen
3. create url for 2nd user by adding numeric meetingId at end to : https://chime-demo.evareg.com/?userId=750&meetingId=
4. join meeting on another computer preferably on edge using new created url in step 3
5. test video/audio output and buttons

I tested just now and failed to get audio for either user

pls do make sure no special plugins are installed on firefox(1st user)

**Comment by RidipDe** [comment]
Thanks for the steps. I tried the repro steps mentioned above on FF and Chrome.
We officially do not support Edge. Here are the list of browsers we support: https://github.com/aws/amazon-chime-sdk-js/blob/master/guides/07_FAQs.md#browser-support

I was able to join and start the meeting and see the video on both the meetings. However could not hear the audio.
Meeting Id: 11ac8156-8ede-40b3-9819-2bd6525a833a

From the console logs, we see that "The AudioContext was not allowed to start. It must be resumed (or created) after a user gesture on the page. https://goo.gl/7K7WLu DefaultDeviceController.ts:1351 " - perhaps the redirection is preventing the audio context to enable by itself.

This is the reason why we are not able to listen to the audio.


<img width="681" alt="Screen Shot 2021-04-20 at 12 52 34 AM" src="https://user-images.githubusercontent.com/15669836/115358880-f5f8d080-a172-11eb-885a-d82e7dc0aaf9.png">

**Comment by gsudhanshu** [comment]
@RidipDe any possible solution? am I doing something wrong somewhere?

**Comment by gsudhanshu** [comment]
@RidipDe Did you allow audio input and audio output?

**Comment by RidipDe** [comment]
@gsudhanshu do you see the same warning on your browser?
Yes i allowed the audio input and the audio output.

As a fix you can try one of the following solutions:
1. Prevent redirection
2. Perform some manual action after the redirection - like page click.

**Comment by gsudhanshu** [comment]
@RidipDe 
Let me replicate this issue

**Comment by gsudhanshu** [comment]
@RidipDe which OS version and browser version were you using?
Can you post browser console logs here?

**Comment by RidipDe** [comment]
I tried it on 
+ Chrome v90
+ Firefox v87


I can provide you with the browser logs, however lately I am seeing the following message when I try to use the link that you provided.
![Screen Shot 2021-04-26 at 11 03 14 AM](https://user-images.githubusercontent.com/15669836/116129521-0e8b4e00-a67f-11eb-9142-7a236c99df82.png)

**Comment by gsudhanshu** [comment]
which OS?

use the following url's:

https://evachime-test.evareg.com/?userId=1&toUserId=2

**Comment by RidipDe** [comment]
PFA log file from my Chrome browser. It has info, error and warning logs as I could see on my browser console.

[evachime-test.evareg.com-1619481465261.log](https://github.com/aws/amazon-chime-sdk-js/files/6381024/evachime-test.evareg.com-1619481465261.log)

**Comment by gsudhanshu** [comment]
it is working for me, thanks
