### ISSUE TITLE
Chime API - CreateAppInstanceUser - AppInstanceUserId allowed length too short

### ISSUE THREAD

**Issue by teason** [aws/amazon-chime-sdk-js#1207]
Issue: 
-------
When using CreateAppInstanceUser API to create app instance user using Chime SDK, the request body field AppInstanceUserId is too short. https://docs.aws.amazon.com/chime/latest/APIReference/API_CreateAppInstanceUser.html#API_CreateAppInstanceUser_RequestSyntax
> AppInstanceUserId
> Type: String
> Length Constraints: Minimum length of 1. Maximum length of 50.

Use case: 
-----------
We would like to use Cognito Identity Pool Identity ID as the AppInstanceUserId, such that we can easily setup relevant access control on the Chime AuthorizedRole access in IAM role just like what is done in AWS Chime Chat demo. (https://github.com/aws/amazon-chime-sdk-component-library-react/tree/master/demo/chat)

In the chat demo, they are using region us-east-1, so the identity pool identity ID will only be : 
     us-east-1 : xxxxfc5c-xxxx-xxxx-xxxx-eb1b1509xxxx  (region + : + ID = **46 characters**)
In our region, our identity pool identity ID has exceeded the limit of 50 characters: 
     ap-southeast-1 : xxxxfc5c-xxxx-xxxx-xxxx-eb1b1509xxxx  (region + : + ID = **51 characters**)

Request: 
-----------
We would like to request AWS team to increase the length constraint to at least match the Chime meeting API CreateAttendee field: 
> ExternalUserId
> Type: String
> Length Constraints: Minimum length of 2. Maximum length of 64.

Thank you.

**Comment by ltrung** [comment]
@teason Thank for reporting this. I have brought this up with our team and see if we can increase the length constraint

**Comment by ltrung** [comment]
@teason We have made the change. Closing the issue  but feel free to reopen it if you still encounter the same issue.
