### ISSUE TITLE
Screen sharing does not work from Safari on an Apple M1

### ISSUE THREAD

**Issue by MaxQuantumCake** [aws/amazon-chime-sdk-js#1209]
**bug**

Hello ,

Screen sharing does not work from Safari on an Apple M1: in this case remote users do not see what Safari shares.

The problem appears both on the application we are developing and on the AWS demo available here: https://github.com/aws/amazon-chime-sdk-js/tree/master/demos/browser

Test results (on the left the one who shares --> the one who watches):
- Safari (mac Intel) --> Chrome (mac Intel)✅
- Safari (mac Intel) --> Chrome (mac M1)✅
- Safari (mac M1) --> Chrome (mac Intel)❌
- Safari (mac M1) --> Chrome (mac M1)❌
- Chrome (mac Intel) --> Safari (mac Intel)✅
- Chrome (mac Intel) --> Safari (mac M1)✅
- Chrome (mac M1) --> Safari (mac Intel)✅
- Chrome (mac M1) --> Chrome (mac M1)✅

For info screen sharing works with Google Meet from Safari on mac M1. I give you this information to eliminate a bug coming from Safari side.

**screenshot**

webrtc-internals data for screen sharing video, received from Chrome (mac intel) when Safari (mac M1) shares:
<img width="828" alt="Screenshot 2021-04-20 at 11 14 52" src="https://user-images.githubusercontent.com/66793204/115371433-42232f80-a1ca-11eb-8bc0-779b87855013.png">

**Platform**
 - OS: Mac OS 11.2.3 -- Mac mini M1
 - Browser: Safari
 - Browser Version: 14.0.3 (16610.4.3.1.7)
 - Amazon Chime SDK GitHub Commit: 7438e2ca9c36af7350260554c381087217c9e9ad

**Comment by rlebosse** [comment]
I'm facing the same issue, thank for reporting it @MaxQuantumCake !

**Comment by richnew10** [comment]
I can reproduce this.

In Safari Tech Preview, setting "GPU Process: Video Capture" causes even the local preview to appear black. That points to an encoder/capture bug in Safari.

I can also reproduce this in https://janus.conf.meetecho.com/screensharingtest.html, so this is not limited to the SDK: it's a browser bug.

**Comment by devalevenkatesh** [comment]
Filed a Webkit bug: https://bugs.webkit.org/show_bug.cgi?id=236870
Had not found a bug with Webkit around this. Please feel free to update if you have information on similar filed bugs.

**Comment by devalevenkatesh** [comment]
This issue is fixed in newer versions of Safari on MacOS Monterey M1 (Not sure if MacOS Big Sur latest version still faces this issue).

Webkit main bug: https://bugs.webkit.org/show_bug.cgi?id=233036

Please update the Safari to latest and see whether this is still an issue.
