### ISSUE TITLE
I cloned this repository and then i am running command   npm run start inside browser folder it is showing error .........   'script' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by rnqayush** [aws/amazon-chime-sdk-js#1224]
![chime issue](https://user-images.githubusercontent.com/74084740/115949585-c390ff80-a4f3-11eb-8d1f-224acdb0900a.png)

kindly help me out

**Comment by ltrung** [comment]
@rnqayush The build script recently adds a step in prebuild (https://github.com/aws/amazon-chime-sdk-js/blob/master/package.json#L26) that needs Ruby installation. 
For Windows, you may also want to modify that line in package.json to append `ruby`:
```
    "prebuild": "ruby script/conditional-install",
```

**Comment by rnqayush** [comment]
thanks for response. I solved this issue by using  AWS cloud9 service.
