### ISSUE TITLE
Unable to set audio input and output device on Firefox 

### ISSUE THREAD

**Issue by iamibrahimkholil** [aws/amazon-chime-sdk-js#1225]
Audio input and output working on other browsers but we are unable set audio input and output device in firefox browser.
We are passing deviceId as a parameter to this function.
```js
  async function setDevices(deviceType, deviceId) {
    if (deviceType === "audioInput") {
      await meetingSession.audioVideo.chooseAudioInputDevice(deviceId);
    } else if (deviceType === "audioOutput") {
      await meetingSession.audioVideo.chooseAudioOutputDevice(deviceId);
    } else if (deviceType === "video") {
      await meetingSession.audioVideo.chooseVideoInputDevice(deviceId);
    }
  }
```

**Screenshots**
Here is the log
![Capture](https://user-images.githubusercontent.com/79884206/116044777-2371dc80-a693-11eb-9368-86b90c9a4114.PNG)

**Platform**
 - OS: Windows, Mac
 - Browser: Firefox
 - Browser Version: 88.0

**Comment by ltrung** [comment]
@iamibrahimkholil 

* For Audio Input:
    * Do you have any error in your console log? 
    * What SDK version are you using?
    * Did you call listAudioInputDevices() before calling chooseAudioInputDevices()?
    * Did you pass in deviceId as string?
* For Audio Output: As call out in our [FAQs](https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html), you cannot set audio output in Firefox because the browser does not support enumerate audio output devices (unless end users enable 'media.setsinkid.enabled' in their Firefox pref setting).

**Comment by iamibrahimkholil** [comment]
Problem solved. As it turned out for firefox are were not calling listAudioInputDevices() this method. Instead, we were calling MediaDevices.enumerateDevices() this method. When we used listAudioInputDevices() it was working fine. Now I will close the issue.
