### ISSUE TITLE
Meeting Session charges

### ISSUE THREAD

**Issue by william-levi** [aws/amazon-chime-sdk-js#1226]
I just want to clarify about the charges

It says $0.0017 per session / minute

So when i create a meeting session, it automatically charges ?
So how do i stop the session ? 

I'm developing an application right now using chime-sdk-js and
I have created many sessions. And I'm worried cause I didnt close or delete the session.
Im worried it might jacked up the bill.

**Comment by ltrung** [comment]
@william-levi Thanks for your question. We detailed how we calculated the cost in our [FAQs](https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html#how-much-does-the-amazon-chime-sdk-cost).
The meeting will start charging when an attendee joins the meeting.
To stop the meeting session, you can manually call deleteMeeting API or the meeting will auto-end after 5 minutes without any attendee (i.e., audio connection). More details on meeting auto-end policies can be found [here](https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html#when-does-an-amazon-chime-sdk-meeting-end).
Feel free to reopen the issue if you have additional question.

**Comment by scortes1989** [comment]
@ltrung if i have 3 attendees in a meet , the first attendee is during 60 minutes connected and the second attendee during 30 minutes and the third by 15 minutes, what is the charges ?

**Comment by scortes1989** [comment]
@ltrung how i can know the meeting time by attendee in a meet or the cost by meeting ? i need charge this

**Comment by ltrung** [comment]
@scortes1989 You can view the cost under AWS Cost Explorer. If you want to measure it programmatically, you can setup [Chime Event Bridges](https://docs.aws.amazon.com/chime/latest/ag/automating-chime-with-cloudwatch-events.html) to calculate when an attendee joins and leaves.

**Comment by scortes1989** [comment]
thanks !!
