### ISSUE TITLE
Video Flickers

### ISSUE THREAD

**Issue by junedlanja** [aws/amazon-chime-sdk-js#1227]
**Important:** 
I have one application build using amazon chime. Its basically coded based on classroom demo. One of our client have recently complained about flicker issue in their video. 

**Meeting and attendee IDs:**
-

**Timeline**
-

**Describe the bug**
-

**Screenshots**
Here is screencast we have from client : https://drive.google.com/file/d/11zJbDYWKASvxxAT330-X8s1ztM29iEYX/view?usp=sharing

**Platform**
 - OS: mac
 - Browser: Chrome
 - Browser Version: 
 - Amazon Chime SDK GitHub Commit: 2.2.1 or 2.6.0

**Comment by vidya-mohan** [comment]
@junedlanja - thanks for reporting your issue. Can you help us with the following questions:
- Is the video being flipped that of a local user (and their local view) or of a remote user? If the latter, is the other user also seeing the video being flipped?
- Do you have Chime meeting or attendee Ids for these users?
- Are you modifying the video element characteristics by rotating it via CSS?

**Comment by junedlanja** [comment]
@vidya-mohan  Thanks for quick reply.

- We are not modifying the video element characteristics through CSS.
- There were 3 attendees in these meeting. Here is the details about them:

```
"meetingId": "dd84a605-fc2f-4951-9fa8-4deef3c74b46", 
"attendeeId": "26758fd6-fefe-14c6-1fbb-696dbe7a1fc5", 
"osName": "Mac OS", 
"osVersion": "11.2.3", 
"sdkVersion": "2.6.0",
"browserMajorVersion": "89",
"browserName": "Chrome", 
"browserVersion": "89.0.4389.114"


"meetingId": "dd84a605-fc2f-4951-9fa8-4deef3c74b46", 
"osName": "Mac OS", 
"osVersion": "11.2.3", 
"sdkVersion": "2.6.0",
“attendeeId": "46d48088-7580-75d8-4ee0-b504f74fab36", 
"browserMajorVersion": "89", 
"browserName": "Chrome", 
"browserVersion": "89.0.4389.128",


"meetingId": "dd84a605-fc2f-4951-9fa8-4deef3c74b46", 
"osName": "Mac OS", 
"osVersion": "11.2.3", 
"sdkVersion": "2.6.0",
"attendeeId": "055ddf39-a26d-ae99-a9fa-ddc86eb58ae2", 
"browserMajorVersion": "89", 
"browserName": "Chrome", 
"browserVersion": "89.0.4389.114",


```

**Comment by XHatan** [comment]
hey thanks for reporting this, is this possible to get client log for those participants who observed video flicker ?

**Comment by bjason** [comment]
Hi, I have tested the classroom demo but failed to reproduce the issue. Is it possible for you to describe the steps to reproduce the issue and update with the log? Thanks!

**Comment by junedlanja** [comment]
Unfortunately, we don't have client-side logs.

**Comment by bjason** [comment]
Thanks for looking into that, The log can also be stored in `/Users/<User>/Library/Logs/<App Name>`, would you mind double checking for me?

**Comment by vidya-mohan** [comment]
Resolving as no logs. Please see https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html#how-can-i-get-amazon-chime-sdk-logs-for-debugging
