### ISSUE TITLE
Doubt will the demo run and call services from AWS AISPL account of India 

### ISSUE THREAD

**Issue by gavandivya** [aws/amazon-chime-sdk-js#1228]
### What are you trying to do?
I want to add a Video calling,audio calling, screen sharing and messaging feature to existing website.

I saw that in Media region we have Mumbai as nearest region to host meeting. But the Chime Console page is not  loaded at our end due to AISPL account. 

Need urgent help....
Can I run the demo provided my AWS without being able to use the Chime console and call my services needed?

**Comment by ltrung** [comment]
@gavandivya Thanks for reaching out. Even without access to console, you should still be able to run the demo with your aws account as you have access to all Chime Meeting API in AWS SDK.
Could you give it a try and feel free to reopen this issue if you run into any issue?

**Comment by gavandivya** [comment]
Okay thanks for helping me out will try the demo and let you know..
