### ISSUE TITLE
Doesn't support Node v16.0.0

### ISSUE THREAD

**Issue by tvotan** [aws/amazon-chime-sdk-js#1229]
**Describe the bug**
I think this repo doesn't support Node v16.0.0. It recently came out.

**Screenshots**
<img width="961" alt="Screenshot 2021-04-27 at 15 05 17" src="https://user-images.githubusercontent.com/39995527/116246214-107e0b80-a76a-11eb-8cf4-81bf7fcf9b5c.png">

**Platform**
 - OS: Mac OSX Big Sur (Intel processor)
 - Browser: Brave
 - Browser Version: -
 - Amazon Chime SDK GitHub Commit: -

**Comment by ltrung** [comment]
@tvotan Thanks for reporting this. PR #1230 has updated to include Node 16.

**Comment by ltrung** [comment]
We have updated the latest v2.8.0 support Node 16.
