### ISSUE TITLE
Issue with Mozila firefox

### ISSUE THREAD

**Issue by rohit0337** [aws/amazon-chime-sdk-js#1231]
hello
while camera is used by some other applications like google meet or zoom, and user try to join meeting in chime application 
its give an error in console

2021-04-29T08:54:06.330Z [ERROR] SDK - failed to get video device for constraints {"video":{"deviceId":{"exact":"LlupIEF8UsFeXFmeDtZhinjoebGGVn89ZjK1HvxSoLo="},"width":{"ideal":960},"height":{"ideal":540},"frameRate":{"ideal":15},"googCpuOveruseDetection":true,"googCpuOveruseEncodeUsage":true,"googCpuOveruseThreshold":85,"googCpuUnderuseThreshold":55}}: AbortError: Starting video failed ConsoleLogger.js:67:25

2021-04-29T08:54:06.330Z [ERROR] SDK - Over-constrained by constraint:

and user when click on join its not able to join the meeting

is there any event we can check audio or video devices available and how to handle these error. because i thinks this is a fatal error.

**Comment by simmkyu** [comment]
Using the [Chime SDK serverless demo](https://github.com/aws/amazon-chime-sdk-js/tree/master/demos/serverless), I joined a meeting while I enabled videos in other WebRTC-based applications and desktop applications. In macOS Firefox (78.10.0), I could not reproduce the bug.

In the attached video, I turned videos on in our serverless demo and the [WebRTC official demo](https://appr.tc/). You can see that no constraint occurred in Firefox.

https://user-images.githubusercontent.com/36240708/116616172-3b469c00-a8f1-11eb-9b5d-5461b3de3403.mov

⠀

> is there any event we can check audio or video devices available and how to handle these error. because i thinks this is a fatal error.

`chooseAudioInputDevice` and `chooseVideoInputDevice` APIs throw a custom error object with a "getUserMedia" exception, e.g., [OverconsraintError](https://github.com/aws/amazon-chime-sdk-js/blob/master/src/devicecontroller/OverconstrainedError.ts). You can access the "getUserMedia" exception via the `cause` property.

Here's a list of getUserMedia exceptions.
https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getUserMedia#exceptions

For example, you can handle the `OverconstrainedError` error when choosing a video input device.

```
try {
  const videoDevice = (await app.audioVideo.listVideoInputDevices())[0]
  await app.audioVideo.chooseVideoInputDevice(videoDevice);
} catch (error) {
  if (error?.cause?.name === 'OverconstrainedError') {
    console.error('Handle an OverconstrainedError here');
  } else {
    console.error('Other errors');
  }
}
```

**Comment by simmkyu** [comment]
The `OverconstrainedError` occurs when you call the `meetingSession.audioVideo.chooseVideoInputDevice` API with an invalid device ID.

Another user reported the same `OverconstrainedError` issue (https://github.com/aws/amazon-chime-sdk-js/issues/1248). They called the `meetingSession.audioVideo.chooseVideoInputDevice` with a device ID that did not exist in iPad.

Could you ensure that the device ID `LlupIEF8UsFeXFmeDtZhinjoebGGVn89ZjK1HvxSoLo=` is one of devices returned from `meetingSession.audioVideo.listVideoInputDevices` API?

**Comment by vidya-mohan** [comment]
Resolving as no response
