### ISSUE TITLE
Using external IP Camera as video source

### ISSUE THREAD

**Issue by chandruchiku** [aws/amazon-chime-sdk-js#1235]
We would like to use external IP Camera as a video source for the meeting instead of default mediaDevices. 

This feature can be used to include a higher resolution meeting camera in the meeting room instead of camera available on the device. 

Is this feature currently supported or how to achieve this ?

**Comment by simmkyu** [comment]
The `meetingSession.audioVideo.chooseVideoInputDevice` API takes the following types:
- `string` and `MediaTrackConstraints`: to get a media device using a browser's `getUserMedia` API
- `null`: to choose no device
- `VideoTransformDevice`: to process a video input, e.g., Amazon VoiceFocus feature
- **[`MediaStream`](https://developer.mozilla.org/en-US/docs/Web/API/MediaStream): If you can get a stream from your external IP camera, you can pass it to the `chooseVideoInputDevice` API.**

⠀

https://github.com/aws/amazon-chime-sdk-js/blob/5e0eae76ec33e1c7a2b60e0b826bb0d394a16897/src/devicecontroller/DeviceController.ts#L80-L86

https://github.com/aws/amazon-chime-sdk-js/blob/5e0eae76ec33e1c7a2b60e0b826bb0d394a16897/src/devicecontroller/Device.ts#L9

**Comment by devalevenkatesh** [comment]
Closing this issue as looks like no further action is pending, please open new issues as required.
