### ISSUE TITLE
Missing promise rejection\\error from audioVideo.bindAudioElement on Safari

### ISSUE THREAD

**Issue by DynamicSTOP** [aws/amazon-chime-sdk-js#1238]
**Describe the bug**
`Unhandled Promise Rejection: AbortError: The operation was aborted.` from this line https://github.com/aws/amazon-chime-sdk-js/blob/master/src/audiomixcontroller/DefaultAudioMixController.ts#L80 whenever I try to run this part outside of some user action callback (on message from websocket) 
```javascript
const bindDevices = async () => {
  //...
  try {
      await session.audioVideo.bindAudioElement(audioRef);
  } catch (e) {
      console.log('catch!');
      console.error(e);
  }
  // ...
  // some other stuff
  // ...
}
```
This happens only in Safari (thanks apple). The reason is it's not triggered by user action, but rather by callback coming from network. In my app I have to authorize user first, then once I got "OK" from my app via websocket I start session etc. But safari doesn't like that all of this happens not by clicking on some button and things on screenshots bellow happens.

On a stack trace bellow I can see my bindAudioElement function. I am not sure why it goes unhandled https://github.com/aws/amazon-chime-sdk-js/blob/master/src/audiomixcontroller/DefaultAudioMixController.ts#L23.

**Screenshots**
![image](https://user-images.githubusercontent.com/9434504/116749294-66241380-aa09-11eb-8ff0-1e24b1bef48c.png)
![image](https://user-images.githubusercontent.com/9434504/116750095-9ddf8b00-aa0a-11eb-85ec-e2d3fbe57a15.png)

**Platform**
 - OS: macOs Catalina 10.15.7
 - Browser: Safari
 - Browser Version: Version 14.0.3 (15610.4.3.1.7, 15610)
 
  - OS: iPadOS 14.4.2
 - Browser: Safari
 - Browser Version: Version 14.0.3
 
 - Amazon Chime SDK GitHub Commit: 2.8.0 tag  244aafa7d512e344e272e08f3772e9413a147aac

**Comment by Taapo** [comment]
We were advised to post the issue here on Github, instead of creating a ticket on AWS support. Is someone from the Chime SDK team willing to comment on this? I can't imagine that nobody else has this problem, so it would be appreciated to know if there is something we are overlooking ...

**Comment by simmkyu** [comment]
The [Chime SDK serverless demo](https://github.com/aws/amazon-chime-sdk-js/tree/master/demos/serverless) offers `app.audioVideo` to access audio-video APIs for debugging.

In macOS 10.15.7 Safari 14.1, I ran the following script in the browser console to simulate a callback without user interaction. The `bindAudioElement` worked okay without any error.

```
setTimeout(async () => {
  try {
    const audioRef = document.getElementById('meeting-audio');
    await app.audioVideo.bindAudioElement(audioRef);
  } catch (e) {
    console.error(e);
  }
}, 5000);
```

https://user-images.githubusercontent.com/36240708/117068776-90fbb980-ace0-11eb-9df0-9693e58d1efa.mov

⠀

---

>  The reason is it's not triggered by user action, but rather by callback coming from network. 

Could you elaborate on the callback coming from a network? Is your callback invoked after a long period of inactivity?

⠀

The `meetingSession.audioVideo.bindAudioElement` API performs these key operations on the HTMLAudioElement you pass.
- Setting `audioElement.autoplay` to `true`
- Setting `audioElement.srcObject` to a stream if available
- Calling `audioElement.setSinkId` to set the audio device ID

Do you know which exact operation the Chime SDK for JavaScript fails to handle in your stack trace (probably at the top one)?

**Comment by DynamicSTOP** [comment]
Hi!

> Do you know which exact operation the Chime SDK for JavaScript fails to handle in your stack trace (probably at the top one)?

as I pointed in first message it's this line https://github.com/aws/amazon-chime-sdk-js/blob/master/src/audiomixcontroller/DefaultAudioMixController.ts#L80

More or less my issue is caused by this https://developer.apple.com/documentation/webkit/delivering_video_content_for_safari#3030252

I assume you might miss error by one of the following reasons 
- devtools are privileged
- assigning same srcObject won't have any effect
- (very unlikely) you've allowed autoplay for that domain 

I've played a bit with example. Though I can't get to same error (probably because of the order of chime functions call or something like that) but I can at least get an example of refused promise (yeah, probably should have forked at this point)
https://gist.github.com/DynamicSTOP/554ef13e6921cdd83c0dc80419cd9910#file-meetingv2-ts-L1194-L1208
![image](https://user-images.githubusercontent.com/9434504/117141044-c1158c00-adb6-11eb-9859-a20d3ca0e5c9.png)

**Comment by simmkyu** [comment]
In macOS 10.15.7 Safari 14.1, I could reproduce the `AbortError` by running the following script in the [Chime SDK serverless demo](https://github.com/aws/amazon-chime-sdk-js/tree/master/demos/serverless).

```js
(async () => {
    const audioRef = document.getElementById('meeting-audio');
    
    // Starts playing an audio.
    await app.audioVideo.bindAudioElement(audioRef);
    audioRef.play();

    // Setting srcObject interrupts an audio?
    await app.audioVideo.bindAudioElement(audioRef);
})();
```

⠀

In Chrome, the `DOMException: The play() request was interrupted by a new load request` error occurs. The error message contains a link to this article: https://developers.google.com/web/updates/2017/06/play-request-was-interrupted

The article says:
>  Calling video.pause() isn't the only way to interrupt a video. You can entirely reset the video playback state, including the buffer, with video.load() and video.src = ''.

⠀

Similarly, setting the `HTMLMediaElement.srcObject`  before a promise from `HTMLMediaElement.play()` gets resolved causes the `AbortError`.

The Chime SDK for JavaScript enables the `HTMLMediaElement.autoplay` property, but it does not call `play()` or `pause()`. When you call the `meetingSession.audioVideo.start` API, the Chime SDK for JavaScript internally sets `HTMLMediaElement.srcObject` to a `MediaStream` object available from a [`RTCPeerConnection` object](https://developer.mozilla.org/en-US/docs/Web/API/RTCPeerConnection).

In your project, do you call `HTMLMediaElement.play()`? Otherwise, Safari's autoplay behavior may cause this race condition.

**Comment by DynamicSTOP** [comment]
In the click handler for the login button we do `document.getElementById('audioRef').play();` because it counts as clear user intention by browsers.
Yet audio element doesn't have any src in html `<audio id="audioRef" class="d-none" playsinline></audio>` nor anything is set as src or srcObject using JS outside of chime sdk.

**Comment by DynamicSTOP** [comment]
Ok, I guess I'll try it your way to move `play()` after callback with `bindAudioElement()`. That's clearly won't autoplay on safari, but I might at least catch rejected promise. ~~god I hate safari~~

**Comment by simmkyu** [comment]
In the Chime SDK demo, we have an audio element with only the `display:none` style.

https://github.com/aws/amazon-chime-sdk-js/blob/8de51639a8d00519d17d42f1722dd7fea2d065f2/demos/browser/app/meetingV2/meetingV2.html#L271

⠀

We simply pass the audio element to `bindAudioElement` API.  The Chime SDK for JavaScript internally enables the `HTMLMediaElement.autoplay` attribute. We do not call the `play()` in the demo application.

https://github.com/aws/amazon-chime-sdk-js/blob/8de51639a8d00519d17d42f1722dd7fea2d065f2/demos/browser/app/meetingV2/meetingV2.ts#L2058-L2064


Just curious, are you re-using the same audio element for other features in your application?

**Comment by DynamicSTOP** [comment]
No, we don't. Audio element is used only for playing audio from chime.

**Comment by DynamicSTOP** [comment]
I have more questions regarding late bind of audio element.

So first I catch the "denied" error like so
```javascript
const bindDevices = async () => {
        console.log('bind devices');
        if (session && meetingStartSucceeded) {
            try {
                await session.audioVideo.bindAudioElement(audioRef);
                try {
                    if (audioRef.paused) {
                        await audioRef.play();
                    }
                } catch (e) {
                    console.log('Not allowed to autoplay due to the following error');
                    console.log(e);
                    audioRef.pause();
                    dispatch({type: 'SET_FORCE_MUTED', forceMuted: true});
                }
                if (autoJoinAsSpeaker || isStartingStreaming) {
                    // binding audio and webcam for speakers
                } else {
                    await session.audioVideo.chooseAudioInputDevice(null);
                    await session.audioVideo.chooseVideoInputDevice(null);
                }
                session.audioVideo.start();
            } catch (e) {
                console.error(e);
            }
}
```
console at that point
![image](https://user-images.githubusercontent.com/9434504/117541161-3aadb400-b01b-11eb-855f-ca24df64dec0.png)

I make "mute" button look active to force user to tap on it. Upon tapping I do the following
```javascript
            console.log('was force muted toggle');
            console.log('starting from muted toggle');
            audioRef.pause();
            audioRef.srcObject = null;
            audioRef.src = null;
            dispatch({type: 'SET_FORCE_MUTED', forceMuted: false});
```
Upon changing forceMuted to false, bindDevices are triggered in chain.

![image](https://user-images.githubusercontent.com/9434504/117541104-ff12ea00-b01a-11eb-87c4-f12d8ca4f428.png)

After that I see only `local clock skew estimate` lines. I don't see any errors or anything related.
I've tried different combinations of audioRef.pause() audioRef.play() audioVideoFacade.unbindAudioElement(). It shouldn't be connection issue since if I allow autoplay (safari->preference->auto-play-> Allow all autoplay) everything works.

So any advice on proper rebinding audioRef? Or am I doomed to drop modern websockets and use old http ajax requests?

**Comment by simmkyu** [comment]
In the [Chime SDK demo], we call `meetingSession.audioVideo.bindAudioElement` / `meetingSession.audioVideo.unbindAudioElement` APIs to enable/disable an audio output. We do not invoke `play()` or `pause()` on the audio element.

https://github.com/aws/amazon-chime-sdk-js/blob/2fca426171ca6aff5feece7819cf114170372c7b/demos/browser/app/meetingV2/meetingV2.ts#L772-L783

⠀

The implementation is simple.
1. `bindAudioElement` API performs:
    - Sets `audioElement.autoplay` to `true`
    - Sets `audioElement.srcObject` to a stream if available
    - Calls `audioElement.setSinkId` to set the audio device ID
2. `unbindAudioElement` API performs:
    - Sets `HTMLMediaElement.srcObject` to `null`

⠀

Can you call `meetingSession.audioVideo.unbindAudioElement` to implement your `SET_FORCE_MUTED` action?

**Comment by DynamicSTOP** [comment]
Like I said I've tried unbindAudioElement(). So I have no idea what safari doesn't likes now. 

How it looks like (had to mask some things): [video](https://leonid.work/tmp/bugged_1.mp4)
console log [chime_log.txt](https://github.com/aws/amazon-chime-sdk-js/files/6487676/chime_log.txt)
Once I get error I stop <audio> and reset it's src and srcObject. Once I click unmute button (so it's actually treated as user action) I try to bind again and play(). Safari shows that blue audio icon in address bar, but I still can't hear any audio.

How it expected to be and how it actually is in every other browser (achieved with safari preferences just to show that it's not rdp problem): [video](https://leonid.work/tmp/bugged_2.mp4)
Video tile in the middle is active speaker that I get with https://aws.github.io/amazon-chime-sdk-js/interfaces/audiovideofacade.html#subscribetoactivespeakerdetector

**Comment by Taapo** [comment]
Hi Chime Team, could someone please check this last message? We're stuck on this problem, and still completely in the dark whether we are the only ones experiencing this problem or if there are others ... thanks for any feedback!

**Comment by simmkyu** [comment]
I tested the force-mute scenario using the [Chime SDK serverless demo](https://github.com/aws/amazon-chime-sdk-js/tree/master/demos/serverless) on macOS Safari 14.1. I did not need to check the `HTMLMediaElement.paused ` property or call `HTMLMediaElement.play()`.

In the attached videos, Chrome (right) produces a noise (the 440 Hz option in the demo). You hear that noise from Safari (left).
⠀

**1. Muting/unmuting an audio output using `bindAudioElement`/`unbindAudioElement`** API

https://user-images.githubusercontent.com/36240708/118890191-20919280-b8b3-11eb-8738-4fb85e4373ef.mov

⠀

**2. Binding an audio element after starting a session**

https://user-images.githubusercontent.com/36240708/118893014-a19e5900-b8b6-11eb-8842-017e24aaa096.mov

These are snippets I ran in the demo's browser console. Similar to your code, I call the `bindAudioElement` API after the session starts.

```js
app.audioVideoDidStop = () => { /* To prevent the demo behavior */ console.warn('ended!') };
app.audioVideo.stop();
```
```js
app.audioVideo.unbindVideoElement(); /* Force mute before start. */
app.audioVideo.start();
app.audioVideo.addObserver({
   audioVideoDidStart() {
      console.warn('started! Bind an audio element now.');
      app.audioVideo.bindAudioElement(document.getElementById('meeting-audio'));
   }
});

```

⠀

---

Could you elaborate on this part again? The Chime SDK for JavaScript does not (or should not) require an application to check `paused` and call `play()` on an audio element.

![image](https://user-images.githubusercontent.com/36240708/118893965-2c338800-b8b8-11eb-9fcb-2110a1f4a758.png)

**Comment by vidya-mohan** [comment]
Resolving due to no response
