### ISSUE TITLE
Feature Request - Exposing key/value tags feature from CreateAttendee API

### ISSUE THREAD

**Issue by malsabbagh** [aws/amazon-chime-sdk-js#1246]
It seems [`CreateAttendee API`](https://docs.aws.amazon.com/chime/latest/APIReference/API_CreateAttendee.html) supports passing key/value tags. However, these tags are not available within `amazon-chime-sdk-js` package. 

Are there any plans to expose this feature to be accessible by the js clients?

**Comment by vidya-mohan** [comment]
Thank you for your interest @malsabbagh , this is not something we support right now - but we will keep the issue opened till we plan to

**Comment by YauheniBH-EF** [comment]
it would be REALLY useful :)

**Comment by ltrung** [comment]
In the regional Chime Meeting SDK we no longer support tagging attendee as as attendees are ephemeral resources so closing the issue.
