### ISSUE TITLE
Failed to get video device for constraints - iPad Safari and Chrome

### ISSUE THREAD

**Issue by adilsaeed31** [aws/amazon-chime-sdk-js#1248]
**Describe the bug**
Failed to get video device for constraints - iPad Safari and Chrome

**Screenshots**
<img width="2034" alt="ipad" src="https://user-images.githubusercontent.com/6284410/117355742-a11bc080-aebb-11eb-939e-8a1bf0b28f4e.png">

**Platform**
 - OS: iPad 8th Gen 10.2 IOS 14.5
 - Browser: Safari and Chrome both giving same
 - Browser Version: 14.1
 - Amazon Chime SDK GitHub Commit: 2.8.0

**Comment by simmkyu** [comment]
In the screenshot, you called the `meetingSession.audioVideo.listVideoInputDevices` API that returns two devices:
- Front Camera / Device ID:`558D92...`
- Back Camera / Device ID `E1DEA7...`

![image](https://user-images.githubusercontent.com/36240708/117233312-bcad9b00-add7-11eb-8311-50e5185a9c6d.png)


However, you call `meetingSession.audioVideo.chooseVideoInputDevice` API with a device ID that starts with `483765...`.

![image](https://user-images.githubusercontent.com/36240708/117233330-c6370300-add7-11eb-8fee-ce340617702b.png)

⠀

The `chooseVideoInputDevice` API internally calls the browser's [getUserMedia](https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getUserMedia#exceptions) API to acquire a requested device. The `getUserMedia` throws  `OverconstrainedError` because you attempt to choose an unavailable device.

From the [getUserMedia doc](https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getUserMedia#exceptions):
> The specified constraints resulted in no candidate devices which met the criteria requested. The error is an object of type OverconstrainedError, and has a constraint property whose string value is the name of a constraint which was impossible to meet, and a message property containing a human-readable string explaining the problem.

⠀

Could you ensure that you pass the device ID from the `listVideoInputDevices` API?

```
const videoInputDevices = await meetingSession.audioVideo.listVideoInputDevices();
await meetingSession.audioVideo.chooseVideoInputDevice(videoInputDevices[0].deviceId);
```

**Comment by adilsaeed31** [comment]
@simmkyu Thanks for your reply, The same code is working in Mac Safari/Chrome/Firefox browsers and in Windows Chrome/Firefox browsers, also working fine in Android Tablets and Mobile Chrome browser, Only I am having an issue in iPad Safari and Chrome browser.

**Comment by adilsaeed31** [comment]
@simmkyu This issue has been fixed not sure how just rewrite some device selection piece of code, now only one issue iPad video showing the black screen in chrome browser.

**Comment by adilsaeed31** [comment]
@simmkyu Any suggestion, How can I fix this black screen issue in Mac Browsers, which not displaying iPad video feed to desktop browsers.

**Comment by simmkyu** [comment]
I tried the [Chime SDK serverless demo](https://github.com/aws/amazon-chime-sdk-js/tree/master/demos/serverless) between these two attendees.

* Attendee 1 (top left in the attached video): iPad Pro (2nd generation) + iOS 14.5.1 + Safari 14.1
* Attendee 2 (top right in the attached video): macOS Mojave + Chrome 81.0.4044.138

Both iPad and macOS attendees can see each other's video. The iPad attendee can share both "Front Camera" and "Rear Camera" without any issue. In the attached video, the bottom is the iPad Safari's inspector. At 00:19, you can the user agent information of iPad Safari.

https://user-images.githubusercontent.com/36240708/117400606-db835e80-aeb7-11eb-8c9a-375252f86133.mov

---

macOS and iOS Safari browsers have a limitation that only one tab can share a video at a time.
- https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html#my-video-disappears-in-safari-browsers-is-this-a-known-issue

Also, some mobile browsers show a black video tile when the browser is in the background mode.
- https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html#i-notice-that-if-i-turn-on-camera-and-put-the-browsers-in-background-others-in-the-meeting-will-see-black-tile-in-safarichromefirefox-in-ios-and-frozen-tile-in-chrome-in-android-is-this-a-known-issue

Could you check if you encounter one of the following issues? You can also try our [Chime SDK serverless demo](https://github.com/aws/amazon-chime-sdk-js/tree/master/demos/serverless).

**Comment by adilsaeed31** [comment]
@simmkyu I've checked already these issues and documentations, The strange thing is the V2Meeting browser demo is working fine in iPad and Mac Safari/Chrome, So how that demo is working fine, I tried to replace the same code into my project but Mac Safari/Chrome not showing iPad Safari video.

**Comment by simmkyu** [comment]
Could you provide the following information?

1. **Meeting IDs and attendee IDs:** You can provide one sample meeting ID and attendee ID who experiences the black screen issue. In the Chime server logs, we can check if the attendee has successfully enabled a video.
2. **INFO-level browser logs of both iOS and desktop users**: You can create an instance of the `ConsoleLogger` with `LogLevel.INFO`. For iOS Safari logs, please follow the instructions in [Enabling Web Inspector in the WebKit official website](https://webkit.org/web-inspector/enabling-web-inspector/).
   ```
   const logger = new ConsoleLogger('MyLogger', LogLevel.INFO);
   ```

We may use that information to determine if your client application has an issue binding a Chime SDK video tile to an HTMLVideoElement.

**Comment by vidya-mohan** [comment]
Resolving as no response
