### ISSUE TITLE
VideoTransformDevice is not taken into account when previewing video

### ISSUE THREAD

**Issue by ReneS1991** [aws/amazon-chime-sdk-js#1253]
### What are you trying to do?

To start off, I am not sure if this is something missing in the documentation, a "bug" (don't think so) or a "feature request".

I are currently adding a toggle to blur the background of your video while in a meeting. This all works perfectly fine, it nicely blurs the background of your video. So as a next step I also want to add this option to the pre-meeting device settings so the attendee can preview the background blurring before entering the meeting. But when calling the exact same code for transforming the video device and then starting the preview by calling "deviceController.startVideoPreviewForVideoInput" it does not take the DefaultVideoTransformDevice into account, it simply shows the regular video without "transformation".

### What documentation have you looked at so far?

I checked both the demo and the JS SDK documentation but cannot find anything about transforming the video for the preview specifically. Did I miss anything or is the preview simply not "accepting" a transform device. (In other words, it does nothing with it)

**Comment by simmkyu** [comment]
The `startVideoPreviewForVideoInput` API does not support the video transform device yet. In the current version (`2.8.0`), the preview API uses an underlying `MediaStream` object of a selected device. We will keep this issue open and post any updates.

**Comment by ltrung** [comment]
@ReneS1991 The preview video API `startVideoPreviewForVideoInput`  actually requires to call `chooseVideoInputDevice` first. All it does is to attach the current active video stream to a video element (https://github.com/aws/amazon-chime-sdk-js/blob/master/src/devicecontroller/DefaultDeviceController.ts#L629). 
In the meeting demo, the code path for preview and turn on video is actually the same (https://github.com/aws/amazon-chime-sdk-js/blob/master/demos/browser/app/meetingV2/meetingV2.ts#L2655).  So I think we just need to add a video filter button in the preview screen to enable it for preview.

**Comment by vidya-mohan** [comment]
Released to NPM v 2.17.0 : https://www.npmjs.com/package/amazon-chime-sdk-js
