### ISSUE TITLE
Content share connection is not snapped when main connection disconnects

### ISSUE THREAD

**Issue by rnewman** [aws/amazon-chime-sdk-js#1254]
Not sure whether this is a reproducible issue, but we saw this in today's standup:

* Connect.
* Share screen.
* Leave the meeting.

Other attendees will see the content connection until it times out.

**Comment by ltrung** [comment]
@rnewman I wasn't able to reproduce it using the above steps so I think we are missing some steps here.

**Comment by rnewman** [comment]
@simmkyu could you add more details?

**Comment by vidya-mohan** [comment]
Is this a consistent repro? Could we check if the recent build of Chrome fixes this ?

**Comment by simmkyu** [comment]
@vidya-mohan No repro. We observed the issue only once in the meeting on May 5.

**Comment by vidya-mohan** [comment]
ok i will resolve it as its not actionable - we can reactivate with more details
