### ISSUE TITLE
Meetings with Dial-In users - will the SDK be able to interact with dial-in attendees?

### ISSUE THREAD

**Issue by mark-vanr** [aws/amazon-chime-sdk-js#1257]
In our project we are adding dial-in capabilities using Chime-provisioned phone numbers with a Lambda function acting as the SIP media application, so attendees can join via telephone. Will it become possible for an SDK-based user to interact with telephony-based users through some mechanism? 

Our current use cases are -
**Mute Other**
We've implemented mute-others using data messages as suggested in issue #237 , but these messages are limited to being handled by other SDK-based observers. On the telephony side, the [Lambda SIP mute action](https://docs.aws.amazon.com/chime/latest/dg/mute-unmute.html) is documented as allowing callers to mute/unmute other telephony-attendees. I haven't found any to bridge the gap between these SDK and SIP-based actions - is this something that could be revisited to allow mute of remote attendees (including telephony-based ones) from the SDK? 

**Meeting Admittance**
We are implementing a waiting-room style feature in our application where the 'host' admits an attendee before we connect them to the meeting. We'd like to extend something similar to telephony attendees - where they have entered the needed meeting information but have not yet connected - but I don't see a way to trigger a SIP action from outside the telephone call leg. Is there any mechanism possible to fire events into the Lambda SIP app from outside the call? 
A naive suggestion might be something that could [invoke the Lambda](https://docs.aws.amazon.com/chime/latest/dg/invoking-Lambda.html) given a valid CallId, with an event containing client-specified information; the Lambda function could be written to handle such an event. In this case, the event could be admittance that would trigger the Lambda handler to run [JoinChimeMeeting](https://docs.aws.amazon.com/chime/latest/dg/join-chime-meeting.html), or rejection and a hang-up. I'm sure there may be other/better options as well.

Thanks for the consideration!

**Comment by vidya-mohan** [comment]
Thank you for the interest in the SDK @mark-vanr . This feature is not currently supported and we will keep the issue updated on the status

**Comment by immvijay** [comment]
> In our project we are adding dial-in capabilities using Chime-provisioned phone numbers with a Lambda function acting as the SIP media application, so attendees can join via telephone. Will it become possible for an SDK-based user to interact with telephony-based users through some mechanism?
> 
> Our current use cases are -
> **Mute Other**
> We've implemented mute-others using data messages as suggested in issue #237 , but these messages are limited to being handled by other SDK-based observers. On the telephony side, the [Lambda SIP mute action](https://docs.aws.amazon.com/chime/latest/dg/mute-unmute.html) is documented as allowing callers to mute/unmute other telephony-attendees. I haven't found any to bridge the gap between these SDK and SIP-based actions - is this something that could be revisited to allow mute of remote attendees (including telephony-based ones) from the SDK?
> 
> **Meeting Admittance**
> We are implementing a waiting-room style feature in our application where the 'host' admits an attendee before we connect them to the meeting. We'd like to extend something similar to telephony attendees - where they have entered the needed meeting information but have not yet connected - but I don't see a way to trigger a SIP action from outside the telephone call leg. Is there any mechanism possible to fire events into the Lambda SIP app from outside the call?
> A naive suggestion might be something that could [invoke the Lambda](https://docs.aws.amazon.com/chime/latest/dg/invoking-Lambda.html) given a valid CallId, with an event containing client-specified information; the Lambda function could be written to handle such an event. In this case, the event could be admittance that would trigger the Lambda handler to run [JoinChimeMeeting](https://docs.aws.amazon.com/chime/latest/dg/join-chime-meeting.html), or rejection and a hang-up. I'm sure there may be other/better options as well.
> 
> Thanks for the consideration!

Hi @mark-vanr , The new SDK API UpdateSipMediaApplicationCall will allow you to trigger a Lambda function at any time while a call is active, replacing the current actions with new actions returned by the invocation. Please download the latest version of the SDK to try this out.  For further details on the API, please refer to the AWS documentation : https://docs.aws.amazon.com/chime/latest/APIReference/API_UpdateSipMediaApplicationCall.html
https://docs.aws.amazon.com/chime/latest/dg/update-sip-call.html

**Comment by mark-vanr** [comment]
Thanks @immvijay I've checked it out and this is exactly what I needed!

**Comment by vidya-mohan** [comment]
thanks @mark-vanr for the confirmation. I am resolving the issue after your acknowledgement
