### ISSUE TITLE
AudioVideoFacade.startVideoPreviewForVideoInput does not return a promise

### ISSUE THREAD

**Issue by jrowny** [aws/amazon-chime-sdk-js#1260]
**Describe the bug**
The startVidePreviewForVideoInput does not return a promise and we have no way to know about or react to failures. IMO, it should bubble the exceptions found here: https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getUserMedia

Because you're currently exposing as a void, returning a promise shouldn't be a breaking change.

**Platform**
 - OS: any
 - Browser: any
 - Browser Version: any

**Comment by vidya-mohan** [comment]
Thank you for cutting the issue calling out the limitation @jrowny!

**Comment by ltrung** [comment]
@jrowny PR #1236 has fixed `startVideoPreviewForVideoInput` to no longer call `getUserMedia` which should be available in the next npm push. Thus, you only have to handle `getUserMedia` failure in `chooseVideoInput`.
