### ISSUE TITLE
Intermittent Timeouts for API createAttendee

### ISSUE THREAD

**Issue by peili** [aws/amazon-chime-sdk-js#1263]
We're experiencing intermittent timeouts for CreateAttendee API, increased number of such timeouts today on 05/06/2021.

https://docs.aws.amazon.com/chime/latest/APIReference/API_CreateAttendee.html

**Comment by ashleyqu** [comment]
Do you mind provide the meetingId and the exact meeting time so I can dive deep?

**Comment by simmkyu** [comment]
We did not have any significant outage on 05/06/2021.

@ashleyqu is from the Amazon Chime service team that manages the Chime APIs available in AWS SDK, AWS CLI, and the REST API. If you provide Ashley with the Chime SDK meeting ID and the brief timeline, she can provide guidance on timeouts.

**Comment by peili** [comment]
@ashleyqu 
We haven't experienced any timeouts yesterday. Today we're seeing timeouts again.

(GMT+2) 3:32:09.411 AM meetingId 9c16d85f-ba1c-4571-ac50-58b90f77daee
(GMT+2) 3:32:19.999 AM meetingId 9c16d85f-ba1c-4571-ac50-58b90f77daee
(GMT+2) 3:49:36.168 AM meetingId 9c16d85f-ba1c-4571-ac50-58b90f77daee
(GMT+2) 4:08:16.252 AM meetingId 74b6257b-4516-41c4-9fe6-90312f51e237

**Comment by peili** [comment]
Also adding some charts where you can see the impact in execution time using the AWS Chime API. 
![image](https://user-images.githubusercontent.com/1823148/117806028-0b38ba80-b25a-11eb-8766-fde71ba9afc1.png)
![image](https://user-images.githubusercontent.com/1823148/117806493-b3e71a00-b25a-11eb-93d8-cd09adc243bc.png)

**Comment by peili** [comment]
More timeouts we're seeing:
May 12, (GMT+2) 8:31:58.483 PM meetingId 2bbe99a7-1b69-4245-ad6d-5cee1aae5418
May 12, (GMT+2) 2:47:28.409 PM meetingId ea4d9915-9580-45f6-9b68-871c62b7e95a

**Comment by aws-geoff** [comment]
Hi @peili,

Thanks for creating this issue.  From what AWS region is your app making these CreateAttendee API calls?

Thanks,
Geoff

**Comment by jing-chen1** [comment]
Closing the issue for now. Feel free to reopen it if you still have problems.
