### ISSUE TITLE
Will Amazon Chime SDK supports android and IOS with Ionic Framework?

### ISSUE THREAD

**Issue by sowjanyanarra** [aws/amazon-chime-sdk-js#127]
**Amazon Chime SDK Integration with Ionic Framework**

**Platform**
 - OS: Android Version 9

**Bug Description**

We are trying to integrate the Amazon Chime SDK with Ionic framework(using Angular) in Android device. We were able to join a meeting from  browser and ionic integrated android device, And able to share audio/video from browser application to android device.We are getting video/audio preview in device shared by browser application. 

But, the issue is we are unable to access the device's inbuilt audio/video hardware components permission and hence we are not getting the preview in desktop. 

We even tried to access the device's audio/video components by writing the following lines in **AndroidManifest.xml** and have given app-level permissions in device to access **Camera** and **Microphone.** 

` <uses-permission android:name="android.permission.CAMERA" />`        
` <uses-permission android:name="android.permission.RECORD_AUDIO" />`              

When we try to toggle camera/microphone we are getting an error in console and same is attached below.

**We would like to know that, is Amazon Chime SDK supports to integrate with Mobile applications?
If yes please let us know how we can solve the below issue.**

**Screenshots**
![image](https://user-images.githubusercontent.com/53859080/74521588-9932d200-4f3f-11ea-98fa-dca773844bc7.png)

**Comment by vidya-mohan** [comment]
Hello @sowjanyanarra,

Thank you for the interested in our SDK. Currently only the following browsers are supported for applications created using the Amazon Chime SDK:

Mozilla Firefox (version 60 and later), for macOS and Windows
Google Chrome (version 78 and later), for macOS and Windows
Chromium-based Edge (version 79 and later), for Windows
Chromium-based Electron (Electron 7 and later, with Chromium version 78 and later)
Safari (version 12 and later, audio and video only, no screen sharing)
Opera (version 66 and later)
 
Please watch out [Amazon Chime Developer Guide ]([https://docs.aws.amazon.com/chime/latest/dg/meetings-sdk.html#mtg-browsers](https://docs.aws.amazon.com/chime/latest/dg/meetings-sdk.html#mtg-browsers)) where we will post any updates on browser support.

**Comment by sidharth-sid** [comment]
Hi @vidya-mohan @sowjanyanarra 
Our team was interested in the amazon chime video meeting services and wanted to use it in our application.
We have a hybrid application where we have the web app in angular js and the android and Ios builds are created using the ionic-Cordova framework. We were able to see the demos in the web but were worried about Chime SDK support in the ionic framework.

Can you give a brief about the current available support?
Saw a few other Github issues related to this.
https://github.com/aws-samples/amazon-chime-react-native-demo/issues

@codeslinger @weichenhamzn

**Comment by hiteshranaut** [comment]
Hey we have our android and ios applicaiton using ionic and right now using different solution for video calling. but our clients want to move to chime. is it possible. I check there is no plugin for cordova right now.

Question is can we implement Chime in ionic app?

**Comment by ajaysankarnair** [comment]
@hiteshranaut  which ionic whats the good way to integrate video call

**Comment by hitesh-encora** [comment]
@ajaysankarnair I was not able to found SDK working for cordova for chime.

**Comment by idb-umangtyagi** [comment]
can we use aws chime for meeting in ionic angular mobile application?
