### ISSUE TITLE
share screen is visible on both side (attendee as well as host) and sharing My meetings active screen it is generating infinite windows,

### ISSUE THREAD

**Issue by E5920** [aws/amazon-chime-sdk-js#1282]
1:-  i am facing unexpected behaviour, my requirement is share screen is visible only attendee side not host  :- 

  async startContentShare(tileState: VideoTileState){
    console.log('Screen share started');
    await this.meeting.meetingSession.audioVideo.startContentShare();
  }

  
  async contentShareDidStop(){
    console.log('Content share stopped');   
    await this.meeting.meetingSession.audioVideo.stopContentShare();
  }

  videoTileDidUpdate(tileState: VideoTileState){
    console.log("Sudhanshu: inside videoTileDidUpdate"+tileState);
    console.log(tileState)
    // Ignore a tile without attendee ID and a content/screen share.
    
    if (!tileState.boundAttendeeId || !tileState.tileId ) {
      return;
    }

2:- i am facing issue, When we are sharing My meetings active screen it is generating infinite windows, Please check below image  :- 
![image](https://user-images.githubusercontent.com/80304004/117953415-a18cdf00-b333-11eb-91a9-88e70734935e.png)

thanks,
rajat.

**Comment by devalevenkatesh** [comment]
Hello, thanks for your interest in the library.

1. To achieve the first case you can simply follow the Use case 18 under [Screen share section](https://github.com/aws/amazon-chime-sdk-js#screen-and-content-share) in our README.

Basically, you can to check whether the content attendeeId is matching your local attendeeId. If so, then do not bind the tile to the video element.

```js
videoTileDidUpdate(tileState: VideoTileState): void {
  // Get your local attendeeId from your meeting session.
  const yourAttendeeId = meetingSession.configuration.credentials.attendeeId;
  if (
       !tileState.boundAttendeeId ||
       (yourAttendeeId === new DefaultModality(tileState.boundAttendeeId).base() && tileState.isContent)
  )
  {
     // Do nothing just return.
     return;
  }
}
```

2. I could find the infinite screen behavior on the [WebRTC's sample](https://webrtc.github.io/samples/src/content/getusermedia/getdisplaymedia/) as well. JS SDK is based off on WebRTC and hence we do not explicitly do anything here.

Please let us know if have more questions.

**Comment by devalevenkatesh** [comment]
Closing this issue as no further action is needed. Please feel free to re-open or create another if you need more help.

**Comment by E5920** [comment]
thanks for the solutions.
