### ISSUE TITLE
implementation of group video call

### ISSUE THREAD

**Issue by E5920** [aws/amazon-chime-sdk-js#1288]
I am facing issue of implementation of group video call feature means new tileid is coming then new tileid replace all the existing tile id(other screen) in amazon-chime so, that's why new video is not visible on vacant tile rather, new video is visible ocuupied tile.

Note :- infinite attendee join video call simultaneously.

videoTileDidUpdate(tileState: VideoTileState){
    console.log(tileState)
  
    if (!tileState.boundAttendeeId || !tileState.tileId ) {
      return;
    }
    var videoElement = tileState.localTile? 'session-local-video' : 'session-remote-video';

    this.meeting.meetingSession.audioVideo
      .bindVideoElement(tileState.tileId,this.domElement(videoElement));

regards,
Rajat.

**Comment by devalevenkatesh** [comment]
Hello Rajat,

You can check Use case 16 under [Video](https://github.com/aws/amazon-chime-sdk-js#video) in our README. It explains how you can achieve that.

Also, as recommended in #1289 can you check the JS SDK demo once which implements your use cases.

Please feel free to re-open this issue if you face any further issues after going through the documentation we have as well as the JS SDK demo.
