### ISSUE TITLE
implementation of toggle in share screen on amazon-chime

### ISSUE THREAD

**Issue by E5920** [aws/amazon-chime-sdk-js#1289]
i am facing issue, implementation of toggle in share screen means if my screen is shared then click the share screen button have seen stop sharing button or disabled share button. how to use use " stopContentShare " .

  public async toggleShareScreen() {
      await this.meeting.meetingSession.audioVideo.startContentShareFromScreenCapture();
  }

thanks,
Rajat.

**Comment by devalevenkatesh** [comment]
Hello Rajat,

Request you to check our JS SDK meeting [demo app](https://github.com/aws/amazon-chime-sdk-js/tree/master/demos/browser) which has a similar functionality as your use case.

We recommend you to go through the demo once. While running the app please follow the pre-requisite and run the browser meeting demo locally as instructed [here](https://github.com/aws/amazon-chime-sdk-js/tree/3acb963bb9eb8fdd84d82143fcd8bce0b366f212/demos/browser#running-the-browser-demos-with-a-local-server)

In the demo on the button click we start the content share and then stop it if already enabled, it has check on whether the button state is enabled or disabled.
https://github.com/aws/amazon-chime-sdk-js/blob/3acb963bb9eb8fdd84d82143fcd8bce0b366f212/demos/browser/app/meetingV2/meetingV2.ts#L815-L824

The [`contentShareStart`](https://github.com/aws/amazon-chime-sdk-js/blob/master/demos/browser/app/meetingV2/meetingV2.ts#L2359) function calls the `startContentShare` API and toggles the button [here](https://github.com/aws/amazon-chime-sdk-js/blob/master/demos/browser/app/meetingV2/meetingV2.ts#L2388). Similarly, the `contentShareStop` function calls the [`stopContentShare`](https://github.com/aws/amazon-chime-sdk-js/blob/master/demos/browser/app/meetingV2/meetingV2.ts#L2392) API and toggles the button state.

We also have a [guide](https://github.com/aws/amazon-chime-sdk-js/blob/3acb963bb9eb8fdd84d82143fcd8bce0b366f212/guides/02_Content_Share.md) on using the content share APIs which will be useful to learn more.

**Comment by devalevenkatesh** [comment]
Please feel free to re-open and create issue if you have more questions.
