### ISSUE TITLE
List disconnected or still connected attendees using SDK

### ISSUE THREAD

**Issue by paul365** [aws/amazon-chime-sdk-js#1294]
### What are you trying to do?
I'm trying to get disconnected attendees using the SDK. Is this possible? Running list-attendees just shows attendee ids without details whether they are still on the meeting or not. Or at least be  able to get how many attendees are still connected to the meeting.

### What documentation have you looked at so far?

README.md, Amazon Chime SDK Developer Guide, etc.
https://docs.amazonaws.cn/AWSJavaScriptSDK/latest/AWS/Chime.html

**Comment by devalevenkatesh** [comment]
We currently do not have API for disconnected attendees. But, you can try using Amazon EventBridge and listen to attendee drop events and then maintain the map of the same.

You can check more on the link below:
https://docs.aws.amazon.com/chime/latest/ag/automating-chime-with-cloudwatch-events.html

Amazon Chime SDK attendee specific events are detailed under "Automating the Amazon Chime SDK with EventBridge" section.

Our JS SDK demo implements the roster functionality which keeps the current attendees in an live meeting and shows in a table. You can check and implement similar functionality. Check Use case 23, 24 under [Attendees](https://github.com/aws/amazon-chime-sdk-js#attendees) in our README.

[JS SDK Demo Link](https://github.com/aws/amazon-chime-sdk-js/tree/master/demos/browser)

Please feel free to re-open this issue or create new one if you have more questions.
