### ISSUE TITLE
When unmuting a participant, the user is not unmuted and participant appears to be removed from realtimeParticipants

### ISSUE THREAD

**Issue by caydgreen** [aws/amazon-chime-sdk-js#1303]
**Important:** Please attach INFO-level logs with timestamps to the report from *before* the session started up until the point at which the unexpected behavior occurred. For multi-participant calls, attach a log file for each participant if possible.

**Meeting and attendee IDs:**
***Situation #1***
Meeting ID: 5fc80a0c2e984e0001ad2c51
Attendee ID: d31e7a29-2f4a-2b7a-9b20-acdaa193613a

***Situation #2***
Meeting ID: 5fc80bcc2e984e0001ad2c77
Attendee ID: b0541eb6-e527-d45a-e34e-145623a255ce

**Timeline**
Outline the main actions the user performed and when:
Attempted to unmute (fail)
Attempted to mute
Attempted to unmute (fail)
Participant removed from attendee list and tile state map
send chat (success)
send chat (success)

**Describe the bug**
***Situation #1***
When attempting to unmute, the user remained muted to all other attendees just before May 19, 2021 09:02:18, then the user noticed all the participant videos were flickering, then the user sent a chat May 19, 2021 09:02:18, all users were able to see the chat message, then the user noticed they were not showing up in the participants list and their video was missing, then the user received the ConnectionDidSuggestStopVideo callback at May 19, 2021 09:02:41.  
Error in console: [​ 2021-05-19T16:04:17.653Z ] Uncaught TypeError: Cannot read property 'srcObject' of null
    at y.stopVideoPreviewForVideoInput (774.48c17ad….bundle.js:2)
    at t.default.stopVideoPreviewForVideoInput (774.48c17ad….bundle.js:2)
    at Object.audioVideoDidStart (live-stream.48c17ad7…4686c18.bundle.js:1)
    at 774.48c17ad….bundle.js:2
    at n.map (774.48c17ad….bundle.js:2)
    at 774.48c17ad….bundle.js:2
    at 774.48c17ad….bundle.js:2
Then the participant left the meeting and rejoined, then everything was working as expected.

***Situation #2***
When attempting to unmute, the user remained muted to all other attendees, then the user received the ConnectionDidSuggestStopVideo callback at May 19, 2021 11:34:41, then the user was removed from the realtimeParticipantsList, then they were able to send chat messages with the data message feature and the other participants were able to see. 

Error in console: [​ 2021-05-19T18:35:24.959Z ] Uncaught TypeError: Cannot read property 'srcObject' of null
    at y.stopVideoPreviewForVideoInput (774.48c17ad….bundle.js:2)
    at t.default.stopVideoPreviewForVideoInput (774.48c17ad….bundle.js:2)
    at Object.audioVideoDidStart (live-stream.48c17ad7…4686c18.bundle.js:1)
    at 774.48c17ad….bundle.js:2
    at n.map (774.48c17ad….bundle.js:2)
    at 774.48c17ad….bundle.js:2
    at 774.48c17ad….bundle.js:2
Other participant in the meeting noticed this log around the time the muted participant video disappeared (attendee b0541eb6-e527-d45a-e34e-145623a255ce): ChimeMeetingLogs - Ignoring video element binding for unknown tile id 13. Then the participant left the meeting and rejoined, then everything was working as expected.

**Platform**

Situation 1
 - OS: Mac 
 - Browser:  Chrome
 - Browser Version:  90

Situation 2
 - OS: Mac 
 - Browser:  Chrome
 - Browser Version:  89

**Comment by michhyun1** [comment]
Hi @caydgreen, thanks for using the Chime SDK for Javascript! 

So I'm assuming you're working on your own version of an app - using the SDK. It looks like you might be getting this 'srcObject' of null log because you are calling stopVideoPreviewForVideoInput in the audioVideoDidStart callback. If you look at [where we call stopVideoPreviewForVideoInput](https://github.com/aws/amazon-chime-sdk-js/blob/master/demos/browser/app/meetingV2/meetingV2.ts#L699-L701), we still have reference to the video preview element on the dom - I think you may be switching pages and then calling stopVideoPreview API - when the video preview element is no longer on the dom because you switched pages. Let me know if that is true or not. 

As for the mute/unmute not working - that seems to be a different issue. [This is where we call the callback](https://github.com/aws/amazon-chime-sdk-js/blob/2a43d4890f9d85a0b004cd32f6dc7387903d3255/src/task/MonitorTask.ts#L292)  for ConnectionDidSuggestStopVideo. Is this reproduceable 100% of the time?

**Comment by caydgreen** [comment]
It is not happening 100% of the time, and only recently started happening after our upgrade to the latest Chime SDK (to leverage downlink Policy). I don't believe the user is unable to unmute due to the ConnectionDidSuggestStopVideo, but that message tends to pop up as the user is being booted from the meeting.

**Comment by michhyun1** [comment]
@caydgreen Could you supply us with more complete browser logs from the time the use joins to when they are dropped? That will help us determine what is happening.

**Comment by caydgreen** [comment]
[logFileNoUnmute.log](https://github.com/aws/amazon-chime-sdk-js/files/6541359/logFileNoUnmute.log)
Here you go!

**Comment by caydgreen** [comment]
Here is a second one, it happened to me today.  I stopped the logs right as the problem occurred 
[noMuteDropped.log](https://github.com/aws/amazon-chime-sdk-js/files/6542048/noMuteDropped.log)

**Comment by michhyun1** [comment]
@caydgreen thanks for those logs- it seems like those are your application logs, but its missing some of the SDK logs. We usually suggest that you follow this step to get the SDK logs in your console or cloudwatch: https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html#how-can-i-get-amazon-chime-sdk-logs-for-debugging

Could you also specify what SDK version you were using prior to this issue? And what is the version you switched to?

 Would you mind creating a ticket through aws support?

**Comment by vidya-mohan** [comment]
Closing as no response
