### ISSUE TITLE
facing issue unbind videoElement with tileId

### ISSUE THREAD

**Issue by E5920** [aws/amazon-chime-sdk-js#1310]
i am try to unbind videoElement with tileId but facing issue so, my requirement is firstly videoElement is unbind with old tileId then same videoElement is bind with new tileId.

temp: VideoTileState;

public next(){
    var videoElement = this.temp.localTile? 'session-local-video' : 'session-remote-video';
    var videoElNext = this.domElement(videoElement);

    // unbind videoElement with old tileId
    this.meeting.meetingSession.audioVideo.unbindVideoElement(this.temp.tileId);
    // bind videoElement with new tileId
    this.meeting.meetingSession.audioVideo.bindVideoElement(this.temp.tileId, videoElNext);
  }

regards,
Rajat Kesharwani.

**Comment by michhyun1** [comment]
Hey @E5920, can you verify if the new tile that you are trying to bind to the videoElement has an active video stream attached to it? 

Also, you may want to remove the srcObject of the videoElement after you call unbindVideoElement. Calling unbindVideoElement will remove the videoElement reference in the tile's state, but it wont remove the active stream from the video element. This is something we plan to fix.

**Comment by E5920** [comment]
yes, new tile  bind to the videoElement  has an active video stream.

**Comment by E5920** [comment]
thanks for your solution,
i was going with your solution but  facing issue that, unbind videoElement with old tileId then same videElement bind with old tileId that's why videoElement is not binding with new tileId.
please check my below code & suggest.

public shift_next(){
    var videoElement = this.temp.localTile? 'session-local-video' : 'session-remote-video';
    var videoEl = this.group1[this.temp.boundAttendeeId].videoElement;
    var videoElNext = this.domElement(videoElement);
    this.meeting.meetingSession.audioVideo
      .unbindVideoElement(this.temp.tileId);
    this.meeting.meetingSession.audioVideo
      .bindVideoElement(this.temp.tileId, videoElNext);
    videoEl.srcObject = null;
  }

regards,
Rajat Kesharwani

**Comment by gsudhanshu** [comment]
@ltrung Kindly help.

videoEl.srcObject = null; is not working properly and the oldtileId is getting reattached to video element

**Comment by michhyun1** [comment]
@gsudhanshu, you should be able to unbind the video and then re-bind the tileId to a new video element. 

You may want to console.log(temp) after you do the unbindVideoElement, and verify that the TileState no longer has a reference to the VideoElement. 

When you call bindVideoElement, please verify that the videoElNext is a different videoElement than the one you just un-binded from, otherwise, you will see the exact behavior you just mentioned. 

Also, you should call videoEl.srcObject = null immediately after you unbindVideoElement, not after you bind Video Element.

**Comment by michhyun1** [comment]
@gsudhanshu we use the tileId to get the tileState here: https://github.com/aws/amazon-chime-sdk-js/blob/2e2c7e36631d898b925e6e341c28f72dafcfa8d6/src/videotilecontroller/DefaultVideoTileController.ts#L35

**Comment by michhyun1** [comment]
@gsudhanshu Is your issue resolved now?

**Comment by gsudhanshu** [comment]
@michhyun1 

I think it is
@E5920 Rajat, pls confirm

**Comment by michhyun1** [comment]
@gsudhanshu i'll go ahead and close this first, @E5920 if there are any other issues, please reopen. I'm glad we were able to resolve this for you!
