### ISSUE TITLE
Attendee dropped ("eventType": "chime:AttendeeDropped”) timing parameters 

### ISSUE THREAD

**Issue by albrich-me** [aws/amazon-chime-sdk-js#1314]
### What are you trying to do?

Need to know what causes the "eventType": "chime:AttendeeDropped”.  Determine how long a person will be offline before it’s reported.  Determine if after that event the SDK might try to reconnect. 

### How can the documentation be improved to help your use case?

Provide guidance for the timing parameters and retry logic (if any) around chime:AttendeeDropped event.

**Comment by michhyun1** [comment]
@albrich-me Thanks for bringing this up - we've marked this issue with a Documentation label and we'll try to address this in our documentation. For now, you might want to take a look at the [MeetingSessionConfiguration.ts](https://github.com/aws/amazon-chime-sdk-js/blob/master/src/meetingsession/MeetingSessionConfiguration.ts#L40) file, that's where we have some default timeout values, with comments on what the timeout values indicate.

**Comment by simmkyu** [comment]
The `chime:AttendeeDropped` event occurs as soon as the Chime SDK attendee is dropped from the meeting. Poor or no internet connection causes the dropped event.

The Chime SDK for JavaScript automatically retries the connection when the SDK detects the following unstable connectivity event:
- No audio packets (WebRTC)
- Bad audio delay (WebRTC)
- No pong reply (WebSocket)

Feel free to reopen the issue if you have additional questions.
