### ISSUE TITLE
facing issue bind videoElement with empty remote tile.

### ISSUE THREAD

**Issue by RajatKesharwani1975** [aws/amazon-chime-sdk-js#1315]
@michhyun1, i am trying to bind videoElement with empty remote tile but couldn't. My requirement is suppose 3 users are present but i have 1 remote tile & 1 local tile then 1st user have turned off there camera it's means 2nd user remote tile is empty then 3rd user video element bind with empty tile which are present in 2nd user screen. in this case 3rd user video element is not binding with empty tile which are present in 2nd user screen.

 group1 : {[attendeeId : string]: {tileId:number, videoElement:HTMLVideoElement}} = {}; 

  audioVideoDidStop() {
    console.log(" inside audioVideoDidStop");
    this.meeting.meetingSession.audioVideo.stopLocalVideoTile();
    //this.meeting.dropAttendee();
    this.modalService.open('meeting-end-modal');
  }

  videoTileWasRemoved(tileId :number) {
this.group1[tileState.boundAttendeeId] =  {"tileId" : tileState.tileId, "videoElement" : null};
  }

regards,
rajat.

**Comment by michhyun1** [comment]
@RajatKesharwani1975 the bindVideoElement API simply binds a videoStream to a video element on the DOM. It does not send that video stream to another client.

Can you please elaborate on your use case a bit? I'm a bit confused by the way you've explained it. 

Normally you would get the tileId of a TileState that has an active stream attached to it, and then call bindVideoElement using that tileId and a reference to a videoElement on the DOM and you should see that the videoStream plays on the videoElement. However, if you want a video stream to be sent to other clients, you'll need to call startLocalVideoTile.

**Comment by RajatKesharwani1975** [comment]
@michhyun1, thanks ,i have done above solution to bindVideoElement with tile id but in this case some requirement is different   like. "x" & "y" user are present & both share a video (only 1 remote & 1 local tile is present) if "z" user is enter with video then "y" user have turned off there camera it means "x" user remote tile is blank so, ideally "z" user videoElement bind with "x" user remote tile(means "z" user videElement bind with "x" user remote tile) but in my case this is not happen. pl check my code and function which i have use is this corrent or not kindly help me.

temp: VideoTileState;
  videoTileWasRemoved() {
    var videoElement = this.temp.localTile? 'session-local-video' : 'session-remote-video';
    this.meeting.meetingSession.audioVideo
      .bindVideoElement(this.temp.tileId,  this.domElement(videoElement));
  }

thanks 
rajat

**Comment by michhyun1** [comment]
Its hard to say without seeing your code - but you need to verify if you actually have an active video stream on that video tileState before you bindVideoElement. Can you do a `console.log(this.temp)` before and after, and see if the boundVideoStream is attached? 

After you call bindVideoElement, print out the tileState of the videoTiles that you expected to be bound to the videoElement, and check the boundVideoElement property of the TileState. Alternatively, you can set breakpoints and check the tileState.

**Comment by RajatKesharwani1975** [comment]
issue resolved

**Comment by michhyun1** [comment]
@RajatKesharwani1975 great to hear! Thanks for using the Chime SDK for Javascript
