### ISSUE TITLE
Need to migrate from legacy getStats() to standard getStats() in DefaultStatsController

### ISSUE THREAD

**Issue by ldai1** [aws/amazon-chime-sdk-js#1320]
**Important:** Please attach INFO-level logs with timestamps to the report from *before* the session started up until the point at which the unexpected behavior occurred. For multi-participant calls, attach a log file for each participant if possible.

**Describe the bug**
Currently, the JS SDK StatsCollector collects webRTC legacy getStats() API for Chromium based browsers. There are three reasons to migrate to standard getStats() API:

1. Simulcast is not supported by legacy stats. When we enable simulcast for chromium based browsers, local attendee should expect multiple SSRCs returned for their upstream video metrics. But with this legacy stats, only single upstream is returned.
2. Legacy stats will be eventually deprecated. It is recommended by Google to migrate to using standard stats before its deprecation. Official doc: https://docs.google.com/document/d/1z-D4SngG36WPiMuRvWeTMN7mWQXrf1XKZwVl3Nf1BIE/edit
3. To simplify our code base as well as avoid confusion for developers (See https://github.com/aws/amazon-chime-sdk-js/blob/421aced210d5ccdf6994e42b9e02ec7e83c9def8/demos/browser/app/meetingV2/meetingV2.ts#L987 where developers have to get different bandwidth metric name for the same bandwidth metric)

**Comment by xuesichao** [comment]
Close the issue as the fix will be release in v3.0.0-beta.1
