### ISSUE TITLE
Use of eventDidReceive - meetingEnded event not triggering

### ISSUE THREAD

**Issue by AlexMCarv** [aws/amazon-chime-sdk-js#1321]
### What are you trying to do?
I am trying to add an observer for eventDidReceive and log some specific events. I am successful in logging the meetingStartSucceeded,  audioInputFailed and videoInputFailed with some manual testing, but for some reason the meetingEnded event is never triggered. I tried the End Meeting for all, Leaving the meeting and disconnecting the internet, but I can seem to make it work.

What would be the conditions to make the meetingEnded event to be published and observed?

This is how I have my observer setup. It is being used as a hook.

```
const useEventObserver = () => {
  const meetingManager = useMeetingManager();
  const audioVideo = meetingManager?.audioVideo;

  useEffect(() => {
    const observer = {
      eventDidReceive: (name, attributes) => {
        const { meetingHistory, ...otherAttributes } = attributes;
        switch (name) {
          case 'meetingStartSucceeded':
          case 'meetingEnded':
            console.log(`${name} with attributes: ${JSON.stringify(otherAttributes)}`);
            break;
          case 'audioInputFailed':
          case 'videoInputFailed':
          case 'meetingStartFailed':
          case 'meetingFailed':
            console.log(`${name} with attributes: ${JSON.stringify(otherAttributes)}`);
            break;
          default:
            break;
        }
      }
    };
    audioVideo?.addObserver(observer);
    return () => {
      audioVideo?.removeObserver(observer);
    };
  }, [audioVideo]);
};
```

### What documentation have you looked at so far?
https://aws.github.io/amazon-chime-sdk-js/modules/meetingevents.html
https://aws.amazon.com/blogs/business-productivity/monitoring-and-troubleshooting-with-amazon-chime-sdk-meeting-events/

**Comment by ldai1** [comment]
Hi,

Thanks for reporting the issue with detailed code example. Whenever you receive `AudioVideoObserver.audioVideoDidStop`, the SDK raises the `meetingEnded` event. https://github.com/aws/amazon-chime-sdk-js/blob/3196df1e0bb2db71389e01e36123492da7c3c754/src/audiovideocontroller/DefaultAudioVideoController.ts#L840-L882. What I could recommend is check on side to see if you have ever received `audioVideoDidStop`. If yes, then that is the reason why you don't see an meetingEnd event logged. Hope this is helpful for your debugging.

**Comment by AlexMCarv** [comment]
I did the following approach, and it worked. I can successfully log the MeetingEnded event, but I am not happy with it because I had to remove the cleanup from the hook. Which means that if audioVideo changes, MeetingEventObserver is going to re-render and the observer is going to be added in duplicate.
The MyApp component here is responsible for calling the meetingManager.join() and initiating the session.

```
import React from 'react';
import { MeetingProvider } from 'amazon-chime-sdk-component-library-react';

const App = () => (
  <MeetingProvider>
    <MyApp />
    <MeetingEventObserver />
  </MeetingProvider>
);

const MeetingEventObserver = ({ logger }) => {
  const audioVideo = useAudioVideo();

  useEffect(() => {
    const observer = {
      eventDidReceive: (name, attributes) => {
        const { meetingHistory, ...otherAttributes } = attributes;
        switch (name) {
          case 'meetingStartSucceeded':
          case 'meetingEnded':
            logger.info(`${name} with attributes: ${JSON.stringify(otherAttributes)}`);
            break;
          case 'audioInputFailed':
          case 'videoInputFailed':
          case 'meetingStartFailed':
          case 'meetingFailed':
            logger.error(`${name} with attributes: ${JSON.stringify(otherAttributes)}`);
            break;
          default:
            break;
        }
      }
    };
    audioVideo?.addObserver(observer);
  }, [audioVideo, logger]);

  return <></>;
};
```

Adding the cleanup to the effect in this scenario will remove the observer before it has a chance to run the eventDidReceive.
```
return () => {
      audioVideo?.removeObserver(observer);
    };
```

**Comment by simmkyu** [comment]
> Which means that if audioVideo changes, MeetingEventObserver is going to re-render and the observer is going to be added in duplicate.

How about removing and re-adding an observer only when the `audioVideo` becomes available?

```js
import React from 'react';
import { MeetingProvider } from 'amazon-chime-sdk-component-library-react';

const App = () => (
  <MeetingProvider>
    <MyApp />
    <MeetingEventObserver />
  </MeetingProvider>
);

const MeetingEventObserver = ({ logger }) => {
  const audioVideo = useAudioVideo();
  const observer = {
    eventDidReceive: (name, attributes) => {
      console.warn(`MeetingEventObserver::${name}::`, attributes);
    }
  };

  useEffect(() => { 
    if (!audioVideo) {
      return;
    }

    // Remove the observer in case the "audioVideo" refers to the previous object.
    audioVideo?.removeObserver(observer);
    audioVideo?.addObserver(observer);
  }, [audioVideo]);

  return <></>;
};
```

**Comment by AlexMCarv** [comment]
That is an interesting approach, but I actually realized something. Rather than use the useAudioVideo hook, it would be best to use the useMeetingManager, and access the audioVideo from there. Just tested the following approach and I am consistently being able to log all events I can manually trigger. This way the cleanup effect only runs when the meetingManager changes, which fixes the issue with the MeetingEnded.

```
import React from 'react';
import { MeetingProvider, useMeetingManager } from 'amazon-chime-sdk-component-library-react';

const App = () => (
  <MeetingProvider>
    <MyApp />
    <MeetingEventObserver />
  </MeetingProvider>
);

const MeetingEventObserver = ({ logger }) => {
  const meetingManager = useMeetingManager();

  useEffect(() => {
    const audioVideo = meetingManager?.audioVideo;
    const observer = {
      eventDidReceive: (name, attributes) => {
        const { meetingHistory, ...otherAttributes } = attributes;
        switch (name) {
          case 'meetingStartSucceeded':
          case 'meetingEnded':
            logger.info(`${name} with attributes: ${JSON.stringify(otherAttributes)}`);
            break;
          case 'audioInputFailed':
          case 'videoInputFailed':
          case 'meetingStartFailed':
          case 'meetingFailed':
            logger.error(`${name} with attributes: ${JSON.stringify(otherAttributes)}`);
            break;
          default:
            break;
        }
      }
    };
    audioVideo?.addObserver(observer);
    return () => {
      audioVideo?.removeObserver(observer);
    };
  }, [meetingManager, logger]);

  return null;
```

**Comment by simmkyu** [comment]
Yeah, the `useAudioVideo()` the Chime React Component Library returns the `null` whenever the attendee leaves a meeting.

Please reopen if you have any additional questions. We will keep this issue informed when the Chime SDK team adds a meeting-event observer in the Chime React Component Library.
