### ISSUE TITLE
prebuild scripts/conditional-install in browser demo for windows.

### ISSUE THREAD

**Issue by Critchleyb** [aws/amazon-chime-sdk-js#1323]
### What are you trying to do?
`npm run build` on windows for local testing and development

### How can the documentation be improved to help your use case?
The build fails at the prebuild stage as it tries to call scripts/conditional-install. The file doesn't have an extension but I assume this is a ruby script? Do I need to take additional steps to get this working on windows or is something possibly wrong with my local dev environment?

### What documentation have you looked at so far?

README.md

**Comment by Critchleyb** [comment]
Error message from the console below:

PS C:\amazon-chime-sdk-js\demos\browser> npm run build

> amazon-chime-sdk-js-demos@0.1.0 build C:\Users\bcrit\Documents\Code\amazon-chime-sdk-js\demos\browser
> npm run deps && npm install && tsc && npm run build:fast


> amazon-chime-sdk-js-demos@0.1.0 deps C:\Users\bcrit\Documents\Code\amazon-chime-sdk-js\demos\browser
> cd ../.. && npm run build


> amazon-chime-sdk-js@2.9.0 prebuild C:\Users\bcrit\Documents\Code\amazon-chime-sdk-js
> script/conditional-install

'script' is not recognized as an internal or external command,
operable program or batch file.

**Comment by Critchleyb** [comment]
Confirmed that this was an issue with Ruby not being installed on my machine. Installed and edited the prebuild script in package.json in the root directory from:

`"prebuild": "script/conditional-install",`
to
`"prebuild": "ruby script/conditional-install",`

**Comment by michhyun1** [comment]
@Critchleyb yes, thats a ruby script. It looks like this is resolved for you so I'll go ahead and close this one out. Feel free to reopen if need be.
