### ISSUE TITLE
Error adding meeting observer. TypeError: Converting circular structure to JSON

### ISSUE THREAD

**Issue by paramonych** [aws/amazon-chime-sdk-js#1332]
**Logs before error:** 
2021-05-30T07:53:15.681Z [INFO] ChimeMeetingLogs - DefaultDeviceController video dimension 960 x 540
2021-05-30T07:53:15.683Z [INFO] ChimeMeetingLogs - Supported Constraints in this browser {"aspectRatio":true,"autoGainControl":true,"brightness":true,"channelCount":true,"colorTemperature":true,"contrast":true,"deviceId":true,"echoCancellation":true,"exposureCompensation":true,"exposureMode":true,"exposureTime":true,"facingMode":true,"focusDistance":true,"focusMode":true,"frameRate":true,"groupId":true,"height":true,"iso":true,"latency":true,"noiseSuppression":true,"pan":true,"pointsOfInterest":true,"resizeMode":true,"sampleRate":true,"sampleSize":true,"saturation":true,"sharpness":true,"tilt":true,"torch":true,"whiteBalanceMode":true,"width":true,"zoom":true}
2021-05-30T07:53:15.689Z [INFO] ChimeMeetingLogs - browser is chrome 90 (90.0.4430)
2021-05-30T07:53:15.689Z [INFO] ChimeMeetingLogs - WebRTC unified plan for Chromium-based browsers is enabled
2021-05-30T07:53:15.735Z [INFO] ChimeMeetingLogs - adding meeting observer

**Meeting and attendee IDs:**
 "MeetingId": "4aba972a-34f9-426e-8124-b570796b9c6e"
"AttendeeId": "6c233379-3817-56e4-19fb-d17b1bcf23e4"

**Bug description**
I'm successfully receiving the Meeting and Attendee objects from the Lambda function I've made,  I'm also checking the meeting and attendee with AWS CLI and everything seems fine. But then when I'm trying to instantiate the meeting session in browser using the standard piece of code from here https://github.com/aws/amazon-chime-sdk-js#meeting-session it breaks with circular dependency exception. 

Please take a look at the attached screenshots. 

**Screenshots**
<img width="960" alt="Lambda repsonse" src="https://user-images.githubusercontent.com/2950010/120144622-713ab100-c20c-11eb-82a3-19c55b8ad097.png">

<img width="960" alt="Check meeting and attendee" src="https://user-images.githubusercontent.com/2950010/120144619-6f70ed80-c20c-11eb-95f2-94e321ff19bc.png">

<img width="960" alt="Meeting session creating client code" src="https://user-images.githubusercontent.com/2950010/120144624-71d34780-c20c-11eb-97ae-8f3fc413b860.png">

<img width="960" alt="invoking-the-library" src="https://user-images.githubusercontent.com/2950010/120432200-c65cfb00-c3a3-11eb-8f31-c6495f11e22c.png">

<img width="960" alt="Error trying to add observer" src="https://user-images.githubusercontent.com/2950010/120144621-70a21a80-c20c-11eb-8a3c-fdb42c62e6e6.png">

**Platform**
 - OS: Windows 10
 - Browser: Chrome 
 - Browser Version: 90.0.4430.212 64bit
 - Amazon Chime SDK GitHub Commit:

**Comment by ltrung** [comment]
@paramonych Thanks for reporting. I do not think this is an issue with your createMeeting and createAttendee calls and probably just an issue with javascript packing.
Could you give more details about your setup and maybe a minimal step to reproduce your issue?

**Comment by paramonych** [comment]
I am using the parcel bundler along with the Svelte3 components

I would prefer to use the context independent prebuilt and tested version of the chime sdk js library, rather that building it as a node module. Is it possible?

Here is the simple Lambda function for JOIN and END endpoints and the client side code
[parcel-minimum.zip](https://github.com/aws/amazon-chime-sdk-js/files/6590490/parcel-minimum.zip)


<img width="677" alt="package-json and ts-config" src="https://user-images.githubusercontent.com/2950010/120621327-fb427e00-c487-11eb-8919-96246b95fd8d.png">
<img width="960" alt="successfull-build" src="https://user-images.githubusercontent.com/2950010/120621334-fc73ab00-c487-11eb-89b9-f9a67bb00e04.png">
<img width="254" alt="ts-config" src="https://user-images.githubusercontent.com/2950010/120621337-fc73ab00-c487-11eb-8ad5-5e49cceeb267.png">
<img width="959" alt="ts-warnings" src="https://user-images.githubusercontent.com/2950010/120621342-fd0c4180-c487-11eb-819a-1a2ebb52bbaa.png">

**Comment by simmkyu** [comment]
I followed the [dev.to blog post](https://dev.to/alexparra/basic-svelte-app-with-parcel-30i5) to set up a minimal Svelte app with Parcel. I could import the "Chime SDK for JavaScript" library, add an audio-video observer, and start a meeting without the circular dependency error.

1. Download and unzip [parcel-svelte.zip](https://github.com/aws/amazon-chime-sdk-js/files/6626868/parcel-svelte.zip).
2. Assign your responses to `meetingResponse` and `attendeeResponse` in `src/App.svelte`.
3. Install dependencies and start a dev server.
    ```
    npm i
    npm run dev
    ```
4. Open `http://localhost:1234`, click the "Join a meeting", and allow the microphone permission.

**Dependencies**
```
"amazon-chime-sdk-js": "^2.11.0"
"parcel-bundler": "^1.12.5",
"parcel-plugin-svelte": "^4.0.8",
"sass": "^1.34.1",
"svelte": "^3.38.2"
```

**Environment**
```
% node -v
v14.17.0
% npm -v
6.14.13
```
---

> I would prefer to use the context independent prebuilt and tested version of the chime sdk js library, rather that building it as a node module. Is it possible?

You can try our "single-js" instruction to bundle the Chime SDK for JavaScript into a single file and embed it in your `index.html` file. You can access the Chime SDK components via `window.ChimeSDK` in a non-NPM project.
https://github.com/aws/amazon-chime-sdk-js/tree/master/demos/singlejs

**Comment by Coachtube** [comment]
@simmkyu @vidya-mohan Thank you guys for the update! It worked for me after updating the SDK vesion from 2.10.0 to 2.11.0 

![image](https://user-images.githubusercontent.com/30532310/122927475-20455500-d393-11eb-91bb-29d8c907fa73.png)
