### ISSUE TITLE
ReferenceError: window is not defined at MessagingSessionConfiguration

### ISSUE THREAD

**Issue by abhimanusharma** [aws/amazon-chime-sdk-js#1334]
Trying to generate a meeting session at server end (NestJs), 

Here my code:
```
        const envConfig = dotenv.parse(fs.readFileSync(path.resolve(process.cwd(), 'api/env', `.env.${currentEnv}`)));
        const chime = new Chime({ region: 'us-east-1' });
        const endpoint = await chime.getMessagingSessionEndpoint().promise();
        
        return new Promise((resolve, reject) => {

            AWS.config.update({accessKeyId: envConfig.AWS_ACCESS_KEY_ID, secretAccessKey: envConfig.AWS_SECRET_ACCESS_KEY});
            const logger = new ConsoleLogger('SDK', LogLevel.INFO);
            // You will need AWS credentials configured before calling AWS or Amazon Chime APIs.

            const userArn = 'arn:aws:chimemessage:us-east-1:<accountid>:user:'+meeting.attendeeId/* The userArn */;
            const sessionId = ''/* The sessionId */;

            try {
                const configuration = new MessagingSessionConfiguration(userArn, sessionId, endpoint.Endpoint.Url, chime, AWS);
                const messagingSession = new DefaultMessagingSession(configuration, logger);
                console.log(messagingSession);
                

                resolve(messagingSession)
            } catch (error) {
                reject(error)
            }
        });
```
evnConfig is working fine, and the parameters are correct.

I am getting below error.
```
ReferenceError: window is not defined
    at MessagingSessionConfiguration.generateSessionId (/var/www/html/project_dev/node_modules/amazon-chime-sdk-js/build/messagingsession/MessagingSessionConfiguration.js:45:27)
    at new MessagingSessionConfiguration (/var/www/html/project_dev/node_modules/amazon-chime-sdk-js/build/messagingsession/MessagingSessionConfiguration.js:40:44)
    at /var/www/html/project_dev/api/dist/modules/meeting/services/meeting/meeting.service.js:39:39
    at new Promise (<anonymous>)
    at MeetingService.getMessageSession (/var/www/html/project_dev/api/dist/modules/meeting/services/meeting/meeting.service.js:33:16)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async MeetingController.getMessageSession (/var/www/html/project_dev/api/dist/modules/meeting/controllers/meeting/meeting.controller.js:39:36)
```

**Comment by ltrung** [comment]
@abhimanusharma The error `window` is not defined is because JS SDK is supposed to run in a browser environment. Specifically in this case, we use the crypto function of window to generate the session ID for the messaging session.
Is there a specific reason you want to do this in server? For now, you would need to fork the repo and change the crypto function to node's specifc one.

**Comment by abhimanusharma** [comment]
@ltrung It is mentioned [here](https://github.com/aws/amazon-chime-sdk-js#getting-responses-from-your-server-application-1) in the documentation that the session has to be generated on the server. How to generate session on the client end when it is using so many sensitive information to generate one. Please tell me is the documentation wrong?

**Comment by ltrung** [comment]
Gotcha. That is incorrect on our part. That sample code is supposed to run on client. The documentation is now updated.
For your question on how to generate a session on client end, I believe @dpwspoon have already answered that in another thread https://github.com/aws/amazon-chime-sdk-js/issues/1335#issuecomment-852997545 so closing this issue for now. Feel free to post any other question on that thread.

**Comment by abhimanusharma** [comment]
@ltrung I don't think this issue should be closed because I think it's unsafe to use AWS_ACCESS and AWS_SECRET on client side application as it will be exposed easily. Also during creation of userArn our AWS accountId will also exposed, Is this the correct way to implement this? Is it safe? Shouldn't there be a better way?

**Comment by ltrung** [comment]
I closed this issue since you already discussed with @dpwspoon in thread #1335. Could you post your question there?
