### ISSUE TITLE
observer is removed but still getting called

### ISSUE THREAD

**Issue by junedlanja** [aws/amazon-chime-sdk-js#1336]
**Describe the bug**
I'm removing observer using `removeObserver` on meeting leave but observers are still called. I can see it's getting removed from `observerQueue` but still observer for `audioVideoDidStop` still being called. is it expected?

**Comment by ldai1** [comment]
Hi,

Thanks for reporting the issue. Can you provide logs and more implementation details? There could be a race condition happening when dequeuing from this async observerQueue, but we need more logs to help debug this issue.

**Comment by junedlanja** [comment]
In my case on meeting leave or any exceptions, I'm redirecting users to another page. But on the old page, I'm still getting event ** audioVideoDidStop**. What you log need? info level logs? @ldai1

**Comment by vidya-mohan** [comment]
You can find guidance https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html#how-can-i-get-amazon-chime-sdk-logs-for-debugging . I would recommend keeping the original bug template when opening the request that calls out the steps or helpful information to go faster in the issue

**Comment by vidya-mohan** [comment]
Resolving as no update on data
