### ISSUE TITLE
issue with creating dynamic videoElement

### ISSUE THREAD

**Issue by E5920** [aws/amazon-chime-sdk-js#1339]
@michhyun1, i am facing issue with creating dynamic video element. my requirement is if user "A" local video is turned off then user "B" remote video element should be removed dynamically but not getting removed. pl check my code & correct me.

.html 
    <audio class="session-audio"></audio>
    <video class="session-remote-video"></video>
    <video class="session-local-video" ></video>    

.ts 

 private domElement(className : string) {
    return document.getElementsByClassName(className)[0];
  }

 private domShow(ele : HTMLElement) {
    ele.style.display = 'block';
    ele.setAttribute('show', 'true');
  }

 audioVideoDidStart() {
    console.log("Sudhanshu: inside audioVideoDidStart");
    this.meeting.meetingSession.audioVideo.startLocalVideoTile();
  }

  audioVideoDidStop() {
    console.log("Sudhanshu: inside audioVideoDidStop");
    this.meeting.meetingSession.audioVideo.stopLocalVideoTile();
    alert("meeting has ended");
  }
  videoTileDidUpdate(tileState: VideoTileState) {
    // Ignore a tile without attendee ID and a content/screen share.
    if (!tileState.boundAttendeeId || tileState.isContent) {
      return;
    }
    // Choose the right video element in your web application
    var videoElement = tileState.localTile? 'session-local-video' : 'session-remote-video';
    // Bind the given tile state to the target video element
    this.meeting.meetingSession.audioVideo
      .bindVideoElement(tileState.tileId, this.domElement(videoElement));
    this.domShow(<HTMLElement>this.domElement(videoElement));
  }

regards,
Rajat

**Comment by michhyun1** [comment]
@E5920 please correct me if I'm wrong, but where do you actually remove any remote video tiles?

If your use case is to disable a remote video when a local video is disabled, then you need to have a domHide function too, right?

**Comment by E5920** [comment]
.
