### ISSUE TITLE
How to implement Connection Indicator in Chime SDK? 

### ISSUE THREAD

**Issue by mrnav90** [aws/amazon-chime-sdk-js#1345]
Hi everyone.
I'm trying to research implement `Connection Indicator` like image below:
<img width="233" alt="Screen Shot 2021-06-03 at 16 17 27" src="https://user-images.githubusercontent.com/9253581/120647177-816cbd80-c4a4-11eb-9ed7-1f3c5f1f59f0.png">
<img width="389" alt="Screen Shot 2021-06-03 at 16 17 52" src="https://user-images.githubusercontent.com/9253581/120647206-8893cb80-c4a4-11eb-8daa-4a7f5373c36a.png">
 
I also to know Chime SDK was support function: `getObservableVideoMetrics` but I want to more information like image.

Many thanks

**Comment by ldai1** [comment]
Hi, thanks for using the Chime JS SDK. Yes, you can use the new method we recently launched to get these WebRTC metrics: https://aws.github.io/amazon-chime-sdk-js/interfaces/clientmetricreport.html#getobservablevideometrics. We also render those metrics in our meeting demo app to show those stats when you toggle the video WebRTC stats button and hover your mouse on video tiles. You can find the implementation here: https://github.com/aws/amazon-chime-sdk-js/blob/master/demos/browser/app/meetingV2/meetingV2.ts#L1135

We are working on adding more documentations for this feature. Let us know if you need any help or if you have any feedback about this feature.

**Comment by mrnav90** [comment]
@ldai1 
Hi, Thank you for your reply.
We need more info about ( Uplink and DownLink ) for  both `Local user` and `Remote user`
Currently, we just only get 
`Uplink for local user` -> `videoUpstreamMetricsKeyStats`
`Downlink for remote user` -> `videoDownstreamMetricsKeyStats`

How to get data `Packet loss` for Local user?
And about 2 observer of `AudioVideoObserver` not working. 
We tried to add 2 observer `connectionDidBecomeGood` and `connectionDidBecomePoor` but don't see anything.
We also used tool `network link conditioner` for downgrade network for test but can't get expected result. 

Please help or give me more info :(
Many thanks

**Comment by ldai1** [comment]
In our new method we recently launched, we provide both upstream and downstream metrics for local user. If you print the output of  `getObservableVideoMetrics`, you will see a list of metrics for each attendeeId include the local attendee. For the local attendee, you will see the metrics with following: 
```
videoUpstreamBitrate,
videoUpstreamPacketsSent,
videoUpstreamFramesEncodedPerSecond,
videoUpstreamGoogFrameHeight, (for chromium based browsers)
videoUpstreamGoogFrameWidth,(for chromium based browsers)
videoUpstreamFrameHeight,
videoUpstreamFrameWidth,
```
for all other attendees, you will get following metrics:
```
videoDownstreamBitrate
videoDownstreamPacketLossPercent,
videoDownstreamFramesDecodedPerSecond,
videoDownstreamGoogFrameHeight,
videoDownstreamGoogFrameWidth,
videoDownstreamFrameHeight,
videoDownstreamFrameWidth,
```
Do you see any information that is missing from those metrics?

Also, can you provide a code snippet of your implementation of using  `connectionDidBecomeGood` and `connectionDidBecomePoor`?

**Comment by mrnav90** [comment]
@ldai1 
Thank you reply and support.

1. About method `getObservableVideoMetrics` when we join 1 local user and 3 remote users then we can get array data of list user. But at local user we need to know `downlink info` of all remote users, it's mean each user have `Bitrate` = 100Kbps so local user should have `Bitrate downlink` = 300Kbps. ( Could you check my image attachment at issue detail )

2. We hope next version release, Chime SDK Team will add `PacketLost` for local user ( Many Thanks )

3. Just short code add Observer ( don't see trigger event )
`
export default class MeetingObserver {
  constructor(meetingSession, evt) {
    this.meetingSession = meetingSession;
    this.event = evt;
    this.initialize();
  }

  initialize = () => {
    this.observers = {
      connectionDidBecomeGood: this.connectionDidBecomeGood,
      connectionDidBecomePoor: this.connectionDidBecomePoor,
    };
  };

  subscribe = () => {
    this.meetingSession.addObserver(this.observers);
  };

  unsubscribe = () => {
    this.meetingSession.removeObserver(this.observers);
  };


  connectionDidBecomeGood = () => {
    console.log('network good');
  };

  connectionDidBecomePoor = () => {
    console.log('network bad');
  };
}
`

**Comment by ldai1** [comment]
Hi @mrnav90,

Thanks for your response and patience. We are working on adding the `PacketLost` for local user, which targeting to get released in our next version.

Currently we are not supporting the accumulated bytes received for local user. We are in the progress to migrate to using standard getStats() API. We will consider to get it included in our migration. Thanks for bringing this up.

I am working on reproducing the issue using you code snippet.  Will get back to you shortly.

Thanks

**Comment by mrnav90** [comment]
@ldai1 
Hi, thank you for your support.
About method `getObservableVideoMetrics` it will receive video metrics data. But when we set turn off camera it not receive data, so now how to get PacketLost ?
About observer `connectionDidBecomeGood` `connectionDidBecomePoor` I saw it not working for me so I can use `PacketLost` calc network connection via code example.
```
          if (keyMetric && keyMetric === 'packetLoss') {
            let status;
            switch (true) {
              case value <= 4:
                status = 'good';
                break;
              case value <= 6:
                status = 'medium';
                break;
              case value <= 12:
                status = 'bad';
                break;

              default:
                status = 'bad';
                break;
            }
```
Can you help or tell me know can get more info like image below?

For `Local user`
<img width="233" alt="120647177-816cbd80-c4a4-11eb-9ed7-1f3c5f1f59f0" src="https://user-images.githubusercontent.com/9253581/123061661-0a3ca080-d436-11eb-851b-e6133d5ffc5a.png">

For `Remote user`
<img width="389" alt="120647206-8893cb80-c4a4-11eb-8daa-4a7f5373c36a" src="https://user-images.githubusercontent.com/9253581/123061745-1c1e4380-d436-11eb-8b64-824053dc522e.png">

`Local User` and `Remote User` have both video metrics data for `Uplink` and `DownLink`

Many thanks

**Comment by ldai1** [comment]
Hi, 

If you turn off camera, you won't get video quality metrics for yourself, the packet lost will be 0 for your video stream metrics. We are adding the the packets loss for local user and packets received for remote users in this [pr](https://github.com/aws/amazon-chime-sdk-js/pull/1382) as you requested. 

Also did you check our implementation in the meeting app demo [here](https://github.com/aws/amazon-chime-sdk-js/blob/master/demos/browser/app/meetingV2/meetingV2.ts#L1135)? If you follow or just copy the code, you will get those metrics in when you hover on every attendee in the roster if you click the statistic bar button.

**Comment by ldai1** [comment]
Hi,

We will be releasing the packet loss percent for video upstream and packet received for video downstream so that you will get both uplink data and downlink data for local attendee.

You won't get PacketLost when you turn off camera. But you will still get packet lost data for remove attendees if they turn on their video.

Can you include the code snippet that you use the observer and how you call the `connectionDidBecomeGood`?

**Comment by mrnav90** [comment]
Hi @ldai1 
This short code I'm using observer.
Just call: `meetingObserver.subscribe();`
I don't know how to trigger this event? it's mean you say we need to call a function for trigger event? or this event will be trigger automated?
If not correct, could you help explain for me?

Thanks
```
export default class MeetingObserver {
  constructor(meetingSession, evt) {
    this.meetingSession = meetingSession;
    this.event = evt;
    this.initialize();
  }

  initialize = () => {
    this.observers = {
      connectionDidBecomeGood: this.connectionDidBecomeGood,
      connectionDidBecomePoor: this.connectionDidBecomePoor,
    };
  };

  subscribe = () => {
    this.meetingSession.addObserver(this.observers);
  };

  unsubscribe = () => {
    this.meetingSession.removeObserver(this.observers);
  };


  connectionDidBecomeGood = () => {
    console.log('network good');
  };

  connectionDidBecomePoor = () => {
    console.log('network bad');
  };
}
```

**Comment by ldai1** [comment]
Does you class implements [AudioVideoObserver](https://github.com/aws/amazon-chime-sdk-js/blob/48e1d3842f7bd72a2110659155e4c8df0bce7628/src/audiovideoobserver/AudioVideoObserver.ts) ? According to this [guide](https://github.com/aws/amazon-chime-sdk-js/blob/11f66bb9ba2bb35582501ffb8b56b2f5f3008c1d/guides/04_Quality_Bandwidth_Connectivity.md), the `connectionDidBecomeGood` can only be triggered as an event of `AudioVideoObserver` to monitor connectivity and quality.

**Comment by ldai1** [comment]
code to add packetLossPercent for video upstream and packetReceived for video downstream: https://github.com/aws/amazon-chime-sdk-js/pull/1382

**Comment by mrnav90** [comment]
Hi @ldai1 
I've implement class like you said.
Add observer, connect audio-video success but can't see trigger event `connectionDidBecomeGood`
Could you help me press down detail like: step by step or show me a video demo trigger event?

And like you said before.
`
We will be releasing the packet loss percent for video upstream and packet received for video downstream so that you will get both uplink data and downlink data for local attendee.
`
But I've update SDK and show log, we can't get `down link data` and `uplink data` for local user.
It's mean we want to get `VideoDowns` and `VideoUp` for IDs (244188439)
![Uploading Screen Shot 2564-07-05 at 16.55.44.png…]()

Many thanks

**Comment by ldai1** [comment]
Hi,

My understanding of downlink data anda uplink data for local user is:

for packet loss uplink, you can use the videoUpstreamPacketSent
for packet loss downlink, you can use the videoUpstreamPacketLossPercent, this value is calculated in this [funciton](https://github.com/aws/amazon-chime-sdk-js/blob/master/src/clientmetricreport/DefaultClientMetricReport.ts#L53-L66), you can do some calculation to get the actual packet lost value.

If that is not what you want, I am afraid that we probably couldn't provide more metrics for the current phase. You might want to build your own version sdk to expose more metrics or you can wait for our new release to use standard getStats() API to get these metrics.

**Comment by mrnav90** [comment]
@ldai1 
Hi, thank you for your support.

I'll try your demo.

Thanks.
