### ISSUE TITLE
Sometimes screen share viewers do not see share until presenter interacts with presented app

### ISSUE THREAD

**Issue by vidya-mohan** [aws/amazon-chime-sdk-js#135]
### What are you trying to do?
When multiple monitors are plugged in - sometimes screen sharing doesnt begin unless the presenter actively interacts with the screen.

Platform

OS: win10
Browser: chrome
Browser Version: 79
Amazon Chime SDK GitHub Commit: 6afdca0

This is not specific to Chime SDK and could be reproed with an independent WebRtc app. https://janus.conf.meetecho.com/screensharingtest.html 

### How can the documentation be improved to help your use case?

Call out in the API or so that this is a limitation of the browser and not a chime SDK bug

### What documentation have you looked at so far?

README.md, Amazon Chime SDK Developer Guide, etc.

**Comment by aburnson** [comment]
We should add this to an FAQ
