### ISSUE TITLE
Chrome not asking for audio/video permission in iOS..

### ISSUE THREAD

**Issue by rakesh-eltropy** [aws/amazon-chime-sdk-js#1350]
**Describe the bug**

Chrome is not asking for audio/video permission in iOS, hence not able to use audio/video controls. It's working fine in Safari. Is this a known issue in iOS Chrome? or someone can help me with this. I am using` amazon-chime-sdk-component-library-react`.

**Platform**
 - OS: iOS
 - Browser: Chrome
 - Browser Version: 91
 - Amazon Chime SDK GitHub Commit: master

**Comment by michhyun1** [comment]
Hi @rakesh-eltropy - can you please check if you've allowed Microphone and Camera access on the Chrome application level? I think you'll need to enable it in your phone's Settings > Chrome > Microphone/Camera enabled

**Comment by michhyun1** [comment]
@rakesh-eltropy Did this resolve your issue?

**Comment by michhyun1** [comment]
Resolving dude to inactivity  - please reopen if needed
