### ISSUE TITLE
Camera LED stays ON after calling stopLocalVideoTile()

### ISSUE THREAD

**Issue by vsimeikoKG** [aws/amazon-chime-sdk-js#1352]
**Meeting and attendee IDs:**
- Attendee 1 ID - 8c7c286c-44b3-74f8-9e2c-a3d241ce2184
- Attendee 2 ID - df99ab57-d8e1-51de-d518-0982f1a23bfe
- Meeting ID - db027c1a-c0bc-43d7-8d1e-257938ee2c6c

**Timeline**
- Open two Chrome tabs: anonymous and regular.
- Join the meeting from regular tab as attendee 1.
- Join the meeting from anonymous tab as attendee 2.
- Video starts correctly for both attendees.
- Stopping video for both attendees.
- LED Camera stays ON and both tabs have "recording" icon.

**Describe the bug**
LED Camera indicator stays ON after stopping the video.

React hook that we use to handle camera start/stop:
```js
  useEffect(() => {
    if (!meetingSession.current) {
      return;
    }

    const {audioVideo} = meetingSession.current;

    if (!videoInputEnabled && audioVideo.hasStartedLocalVideoTile()) {
      audioVideo.chooseVideoInputDevice(null).then(() => {
        audioVideo.stopLocalVideoTile();
        console.log('VIDEO STOPPED');
      });
    }

    if (
      videoInputEnabled &&
      (!audioVideo.hasStartedLocalVideoTile() ||
        (audioVideo.hasStartedLocalVideoTile() &&
          audioVideo
            .getLocalVideoTile()
            .state()
            .boundVideoStream?.getVideoTracks()?.[0]
            .getSettings()?.deviceId !== videoInputDeviceID))
    ) {
      audioVideo.chooseVideoInputDevice(videoInputDeviceID).then(() => {
        // Extra check here to avoid having "lost" MediaStream somewhere in Chime state.
        if (!audioVideo.hasStartedLocalVideoTile()) {
          console.log('VIDEO STARTED');
          audioVideo.startLocalVideoTile();
        }
      });
    }
  }, [meetingSession.current, videoInputEnabled, videoInputDeviceID]);
```

**Notes:**
- I removed all local `MediaStream` uses and made sure that there is no `navigator.mediaDevices.getUserMedia()` calls anywhere in the app. Only Chime manages video and audio streams.
- Both attendees joined as muted.
- I added console.log() calls to make it clear that we call start/stop functions only once.
- Same issue happens as well within the real meeting with other users.

**Platform**
 - OS: macOS 10.15.7
 - Browser: Chrome
 - Browser Version: 90.0.4430.212 (Official Build) (x86_64)
 - Amazon Chime SDK GitHub Commit: 2.9.0

[Attendee 1 localhost-1623081853466.log](https://github.com/aws/amazon-chime-sdk-js/files/6610519/Attendee.1.localhost-1623081853466.log)
[Attendee 2 localhost-1623081863953.log](https://github.com/aws/amazon-chime-sdk-js/files/6610520/Attendee.2.localhost-1623081863953.log)

**Comment by vidya-mohan** [comment]
@vsimeikoKG could you please look at the guidance in our FAQs on the order of the APIs being called https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html#after-leaving-a-meeting-the-camera-led-is-still-on-indicating-that-the-camera-has-not-been-released-what-could-be-wrong 

Since you are building a React app, we also have a React SDK here and you can compare and use components against this SDK - https://github.com/aws/amazon-chime-sdk-component-library-react

**Comment by vsimeikoKG** [comment]
@vidya-mohan ,

I tried using the following and it still didn't work:
```js
    if (!videoInputEnabled && audioVideo.hasStartedLocalVideoTile()) {
      audioVideo.chooseVideoInputDevice(null).then(() => {
        audioVideo.stopContentShare(); // No attendee streams content, but I added here from FAQ example.
        audioVideo.stopLocalVideoTile();
        audioVideo.unbindAudioElement(); // Took from React SDK example.
      });
    }
```

Attendee is still present in the meeting, so I can't call `audioVideo.stop()`

**Comment by vsimeikoKG** [comment]
@simmkyu @vidya-mohan ,

Thanks for the summary!

I was able to resolve the issue by making sure that there is only one active promise for `audioVideo.chooseVideoInputDevice()`. Seems to work as expected.

However, it would be great if there would be some kinda `LogLevel.WARN` or `LogLevel.ERROR` message for such situations since it's not documented in the documentation.

I think the issue can be closed now.

Thanks for the help!

**Comment by vsimeikoKG** [comment]
UPD.

Looks like it handles camera OFF/ON state locally for me, but for other attendees in the meeting it doesn't work properly.

I made some additional changes to properly reset video input with `audioVideo.chooseVideoInputDevice(null)`, so hopefully that fixes the issue for other users.

I'll try to gather some logs if the issue persists.

**Comment by vsimeikoKG** [comment]
Issue was resolved after we updated to the latest master branch that has #1366 fix.

Additionally, we updated our code to make sure there is no multiple calls to `choose[audio|video]InputDevice`.
