### ISSUE TITLE
Sound Quality issue: VoiceFocus with builtin Noise Cancellation Microphones (Headphones) 

### ISSUE THREAD

**Issue by peili** [aws/amazon-chime-sdk-js#1356]
Amazon Voice Focus noise suppressor can cause distorted audio when a device with active audio input noise cancellation is used.

Devices we are able to reproduce include: Bose QuietComfort and Jabra Evolve 75 MS.
There is no indicator/observer to detect the quality issue in the SDK. The user manually has to disable Amazon Voice Focus, when other participants share feedback about that bad quality audio output.

Any guidance for auto detection on such devices would be very helpful.

**Comment by simmkyu** [comment]
The Chime SDK for JavaScript offers two observer methods for the Amazon Voice Focus feature: `voiceFocusFellBackToInnerStream` and `voiceFocusInsufficientResources`. The `voiceFocusInsufficientResources` method indicates that the user experiences audio glitching. When this event occurs, you may disable the Voice Focus, limit video tiles, and notify the user.

Please see the Amazon Voice Focus guide and the API reference for more information.
- https://aws.github.io/amazon-chime-sdk-js/modules/amazonvoice_focus.html#observer-notifications
- https://aws.github.io/amazon-chime-sdk-js/interfaces/voicefocustransformdeviceobserver.html

**Comment by rnewman** [comment]
Do you see the same issue on the same machine, same meeting, with Voice Focus enabled, but switching to e.g., built-in microphones?

**Comment by rnewman** [comment]
Which browser and version is exhibiting issues?

**Comment by peili** [comment]
> Do you see the same issue on the same machine, same meeting, with Voice Focus enabled, but switching to e.g., built-in microphones?

Yes.

**Comment by peili** [comment]
> Which browser and version is exhibiting issues?

Chrome 91.0.4472.101, Chime SDK 2.11.0

**Comment by richnew10** [comment]
Chrome 91 and earlier had [issues with Bluetooth audio devices](https://bugs.chromium.org/p/chromium/issues/detail?id=1173656). This was fixed in Chrome 92. Resolving.
