### ISSUE TITLE
Invalid camera gets selected when using MediaStream.clone() with chooseVideoInputDevice()

### ISSUE THREAD

**Issue by vsimeikoKG** [aws/amazon-chime-sdk-js#1357]
**Meeting and attendee IDs:**
Meeting ID - f6464f45-7a03-4531-9632-4c2cc0912074
Attendee ID - abf5d8cb-a3cb-dc39-642d-5f60526b5afd

**Timeline**
- Open browser with 2 video inputs available: USB and FaceTime cameras.
- Join the meeting with camera A selected.
- I can see my local video preview from camera A, but all other attendees can see output from camera B.

**Describe the bug**
Chime connects to the wrong camera when I use `chooseVideoInputDevice(existingMediaStream.clone())`. However, I can see correct camera local video preview (non-Chime video).

```js
  useEffect(() => {
    if (!meetingSession.current) {
      return;
    }

    const {audioVideo} = meetingSession.current;

    const handler = (stream) => {
      // Stop video if stream is null.
      if (!stream && audioVideo.hasStartedLocalVideoTile()) {
        audioVideo.stopLocalVideoTile();
      }

      const videoSettings = getVideoQualitySettings(/* ... */);

      if (
        stream &&
        (!audioVideo.hasStartedLocalVideoTile() ||
          !deepEqual(lastVideoQualitySettings.current, videoSettings))
      ) {
        const clone = stream.clone();

        window.clone = clone; // To debug. See console logs.

        console.log('CLONE DEVICE LABEL', clone.getTracks()[0].label);

        audioVideo.chooseVideoInputQuality(...videoSettings);
        audioVideo.listVideoInputDevices().then(() =>
          audioVideo.chooseVideoInputDevice(clone).then(() => {
            // Extra check here to avoid having "lost" MediaStream somewhere in Chime state.
            if (!audioVideo.hasStartedLocalVideoTile()) {
              audioVideo.startLocalVideoTile();
              console.log('VIDEO START');
            }
          })
        );

        lastVideoQualitySettings.current = videoSettings;
      }
    };

    MediaStreamSingleton.subscribeToVideoStream(handler);

    return () => MediaStreamSingleton.unsubscribeFromVideoStream(handler);
  }, [meetingSession.current, /* ... */]);
```

**Platform**
 - OS: macOS Catalina 10.15.7 (19H114)
 - Browser: Chrome
 - Browser Version: 91.0.4472.101 (Official Build) (x86_64)
 - Amazon Chime SDK GitHub Commit: 2.11.0

[logs.txt](https://github.com/aws/amazon-chime-sdk-js/files/6627104/logs.txt)

**Comment by vsimeikoKG** [comment]
@ltrung ,

I saw you added a `Bug` label to the issue.

Is there any timeline for this issue to get fixed?

Thanks!

**Comment by ltrung** [comment]
@vsimeikoKG We have been able to reproduced this bug and are currently discussing on how best to fix this.

**Comment by vsimeikoKG** [comment]
@ltrung ,

We tested the latest changes from master branch and your changes fixed our problem.

Much appreciated for the quick fix for the bug!

**Comment by ltrung** [comment]
@vsimeikoKG Thanks. I will close the issue for now.
