### ISSUE TITLE
How can I respond to end of support for Node.js 10 in Lambda?

### ISSUE THREAD

**Issue by jungmal** [aws/amazon-chime-sdk-js#1358]
Hi,

I'm using severless demo and it is composed by Node.js 10.x
As you know, support is ended of for Node.js 10 in Lambda.

So, how can i handle it?

just replace nodejs10.x to nodejs12.x or nodejs14.x 
in https://github.com/aws/amazon-chime-sdk-js/blob/master/demos/serverless/template.yaml
and re-deploy serverless app?
(I don't know if this will)

or any other solutions?

thank you.

**Comment by ltrung** [comment]
Thanks for bringing this to our attention. I have updated our Lambda Node version to 14 in serverless demo deploy template.
You can checkout the latest code and re-deploy your own stack.
