### ISSUE TITLE
Too much pause unpause make a binded video blank

### ISSUE THREAD

**Issue by rlebosse** [aws/amazon-chime-sdk-js#1359]
**Describe the bug**

In order to preserve the user's data, each time there is a new `videoTile` (thanks to `videoTileDidUpdate`) I use `audioVideo.pauseVideoTile(tileId)` to pause the video stream.
When the attendee is displayed on screen on a `<video>` element, the video is unpaused with `audioVideo.unpauseVideoTile(tileId)` then bound to the `<video>` element.

Since the number of attendees that are displayed on screen depends on the screen dimensions (width & height).
Each time I resize the browser's window, some video are paused and some are unpaused.

When I do the resize the window a lot of times, when the video is unpaused and bound to the `<video>` element, it takes more and more time to pass from blank to the "real video stream".
If I keep doing these consecutive pause-unbind video element-unpause-bind video element, the video stays blank and the "real video stream" is never displayed.

When I face the problem, here is the state of the video tile :

<img width="881" alt="Capture d’écran 2021-06-10 à 10 58 44" src="https://user-images.githubusercontent.com/2794137/121496557-de073580-c9da-11eb-9763-5b813baba648.png">

Maybe there is a way to check that the media stream is on and that I am currently receiving data from these stream ?

Could you help me with this ?
Thanks a lot !

**Platform**
 - OS: macOS 11.3.1
 - Browser: Chrome 91
 - Amazon Chime SDK GitHub Commit: 2.9.0

**Comment by XHatan** [comment]
Thanks @rlebosse for opening the issue.

Could you explain more why pausing and unpausing the tile ? 

FYI, pausing and unpausing are actual network operations to stop/resume receiving the stream data. So frequent use of the `pauseVideoTile` API is quite a network overhead

**Comment by rlebosse** [comment]
In my webapp, I display :
* Only **n** (n < 16) videos on the user's screen
* Those ***n* videos displayed are the attendees with the most recent activity

In order to limit the network data usage of the user, the videos that are not currently displayed on his screen are paused.
But when there is a switch and a video displayed is replaced by another : the remove one is **paused** and the displayed one is **unpaused**.

In this use case and in some conditions, there can be a large amount of video switches in a short time. Thus, a large amount of **pauseVideoTile** and **unpauseVideoTile** calls.

Since you say it can cause quite a network overhead, is there any recommandations from your side ?

**Comment by xuesichao** [comment]
Hi @rlebosse, I would recommend you to try the `priorityBasedDownlinkPolicy` in this scenario. Check the doc [here](https://aws.github.io/amazon-chime-sdk-js/modules/prioritybased_downlink_policy.html).

The general idea is to use the `priorityBasedDownlinkPolicy` to update the `VideoPreferences` to drop the video sources that are not currently displayed on the screen. This can save your network bandwidth.

You can also set the priority of each video sources, so whenever there is a network restriction. The video sources with higher priority will try to keep its target resolution, while the lower priority ones will be lower the resolution or even paused.
