### ISSUE TITLE
Change username in chime meeting

### ISSUE THREAD

**Issue by tkulis** [aws/amazon-chime-sdk-js#1360]
Hi,

sorry for reporting this as a bug.
I cannot find Info, if it is possible to change username in one Chime meeting?

**Comment by simmkyu** [comment]
The Amazon Chime SDK for JavaScript (this repository) does not have the **username** concept, parameter, or API.

I assume that you mean the Chime Application. You can specify the `username` parameter in the [CreateUser API action](https://docs.aws.amazon.com/chime/latest/APIReference/API_CreateUser.html#chime-CreateUser-request-Username), but I cannot find other Chime APIs to change the username. Note that this CreateUser API action is not a part of the Chime SDK for JavaScript.

Sorry for the confusion. For the Chime Application-related question, you can ask in https://answers.chime.aws/

**Comment by tkulis** [comment]
Hi @simmkyu , 

sorry for confusion and wrong wording.
I was referring to **attendee** terminology. 
in node.js MeetingDemo app that is this part.
![image](https://user-images.githubusercontent.com/8543254/121648515-e1acc200-ca97-11eb-820c-12eeda162dc1.png)
