### ISSUE TITLE
Getting empty array in listChannels response

### ISSUE THREAD

**Issue by abhimanusharma** [aws/amazon-chime-sdk-js#1369]
I am using aws chat demo to implement chime's messaging/chat sdk.

Here is my sample code.
```
const userArn = await this.createMemberArn(paramsObj.userId);
const params = {
    AppInstanceArn: conf.appInstaceArn, //required
    ClientRequestToken: uuid(),
    Name: paramsObj.name,
    Mode: paramsObj.mode,
    Privacy: paramsObj.privacy
};

const request = (await this.chimeClient()).createChannel(params);
request.on('build', function() {
    request.httpRequest.headers[this.appInstanceUserArnHeader] = userArn
}.bind(this));
const response = await request.promise();
```
**Payload:**
```
{
    "name": "testChannel1",
    "mode": "UNRESTRICTED",
    "privacy": "PRIVATE",
    "userId": "asdas@asd.ccc"
}
```
I am getting channel ARN in response.

Using the same userArn and appInstanceArn I am calling listChannels.
```
const params = {
    AppInstanceArn: conf.appInstaceArn
};

const request = (await this.chimeClient()).listChannels(params);
    request.on('build', function() {
    request.httpRequest.headers[this.appInstanceUserArnHeader] = userArn
}.bind(this));
const response = await request.promise();
const channels = response.Channels;
```

**Payload:**
```
{
    "userId": "asdas@asd.ccc"
}
```
Getting empty array in response.

**Comment by jingwy** [comment]
Hi,

According to your code, you are creating a private channel. 

When listChannels is called with an AppInstanceUser that is not AppInstanceAdmin, and the Privacy field is not specified, listChannels returns only public channels for the AppInstance by default.

However, when listChannels is called with an AppInstanceUser that is an AppInstanceAdmin, and the Privacy field is not specified, listChannels returns both public channels and private channels by default.

In your case, if you create an AppInstanceUser that is not promoted to an AppInstanceAdmin, and there are no public channels created yet, then listChannels will return an empty array when called by that AppInstanceUser.

Let me know if this is the issue or if you have other questions. You can also find more details on our API documentation page: https://docs.aws.amazon.com/chime/latest/APIReference/API_ListChannels.html

**Comment by abhimanusharma** [comment]
@jingwy I want to all list private channels which are related to the current AppInstanceUser, In other words, I want all the channels in which this AppInstanceUser is a member of. Shouldn't he receive list of all the channels in which he is a member by default?

Can you also tell me, what could be the case when **messagingSessionDidReceiveMessage** is not receiving response in realtime from endpoint that is being use to **startMessagingSession** or **createChannel**?

**Comment by jingwy** [comment]
Hi,

I think [ListChannelMembershipsForAppInstanceUser](https://docs.aws.amazon.com/chime/latest/APIReference/API_ListChannelMembershipsForAppInstanceUser.html) API is what you are looking for.  It will return you all the channels for a user.

**Comment by abhimanusharma** [comment]
Thank you so much, that is exactly what I was looking for.
