### ISSUE TITLE
remote video is not coming when added more than 2rd user

### ISSUE THREAD

**Issue by E5920** [aws/amazon-chime-sdk-js#1372]
@michhyun1, i am facing issue when i have added  more than 2 users then 1st user, 2nd user screen, remote video is not coming while 3rd user screen remote video is perfectly fine & this is happen when i have added number of users. i don't know how is going to unbind videoElement after added more than 2 user, pl check & give a suggestion.

3rd user screenshot.
![image](https://user-images.githubusercontent.com/80304004/122715347-5cd75a80-d286-11eb-945b-3256f30ba49d.png)

1st user screenshot same as 2nd user screenshot.
![image](https://user-images.githubusercontent.com/80304004/122715311-4fba6b80-d286-11eb-8adf-7555bc1b72ec.png)

Html Code.

< *ngFor="let user of videoElementStatus | keyvalue">
    
    <id="{{user.key}}">  

ts code :- 

  videoElementStatus: { [index: string]: number; } = {};
  private domElement(className : string, key : string) {
    if(className == 'session-local-video' || className == 'session-audio' ){
      return document.getElementsByClassName(className)[0];
    } else {
      //remote video element
      return document.getElementById(key);
    }
    return null;
  }

videoTileDidUpdate(tileState: VideoTileState) {
  // Ignore a tile without attendee ID and a content/screen share.
    if (!tileState.boundAttendeeId || !tileState.tileId) {
      return;
    }

    // Choose the right video element in your web application
    var videoElement = tileState.localTile? 'session-local-video' : 'session-remote-video';

    if(!tileState.localTile){
      if (tileState.boundAttendeeId in this.videoElementStatus === false) {
    
        this.videoElementStatus[tileState.boundAttendeeId] = -1;
  
        this.changeDetectorRef.detectChanges();
      }
    }

     let videoEl = null;    
    videoEl = this.domElement(videoElement, tileState.boundAttendeeId);
   
    // Bind the given tile state to the target video element
    if (videoEl != null){
		this.meeting.meetingSession.audioVideo
      .bindVideoElement(tileState.tileId, videoEl);
      this.domShow(videoEl);
    } else {
    }
  }

**Comment by devalevenkatesh** [comment]
Hi @E5920 ,

Thanks for reporting the issue, it looks like your bind and unbind video element logic may not be correct to handle more users.

The JS SDK [browser meeting demo app](https://github.com/aws/amazon-chime-sdk-js/tree/master/demos/browser) shows how you can implement such a scenario. Request you to go through it and understand the implementation for your use-case.

We also have few video related use-cases in our README to explain how builders can handle multiple video elements bind and unbind. Please check use case 13-16 in the JS SDK README [here](https://github.com/aws/amazon-chime-sdk-js#video).

If you still find issues please feel free to re-open this issue.
