### ISSUE TITLE
Can I  deploy the serverless meet in other region or is us-east-1 the only option?

### ISSUE THREAD

**Issue by gavandivya** [aws/amazon-chime-sdk-js#1374]
### What are you trying to do?
I am able to run the browser meeting demo and now want to deploy it as serverless meeting.

cd demos/serverless
npm install
npm run deploy -- -r us-east-1 -b <my-bucket> -s <my-stack-name> -a meeting

here while npm run deploy is it possible to create bucket in some other AWS region or us-east-1 is the only option?

**Comment by devalevenkatesh** [comment]
Hi @gavandivya ,

Yes, It is possible to deploy (create AWS S3 bucket and AWS CloudFormation template) the demo in a different region. I just tried with below command and it worked for me.
```
npm run deploy -- -r us-west-2 -b chime-sdk-demo-test-us-west-2-s3 -s chime-sdk-demo-test-us-west-2-cft -a meeting
```

Closing this issue please feel free to create new issue if you run into problems.

**Comment by gavandivya** [comment]
Okay I thanks. So I hope it will even work in ap-south-1 region. Because previously  when I tried doing it and used ap-south-1, I was caught into some error.

**Comment by gavandivya** [comment]
I am able to run the serverless chime demo(Create s3 bucket) in ap-south-1 so now where will my data stored? Is US-east-1 the only storage available or will my s3 bucket will be used for storage client and meeting details?
