### ISSUE TITLE
Unable to join chime meeting session with Request URL

### ISSUE THREAD

**Issue by husaindevelop** [aws/amazon-chime-sdk-js#1381]
Be informed, we have deployed amazon chime singlejs sdk to implement our own meeting session. It was successfully deployed with the help of aws documentation. Self-Video shows up, meeting is initialized, attendees registered and even guest video shows up if we open the page on another tab. But what i'm unable to do is to join that particular meeting with a REQUEST URL eg ?join=109010101. I used the same meeting id as a join request that i registered, but despite that both of windows do not show up guest video tiles.

Shall appreciate if you can help us in getting us out from this issue. 

The code we are using is as given below
```
<?
$result = $client->listMeetings([]);
if (count($result['Meetings']) == 0) {

    $options = [
        'ClientRequestToken' =>'mbrace_meeting',
        'MediaRegion' => 'ap-south-1',
    ];
    $result = $client->createMeeting($options);
    $meeting = $result['Meeting'];
    
} else {
    
    $meeting = $result['Meetings'][0];
    $_SESSION['meeting']=$result['Meetings'][0];
}
$options = [
    'ExternalUserId' => date('Ymd_His') . '_attendee0_' . uniqid(),
    'MeetingId' => $meeting['MeetingId'],
];
$result = $client->createAttendee($options);
$attendee = $result['Attendee']; 
?>

   <script src="amazon-chime-sdk-js/demos/singlejs/build/amazon-chime-sdk.min.js"></script>
    <script>
        (async () => {
            const logger = new ChimeSDK.ConsoleLogger('MyLogger', ChimeSDK.LogLevel.ERROR);
            const deviceController = new ChimeSDK.DefaultDeviceController(logger);
const logger = new ChimeSDK.ConsoleLogger('ChimeMeetingLogs', ChimeSDK.LogLevel.INFO);
const deviceController = new ChimeSDK.DefaultDeviceController(logger);
const configuration = new ChimeSDK.MeetingSessionConfiguration(meeting, attendee);
const meetingSession = new ChimeSDK.DefaultMeetingSession(configuration, logger, deviceController);
            const meetingResponse = {"Meeting":<? echo $_GET['met'] ?>};
            const attendeeResponse = {"Attendee":<?php echo json_encode($attendee) ?>};

            const configuration = new ChimeSDK.MeetingSessionConfiguration(meetingResponse, attendeeResponse);
            const meetingSession = new ChimeSDK.DefaultMeetingSession(configuration, logger, deviceController);

            const audioInputDevices = await meetingSession.audioVideo.listAudioInputDevices();
            const audioOutputDevices = await meetingSession.audioVideo.listAudioOutputDevices();
            const videoInputDevices = await meetingSession.audioVideo.listVideoInputDevices();

            meetingSession.audioVideo.chooseVideoInputQuality(1280,720,3,1000);
            await meetingSession.audioVideo.chooseVideoInputDevice(videoInputDevices[0].deviceId);
            await meetingSession.audioVideo.chooseAudioInputDevice(audioInputDevices[0].deviceId);
            if (audioOutputDevices[0]) {
                await meetingSession.audioVideo.chooseAudioOutputDevice(audioOutputDevices[0].deviceId);
            }
            meetingSession.audioVideo.startVideoPreviewForVideoInput(document.getElementById('self-video'));



            const audioElement = document.getElementById('audio-preview');
            meetingSession.audioVideo.bindAudioElement(audioElement);

            const videoElement = document.getElementById('video-preview');

            

            const observer = {
                audioVideoDidStart: () => {
                    console.log('Started');
                },
                videoTileDidUpdate: tileState => {
                    if (!tileState.boundAttendeeId || tileState.localTile || tileState.isContent) {
                        return;
                    }

                    console.log('Start video');
                    meetingSession.audioVideo.bindVideoElement(tileState.tileId, videoElement);
                }
            };

            meetingSession.audioVideo.addObserver(observer);
            meetingSession.audioVideo.start();
            meetingSession.audioVideo.startLocalVideoTile();
        }) ();
    </script>


<div id="video-preview"></div>
<div id="audio-preview"></div>
```

**Comment by devalevenkatesh** [comment]
Hi @husaindevelop ,

Thanks for reporting this issue. From the code, you are creating meeting session configuration and meeting session twice. This is not required.
```
const configuration = new ChimeSDK.MeetingSessionConfiguration(meeting, attendee);
const meetingSession = new ChimeSDK.DefaultMeetingSession(configuration, logger, deviceController);
            const meetingResponse = {"Meeting":<? echo $_GET['met'] ?>};
            const attendeeResponse = {"Attendee":<?php echo json_encode($attendee) ?>};

            const configuration = new ChimeSDK.MeetingSessionConfiguration(meetingResponse, attendeeResponse);
            const meetingSession = new ChimeSDK.DefaultMeetingSession(configuration, logger, deviceController);
```

This code block is also repetitive, the latter two lines are fine, you can remove the first two line:
```
const logger = new ChimeSDK.ConsoleLogger('MyLogger', ChimeSDK.LogLevel.ERROR);
const deviceController = new ChimeSDK.DefaultDeviceController(logger);
const logger = new ChimeSDK.ConsoleLogger('ChimeMeetingLogs', ChimeSDK.LogLevel.INFO);
const deviceController = new ChimeSDK.DefaultDeviceController(logger);
```

Please correct me if I am understanding incorrectly. So you are trying to create / re-use the meeting response and create the attendee each time you put an URL in the browser and then do setup steps to create the meeting session and call `audioVideo.start()` to see the meeting.

Can you please check following points:
- Check whether your `$result['Meetings']` is ever getting populated cause I do not see how it is updated in the provided `if-else` block. Sorry, I am not familiar with PHP. 
- Check if you are getting the correct `CreateMeeting` and `CreateAttendee` API responses.
- If all this is good and you are still facing issues, we would need the `INFO` level browser console logs to check for any problems.

**Comment by husaindevelop** [comment]
To put it in short words, i'm trying to join the room which already has attendees, I was able to somehow create a meeting with two persons successfully. But after closing the window and few hours after, if i try to recall that meeting id with attendees, the page shows up blank. Why is that ? Should it not just re-enter the meeting session.

**Comment by devalevenkatesh** [comment]
An Amazon Chime meeting auto-ends in below cases:
- No audio connections are present in the meeting for more than five minutes.
- Less than two audio connections are present in the meeting for more than 30 minutes.
- Screen share viewer connections are inactive for more than 30 minutes.
- The meeting time exceeds 24 hours.

https://docs.aws.amazon.com/chime/latest/dg/mtgs-sdk-mtgs.html

Since, you are trying to join after few hours the meeting should have been already ended and hence you are not able to join it successfully. The JS SDK console logs will show this.

Can you provide us the `meetingId` to confirm whether it auto-ended?

**Comment by husaindevelop** [comment]
I think that answers the question. We are fine with it. Thank you for the reply. I'm closing the ticket.
