### ISSUE TITLE
"TypeError: Chime is not a constructor" via aws-sdk with MessagingSessionConfiguration

### ISSUE THREAD

**Issue by Berkyle** [aws/amazon-chime-sdk-js#1384]
### What are you trying to do?

I'm trying to initialize a messaging session on the client side using the AWS SDK and the AWS SDK's Chime client.

### How can the documentation be improved to help your use case?

Document how to utilize the AWS-SDK in the browser in order to subscribe to message events.

### What documentation have you looked at so far?

I've followed documentation within this repo as well as a few other AWS examples as to how to subscribe to a messaging session, most notably:
- https://github.com/aws/amazon-chime-sdk-js#messaging-session
- https://github.com/aws/amazon-chime-sdk-js/blob/master/demos/browser/app/messagingSession/messagingSession.ts#L21-L22

These examples work fine in a development bundle. But once I've compiled my application into a production bundle and serve the minified file from my application server, I'm seeing: `TypeError: h is not a constructor`. Here, `h` is `Chime`, imported via:
```javascript
import * as Chime from 'aws-sdk/clients/chime';
```

I've found a few other instances around the web getting this exact error ([here](https://stackoverflow.com/questions/61300302/typeerror-aws-chime-is-not-a-constructor) and [here](https://github.com/aws/amazon-chime-sdk-js/issues/303), for example), but in all of those cases the answer seemed to be "Don't import from the aws-sdk on the client side. Browser applications don't need the aws-sdk." But unfortunately the chime messaging session very much needs to use the main sdk. Is this possibly an issue with my webpack configuration, or have I wildly misunderstood how a messaging session is meant to be configured on the browser?

![image](https://user-images.githubusercontent.com/34729254/123160782-30614100-d434-11eb-84a3-c4959ea81601.png)
![image](https://user-images.githubusercontent.com/34729254/123160731-22abbb80-d434-11eb-8449-b7c4c9c01163.png)

**Comment by Berkyle** [comment]
Turns out the fix is just to not use a wildcard import. It would probably be best to update this in the documentation since I imagine a lot of use cases will involve developing a chat application for the browser.

```javascript
// ❌  This breaks when compiled to vanilla js
import * as Chime from 'aws-sdk/clients/chime';

// ✅  The default export is the Chime client class anyway, no need for wildcard import
import Chime from 'aws-sdk/clients/chime';
```

**Comment by devalevenkatesh** [comment]
Thanks for pointing this out and helping us correct it. We will be updating the README for this soon.

**Comment by jing-chen1** [comment]
Hi @Berkyle, we have tested that wildcard import works with the demo, however, removing the wildcard *does not* work. So would keep the README as is. 

Could you please compare your Webpack configuration with the [chat demo](https://github.com/aws-samples/amazon-chime-sdk/blob/main/apps/chat/webpack.config.js)? The chat demo is a modern chat messaging application. Hope it helps.

**Comment by jing-chen1** [comment]
Closing it now. Feel free to reopen if you still have issues.
