### ISSUE TITLE
Unable initializing chime singlejs sdk in android webview

### ISSUE THREAD

**Issue by husaindevelop** [aws/amazon-chime-sdk-js#1386]
Be informed, we have deployed chime singlejs sdk in our web app and android apps. Under web app, it is working just fine, but on android webview, the amazon chime sdk just does not initialize, so much so even self-camera itself does not show up. All the permissions are given, but yet even basics do not work (camera initialization). Only a play icon is visible in those video-frames.  Tell us how we go about this ?

Code is as given below for you reference:

Android Manifest.xml
<?xml version="1.0" encoding="utf-8"?>
```
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
	xmlns:tools="http://schemas.android.com/tools"
	package="com.mbracetechapp.mailecitizen"
	android:installLocation="auto">

	<supports-screens
		android:anyDensity="true"
		android:resizeable="true"
		android:smallScreens="true"
		android:largeScreens="true"
		android:normalScreens="true"
		android:xlargeScreens="true" />

	<!-- remove permissions that your app doesn't require;
	asking for authority over unwanted information can cause damage to your reputation among your users -->
	<uses-permission android:name="android.permission.INTERNET" />
	<uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
	<uses-permission android:name="android.permission.ACCESS_WIFI_STATE" />
	<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" tools:remove="android:maxSdkVersion" />
	<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
	<uses-permission android:name="android.permission.CAMERA" />
	<uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
	<uses-permission android:name="android.permission.VIBRATE" />
	<uses-permission android:name="com.google.android.c2dm.permission.RECEIVE" />

	<!-- remove location.gps feature if not using permission ACCESS_FINE_LOCATION -->
	<uses-feature android:name="android.hardware.location.gps" />
	<uses-feature android:name="android.hardware.touchscreen" android:required="false" />

	<!--<uses-sdk tools:overrideLibrary="com.google.zxing.client.android" />-->

	<application
		android:allowBackup="true"
		android:icon="@mipmap/ic_launcher"
		android:label="@string/app_name"
		android:supportsRtl="true"
		android:theme="@style/SplashTheme"
		android:hardwareAccelerated="true"
		android:usesCleartextTraffic="true"
		android:requestLegacyExternalStorage="true"
		tools:ignore="AllowBackup,UnusedAttribute">
		<activity
			android:name="com.mbracetechapp.mailecitizen.SplashScreen"
			android:label="@string/app_name"
			android:screenOrientation="portrait" >
			<intent-filter>
				<action android:name="android.intent.action.MAIN" />
				<category android:name="android.intent.category.LAUNCHER" />
			</intent-filter>
		</activity>
		<activity
			android:name="com.mbracetechapp.mailecitizen.MainActivity"
			android:screenOrientation="portrait" >		<!-- remove or alter as your apps requirement -->
			<intent-filter android:label="@string/app_name">
				<action android:name="android.intent.action.VIEW" />
				<category android:name="android.intent.category.DEFAULT" />
				<category android:name="android.intent.category.BROWSABLE" />
				<data android:scheme="https"
					android:host="apps.mgks.dev"
					android:pathPrefix="/swv" />
				<!-- if you want only a specific directory from your website to be opened in the app through external links -->
			</intent-filter>
			<intent-filter android:label="OpenURI">
				<action android:name="Open_URI" />
				<category android:name="android.intent.category.DEFAULT" />
			</intent-filter>
		</activity>
		<activity android:name="com.mbracetechapp.mailecitizen.ShareActivity">
			<intent-filter android:label="Share">
				<action android:name="android.intent.action.SEND" />
				<category android:name="android.intent.category.DEFAULT" />
				<data android:mimeType="text/*" />
				<!-- <data android:mimeType="image/*" /> -->
			</intent-filter>
		</activity>
		<!--<receiver android:name=".NotificationPausePlay" />-->
		<service android:name="com.mbracetechapp.mailecitizen.Firebase">
			<intent-filter>
				<action android:name="com.google.firebase.MESSAGING_EVENT" />
				<action android:name="com.google.firebase.INSTANCE_ID_EVENT" />
			</intent-filter>
		</service>
		<meta-data
			android:name="com.google.android.gms.version"
			android:value="@integer/google_play_services_version" />
		<meta-data
			android:name="com.google.android.gms.ads.APPLICATION_ID"
			android:value="@string/app_id"/>
	</application>
</manifest>

```

**Comment by devalevenkatesh** [comment]
Hi @husaindevelop ,

Thanks for reporting the issue. Currently, we do not have official support for Android Webview.
Could you please let us which Andriod webview version you are using?

Currently supported browsers: https://docs.aws.amazon.com/chime/latest/dg/meetings-sdk.html#mtg-browsers.

**Comment by husaindevelop** [comment]
While we are able to view on mobile browser, fail doing through an android webview app compiled with version 30, though it carries a chrome browser frame, that was duly acknowledged by amazon chime supported browsers: https://docs.aws.amazon.com/chime/latest/dg/meetings-sdk.html#mtg-browsers

What we expect is its resolution, that will enable an identical view outcome on both android webview app and mobile browser.

**Comment by devalevenkatesh** [comment]
Sorry I could not understand the issue specifically.

Could you please tell us if you are able to use Amazon Chime JS SDK in Android Webview and are having problem with resolution? (As per latest comment). Is this video resolution or something else?
Also, in the initial description you said that the nothing is working with Amazon Chime JS SDK hence we would like to confirm the exact issue.

**Comment by michhyun1** [comment]
@husaindevelopthe sdk does not currently support android webviews. You'll find the [list of user-agents](https://github.com/aws/amazon-chime-sdk-js/blob/master/src/browserbehavior/DefaultBrowserBehavior.ts#L12-L24) that we use to identify supported browsers. 

Android webviews should support WebRTC, so theoretically, you should be able to add the browser name extracted from the user-agent by ua-parser and put that string inside of the array of [supported browsers](https://github.com/aws/amazon-chime-sdk-js/blob/master/src/browserbehavior/DefaultBrowserBehavior.ts#L12-L24). However, we don't claim to support Android webviews as of today.

**Comment by husaindevelop** [comment]
@devalevenkatesh, No by resolution, we mean solution to the problem we are facing, which is amazon chime SDK not working in android webview. That's the issue. This SDK works just fine in mobile chrome browser but not in android webview, which actually runs a chrome browser client frame.  Naturally, i thought it would work considering chrome is a supported browser as per your documentation. 

Not pushing you, when can we expect you to add support to this particular issue, or alternatively, is there any possibility, we can  get this done through amazon premium code support. Thanks

**Comment by husaindevelop** [comment]
Do you support cross platform technologies like cordova, react, ionic. We won't mind changing to them if chime support them.

**Comment by devalevenkatesh** [comment]
Hi @husaindevelop ,

We do not officially support cordova, ionic and xamarin as documented in the supported browsers linked in above comments. However, we have a react library if you want to try. It gives you UI components, hooks and providers to build a audio-video application.

Github: https://github.com/aws/amazon-chime-sdk-component-library-react
[React SDK documentation](https://aws.github.io/amazon-chime-sdk-component-library-react/?path=/story/introduction--page)

**Comment by LeviSklaroff** [comment]
@husaindevelop We are now supporting Android WebView! Please update your chime sdk version and for code reference on how to setup a Android WebView application for the Chime SDK please refer to https://github.com/aws-samples/amazon-chime-sdk/tree/main/apps/Android-WebView-sample

Be aware that Android WebView is not the same as Chrome for Android and has more limitations. One particular issue exists with device labels that will prevent devices being labeled the same between the two browsers https://bugs.chromium.org/p/chromium/issues/detail?id=669492

**Comment by husaindevelop** [comment]
The above link is broken.

**Comment by devalevenkatesh** [comment]
Sorry, looks like there was renaming, here is the updated link:
https://github.com/aws-samples/amazon-chime-sdk/tree/main/apps/android-webview-sample

[This repo](https://github.com/aws-samples/amazon-chime-sdk) holds Amazon Chime SDK sample demos.
