### ISSUE TITLE
How to set and edit user information effectively in Chime SDK

### ISSUE THREAD

**Issue by bachvutrong** [aws/amazon-chime-sdk-js#1390]
### What are you trying to do?
Hi. 
I'm trying to set and edit the user information in a room (i.e. user avatar, ...). Is there any way to do that like a data channel but not message channel, so that if a user update the avatar, the others will be synchronized and display it correctly"

**Comment by devalevenkatesh** [comment]
Hi @bachvutrong ,

Thanks for your interest in the Amazon Chime SDK for JavaScript. 

Unfortunately, we do not have a direct way for your use case to do synchronization across all attendees (local + remote) in an meeting. Assuming that by data channel you mean the WebRTC datamessages and message channel means the JS SDK messaging session. Using data messages you can use AudioVideoFacade's [`realtimeSendDataMessage`](https://aws.github.io/amazon-chime-sdk-js/interfaces/audiovideofacade.html#realtimesenddatamessage) API to send a data message with that attendeeId and the avatar identifier id to a topic and then listen to that message on remote attendee side using the AudioVideoFacade's [`realtimeSubscribeToReceiveDataMessage`](https://aws.github.io/amazon-chime-sdk-js/interfaces/audiovideofacade.html#realtimesubscribetoreceivedatamessage) subscribe method and then get the avatar data from the backend in your app once you receive the message. You can unsubscribe by using AudioVideoFacade's [`realtimeUnsubscribeFromReceiveDataMessage`](https://aws.github.io/amazon-chime-sdk-js/interfaces/audiovideofacade.html#realtimeunsubscribefromreceivedatamessage) API.

We use these APIs along with the [`realtimeSubscribeToAttendeeIdPresence`](https://aws.github.io/amazon-chime-sdk-js/interfaces/audiovideofacade.html#realtimesubscribetoattendeeidpresence) in our default meetingV2 browser demo [app](https://github.com/aws/amazon-chime-sdk-js/tree/master/demos/browser) to implement roster of attendees and messaging between them.

For more information on data message in Amazon Chime SDK for JavaScript you can check: https://aws.github.io/amazon-chime-sdk-js/modules/apioverview.html#9-send-and-receive-data-messages-optional

Closing this issue for now, please feel free to re-open if you need further help.
