### ISSUE TITLE
Control output volume level

### ISSUE THREAD

**Issue by paul365** [aws/amazon-chime-sdk-js#1391]
### What are you trying to do?

Hi, I'm trying to control the output volume of the chime meeting just on my end, but can't find any documentation on how to do it. I've seen it being done with the input but what I want to control is the output volume. Thanks!

### How can the documentation be improved to help your use case?

Show steps and/or example of the to control the output volume.

### What documentation have you looked at so far?

README.md,
Amazon Chime SDK Developer Guide,
https://aws.amazon.com/blogs/business-productivity/transforming-audio-and-shared-content-in-the-amazon-chime-sdk-for-javascript/

**Comment by devalevenkatesh** [comment]
Hello @paul365 ,

Currently, The Amazon Chime SDK for JavaScript has no APIs to control the output volume of the Amazon Chime meeting. However as a workaround, you might be able to change the volume for the audio element you bind using the `bindAudioElement` API like explained below. You can get the audio element which is used to bind the audio from the meeting and then change the volume for it.
```
// First set up the Amazon Chime SDK meeting session
// Bind audio 
// Then do below step
const audioElement = document.getElementById('<bound-audio-element-id-in-your-app');
console.log(audioElement.volume); // 1
obj.volume = 0.75;
```

https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/volume

**Comment by paul365** [comment]
Thanks!

**Comment by christiansaavedra** [comment]
@devalevenkatesh  Thanks for your answer, it helped me!
Unfortunately i realized that browser's audio volume can't be more than 1, which is the default value. So my users will have to adjust their own device's output volume if they want it higher.
