### ISSUE TITLE
Non host attendees wait until host join meeting

### ISSUE THREAD

**Issue by mvaghasia** [aws/amazon-chime-sdk-js#1403]
### What are you trying to do?

I wants attendees should be in wait page until host join meeting.  Do you have any event  which can notify attendees that host join meeting. Will it possible to get host join event through existing socket connection ?

### What documentation have you looked at so far?

socket data which can be received at attendees socket

**Comment by gsudhanshu** [comment]
@mvaghasia we had a similar use case and we implemented this through our application. I think you need to build that into your application

**Comment by mvaghasia** [comment]
Can you provide more details how did you implement ? Have you created new socket with yours server which used for notify attendees of host join event ?

**Comment by michhyun1** [comment]
@gsudhanshu unfortunately, we don't have a way to do this using the Amazon Chime SDK for Javascript today. However, you may try to build your own implementation around the SDK to support your use case.

**Comment by gsudhanshu** [comment]
@mvaghasia you can use socket.io websockets to implement the same

**Comment by gsudhanshu** [comment]
@mvaghasia you can contact me for details garg.sudhanshu@gmail.com
