### ISSUE TITLE
active speaker screen is not working

### ISSUE THREAD

**Issue by E5920** [aws/amazon-chime-sdk-js#1405]
@devalevenkatesh , i am facing issue with active speaker screen, when speaker is activated then controll is not coming in "activeSpeakerCallback(attendeeIds )"  so that way active speaker  not  detecting. pl check my code and suggest

ts  file

t ileIdToIndex: {[tileId: number]: string; } = {};
  attendeeIdToTileid: {[attendeeId: string]: number; } = {};
  activeAttendeeId:string = "";

constructor(){
this.meeting.meetingSession.audioVideo.subscribeToActiveSpeakerDetector(new DefaultActiveSpeakerPolicy(), this.activeSpeakerCallback, 1000);
}
  activeSpeakerCallback(attendeeIds ) {
    
    console.log("active speaker attendeeIds"+attendeeIds);
    // console.log("active speaker tileId"+tileId);
    var videoElement = document.getElementById('session-remote-video-0');
    
    if(this.activeAttendeeId != attendeeIds[0]){
      if (attendeeIds.length) {
        console.log("inside if active speaker");
        console.log(`${attendeeIds[0]} is the most active speaker`);
        // this.attendeeIdToTileid.tileId

        if(this.activeAttendeeId != ""){
          var videoElement1 = 'session-remote-video';
          var videoEl : HTMLVideoElement;
          //Bind the given tile state to the target video element
          videoEl = <HTMLVideoElement>this.domElement(videoElement1,  this.attendeeIdToTileid[this.activeAttendeeId],this.activeAttendeeId );
          if (videoEl != null){
            console.log("Rajat here 11");
            this.meeting.meetingSession.audioVideo
             .bindVideoElement(this.attendeeIdToTileid[this.activeAttendeeId], videoEl);           
            console.log("Rajat: video element bind called "+videoElement);
            var divEl = document.getElementById('div-'+videoEl.id);
            divEl.classList.remove("inactive");
            divEl.classList.add("active");
            //
          } else {
            console.log("Rajat here 10");
          }
        }
        this.meeting.meetingSession.audioVideo
        .bindVideoElement(this.attendeeIdToTileid[attendeeIds[0]], videoElement);
        this.activeAttendeeId = attendeeIds[0];
        var id = this.attendeeIdToTileid[attendeeIds[0]];
        if(id in this.tileIdToIndex){
          var eleId = this.tileIdToIndex[id];
          divEl.classList.remove("active");
          divEl.classList.add("inactive");
          delete this.tileIdToIndex[id];
          this.videoElementStatus[eleId] = -1;
        }  
      }
    }
   
thanks & regards,
Rajat;

**Comment by devalevenkatesh** [comment]
Hi,

Thanks for reporting the issue. Checking through the code, is this pasted code is in its own class?

If so checking if the constructor is having the correct access to `this.meeting.meetingSession.audioVideo`. Want to know if the `audioVideo` is the valid one to which you are adding the active speaker callback subscription.

Could you try creating the meeting session in this constructor and then adding the subscription and see whether your callback is working fine?

**Comment by gsudhanshu** [comment]
[code.zip](https://github.com/aws/amazon-chime-sdk-js/files/6757183/code.zip)
check the attached code files

**Comment by gsudhanshu** [comment]
@devalevenkatesh @michhyun1 @ltrung

**Comment by michhyun1** [comment]
@gsudhanshu thanks for sharing your code. I see you are calling audioVideo.start on `meeting.meetingSession.audioVideo.start();` in the CallVideoComponent constructor. 
```
  constructor(private meeting: MeetingService, private modalService: ModalService, private changeDetectorRef: ChangeDetectorRef) { 
    this._meetingSessionSubscription = meeting.meetingSessionChange.subscribe((value) => {
      //this.meetingSession = value;
      meeting.meetingSession.audioVideo.addObserver(this);
      meeting.meetingSession.audioVideo.bindAudioElement(this.domElement('session-audio', null, null));
      meeting.meetingSession.audioVideo
        .bindVideoElement(0, this.domElement("session-local-video", null, null));
      //this.meetingSession.audioVideo.startLocalVideoTile();
      
      for(let i = 1; i <= this.MAX_VIDEO_ELEMENTS; i++) {
        this.dynamicVideoElementIds.push('session-remote-video-'+i);
      }
      this.dynamicVideoElementIds.forEach(element => {
        this.videoElementStatus[element] = -1;  
      });

      meeting.meetingSession.audioVideo.start();
      this.meeting.meetingSession.audioVideo.subscribeToActiveSpeakerDetector(new DefaultActiveSpeakerPolicy(), 
                                                                              this.activeSpeakerCallback, 1000);
    });
  }
  ```
  
Can you confirm that this `this.meeting.meetingSession.audioVideo.subscribeToActiveSpeakerDetector(new DefaultActiveSpeakerPolicy(), this.activeSpeakerCallback, 1000);` is actually being called? If so, do you need to be using `this.meeting`? Can you just do `meeting.`?

**Comment by devalevenkatesh** [comment]
We are closing this issue due to in-activity, please feel free to create a new if you need more help.
