### ISSUE TITLE
getting end call message when chime app is running

### ISSUE THREAD

**Issue by E5920** [aws/amazon-chime-sdk-js#1406]
@devalevenkatesh , i am facing issue when  chime application running sometime it's working fine but most of the time getting end call message , have only added activeSpeakerCallback(attendeeIds ) for active speaker then issue is creating, pl  check & suggest.

ts file.
t ileIdToIndex: {[tileId: number]: string; } = {};
attendeeIdToTileid: {[attendeeId: string]: number; } = {};
activeAttendeeId:string = "";

constructor(){
this.meeting.meetingSession.audioVideo.subscribeToActiveSpeakerDetector(new DefaultActiveSpeakerPolicy(), this.activeSpeakerCallback, 1000);
}

activeSpeakerCallback(attendeeIds ) {

console.log("active speaker attendeeIds"+attendeeIds);
// console.log("active speaker tileId"+tileId);
var videoElement = document.getElementById('session-remote-video-0');

if(this.activeAttendeeId != attendeeIds[0]){
  if (attendeeIds.length) {
    console.log("inside if active speaker");
    console.log(`${attendeeIds[0]} is the most active speaker`);
    // this.attendeeIdToTileid.tileId

    if(this.activeAttendeeId != ""){
      var videoElement1 = 'session-remote-video';
      var videoEl : HTMLVideoElement;
      //Bind the given tile state to the target video element
      videoEl = <HTMLVideoElement>this.domElement(videoElement1,  this.attendeeIdToTileid[this.activeAttendeeId],this.activeAttendeeId );
      if (videoEl != null){
        console.log("Rajat here 11");
        this.meeting.meetingSession.audioVideo
         .bindVideoElement(this.attendeeIdToTileid[this.activeAttendeeId], videoEl);           
        console.log("Rajat: video element bind called "+videoElement);
        var divEl = document.getElementById('div-'+videoEl.id);
        divEl.classList.remove("inactive");
        divEl.classList.add("active");
        //
      } else {
        console.log("Rajat here 10");
      }
    }
    this.meeting.meetingSession.audioVideo
    .bindVideoElement(this.attendeeIdToTileid[attendeeIds[0]], videoElement);
    this.activeAttendeeId = attendeeIds[0];
    var id = this.attendeeIdToTileid[attendeeIds[0]];
    if(id in this.tileIdToIndex){
      var eleId = this.tileIdToIndex[id];
      divEl.classList.remove("active");
      divEl.classList.add("inactive");
      delete this.tileIdToIndex[id];
      this.videoElementStatus[eleId] = -1;
    }  
  }
}

thanks & regards,
Rajat

**Comment by devalevenkatesh** [comment]
Hello,

Sorry, I could not understand the issue completely. Could you please clarify below questions?
1. What do you mean by the "end call message"?
2. From the code, it looks like based on active speaker you want to bind and show the video tile for the active speaker. But this is my guess, could you please help us understand your use case here?
3. We have a subscribe and unsubscribe functions which will provide you the active speaker list ascending from most recent to least with attendeeIds, request you to check [here](https://github.com/aws/amazon-chime-sdk-js/blob/master/guides/03_API_Overview.md#5d-subscribe-to-an-active-speaker-detector-optional).

Request you to provide above information to further understand this issue.

**Comment by gsudhanshu** [comment]
@devalevenkatesh @michhyun1 

We are already using the subscribe method in the constructor

```
constructor(){
this.meeting.meetingSession.audioVideo.subscribeToActiveSpeakerDetector(new DefaultActiveSpeakerPolicy(), this.activeSpeakerCallback, 1000);
}
```

We are using callback this.activeSpeakerCallback but this callback function is not being called. And most of the times we are getting control in audiovideodidstop

```
audioVideoDidStop() {
    console.log(" inside audioVideoDidStop");
    this.meeting.meetingSession.audioVideo.stopLocalVideoTile();
    //this.meeting.dropAttendee();
    this.modalService.open('meeting-end-modal');
  }
```

We are concerned why this is happening?

**Comment by gsudhanshu** [comment]
@michhyun1 @devalevenkatesh 

Also, I observed that there is an interface 

[ActiveSpeakerObserver](https://aws.github.io/amazon-chime-sdk-android/amazon-chime-sdk/com.amazonaws.services.chime.sdk.meetings.audiovideo.audio.activespeakerdetector/-active-speaker-observer/index.html
)

but I am not able to import it from amazon-chime-sdk-js, how can I use this for my use case?
*Use case to show active speaker in big tile

**Comment by devalevenkatesh** [comment]
Hi @gsudhanshu ,

Could you please help us with `meetingId`, `attendeeId` and corresponding console logs?

This will help us understand how the `audioVideoDidStop` occurs. If you are calling the `audioVideo.stop()` or something else.

**Comment by gsudhanshu** [comment]
@devalevenkatesh sometimes it works, sometimes we get the error. When I get the error then I am unable to get logs as the system would freeze as I try to access console logs

**Comment by gsudhanshu** [comment]
@devalevenkatesh Pls find attached the logs, we are getting following error:

meetingFailed event:

main.445b0c10e527078841c1.js:1 Rajat Failed during a meeting: Signaling client is not ready in  Object
eventDidReceive @ main.445b0c10e527078841c1.js:1

[demo.evareg.com-1625567651465.log](https://github.com/aws/amazon-chime-sdk-js/files/6769352/demo.evareg.com-1625567651465.log)

**Comment by gsudhanshu** [comment]
> @michhyun1 @devalevenkatesh 
> 
> Also, I observed that there is an interface 
> 
> [ActiveSpeakerObserver](https://aws.github.io/amazon-chime-sdk-android/amazon-chime-sdk/com.amazonaws.services.chime.sdk.meetings.audiovideo.audio.activespeakerdetector/-active-speaker-observer/index.html
> )
> 
> but I am not able to import it from amazon-chime-sdk-js, how can I use this for my use case?
> *Use case to show active speaker in big tile
> 

@ltrung @michhyun1 @devalevenkatesh any suggestions in this direction?

**Comment by michhyun1** [comment]
@gsudhanshu that link is for the amazon-chime-sdk-android, not for the JS SDK. It looks like from your code, you subscribe to the activeSpeaker correctly:

```
this.meeting.meetingSession.audioVideo.subscribeToActiveSpeakerDetector(new DefaultActiveSpeakerPolicy(), this.activeSpeakerCallback, 1000);
```

You can see on the [documentation](https://aws.github.io/amazon-chime-sdk-js/) use case #12 how to implement the active speaker detector interface.

It might be an issue with the meetingSession that youre subscribing to. A ended meeting can occur automatically for [these reasons](https://answers.chime.aws/questions/606/how-does-chime-decide-when-to-end-a-meeting.html#:~:text=Chime%20checks%20every%205%20minutes,state%20changes%2C%20for%2030%20minutes.).

**Comment by devalevenkatesh** [comment]
We are closing this issue due to in-activity, please feel free to create a new if you need more help.
