### ISSUE TITLE
Remote video tile stops automatically after few seconds

### ISSUE THREAD

**Issue by gsudhanshu** [aws/amazon-chime-sdk-js#1411]
@devalevenkatesh @michhyun1 

We are trying to create a conference section to our chime meeting app in which different attendees join and their remote video tiles appear side by side. It was working just fine and then we added some code to display names of attendees and the remote video tile would disappear after few seconds of joining. Not able to figure out why.

looking at logs found this piece: no active meeting and peer connection
which is very surprising as we have 2 attendees in the meeting.

Detailed logs attached. chime meeting id: 73675cb0-e03c-4c56-bd29-ed08e3670706
[localhost-1625260842005.log](https://github.com/aws/amazon-chime-sdk-js/files/6759513/localhost-1625260842005.log)

**Comment by gsudhanshu** [comment]
@ltrung any suggestions?

**Comment by michhyun1** [comment]
@gsudhanshu I am seeing this log: 
```
main.83c509f2df177fe1e327.js:1 ERROR TypeError: Cannot read property 'audioVideo' of undefined
    at e.startAudioPreview (main.83c509f2df177fe1e327.js:1)
    at e.ngOnInit (main.83c509f2df177fe1e327.js:1)
    at hn (main.83c509f2df177fe1e327.js:1)
    at dn (main.83c509f2df177fe1e327.js:1)
    at cn (main.83c509f2df177fe1e327.js:1)
    at as (main.83c509f2df177fe1e327.js:1)
    at As (main.83c509f2df177fe1e327.js:1)
    at main.83c509f2df177fe1e327.js:1
    at as (main.83c509f2df177fe1e327.js:1)
    at As (main.83c509f2df177fe1e327.js:1)
```

and also:

```
nr @ main.83c509f2df177fe1e327.js:1
:8001/socket.io/?EIO=4&transport=polling&t=NfmHq4P:1 Failed to load resource: net::ERR_CONNECTION_REFUSED
4main.83c509f2df177fe1e327.js:1 ERROR TypeError: Cannot read property 'length' of undefined
    at template (main.83c509f2df177fe1e327.js:1)
```

This seems to be related to your implementation. Perhaps you should double check the startAudioPreview implementation to make sure a audioVideo instance is created before calling startVideoPreview. And for the second log, I'm not sure what youre trying to do, but there is an error there as well.

**Comment by devalevenkatesh** [comment]
We are closing this issue due to in-activity, please feel free to create a new if you need more help.
