### ISSUE TITLE
What does "Bump maxVideos limit from 16 to 25" means ?

### ISSUE THREAD

**Issue by rlebosse** [aws/amazon-chime-sdk-js#1412]
I've seen that the PR [Bump maxVideos limit to 25](https://github.com/aws/amazon-chime-sdk-js/pull/1365) was released in the version 2.12.0.

Does this mean that from now, the maximum of simultaneous videos in a meeting is 25 (and not 16 anymore) ?
Has the switch been done automatically on Amazon Chime servers side or do we need to do something to pass from 16 to 25 videos ?

In the https://docs.aws.amazon.com/chime/latest/dg/meetings-sdk.html page, it still says that the limit of video tiles per meeting is **16**. That's why I'm confused.

Thanks in advance !

**Comment by dnnejo** [comment]
The number of video tiles is listed as an adjustable service-side enforced quota, with a default number of 16.  If adjusted, customers needed to "edit" the SDK to remove the hardcoded "16".  This change allows those customers to use the SDK direct from NPM without any edits.
You can request an increase for the number of video tiles via the AWS Console, Service Quotas, Amazon Chime in the US-EAST-1 region.

**Comment by michhyun1** [comment]
@rlebosse I'll close this issue for now - please reopen if necessary.
