### ISSUE TITLE
TypeError: Cannot read property 'configuration' of undefined

### ISSUE THREAD

**Issue by vsimeikoKG** [aws/amazon-chime-sdk-js#1413]
**Meeting and attendee IDs:**
Chime meeting ID - ef24957f-aee5-47bd-a619-bff799030706, 6e209c45-a16c-4f87-b023-ff34cd640706
Chime attendee ID - 90d90753-7325-ef91-942e-7d2e90044792 (attendee ID changes every time when user changes the room)

**Timeline**
- User joins room A
- User joins room B
- User joins room A
- Repeat until the error happens

**Describe the bug**
Sometimes when user changes the room (meeting) it would throw an error in the console. Meeting seems to continue to work normally, but sometimes camera LED indicator may stay ON forever.

**Screenshots**
![image](https://user-images.githubusercontent.com/72414337/124631783-b7111780-de51-11eb-805a-319c9633215e.png)

**Additional Info**
Every time when user changes the room, we do the following:
1) Destroy current Chime meetingSession object.
2) Initialize a new Chime meetingSession object as per documentation.

Chime object destroy function:
```js
  // Destroy Chime session.
  const destroySession = (callback = null) => {
    if (!meetingSession.current) {
      return;
    }

    isDestroyingRef.current = true;

    const session = meetingSession.current;

    // Stop the meeting and destroy object.
    const destroy = async () => {
      // Stop video, audio, and the session.
      await session.audioVideo.chooseVideoInputDevice(null);
      await session.audioVideo.chooseVideoInputDevice(null);
      session.audioVideo.stopLocalVideoTile();
      session.audioVideo.realtimeMuteLocalAudio();
      session.audioVideo.stop();

      // Clear up audio indicator handlers.
      Object.values(setRemoteAudioStatusRef.current).forEach((handler) => handler.unsubscribe());

      setRemoteAudioStatusRef.current = {};

      // Destroy session object.
      session.destroy().then(() => {
        meetingSession.current = null;
        isDestroyingRef.current = false;

        if (callback) {
          callback();
        }

        console.debug('Meeting Session - Destroyed');
      });
    };

    // Stop screenshare and kill session.
    if (isSharingScreen) {
      session.audioVideo.addContentShareObserver({
        contentShareDidStop() {
          globalDispatch(setScreenShare(null));
          destroy();
        },
      });

      session.audioVideo.stopContentShare();
    } else {
      destroy();
    }
  };
```

**Platform**
 - OS: macOS 10.15.7 (19H114)
 - Browser: Chrome
 - Browser Version: Version 91.0.4472.101 (Official Build) (x86_64)
 - Amazon Chime SDK GitHub Commit: 2.12.0

[Chime undefined error.log](https://github.com/aws/amazon-chime-sdk-js/files/6771296/Chime.undefined.error.log)

**Comment by devalevenkatesh** [comment]
Hello, Thanks for reporting this issue.

From the logs, the meeting session destroyed line appears actually before the `audioVideo.stop()` completes.

Can you please check below points if it solves your issue?
1. await the `destory()` calls in your code.
2. As a different approach, can you implement [`audioVideoDidStop`](https://aws.github.io/amazon-chime-sdk-js/interfaces/audiovideoobserver.html#audiovideodidstop) AudioVideoObserver. This observer will receive the meeting session status once the user leaves a meeting or drops from the meeting. We in our JS SDK demo clean up resources in this observer. Below is the link to the demo code.
https://github.com/aws/amazon-chime-sdk-js/blob/d9f008442ec833957bb54c8a86b775ce48f08b11/demos/browser/app/meetingV2/meetingV2.ts#L2619-L2680
3. Cleaning it up correctly by point 2 should stop the camera LED. I suspect if the `chooseVideoInputDevice` with `null` completes after few other calls running.

Now for the undefined configuration:
The screenshot shows that the error triggered in the callback passed to `realtimeSetAttendeeIdPresence` API. Could you please check if you are unsubscribing from the attached callback using `realtimeUnsubscribeToAttendeeIdPresence(handler)` when you destroy the meeting session?

I think there are two problems here. First, the meeting session not getting destroyed correctly and second, the configuration is not getting set correctly when you create the new meeting session. Let us know if above discussed point help.

**Comment by vidya-mohan** [comment]
Resolving as couldnt proceed
