### ISSUE TITLE
TypeError: undefined is not an object (evaluating 'navigator.mediaDevices.enumerateDevices')

### ISSUE THREAD

**Issue by shriyajuneja** [aws/amazon-chime-sdk-js#1417]
**Meeting and attendee IDs:**

MeetingId: "3ac92b55-efcb-4b4c-9cc2-4dc15e4f0706"
AttendeeId: "2884a91f-e183-cf34-355f-6cf880193862"

**Describe the bug**
try running demo meeting in chrome on iPhone 12 mini 

**Screenshots**
![Image from iOS](https://user-images.githubusercontent.com/14612003/124816829-9a2a3080-df86-11eb-98b3-387465054fb5.png)

**Platform**
 - OS: iOS 14.2
 - Browser: Google Chrome
 - Browser Version: 91.0.4472.80
 - Amazon Chime SDK version: 2.13.0
 - Phone: iPhone 12 mini

**Comment by michhyun1** [comment]
@shriyajuneja Thanks for bringing this to our attention - which meeting url are you joining? I just tried joining my serverless meeting demo from iOS chrome with no issues, but I am using an iPhone 11.

**Comment by shriyajuneja** [comment]
I am trying browser demo, It's working fine for me in iPhone 11, iPhone X, iPhone 12 and 12 pro, This issue comes only in iPhone 12 mini and is reproducible on BrowserStack iOS chrome too.

**Comment by michhyun1** [comment]
@shriyajuneja Can you please try upgrading to 14.3. I just noticed you're on 14.2 still. https://blog.bitsrc.io/ios-14-3-brings-webrtc-to-wkwebview-closing-gap-on-ios-accessibility-90a83fa6bda2

**Comment by michhyun1** [comment]
@shriyajuneja Can you confirm if this resolved your issue? Thanks

**Comment by shriyajuneja** [comment]
Yes, it resolved the issue. Thanks.

**Comment by shriyajuneja** [comment]
Hi @michhyun1 [documentation](https://docs.aws.amazon.com/chime/latest/dg/meetings-sdk.html#mtg-browsers) says supported browsers are Google Chrome for Android and iOS (10.0 and later) but I had to update iOS to 14.3. Can we update it in documentation ?

**Comment by michhyun1** [comment]
@shriyajuneja thanks for bringing this to our attention. I'll be sure to make the necessary changes. Thanks. I'll go ahead and close this ticket again.
