### ISSUE TITLE
Facing high cpu usage when multiple users turns the webcam on

### ISSUE THREAD

**Issue by suman2755** [aws/amazon-chime-sdk-js#1419]
We are seeing an issue with cameras flickering, freezing, and in some cases turning off.
We have noticed that each time an user turns the webcam on the CPU % increase.
We noticed that each time an user turns the webcam on the CPU % increase. If we all have our camera off it’s fine. Every time someone turned their camera on CPU increased causing freezing. For instance one person turned camera on CPU was at 10% and at some point it reached 60%

Any solution for this?

**Comment by michhyun1** [comment]
@suman2755 Thanks for using the Chime SDK for Javascript. Could you please provide more details about your use case? Have you tried running the server-less meeting demo? Perhaps you can compare your implementation with the demo to see if there are any discrepancies that might be causing the high CPU usage. Also, for future reference, could you please complete the issue template form so that we can help you as best as we can. Thanks.

**Comment by suman2755** [comment]
@michhyun1 Thanks for the reply. Regarding our use case. We have hosted serverless chime application and our clients are using that. Several clients have reported cameras flickering, freezing, and in some cases turning off. At first, we believed it may be down to internet connectivity but we've had several cases where clients have been in the same room/building (in one scenario sitting next to one another) with the same internet connection and computers, but have different experiences on both the laptops. One computer flickering and the other fine, and reports of all computers having issues with different users cameras.

We have followed the same guidlines as with demo meeting and don't see any discrepancies.
We are using **amazon-chime-sdk-js version of 2.11.0.** 

Please let me know. if you need any further information.

**Comment by michhyun1** [comment]
@suman2755 If you could, would you mind filing a ticket through the support queue so that we can assist you further? Thanks. https://github.com/aws/amazon-chime-sdk-js#troubleshooting-and-support
