### ISSUE TITLE
Amazon Chime messaging application

### ISSUE THREAD

**Issue by soroka-ihor** [aws/amazon-chime-sdk-js#1420]
### What are you trying to do?

I'm trying to create a messaging application, using Amazon Chime SDK (java).

 I figured out with creating appInstanceUser, messageChannel, adding this user to the channel and send a message to it. 

I've finished with my backend layer, and trying to impelement client interface. But I can't understand how to send messages in real time. I'm completely new to JS and TS, so I find it difficult to image what's going on in the example *messagingSession* app.

I'm right, that for sending messages I must to have:

1) AWS creds;
2) instanceArn;
3) instanceUserArn

What is next? 

### How can the documentation be improved to help your use case?

*Please, begging you, please add sending message feature to the messagingSession example*

### What documentation have you looked at so far?

*Amazon Chime SDK Developer Tutorial, Amazon Chime API.*

P.S. I'm really sorry for sending this kind of garbage comment here, but I'm really want to figure out how it actually works. Thanks for any effort!

**Comment by ldai1** [comment]
Hi,

Thanks for using Amazon Chime SDK. 

You can go here to check our sample code for sending messages: https://github.com/aws-samples/amazon-chime-sdk/tree/main/apps/chat. It also has a full messaging example.

Basically you need to do is to setup a messaging session and subscribe to messagingSessionDidReceiveMessage as shown in this example https://github.com/aws/amazon-chime-sdk-js/blob/master/demos/browser/app/messagingSession/messagingSession.ts.

Hope this is helpful. Let me know if you need any additional help.

**Comment by soroka-ihor** [comment]
Hi @ldai1 ,

Thanks for that fast reply! I'm gonna try to deal with react example you linked, and will let you know if I figured it out
