### ISSUE TITLE
How to establish a connection between the Web meeting and the Mongo DB.

### ISSUE THREAD

**Issue by rnqayush** [aws/amazon-chime-sdk-js#1424]
hello team,,
1- i have a react native chime meeting app for Edtech which is connected to mongoDB. teacher can specify a time in that app and attendees can join in during that specified time. Also the app is programmed to end after 60 minutes from starting of meeting.

2- we are sending a link to attendees email and they have option to join with app or amazon-chime-sdk-js meeting url .

3- I want to set the same logic which is applied to our app so that attendees which are joining through amazon-chime-sdk-js web meeting url can only join when meeting has started at a specifiied time.

4- i want amazon-chime-sdk-js meeting url to get linked with mongoDb database for achieving this because all the time for starting meetings is getting stored in there.

5- Kindly suggest right approach to resolve this.

**Comment by rnqayush** [comment]
Still waiting for the response, Kindly help me with this

**Comment by devalevenkatesh** [comment]
Hi @rnqayush,

There may be different approaches but here is an approach that can help. You would have to create a scheduler and a polling mechanism to check whether a meeting can be created say some X minutes before your scheduled start of the meeting.

The scheduler will create/update a table in the MongoDB which will hold the scheduled meeting and its status (INACTIVE | CREATE | ACTIVE). When a meeting is to be scheduled you can store the details necessary to create a meeting in this table setting the status to INACTIVE initially. This table will also have the meeting start time.

The polling logic based on an timed interval will check whether any meeting (or meetings) can be activated if reaching a scheduled time in the same table. Once, you find that any meeting is to be activated, you can then set it to CREATE and then call the [`CreateMeeting`](https://docs.aws.amazon.com/chime/latest/APIReference/API_CreateMeeting.html) API and store the response or later use [`GetMeeting`](https://docs.aws.amazon.com/chime/latest/APIReference/API_GetMeeting.html) API to get the meeting details. This way you would create a meeting at the scheduled time. Once a meeting is created you can set the status to ACTIVE.

Now, anyone hitting a link you have shared can get a message that "the meeting is not yet active" or "not started by the teacher", if you find that the table in MongoDB has the meeting status as INACTIVE. If the hit receives a ACTIVE state meeting, you can return the meeting details received from `CreateMeeting` API or `GetMeeting` API response and create the attendee using [`CreateAttendee`](https://docs.aws.amazon.com/chime/latest/APIReference/API_CreateAttendee.html) API and then join them. While creating meeting if you know the attendees already you can use [`CreateMeetingWithAttendees`](https://docs.aws.amazon.com/chime/latest/APIReference/API_CreateMeetingWithAttendees.html) API.

With the hit from your shared URL and if a meeting is active, you would require to give back the meeting and attendee info from the backend and then the frontend can follow the steps to a create JS SDK the meeting session and join it. Check our [API overview guide](https://aws.github.io/amazon-chime-sdk-js/modules/apioverview.html) for more information on the steps.

Hope this helps you.

**Comment by rnqayush** [comment]
thank you @devalevenkatesh for your reply, I understand completely whatever you have suggested But my concern is this that i want to start meeting at a specific time and attendee should not be able to join that meeting before a particular time.
 I have my time details stored in my database. So in order to get that time i will have to make an api call so that i can set when to allow attendees to start . 
Now i am not able to understand where should i set my api inside amazon-chime-sdk-js to make it working and also will axios or http will work to make an api call?

**Comment by devalevenkatesh** [comment]
As explained this feature would have to be implemented on your side and you do not need to implement the API inside the `amazon-chime-sdk-js`. You have to implement these `fetch` calls in your front end application logic where you would handle a user loading your webpage. Your front-end will need to make the HTTP calls to your backend which will provide you either with the status of the meeting or the meeting creation response. The backend would be working with MongoDB.

So, on the front-end where you handle an attendee loading the join page, you can check using Browser APIs such as using `load` event to know that the join page is getting loaded and then you can make the call to your backend to know whats the meeting status and so on (just an example, check links below for various ways to make the HTTP calls to your backend). I do not know what is your front-end framework but you can make HTTP Fetch calls using browser implemented Fetch API or axios to your backend and correspondingly re-direct your attendee.

Sorry, I am also not sure if you are aware of making HTTP calls from your front-end code. Hence, I found few resources below which may help you:
- https://www.freecodecamp.org/news/here-is-the-most-popular-ways-to-make-an-http-request-in-javascript-954ce8c95aaa/
- https://levelup.gitconnected.com/all-possible-ways-of-making-an-api-call-in-plain-javascript-c0dee3c11b8b

**Comment by devalevenkatesh** [comment]
We are closing this issue now. Please feel free to create new one for any further help.
