### ISSUE TITLE
WebSocket connection fails signal.*.app.chime

### ISSUE THREAD

**Issue by peili** [aws/amazon-chime-sdk-js#1427]
Amazon Chime MeetingId: 495ec176-4fb6-4879-9fda-3bb584050706
We're experiencing issues with the WebSocket connection. They intermittently fail for some users.

Chime JS SDK version: 2.12.0

chunk-vendors.163d6223.js:2684 WebSocket connection to 'wss://signal.m1.ue1.app.chime.aws/control/495ec176-4fb6-4879-9fda-3bb584050706?X-Chime-Control-Protocol-Version=3&X-Amzn-Chime-Send-Close-On-Error=1&X-Amzn-Version=2.12.0&X-Amzn-User-Agent=chrome-91' failed: WebSocket is closed before the connection is established.

<img width="906" alt="CleanShot 2021-07-12 at 12 40 54@2x" src="https://user-images.githubusercontent.com/1823148/125282726-ff2fae80-e317-11eb-9329-ca93fa2258f5.png">
<img width="1345" alt="CleanShot 2021-07-12 at 12 40 43@2x" src="https://user-images.githubusercontent.com/1823148/125282732-0060db80-e318-11eb-99f6-8d953d0c3e5a.png">

**Comment by ldai1** [comment]
Hi,

Thanks for reporting the issue. Is that possible to provide more logs from the console? The console log will probably will have api response like `TaskFailed` or `SignalingBadRequest`. you will probably see those [status code](https://aws.github.io/amazon-chime-sdk-js/enums/meetingsessionstatuscode.html) for an unexpected meeting ended session.

Also have you implemented any observers like `connectionHealthDidChange` or `audioVideoDidStartConnecting` that can tell your connection health status and connection, reconnection activities.

**Comment by peili** [comment]
@ldai1 Unfortunately that's the only log, that the WebSocket connection failed.

**Comment by devalevenkatesh** [comment]
Hi @peili ,

Could you please check our [Networking FAQs](https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html#networking) if you find any configuration changes on the affected laptops like blocking any ports? Checking if we can rule out if that's an issue.

**Comment by peili** [comment]
> Hi @peili ,

It was an intermittent issue and only affected users in Europe connecting to US East (N. Virginia), that's why I don't think it's caused by blocked ports / Firewall restrictions, because that would be permanent. Currently we can't reproduce it anymore.

**Comment by michhyun1** [comment]
@peili I'm going to close this issue for now - it seems as if it was a transient issue. If you could please open a new issue if this occurs again and please provide all of the information in the new issue template so that its easier for us to debug the issue. Please include the meeting and attendeeId as well. Thanks
