### ISSUE TITLE
Messaging in real time

### ISSUE THREAD

**Issue by i-soroka** [aws/amazon-chime-sdk-js#1429]
### What are you trying to do?

*I'm trying to add real time chating feature to this https://github.com/aws/amazon-chime-sdk-js/tree/master/demos/browser/app/messagingSession example. Could you please, if it even possible, provide me with steps, those I basically need to do?*

### How can the documentation be improved to help your use case?

*Would be great if you add this feature as an official example.*

**Comment by i-soroka** [comment]
@ltrung hi and thank you. This example doesn't run on Windows — i tried it on a few Windows machines, and result the same: the app has started but nothing is available on localhost:3000 or localhost:9000 
![stuck](https://user-images.githubusercontent.com/80392255/125734640-97a373e8-6b77-4e82-b1b7-303796733d55.PNG)

**Comment by ltrung** [comment]
Could you try to use `https://localhost:9000` instead? You may need to ignore a security warning but it worked for me in Windows.

**Comment by i-soroka** [comment]
@ltrung just tried with https on 9000 port, and it says that it is unsecure connection with expired SSL cert.

**Comment by i-soroka** [comment]
@ltrung okay i've fixed it. In webpack.config.js change 'https' to 'false', and 'host' to 'localhost' and it works.
