### ISSUE TITLE
502 while starting media capture

### ISSUE THREAD

**Issue by Dev-shubham45** [aws/amazon-chime-sdk-js#1490]
### What happened and what did you expect to happen?

Getting 502 error while starting and ending media capture from demo app.

### Have you reviewed our existing documentation?

- [X] GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [X] FAQs [page](https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html)
- [X] README [page](https://github.com/aws/amazon-chime-sdk-js#amazon-chime-sdk-for-javascript)
- [X] Feature-specific [guides](https://github.com/aws/amazon-chime-sdk-js#guides)

### Reproduction steps

Deploy chime serverles demo app.
start recording/end recording

### Amazon Chime SDK for JavaScript version

Latest

### What browsers are you seeing the problem on?

Chrome

### Browser version

Chrome version 92

### Browser console logs

![image](https://user-images.githubusercontent.com/88028397/128240495-b8be730a-18af-4e59-a982-bfc9a7cf181b.png)

**Comment by anuranduttaroy** [comment]
Hey @Dev-shubham45 thanks for reporting the issue. In order to help us debug it, could you provide us the `INFO` level logs of the session when you are seeing this error?

Also, one more thing to confirm, did you see any errors while deploying the serverless demo with the media capture functionality?

**Comment by achris** [comment]
Also double check that you provided the `-o` option when deploying the serverless demo (see https://github.com/aws/amazon-chime-sdk-js/blob/master/demos/serverless/README.md#media-capture ).  If you did it should have created a bunch of S3 buckets in your account as part of deploying.

**Comment by vidya-mohan** [comment]
Resolving as couldnt proceed
