### ISSUE TITLE
[Question] Screen Share in mobile environment

### ISSUE THREAD

**Issue by gsphyo91** [aws/amazon-chime-sdk-js#1493]
I am developing a video meeting service using Javascript SDK.
I want to provide the same service for Android and iOS. However, Screen Share does not work in the mobile browser.

Is there a way to provide Screen Share in a mobile environment using Javascript SDK without using Android SDK or iOS SDK?

**Comment by ltrung** [comment]
@gsphyo91 JS SDK relies on `GetDisplayMedia` to capture screen from browser. Unfortunately, this is not available in mobile browsers for now: https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getDisplayMedia.
