### ISSUE TITLE
Chime meeting session is not expiring

### ISSUE THREAD

**Issue by tapaskdhar** [aws/amazon-chime-sdk-js#1496]
### What happened and what did you expect to happen?

Chime meeting session is not ending consistently even though there is inactivity for several days.

### Have you reviewed our existing documentation?

- [X] GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [X] FAQs [page](https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html)
- [X] README [page](https://github.com/aws/amazon-chime-sdk-js#amazon-chime-sdk-for-javascript)
- [X] Feature-specific [guides](https://github.com/aws/amazon-chime-sdk-js#guides)

### Reproduction steps

-

### Amazon Chime SDK for JavaScript version

chime sdk version 2.11.0

### What browsers are you seeing the problem on?

Chorme , Firefox ,safari

### Browser version

Chorme , Firefox ,safari

### Browser console logs

-

**Comment by devalevenkatesh** [comment]
Hello @tapaskdhar ,

Thanks for reporting the issue.

Could you please let us know what is the Chime meeting session, is it the `DefaultMeetingSession` you created using the Amazon Chime SDK for JavaScript? Could you please clarify more on "Chime meeting session not ending"?

The meetings end when you run the [`DeleteMeeting`](https://docs.aws.amazon.com/chime/latest/APIReference/API_DeleteMeeting.html) API action. A meeting automatically ends after a period of inactivity, such as the following:
- No audio connections are present in the meeting for more than five minutes.
- Less than two audio connections are present in the meeting for more than 30 minutes.
- Screen share viewer connections are inactive for more than 30 minutes.
- The meeting time exceeds 24 hours.

Are you calling `chimeSDKMeetingSession.audioVideo.stop()` to leave and end the Amazon Chime JS SDK meeting session?

We would want the `meetingId` to check this issue further, so request you to provide meeting IDs for such scenarios.

**Comment by vidya-mohan** [comment]
Resolving as couldnt proceed
