### ISSUE TITLE
Can I use 25 video tiles without to AWS request?

### ISSUE THREAD

**Issue by rusicsemenov** [aws/amazon-chime-sdk-js#1497]
I updated our application to SDK v2.12.0, and can't use 25 video tiles. Only 16 video tiles actives, each participant have a different active video channel. I should write a request to increase video? 
Here is example:
![image](https://user-images.githubusercontent.com/20163858/128624234-3bb0c7bb-55d0-4694-ab82-2fb906d34f36.png)

Thank you for your attention

**Comment by lzongkun** [comment]
Hi,

Thanks for reaching out!
Currently you will still have to submit a limit increase request via the console to be able to adopt that feature since it is not GA-ed yet.

**Comment by vidya-mohan** [comment]
@rusicsemenov this feature is released so you won't need to make limit increases anymore. If you are using the [Amazon Chime React Components](https://github.com/aws/amazon-chime-sdk-component-library-react), the VideoGrid should support this limit.

I am resolving this ticket

**Comment by Rambarani** [comment]
@rusicsemenov I need your help, how you added video tile image if user didn't turned on camera and name and mute status over it.

**Comment by rusicsemenov** [comment]
@Rambarani Hello, I have written a new app on the vuejs and this background on the tile from me. You can make the default background for tile.

**Comment by Rambarani** [comment]
Okay thank you for the reply @rusicsemenov .  Mine is react and I have used their official SDK https://github.com/aws/amazon-chime-sdk-component-library-react . not able to customize tile or show mute and unmute status. once again thank you.
