### ISSUE TITLE
Chime error over constrained while starting the call

### ISSUE THREAD

**Issue by abhinavOmni** [aws/amazon-chime-sdk-js#1502]
### What happened and what did you expect to happen?

![image](https://user-images.githubusercontent.com/71629015/128967573-d038548f-8d1e-4912-af1f-18687db23a3a.png)

### Have you reviewed our existing documentation?

- [X] GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [X] FAQs [page](https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html)
- [X] README [page](https://github.com/aws/amazon-chime-sdk-js#amazon-chime-sdk-for-javascript)
- [X] Feature-specific [guides](https://github.com/aws/amazon-chime-sdk-js#guides)

### Reproduction steps

starting the call from any browser like chrome or chrome incognito.
this is running good for sometime and suddenly get this issue pls help..

![image](https://user-images.githubusercontent.com/71629015/128967671-015a5e63-b436-491e-839b-06abc9aa290d.png)

### Amazon Chime SDK for JavaScript version

  "amazon-chime-sdk-js": "^2.7.0",    "aws-sdk": "^2.816.0",

### What browsers are you seeing the problem on?

chrome and chrome incognito

### Browser version

chrome 80 and above

### Meeting and Attendee ID Information.

{
  "JoinInfo": {
    "Meeting": {
      "Meeting": {
        "MeetingId": "24fd8dd5-7507-48f9-89db-04b0cb160706",
        "ExternalMeetingId": "233Ih0YxBthUqKOzHOCj",
        "MediaPlacement": {
          "AudioHostUrl": "37064670ad434b86b63a4ab3ad5bd2a2.k.m3.ue2.app.chime.aws:3478",
          "AudioFallbackUrl": "wss://haxrp.m3.ue2.app.chime.aws:443/calls/24fd8dd5-7507-48f9-89db-04b0cb160706",
          "ScreenDataUrl": "wss://bitpw.m3.ue2.app.chime.aws:443/v2/screen/24fd8dd5-7507-48f9-89db-04b0cb160706",
          "ScreenSharingUrl": "wss://bitpw.m3.ue2.app.chime.aws:443/v2/screen/24fd8dd5-7507-48f9-89db-04b0cb160706",
          "ScreenViewingUrl": "wss://bitpw.m3.ue2.app.chime.aws:443/ws/connect?passcode=null&viewer_uuid=null&X-BitHub-Call-Id=24fd8dd5-7507-48f9-89db-04b0cb160706",
          "SignalingUrl": "wss://signal.m3.ue2.app.chime.aws/control/24fd8dd5-7507-48f9-89db-04b0cb160706",
          "TurnControlUrl": "https://ccp.cp.ue1.app.chime.aws/v2/turn_sessions"
        },
        "MediaRegion": "us-east-2"
      }
    },
    "Attendee": {
      "Attendee": {
        "ExternalUserId": "8c8ac817#Sunitha$126347243",
        "AttendeeId": "2f7d538a-263e-fff4-0c94-da4c4d6b5554",
        "JoinToken": "MmY3ZDUzOGEtMjYzZS1mZmY0LTBjOTQtZGE0YzRkNmI1NTU0OjI5ODNkYWY0LTI0NzItNGM5Zi04YmJlLTI4NzI5ZWIwMWQyNQ"
      }
    }
  }
}

### Browser console logs

![image](https://user-images.githubusercontent.com/71629015/128969077-e87bd018-cfb7-42bf-b1b2-ec3d08339766.png)

**Comment by abhinavOmni** [comment]
Its working in same machine for many days and suddenly we found this issue..

**Comment by michhyun1** [comment]
Can you please clarify exactly the api call you are making? Thanks.

**Comment by abhinavOmni** [comment]
we did not call any method getUserMedia, we just call the chime.slayt.io api.

**Comment by michhyun1** [comment]
@abhinavOmni Can you please confirm that you've granted permissions to your media devices before joining the meeting?

**Comment by abhinavOmni** [comment]
Yes we have granted.

**Comment by devalevenkatesh** [comment]
Hello, could you please provide all the browser console logs for this error?

We would need the entire console logs (137 messages) shown in the attached image.
