### ISSUE TITLE
Outbound call attendee not presence in meeting unless they hit a digit on keypad

### ISSUE THREAD

**Issue by brianinator** [aws/amazon-chime-sdk-js#1509]
### What happened and what did you expect to happen?

An attendee on the phone has audio of other attendees but `realtimeSubscribeToAttendeeIdPresence` has **not** been invoked until they have hit a digit on keypad. I expected `realtimeSubscribeToAttendeeIdPresence` immediately once they answered the call. It can take sometimes up to 3 to 5 minutes for it to be invoked.

### Have you reviewed our existing documentation?

- [X] GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [X] FAQs [page](https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html)
- [X] README [page](https://github.com/aws/amazon-chime-sdk-js#amazon-chime-sdk-for-javascript)
- [X] Feature-specific [guides](https://github.com/aws/amazon-chime-sdk-js#guides)

### Reproduction steps

**Pre-condition**: SipMediaApplication + Lambda function (with JoinMeeting action)

1. Create a meeting.
2. Create a webRTC attendee.
3. Start meeting session.
4. Create an attendee.
5. Call this attendee. (using CreateSipMediaApplicationCall)
6. Answer call.

**Note:** I have not been able to reproduce this 100 % of the time.

### Amazon Chime SDK for JavaScript version

2.7.0

### What browsers are you seeing the problem on?

Firefox

### Browser version

90.0.2

### Meeting and Attendee ID Information.

In the logs, the attendee ID 01d93c26-4887-cf4b-20ff-fcb514d0fae0 is the caller with the issue.

### Browser console logs

[console-export-2021-8-13_11-55-35.txt](https://github.com/aws/amazon-chime-sdk-js/files/6983886/console-export-2021-8-13_11-55-35.txt)

**Comment by haifengx** [comment]
We deployed a server side change to fix the issue (no Chime SDK upgrade needed). Please test again and reopen if you are still seeing the issue. Thanks!
