### ISSUE TITLE
Potential WebRTC conflicts with other audio/video WebRTC based frameworks

### ISSUE THREAD

**Issue by russellc92** [aws/amazon-chime-sdk-js#1510]
### What are you trying to do?

As part of a front end application (React)
- Use the Chime SDK for normal purposes (join meetings etc).
- Use AWS KVS WebRTC service (or any other third party audio webrtc based framework)

Question:

Considering both Chime SDK and AWS KVS WebRTC use webRtc under the hood, could there be a collision when used together? 

Specifically in my case; Chime SDK to retrieve audio and video (one SDK meeting session per user tab), AWS KVS WebRTC to send and receive audio (NOT video)(One KVS WebRTC connection per user tab). 
Will the users browsers API be able to handle this?

Reference Issue: #559 

### How can the documentation be improved to help your use case?

Potentially a section on the using Chime SDK in conjuction with other libs/frameworks to that use WebRTC (specifically audio/video)

### What documentation have you looked at so far?
https://docs.aws.amazon.com/chime/latest/dg/meetings-sdk.html
https://aws.github.io/amazon-chime-sdk-js/index.html
https://www.html5rocks.com/en/tutorials/webrtc/basics/

Thank you

**Comment by ldai1** [comment]
Hi, thanks for using Chime JS SDK. In a WebRTC-based application, you create an instance of RTCPeerConnection to transmit audio/video stream. In our JS SDK, we also create a single instance of RTCPeerConnection.The following example shows that you can use multiple instances of RTCPeerConnection object: https://webrtc.github.io/samples/src/content/peerconnection/multiple/.

Theoretically your proposal should work, but we 've never tried integrating AWS KVS WebRTC into our demo app. I think you can try it. Let me know if it doesn't work for your case.

**Comment by vidya-mohan** [comment]
@russellc92 hope the suggestion was helpful. Our ports are documented in https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html#what-are-the-subnets-and-ports-used-by-an-application-using-the-aws-sdk and if not used by KVS, should be fine
