### ISSUE TITLE
Buzzing sound when checking audio output on ipad

### ISSUE THREAD

**Issue by leannepatmoretsl** [aws/amazon-chime-sdk-js#1515]
### What happened and what did you expect to happen?

When running the meetingReadinessChecker demo after confirming or denying the audio output check there is a buzzing that plays afterwards. This is also happening in our own project when using `checkAudioOutput`. I believe this could be caused by disconnecting the `oscillatorNode` and `gainNode` in `stopTone`, as removing this code solves the issue.

I am able to create this on an iPad mini iOS 14.0, but not on an iPad iOS 14.6.

### Have you reviewed our existing documentation?

- [X] GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [X] FAQs [page](https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html)
- [X] README [page](https://github.com/aws/amazon-chime-sdk-js#amazon-chime-sdk-for-javascript)
- [X] Feature-specific [guides](https://github.com/aws/amazon-chime-sdk-js#guides)

### Reproduction steps

- Run the meeting readiness checker demo on an iPad
- Click check my device
- Select Play Tone
- Select Yes
- Buzzing will happen

### Amazon Chime SDK for JavaScript version

2.15.0

### What browsers are you seeing the problem on?

Safari 

### Browser version

14

### Browser console logs

[Console.txt](https://github.com/aws/amazon-chime-sdk-js/files/7000676/Console.txt)

**Comment by ldai1** [comment]
Hi,

We will reproduce the issue using the device and platform version that you mentioned share our findings here. Thanks for reporting the issue.

**Comment by ldai1** [comment]
Hi,

I tried to reproduce the issue on my device with following info:

Device and operation system: IPad 14.0
Borwser: Safari
Chime JS SDK version: 2.17.0

There was no buzzing happened during my test. Could you try to test again against the latest version of JS SDK 2.17.0 and see if you can reproduce the issue? If you still see the issue, can you record it and attach the recording to this ticket? Thanks!
