### ISSUE TITLE
Document Content Security Policy

### ISSUE THREAD

**Issue by richnew10** [aws/amazon-chime-sdk-js#1518]
Sophisticated customers will try to figure this out on their own, and might do so incorrectly.

Additionally, we should think about how to support customers whose CSP configuration is causing issues: e.g., blocking WebSockets.

**Comment by ldai1** [comment]
We talked about using [SecurityPolicyViolationEvent](https://developer.mozilla.org/en-US/docs/Web/API/SecurityPolicyViolationEvent). Also we probably can print out the signaling URLs that customers are using for a faster debugging. Will provide more information for the plans.

**Comment by ldai1** [comment]
Raise a pr for adding the csp setup guide and add a logging for blocked urls when there is CSP violation: https://github.com/aws/amazon-chime-sdk-js/pull/1556

**Comment by richnew10** [comment]
Resolved in #1620.
