### ISSUE TITLE
[Virtual Background] How to implement virtual background in Chime SDK?

### ISSUE THREAD

**Issue by mrnav90** [aws/amazon-chime-sdk-js#1529]
I also read document video processor: https://github.com/aws/amazon-chime-sdk-js/blob/master/guides/10_Video_Processor.md

Check more tutorial: 
https://dannadori.medium.com/amazon-chime-sdk-virtual-background-with-powerpoints-slides-9922d6afccee
https://dannadori.medium.com/google-meet-virtual-background-with-amazon-chime-sdk-34656a625fed

But can't implement with Chime SDK, could you please share document about that.
If Chime SDK do not ready for implement this, could you please tell me plan for development it?

Many thanks

**Comment by red62labs** [comment]
the danna dori tutorials work using BodyPix. This link should help you. I have tested it out.
https://github.com/FLECT-DEV-TEAM/LocalVideoEffector#readme

**Comment by mrnav90** [comment]
Hi @red62labs 
> the danna dori tutorials work using BodyPix. This link should help you. I have tested it out.
> https://github.com/FLECT-DEV-TEAM/LocalVideoEffector#readme

This tutorial not compatibility with Chime SDK because chime sdk using bind stream to element so I think we need a hook and setting video processor for virtual background.

@ldai1 Could you say anything about plan development? :(

Many thanks

**Comment by vidya-mohan** [comment]
@mrnav90 Could you help me understand the request better? Are you looking for an example of how to use the Video Processing APIs? If so, we have you looked at our demo application? The [APIs](https://github.com/aws/amazon-chime-sdk-js/blob/e72f9e85038230143f8aca7b300c91a41358b9b8/demos/browser/app/meetingV2/meetingV2.ts#L2341) are integrated there.

**Comment by mrnav90** [comment]
@vidya-mohan 
Currently, I'm researching how to implement virtual background in Chime SDK.
I know chime SDK have Video Processing API but I don't know how to implement that with virtual background.
I've check your demo application but this is tutorial for implement with bodyfix? right?
But how to implement virtual background with google-meet model?

Thanks

**Comment by vidya-mohan** [comment]
@ArtemZakharchuk @mrnav90 https://github.com/aws/amazon-chime-sdk-js/pull/1686 so resolving this

**Comment by vidya-mohan** [comment]
Another resource for background replacement that allow users to use background image (See PR https://github.com/aws/amazon-chime-sdk-js/pull/1920). This feature is available in NPM version 2.25.0. Feel free to try it out and let us know your feedback.
