### ISSUE TITLE
Any API to find out how much a said meeting cost?

### ISSUE THREAD

**Issue by red62labs** [aws/amazon-chime-sdk-js#1530]
### What are you trying to do?

trying to get the actual cost of the meeting that chime is charging.

### How can the documentation be improved to help your use case?

include an example of how to get the actual cost of the meeting, I currently use the start time and end time then calculate the cost.

### What documentation have you looked at so far?

getMeeting call the meeting object does not return the actual cost of the meeting

**Comment by ldai1** [comment]
Hi,

Thanks for using Chime JS SDK. Currently we are not exposing any APIs for cost calculation, but you can check here for more information:  https://aws.amazon.com/chime/chime-sdk/pricing/

**Comment by vidya-mohan** [comment]
Please check out our FAQs @ https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html#how-much-does-the-amazon-chime-sdk-cost

You can track your usage using Cost Explorer: https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html#do-i-get-billed-for-using-the-demos
