### ISSUE TITLE
Virtual background and blur background

### ISSUE THREAD

**Issue by qamrulhaque** [aws/amazon-chime-sdk-js#1533]
Is it possible to add virtual background or blur background in a video meeting?

If not available will there be any such feature in future so attendees can hide their actual background?

Thanks.

**Comment by vidya-mohan** [comment]
@qamrulhaque could you please help us with preserving the Bug or Feature Issue template so we can help you faster? The guide is captured https://aws.github.io/amazon-chime-sdk-js/modules/videoprocessor.html .

Our demos are integrated here : @ https://github.com/aws/amazon-chime-sdk-js/blob/e72f9e85038230143f8aca7b300c91a41358b9b8/demos/browser/app/meetingV2/meetingV2.ts#L2341

**Comment by ltrung** [comment]
@qamrulhaque Please check out #1686 that will add background blur to JS SDK.
