### ISSUE TITLE
[Question] Get the size of the screen being shared

### ISSUE THREAD

**Issue by gsphyo91** [aws/amazon-chime-sdk-js#1537]
I want to get the size of the screen being shared in the screen sharing function.

When screen sharing starts, the shared screen appears inside the video element, and depending on the size of the video element, white space is created on the left and right or top and bottom. 
Whenever the actual window size of the shared screen changes, the size of the shared screen within the video element also changes.

I want to get the size of the shared screen excluding the white space.

Whenever the actual window size of the shared screen changes, is there a way to get the horizontal and vertical dimensions of the screen?

Thank you.

**Comment by ltrung** [comment]
Close for now. Please reopen if you have any additional questions.
