### ISSUE TITLE
AudioVoiceFocus and Volume Input Control

### ISSUE THREAD

**Issue by majo35-6c** [aws/amazon-chime-sdk-js#1538]
SingleNodeAudioTransformDevice -> When i extends this class => I can control volume of mic
VoiceFocusDeviceTransformer - I can remove noise from AudioInput.

However i dont know how i can remove noise from my audioInput and also have options for control volume of audioInput.
Any idea ?

```
const spec = {
    variant: 'c50',
    executionPreference: 'auto',
  };
  
const transformer = await VoiceFocusDeviceTransformer.create(spec, {});

const volumeTransformDevice = new VolumeTransformDevice(audioInputId);
const vfDevice = await transformer.createTransformDevice(volumeTransformDevice);
await deviceController.chooseAudioInputDevice(vfDevice);
 
```
When i use voiceFocuse Device as wrapper of volumeTransformDevice only voiceFocus works.
```
vfDevice: {
 device: volumeTransformDevice {
  inner: audioInputId
 }
}
```
When i use  VolumeTransformationDevice as wrapper of vfDevice only volume control works.

VolumeTransformDevice code from:
https://aws.amazon.com/blogs/business-productivity/transforming-audio-and-shared-content-in-the-amazon-chime-sdk-for-javascript/

**Comment by majo35-6c** [comment]
In documentation:
Amazon Voice enables the built-in AGC by default. If you need additional control of the user’s volume, you can apply a GainNode in a custom AudioTransformDevice in series after the Amazon Voice Focus node.

@richnew10  Can you provide example ?

**Comment by richnew10** [comment]
@majo35-6c you might find this blog post useful: it walks you through building a volume adjuster. We don't have an example of a compound transform device, I'm afraid, but it should be straightforward to figure out how to combine the two.

https://aws.amazon.com/blogs/business-productivity/transforming-audio-and-shared-content-in-the-amazon-chime-sdk-for-javascript/

**Comment by richnew10** [comment]
Ah, I see you already found that blog post. Sorry, we don't have a direct example that implements what you're trying to build.

**Comment by xuesichao** [comment]
Feel free to reopen it.
