### ISSUE TITLE
Distorted input audio on MacOS/Safari 13.1.3

### ISSUE THREAD

**Issue by cfalzone-victoria** [aws/amazon-chime-sdk-js#1548]
### What happened and what did you expect to happen?

Hello,

I'm using sdk 2.14.0 / Angular 11.

All users using MacOS/Safari 13.1.3 are experimenting low volume and distorted audio. (like a robot)
Voice focus is not used on Safari 13.X
Device used is typically standard builtin Micro device

Same web application works perfetly on MAC/Chrome, MAC/Firefox, PC/Chrome, PC/Firefow, IOS/Safari, etc.

Any idea ?

Regards,
Claudio

### Have you reviewed our existing documentation?

- [X] GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [X] FAQs [page](https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html)
- [X] README [page](https://github.com/aws/amazon-chime-sdk-js#amazon-chime-sdk-for-javascript)
- [X] Feature-specific [guides](https://github.com/aws/amazon-chime-sdk-js#guides)

### Reproduction steps

Unable to provide you with reproduction steps...

### Amazon Chime SDK for JavaScript version

2.14.0

### What browsers are you seeing the problem on?

MacOS Safari

### Browser version

13.1.3

### Browser console logs

Will provide some logs asap

**Comment by cfalzone-victoria** [comment]
Hi richnew10,
Thanks your for your thoughts.

No AirPods or other additional audio devices. Built-in Mac microphone only.
I'm currently gathering these kind of information (Hardware specs).
For now, impacted hardware seems to be Mac Air ( 3 cases)
I've tried with one MacBook Pro, No problem with Safari 13.1.3 !!!

The problem is already observed with 2 video tiles (its own local tile and one remote).

Regards,
Claudio

**Comment by richnew10** [comment]
Safari's WebAssembly runtime is about 3x slower than that of Firefox and Chrome. We recommend using a more sophisticated browser when possible — either Firefox or a Chromium-based browser like Edge or Chrome — but understand that for some applications that's not possible.

Older MacBook Air devices are relatively slow in general. They get a Geekbench score ranging from 374 for a 2011 Air through to 740 for a 2015, and only jumping up to over 1000 by 2020. Compare that to an iPhone 7 (777). You have to roll back to a 6S to find an iPhone that's slower than a low-end 2018 or older MacBook Air.

Combine those two facts and Safari on a MacBook Air is at the very lowest end of support for an ML feature like Amazon Voice Focus. 

It is possible that you're running the Amazon Voice Focus estimator prior to starting video and doing other CPU-intensive tasks, and so it's deciding that there is enough horsepower to use VF, but then it's getting starved during a meeting. If you find that their audio is OK with zero video tiles, and starts to degrade at 2, then that makes sense.

If your logs show the estimator selecting `c10`, and you find out that these are old or low-end MacBook Airs, then I think that is sufficient explanation for the issue, and we can give you advice on how to tune model selection.

If your logs show something else, then we'll see what else could be the culprit.

**Comment by cfalzone-victoria** [comment]
Hi richnew10,

Thanks for your analysis, and I fully agree with you as far as the low-end Mac Airs are concerned. Unfortunaltely, we will not be able to "Reject" these users...

Voice Focus is tagged, in the doc, as compatible from Safari 14.1.
The problem is occuring in Safari 13.1.3 and we do NOT use Voice focus at all for Safari 13.
So, I don't think that VF could be the culprit...

Could it be possible that Chime is probing Voice focus even if not asked to do so explicitly ?

Regards,
Claudio

**Comment by sbcarp** [comment]
Experiences (Not always) robot like sound on Safari 15 when VF is enabled, Chrome doesn't have this issue, the problem exists in sdk demo

**Comment by cfalzone-victoria** [comment]
The only workaround I've found is to set WebAudio to false for all safari versions. This seems to work but, indeed, bye bye Voice Focus. Never had this behavior in other browsers (even on Macs)

**Comment by richnew10** [comment]
> So, I don't think that VF could be the culprit...
> 
> Could it be possible that Chime is probing Voice focus even if not asked to do so explicitly ?

It's probably that Web Audio support in general uses a different code path in Safari, and you're seeing issues with that capability on low-end devices with older versions (and sometimes even newer versions) of Safari. VF requires Web Audio, but they're distinct features.

Safari is unfortunately not a great browser from a media/WebRTC perspective.

**Comment by devalevenkatesh** [comment]
Going through the issue, seems like SDK cannot do much and it is due to the Web Audio support in general on Safari browser. Closing this issue due to no new activity, request you to please re-open if you still face the same issue. Thanks!
