### ISSUE TITLE
S3 Bucket policy not valid/present for Sink

### ISSUE THREAD

**Issue by E5920** [aws/amazon-chime-sdk-js#1558]
### What happened and what did you expect to happen?

@sinanliuAmazon @achris ,   I am facing problem at the time of executing createMediaCapturePipeline & getting error  "S3 Bucket policy not valid/present for Sink arn:aws:s3:::xx-xx-xx\",\"RequestId\":\" (truncated...) "

controller.php

public function startRecording(Request $request) {
        \Log::debug("inside start recording");       
        
        $mId = (int) $request->query('meetingId');
        if(!empty($mId)) {
            $meeting = Meeting::where('id', $mId)->firstOrFail();
        }
        $result = null;

        if (empty($meeting->status) || $meeting->status == 'active') {
            \Log::debug("In start recording, meetingId:".$meeting->id);  
            
            $chimeClient = AWS::createClient('chime');
            
            $result = $chimeClient->createMediaCapturePipeline([
                'ClientRequestToken' => "Meeting".$meeting->id,
                'SinkArn' => 'arn:aws:s3:::xx-xx-xx, // REQUIRED
                'SinkType' => 'S3Bucket', // REQUIRED
                'SourceArn' => "arn:aws:chime::".env('AWS_ACCOUNT_ID').":meeting:"."Meeting".$meeting->id, // REQUIRED
                'SourceType' => 'ChimeSdkMeeting', // REQUIRED
            ]);
            \Log::debug("inside start recording1234".$result);
        }
        \Log::debug("inside start recording5678");
        return response()->json($result, 200);
    }

### Have you reviewed our existing documentation?

- [X] GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [X] FAQs [page](https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html)
- [X] README [page](https://github.com/aws/amazon-chime-sdk-js#amazon-chime-sdk-for-javascript)
- [X] Feature-specific [guides](https://github.com/aws/amazon-chime-sdk-js#guides)

### Reproduction steps

when i called createMediaCapturePipeline API the have faced s3 bucket policy not valid.

### Amazon Chime SDK for JavaScript version

2.973.0

### What browsers are you seeing the problem on?

n/a

### Browser version

n/a

### Meeting and Attendee ID Information.

n/a

### Browser console logs

[2021-08-31 05:38:46] local.DEBUG: inside start recording  
[2021-08-31 05:38:46] local.DEBUG: In start recording, meetingId:3031  
[2021-08-31 05:38:47] local.ERROR: Error executing "CreateMediaCapturePipeline" on "https://chime.us-east-1.amazonaws.com/media-capture-pipelines"; AWS HTTP error: Client error: `POST https://chime.us-east-1.amazonaws.com/media-capture-pipelines` resulted in a `400 Bad Request` response:
{"Code":"BadRequest","Message":"S3 Bucket policy not valid/present for Sink arn:aws:s3:::xx-xx-xx","RequestId":" (truncated...)
 BadRequestException (client): S3 Bucket policy not valid/present for Sink arn:aws:s3:::xx-xx-xx-- {"Code":"BadRequest","Message":"S3 Bucket policy not valid/present for Sink arn:aws:s3:::xx-xx-xx","RequestId":"aaaecfad-3e06-4269-a970-17bdeb581fef","Resource":null} {"exception":"[object] (Aws\\Chime\\Exception\\ChimeException(code: 0): Error executing \"CreateMediaCapturePipeline\" on \"https://chime.us-east-1.amazonaws.com/media-capture-pipelines\"; AWS HTTP error: Client error: `POST https://chime.us-east-1.amazonaws.com/media-capture-pipelines` resulted in a `400 Bad Request` response:
{\"Code\":\"BadRequest\",\"Message\":\"S3 Bucket policy not valid/present for Sink arn:aws:s3:::xx-xx-xx\",\"RequestId\":\" (truncated...)
 BadRequestException (client): S3 Bucket policy not valid/present for Sink arn:aws:s3:::xx-xx-xx - {\"Code\":\"BadRequest\",\"Message\":\"S3 Bucket policy not valid/present for Sink arn:aws:s3:::xx-xx-xx\",\"RequestId\":\"aaaecfad-3e06-4269-a970-17bdeb581fef\",\"Resource\":null} at /home/rajatk/hytechpro/VirtualConf-Laravel/vendor/aws/aws-sdk-php/src/WrappedHttpHandler.php:195)
[stacktrace]
#0 /home/rajatk/hytechpro/VirtualConf-Laravel/vendor/aws/aws-sdk-php/src/WrappedHttpHandler.php(97): Aws\\WrappedHttpHandler->parseError()
#1 /home/rajatk/hytechpro/VirtualConf-Laravel/vendor/guzzlehttp/promises/src/Promise.php(204): Aws\\WrappedHttpHandler->Aws\\{closure}()
#2 /home/rajatk/hytechpro/VirtualConf-Laravel/vendor/guzzlehttp/promises/src/Promise.php(169): GuzzleHttp\\Promise\\Promise::callHandler()
#3 /home/rajatk/hytechpro/VirtualConf-Laravel/vendor/guzzlehttp/promises/src/RejectedPromise.php(42): GuzzleHttp\\Promise\\Promise::GuzzleHttp\\Promise\\{closure}()
#4 /home/rajatk/hytechpro/VirtualConf-Laravel/vendor/guzzlehttp/promises/src/TaskQueue.php(48): GuzzleHttp\\Promise\\RejectedPromise::GuzzleHttp\\Promise\\{closure}()
#5 /home/rajatk/hytechpro/VirtualConf-Laravel/vendor/guzzlehttp/guzzle/src/Handler/CurlMultiHandler.php(158): GuzzleHttp\\Promise\\TaskQueue->run()
#6 /home/rajatk/hytechpro/VirtualConf-Laravel/vendor/guzzlehttp/guzzle/src/Handler/CurlMultiHandler.php(183): GuzzleHttp\\Handler\\CurlMultiHandler->tick()
#7 /home/rajatk/hytechpro/VirtualConf-Laravel/vendor/guzzlehttp/promises/src/Promise.php(248): GuzzleHttp\\Handler\\CurlMultiHandler->execute()
#8 /home/rajatk/hytechpro/VirtualConf-Laravel/vendor/guzzlehttp/promises/src/Promise.php(224): GuzzleHttp\\Promise\\Promise->invokeWaitFn()
#9 /home/rajatk/hytechpro/VirtualConf-Laravel/vendor/guzzlehttp/promises/src/Promise.php(269): GuzzleHttp\\Promise\\Promise->waitIfPending()
#10 /home/rajatk/hytechpro/VirtualConf-Laravel/vendor/guzzlehttp/promises/src/Promise.php(226): GuzzleHttp\\Promise\\Promise->invokeWaitList()
#11 /home/rajatk/hytechpro/VirtualConf-Laravel/vendor/guzzlehttp/promises/src/Promise.php(269): GuzzleHttp\\Promise\\Promise->waitIfPending()
#12 /home/rajatk/hytechpro/VirtualConf-Laravel/vendor/guzzlehttp/promises/src/Promise.php(226): GuzzleHttp\\Promise\\Promise->invokeWaitList()
#13 /home/rajatk/hytechpro/VirtualConf-Laravel/vendor/guzzlehttp/promises/src/Promise.php(62): GuzzleHttp\\Promise\\Promise->waitIfPending()
#14 /home/rajatk/hytechpro/VirtualConf-Laravel/vendor/aws/aws-sdk-php/src/AwsClientTrait.php(58): GuzzleHttp\\Promise\\Promise->wait()
#15 /home/rajatk/hytechpro/VirtualConf-Laravel/vendor/aws/aws-sdk-php/src/AwsClientTrait.php(86): Aws\\AwsClient->execute()
#16 /home/rajatk/hytechpro/VirtualConf-Laravel/app/Http/Controllers/APIController.php(749): Aws\\AwsClient->__call()
#17 /home/rajatk/hytechpro/VirtualConf-Laravel/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): App\\Http\\Controllers\\APIController->startRecording()
#18 /home/rajatk/hytechpro/VirtualConf-Laravel/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction()
#19 /home/rajatk/hytechpro/VirtualConf-Laravel/vendor/laravel/framework/src/Illuminate/Routing/Route.php(254): Illuminate\\Routing\\ControllerDispatcher->dispatch()
#20 /home/rajatk/hytechpro/VirtualConf-Laravel/vendor/laravel/framework/src/Illuminate/Routing/Route.php(197): Illuminate\\Routing\\Route->runController()
#21 /home/rajatk/hytechpro/VirtualConf-Laravel/vendor/laravel/framework/src/Illuminate/Routing/Router.php(695): Illuminate\\Routing\\Route->run()
#22 /home/rajatk/hytechpro/VirtualConf-Laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()
#23 /home/rajatk/hytechpro/VirtualConf-Laravel/app/Http/Middleware/EnsureTokenIsValid.php(23): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#24 /home/rajatk/hytechpro/VirtualConf-Laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): App\\Http\\Middleware\\EnsureTokenIsValid->handle()
#25 /home/rajatk/hytechpro/VirtualConf-Laravel/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(50): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#26 /home/rajatk/hytechpro/VirtualConf-Laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle()
#27 /home/rajatk/hytechpro/VirtualConf-Laravel/vendor/laravel/framework/src/Illuminate/Routing/Middleware/ThrottleRequests.php(127): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#28 /home/rajatk/hytechpro/VirtualConf-Laravel/vendor/laravel/framework/src/Illuminate/Routing/Middleware/ThrottleRequests.php(103): Illuminate\\Routing\\Middleware\\ThrottleRequests->handleRequest()
#29 /home/rajatk/hytechpro/VirtualConf-Laravel/vendor/laravel/framework/src/Illuminate/Routing/Middleware/ThrottleRequests.php(55): Illuminate\\Routing\\Middleware\\ThrottleRequests->handleRequestUsingNamedLimiter()
#30 /home/rajatk/hytechpro/VirtualConf-Laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Routing\\Middleware\\ThrottleRequests->handle()
#31 /home/rajatk/hytechpro/VirtualConf-Laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#32 /home/rajatk/hytechpro/VirtualConf-Laravel/vendor/laravel/framework/src/Illuminate/Routing/Router.php(697): Illuminate\\Pipeline\\Pipeline->then()
#33 /home/rajatk/hytechpro/VirtualConf-Laravel/vendor/laravel/framework/src/Illuminate/Routing/Router.php(672): Illuminate\\Routing\\Router->runRouteWithinStack()
#34 /home/rajatk/hytechpro/VirtualConf-Laravel/vendor/laravel/framework/src/Illuminate/Routing/Router.php(636): Illuminate\\Routing\\Router->runRoute()
#35 /home/rajatk/hytechpro/VirtualConf-Laravel/vendor/laravel/framework/src/Illuminate/Routing/Router.php(625): Illuminate\\Routing\\Router->dispatchToRoute()
#36 /home/rajatk/hytechpro/VirtualConf-Laravel/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(166): Illuminate\\Routing\\Router->dispatch()
#37 /home/rajatk/hytechpro/VirtualConf-Laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
#38 /home/rajatk/hytechpro/VirtualConf-Laravel/app/Http/Middleware/CheckDomain.php(42): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#39 /home/rajatk/hytechpro/VirtualConf-Laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): App\\Http\\Middleware\\CheckDomain->handle()
#40 /home/rajatk/hytechpro/VirtualConf-Laravel/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#41 /home/rajatk/hytechpro/VirtualConf-Laravel/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#42 /home/rajatk/hytechpro/VirtualConf-Laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle()
#43 /home/rajatk/hytechpro/VirtualConf-Laravel/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#44 /home/rajatk/hytechpro/VirtualConf-Laravel/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#45 /home/rajatk/hytechpro/VirtualConf-Laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle()
#46 /home/rajatk/hytechpro/VirtualConf-Laravel/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#47 /home/rajatk/hytechpro/VirtualConf-Laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle()
#48 /home/rajatk/hytechpro/VirtualConf-Laravel/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#49 /home/rajatk/hytechpro/VirtualConf-Laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle()
#50 /home/rajatk/hytechpro/VirtualConf-Laravel/vendor/fruitcake/laravel-cors/src/HandleCors.php(52): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#51 /home/rajatk/hytechpro/VirtualConf-Laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fruitcake\\Cors\\HandleCors->handle()
#52 /home/rajatk/hytechpro/VirtualConf-Laravel/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#53 /home/rajatk/hytechpro/VirtualConf-Laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fideloper\\Proxy\\TrustProxies->handle()
#54 /home/rajatk/hytechpro/VirtualConf-Laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#55 /home/rajatk/hytechpro/VirtualConf-Laravel/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(141): Illuminate\\Pipeline\\Pipeline->then()
#56 /home/rajatk/hytechpro/VirtualConf-Laravel/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(110): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#57 /home/rajatk/hytechpro/VirtualConf-Laravel/public/index.php(52): Illuminate\\Foundation\\Http\\Kernel->handle()
#58 /home/rajatk/hytechpro/VirtualConf-Laravel/server.php(21): require_once('/home/rajatk/hy...')
#59 {main}

[previous exception] [object] (GuzzleHttp\\Exception\\ClientException(code: 400): Client error: `POST https://chime.us-east-1.amazonaws.com/media-capture-pipelines` resulted in a `400 Bad Request` response:
{\"Code\":\"BadRequest\",\"Message\":\"S3 Bucket policy not valid/present for Sink arn:aws:s3::xx-xx-xx\",\"RequestId\":\" (truncated...)
 at /home/rajatk/hytechpro/VirtualConf-Laravel/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:113)
[stacktrace]
#0 /home/rajatk/hytechpro/VirtualConf-Laravel/vendor/guzzlehttp/guzzle/src/Middleware.php(69): GuzzleHttp\\Exception\\RequestException::create()
#1 /home/rajatk/hytechpro/VirtualConf-Laravel/vendor/guzzlehttp/promises/src/Promise.php(204): GuzzleHttp\\Middleware::GuzzleHttp\\{closure}()
#2 /home/rajatk/hytechpro/VirtualConf-Laravel/vendor/guzzlehttp/promises/src/Promise.php(153): GuzzleHttp\\Promise\\Promise::callHandler()
#3 /home/rajatk/hytechpro/VirtualConf-Laravel/vendor/guzzlehttp/promises/src/TaskQueue.php(48): GuzzleHttp\\Promise\\Promise::GuzzleHttp\\Promise\\{closure}()
#4 /home/rajatk/hytechpro/VirtualConf-Laravel/vendor/guzzlehttp/guzzle/src/Handler/CurlMultiHandler.php(158): GuzzleHttp\\Promise\\TaskQueue->run()
#5 /home/rajatk/hytechpro/VirtualConf-Laravel/vendor/guzzlehttp/guzzle/src/Handler/CurlMultiHandler.php(183): GuzzleHttp\\Handler\\CurlMultiHandler->tick()
#6 /home/rajatk/hytechpro/VirtualConf-Laravel/vendor/guzzlehttp/promises/src/Promise.php(248): GuzzleHttp\\Handler\\CurlMultiHandler->execute()
#7 /home/rajatk/hytechpro/VirtualConf-Laravel/vendor/guzzlehttp/promises/src/Promise.php(224): GuzzleHttp\\Promise\\Promise->invokeWaitFn()
#8 /home/rajatk/hytechpro/VirtualConf-Laravel/vendor/guzzlehttp/promises/src/Promise.php(269): GuzzleHttp\\Promise\\Promise->waitIfPending()
#9 /home/rajatk/hytechpro/VirtualConf-Laravel/vendor/guzzlehttp/promises/src/Promise.php(226): GuzzleHttp\\Promise\\Promise->invokeWaitList()
#10 /home/rajatk/hytechpro/VirtualConf-Laravel/vendor/guzzlehttp/promises/src/Promise.php(269): GuzzleHttp\\Promise\\Promise->waitIfPending()
#11 /home/rajatk/hytechpro/VirtualConf-Laravel/vendor/guzzlehttp/promises/src/Promise.php(226): GuzzleHttp\\Promise\\Promise->invokeWaitList()
#12 /home/rajatk/hytechpro/VirtualConf-Laravel/vendor/guzzlehttp/promises/src/Promise.php(62): GuzzleHttp\\Promise\\Promise->waitIfPending()
#13 /home/rajatk/hytechpro/VirtualConf-Laravel/vendor/aws/aws-sdk-php/src/AwsClientTrait.php(58): GuzzleHttp\\Promise\\Promise->wait()
#14 /home/rajatk/hytechpro/VirtualConf-Laravel/vendor/aws/aws-sdk-php/src/AwsClientTrait.php(86): Aws\\AwsClient->execute()
#15 /home/rajatk/hytechpro/VirtualConf-Laravel/app/Http/Controllers/APIController.php(749): Aws\\AwsClient->__call()
#16 /home/rajatk/hytechpro/VirtualConf-Laravel/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): App\\Http\\Controllers\\APIController->startRecording()
#17 /home/rajatk/hytechpro/VirtualConf-Laravel/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction()
#18 /home/rajatk/hytechpro/VirtualConf-Laravel/vendor/laravel/framework/src/Illuminate/Routing/Route.php(254): Illuminate\\Routing\\ControllerDispatcher->dispatch()
#19 /home/rajatk/hytechpro/VirtualConf-Laravel/vendor/laravel/framework/src/Illuminate/Routing/Route.php(197): Illuminate\\Routing\\Route->runController()
#20 /home/rajatk/hytechpro/VirtualConf-Laravel/vendor/laravel/framework/src/Illuminate/Routing/Router.php(695): Illuminate\\Routing\\Route->run()
#21 /home/rajatk/hytechpro/VirtualConf-Laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()
#22 /home/rajatk/hytechpro/VirtualConf-Laravel/app/Http/Middleware/EnsureTokenIsValid.php(23): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#23 /home/rajatk/hytechpro/VirtualConf-Laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): App\\Http\\Middleware\\EnsureTokenIsValid->handle()
#24 /home/rajatk/hytechpro/VirtualConf-Laravel/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(50): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#25 /home/rajatk/hytechpro/VirtualConf-Laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle()
#26 /home/rajatk/hytechpro/VirtualConf-Laravel/vendor/laravel/framework/src/Illuminate/Routing/Middleware/ThrottleRequests.php(127): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#27 /home/rajatk/hytechpro/VirtualConf-Laravel/vendor/laravel/framework/src/Illuminate/Routing/Middleware/ThrottleRequests.php(103): Illuminate\\Routing\\Middleware\\ThrottleRequests->handleRequest()
#28 /home/rajatk/hytechpro/VirtualConf-Laravel/vendor/laravel/framework/src/Illuminate/Routing/Middleware/ThrottleRequests.php(55): Illuminate\\Routing\\Middleware\\ThrottleRequests->handleRequestUsingNamedLimiter()
#29 /home/rajatk/hytechpro/VirtualConf-Laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Routing\\Middleware\\ThrottleRequests->handle()
#30 /home/rajatk/hytechpro/VirtualConf-Laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#31 /home/rajatk/hytechpro/VirtualConf-Laravel/vendor/laravel/framework/src/Illuminate/Routing/Router.php(697): Illuminate\\Pipeline\\Pipeline->then()
#32 /home/rajatk/hytechpro/VirtualConf-Laravel/vendor/laravel/framework/src/Illuminate/Routing/Router.php(672): Illuminate\\Routing\\Router->runRouteWithinStack()
#33 /home/rajatk/hytechpro/VirtualConf-Laravel/vendor/laravel/framework/src/Illuminate/Routing/Router.php(636): Illuminate\\Routing\\Router->runRoute()
#34 /home/rajatk/hytechpro/VirtualConf-Laravel/vendor/laravel/framework/src/Illuminate/Routing/Router.php(625): Illuminate\\Routing\\Router->dispatchToRoute()
#35 /home/rajatk/hytechpro/VirtualConf-Laravel/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(166): Illuminate\\Routing\\Router->dispatch()
#36 /home/rajatk/hytechpro/VirtualConf-Laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
#37 /home/rajatk/hytechpro/VirtualConf-Laravel/app/Http/Middleware/CheckDomain.php(42): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#38 /home/rajatk/hytechpro/VirtualConf-Laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): App\\Http\\Middleware\\CheckDomain->handle()
#39 /home/rajatk/hytechpro/VirtualConf-Laravel/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#40 /home/rajatk/hytechpro/VirtualConf-Laravel/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#41 /home/rajatk/hytechpro/VirtualConf-Laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle()
#42 /home/rajatk/hytechpro/VirtualConf-Laravel/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#43 /home/rajatk/hytechpro/VirtualConf-Laravel/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#44 /home/rajatk/hytechpro/VirtualConf-Laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle()
#45 /home/rajatk/hytechpro/VirtualConf-Laravel/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#46 /home/rajatk/hytechpro/VirtualConf-Laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle()
#47 /home/rajatk/hytechpro/VirtualConf-Laravel/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#48 /home/rajatk/hytechpro/VirtualConf-Laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle()
#49 /home/rajatk/hytechpro/VirtualConf-Laravel/vendor/fruitcake/laravel-cors/src/HandleCors.php(52): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#50 /home/rajatk/hytechpro/VirtualConf-Laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fruitcake\\Cors\\HandleCors->handle()
#51 /home/rajatk/hytechpro/VirtualConf-Laravel/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#52 /home/rajatk/hytechpro/VirtualConf-Laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fideloper\\Proxy\\TrustProxies->handle()
#53 /home/rajatk/hytechpro/VirtualConf-Laravel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#54 /home/rajatk/hytechpro/VirtualConf-Laravel/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(141): Illuminate\\Pipeline\\Pipeline->then()
#55 /home/rajatk/hytechpro/VirtualConf-Laravel/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(110): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#56 /home/rajatk/hytechpro/VirtualConf-Laravel/public/index.php(52): Illuminate\\Foundation\\Http\\Kernel->handle()
#57 /home/rajatk/hytechpro/VirtualConf-Laravel/server.php(21): require_once('/home/rajatk/hy...')
#58 {main}

**Comment by gsudhanshu** [comment]
Thanks @sinanliuAmazon ,we will try these steps.
