### ISSUE TITLE
Can't see other video/screenshare or hear anything in ongoing meeting

### ISSUE THREAD

**Issue by gsudhanshu** [aws/amazon-chime-sdk-js#1559]
### What happened and what did you expect to happen?

We conducted our monthly company meet using in-house application built using aws-chime-sdk-js

I will describe the problem faced by one of the participants below:
The call was scheduled at 5 pm on Friday, 27th Aug. 
* He was able to join the call at 4:55pm and could see other participants but faced audio issues from the start itself.
* After 5 min, when there were around 35 participants; the application froze and he was not able to see videos as well
* He received a message : "your session has ended; do you want to rejoin?"; but he was not able to click on yes button as the application was frozen. He could switch to skype and make a call on skype to another participant.
* Then he restarted his system and tried to join again. This time his webcam started showed a light briefly but he could neither see other participants or hear them.
* Then he tried joining using mobile browser but received gateway timeout error

### Have you reviewed our existing documentation?

- [X] GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [X] FAQs [page](https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html)
- [X] README [page](https://github.com/aws/amazon-chime-sdk-js#amazon-chime-sdk-for-javascript)
- [X] Feature-specific [guides](https://github.com/aws/amazon-chime-sdk-js#guides)

### Reproduction steps

join amazon chime 

### Amazon Chime SDK for JavaScript version

2.4.1

### What browsers are you seeing the problem on?

chrome

### Browser version

92.0.4515.159

### Meeting and Attendee ID Information.

751baa7a-448f-4777-923c-94c84e130706 : meeting Id

attendee_user_ids: 

NjIyYmFlZmUtNWNhMC0xM2VmLTI5ZTQtMjNkNDJmOTdkZDg4OmYwYmJjY2QwLTkyZTItNDdiOC05OWM5LTJlNDhkMjY2NDFiZg

NjIyYmFlZmUtNWNhMC0xM2VmLTI5ZTQtMjNkNDJmOTdkZDg4OjljZWIwN2NhLTZiYmEtNGEwYi1hMTE1LTBlY2I0NDM4ZmE3MQ

### Browser console logs

was not able to retreive browser logs as browser froze

**Comment by michhyun1** [comment]
@gsudhanshu This seems to be a large meeting - could you help us by providing the real attendee id of that user by any chance? Thanks

**Comment by gsudhanshu** [comment]
@michhyun1 

chime_attendee_user_ids (for the same user):

NjIyYmFlZmUtNWNhMC0xM2VmLTI5ZTQtMjNkNDJmOTdkZDg4OmYwYmJjY2QwLTkyZTItNDdiOC05OWM5LTJlNDhkMjY2NDFiZg

NjIyYmFlZmUtNWNhMC0xM2VmLTI5ZTQtMjNkNDJmOTdkZDg4OjljZWIwN2NhLTZiYmEtNGEwYi1hMTE1LTBlY2I0NDM4ZmE3MQ

multiple attendee id because the user tried to leave and then join back

**Comment by michhyun1** [comment]
@gsudhanshu Can you please provide the attendee id - not sure what this ID you provided is, perhaps the external attendee id? The meeting browser logs are prepended with the attendee id - can you send us those instead?

It should look like this: (example) 38f09f93-ef7c-1af6-8ae4-5dfe370eb744

**Comment by gsudhanshu** [comment]
External attendee Id : User52

**Comment by gsudhanshu** [comment]
@michhyun1

**Comment by devalevenkatesh** [comment]
Hi @gsudhanshu ,

The attendee ID you provided is an external User ID and not the attendeeID which you would receive from the `CreateAttendee` API. The earlier provided attendee IDs are also not the expected ones as @michhyun1 commented earlier.

Could you please clarify few questions below?
1. Was this the only participant that experienced issues?
2. How frequent is this behavior?
3. We would need some repro steps to see if we can debug this further if we cannot get any browser console logs for this. So, we would request you to provide repro steps here.
4. Does this participant faces similar issues when joining normal other meetings?
5. As requested, we need the `attendeeId` for the affected user if this is a frequent issue.

**Comment by vidya-mohan** [comment]
Resolving as no response
