### ISSUE TITLE
audiovideodidstop is being called for many attendees without meeting end or user action

### ISSUE THREAD

**Issue by gsudhanshu** [aws/amazon-chime-sdk-js#1561]
### What happened and what did you expect to happen?

We conducted a company meet using our application built on aws-chime-sdk-js

During the meeting many users faced this issue that audiovideodidstop was called when meeting was going on!

We are not able to find the issue..

chimeMeetingId - 751baa7a-448f-4777-923c-94c84e130706

attendeeId - YWU1NmViN2UtNWZlNy01MjFkLThlM2MtZGY3NDg1MWJmMmIxOmI3NjEwYmMxLWNmZGUtNDI5ZC1hNDQwLTM3YTFiNDc2YzE1Yw

### Have you reviewed our existing documentation?

- [X] GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [X] FAQs [page](https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html)
- [X] README [page](https://github.com/aws/amazon-chime-sdk-js#amazon-chime-sdk-for-javascript)
- [X] Feature-specific [guides](https://github.com/aws/amazon-chime-sdk-js#guides)

### Reproduction steps

j

### Amazon Chime SDK for JavaScript version

2.4.1

### What browsers are you seeing the problem on?

chrome

### Browser version

92.0.4515.159

### Browser console logs

not able to retrieve browser console logs

**Comment by devalevenkatesh** [comment]
Hi @gsudhanshu ,

The attendeeId you provide in the issues is in-correct, could you please provide us the attendeeId that you receive when you call `CreateAttendee` API. I do not know and cannot map your provided attendee to anything on our side. A typical attendee ID should look like: `88b2dd42-6227-74e4-fb49-9e643ab4decc` (one attendee from your meeting).

We would also need some more details like what is the typical flow of your application and need browser console logs for an affected attendee ID to debug the issue further.

The `audioVideoDidStop` is called with a `MeetingSessionStatusCode` could you please provide us more information on what status the affected attendees received?

**Comment by vidya-mohan** [comment]
Resolving as no response
