### ISSUE TITLE
Save transcription result to database

### ISSUE THREAD

**Issue by paul365** [aws/amazon-chime-sdk-js#1563]
### What are you trying to do?
I want to save the transcription result to a database. Can this be done via EventBridge? Thanks

### How can the documentation be improved to help your use case?
Include a section on how to persist transcription results.

### What documentation have you looked at so far?
README.md
Amazon Chime SDK Developer Guide
https://docs.aws.amazon.com/chime/latest/dg/meeting-transcription.html

**Comment by tenge-amzn** [comment]
You can use media capture pipeline to store the transcription in to S3 file as json objects.
https://aws.amazon.com/blogs/business-productivity/capture-amazon-chime-sdk-meetings-using-media-capture-pipelines/
