### ISSUE TITLE
Video stream from Samsung S8 appears black & white

### ISSUE THREAD

**Issue by Jagordon** [aws/amazon-chime-sdk-js#1566]
### What happened and what did you expect to happen?

When we upgraded from v2.15.0 -> v2.16.1 our Samsung S8 test devices started manifesting this issue. Other devices saw their output video as seen in the screenshot below.

<img width="1044" alt="Screen Shot 2021-09-01 at 15 01 50" src="https://user-images.githubusercontent.com/7779656/131852591-3d2f4319-fb74-417f-8824-39bbb301fe1d.png">

This was not observed on any other devices.
Macbook
iPhone
iPad
Surface Pro
Motorola 

### Have you reviewed our existing documentation?

- [X] GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [X] FAQs [page](https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html)
- [X] README [page](https://github.com/aws/amazon-chime-sdk-js#amazon-chime-sdk-for-javascript)
- [X] Feature-specific [guides](https://github.com/aws/amazon-chime-sdk-js#guides)

### Reproduction steps

Install v2.16.1 and use the video on a Samsung S8

### Amazon Chime SDK for JavaScript version

2.16.1

### What browsers are you seeing the problem on?

Chrome

### Browser version

92.0

### Browser console logs

none

**Comment by ltrung** [comment]
@Jagordon Thanks for reporting the issue. Could you confirm whether you would not see this issue if you roll back to 2.15? I looked at the change log and did not see anything that could affect this.

**Comment by Jagordon** [comment]
We have rolled back to 2.15 and the issue is resolved.

**Comment by ltrung** [comment]
We have not been able to reproduce the issue on our end with a S8 and a S9 device. Looking at the diff between 2.15 and 2.16.1 i only found this commit https://github.com/aws/amazon-chime-sdk-js/commit/6638ea4492f3cae4aa56bb342978eb0efeed0606 that has anything to do with video. Could you try to remove this commit and see if it fixes the issue for you?

**Comment by dchen-aws** [comment]
Closing since this has been stale for some time. Please re-open if needs more help from us.

**Comment by ltrung** [comment]
@Jagordon Can you pull #1751 and see whether if it fixes it for you?

**Comment by Jagordon** [comment]
We will do this testing this sprint Ty guys

**Comment by Jagordon** [comment]
This issue is fixed. Thanks guys!
