### ISSUE TITLE
user enter into the meeting then only visible white screen

### ISSUE THREAD

**Issue by E5920** [aws/amazon-chime-sdk-js#1567]
### What happened and what did you expect to happen?

@ltrung, i am facing issue when user enter into the meeting or rejoin the meeting then only visible white screen with meeting Id & my requirement is if user into the meeting then visible remote video of other user. please suggest

please find a screenshot of white screen.

![image](https://user-images.githubusercontent.com/80304004/131885032-78f118a3-f817-41da-9b67-d46c8f37f072.png)

### Have you reviewed our existing documentation?

- [X] GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [X] FAQs [page](https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html)
- [X] README [page](https://github.com/aws/amazon-chime-sdk-js#amazon-chime-sdk-for-javascript)
- [X] Feature-specific [guides](https://github.com/aws/amazon-chime-sdk-js#guides)

### Reproduction steps

user schedule a meeting &  enter or rejoin the meeting then visible white screen

### Amazon Chime SDK for JavaScript version

2.4.1

### What browsers are you seeing the problem on?

n/a

### Browser version

n/a

### Meeting and Attendee ID Information.

n/a

### Browser console logs

[re-join logs.txt](https://github.com/aws/amazon-chime-sdk-js/files/7100321/re-join.logs.txt)

**Comment by ltrung** [comment]
@E5920 Could you clarify the issue? Did this work before and you only encountered it recently or you asked how to view remote videos?
Upon joining you should receive remote video streams right away but in order to see them you need to bind them to your application's video elements using `bindVideoElement` in the `videoTileDidUpdate` event. For more details, you can see our implementation in the demo (https://github.com/aws/amazon-chime-sdk-js/blob/master/demos/browser/app/meetingV2/meetingV2.ts#L3240).

**Comment by E5920** [comment]
@ltrung , Sometime it's working fine but sometimes not working.

**Comment by simmkyu** [comment]
We are not aware of any white video issues. Usually, the grey or dark video appears when a video tile has a problem. I assume that the video tile did not show up, so a white background is visible in your application.

- As @ltrung suggested, ensure that you successfully bind a video tile.
- Provide us with the following information:
  - Browser and device information when you experience the problem
  - Reproduction steps if existed
  - Chime SDK meeting ID (`3089` in the screenshot looks like your service's ID)
  - Chime SDK attendee ID of those who had an issue viewing a video tile
- I also recommend using the recent version of the Chime SDK for JavaScript. The latest version is 2.16.1 as of Sep 9, 2021.
