### ISSUE TITLE
Meeting ended without calling audiovideodidstop

### ISSUE THREAD

**Issue by gsudhanshu** [aws/amazon-chime-sdk-js#1569]
### What happened and what did you expect to happen?

Steps to reproduce the issue:

1. Host starts meeting
2. Attendee joins meeting
3. Attendee leaves meeting
4. Attendee tries to rejoin --> but unable to join
5. Host is still waiting for attendee to join in the meeting. Host has not yet received the error message "Meeting has ended". This message comes on audioVideoDidStop

Server logs:

[2021-09-03 07:34:33] stage.ERROR: Error executing "GetMeeting" on "https://chime.us-east-1.amazonaws.com/meetings/26675937-400e-4d37-b04e-000a197b0706"; AWS HTTP error: Client error: `GET https://chime.us-east-1.amazonaws.com/meetings/26675937-400e-4d37-b04e-000a197b0706` resulted in a `404 Not Found` response:
{"Code":"NotFound","Message":"Meeting <26675937-400e-4d37-b04e-000a197b0706> not found","RequestId":"2135c6b3-f451-4008- (truncated...)
 NotFoundException (client): Meeting <26675937-400e-4d37-b04e-000a197b0706> not found - {"Code":"NotFound","Message":"Meeting <26675937-400e-4d37-b04e-000a197b0706> not found","RequestId":"2135c6b3-f451-4008-b0e7-0a7c71300e77","Resource":null} {"exception":"[object] (Aws\\Chime\\Exception\\ChimeException(code: 0): Error executing \"GetMeeting\" on \"https://chime.us-east-1.amazonaws.com/meetings/26675937-400e-4d37-b04e-000a197b0706\"; AWS HTTP error: Client error: `GET https://chime.us-east-1.amazonaws.com/meetings/26675937-400e-4d37-b04e-000a197b0706` resulted in a `404 Not Found` response:
{\"Code\":\"NotFound\",\"Message\":\"Meeting <26675937-400e-4d37-b04e-000a197b0706> not found\",\"RequestId\":\"2135c6b3-f451-4008- (truncated...)
 NotFoundException (client): Meeting <26675937-400e-4d37-b04e-000a197b0706> not found - {\"Code\":\"NotFound\",\"Message\":\"Meeting <26675937-400e-4d37-b04e-000a197b0706> not found\",\"RequestId\":\"2135c6b3-f451-4008-b0e7-0a7c71300e77\",\"Resource\":null} at /var/www/html/laravelvc-hytech/VirtualConf-Laravel/vendor/aws/aws-sdk-php/src/WrappedHttpHandler.php:195)

### Have you reviewed our existing documentation?

- [X] GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [X] FAQs [page](https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html)
- [X] README [page](https://github.com/aws/amazon-chime-sdk-js#amazon-chime-sdk-for-javascript)
- [X] Feature-specific [guides](https://github.com/aws/amazon-chime-sdk-js#guides)

### Reproduction steps

Steps to reproduce the issue:

1. Host starts meeting
2. Attendee joins meeting
3. Attendee leaves meeting
4. Attendee tries to rejoin --> but unable to join
5. Host is still waiting for attendee to join in the meeting. Host has not yet received the error message "Meeting has ended". This message comes on audioVideoDidStop

Server logs:

[2021-09-03 07:34:33] stage.ERROR: Error executing "GetMeeting" on "https://chime.us-east-1.amazonaws.com/meetings/26675937-400e-4d37-b04e-000a197b0706"; AWS HTTP error: Client error: `GET https://chime.us-east-1.amazonaws.com/meetings/26675937-400e-4d37-b04e-000a197b0706` resulted in a `404 Not Found` response:
{"Code":"NotFound","Message":"Meeting <26675937-400e-4d37-b04e-000a197b0706> not found","RequestId":"2135c6b3-f451-4008- (truncated...)
 NotFoundException (client): Meeting <26675937-400e-4d37-b04e-000a197b0706> not found - {"Code":"NotFound","Message":"Meeting <26675937-400e-4d37-b04e-000a197b0706> not found","RequestId":"2135c6b3-f451-4008-b0e7-0a7c71300e77","Resource":null} {"exception":"[object] (Aws\\Chime\\Exception\\ChimeException(code: 0): Error executing \"GetMeeting\" on \"https://chime.us-east-1.amazonaws.com/meetings/26675937-400e-4d37-b04e-000a197b0706\"; AWS HTTP error: Client error: `GET https://chime.us-east-1.amazonaws.com/meetings/26675937-400e-4d37-b04e-000a197b0706` resulted in a `404 Not Found` response:
{\"Code\":\"NotFound\",\"Message\":\"Meeting <26675937-400e-4d37-b04e-000a197b0706> not found\",\"RequestId\":\"2135c6b3-f451-4008- (truncated...)
 NotFoundException (client): Meeting <26675937-400e-4d37-b04e-000a197b0706> not found - {\"Code\":\"NotFound\",\"Message\":\"Meeting <26675937-400e-4d37-b04e-000a197b0706> not found\",\"RequestId\":\"2135c6b3-f451-4008-b0e7-0a7c71300e77\",\"Resource\":null} at /var/www/html/laravelvc-hytech/VirtualConf-Laravel/vendor/aws/aws-sdk-php/src/WrappedHttpHandler.php:195)

### Amazon Chime SDK for JavaScript version

2.4.1

### What browsers are you seeing the problem on?

chrome

### Browser version

92.0.4515.159

### Browser console logs

NA

**Comment by gsudhanshu** [comment]
@ltrung @E5920

**Comment by jing-chen1** [comment]
Hi @gsudhanshu, thanks for your interest.

I tried on the [meeting demo](https://github.com/aws/amazon-chime-sdk-js/tree/master/demos/browser), following your step, I can see the `audioVideoDidStop()` being called when an attendee leaves meeting. Can you please let us know which demo has this issue?

**Comment by gsudhanshu** [comment]
@jing-chen1 
Need to check: why would getMeeting return not found when meeting is already going on? Please refer to logs shared originally

**Comment by devalevenkatesh** [comment]
Hi @gsudhanshu ,

Could you please provide us with client JS SDK log from browser from the affected attendee?

The log above is not sufficient to root cause this issue. I also checked the backend events for the meeting: 
`26675937-400e-4d37-b04e-000a197b0706` and see when an attendee leaves you may be deleting the attendee from the meeting as well.

Few more questions:
1. Are you are trying to re-join an attendee to an ended meeting due to auto-end policies?
https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html#when-does-an-amazon-chime-sdk-meeting-end
2. Are you deleting the attendee from the meeting when an attendee leaves? This needs attendee side browser console logs to verify further why the attendee fails to join. From backend event, I could see an attendee left and could re-join back again.

**Comment by vidya-mohan** [comment]
Resolving as no response
