### ISSUE TITLE
Fix the video tile unbinding issue

### ISSUE THREAD

**Issue by simmkyu** [aws/amazon-chime-sdk-js#157]
### Problem

From [DefaultVideoTile.disconnectVideoStreamFromVideoElement()](https://github.com/aws/amazon-chime-sdk-js/blob/master/src/videotile/DefaultVideoTile.ts#L75):

```
// Need to yield the message loop before clearing `srcObject` to
// prevent Safari from crashing.
new AsyncScheduler().start(() => {
  videoElement.srcObject = null;
});
```

`DefaultVideoTile.disconnectVideoStreamFromVideoElement()` is setting `videoElement.srcObject` to `null` after a slight delay. However, `disconnectVideoStreamFromVideoElement()` and all callers, such as `VideoTileController.unbindVideoElement()`-are not async functions.

See this example:

```
// Assume that a <video> element "element" is bound to oldTileId.
// Unbind "element" asynchronously.
VideoTileController.unbindVideoElement(oldTileId);

// Bind "element" synchronously.
VideoTileController.bindVideoElement(newTileId, element);

// After binding "element," "element.srcObject" is set to null.
```

#### Option 1 (preferred):
Set `videoElement.srcObject` to `null` synchronously. We need to investigate why this can cause Safari to crash.

#### Option 2:
Make all callers to `async`. This requires significant changes that should be related to `2.0.0`.

**Comment by aburnson** [comment]
Fixed in #325
