### ISSUE TITLE
Participant drops if meeting continues with locked screen or in background

### ISSUE THREAD

**Issue by shriyajuneja** [aws/amazon-chime-sdk-js#1570]
### What happened and what did you expect to happen?

If user locks screen or try to run meeting in background, participant drops after 1 minute or so and is reconnected once they switch back to meeting tab, found similar issue in [FAQS](https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html#i-notice-that-my-clients-lose-audio-and-drop-from-the-meeting-if-the-chrome-browser-on-android-stays-in-background-for-several-minutes-is-that-a-known-issue) looks like its known issue for chromium based browsers on android, but faced similar issue for chrome, firefox on both android and iOS. 

### Have you reviewed our existing documentation?

- [X] GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [X] FAQs [page](https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html)
- [X] README [page](https://github.com/aws/amazon-chime-sdk-js#amazon-chime-sdk-for-javascript)
- [X] Feature-specific [guides](https://github.com/aws/amazon-chime-sdk-js#guides)

### Reproduction steps

Lock phone screen in middle of call, and wait for ~2 minutes

### Amazon Chime SDK for JavaScript version

2.16.1

### What browsers are you seeing the problem on?

Chrome, Firefox, Samsung Internet

### Browser version

Firefox version - 36.0

### Meeting and Attendee ID Information.

Meeting ID - 73759a7a-c335-4259-8960-696997bf0706
Attendee 1 - e5ec218b-0146-d1ae-8e6b-2a09dad8001b (user on iOS firefox)
Attendee 2 - c0af1d43-08a7-7d80-6c17-bbc77f357e0c

### Browser console logs

[call-drop-firefox-ios.log](https://github.com/aws/amazon-chime-sdk-js/files/7106524/call-drop-firefox-ios.log)

**Comment by ltrung** [comment]
As documented in the FAQs, it is due to the mobile OS and browsers limit. 
If it is a requirement for the application to run in background, please consider the Chime mobile SDK https://github.com/aws/amazon-chime-sdk-ios or https://github.com/aws/amazon-chime-sdk-android.
Another option is maybe to create a app with WebView and request for background microphone access.
