### ISSUE TITLE
Is message throttling based on individual clients or the entire meeting session?

### ISSUE THREAD

**Issue by bb-marco-olea** [aws/amazon-chime-sdk-js#1571]
### What are you trying to do?

I'm trying to understand how throttling works when attendees broadcast data messages to other attendees via these API methods: `meetingSession.audioVideo.realtimeSendDataMessage`, `meetingSession.audioVideo.realtimeSubscribeToReceiveDataMessage`, and `meetingSession.audioVideo.realtimeUnsubscribeFromReceiveDataMessage`.

In [this API overview](https://aws.github.io/amazon-chime-sdk-js/modules/apioverview.html#9-send-and-receive-data-messages-optional) it is mentioned that:

> If you send too many messages at once, your messages may be returned to you with the throttled flag set.

It is unclear to me whether _you_ refers to an individual attendee, a topic, or the data channel where these messages are exchanged. 

### How can the documentation be improved to help your use case?

Clarify if the specified throttling soft/hard limits refer to:

1. An individual attendee (e.g. each individual attendee can send up to 100 messages a second before reaching the soft limit),
2. A topic (e.g. each topic can receive up to 100 messages a second before reaching the soft limit), or
3. The data channel (e.g. in a meeting session, only 100 messages can be sent every second before reaching the soft limit, it doesn't matter which attendee they come from or what topic they're posted to).

### What documentation have you looked at so far?

[https://aws.github.io/amazon-chime-sdk-js/modules/apioverview.html#9-send-and-receive-data-messages-optional](https://aws.github.io/amazon-chime-sdk-js/modules/apioverview.html#9-send-and-receive-data-messages-optional)

**Comment by ltrung** [comment]
@bb-marco-olea Thanks for your question. I have updated in the API Overview the rate limit to clarify the attendee limit and meeting limit in PR #1573.

**Comment by bb-marco-olea** [comment]
Thank you very much!
