### ISSUE TITLE
Add width, height, maxBandwidthKbps to startContentShareFromScreenCapture

### ISSUE THREAD

**Issue by penguin-taling** [aws/amazon-chime-sdk-js#1578]
## What do you want us to build?

I try to use scree share with [startContentShareFromScreenCapture](https://aws.github.io/amazon-chime-sdk-js/interfaces/audiovideofacade.html#startcontentsharefromscreencapture) and it's success and easy to use. But I found my shared screen has low resolution. 

## Tell us about the problem you are trying to solve and why is it hard?

So I try to increase resolution, but startContentShareFromScreenCapture only have 2 parameters. `sourceId`, `frameRate`.
And I can't find any other options.

## How are you currently solving a problem?

By the way, input devise can change `width`, `height`, `frameRate`, `maxBandwidthKbps` with [chooseVideoInputQuality](https://aws.github.io/amazon-chime-sdk-js/interfaces/audiovideofacade.html#choosevideoinputquality).

So I think startContentShareFromScreenCapture can also provide these options. Is it possible?

**Comment by ltrung** [comment]
@penguin-taling `startContentShareFromScreenCapture` uses `getDisplayMedia` from webRTC to capture the screen so it should get resolution similar to the screensize.
Can you share more details about your use case, device and browser info, and what you mean by low resolution?

**Comment by vidya-mohan** [comment]
Resolving as no response
