### ISSUE TITLE
Is there a blog?

### ISSUE THREAD

**Issue by ellismarte** [aws/amazon-chime-sdk-js#1586]
Hi i'd like to learn more about the chime backend architecture. Have you all posted anything online?

**Comment by simmkyu** [comment]
The [Building a Meeting Application using the Amazon Chime SDK post](https://aws.amazon.com/blogs/business-productivity/building-a-meeting-application-using-the-amazon-chime-sdk/) explains a high-level architecture and walkthrough of the Chime SDK serverless demo.

You can also review the list of Chime blog posts here:
https://aws.amazon.com/blogs/business-productivity/category/business-productivity/amazon-chime/
