### ISSUE TITLE
Users disappearing from meeting - [ERROR] SDK - missing TURN credentials - falling back to fetch

### ISSUE THREAD

**Issue by BC-Mikey** [aws/amazon-chime-sdk-js#1591]
### What happened and what did you expect to happen?

We are displaying a list of attendees currently in the meeting. At random points an attendee will receive this error:

```
react_devtools_backend.js:4049 2021-09-13T14:27:09.872Z [ERROR] SDK - missing TURN credentials - falling back to fetch
overrideMethod @ react_devtools_backend.js:4049
log @ ConsoleLogger.js?cddf:67
error @ ConsoleLogger.js?cddf:37
eval @ ReceiveTURNCredentialsTask.js?b904:46
eval @ ReceiveTURNCredentialsTask.js?b904:10
__awaiter @ ReceiveTURNCredentialsTask.js?b904:6
run @ ReceiveTURNCredentialsTask.js?b904:41
eval @ BaseTask.js?8feb:59
eval @ BaseTask.js?8feb:10
__awaiter @ BaseTask.js?8feb:6
baseRun @ BaseTask.js?8feb:46
eval @ SerialGroupTask.js?2be6:45
fulfilled @ SerialGroupTask.js?2be6:7
Promise.then (async)
step @ SerialGroupTask.js?2be6:9
fulfilled @ SerialGroupTask.js?2be6:7
Promise.then (async)
step @ SerialGroupTask.js?2be6:9
eval @ SerialGroupTask.js?2be6:10
__awaiter @ SerialGroupTask.js?2be6:6
run @ SerialGroupTask.js?2be6:37
eval @ BaseTask.js?8feb:59
eval @ BaseTask.js?8feb:10
__awaiter @ BaseTask.js?8feb:6
baseRun @ BaseTask.js?8feb:46
eval @ SerialGroupTask.js?2be6:45
fulfilled @ SerialGroupTask.js?2be6:7
Promise.then (async)
step @ SerialGroupTask.js?2be6:9
eval @ SerialGroupTask.js?2be6:10
__awaiter @ SerialGroupTask.js?2be6:6
run @ SerialGroupTask.js?2be6:37
eval @ BaseTask.js?8feb:59
eval @ BaseTask.js?8feb:10
__awaiter @ BaseTask.js?8feb:6
baseRun @ BaseTask.js?8feb:46
eval @ TimeoutTask.js?8903:40
eval @ TimeoutTask.js?8903:10
__awaiter @ TimeoutTask.js?8903:6
run @ TimeoutTask.js?8903:33
eval @ BaseTask.js?8feb:59
eval @ BaseTask.js?8feb:10
__awaiter @ BaseTask.js?8feb:6
baseRun @ BaseTask.js?8feb:46
eval @ SerialGroupTask.js?2be6:45
eval @ SerialGroupTask.js?2be6:10
__awaiter @ SerialGroupTask.js?2be6:6
run @ SerialGroupTask.js?2be6:37
eval @ BaseTask.js?8feb:59
eval @ BaseTask.js?8feb:10
__awaiter @ BaseTask.js?8feb:6
baseRun @ BaseTask.js?8feb:46
eval @ DefaultAudioVideoController.js?6ba3:730
eval @ DefaultAudioVideoController.js?6ba3:10
__awaiter @ DefaultAudioVideoController.js?6ba3:6
actionReconnect @ DefaultAudioVideoController.js?6ba3:700
eval @ DefaultAudioVideoController.js?6ba3:685
perform @ DefaultSessionStateController.js?a27f:68
eval @ DefaultAudioVideoController.js?6ba3:684
eval @ DefaultAudioVideoController.js?6ba3:10
__awaiter @ DefaultAudioVideoController.js?6ba3:6
eval @ DefaultAudioVideoController.js?6ba3:677
eval @ DefaultReconnectController.js?97ba:77
eval @ TimeoutScheduler.js?cdc8:18
setTimeout (async)
start @ TimeoutScheduler.js?cdc8:16
retryWithBackoff @ DefaultReconnectController.js?97ba:75
reconnect @ DefaultAudioVideoController.js?6ba3:677
handleMeetingSessionStatus @ DefaultAudioVideoController.js?6ba3:798
eval @ DefaultAudioVideoController.js?6ba3:626
perform @ DefaultSessionStateController.js?a27f:68
eval @ DefaultAudioVideoController.js?6ba3:621
rejected @ DefaultAudioVideoController.js?6ba3:8
Promise.then (async)
step @ DefaultAudioVideoController.js?6ba3:9
eval @ DefaultAudioVideoController.js?6ba3:10
__awaiter @ DefaultAudioVideoController.js?6ba3:6
actionUpdate @ DefaultAudioVideoController.js?6ba3:600
eval @ DefaultAudioVideoController.js?6ba3:503
perform @ DefaultSessionStateController.js?a27f:68
performDeferredAction @ DefaultSessionStateController.js?a27f:122
perform @ DefaultSessionStateController.js?a27f:76
eval @ DefaultAudioVideoController.js?6ba3:615
fulfilled @ DefaultAudioVideoController.js?6ba3:7
Promise.then (async)
step @ DefaultAudioVideoController.js?6ba3:9
eval @ DefaultAudioVideoController.js?6ba3:10
__awaiter @ DefaultAudioVideoController.js?6ba3:6
actionUpdate @ DefaultAudioVideoController.js?6ba3:600
eval @ DefaultAudioVideoController.js?6ba3:503
perform @ DefaultSessionStateController.js?a27f:68
update @ DefaultAudioVideoController.js?6ba3:502
resubscribe @ ReceiveVideoStreamIndexTask.js?af0d:102
handleIndexFrame @ ReceiveVideoStreamIndexTask.js?af0d:64
handleSignalingClientEvent @ ReceiveVideoStreamIndexTask.js?af0d:47
sendEvent @ DefaultSignalingClient.js?1c6f:246
receiveMessage @ DefaultSignalingClient.js?1c6f:199
eval @ DefaultSignalingClient.js?1c6f:257
Show 31 more frames
```

When this error is received, it looks like the attendee has been dropped from the meeting to all other attendees. However, the attendee themselves who experienced the issue did not actually get dropped from the room. They can still interact with the SDK. Call APIs, etc. They won't be able to communicate with anyone else, however. All other cameras/microphones or content shares that were communicating with them will have been disconnected.

Eventually, the user does get dropped from the room. But only upon seeing this error:

```
react_devtools_backend.js:4049 2021-09-13T14:29:16.535Z [ERROR] SDK - failed with status code ICEGatheringTimeoutWorkaround and error: serial group task AudioVideoReconnect/5ac3df78-7bf5-467c-a955-87f9c3fc0706/8d3d1e7e-627b-614e-4d18-535b7c6c1a70 was canceled due to subtask AudioVideoReconnect/5ac3df78-7bf5-467c-a955-87f9c3fc0706/8d3d1e7e-627b-614e-4d18-535b7c6c1a70/Timeout15000ms error: serial group task AudioVideoReconnect/5ac3df78-7bf5-467c-a955-87f9c3fc0706/8d3d1e7e-627b-614e-4d18-535b7c6c1a70/Timeout15000ms/UpdateSession was canceled due to subtask AudioVideoReconnect/5ac3df78-7bf5-467c-a955-87f9c3fc0706/8d3d1e7e-627b-614e-4d18-535b7c6c1a70/Timeout15000ms/UpdateSession/FinishGatheringICECandidatesTask error: canceling AudioVideoReconnect/5ac3df78-7bf5-467c-a955-87f9c3fc0706/8d3d1e7e-627b-614e-4d18-535b7c6c1a70/Timeout15000ms/UpdateSession/FinishGatheringICECandidatesTask due to the meeting status code: 16
overrideMethod @ react_devtools_backend.js:4049
log @ ConsoleLogger.js?cddf:67
error @ ConsoleLogger.js?cddf:37
handleMeetingSessionStatus @ DefaultAudioVideoController.js?6ba3:803
eval @ DefaultAudioVideoController.js?6ba3:744
perform @ DefaultSessionStateController.js?a27f:68
eval @ DefaultAudioVideoController.js?6ba3:741
rejected @ DefaultAudioVideoController.js?6ba3:8
Promise.then (async)
step @ DefaultAudioVideoController.js?6ba3:9
eval @ DefaultAudioVideoController.js?6ba3:10
__awaiter @ DefaultAudioVideoController.js?6ba3:6
actionReconnect @ DefaultAudioVideoController.js?6ba3:700
eval @ DefaultAudioVideoController.js?6ba3:685
perform @ DefaultSessionStateController.js?a27f:68
performDeferredAction @ DefaultSessionStateController.js?a27f:122
perform @ DefaultSessionStateController.js?a27f:76
eval @ DefaultAudioVideoController.js?6ba3:741
rejected @ DefaultAudioVideoController.js?6ba3:8
Promise.then (async)
step @ DefaultAudioVideoController.js?6ba3:9
eval @ DefaultAudioVideoController.js?6ba3:10
__awaiter @ DefaultAudioVideoController.js?6ba3:6
actionReconnect @ DefaultAudioVideoController.js?6ba3:700
eval @ DefaultAudioVideoController.js?6ba3:685
perform @ DefaultSessionStateController.js?a27f:68
performDeferredAction @ DefaultSessionStateController.js?a27f:122
perform @ DefaultSessionStateController.js?a27f:76
eval @ DefaultAudioVideoController.js?6ba3:741
rejected @ DefaultAudioVideoController.js?6ba3:8
```

This is happening very frequently to users with different computer & network types.

### Have you reviewed our existing documentation?

- [X] GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [X] FAQs [page](https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html)
- [X] README [page](https://github.com/aws/amazon-chime-sdk-js#amazon-chime-sdk-for-javascript)
- [X] Feature-specific [guides](https://github.com/aws/amazon-chime-sdk-js#guides)

### Reproduction steps

Log into our QA environment:
https://d3e6r5h1xj0f5h.cloudfront.net/

- Choose a unique Room ID (such as using the time or date)
- One user must log in with the First Name of 'speaker1'. Any user afterward can use any first name they'd like

The issue seems to occur easily with many people in the room. But has also been reproduced after about 15 minutes if you just log in with 2 people.

### Amazon Chime SDK for JavaScript version

2.11.0

### What browsers are you seeing the problem on?

Google Chrome, Firefox, Safari

### Browser version

Chrome Version 92

### Browser console logs

ping update : {"meeting":"5ac3df78-7bf5-467c-a955-87f9c3fc0706","meetingEnded":false,"state":{"audio":{"status":true,"exceptions":["user_304","user_417","user_75","user_796"]},"video":{"status":true,"exceptions":[]},"screen":{"status":false,"exceptions":["user_796"]},"queue":[],"attendees":[{"firstName":"Ludovic","lastName":"Francois","attendeeId":"cd23f40b-d30a-f0a6-d326-3dfc64fdb208","userId":"user_796","email":"Ludovic@Francois.com"},{"firstName":"George","lastName":"A","attendeeId":"54037d0e-7b29-26c7-1ec8-7ede45dc044c","userId":"user_304","email":"George@A.com"},{"firstName":"Memo","lastName":"LastName","attendeeId":"755d9a3b-dd6d-2a5e-78e6-9c3a77a0c7f6","userId":"user_75","email":"Memo@LastName.com"},{"firstName":"Alexis","lastName":"Trackit","attendeeId":"3ca8989a-3529-c061-402d-082047cb2200","userId":"user_225","email":"Alexis@Trackit.com"},{"firstName":"Speaker3","lastName":"Pham","attendeeId":"f7aef9c8-6a3d-a613-2b30-b40c9ad38fc9","userId":"user_97","email":"Speaker3@Pham.com"},{"firstName":"test123","lastName":"LastName","attendeeId":"9b9e90ba-b095-b168-1d3e-4a9ba7c62446","userId":"user_570","email":"test123@LastName.com"},{"firstName":"clément","lastName":"LastName","attendeeId":"c68ec82e-632b-b04f-74a3-1075de3a5e5c","userId":"user_799","email":"clément@LastName.com"},{"firstName":"Rick","lastName":"Albertson","attendeeId":"f1bd0f75-3511-496c-7cb6-a095191396f0","userId":"user_333","email":"Rick@Albertson.com"},{"firstName":"Khai","lastName":"Pham","attendeeId":"34549083-6ac0-584e-edf6-c0d57e81f786","userId":"user_767","email":"Khai@Pham.com"},{"firstName":"Khai2","lastName":"Edge","attendeeId":"1a23d833-319f-2728-5bc8-3b634a8beab1","userId":"user_599","email":"Khai2@Edge.com"},{"firstName":"Jimmy","lastName":"Carfagno","attendeeId":"2d38c0c4-8178-0242-8d2e-46756236d24e","userId":"user_744","email":"Jimmy@Carfagno.com"},{"firstName":"Julian","lastName":"LastName","attendeeId":"606bcba7-0319-af66-8fd7-5d2c6dc48381","userId":"user_430","email":"Julian@LastName.com"},{"firstName":"speaker1","lastName":"Carreiro","attendeeId":"8d3d1e7e-627b-614e-4d18-535b7c6c1a70","userId":"user_475","email":"speaker1@Carreiro.com"},{"firstName":"hugo","lastName":"trackit","attendeeId":"1656488f-5a68-ef8c-3c3c-7e3988c07bd3","userId":"user_593","email":"hugo@trackit.com"},{"firstName":"Rick","lastName":"Albertson","attendeeId":"d530d9e2-c56e-38e1-1b09-e0b1bbe4d9ec","userId":"user_348","email":"Rick@Albertson.com"},{"firstName":"Robert","lastName":"Figueras","attendeeId":"3d4b8b49-2f0f-8cf9-0229-9c0818a189e1","userId":"user_810","email":"Robert@Figueras.com"}]}}
react_devtools_backend.js:4049 ping update : {"meeting":"5ac3df78-7bf5-467c-a955-87f9c3fc0706","meetingEnded":false,"state":{"audio":{"status":true,"exceptions":["user_304","user_417","user_75","user_796"]},"video":{"status":true,"exceptions":[]},"screen":{"status":false,"exceptions":["user_796"]},"queue":[],"attendees":[{"firstName":"Ludovic","lastName":"Francois","attendeeId":"cd23f40b-d30a-f0a6-d326-3dfc64fdb208","userId":"user_796","email":"Ludovic@Francois.com"},{"firstName":"George","lastName":"A","attendeeId":"54037d0e-7b29-26c7-1ec8-7ede45dc044c","userId":"user_304","email":"George@A.com"},{"firstName":"Memo","lastName":"LastName","attendeeId":"755d9a3b-dd6d-2a5e-78e6-9c3a77a0c7f6","userId":"user_75","email":"Memo@LastName.com"},{"firstName":"Alexis","lastName":"Trackit","attendeeId":"3ca8989a-3529-c061-402d-082047cb2200","userId":"user_225","email":"Alexis@Trackit.com"},{"firstName":"Speaker3","lastName":"Pham","attendeeId":"f7aef9c8-6a3d-a613-2b30-b40c9ad38fc9","userId":"user_97","email":"Speaker3@Pham.com"},{"firstName":"test123","lastName":"LastName","attendeeId":"9b9e90ba-b095-b168-1d3e-4a9ba7c62446","userId":"user_570","email":"test123@LastName.com"},{"firstName":"clément","lastName":"LastName","attendeeId":"c68ec82e-632b-b04f-74a3-1075de3a5e5c","userId":"user_799","email":"clément@LastName.com"},{"firstName":"Rick","lastName":"Albertson","attendeeId":"f1bd0f75-3511-496c-7cb6-a095191396f0","userId":"user_333","email":"Rick@Albertson.com"},{"firstName":"Khai","lastName":"Pham","attendeeId":"34549083-6ac0-584e-edf6-c0d57e81f786","userId":"user_767","email":"Khai@Pham.com"},{"firstName":"Khai2","lastName":"Edge","attendeeId":"1a23d833-319f-2728-5bc8-3b634a8beab1","userId":"user_599","email":"Khai2@Edge.com"},{"firstName":"Jimmy","lastName":"Carfagno","attendeeId":"2d38c0c4-8178-0242-8d2e-46756236d24e","userId":"user_744","email":"Jimmy@Carfagno.com"},{"firstName":"Julian","lastName":"LastName","attendeeId":"606bcba7-0319-af66-8fd7-5d2c6dc48381","userId":"user_430","email":"Julian@LastName.com"},{"firstName":"speaker1","lastName":"Carreiro","attendeeId":"8d3d1e7e-627b-614e-4d18-535b7c6c1a70","userId":"user_475","email":"speaker1@Carreiro.com"},{"firstName":"hugo","lastName":"trackit","attendeeId":"1656488f-5a68-ef8c-3c3c-7e3988c07bd3","userId":"user_593","email":"hugo@trackit.com"},{"firstName":"Rick","lastName":"Albertson","attendeeId":"d530d9e2-c56e-38e1-1b09-e0b1bbe4d9ec","userId":"user_348","email":"Rick@Albertson.com"},{"firstName":"Robert","lastName":"Figueras","attendeeId":"3d4b8b49-2f0f-8cf9-0229-9c0818a189e1","userId":"user_810","email":"Robert@Figueras.com"}]}}
react_devtools_backend.js:4049 2021-09-13T14:28:38.293Z [ERROR] SDK - missing TURN credentials - falling back to fetch
overrideMethod @ react_devtools_backend.js:4049
log @ ConsoleLogger.js?cddf:67
error @ ConsoleLogger.js?cddf:37
eval @ ReceiveTURNCredentialsTask.js?b904:46
eval @ ReceiveTURNCredentialsTask.js?b904:10
__awaiter @ ReceiveTURNCredentialsTask.js?b904:6
run @ ReceiveTURNCredentialsTask.js?b904:41
eval @ BaseTask.js?8feb:59
eval @ BaseTask.js?8feb:10
__awaiter @ BaseTask.js?8feb:6
baseRun @ BaseTask.js?8feb:46
eval @ SerialGroupTask.js?2be6:45
fulfilled @ SerialGroupTask.js?2be6:7
Promise.then (async)
step @ SerialGroupTask.js?2be6:9
fulfilled @ SerialGroupTask.js?2be6:7
Promise.then (async)
step @ SerialGroupTask.js?2be6:9
eval @ SerialGroupTask.js?2be6:10
__awaiter @ SerialGroupTask.js?2be6:6
run @ SerialGroupTask.js?2be6:37
eval @ BaseTask.js?8feb:59
eval @ BaseTask.js?8feb:10
__awaiter @ BaseTask.js?8feb:6
baseRun @ BaseTask.js?8feb:46
eval @ SerialGroupTask.js?2be6:45
fulfilled @ SerialGroupTask.js?2be6:7
Promise.then (async)
step @ SerialGroupTask.js?2be6:9
eval @ SerialGroupTask.js?2be6:10
__awaiter @ SerialGroupTask.js?2be6:6
run @ SerialGroupTask.js?2be6:37
eval @ BaseTask.js?8feb:59
eval @ BaseTask.js?8feb:10
__awaiter @ BaseTask.js?8feb:6
baseRun @ BaseTask.js?8feb:46
eval @ TimeoutTask.js?8903:40
eval @ TimeoutTask.js?8903:10
__awaiter @ TimeoutTask.js?8903:6
run @ TimeoutTask.js?8903:33
eval @ BaseTask.js?8feb:59
eval @ BaseTask.js?8feb:10
__awaiter @ BaseTask.js?8feb:6
baseRun @ BaseTask.js?8feb:46
eval @ SerialGroupTask.js?2be6:45
eval @ SerialGroupTask.js?2be6:10
__awaiter @ SerialGroupTask.js?2be6:6
run @ SerialGroupTask.js?2be6:37
eval @ BaseTask.js?8feb:59
eval @ BaseTask.js?8feb:10
__awaiter @ BaseTask.js?8feb:6
baseRun @ BaseTask.js?8feb:46
eval @ DefaultAudioVideoController.js?6ba3:730
eval @ DefaultAudioVideoController.js?6ba3:10
__awaiter @ DefaultAudioVideoController.js?6ba3:6
actionReconnect @ DefaultAudioVideoController.js?6ba3:700
eval @ DefaultAudioVideoController.js?6ba3:685
perform @ DefaultSessionStateController.js?a27f:68
performDeferredAction @ DefaultSessionStateController.js?a27f:122
perform @ DefaultSessionStateController.js?a27f:76
eval @ DefaultAudioVideoController.js?6ba3:741
rejected @ DefaultAudioVideoController.js?6ba3:8
Promise.then (async)
step @ DefaultAudioVideoController.js?6ba3:9
eval @ DefaultAudioVideoController.js?6ba3:10
__awaiter @ DefaultAudioVideoController.js?6ba3:6
actionReconnect @ DefaultAudioVideoController.js?6ba3:700
eval @ DefaultAudioVideoController.js?6ba3:685
perform @ DefaultSessionStateController.js?a27f:68
performDeferredAction @ DefaultSessionStateController.js?a27f:122
perform @ DefaultSessionStateController.js?a27f:76
eval @ DefaultAudioVideoController.js?6ba3:741
rejected @ DefaultAudioVideoController.js?6ba3:8
Show 29 more frames

**Comment by simmkyu** [comment]
### Browser logs

Your browser logs showed that the attendee (`8d3d1e7e-627b-614e-4d18-535b7c6c1a70`) received two error messages. 

```
2021-09-13T14:27:09.872Z [ERROR] SDK - missing TURN credentials - falling back to fetch
2021-09-13T14:29:16.535Z [ERROR] SDK - failed with status code ICEGatheringTimeoutWorkaround and error: serial group task AudioVideoReconnect/5ac3df78-7bf5-467c-a955-87f9c3fc0706/8d3d1e7e-627b-614e-4d18-535b7c6c1a70 was ...
```

### Thie Chime server logs

The Chime server logs indicate that the attendee got dropped at 14:26:59 several seconds before receiving the first error message in your client application. Between 14:26:59 and 14:29:56, the Chime server did not get any request from this attendee. At 14:29:56, the attendee successfully re-joined the meeting.

The attendee seemed to have a connectivity issue, failing to send any request between 14:26:59 and 14:29:56. While the Chime SDK for JavaScript retried the connection in your client application, it threw those error messages. Please see the retry behavior in the FAQ: https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html#when-does-the-amazon-chime-sdk-retry-the-connection-can-i-customize-this-retry-behavior


Time | Action
--|--
09/13/21 14:20:31 | Created using CreateAttendee, BatchCreateAttendees, CreateMeetingWithAttendees API in the server application
09/13/21 14:20:34 | Called the `meetingSession.audioVideo.start` API in the client application
09/13/21 14:20:34 | Successfully joined the meeting with a microphone
09/13/21 14:20:42 | Enabled a video
**09/13/21 14:26:59** | **Dropped from the meeting**
09/13/21 14:29:56 | Successfully re-joined the meeting
09/13/21 14:30:27 | Enabled a video
**09/13/21 14:37:57** | **Dropped again from the meeting**

### Next steps

- Could you ensure that the attendee has a stable internet connection? You can also cut an AWS customer support ticket to the AWS Chime team and securely attach your full browser logs.
- I see that you hosted a meeting at the `us-east-1 region. Note that you can specify the region close to your attendees.
  https://docs.aws.amazon.com/chime/latest/dg/chime-sdk-meetings-regions.html
- Your QA website (https://d3e6r5h1xj0f5h.cloudfront.net) asks for the Username/Password. Were you able to reproduce the bug without calling any API, e.g., starting a video or screen sharing?
  > But has also been reproduced after about 15 minutes if you just log in with 2 people.

**Comment by BC-Mikey** [comment]
Hi @simmkyu,
Thank you for the additional help & information!
We discovered some issues in our React application that was causing it to produce an exponential amount of re-renders and really ate at the browser's processing power. This seems to have been the cause of the issue because since resolving, we have not experienced them. I will close this issue and re-open with additional information & logging if it is rediscovered.

-Mikey
