### ISSUE TITLE
Display last frame when host pause screen share

### ISSUE THREAD

**Issue by AlexMCarv** [aws/amazon-chime-sdk-js#1592]
### What are you trying to do?
I am trying to get the videoTile to display the last frame in the attendee side, when the host pauses the screen sharing.
Currently, what I get is just a black screen. Is there some support to display the last frame shared instead?

In addition, are content share observers contentShareDidPause, contentShareDidStart, contentShareDidStop, and contentShareDidUnpause only called in the attendee that is sharing the video?

### What documentation have you looked at so far?
React components documentation: https://aws.github.io/amazon-chime-sdk-component-library-react/?path=/story/sdk-providers-contentshareprovider--page
API Overview (Section 8): https://aws.github.io/amazon-chime-sdk-js/modules/apioverview.html
Content share guide: https://aws.github.io/amazon-chime-sdk-js/modules/contentshare.html

**Comment by simmkyu** [comment]
> I am trying to get the videoTile to display the last frame in the attendee side, when the host pauses the screen sharing.
Currently, what I get is just a black screen. Is there some support to display the last frame shared instead?

No, the Chime SDK for JavaScript does not support displaying the last frame. The SDK uses the browser's [`getDisplayMedia` API](https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getDisplayMedia) (or the `getUserMedia` API when the `sourceId` is provided, e.g., in Electron) to acquire a `MediaStream` object for the screen. 

When you pause/unpause a stream, the SDK simply toggles the browser's [`MediaStreamTrack.enabled`](https://developer.mozilla.org/en-US/docs/Web/API/MediaStreamTrack/enabled) property. When paused, the browser renders a black video frame.

⠀⠀

> In addition, are content share observers contentShareDidPause, contentShareDidStart, contentShareDidStop, and contentShareDidUnpause only called in the attendee that is sharing the video?

Yes, only the attendee who shares a screen receives those content-share observer events: `contentShareDidPause`, `contentShareDidStart`, `contentShareDidStop`, and `contentShareDidUnpause`. In the Chime SDK, the screen share is no different from a regular video on a receiver's side. When one attendee enables screen sharing, other attendees will receive the video tile state containing the screen share information in the `videoTileDidUpdate` observer.

From https://github.com/aws/amazon-chime-sdk-js#screen-and-content-share
> When you or other attendees share content (a screen capture, a video file, or any other MediaStream object), the content attendee (attendee-id#content) joins the session and shares content as if a regular attendee shares a video.
> 
> For example, your attendee ID is "my-id". When you call meetingSession.audioVideo.startContentShare, the content attendee "my-id#content" will join the session and share your content.

**Comment by ltrung** [comment]
@AlexMCarv I recently made a change in https://github.com/aws/amazon-chime-sdk-js/pull/1872 to allow showing last frame when pausing a remote video so I think you workaround to get what you want.
Basically when users click on pause content share you can send data messages to all other remote attendees and call audioVideo.pauseVideoTile() to show the last frame. However, this only works with remote attendees and not your local user.

**Comment by vidya-mohan** [comment]
Resolving - hope this solution works for you @AlexMCarv
