### ISSUE TITLE
chooseAudioOutputDevice giving error in case of Chrome browser from Android device.

### ISSUE THREAD

**Issue by Sagar1219** [aws/amazon-chime-sdk-js#1601]
### What happened and what did you expect to happen?

Hi Team,

I am opening my video calling application in Chrome mobile app but chooseAudioOutputDevice() is producing the below error:

`Uncaught (in promise) Error: Cannot select audio output device. This browser does not support setSinkId.`

The thing to note here is it's working perfectly in Chrome Desktop application.

### Have you reviewed our existing documentation?

- [X] GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [X] FAQs [page](https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html)
- [X] README [page](https://github.com/aws/amazon-chime-sdk-js#amazon-chime-sdk-for-javascript)
- [X] Feature-specific [guides](https://github.com/aws/amazon-chime-sdk-js#guides)

### Reproduction steps

This is the code, although I think the code should be okay as it's working fine on Desktop.

```
await audioVideo.chooseAudioInputDevice(
            audioInputs[0].deviceId
        );
        await audioVideo.chooseAudioOutputDevice(
            audioOutputDevices[0].deviceId
        );
        await audioVideo.chooseVideoInputDevice(
            videoInputs[0].deviceId
        );
```

### Amazon Chime SDK for JavaScript version

2.13.0

### What browsers are you seeing the problem on?

Chrome Mobile App 

### Browser version

Chrome (93.0.4577.82)

### Meeting and Attendee ID Information.

Meeting Id : 5680b73e-ca47-4379-ae92-930e16850706

### Browser console logs

![Screenshot (271)](https://user-images.githubusercontent.com/14037958/133618229-8de5c61b-e846-4343-b771-2094025e10d9.png)

**Comment by michhyun1** [comment]
Please check out our FAQ: https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html#i-am-getting-cannot-select-audio-output-device-this-browser-does-not-support-setsinkid-error-on-the-browser-console-is-this-a-known-issue.

Hopefully this answers your questions.

**Comment by Sagar1219** [comment]
Thanks for the response,

Found this issue in a particular Chrome Browser ( on laptop ), where `await audioVideo.listAudioInputDevices();` is giving list of devices without the device Ids.

```
Array [ MediaDeviceInfo ]
​ 0:  MediaDeviceInfo { deviceId: "", kind: "audioinput", groupId: "4tL0Aggdgq5BFSQ0TtfZB8C0J2YvJlPtKbuMtX3s5K4=", … }
​​  deviceId: ""
​​  groupId: "4tL0Aggdgq5BFSQ0TtfZB8C0J2YvJlPtKbuMtX3s5K4="
​​  kind: "audioinput"
​​  label: ""
​​  <prototype>: MediaDeviceInfoPrototype { toJSON: toJSON(), deviceId: Getter, kind: Getter, … }
​   length: 1

```
As a result, this is not working,
```
await audioVideo.chooseAudioInputDevice(
    audioInputs[0].deviceId
);
```
Same behaviour is their in case of `await audioVideo.listAudioOutputDevices();` and `await audioVideo.listVideoInputDevices();`

Browser version is latest: Version 93.0.4577.82 (Official Build) (64-bit)
​​

**Comment by michhyun1** [comment]
From our FAQ: 
`
The device controller includes an injectable device label trigger which allows you to perform custom behavior in case there are no labels, such as creating a temporary audio/video stream to unlock the device names, which is the default behavior.
`

Basically, sometimes we aren't able to retrieve the Device labels by simply calling listAudioOutputDevices() - it calls enumerateDevice WebRTC API behind the scenes. In order to get the device labels, we call getUserMedia to "unlock" those device labels and then we immediately release any stream that was retrieved when calling getUserMedia. 

You can see that here:
https://github.com/aws/amazon-chime-sdk-js/blob/deb45ad946aee79bf61f76f84b0463cfca8c6b0e/guides/03_API_Overview.md#2a-configure-the-device-label-trigger-optional

**Comment by michhyun1** [comment]
For chooseAudioOutputDevice, some browsers just don't support selecting an audio output device. You'll need to check if supportSetinkId is true before calling chooseAudioOutputDevice. 

https://caniuse.com/?search=setSinkId

**Comment by michhyun1** [comment]
I'll close this issue now - feel free to reopen if you need any more guidance
