### ISSUE TITLE
The callback `audioVideoDidStartConnecting` is fired if the `<LocalVideo/>` component is frequently mounted/unmounted

### ISSUE THREAD

**Issue by amardeep24** [aws/amazon-chime-sdk-js#1602]
Hi Team,

We have a use case where we need to frequently unmount/re-mount the  `<LocalVideo/>`  component. We noticed that while doing so we noticed that this callback `audioVideoDidStartConnecting` in `AudioVideoFacade.addObserver` is getting invoked. This is not correct. This callback is used by us to detect network disruptions. 

We had the below console warning printed when this callback is fired:
```
react_devtools_backend.js:4049 2021-09-16T13:27:35.382Z [WARN] SDK - will retry due to status code TaskFailed and error: serial group task AudioVideoUpdate/2a8be406-c7ce-43ce-b4da-fe0b50c80706/bec3930c-95cd-dfe4-9f03-9a227a4fab65 was canceled due to subtask AudioVideoUpdate/2a8be406-c7ce-43ce-b4da-fe0b50c80706/bec3930c-95cd-dfe4-9f03-9a227a4fab65/ReceiveVideoInputTask error: Cannot read properties of undefined (reading ‘getSettings’)
```
We went through the code and the issue seems to be coming from the below line when the `getSettings` is called on an `undefined` object.

https://github.com/aws/amazon-chime-sdk-js/blob/c0c78983bdd6637a922c68237ffc0206eba37028/src/audiovideocontroller/DefaultAudioVideoController.ts#L798

We have a custom network retry screen that is shown when the network is disconnected for a while, this issue is triggerin g that screen in a consistent way when we have to re-mount/unmount the `<LocalVideo/>`  component.

Tested on Google Chrome: Version 93.0.4577.63 (Official Build) (x86_64)

**Comment by ltrung** [comment]
This should be fixed in PR https://github.com/aws/amazon-chime-sdk-js/pull/1617 so closing the issue.
