### ISSUE TITLE
realtimeSubscribeToReceiveDataMessage can't receive message before audiovideo.start

### ISSUE THREAD

**Issue by ReflexFox** [aws/amazon-chime-sdk-js#1612]
### What are you trying to do?

I'm trying to build a waiting room before attendee audiovideo.start

Is there any way before attendee audiovideo.start to realtimeSubscribeToReceiveDataMessage？

**Comment by ReflexFox** [comment]
i try to use  audioVideo.start({signalingOnly: true }) But also can not receive any message

**Comment by ltrung** [comment]
Unfortunately, sending data message requires the web socket connection that starts via `audioVideo.start()`.  You would need to set up your own websocket or using Chime Messaging SDK `https://aws.amazon.com/blogs/business-productivity/build-chat-features-into-your-application-with-amazon-chime-sdk-messaging/`.

**Comment by devalevenkatesh** [comment]
Closing this issue as we currently do not have a way to do this without the Amazon Chime SDK for JavaScript sets the WebSocket connection. Please feel free to re-open if you need more information.
