### ISSUE TITLE
Audio input output devices not listed when using USB Headphone

### ISSUE THREAD

**Issue by gsudhanshu** [aws/amazon-chime-sdk-js#1621]
### What happened and what did you expect to happen?

While joining meeting using USB Headphone, I can hear the meeting voice but my voice is not audible to other attendees.

When I click on audio/video settings: my audio and video devices are not listed.

browser console logs:
Uncaught SyntaxError: Unexpected token 'export'
core.js:27932 Angular is running in development mode. Call enableProdMode() to enable production mode.
conference.component.ts:16 inside ConferenceComponent constructor
conference.component.ts:31 toUserId: -1
socket.service.ts:33 Socket connected
socket.io/?EIO=4&transport=polling&t=Nmd8ApR&sid=_ZSvq1qMNqp3LQPvAAAT:1 Failed to load resource: the server responded with a status of 400 ()
websocket.js:190 WebSocket connection to 'wss://hytech.evareg.com/socket.io/?EIO=4&transport=websocket&sid=_ZSvq1qMNqp3LQPvAAAT' failed: WebSocket is closed before the connection is established.
doClose @ websocket.js:190
socket.service.ts:35 Received updated attendee List on socket connect
call-attendee-list.component.ts:76 Meeting Session established
call-attendee-list.component.ts:79 meeting started
meeting.service.ts:154 data meeting{"meetingId":218,"meetingResponse":{"Meeting":{"MeetingId":"e8b9603e-9cf6-4718-9c58-3e11a6e10706","ExternalMeetingId":"hytechevaregcom_Meeting218","MediaPlacement":{"AudioHostUrl":"a0e29ddb119a69943500339e915142c0.k.m2.as1.app.chime.aws:3478","AudioFallbackUrl":"wss://haxrp.m2.as1.app.chime.aws:443/calls/e8b9603e-9cf6-4718-9c58-3e11a6e10706","ScreenDataUrl":"wss://bitpw.m2.as1.app.chime.aws:443/v2/screen/e8b9603e-9cf6-4718-9c58-3e11a6e10706","ScreenSharingUrl":"wss://bitpw.m2.as1.app.chime.aws:443/v2/screen/e8b9603e-9cf6-4718-9c58-3e11a6e10706","ScreenViewingUrl":"wss://bitpw.m2.as1.app.chime.aws:443/ws/connect?passcode=null&viewer_uuid=null&X-BitHub-Call-Id=e8b9603e-9cf6-4718-9c58-3e11a6e10706","SignalingUrl":"wss://signal.m2.as1.app.chime.aws/control/e8b9603e-9cf6-4718-9c58-3e11a6e10706","TurnControlUrl":"https://ccp.cp.ue1.app.chime.aws/v2/turn_sessions"},"MediaRegion":"ap-southeast-1"},"@metadata":{"statusCode":200,"effectiveUri":"https://chime.us-east-1.amazonaws.com/meetings/e8b9603e-9cf6-4718-9c58-3e11a6e10706","headers":{"x-amzn-requestid":"c6011145-5524-42b2-93b3-89183844775a","content-type":"application/json","content-length":"893","date":"Mon, 27 Sep 2021 12:00:24 GMT"},"transferStats":{"http":[[]]}}},"chime_enable_invite":1,"chime_attendee_limit":250,"theme_folder":"hytech","chime_socket":1,"meeting":{"id":218,"meeting_title":"Review Meeting","chime_meeting_id":"e8b9603e-9cf6-4718-9c58-3e11a6e10706","conference_program_id":null,"host_user_id":1,"scheduled_date":"2021-09-27","start_time":"17:30:00","duration":0,"status":"active","created_on":"2021-09-27 11:38:38","modified_on":"2021-09-27 11:55:12","app_instance_arn":null,"content_type_id":17,"content_id":null,"domain_id":1,"event_id":1,"meeting_type":1,"meeting_hosts":[{"id":440,"meeting_id":218,"host_user_id":1,"status":1,"created_at":"2021-09-27T11:38:38.000000Z","updated_at":"2021-09-27T11:38:38.000000Z"},{"id":441,"meeting_id":218,"host_user_id":7,"status":1,"created_at":"2021-09-27T11:38:38.000000Z","updated_at":"2021-09-27T11:38:38.000000Z"}]},"attendeeId":2270,"attendeeName":"Mukesh Kumar","attendeeResponse":{"Attendee":{"ExternalUserId":"User72","AttendeeId":"76abcb69-b9c7-d1d6-1171-4495a4a98444","JoinToken":"NzZhYmNiNjktYjljNy1kMWQ2LTExNzEtNDQ5NWE0YTk4NDQ0OjJmNjNmOTY3LWZjNWMtNGQyNS05NmMxLTc0YTA3YTAyZGU5NA"},"@metadata":{"statusCode":201,"effectiveUri":"https://chime.us-east-1.amazonaws.com/meetings/e8b9603e-9cf6-4718-9c58-3e11a6e10706/attendees","headers":{"x-amzn-requestid":"29584917-c945-4dd7-b9a7-f9c593e5b1cc","content-type":"application/json","content-length":"217","date":"Mon, 27 Sep 2021 12:00:24 GMT"},"transferStats":{"http":[[]]}}},"attendeeList":[{"id":2266,"meeting_id":218,"attendee_user_id":1,"join_token":"YzJjYmIzZTUtZGFjZi02ZGRlLTQ2ZGEtZTc2MDkzNTViNTJhOmE3OTE5ODA1LTNjZmYtNDYwMS04OGI1LTRkNTVlZTlhZjliZg","join_url":null,"zoom_webinar_id":null,"status":"active","created_on":"2021-09-27 11:55:12","modified_on":"2021-09-27 11:55:12","chime_attendee_id":"c2cbb3e5-dacf-6dde-46da-e7609355b52a","full_name":"Manoj Verma","isHost":1},{"id":2267,"meeting_id":218,"attendee_user_id":7,"join_token":"ZmZhNGIyZmUtMGFmZS05NjdjLTExYzgtMzNkMjcxOTYxYjIyOmRiZDVjODczLTFlYTUtNDY2NS1hMjdjLWE2MWI1OTMxNjMxYg","join_url":null,"zoom_webinar_id":null,"status":"active","created_on":"2021-09-27 11:57:39","modified_on":"2021-09-27 11:57:39","chime_attendee_id":"ffa4b2fe-0afe-967c-11c8-33d271961b22","full_name":"Sudhanshu Garg","isHost":1},{"id":2268,"meeting_id":218,"attendee_user_id":6,"join_token":"ZWQwMjA4MmUtOTRhOC02ZGY0LWU4YjQtODM3ZWM5ZTViOGM3OmVlNjY5YmFiLTU3NTctNGU3OC05MGIzLTQxNzlmYTE4YjY0OQ","join_url":null,"zoom_webinar_id":null,"status":"active","created_on":"2021-09-27 11:58:25","modified_on":"2021-09-27 11:58:25","chime_attendee_id":"ed02082e-94a8-6df4-e8b4-837ec9e5b8c7","full_name":"Rajat Kesharwani","isHost":0},{"id":2269,"meeting_id":218,"attendee_user_id":152,"join_token":"OGI2OTJkOGUtYmVhMy04MTkyLTU0OGQtZmQ0NTM3YTNhZmZlOmNmMzdjMTQ3LWU2YTAtNGMyOC04NTMxLTg0ZTdkN2JjNzUzNA","join_url":null,"zoom_webinar_id":null,"status":"active","created_on":"2021-09-27 12:00:07","modified_on":"2021-09-27 12:00:07","chime_attendee_id":"8b692d8e-bea3-8192-548d-fd4537a3affe","full_name":"Srihari Reddy","isHost":0},{"id":2270,"meeting_id":218,"attendee_user_id":72,"join_token":"NzZhYmNiNjktYjljNy1kMWQ2LTExNzEtNDQ5NWE0YTk4NDQ0OjJmNjNmOTY3LWZjNWMtNGQyNS05NmMxLTc0YTA3YTAyZGU5NA","join_url":null,"zoom_webinar_id":null,"status":"active","created_on":"2021-09-27 12:00:24","modified_on":"2021-09-27 12:00:24","chime_attendee_id":"76abcb69-b9c7-d1d6-1171-4495a4a98444","full_name":"Mukesh Kumar","isHost":0}],"prevChats":[],"logoURL":"https://d1e02s8gfmqaad.cloudfront.net/storage/app/public/hytech/images/logo1631256780.png"}
call-controls.component.ts:154 Array(1)0: InputDeviceInfodeviceId: ""groupId: "1da6d2a6b99312ff480a917a4a72570a718552f1e5cc67e0aa4778a270457408"kind: "audioinput"label: ""[[Prototype]]: InputDeviceInfolength: 1[[Prototype]]: Array(0)
call-controls.component.ts:175 Array(1)0: MediaDeviceInfo {deviceId: '', kind: 'audiooutput', label: '', groupId: '1da6d2a6b99312ff480a917a4a72570a718552f1e5cc67e0aa4778a270457408'}length: 1[[Prototype]]: Array(0)
socket.io/?EIO=4&transport=polling&t=Nmd8B3O&sid=0hfsnUBUJL6tL4wIAAAc:1 Failed to load resource: the server responded with a status of 400 ()
websocket.js:190 WebSocket connection to 'wss://hytech.evareg.com/socket.io/?EIO=4&transport=websocket&sid=0hfsnUBUJL6tL4wIAAAc' failed: WebSocket is closed before the connection is established.
doClose @ websocket.js:190
socket.io/?EIO=4&transport=polling&t=Nmd8BC_&sid=uxF0ldTJJ0HMDibgAAAf:1 Failed to load resource: the server responded with a status of 400 ()
websocket.js:190 WebSocket connection to 'wss://hytech.evareg.com/socket.io/?EIO=4&transport=websocket&sid=uxF0ldTJJ0HMDibgAAAf' failed: WebSocket is closed before the connection is established.
doClose @ websocket.js:190
CreatePeerConnectionTask.ts:104 [Deprecation] Obsolete constraint named googCpuOveruseEncodeUsage is ignored. Please stop using it.
(anonymous) @ CreatePeerConnectionTask.ts:104
CreatePeerConnectionTask.ts:104 [Deprecation] Obsolete constraint named googCpuUnderuseThreshold is ignored. Please stop using it.
(anonymous) @ CreatePeerConnectionTask.ts:104
CreatePeerConnectionTask.ts:104 [Deprecation] Obsolete constraint named googCpuOveruseThreshold is ignored. Please stop using it.
(anonymous) @ CreatePeerConnectionTask.ts:104
core.js:6157 ERROR Error: Uncaught (in promise): TypeError: Cannot read properties of undefined (reading 'deviceId')
TypeError: Cannot read properties of undefined (reading 'deviceId')
    at ConferenceVideoComponent.<anonymous> (conference-video.component.ts:136)
    at Generator.next (<anonymous>)
    at fulfilled (tslib.es6.js:73)
    at ZoneDelegate.invoke (zone-evergreen.js:372)
    at Object.onInvoke (core.js:28535)
    at ZoneDelegate.invoke (zone-evergreen.js:371)
    at Zone.run (zone-evergreen.js:134)
    at zone-evergreen.js:1276
    at ZoneDelegate.invokeTask (zone-evergreen.js:406)
    at Object.onInvokeTask (core.js:28522)
    at resolvePromise (zone-evergreen.js:1213)
    at zone-evergreen.js:1120
    at fulfilled (tslib.es6.js:73)
    at ZoneDelegate.invoke (zone-evergreen.js:372)
    at Object.onInvoke (core.js:28535)
    at ZoneDelegate.invoke (zone-evergreen.js:371)
    at Zone.run (zone-evergreen.js:134)
    at zone-evergreen.js:1276
    at ZoneDelegate.invokeTask (zone-evergreen.js:406)
    at Object.onInvokeTask (core.js:28522)
defaultErrorLogger @ core.js:6157
call-controls.component.ts:157 Enter in inpu
call-controls.component.ts:178 Enter in out
socket.service.ts:33 Socket connected
socket.service.ts:35 Received updated attendee List on socket connect
2meeting.service.ts:416 postCreateLogs
2core.js:6157 ERROR Error: Uncaught (in promise): NotAllowedError: Permission denied
    at resolvePromise (zone-evergreen.js:1213)
    at zone-evergreen.js:1120
    at rejected (tslib.es6.js:74)
    at ZoneDelegate.invoke (zone-evergreen.js:372)
    at Object.onInvoke (core.js:28535)
    at ZoneDelegate.invoke (zone-evergreen.js:371)
    at Zone.run (zone-evergreen.js:134)
    at zone-evergreen.js:1276
    at ZoneDelegate.invokeTask (zone-evergreen.js:406)
    at Object.onInvokeTask (core.js:28522)
defaultErrorLogger @ core.js:6157
meeting.service.ts:416 postCreateLogs
core.js:6157 ERROR Error: Uncaught (in promise): NotAllowedError: Permission denied
    at resolvePromise (zone-evergreen.js:1213)
    at zone-evergreen.js:1120
    at rejected (tslib.es6.js:74)
    at ZoneDelegate.invoke (zone-evergreen.js:372)
    at Object.onInvoke (core.js:28535)
    at ZoneDelegate.invoke (zone-evergreen.js:371)
    at Zone.run (zone-evergreen.js:134)
    at zone-evergreen.js:1276
    at ZoneDelegate.invokeTask (zone-evergreen.js:406)
    at Object.onInvokeTask (core.js:28522)
defaultErrorLogger @ core.js:6157
CreatePeerConnectionTask.ts:104 [Deprecation] Obsolete constraint named googCpuOveruseEncodeUsage is ignored. Please stop using it.
(anonymous) @ CreatePeerConnectionTask.ts:104
CreatePeerConnectionTask.ts:104 [Deprecation] Obsolete constraint named googCpuUnderuseThreshold is ignored. Please stop using it.
(anonymous) @ CreatePeerConnectionTask.ts:104
CreatePeerConnectionTask.ts:104 [Deprecation] Obsolete constraint named googCpuOveruseThreshold is ignored. Please stop using it.
(anonymous) @ CreatePeerConnectionTask.ts:104

### Have you reviewed our existing documentation?

- [X] GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [X] FAQs [page](https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html)
- [X] README [page](https://github.com/aws/amazon-chime-sdk-js#amazon-chime-sdk-for-javascript)
- [X] Feature-specific [guides](https://github.com/aws/amazon-chime-sdk-js#guides)

### Reproduction steps

NA

### Amazon Chime SDK for JavaScript version

2.4.1

### What browsers are you seeing the problem on?

Chrome

### Browser version

93

### Browser console logs

pasted above

**Comment by devalevenkatesh** [comment]
Hi @gsudhanshu ,

Thanks for reporting the issue. From the pasted logs, I could see that the attendee did not provide the audio video permissions to the browser hence the audio video devices could not be listed.

```
2core.js:6157 ERROR Error: Uncaught (in promise): NotAllowedError: Permission denied
at resolvePromise (zone-evergreen.js:1213)
at zone-evergreen.js:1120
at rejected (tslib.es6.js:74)
```

Could you please ask the attendee to provide the audio-video permissions once prompted while joining the Amazon Chime SDK meeting? That should solve this issue.

Please let us know if you still face any issues. Also, the provided logs are not full INFO level logs and seem to be just ERROR logs, we request you to provide INFO level logs at least if issue persists.

**Comment by gsudhanshu** [comment]
hi @devalevenkatesh ,

thanks, the issue was permissions.

Is there a way through awschime-sdk-js that we can know if permissions are not granted for audio and video

Thanks!

**Comment by devalevenkatesh** [comment]
Cool, The JS SDK does not have any API to help with the permissions check.

I could find below API but it is still experimental and could not find a general available browser API:
https://developer.mozilla.org/en-US/docs/Web/API/Permissions/query

I am closing this issue now.
