### ISSUE TITLE
Cloud9 low disk space and JavaScript heap out of memory

### ISSUE THREAD

**Issue by albrich-me** [aws/amazon-chime-sdk-js#1630]
### What are you trying to do?

When following the directions to install the serverless demo, it appears to run out of disk space causing a variety of errors (unfortunately not captured).  After running the script in https://docs.aws.amazon.com/cloud9/latest/user-guide/move-environment.html under Resize an Amazon EBS volume used by an environment, I then got a JavaScript heap out of memory error.  Running export NODE_OPTIONS=--max_old_space_size=4096 in the terminal prior to the install solved that issue and allowed the deployment to succeed.

### How can the documentation be improved to help your use case?
Add a note or instructions to help users deal with both situations.

### What documentation have you looked at so far?

https://github.com/aws/amazon-chime-sdk-js/tree/master/demos/serverless

**Comment by devalevenkatesh** [comment]
Hi @albrich-me ,

Thanks for reporting this issue, we currently in the README do not have any Cloud 9 instructions to setup the demo and we would appreciate your help if you could put a PR to update the serverless deployment README instructions with deploying the serverless demo using Cloud 9 setup instructions.
