### ISSUE TITLE
Is 25 video tiles enabled by default now?

### ISSUE THREAD

**Issue by paul365** [aws/amazon-chime-sdk-js#1631]
### What are you trying to do?
Hello, I'm trying to use the 25 video tiles feature. Is this enabled by default now or do we need to request an increase? Also if it's possible to have more than 25 video tiles and how many are possible?

### How can the documentation be improved to help your use case?
Describe it more in the documentation.

### What documentation have you looked at so far?
README.md, Amazon Chime SDK Developer Guide, FAQ

**Comment by devalevenkatesh** [comment]
Hi @paul365 ,

We support up to 25 video tiles and should be enabled by default. Please let us know if you are experiencing any issues with it. If you have a use case where you would like more video tiles, we would like to learn more about it.

Request you to come through the AWS support for the same. Closing this issue now.
