### ISSUE TITLE
DefaultVideoTransformDevice is not removing observer correctly

### ISSUE THREAD

**Issue by Nanosync** [aws/amazon-chime-sdk-js#1636]
### What happened and what did you expect to happen?

In the file `DefaultVideoTransformDevice.ts:162`, the function `removeObserver` is adding the same observer that was removed. It should call `this.observers.delete(observer)`.

```
  removeObserver(observer: DefaultVideoTransformDeviceObserver): void {
    this.observers.add(observer);
  }
```

### Have you reviewed our existing documentation?

- [X] GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [X] FAQs [page](https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html)
- [X] README [page](https://github.com/aws/amazon-chime-sdk-js#amazon-chime-sdk-for-javascript)
- [X] Feature-specific [guides](https://github.com/aws/amazon-chime-sdk-js#guides)

### Reproduction steps

Issue is listed in description.

### Amazon Chime SDK for JavaScript version

2.18.0

### What browsers are you seeing the problem on?

Chrome

### Browser version

94.0.4606.61

### Meeting and Attendee ID Information.

N/A

### Browser console logs

N/A

**Comment by michhyun1** [comment]
Thanks for bringing this up - we've applied the changes accordingly and it will be released with our next release. Thanks
