### ISSUE TITLE
removeObserver on audioVideo does not work

### ISSUE THREAD

**Issue by gsudhanshu** [aws/amazon-chime-sdk-js#1643]
### What happened and what did you expect to happen?

I created a preview component and added it as an observer to meetingsession.audioVideo.addObserver

Then when the component was closed, I used removeObserver and moved to another component conference. now, I added conference as an observer.

Problem: Even after using removeObserver, I am getting updates in videoTileDidUpdate in both Preview component and Conference Component.

I should have only received update in conference component

### Have you reviewed our existing documentation?

- [X] GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [X] FAQs [page](https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html)
- [X] README [page](https://github.com/aws/amazon-chime-sdk-js#amazon-chime-sdk-for-javascript)
- [X] Feature-specific [guides](https://github.com/aws/amazon-chime-sdk-js#guides)

### Reproduction steps

NA

### Amazon Chime SDK for JavaScript version

2.4.1

### What browsers are you seeing the problem on?

chrome

### Browser version

92.0.4515.159

### Browser console logs

NA

**Comment by richnew10** [comment]
Can you reproduce this issue with the current version of the SDK? 2.4.1 is nine months old and no longer supported.

**Comment by devalevenkatesh** [comment]
Checking if you are implementing adding-removing the observers based on a reference?

```js
// Referenced observer
const observer = {
      videoTileDidUpdate: (tileState) => {
         .....
      },
};

// Add observer
audioVideo.addObserver(observer);

// Remove observer
audioVideo.removeObserver(observer);
```

**Comment by gsudhanshu** [comment]
@devalevenkatesh based on 'this'

My class implements audiovideoobserver

**Comment by ldai1** [comment]
Hi @gsudhanshu Have you checked the latest version of SDK? Can you still reproduce the issue?

Also, I am wondering how you implement the observer. Did you call`meetingSession.audioVideo.removeObserver(observer)` to remove the observer? We have a adding and removing observer guide here in [Readme](https://github.com/aws/amazon-chime-sdk-js/blob/master/README.md#starting-a-session) which perhaps can help you.

**Comment by michhyun1** [comment]
@gsudhanshu it seems that the issue you mentioned has been closed - is there anything you are waiting on to migrate to the latest version?

**Comment by gsudhanshu** [comment]
Will migrate after 14th

**Comment by ldai1** [comment]
Close the issue for now. Feel free to re-open it if you still see the issue.
