### ISSUE TITLE
mediaCapturePipleine screen share recording is missing last 5-10 seconds

### ISSUE THREAD

**Issue by benjamhawk** [aws/amazon-chime-sdk-js#1651]
### What happened and what did you expect to happen?

We have one user that broadcasts video, audio, and screen share to multiple users.
We are recording the stream using createMediaCapturePipline method and we are using the React chime library for our UI.

Generally, the artifacts are uploaded to S3 as:
 /audio (audio and video mp4)
/video  (screen share files)

The issue is that the screen share files consistently have the last 5-10 seconds of content missing from the recording.
If the screen share duration is less than around 5 seconds, then no files are uploaded at all.

### Have you reviewed our existing documentation?

- [X] GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [X] FAQs [page](https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html)
- [X] README [page](https://github.com/aws/amazon-chime-sdk-js#amazon-chime-sdk-for-javascript)
- [X] Feature-specific [guides](https://github.com/aws/amazon-chime-sdk-js#guides)

### Reproduction steps

1. Start Meeting
2. Start recording with createMediaCapturePipeline from the sdk
` const pipelineInfo = await chime
      .createMediaCapturePipeline({
        SourceType: "ChimeSdkMeeting",
        SourceArn: `arn:aws:chime:888888888:meeting:${meetingid}`,
        SinkType: "S3Bucket",
        SinkArn: "arn:aws:s3:::our-bucket-name",
      })
      .promise();`
3. start screen sharing with toggleContentShare from the amazon-chime-sdk-component-library-react package
4. End the screen share by either ending the meeting or calling toggleContentShare again

### Amazon Chime SDK for JavaScript version

2.989

### What browsers are you seeing the problem on?

Chrome

### Browser version

Version 94.0.4606.61 

### Meeting and Attendee ID Information.

Meeting ID - d02ce018-daad-4f7b-972b-2ed922ab0706

### Browser console logs

MeetingManager audioVideoDidStart] Meeting started successfully
react_devtools_backend.js:2526 2021-10-06T17:10:49.905Z [WARN] SDK - release media stream called
overrideMethod @ react_devtools_backend.js:2526
log @ ConsoleLogger.js?cddf:70
warn @ ConsoleLogger.js?cddf:34
releaseMediaStream @ ContentShareMediaStreamBroker.js?2273:41
eval @ ReleaseMediaStreamsTask.js?7524:44
eval @ ReleaseMediaStreamsTask.js?7524:10
__awaiter @ ReleaseMediaStreamsTask.js?7524:6
run @ ReleaseMediaStreamsTask.js?7524:22
eval @ BaseTask.js?8feb:59
eval @ BaseTask.js?8feb:10
__awaiter @ BaseTask.js?8feb:6
baseRun @ BaseTask.js?8feb:46
eval @ SerialGroupTask.js?2be6:45
fulfilled @ SerialGroupTask.js?2be6:7
Promise.then (async)
step @ SerialGroupTask.js?2be6:9
eval @ SerialGroupTask.js?2be6:10
__awaiter @ SerialGroupTask.js?2be6:6
run @ SerialGroupTask.js?2be6:37
eval @ BaseTask.js?8feb:59
eval @ BaseTask.js?8feb:10
__awaiter @ BaseTask.js?8feb:6
baseRun @ BaseTask.js?8feb:46
eval @ DefaultAudioVideoController.js?6ba3:524
fulfilled @ DefaultAudioVideoController.js?6ba3:7
Promise.then (async)
step @ DefaultAudioVideoController.js?6ba3:9
eval @ DefaultAudioVideoController.js?6ba3:10
__awaiter @ DefaultAudioVideoController.js?6ba3:6
actionDisconnect @ DefaultAudioVideoController.js?6ba3:508
eval @ DefaultAudioVideoController.js?6ba3:498
perform @ DefaultSessionStateController.js?a27f:68
eval @ DefaultAudioVideoController.js?6ba3:495
stopReturningPromise @ DefaultAudioVideoController.js?6ba3:494
stop @ DefaultAudioVideoController.js?6ba3:505
stopContentShare @ DefaultContentShareController.js?7a0c:101
stopContentShare @ DefaultAudioVideoFacade.js?166e:329
eval @ index.esm.js?e166:6730
step @ index.esm.js?e166:78
eval @ index.esm.js?e166:59
eval @ index.esm.js?e166:52
__awaiter @ index.esm.js?e166:48
MeetingManager.leave @ index.esm.js?e166:6725
_callee$ @ Navbar.tsx?d77a:42
tryCatch @ runtime.js?96cf:63
invoke @ runtime.js?96cf:293
eval @ runtime.js?96cf:118
asyncGeneratorStep @ asyncToGenerator.js?1da1:3
_next @ asyncToGenerator.js?1da1:25
eval @ asyncToGenerator.js?1da1:32
eval @ asyncToGenerator.js?1da1:21
onClick @ Navbar.tsx?d77a:40
callCallback @ react-dom.development.js?61bb:188
invokeGuardedCallbackDev @ react-dom.development.js?61bb:237
invokeGuardedCallback @ react-dom.development.js?61bb:292
invokeGuardedCallbackAndCatchFirstError @ react-dom.development.js?61bb:306
executeDispatch @ react-dom.development.js?61bb:389
executeDispatchesInOrder @ react-dom.development.js?61bb:414
executeDispatchesAndRelease @ react-dom.development.js?61bb:3278
executeDispatchesAndReleaseTopLevel @ react-dom.development.js?61bb:3287
forEachAccumulated @ react-dom.development.js?61bb:3259
runEventsInBatch @ react-dom.development.js?61bb:3304
runExtractedPluginEventsInBatch @ react-dom.development.js?61bb:3514
handleTopLevel @ react-dom.development.js?61bb:3558
batchedEventUpdates$1 @ react-dom.development.js?61bb:21871
batchedEventUpdates @ react-dom.development.js?61bb:795
dispatchEventForLegacyPluginEventSystem @ react-dom.development.js?61bb:3568
attemptToDispatchEvent @ react-dom.development.js?61bb:4267
dispatchEvent @ react-dom.development.js?61bb:4189
unstable_runWithPriority @ scheduler.development.js?3069:653
runWithPriority$1 @ react-dom.development.js?61bb:11039
discreteUpdates$1 @ react-dom.development.js?61bb:21887
discreteUpdates @ react-dom.development.js?61bb:806
dispatchDiscreteEvent @ react-dom.development.js?61bb:4168
Show 42 more frames
react_devtools_backend.js:2526 2021-10-06T17:10:49.907Z [WARN] SDK - release media stream called

**Comment by benjamhawk** [comment]
Thanks for the reply. It appears to be happening in every meeting and is usually around 5-10 seconds that is cut off from the end

**Comment by tenge-amzn** [comment]
This should be fixed. Let us know if you still see the issue
