### ISSUE TITLE
Iphone Audio low after IOS update

### ISSUE THREAD

**Issue by benjing** [aws/amazon-chime-sdk-js#1653]
### What happened and what did you expect to happen?

We have been using chime sdk js since August

Just recently we have noticed that the newest IOS update for iPhone has made the audio come out softer than it usually does. We tested using iPhones with older IOS versions like 14.7 and 14.0 and the sound comes through the speaker and is louder than when using IOS 15.

we believe it might be that it is using handset speakers instead of loud speaker.

We expected the sound to be the same volume or around the same volume for when on loudspeaker in a normal phone call.

### Have you reviewed our existing documentation?

- [X] GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [X] FAQs [page](https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html)
- [X] README [page](https://github.com/aws/amazon-chime-sdk-js#amazon-chime-sdk-for-javascript)
- [X] Feature-specific [guides](https://github.com/aws/amazon-chime-sdk-js#guides)

### Reproduction steps

Using chime sdk js 2.18 start a call on an iPhone with IOS 15.0

### Amazon Chime SDK for JavaScript version

2.18

### What browsers are you seeing the problem on?

IOS Iphone Safari

### Browser version

15.0

### Browser console logs

NA

**Comment by ltrung** [comment]
Thanks @benjing for reporting the issue. As @ElielCohen has pointed out this is a regression in iOS 15. I have put this in our known issue #1059 to track it there so I will close this one.
