### ISSUE TITLE
Chrome iOS supported version documentation

### ISSUE THREAD

**Issue by minhdao88** [aws/amazon-chime-sdk-js#1662]
### What are you trying to do?
I'm trying to check if the browser is supported to use Chime js SDK. In the documentation, I can see it states that iOS Chrome supported versions is `10.0 and later` which is confusing a bit. 
<img width="1012" alt="Screen Shot 2021-10-11 at 11 41 51 AM" src="https://user-images.githubusercontent.com/2589963/136734280-a1132a4f-3b5a-4b9c-ac88-470b4c4a31a6.png">

Is it the browser version or the iOS version? 
I also checked the source code which might indicate to me that the correct version for Chrome iOS is > 86 and iOS > 12 at https://github.com/aws/amazon-chime-sdk-js/blob/25c9d0d6db5e203c4d7c4f701e70cad78ed0b370/src/browserbehavior/DefaultBrowserBehavior.ts#L21

Please help me to clarify which is the correct supported versions for Chrome iOS.

### How can the documentation be improved to help your use case?

Please update the correct supported version for Chrome iOS

### What documentation have you looked at so far?

https://docs.aws.amazon.com/chime/latest/dg/meetings-sdk.html#mtg-browsers
https://github.com/aws/amazon-chime-sdk-js/blob/25c9d0d6db5e203c4d7c4f701e70cad78ed0b370/src/browserbehavior/DefaultBrowserBehavior.ts#L21

**Comment by ldai1** [comment]
Hi,

Thanks for reporting the issue. You are right, the version info is not correct for Chrome on IOS. It should be `78 or later`. We will make sure to update it in the developer guide. Thanks for help us catching issues!
