### ISSUE TITLE
Did not receive event 'meetingReconnected' in version chime sdk 2.18

### ISSUE THREAD

**Issue by dathacky** [aws/amazon-chime-sdk-js#1679]
### What happened and what did you expect to happen?

I updated to chime version 2.18, and used [reconnect](https://aws.github.io/amazon-chime-sdk-js/interfaces/audiovideocontroller.html#reconnect) but don't receive event 'meetingReconnected' with 'eventDidReceive'

### Have you reviewed our existing documentation?

- [X] GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [X] FAQs [page](https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html)
- [X] README [page](https://github.com/aws/amazon-chime-sdk-js#amazon-chime-sdk-for-javascript)
- [X] Feature-specific [guides](https://github.com/aws/amazon-chime-sdk-js#guides)

### Reproduction steps

call function [reconnect](https://aws.github.io/amazon-chime-sdk-js/interfaces/audiovideocontroller.html#reconnect)
and listen 'eventDidReceive'

### Amazon Chime SDK for JavaScript version

2.18

### What browsers are you seeing the problem on?

Chrome

### Browser version

94.0.4606.81 (Official Build) (x86_64)

### Browser console logs

No

**Comment by dathacky** [comment]
> Did it work in a previous version for you? If so could you let us know the version? Also how did you call reconnect? Did you pass in the statusCode? I believe if you just call `audioVideo.audioVideoController.reconnect()` you would see the below error in the console log as we require the statusCode before publishing the event ([Code](https://github.com/aws/amazon-chime-sdk-js/blob/master/src/audiovideocontroller/DefaultAudioVideoController.ts#L1200)):
> 
> ```
>  error during state Connected with action FinishConnecting: TypeError: Cannot read properties of undefined (reading **'statusCode')**
> ```
in version 2.16 i just call audioVideo.audioVideoController.reconnect() and still work. So what status should I pass to get 'meetingReconnected'

**Comment by dathacky** [comment]
Thank you, I had success with 
```
audioVideoController.reconnect(
         new MeetingSessionStatus(
           MeetingSessionStatusCode.ConnectionHealthReconnect,
         ),
       );
```
but on the remote side, I no longer get the video, and on the local side get the following log
`[WARN] CallingChimeLogs - the volume indicator adapter cleans up the current attendee (presence = false) after reconnection`

**Comment by ltrung** [comment]
You can ignore that warning in 2.18. 
I am not sure about the video part though. If you reconnect, the video will stop sending so the remote will not be able to see it anymore so seem like expected to me.
Also just curious, why do you need to call reconnect manually? reconnect is an internal API and developers should not need to call it manually.

**Comment by dathacky** [comment]
@ltrung 
I have investigated in both versions 2.16 and 2.18, after successfully reconnected, I can't receive the video. About 2 weeks ago, version 2.16 after reconnected, the remote still received the video. This error I'm pretty sure happened 2 weeks ago and I didn't edit any lines of code.
We provide a reconnect button for users so they can manually reconnect, and when that button is pressed, the above will happen.

**Comment by devalevenkatesh** [comment]
So this seems like we do not support manual reconnection and SDK can run into issues if this is triggered manually. Also the meeting session status is used when upon existing calculations within SDK it is determined that there is an issue with connection and in this there might be knobs for video which are affected so manually calling it does not seem to work. This API is also an internally used so request not to use it.

If to re-connect, I suggest tearing down the session or calling `meetingSession.audioVideo.stop()` and then listen for the stop being successful in the `audioVideoDidStop` observer method which you have to implement on a class level and then re-starting the session as you would usually do.

Closing this issue now, please feel free to re-open if you still need further help or have more questions.
