### ISSUE TITLE
Mic volume control using vanilla js

### ISSUE THREAD

**Issue by markcadag** [aws/amazon-chime-sdk-js#1683]
### What are you trying to do?

Control user's mic volume in a meeting session

### How can the documentation be improved to help your use case?

Include a demo using this SDK to control volume

### What documentation have you looked at so far?

https://aws.amazon.com/blogs/business-productivity/transforming-audio-and-shared-content-in-the-amazon-chime-sdk-for-javascript/

Thank you

**Comment by ltrung** [comment]
Please refer to https://github.com/aws/amazon-chime-sdk-js/issues/1391 as this seems like the same question.
