### ISSUE TITLE
Deprecating Plan B SDP for Chromium-based browsers

### ISSUE THREAD

**Issue by rixiang-dev** [aws/amazon-chime-sdk-js#1691]
# Tell us about your request
## What do you want us to build?
Which Amazon Chime SDK or feature area is this request for?
[amazon-chime-sdk-js](https://github.com/aws/amazon-chime-sdk-js)

## Tell us about the problem you are trying to solve and why is it hard?
Chromium has deprecated Plan B SDP and is removing it in release M96 (https://groups.google.com/g/discuss-webrtc/c/UBtZfawdIAA/m/m-4wnVHXBgAJ).  All builders must migrate from Plan B to Unified Plan for continued operation.

The Amazon Chime SDK for Javascript has used Unified Plan SDP as the default SDP since version 1.17.0, however builders can choose to use Plan B SDP by specifying enableUnifiedPlanForChromiumBasedBrowsers = false in the AudioVideoController configuration. 
Example: https://github.com/aws/amazon-chime-sdk-js/blob/398717cc502a39be6d9145e725bee5b2beaae586/test/meetingsession/DefaultMeetingSession.test.ts#L93

Removing the option for Plan B in the Amazon Chime SDK for Javascript ensures builders cannot configure an option which is no longer supported in Chromium.

## How are you currently solving a problem?
Are there any workarounds or mitigations you have used? Why is it not working for you?
N/A 

## Additional context
Anything else we should know?
PR to address this issue: https://github.com/aws/amazon-chime-sdk-js/pull/1681

**Comment by vidya-mohan** [comment]
Resolving as released in 2.21.0
