### ISSUE TITLE
Toggling video can result in no remote video

### ISSUE THREAD

**Issue by alhambra1** [aws/amazon-chime-sdk-js#1694]
### What happened and what did you expect to happen?

We can easily replicate this in our web-based meeting room, using Chime 2.19.0 on Chrome with simulcast -- have one participant toggle their video off. Wait a few seconds (we waited around 5-10 seconds), then toggle it back on. Some or all participants do not receive a callback updating the remote tile with the returning stream. A second oddity is that if someone else then turns off their video, it can trigger the callback finally showing the first person's stream, but possibly also causing another person's stream to turn off. (We initialise simulcast with `videoDownlinkBandwidthPolicy = new VideoAdaptiveProbePolicy(this.logger)`.

Please see attached logs for both instigator (the person toggling their video) and receiver (the person seeing the bug).

-- Sincerely,

### Have you reviewed our existing documentation?

- [X] GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [X] FAQs [page](https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html)
- [X] README [page](https://github.com/aws/amazon-chime-sdk-js#amazon-chime-sdk-for-javascript)
- [X] Feature-specific [guides](https://github.com/aws/amazon-chime-sdk-js#guides)

### Reproduction steps

Please see description.

### Amazon Chime SDK for JavaScript version

2.19.0

### What browsers are you seeing the problem on?

Chrome 

### Browser version

94.0.4606.81

### Browser console logs

[instigator.log](https://github.com/aws/amazon-chime-sdk-js/files/7377768/instigator.log)
[receiver.log](https://github.com/aws/amazon-chime-sdk-js/files/7377770/receiver.log)

**Comment by ltrung** [comment]
The fix has been released in the new NPM 2.21.0 so closing this issue.
