### ISSUE TITLE
Enhance the audio quality while sharing only the sound (or with the video)

### ISSUE THREAD

**Issue by LouisMx** [aws/amazon-chime-sdk-js#1695]
### What are you trying to do?

*I'm trying to have the best possible audio quality, if the presentator wants to share his audio output stream. For example: sharing a music during the meeting.*

### How can the documentation be improved to help your use case?

*Is there another part than `setContentAudioProfile(AudioProfile.fullbandMusicMono()` and `mixIntoAudioInput(stream)` ?
Theses parts do not have much information.*

### What documentation have you looked at so far?

I tried to mix the audio stream from `getDisplayMedia`, and mix it with the audio input: `mixIntoAudioInput(stream)`
-> nothing happened, perhaps I've done something wrong
I tried to directly put the stream from `getDisplayMedia` into `chooseAudioInputDevice(stream)`
-> it worked, but the quality is very poor (voice from microphone ok, but the music is not)
I configured `setContentAudioProfile(AudioProfile.fullbandMusicMono())`, but still very poor.

Is there a better way to do that ? To share a music (from a tab/window or output) with the clearest and best possible audio quality?

**Comment by devalevenkatesh** [comment]
Hi @LouisMx ,

Thank you for the issue. We had a blog post in the past about transforming audio with Amazon Chime SDK for JavaScript, so linking it here:
https://aws.amazon.com/blogs/business-productivity/transforming-audio-and-shared-content-in-the-amazon-chime-sdk-for-javascript/

Sorry, I am not sure, if this suits your use-case, but hope it helps.

**Comment by LouisMx** [comment]
@richnew10 Hi ! I could tried just today..., a lot of combinations. I have the same result.
I tried with different sampleRate, sampleSize,
like :`audio: {
                    autoGainControl: false,
                    channelCount: 2,
                    echoCancellation: false,
                    googAutoGainControl: false,
                    latency: 0,
                    noiseSuppression: false,
                    sampleRate: 44100,
                    sampleSize: 16,
                    volume: 1.0
                }`
I tried different AudioProfile() for the presentator (100000, 64000). I can't get a better quality than the default one. I think Chime SDK (client or server side) overrides some settings. I hear a lot of audio compression.
Any new idea ? Thanks.

**Comment by zhemitu-amzn** [comment]
@LouisMx Currently the best audio quality configuration is
`audio: { autoGainControl: false, channelCount: 1, echoCancellation: false, googAutoGainControl: false, latency: 0, noiseSuppression: false, sampleRate: 48000, sampleSize: 16, volume: 1.0 }`
This will give you a 64 kbps 48 kHz sampled Opus audio stream.

**Comment by devalevenkatesh** [comment]
Closing this issue, please feel free to re-open / create if required.
