### ISSUE TITLE
facing issue on muted 

### ISSUE THREAD

**Issue by E5920** [aws/amazon-chime-sdk-js#1701]
### What happened and what did you expect to happen?

@ltrung @michhyun1 @devalevenkatesh @simmkyu  , i am facing issue when remote user turned off their mic but in host screen mic turned off status is not updating. my requirement is when remote user turned off mic then host can able to see mic turned off on atteedee list section. 
we are trying to show mute/unmute status of all attendees to host.

please check below screenshot. 

remote user screen :- 

![image](https://user-images.githubusercontent.com/80304004/138242827-22771490-4a6e-42b6-b7ac-81b88aaaf14c.png)

host user screen :- 

![image](https://user-images.githubusercontent.com/80304004/138243300-edb238da-9755-46e3-a62a-468cd5d7e266.png)

this._attendeeListSubscription = meeting.attendeeListChange.subscribe((value) => {
      this.attendeeList = value;
      this.attendeeList.forEach(element => {
      this.meeting.meetingSession.audioVideo.realtimeSubscribeToVolumeIndicator(
        element.chime_attendee_id,
        (attendeeId, volume, muted, signalStrength) => {
          // A null value for volume, muted and signalStrength field means that it has not changed.
          if (volume === null) {
            // signalStrength has not changed, ignore volume and muted changes
            return;
          }
          if (muted !== null) {
            if(muted == true){
                 this.fmicrophone[element.chime_attendee_id] = faMicrophoneSlash;
            }else{
              this.fmicrophone[element.chime_attendee_id] = faMicrophone;
            }
            
          }
          else if(volume>= 0){
            this.fmicrophone[element.chime_attendee_id] = faMicrophone;
          }

### Have you reviewed our existing documentation?

- [X] GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [X] FAQs [page](https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html)
- [X] README [page](https://github.com/aws/amazon-chime-sdk-js#amazon-chime-sdk-for-javascript)
- [X] Feature-specific [guides](https://github.com/aws/amazon-chime-sdk-js#guides)

### Reproduction steps

please check above

### Amazon Chime SDK for JavaScript version

2.4.1

### What browsers are you seeing the problem on?

n/a

### Browser version

n/a

### Meeting and Attendee ID Information.

n/a

### Browser console logs

n/a

**Comment by vidya-mohan** [comment]
resolving as no response
