### ISSUE TITLE
Add a do-not-pause priority for priority-based downlink policy

### ISSUE THREAD

**Issue by mark-vanr** [aws/amazon-chime-sdk-js#1707]
# Community Note
* Please vote for this issue by adding a 👍 reaction to the issue. This will help the community and maintainers from the Amazon Chime SDK team to prioritize this request.
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request.

# Tell us about your request
## What do you want us to build?
Which Amazon Chime SDK or feature area is this request for?
[amazon-chime-sdk-js](https://github.com/aws/amazon-chime-sdk-js)

## Tell us about the problem you are trying to solve and why is it hard?
Using simulcast and the existing priority-based downlink policy, we are currently setting content streams to priority 1 if it is there, and other attendees to a lower priority. When sharing content, we'd like to be able to maintain the view of the content that is being shared, even if the downlink bandwidth of the attendee is very poor - even if it's a frozen frame as packets are missed, it will at least keep the context in front of the meeting attendee. In the current policy, even priority 1 streams will be paused in low-bandwidth scenarios. 

If possible, it would be great to have a priority 0 or a non-pausing priority so that we can always keep that stream open with a reduced experience, as that is (in our opinion) a better experience in the case of content sharing than having the large, sharing video tile go 'blank' as the stream is paused

## How are you currently solving a problem?
Currently setting content to priority 1 in the downlink policy preferences, but it will still be paused if the attendee's downlink is detected to be too low.

**Comment by ltrung** [comment]
@mark-vanr and @dathacky, we just added an option `keepLastFrameWhenPaused` in the meeting session configuration to allow you to keep the last frame when video is paused. Let me know if this meets your requirement.

**Comment by hensmi-amazon** [comment]
Closing as mitigation is likely provided. Please reopen if the feature mentioned by Trung does not solve your issue.
