### ISSUE TITLE
Unable integrating voicefocus in chime sdk single js

### ISSUE THREAD

**Issue by husaindevelop** [aws/amazon-chime-sdk-js#1720]
Continuing from issue #1622, which is closed. 

As suggested by the admin in the ticket, we removed the old stable release of amazon chime sdk and rebundled the latest version of amazon chime sdk single js.  But despite that, on initializing VoiceFocusDeviceTransformer.isSupported() static method. It replies false on checking the support for the feature. Even the logs are displaying the same results as before.
https://user-images.githubusercontent.com/62126860/135187190-bb580959-b9e4-4bb6-840a-896ccc7d1342.png

Please guide us as how we move forward on this particular issue.

**Comment by husaindevelop** [comment]
Yes i did, every line of it. Still i don't get what i missed.  Here is the entire code i'm using for your information which also includes Voicefocus part.

```
 (async () => {
            
            const logger = new ChimeSDK.ConsoleLogger('MyLogger', ChimeSDK.LogLevel.INFO);
            let transformer;
let isVoiceFocusSupported;

try {
    const transformer = await VoiceFocusDeviceTransformer.create({}, { logger });
    const isVoiceFocusSupported = await VoiceFocusDeviceTransformer.isSupported();

} catch (e) {
  // Will only occur due to invalid input or transient errors (e.g., network).
  isVoiceFocusSupported = false;
  alert (isVoiceFocusSupported);
}
            
            const deviceController = new ChimeSDK.DefaultDeviceController(logger);
             const meetingResponse = {"Meeting":<?php if ($_GET ['met1']) echo $_SESSION ['met1'];else echo $_SESSION ['met']; ?>};
            const attendeeResponse = {"Attendee":<?php echo json_encode($attendee) ?>};

            const configuration = new ChimeSDK.MeetingSessionConfiguration(meetingResponse, attendeeResponse);
            const meetingSession = new ChimeSDK.DefaultMeetingSession(configuration, logger, deviceController);

            const audioInputDevices = await meetingSession.audioVideo.listAudioInputDevices();
            const audioOutputDevices = await meetingSession.audioVideo.listAudioOutputDevices();
            const videoInputDevices = await meetingSession.audioVideo.listVideoInputDevices();
            meetingSession.audioVideo.chooseVideoInputQuality(960,540,15,1400);
            
            await meetingSession.audioVideo.chooseVideoInputDevice(videoInputDevices[0].deviceId);
            await meetingSession.audioVideo.chooseAudioInputDevice(audioInputDevices[0].deviceId);
            if (audioOutputDevices[0]) {
                await meetingSession.audioVideo.chooseAudioOutputDevice(audioOutputDevices[0].deviceId);
            }
            meetingSession.audioVideo.startVideoPreviewForVideoInput(document.getElementById('self-video'));



            const audioElement = document.getElementById('audio-preview');
            meetingSession.audioVideo.bindAudioElement(audioElement);

            const videoElement = document.getElementById('video-prime');
            const videoElement1 = document.getElementById('video-preview1');

            

            const observer = {
                audioVideoDidStart: () => {
                    console.log('Started');
                },
                videoTileDidUpdate: tileState => {
                    if (!tileState.boundAttendeeId || tileState.localTile || tileState.isContent) {
                           
                        return;
                        
                    }
                    //console.log('Start video');                  
    const videoElement = document.getElementById('video-prime');
    $('#vi').html (tileId);                 
   
});
   
             }
            };

            meetingSession.audioVideo.addObserver(observer);
            meetingSession.audioVideo.start();
            meetingSession.audioVideo.startLocalVideoTile();
        }) ();
```

We have been literally stuck on this for a month actually without any result.  Shall appreciate should you guide us on this issue and point us where we are going wrong.

**Comment by richnew10** [comment]
From reading this section:
        
```javascript
            const logger = new ChimeSDK.ConsoleLogger('MyLogger', ChimeSDK.LogLevel.INFO);
            let transformer;
let isVoiceFocusSupported;

try {
    const transformer = await VoiceFocusDeviceTransformer.create({}, { logger });
    const isVoiceFocusSupported = await VoiceFocusDeviceTransformer.isSupported();

} catch (e) {
  // Will only occur due to invalid input or transient errors (e.g., network).
  isVoiceFocusSupported = false;
  alert (isVoiceFocusSupported);
}
            
            const deviceController = new ChimeSDK.DefaultDeviceController(logger);
```

I suspect that you need to put `ChimeSDK.VoiceFocusDeviceTransformer` instead of just `VoiceFocusDeviceTransformer`, because the SDK names are not in the default scope.

Your browser developer tools should have let you enter that `catch` block and see what `e` was: I bet it's something like `ReferenceError: VoiceFocusDeviceTransformer is not defined`.

You could also add a simple `console.error(e)` in that catch block to see what's happening.

I should stress that this is quite rudimentary web development, not specific to Amazon Chime at all, and seems to be entirely isolated to how you have chosen to package and import the Chime SDK. We typically suggest that our customers use the SDK via NPM, using TypeScript, and using a bundler like Webpack or Rollup – the developer experience is much better.

**Comment by husaindevelop** [comment]
Well, its working now. First of all meeting demo v2 seems to be working in localhost environment only, which is not ideal one for us. All my resources are in remote. Regarding singlejs, which we have deployed, we have followed what Chime SDK documentation mentioned, we used the following bundling command.
```
git clone https://github.com/aws-samples/amazon-chime-sdk.git
cd amazon-chime-sdk/utils/singlejs
npm install
npm run bundle
```

I feel what was followed above is specific to amazon chime. Please do point out if it is not.

**Comment by husaindevelop** [comment]
Sorry to bother you again. On proceeding forward to adding amazon Voice Focus to the application with the below code
```
const chosenAudioInput = 'abcdef';   
const vfDevice = await transformer.createTransformDevice('Default');

```            
I encountered this error "Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'createTransformDevice')". Need your guidance as where i'm going wrong as i'm pretty new to this typescript language.

**Comment by richnew10** [comment]
It means `transformer` is `undefined`, which is probably happening because in this code block:

```javascript
            let transformer;
let isVoiceFocusSupported;

try {
    const transformer = await VoiceFocusDeviceTransformer.create({}, { logger });
 
```

you are defining `transformer` twice: once with `let` outside the `try` block, and once as a `const` inside it, so that inner assignment disappears after it leaves scope. 

Your developer tooling should have caught this, and it's not TypeScript. 

If you're not using language-aware developer tooling, I strongly suggest you do so (I recommend VS Code), because this is not the correct forum to be giving you beginner JavaScript advice.

**Comment by husaindevelop** [comment]
Yes i agree. The questions are novice, i presumed it before posting it. My bad. Sorry about that. Got that figured right now. Now there are no errors. Now it has successful created "TransformDevice" element with chosen audio input device. But still the amazon voice focus does not seem to boot.  The final blocks of code which initiates deviceController as given below returns "undefined" as result, thus not enabling amazon voice focus. 
```
const deviceToUse = vfDevice || chosenAudioInput;
await deviceController.chooseAudioInputDevice(deviceToUse);
alert (vfDevice);
if (vfDevice) {
  console.log('Amazon Voice Focus enabled');
}
```
I know i'm asking something this forum is not meant to answer. But shall appreciate should you help us out of this mess that we have been fighting for weeks on and off.

**Comment by richnew10** [comment]
I can't tell from your comment what is happening.

What are the values of `transformer`, `vfDevice`, `chosenAudioInput`, and `deviceController` as shown in your browser developer tools?

**Comment by husaindevelop** [comment]
Here given below is the configuration code for your information.

           ```
 const deviceController = new ChimeSDK.DefaultDeviceController(logger);
            const meetingResponse = {"Meeting":<?php echo json_encode($meeting) ?>};
            const attendeeResponse = {"Attendee":<?php echo json_encode($attendee) ?>};
            const configuration = new ChimeSDK.MeetingSessionConfiguration(meetingResponse, attendeeResponse);
            const meetingSession = new ChimeSDK.DefaultMeetingSession(configuration, logger, deviceController);
            const audioOutputDevices = await meetingSession.audioVideo.listAudioOutputDevices();
            const videoInputDevices = await meetingSession.audioVideo.listVideoInputDevices();
            meetingSession.audioVideo.chooseVideoInputQuality(960,540,15,1400);
            const audioInputDevices = await meetingSession.audioVideo.listAudioInputDevices();
            const transformer = await ChimeSDK.VoiceFocusDeviceTransformer.create({}, { logger });
            await meetingSession.audioVideo.chooseVideoInputDevice(videoInputDevices[0].deviceId);
            await meetingSession.audioVideo.chooseAudioInputDevice(audioInputDevices[0].deviceId);
            onst chosenAudioInput = audioInputDevices[0].deviceId;    
            const vfDevice = await transformer.createTransformDevice(chosenAudioInput);
            if (audioOutputDevices[0]) {
            await meetingSession.audioVideo.chooseAudioOutputDevice(audioOutputDevices[0].deviceId);
            }
const deviceToUse = vfDevice || chosenAudioInput;
await deviceController.chooseAudioInputDevice(deviceToUse);
alert (vfDevice);

if (vfDevice) {
  console.log('Amazon Voice Focus enabled');
}

```
Please guide us as where we are going wrong. Thanks.

**Comment by rnewman** [comment]
Please open your browser developer tools, set some breakpoints, and tell me what the actual values are of the variables I mentioned.

**Comment by husaindevelop** [comment]
I set breakpoints as you mentioned. Here are values to the variables you mentioned.


Transformer
```
"configuration: Promise {<fulfilled>: {…}}
fetchBehavior: {escapedQueryString: 'sdk=2.1.0&ua=edge-chromium-95'}
logger: t.default {name: 'MyLogger', level: 1}
preload: true
spec: {assetGroup: 'sdk-2.1'}
supported: false
vfLogger: t.default {base: t.default}
[[Prototype]]: Object"
```

Audio Input Devices
```
"0: InputDeviceInfo {deviceId: 'default', kind: 'audioinput', label: 'Default - Microphone Array (Realtek(R) Audio)', groupId: 'c90ba44b89ff7479d1a608d7521ad3da749dadbdc85237789c26a3d9f769018f'}
1: InputDeviceInfo {deviceId: 'communications', kind: 'audioinput', label: 'Communications - Microphone Array (Realtek(R) Audio)', groupId: 'c90ba44b89ff7479d1a608d7521ad3da749dadbdc85237789c26a3d9f769018f'}
2: InputDeviceInfo {deviceId: '6bf1339febdc2e0c866f540d648844c376de581e199bfd14399dae7b2a8d0837', kind: 'audioinput', label: 'Stereo Mix (Realtek(R) Audio)', groupId: 'c90ba44b89ff7479d1a608d7521ad3da749dadbdc85237789c26a3d9f769018f'}
3: InputDeviceInfo {deviceId: '91c46f54b6e8b2a34d4b26ee76b2d64e33179f51d2be377600c8aedc2ec9908b', kind: 'audioinput', label: 'Microphone Array (Realtek(R) Audio)', groupId: 'c90ba44b89ff7479d1a608d7521ad3da749dadbdc85237789c26a3d9f769018f'}
length: 4
[[Prototype]]: Array(0)"
```


Device Controller
```
"activeDevices: {audio: t.default, video: t.default}
alreadyHandlingDeviceChange: false
audioInputDestinationNode: null
audioInputSourceNode: null
audioOutputDeviceId: "default"
boundAudioVideoController: o {_audioProfile: i, connectionHealthData: i, observerQueue: Set(0), meetingSessionContext: t.default, enableSimulcast: false, …}
browserBehavior: t.default {browser: BrowserInfo, browserSupport: {…}, browserName: {…}, chromeLike: Array(4), enableUnifiedPlanForChromiumBasedBrowsers: false}
deviceChangeObservers: Set(0) {size: 0}
deviceInfoCache: (8) [InputDeviceInfo, InputDeviceInfo, InputDeviceInfo, InputDeviceInfo, InputDeviceInfo, MediaDeviceInfo, MediaDeviceInfo, MediaDeviceInfo]
deviceLabelTrigger: ()=>navigator.mediaDevices.getUserMedia({audio:!0,video:!0})
inputDeviceCount: 4
logger: t.default {name: 'MyLogger', level: 1}
muteCallback: e=> {…}
useWebAudio: false
videoInputQualitySettings: t.default {videoWidth: 960, videoHeight: 540, videoFrameRate: 15, videoMaxBandwidthKbps: 1400}
[[Prototype]]: Object"
```

chosenAudioInput
`"default"`

const vfDevice
`"Undefined"`

**Comment by rnewman** [comment]
Firstly, you need to enable Web Audio. See that section in the Voice Focus guide. 

Secondly, you appear to have bundled SDK 2.1, which is a year old. You might need to amend the singlejs sample repo to track a more current release.

**Comment by husaindevelop** [comment]
Sorry for posting such beginner question. Have no way. On inserting the code as directed by you:
  ```
  this.deviceController = new ChimeSDK.DefaultDeviceController({
                enableWebAudio: isVoiceFocusSupported
            });
```
We encounter this error in the log
```
Oncaught (in promise) TypeError: this.logger.info is not a function
    at new o (DefaultDeviceController.js:57)
```

**Comment by richnew10** [comment]
The first argument is a `Logger`. The options dictionary is the second argument.

https://aws.github.io/amazon-chime-sdk-js/classes/defaultdevicecontroller.html#constructor

**Comment by husaindevelop** [comment]
For your information, i originally had logger argument alongside enablewebaudio, but upon encountering same error, i removed it from the code. Now on your instruction, i have reinserted the argument again in two alternate ways:
Code1:
As specified in "https://aws.github.io/amazon-chime-sdk-js/classes/defaultdevicecontroller.html#constructor"
`this.deviceController = new ChimeSDK.DefaultDeviceController({logger:logger, options:{enableWebAudio: isVoiceFocusSupported}});
`
Code 2:
`this.deviceController = new ChimeSDK.DefaultDeviceController({logger, enableWebAudio:isVoiceFocusSupported});
`
But both arguments emit the same response in the console logs:
```
DefaultDeviceController.js:57 
 Uncaught (in promise) TypeError: this.logger.info is not a function
    at new o (DefaultDeviceController.js:57)
    at page.php:76
```
Actually i do not understand, logger argument is part of many lines of code including meetingsession and transformer and it works perfectly there but not on this one. Do guide us as where we are going wrong.

**Comment by rnewman** [comment]
Neither of those.

```
this.deviceController = new ChimeSDK.DefaultDeviceController(logger, { enableWebAudio: isVoiceFocusSupported });
```

**Comment by husaindevelop** [comment]
The enableWebAudio is working right now, but results continue to elude us. The vf device element as given below returns "undefined" value despite carrying a valid chosen audio input device: "default". 
`const vfDevice = await transformer.createTransformDevice(chosenAudioInput);`. 

With all elements in place, i think it should have worked by now.  I do not know as where i have gone wrong.  For your information, we hereby furnish the code implemented in the page so far
 ```
             const transformer = await ChimeSDK.VoiceFocusDeviceTransformer.create({}, { Logger });
            const deviceController = new ChimeSDK.DefaultDeviceController(Logger);
            const meetingResponse = {"Meeting":<?php echo json_encode($met) ?>};
            const attendeeResponse = {"Attendee":<?php echo json_encode($attendee) ?>};
            const configuration = new ChimeSDK.MeetingSessionConfiguration(meetingResponse, attendeeResponse);
            const meetingSession = new ChimeSDK.DefaultMeetingSession(configuration, Logger, deviceController);
            const audioInputDevices = await meetingSession.audioVideo.listAudioInputDevices();
            const audioOutputDevices = await meetingSession.audioVideo.listAudioOutputDevices();
            const videoInputDevices = await meetingSession.audioVideo.listVideoInputDevices();
            meetingSession.audioVideo.chooseVideoInputQuality(960,540,15,1400);
            await meetingSession.audioVideo.chooseVideoInputDevice(videoInputDevices[0].deviceId);
            await meetingSession.audioVideo.chooseAudioInputDevice(audioInputDevices[0].deviceId);
            this.deviceController = new ChimeSDK.DefaultDeviceController(Logger, { enableWebAudio: isVoiceFocusSupported });
            const chosenAudioInput = audioInputDevices[0].deviceId;    
            const vfDevice = await transformer.createTransformDevice(chosenAudioInput);
            if (audioOutputDevices[0]) {
            await meetingSession.audioVideo.chooseAudioOutputDevice(audioOutputDevices[0].deviceId);
            }
const deviceToUse = vfDevice || chosenAudioInput;
await deviceController.chooseAudioInputDevice(deviceToUse);
alert (vfDevice);

if (vfDevice) {
  console.log('Amazon Voice Focus enabled');
}
```

Shall appreciate should you  check and point us out as where we are going wrong.

**Comment by husaindevelop** [comment]
Still the same result after changing the line as mentioned by you. Probably SDK's old version is not allowing the voicefocus to boot. Shall update the SDK and revert.

**Comment by husaindevelop** [comment]
Yes updated and checked. Changed the version to 2.20.1 in package.json before running npm bundle. Now on running the code, we are still facing the same error returning VF device value as "undefined". On running breakpoints in browser developer tools i found vf device line return the following values under scope window.
```
Logger: t.default {name: 'MyLogger', level: 1}
attendeeResponse: {Attendee: {…}}
audioElement: undefined
audioInputDevices: (4) [InputDeviceInfo, InputDeviceInfo, InputDeviceInfo, InputDeviceInfo]
audioOutputDevices: (3) [MediaDeviceInfo, MediaDeviceInfo, MediaDeviceInfo]
chosenAudioInput: "default"
configuration: t.default {meetingId: '45c47ce8-3081-4748-bcf9-c383059e0706', externalMeetingId: undefined, credentials: t.default, urls: t.default, connectionTimeoutMs: 15000, …}
deviceController: o {logger: t.default, deviceInfoCache: Array(8), activeDevices: {…}, audioOutputDeviceId: null, deviceChangeObservers: Set(0), …}
deviceToUse: undefined
isVoiceFocusSupported: undefined
meetingResponse: {Meeting: {…}}
meetingSession: i {_configuration: t.default, _logger: t.default, _deviceController: o, audioVideoController: o, contentShareController: t.default, …}
observer: undefined
transformer: o {spec: {…}, supported: false, logger: t.default, vfLogger: t.default, preload: true, …}
vfDevice: undefined
videoElement: undefined
videoElement1: undefined
videoInputDevices: [InputDeviceInfo]
```

And on console log
`2021-11-02T16:49:34.376Z [INFO] MyLogger - API/DefaultDeviceController/chooseAudioOutputDevice "default" -> null
`
Thought this could help you decipher as where i'm going wrong. Also if it could be of some help, you can take a look at the page we are working on: https://mbracecloud.com/vp00017.php?v=Yes

We hope you will be able to guide us through this issue.

**Comment by richnew10** [comment]
I see that Voice Focus is supported:

```
 2021-11-02T16:55:48.767Z [INFO] MyLogger - Decided execution approach {"supported":true,"useSIMD":true,"processor":"voicefocus-inline-processor","executionApproach":"inline","variant":"c100","executionQuanta":3}
```

and seems to be getting to the point of selection:

```
2021-11-02T16:55:52.809Z [INFO] MyLogger - Choosing transform input device [object Object]
```

but I see that you have not enabled Web Audio:

```
 Uncaught (in promise) Error: Cannot apply transform device without enabling Web Audio.
    chooseAudioTransformInputDevice DefaultDeviceController.js:353
    i DefaultDeviceController.js:10
    i DefaultDeviceController.js:6
    chooseAudioTransformInputDevice DefaultDeviceController.js:348
    chooseAudioInputDevice DefaultDeviceController.js:327
    i DefaultDeviceController.js:10
    i DefaultDeviceController.js:6
    chooseAudioInputDevice DefaultDeviceController.js:246
    <anonymous> vp00017.php:82
    async* vp00017.php:134
DefaultDeviceController.js:353:22
```

**Comment by husaindevelop** [comment]
Yes i encountered that error, but on refreshing that error goes off. Thought it had solved. Below given is block of code i'm using and it does makes sure web audio is enabled before hand transformer element  is created.
```
const deviceController = new ChimeSDK.DefaultDeviceController(Logger);
this.deviceController = new ChimeSDK.DefaultDeviceController(Logger, { enableWebAudio: isVoiceFocusSupported });
const transformer = await ChimeSDK.VoiceFocusDeviceTransformer.create({}, { logger: Logger });

```

**Comment by husaindevelop** [comment]
Ok. Devicecontrollers were my error. I just misplaced it. 
But considering everything is coded right now based on what you have given, why does vf device continue to return undefined.

**Comment by richnew10** [comment]
> Ok. Devicecontrollers were my error. I just misplaced it. But considering everything is coded right now based on what you have given, why does vf device continue to return undefined.

In my testing it does not — 

```
2021-11-02T16:55:52.809Z [INFO] MyLogger - Choosing transform input device [object Object]
```

**Comment by husaindevelop** [comment]
So just to get a clarity, do you get a log: Amazon Voice Focus Enabled in the console from your testing.

**Comment by husaindevelop** [comment]
Ok it seems to work on Chrome 95 but not on Microsoft Edge 95 which also runs chromium engine.

**Comment by richnew10** [comment]
In Edge 95 on macOS, I get:

> Amazon Voice Focus enabled

in your app.

**Comment by husaindevelop** [comment]
Ok its working in edge as well now. In the same app, voice focus event is booted for the first attendee, but on opening another tab for testing another attendee, the voicefocus event returns "undefined". Is it because we also need to bind the voicefocus with the observer or videotileupdate event ?

**Comment by rnewman** [comment]
The transformer returns `undefined` if it is not supported:

https://aws.github.io/amazon-chime-sdk-js/classes/voicefocusdevicetransformer.html#createtransformdevice

If this happens on the second tab, it’s most likely because your device doesn’t have enough free CPU cycles.

**Comment by husaindevelop** [comment]
It only happens on the second tab, the first tab works pretty fine. I shall check it in my another laptop for assurance. Shall update you.
