### ISSUE TITLE
How to know if video is off or on for a chime attendee id

### ISSUE THREAD

**Issue by E5920** [aws/amazon-chime-sdk-js#1730]
### What happened and what did you expect to happen?

@ltrung @michhyun1 ,  is there a way to know if a given chime attendee video is off or on ?

we are trying to show video is off/on status of all attendees to host

### Have you reviewed our existing documentation?

- [X] GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [X] FAQs [page](https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html)
- [X] README [page](https://github.com/aws/amazon-chime-sdk-js#amazon-chime-sdk-for-javascript)
- [X] Feature-specific [guides](https://github.com/aws/amazon-chime-sdk-js#guides)

### Reproduction steps

please check above details

### Amazon Chime SDK for JavaScript version

2.4.1

### What browsers are you seeing the problem on?

n/a

### Browser version

n/a

### Meeting and Attendee ID Information.

n/a

### Browser console logs

n/a

**Comment by devalevenkatesh** [comment]
Closing this issue due to in-activity, please feel free to re-open if you have more questions.
