### ISSUE TITLE
Video Frame Processor for Screen sharing

### ISSUE THREAD

**Issue by majo35-6c** [aws/amazon-chime-sdk-js#1731]
I can modify media stream which i already share.

- for example i merge together media stream form my desktop and from my camera.

Does there any way for screenSharing similar to Custom Video Frame Processor for Video Tile of attendee ?

I would like to use it somehow like this:

```
const mergedMediaStream = chime.audioVideo.startContentShareFromScreenCapture([myVideoProcesor]);
chime.audioVideo.startContentShare(mergedMediaStream);
```
I can used it now this way:
```
const stream = await navigator.mediaDevices.getDisplayMedia({ video: true });
const screenPresenter = new ScreenPresenter();
screenPresenter.setVirtualBackgroundStream(stream);
const mediaStream = screenPresenter.getMediaStream();
chime.audioVideo.startContentShare(mediaStream);
```
However this way has performance issue.

Any ideas how i can build something like startContentShareFromScreenCapture with the same performance ?

**Comment by majo35-6c** [comment]
@ltrung 
![image](https://user-images.githubusercontent.com/80401548/139501008-86e60652-93a8-4141-b5a4-033dd68eff8d.png)

**Comment by darek-gc** [comment]
Hello,

Is it possible to use Video Frame Processor to send frames by http requests. I would like to process frames in Rekognition as it is implemented here https://github.com/aws-samples/amazon-rekognition-virtual-proctor#architecture.

Finally, my app will work on Android and iOS, so next question whether Chime SDK for Android(https://github.com/aws/amazon-chime-sdk-android) and iOS has equivalent to Video Frame Processor service?

**Comment by darek-gc** [comment]
Seems I already found an answer for my first question, I managed to send frames by HTTP requests by modifying this example
https://github.com/trackit/amazon-chime-sdk-js/commit/a3808219ef8c53bceb1e9960451e7540b4e6da79#diff-e870111fa9bc964600df41f9dedbd7396bef0bd816432b2333d0e33da18c0b15R244

to something like this
`function isHTMLCanvasElement(obj: HTMLCanvasElement | OffscreenCanvas): obj is HTMLCanvasElement {
  return (obj as HTMLCanvasElement).toDataURL  !== undefined;
}
class BlurBackgroundProcessor implements VideoFrameProcessor {
  async process(buffers: VideoFrameBuffer[]): Promise<VideoFrameBuffer[]> {
    for (let i = 0; i < buffers.length; i++) {
      const canvas = await buffers[i].asCanvasElement();
      
      if (isHTMLCanvasElement(canvas)) {
        const base64Canvas = canvas.toDataURL("image/jpeg").split(';base64,')[1];
        
        await fetch('https://qgpl20jbt5.execute-api.eu-west-1.amazonaws.com/Prod/process', {
          method: 'POST',
          body: JSON.stringify({image: base64Canvas})
        });      
      }
    }
    return buffers;
  }

  async destroy() {}
}`

**Comment by darek-gc** [comment]
Thank you

**Comment by namtxhybrid** [comment]
> So we currently do not support any video processing API for content share. However, I think you can still use the video transform pipeline to do it. I tried to apply the [demo emoji video processor](https://github.com/aws/amazon-chime-sdk-js/blob/master/demos/browser/app/meetingV2/videofilter/EmojifyVideoFrameProcessor.ts#L10) to a screen capture using the following code and it worked for me:
> 
> ```
> // Get the screen share
> const stream = await navigator.mediaDevices.getDisplayMedia();
> // Create a video transform pipeline
> this.contentPipe = new DefaultVideoFrameProcessorPipeline(this.meetingLogger, [new EmojifyVideoFrameProcessor('🚀')]);
> await this.contentPipe.setInputMediaStream(stream);  //Set the screen capture as input to video pipeline
> await this.audioVideo.startContentShare(this.contentPipe.getActiveOutputMediaStream()); //Stream the pipeline output
> ```
> 
> Would this work for you?

Hi @ltrung,

According to Video Frame Processor, Can I place a video camera stream into content share? I meant the background is a content share and video camera is on it.
