### ISSUE TITLE
Mobile-friendly documentation / quickstart guide

### ISSUE THREAD

**Issue by maciejgoscinski** [aws/amazon-chime-sdk-js#1739]
### What are you trying to do?

I'm trying to get to know the Chime platform and implement 1v1 voicecalls between an agent working on desktop, and a customer answering either from within a web-view application, or mobile browser. After finally succeeding to develop an MVP, I have a couple observations, regarding the process which turned out to be more difficult than I expected and had some pitfalls.

### What documentation have you looked at so far?/  How can the documentation be improved to help your use case?

- the SDK itself could be friendlier and more abstract / high-level (not forcing me to write desktop and mobile specific code). At the very least, trying to set the output device on mobile devices should result with a more helpful message.
- the documentation[ (especially the frontpage) ](https://github.com/aws/amazon-chime-sdk-js)could be more mobile inclusive. Currently there's no mention of BrowserBehaviour / supportsSinkId there, which is a necessity to be able to handle mobile browsers from the start
- the documentation says we should enumerate available devices and choose from them. There should be a mention that on devices not supporting setSinkId (like mobile browsers) we should force-choose an audio output = null, but still allow choosing an audio input
- [here](https://docs.aws.amazon.com/chime/latest/dg/initialize-session.html) we should avoid unexplained cryptic pieces of code such as enableWebAudio
- [here](https://github.com/aws-samples/amazon-chime-sdk) the [Android WebView Sample](https://github.com/aws-samples/amazon-chime-sdk/tree/main/apps/Android-WebView-sample) is a dead link

**Comment by ltrung** [comment]
@maciejgoscinski Thanks for feedback. 
I have fixed the broken link for Android WebView Sample.

**Comment by ltrung** [comment]
Closing for now. We have an internal ticket to improve the demo as a whole.
