### ISSUE TITLE
What is the release strategy of new versions?

### ISSUE THREAD

**Issue by lawrencepit** [aws/amazon-chime-sdk-js#174]
The master branch contains a demo example named demos/browser/app/meetingV2. In there the class DefaultModality is used. This class does not exist in v1.1.0 of the SDK. When trying to install the latest version of the SDK via yarn upgrade the following is output:

```
∴ yarn upgrade chime
yarn upgrade v1.22.0
Couldn't find any versions for "amazon-chime-sdk-js" that matches "^1.1.22"
? Please choose a version of "amazon-chime-sdk-js" from this list: (Use arrow keys)
❯ 1.1.0
  1.0.0
```

When will the latest version from master be available to install via yarn?

**Comment by aburnson** [comment]
We currently release minor versions to NPM. We have just released version 1.2.1, which should resolve the issue with the missing DefaultModality class. I agree we should have documentation on our version release cadence and how to use yarn. We may need to do some work to support yarn with the demos. Currently we suggest you use `npm` to build those.

**Comment by vidya-mohan** [comment]
Hello @lawrencepit - thank you for your interest on our SDK. DefaultModality is a class we have introduced recently and have just updated our NPM. 

Could you please retry and checkout version 1.2.1?

**Comment by lawrencepit** [comment]
Hi Vidya,

I just upgraded to v1.2.1, works perfectly. Thanks!

Best regards,
Lawrence
