### ISSUE TITLE
Meeting not ending after 5 minutes of inactivity

### ISSUE THREAD

**Issue by abhimanusharma** [aws/amazon-chime-sdk-js#1743]
### What happened and what did you expect to happen?

**What Happened?:**
I have joined a meeting with single user and muted the mic, I have waited for 5 minutes first and meeting did not ended. Then I waited for 30 minutes with single user and muted audio the meeting still not ended. I tried to join a new attendee in that meeting after 30 minutes and he was able to join that meeting successfully.

**What I expected?**
1. The 'eventDidReceive' observer should fire with 'meetingEnded' event.
2. Meeting not found error should throw when new attendee tries to join after 6 minutes or more in an Inactive meeting.

### Have you reviewed our existing documentation?

- [X] GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [X] FAQs [page](https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html)
- [X] README [page](https://github.com/aws/amazon-chime-sdk-js#amazon-chime-sdk-for-javascript)
- [X] Feature-specific [guides](https://github.com/aws/amazon-chime-sdk-js#guides)

### Reproduction steps

1. Create a new meeting with 6 digit (numeric) meeting id.
2. Mute audio on preview screen or mute audio after joining the meeting.
3. Wait for 6 minutes without adding any new users.
4. Notice the meetingEnded event did not occured.
5. Now wait for 25 minutes more without adding new user and muted audio.
6. Notice that there are still no meetingEnded event triggered.

### Amazon Chime SDK for JavaScript version

"amazon-chime-sdk-js": "2.16.1",

### What browsers are you seeing the problem on?

Google Chrome

### Browser version

Version 95.0.4638.54 (Official Build) (64-bit)

### Meeting and Attendee ID Information.

attendeeId: "72690610-6d6b-8213-59d8-134cb6f33b6c"

meetingId: "1e5d6113-47a5-4e7c-a7fe-530bc6820706"

### Browser console logs

N/A

**Comment by ltrung** [comment]
Looking at the meeting Id, the meeting did auto end at the 30 minute mark which is as documented in our [FAQs](1e5d6113-47a5-4e7c-a7fe-530bc6820706).
>No audio connections are present in the meeting for more than five minutes.
Only one audio connection is present in the meeting for more than 30 minutes.

In the case of 5 minutes, it means there is no audio connection established such as you do not call `audioVideo.start` after getting back the response from `createMeeting`.

**Comment by abhimanusharma** [comment]
My main concern is that even if the meeting ended the event trigger should work (eventDidReceive) observer, I also implemented eventBridge for meetingEnded with a Lambda function which is not receiving anything after the certain time period.

**Comment by ltrung** [comment]
Did you not receive the meetingEnded eventBridge after 30 minutes? I checked the server and it was ended after 30 minutes.

**Comment by abhimanusharma** [comment]
Yes, getting it after 30 minutes but not after 10 minutes with audio muted for single or even two users.
