### ISSUE TITLE
Not getting meeting Title and external meeting id using eventBridge

### ISSUE THREAD

**Issue by abhimanusharma** [aws/amazon-chime-sdk-js#1749]
### What happened and what did you expect to happen?

https://docs.aws.amazon.com/chime/latest/ag/automating-chime-with-cloudwatch-events.html

Using this tutorial to setup eventBridge.

getting below output:

```
{
  version: '0',
  id: '630ef3de-fcc5-2e37-9e63-7e58aaf8e998',
  'detail-type': 'Chime Meeting State Change',
  source: 'aws.chime',
  account: '420344168816',
  time: '2021-11-02T11:52:34Z',
  region: 'us-east-1',
  resources: [],
  detail: {
    version: '0',
    eventType: 'chime:MeetingEnded',
    timestamp: 1635853954342,
    meetingId: '303589ed-97b3-4d28-b76d-48479a3b0706',
    mediaRegion: 'us-east-1'
  }
}
```

### Have you reviewed our existing documentation?

- [X] GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [X] FAQs [page](https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html)
- [X] README [page](https://github.com/aws/amazon-chime-sdk-js#amazon-chime-sdk-for-javascript)
- [X] Feature-specific [guides](https://github.com/aws/amazon-chime-sdk-js#guides)

### Reproduction steps

Enable eventBridge for Chime meetingEnd.
Join a meeting and wait for it to end.
See the logs in lambda

### Amazon Chime SDK for JavaScript version

"amazon-chime-sdk-js": "2.16.1",

### What browsers are you seeing the problem on?

Google Chrome

### Browser version

Version 95.0.4638.54 (Official Build) (64-bit)

### Meeting and Attendee ID Information.

meetingId: '303589ed-97b3-4d28-b76d-48479a3b0706',

### Browser console logs

N/A

**Comment by ashleyqu** [comment]
1. The external meeting id is one of the create meeting request parameters: https://docs.aws.amazon.com/chime/latest/APIReference/API_CreateMeeting.html when create a meeting. Have you passed external meeting id when create the meeting?
2. I do not see meeting title from: https://docs.aws.amazon.com/chime/latest/ag/automating-chime-with-cloudwatch-events.html. It's expected?

**Comment by abhimanusharma** [comment]
@ltrung any update, how to achieve this?

**Comment by devalevenkatesh** [comment]
@abhimanusharma Please note that there is no meeting title attribute and in the `amazon-chime-sdk-js` demo, the title is basically used as just a name for `ExternalMeetingId` attribute which can be passed while you call the `createMeeting` API. Hence, there would not be any title attribute and you will receive the `externalMeetingId` if it is provided.

In the demo, check [here](https://github.com/aws/amazon-chime-sdk-js/blob/main/demos/browser/server.js#L93) in the node.js backend server code, the meeting title is taken as a user input and is passed as a `ExternalMeetingId` value.

I am closing this issue for now and sorry if there was no traction on this. Please feel free to re-open if still an issue.
