### ISSUE TITLE
Integration with AWS Transcribe, Rekognition

### ISSUE THREAD

**Issue by Axe129** [aws/amazon-chime-sdk-js#175]
Hi,

I don't know if this is the right place to ask this question. But, I would like to know how we can integrate services like AWS Transcribe, Rekogntion with chime sdk. Specifically, I'd like to know how to send the audio/video to these services to get responses. Any pointers would be very much appreciated.

Thanks

**Comment by vidya-mohan** [comment]
Hello @Axe129,

Thank you for the interest in our SDK!

While we dont have a first class API to support your scenario- we can recommend some options for you to get started:

- Recording only Audio by following the guidelines https://aws.amazon.com/about-aws/whats-new/2019/11/amazon-chime-voice-connector-now-supports-siprec/. It would require you to set up a voice connector and have a participant join the SDK call via https://docs.aws.amazon.com/chime/latest/dg/mtgs-sdk-cvc.html. 
- Build a custom solution running in an AWS EC2 or ECS instance to capture the audio + video streams in a web page using Chrome's tabCapture APIs (https://developer.chrome.com/extensions/tabCapture) and piping the resulting MediaStream into Kinesis

Thanks!

**Comment by Axe129** [comment]
Thanks a lot for your response! Really appreciate it.

**Comment by peternijssen** [comment]
@vidya-mohan I am looking for the same solution as mentioned above.
Is AWS expecting to expand Chime with being able to send the video + audio streams to Kinesis? That would open up so many options!

In the meantime, do you have a working example or more information how to achieve this with tabCapture?

**Comment by vidya-mohan** [comment]
@peternijssen @Axe129 We dont have a sample yet. We have just published https://github.com/aws-samples/amazon-chime-sdk-recording-demo which captures the stream and pushes to S3. You can use that as a starter code and along with the https://docs.aws.amazon.com/kinesisvideostreams/latest/dg/producer-sdk.html push to Kinesis and from there to Rekognition or Transcribe.

**Comment by peternijssen** [comment]
@vidya-mohan Thanks. We will start trying this right away.

**Comment by aburnson** [comment]
Closing issue. Feel free to re-open if you have more questions on this topic.

**Comment by rakesh-eltropy** [comment]
@vidya-mohan do we have any first class API support for meeting recording, ability to send stream to Kinesis etc now?

**Comment by vidya-mohan** [comment]
@rakesh-eltropy we launched better support: https://github.com/aws/amazon-chime-sdk-js/issues/1011

**Comment by rakesh-eltropy** [comment]
Brilliant, thank you @vidya-mohan. This will make AWS Chime SDK even better.
