### ISSUE TITLE
Camera immediately freezes on Galaxy A8+, Android 9

### ISSUE THREAD

**Issue by BC-Mikey** [aws/amazon-chime-sdk-js#1754]
### What happened and what did you expect to happen?

When enabling a camera with a Galaxy A8+, Android 9 the video stream in the Attendee Tile immediately freezes. This happens regardless of whether or not other users have their cameras enabled. The expected behavior is that their video should broadcast just as it does for other attendees.

### Have you reviewed our existing documentation?

- [X] GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [X] FAQs [page](https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html)
- [X] README [page](https://github.com/aws/amazon-chime-sdk-js#amazon-chime-sdk-for-javascript)
- [X] Feature-specific [guides](https://github.com/aws/amazon-chime-sdk-js#guides)

### Reproduction steps

Enter a Chime Meeting with a Galaxy A8+, Android 9 device. Enable Camera. It will freeze after a second or two. You can turn your camera off and back on and the same behavior will happen.

### Amazon Chime SDK for JavaScript version

2.21.0

### What browsers are you seeing the problem on?

Google Chrome

### Browser version

95.0.4638.54

### Browser console logs

There were no specific logs or errors for this issue in the browser console.

**Comment by xuesichao** [comment]
Hi @BC-Mikey , thanks for reporting this issue. Could you please provide the logs to help us debug the issue?

**Comment by BC-Mikey** [comment]
@xuesichao which kinds of logs are you looking for? An export of HAR logs from the browser?

**Comment by BC-Mikey** [comment]
Hi @xuesichao, I have three sets of logs. One of them is captures from the Android device and the other two are from mine where I saw the device was frozen. They appeared to happen when he either switched between front & back cameras or exited to the home page. I have two logs of either scenario.

[android-a8-camera-switch-back-camera.txt](https://github.com/aws/amazon-chime-sdk-js/files/7500219/android-a8-camera-switch-back-camera.txt)
[android-a8-camera-switch-home-screen.txt](https://github.com/aws/amazon-chime-sdk-js/files/7500220/android-a8-camera-switch-home-screen.txt)
[android-a8-pablo-device-log.txt](https://github.com/aws/amazon-chime-sdk-js/files/7500221/android-a8-pablo-device-log.txt)

**Comment by ltrung** [comment]
@BC-Mikey Just to clarify was the video freeze on the remote side or on the Android device too?

**Comment by BC-Mikey** [comment]
Sorry - I mean "exit to lock screen" or just leave the browser. We weren't sure what the desired behavior for the camera should be here, since the meeting & audio appears to continue.

The video freeze occurs on both of our ends.

**Comment by ltrung** [comment]
So for that 'exit to lock screen' issue, it is documented in our [FAQs](https://github.com/aws/amazon-chime-sdk-js/blob/master/guides/07_FAQs.md#i-notice-that-if-i-turn-on-camera-and-put-the-browsers-in-background-others-in-the-meeting-will-see-black-tile-in-safarichromefirefox-in-ios-and-frozen-tile-in-chrome-in-android-is-this-a-known-issue). 
>In Android, the video stream is muted when in background and thus, the video will show the last frame

**Comment by Sandip-Z** [comment]
I am facing the same issue. When the attendee joins the meeting with switching off their camera and switch on their camera in the middle of meeting, their camera freezes until they manually switch off and switch on again or switch to back camera. I wonder what's causing this.

**Comment by devalevenkatesh** [comment]
@Sandip-Z @BC-Mikey Is this still happening? Does this happen with latest versions of JS SDK as well?

If yes, could you try below official WebRTC sample to check if this is a generic issue on your devices:
1. https://webrtc.github.io/samples/src/content/peerconnection/pc1/ (This involved peerconnection and should give a local and remote view of your video)
2. https://webrtc.github.io/samples/src/content/getusermedia/gum/ (This is basic getUserMedia demo)

Please let us know what your results are?

**Comment by BC-Mikey** [comment]
Hi @devalevenkatesh, our engineer with this device is currently out of the office, but I will make sure this gets over to him to test next week when he returns. Thank you for the update!

**Comment by pgutierrez-bcov** [comment]
We tested with the device using the WebRTC samples. It seems to be a generic issue with the device. Thanks for the help!

**Comment by ltrung** [comment]
Thanks. Closing the issue for now.
