### ISSUE TITLE
Reduction in delay when switching video processors

### ISSUE THREAD

**Issue by Nanosync** [aws/amazon-chime-sdk-js#1759]
# Community Note
* Please vote for this issue by adding a 👍 reaction to the issue. This will help the community and maintainers from the Amazon Chime SDK team to prioritize this request.
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request.
* Please go through the existing [issues](https://github.com/aws/amazon-chime-sdk-js/issues) to see if your request has already been recommended.
* Please do not use this template for bugs or support. Each individual repository has a PR template, documentation and resources for [troubleshooting](https://github.com/aws/amazon-chime-sdk-js#troubleshooting-and-support).
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.

# Tell us about your request
## What do you want us to build?
Which Amazon Chime SDK or feature area is this request for?
- [amazon-chime-sdk-js](https://github.com/aws/amazon-chime-sdk-js)
- [amazon-chime-sdk-component-library-react](https://github.com/aws/amazon-chime-sdk-component-library-react)

We would like to request for a video processor feature that can reduce the delay when switching transform devices. Currently, we have implemented our own virtual background feature. At the moment, the process is as follows: stop the existing video transform device, setup and choose a new transform device, start it. This is done for different backgrounds.

## Tell us about the problem you are trying to solve and why is it hard?
The more details you provide us, the better we will be able to help you.

There is a noticeable delay such that the video feed turns black for almost 1.5 seconds before responding again. We have tried to choose a new device without stopping the existing transform device. But as a result, the other transform device causes memory leaks while its video processing pipelines continue to execute, and sometimes the device output also becomes completely black, with an error indicating no device was selected.

## How are you currently solving a problem?
Are there any workarounds or mitigations you have used? Why is it not working for you?

We are currently using the default approach (stop transform device, choose a new transform device, start the transform device).

## Additional context
Anything else we should know?

n/a

**Comment by ltrung** [comment]
We have released background replacement that allow users to use background image (See PR #1920). This feature is available in NPM version 2.25.0. Could you try it to see if it improves on the delay when switching background?
