### ISSUE TITLE
Virtual background video frame processor

### ISSUE THREAD

**Issue by shriyajuneja** [aws/amazon-chime-sdk-js#1766]
# Community Note
* Please vote for this issue by adding a 👍 reaction to the issue. This will help the community and maintainers from the Amazon Chime SDK team to prioritize this request.
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request.
* Please go through the existing [issues](https://github.com/aws/amazon-chime-sdk-js/issues) to see if your request has already been recommended.
* Please do not use this template for bugs or support. Each individual repository has a PR template, documentation and resources for [troubleshooting](https://github.com/aws/amazon-chime-sdk-js#troubleshooting-and-support).
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.

# Tell us about your request
## What do you want us to build?

Virtual background frame processor just like background blur frame processor, to change background of video stream to custom images
Which Amazon Chime SDK or feature area is this request for?
[amazon-chime-sdk-js](https://github.com/aws/amazon-chime-sdk-js),
[amazon-chime-sdk-component-library-react](https://github.com/aws/amazon-chime-sdk-component-library-react)

## Tell us about the problem you are trying to solve and why is it hard?
We want to implement custom images as backgrounds in video, we have already implemented this but since chime has provided blur feature now, it may as well provide custom background images option.

## How are you currently solving a problem?
Are there any workarounds or mitigations you have used? Why is it not working for you?

## Additional context
Anything else we should know?

**Comment by ltrung** [comment]
We have released background replacement that allow users to use background image (See PR #1920). This feature is available in NPM version 2.25.0 so close this issue now. Feel free to try it out and let us know your feedback.
