### ISSUE TITLE
Unable to add ExternalMeetingId with Create Meeting API

### ISSUE THREAD

**Issue by abhimanusharma** [aws/amazon-chime-sdk-js#1767]
### What happened and what did you expect to happen?

Here is my code:

```
 await chime
        .createMeeting({
          ClientRequestToken: uuid(),
          ExternalMeetingId: title,
          MeetingHostId: meetingHost,
          MediaRegion: region
        })
        .promise();
```

After join request I am getting a response like this:

```
{
	"Title": "UbyaSot",
	"Meeting": {
		"MeetingId": "026f173e-6209-4df9-97fb-893051020706",
		"ExternalMeetingId": null,
		"MediaPlacement": {
			"AudioHostUrl": "76bf5ecaa14ea0ff7f761e56d9354106.k.m1.ue1.app.chime.aws:3478",
			"AudioFallbackUrl": "wss://haxrp.m1.ue1.app.chime.aws:443/calls/026f173e-6209-4df9-97fb-893051020706",
			"ScreenDataUrl": "wss://bitpw.m1.ue1.app.chime.aws:443/v2/screen/026f173e-6209-4df9-97fb-893051020706",
			"ScreenSharingUrl": "wss://bitpw.m1.ue1.app.chime.aws:443/v2/screen/026f173e-6209-4df9-97fb-893051020706",
			"ScreenViewingUrl": "wss://bitpw.m1.ue1.app.chime.aws:443/ws/connect?passcode=null&viewer_uuid=null&X-BitHub-Call-Id=026f173e-6209-4df9-97fb-893051020706",
			"SignalingUrl": "wss://signal.m1.ue1.app.chime.aws/control/026f173e-6209-4df9-97fb-893051020706",
			"TurnControlUrl": "https://ccp.cp.ue1.app.chime.aws/v2/turn_sessions",
			"EventIngestionUrl": null
		},
		"MediaRegion": "us-east-1"
	},
	"Attendee": {
		"ExternalUserId": "615fe7d00c8f4300dc2af43a#Abhimanu Sharma",
		"AttendeeId": "2060b61d-bfd8-aee8-3eeb-51206f8b6503",
		"JoinToken": "MjA2MGI2MWQtYmZkOC1hZWU4LTNlZWItNTEyMDZmOGI2NTAzOjllM2JkMmY3LTU3ZTYtNDc5Ny1hMTJkLTNmNjczYmY2NWJmNg",
		"UserImage": ""
	}
}
```

Title has string value but it is not setting for external Meeting id. It is becoming null automatically,

### Have you reviewed our existing documentation?

- [X] GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [X] FAQs [page](https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html)
- [X] README [page](https://github.com/aws/amazon-chime-sdk-js#amazon-chime-sdk-for-javascript)
- [X] Feature-specific [guides](https://github.com/aws/amazon-chime-sdk-js#guides)

### Reproduction steps

Use createMeeting function to create a Chime meeting, observe that the ExternalMeetingId is missing from the output object.

### Amazon Chime SDK for JavaScript version

"amazon-chime-sdk-js": "2.16.1",

### What browsers are you seeing the problem on?

Google Chrome

### Browser version

Version 95.0.4638.54 (Official Build) (64-bit)

### Meeting and Attendee ID Information.

"MeetingId": "026f173e-6209-4df9-97fb-893051020706",
"AttendeeId": "2060b61d-bfd8-aee8-3eeb-51206f8b6503",

### Browser console logs

NA

**Comment by ashleyqu** [comment]
The "ExternalUsersEnabled" is no. It seems that you did not enable external users and that might be why you did not get ExternalMeetingId from response.

**Comment by abhimanusharma** [comment]
@ashleyqu I don't see any such option "ExternalUsersEnabled". Where should I add it? Can you show me with an example?

I have read all the documentation, REAEME, FAQs but could not find this "ExternalUsersEnabled" anywhere.

**Comment by vincebai** [comment]
Have you verified that the passed in string in the request is not empty before awaiting on the promise? Do you get the same result with a string constant value passed in to the request instead of your `title` variable?

**Comment by vincebai** [comment]
This it the request body that I see in our logs. Seems that you are passing in `null` as the ExternalMeetingId
```
{
    "ClientRequestToken": "17125d37-650e-4907-848a-5e899a8b026e",
    "MediaRegion": "us-east-1"
}
```

**Comment by devalevenkatesh** [comment]
Closing this issue due to in-activity, feel free to re-open if you still need any help further or have any questions around this.
