### ISSUE TITLE
boundExternalUserId undefined for local tile

### ISSUE THREAD

**Issue by andrewwusfdc** [aws/amazon-chime-sdk-js#1768]
### What happened and what did you expect to happen?

When handling the videoTileDidUpdate callback for a local tile, we noticed that boundExternalUserId doesn't exist. That value does exist for remote tiles.

We were hoping to just use the same logic to pull the external user id (which contains the display name for our implementation) for all video tiles. Can Chime comment on if this behavior is expected or not?

### Have you reviewed our existing documentation?

- [X] GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [X] FAQs [page](https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html)
- [X] README [page](https://github.com/aws/amazon-chime-sdk-js#amazon-chime-sdk-for-javascript)
- [X] Feature-specific [guides](https://github.com/aws/amazon-chime-sdk-js#guides)

### Reproduction steps

Create a local video tile and attempt to retrieve boundExternalUserId

### Amazon Chime SDK for JavaScript version

2.17.0

### What browsers are you seeing the problem on?

Chrome

### Browser version

95.0.4638.69

### Browser console logs

NA

**Comment by devalevenkatesh** [comment]
Hi @andrewwusfdc ,

I checked and ran JS SDKs [meeting demo app](https://github.com/aws/amazon-chime-sdk-js/tree/master/demos/browser) and could see the `boundExternalUserId` for the local tile in `videoTileDidUpdate`.

There are multiple updates provided in `videoTileDidUpdate` and I could see in the initial first update when the `tileId` is assigned then lot of fields are empty but later as fields are updated in the second update itself you should see the `boundExternalUserId` in the tileState.

In the meeting demo app, [here](https://github.com/aws/amazon-chime-sdk-js/blob/master/demos/browser/app/meetingV2/video/VideoTileCollection.ts#L162-L164) we attach the video tile nameplate by accessing the same tileState's boundExternalUserId.

Could you please once check the demo app and see if you are ignoring next updates where it send the attached boundExternalUserId?

Also, request you to attach the browser console logs for further checking, here are some steps to help get logs:
- https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html#how-can-i-get-amazon-chime-sdk-logs-for-debugging
- https://aws.github.io/amazon-chime-sdk-js/modules/apioverview.html#1a-create-a-logger

**Comment by ltrung** [comment]
Close due to inactivity. Feel free to reopen if you still need help.
