### ISSUE TITLE
Participants can lose audio from a Safari user who switches tabs (using WebAudio)

### ISSUE THREAD

**Issue by alhambra1** [aws/amazon-chime-sdk-js#1773]
### What happened and what did you expect to happen?

We revisited and replicated an audio issue our QA team reported internally some time ago -- using the JavaScript client SDK (we tested version 2.20.1), when we set

`deviceController = new DefaultDeviceController(this.meetingLogger, {enableWebAudio: true});`

which we believe we need in order to use the Voice Focus feature, we see the following symptom: if a Safari user (tested on version 15.0) shifts focus to another tab on the Safari browser, all other participants lose the audio from the Safari user that shifted focus to another tab. Additionally, but not consistently, when shifting focus back to the video conference browser tab, the other participants can sometimes get sounds described as "static" or "robot voice" (possibly related to https://github.com/aws/amazon-chime-sdk-js/issues/1548) (switching the tab a few times on the Safari browser with the receiver on an older Windows laptop, I even once heard only static for the Safari user). The issue apparently does not happen when WebAudio is not enabled.

### Have you reviewed our existing documentation?

- [X] GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [X] FAQs [page](https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html)
- [X] README [page](https://github.com/aws/amazon-chime-sdk-js#amazon-chime-sdk-for-javascript)
- [X] Feature-specific [guides](https://github.com/aws/amazon-chime-sdk-js#guides)

### Reproduction steps

Please see description.

### Amazon Chime SDK for JavaScript version

2.20.1

### What browsers are you seeing the problem on?

Instigator on Safari 15 (and possibly lower), receivers on any browser.

### Browser version

15.0 and possibly lower

### Browser console logs

We do not have debug logs for this at this time but the issue is prominent and easy to replicate.

**Comment by ltrung** [comment]
This is documented in #1059. We have submitted the [Safari bug](https://bugs.webkit.org/show_bug.cgi?id=231105).

**Comment by devalevenkatesh** [comment]
Closing due to reported safari bug.
