### ISSUE TITLE
tileWillBePausedByDownlinkPolicy and tile pausing vs removal

### ISSUE THREAD

**Issue by alhambra1** [aws/amazon-chime-sdk-js#1774]
### What are you trying to do?

Using Chime SDK version 2.18, which we worked with up to a few weeks ago, we were able to see callbacks for tileWillBePausedByDownlinkPolicy (albeit by trying to force it using higher uplink and straining the bandwidth). However in our general testing for 2.20.1, which includes staff with varying internet setups and locations, we have not yet seen this callback. We have, however, seen tiles updated to the `tileState.paused` `true` value, which we are using to indicate to users that the video stream removal was not the user's choice.

### How can the documentation be improved to help your use case?

Could you please help us understand if this tile paused state is expected and what is the relationship between that and tileWillBePausedByDownlinkPolicy, which we don't seem to get now? To further clarify, when we were getting tileWillBePausedByDownlinkPolicy callbacks, *they were associated with tile removal, not tileState paused*.

### What documentation have you looked at so far?

https://aws.github.io/amazon-chime-sdk-js/modules/prioritybased_downlink_policy.html

**Comment by ltrung** [comment]
@alhambra1 Could you add a client log where you see that `tileState.paused`? the pause state means the video tile is paused either by the priority-based downlink policy or by the application calling `pauseVideoTile` API. 
If it is paused by the priority downlink policy, it should trigger `tileWillBePausedByDownlinkPolicy` (As seen in this code:  https://github.com/aws/amazon-chime-sdk-js/blob/master/src/videodownlinkbandwidthpolicy/VideoPriorityBasedPolicy.ts#L770). 
Can you attach a client log where the tile is paused but you do not receive `tileWillBePausedByDownlinkPolicy`?

**Comment by alhambra1** [comment]
[tiles_paused.log.zip](https://github.com/aws/amazon-chime-sdk-js/files/7517495/tiles_paused.log.zip)

@ltrung Please see attached logs.

**Comment by alhambra1** [comment]
@ltrung I think the pausing started after 3:00am UTC in the logs.

**Comment by ltrung** [comment]
```
logging.ts:238 2021-11-11T03:03:46.746Z [INFO] ChimeMeetingLogs - bwe: pausing streamId 27 attendee d86756af-7841-b015-426c-3cfce4710d02 due to bandwidth
logging.ts:238 2021-11-11T03:03:46.747Z [INFO] ChimeMeetingLogs - bwe: pausing streamId 47 attendee 9a668cd9-18e4-b8c0-5abc-c9713922cd01 due to bandwidth
```
According to the logs, the policy tries to pause streams at 3:03. Did you not receive `tileWillBePausedByDownlinkPolicy` event? As can be seen in this code [here](https://github.com/aws/amazon-chime-sdk-js/blob/master/src/videodownlinkbandwidthpolicy/VideoPriorityBasedPolicy.ts#L771), after that log line we trigger the event right away.

**Comment by alhambra1** [comment]
@ltrung the code does seem straightforward so it would be surprising not to receive the callback. The way we have been checking is by calling our own logger, which seemed to work fine on 2.18 (although there we would get a tile removal not pause). Let me make some code changes to rule out an issue in our own code, test and get back to you.

**Comment by alhambra1** [comment]
@ltrung I believe the error is in our code, we accidentally removed a line calling the observer initialiser. Sorry about the trouble. If we find otherwise, we'll reopen the issue.
