### ISSUE TITLE
Does AWS Chime SDK 2.21.0 support media capture pipeline events?

### ISSUE THREAD

**Issue by dimabory** [aws/amazon-chime-sdk-js#1777]
### What are you trying to do?

I'm trying to listen for events such as `chime:MediaPipelineInProgress`, `chime:MediaPipelineDeleted`, `chime:MediaPipelineTemporaryFailure`, `chime:MediaPipelineResumed` and `chime:MediaPipelinePermanentFailure`, but neither actually coming. 

### How can the documentation be improved to help your use case?

N/A

### What documentation have you looked at so far?

Amazon Chime SDK Developer Guide
- Automating Amazon Chime with EventBridge https://docs.aws.amazon.com/chime/latest/ag/automating-chime-with-cloudwatch-events.html#events-sdk

**Comment by ajselvar-work** [comment]
@dimabory can you please provide a sample meeting id to further debug this issue

**Comment by dimabory** [comment]
Hi @ajselvar-work . Please check `2646bd30-26be-4d2c-b190-8814de210706`. I was able to receive `chime:MediaPipelineInProgress`, but not `chime:MediaPipelineDeleted`, which I assume should have come when I stop recording.

**Comment by ajselvar-work** [comment]
Our record shows that the service was able to successfully publish to the SNS topic you provided and the eventbridge.

**Comment by devalevenkatesh** [comment]
@dimabory Is this still an issue? We could see that the events were successfully posted.

**Comment by dimabory** [comment]
> @dimabory Is this still an issue? We could see that the events were successfully posted.

Yes, we can close this
