### ISSUE TITLE
Video recorder successfully but all is black page without audio and video

### ISSUE THREAD

**Issue by MjdBh** [aws/amazon-chime-sdk-js#1782]
### What happened and what did you expect to happen?

We have a react base web application that users join in a meeting and record their meeting. It is working properly but today at a meeting that 3 times recorded first it worked correctly but 2 of them were black pages, without any audio and video but the time of recording is correct. Before starting the meeting we are checking audio and video devices are available.

SDK version:2.16
browser: chrome
recording method: pipeline

### Have you reviewed our existing documentation?

- [X] GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [X] FAQs [page](https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html)
- [X] README [page](https://github.com/aws/amazon-chime-sdk-js#amazon-chime-sdk-for-javascript)
- [X] Feature-specific [guides](https://github.com/aws/amazon-chime-sdk-js#guides)

### Reproduction steps

We can share our account id and pipeline information.

### Amazon Chime SDK for JavaScript version

2.16

### What browsers are you seeing the problem on?

Chrome

### Browser version

96

### Meeting and Attendee ID Information.

{\"MeetingId\":\"081c5d05-f3ec-4278-b485-b506a53a0706\

### Browser console logs

I don't have ir.it

**Comment by MjdBh** [comment]
I found that when the recording was starting if one of the attendees are mute then the recording page is black.

**Comment by devalevenkatesh** [comment]
Thanks for reporting the issue. You mentioned "pipeline" in the issue content, but, to confirm are you using Amazon Chime SDK media capture pipeline?
https://aws.amazon.com/blogs/business-productivity/capture-amazon-chime-sdk-meetings-using-media-capture-pipelines/

**Comment by tenge-amzn** [comment]
Hi @MjdBh 
How was the recording started? Is it though create-media-capture-pipeline?

**Comment by MjdBh** [comment]
Yes it start from create media pipeline

**Comment by MjdBh** [comment]
Yes all using video

**Comment by ajselvar-work** [comment]
@MjdBh There are total of 9 capture media-pipelines Create and Delete for this particular meeting. 8 for 30 seconds and the last one lasted for about a minute. Will you be able to tell us which media-pipeline u had issue with? 

Please make sure that you have audio turned on when you start the media capture. Since media-pipelines capture the active speaker stream, it will wait for the audio to be available to pick the right video for active speaker. Until that, there will be a black video.

**Comment by tenge-amzn** [comment]
Closing for now. Please reopen if you still experience issues.
