### ISSUE TITLE
MediaPipeline is stopping automatically after 20-30 minute

### ISSUE THREAD

**Issue by abhimanusharma** [aws/amazon-chime-sdk-js#1788]
### What happened and what did you expect to happen?

chime:MediaPipelineDeleted is triggered automatically even when there is no request to stop recording made by the user or last participant left.

### Have you reviewed our existing documentation?

- [X] GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [X] FAQs [page](https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html)
- [X] README [page](https://github.com/aws/amazon-chime-sdk-js#amazon-chime-sdk-for-javascript)
- [X] Feature-specific [guides](https://github.com/aws/amazon-chime-sdk-js#guides)

### Reproduction steps

Join a meeting, Start a meeting recording, Voice is enabled for the participant. keep the recording started for 3-4 hours, but the recording file contain meeting only for 20 mins or sometimes 30 mins.

### Amazon Chime SDK for JavaScript version

"amazon-chime-sdk-js": "2.16.1",

### What browsers are you seeing the problem on?

Google Chrome

### Browser version

Version 95.0.4638.54 (Official Build) (64-bit)

### Browser console logs

N/A

**Comment by devalevenkatesh** [comment]
Can you also please provide browser console JS SDK logs by providing the console logger while creating the meeting session?

https://aws.github.io/amazon-chime-sdk-js/modules/apioverview.html#1a-create-a-logger

**Comment by ajselvar-work** [comment]
@abhimanusharma Can you please provide the meeting id where the issue happened

**Comment by abhimanusharma** [comment]
@ajselvar-work Let me reproduce this issue and come up with meeting id and logs.

**Comment by devalevenkatesh** [comment]
Closing due to no-activity, but please feel free to re-open if you still face issue with request information. Thanks!
