### ISSUE TITLE
tileWillBePausedByDownlinkPolicy event is notified asynchronously

### ISSUE THREAD

**Issue by richnew10** [aws/amazon-chime-sdk-js#1790]
It stands to reason that a 'will' event should be processed by observers _before_ the action takes place. This is necessary for consumers to perform tasks like snapshotting a video stream, adapting layout, etc.

That is not the case for `VideoPriorityBasedPolicy`, where

https://github.com/aws/amazon-chime-sdk-js/blob/master/src/videodownlinkbandwidthpolicy/VideoPriorityBasedPolicy.ts#L248-L256

follows the SDK convention of using `setTimeout` to trigger observers, and thus

https://github.com/aws/amazon-chime-sdk-js/blob/master/src/videodownlinkbandwidthpolicy/VideoPriorityBasedPolicy.ts#L774-L776

completes _after_ the policy's decision is actually applied. The observers never get to see the state of the world _before_ the action, so this is effectively `tileWasPausedByDownlinkPolicy`, not `tileWillBePausedByDownlinkPolicy`. I expect that `tileWillBeUnpausedByDownlinkPolicy` suffers the same fate.

We should either:

1. Synchronously invoke these observers.
2. Asynchronously invoke the rest of the downlink policy behavior after the observer tasks have been queued on the event loop.

**Comment by devalevenkatesh** [comment]
The PR is merged now, hence closing the issue.
