### ISSUE TITLE
Random video tiles freezing with simulcast and Video priority based downlink policy on

### ISSUE THREAD

**Issue by paul365** [aws/amazon-chime-sdk-js#1797]
### What happened and what did you expect to happen?

Video tiles are freezing, getting 0 receivedAverageBitrateKbps for multiple video tiles. Videos are not paused by the downlink policy and just start freezing after a few minutes after joining. After refreshing and rejoining the frozen tiles start moving again but start freezing again after a while. I expect tiles not to freeze, unless if the video is paused by the downlink policy

Our config:
simulcast enabled
videoDownlinkBandwidthPolicy set to VideoPriorityBasedPolicy

### Have you reviewed our existing documentation?

- [X] GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [X] FAQs [page](https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html)
- [X] README [page](https://github.com/aws/amazon-chime-sdk-js#amazon-chime-sdk-for-javascript)
- [X] Feature-specific [guides](https://github.com/aws/amazon-chime-sdk-js#guides)

### Reproduction steps

join a meeting with simulcast on, with 4 or more attendees on video.

### Amazon Chime SDK for JavaScript version

2.21.1

### What browsers are you seeing the problem on?

Chrome

### Browser version

Version 95.0.4638.69 (Official Build) (arm64)

### Meeting and Attendee ID Information.

33f0efd2-7909-4fe6-a53d-72b114890706

### Browser console logs

2-es2015.4efd30c9b27842bf6857.js:1 2021-11-16T10:37:23.198Z [INFO] SDK - [CHIME] One or more video streams are not receiving expected amounts of data [{"expectedAverageBitrateKbps":159.327,"receivedAverageBitrateKbps":155.288,"attendeeId":"6c61fe57-4d39-a3eb-7399-094ef11b7de5"},{"expectedAverageBitrateKbps":161.686,"receivedAverageBitrateKbps":173.592,"attendeeId":"213726c5-255d-24cd-ad4b-092d0afaf6b8"},{"expectedAverageBitrateKbps":368.154,"receivedAverageBitrateKbps":0,"attendeeId":"6d53482a-887f-8c88-2467-a5018a3dd591"},{"expectedAverageBitrateKbps":151.156,"receivedAverageBitrateKbps":152.896,"attendeeId":"b11afa83-aac1-c58c-4c8d-ed9180f18704"},{"expectedAverageBitrateKbps":140.335,"receivedAverageBitrateKbps":158.64,"attendeeId":"fe7d1dac-3efa-2238-5f78-5881ca7f4f35"},{"expectedAverageBitrateKbps":145.499,"receivedAverageBitrateKbps":0,"attendeeId":"a56bc7a7-e769-ce17-5d68-9dfacaa0af18"},{"expectedAverageBitrateKbps":112.276,"receivedAverageBitrateKbps":62.704,"attendeeId":"30cf7688-92e6-dc30-1966-751526a57048"},{"expectedAverageBitrateKbps":67.466,"receivedAverageBitrateKbps":0,"attendeeId":"8c848f77-7d46-bd87-cd7b-2b7da2e1a260"}]

2-es2015.4efd30c9b27842bf6857.js:1 2021-11-16T10:37:18.203Z [INFO] SDK - [CHIME] One or more video streams are not receiving expected amounts of data [{"expectedAverageBitrateKbps":108.071,"receivedAverageBitrateKbps":152.856,"attendeeId":"fe7d1dac-3efa-2238-5f78-5881ca7f4f35"},{"expectedAverageBitrateKbps":368.953,"receivedAverageBitrateKbps":0,"attendeeId":"a56bc7a7-e769-ce17-5d68-9dfacaa0af18"},{"expectedAverageBitrateKbps":140.018,"receivedAverageBitrateKbps":0,"attendeeId":"8c848f77-7d46-bd87-cd7b-2b7da2e1a260"},{"expectedAverageBitrateKbps":129.146,"receivedAverageBitrateKbps":166.08,"attendeeId":"6c61fe57-4d39-a3eb-7399-094ef11b7de5"},{"expectedAverageBitrateKbps":153.508,"receivedAverageBitrateKbps":158.968,"attendeeId":"b11afa83-aac1-c58c-4c8d-ed9180f18704"},{"expectedAverageBitrateKbps":176.19,"receivedAverageBitrateKbps":0,"attendeeId":"6d53482a-887f-8c88-2467-a5018a3dd591"},{"expectedAverageBitrateKbps":107.294,"receivedAverageBitrateKbps":141.152,"attendeeId":"30cf7688-92e6-dc30-1966-751526a57048"},{"expectedAverageBitrateKbps":160.986,"receivedAverageBitrateKbps":60.504,"attendeeId":"213726c5-255d-24cd-ad4b-092d0afaf6b8"}]

I can provide full logs

**Comment by hensmi-amazon** [comment]
I've localized this to an issue on backend with regards to non-subscribed videos being disabled when the client is simulcast stream switching and am pushing a change.  It would probably go in starting next week but due to holidays it may only be partially deployed.  I will update this ticket next week.  In the mean time if possible you can temporarily disable simulcast.

**Comment by hensmi-amazon** [comment]
The backend changes to fix the issues described in this issue have been deployed.  Please reopen (or cut a new issue) if you continue to see freezes like mentioned.

**Comment by paul365** [comment]
thanks @hensmi-amazon!
