### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'bgd')

### ISSUE THREAD

**Issue by christiansaavedra** [aws/amazon-chime-sdk-js#1803]
### What happened and what did you expect to happen?

Hello, 

I've using Chime on my react app for months and it went well. Today, I updated react to version 17.0.2, and also Material UI to v5. Since then, I've been receiving this error when joining a meeting.

I also updated to the latest chime and react chime versions, but the error appeared on the old ones I had too.

I didn't received any errors on the network endpoints, they all returned 200.

### Have you reviewed our existing documentation?

- [X] GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [X] FAQs [page](https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html)
- [X] README [page](https://github.com/aws/amazon-chime-sdk-js#amazon-chime-sdk-for-javascript)
- [X] Feature-specific [guides](https://github.com/aws/amazon-chime-sdk-js#guides)

### Reproduction steps

1. Join a meeting

### Amazon Chime SDK for JavaScript version

2.21.1

### What browsers are you seeing the problem on?

Chrome

### Browser version

Version 96.0.4664.45 (Official Build) (arm64)

### Browser console logs

TypeError: Cannot read properties of undefined (reading 'bgd')
push../node_modules/amazon-chime-sdk-component-library-react/lib/index.esm.js.gridData.usingGrid
node_modules/amazon-chime-sdk-component-library-react/lib/index.esm.js:5482
  5479 | var landscapeStyles = "\n  @media (max-height: 600px) {\n    grid-template-areas: 'ft ft' 'ft ft';\n    grid-template-rows: repeat(2,1fr);\n    grid-template-columns: 25%;\n    grid-auto-columns: 25%;\n    grid-auto-flow: column;\n  }\n";
  5480 | var StyledGrid$1 = styled.div(templateObject_1$f || (templateObject_1$f = __makeTemplateObject(["\n  position: relative;\n  display: grid;\n  height: 100%;\n  width: 100%;\n  overflow: auto;\n  background-color: ", ";\n\n  ", "\n  ", ";\n"], ["\n  position: relative;\n  display: grid;\n  height: 100%;\n  width: 100%;\n  overflow: auto;\n  background-color: ", ";\n\n  ",
  5481 |     "\n  ",
> 5482 |     ";\n"])), function (props) { return props.theme.videoGrid.bgd; }, function (_a) {
  5483 |     var size = _a.size, featured = _a.featured;
  5484 |     return ratioStyles["" + size + (featured ? '.featured' : '')] || '';
  5485 | }, function (_a) {
View compiled
Ne
src/utils/flatten.js:80
  77 |     }
  78 | 
  79 |     return flatten(result, executionContext, styleSheet, stylisInstance);
> 80 |   } else return chunk;
     | ^  81 | }
  82 | 
  83 | if (chunk instanceof Keyframes) {
View compiled
e.generateAndInjectStyles
src/models/ComponentStyle.js:90
  87 |   css += partRule;
  88 | 
  89 |   if (process.env.NODE_ENV !== 'production') dynamicHash = phash(dynamicHash, partRule + i);
> 90 | } else if (partRule) {
     | ^  91 |   const partChunk = flatten(partRule, executionContext, styleSheet, stylis);
  92 |   const partString = Array.isArray(partChunk) ? partChunk.join('') : partChunk;
  93 |   dynamicHash = phash(dynamicHash, partString + i);
View compiled
(anonymous function)
src/models/StyledComponent.js:80
  77 |   componentStyle: ComponentStyle,
  78 |   isStatic: boolean,
  79 |   resolvedAttrs: T,
> 80 |   warnTooManyClasses?: $Call<typeof createWarnTooManyClasses, string, string>
  81 | ) {
  82 |   const styleSheet = useStyleSheet();
  83 |   const stylis = useStylis();
View compiled
(anonymous function)
src/models/StyledComponent.js:125
  122 | 
  123 | const [context, attrs] = useResolvedAttrs(theme || EMPTY_OBJECT, props, componentAttrs);
  124 | 
> 125 | const generatedClassName = useInjectedStyle(
      | ^  126 |   componentStyle,
  127 |   isStatic,
  128 |   context,
View compiled
O
src/models/StyledComponent.js:174
  171 | 
  172 |   propsForElement.ref = refToForward;
  173 | 
> 174 |   return createElement(elementToBeCreated, propsForElement);
  175 | }
  176 | 
  177 | export default function createStyledComponent(
View compiled
▶ 18 stack frames were collapsed.
_callee4$
src/pages/pages/Train.tsx:378
  375 | async function toggle() {
  376 |   if (meetingStatus === MeetingStatus.Succeeded) {
  377 |     await toggleVideo();
> 378 |     setIsLoading(false);
      | ^  379 |   }
  380 | }
  381 | toggle();
View compiled
▶ 5 stack frames were collapsed.

**Comment by devalevenkatesh** [comment]
Closing as I see you opened one on the React library here:
https://github.com/aws/amazon-chime-sdk-component-library-react/issues/675

**Comment by christiansaavedra** [comment]
> Closing as I see you opened one on the React library here: [aws/amazon-chime-sdk-component-library-react#675](https://github.com/aws/amazon-chime-sdk-component-library-react/issues/675)

Sure, no problem. Sorry for the duplicate.
By the way, do you know how can I fix it?
