### ISSUE TITLE
Navigator API errors are being rethrown as generic errors

### ISSUE THREAD

**Issue by Nanosync** [aws/amazon-chime-sdk-js#1804]
### What happened and what did you expect to happen?

We are currently catching error names and handling them by a switch case when calling functions `listVideoInputDevices`, `listAudioInputDevices`, `chooseVideoInputDevice`, `chooseAudioInputDevice`. However, the chime JS sdk rethrows errors leading to generic errors, although the `error.message` property is preserved. In the `handleGetUserMediaError` function, the base error `GetUserMediaError` doesn't preserve the original `error.name` property.

### Have you reviewed our existing documentation?

- [X] GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [X] FAQs [page](https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html)
- [X] README [page](https://github.com/aws/amazon-chime-sdk-js#amazon-chime-sdk-for-javascript)
- [X] Feature-specific [guides](https://github.com/aws/amazon-chime-sdk-js#guides)

### Reproduction steps

Disable browser audio/video permissions then call any of the listed functions above. The functions that throw `GetUserMediaError` or a subclass of it has the `error.name` property `Error` although the original error name was more specific.

### Amazon Chime SDK for JavaScript version

2.21.0

### What browsers are you seeing the problem on?

Chrome

### Browser version

95.0.4638.69

### Browser console logs

n/a

**Comment by ltrung** [comment]
I created PR #1815 to address this issue but for now you can check the error name via error.cause.name.
```
catch (error) {
  if (error instanceof GetUserMediaError) {
    // Use error.cause?.name to access an Error name and error.cause?.message to access the original error messasge.
  }
}
```

**Comment by ltrung** [comment]
@Nanosync Would the PR #1815 solve your use case? We will return the class name instead of the generic Error name?

**Comment by ltrung** [comment]
PR #1815 has been merged so close this.

**Comment by Nanosync** [comment]
Hi @ltrung, yes, it will solve the issue. Thank you!
