### ISSUE TITLE
Creating Messaging Sessions without the AWS SDK for JavaScript v2

### ISSUE THREAD

**Issue by ryanbrown-rcd** [aws/amazon-chime-sdk-js#1810]
# Community Note
* Please vote for this issue by adding a 👍 reaction to the issue. This will help the community and maintainers from the Amazon Chime SDK team to prioritize this request.
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request.
* Please go through the existing [issues](https://github.com/aws/amazon-chime-sdk-js/issues) to see if your request has already been recommended.
* Please do not use this template for bugs or support. Each individual repository has a PR template, documentation and resources for [troubleshooting](https://github.com/aws/amazon-chime-sdk-js#troubleshooting-and-support).
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.

# Tell us about your request
## What do you want us to build?

For the [amazon-chime-sdk-js](https://github.com/aws/amazon-chime-sdk-js), the ability to create default Messaging Session Configurations and Messaging Sessions without the AWS SDK for JavaScript v2 client. This will enable an easier transition to the AWS SDK for JavaScript v3.

## Tell us about the problem you are trying to solve and why is it hard?

Currently, the chime sdk js requires passing in the AWS SDK for JavaScript v2 client when creating a new MessagingSessionConfiguration and DefaultMessagingSession. 

[Full code snippet from the README](https://github.com/aws/amazon-chime-sdk-js#messaging-session):
```javascript
import * as AWS from 'aws-sdk/global';
import * as Chime from 'aws-sdk/clients/chime';

import {
  ConsoleLogger,
  DefaultMessagingSession,
  LogLevel,
  MessagingSessionConfiguration,
} from 'amazon-chime-sdk-js';

const logger = new ConsoleLogger('SDK', LogLevel.INFO);

// You will need AWS credentials configured before calling AWS or Amazon Chime APIs.
const chime = new Chime({ region: 'us-east-1' });
const endpoint = await chime.getMessagingSessionEndpoint().promise();

const userArn = /* The userArn */;
const sessionId = /* The sessionId */;
const configuration = new MessagingSessionConfiguration(userArn, sessionId, endpoint.Endpoint.Url, chime, AWS);
const messagingSession = new DefaultMessagingSession(configuration, logger);
```
In the above code snippet, we import the aws-sdk v2 then pass it into the MessagingSessionConfiguration constructor. This seems to be required for the aws-sdk v2 crypto utilities, which are used in the [DefaultSigV4.ts file](https://github.com/aws/amazon-chime-sdk-js/blob/3d220d4222fd36e77e0c205d5f8677a0c5022bdd/src/sigv4/DefaultSigV4.ts).

## How are you currently solving the problem?

Currently, I am using both the AWS SDK for JavaScript v2 and v3 as a workaround. I use the aws-sdk v2 to create the default chime messaging session, then use the aws-sdk v3 for interacting with chime after the session is created. This workaround is working well, but needing both sdk versions is not ideal. It looks like I can maybe create a custom SigV4 signing class and pass it in as a potential alternative workaround, however that seemed like an unnecessary complexity for this scenario.

**Comment by michhyun1** [comment]
@ryanbrown-rcd thanks for bringing this up. We'll try to get to this as soon as we can.

**Comment by ryanbrown-rcd** [comment]
Awesome, thanks for the quick response, @michhyun1!

**Comment by ltrung** [comment]
@ryanbrown-rcd I have made some quick changes to migrate to aws sdk v3 in this branch https://github.com/aws/amazon-chime-sdk-js/blob/aws-sdk-v3/. Could you check this out to see if it solves the issue for you?
Just want to point out that `messagingSession.start` is now an async function due to aws-sdk v3 changes (https://github.com/aws/amazon-chime-sdk-js/blob/aws-sdk-v3/src/messagingsession/DefaultMessagingSession.ts#L63)

**Comment by alisaliso** [comment]
Also trying to reduce bundle size on the project with v3 `@aws-sdk/client-chime-sdk-messaging` lib functions for getting / deleting and listing messages, but the `amazon-chime-sdk-js` requires `aws-sdk/global`. 

`amazon-chime-sdk-js` doesn't support the `@aws-sdk/client-chime-sdk-messaging` ChimeSDKMessagingClient and can't connect

**Comment by ltrung** [comment]
@alisaliso Can you try the branch above to see if it resolves for you?

**Comment by alisaliso** [comment]
@ltrung  The link to the branch leads to the 404 page for me

**Comment by ltrung** [comment]
Sorry, fixed the link now.

**Comment by ltrung** [comment]
@alisaliso Did it work for you?

**Comment by alisaliso** [comment]
@ltrung, not sure, I'm getting the 
```
ERROR in ../../amazon-chime-sdk-js/node_modules/detect-browser/es/index.js Module not found: Error: Can't resolve 'process/browser' in
```
when trying to run my project. I'm figuring out why

**Comment by ltrung** [comment]
@alisaliso Any luck?

**Comment by ltrung** [comment]
@ltrung @ryanbrown-rcd We have released v3.0.0-beta.0 that remove the need for aws global object. Could you check it out?

**Comment by alisaliso** [comment]
On it

**Comment by alisaliso** [comment]
@ltrung hi! Checked the v3.0.0-beta.0, everything is working perfectly

**Comment by simmkyu** [comment]
We published the [Chime SDK for JavaScript v3](https://www.npmjs.com/package/amazon-chime-sdk-js). You can now create a messaging session with the AWS SDK for v3.
