### ISSUE TITLE
Attendees dropping from meeting

### ISSUE THREAD

**Issue by sanjitkung** [aws/amazon-chime-sdk-js#1812]
I was trying to test what happens when there are more than 200 attendees in my app.

I created 10 ECS tasks that opens up 20 headless browser instance in each. Then I ran puppeteer script that navigate through my application, fill required fields and join the meeting. 

After some time time, I saw few attendees were dropping from the meeting randomly.  updateAttendeePresence callback return presence value as false for dropped attendees.

is it because robot attendees does not have audio output, input or video input attached? or I am doing something wrong?

**Comment by devalevenkatesh** [comment]
Thanks for reporting the issue. Could you please use **Bug report form** template from [here] to create the issue? It helps us getting more information when you file the issue.

Could you please provide browser console level logs to check further on this?

**Comment by ltrung** [comment]
JS SDK requires audio input to for the attendeePresence. Otherwise, the attendee will be kicked from the meeting. You can use `--use-fake-device-for-media-stream', '--use-fake-ui-for-media-stream` when testing with headless devices for fake audio.

**Comment by sanjitkung** [comment]
@devalevenkatesh  Please find the attached log file. Attendee removed logged around line 1347.
[1637377644606.log](https://github.com/aws/amazon-chime-sdk-js/files/7573841/1637377644606.log)

@ltrung I added these flag to headless chrome, but no luck. Also I want to point out:

- It does not remove all the users, Only few random users being kicked out.
- As number of attendees increase, it kick out more and more users.
- If number of attendees are less (around 30 to 50) it does not kick out any one.

**Comment by sanjitkung** [comment]
I also added MeetingSessionPOSTLogger to my to log headless chrome event. One the users that got removed had this log
[log-events-viewer-result (2).csv](https://github.com/aws/amazon-chime-sdk-js/files/7575441/log-events-viewer-result.2.csv)

**Comment by devalevenkatesh** [comment]
@sanjitkung The log you attached is not a full log and only a few lines. You can check our [meetingV2](https://github.com/aws/amazon-chime-sdk-js/blob/master/demos/browser/app/meetingV2/meetingV2.ts#L1570-L1613) demo on how to use the meeting session POST logger. 

Can you try increasing the ECS tasks and see whether that help?

**Comment by RidipDe** [comment]
Hi @sanjitkung,

May I suggest to try varying load capacity?
For example:
a. 20 ECS tasks1 -> 10 headless browser instance in each
b. 40 ECS tasks1 -> 5 headless browser instance in each

Do you still observe the similar issue of random attendees being pushed out? 
If so, is the number of attendees being dropped in both scenarios similar to what you were observing before?

**Comment by sanjitkung** [comment]
@RidipDe Thanks a lot. Using 10 headless browser instance in each task seems to solve the problem.
