### ISSUE TITLE
Missing remote video tiles

### ISSUE THREAD

**Issue by kg-jcaron** [aws/amazon-chime-sdk-js#1813]
### What happened and what did you expect to happen?

We're seeing an issue where occasionally user A can't see user B's video, despite user B having their video enabled and all other users being able to see it.

The issue seems to start right on joining the meeting.

Even after 10+ minutes the video won't load unless the user B toggles their camera off and on again. Calling `meetingSession.audioVideo.getRemoteVideoTiles()` won't include the data for the missing video stream at any time until User B's camera is reset.

### Have you reviewed our existing documentation?

- [X] GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [X] FAQs [page](https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html)
- [X] README [page](https://github.com/aws/amazon-chime-sdk-js#amazon-chime-sdk-for-javascript)
- [X] Feature-specific [guides](https://github.com/aws/amazon-chime-sdk-js#guides)

### Reproduction steps

The issue is very intermittent; we can't reproduce it unfortunately. We've seen the issue 3 times total, and managed to get some logs for 1 of the occurrences.

### Amazon Chime SDK for JavaScript version

20.21.0, 20.20.0

### What browsers are you seeing the problem on?

Chrome

### Browser version

95.0.4638.69

### Meeting and Attendee ID Information.

Meeting ID: cecd8930-7fee-4368-bfb0-8993d5020706
Attendee whose video isn't showing up: 357127#89202bb9-6bfa-4de7-97e8-c8e561bfa431 

getRemoteVideoTiles() response for the user who can't see the video (missing attendee `357127#89202bb9-6bfa-4de7-97e8-c8e561bfa431`):
```
[
    {
        "tileId": 3,
        "localTile": false,
        "localTileStarted": false,
        "isContent": false,
        "active": false,
        "paused": false,
        "poorConnection": true,
        "boundAttendeeId": "fd7e723e-3185-28e8-5f77-da50c4165bf7",
        "boundExternalUserId": "357111#cca746c4-fea3-47e5-b822-da7e2869f98a",
        "boundVideoStream": {},
        "boundVideoElement": null,
        "nameplate": null,
        "videoElementCSSWidthPixels": null,
        "videoElementCSSHeightPixels": null,
        "devicePixelRatio": 1,
        "videoElementPhysicalWidthPixels": null,
        "videoElementPhysicalHeightPixels": null,
        "streamId": 3
    },
    {
        "tileId": 4,
        "localTile": false,
        "localTileStarted": false,
        "isContent": false,
        "active": false,
        "paused": false,
        "poorConnection": false,
        "boundAttendeeId": "7433d1c8-48e2-72f2-b4cc-dd59eae0f883",
        "boundExternalUserId": "85641#5549f451-1bf8-49a7-a5a2-a22836a81471",
        "boundVideoStream": {},
        "boundVideoElement": null,
        "nameplate": null,
        "videoStreamContentWidth": 720,
        "videoStreamContentHeight": 540,
        "videoElementCSSWidthPixels": null,
        "videoElementCSSHeightPixels": null,
        "devicePixelRatio": 1,
        "videoElementPhysicalWidthPixels": null,
        "videoElementPhysicalHeightPixels": null,
        "streamId": 6
    },
    {
        "tileId": 6,
        "localTile": false,
        "localTileStarted": false,
        "isContent": false,
        "active": false,
        "paused": true,
        "poorConnection": false,
        "boundAttendeeId": "",
        "boundExternalUserId": "",
        "boundVideoStream": {},
        "boundVideoElement": null,
        "nameplate": null,
        "videoElementCSSWidthPixels": null,
        "videoElementCSSHeightPixels": null,
        "devicePixelRatio": 1,
        "videoElementPhysicalWidthPixels": null,
        "videoElementPhysicalHeightPixels": null,
        "streamId": 8
    },
    {
        "tileId": 8,
        "localTile": false,
        "localTileStarted": false,
        "isContent": false,
        "active": false,
        "paused": false,
        "poorConnection": false,
        "boundAttendeeId": "1f4df155-b1b9-10e8-530a-9bb2d2dc4cce",
        "boundExternalUserId": "17908#a64dada8-c929-491b-9ca9-63a33cfe9b9e",
        "boundVideoStream": {},
        "boundVideoElement": null,
        "nameplate": null,
        "videoStreamContentWidth": 640,
        "videoStreamContentHeight": 480,
        "videoElementCSSWidthPixels": null,
        "videoElementCSSHeightPixels": null,
        "devicePixelRatio": 1,
        "videoElementPhysicalWidthPixels": null,
        "videoElementPhysicalHeightPixels": null,
        "streamId": 10
    },
    {
        "tileId": 15,
        "localTile": false,
        "localTileStarted": false,
        "isContent": false,
        "active": false,
        "paused": false,
        "poorConnection": false,
        "boundAttendeeId": "9ec47026-4ebe-071f-c5e9-dcfd86ede26b",
        "boundExternalUserId": "301335#b8f4a205-b09f-48bb-a266-71374f94d33a",
        "boundVideoStream": {},
        "boundVideoElement": null,
        "nameplate": null,
        "videoStreamContentWidth": 640,
        "videoStreamContentHeight": 480,
        "videoElementCSSWidthPixels": null,
        "videoElementCSSHeightPixels": null,
        "devicePixelRatio": 1,
        "videoElementPhysicalWidthPixels": null,
        "videoElementPhysicalHeightPixels": null,
        "streamId": 22
    },
    {
        "tileId": 19,
        "localTile": false,
        "localTileStarted": false,
        "isContent": false,
        "active": false,
        "paused": false,
        "poorConnection": false,
        "boundAttendeeId": "d9e9adcf-08f7-e5a4-97a1-90990e1aa63d",
        "boundExternalUserId": "87683#70909359-a6f6-4bb5-8b47-1a8b53af0cf3",
        "boundVideoStream": {},
        "boundVideoElement": null,
        "nameplate": null,
        "videoStreamContentWidth": 640,
        "videoStreamContentHeight": 480,
        "videoElementCSSWidthPixels": null,
        "videoElementCSSHeightPixels": null,
        "devicePixelRatio": 1,
        "videoElementPhysicalWidthPixels": null,
        "videoElementPhysicalHeightPixels": null,
        "streamId": 26
    }
]
```

getRemoteVideoSourcesResponse (does include `357127#89202bb9-6bfa-4de7-97e8-c8e561bfa431`):
```
[
    {
        "attendee": {
            "attendeeId": "b51e62cd-4e7f-b4c2-8ef4-51b2f3f90d47",
            "externalUserId": "357127#89202bb9-6bfa-4de7-97e8-c8e561bfa431"
        }
    },
    {
        "attendee": {
            "attendeeId": "d9e9adcf-08f7-e5a4-97a1-90990e1aa63d",
            "externalUserId": "87683#70909359-a6f6-4bb5-8b47-1a8b53af0cf3"
        }
    },
    {
        "attendee": {
            "attendeeId": "9ec47026-4ebe-071f-c5e9-dcfd86ede26b",
            "externalUserId": "301335#b8f4a205-b09f-48bb-a266-71374f94d33a"
        }
    },
    {
        "attendee": {
            "attendeeId": "7433d1c8-48e2-72f2-b4cc-dd59eae0f883",
            "externalUserId": "85641#5549f451-1bf8-49a7-a5a2-a22836a81471"
        }
    },
    {
        "attendee": {
            "attendeeId": "fd7e723e-3185-28e8-5f77-da50c4165bf7",
            "externalUserId": "357111#cca746c4-fea3-47e5-b822-da7e2869f98a"
        }
    },
    {
        "attendee": {
            "attendeeId": "1f4df155-b1b9-10e8-530a-9bb2d2dc4cce",
            "externalUserId": "17908#a64dada8-c929-491b-9ca9-63a33cfe9b9e"
        }
    }
]
```

### Browser console logs

Haven't managed to reproduce this with the INFO-level logs enabled yet. If we can I'll add a comment with the logs included.

**Comment by ltrung** [comment]
Do you use Simulcast by any chance?

**Comment by ltrung** [comment]
There is a blank tile with the paused state set to true (tileId=6) which seems to indicate that the priority downlink policy does not subscribe to that subscriber due to bandwidth and instead just create a blank video tile. Did you receive any `tileWillBePausedByDownlinkPolicy` event?

**Comment by husaindevelop** [comment]
Soon we experience a problem, you are reminded and undermentioned lose no time connecting you. Here before you with another problem soliciting your guidance for its way out. That was only in the ligher vein, we do remember you and valued support you have provided. 

The current problem that we have encountered is the dimension of video-frame enhances proportionately and not discretely. For instance the size we get is 400px x 250 and enhances proportionately to 800 x 500 and not discretely like 400 x 800. To be more precise, we need the length and breadth be varied at discretion. Sure this problem replenishes grist to grind

**Comment by hensmi-amazon** [comment]
I'm seeing some oddities in this call, perhaps explanation (in addition to logs) may help us narrow down the issue.  I'm seeing that in this call there are about 8 attendees, and then 15 minutes in they all disconnect.  Then around 8 new attendees join a few seconds later.  Each external user ID prefix matched ones before the event.  Additionally most connecting IPs of the new attendees matched ones in previous set, the only difference was that there was a version bump of the JS SDK.  Was there some sort of remote update during this call?

**Comment by kg-jcaron** [comment]
We're not using priority downlink policy (unless it's enabled by default?) or simulcast. I'll add logging on `tileWillBePausedByDownlinkPolicy` just incase though.

In terms of the users all reconnecting at once, we have functionality to switch from a stable build of our software to an experimental one (which happens to use a newer sdk version at the moment) and reconnect all the users which is what happened here (it forces a refresh for the users, and refetches different version of the javascript, etc.). We've seen the same issue without using this, but it seems to only happen when a whole bunch of users join at the same time which this triggers. We have a waiting room feature to join users after the host starts the meeting, and that flow can trigger this as well since they all join the meeting at once.

We add a random suffix to the end of our user ids since we'd previously had some issues with deleting an attendee in one meeting, then creating an attendee in a different meeting too quickly if the external user id was the same between them, so we do this to ensure they're unique. We've been doing this for a long time though so I don't imagine it's what's causing any issues?

Let me know if you think any of that sounds like it could be related though and we can try to change how we handle it. Thanks!

**Comment by hensmi-amazon** [comment]
Just to follow up there.  Wanted to confirm that you are intentionally using `pauseReceivingStream`.

Also in the aforementioned example, was the missing tile post reconnect? `357127#89202bb9-6bfa-4de7-97e8-c8e561bfa431` corresponds to an attendee post reconnect.  Also was the tile missing for all participants? Or one specific (could you mention which one?).

**Comment by kg-jcaron** [comment]
Yeah we do intentionally call `pauseReceivingStream` to pause streams we aren't rendering depending on the layout, but our logs don't have any records of us calling that in this case, and we have some test code that recalculates that logic which didn't resolve any of the issues in this case.

 Yes `357127#89202bb9-6bfa-4de7-97e8-c8e561bfa431` is the tile which was missing after the reconnect.
 
 All users except one could see the tile correctly.
 
 The user who couldn't see it should start with a prefix of `42174#` and has a chime id of `3e23844b-cd9c-b3c4-d403-7c1e37490c15`. We don't log the random suffixes in our database and I didn't think to grab the data earlier, but hopefully this is still enough.

**Comment by hensmi-amazon** [comment]
Hi @kg-jcaron have you been able to reproduce the issue with client logs? Do you continue to see the issue?
