### ISSUE TITLE
Video not initializing in chrome version 95 in mobile

### ISSUE THREAD

**Issue by husaindevelop** [aws/amazon-chime-sdk-js#1818]
Be informed, we are using amazon chime sdk single js for our one-to-one video chat application.  Its working perfectly fine in EDGE, chrome browser in laptop and safari in mobile. But chrome mobile version 95 does not seem to initialize video. at all Though it asks for permission for microphone and webcam permission, but video never initializes.  Here is the entire code:
 ```
(async () => {
            const Logger = new ChimeSDK.ConsoleLogger('MyLogger', ChimeSDK.LogLevel.INFO);

try {
    //const transformer = await ChimeSDK.VoiceFocusDeviceTransformer.create({}, { logger });
    const isVoiceFocusSupported = await ChimeSDK.VoiceFocusDeviceTransformer.isSupported();
    alert (isVoiceFocusSupported)
    
} catch (e) {
    console.error(e);
    
  // Will only occur due to invalid input or transient errors (e.g., network).
  isVoiceFocusSupported = false;
  alert (isVoiceFocusSupported);
}
           
        const isVoiceFocusSupported = await ChimeSDK.VoiceFocusDeviceTransformer.isSupported();
           this.deviceController = new ChimeSDK.DefaultDeviceController(Logger, { enableWebAudio: isVoiceFocusSupported });
            const transformer = await ChimeSDK.VoiceFocusDeviceTransformer.create({}, { logger: Logger });
            const meetingResponse = {"Meeting":<?php if ($_GET ['met1']) echo $_SESSION ['met1'];else echo $_SESSION ['met']; ?>};
            const attendeeResponse = {"Attendee":<?php echo json_encode($attendee) ?>};
            const configuration = new ChimeSDK.MeetingSessionConfiguration(meetingResponse, attendeeResponse);
            const meetingSession = new ChimeSDK.DefaultMeetingSession(configuration, Logger, deviceController);
            const audioInputDevices = await meetingSession.audioVideo.listAudioInputDevices();
            const audioOutputDevices = await meetingSession.audioVideo.listAudioOutputDevices();
            const videoInputDevices = await meetingSession.audioVideo.listVideoInputDevices();
            meetingSession.audioVideo.chooseVideoInputQuality(960,540,15,1400);
            await meetingSession.audioVideo.chooseVideoInputDevice(videoInputDevices[0].deviceId);
            await meetingSession.audioVideo.chooseAudioInputDevice(audioInputDevices[0].deviceId);
            const chosenAudioInput = audioInputDevices[0].deviceId;    
            const vfDevice = await transformer.createTransformDevice(chosenAudioInput);
            if (audioOutputDevices[0]) {
            await meetingSession.audioVideo.chooseAudioOutputDevice(audioOutputDevices[0].deviceId);
            }
const deviceToUse = vfDevice || chosenAudioInput;
await deviceController.chooseAudioInputDevice(deviceToUse);
alert (vfDevice);

if (vfDevice) {
  console.log('Amazon Voice Focus enabled');
}

            meetingSession.audioVideo.startVideoPreviewForVideoInput(document.getElementById('self-video'));
            const audioElement = document.getElementById('audio-preview');
            meetingSession.audioVideo.bindAudioElement(audioElement);
            const videoElement = document.getElementById('video-prime');
            const videoElement1 = document.getElementById('video-preview1');

            

            const observer = {
                audioVideoDidStart: () => {
                    console.log('Started');
                },
                videoTileDidUpdate: tileState => {
                    if (!tileState.boundAttendeeId || tileState.localTile || tileState.isContent) {
                           
                        return;
                        
                    }
                    //console.log('Start video');
                    
    const videoElement = document.getElementById('video-prime');
   const videoElement1 = document.getElementById('video-preview1');
   const videoElement2 = document.getElementById('video-preview2');
   
   const tiles = meetingSession.audioVideo.getAllVideoTiles();

tiles.forEach(tile => {
    let tileId = tile.tileState.tileId;
    
    if (tileId=="2") { meetingSession.audioVideo.bindVideoElement(tileId, videoElement);}
    if (tileId=="3") { meetingSession.audioVideo.bindVideoElement(tileId, videoElement);}
    if (tileId=="4") { meetingSession.audioVideo.bindVideoElement(tileId, videoElement);}
    if (tileId=="5") { meetingSession.audioVideo.bindVideoElement(tileId, videoElement);}
    
    //$('#vi').html (tileId);                 
   
});
                    

                }
            };

            meetingSession.audioVideo.addObserver(observer);
            meetingSession.audioVideo.start();
            meetingSession.audioVideo.startLocalVideoTile();
        }) ();
```

Do guide us as how we solve this issue.

**Comment by devalevenkatesh** [comment]
Thanks for reporting the issue.

I see that you make below calls one after the other:
```
meetingSession.audioVideo.start();
meetingSession.audioVideo.startLocalVideoTile();
```

With this, the `startLocalVideoTile` can get called before the JS SDK actually starts the meeting session successfully and hence might not start the local video as expected.

Few suggestion to see if this fixes the problem:
1. Call the `meetingSession.audioVideo.startLocalVideoTile();` after you receive an update in `audioVideoDidStart` observer. `audioVideoDidStart` is triggered once the meeting session is successfully established.
2. Like we do on the meeting demo, call the `meetingSession.audioVideo.startLocalVideoTile();` on the button click. The button appears once meeting session is established.

If above does not solve your issue, please provide browser console logs to troubleshoot further. Request you to please follow the "Bug form template" while creating the issue.

**Comment by ltrung** [comment]
What Chrome mobile version do you use? Is that iOS or Android?

**Comment by husaindevelop** [comment]
Its Android - Chrome version 96.  We are using startVideoPreviewForVideoInput for self-tile view. I tried implementing all the options said by you. Lastly i created button click event as well to initiate the tile, it does work in laptop and safari mobile but not in chrome mobile.  I tried checking it in my laptop's chrome browser tools in- built mobile emulator, it worked fine there too, but not in chrome mobile. Here is the url of our chat: https://mbracecloud.com/video_chat_n.php?v=Yes  Please check.

**Comment by husaindevelop** [comment]
Please check the logs that is outputted on testing the sdk on mobile device as asked by you

```
DefaultAudioMixController.js:64 Uncaught (in promise) Error: Cannot select audio output device. This browser does not support setSinkId.
    at t.default.<anonymous> (DefaultAudioMixController.js:64)
    at Generator.next (<anonymous>)
    at DefaultAudioMixController.js:10
    at new Promise (<anonymous>)
    at i (DefaultAudioMixController.js:6)
    at t.default.bindAudioDevice (DefaultAudioMixController.js:58)
    at r.<anonymous> (DefaultDeviceController.js:1385)
    at Generator.next (<anonymous>)
    at DefaultDeviceController.js:10
    at new Promise (<anonymous>)
(anonymous) @ DefaultAudioMixController.js:64
(anonymous) @ DefaultAudioMixController.js:10
i @ DefaultAudioMixController.js:6
bindAudioDevice @ DefaultAudioMixController.js:58
(anonymous) @ DefaultDeviceController.js:1385
(anonymous) @ DefaultDeviceController.js:10
i @ DefaultDeviceController.js:6
bindAudioOutput @ DefaultDeviceController.js:1380
(anonymous) @ DefaultDeviceController.js:475
(anonymous) @ DefaultDeviceController.js:10
i @ DefaultDeviceController.js:6
chooseAudioOutputDevice @ DefaultDeviceController.js:472
chooseAudioOutputDevice @ DefaultAudioVideoFacade.js:258
(anonymous) @ video_chat_n.php?v=Yes:79
await in (anonymous) (async)
(anonymous) @ video_chat_n.php?v=Yes:147
```

**Comment by ltrung** [comment]
Did you call `chooseAudioOutputDevice`? It seems the browsers in Android does not support changing select audio device and thus, it errors out.

**Comment by husaindevelop** [comment]
Yes used chooseAudioOutputDevice. Can we comment it out ? So that it can start working.

**Comment by ltrung** [comment]
You should be able to use `supportsSetSinkId` API (https://github.com/aws/amazon-chime-sdk-js/blob/main/src/browserbehavior/DefaultBrowserBehavior.ts#L274) to check whether the browser supports it.

**Comment by devalevenkatesh** [comment]
We also have an FAQ on the `setSinkId` support: 
https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html#i-am-getting-cannot-select-audio-output-device-this-browser-does-not-support-setsinkid-error-on-the-browser-console-is-this-a-known-issue

The Android Chrome 96 does not support it and hence the error. 
https://caniuse.com/?search=setsinkid

You should use `chooseAudioOutputDevice` and `listAudioOutputDevice` APIs only when it is supported. Check [here](https://github.com/aws/amazon-chime-sdk-js/blob/main/demos/browser/app/meetingV2/meetingV2.ts#L2556-L2591) in the sample meetingV2 demo for JS SDK.

**Comment by husaindevelop** [comment]
So does Chrome 97, Yes, commenting out chooseAudioOutputDevice and listAudioOutputDevice when it is not supported initializes the video successfully. Shall use setSinkId to check whether support exists or not before using both these apis.

**Comment by devalevenkatesh** [comment]
Unless Android Chrome supports it we cannot do anything on our side.

Thanks for confirmation though! I am closing this issue now. Feel free to open new issue if you face any further issues.
