### ISSUE TITLE
Need to integrate Media Recording in demos/browser/meeting

### ISSUE THREAD

**Issue by gauravhanda25** [aws/amazon-chime-sdk-js#182]
### Need to add media recording feature in demos/browser/meeting

*For example: User wants to start pause and end media recording.*

### How can the documentation be improved to help your use case?

*For example: Include a section where example of Media recording is already explained how to use.*

**Comment by gauravhanda25** [comment]
@agowatch @dylonChime @aburnson   I have used WebMMediaRecoding in demos/browser/meeting/app/meeting.ts to start and stop recording. Do I need to add any server side code to save it anywhere in s3 or will it be saved automatically ?

**Comment by koni-a** [comment]
@gauravhanda25 do we have any sample to integrate Start Record and Stop Record

**Comment by gauravhanda25** [comment]
> @gauravhanda25 do we have any sample to integrate Start Record and Stop Record

Sample is not there but a test case is available which is helpful to implement WebMMediaRecording class in meeting.ts

**Comment by vidya-mohan** [comment]
@gauravhanda25 @Aarondorn2 @koni-a we have release a demo to do client side recording. You can find our sample code here: https://github.com/aws-samples/amazon-chime-sdk-recording-demo

**Comment by Aarondorn2** [comment]
Thank you!

**Comment by Lestat86** [comment]
> @agowatch @dylonChime @aburnson I have used WebMMediaRecoding in demos/browser/meeting/app/meeting.ts to start and stop recording. Do I need to add any server side code to save it anywhere in s3 or will it be saved automatically ?

Could you share how you did that? As far as i'm concerned the demo they published yesterday records the video on s3, but there is no mention of recording it on the client system directly

**Comment by bajarang-agarwal** [comment]
@vidya-mohan Thank you for sharing the demo. I was going through with the specified demo but it looks this we need to deploy on AWS Cloud9, Create ECR repo etc. but how we can run/deploy this demo locally and file get save in S3 bucket.

If you can provide some ideas/help with this then I think it will help a lot to different people.

@gauravhanda25 Do you able to save the file on S3 using WebMMediaRecoding, if yes then can you provide some detail that how you able to do it. 

I think it will be a good idea if we can add a recording in this sdk demo itself.

**Comment by koni-a** [comment]
Hi Team,

Where should I get a meeting URL, to pass when the recording starts.

Below are the parameters we are getting when the meeting created

public class Meeting
{
    public Meeting();
    public MediaPlacement MediaPlacement { get; set; } 
    public string MediaRegion { get; set; }  
    public string MeetingId { get; set; }
}

public class MediaPlacement
{
    public MediaPlacement();

    public string AudioFallbackUrl { get; set; } 
    public string AudioHostUrl { get; set; } 
    public string ScreenDataUrl { get; set; } 
    public string ScreenSharingUrl { get; set; } 
    public string ScreenViewingUrl { get; set; } 
    public string SignalingUrl { get; set; } 
    public string TurnControlUrl { get; set; }
}
can u please tell me the steps.

Thanks

> @gauravhanda25 @Aarondorn2 @koni-a we have release a demo to do client side recording. You can find our sample code here: https://github.com/aws-samples/amazon-chime-sdk-recording-demo 
@vidya-mohan Where should I get a meeting URL, to pass when the recording starts.

check below image

https://github.com/aws-samples/amazon-chime-sdk-recording-demo/blob/master/resources/postman-app-start-recording.png

Below are the parameters we are getting when the meeting created

public class Meeting
{
    public Meeting();
    public MediaPlacement MediaPlacement { get; set; } 
    public string MediaRegion { get; set; }  
    public string MeetingId { get; set; }
}

public class MediaPlacement
{
    public MediaPlacement();

    public string AudioFallbackUrl { get; set; } 
    public string AudioHostUrl { get; set; } 
    public string ScreenDataUrl { get; set; } 
    public string ScreenSharingUrl { get; set; } 
    public string ScreenViewingUrl { get; set; } 
    public string SignalingUrl { get; set; } 
    public string TurnControlUrl { get; set; }
}
can u please tell me the steps.

Thanks

**Comment by sidharth-sid** [comment]
> @gauravhanda25 @Aarondorn2 @koni-a we have release a demo to do client side recording. You can find our sample code here: https://github.com/aws-samples/amazon-chime-sdk-recording-demo

@vidya-mohan I'm able to find the mp4 of the record in the S3 bucket. But the video has no content it plays but no audio or video (screen share).
