### ISSUE TITLE
ERROR unable to get video and device for constraints -  error only in specific devices suddenly..PFA

### ISSUE THREAD

**Issue by abhinavOmni** [aws/amazon-chime-sdk-js#1829]
### What happened and what did you expect to happen?

While joining the meeting form chrome browser, it showing this error.

### Have you reviewed our existing documentation?

- [X] GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [X] FAQs [page](https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html)
- [X] README [page](https://github.com/aws/amazon-chime-sdk-js#amazon-chime-sdk-for-javascript)
- [X] Feature-specific [guides](https://github.com/aws/amazon-chime-sdk-js#guides)

### Reproduction steps

![imgpsh_fullsize_anim (4)](https://user-images.githubusercontent.com/71629015/143203991-8a07aebb-31af-4e4b-94a2-6eae29352b28.png)
![imgpsh_fullsize_anim (3)](https://user-images.githubusercontent.com/71629015/143203999-0ec57678-6365-4f49-af4b-12f8af5c4fad.png)
![imgpsh_fullsize_anim (2)](https://user-images.githubusercontent.com/71629015/143204000-8e040190-bde5-4da8-85f3-e8db05cedeca.png)
![imgpsh_fullsize_anim (1)](https://user-images.githubusercontent.com/71629015/143204006-79e2d4f1-131c-4cef-9d00-e5285cf2b651.png)
![imgpsh_fullsize_anim](https://user-images.githubusercontent.com/71629015/143204007-d1f8ef9d-80f5-4b8e-9ef6-1dd3d99134f1.png)
![imgpsh_fullsize_anim (5)](https://user-images.githubusercontent.com/71629015/143204060-a44197a6-fe02-45b5-a6c1-283eb921e653.png)

### Amazon Chime SDK for JavaScript version

  "amazon-chime-sdk-js": "^2.7.0",    "aws-sdk": "^2.816.0",

### What browsers are you seeing the problem on?

chrome 96 and above and chrome incognito

### Browser version

chrome 96 and above

### Browser console logs

![imgpsh_fullsize_anim (1)](https://user-images.githubusercontent.com/71629015/143204151-a2a08742-5b51-4f07-8a25-e4468011412b.png)
![imgpsh_fullsize_anim (4)](https://user-images.githubusercontent.com/71629015/143204169-1327a072-a74b-4a02-a73c-624f00ffc58a.png)

**Comment by ltrung** [comment]
@abhinavOmni What is the OS in this case? The error is thrown by the browser when we try to get the video stream.
Can you try to manually call `getUserMedia` in developer console and see whether it succeeds?
```
await navigator.mediaDevices.getUserMedia({video: true});
```

**Comment by abhinavOmni** [comment]
![image](https://user-images.githubusercontent.com/71629015/143815323-f74554b8-8489-401f-9b02-8cd875e59764.png

this is the error getting when running await navigator.mediaDevices.getUserMedia({video: true});

PLS SUGGEST HOW TO FIX THE ISSUE

OS: WINDOWS 10 and CHROME 96

**Comment by ltrung** [comment]
Another sample to try is the webRTC sample app https://webrtc.github.io/samples/src/content/devices/input-output/ but if calling `getUserMedia` directly fails then I think it is an issue with either the device or a browser or OS permission setting. Also could you make sure you do not have another app or browser access the camera at the same time?

**Comment by abhinavOmni** [comment]
Yes tried checking it nothing working.. Whats the solution to fix from coding ? pls suggest

**Comment by ltrung** [comment]
Could you check to see whether you enable camera in Windows (https://support.microsoft.com/en-us/windows/manage-app-permissions-for-your-camera-in-windows-87ebc757-1f87-7bbf-84b5-0686afb6ca6b#WindowsVersion=Windows_10)?

**Comment by abhinavOmni** [comment]
tried checking , everything is enabled already..

**Comment by michhyun1** [comment]
@abhinavOmni  I think what Trung meant to say is to double check that no other video stream is active when you call this API.

**Comment by abhinavOmni** [comment]
@michhyun1  @ltrung  do we have any Method to start the audio call only.. i see Amazon chime has only  meetingSession.audioVideo.start(); and not only audio call. how to only start audio calls only without making camera splash on..pls guide.i think i can fix atleast with this approach..

**Comment by devalevenkatesh** [comment]
@abhinavOmni we do not have any specific method to start audio only meeting but to workaround the permission you can try below steps:

```js
// First request only audio permissions and no video permissions. JS SDK by default requests audio and video permissions.
meetingSession.audioVideo.setDeviceLabelTrigger(
    async (): Promise<MediaStream> => {
      const stream = await navigator.mediaDevices.getUserMedia({ audio: true });
      return stream;
    }
);

// Choose only audio input device.
meetingSession.audioVideo.chooseAudioInputDevice('deviceID');

// Make sure you disable video related API calls if video permissions are not requested.
```

The `NotReadableError` can have multiple issues. [MDN Docs](https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getUserMedia#exceptions)

If you have tried `await navigator.mediaDevices.getUserMedia({video: true});` normally in a window where there is no app / other browser window running which has access to the camera then this looks like a device specific issue.

- Is this a wide spread device specific issue pertaining to a single device or how?
- Are there any other devices, users who are able to run the app fine?
