### ISSUE TITLE
Further guidance new EchoReduction API

### ISSUE THREAD

**Issue by chuckntaylor** [aws/amazon-chime-sdk-js#1833]
### What are you trying to do?
I am trying to make use of the new EchoReduction API.

On the server side I am using `aws-sdk`(js) v.2.1036.0
My code is as follows on the server:
```ts
import { Endpoint, ChimeSDKMeetings } from 'aws-sdk'
...
const chime = new ChimeSDKMeetings({ region: 'us-east-1' })
...
// =========== CREATE A MEETING ================
  const createNewMeeting = async () => {
    // Use a ULID for the client request token to ensure that any request retries
    // do not create multiple meetings.
    const request = {
      ClientRequestToken: ULID(),
      ExternalMeetingId: meetingName,
      MediaRegion: mediaRegion,
      MeetingFeatures: {
        Audio: {
          EchoReduction: 'AVAILABLE',
        },
      },
    }

    try {
      let newMeeting = await chime.createMeeting(request).promise()
      console.log(newMeeting)
      return newMeeting
    } catch (err) {
      log.error(err)
      return null
    }
  }

  // =========== CREATE AN ATTENDEE ================
  const createAttendee = async (meeting) => {

    const externalUserId = ulid || ULID()

    const attendee = await chime
      .createAttendee({
        // pass in the meeting ID received from AWS Chime in previous step
        MeetingId: meeting.Meeting.MeetingId,
        ExternalUserId: externalUserId,
      })
      .promise()
    console.log(attendee)
    return attendee
  }
...
```

On the frontend, I followed the similar example from #1821 using `amazon-chime-sdk-js` v2.23.0. However, I get an error before I can even start to make use of the returned `VoiceFocusDeviceTransformer`
```ts
const spec: VoiceFocusSpec = {
        name: 'ns_es',
      }
      try {
// This throws an error
        this.state.transformer = await VoiceFocusDeviceTransformer.create(
          spec,
          { logger: consoleLogger },
          undefined,
          meeting,
          attendee
        )
        this.state.isVoiceFocusSupported = this.state.transformer.isSupported()
      } catch (e) {
        console.error(e)
        this.state.isVoiceFocusSupported = false
      }
```

The error I am seeing in the console reads: `Echo Reduction requested but not enabled`

On the server side, I logged out the meeting and attendee objects.
```
{
  Meeting: {
    MeetingId: '6ac8a218-df6b-4c85-a0ab-47545bc20706',
    ExternalMeetingId: '12345',
    MediaRegion: 'ca-central-1',
    MediaPlacement: {
      AudioHostUrl: 'f65998e0242e1c97c49c3561de79fb14.k.m3.cc1.app.chime.aws:3478',
      AudioFallbackUrl: 'wss://haxrp.m3.cc1.app.chime.aws:443/calls/6ac8a218-df6b-4c85-a0ab-47545bc20706',
      SignalingUrl: 'wss://signal.m3.cc1.app.chime.aws/control/6ac8a218-df6b-4c85-a0ab-47545bc20706',
      TurnControlUrl: 'https://ccp.cp.ue1.app.chime.aws/v2/turn_sessions',
      ScreenDataUrl: 'wss://bitpw.m3.cc1.app.chime.aws:443/v2/screen/6ac8a218-df6b-4c85-a0ab-47545bc20706',
      ScreenViewingUrl: 'wss://bitpw.m3.cc1.app.chime.aws:443/ws/connect?passcode=null&viewer_uuid=null&X-BitHub-Call-Id=6ac8a218-df6b-4c85-a0ab-47545bc20706',
      ScreenSharingUrl: 'wss://bitpw.m3.cc1.app.chime.aws:443/v2/screen/6ac8a218-df6b-4c85-a0ab-47545bc20706',
      EventIngestionUrl: null
    }
  }
}
{
  Attendee: {
    ExternalUserId: '01FNANBP5SAXCJ7QMYXRCYTCEB',
    AttendeeId: '3d395476-c341-3a3e-4ab1-0d4954ddba2f',
    JoinToken: 'M2QzOTU0NzYtYzM0MS0zYTNlLTRhYjEtMGQ0OTU0ZGRiYTJmOjhlNWE1M2ZhLTMyZmQtNDI4My1iODQ1LTkwMzA0YjQ4NmY3ZQ'
  }
}
```

It is true that I'm not seeing anything that would imply that there are these MeetingFeatures. Am I missing something obvious?

### How can the documentation be improved to help your use case?

Include a section with a bit more details on how to setup the Echo Reduction feature. This should probably include information for the frontend and backend as they go hand in hand in this case.

### What documentation have you looked at so far?

Amazon Chime SDK Developer Guide, GitHub pull request #1821 , release notes for v2.23.0, API docs

**Comment by chuckntaylor** [comment]
*Update* I have this working now.

On the server, I was setting:
```ts
chime.endpoint = new Endpoint(process.env.CHIME_ENDPOINT || 'https://service.chime.aws.amazon.com')
```

If I get rid of this line, everything seems to work now.

I have to say that this echo reduction is VERY effective. I ran two instances of the meeting from the same computer, and there is absolutely no echo. Congrats to the hard working devs!

**Comment by chuckntaylor** [comment]
Hello again. I just wanted to share this morning that I logged out the meeting and attendee objects again on the server after having removed the endpoint setting, and now I see the `MeetingFeatures` property

```
{
  Meeting: {
    MeetingId: '56e925d5-feef-4750-b915-023a17eb2713',
    MeetingHostId: null,
    ExternalMeetingId: '12345',
    MediaRegion: 'ca-central-1',
    MediaPlacement: {
      AudioHostUrl: '4bda81dd25dd37d7567cc2833e36a32f.k.m3.cc1.app.chime.aws:3478',
      AudioFallbackUrl: 'wss://haxrp.m3.cc1.app.chime.aws:443/calls/56e925d5-feef-4750-b915-023a17eb2713',
      SignalingUrl: 'wss://signal.m3.cc1.app.chime.aws/control/56e925d5-feef-4750-b915-023a17eb2713',
      TurnControlUrl: 'https://2713.cell.us-east-1.meetings.chime.aws/v2/turn_sessions',
      ScreenDataUrl: 'wss://bitpw.m3.cc1.app.chime.aws:443/v2/screen/56e925d5-feef-4750-b915-023a17eb2713',
      ScreenViewingUrl: 'wss://bitpw.m3.cc1.app.chime.aws:443/ws/connect?passcode=null&viewer_uuid=null&X-BitHub-Call-Id=56e925d5-feef-4750-b915-023a17eb2713',
      ScreenSharingUrl: 'wss://bitpw.m3.cc1.app.chime.aws:443/v2/screen/56e925d5-feef-4750-b915-023a17eb2713',
      EventIngestionUrl: null
    },
    MeetingFeatures: { Audio: [Object] }
  }
}
{
  Attendee: {
    ExternalUserId: '01FNBQCEJB61NQTBX4BPJSFA6R',
    AttendeeId: '29710db3-be2a-58d3-2f77-b037d696a0a0',
    JoinToken: 'Mjk3MTBkYjMtYmUyYS01OGQzLTJmNzctYjAzN2Q2OTZhMGEwOjEwNzYzNjA5LTU4MzItNGE1ZS04ZDdkLTNlMjA0YzE3NTM4Yg'
  }
}
```

I'm not sure why the endpoint setting caused the problem - no errors were thrown at the time. I just noticed in the discussion of pull #1821 there was some chat regarding whether or not setting the endpoint was necessary, and so I tried removing it. I must have had it in there from another example in the docs.

Lastly, I am looking for information regarding *how* the EchoReduction is processed. Does this happen on AWS's end, or is it on the client like noise reduction? I understand that it comes at an additional cost, and really want to make it the default for my application. And so, I am curious to know - where as noise reduction is processed on the client and is dependant on the client hardware for the `model complexity`, does EchoReduction take place purely on Chime's end? Is it reasonable to assume that as long as the device supports `webAudio`, that this should work? Thank you!

**Comment by ltrung** [comment]
@chuckntaylor Glad that the feature works well for you.
So the new Echo ability feature is only available in Chime Meeting SDK (i.e., our sdk with regional endpoints) and not available in the regular Chime SDK (with global endpoint) and that endpoint line will set the endpoint to global.
EchoReduction works the same way as Voice Focus and is processed on the client and thus, dependent on the client hardware as well as needs support for `webAudio`.

**Comment by chuckntaylor** [comment]
Thank you kindly for your response. I really like the feature and it works great! Just a followup question to clarify my understanding a bit further.

My server-side code is written in typescript so I was quickly able to see that I needed to be calling `createMeeting` on `ChimeSDKMeetings` instead of `Chime` in order to have the typings for the `MeetingFeatures` properties on the `CreateMeetingRequest`. Until now, I always imported `Chime` from `aws-sdk`.

My question is, where is the separation between these two / why are there two? I see Chime contains all the same API Actions as ChimeSDKMeetings (plus several more). So I was wondering why they are separate, and why Chime.createMeeting() does not allow for `MeetingFeatures`?

**Comment by ltrung** [comment]
@chuckntaylor The previous global chime sdk contains all of our APIs from meetings, messagings, identity, and Chime Application. and thus, we recently migrate to a more specific name space (Chime Meeting SDK, Chime Messaging SDK, and Chime Identity SDK) so that its easier for developer to find the API they need. You can find more info in the [migration doc](https://docs.aws.amazon.com/chime/latest/dg/meeting-namespace-migration.html).
Another benefit to migrate to the more specific Chime Meeting SDK is that it supports regionalization and allow you to select regions other than `us-east-1`.

**Comment by chuckntaylor** [comment]
Thanks for the clarification!

**Comment by ltrung** [comment]
Updated the guide in PR https://github.com/aws/amazon-chime-sdk-js/pull/1848 to mention the need to use the regional meeting SDK so close this issue for now. Feel free to reopen if you have additional question.
