### ISSUE TITLE
How can I set nameplate?

### ISSUE THREAD

**Issue by sanjitkung** [aws/amazon-chime-sdk-js#1834]
### What are you trying to do?

I'm trying to set nameplate on video element. I can see there is nameplate property on TileState object, which is null. How can I set the nameplate. Does I have to pass this parameter from the server while calling CreateAttendee endpoint? 

### How can the documentation be improved to help your use case?
Include instruction to add nameplate to tile.

### What documentation have you looked at so far?
AWS Chime PHP SDK guide, AWS Chime JS client API Overview

**Comment by ltrung** [comment]
@sanjitkung I think that `nameplate` property is not actually used. Do you just want to get the name of the attendee from `TileState`. If so you can use the property `boundExternalUserId` instead.

**Comment by sanjitkung** [comment]
Thanks for clarification.
