### ISSUE TITLE
createMediaCapturePipeline: Unexpected key 'ChimeSdkMeetingConfiguration'

### ISSUE THREAD

**Issue by LouisMx** [aws/amazon-chime-sdk-js#1835]
### What happened and what did you expect to happen?

Hi community,

I implemented the mediaCapturePipeline. It works fine!
But, If I add the "ChimeSdkMeetingConfiguration" parameters to my capture settings, I get this error:
`UnexpectedParameter: Unexpected key 'ChimeSdkMeetingConfiguration' found in params`

### Have you reviewed our existing documentation?

- [X] GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [X] FAQs [page](https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html)
- [X] README [page](https://github.com/aws/amazon-chime-sdk-js#amazon-chime-sdk-for-javascript)
- [X] Feature-specific [guides](https://github.com/aws/amazon-chime-sdk-js#guides)

### Reproduction steps

Here are my settings:
```
const captureRequest = {
    "SourceType": "ChimeSdkMeeting",
    "SourceArn": "arn:aws:chime::" + awsAccountId + ":meeting:" + meetingId,
    "SinkType": "S3Bucket",
    "SinkArn": "arn:aws:s3:::" + mediaCaptureBucket + "/captures/" + body.eventID,
    "ChimeSdkMeetingConfiguration": {
        "SourceConfiguration": {
            "SelectedVideoStreams": {
                "ExternalUserIds": [identitySub]
            }
        },
        "ArtifactsConfiguration": {
            "Audio": {
                "MuxType": "AudioWithActiveSpeakerVideo"
            },
            "Video": {
                "State": "Disabled",
            },
            "Content": {
                "State": "Disabled",
            }
        }
    }
};
try {
    const captureInfo = await chime
        .createMediaCapturePipeline(captureRequest)
        .promise();
} catch (err) {
    console.log(err);
}
```

If I remove the ChimeSdkMeetingConfiguration node it works.

I tried with AttendeeIds, ExternalUserIds, without Artifacts, etc...

### Amazon Chime SDK for JavaScript version

2.20.1

### What browsers are you seeing the problem on?

Lambda Node.js 14.x x86_64

### Browser version

Chrome Version 96.0.4664.45 64bits

### Meeting and Attendee ID Information.

Attendee ID eb598a71-3d00-f98b-b23e-680994cb5f07
ExternalUser ID 10021dc7-9c4c-4edd-9cd6-12763c7a6851
Meeting ID 23f80018-8d4c-45f4-9efb-639f01ba0706

### Browser console logs

2021-11-25T23:24:22.965Z	a0de4eea-3f7a-4588-9ffb-8e2efee57d21	INFO	UnexpectedParameter: Unexpected key 'ChimeSdkMeetingConfiguration' found in params
    at ParamValidator.fail (/var/runtime/node_modules/aws-sdk/lib/param_validator.js:50:37)
    at ParamValidator.validateStructure (/var/runtime/node_modules/aws-sdk/lib/param_validator.js:77:14)
    at ParamValidator.validateMember (/var/runtime/node_modules/aws-sdk/lib/param_validator.js:88:21)
    at ParamValidator.validate (/var/runtime/node_modules/aws-sdk/lib/param_validator.js:34:10)
    at Request.VALIDATE_PARAMETERS (/var/runtime/node_modules/aws-sdk/lib/event_listeners.js:132:42)
    at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at callNextListener (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:96:12)
    at /var/runtime/node_modules/aws-sdk/lib/event_listeners.js:86:9
    at finish (/var/runtime/node_modules/aws-sdk/lib/config.js:386:7)
    at /var/runtime/node_modules/aws-sdk/lib/config.js:404:9 {
  code: 'UnexpectedParameter',
  time: 2021-11-25T23:24:22.964Z
}

**Comment by achris** [comment]
Hi,

Could you also confirm the version of the AWS SDK that you are using?

**Comment by LouisMx** [comment]
Hi @achris ,
My lambda is running the Nodejs14x, so with the default SDK version 2.1001.0 (Lambda created recently)

**Comment by achris** [comment]
Hi,

Support for the ChimeSdkMeetingConfiguration key was added in the SDK version 2.1003.0, could you try with a later version?

**Comment by LouisMx** [comment]
Thanks @achris !

it works... With the latest AWS SDK version (2.1036.0). Sorry :)

**Comment by achris** [comment]
Great, glad we were able to sort it out quickly
