### ISSUE TITLE
Audio Input and Audio Output Enable But Not Work iOS Safari Devices

### ISSUE THREAD

**Issue by thaithanhdhv** [aws/amazon-chime-sdk-js#1842]
Hello. I started using Chime SDK to build one to one calling client on Vuejs.
I got an issue with Safari.
Can someone help me?
1. Join Meeting from Desktop, Chrome on Android and Safari on IOS
2.  Desktop and Android work as expect
3. Safari -> can't talk or hear from other people in meeting session.
SDK version: 2.23.0
IOS: 15

**Comment by ltrung** [comment]
Hi, I did a quick test using our [meeting demo](https://github.com/aws/amazon-chime-sdk-js/tree/master/demos/browser) in iPhone iOS 15.1 and we could hear each other fine. Could you try our meeting demo and see if you could reproduce the issue?
Also could you upload a console log ?

**Comment by thaithanhdhv** [comment]
ok. Thank you. let me check it.

**Comment by thaithanhdhv** [comment]
@ltrung  I fixed audio. Can hear each other.
But still can't talk. Microphone is allowed.

**Comment by thaithanhdhv** [comment]
```
try {
        await this.audioVideo.chooseAudioInputDevice(
          this.audioInputDevice.deviceId
        );
      } catch (e) {
        this.audioInputDevice = {};
      }
```

**Comment by thaithanhdhv** [comment]
<img width="590" alt="Screen Shot 2021-12-02 at 13 12 28" src="https://user-images.githubusercontent.com/39685046/144367819-87d69096-260b-481a-bbc0-150dbb88bbda.png">

**Comment by thaithanhdhv** [comment]
@ltrung 
I got problem like this. https://github.com/aws/amazon-chime-sdk-js/issues/1004

**Comment by mickyarun** [comment]
Same with me 
 <audio id="audioTracks" ></audio>


try{
        if (new DefaultBrowserBehavior().supportsSetSinkId()) {
          try {
            this.meetingSession.audioVideo.chooseAudioOutputDevice(deviceId);
          } catch (e) {
            this.log('failed to chooseAudioOutputDevice', e);
          }
        }
        try {
            await this.meetingSession.audioVideo.bindAudioElement(this.audioElement); 
          } catch (e) {
            this.log('failed to bindAudioElement', e);
        }
      }catch (e) {
        this.log('failed to bindAudioElement', e);
      }

**Comment by thaithanhdhv** [comment]
@mickyarun  Did you fix it?

**Comment by mickyarun** [comment]
@thaithanhdhv still struggling, code is almost same as sample

**Comment by michhyun1** [comment]
I dont think mobile supports choosing audio output - perhaps you can choose the audio input instead. https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html#i-am-unable-to-select-an-audio-output-device-in-some-browsers-is-this-a-known-issue

**Comment by anupjk-5** [comment]
@thaithanhdhv are you able to hear other attendee in safari now?

**Comment by thaithanhdhv** [comment]
@anupjk-5  no.

**Comment by mickyarun** [comment]
@thaithanhdhv If I manually do this from javascript its working document.getElementById("audioTracks").muted = false , somehow audio tag is getting muted

**Comment by thaithanhdhv** [comment]
@mickyarun  I have button to control muted or unmute. I try to switch but still not working

**Comment by anupjk-5** [comment]
@thaithanhdhv instead of muted/ unmuted, control the play/ pause methods of the audio element using the button

**Comment by thaithanhdhv** [comment]
@anupjk-5 are you talking about audio input?

**Comment by anupjk-5** [comment]
I am talking about the audio element which is used to bind the audio stream

**Comment by thaithanhdhv** [comment]
oh, let me try.
Working on IOS or not?
@anupjk-5

**Comment by anupjk-5** [comment]
It was working on iOS

**Comment by thaithanhdhv** [comment]
@anupjk-5  tried your solution. Microphone still don't work on IOS

**Comment by michhyun1** [comment]
@thaithanhdhv Have you tried the meeting demo? Everything seems to work on the meeting demo that I deployed serverlessly. 

Can you also make sure that the microphone is not being used by any other application. 

You can also try to see if its an issue with your mic: https://webrtc.github.io/samples/src/content/getusermedia/audio/

**Comment by thaithanhdhv** [comment]
@michhyun1  I tested my mic. It's ok.
and also checked.
 it's not being used by any other application.

**Comment by thaithanhdhv** [comment]
I don't understand what missing here :(

**Comment by thaithanhdhv** [comment]
When I put 2 devices close to each other.
There is sound when 2 microphones are close to each other.
So here I think the iPhone's microphone is still working but it can't transmit audio to other meeting participants

**Comment by michhyun1** [comment]
@thaithanhdhv Is there a way you can attach any console logs? thanks

**Comment by vidya-mohan** [comment]
Resolving as no response
