### ISSUE TITLE
Is there any Demo available in JavaScript version?

### ISSUE THREAD

**Issue by codetycon** [aws/amazon-chime-sdk-js#185]
Hi,

I am integrating chime SDK in a Laravel project. Is there any demo available in javascript version instead of typescript(https://github.com/aws/amazon-chime-sdk-js/tree/master/demos/browser)?

Thanks

**Comment by aburnson** [comment]
@codetycon, yes check out the [Video Help Desk](https://github.com/aws/amazon-chime-sdk-js/tree/master/demos/videohelpdesk) demo, which uses JavaScript.

- https://github.com/aws/amazon-chime-sdk-js/blob/master/demos/videohelpdesk/src/helpdesk.js
- https://github.com/aws/amazon-chime-sdk-js/blob/master/demos/videohelpdesk/src/website.js
