### ISSUE TITLE
How do I get the online/offline presence of a AppInstanceUser?

### ISSUE THREAD

**Issue by NS-BOBBY-C** [aws/amazon-chime-sdk-js#1853]
### What are you trying to do?

I'm trying to subscribe my application to sense the presences of users. I see there is a meeting attendee presence, and I understand how to use that. However, I'm not trying to have a meeting, I'm just trying to have a chat within a channel, and indicate to the users which channel members are online/offline. To me, subscribing to "attendee presence" seems to be overkill, but it might be the solution. Is this the case?

### How can the documentation be improved to help your use case?

Add a use case: displaying an indicator to show if users are online, offline, or busy

### What documentation have you looked at so far?

README.md
https://docs.aws.amazon.com/chime/latest/dg/getting-started.html
https://docs.aws.amazon.com/chime/latest/dg/websockets.html#message-structures
https://github.com/aws/amazon-chime-sdk-js/tree/master/src/realtimecontroller

**Comment by simmkyu** [comment]
Chime SDK Messaging does not support retrieving the presence of channel members. You can only see whether the current  member (you) is ready to receive Chime SDK messages via the `MessagingSessionObserver` methods:
- [MessagingSessionObserver.messagingSessionDidStart](https://aws.github.io/amazon-chime-sdk-js/interfaces/messagingsessionobserver.html#messagingsessiondidstart)
- [MessagingSessionObserver.messagingSessionDidStop](https://aws.github.io/amazon-chime-sdk-js/interfaces/messagingsessionobserver.html#messagingsessiondidstop)

⠀

> To me, subscribing to "attendee presence" seems to be overkill, but it might be the solution. Is this the case?

Yes, using `audioVideo.realtimeSubscribeToAttendeeIdPresence` API can be an option. (A downside is that you have to create a Chime SDK meeting even if you do not need an audio/video call.)

**Comment by NS-BOBBY-C** [comment]
Closing issue - no longer required for my project. Thank you for the answer!
