### ISSUE TITLE
Cannot launch browser sample app based on readme instruction

### ISSUE THREAD

**Issue by Th3G4mbl3r** [aws/amazon-chime-sdk-js#1871]
### What happened and what did you expect to happen?

I followed the instructions at the [readme for browser sample app](https://github.com/aws/amazon-chime-sdk-js/tree/master/demos/browser#readme) to try and run the MeetingAppv2 demo. However, it fails to start with the following error:

```
Starting server.
/Users/rohitus/Documents/Projects/amazon-chime-sdk-meeting-avatar/amazon-chime-sdk-js/demos/browser/server.js:52
  return ((useChimeSDKMeetings === 'true') || (meeting?.Meeting?.MeetingFeatures?.Audio?.EchoReduction === 'AVAILABLE')) ? chimeSDKMeetings : chime;
                                                       ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/Users/rohitus/Documents/Projects/amazon-chime-sdk-meeting-avatar/amazon-chime-sdk-js/demos/browser/serve.js:1:19)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
```
As we can see the problem is that in server.js line 52 - the member reference for meeting object also includes a ? which is wrong syntax. It needs to be changed to only a . So the correct code needs to be:

```
 return ((useChimeSDKMeetings === 'true') || (meeting.Meeting.MeetingFeatures.Audio?EchoReduction === 'AVAILABLE')) ? chimeSDKMeetings : chime;
```

### Have you reviewed our existing documentation?

- [X] GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [X] FAQs [page](https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html)
- [X] README [page](https://github.com/aws/amazon-chime-sdk-js#amazon-chime-sdk-for-javascript)
- [X] Feature-specific [guides](https://github.com/aws/amazon-chime-sdk-js#guides)

### Reproduction steps

npm start run in the browser directory

### Amazon Chime SDK for JavaScript version

2.23.0

### What browsers are you seeing the problem on?

Google Chrome

### Browser version

Chrome 96.0.4664.93

### Meeting and Attendee ID Information.

3797541364 - rohit

### Browser console logs

Not applicable

**Comment by devalevenkatesh** [comment]
Thanks for reporting the issue, I checked and find this to be running fine for me. This is optional chaining, I do not know why it is failing for you.

- Can you once confirm if `meeting.Meeting?.MeetingFeatures?.Audio?.EchoReduction === 'AVAILABLE'` works for you? This should not change much as the first `?.` will check for valid `meeting` object itself.
- What is your typescript version?
- What is your NPM and Node version?

I am running:
- Node v16.8.0
- NPM 7.21.0
- typescript 4.2.3

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining

**Comment by devalevenkatesh** [comment]
Found that Node14+ supports optional chaining.
https://stackoverflow.com/questions/59574047/how-to-use-optional-chaining-in-node-js-12

Request to confirm your node version, I am raising this PR to fallback to older syntax.
#1873

**Comment by devalevenkatesh** [comment]
The PR is merged and this should be fixed now. Thanks!
