### ISSUE TITLE
videoTileDidUpdate: boundExternalUserId null in tileState

### ISSUE THREAD

**Issue by alhambra1** [aws/amazon-chime-sdk-js#1874]
### What happened and what did you expect to happen?

We regularly, but not all the time, see an explicit JavaScript `null` value in the `boundExternalUserId` field of tileState parameter provided to the `videoTileDidUpdate` callback.

We expect to see a correct string for that value that would enable us to associate it with information needed for our use case.

We are on version 2.21.0 of the JavaScript client SDK.

### Have you reviewed our existing documentation?

- [X] GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [X] FAQs [page](https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html)
- [X] README [page](https://github.com/aws/amazon-chime-sdk-js#amazon-chime-sdk-for-javascript)
- [X] Feature-specific [guides](https://github.com/aws/amazon-chime-sdk-js#guides)

### Reproduction steps

We see logs for this regularly now for meetings by our staff in our web-based video conferencing app at circl.es.

### Amazon Chime SDK for JavaScript version

2.21.0

### What browsers are you seeing the problem on?

Chrome (did not test others)

### Browser version

96

### Browser console logs

N/A at this time.

**Comment by alhambra1** [comment]
An example tileState we received:
```
"chime_tile_state_obj": {
      "videoStreamContentWidth": 0,
      "devicePixelRatio": 2,
      "nameplate": null,
      "localTileStarted": false,
      "active": false,
      "boundExternalUserId": null,
      "isContent": false,
      "videoStreamContentHeight": 0,
      "poorConnection": false,
      "videoElementCSSHeightPixels": null,
      "localTile_bln": false,
      "boundVideoElement": null,
      "boundVideoStream": null,
      "videoElementPhysicalHeightPixels": null,
      "streamId_num": 0,
      "boundAttendeeId": "8341a756-7c06-163d-949a-00c92ab058db",
      "tileId": 3,
      "videoElementCSSWidthPixels": null,
      "videoElementPhysicalWidthPixels": null,
      "paused": false
    }
```

**Comment by ltrung** [comment]
Do  you use priority based downlink policy by any chance? From the log you show it seems to be the case. Priority based downlink policy create an empty video if there is no bandwidth to subscribe to that video and will subscribe to it once bandwidth allows. You should receive a `tileWillBePausedByDownlinkPolicy` (See https://github.com/aws/amazon-chime-sdk-js/blob/master/src/videodownlinkbandwidthpolicy/VideoPriorityBasedPolicy.ts#L784) and see this console log `bwe: Created video tile <tideId> for bw paused attendee <attendeeId>`.

**Comment by ltrung** [comment]
Closing for now. Feel free to reopen if you have additional questions.

**Comment by alhambra1** [comment]
@ltrung thank you for clarifying!

**Comment by alhambra1** [comment]
@ltrung by the way, is this line incorrect? https://github.com/aws/amazon-chime-sdk-js/blob/457dd7c1db9630817af92e9d170c994b8fa98b8f/src/videouplinkbandwidthpolicy/DefaultSimulcastUplinkPolicy.ts#L156

Shouldn't the 1200 be assigned in the next line (157) because on line 154, we have `this.newActiveStreams = ActiveStreams.kHi;` ??
