### ISSUE TITLE
When will v2.24 go to npm

### ISSUE THREAD

**Issue by gmonn** [aws/amazon-chime-sdk-js#1875]
I see that v2.24 was released on 12/7 but it is not available on npm yet. Any word on when that will happen?

**Comment by gmonn** [comment]
Thank you for the update.

**Comment by gmonn** [comment]
Any more word on when this might be released?

**Comment by xuesichao** [comment]
Hi @gmonn We are now working on testing, it should be released soon. We will update this thread once we released.

**Comment by devalevenkatesh** [comment]
Closing this is issue as the v24 is released. Sorry for any misscommunication.
