### ISSUE TITLE
Make vocal changes

### ISSUE THREAD

**Issue by luchinilato** [aws/amazon-chime-sdk-js#1882]
Is there a possibility to apply vocal changes of a participant?

**Comment by xuesichao** [comment]
Hi! Could you please explain it a bit more? What do you mean by "vocal change"?

**Comment by luchinilato** [comment]
Hi. Thanks for the reply.
Sorry if I didn't explain my question correctly. I will try to be more clear.

I found the following project: 
https://voicechanger.io
The project is basically a list of effects to apply to the audio. 
Ex:
https://voicechanger.io/transforms/church.js
https://voicechanger.io/transforms/pitch.js
https://voicechanger.io/transforms/cuteRobot.js
https://voicechanger.io/transforms/vibrato.js

I would like to know if it would be possible to apply any of these effects to the audio of a chime participant.

**Comment by ltrung** [comment]
I have not tried this library before but if it can produce a MediaStream then you can call `chooseAudioInputDevice` and set the audio input to that media stream.

**Comment by ltrung** [comment]
Closing for now but feel free to reopen if you have additional questions.
