### ISSUE TITLE
Missing TURN credentials - user video appears and disappears

### ISSUE THREAD

**Issue by vsimeikoKG** [aws/amazon-chime-sdk-js#1884]
### What happened and what did you expect to happen?

We had an issue where only one video tile was constantly disappearing for a few seconds and then appearing back for maybe seconds 10. It was happening all the time during our meeting. To be more specific, all users were seeing the same behaviour for that user.

Chime setup notes:
- In this meeting we had a priority policy enabled with the stable network preset. We had no issues with this policy for the last 2-3 weeks.
- We have an auto-reconnect enabled which tries to reconnect upon Chime error.

Additional information from the user who constantly disappeared:
- Internet speed test: 1ms ping, 517mbps uplink, and 549mbps downlink;
- MacOS version 11.6.1 (20G224);
- Chrome version 96.0.4664.93 (Official Build) (x86_64)

### Have you reviewed our existing documentation?

- [X] GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [X] FAQs [page](https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html)
- [X] README [page](https://github.com/aws/amazon-chime-sdk-js#amazon-chime-sdk-for-javascript)
- [X] Feature-specific [guides](https://github.com/aws/amazon-chime-sdk-js#guides)

### Reproduction steps

Unfortunately, we don't have exact steps to reproduce. User started to appear and disappear as soon as he joined the call.

### Amazon Chime SDK for JavaScript version

2.23.0

### What browsers are you seeing the problem on?

Chrome (probably for all users in the call)

### Browser version

96.0.4664.93 (Official Build) (x86_64) (probably for most of users as well)

### Meeting and Attendee ID Information.

Chime meeting ID - f34c3973-9752-43f6-a9b0-541974150706
Attendee ID of the user who appeared and disappeared all the time - 227c8af7-6d33-9c42-2c69-ae15ff1b42d8
Attendee ID of the user who saw other user video tile appear & disappear (my ID) - c2db34ce-e6ae-4c54-cd97-2c3074272285

There were more attendees in the call, so you could probably grab other attendee IDs from that call as well if needed.

### Browser console logs

Unfortunately, we don't have an `INFO` level logs for this call, but we had a screen recording from the user who constantly appeared and disappeared in the call. I attached a screenshot with the console logs of that user below.

![image](https://user-images.githubusercontent.com/72414337/146400962-59ff4734-b2ad-4a57-b339-daaebfb13330.png)

**Comment by ltrung** [comment]
>We have an auto-reconnect enabled which tries to reconnect upon Chime error.

Do you mean the default Amazon Chime JS SDK reconnect logic or your custom logic?
The error comes from here `https://github.com/aws/amazon-chime-sdk-js/blob/master/src/task/ReceiveTURNCredentialsTask.ts#L45` which just means that the TURN credentials is not available and it will fallback ad try to fetch it from the backend. Without the INFO log, we can't tell whether it succeeds but from our backend logs, it seems the reconnect succeeds before dropped again due to the same audio delay. The error is unexpected though as it should receive TURN credentials before that in https://github.com/aws/amazon-chime-sdk-js/blob/master/src/task/JoinAndReceiveIndexTask.ts#L75. I checked the backend and we did send that so not sure how the client could get to that state.

For the reconnection, according to the log it is due to bad audio delay from webRTC stat `googCurrentDelayMs` that is above the meeting configuration `maximumAudioDelayMs` (which default to 60s).

**Comment by vsimeikoKG** [comment]
@ltrung ,

We're using two reconnects:
1) Default Chime JS SDK reconnect logic
2) Our custom reconnect logic. Code snippet for it:
```js
audioVideoDidStop(meetingSessionStatus) {
  if (
    ![MeetingSessionStatusCode.Left, MeetingSessionStatusCode.MeetingEnded].includes(
      meetingSessionStatus.statusCode()
    )
  ) {
    console.debug('Meeting Session - Stopped');
    dispatch(setMeetingStatus(MeetingStatusEnum.Stopped));
    // We have a hook that listens to the meeting status.
    // Once "Stopped" state is detected, then user will re-join the meeting with new credentials.
    // Upon rejoin we completely re-create a new meetingSession object.
  }
},
```

It looks like the same user had the same issue this morning again.

I'll add DEBUG/INFO logs and hopefully we can get back to you with more information.

**Comment by ltrung** [comment]
Just curious why do we need custom reconnect logic? Doesn't JS SDK reconnect by itself in these case (not meeting ended or left) anyway?

**Comment by devalevenkatesh** [comment]
Closing this issue due to no new activity, request you to please re-open if you still face the same issue and please provide the browser console logs as request for further debugging. Thanks!
