### ISSUE TITLE
Simulcast kills video streams

### ISSUE THREAD

**Issue by vsimeikoKG** [aws/amazon-chime-sdk-js#1885]
### What happened and what did you expect to happen?

I experience missing video streams or simply frozen video tiles for almost all remote users when I enter meeting with enabled default simulcast policy.

Additional notes:
- I didn't use any custom downlink policy here.
- My internet speed: 3ms ping, 264mbps downlink, and 53mbps uplink.
- All four attendees joined from the same device (my localhost).
- Disabling simulcast policy fixes all missing/freezing video tiles.

Simulcast policy code:
```js
const logger = new ConsoleLogger('[ChimeLogger]', chimeLogLevel);

const meetingSessionConfiguration = new MeetingSessionConfiguration(meeting, attendee);

if (new DefaultBrowserBehavior().isSimulcastSupported()) {
  meetingSessionConfiguration.enableSimulcastForUnifiedPlanChromiumBasedBrowsers = true;
  meetingSessionConfiguration.videoUplinkBandwidthPolicy = new DefaultSimulcastUplinkPolicy(
    attendee.AttendeeId,
    logger
  );
}

const meetingSession = new DefaultMeetingSession(
  meetingSessionConfiguration,
  logger,
  new DefaultDeviceController(logger, {enableWebAudio: state.isVoiceFocusSupported})
);
```

### Have you reviewed our existing documentation?

- [X] GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [X] FAQs [page](https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html)
- [X] README [page](https://github.com/aws/amazon-chime-sdk-js#amazon-chime-sdk-for-javascript)
- [X] Feature-specific [guides](https://github.com/aws/amazon-chime-sdk-js#guides)

### Reproduction steps

1) Join meeting with muted audio and video enabled.
2) Experience missing or frozen video right away.

### Amazon Chime SDK for JavaScript version

2.23.0

### What browsers are you seeing the problem on?

Chrome

### Browser version

95.0.4638.54 (Official Build) (x86_64)

### Meeting and Attendee ID Information.

Chime meeting ID - 721df285-19e8-45e1-a7bd-3f5368fd0706

Attendee ID 1 - 60e73061-2912-a173-2a66-ba5a76e03191. Had 1 frozen video, 1 missing video, and 1 video working normally. After some time all video started to work.
Attendee ID 2 -  0da9298c-8f88-d787-6869-017c8520444a. Had one frozen video and 2 videos working normally.
Attendee ID 3 - 2aa5f631-1e47-0795-ebea-9bd0e2af6a28. Had two missing and 1 frozen video.
Attendee ID 4- 93e5a328-9153-9f05-992c-0dbaf33b59fc. Had two missing and 1 frozen video.

### Browser console logs

Debug level logs for all users in the call:
[Attendee 93e5a328-9153-9f05-992c-0dbaf33b59fc.txt](https://github.com/aws/amazon-chime-sdk-js/files/7728766/Attendee.93e5a328-9153-9f05-992c-0dbaf33b59fc.txt)
[Attendee 0da9298c-8f88-d787-6869-017c8520444a.txt](https://github.com/aws/amazon-chime-sdk-js/files/7728763/Attendee.0da9298c-8f88-d787-6869-017c8520444a.txt)
[Attendee 2aa5f631-1e47-0795-ebea-9bd0e2af6a28.txt](https://github.com/aws/amazon-chime-sdk-js/files/7728764/Attendee.2aa5f631-1e47-0795-ebea-9bd0e2af6a28.txt)
[Attendee 60e73061-2912-a173-2a66-ba5a76e03191.txt](https://github.com/aws/amazon-chime-sdk-js/files/7728765/Attendee.60e73061-2912-a173-2a66-ba5a76e03191.txt)

**Comment by ltrung** [comment]
@vsimeikoKG  This is similar to this issue here that I have replied https://github.com/aws/amazon-chime-sdk-js/issues/1887#issuecomment-998323487.

**Comment by ltrung** [comment]
Closing as dup of #1887.
