### ISSUE TITLE
Need to set the highest priority for video source of active speaker

### ISSUE THREAD

**Issue by suman2755** [aws/amazon-chime-sdk-js#1896]
### What are you trying to do?

I am trying to set highest priority for video source of active speaker. For identifying the active speaker, I am using useActiveSpeakersState hook. But this hook is updated often and causes frequent rendering. For setting up the priority, I am using VideoPriorityBasedPolicy. As we know, useActiveSpeakersState causes frequent rendering, so I doubt it might affect the performance as I need to update the video preference for priority setting on each update.

can someone guide me on this. Am I using the right approach. Or is there any better and optimized way to do this.

**Comment by xuesichao** [comment]
Hi @suman2755. The `activeSpeakerDetector` is designed to reflect the active speakers in real-time, so it's supposed to update frequently. However you could delay this update by creating a new hook yourself. I would recommend you to check the implementation of `useFeaturedTileState` hook which returns the most active speaker. Or maybe just use this hook.

https://github.com/aws/amazon-chime-sdk-component-library-react/blob/f26a6c0eca769f306d43cc3c95bc0d5cb0705d5f/src/providers/FeaturedVideoTileProvider/index.tsx#L32-L80

**Comment by ltrung** [comment]
Could you let us know the JS SDK version that you are using?

**Comment by suman2755** [comment]
Hi @ltrung , I am using the latest JS SDK version 2.24.0

**Comment by ltrung** [comment]
To avoid the frequent rendering when active speakers change frequently, I think you may need to add some additional logic like what @xuesichao suggested or implement your custom [active speaker policy](https://aws.github.io/amazon-chime-sdk-js/classes/defaultactivespeakerpolicy.html) with less take over rate.

**Comment by vidya-mohan** [comment]
Resolving as no response - @suman2755 hope this suggestion helps you
