### ISSUE TITLE
DefaultBrowserBehavior.isSupported() returns incorrect value for firefox

### ISSUE THREAD

**Issue by shriyajuneja** [aws/amazon-chime-sdk-js#1898]
### What happened and what did you expect to happen?

As per chime's documentation Firefox version 75 and above are supported but `DefaultBrowserBehavior.isSupported` returns true for all versions above 60. 
https://github.com/aws/amazon-chime-sdk-js/blob/457dd7c1db9630817af92e9d170c994b8fa98b8f/src/browserbehavior/DefaultBrowserBehavior.ts#L16
However it does break in versions below 75, it throws `Syntax error: invalid regex group`. Can we please update this function ?

### Have you reviewed our existing documentation?

- [X] GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [X] FAQs [page](https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html)
- [X] README [page](https://github.com/aws/amazon-chime-sdk-js#amazon-chime-sdk-for-javascript)
- [X] Feature-specific [guides](https://github.com/aws/amazon-chime-sdk-js#guides)

### Reproduction steps

NA

### Amazon Chime SDK for JavaScript version

2.24.0

### What browsers are you seeing the problem on?

Firefox

### Browser version

72

### Meeting and Attendee ID Information.

NA

### Browser console logs

NA

**Comment by ltrung** [comment]
@shriyajuneja Thanks for finding it. I have opened PR #1903 to address it.

**Comment by devalevenkatesh** [comment]
The linked PR is merged now and should be available in the next release.
