### ISSUE TITLE
 How do I know if the screen is being shared or not.

### ISSUE THREAD

**Issue by E5920** [aws/amazon-chime-sdk-js#1904]
### What happened and what did you expect to happen?

@ltrung @michhyun1 @devalevenkatesh  @simmkyu  ,We have used aws chime to build a virtual conferencing platform in our application.So I have question, 
1 :- How do I know if the screen is being shared or not. kindly suggest me,  we can know whether screen sharing is happening or not through event or any other ways ?

2:- I know Chime SDK only allows share screen 2 times in every meeting.but  I want to allow only one screen sharing at a time but How ? 

 

regards,
Rajat Kesharwani.

### Have you reviewed our existing documentation?

- [X] GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [X] FAQs [page](https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html)
- [X] README [page](https://github.com/aws/amazon-chime-sdk-js#amazon-chime-sdk-for-javascript)
- [X] Feature-specific [guides](https://github.com/aws/amazon-chime-sdk-js#guides)

### Reproduction steps

pl check above

### Amazon Chime SDK for JavaScript version

2.4.1

### What browsers are you seeing the problem on?

n/a

### Browser version

n/a

### Meeting and Attendee ID Information.

n/a

### Browser console logs

n/a

**Comment by devalevenkatesh** [comment]
1 :- How do I know if the screen is being shared or not. kindly suggest me, we can know whether screen sharing is happening or not through event or any other ways ?

- You can use the content share observer methods to know when a content share starts / stops or is paused / un-paused. 

- Check that the meetingV2 demo [implements](https://github.com/aws/amazon-chime-sdk-js/blob/main/demos/browser/app/meetingV2/meetingV2.ts#L217) the `ContentShareObserver` and then adds itself as an observer to the [`meetingSession.audioVideo`](https://github.com/aws/amazon-chime-sdk-js/blob/main/demos/browser/app/meetingV2/meetingV2.ts#L1611).
- Then listens on to events through above mentioned [observers](https://github.com/aws/amazon-chime-sdk-js/blob/main/demos/browser/app/meetingV2/meetingV2.ts#L3354-L3374).

2:- I know Chime SDK only allows share screen 2 times in every meeting.but I want to allow only one screen sharing at a time but How ?

- This is also implemented in the meetingV2 demo. Basically, when you see that an attendee or a video tile is a content one then call `meetingSession.audioVideo.stopContentShare()` first. Listen for the stop in `contentShareDidStop` and close the HTML video element bound for it.
- In meetingV2 demo, this is done based on attendee presence handler. Please check this code [here](https://github.com/aws/amazon-chime-sdk-js/blob/b3b4151b605aaa94102e70fe7e5afc02faca2601/demos/browser/app/meetingV2/meetingV2.ts#L1766-L1774).

Documentation Resources:
- [ContentShareObserver](https://aws.github.io/amazon-chime-sdk-js/interfaces/contentshareobserver.html)
- [Content Share API Overview](https://aws.github.io/amazon-chime-sdk-js/modules/contentshare.html#receive-content-share-events)

Please let us know if you have more questions.

**Comment by ltrung** [comment]
Closing this for now. Feel free to open if you have additional questions.
