### ISSUE TITLE
After the meeting ends, the red LED on the active chrome tab

### ISSUE THREAD

**Issue by Breners** [aws/amazon-chime-sdk-js#1906]
### What happened and what did you expect to happen?

After the meeting ends, the red LED on the active chrome tab indicates that a device is being used and in this case, the chrome indicates that the microphone is being used

### Have you reviewed our existing documentation?

- [X] GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [X] FAQs [page](https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html)
- [X] README [page](https://github.com/aws/amazon-chime-sdk-js#amazon-chime-sdk-for-javascript)
- [X] Feature-specific [guides](https://github.com/aws/amazon-chime-sdk-js#guides)

### Reproduction steps

I end the interview and am redirected to another route, after this, these methods are called

```
await audioVideo?.chooseAudioInputDevice(null);
await meetingManager.leave().then(() => audioVideo?.stop());
```

### Amazon Chime SDK for JavaScript version

2.17.0

### What browsers are you seeing the problem on?

Chrome

### Browser version

96.0.4664.110 (64 bits)

### Browser console logs

none

**Comment by devalevenkatesh** [comment]
Hello, thanks for reporting this issue.

Few questions:
1. Are you using video as well or simply just audio?
2. Are you using amazon-chime-sdk-js or amazon-chime-sdk-component-library-react?

For cleaning up the audio and video, please follow below FAQ:
https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html#after-leaving-a-meeting-the-camera-led-is-still-on-indicating-that-the-camera-has-not-been-released-what-could-be-wrong

Please let us know above request info to help further.

**Comment by Breners** [comment]
1. Both
2. amazon-chime-sdk-component-library-react

**Comment by devalevenkatesh** [comment]
@Breners thanks, so did you check the FAQ I linked, if you are using react component library you do not have to call stop after leave as it is done for you inside the [`meetingManager.leave()`](https://github.com/aws/amazon-chime-sdk-component-library-react/blob/main/src/providers/MeetingProvider/MeetingManager.ts#L246-L271) call.

I request you to check our [meeting demo](https://github.com/aws-samples/amazon-chime-sdk/tree/main/apps/meeting) based and built using the `amazon-chime-sdk-component-library-react`. 

We handle two ways of an attendee leaving a meeting:
1. Whether a local attendee leaves the meeting or when the attendee hits a back button or changes route any one other than the in-meeting screen route.
2. If some remote attendee ends meeting for all.

In this demo, we also re-direct upon meeting leave. We call the [`meetingManager.leave()`](https://github.com/aws-samples/amazon-chime-sdk/blob/main/apps/meeting/src/providers/NavigationProvider.tsx#L45-L51) when we see that the app is going away from the in-meeting screen route.

When a meeting is ended by some other attendee, component library internally sets the `MeetingStatus` to `Ended` and publishes it through the `useMeetingStatus` hook. We then in the demo have a [custom hook](https://github.com/aws-samples/amazon-chime-sdk/blob/main/apps/meeting/src/hooks/useMeetingEndRedirect.tsx#L33) to listen for the `MeetingStatus` and push the app to the home page.

In our demo app, I do not see any red icon upon meeting leave, hence request you to please check its implementation and let us know if you still have further questions.

**Comment by Brenerss** [comment]
I tested the demo and the led disappears. In my case, when the interview ends, I take the user to a new route if I don't call meetingManager.leave(); both the camera and microphone are enabled, but if I call meetingManager.leave(); google indicates that only the microphone is being used

**Comment by devalevenkatesh** [comment]
Yes, you have to call `meetingManager.leave()` to clear-up the meeting session. It calls the necessary clean-up APIs so you won't have to call `audioVideo.stop()` explicitly. Can you listen on the `useMeetingStatus` hook and re-direct rather than early re-directing. Not sure early re-directing is affecting the `leave` call.

**Comment by devalevenkatesh** [comment]
Closing this issue request you to please checkout the meeting demo linked in previous which you confirmed works for you. In that solution also we re-direct when user click leave meeting and hence would be a similar implementation required in your side to solve it. Please feel free to re-open if you still face issues.
