### ISSUE TITLE
Local video is forcibly shut down when switching devices.

### ISSUE THREAD

**Issue by t-sugimoto0914** [aws/amazon-chime-sdk-js#1914]
### What happened and what did you expect to happen?

When switching devices, local video is forcibly terminated and goes dark when the acquisition fails.

### Have you reviewed our existing documentation?

- [X] GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [X] FAQs [page](https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html)
- [X] README [page](https://github.com/aws/amazon-chime-sdk-js#amazon-chime-sdk-for-javascript)
- [X] Feature-specific [guides](https://github.com/aws/amazon-chime-sdk-js#guides)

### Reproduction steps

1. Join a meeting using Chrome 97 (currently in Beta)
2. Enable video
3. Switch devices

### Amazon Chime SDK for JavaScript version

2.21.1

### What browsers are you seeing the problem on?

chrome

### Browser version

97

### Browser console logs

 [ERROR] SDK - no video device chosen, stopping local video tile

**Comment by devalevenkatesh** [comment]
Thanks for reporting the issue, could you please take a look at https://github.com/aws/amazon-chime-sdk-js/issues/1893 and see whether it is a similar one?


If yes, request you to upgrade to JS SDK >=v2.23.1 to solve the issue.

**Comment by jing-chen1** [comment]
Closing it, please feel free to reopen it if you still have problem.
