### ISSUE TITLE
Camera / Mic Indicator is on when the camera was initialising user routed to different page.

### ISSUE THREAD

**Issue by arpitmittal-lab** [aws/amazon-chime-sdk-js#1915]
I am using the below code to show the preview video before joining the call, but when the camera was initialising if the user navigates to a different page then the LED light indicator keeps on running on different route also. It should get closed as soon as the user leaves the page.

**Previe Video Code**
```
import {
	ConsoleLogger,
	DefaultDeviceController,
	LogLevel,
} from "amazon-chime-sdk-js";

const logger = new ConsoleLogger("sdk", LogLevel.INFO);
const deviceController = new DefaultDeviceController(logger, {
enableWebAudio: true,
});

const previewVideo = async () => {
  const audioList = await deviceController.listAudioInputDevices();
  const deviceList = await deviceController.listVideoInputDevices();
  await deviceController.chooseVideoInputDevice(deviceList[0]?.deviceId);
  deviceController.startVideoPreviewForVideoInput(videoElement.current);
};
```

**Render**:
`<video ref={videoElement}></video>`

**Comment by devalevenkatesh** [comment]
Thanks for reporting the issue. Yes, if JS SDK has already called `getUserMedia` as part of `await deviceController.chooseVideoInputDevice(deviceList[0]?.deviceId);` then the LED will go ON and any re-direction would not stop it automatically.

To turn the LED off, you have to follow this [FAQ](https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html#after-leaving-a-meeting-the-camera-led-is-still-on-indicating-that-the-camera-has-not-been-released-what-could-be-wrong).

You also have to check for user re-direction though. You can use [PageVisibility](https://developer.mozilla.org/en-US/docs/Web/API/Page_Visibility_API) API to this and do the following:

```
// Handle page visibility change
document.addEventListener(visibilityChange, handleVisibilityChange, false);

async function handleVisibilityChange() {
  if (document.visibilityState === 'hidden') {
    // Select no video device (releases any previously selected device)
    await meetingSession.audioVideo.chooseVideoInputDevice(null);
    
    // Stop a video preview that was previously started (before session starts)
    meetingSession.audioVideo.stopVideoPreviewForVideoInput(previewVideoElement);
    
    // Stop the meeting session (audio and video)
    meetingSession.audioVideo.stop();
  }
}
```

Please let me know if this works for you or you have more questions.

**Comment by arpitmittal-lab** [comment]
@devalevenkatesh the solution that you have shared is for closing the camera on the tab change, but we need the solution when the user is routing to a different route/page on our website.

**Comment by ltrung** [comment]
@arpitmittal-lab That is the app logic to handle whether to stop the video so its hard for us to suggest a concrete solution without knowing how your app works. For framework like React, you can make sure to call audioVideo.stop() when a component is unmount.

**Comment by devalevenkatesh** [comment]
For the route change, you can implement the same API calls logic but before routing. I am not sure what routing mechanism you are using or any framework but you could use same above code but with `beforeunload` or `unload` event from browser.

You can also use `window.location.pathname | href` to know the location and then trigger the APIs to leave the meeting. For example in our react meeting demo, we do [this](https://github.com/aws-samples/amazon-chime-sdk/blob/main/apps/meeting/src/providers/NavigationProvider.tsx#L45-L51) to check if user is moving away.

> Please check the reliability of `beforeunload` and `unload` events triggered by browser.

**Comment by arpitmittal-lab** [comment]
@devalevenkatesh I am already doing so on unmounting.

Issue Video: https://youtu.be/bKN-j5KJl74

I notice sometimes it gets removed after a few seconds and sometimes it doesn't.

Note: I am using amazon-chime-sdk-js just for handling the preview video without joining the meeting.

**Code**
```
const previewVideo = async () => {
		const audioList = await deviceController.listAudioInputDevices();
		setAudioBlock(audioList[0]?.label === "" ? false : true);
		const deviceList = await deviceController.listVideoInputDevices();
		setVideoBlock(deviceList[0]?.label === "" ? false : true);
		await deviceController.chooseVideoInputDevice(deviceList[0]?.deviceId);
		deviceController.startVideoPreviewForVideoInput(videoElement.current);
		console.log("video turn on");
	};

	const privewVideoStop = async () => {
		if (videoElement.current) {
			console.log("Code Executed inside previewVideoStop");
			deviceController.stopVideoPreviewForVideoInput(videoElement.current);
			console.log("Code Executed inside after stopping previewVideoStop");
		}
	};

	useEffect(() => {
		if (props?.location?.search !== "?join=true") {
			previewVideo();
		}
		return () => {
			if (props?.location?.search !== "?join=true") {
				console.log("Code Executed on Unmount");
				privewVideoStop();
			}
		};
	}, [props?.location?.search]);
```

**Comment by michhyun1** [comment]
hmm just curious - could you try putting the code for previewVideoStop:
```
console.log("Code Executed inside previewVideoStop");
			deviceController.stopVideoPreviewForVideoInput(videoElement.current);
			console.log("Code Executed inside after stopping previewVideoStop");
```

directly into the return function for that last useEffect hook? I'm suspicious of the `ref.current` somehow being cleared before we can use it to stop the preview video. 


```
	useEffect(() => {
		if (props?.location?.search !== "?join=true") {
			previewVideo();
		}
		return () => {
			if (props?.location?.search !== "?join=true") {
				console.log("Code Executed on Unmount");
				deviceController.stopVideoPreviewForVideoInput(videoElement.current);
     			        console.log("Code Executed inside after stopping previewVideoStop");
			}
		};
	}, [props?.location?.search]);
```

**Comment by arpitmittal-lab** [comment]
@michhyun1 tried the way you suggested, but no luck.

**Comment by michhyun1** [comment]
@arpitmittal-lab Thanks for your patience. Is there a way you can call `stopVideoPreviewForVideoInput` on the button click event - instead of on a useEffect event? Im wondering if there might be some race condition with the videoElement.current ref being cleared out before the stream attached to that HTMLVideoElement ref can be removed.

**Comment by devalevenkatesh** [comment]
Hi @arpitmittal-lab , I tried to work with your provided code and could re-pro using a react app created using the `create-react-app`. The reason your camera does not get clear is due to the `ref.current` goes to `null`  before react calls the `useEffect`'s cleanup function. Hence, this results into the JS SDK API failure to stop the video preview, the video component un-mounts but the camera is still being accessed by the browser.

To help with a solution I created a simple repo to provide the solution. It demos how in a routing based SPA, one can start the video preview and stop it correctly on route changes using only the device controller from Amazon Chime SDK for JavaScript.

The routing is in separate component but this is the code for the component which starts and stops the preview.
```js
import {ConsoleLogger, DefaultDeviceController, LogLevel} from 'amazon-chime-sdk-js';
import {useEffect, useRef} from 'react';
import {useLocation} from 'react-router-dom';


export default function Home() {
  const videoRef = useRef();
  const location = useLocation();

  let dc; 
  async function startVideoPreview() {
    dc = new DefaultDeviceController(new ConsoleLogger('test-device-controller', LogLevel.WARN), { enableWebAudio: false});
    const audioInputs = await dc.listAudioInputDevices();
    const videoInputs = await dc.listVideoInputDevices();
    const audioOutputs = await dc.listAudioOutputDevices();
    await dc.chooseAudioInputDevice(audioInputs[0].deviceId);
    await dc.chooseVideoInputDevice(videoInputs[0].deviceId);
    await dc.chooseAudioOutputDevice(audioOutputs[0].deviceId);
    dc.startVideoPreviewForVideoInput(videoRef.current);
  }

  async function stopVideoPreview(videoElement) {
    dc.stopVideoPreviewForVideoInput(videoElement);
    await dc.chooseAudioInputDevice(null);
    await dc.chooseVideoInputDevice(null);
    await dc.chooseAudioOutputDevice(null);
    dc = undefined;
  }
  
  useEffect(() => {
    // This is important. We need to store the ref created since the useEffect's cleanup function runs after the component is un-mounted.
    // Since the "video" element un-mounts early, the ref.current will hold "null" and hence result in not cleaning of video correctly.
    const videoElement = videoRef.current;
    if (location.pathname.includes('home')) {
      startVideoPreview();
      return () => {
        stopVideoPreview(videoElement);
      }
    }
  }, [location.pathname]);

  return (
    <div className="Home">
      <h1>Home</h1>
      <div style={{width: '400px', height: '300px'}}>
        <video ref={videoRef}></video>
      </div>
    </div>
  )
}
```

Solution Repository Link: https://github.com/devalevenkatesh/video-preview-only-js-sdk
Request you to please check it out. Please let me know if you have further questions.

**Comment by jing-chen1** [comment]
Closing it for now, feel free to reopen it if you still have problems.
