### ISSUE TITLE
Delay removing attendee from meeting and meeting status

### ISSUE THREAD

**Issue by jitt3** [aws/amazon-chime-sdk-js#1916]
### What happened and what did you expect to happen?

We have implemented a feature to remove an attendee from the call.  but we have a huge delay since we request the 'remove' until we get the signal in the frontend side

### Have you reviewed our existing documentation?

- [X] GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [X] FAQs [page](https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html)
- [X] README [page](https://github.com/aws/amazon-chime-sdk-js#amazon-chime-sdk-for-javascript)
- [X] Feature-specific [guides](https://github.com/aws/amazon-chime-sdk-js#guides)

### Reproduction steps

These are the steps we follow to do so:
- The host sends a request to our backend, which is the one that removes the attendee calling this endpoint `/meetings/meetingId/attendees/attendeeId`
- Once the attendee is removed from the call, we get the signal in the frontend side
-  We handle finishing the session of the removed attendee inside  the `audioVideoDidStop` listener

Here is the point where it gets weird

the value of the meeting status of the removed attendee becomes `SignalingRequestFailed` instead of `AudioAttendeeRemoved`(according to the documentation, this should be the proper status)

As we get `SignalingRequestFailed` as meeting status, we end the session of the removed attendee, but so far is taking up to 20 seconds to get that status, causing a delay when we update the UI.

### Amazon Chime SDK for JavaScript version

2.24.0

### What browsers are you seeing the problem on?

Chrome, Brave, Edge, Opera

### Browser version

95.0.4638.69

### Meeting and Attendee ID Information.

attendeeId: b93013b0-5a4e-5f87-741c-545742d9d58d
meetingId: 8850286b-297c-4572-8333-fc741aa10706

### Browser console logs

2022-01-04T15:12:10.504Z [INFO] MEDIACALLS - notifying event: WebSocketClosed
ConsoleLogger.js?cddf:76 2022-01-04T15:12:10.504Z [INFO] MEDIACALLS - stopped pinging (WebSocketClosed)
ConsoleLogger.js?cddf:76 2022-01-04T15:12:10.504Z [INFO] MEDIACALLS - no connection requests to service
ConsoleLogger.js?cddf:76 2022-01-04T15:12:17.472Z [INFO] MEDIACALLS - peer connection ice connection state changed: disconnected
ConsoleLogger.js?cddf:76 2022-01-04T15:12:17.472Z [INFO] MEDIACALLS - peer connection state changed: disconnected
ConsoleLogger.js?cddf:76 2022-01-04T15:12:18.348Z [INFO] MEDIACALLS - unusable audio warning is now: 0
ConsoleLogger.js?cddf:76 2022-01-04T15:12:27.451Z [INFO] MEDIACALLS - peer connection state changed: failed

**Comment by devalevenkatesh** [comment]
Hi, thanks for reporting this issue. We already have an open issue for this. https://github.com/aws/amazon-chime-sdk-js/issues/1440 and https://github.com/aws/amazon-chime-sdk-js/issues/1042 related to this issue.

Could you please provide full browser console logs to understand the delay?

**Comment by vidya-mohan** [comment]
Resolving as no response
