### ISSUE TITLE
Is it possible to create a watch-only attendee in AWS Chime SDK?

### ISSUE THREAD

**Issue by ThomasCarltonInPerson** [aws/amazon-chime-sdk-js#1917]
Hello community,

We are creating a video app using AWS Chime SDK.

We would like some users to be able to join the meeting only to watch. Without any adding-video/audio capability.

So far, our app requests a join token for an attendee and sends it back to the client :

	{
	"Attendee":
		{
		"AttendeeId":"b0637fd9-0140-3412-a51a-2c51ebd8fd08",
		"ExternalUserId":"MaavEFZt1DEfy",
		"JoinToken":"YjA2MzdmZDktMGZmMC04MTMyLWE1MWEtjBiYWU0YWE3LWVhYjctNDBkZS1iMjE4LTYyOWVlNGVmNTAxOA",
		"Tags":null
		}
	}
 
The attendee can then, watch the meeting using the code : 

	/*----------------------------------------------*/
	/* Create meeting session and init 			    */
	/*----------------------------------------------*/
	const MeetingResponse = 'some json representing the meeting response';
	const ParticipantResponse = 'previous participant response';

	const logger = new ChimeSDK.ConsoleLogger('ChimeMeetingLogs', ChimeSDK.LogLevel.INFO);
	const deviceController = new ChimeSDK.DefaultDeviceController(logger);		
	const configuration = new ChimeSDK.MeetingSessionConfiguration(MeetingResponse, ParticipantResponse);
	
	const meetingSession = new ChimeSDK.DefaultMeetingSession(configuration, logger, deviceController);

	/*----------------------------------------------*/
	/* Create the observer 							*/
	/*----------------------------------------------*/				
	const observer = {
		  audioVideoDidStart: () 						=> {dosomething();},
		  audioVideoDidStop: sessionStatus 				=> {console.log('Stopped with a session status code: ', sessionStatus.statusCode());},
		  audioVideoDidStartConnecting: reconnecting 	=> {if (reconnecting) {console.log('Attempting to reconnect');}},
		  
		  videoTileDidUpdate: tileState => {
			if (!tileState.boundAttendeeId) {return;}
			meetingSession.audioVideo.bindVideoElement(tileState.tileId, SomeHtmlElement);				
		  }
		};		

	meetingSession.audioVideo.addObserver(observer);
	meetingSession.audioVideo.start();

This code works fine. However the problem is that we want this attendee to be able only to watch the meeting. And if he runs manually the following code, his video/audio will be added to the meeting which we don't want.

	audioInputDevices = await meetingSession.audioVideo.listAudioInputDevices();
	audioOutputDevices = await meetingSession.audioVideo.listAudioOutputDevices();	
	videoInputDevices = await meetingSession.audioVideo.listVideoInputDevices();
		
	const audioInputDeviceInfo = audioInputDevices[0];			
	await meetingSession.audioVideo.chooseAudioInputDevice(audioInputDeviceInfo.deviceId);
	
	const audioOutputDeviceInfo = audioOutputDevices[0];			
	await meetingSession.audioVideo.chooseAudioOutputDevice(audioOutputDeviceInfo.deviceId);			
	
	const videoInputDeviceInfo = videoInputDevices[0];
	await meetingSession.audioVideo.chooseVideoInputDevice(videoInputDeviceInfo.deviceId);	

We thought about adding a condition on the other clients, to check whether a user is allowed to join the discussion or not before adding him to their piles, but this is not a robust solution. Since, eventhough his video wont be shown in the pile of the other clients, he will still be sending video and consuming Chime bandwith. Hi audio will also be mixed with the other participants.

So I was wondering if there is any solution to force an attendee to be in "watch-only" mode and not send any audio nor video ?

Thanks,
regards.

**Comment by ltrung** [comment]
@ThomasCarltonInPerson I am not sure I follow the question. If you want the attendee to not send video, you can just not call `chooseVideoInputDevice` right? Your app can handle the permission on whether an attendee can turn on video and only call that API when they have permission.

**Comment by ThomasCarltonInPerson** [comment]
> @ThomasCarltonInPerson I am not sure I follow the question. If you want the attendee to not send video, you can just not call `chooseVideoInputDevice` right? Your app can handle the permission on whether an attendee can turn on video and only call that API when they have permission (same for audio input permission).

Thanks Itrung for your answer. 

Actually yes I'm not calling `chooseVideoInputDevice `. But I'm talking about the case where the end user forces it or runs this command from the developer tab of his browser for exemple.

How can my app handle this permission since this is happening between the client and Chime SDK ? Can you please explain that ?

Thank you very much.

**Comment by ltrung** [comment]
Just curious, do you export the audio video facade or meeting session object? Otherwise, how do users can call `chooseVideoInputDevice` in console?

**Comment by ThomasCarltonInPerson** [comment]
Please correct me if I'm mistaken. Video facade and meeting session objects are available on the client side. I'm using the following [article](https://github.com/aws-samples/amazon-chime-sdk/tree/main/utils/singlejs) to integrate the SDK as a single JS file in my web app. Hence meeting session objects are accessible from the client side. Am I wrong about that please ?

**Comment by ltrung** [comment]
So unless you explicitly export a variable like in our [demo](https://github.com/aws/amazon-chime-sdk-js/blob/main/demos/browser/app/meetingV2/meetingV2.ts#L373), i don't think it is possible to just open the console and type in `audioVideo.chooseVideoInputDevice`. They would need to know where to put a break point and call it in debug mode.

Regarding your question, unfortunately, we do not currently have a permission feature to prevent users from turning in video so I will mark this as feature request for now and bring back to our team.

A workaround I could think of is using meeting EventBridge ([doc](https://docs.aws.amazon.com/chime/latest/dg/using-events.html)) and listen to `chime:AttendeeVideoStarted` event so that you can tell whether an attendee should be able to share video or not. If not, then you can do appropriate action such as kick that user.

**Comment by michhyun1** [comment]
We actually have this feature in our [React Library demo guide](https://github.com/aws/amazon-chime-sdk-component-library-react/blob/46834ce43f25c00638467671933abc9b17d35f01/src/components/quickStarts.stories.mdx#join-a-meeting-in-view-only-mode). Feel free to take a look there.

**Comment by ltrung** [comment]
@ThomasCarltonInPerson We just launched the ability to control capabilities for each attendee on the backend via [createAttendee](https://docs.aws.amazon.com/chime-sdk/latest/APIReference/API_meeting-chime_CreateAttendee.html) API. Could you check it out?

**Comment by dnnejo** [comment]
We have launched support for attendee capabilities, which control whether an attendee can send or receive audio, video and content.
Refer to the API reference: https://docs.aws.amazon.com/chime-sdk/latest/APIReference/API_meeting-chime_CreateAttendee.html
