### ISSUE TITLE
[Feature request]: `keepAliveTime` option for `createMeeting()`

### ISSUE THREAD

**Issue by marnixhoh** [aws/amazon-chime-sdk-js#1923]
# Community Note
* Please vote for this issue by adding a 👍 reaction to the issue. This will help the community and maintainers from the Amazon Chime SDK team to prioritize this request.
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request.
* Please go through the existing [issues](https://github.com/aws/amazon-chime-sdk-js/issues) to see if your request has already been recommended.
* Please do not use this template for bugs or support. Each individual repository has a PR template, documentation and resources for [troubleshooting](https://github.com/aws/amazon-chime-sdk-js#troubleshooting-and-support).
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.

# Tell us about your request
It would be great to be able to pass a minimum meeting duration (keep-alive time) when creating a meeting.

## What do you want us to build?
The ability to pass a `keepAliveTime` option to the `createMeeting()` call.

## Which Amazon Chime SDK or feature area is this request for?
[amazon-chime-sdk-js](https://github.com/aws/amazon-chime-sdk-js)

## Tell us about the problem you are trying to solve and why is it hard?
The meeting feature I'm working on has the requirement that the meeting stays alive for at least X minutes. Even if there is prolonged inactivity during this time.

## How are you currently solving a problem?
Currently, it seems like the only option is to create a new meeting when the meeting has expired. However, this is rather tricky when someone has already joined the meeting, but has not started it yet. In this scenario, the user is considered to be inactive. But, when this meeting expires and another attendee creates a new meeting to replace the expired one, the joined user, will now have to leave the expired meeting and then again join the new meeting.

## Additional context
/

**Comment by michhyun1** [comment]
@marnixhoh you've probably seen this already, but just attaching here for visibility: https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html#when-does-an-amazon-chime-sdk-meeting-end
Chime Meeting Auto end policy ^

Thanks for bringing this up. We'll take a look at this and determine if its something we can work on in the future.

**Comment by marnixhoh** [comment]
@michhyun1 Yes I have indeed already seen that. But thank you anyway for sharing! :)

No worries. That would be great! Do you happen to know any "workarounds"?

**Comment by michhyun1** [comment]
@marnixhoh unfortunately not that I know of currently. We'll be sure to keep track of this item. Thanks!

**Comment by luchinilato** [comment]
I have the same problem and this is limiting me a lot

**Comment by Brenerss** [comment]
This feature will help me to make better my project and remove there limits

**Comment by thiagosilvadev** [comment]
Same here. The 5 min auto-end policy gave me a huge problem. This feature would solve my problem

**Comment by marnixhoh** [comment]
@itsbeautifullife Yes that's correct... I really don't like this either.

I "solved" it by checking server-side if the meeting exists. If it no longer exists, I just create a new meeting.

**Comment by yochum** [comment]
Closing this issue as it does not directly pertain to the Chime SDK for JavaScript. Please do reach out through your AWS account team or contact us in AWS Console for further help on this topic. Much appreciated.
