### ISSUE TITLE
missing TURN credentials - falling back to fetch

### ISSUE THREAD

**Issue by ildar-shamilov-clearscale** [aws/amazon-chime-sdk-js#1928]
### What happened and what did you expect to happen?

- Deploy chime demo app locally "amazon-chime-sdk-js\demos\browser"
- Join multiple users
- Enable cameras on for users
- See random flickering, hanging, dissapearing of video tiles
happens on any platform
Looks like it works fine for only one user online.

### Have you reviewed our existing documentation?

- [X] GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [X] FAQs [page](https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html)
- [X] README [page](https://github.com/aws/amazon-chime-sdk-js#amazon-chime-sdk-for-javascript)
- [X] Feature-specific [guides](https://github.com/aws/amazon-chime-sdk-js#guides)

### Reproduction steps

- Deploy chime demo app locally "amazon-chime-sdk-js\demos\browser"
- Join multiple users
- Enable cameras on for users
- See random flickering, hanging, dissapearing of video tiles
happens on any platform

### Amazon Chime SDK for JavaScript version

2.23.0

### What browsers are you seeing the problem on?

Chrome/Safari

### Browser version

latest

### Browser console logs

setting nameplate to test
VM10:2 setting attendeeId to 92a92532-143b-bafb-b068-f029d4a9daf5
2VM10:2 2022-01-12T18:26:35.533Z [INFO] SDK - API/DefaultAudioVideoFacade/a6600957-c66d-4de6-932f-68d4bd1c2713/92a92532-143b-bafb-b068-f029d4a9daf5/hasStartedLocalVideoTile null -> false
VM10:2 2022-01-12T18:26:35.533Z [INFO] SDK - API/DefaultAudioVideoFacade/a6600957-c66d-4de6-932f-68d4bd1c2713/92a92532-143b-bafb-b068-f029d4a9daf5/getAllVideoTiles
VM10:2 2022-01-12T18:26:35.534Z [INFO] SDK - API/DefaultAudioVideoFacade/a6600957-c66d-4de6-932f-68d4bd1c2713/92a92532-143b-bafb-b068-f029d4a9daf5/getAllVideoTiles
VM10:2 2022-01-12T18:26:35.534Z [INFO] SDK - API/DefaultAudioVideoFacade/a6600957-c66d-4de6-932f-68d4bd1c2713/92a92532-143b-bafb-b068-f029d4a9daf5/hasStartedLocalVideoTile null -> false
2VM10:2 2022-01-12T18:26:35.534Z [INFO] SDK - API/DefaultAudioVideoFacade/a6600957-c66d-4de6-932f-68d4bd1c2713/92a92532-143b-bafb-b068-f029d4a9daf5/getAllVideoTiles
2VM10:2 2022-01-12T18:26:35.534Z [INFO] SDK - API/DefaultAudioVideoFacade/a6600957-c66d-4de6-932f-68d4bd1c2713/92a92532-143b-bafb-b068-f029d4a9daf5/hasStartedLocalVideoTile null -> false
2VM10:2 2022-01-12T18:26:35.534Z [INFO] SDK - API/DefaultAudioVideoFacade/a6600957-c66d-4de6-932f-68d4bd1c2713/92a92532-143b-bafb-b068-f029d4a9daf5/getAllVideoTiles
VM10:2 2022-01-12T18:26:35.534Z [INFO] SDK - serial group task AudioVideoUpdate/a6600957-c66d-4de6-932f-68d4bd1c2713/92a92532-143b-bafb-b068-f029d4a9daf5/Timeout15000ms/UpdateSession was canceled due to subtask AudioVideoUpdate/a6600957-c66d-4de6-932f-68d4bd1c2713/92a92532-143b-bafb-b068-f029d4a9daf5/Timeout15000ms/UpdateSession/SetLocalDescriptionTask error: Failed to execute 'setLocalDescription' on 'RTCPeerConnection': Failed to set local offer sdp: Failed to set local video description recv parameters for m-section with mid='1'.
VM10:2 2022-01-12T18:26:35.534Z [INFO] SDK - serial group task AudioVideoUpdate/a6600957-c66d-4de6-932f-68d4bd1c2713/92a92532-143b-bafb-b068-f029d4a9daf5 was canceled due to subtask AudioVideoUpdate/a6600957-c66d-4de6-932f-68d4bd1c2713/92a92532-143b-bafb-b068-f029d4a9daf5/Timeout15000ms error: serial group task AudioVideoUpdate/a6600957-c66d-4de6-932f-68d4bd1c2713/92a92532-143b-bafb-b068-f029d4a9daf5/Timeout15000ms/UpdateSession was canceled due to subtask AudioVideoUpdate/a6600957-c66d-4de6-932f-68d4bd1c2713/92a92532-143b-bafb-b068-f029d4a9daf5/Timeout15000ms/UpdateSession/SetLocalDescriptionTask error: Failed to execute 'setLocalDescription' on 'RTCPeerConnection': Failed to set local offer sdp: Failed to set local video description recv parameters for m-section with mid='1'.
2022-01-12T18:26:35.534Z [INFO] SDK - transitioning from Updating to Connected with FinishUpdating
VM10:2 2022-01-12T18:26:35.534Z [INFO] SDK - failed to update audio-video session
VM10:2 2022-01-12T18:26:35.534Z [INFO] SDK - handling status: TaskFailed
VM10:2 2022-01-12T18:26:36.027Z [INFO] SDK - transitioning from Connected to Connecting with Reconnect
VM10:2 2022-01-12T18:26:36.027Z [INFO] SDK - running task AudioVideoReconnect/a6600957-c66d-4de6-932f-68d4bd1c2713/92a92532-143b-bafb-b068-f029d4a9daf5

**Comment by ShutoYamada** [comment]
I am facing the same situation.

In my case, the error occurred when I made a call between the same networks.
On the other hand, I can talk on different networks without any problems.

Maybe the Turn Server is down.

**Comment by ildar-shamilov-clearscale** [comment]
Bumped to 2.24.0, works fine now.
