### ISSUE TITLE
Video tiles does not appear even though there are no errors

### ISSUE THREAD

**Issue by Coachtube** [aws/amazon-chime-sdk-js#1930]
### What happened and what did you expect to happen?

Reopening the https://github.com/aws/amazon-chime-sdk-js/issues/1877

Hi guys!
I did what you suggested in the #1877, but there is no visuals rendered in the required area. Please find the attachments below
[localhost-1642068324140.log](https://github.com/aws/amazon-chime-sdk-js/files/7861893/localhost-1642068324140.log)

<img width="570" alt="1" src="https://user-images.githubusercontent.com/30532310/149310838-196d3b2d-6097-44f0-b429-56f82ce269e3.png">

<img width="960" alt="2" src="https://user-images.githubusercontent.com/30532310/149310871-2c07d999-3ac8-4f34-a435-fcce09f64bc0.png">

### Have you reviewed our existing documentation?

- [X] GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [X] FAQs [page](https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html)
- [X] README [page](https://github.com/aws/amazon-chime-sdk-js#amazon-chime-sdk-for-javascript)
- [X] Feature-specific [guides](https://github.com/aws/amazon-chime-sdk-js#guides)

### Reproduction steps

- Asking our custom Lambda endpoint to create the meeting session and the attendee
- Recieving the required objects back
- Trying to establish the connection and render the video like you did here https://github.com/aws-samples/amazon-chime-sdk-classroom-demo/blob/master/app/chime/ChimeSdkWrapper.ts starting from 196 line
- Get empty tiles objects

### Amazon Chime SDK for JavaScript version

2.23.0

### What browsers are you seeing the problem on?

Latest Chrome, Brave, SRWare Iron browsers

### Browser version

93.0.4750

### Browser console logs

[localhost-1642068324140.log](https://github.com/aws/amazon-chime-sdk-js/files/7861906/localhost-1642068324140.log)

**Comment by Coachtube** [comment]
@michhyun1 thanks for the point, but, unfortunately this is also not working. Please find the screenshots and logs below

![image](https://user-images.githubusercontent.com/30532310/150520134-51c6bf7e-6f48-4ec1-8d55-f73e15dc0a78.png)

![image](https://user-images.githubusercontent.com/30532310/150520237-1251b7c3-7267-4ef2-b5b1-ced710fa1a85.png)

[localhost-1642764934187.log](https://github.com/aws/amazon-chime-sdk-js/files/7912965/localhost-1642764934187.log)

**Comment by michhyun1** [comment]
Perhaps you can remove the startLocalVideoTile() before the audioVideo.start() call, since youre calling it after the audioVideo starts via the observer callback.

Just for debugging purposes, could you perhaps attach the startLocalVideo call to a button and click on the button to be able to see what happens when you click on it? Rather than be in the observer callback.

**Comment by Coachtube** [comment]
@michhyun1 here it is

[localhost-1643123953349.log](https://github.com/aws/amazon-chime-sdk-js/files/7934817/localhost-1643123953349.log)

<img width="960" alt="fe" src="https://user-images.githubusercontent.com/30532310/151006181-8477654d-3fd9-4cbf-8d7f-6c18ac7cbb25.png">

<img width="672" alt="cd" src="https://user-images.githubusercontent.com/30532310/151006230-7ba9c9d7-9dd1-432d-8045-66cb3bcffe22.png">

**Comment by michhyun1** [comment]
@Coachtube thanks for the quick reply - is it possible to try this without the usb camera that you're defaulting to?

**Comment by Coachtube** [comment]
@michhyun1 this is an only option to use the USB camera on my ROG Zepyrus, since it dosen't have a built in one.

**Comment by michhyun1** [comment]
@Coachtube usually the usb cameras have a light that comes on when the device is selected - can you confirm if the usb camera light turns on? 

Perhaps from the developer console, you can try:

```
const videoStream = await navigator.mediaDevices.getUserMedia({video: true}); // Check if your camera light is on after this call
const videoElement = document.getElementById('video-streams');  // select your video element here
videoElement.srcObject = videoStream;
videoElement.playsInline = true;
videoElement.autoplay = true;
videoElement.play();
```

Does this work for you?

**Comment by ltrung** [comment]
@Coachtube Just to verify that the webcam work, can you try https://webrtc.github.io/samples/src/content/devices/input-output/ to see whether you can get a video stream?
I took a look at the log and it all seems fine to me (Also can you try JS SDK 2.26.0 and Chrome latest).

**Comment by Coachtube** [comment]
Guys! I woudn't be bothering you without checking that the camera is working. I'm using the same set making calls for months with Zoom, Google Meet, Telegram Desktop and even AWS Kinesis Video Streams Sample is perfectly working on the very same setting.

![image](https://user-images.githubusercontent.com/30532310/152647930-88e8d263-ed5f-43d7-be02-c8d660b85027.png)

![image](https://user-images.githubusercontent.com/30532310/152648205-0bbc9e16-d39d-4e6a-9d1b-26b51a5d8d02.png)

**Comment by ltrung** [comment]
Sorry @Coachtube, i know it is obvious but just want to make sure it is not a camera issue. I have looked at the logs but did not see any potential issue (Thanks for adding the binding log). For next step:
- Have you tried the [JS SDK meeting demo](https://github.com/aws/amazon-chime-sdk-js/tree/main/demos/browser/app/meetingV2)? That would tell us whether this is something with our JS SDK or your code.
- Have you tried what Michael suggested above:
```
const videoStream = await navigator.mediaDevices.getUserMedia({video: true}); // Check if your camera light is on after this call
const videoElement = document.getElementById('video-streams');  // select your video element here
videoElement.srcObject = videoStream;
videoElement.playsInline = true;
videoElement.autoplay = true;
videoElement.play();
```
-  Another thing to try is to look at `chrome://webrtc-internals` and see if there is any outbound video going out. If there is then it is probably just a binding/video element issue.
- You can also open a AWS support case where you can share a private link to your app so we can directly look at it.

Thanks for being patient.

**Comment by xuesichao** [comment]
Close this issue for now due to inactivity. Please let us know if you still have the issue and we will reopen it. @Coachtube
