### ISSUE TITLE
iOS device cant automatically reconnect to call after restore internet connection 

### ISSUE THREAD

**Issue by ArtemZakharchuk** [aws/amazon-chime-sdk-js#1931]
### What happened and what did you expect to happen?

Expected: 
After restoring the internet connection iOS device should successfully reconnect to call
Actual: 
iOS device cant reconnect to call after restoring the internet connection. 

### Have you reviewed our existing documentation?

- [X] GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [X] FAQs [page](https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html)
- [X] README [page](https://github.com/aws/amazon-chime-sdk-js#amazon-chime-sdk-for-javascript)
- [X] Feature-specific [guides](https://github.com/aws/amazon-chime-sdk-js#guides)

### Reproduction steps

Can be reproduced on demo/browser meeting example from chime SDK. 
- Create a meeting. 
- Join to call from an iOS device (e.g. iPhone)
- Turn off Internet connection on the device and wait ~30 seconds
- Turn on back Internet connection on the device

### Amazon Chime SDK for JavaScript version

2.23.1

### What browsers are you seeing the problem on?

Chrome for iOS, iOS Safari

### Browser version

97.0.4692.84, 15.2

### Browser console logs

[Console.txt](https://github.com/aws/amazon-chime-sdk-js/files/7863518/Console.txt)

**Comment by jing-chen1** [comment]
Hi @ArtemZakharchuk 

Thanks for reporting this issue! I can reproduce it on the IPhone. Tested disconnecting it from the internet for 10s, 30s, 1 min and 2min, and there is no auto-reconnect in all cases. I think it may be related OpenSignalingConnection. We have a known issue that there is no `WebSocketClosed` event after `WebSocketClosing` when the Internet connection is back. We are working on it.

For more details: [Reconnection timeout on VPN](https://github.com/aws/amazon-chime-sdk-js/issues/1985)
Corresponding PR: [Fix vpn reconnecting issue](https://github.com/aws/amazon-chime-sdk-js/pull/1993)

**Comment by vidya-mohan** [comment]
@ArtemZakharchuk could you please try NPM 2.27.0 and see if you are hitting it and if so share the details?

**Comment by ArtemZakharchuk** [comment]
@vidya-mohan Ok. I try a new version and share the results with you.

**Comment by ArtemZakharchuk** [comment]
@vidya-mohan Sorry for the delayed response. The problem is gone after the SDK update.

**Comment by michhyun1** [comment]
@ArtemZakharchuk thanks for the reply - closed this issue for now. Please let us know if you have any other issues.
