### ISSUE TITLE
Safari 15+ unable to select a microphone that's attached to a camera

### ISSUE THREAD

**Issue by marrionluaka** [aws/amazon-chime-sdk-js#1935]
### What happened and what did you expect to happen?

**Expected:**
When selecting a microphone that's attached to a camera (that belongs to the same physical device), the mic in question should be selected and should be able to pick up my voice.

**Actual:**
The selected microphone does not pick up my voice.

**Extra notes:**
It seems to only be an issue in Safari 15+

https://user-images.githubusercontent.com/11777364/149431901-b2320445-793d-4580-8d26-f4f6c4093693.mov

### Have you reviewed our existing documentation?

- [X] GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [X] FAQs [page](https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html)
- [X] README [page](https://github.com/aws/amazon-chime-sdk-js#amazon-chime-sdk-for-javascript)
- [X] Feature-specific [guides](https://github.com/aws/amazon-chime-sdk-js#guides)

### Reproduction steps

1. Open Safari 15+

2. Navigate to an AWS Chime Demo (refer to the above video)

3. Plug in an external Camera that contains a microphone attached to it (i.e.: HD Pro Webcam C920)

4. On the `Select Devices` page, select your external mic and camera

### Amazon Chime SDK for JavaScript version

2.24.0

### What browsers are you seeing the problem on?

Safari

### Browser version

15+

### Browser console logs

N/A

**Comment by michhyun1** [comment]
I just tried this on my macbook pro 16", and I was not able to reproduce with my external webcam. I am able to switch between the macbook mic and the external webcam mic. 

@marrionluaka Is there any way you can send us some browser logs for this case?

**Comment by marrionluaka** [comment]
Hi @michhyun1 thanks for getting back to me so quickly! Attached please find the browser logs you requested.
[Console.txt](https://github.com/aws/amazon-chime-sdk-js/files/7872956/Console.txt)

**Comment by michhyun1** [comment]
I mostly just see logs like this:
```
[Error] WebSocket connection to 'wss://signal.m2.en1.app.chime.aws/control/01accad1-58aa-4ab1-a4c2-bccfc8402713?X-Chime-Control-Protocol-Version=3&X-Amzn-Chime-Send-Close-On-Error=1&X-Amzn-Version=2.24.0&X-Amzn-User-Agent=ios-15' failed: The Internet connection appears to be offline.
```

Can you please check that the internet connection is okay? Also, I didnt see any calls to `chooseAudioInputDevice`, so not which should be called when you switch audio input devices.

**Comment by marrionluaka** [comment]
There were no issues with the internet connection and yes these logs were taken when I switched between audio input devices (just like the video above).

**Comment by marrionluaka** [comment]
Hi @michhyun1 Any updates on this issue?

**Comment by xuesichao** [comment]
@marrionluaka Hi, sorry for the late reply. Could you please try to reproduce the same issue using this WebRTC sample?
https://webrtc.github.io/samples/src/content/devices/input-output/

**Comment by xuesichao** [comment]
I was not able to reproduce this issue with external camera with JS SDK 2.24.0 and Safari 15.3.

**Comment by marrionluaka** [comment]
Hi @xuesichao I can no longer reproduce the issue after I've upgraded to the latest version of the SDK 2.26.1. Closing for now.
