### ISSUE TITLE
Turning video on during a meeting causes meeting to stop and reconnect

### ISSUE THREAD

**Issue by Demi-ob** [aws/amazon-chime-sdk-js#1940]
### What happened and what did you expect to happen?

Everything works well if no video is turned on but once a video gets turned on, it causes the meeting session to reconnect and i get the following warning in console:

```react_devtools_backend.js:4045 2022-01-16T10:10:48.179Z [WARN] SDK - will retry due to status code TaskFailed and error: serial group task AudioVideoUpdate/6d6060af-e9e7-488f-84da-b90843010706/3988f79c-d61d-9e54-fa63-1b2bd8a778ab was canceled due to subtask AudioVideoUpdate/6d6060af-e9e7-488f-84da-b90843010706/3988f79c-d61d-9e54-fa63-1b2bd8a778ab/Timeout15000ms error: serial group task AudioVideoUpdate/6d6060af-e9e7-488f-84da-b90843010706/3988f79c-d61d-9e54-fa63-1b2bd8a778ab/Timeout15000ms/UpdateSession was canceled due to subtask AudioVideoUpdate/6d6060af-e9e7-488f-84da-b90843010706/3988f79c-d61d-9e54-fa63-1b2bd8a778ab/Timeout15000ms/UpdateSession/SetLocalDescriptionTask error: Failed to execute 'setLocalDescription' on 'RTCPeerConnection': Failed to set local offer sdp: Failed to set local video description recv parameters for m-section with mid='1'```

Expectation is turning a video on should not trigger a reconnection

### Have you reviewed our existing documentation?

- [X] GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [X] FAQs [page](https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html)
- [X] README [page](https://github.com/aws/amazon-chime-sdk-js#amazon-chime-sdk-for-javascript)
- [X] Feature-specific [guides](https://github.com/aws/amazon-chime-sdk-js#guides)

### Reproduction steps

Start a meeting session with the video turned off and then turn on the video

### Amazon Chime SDK for JavaScript version

2.21.1

### What browsers are you seeing the problem on?

Chrome on Mac

### Browser version

Version 97.0.4692.71 (Official Build) (arm64)

### Meeting and Attendee ID Information.

meetingId: "6d6060af-e9e7-488f-84da-b90843010706"
attendeeId: "3988f79c-d61d-9e54-fa63-1b2bd8a778ab"

### Browser console logs

react_devtools_backend.js:4045 2022-01-16T10:22:25.339Z [WARN] SDK - will retry due to status code TaskFailed and error: serial group task AudioVideoUpdate/6d6060af-e9e7-488f-84da-b90843010706/3988f79c-d61d-9e54-fa63-1b2bd8a778ab was canceled due to subtask AudioVideoUpdate/6d6060af-e9e7-488f-84da-b90843010706/3988f79c-d61d-9e54-fa63-1b2bd8a778ab/Timeout15000ms error: serial group task AudioVideoUpdate/6d6060af-e9e7-488f-84da-b90843010706/3988f79c-d61d-9e54-fa63-1b2bd8a778ab/Timeout15000ms/UpdateSession was canceled due to subtask AudioVideoUpdate/6d6060af-e9e7-488f-84da-b90843010706/3988f79c-d61d-9e54-fa63-1b2bd8a778ab/Timeout15000ms/UpdateSession/SetLocalDescriptionTask error: Failed to execute 'setLocalDescription' on 'RTCPeerConnection': Failed to set local offer sdp: Failed to set local video description recv parameters for m-section with mid='1'.

**Comment by w-okada** [comment]
Maybe the same issue. Connect and reconnect are repeated in official demo.

https://user-images.githubusercontent.com/48346627/149749327-868244c8-b2a8-41c1-949a-7705b3a020b3.mp4

**Comment by michhyun1** [comment]
@Demi-ob I think this issue would be solved if you upgrade to 2.24.0 or higher.

**Comment by Demi-ob** [comment]
Thanks. Upgrading fixed it for me
