### ISSUE TITLE
Not able to start recording c# SDK S3 Bucket Issue

### ISSUE THREAD

**Issue by DhavalKholiya3** [aws/amazon-chime-sdk-js#1942]
I am using .net sdk for meetings. I am trying to start recording but following getting exception 
I have tried to assigned all the required permissions to user and also created bucket as public but I am still getting following error.

![S3BuckertError](https://user-images.githubusercontent.com/66063891/149775270-e6b72a59-9e84-47a1-9c20-ab367de4e226.png)
Please suggest me possible solutions.

**S3 Bucket policy not valid/present for Sink arn:aws:s3:::chimemeeting/df8e8ebe-841a-4ef0-8815-a686630f0706/**

following is my code snippets

public async Task<string> start_capture(string title = "")
        {
            string result = "";
            try
            {
                // set up client
                var chimeClient = new AmazonChimeClient(accessKeyId, secretAccessKey, RegionEndpoint.USEast1);

                var meeting = await chimeClient.GetMeetingAsync(new Amazon.Chime.Model.GetMeetingRequest
                {
                    MeetingId = title
                });
                
                string meetingRegion = meeting.Meeting.MediaRegion;
                
                string MeetId = meeting.Meeting.MeetingId.Replace("-", "");
               
                string captureS3Destination = "arn:aws:s3:::chimemeeting/" + MeetId;
              
                // start record meeting
                var pipelineInfo = await chimeClient.CreateMediaCapturePipelineAsync(new Amazon.Chime.Model.CreateMediaCapturePipelineRequest
                {
                    SourceType = MediaPipelineSourceType.ChimeSdkMeeting,                   
                    SourceArn = "arn:aws:chime::" + AWS_AccountId + ":meeting:" + meeting.Meeting.MeetingId,
                    SinkType = MediaPipelineSinkType.S3Bucket,
                    SinkArn = captureS3Destination
                });
                string recordingpipelineId = pipelineInfo.MediaCapturePipeline.MediaPipelineId;
                result = recordingpipelineId;
               
            }
            catch (Exception ex)
            {
                throw;
            }
            return result;
        }

**Comment by michhyun1** [comment]
@DhavalKholiya3 Can you please take a look at this issue? - https://github.com/aws/amazon-chime-sdk-js/issues/1558

**Comment by nehtambe** [comment]
Adding a blog link for reference - https://aws.amazon.com/blogs/business-productivity/capture-amazon-chime-sdk-meetings-using-media-capture-pipelines/

**Comment by DhavalKholiya3** [comment]
Thanks It's resolved now meeting is getting recorded.

Now I am looking on how to generate single from from multiple recorded chunks. I am using .Net sdk for meetings and single JS for meetings.

Can you provide sample code or solution for .NET how to concat this recording files in single file?

**Comment by nehtambe** [comment]
You can check the section **Demo for combining the meeting artifacts** in the above shared blog.
Demo for combining the chunks - https://github.com/aws-samples/amazon-chime-media-capture-pipeline-demo
Let us know if this helps.

**Comment by DhavalKholiya3** [comment]
I am already referring this demo. But we are using .net SDK in our project not node js.
Currently I am facing following issues.

1. Currently files are getting recorded in 5 seconds chunk. Is there any setting or parameter available we can set it to record meeting in single file in one go instead of applying solution to combine it?

2. I am also facing issue of sometime audio getting properly and sometime not getting properly

3. I am getting video on my screen some time when I try to stop video and start again, then video is not getting display on screen. Sometime its getting displayed and sometime its not getting displayed

**Comment by MingcongQi** [comment]
Hi,
#1 which stream do you want to combine?
#2 could you give more information about how "not getting properly"?
#3 We are doing a fix for this issue in our backend
