### ISSUE TITLE
Incorrect video chunks are generated for shared screen in Media Capture Pipeline

### ISSUE THREAD

**Issue by yoshitsugu** [aws/amazon-chime-sdk-js#1943]
### What happened and what did you expect to happen?

I don't know here is the right place to report this kind of issue. Please close if not.
(Please tell me where is the right place to report if you know...)
I've tried Media Capture Pipelines following this article.
https://aws.amazon.com/blogs/business-productivity/capture-amazon-chime-sdk-meetings-using-media-capture-pipelines/
I've noticed sometimes video for recording shared screen is not what I expected.

- Some video chunks show previous shared screen's image (maybe the image of the last frame of previous shared screen?) for several seconds before start to show next shared screen.
- Some video chunks which has above problem has long duration (like 13 seconds).
  - the article above says `All meeting artifacts are delivered to the S3 bucked designated by the builder in up to five second file chunks throughout the meeting.`

### Have you reviewed our existing documentation?

- [X] GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [X] FAQs [page](https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html)
- [X] README [page](https://github.com/aws/amazon-chime-sdk-js#amazon-chime-sdk-for-javascript)
- [X] Feature-specific [guides](https://github.com/aws/amazon-chime-sdk-js#guides)

### Reproduction steps

0. 1 attendee In a meeting.
1. Start recording with following configuration
```
{
    "SourceType": "ChimeSdkMeeting",
    "SourceArn": "arn:aws:chime::[ACCOUNT-ID]:meeting:[MEETING-ID]",         
    "SinkType": "S3Bucket",
    "SinkArn": "arn:aws:s3:::[BUCKET-NAME]/[Prefix]",
    "ChimeSdkMeetingConfiguration": {
        "SourceConfiguration": {
            "SelectedVideoStreams": {
                "AttendeeIds": ["[ATTENDEE-ID]"],
                "ExternalUserIds": ["[EXTERNAL-USER-ID]"]
            }
        },
        "ArtifactsConfiguration": {
            "Audio": {
                "MuxType": "AudioWithActiveSpeakerVideo"
            },
            "Video": {
                "State": "Disabled",
                "MuxType": "VideoOnly"
            },
            "Content": {
                "State": "Enabled",
                "MuxType": "ContentOnly"
            }
        }
    }
}
```
2. Start sharing screen
3. Stop sharing screen
4. Start sharing screen (after like 5-6 seconds)
5. Stop sharing screen
6. Stop recording.
7. Check the generated `video` direcoty.

### Amazon Chime SDK for JavaScript version

2.25.0

### What browsers are you seeing the problem on?

Chrome

### Browser version

97.0.4692.71

### Browser console logs

N / A

**Comment by nehtambe** [comment]
Hi, we are looking into this issue. We will update once it is fixed.

**Comment by yoshitsugu** [comment]
@nehtambe thank you for your response. please notify me if you have any update.

**Comment by yoshitsugu** [comment]
@nehtambe Do you have any idea when it will be fixed?

**Comment by sinanliuAmazon** [comment]
Hi, we will deploy the fix to ap-northeast-1 region in around 2 - 3 weeks.

**Comment by sinanliuAmazon** [comment]
Hi, the fix is deployed to ap-northeast-1 region, please let us know if you still see this issue.

**Comment by yoshitsugu** [comment]
@sinanliuAmazon I've confirmed it's fixed and I can see expected video data. Thank you very much!
