### ISSUE TITLE
The video bitrate beyond the selected value?

### ISSUE THREAD

**Issue by dathacky** [aws/amazon-chime-sdk-js#1946]
I noticed that the bitrate value during the meeting exceeds the bitrate value previously selected, is this a bug? If not please explain bitrate to help me. Thank you!

<img width="395" alt="Screen Shot 2022-01-20 at 16 42 56" src="https://user-images.githubusercontent.com/37299929/150314800-ef2c9c4b-0eb8-4260-b656-a0401d0c9563.png">
<img width="758" alt="Screen Shot 2022-01-20 at 16 45 07" src="https://user-images.githubusercontent.com/37299929/150314900-7b442253-32e4-4514-a8e0-52a849a16ad5.png">

### Have you reviewed our existing documentation?

- [X] GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [X] FAQs [page](https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html)
- [X] README [page](https://github.com/aws/amazon-chime-sdk-js#amazon-chime-sdk-for-javascript)
- [X] Feature-specific [guides](https://github.com/aws/amazon-chime-sdk-js#guides)

### Reproduction steps

Join meeting and select resolution 360p 15fps 600 kbps max

### Amazon Chime SDK for JavaScript version

2.25.0

### What browsers are you seeing the problem on?

Chrome 

### Browser version

Version 97.0.4692.71 (Official Build) (x86_64)

### Browser console logs

No

**Comment by ltrung** [comment]
@dathacky Hi, thanks for reporting. We are currently looking at this issue. Could you let us know how you reproduced it in our meeting demo?

**Comment by dathacky** [comment]
> @dathacky Hi, thanks for reporting. We are currently looking at this issue. Could you let us know how you reproduced it in our meeting demo?

I joined the meeting and select resolution 360p 15fps 600 kbps max

**Comment by ltrung** [comment]
@dathacky Can you still reproduce this issue? We pushed out some fixes in 2.26 version.

**Comment by dathacky** [comment]
it's fixed, thank you
