### ISSUE TITLE
Black background in video element - IPad 12.9 Inch IOS 15.1 version

### ISSUE THREAD

**Issue by Abhilash-Ram** [aws/amazon-chime-sdk-js#1947]
### What happened and what did you expect to happen?

We updated Chime SDK to 2.24 and, this resolved Ipad device video issue. Now we are facing black screen in video element whenever we minimize the safari browser in ipad and resume that browser window back. At the time of minimize, we saw black screen of ipad device video element in other users screen but after switching back to safari browser in ipad device we see only black screen in video element.

Chime SDK version: 2.24
Device: Apple Ipad 12.9 inch IOS15.1

### Have you reviewed our existing documentation?

- [X] GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [X] FAQs [page](https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html)
- [X] README [page](https://github.com/aws/amazon-chime-sdk-js#amazon-chime-sdk-for-javascript)
- [X] Feature-specific [guides](https://github.com/aws/amazon-chime-sdk-js#guides)

### Reproduction steps

1. Join a meeting using chime sdk in Ipad 12.9 inch model
2. Start the video
3. minimize the browser window
4. Now we see black screen in video element from other users in that party.
5. Open browser window again to resume the meeting. 
6. In this step, we see only black screen in video element. 

### Amazon Chime SDK for JavaScript version

2.24

### What browsers are you seeing the problem on?

Ipad Safari

### Browser version

15.1

### Meeting and Attendee ID Information.

Meeting Id: 31520a77-faaa-45bf-8d04-a73b8fc60706
External Meeting Id: tupp1cabhilashtestvtup15352fa79
Attendee Id: c8c5cff5-e640-3020-929a-112a1f544ef1

### Browser console logs

We don't have it right now. I can post the console logs in upcoming comment

**Comment by jing-chen1** [comment]
Hi @Abhilash-Ram,

Thanks for your interest in Chime SDK for JavaScript. Here are the steps I do to reproduce (IPad Pro 11 / IOS 15.1):
* Join a meeting, one attendee from Ipad/Safari, and the other one from Mac/Chrome
* Turn on the video for both attendees
* If I switch to other application: I can still see the video of Ipad
* If I press the `home` button and put the browsers in the background: I can only see black screen from Mac Chrome

I guess "minimize the browser window" means you put the browsers in the background? If so, it is a known issue. This is the default behavior that others will see black tile in Safari/IOS if the user "minimize the window". For better user experience, please try our [Chime SDK iOS](https://github.com/aws/amazon-chime-sdk-ios).

**Comment by Abhilash-Ram** [comment]
Hey @jing-chen1 m
Yes, minimize the browser window.

**Comment by jing-chen1** [comment]
Then it is a default behavior. For more details, please check our [FAQ](https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html#i-notice-that-if-i-turn-on-camera-and-put-the-browsers-in-background-others-in-the-meeting-will-see-black-tile-in-safarichromefirefox-in-ios-and-frozen-tile-in-chrome-in-android-is-this-a-known-issue)
Closing this ticket, please feel free to reopen it if you still have problem
