### ISSUE TITLE
Is there a direct download url for a minified version?

### ISSUE THREAD

**Issue by Aarondorn2** [aws/amazon-chime-sdk-js#195]
### What are you trying to do?
I would like to Add the javascript to my app dynamically instead of through npm so as to reduce my app's footprint.  I'm looking for a link similar to this: https://sdk.amazonaws.com/js/aws-sdk-2.648.0.min.js 

### How can the documentation be improved to help your use case?
Provide a link for downloading the sdk minified js directly

### What documentation have you looked at so far?
all of it

**Comment by simmkyu** [comment]
Chime SDK repo does not provide a link for downloading a minified JS file. I created PR (#203 ) for adding a bundling script. Once merged, you can generate a minified JS file from the latest release of `amazon-chime-sdk-js` and embed it in your web application.

**Comment by vidya-mohan** [comment]
@Aarondorn2 https://github.com/aws/amazon-chime-sdk-js/pull/203 is merged so i am resolving this issue
