### ISSUE TITLE
Limite of data on realtime

### ISSUE THREAD

**Issue by Brenerss** [aws/amazon-chime-sdk-js#1955]
### What happened and what did you expect to happen?

I tried to pass a relatively large json with array of objects and it returned me the following message

"SDK - failed with status code RealtimeApiFailed and error: Data size has to be less than 2048 bytes"

Is it impossible to transfer data larger than that?
If not, what alternative do you suggest?

### Have you reviewed our existing documentation?

- [X] GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [X] FAQs [page](https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html)
- [X] README [page](https://github.com/aws/amazon-chime-sdk-js#amazon-chime-sdk-for-javascript)
- [X] Feature-specific [guides](https://github.com/aws/amazon-chime-sdk-js#guides)

### Reproduction steps

npm run start

### Amazon Chime SDK for JavaScript version

2.17.0

### What browsers are you seeing the problem on?

Chrome

### Browser version

97.0.4692.71 (Versão oficial) 64 bits

### Browser console logs

none

**Comment by ltrung** [comment]
Yes, we currently limit the data size to less than 2048 bytes. Could you try some compression 3rd party tool to compress the json file?

**Comment by Brenerss** [comment]
i used another way to send message

**Comment by ltrung** [comment]
Just curious, did you end up use another 3rd party tool to send message?

**Comment by Brenerss** [comment]
No, instead of passing all the json, I only pass the object or values ​​that I want to update and when I receive it, I do the replace

**Comment by mauriciogior** [comment]
If anyone is interested, I had the same issue and solved it by sending the JSON in chunks.

Here is the gist:
```javascript
// uuid gen fn
function uuidv4() {
  return ([1e7]+-1e3+-4e3+-8e3+-1e11).replace(/[018]/g, c =>
    (c ^ crypto.getRandomValues(new Uint8Array(1))[0] & 15 >> c / 4).toString(16)
  );
}

// fn to send message, will chunk if > 1.8kb
function sendMessage(message) {
  message = JSON.stringify(message) || "{}";
  var messageSize = new Blob([message]).size;
  var maxSizeAllowed = 1800; // 1.8kb -- little margin
  if (maxSizeAllowed < messageSize) {
    var messageId = uuidv4();
    var parts = message.match(new RegExp(".{1,"+ maxSizeAllowed +"}", "g"));
    for (var i in parts) {
      this.audioVideo.realtimeSendDataMessage("signal", JSON.stringify({
        messageId: messageId, part: i, total: parts.length, chunk: parts[i]
      }));
    }
  } else {
    this.audioVideo.realtimeSendDataMessage("signal", message);
  }
}

// fn to receive message, will wait & merge if chunked
this.audioVideo.realtimeSubscribeToReceiveDataMessage("signal", function(dataMessage) {
  var json = null;

  try {
    json = JSON.parse(String.fromCharCode.apply(null, dataMessage.data))
  } catch (e) { }

  if (json.messageId && json.chunk) {
    if (!this.socketChunks[json.messageId]) {
      this.socketChunks[json.messageId] = {
        total: parseInt(json.total),
        chunks: {}
      };
    }

    this.socketChunks[json.messageId].chunks["part:" + json.part] = json.chunk;

    // Has all parts
    if (Object.keys(this.socketChunks[json.messageId].chunks).length == this.socketChunks[json.messageId].total) {
      var formedJson = "";
      for (var i = 0; i < this.socketChunks[json.messageId].total; i++) {
        formedJson += this.socketChunks[json.messageId].chunks["part:" + i];
      }

      try {
        json = JSON.parse(formedJson);
      } catch (e) { }

      delete this.socketChunks[json.messageId];
      
      // Total is on `json`

    } else {
      // Missing chunks
      return;
    }

  } else {
    // Not chunked!
  }
});
```

**Comment by ltrung** [comment]
@mauriciogior Thanks. Another approach is use 3rd party library like pako to compress the message.
