### ISSUE TITLE
Possible solution for Testing without browser

### ISSUE THREAD

**Issue by nandzz** [aws/amazon-chime-sdk-js#1959]
# Tell us about your request

I'd like to know if it's possible to test the video call without using the browser but with a video simulating the audio/video input broadcasted from a server.

## What do you want us to build?

A way to make chime SDK run on the server-side without the need for browser support.

## Tell us about the problem you are trying to solve and why is it hard?

We have a proctoring system in which the proctoring application is made to run on (Desktop - Web browser) and the client joins the call using the app (iOS - Android ) mobile phone.

For instance, I'd like to know if we can simulate the proctoring side without any human interaction by calling an API on our server-side running chime SDK and Node which would broadcast a test video that simulates the proctor.

## How are you currently solving a problem?

We don't have a current solving problem yet.

Whenever we need to test, we have to open a web browser enter a call as proctor. Once the proctor is online we can join from a mobile phone, but this process slows the development.

## Additional context

This solution would help us with: 
     - Demos
     - Unit Test
     - UI Test

**Comment by ltrung** [comment]
We do not currently support this use case but I am curious if you can use Selenium or other automation frameworks (Playwright, Cypress, etc.) to automate this process?

**Comment by nandzz** [comment]
Hi @ltrung , Thank you for your feedback. It would be great to have the possibility without using a framework. But Your idea just works in our case. Thank you very much!

**Comment by joeypedicini92** [comment]
this would be super helpful, just bumping this
