### ISSUE TITLE
[Feature request]: MediaCapturePipeline - add State to AudioArtifactsConfiguration

### ISSUE THREAD

**Issue by user4fti** [aws/amazon-chime-sdk-js#1961]
# Community Note
* Please vote for this issue by adding a 👍 reaction to the issue. This will help the community and maintainers from the Amazon Chime SDK team to prioritize this request.
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request.
* Please go through the existing [issues](https://github.com/aws/amazon-chime-sdk-js/issues) to see if your request has already been recommended.
* Please do not use this template for bugs or support. Each individual repository has a PR template, documentation and resources for [troubleshooting](https://github.com/aws/amazon-chime-sdk-js#troubleshooting-and-support).
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.

# Tell us about your request
We use chime in our application and need to create meeting protocol at the end of a session. We used a workaround to log all necessary data to do the job but now with the MediaCapturePipeline feature we can do that directly using chime! One configuration we are missing, which is very important for us (privacy issue), is the ability to disable audio and then only capture the data-channel and meeting-events (no audio or video of the attendees).
## What do you want us to build?
Please add "State": "Enabled | Disabled" to the Chime AudioArtifactsConfiguration interface.
## Which Amazon Chime SDK or feature area is this request for?
[amazon-chime-sdk-js](https://github.com/aws/amazon-chime-sdk-js)
[aws-sdk-js](https://github.com/aws/aws-sdk-js) 

## Tell us about the problem you are trying to solve and why is it hard?
privacy issue, our costumers don't allow us to save any personalized data

## How are you currently solving a problem?
The workaround is very complex and unstable

## Additional context
/

**Comment by achris** [comment]
Thanks for the feature request.  What data are you looking to capture?  Is it the data messages, the meeting events, or audio transcript?

**Comment by user4fti** [comment]
>  disable audio and then only capture the data-channel and meeting-events (no audio or video of the attendees).

- Data messages, Yes 
- Meeting events, Yes
- Audio transcript, No

**Comment by tenge-amzn** [comment]
Hi,
Would like to know more information about your data messages. Are they encoded or plaintext? Right now media capture pipeline print the data messages as ascii - it will not handling well if your data messages are not text.
