### ISSUE TITLE
Amazon Chime SDK JS V3 Plan

### ISSUE THREAD

**Issue by ltrung** [aws/amazon-chime-sdk-js#1964]
The Amazon Chime SDK JS team is planning for the next major version v3.0.0 to:
- Improve device workflow by decoupling the device controller from audio video controller, better high level API to handle audio/video permission mode when joining. 
- Improve our client metrics and audio/video bandwidth events.
- Decouple event controller so that it can be used out of the meeting context. 
- Improve audioVideo.update to make sure it is idempotent and prevent race condition when switching between different video inputs.
- Other minor clean up code.

We will update here when we have more details to share. Please let us know if you are looking forward to any of the upcoming changes by commenting or adding a 👍 reaction to the issue.

Please refer to the [v3 Migration guide](https://github.com/aws/amazon-chime-sdk-js/blob/main/guides/17_Migration_to_3_0.md) on how to migrate to v3.

If you want to try out the beta version, please use `npm install amazon-chime-sdk-js@beta` to get the latest beta version.  

# Community Note
* Please vote for this issue by adding a 👍 reaction to the issue. This will help the community and maintainers from the Amazon Chime SDK team to prioritize this request.
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request.

**Comment by ltrung** [comment]
[amazon-chime-sdk-js@v3.0.0-beta.0](https://www.npmjs.com/package/amazon-chime-sdk-js/v/3.0.0-beta.0) has been released. You can find more info from [CHANGELOG.md](https://github.com/aws/amazon-chime-sdk-js/blob/v3.0.0-beta.0/CHANGELOG.md#300-beta0---2022-02-08).
We also start a [migration doc](https://github.com/aws/amazon-chime-sdk-js/blob/v3.0.0-beta.0/guides/17_Migration_to_3_0.md) from v2 to v3 that will be updated with all the changes that are not backward compatible. 
The main changes in the first beta build is:
- Decouple event controller from audio video controller so that it does not depend on the audio video lifecycle.
- Clean up a lot of unused/deprecated code. Major thing is remove support for Safari 12 as well as planB.

**Comment by ltrung** [comment]
[amazon-chime-sdk-js@v3.0.0-beta.1](https://www.npmjs.com/package/amazon-chime-sdk-js/v/3.0.0-beta.1) has been released. The main change in this beta build is:
- Migrate from the legacy Google metric stats in `metricsDidReceive`.  You will receive standard metrics in Chrome now. You can also access raw webRTC stats [`RTCStatsReport`](https://developer.mozilla.org/en-US/docs/Web/API/RTCStatsReport) via `rtcStatsReport` property of `ClientMetricReport` in `metricsDidReceive` events. This should be used to access raw stats instead of the current [getRTCPeerConnectionStats](https://aws.github.io/amazon-chime-sdk-js/classes/defaultaudiovideofacade.html#getrtcpeerconnectionstats).

**Comment by joshivaibhavs** [comment]
Looking forward to the upcoming changes. :+1:

**Comment by ltrung** [comment]
[amazon-chime-sdk-js@3.0.0](https://www.npmjs.com/package/amazon-chime-sdk-js/v/3.0.0) has been released. Please find more of the details in the [CHANGELOG.md](https://github.com/aws/amazon-chime-sdk-js/blob/v3.0.0/CHANGELOG.md#300---2022-03-30).
