### ISSUE TITLE
Getting "AudioJoinedFromAnotherDevice" error too frequently after version update.

### ISSUE THREAD

**Issue by abhimanusharma** [aws/amazon-chime-sdk-js#1972]
### What happened and what did you expect to happen?

Getting this in log.
```
Failed to choose camera: NotReadableError: Could not start video source in
attendeeId: "9207e233-5036-f8ec-e883-b42e56ffa4d3"
browserMajorVersion: "97"
browserName: "Chrome"
browserVersion: "97.0.4692.99"
deviceName: "Unavailable"
externalMeetingId: "iU5CWjA#development"
externalUserId: "615fe7d00c8f4300dc2af43a#Abhimanu Sharma"
meetingHistory: (6) [{…}, {…}, {…}, {…}, {…}, {…}]
meetingId: "92d2ab67-c207-42a9-ab9a-dca25ba60706"
osName: "Windows"
osVersion: "10"
sdkName: "amazon-chime-sdk-js"
sdkVersion: "2.24.0"
timestampMs: 1643610038514
videoInputErrorMessage: "NotReadableError: Could not start video source"
[[Prototype]]: Object

```
```
The meeting ended with the status: AudioJoinedFromAnotherDevice in  

```

Then meeting session is ended.

Meeting session should not be ended until host ends or chime policy end session requirements are met.

### Have you reviewed our existing documentation?

- [X] GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [X] FAQs [page](https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html)
- [X] README [page](https://github.com/aws/amazon-chime-sdk-js#amazon-chime-sdk-for-javascript)
- [X] Feature-specific [guides](https://github.com/aws/amazon-chime-sdk-js#guides)

### Reproduction steps

Joined meeting with 6 participants and all user joined with different devices and all user's mic is on. All users are speaking at once.

### Amazon Chime SDK for JavaScript version

"amazon-chime-sdk-js": "2.24.0",

### What browsers are you seeing the problem on?

Google Chrome

### Browser version

Version 97.0.4692.99 (Official Build) (64-bit)

### Meeting and Attendee ID Information.

meetingId: "92d2ab67-c207-42a9-ab9a-dca25ba60706"
attendeeId: "9207e233-5036-f8ec-e883-b42e56ffa4d3"

### Browser console logs

Failed to choose camera: NotReadableError: Could not start video source in
attendeeId: "9207e233-5036-f8ec-e883-b42e56ffa4d3"
browserMajorVersion: "97"
browserName: "Chrome"
browserVersion: "97.0.4692.99"
deviceName: "Unavailable"
externalMeetingId: "iU5CWjA#development"
externalUserId: "615fe7d00c8f4300dc2af43a#Abhimanu Sharma"
meetingHistory: (6) [{…}, {…}, {…}, {…}, {…}, {…}]
meetingId: "92d2ab67-c207-42a9-ab9a-dca25ba60706"
osName: "Windows"
osVersion: "10"
sdkName: "amazon-chime-sdk-js"
sdkVersion: "2.24.0"
timestampMs: 1643610038514
videoInputErrorMessage: "NotReadableError: Could not start video source"

`The meeting ended with the status: AudioJoinedFromAnotherDevice in  `

**Comment by simmkyu** [comment]
### AudioJoinedFromAnotherDevice

The `AudioJoinedFromAnotherDevice` error occurs when you use the same attendee response in multiple meetings.

From the [Meeting error messages](https://aws.github.io/amazon-chime-sdk-js/modules/meetingevents.html#meeting-error-messages) section in the meeting event guide:
> Ensure that you do not use the same attendee response from the CreateAttendee, BatchCreateAttendee, or CreateMeetingWithAttendees API action in two or more meetings simultaneously.

⠀
### NotReadableError

The `NotReadableError: Could not start video source` error often occurs when other browser tabs or applications share the same media devices.

From the [Meeting error messages](https://aws.github.io/amazon-chime-sdk-js/modules/meetingevents.html#meeting-error-messages) section in the meeting event guide:
> Ensure that you do not use the media devices in other browser tabs or applications. A hardware error may also occur at the operating system or browser. If the problem persists, restart the browser and try again.

⠀

### Chime server logs for `92d2ab67-c207-42a9-ab9a-dca25ba60706`

The Chime server logs indicate that you have created the attendee 9207e233-5036-f8ec-e883-b42e56ffa4d3 8 times at 01/30/22 22:14:15 (PST) with `CreateAttendee`, `BatchCreateWithAttendees`, or `CreateMeetingWithAttendees` API in your server application. This attendee repeated leaving and joining a meeting 8 times.

**Comment by xuesichao** [comment]
Close this issue due to inactivity. Feel free to ping us if you still have the issue and we can reopen this. @abhimanusharma
