### ISSUE TITLE
Video not working on few Android mobile chrome

### ISSUE THREAD

**Issue by venkatrv75** [aws/amazon-chime-sdk-js#1976]
### What happened and what did you expect to happen?

Hello all, I am using the latest chime js sdk. On one of the Android tablet I have, on Chrome browser (latest), video is not working, with below error. On a different android mobile phone, it is working fine. Could you please provide any pointers for resolving?

Thanks in advance!!
-Ramana

### Have you reviewed our existing documentation?

- [X] GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [X] FAQs [page](https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html)
- [X] README [page](https://github.com/aws/amazon-chime-sdk-js#amazon-chime-sdk-for-javascript)
- [X] Feature-specific [guides](https://github.com/aws/amazon-chime-sdk-js#guides)

### Reproduction steps

Just run chime Javascript SDK based solution on Samsung tablet 

### Amazon Chime SDK for JavaScript version

2.26.0

### What browsers are you seeing the problem on?

Android Chrome

### Browser version

97.0.4692

### Browser console logs

----------Error----------------
2022-01-31T13:35:15.014Z [ERROR] ChimeMeetingLogs - failed to get video device for constraints {"video":{"deviceId":{"exact":"f7215023a6fc19d2aae0fe95f072f034c6e7d3a82f42a7658835b0aa9569808b"},"width":{"ideal":960},"height":{"ideal":540},"frameRate":{"ideal":15},"googCpuOveruseDetection":true,"googCpuOveruseEncodeUsage":true,"googCpuOveruseThreshold":85,"googCpuUnderuseThreshold":55}}: NotReadableError: Could not start video source

----------------End Error----------------

**Comment by ltrung** [comment]
`NotReadableError` is an error thrown by the browsers when the video stream could not be acquired.
I noticed from the log you pasted that it contains some old constraints that we have ( `googCpuOveruseDetection`, `googCpuOveruseEncodeUsage`, etc.) that have been removed since July last year (https://github.com/aws/amazon-chime-sdk-js/commit/9fcb308859812f56e12951b079a0e99a5f257267#diff-5bbd65d9874d666d837e5703be73ef28feac09ad715de302cdaacf4c2a2f2c9aL1564)). Do you manually pass those constraints or can you double check the version of amazon-chime-sdk-js that you are using?

**Comment by venkatrv75** [comment]
I have updated the chime js sdk and still below error is seen.

--------------------
2022-02-02T04:14:28.617Z [ERROR] ChimeMeetingLogs - failed to get video device for constraints {"video":{"deviceId":{"exact":"9b04c4b235488a089a4fc4c983aac99c8de3b0608e2f81d2fee9d7a1fca690e0"},"width":{"ideal":960},"height":{"ideal":540},"frameRate":{"ideal":15}}}: NotReadableError: Could not start video source
-------------------

**Comment by venkatrv75** [comment]
I am not passing any constraints. The code looks like:
await deviceController.chooseVideoInputDevice(cameraId)

thanks.
Ramana

**Comment by ltrung** [comment]
@venkatrv75 Could you try to use our [meeting demo app](https://github.com/aws/amazon-chime-sdk-js/tree/main/demos/browser/app/meetingV2) and see whether it works? 
Another sample to try is the webRTC sample https://webrtc.github.io/samples/src/content/devices/input-output/. If this fails, then something in browser or os setting prevents the browser from getting the video stream from the camera.

**Comment by devalevenkatesh** [comment]
Hello @venkatrv75 , I am closing this issue due to in-activity, please feel free to re-open if you are still facing the same issue and as requested in previous comment request you to test on provided links to check if this is SDK related or WebRTC or device specific issue.
