### ISSUE TITLE
How to send attachments and emojis in Chime Messaging ? 

### ISSUE THREAD

**Issue by Sagar1219** [aws/amazon-chime-sdk-js#1977]
### What are you trying to do?

I am trying to find out how I can send an attachment like a file ( doc/pdf/xml/json/xlsv/odt/txt ) or maybe an image or a video in a
conversation channel?
So far the messaging has been working fine on basic texting,  I am only able to push text messages into the channel using [sendChannelMessage](https://docs.aws.amazon.com/aws-sdk-php/v3/api/api-chime-2018-05-01.html#sendchannelmessage)

Also, along with media files, does this SDK supports emoticons & emojis ?

### What documentation have you looked at so far?

Using backend PHP so have gone through this: https://docs.aws.amazon.com/aws-sdk-php/v3/api/api-chime-2018-05-01.html
Read these too : 
https://docs.aws.amazon.com/chime/latest/dg/configure-attachments.html
https://docs.aws.amazon.com/chime/latest/dg/using-the-messaging-sdk.html
P.S. Using min.js version of this SDK on frontend for the Messaging observer to capture the meeting events.

**Comment by Sagar1219** [comment]
Guys any update?

**Comment by fenderrex** [comment]
2024 and it looks like the decimation on this workaround has fallen behind the demo page has a notice of deprecation the permalinks to reference the GitHub sources have not merged well with the branch updates. if anyone has up-to-date resources or know what authorization protocol is in place for the chime web service it would be nice to not have a S3 on the side for migration

**Comment by yochum** [comment]
Thank you for your interest in this feature. This feature is not currently available. Closing this feature request as it does not directly pertain to the Chime SDK for JavaScript. Please do reach out through your AWS account team or contact us in AWS Console to submit a feature request. Much appreciated.
