### ISSUE TITLE
realtimeSubscribeToAttendeeVideoTileStatus

### ISSUE THREAD

**Issue by abhimanusharma** [aws/amazon-chime-sdk-js#1978]
### What are you trying to do?

*I'm trying to get the status of all video is enabled/disabled by the attendees.*

### How can the documentation be improved to help your use case?

*Include a section which shows how to get if videoTile is on or off of every attendee*
If this section is not yet present this should be part of the SDK.

### What documentation have you looked at so far?

*README.md, Amazon Chime SDK Developer Guide, 
https://aws.github.io/amazon-chime-sdk-js/interfaces/realtimecontroller.html#realtimesubscribetoattendeeidpresence.*

**Comment by ltrung** [comment]
There is no API or single event to manage attendee's video status but you can easily do so by registering to `audioVideoObserver` and handle `videoTileDidUpdate` and `videoTileWasRemoved`. As seen from our meeting demo:
```
const observer = {
  // videoTileDidUpdate is called whenever there is a new video
  videoTileDidUpdate: tileState => {
    // You can tell from tileState.boundAttendeeId or boundExternalUserId and maintain a local map
    this.videos[tileState.tileId] = tileState.boundAttendeeId;
  }
  // This should be called when a remote video is turned off
  videoTileWasRemoved: tileId => {
    // You can tell who turn off video from the mapping above.
  }
};
meetingSession.audioVideo.addObserver(observer)
}
```

**Comment by abhimanusharma** [comment]
@ltrung what about the participants whose tile was off initially, on preview page settings?
