### ISSUE TITLE
Status internet

### ISSUE THREAD

**Issue by Brenerss** [aws/amazon-chime-sdk-js#1979]
### What happened and what did you expect to happen?

I need to check if my user has been disconnected from the meeting, is there any property that does this?

Because React's useRosterState only returns the updated roster if I'm connected to the internet

### Have you reviewed our existing documentation?

- [X] GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [X] FAQs [page](https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html)
- [X] README [page](https://github.com/aws/amazon-chime-sdk-js#amazon-chime-sdk-for-javascript)
- [X] Feature-specific [guides](https://github.com/aws/amazon-chime-sdk-js#guides)

### Reproduction steps

npm run start

### Amazon Chime SDK for JavaScript version

"^2.17.0"

### What browsers are you seeing the problem on?

Chrome

### Browser version

97.0.4692.99 64 bits

### Browser console logs

none

**Comment by Brenerss** [comment]
That's right, it's the local user. These methods have an empty return, wouldn't there be something like status = 99 (No connection) for example?

**Comment by ltrung** [comment]
These methods are events so you will need to register to audioVideoObserver to receive the events.
```
const observer = {
  audioVideoDidStart: () => {
    console.log('Started');
  }
  audioVideoDidStartConnecting: (reconnecting: boolean) => {
    if (reconnecting) {
      console.log('Reconnecting');
    }
  }
};

meetingSession.audioVideo.addObserver(observer);
```

**Comment by Brenerss** [comment]
Obrigado
