### ISSUE TITLE
Record meeting as a single MP4 file

### ISSUE THREAD

**Issue by itsbeautifullife** [aws/amazon-chime-sdk-js#1989]
# Community Note
* Please vote for this issue by adding a 👍 reaction to the issue. This will help the community and maintainers from the Amazon Chime SDK team to prioritize this request.
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request.
* Please go through the existing [issues](https://github.com/aws/amazon-chime-sdk-js/issues) to see if your request has already been recommended.
* Please do not use this template for bugs or support. Each individual repository has a PR template, documentation and resources for [troubleshooting](https://github.com/aws/amazon-chime-sdk-js#troubleshooting-and-support).
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.

# Tell us about your request
## What do you want us to build?
Which Amazon Chime SDK or feature area is this request for?
Record meeting as a single file instead of multiple separate files
## Tell us about the problem you are trying to solve and why is it hard?
Having many files makes organizing and keeping track difficult. Is there any option we can pass in chime record call to tell it should compose single mp4 file instead of multiple?

## How are you currently solving a problem?
Currently we using FFMPEG to join video files manually. Download all files given in a meeting to a folder on disk then run ffmpeg on those files to get a single file output

## Additional context
Anything else we should know?
```
  let captureS3Destination = `arn:aws:s3:::${CAPTURE_S3_DESTINATION_PREFIX}-${meetingRegion}/${meeting.Meeting.MeetingId}/`
  pipelineInfo = await chime.createMediaCapturePipeline({
    SourceType: "ChimeSdkMeeting",
    SourceArn: `arn:aws:chime::${AWS_ACCOUNT_ID}:meeting:${meeting.Meeting.MeetingId}`,
    SinkType: "S3Bucket",
    SinkArn: captureS3Destination,
    // Anything we need to add here to get a single file output?
  }).promise();
  ```
![image](https://user-images.githubusercontent.com/94893214/152483251-0dd10fe5-6c72-45e6-ba48-94fbced55910.png)

**Comment by achris** [comment]
Thanks for the feature request.

As a workaround, you can take a look at https://github.com/aws-samples/amazon-chime-media-capture-pipeline-demo which demonstrates how to post-process the artifacts in a lambda function.

**Comment by tenge-amzn** [comment]
The team is currently working on this. We will provide more updates once we have design finalized.

**Comment by minal-vaghasiya** [comment]
@tenge-amzn  we have any timeline to release this feature request?

**Comment by tenge-amzn** [comment]
This is launched today. 
Launch announcement:
https://aws.amazon.com/about-aws/whats-new/2022/08/amazon-chime-sdk-video-compositing-merging-concatenation-webrtc-media-capture/

Technical blog (updated part):
https://aws.amazon.com/blogs/business-productivity/capture-amazon-chime-sdk-meetings-using-media-capture-pipelines/
