### ISSUE TITLE
Live transcription implementation on ReactJS app

### ISSUE THREAD

**Issue by Brenerss** [aws/amazon-chime-sdk-js#1994]
### What happened and what did you expect to happen?

I'm currently needing to implement a feature that will show the entire transcript during the meeting.
I completed the first step which would be "Creating a Service-Linked Role for Amazon Chime Live Transcription" from this 
url (https://docs.aws.amazon.com/chime/latest/ag/using-service-linked-roles-transcription.html)

after that, as soon as the meeting starts I call this url -> `meetings/${meetingIdFromAWS}/transcription?operation=start`
that `meetingIdFromAWS` is MeetingId returned from `join?title=meetingId&name=name&regionregion`

First problem:
   in my local computer this url returns 404 not found `meetings/${meetingIdFromAWS}/transcription?operation=start`, only on production this url works

Second problem: 
   even in production when I call this url and it returns 200(OK), the class `Transcript` of this import always returns empty
```
import { Transcript } from 'amazon-chime-sdk-js';

const transcript = new Transcript();
console.log('transcript', transcript);
```

I'm kind of confused about the documentation, what would be the correct way to use this transcription feature

### Have you reviewed our existing documentation?

- [X] GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [X] FAQs [page](https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html)
- [X] README [page](https://github.com/aws/amazon-chime-sdk-js#amazon-chime-sdk-for-javascript)
- [X] Feature-specific [guides](https://github.com/aws/amazon-chime-sdk-js#guides)

### Reproduction steps

npm run start

### Amazon Chime SDK for JavaScript version

^2.17.0

### What browsers are you seeing the problem on?

Chrome

### Browser version

97.0.4692.99 64 bits

### Browser console logs

none

**Comment by xuesichao** [comment]
@Brenerss Are you following this guide? https://docs.aws.amazon.com/chime/latest/dg/meeting-transcription.html

For your first question:
> in my local computer this url returns 404 not found meetings/${meetingIdFromAWS}/transcription?operation=start, only on production this url works

You need to have a serverless deployment to create new AWS Lambda endpoints for live transcription. AWS Lambda endpoints for live transcription does not exist when running locally.

**Comment by Brenerss** [comment]
Yes, im following this guide and ok i will try create this

**Comment by xuesichao** [comment]
@Brenerss For your second question:
> even in production when I call this url and it returns 200(OK), the class Transcript of this import always returns empty

According to our [doc](https://docs.aws.amazon.com/chime/latest/dg/initiate-transcription.html): 
> OK (200) with empty body, if you successfully apply the TranscriptionConfiguration to the meeting.

You got the response 200, basically it means you started the transcription service successfully. I assume the cause here is you used the wrong way to receive the transcription result.

According to our [demo App implementation](https://github.com/aws/amazon-chime-sdk-js/blob/ca6dd41c8683ab295c0bd5caa0a22e47f1a8cb0d/demos/browser/app/meetingV2/meetingV2.ts#L1940-L2025) and the [AWS doc](https://docs.aws.amazon.com/chime/latest/dg/process-msgs.html):

You need to implement a `transcriptEventHandler`, and subscribe to transcript event:
```ts
transcriptEventHandler = (transcriptEvent: TranscriptEvent): void => {
  // `transcriptEvent` could be either a `Transcript` or `TranscriptionStatus`
  // if it is `Transcript`, then it should contain transcription results
  // else you need to handle the logic of `TranscriptionStatus` changes (start/ stop/ ...)

  if (transcriptEvent instanceof TranscriptionStatus) {
    // Print Transcript Status, could be `STARTED`, `INTERRUPTED`, `RESUMED`, `STOPPED` or `FAILED`
    console.log(transcriptEvent.type);
  } else if (transcriptEvent instanceof Transcript) {
    // Print Transcript result collection
    console.log(transcriptEvent.results);
  }
};

this.audioVideo.transcriptionController?.subscribeToTranscriptEvent(this.transcriptEventHandler);
```

**Comment by Brenerss** [comment]
I used this function, the call to api returned 200 but no console.log of this function referring to the transcript event is shown as I speak

I'm not sure if I'm getting the MeetingId from the right place

endpoint of fetchMeeting is `join?title=meetingId&name=name&region=region`

```
const { JoinInfo } = await handleAPICall(() => AWSServices.fetchMeeting({ 
        meetingId,
        name: participantName,
        region: appRegion,
 }));
```

and JoinInfo retuns `JoinInfo.Meeting.MeetingId` and it is this value that I am passing to the request `meetings/${meetingIdFromAWS}/transcription?operation=start`

**Comment by xuesichao** [comment]
@Brenerss I assume you were using the HTTP request to start the transcription service following this doc: https://docs.aws.amazon.com/chime/latest/dg/initiate-transcription.html

I'm not familiar with this part. I checked our browser demo where it calls `StartMeetingTranscription` API to start the transcription service. 
Could you please follow the steps in below comment and see if it helps?
https://github.com/aws/amazon-chime-sdk-js/issues/2026#issuecomment-1047205400

**Comment by Brenerss** [comment]
Its works! But when i tested on prod, returns 

```
{
    "errorType": "Forbidden",
    "errorMessage": "AWS authorization failed",
    "code": "Forbidden",
    "message": "AWS authorization failed",
    "time": "2022-03-07T14:38:26.070Z",
    "requestId": "5bba27fb-e456-4509-a27b-3c1d9db81e28",
    "statusCode": 403,
    "retryable": false,
    "retryDelay": 27.326964869587588,
    "stack": [
        "Forbidden: AWS authorization failed",
        "    at Object.extractError (/var/runtime/node_modules/aws-sdk/lib/protocol/json.js:52:27)",
        "    at Request.extractError (/var/runtime/node_modules/aws-sdk/lib/protocol/rest_json.js:49:8)",
        "    at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:106:20)",
        "    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:78:10)",
        "    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/request.js:686:14)",
        "    at Request.transition (/var/runtime/node_modules/aws-sdk/lib/request.js:22:10)",
        "    at AcceptorStateMachine.runTo (/var/runtime/node_modules/aws-sdk/lib/state_machine.js:14:12)",
        "    at /var/runtime/node_modules/aws-sdk/lib/state_machine.js:26:10",
        "    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:38:9)",
        "    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:688:12)"
    ]
}
```

**Comment by LeviSklaroff** [comment]
I noticed in this #2085 you are not passing a region, if the region is not specified it uses the same region as the meeting, which can sometimes not support transcription and you will receive this error. You can Use "region = 'auto'" to have Amazon Chime use Amazon Transcribe in a nearby region if it is not available in the meeting region.
https://docs.aws.amazon.com/chime/latest/APIReference/API_StartMeetingTranscription.html

This can also occur if you are hosting a meeting in an "opt in" region (eu-south-1, af-south-1), then you must "enable" those regions for your AWS account for Amazon Chime to invoke Amazon Transcribe from that region (regardless of the region of Amazon Transcribe)
https://docs.aws.amazon.com/chime/latest/dg/transcription-options.html#choose-region
