### ISSUE TITLE
Make the intent of the Minimal demo clear

### ISSUE THREAD

**Issue by vidya-mohan** [aws/amazon-chime-sdk-js#200]
### What are you trying to do?
Currently the minimal demo application is incomplete so its not clear what the purpose is. Perhaps we can use it to demonstrate as a simple Vanilla JS demo app. This would require to be clear.

### How can the documentation be improved to help your use case?
The existing documentation doesn't make the intention of this demo clear.

### What documentation have you looked at so far?
README.md, Amazon Chime SDK Developer Guide, etc.

**Comment by aburnson** [comment]
Closing in favor of #223
