### ISSUE TITLE
Camera videos are rendered in grayscale in Chromium 98/ Windows

### ISSUE THREAD

**Issue by xuesichao** [aws/amazon-chime-sdk-js#2002]
### What happened and what did you expect to happen?

Camera videos are rendered in grayscale on Chrome 98/ Windows when 5-8 videos are enabled in a call and hardware acceleration is enabled.

#### Cause
The issue occurs on the video sender side with the default video uplink bandwidth policy. If the video sender is using Chrome 98 on Windows and there are 5-8 videos enabled in the meeting. The video source from this sender will turns into grayscale, and other attendees can observe it.

The `NScaleVideoUplinkBandwidthPolicy` downgrades the video resolution as the number of videos increases. When there are 5-8 videos enabled in a call, the video resolutions are downgrade to 480P. At this moment the videos are rendered in grayscale. The encoder seems to be broken in Chrome 98 when encoding the videos at 480P.

We have filed a Chromium bug https://bugs.chromium.org/p/chromium/issues/detail?id=1296700 and released 2.26.1 to work around this issue by scaling down to 360P instead of 480P.

### Have you reviewed our existing documentation?

- [X] GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [X] FAQs [page](https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html)
- [X] README [page](https://github.com/aws/amazon-chime-sdk-js#amazon-chime-sdk-for-javascript)
- [X] Feature-specific [guides](https://github.com/aws/amazon-chime-sdk-js#guides)

### Reproduction steps

* Enable hardware acceleration
* 5 attendees join a call and enable the camera.
* When the 5th attendee enable the camera, the video tiles are rendered in grayscale.

### Amazon Chime SDK for JavaScript version

N/A

### What browsers are you seeing the problem on?

Chrome/Edge 98 on Windows.

### Browser version

98

### Browser console logs

N/A

**Comment by xuesichao** [comment]
Hi @ildar-shamilov-clearscale we are actively working on the fix right now. Once the fix is finalized we will release a hot fix ASAP.

**Comment by jpchatt** [comment]
Are you guys also working on the related issues of a dis-colored screen shares?

**Comment by jpchatt** [comment]
@ltrung I have run into it myself, yes. but only when hardware acceleration is turned on.
<img width="1075" alt="Screen Shot 2022-02-10 at 3 59 46 PM" src="https://user-images.githubusercontent.com/2590314/153495482-ce2a89ed-1110-40cf-b7f2-6a256e8958ed.png">

**Comment by xuesichao** [comment]
@antoineveldhoven , by default the active speaker is set to 540P. That's why it's in full color. The issue only occurs when encoding video in 480P.

**Comment by ltrung** [comment]
@jpchatt What browser version and Windows did you see this on? If it is Chrome 98, have you tried on Chrome 97?
I did a quick check on Chrome 98 on Mac (Big Sur) and did not see any issue.
It maybe another encoder issue with Chrome hardware acceleration. In Chrome 88, it also broke and sent a black screen instead.
Anyway I would suggest to open a new issue regarding this.

**Comment by xuesichao** [comment]
@jpchatt Hi, could you please provide more info for your issue?
* How many people are in the meeting?
* What is the browser version and OS platform does the content sharer use?
* What is the browser version and OS platform does the one that is able to observe this issue?
* Can content sharer observe this issue?
*

**Comment by xuesichao** [comment]
Hi, we have published the hotfix 2.26.1 to npm. Could you please try to upgrade the SDK and let us know the result?

**Comment by ildar-shamilov-clearscale** [comment]
> Hi, we have published the hotfix 2.26.1 to npm. Could you please try to upgrade the SDK and let us know the result?

Looks good so far. Thanks.

**Comment by xuesichao** [comment]
Close the issue as the fix has been released in v2.26.1.
https://www.npmjs.com/package/amazon-chime-sdk-js

**Comment by xuesichao** [comment]
> @ltrung I have run into it myself, yes. but only when hardware acceleration is turned on. <img alt="Screen Shot 2022-02-10 at 3 59 46 PM" width="1075" src="https://user-images.githubusercontent.com/2590314/153495482-ce2a89ed-1110-40cf-b7f2-6a256e8958ed.png">

@jpchatt Hi, we reproduced this issue today, it happens when using Chrome Version 98.0.4758.80, enabling hardware acceleration, sharing the screen of laptop itself instead of external monitor( We are using MacBook Pro 16-inch) and having at least one other video tile. After we upgrade the Chrome version to 98.0.4758.102 (Official Build) (x86_64). The issue is gone.

Could you please try to update your Chrome version to latest and see if the issue still happens?
