### ISSUE TITLE
Unable to join meeting with Samsung Galaxy Tab A7 Lite, SM-T220

### ISSUE THREAD

**Issue by Level60Warlock** [aws/amazon-chime-sdk-js#2005]
### What happened and what did you expect to happen?

Unable to successfully join a meeting with a Samsung Galaxy Tab A7 Lite, SM-T220, running Chrome 97.  Experiencing in both older 
 (2.7) and latest versions of the SDK.  Reproduced in browser demo app.

### Have you reviewed our existing documentation?

- [X] GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [X] FAQs [page](https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html)
- [X] README [page](https://github.com/aws/amazon-chime-sdk-js#amazon-chime-sdk-for-javascript)
- [X] Feature-specific [guides](https://github.com/aws/amazon-chime-sdk-js#guides)

### Reproduction steps

Attempt to connect to browser demo app using the device in question (Samsung Galaxy Tab A7 Lite, SM-T220).  The user never successfully joins the meeting.

### Amazon Chime SDK for JavaScript version

2.7, 3.0.0

### What browsers are you seeing the problem on?

Chrome

### Browser version

97

### Browser console logs

[Samsung_GalaxyTab_log.txt](https://github.com/aws/amazon-chime-sdk-js/files/8044390/Samsung_GalaxyTab_log.txt)

**Comment by ltrung** [comment]
It seems ICEGathering fails. Did you connect with VPN?
From the log:
```
Gathering ICE candidates timed out. In Chrome, this might indicate that the browser is in a bad state after reconnecting to VPN. due to error Error: serial group task AudioVideoStart/b3c9c43d-6657-48d3-9466-9bc346bf0706/5a3902c8-0714-627d-9d88-3f18beebd0ba was canceled due to subtask AudioVideoStart/b3c9c43d-6657-48d3-9466-9bc346bf0706/5a3902c8-0714-627d-9d88-3f18beebd0ba/Timeout15000ms error: serial group task AudioVideoStart/b3c9c43d-6657-48d3-9466-9bc346bf0706/5a3902c8-0714-627d-9d88-3f18beebd0ba/Timeout15000ms/Peer was canceled due to subtask AudioVideoStart/b3c9c43d-6657-48d3-9466-9bc346bf0706/5a3902c8-0714-627d-9d88-3f18beebd0ba/Timeout15000ms/Peer/SubscribeAndReceiveSubscribeAckTask (once) error: canceling FinishGatheringICECandidatesTask due to the meeting status code: 16.
```

**Comment by Level60Warlock** [comment]
@ltrung - Thanks for the question.  In this case, there is no VPN being used, so I believe that to be a red herring.  Has also been experienced on multiple instances of this specific device, all on different network connections, but never with VPN in the equation.

**Comment by ltrung** [comment]
@Level60Warlock Have you tried to update to Chrome 98 to see if it fixes the issue?

**Comment by devalevenkatesh** [comment]
I tested on Chrome 98 Android 11 samsung device but could see the connectivity fine and the attendee could join the meeting fine. As mentioned by Trung above two things to try:
1. Could you please test peer connection demo if working fine on that device with below official WebRTC sample? https://webrtc.github.io/samples/src/content/peerconnection/channel/
2. Try upgrading to Chrome 98 on the same device and test if that solves the issue.

**Comment by Level60Warlock** [comment]
@ltrung / @devalevenkatesh  - I am working on both of these requests.  Will keep you posted on my findings.

**Comment by Level60Warlock** [comment]
@ltrung / @devalevenkatesh - I was able to confirm the device in question has been upgraded to the latest chrome version: Chrome is 98.0.4758.101
OS Android 11, SM-T220 Build/RP1A.200720.02

While attempting to load the WebRTC peer connection demo on that device in Chrome 98, here was the behavior experienced:
1. On browser tab 1, when starting the Peer connection test, the video feed displays
2. On browser tab 2, when attempting to start the test, no video feeds display on tab 2, and no audio loopback/echo is heard
3. Upon going back to browser tab 1, the video tile is frozen, and still no audio is heard

I then attempted the WebRTC test on Firefox on the same device, with the following behavior:
1. On browser tab 1, when starting the Peer connection test, the video feed displays
2. On browser tab 2, when attempting to start the test, both video tiles display correctly
3. Upon going back to browser tab 1, both video tiles display correctly

Having this work on Firefox but not Chrome was unexpected, so I then tested the Chime demo app via Firefox (97.2.0) on the SM-T220 device, which was able to connect successfully, with both audio and video functioning correctly.

I also attempted to test the same Webrtc demo app on my personal device (Pixel3) running Chrome 98, and experienced the same as above, no audio/video functioning.  That same Pixel3 device running Firefox is able to complete the Webrtc demo workflow.  And that same Pixel3 device using Chrome is able to connect successfully with the Chime demo app.

Please advise on what additional troubleshooting steps you'd like me to take.

**Comment by Level60Warlock** [comment]
@ltrung - There are no errors in the browser console, at least none when doing remote debugging.  

Logged a Chromium issue: https://bugs.chromium.org/p/chromium/issues/detail?id=1299615

**Comment by Level60Warlock** [comment]
@ltrung - Still waiting on Google for additional guidance around these Samsung device issues.

Any reason that this can't be added to https://github.com/aws/amazon-chime-sdk-js/issues/1059/?

Additionally, do we have any options to beef up [defaultbrowserbehavior.html#issupported](https://aws.github.io/amazon-chime-sdk-js/classes/defaultbrowserbehavior.html#issupported), which would allow consumers to prevent attendees from trying to join a conference that they ultimately would be unsuccessful in joining?

**Comment by LeviSklaroff** [comment]
Thanks for the update, added to known issues. Sadly because this is a device specific issue we are not able to handle it in `isSupported` as we are only able to gather the browser and the OS from the browser level.
