### ISSUE TITLE
Amazon Chime SDK now supports streaming to Amazon IVS and Elemental MediaLive through live connector feature

### ISSUE THREAD

**Issue by tenge-amzn** [aws/amazon-chime-sdk-js#2007]
# Community Note
* Please vote for this issue by adding a 👍 reaction to the issue. This will help the community and maintainers from the Amazon Chime SDK team to prioritize this request.
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request.
* Please go through the existing [issues](https://github.com/aws/amazon-chime-sdk-js/issues) to see if your request has already been recommended.
* Please do not use this template for bugs or support. Each individual repository has a PR template, documentation and resources for [troubleshooting](https://github.com/aws/amazon-chime-sdk-js#troubleshooting-and-support).
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.

# Tell us about your request
## What do you want us to build?
Which Amazon Chime SDK or feature area is this request for?
All.

## Tell us about the problem you are trying to solve and why is it hard?
Using media pipeline to capture the audio/video/content, and select specific streams and composite in a single view to broadcast. It can be a generic RTMPS endpoint, such as IVS channel, or Youtube Live.

This will be a managed service by simply calling media-pipeline API to invoke a new meeting agent like media-capture-pipeline.

## How are you currently solving a problem?
Are there any workarounds or mitigations you have used? Why is it not working for you?
Using broadcast demo: https://github.com/aws-samples/amazon-chime-meeting-broadcast-demo
This needs to provision my own containers, not a managed fleet.

## Additional context
Anything else we should know?

**Comment by philippd8e** [comment]
This is very interesting. A great feature could be the addition of eg. adding a rtmp/IVS output option to media-capture-pipelines directly, instead of going via s3 and ffmpeg job to push to rtmp further (or using the browser scraping solution linked in OP)

**Comment by fred-boink** [comment]
This would be great! Similar interface to MediaPipeline except instead of S3 it could be IVS. What is the ETA on this feature?

**Comment by steveRW** [comment]
I've been waiting for this feature. And, what would make this really useful would be control of the output to RTMP, youtube etc. Having the interface with all of the videos (webinar style) would not be that useful. What would be useful would be to have one video window at a time (ie the main speaker or someone they are interacting with) be sent full screen as output to the RTMP, etc. No one wants to watch a "Zoom Call" on livestream If you're broadcasting, you want to see the main speaker and at full screen and in HD.

**Comment by fred-boink** [comment]
@steveRW yeah, options would be great. Speaker or all view.

**Comment by tenge-amzn** [comment]
Amazon Chime SDK can now send real-time video from applications to streaming platforms such as Amazon Interactive Video Service (IVS) or AWS Elemental MediaLive. Amazon Chime SDK enables multi-party video sessions by letting developers add real-time voice and video to their web and mobile apps. Live connector helps to simplify the process of live streaming these sessions through a single API. Customer can send real-time video to streaming platforms such as AWS Elemental MediaLive, Amazon IVS, Twitch, YouTube Live, Facebook Live, and more.

Launch announcement: https://aws.amazon.com/about-aws/whats-new/2022/08/amazon-chime-sdk-streaming-ivs-elemental-medialive/

Technical blog post: https://aws.amazon.com/blogs/business-productivity/amazon-chime-sdk-launches-live-connector-for-streaming/

**Comment by yoshio-nakamura-nw** [comment]
`create-media-live-connector-pipeline` should work in us-east1,
something wrong?

![image](https://user-images.githubusercontent.com/80370238/185520071-be413e80-3fd8-4f75-8b96-880e8b66fd6f.png)

**Comment by yoshio-nakamura-nw** [comment]
improved.

![image](https://user-images.githubusercontent.com/80370238/185815609-22dcc179-1dee-4636-8db8-a31104aa8016.png)
