### ISSUE TITLE
Update Media capture pipeline to record constant frame rate to avoid audio sync issues

### ISSUE THREAD

**Issue by reynelle101** [aws/amazon-chime-sdk-js#2015]
# Community Note
* Please vote for this issue by adding a 👍 reaction to the issue. This will help the community and maintainers from the Amazon Chime SDK team to prioritize this request.
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request.
* Please go through the existing [issues](https://github.com/aws/amazon-chime-sdk-js/issues) to see if your request has already been recommended.
* Please do not use this template for bugs or support. Each individual repository has a PR template, documentation and resources for [troubleshooting](https://github.com/aws/amazon-chime-sdk-js#troubleshooting-and-support).
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.

# Tell us about your request
## What do you want us to build?
Which Amazon Chime SDK or feature area is this request for?
Such as: [amazon-chime-sdk-js](https://github.com/aws/amazon-chime-sdk-js), [amazon-chime-sdk-ios](https://github.com/aws/amazon-chime-sdk-ios), [amazon-chime-sdk-android](https://github.com/aws/amazon-chime-sdk-android), [amazon-chime-sdk-component-library-react](https://github.com/aws/amazon-chime-sdk-component-library-react), a new feature idea.

Mediapipeline recording audio goes out of sync as time goes when you are trying to use a video editor. This is caused by the recording format being VFR which doesn't have wide support with editors.  

## Tell us about the problem you are trying to solve and why is it hard?
The more details you provide us, the better we will be able to help you.

Currently the process to use this backup recording is: 
1. Download all segments 
2. Generate a list of the video files and concatenate to a single mp4 file (FFmpeg)
3. Run it through handbrake to convert it from VFR to CFR  https://handbrake.fr/ 
Edit/cut

(Unsure if this was also the issue with the ffmpeg recordings) 

## How are you currently solving a problem?
Are there any workarounds or mitigations you have used? Why is it not working for you?

## Additional context
Anything else we should know?

**Comment by reynelle101** [comment]
Do we have any updates for this request?

**Comment by MingcongQi** [comment]
Are you able to provide a meeting id and capture id for us? thanks!

**Comment by tenge-amzn** [comment]
no response. close.

**Comment by vishnun** [comment]
Can this issue be re-opened? We're running into this with our customers

**Comment by hensmi-amazon** [comment]
Please reopen if you have a meeting ID and capture ID
