### ISSUE TITLE
Unable to execute startMeetingTranscription in chime singlejs

### ISSUE THREAD

**Issue by husaindevelop** [aws/amazon-chime-sdk-js#2026]
### What happened and what did you expect to happen?

We tried to implement amazon transcribe with amazon chime for live transcription of attendee and host's speech based on the documentation given:https://docs.aws.amazon.com/chime/latest/dg/delivery-examples.html, but unfortunately we encountered error "meetingSession.startMeetingTranscription is not a function". 

### Have you reviewed our existing documentation?

- [X] GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [X] FAQs [page](https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html)
- [X] README [page](https://github.com/aws/amazon-chime-sdk-js#amazon-chime-sdk-for-javascript)
- [X] Feature-specific [guides](https://github.com/aws/amazon-chime-sdk-js#guides)

### Reproduction steps

We have deployed chime sdk single js to create the meeting platform. Now to attain the feature of speech to text, we are trying to combine amazon transcribe with chime based on the documentation given in here https://docs.aws.amazon.com/chime/latest/dg/delivery-examples.html.  Following the documentation , we tried executing startMeetingTranscription function, but encountered an error in the console log "meetingSession.startMeetingTranscription is not a function".  Here is the transcribe focussed code

```
 var params = {
  MeetingId: "<?=$meeting['MeetingId'] ?>", /* required */
  TranscriptionConfiguration: { /* required */
    EngineTranscribeSettings: {
      LanguageCode: 'en-US',
      ContentIdentificationType: 'PII',
      ContentRedactionType: 'PII',
      EnablePartialResultsStabilization: true,
      PartialResultsStability: 'medium',
      Region: 'us-east-2',
      VocabularyFilterMethod: 'remove',
      VocabularyFilterName: 'Nothing',
      VocabularyName: 'no'
    }
  }
};
   
const meetingSession = new ChimeSDK.DefaultMeetingSession(configuration, Logger, deviceController);
            
            meetingSession.startMeetingTranscription(params, function(err, data) {
  if (err) console.log(err, err.stack); // an error occurred
  else     console.log(data);           // successful response
});  
   
```

Shall appreciate should you guide us as where we are going wrong.

### Amazon Chime SDK for JavaScript version

latest

### What browsers are you seeing the problem on?

Chrome

### Browser version

97

### Browser console logs

```
2022-02-16T09:49:04.932Z [INFO] MyLogger - DefaultDeviceController video dimension 960 x 540
ConsoleLogger.js:76 2022-02-16T09:49:04.933Z [INFO] MyLogger - Supported Constraints in this browser {"aspectRatio":true,"autoGainControl":true,"brightness":true,"channelCount":true,"colorTemperature":true,"contrast":true,"deviceId":true,"echoCancellation":true,"exposureCompensation":true,"exposureMode":true,"exposureTime":true,"facingMode":true,"focusDistance":true,"focusMode":true,"frameRate":true,"groupId":true,"height":true,"iso":true,"latency":true,"noiseSuppression":true,"pan":true,"pointsOfInterest":true,"resizeMode":true,"sampleRate":true,"sampleSize":true,"saturation":true,"sharpness":true,"tilt":true,"torch":true,"whiteBalanceMode":true,"width":true,"zoom":true}
ConsoleLogger.js:76 2022-02-16T09:49:05.748Z [INFO] MyLogger - Supports SIMD: true (force: false)
ConsoleLogger.js:76 2022-02-16T09:49:06.363Z [INFO] MyLogger - SIMD timing: 9.814285721097674
ConsoleLogger.js:76 2022-02-16T09:49:06.364Z [INFO] MyLogger - Decided execution approach {"supported":true,"useSIMD":true,"processor":"voicefocus-inline-processor","executionApproach":"inline","variant":"c20","executionQuanta":3}
ConsoleLogger.js:76 2022-02-16T09:49:06.489Z [INFO] MyLogger - browser is edge-chromium 98 (98.0.1108)
ConsoleLogger.js:76 2022-02-16T09:49:06.489Z [INFO] MyLogger - WebRTC unified plan for Chromium-based browsers is enabled
ConsoleLogger.js:76 2022-02-16T09:49:06.498Z [INFO] MyLogger - adding meeting observer
index_n.php?vsn=9302010091&v=Yes:585
``` 
        
       Uncaught (in promise) TypeError: meetingSession.startMeetingTranscription is not a function
    at index_n.php?vsn=9302010091&v=Yes:585:28

**Comment by xuesichao** [comment]
Hi @husaindevelop , in JS SDK meeting demo, we have this function to trigger the start transcript API in our `server.js` file.
https://github.com/aws/amazon-chime-sdk-js/blob/32f93abd80f84c17b78e7e0f7a7cbadfbefed753/demos/browser/app/meetingV2/meetingV2.ts#L1155-L1165

And the corresponding API is:
https://github.com/aws/amazon-chime-sdk-js/blob/32f93abd80f84c17b78e7e0f7a7cbadfbefed753/demos/browser/server.js#L181-L243

The line 239 is the function call to start the transcript service.

I have notified the our transcript team to take a look at this issue. While waiting for their response, could you refer to this example for implementation?

**Comment by husaindevelop** [comment]
Thanks for your response. I did refer it for your information, unlike in the meeting demo,  in our use case, the user need not to choose parameters under transcriptionconfiguration. The configuration is default chosen with values as given in our above code. The 239 line which you specified is the problem for us. 

```
await client.startMeetingTranscription({ 
     MeetingId: meetingTable[requestUrl.query.title].Meeting.MeetingId, 
     TranscriptionConfiguration: transcriptionConfiguration 
   }).promise(); 
```

We are unable to point to appropriate the 'client' element, which results in either of error being displayed: "startMeetingTranscription is not a function".

**Comment by xuesichao** [comment]
@husaindevelop 
So in our `server.js` file:
https://github.com/aws/amazon-chime-sdk-js/blob/db36d8a4191ad6fe58af68d51008c12a5b1286a9/demos/browser/server.js#L237-L243

The `client` is returned by `getClientForMeeting()` API which returns either `chimeSDKMeetings` or `chime`:
https://github.com/aws/amazon-chime-sdk-js/blob/db36d8a4191ad6fe58af68d51008c12a5b1286a9/demos/browser/server.js#L51-L60

And `chimeSDKMeetings` and `chime` are from:
https://github.com/aws/amazon-chime-sdk-js/blob/db36d8a4191ad6fe58af68d51008c12a5b1286a9/demos/browser/server.js#L28-L38

I don't know which client you are using, but could you please try to follow the same way to see if it helps?

**Comment by husaindevelop** [comment]
Shall check and revert back to you.

**Comment by nainkunal933** [comment]
@husaindevelop Do you still need help with this issue?

**Comment by LeviSklaroff** [comment]
Closing issue as there has not been a response in over 30 days.
