### ISSUE TITLE
Stop chime media capture pipeline when no one join in meeting 

### ISSUE THREAD

**Issue by AnkurSavaliya** [aws/amazon-chime-sdk-js#2027]
## Tell us about the problem you are trying to solve and why is it hard?
I am using chime SDK java for creating meetings and creating a media capture pipeline.
So First I create a meeting and join one attendee, and also started a chime media capture pipeline, so this attendee did not initialize the meeting/Not join from the frontend side. So that time only the media capture attendee is in a meeting So I need to delete the media capture pipeline because no real attendee joined in the meeting.

By default, the meeting ended after 30 minutes because one media capture attendee is in a meeting so the media capture pipeline was deleted when the meeting ended at the default time.
So I need that can I get any chime events or any callback for I know that no one joins this meeting, or we can delete the media capture pipeline when on one in the meeting.

**Comment by xuesichao** [comment]
Hi @AnkurSavaliya , I don't really think this should be a feature request.

According to our doc: https://github.com/aws/amazon-chime-sdk-js#attendees

**Use case 23**. Subscribe to attendee presence changes. When an attendee joins or leaves a session, the callback receives presentAttendeeId and present (a boolean).

```js
const attendeePresenceSet = new Set();
const callback = (presentAttendeeId, present) => {
  console.log(`Attendee ID: ${presentAttendeeId} Present: ${present}`);
  if (present) {
    attendeePresenceSet.add(presentAttendeeId);
  } else {
    attendeePresenceSet.delete(presentAttendeeId);
  }
};

meetingSession.audioVideo.realtimeSubscribeToAttendeeIdPresence(callback);
```
You could subscribe to this event and listen to the number of attendees in the meeting. Or even to check the name of the attendee in the meeting. Whenever some real attendee joins the meeting, start the capture. And whenever the last real attendee leaves the meeting, stop the capture.

Could you please try if this helps?

**Comment by AnkurSavaliya** [comment]
Hi @xuesichao 

For example, the meeting have only one real attendee and I started a media capture pipeline, but if that attendee close the browser/tab so it accidentally left from the meeting, how can I know no one in a meeting? or how can I stop media capture pipeline because last real attendee left accidentally, So I don't get a callback from `**realtimeSubscribeToAttendeeIdPresence**`
this subscriber.

**Comment by xuesichao** [comment]
@AnkurSavaliya You're right, in that case `realtimeSubscribeToAttendeeIdPresence` can not help. 

Then you can try to receive the lifecycle event from server side. 
There's an event for this case - "Amazon Chime SDK attendee leaves a meeting". Check this guide: https://docs.aws.amazon.com/chime/latest/dg/using-events.html

**Comment by devalevenkatesh** [comment]
@AnkurSavaliya so the `amazon-chime-sdk-js` on the client side wont be able to help much since there wont be a central place to get events rather only on specific attendees client side individually. I suggest you to please check below meeting events guide. Using it, you can receive events from Amazon Chime backend and then trigger the appropriate downstream logic.

As stated by Sichao above, request you to check below guide:
https://docs.aws.amazon.com/chime/latest/dg/using-events.html

You still have to keep track of attendee joins and leaves and accordingly take the decision on media capture setup / destroy. I am closing this issue for now due to in-activity. Feel free to re-open if you are still facing any issues.
