### ISSUE TITLE
Unable to find meeting

### ISSUE THREAD

**Issue by DjWilly** [aws/amazon-chime-sdk-js#2040]
### What happened and what did you expect to happen?

I fill in the details and press continue only to be faced with meeting cannot be found!

![image](https://user-images.githubusercontent.com/7012392/154824113-6e1d5322-3246-4bb5-87e4-1570aa8c7741.png)

![image](https://user-images.githubusercontent.com/7012392/154824101-4130db57-139f-4afd-a6da-46eb0a6976f8.png)

### Have you reviewed our existing documentation?

- [X] GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [X] FAQs [page](https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html)
- [X] README [page](https://github.com/aws/amazon-chime-sdk-js#amazon-chime-sdk-for-javascript)
- [X] Feature-specific [guides](https://github.com/aws/amazon-chime-sdk-js#guides)

### Reproduction steps

install the serverless demo on aws cloud9. take the link produced and paste it on the browser

### Amazon Chime SDK for JavaScript version

latest to date (20/02/2022)

### What browsers are you seeing the problem on?

Chrome and Edge

### Browser version

latest

### Browser console logs

![image](https://user-images.githubusercontent.com/20471438/155018205-39d926ed-9ffd-43da-bdb1-7a889774c190.png)

**Comment by xuesichao** [comment]
Hi @DjWilly , thanks for reporting this issue. I mosaicked the confidential information in your screenshot.

I saw the status code`502` of below HTTP request in the log:
```
POST */join?title=Jugo2&name=Raed&region=eu-west-2&ns_es=false
```

Before joining the meeting we need to get some meeting data returned by the above HTTP request. And the property `Meeting` is part of this data.

Based on these observations, I suspect that something is wrong with your deployment of `server.js`, which is used to handle all HTTP requests in this demo. 

Could you please check if you missed anything during the deployment and provide more details for how you deployed the demo?

**Comment by DjWilly** [comment]
Many thanks @xuesichao Really appreciate your support.
I should have come back to update this. I tried again with a different region and different EC2 type. Now it's working fine.
Sorry I didn't update the report and thank you for covering my confidential information

**Comment by xuesichao** [comment]
@DjWilly You're welcome! Then let me close this issue for now. Please let us know if you have any other concern.

**Comment by jadamroth** [comment]
Sorry to hijack this issue, but I'm literally having the exact same problem: deployed the serverless demo out of the box via the commands on the readme and have tried deploying to 3 different regions. Same exact error in the browser and in the console.

@DjWilly what did you do to fix the error "Unable to find meeting... cannot read properties of undefined?

**Comment by DjWilly** [comment]
oh.. mine was interesting. I've switched to a different EC2 type (t3.medium). I have a feeling that it shouldn't be a problem but not sure why it worked when I did that. Maybe the free EC2 didn't come with all the requirments (CLI2, npm, sam, etc) pre-installed?

**Comment by jadamroth** [comment]
Thanks for the quick reply. 

Did you not use the serverless demo and let lambda/cloud formation handle the meeting? How did you change/set ec2 type or is this where you ran the script? I’m deploying this from my local machine. My browser demo worked phone

**Comment by jadamroth** [comment]
Just tried running the demo from an ec2 instance and got the same result. Other than setting IAM credentials (which I even made admin, so I know I would have all permissions), what else did you change before successfully running the script, just this?
```sh
cd demos/serverless
npm install
npm run deploy -- -r us-east-1 -b <my-bucket> -s <my-stack-name> -a meeting
```

**Comment by DjWilly** [comment]
I actually just tried to follow the same steps on my company's account and it didn't work. But maybe you have a better luck :)

I added many more policies:

AmazonS3FullAccess
AmazonChimeFullAccess
AdministratorAccess
AmazonChimeUserManagement

AmazonChimeReadOnly (this is probably not needed tbh)
Gamelift-StartSessionPolicy
AmazonChimeSDK
AmazonS3OutpostsFullAccess
GameLiftGameServerGroupPolicy

Then I tried to keep basic. I didn't install nor upgrade anything apart from awscli2. I kept everything else as is. Went straight to this part: 
```
git clone https://github.com/aws/amazon-chime-sdk-js.git
cd amazon-chime-sdk-js/demos/serverless
$ npm install
$ npm run deploy -- -r us-east-1 -b .. etc
``` 

I hope this helps

**Comment by jadamroth** [comment]
Thanks again for the reply. Weird that it now doesn't work for you either. 

I've tried rolling back to older releases. I'm confused on why it's not working since all my tests and outputs seem good. I'll start digging into the code tomorrow and see what I can't find

**Comment by jadamroth** [comment]
Solved my issue. Very stupid. I launched in us-east-2 and us-west-1. Both don't have capabilities for launching meetings in that region. I launched in us-east-1, and it worked. 

https://docs.aws.amazon.com/chime/latest/dg/sdk-available-regions.html
