### ISSUE TITLE
Screen share failed with DOMException: The object can not be found here

### ISSUE THREAD

**Issue by sanjitkung** [aws/amazon-chime-sdk-js#2041]
### What happened and what did you expect to happen?

When I am trying to start a screen share on Firefox (MacOS Catalina, BigSur, or Monterey) using LambdaTest, Screen share failed with "DOMException: The object can not be found here" errors. 

Screenshare is working as expected when I test it on macOS Mojave.

### Have you reviewed our existing documentation?

- [X] GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [X] FAQs [page](https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html)
- [X] README [page](https://github.com/aws/amazon-chime-sdk-js#amazon-chime-sdk-for-javascript)
- [X] Feature-specific [guides](https://github.com/aws/amazon-chime-sdk-js#guides)

### Reproduction steps

- Start firefox on either macOS Catalina, BigSur, or Monterey
- Start screen share and you will get the error

### Amazon Chime SDK for JavaScript version

v2.27.0

### What browsers are you seeing the problem on?

Firefox

### Browser version

95, 96 or 97

### Browser console logs

[console-log-screen-share-failed-with-dom-exception.txt](https://github.com/aws/amazon-chime-sdk-js/files/8104576/console-log-screen-share-failed-with-dom-exception.txt)

**Comment by ltrung** [comment]
Have you enabled screen sharing permission for Firefox under Security & Privacy -> Screen Recording ->  Firefox?
This is an error thrown by the browser and is not from JS SDK.

**Comment by nainkunal933** [comment]
@sanjitkung Did you get a chance to take a look at the Mac permissions?

**Comment by sanjitkung** [comment]
It was due to mac permission. After enabling the permission, screen share works as expected.
