### ISSUE TITLE
How to setup Chime events notification to SNS topic?

### ISSUE THREAD

**Issue by paul365** [aws/amazon-chime-sdk-js#2049]
### What are you trying to do?

I'm trying to receive chime meeting events on an SNS topic in the us-east-1 region, also created a role/policy following https://docs.aws.amazon.com/chime/latest/dg/mtgs-sdk-notifications.html passed the SNS arn in create meeting, but still not getting any notifications.
sample meeting Id: 77a8c8d1-2756-4811-b7bc-957fff7d0706

### How can the documentation be improved to help your use case?

Include a section on how to fully implement event notifications.

### What documentation have you looked at so far?

README.md, Amazon Chime SDK Developer Guide, FAQ, https://docs.aws.amazon.com/chime/latest/dg/mtgs-sdk-notifications.html, https://github.com/aws/amazon-chime-sdk-js/issues/342, https://github.com/aws/amazon-chime-sdk-js/issues/1777

**Comment by ildar-shamilov-clearscale** [comment]
Check policies.
Chime should have policy to write into SNS topic.

**Comment by rapito** [comment]
@paul365 We have a similar situation as yours. Could you tell us if you were able to get the notifications lowing?

**Comment by augusto3691** [comment]
Similar issue here too, any news about that?

**Comment by augusto3691** [comment]
For those who facing same issue, the problem is permission:

````json

{
      "Sid": "allow-chime-sdk-access-statement-id",
      "Effect": "Allow",
      "Principal": {
        "Service": "meetings.chime.amazonaws.com"
      },
      "Action": "SNS:Publish",
      "Resource": "arn:aws:sns:us-east-1:_YOUR_ACCOUNT_ID_:_YOUR_TOPIC_",
      "Condition": {
        "StringEquals": {
          "aws:SourceAccount": "_YOUR_ACCOUNT_ID_"
        },
        "ArnLike": {
          "aws:SourceArn": "arn:aws:chime:us-east-1:_YOUR_ACCOUNT_ID_:meeting/*"
        }
      }
    }

````

**Comment by mamsoudi** [comment]
> For those who facing same issue, the problem is permission:
> 
> {
>       "Sid": "allow-chime-sdk-access-statement-id",
>       "Effect": "Allow",
>       "Principal": {
>         "Service": "meetings.chime.amazonaws.com"
>       },
>       "Action": "SNS:Publish",
>       "Resource": "arn:aws:sns:us-east-1:_YOUR_ACCOUNT_ID_:_YOUR_TOPIC_",
>       "Condition": {
>         "StringEquals": {
>           "aws:SourceAccount": "_YOUR_ACCOUNT_ID_"
>         },
>         "ArnLike": {
>           "aws:SourceArn": "arn:aws:chime:us-east-1:_YOUR_ACCOUNT_ID_:meeting/*"
>         }
>       }
>     }

I'm still facing the same issue even after updating the permission's `ArnLike` attribute.
Hey @augusto3691 was there anything else you had to do to get it to work?
