### ISSUE TITLE
Content sharing denied

### ISSUE THREAD

**Issue by lawrencepit** [aws/amazon-chime-sdk-js#205]
Using the latest Chrome browser, running demo meetingV2, and clicking the "Share" button, I do get a popup where I can select e.g. the entire screen to share, however, after clicking the "Share" button of the popup, nothing appears to be shared. 

The javascript console shows the following error:

systemDefaultContentShareController.js:24 Uncaught (in promise) DOMException: Permission denied by system

Is there a way to test whether the user can share content to begin with, before showing the popup? Or, could a callback be added (perhaps in the ContentShareObserver) that is called whenever it turns out sharing is not permitted by the system?

**Comment by aburnson** [comment]
> Is there a way to test whether the user can share content to begin with, before showing the popup? Or, could a callback be added (perhaps in the ContentShareObserver) that is called whenever it turns out sharing is not permitted by the system?

Due to the nature of the underlying `getDisplayMedia` request, there is not a way to know whether it will succeed until after the browser displays the pop-up. You can test the behavior of `getDisplayMedia`, by opening a browser console and executing `stream = await navigator.mediaDevices.getDisplayMedia()`, which is similar to what the SDK does.

> systemDefaultContentShareController.js:24 Uncaught (in promise) DOMException: Permission denied by system

As to why you are getting a `Permission denied by system`. It seems there is a setting on your system that is preventing the browser from doing a screen capture. If you are on macOS, for example, you would need to ensure that Camera and Microphone are enabled for the browser application in System Preferences > Security & Privacy > Privacy.

Closing issue as it does not appear at the moment that there is a bug in the SDK.

**Comment by Mauricio-Arantes** [comment]
I came here with a similar doubt. How i can caught this error `Permission denied by sistem`?

**Comment by kelvin2200** [comment]
I would also like to know how to catch that promise. The thing is, a user can cancel the request to share content, after which a DOM exception is thrown.... we must be able to catch that

**Comment by davide-desio-eleva** [comment]
Hi, we are also experiencing this issue as described by @kelvin2200.
Basically after canceling a share content session, no more sharing is possible.

Workflow to repeat the issue (on chrome):
- start share content
- click on cancel button
- error "Permission denied by system" is shown in console
- click again on share content, nothing happens.

Attaching a video for reference.
@lawrencepit have you find any solution on this?
@andibrae-amzn have you got any hint on this?

https://user-images.githubusercontent.com/20799924/151540896-3388b89a-0d03-4af5-873e-b1764ec077f1.mov

**Comment by antennix** [comment]
I had the same issue today but solved it with the latest version of chrome browser.

**Comment by davide-desio-eleva** [comment]
Hi @antennix, I've got latest one as well but this is still an open issue to me.

<img width="705" alt="Schermata 2022-01-28 alle 13 22 44" src="https://user-images.githubusercontent.com/20799924/151546207-e9069a32-e01d-4fad-8974-83c779dce35d.png">

**Comment by SplashLearn-sudarshan** [comment]
@davide-desio-eleva 
We encountered this issue in react sdk. It might help in your case.

This issue occurred while loading our assets from a CDN server which usually has a different domain compared to website domain in your browser url.

In such cases chrome/firefox doesn’t listen to event listeners of type "unhandledrejection". Anywhere in chime source code if these events are being used they won’t be listened by browsers and their callbacks won’t run.

To allow browsers to listen to "unhandledrejection" events you need to add an extra attribute crossorigin=‘anonymous’  in your script tag while injecting bundles in your template files.

This issue won’t occur if the script loaded in your html file is from same domain as the one you’re using to open your website.

[https://stackoverflow.com/questions/40026381/unhandledrejection-not-working-in-chrome](https://stackoverflow.com/questions/40026381/unhandledrejection-not-working-in-chrome)
