### ISSUE TITLE
Failed to get video device in Chrome 98

### ISSUE THREAD

**Issue by stanggt3** [aws/amazon-chime-sdk-js#2052]
We recently noticed that our application no longer works in Chrome 98. Both the app itself and the readiness checker cannot get the video. Nothing has changed in our application.

[ERROR] SDK - failed to get video device for constraints {"video":{"deviceId":{"exact":"91530b4f9878a844d2bb2989b31e0178f7947aa296fc1a6f0ff9bb7209c562bd"},"width":{"ideal":1280},"height":{"ideal":720},"frameRate":{"ideal":15},"googCpuOveruseDetection":true,"googCpuOveruseEncodeUsage":true,"googCpuOveruseThreshold":85,"googCpuUnderuseThreshold":55}}: NotReadableError: Could not start video source

**Comment by devalevenkatesh** [comment]
Thanks for reporting this issue. The `NotReadableError` can have many reason as stated in the MDN doc:
https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getUserMedia

It would be great to follow the bug template while filing this issue and provide us with the complete browser console logs. Couple of next things we can try checking:
- Can you reproduce on the JS SDK meeting demo? [Link](https://github.com/aws/amazon-chime-sdk-js/tree/main/demos/browser)
- When selecting video input device in you app, are there any back to back `chooseVideoInputDevice` API calls?
- Can you confirm again that below code works for the problematic device? This is to check if its a generic WebRTC issue or JS SDK.
1. Open below demo in Chrome and click "Open camera" once. This should open your camera after you allow permission to it. Then just refresh the page and this demo should now already have permission to your camera device already. After this perform next steps.
2. Now, open the Chrome browser devtools console and enter and then hit enter:
```
await navigator.mediaDevices.enumerateDevices()
```
This will list `audioinput`, `audiooutput` and `videoinput` media devices in devtools.
3. Next, copy the `deviceId` value against the problematic device and enter below code again in devtools, make sure you use the copied `deviceId` in place of `<copied-deviceId-stated-above>` and then hit enter again, this should again start the video without clicking the "Open camera" button:
```
document.getElementsByTagName('video')[0].srcObject = await navigator.mediaDevices.getUserMedia({"video":{"deviceId":{"exact":"<copied-deviceId-stated-above>"},"width":{"ideal":960},"height":{"ideal":540},"frameRate":{"ideal":15}}})
```

If this results into some problem, then this would be either the device specific issue or browser specific. Please let us know if you need further help.

**Comment by stanggt3** [comment]
Still investigating

**Comment by xzer** [comment]
I observed a similar issue in a webview inside android 8.0.

I did some tests and the reason looks because the old webview does not support specify width/height, once I remove the width/height from constrain, it will work well.
