### ISSUE TITLE
Noise is coming out from the speakers when using chime on macOS - Safari browser

### ISSUE THREAD

**Issue by itzikbuktshin** [aws/amazon-chime-sdk-js#2057]
### What happened and what did you expect to happen?

Join a meeting via Safari web browser and I'm hearing myself repeatedly or with eco.

I'm expecting not to hear myself at all. 

### Have you reviewed our existing documentation?

- [X] GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [X] FAQs [page](https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html)
- [X] README [page](https://github.com/aws/amazon-chime-sdk-js#amazon-chime-sdk-for-javascript)
- [X] Feature-specific [guides](https://github.com/aws/amazon-chime-sdk-js#guides)

### Reproduction steps

Join video conference with microphone audio.

Even when the mic is muted, we still can hear the noise.

### Amazon Chime SDK for JavaScript version

2.27.0

### What browsers are you seeing the problem on?

Safari on macOS

### Browser version

15.x

### Browser console logs

-

**Comment by LeviSklaroff** [comment]
Hi, I tried reproducing the issue as you provided but I was not able to hear myself, so I have a few questions to try and reproduce.

- By "Even when the mic is muted, we still can hear the noise" do you mean the mic is muted in the chime app or is the mic itself muted?
- Is this with the Mac's internal microphone or is this with an external microphone.
- Are you able to reproduce this on our [meeting demo](https://github.com/aws/amazon-chime-sdk-js/tree/main/demos/browser/app/meetingV2)?

**Comment by itzikbuktshin** [comment]
Hi. 
The mic is muted in the chime app.
I'm using Mac's mic microphone.
I wasn't able to reproduce it with the meeting demo app in v.2.27.0

**Comment by LeviSklaroff** [comment]
Hmm, that's quite odd. 

- Could you provide a meeting id for when this bug occurs?
- Could provide browser console logs from the user experiencing this issue?

**Comment by LeviSklaroff** [comment]
Closing as builder has not responded in over 30 days.
