### ISSUE TITLE
Pin a user permanently to the "featured" video tile

### ISSUE THREAD

**Issue by itsbeautifullife** [aws/amazon-chime-sdk-js#2063]
# Community Note
* Please vote for this issue by adding a 👍 reaction to the issue. This will help the community and maintainers from the Amazon Chime SDK team to prioritize this request.
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request.
* Please go through the existing [issues](https://github.com/aws/amazon-chime-sdk-js/issues) to see if your request has already been recommended.
* Please do not use this template for bugs or support. Each individual repository has a PR template, documentation and resources for [troubleshooting](https://github.com/aws/amazon-chime-sdk-js#troubleshooting-and-support).
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.

# Tell us about your request
## What do you want us to build?
Which Amazon Chime SDK or feature area is this request for?
Such as: [amazon-chime-sdk-js](https://github.com/aws/amazon-chime-sdk-js)

## Tell us about the problem you are trying to solve and why is it hard?
We are doing an online seminar and we need to make the presenter (main speaker) the "featured" video tile meaning everyone will see that user which is pinned as the main video title. Currently any talking or other sound from audiences can disturb the focus

## How are you currently solving a problem?
We can tell other users to mute themselves but it's not feasible

## Additional context
We tried to search the code which does video title switching in `meetingV2.html` and `meetingV2.ts` but were not able to find it since looks like that code is in JS SDK files.

**Comment by ltrung** [comment]
Please refer to this comment https://github.com/aws/amazon-chime-sdk-js/issues/1122#issuecomment-969149430 for more details, but you can create a copy of active speaker policy to suppress the default behavior to always feature active speaker. After that you can manually call `setHasBandwidthPriority` from `NScaleVideoUplinkBandwidthPolicy` to set the presenter the main video.

**Comment by nainkunal933** [comment]
@itsbeautifullife Did Trung's comment answer your question?

**Comment by ltrung** [comment]
Closing for now but let us know if you have additional questions.

**Comment by jienco** [comment]
I am building an application where I have this need to "pin" or "spotlight" one or two attendees at a time. These are speakers that are featured by a meeting operator, based on the talks they present in a program.

As mentioned by @itsbeautifullife , "any talking or other sound from audiences can disturb the focus". Having in mind that  currently (as far as I understand) there is no way to prevent attendees to unmute themselves, this can be a problem. In our use case, speakers are unmuted when they are featured by a meeting operator.

In addition, I need to send these featured attendee(s) to the live stream. [I posted a related question in the AWS re:post forum here](https://repost.aws/questions/QUhCrntIB9SOyFLfYYYQZbjQ/is-there-a-way-to-dynamically-change-selectedvideostreams-for-a-chime-sdk-media-pipeline). But to begin with, it would be nice to be able to feature attendee(s) in the meeting.
