### ISSUE TITLE
Live transcription on PRODUCTION

### ISSUE THREAD

**Issue by Brenerss** [aws/amazon-chime-sdk-js#2085]
### What happened and what did you expect to happen?

I managed to configure it to run locally but when I go to test in production, the url returns 502

https://example.com/transcript?title=dd3858cbc47a22b6edfe5cf6bcd41538
Request Method: GET
Status Code: 502 

Do you have an example to use when configuring? I did it this way, but I imagine that some more configuration is missing

this function is in `serverless/src/handlers.js`

```
exports.transcript = async (event, context, callback) => {
  var response = {
    'statusCode': 200,
    'headers': {},
    'body': '',
    'isBase64Encoded': false,
  };
  const title = event.queryStringParameters.title;
  let meetingInfo = await getMeeting(title);
  const res = await chime.startMeetingTranscription({
    MeetingId: meetingInfo.Meeting.MeetingId,
    TranscriptionConfiguration: {
      'EngineTranscribeSettings': {
        'LanguageCode': 'pt-BR',
        // "VocabularyFilterMethod": "tag",
        // "VocabularyFilterName": "profanity",
        // "VocabularyName": "lingo",
        // "Region": "us-east-1",
        'EnablePartialResultsStabilization': true,
        'PartialResultsStability': 'high',
        // "ContentIdentificationType": "PII",
        // "ContentRedactionType": "PII",
        // "PiiEntityTypes": "ALL",
        // "LanguageModelName": "language-model"
      },
    },
  }).promise();

  response.body = JSON.stringify(res, '', 2);

  callback(null, response);
};
```

### Have you reviewed our existing documentation?

- [X] GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [X] FAQs [page](https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html)
- [X] README [page](https://github.com/aws/amazon-chime-sdk-js#amazon-chime-sdk-for-javascript)
- [X] Feature-specific [guides](https://github.com/aws/amazon-chime-sdk-js#guides)

### Reproduction steps

production stage

### Amazon Chime SDK for JavaScript version

^2.17.0

### What browsers are you seeing the problem on?

Chrome

### Browser version

97.0.4692.71 64 bits

### Browser console logs

none

**Comment by LeviSklaroff** [comment]
This AWS post has an example of configuring: https://docs.aws.amazon.com/chime/latest/dg/initiate-transcription.html although it looks like your config is correct. What is https://example.com/transcript?title=dd3858cbc47a22b6edfe5cf6bcd41538 in this case?

**Comment by Brenerss** [comment]
`example.com` is   oculting my production url

**Comment by LeviSklaroff** [comment]
Ah sorry, I was wondering what the transcript?title=dd3858cbc47a22b6edfe5cf6bcd41538 endpoint was in this case? Is this the meeting that is being transcripted?
