### ISSUE TITLE
How increace media creation limitation 

### ISSUE THREAD

**Issue by MjdBh** [aws/amazon-chime-sdk-js#2100]
### What happened and what did you expect to happen?

When  I am starting a new media creation pipeline, I am getting the following error. But I can not find anywhere how I can increase it.

 "errorType": "ResourceLimitExceeded",
    "errorMessage": "Cannot create new media capture pipeline for source type 'ChimeSdkMeeting' and source arn 'arn:aws:chime::*************:meeting:67be25d6-7eca-475f-b17c-901ee9bf0706'. Limit reached",
    "code": "ResourceLimitExceeded",
    "message": "Cannot create new media capture pipeline for source type 'ChimeSdkMeeting' and source arn 'arn:aws:chime::*************:meeting:67be25d6-7eca-475f-b17c-901ee9bf0706'. Limit reached",

### Have you reviewed our existing documentation?

- [X] GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [X] FAQs [page](https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html)
- [X] README [page](https://github.com/aws/amazon-chime-sdk-js#amazon-chime-sdk-for-javascript)
- [X] Feature-specific [guides](https://github.com/aws/amazon-chime-sdk-js#guides)

### Reproduction steps

Starting new media capture on our account

### Amazon Chime SDK for JavaScript version

2.16.1

### What browsers are you seeing the problem on?

Chrome

### Browser version

99

### Meeting and Attendee ID Information.

67be25d6-7eca-475f-b17c-901ee9bf0706

### Browser console logs

Don't have any log. 

"errorType": "ResourceLimitExceeded",
    "errorMessage": "Cannot create new media capture pipeline for source type 'ChimeSdkMeeting' and source arn 'arn:aws:chime::******************:meeting:67be25d6-7eca-475f-b17c-901ee9bf0706'. Limit reached",
    "code": "ResourceLimitExceeded",
    "message": "Cannot create new media capture pipeline for source type 'ChimeSdkMeeting' and source arn 'arn:aws:chime::************************:meeting:67be25d6-7eca-475f-b17c-901ee9bf0706'. Limit reached",
    "time": "2022-03-09T20:54:20.564Z",
    "requestId": "ee4469fb-f66e-47d8-a8ff-cb62cb7a80b1",
    "statusCode": 400,
    "retryable": false,
    "retryDelay": 71.12881894780392,
    "stack": [
        "ResourceLimitExceeded: Cannot create new media capture pipeline for source type 'ChimeSdkMeeting' and source arn 'arn:aws:chime::**************:meeting:67be25d6-7eca-475f-b17c-901ee9bf0706'. Limit reached",
        "    at Object.extractError (/var/runtime/node_modules/aws-sdk/lib/protocol/json.js:52:27)",
        "    at Request.extractError (/var/runtime/node_modules/aws-sdk/lib/protocol/rest_json.js:49:8)",
        "    at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:106:20)",
        "    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:78:10)",
        "    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/request.js:686:14)",
        "    at Request.transition (/var/runtime/node_modules/aws-sdk/lib/request.js:22:10)",
        "    at AcceptorStateMachine.runTo (/var/runtime/node_modules/aws-sdk/lib/state_machine.js:14:12)",
        "    at /var/runtime/node_modules/aws-sdk/lib/state_machine.js:26:10",
        "    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:38:9)",
        "    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:688:12)"
    ]

**Comment by niborkar** [comment]
Hi MjdBh@,

The error indicates that you are trying to create more than one media capture pipeline for the same ChimeSdkMeeting at a given time, which is not allowed. We currently support creating only one capture pipeline per meeting.

**Comment by MjdBh** [comment]
We create meeting at first, so this situation can't happen.
We hadn't had this problem for three months while deploying it to production.
But this type of error occurs in this week.

**Comment by tenge-amzn** [comment]
@MjdBh Have you seen more of the issues? 
I believe this only occurred on March 9th because of some temporary failure. Let us know if this issue is persistent.
