### ISSUE TITLE
Exists some voice changer for amazon chime sdk?

### ISSUE THREAD

**Issue by Brenerss** [aws/amazon-chime-sdk-js#2103]
### What are you trying to do?

I'm trying change my voice to be like robot

### What documentation have you looked at so far?

README.md, Amazon Chime SDK Developer Guide, etc.

**Comment by nainkunal933** [comment]
Hey @Brenerss,

I have worked mostly with video stream transform but I think audio transform is also possible. While doing some research I found this article that showcases how to modify audio streams:
[Transforming audio and shared content in the Amazon Chime SDK for JavaScript](https://aws.amazon.com/blogs/business-productivity/transforming-audio-and-shared-content-in-the-amazon-chime-sdk-for-javascript/)

The JS SDK class that you are looking for is `SingleNodeAudioTransformDevice` which can be found here: https://aws.github.io/amazon-chime-sdk-js/classes/singlenodeaudiotransformdevice.html.

Currently, we are using a beep sound to test our application in our JS SDK demo. This audio file is using the `SingleNodeAudioTransformDevice` to generate the tone. The code for `TestSound`: https://github.com/aws/amazon-chime-sdk-js/blob/main/demos/browser/app/meetingV2/audio/TestSound.ts

The code to alter the stream will look something like this:
```
const audioContext: AudioContext = new (window.AudioContext || window.webkitAudioContext)();
const gainNode = audioContext.createGain();
gainNode.gain.value = 0;
const oscillatorNode = audioContext.createOscillator();
oscillatorNode.frequency.value = this.frequency;
oscillatorNode.connect(gainNode);
const destinationStream = audioContext.createMediaStreamDestination();
```

To add a robotic voice you will have to alter the original audio stream. We currently do not provide a preset for robotic voice so you will have to develop that on your own. 

Happy coding!! Please let me know if that answers your question and if this issues can be resolved.

**Comment by nainkunal933** [comment]
Please feel free to reopen this issue if you still need help.
