### ISSUE TITLE
how could i register a local and production eventbrige

### ISSUE THREAD

**Issue by Brenerss** [aws/amazon-chime-sdk-js#2108]
### What are you trying to do?

I would like to get information from the SDK server from the users who left the meeting to register in our database

We are using Amazon chime sdk react too

### How can the documentation be improved to help your use case?

*For example: Include a section on how to configure the meeting session.*

### What documentation have you looked at so far?

*For example: README.md, Amazon Chime SDK Developer Guide, etc.

**Comment by ltrung** [comment]
Could you explain more about your use case? I am not sure I understand what you mean by local and production event bridge?

**Comment by Brenerss** [comment]
I managed to make it work, but not all events that happen are returned, sometimes a participant leaves the meeting but it doesn't show in the log that the participant left

**Comment by ltrung** [comment]
You should get events 100% of the time. Could you provide some meeting Ids that you do not receive meeting leave event bridge events?
