### ISSUE TITLE
Japan Toll Free Dialing not working

### ISSUE THREAD

**Issue by Pieter1989** [aws/amazon-chime-sdk-js#2114]
### What happened and what did you expect to happen?

All chime toll free phonelines for Japan keep on dropping before initiating call. Issue started on Tuesday. Impossible to call in from toll Free number on chime in Japan.

### Have you reviewed our existing documentation?

- [X] GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [X] FAQs [page](https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html)
- [X] README [page](https://github.com/aws/amazon-chime-sdk-js#amazon-chime-sdk-for-javascript)
- [X] Feature-specific [guides](https://github.com/aws/amazon-chime-sdk-js#guides)

### Reproduction steps

not applicable

### Amazon Chime SDK for JavaScript version

5.6.937

### What browsers are you seeing the problem on?

Chime app

### Browser version

5.6.937

### Browser console logs

not applicable

**Comment by dvervitsiotis** [comment]
I'm sorry to hear that you're having issues dialing into your meetings. The Amazon Chime application is different than the Amazon Chime SDK, and for the best possible support you should follow the steps here - https://answers.chime.aws/questions/294/how-do-i-get-support-for-amazon-chime.html.

That said, I just tested the numbers manually and was able to join meetings without any problems. If you can provide additional information by following the process linked above, the team can look into your issues in particular.
