### ISSUE TITLE
Sharing a test video via Content Share doesnt send stream to remote attendee

### ISSUE THREAD

**Issue by michhyun1** [aws/amazon-chime-sdk-js#2119]
### What happened and what did you expect to happen?

From the meeting demo, I clicked on 'Test Video' to share to the other attendee. From the other attendee's perspective, I only see a black video tile and no audio being sent.

![Screen Shot 2022-03-18 at 11 36 40 AM](https://user-images.githubusercontent.com/54328451/159063629-74a02a79-a3c3-4f05-8691-ac0697e31560.png)

This happens on my Android OS - Samsung S20 Chrome browser (v97).

For more context, here is the bug report:
https://bugs.chromium.org/p/chromium/issues/detail?id=1156408

### Have you reviewed our existing documentation?

- [X] GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [X] FAQs [page](https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html)
- [X] README [page](https://github.com/aws/amazon-chime-sdk-js#amazon-chime-sdk-for-javascript)
- [X] Feature-specific [guides](https://github.com/aws/amazon-chime-sdk-js#guides)

### Reproduction steps

Join a meeting with two separate attendees, click on 'Test Video' button like shown above. 

### Amazon Chime SDK for JavaScript version

2.29.0

### What browsers are you seeing the problem on?

Android Chrome

### Browser version

97

### Browser console logs

n/a

**Comment by ltrung** [comment]
This only happens in Android Chrome and it is due to Chrome bug with H.264 encoding.

**Comment by ltrung** [comment]
This only happens in Android Chrome and it is due to Chrome bug with H.264 encoding.
