### ISSUE TITLE
Explain what video tiles are and their lifecycle

### ISSUE THREAD

**Issue by aburnson** [aws/amazon-chime-sdk-js#212]
From #198

**Comment by simmkyu** [comment]
Closing this issue as [Video](https://github.com/aws/amazon-chime-sdk-js#video) and [Screen and content share](https://github.com/aws/amazon-chime-sdk-js#screen-and-content-share) sections in README explain the video tile object and examples how the local/remote/content tile is bound to a video element in the `videoTileDidUpdate` observer method.
