### ISSUE TITLE
MediaCapturePipeline All Attendees (even those who join after recording started)

### ISSUE THREAD

**Issue by ahmed-classtra** [aws/amazon-chime-sdk-js#2122]
### What are you trying to do?

I'm trying to record the videos for all attendees in a meeting. Using the CreateMediaCapturePipeline API. The problem is that it requires the attendee ids upfront. Is there a way to tell the media capture API to record all videos? Also, is there a way to change this after a media capture pipeline is created? Say we want to add or remove a certain participant to the capture? What's the best way of achieving at least the first one (recording everyone)

**Comment by tenge-amzn** [comment]
https://docs.aws.amazon.com/chime/latest/APIReference/API_CreateMediaCapturePipeline.html

You can leave sourceConfiguration empty while video enabled. All attendee's video will be recorded.

**Comment by ahmed-classtra** [comment]
Thank you @tenge-amzn. Will deleting and restarting the recording pipeline cause a drop in the video/audio recorded?

**Comment by nehtambe** [comment]
Yes, video/audio artifacts will not be saved between an old deleted pipeline and a new one started with different configuration.

**Comment by ahmed-classtra** [comment]
Thanks, @nehtambe. That's not going to be good for our users. For now, at least, we'll have to record all videos until a future update provides more capability. There is, however, a lack of documentation on this part. I was not able to find anything on that docs that documents the behavior that if we leave the attendee ids blank it will record everything. 

One final thing, if we provide a list of attendee ids, and these attendees are not yet present, they will only join after the meeting started, will they be included in the recording? I'm going to try it anyways, but asking here for the benefit of anyone reading or searching.

**Comment by sinanliuAmazon** [comment]
yes, the individual video streams will included in the recording if providing a list of attendee ids upfront. Or if the list of attendee ids is not available yet when creating the capture pipeline, you can also use the `SelectedVideoStreams .ExternalUserIds ` field to select individual video stream by external user ids.

**Comment by ahmed-classtra** [comment]
Thank you @sinanliuAmazon . That's very helpful. Good work chime team.
