### ISSUE TITLE
Empty video tile received from M1 mac with Firefox

### ISSUE THREAD

**Issue by alex-m-aws** [aws/amazon-chime-sdk-js#2123]
### What happened and what did you expect to happen?

**What happened**
Users running our app on an M1 mac with Firefox cannot successfully send web cam video to other attendees. They can see themselves as a local camera tile, but other users cannot see them.

This happens both in our own app, and in the meeting V2 demo app.

**What I expected**
All users who turn on their cameras should successfully have their video feeds received by other users.

### Have you reviewed our existing documentation?

- [X] GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [X] FAQs [page](https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html)
- [X] README [page](https://github.com/aws/amazon-chime-sdk-js#amazon-chime-sdk-for-javascript)
- [X] Feature-specific [guides](https://github.com/aws/amazon-chime-sdk-js#guides)

### Reproduction steps

- Start a meeting
- Have two users join, one with M1 mac on Firefox, and one on another setup
- Turn on cameras for both users
- The user with M1 mac on Firefox will see their own local video, but the other user will not see them as a remote tile

### Amazon Chime SDK for JavaScript version

2.25.0

### What browsers are you seeing the problem on?

Firefox

### Browser version

91.6.1esr (64-bit)

### Meeting and Attendee ID Information.

Meeting ID: 3ba22346-3d08-44c4-b5bf-f847d43e0706

### Browser console logs

Deployed endpoint does not output browser logs, cannot test locally

**Comment by cgandhi22** [comment]
I tried with SDK demo app. I am able to see my video tile as firefox user on other browsers. Meeting ID: f7786f10-66d8-4b68-bcf5-c23e1a4e2713
I am in firefox version: 97.0.2 (64-bit)

**Comment by ltrung** [comment]
@alex-m-aws Could you try the latest version 2.30 to see if you could reproduce the issue as we could not reproduce the issue with our M1 machines.

**Comment by alex-m-aws** [comment]
Just updated to latest version on our app and same issue. The serverless demo app from the repo is hard set to 2.23 because it uses the repo version of the SDK, but still same issue there. I am an AWS employee, could we schedule a call?

**Comment by ltrung** [comment]
@alex-m-aws Could you cut a support ticket then?

**Comment by alex-m-aws** [comment]
As an update, we tested with this same user on an official WebRTC demo app and they have the same problem. So it's not a chime SDK issue.
