### ISSUE TITLE
Video stream not recovering after bandwidth throttle and recovery

### ISSUE THREAD

**Issue by mark-vanr** [aws/amazon-chime-sdk-js#2124]
### What happened and what did you expect to happen?

We are using simulcast with the PriorityBasedDownlinkPolicy. Both users were on Chrome, my local machine was Ubuntu 20.04.4 and remote was Windows 10. In our app if we receive video we show the stream on the tile; otherwise if no video is on or video is paused by downlink policy we show a colored tile. 

I started a meeting with 2 attendees on different machines, both sides sending video. On my local machine I used a tool called Wondershaper to drop my downlink bandwidth to 300kbps for a short time, then removed the throttle. I saw the video feed pause and drop to the fallback tile after the bandwidth reduction as expected. On bandwidth recovery it seems to have attempted to enable the inbound stream, and the stream was un-paused by the policy (seen on line 5086 of log `bandwidth_shaped_no_recover...`), but instead of a video feed the video element showed as grey with no incoming video. The remote client was continuing to send its feed as normal. 

I tried to disable and re-enable the remote client's video but it didn't have an effect on the local, even though I saw the events come through (video events and a new tileId 3 was made, where previously they were tileId 2).

On my local machine I tried refreshing the client to try to trigger a full recovery, but the inbound tile also stayed on the colored fallback tile even though remote client was still sending video. This is the secondary log (`after_refresh...`) attached for interests sake.

### Have you reviewed our existing documentation?

- [X] GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [X] FAQs [page](https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html)
- [X] README [page](https://github.com/aws/amazon-chime-sdk-js#amazon-chime-sdk-for-javascript)
- [X] Feature-specific [guides](https://github.com/aws/amazon-chime-sdk-js#guides)

### Reproduction steps

Start a meeting with 2 participants, both with video on, using Simulcast and VideoPriorityDownlinkPolicy.
Throttle download bandwidth on one client (I throttled to 300kbps with wondershaper) and then remove throttle.
Throttled client inbound video from remote does not recover

### Amazon Chime SDK for JavaScript version

2.27.0

### What browsers are you seeing the problem on?

Chrome

### Browser version

Version 99.0.4844.82 (Official Build) (64-bit)

### Meeting and Attendee ID Information.

Attendee ID experiencing issue: `fb419521-83c0-677a-a393-d26a5971c6d5`
Attendee ID of sending user: `940a019f-aa66-0837-9f9b-9ba092b07233`

### Browser console logs

Receiving attendee logs - the un-pause after bandwidth recovers occurs on line 5086 with line `SDK - bwe: unpausing attendee 940`)
[bandwidth_shaped_no_recover-1648071474678.log](https://github.com/aws/amazon-chime-sdk-js/files/8336924/bandwidth_shaped_no_recover-1648071474678.log)

Refreshed browser to re-join the same meeting, but the video also did not come through - logs from after refresh:
[after_refresh_bandwidth_shaped_no_recover.log](https://github.com/aws/amazon-chime-sdk-js/files/8336926/after_refresh_bandwidth_shaped_no_recover.log)

**Comment by ltrung** [comment]
@mark-vanr Have you tried with 2.29? We have some fixes for priority-based downlink.

**Comment by mark-vanr** [comment]
Thanks @ltrung looks like the changes in 2.30 did fix this problem -- once the network stabilized after the throttling and unthrottling, the video did come back up. Cheers!
