### ISSUE TITLE
Can't upgrade package.json to v3.

### ISSUE THREAD

**Issue by amiller5bf** [aws/amazon-chime-sdk-js#2125]
### What are you trying to do?
Follow the upgrade guide: https://github.com/aws/amazon-chime-sdk-js/blob/main/guides/17_Migration_to_3_0.md to test so we know v3 works in our project.

### How can the documentation be improved to help your use case?

Not sure if its documentation. Trying to figure out why I'm moving from my current package.json to v3 sdk and its saying there is a dependency issue.

Here is the package i'm using. 

```
{
  "name": "chime-sdk-meeting-demo",
  "version": "0.1.0",
  "dependencies": {
    "@types/react": "^16.9.46",
    "@types/react-dom": "^16.9.5",
    "@types/styled-components": "^4.4.2",
    "@types/webpack-env": "^1.15.1",
    "@typescript-eslint/eslint-plugin": "^2.19.2",
    "@typescript-eslint/parser": "^2.19.2",
    "amazon-chime-sdk-component-library-react": "^2.8.0",
    "amazon-chime-sdk-js": "^2.13.0",
    "aws-sdk": "^2.731.0",
    "fs-extra": "^10.0.0",
    "react": "^17.0.1",
    "react-dom": "^17.0.1",
    "react-router-dom": "^5.1.2",
    "react-use-websocket": "^2.7.1",
    "socket.io-client": "^4.2.0",
    "styled-components": "^5.0.0",
    "styled-system": "^5.1.5",
    "throttle-debounce": "^2.3.0",
    "websocket": "^1.0.34"
  },
  "scripts": {
    "lint": "eslint src --ext .js,.jsx --fix",
    "build": "webpack --config ./webpack.config.js --mode=production --devtool=false",
    "start:client": "npm run build && webpack-dev-server",
    "start:backend": "node server.js",
    "start": "concurrently \"npm run start:client\" \"npm run start:backend\""
  },
  "devDependencies": {
    "@babel/core": "^7.11.1",
    "@babel/plugin-transform-regenerator": "^7.10.4",
    "@babel/plugin-transform-runtime": "^7.11.0",
    "@babel/preset-env": "^7.11.0",
    "@babel/preset-react": "^7.10.4",
    "@babel/runtime": "^7.11.2",
    "@fortawesome/fontawesome-svg-core": "^1.2.30",
    "@fortawesome/free-solid-svg-icons": "^5.14.0",
    "@fortawesome/react-fontawesome": "^0.1.9",
    "@types/react-router-dom": "^5.1.3",
    "@types/styled-system": "^5.1.9",
    "@types/throttle-debounce": "^2.1.0",
    "@types/websocket": "^1.0.4",
    "babel-eslint": "^9.0.0",
    "babel-loader": "^8.0.4",
    "concurrently": "5.2.0",
    "css-loader": "^5.2.6",
    "eslint": "^5.16.0",
    "eslint-config-airbnb": "^17.1.1",
    "eslint-config-prettier": "^4.3.0",
    "eslint-config-wesbos": "^0.0.19",
    "eslint-plugin-html": "^5.0.5",
    "eslint-plugin-import": "^2.22.0",
    "eslint-plugin-jsx-a11y": "^6.2.3",
    "eslint-plugin-prettier": "^3.1.2",
    "eslint-plugin-react": "^7.20.5",
    "eslint-plugin-react-hooks": "^1.7.0",
    "html-webpack-inline-source-plugin": "0.0.10",
    "html-webpack-plugin": "^3.2.0",
    "prettier": "^1.19.1",
    "react-is": "^17.0.0",
    "regenerator-runtime": "^0.13.7",
    "resize-observer-polyfill": "^1.5.1",
    "style-loader": "^1.2.1",
    "terser-webpack-plugin": "^1.4.5",
    "ts-loader": "^6.2.1",
    "typescript": "^3.9.7",
    "webpack": "^4.44.1",
    "webpack-cli": "^3.3.11",
    "webpack-dev-server": "^3.11.0"
  }
}
```

When I attempt to run `npm install --save amazon-chime-sdk-js@3` in my cli, I'm getting this error stack. 

npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: chime-sdk-meeting-demo@0.1.0
npm WARN Found: amazon-chime-sdk-js@2.26.0
npm WARN node_modules/amazon-chime-sdk-js
npm WARN   peer amazon-chime-sdk-js@"^2.26.0" from amazon-chime-sdk-component-library-react@2.15.0
npm WARN   node_modules/amazon-chime-sdk-component-library-react
npm WARN     amazon-chime-sdk-component-library-react@"^2.15.0" from the root project
npm WARN   1 more (the root project)
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer amazon-chime-sdk-js@"^2.26.0" from amazon-chime-sdk-component-library-react@2.15.0
npm WARN node_modules/amazon-chime-sdk-component-library-react
npm WARN   amazon-chime-sdk-component-library-react@"^2.15.0" from the root project
npm ERR! code ETARGET
npm ERR! notarget No matching version found for amazon-chime-sdk-js@3.0.0.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/amiller5/.npm/_logs/2022-03-24T15_45_08_911Z-debug.log

I've tried upgrading my package to match the latest commits to master branch for amazon-chime-sdk-component-library-react and amazon-chime-sdk-js but not seeing any difference in results. Could someone help?

**Comment by devalevenkatesh** [comment]
Thanks for reporting the issue, currently we are providing beta versions of 3.0.0 for amazon-chime-sdk-js. Hence, in order to install a beta please do the following:

```
npm install --save amazon-chime-sdk-js@beta
```

I am updating the migration guide adding a note to this. Please let us know if you run into any issues.

**Comment by devalevenkatesh** [comment]
The PR is merged now and I closing this issue, please feel free to let us know if this is still an issue.
