### ISSUE TITLE
Video stream rapid stop-and-recovery with simulcast and priority-based downlink

### ISSUE THREAD

**Issue by mark-vanr** [aws/amazon-chime-sdk-js#2131]
### What happened and what did you expect to happen?

With simulcast enabled and using a VideoPriorityBasedDownlink policy, some meeting attendees experience a rapid drop-and-recovery of attendee video streams, which are not associated with a logged entry for pausing purposefully due to the downlink policy (which would be logged as `SDK - bwe: pausing streamId ...` and also by our client as `Downlink policy - pausing video for tileId #`via the `tileWillBePausedByDownlinkPolicy` downlink observer event). These were reported in meetings of different sizes, from 1-on-1 to group meetings.

Attached a log where the user reports experiencing this issue during minutes 16:09 and 16:17. I did see that there are some `peer connection negotiation is needed` logs at those specific minutes; but there are also similar negotiations logged at different times where the issue was not noticed, so I'm not sure if that's a false correlation. It is a verbose log as that was sent at the time; I will try to get an info-level log with the same issue.

An example video of the stream recovery in question - the colored background is our fallback for when the attendee has no tileId assigned for video or if the videoTile is paused.
https://user-images.githubusercontent.com/66750108/160016264-9e0bf057-bef4-487a-b9c3-fcde2887420a.mp4

### Have you reviewed our existing documentation?

- [X] GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [X] FAQs [page](https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html)
- [X] README [page](https://github.com/aws/amazon-chime-sdk-js#amazon-chime-sdk-for-javascript)
- [X] Feature-specific [guides](https://github.com/aws/amazon-chime-sdk-js#guides)

### Reproduction steps

No concrete reproducible steps identified yet

### Amazon Chime SDK for JavaScript version

2.27.0

### What browsers are you seeing the problem on?

Chrome

### Browser version

chrome 99

### Browser console logs

Log file from a user commonly experiencing the issue. In these logs the issue occurred noticeably twice, once at 16:09 and once at 16:17 EST. Apologies on the verbose log - it is very verbose.

[verbose_kait_1609_1617_client.apps.us.bluescape.com-1648067978147.log](https://github.com/aws/amazon-chime-sdk-js/files/8346003/verbose_kait_1609_1617_client.apps.us.bluescape.com-1648067978147.log)

**Comment by ltrung** [comment]
@mark-vanr Could you try 2.30 - the latest version? We have some fixes for priority-based downlink.

**Comment by mark-vanr** [comment]
Thanks @ltrung I updated our dev environment to 2.30 and tried again. We didn't see exactly the same behavior, but did run into an issue with pausing-unpausing behavior. Partway through the meeting my remote attendee saw my video stop, and then it began to switch between paused (colored tile) and unpaused with no stream (showing as a grey tile). The first pause event occurred at `15:14:19.240` paused by the bwe, and then for the next 15 minutes it did not recover at all.

I had the remote attendee take a video of what she saw - a short clip here for illustration:
https://user-images.githubusercontent.com/66750108/160194152-86d659ad-7914-4e10-a1f9-955fffd8677d.mp4

Here is the log from the attendee for the whole meeting: 
[remote_meet_client_1514-1525.log](https://github.com/aws/amazon-chime-sdk-js/files/8353584/remote_meet_client_1514-1525.log)

With the video and the logs I managed to correlate this with log activity - what's seen above happened between `15:20:17`-`15:20:19`, which in the logs correlates to what appears to be a loop of `bwe: pausing streamId 15` events and then the audioVideoFacade calling `unpauseVideoTile 3`. We do unbind/bind the video element in there as the tile is paused/unpaused.

A few seconds later that pause/unpause loop stops, and at `15:20:25` there is a `bwe: unpausing` event, but this left the video tile grey while it was attempting something - from `15:20:26` until `15:21:25` when there is a probe timeout logged. It looks like this happened again a time or two before we ended the session; the video stream never fully recovered during that time.

**Comment by hensmi-amazon** [comment]
Hi @mark-vanr  sorry for the delay here, the `unpauseVideoTile 3` calls are interesting because those are tracing a top level call to pause (i.e. not from the policy). Can you verify when your application is calling `unpauseVideoTile`? 

Also I'm not sure how relevant it is, bu we recommend that if using the priority-based downlink policy, that instead of pausing video tiles the application instead uses the `chooseRemoteVideoSources` API on the policy with the desired tile removed from the list.

**Comment by devalevenkatesh** [comment]
No further response on this, hence resolving as stale. Please feel free to re-open if still an issue.
Reference:
- [JS SDK browser demo](https://github.com/aws/amazon-chime-sdk-js/tree/main/demos/browser)
- [Video priority documentation](https://aws.github.io/amazon-chime-sdk-js/modules/prioritybased_downlink_policy.html)
