### ISSUE TITLE
When join the meeting, Join lambda function fails due to incorrect region.

### ISSUE THREAD

**Issue by fromcloud** [aws/amazon-chime-sdk-js#2140]
### What happened and what did you expect to happen?

What happened ?

![image](https://user-images.githubusercontent.com/11764522/160953001-03a0c2e6-29ae-464f-ae72-c957e3f9e67b.png)

When manually set region = us-east-1 in environment variables into lamdba. It works.

### Have you reviewed our existing documentation?

- [X] GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [X] FAQs [page](https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html)
- [X] README [page](https://github.com/aws/amazon-chime-sdk-js#amazon-chime-sdk-for-javascript)
- [X] Feature-specific [guides](https://github.com/aws/amazon-chime-sdk-js#guides)

### Reproduction steps

Under demos/serverless directory 

`npm run deploy -- -r ap-northeast-2 -b <buket-name> -o media-capture -i ap-northeast-2 -s <stack-name>  -a meeting`

Join meeting with API endpoint

### Amazon Chime SDK for JavaScript version

Release 38

### What browsers are you seeing the problem on?

Chrome

### Browser version

99.0.4844.84 

### Meeting and Attendee ID Information.

--

### Browser console logs

Instead of browser console log. 

Please refer to lambda error log below. 
![image](https://user-images.githubusercontent.com/11764522/160953507-866c6145-5258-424b-a504-30a2638336d0.png)

**Comment by simmkyu** [comment]
As of Mar 31, 2022, Amazon Chime SDK does not support the `ap-northeast-2` control region yet.
https://docs.aws.amazon.com/chime/latest/dg/sdk-available-regions.html

AWS Region | Meeting control | Meeting media
--|--|--
Africa (Cape Town) (af-south-1) |  | Yes
Asia Pacific (Mumbai) (ap-south-1)		 |  | Yes
**Asia Pacific (Seoul) (ap-northeast-2)** | **Not supported** | **Yes**
Asia Pacific (Singapore) (ap-southeast-1) | Yes | Yes
Asia Pacific (Sydney) (ap-southeast-2) |  | Yes
Asia Pacific (Tokyo) (ap-northeast-1) |  | Yes
Canada (Central) (ca-central-1) |  | Yes
Europe (Frankfurt) (eu-central-1) | Yes | Yes
Europe (Ireland) (eu-west-1) |  | Yes
Europe (London) (eu-west-2) |  | Yes
Europe (Milan) (eu-south-1) |  | Yes
Europe (Paris) (eu-west-3) |  | Yes
Europe (Stockholm) (eu-north-1) |  | Yes
South America (São Paulo) (sa-east-1) |  | Yes
US East (Ohio) (us-east-2) |  | Yes
US East (N. Virginia) (us-east-1) | Yes | Yes
US West (N. California) (us-west-1) |  | Yes
US West (Oregon) (us-west-2) | Yes | Yes
GovCloud (US-East) (us-gov-east-1) | Yes | Yes
GovCloud (US-West) (us-gov-west-1) | Yes | Yes

⠀

## Suggestions

- You can still host a Chime SDK meeting at the `ap-northeast-2` region by specifying the **MediaRegion** parameter in the [CreateMeeting API](https://docs.aws.amazon.com/chime/latest/APIReference/API_CreateMeeting.html#chime-CreateMeeting-request-MediaRegion). **Media regions** host the actual meetings, and **control regions** provide the API endpoint to create, update and delete meetings.
- For a control region, you can try out the `ap-southeast-1` region (Singapore).

**Comment by fromcloud** [comment]
Thank you, but I know that fact, too. What I want to say is that if someone changes the region according to the instructions and deploys the demo, they will surely encounter an error.  

`npm run deploy -- -r ap-northeast-2 -b <buket-name> -o media-capture -i ap-northeast-2 -s <stack-name> -a meeting`

This demonstration deploys api gateway and lmabda, so it is reasonable to try to change to the closest region. Therefore, it is necessary to change the source code of the demo. This demonstration changes the control region to the region which user specify when executing the command.

**Comment by simmkyu** [comment]
We deployed https://github.com/aws/amazon-chime-sdk-js/pull/2150 to ensure that the customer passes supported control regions. Thank you for creating an issue!
