### ISSUE TITLE
Muting the tab's microphone in Safari disconnects from the meeting

### ISSUE THREAD

**Issue by mmarekbb** [aws/amazon-chime-sdk-js#2169]
### What happened and what did you expect to happen?

Joining a meeting and clicking the Microphone icon in the Safari address bar to mute the tab causes Safari to stop sending audio packets and the meeting will disconnect. This is reproducible in the Chime React SDK meeting demo.

### Have you reviewed our existing documentation?

- [X] GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [X] FAQs [page](https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html)
- [X] README [page](https://github.com/aws/amazon-chime-sdk-js#amazon-chime-sdk-for-javascript)
- [X] Feature-specific [guides](https://github.com/aws/amazon-chime-sdk-js#guides)

### Reproduction steps

1. Join a Chime meeting in Safari
2. Click the Safari microphone icon and click Mute microphone
3. Notice that in a few seconds, the attendee gets disconnected from the meeting.

### Amazon Chime SDK for JavaScript version

2.30.0

### What browsers are you seeing the problem on?

Safari

### Browser version

all versions

### Browser console logs

[collaborate-ultra-log-1649861718317.log](https://github.com/aws/amazon-chime-sdk-js/files/8487682/collaborate-ultra-log-1649861718317.log)

**Comment by xuesichao** [comment]
Hi @mmarekbb , our SDK uses the audio input signal to notify the Chime server that the current attendee has joined a meeting. If you mute the tab's microphone, this audio input signal will not be able to sent to Chime server and thus after a while, so the attendee will be disconnected and server will thought this attendee is dropped.

Is there any use case in your application that you have to mute the tab?

**Comment by mmarekbb** [comment]
@xuesichao There is not a specific use case. Safari gives this option to users, so it's a little weird they get disconnected if they use it. I was talking eith @ltrung and apparently there may be a way to work around this by setting the audio device to null when the native mute gets triggered, so the Chime SDK starts sending a dummy audio stream instead.

**Comment by ltrung** [comment]
@mmarekbb Did you have a chance to try out the workaround?

**Comment by xuesichao** [comment]
Close this issue due to inactivity. Feel free to ping us if you still have issue and we can reopen this. @mmarekbb
