### ISSUE TITLE
Replica meeting: Promoted attendee cannot share content

### ISSUE THREAD

**Issue by paul365** [aws/amazon-chime-sdk-js#2175]
### What happened and what did you expect to happen?

Replica meeting promoted attendee cannot share content via startContentShareFromScreenCapture. The attendee is able to turn on the mic and camera.

### Have you reviewed our existing documentation?

- [X] GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [X] FAQs [page](https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html)
- [X] README [page](https://github.com/aws/amazon-chime-sdk-js#amazon-chime-sdk-for-javascript)
- [X] Feature-specific [guides](https://github.com/aws/amazon-chime-sdk-js#guides)

### Reproduction steps

Promote an attendee to the primary meeting
Promoted attendee starts call to startContentShareFromScreenCapture
Observe that the content share fails

### Amazon Chime SDK for JavaScript version

2.29.0

### What browsers are you seeing the problem on?

Chrome/Edge

### Browser version

Version 100.0.4896.88 (Official Build) (arm64)

### Meeting and Attendee ID Information.

MeetingId: "69dcb52f-81ce-476d-81ac-23ab29fd2713"
PrimaryMeetingId: "ea98ab1c-ba35-46bc-9233-13e772a12713"
AttendeeId: "88f20df4-010a-3eb6-5959-901c5e7fb28c"

### Browser console logs

[localhost-1650455792353.log](https://github.com/aws/amazon-chime-sdk-js/files/8521509/localhost-1650455792353.log)

**Comment by LeviSklaroff** [comment]
I attempted to reproduce this on 2.30.0 but was not able to reproduce this issue.
- You mentioned that this is on 2.29.0, but the replica meeting feature was not introduced until 2.30.0. Looking at the MeetingID it says you're on 2.30.0 but I just wanted to double check.
-  Looking at the console logs it doesn't look like `startContentShareFromScreenCapture` was ever called, but I do see `stopContentShare`.
- Can this be reproduced with the serverless demo?

**Comment by paul365** [comment]
Hi @LeviSklaroff,
Thank you for checking! Closing this now as also was not able to replicate it in the serverless demo. Our issue seems to be due to using the original attendeeId instead of the one from the primary meeting.
