### ISSUE TITLE
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'credentials')

### ISSUE THREAD

**Issue by vsimeikoKG** [aws/amazon-chime-sdk-js#2178]
### What happened and what did you expect to happen?

Chime SDK throws an error when user tries to go from meeting A to meeting B. Everything works fine, but the console error is annoying.

### Have you reviewed our existing documentation?

- [X] GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [X] FAQs [page](https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html)
- [X] README [page](https://github.com/aws/amazon-chime-sdk-js#amazon-chime-sdk-for-javascript)
- [X] Feature-specific [guides](https://github.com/aws/amazon-chime-sdk-js#guides)

### Reproduction steps

**Steps to reproduce**
1) Join meeting A;
2) Do anything or just wait a second for the meeting to initialize;
3) Join meeting B;
4) Get console error.

**Code snippet with meeting session destruction:**
```js
state.meetingSession.audioVideo.removeObserver(state.observer);
state.meetingSession.audioVideo.removeContentShareObserver(state.contentShareObserver);
state.meetingSession.audioVideo.realtimeUnsubscribeToAttendeeIdPresence(
  state.presenceHandler
);

if (state.audioElement) {
  await state.meetingSession.audioVideo.unbindAudioElement();
  state.audioElement.remove();
}

if (state.isScreenSharing) {
  await state.meetingSession.audioVideo.stopContentShare();
}

state.meetingSession.audioVideo.stopLocalVideoTile();
state.meetingSession.audioVideo.realtimeMuteLocalAudio();

if (state.isConnected) {
  await state.meetingSession.audioVideo.stop();
}

await state.meetingSession.deviceController.destroy();
await state.meetingSession.destroy();

console.log('MEETING DESTROYED');

// ... Create new meetingSesson object and get an error.
```

### Amazon Chime SDK for JavaScript version

3.0.0

### What browsers are you seeing the problem on?

Chrome

### Browser version

100.0.4896.127 (Official Build) (x86_64)

### Meeting and Attendee ID Information.

Meeting id 1 - 79803fcd-6d14-4d23-85b7-e754ac5b0706
Attendee id 1 - 5156f40b-b7d3-b1b9-fc6f-4577b50c23a3

Meeting id 2 - d405be27-a208-4cca-8640-5944e19a0706
Attendee id 2 - 9100f267-3d48-86ad-b2ac-0bab205af62b

### Browser console logs

<img width="1204" alt="image" src="https://user-images.githubusercontent.com/72414337/164306666-3518c00a-816e-4061-8f35-2fc0b4712b3b.png">

[logs.txt](https://github.com/aws/amazon-chime-sdk-js/files/8524709/logs.txt)

**Comment by devalevenkatesh** [comment]
Thanks for reporting this issue. Could you once try using the `audioVideoDidStop` observer and then destroy the `meetingSession` in there?

In our JS SDK meeting demo, it cleans up the resources once an attendee leaves or an meeting ends.
[Reference](https://github.com/aws/amazon-chime-sdk-js/blob/main/demos/browser/app/meetingV2/meetingV2.ts#L3474-L3584).

Doing so should not run into this error I think. Let me know if you are still running into the issue after that.

**Comment by vsimeikoKG** [comment]
@devalevenkatesh ,

I tried destroying the `meetingSession` object inside `audioVideoDidStop` observer and it fixed my problem. Thanks!

Might be a good idea to add some documentation about destroying the `meetingSession` object. Currently, there is no information about this unless you dig deep into source/example code.

Here is the working solution for anyone who may need it:
```js
const destroyPromise = new Promise((resolve) => {
  const destroyObserver = {
    async audioVideoDidStop() {
      state.meetingSession.audioVideo.removeObserver(destroyObserver);

      await state.meetingSession.deviceController.destroy();
      await state.meetingSession.destroy();

      resolve();
    },
  };

  state.meetingSession.audioVideo.addObserver(destroyObserver);
});

await state.meetingSession.audioVideo.stop();

await destroyPromise;
```

Closing the ticket.

**Comment by devalevenkatesh** [comment]
Glad it works! Thanks for the feedback, I will track and update it.
