### ISSUE TITLE
Resource ownership mismatch While Creating Media capture pipeline

### ISSUE THREAD

**Issue by AnkurSavaliya** [aws/amazon-chime-sdk-js#2182]
Hi, 
I am facing an issue while creating a media capture pipeline.
Exception like : 
`com.amazonaws.services.chime.model.ForbiddenException: Resource ownership mismatch (Service: AmazonChime; Status Code: 403; Error Code: ForbiddenException; Request ID: a00b412f-c553-4e0c-8a27-492a59fa554c; Proxy: null)`
Please someone tell me what I am missing while configuring and what is the meaning of that?

**Comment by sinanliuAmazon** [comment]
Hi, media capture pipeline should be created with the same AWS account as the Chime meeting. The error message indicate that a customer is trying to CreateMediaCapturePipeline for a meeting owned by a different AWS account.
