### ISSUE TITLE
Chime Media capture pipeline store blank screen video in S3 

### ISSUE THREAD

**Issue by AnkurSavaliya** [aws/amazon-chime-sdk-js#2185]
Hi
I am using java SDK to create meetings and create pipelines. when I create a media capture pipeline then it captures and stores only black screen video in the audio folder in the s3 bucket, even though I am sharing the screen but it does not capture.

I am using the java chime SDK version 1.12.128

` CreateMediaCapturePipelineRequest createMediaCapturePipelineRequest = new CreateMediaCapturePipelineRequest();
                createMediaCapturePipelineRequest.withSourceType(MediaPipelineSourceType.ChimeSdkMeeting);
                createMediaCapturePipelineRequest.setSourceArn(sourceArn.concat(Constants.STRING_COLON).concat(meetingId));
                createMediaCapturePipelineRequest.withSinkType(MediaPipelineSinkType.S3Bucket);
                createMediaCapturePipelineRequest.setSinkArn(sinkArn.concat(Constants.STRING_SLASH).concat(fileLocation));`

Please let me know what I am missing and why it happened.

**Comment by michhyun1** [comment]
@AnkurSavaliya - we dont currently support a version `1.12.128` for the Amazon Chime JS SDK. Can you please check our [npm module](https://www.npmjs.com/package/amazon-chime-sdk-js) and update the version to the latest version and try again? thanks.

**Comment by MingcongQi** [comment]
After updating the SDK version, if the issue still exists, could you help share the conference id and media pipeline id?

**Comment by tenge-amzn** [comment]
The black screen video in audio folder is the active speaker - it only shows up the speaker's video. Hence, if you want anything other than black screen, you need:
1. attendee enable video, and
2. someone speaks.

You can refer to the API reference for more media capture customization. Closing this. Please reopen if having more questions.
