### ISSUE TITLE
Replay the capture pipelines content by front end

### ISSUE THREAD

**Issue by austinpan** [aws/amazon-chime-sdk-js#2194]
# Community Note
* Please vote for this issue by adding a 👍 reaction to the issue. This will help the community and maintainers from the Amazon Chime SDK team to prioritize this request.
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request.
* Please go through the existing [issues](https://github.com/aws/amazon-chime-sdk-js/issues) to see if your request has already been recommended.
* Please do not use this template for bugs or support. Each individual repository has a PR template, documentation and resources for [troubleshooting](https://github.com/aws/amazon-chime-sdk-js#troubleshooting-and-support).
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.

# Tell us about your request
We've tried to concat the captured content of the presenter, attendee, and share screen of the capture pipelines.
But found the result is not good as we thought. We want to show all content (include messages) in the meeting.
Is there any way to replay the captured content by front end, then we can record all of them again when we need.

## How are you currently solving a problem?
We use the next example to record a second full page meeting now. But the service is not stable and EC2 pricing is very high.
https://github.com/aws-samples/amazon-chime-sdk-recording-demo

Thanks.

**Comment by MingcongQi** [comment]
Hi, @austinpan
It seems that you open two same issues, we would track in https://github.com/aws-samples/amazon-chime-media-capture-pipeline-demo/issues/29.
