### ISSUE TITLE
v2.* support

### ISSUE THREAD

**Issue by dkravchuk-bg** [aws/amazon-chime-sdk-js#2201]
I am trying to migrate SDK from v2.24 to v3.*

How long will you support  Amazon Chime SDK for JavaScript v2.* ?

**Comment by devalevenkatesh** [comment]
Thank you for your interest in the Amazon Chime SDK! We will continue to support version 2.X with hotfixes for a period of time after the release of version 3.0. This will give our customers time to migrate to our latest version. We will provide notice before ending support for 2.X. All feature launches after the 3.0 release will be in the 3.X version only, and we will not release new features in 2.X. We are making all changes for the 3.0 version in public so you have full visibility of the upcoming changes. Please check the migration guide at : https://github.com/aws/amazon-chime-sdk-js/blob/main/guides/17_Migration_to_3_0.md.

So, we will only do critical hotfixes in 2.x, please feel free to migrate to v3 and let us know if you run into any issue. Closing this issue now. Please open if you still have questions.
