### ISSUE TITLE
Frame size changes when camera is stopped & restarted with video processor applied.

### ISSUE THREAD

**Issue by hajime-goshima** [aws/amazon-chime-sdk-js#2210]
### What happened and what did you expect to happen?

Frame size changes when camera is stopped & restarted with video processor applied.
I was hoping that it would continue to transmit at the frame size set on the device selection screen.
Reproduced in Chime SDK Browser Demo v3.1.0.

### Have you reviewed our existing documentation?

- [X] GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [X] FAQs [page](https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html)
- [X] README [page](https://github.com/aws/amazon-chime-sdk-js#amazon-chime-sdk-for-javascript)
- [X] Feature-specific [guides](https://github.com/aws/amazon-chime-sdk-js#guides)

### Reproduction steps

- Select 720p on the device selection screen and join the meeting.
- Turn on WebRTC Stats Display and confirm that it is transmitting in 720p.

1. Confirm that the camera is transmitting in 720p when it is stopped and started.
2. Verify that the camera is transmitting at 720p when background blur is applied.
3. After that, when the camera is stopped and started, it changes to 480p.

### Amazon Chime SDK for JavaScript version

3.1.0

### What browsers are you seeing the problem on?

Chrome on Ubuntu, Chrome on Windows

### Browser version

101.0.4951.41（Official Build） （64 ビット）

### Meeting and Attendee ID Information.

Meeting ID: 32f1ebaa-71ef-4436-a66a-cafa04662713
Attendee ID: 28b90267-43c9-e682-4946-a9c1203cec6f

### Browser console logs

[console.log](https://github.com/aws/amazon-chime-sdk-js/files/8648271/console.log)

**Comment by ltrung** [comment]
@hajime-goshima Thanks for reporting. I have been able to reproduce and confirmed this was a bug in v3. We will working on a fix.

**Comment by ltrung** [comment]
@hajime-goshima The fix in #2216 has been merged to `main`. Can you try that out and let us know if it resolves the issue on your end?

**Comment by hajime-goshima** [comment]
@ltrung 
I confirmed that it is working perfectly in Chime SDK Browser Demo App.
Thank you for the quick fix.

**Comment by xuesichao** [comment]
Close the issue as the fix has been released.
