### ISSUE TITLE
Web audio causes audio lag and delay after some time 

### ISSUE THREAD

**Issue by andreisergiu98** [aws/amazon-chime-sdk-js#2215]
### What happened and what did you expect to happen?

Enabling web audio makes audio output lag behind video after 30 minutes in the meeting. This can be consistently reproduced even in your meeting demo.

### Have you reviewed our existing documentation?

- [X] GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [X] FAQs [page](https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html)
- [X] README [page](https://github.com/aws/amazon-chime-sdk-js#amazon-chime-sdk-for-javascript)
- [X] Feature-specific [guides](https://github.com/aws/amazon-chime-sdk-js#guides)

### Reproduction steps

Start aws chime meeting demo.

Join with an attendee, tick "enable web audio".
Disable microphone and camera.

Open  a new incognito window and join with another attendee, tick "enable web audio".
Disable microphone, but turn the camera on.

Wait 30-45 minutes.

On the incognito window, unmute the microphone and start talking.
On the main window notice how the audio is lagging behind the video.  

### Amazon Chime SDK for JavaScript version

2.30.0

### What browsers are you seeing the problem on?

Chromium, Safari

### Browser version

Chrome 101

### Browser console logs

[audio-log-main-app.log](https://github.com/aws/amazon-chime-sdk-js/files/8658866/audio-log-main-app.log)
[audio-log-incognito.log](https://github.com/aws/amazon-chime-sdk-js/files/8658867/audio-log-incognito.log)

**Comment by jing-chen1** [comment]
Hi @andreisergiu98, 

I can not reproduce the same audio lag issue from my side. I tested on our meeting demo with JS SDK version 3.3.0. Here are the testing steps (almost same with yours):

1. First attendee joins the meeting, enable "Use WebAudio" button and join the meeting.
2. First attendee mutes himself. The video turns off by default.
3. Second attendee joins the same meeting from an incognito window, enable "Use WebAudio".
4. Second attendee mutes himself and turn on the video.
5. Wait 30 minutes. Second attendee unmutes the microphone and starts talking
6. Audio is not lagging behind the video from the first attendee's window.

First attendee: MacOS Monterey, Chrome 101.0.4951.54, normal window, mute the microphone all the time, other settings are by default.
Second attendee: MacOS BigSur, Chrome 101.0.4951.54, incognito window, disable speaker and open the video all the time. At the beginning, mute the microphone and unmute it after 30 minutes.

I tested twice, one with voice focus and one without voice focus. Could you try our latest version of JS SDK to see if there is still an audio lagging issue? Have you ever move the meeting into background? We have some known issue about the web audio issue in MacOS safari: [In macOS Safari, audio stops playing when I minimize or move the window to the background. Is this a known issue?](https://github.com/aws/amazon-chime-sdk-js/blob/main/guides/07_FAQs.md#in-macos-safari-audio-stops-playing-when-i-minimize-or-move-the-window-to-the-background-is-this-a-known-issue)

**Comment by andreisergiu98** [comment]
We didn't test on MacOS, only on Linux and Windows. The browser window did lose focus, but was not minimized. 
I don't think we can reproduce the issue with the latest sdk, but now we also handle the streams ourselves and we omit sampeSize and sampleRate from audio constraints.

I'll close the issue for now and will reopen if we encounter it again.

Thank you!
