### ISSUE TITLE
Sort channel memberships / channel list based on last message timestamp

### ISSUE THREAD

**Issue by sikka-tanu** [aws/amazon-chime-sdk-js#2233]
Hi
I am trying to build a messaging center ( kind of https://github.com/aws-samples/amazon-chime-sdk/tree/main/apps/chat), but I need to sort the channel list based on the message sent timestamp. The channels with recent messages need to be on top.

I noticed there's no way in the listChannelMemberships / listChannelMembershipsForAppInstanceUser / listChannels to pass a parameter for sorting. Also please confirm how is the channel list sorted.

Alternate solution I thought was to fetch all channel pages and sort on my end, but then it won't be a straight way to implement pagination for me.

Please suggest if this can be achieved in a better way.

Thanks.

**Comment by gmiti-amazon** [comment]
Currently, there is no sorting supported for the list APIs. We are always expanding functionality and will update this issue if this capability is added in the future.

**Comment by gmiti-amazon** [comment]
We recently launched a feature that could potentially help: https://aws.amazon.com/about-aws/whats-new/2022/06/amazon-chime-sdk-messaging-conversation-apis/

When you establish a websocket connection, you can specify prefetch-on=connect in your query parameters to deliver CHANNEL_DETAILS events.

You will receive then the top 50 channels that contain unread messages and the latest LastMessageTimestamp values. More details on the feature are also here: https://docs.aws.amazon.com/chime-sdk/latest/dg/websockets.html#connect-api in the Using prefetch sub section.

**Comment by sikka-tanu** [comment]
Hi @gmiti-amazon - A gentle reminder for help with pagination.

I tried the prefetch option and it works well for the initial load, but not sure how to get subsequent channels for next pages (with pagination).

Currently I am fetching all the channels by sending multiple calls to listChannelMembershipsForAppInstanceUser() using nextToken, but some users have a lot of channels (say more than 1000) and it fires many calls to 'https://messaging-chime.us-east-1.amazonaws.com/channels?scope=app-instance-user-memberships&max-results=30' which ultimaltely results in throttling error from chime.

Please advise on the best way to fetch paginated channels sorted by LastMessageTimestamp

Thanks.

**Comment by jingwy** [comment]
Hi, currently we do not support pagination with prefetch feature. To better use prefetch feature, we recommend the UI to load the top 50 unread channels with latest LastMessageTimestamp first, then have a button for user to view all his/her channels in a separate list. The top 50 channels can be achieved by prefetch feature, and the button to view all channels can be achieved by listChannelMembershipsForAppInstanceUser API call.

If prefetch feature does not work for you with your current UI, listChannelMembershipsForAppInstanceUser API is the only option. However, there is no sorting supported for the listChannelMembershipsForAppInstanceUser API itself, and you will need to load all channels and sort them by LastMessageTimestamp.

Also feel freel to reach out to us through AWS Support for your account so we can discuss your specific needs in more details. https://docs.aws.amazon.com/awssupport/latest/user/case-management.html

**Comment by devalevenkatesh** [comment]
Resolving as no further asks pending, please feel free to re-open as need.
