### ISSUE TITLE
Event Reporting - InMemoryJSONEventBuffer 

### ISSUE THREAD

**Issue by heyolajyd** [aws/amazon-chime-sdk-js#2234]
### What happened and what did you expect to happen?

This issue is to have more understanding of the error: `ChimeMeetingLogger - Event Reporting - InMemoryJSONEventBuffer - sendEventImmediately - Failed to send an important event ...` and how to handle this error properly. 
We have a lot of these logs on data dog and we'd like to know if we should ignore these.

We implemented the MeetingReadinessChecker and have a modal that runs some checks on the machine see image below. We also provided the option for the user to be able to skip the checker and proceed to join the meeting. If the customer, does not wait for the checks to complete, we get the error from Chime but if the checks are complete for the customer no error is logged (_which is expected_). 
<img width="1157" alt="image" src="https://user-images.githubusercontent.com/8596553/168579218-21fb4ae0-b990-45da-aebf-de23d06bbbd4.png">

Is there a way to handle this error?

I've looked at this [document](https://aws.github.io/amazon-chime-sdk-js/classes/inmemoryjsoneventbuffer.html) but I am not sure what to make of it.

### Have you reviewed our existing documentation?

- [X] GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [X] FAQs [page](https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html)
- [X] README [page](https://github.com/aws/amazon-chime-sdk-js#amazon-chime-sdk-for-javascript)
- [X] Feature-specific [guides](https://github.com/aws/amazon-chime-sdk-js#guides)

### Reproduction steps

Using the readiness checker, skip before the checks completes
<img width="1650" alt="image" src="https://user-images.githubusercontent.com/8596553/168580771-72c44d21-7da2-4b48-bd0d-2bbb193d7db4.png">

### Amazon Chime SDK for JavaScript version

2.26.1

### What browsers are you seeing the problem on?

Chrome, Edge

### Browser version

100

### Browser console logs

<img width="643" alt="image" src="https://user-images.githubusercontent.com/8596553/168580588-d4f35942-c71f-4f33-9c66-e16fdabf398d.png">

**Comment by ltrung** [comment]
If users skip the check, do you call aws-sdk API to delete meeting?

**Comment by devalevenkatesh** [comment]
Adding to Trung, these are the meeting events from Amazon Chime SDK for JavaScript sent to Amazon Chime backend. Please check below guide on this client side event ingestion:
https://aws.github.io/amazon-chime-sdk-js/modules/clientevent_ingestion.html

But would like to know how do you use the `meetingId` and if you delete the meeting?

**Comment by heyolajyd** [comment]
Thank you @ltrung and @devalevenkatesh we spin up a sandbox meeting when we create a meeting. The sandbox meeting is available with the same meeting Id for all customers (_that want to join the meeting_) to verify the state of their machine or skip. Once checks are completed we delete the meeting attendee and finally delete the meeting when we end the main meeting. As you suggested, we were deleting the sandbox meeting attendee even when the customer decides to skip the checks hence the error.  We modified how and when we delete the sandbox meeting attendee. I'll close this
