### ISSUE TITLE
realtimeUnsubscribeFromVolumeIndicator causes a fatal error when attendeeId match not found

### ISSUE THREAD

**Issue by schontz** [aws/amazon-chime-sdk-js#2235]
### What happened and what did you expect to happen?

Calling `realtimeUnsubscribeFromVolumeIndicator` with an `attendeeId` for which there are no subscriptions causes a fatal error that is not catch-able by the application. For example:

```javascript
try {
  // even if 'some-attendee' is a valid ID but if we did not first call realtimeSubscribeToVolumeIndicator,
  // it will fail and leave the meeting
  rt.realtimeUnsubscribeFromVolumeIndicator('some-attendee', () => {})
} catch (error) {
  // never fails, but internally creates an error which is considered fatal
}
```

I would expect that this kind of invalid call would not fail, or only fail in a way that the local code would catch. I would not expect it to cause a fatal error.

### Have you reviewed our existing documentation?

- [X] GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [X] FAQs [page](https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html)
- [X] README [page](https://github.com/aws/amazon-chime-sdk-js#amazon-chime-sdk-for-javascript)
- [X] Feature-specific [guides](https://github.com/aws/amazon-chime-sdk-js#guides)

### Reproduction steps

See above

### Amazon Chime SDK for JavaScript version

3.1.0

### What browsers are you seeing the problem on?

Chrome

### Browser version

101

### Browser console logs

```
[ERROR] [pfid: ***] MeetingsSDK::realtime error: TypeError: Cannot read properties of undefined (reading 'indexOf'): TypeError: Cannot read properties of undefined (reading 'indexOf')
    at t.default.realtimeUnsubscribeFromVolumeIndicator
    at t.default.realtimeUnsubscribeFromVolumeIndicator
    at tl.realtimeUnsubscribeFromVolumeIndicator
```

**Comment by hensmi-amazon** [comment]
PR merged.
