### ISSUE TITLE
Add React quick start demo

### ISSUE THREAD

**Issue by aburnson** [aws/amazon-chime-sdk-js#224]
From #198

**Comment by mding5692** [comment]
Is there currently a react demo app or some react examples using the API on the roadmap for near future?

**Comment by vidya-mohan** [comment]
@mding5692  this is sample you can use: https://github.com/aws-samples/amazon-chime-sdk-classroom-demo

**Comment by aburnson** [comment]
Going forward demos will be added in a separate demo-specific repository and handled by the front-end team, so closing this issue in this repo.
