### ISSUE TITLE
chooseAudioOutput doesn't work unless mute is toggled

### ISSUE THREAD

**Issue by vsimeikoKG** [aws/amazon-chime-sdk-js#2242]
### What happened and what did you expect to happen?

Chime SDK doesn't respect selected audio output device unless mute/unmute is toggled.

It worked correctly in the latest Chime v2.x.x version, but after update it seems to be broken.

### Have you reviewed our existing documentation?

- [X] GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [X] FAQs [page](https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html)
- [X] README [page](https://github.com/aws/amazon-chime-sdk-js#amazon-chime-sdk-for-javascript)
- [X] Feature-specific [guides](https://github.com/aws/amazon-chime-sdk-js#guides)

### Reproduction steps

**Steps to Reproduce:**
1) Make sure you have at least 2 audio output devices available.
2) Select non-default audio output device.
3) Join meeting with any number of users.
4) When any other users speaks the audio is coming from the default audio output device.
5) User unmutes and then mutes himself.
6) Audio is coming from the selected audio output now.

**Reference code:**
```js
if (!state.audioElement) {
  document.body.append(audioElement);
}

await meetingSession.audioVideo.listAudioOutputDevices();
await meetingSession.audioVideo.bindAudioElement(audioElement);

if (canSelectAudioOutput()) {
  await meetingSession.audioVideo.chooseAudioOutput(state.audioOutputDeviceID);
}

console.log('SET OUTPUT DEVICE', state.audioOutputDeviceID);
```

### Amazon Chime SDK for JavaScript version

3.2.0

### What browsers are you seeing the problem on?

Chrome

### Browser version

Version 101.0.4951.64 (Official Build) (x86_64)

### Meeting and Attendee ID Information.

Meeting ID - 09bba375-8db6-430f-b542-f01755ca0706
Attendee 1 ID - 01b746da-085c-2cf9-340a-821599d5c795
Attendee 2 ID - 300061a3-5a79-34ff-8c7b-1222492f3b88

### Browser console logs

Logs for the attendee 2.

[logs.txt](https://github.com/aws/amazon-chime-sdk-js/files/8719032/logs.txt)

**Comment by ltrung** [comment]
@vsimeikoKG Thanks for reporting. I think I know what happens. Do you call `chooseAudioOutput` before the meeting start? The current code flow in v3 only receive device change events (including audio input) after `audioVideo.start` so I think it is missing an update there. Although it seems something in your application triggers `chooseAudioOutput` again when you mute/unmute.
We will look into this but for a current workaround can you call `chooseAudioInput` after meeting start?

**Comment by vsimeikoKG** [comment]
@ltrung ,

Yes, seems like the issue is fixed. 

Thank you!

**Comment by ltrung** [comment]
NPM 3.3.0 is released so closing the issue.
