### ISSUE TITLE
Question: no video device chosen, stopping local video tile

### ISSUE THREAD

**Issue by heyolajyd** [aws/amazon-chime-sdk-js#2243]
### What happened and what did you expect to happen?

Having read through the documentation and some closed issues, and implemented some of the suggestions. Typical flow is, a user (director) starts a meeting session, and we initialize a chime session. We show an audio-video settings modal, allow the user (director) to select a video input, preview, and finally join the meeting session. Some of our users have no issues displaying the local video tile, others just get a blank screen with the error: `no video device chosen, stopping local video tile`

### Have you reviewed our existing documentation?

- [X] GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [X] FAQs [page](https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html)
- [X] README [page](https://github.com/aws/amazon-chime-sdk-js#amazon-chime-sdk-for-javascript)
- [X] Feature-specific [guides](https://github.com/aws/amazon-chime-sdk-js#guides)

### Reproduction steps

We have a preview component that previews the user's video input and we're doing something like this in the code snippet

```js
CameraPreview = ({ videoInputDevice, meetingSession}) => {
   ...
   useEffect(() => {
     /** if video element is not defined */
     if (!videoElement) return;
     
     // see: https://aws.github.io/amazon-chime-sdk-js/modules/apioverview.html#2h-preview-local-camera-in-a-video-element-optional
     async function start() {
        await meetingSession.audioVideo.chooseVideoInputDevice(videoInputDevice);
        // Based on trial and error it was discovered that one must first choose a video device ID before starting preview (otherwise an error is yielded)
        meetingSession.audioVideo.startVideoPreviewForVideoInput(videoElement);
     }
     
     start()
     
     return () => {
       meetingSession.audioVideo.stopVideoPreviewForVideoInput(videoElement);
     }
   }, [videoElement, meetingSession, videoInputDevice]);
   
   ...
}
```

Somewhere in our app, where we initialize Chime, we have this in our observer as 

```js

const observer = {
  ...
  audioVideoDidStart: () => {
      // start up video tile
      /*
        We've been getting this error ChimeMeetingLogger - no video device chosen, stopping local video tile
        see: https://github.com/aws/amazon-chime-sdk-js/issues/1818#issuecomment-975774752
        Recommended to add the audioVideoDidStart observer and then call `startLocalVideoTile` function.
        this ensures the meeting session is successfully established before calling the startlocalVideoTile function
      */
      meetingSession.audioVideo.startLocalVideoTile();
    },
    videoTileDidUpdate: (tileState) => { ... },
    videoTileWasRemoved: () => { ... },
    eventDidReceive: () => { ... },
    videoSendBandwidthDidChange: () => { ... },
    videoReceiveBandwidthDidChange: () => { ...},
    ...
};

//Add the tile observer
meetingSession.audioVideo.addObserver(observer);

//Start capturing video / audio
meetingSession.audioVideo.start();
```

We have noticed that some of our users still get this error:
`ERROR] ChimeMeetingLogger - no video device chosen, stopping local video tile`, the video tile doesn't show the video feed from the computer/mac

We're trying to make users starting/joining a meeting a seamless experience and we want to understand this error. What could be wrong with our setup?

### Amazon Chime SDK for JavaScript version

2.30.0

### What browsers are you seeing the problem on?

Chrome, Edge

### Browser version

100

### Browser console logs

[ERROR] ChimeMeetingLogger - no video device chosen, stopping local video tile

<img width="447" alt="image (3)" src="https://user-images.githubusercontent.com/8596553/169128974-4ef56e6b-3c9d-47c8-838f-317d4e5d7fe7.png">

**Comment by ltrung** [comment]
@heyolajyd Just to confirm, is this v2 version of JS SDK? 
Could you upload the entire client log? From the error alone, it means that there is a race condition somewhere that clean up the video stream when the call is starting and think there is a video stream going on.

My guess is that `meetingSession.audioVideo.stopVideoPreviewForVideoInput(videoElement);` releases the media stream during `startLocalVideoTile`.

One suggestion if you use v2 is to migrate to v3 version where we handle release stream better.

**Comment by heyolajyd** [comment]
@ltrung Thank you for getting back to me. Looking at the readme, it seems we're still on v1. This is what we installed `"amazon-chime-sdk-js": "2.30.0"`.

**Comment by ltrung** [comment]
>Thank you for getting back to me. Looking at the readme, it seems we're still on v1

Sorry not sure what you mean here.
Can you try `amazon-chime-sdk-js: 3.2.0` instead? 
Otherwise, I think you can double check and see whether the `stopVideoPreviewForVideoInput` is called during the start method.

**Comment by heyolajyd** [comment]
Ok I will check and revert.

**Comment by heyolajyd** [comment]
Hey @xuesichao Thanks for getting back to me. I tested this locally and no issues for now, unfortunately, we have a code freeze at the moment because one of our customers is having a big event. I can close this until our testing is complete and give feedback or reopen if the issue persists.
