### ISSUE TITLE
Forbidden: AWS authorization failed

### ISSUE THREAD

**Issue by barjabeen12** [aws/amazon-chime-sdk-js#2245]
### What are you trying to do?
i am trying to create a meeting with chime sdk

### How can the documentation be improved to help your use case?
Documentation can be more specific on authorization errors, My keys are correct, Yet i am facing this error. Can't find anything in documentation.

### What documentation have you looked at so far?
README.md, Amazon Chime SDK Developer Guide, etc.

I am getting `Forbidden: AWS authorization failed`
My keys are correct and it was working fine until last week.
any idea what can be the issue?
```
at Request.<anonymous> (C:\Users\Dell\Desktop\Geekinate\Project\finco-client\node_modules\aws-sdk\lib\request.js:688:12) {
  code: 'Forbidden',
  time: 2022-05-19T10:36:18.739Z,
  requestId: '4bf1c831-6de8-4e09-bd44-dd2a72e0928e',
  statusCode: 403,
  retryable: false,
  retryDelay: 68.77911582199548
}
```

**Comment by ashleyqu** [comment]
Hi islamabad, can you please provide:
1. The request id
2. The time when you made the request with a time zone

I searched:
requestId: 4bf1c831-6de8-4e09-bd44-dd2a72e0928e
time: 2022-05-19T 10:36:18.739Z ->  2022-05-19T10:36:18.739 UTC 
but did not find your request.

**Comment by barjabeen12** [comment]
Hey, i solved it, it seems like there was issue with the policies with my IAM user. I tried with root access keys and it worked, although i had full access to chime.
