### ISSUE TITLE
Monitoring Attendee's Upload Speed

### ISSUE THREAD

**Issue by AleKiller21** [aws/amazon-chime-sdk-js#2247]
Hi guys,

We're currently working on a [proctoring](https://honorlock.com/blog/what-is-proctored-testing/) Electron app that will allow students of different academic institutions to take different exams while being recorded inside a Chime meeting. These meetings will consist of a **single** attendee (the student) who will get recorded (webcam + screenshare) using a media capture pipeline and then the institutions' instructors will review such recordings.

To ensure that the instructors are able to properly review the exam sessions recordings, we need to make sure that the student has enough upload bandwidth to produce a good quality video recording. To implement this, we want to monitor the student's uplink speed and be able to identify whenever it falls below a threshold value. This would be the cue for the app to let the students know that they are experimenting with network issues.

I've been going through your [Quality, Bandwidth, and Connectivity](https://aws.github.io/amazon-chime-sdk-js/modules/qualitybandwidth_connectivity.html#quality-bandwidth-and-connectivity) SDK documentation and noticed that it's possible for us to subscribe to the `metricsDidReceive` event and obtain stats metrics by calling the `getObservableMetrics` function included in the `ClientMetricsReport` object. From here, we're reading the `videoUpstreamBitrate` property to ensure that the upload speed is good enough to produce a decent recording.

After running some test meetings where I throttled the app's available upload bandwidth, I noticed that the `videoUpstreamBitrate` started to fall down to some pretty low values even below `1 Mbps`. This resulted in recordings that looked pretty pixelated. After removing the app's upload limit, the `videoUpstreamBitRate` went up resulting in smoother recordings.

With this in mind, I would like to ask you if you think this would be a solid approach to go with in order to let the students know whenever they are experiencing network issues that won't allow the media capture pipeline to produce a decent quality recording.

I also noticed there are other events as well in that documentation (connectionDidSuggestStopVideo, connectionDidBecomePoor, etc..), but I don't think those would work well in our scenario where there's only one single attendee in the meeting that needs to always send both audio and video data to the Chime server.

Do you think that the `videoUpstreamBitrate` would be enough to determine whenever the student's network status has become insufficient to produce a good quality meeting recording? Or are there any other events or tools in the SDK, that I haven't gone through, that would help us get a better reading of the student's upload speed and how it will affect the quality of the resulting recording?

**Chime SDK Version**
2.30.0

Thanks in advance!

**Comment by AleKiller21** [comment]
Hi @ltrung. Thanks for replying back. I ran another test and noticed that both `availableSendBandwidth` and `videoUpstreamBitRate` properties in the `clientMetricReport` object provide somewhat similar values. Could you elaborate on why it would be better to use the former one?

Also, I went through the Simulcast docs that you mentioned and from what I understood, it seems like it creates multiple renditions of the video (with different resolutions) based on the video input device being used by the publisher. Then, the other attendees can decide which video rendition to subscribe to based on different network and hardware constraints. Do you think this would work in our scenario where there will only be **one** attendee (the student) and where our main priority is to record the attendee's webcam and screenshare?

I was also looking at the **Simulcast resolutions and behavior** table show in the [Simulcast](https://github.com/aws/amazon-chime-sdk-js/blob/main/guides/05_Simulcast.md) docs and noticed that the second stream is not used when there are two or less attendees. This seems to also be confirmed by the following paragraph extracted from the docs:

_Note that simulcast is disabled when there are only 2 or fewer attendees. This is because WebRTC has additional functionality to request lower bitrates from the remote end, and we will forward these requests if there are no competing receivers (i.e. if the receiving estimates it has 200kbps downlink bandwidth available, this will be sent and relayed in a message to the sending client). Therefore there is no need for simulcast based adaption._

**Comment by hensmi-amazon** [comment]
@AleKiller21 `availableSendBandwidth` and `videoUpstreamBitRate` will match when the available send bandwidth estimation is below the target/max bitrate for the stream (in this case in a 1 attendee call this will be 1400 kbps, though note, if more videos in the call are enabled, that this value will be reduced. The send bitrate is reduced to equal the bandwidth, as unsurprisingly the browser does not want to send above the link capacity and possibly overload the network.

Simply put in an example:
* `availableSendBandwidth == 2000` and max bitrate == 1400 -> approx. `videoUpstreamBitRate == 1400`
* `availableSendBandwidth == 1000` and max bitrate == 1400 -> approx. `videoUpstreamBitRate == 1000`

I think looking at `availableOutgoingBitrate` is fine as long as the value is compared to the expected value (1400 in this case, though as mentioned this won't be true if there are other videos enabled in conference). Using `videoUpstreamBitRate` takes on the risk the arbitrary encoder issues may be reducing the value for reasons unrelated to bandwidth (i.e. a broken browser implementation that fails to rise above 300kbps). I would recommend additionally looking for non trivial amounts of audio/video packet loss to determine network issues. Given the scenario simulcast is less relevant as you mentioned.

**Comment by AleKiller21** [comment]
Thanks @hensmi-amazon for your explanation.

You mentioned that 1400 kbps is the max bitrate for a stream of a single attendee. However, in the [Chime docs](https://aws.github.io/amazon-chime-sdk-js/modules/qualitybandwidth_connectivity.html#quality-bandwidth-and-connectivity) it mentions that 1400 kbps is the default for upstream sending bandwidth and you can _recommend_ WebRTC what the `maxBandwidthKbps` could be. According to the table shown in that documentation, the max value can be 2500 kbps.

I just want to confirm with you if this is still the case based on what you were telling me in your response.

**Comment by hensmi-amazon** [comment]
Yes that is still the case, you can use https://aws.github.io/amazon-chime-sdk-js/interfaces/audiovideocontroller.html#setvideomaxbandwidthkbps to set the bitrate desired.

**Comment by ltrung** [comment]
Close the issue for now. Feel free to reopen if you have additional questions.
