### ISSUE TITLE
Webpack production build getting failed on deployment

### ISSUE THREAD

**Issue by anmol-rodi** [aws/amazon-chime-sdk-js#2253]
### What happened and what did you expect to happen?

Outline the main actions the user performed and when:
when it loads on the web, it immediately got an error.
I m running NPM version 10.15 but we tried on version more than 14 too but still, the same problem persists.

Environment config :

Desktop OS: Mac OS
amazon-chime-sdk-js version: "^3.2.0"
Browser :chrome, 
browser version : 101.0.4951.64

Attaching the console error screenshot
<img width="1007" alt="Screenshot 2022-05-25 at 9 19 40 PM" src="https://user-images.githubusercontent.com/43090409/170305888-5c14619f-6b9d-44c2-88a9-d93aef158dc6.png">

### Have you reviewed our existing documentation?

- [X] GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [X] FAQs [page](https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html)
- [X] README [page](https://github.com/aws/amazon-chime-sdk-js#amazon-chime-sdk-for-javascript)
- [X] Feature-specific [guides](https://github.com/aws/amazon-chime-sdk-js#guides)

### Reproduction steps

Getting this error while deployment on bucket and website fails to load .

### Amazon Chime SDK for JavaScript version

3.2.0

### What browsers are you seeing the problem on?

CHROME

### Browser version

101.0.4951.64

### Browser console logs

<img width="1007" alt="Screenshot 2022-05-25 at 9 19 40 PM" src="https://user-images.githubusercontent.com/43090409/170306334-e69ff77e-82f8-4144-8934-2dd524479c09.png">

**Comment by MohdIrfan12** [comment]
@chime-sdk-js-bot

**Comment by MohdIrfan12** [comment]
@chime-sdk-js-bot ??

**Comment by devalevenkatesh** [comment]
Closing this issue due to in-activity, please feel free to open if still an issue.
