### ISSUE TITLE
Remote video not starting on Firefox 100+

### ISSUE THREAD

**Issue by andreisergiu98** [aws/amazon-chime-sdk-js#2257]
### What happened and what did you expect to happen?

Remote videos not playing on Firefox 100+. Chime is aware of them, streams are enabled and attached to the video element, video track exists and is active. "autoplay" attribute does nothing, and when attempted to start the video by calling .play() it is never resolved, nor does it throw an error.

This seems more like a browser issue, but I lack the expertise to further debug it. 

This issue affects both our app and "chime-sdk-meeting-demo". Simulcast is disabled, webaudio is enabled, and default uplink/downlink policies were used.

### Have you reviewed our existing documentation?

- [X] GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [X] FAQs [page](https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html)
- [X] README [page](https://github.com/aws/amazon-chime-sdk-js#amazon-chime-sdk-for-javascript)
- [X] Feature-specific [guides](https://github.com/aws/amazon-chime-sdk-js#guides)

### Reproduction steps

1) Join a meeting from Chrome with a couple of attendees (I recommend minimum 4, more will increase our chances) and turn on the camera for all of them.
2) Join the meeting from Firefox and notice some remote streams not starting. If all of them started repeat step 2 (It might take more than 10 refreshes, don't give up).

### Amazon Chime SDK for JavaScript version

3.2.0

### What browsers are you seeing the problem on?

Firefox

### Browser version

100, 101, 102

### Browser console logs

[aws-chime-demo-firefox.txt](https://github.com/aws/amazon-chime-sdk-js/files/8777744/aws-chime-demo-firefox.txt)

**Comment by ltrung** [comment]
@andreisergiu98 Thanks for reporting. We are looking into fixing this.

**Comment by hensmi-amazon** [comment]
There was a change in FF 99 (https://phabricator.services.mozilla.com/D140236) which basically requires yet another mitigation to avoid FF running into its unsignalled SSRC handling issues when multiple media sections are negotiated at the same time (see https://github.com/aws/amazon-chime-sdk-js/issues/2078 for more details). From investigation I was able to add additional mitigation of putting dummy SSRCs in the inactive send section from the backend which with the previous changes was able to fix the issue. This is currently deploying (found this issue last week), it will be done maybe in a week or so, I will update the ticket when it is done.

**Comment by andreisergiu98** [comment]
Hi! @hensmi-amazon any news? We are still reproducing the issue.

**Comment by hensmi-amazon** [comment]
Hi @andreisergiu98 it is mostly deployed at this point, and should wrap up tomorrow, sorry for the delay there. I just retested with manual delays to TCP and confirmed the fix again.

**Comment by hensmi-amazon** [comment]
Deployment completed. Hopefully FF waits a few months before changing this behavior again :).
