### ISSUE TITLE
SDK v2.x Documentation Support

### ISSUE THREAD

**Issue by AleKiller21** [aws/amazon-chime-sdk-js#2260]
Hi, 

I'm currently going through the [Chime SDK API doc](https://aws.github.io/amazon-chime-sdk-js/index.html) and most of its content has been updated to reflect the changes in v3. Is there an option on the website to change the SDK version being shown in the docs to a previous one? In case there's not, do you know where I could go to read the v2.x documentation of the SDK?

**Comment by ltrung** [comment]
Hi the v2.x documentation could be found here https://github.com/aws/amazon-chime-sdk-js/tree/release-2.x. We will look into enable documentation for previous version too.

**Comment by ltrung** [comment]
Yes, you can find pretty much all of the guides in https://github.com/aws/amazon-chime-sdk-js/tree/release-2.x/guides. They are just in markdown format instead of html.

**Comment by AleKiller21** [comment]
Oh, I see it now. Thank you very much!
