### ISSUE TITLE
CloudWatch metrics for API usage

### ISSUE THREAD

**Issue by dnnejo** [aws/amazon-chime-sdk-js#2261]
# Community Note
* Please vote for this issue by adding a 👍 reaction to the issue. This will help the community and maintainers from the Amazon Chime SDK team to prioritize this request.
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request.
* Please go through the existing [issues](https://github.com/aws/amazon-chime-sdk-js/issues) to see if your request has already been recommended.
* Please do not use this template for bugs or support. Each individual repository has a PR template, documentation and resources for [troubleshooting](https://github.com/aws/amazon-chime-sdk-js#troubleshooting-and-support).
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.

# Tell us about your request
## What do you want us to build?
CloudWatch metrics to report per API usage, including number of requests, throttled requests, and errors.
CloudWatch metrics to report any errors in sending WebRTC session notifications to Amazon SQS or Amazon SNS.

## Tell us about the problem you are trying to solve and why is it hard?
These metrics will enable tracking of usage against API service quotas, and provide visibility of any failures.

## How are you currently solving a problem?
Reactively increasing service quotas when throttling is encountered.

## Additional context
This benefits all customers of Amazon Chime SDK, across all SDKs

**Comment by devalevenkatesh** [comment]
Closing as moved to shipped.
