### ISSUE TITLE
CloudWatch metrics for attendee join and drop counts by media region

### ISSUE THREAD

**Issue by dnnejo** [aws/amazon-chime-sdk-js#2262]
# Community Note
* Please vote for this issue by adding a 👍 reaction to the issue. This will help the community and maintainers from the Amazon Chime SDK team to prioritize this request.
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request.
* Please go through the existing [issues](https://github.com/aws/amazon-chime-sdk-js/issues) to see if your request has already been recommended.
* Please do not use this template for bugs or support. Each individual repository has a PR template, documentation and resources for [troubleshooting](https://github.com/aws/amazon-chime-sdk-js#troubleshooting-and-support).
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.

# Tell us about your request
## What do you want us to build?
CloudWatch metrics to provide visibility of the WebRTC media session attendee join experience, by media region:
- attendee joins authorized
- attendee joins denied
- attendee audio drops
- attendee content drops

## Tell us about the problem you are trying to solve and why is it hard?
These metrics will enable tracking of the attendee join/drop experience over time and geography with no code.

## How are you currently solving a problem?
Events are provided on EventBridge, but having an aggregate metric removes event processing to create dashboards and alerts.

## Additional context
This benefits all customers of Amazon Chime SDK, across all SDKs.

**Comment by devalevenkatesh** [comment]
Closing as moved to shipped.
