### ISSUE TITLE
cannnot build the demo App of BreakoutRoom 

### ISSUE THREAD

**Issue by kodai305** [aws/amazon-chime-sdk-js#2277]
### What happened and what did you expect to happen?

I tried to build the demo application of breakout-rooms. The git repository is below.
And I wrote the issue. Please tell me how to build and deploy the app.

https://github.com/aws-samples/amazon-chime-sdk-meetings-breakout-rooms/issues/4

### Have you reviewed our existing documentation?

- [X] GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [X] FAQs [page](https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html)
- [X] README [page](https://github.com/aws/amazon-chime-sdk-js#amazon-chime-sdk-for-javascript)
- [X] Feature-specific [guides](https://github.com/aws/amazon-chime-sdk-js#guides)

### Reproduction steps

see issue page.

### Amazon Chime SDK for JavaScript version

2.30.1

### What browsers are you seeing the problem on?

none

### Browser version

none

### Browser console logs

none

**Comment by devalevenkatesh** [comment]
Thanks for reporting the issue. I am sorry but here we accept only the JS SDK related issues. I understand you may have opened it here due to no response on the demo but now I have tagged a contributor there and see how he can help.

I am closing this issue now.
