### ISSUE TITLE
DefaultMeetingReadinessChecker.checkCameraResolution not return Succeeded on Android

### ISSUE THREAD

**Issue by its-tuanna** [aws/amazon-chime-sdk-js#2278]
### What happened and what did you expect to happen?

I want to check the device before joining the meeting. In the camera test step, i'm using checkCameraResolution() of DefaultMeetingReadinessChecker to test camera'resolution. The function's first parameter receive the camera's information from DefaultMeetingSession.audioVideo.listVideoInputDevices. The rest parameters receive the camera's width, height from stream received from navigator.mediaDevices.getUserMedia. I expected that checkCameraResolution will return Succeeded. I tested on PC, iOS and Android but just PC, iOS return Succeeded

### Have you reviewed our existing documentation?

- [X] GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [X] FAQs [page](https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html)
- [X] README [page](https://github.com/aws/amazon-chime-sdk-js#amazon-chime-sdk-for-javascript)
- [X] Feature-specific [guides](https://github.com/aws/amazon-chime-sdk-js#guides)

### Reproduction steps

```
import {
  CheckCameraResolutionFeedback,
  ConsoleLogger,
  DefaultDeviceController,
  DefaultMeetingReadinessChecker,
  DefaultMeetingSession,
  MeetingSessionConfiguration,
} from 'amazon-chime-sdk-js';
```
1. Get the camera's information
```
const configuration = new MeetingSessionConfiguration(...);
const logger = new ConsoleLogger('MyLogger');
const deviceController = new DefaultDeviceController(logger);
const meetingSession = new DefaultMeetingSession(configuration, logger, deviceController);
const videoInputDeviceInfo = await meetingSession.audioVideo.listVideoInputDevices();
```

2. Get the width and height of the camera
```
let stream = await navigator.mediaDevices.getUserMedia({ video: true });
let { width, height } = stream.getTracks()[0].getSettings();
```

3. Test resolution
```
const meetingReadinessChecker = new DefaultMeetingReadinessChecker(logger, meetingSession);
const cameraInputFeedback = await meetingReadinessChecker.checkCameraResolution(
      videoInputDeviceInfo[0].deviceId,
      width || 0,
      height || 0,
    );
```

### Amazon Chime SDK for JavaScript version

2.30.0

### What browsers are you seeing the problem on?

Chrome

### Browser version

n/a

### Browser console logs

n/a

**Comment by xuesichao** [comment]
Hi @its-tuanna thanks for reporting this issue. Have you tried our [`meetingReadinessChecker`](https://github.com/aws/amazon-chime-sdk-js/tree/main/demos/browser). If not could you please try to run this demo on your Android device and see if you can reproduce it successfully?

Steps:
```
cd demos/browser
npm install
npm run start --app=meetingReadinessChecker
```

**Comment by xuesichao** [comment]
@its-tuanna Hey, I tested on a Pixel 6 pro device with our [`meetingReadinessChecker`](https://github.com/aws/amazon-chime-sdk-js/tree/main/demos/browser). And camera test was passed successfully.

The code in our demo is:
https://github.com/aws/amazon-chime-sdk-js/blob/2657a7c1dba1b599f5520bd509e68d0585625ec8/demos/browser/app/meetingReadinessChecker/meetingReadinessChecker.ts#L255-L269

Could you please let us know which android device you are using? 
And what is the result of `checkCameraResolution()` when testing on Android device?
What is the actual `constraint` when `checkCameraResolution()` calls `getUserMedia()` API? You can find the code here:
https://github.com/aws/amazon-chime-sdk-js/blob/2657a7c1dba1b599f5520bd509e68d0585625ec8/src/meetingreadinesschecker/DefaultMeetingReadinessChecker.ts#L174-L177

**Comment by its-tuanna** [comment]
Well, instead of getting the width, the height of the camera, and then testing, I tested with all 3 cases you suggest and it works. I will close the issue
