### ISSUE TITLE
Explain AudioVideoFacade.start lifecycle

### ISSUE THREAD

**Issue by aburnson** [aws/amazon-chime-sdk-js#228]
From #198

**Comment by simmkyu** [comment]
[The "Starting a session" section in the root REAMDE](https://github.com/aws/amazon-chime-sdk-js#starting-a-session) explains the session lifecycle: connecting, start, and stop.

[The "Stopping a session" section](https://github.com/aws/amazon-chime-sdk-js#stopping-a-session) explains two key stop events when an attendee leaves a meeting or when a meeting has ended.
