### ISSUE TITLE
Hi chime team, i have problem with leaves meeting

### ISSUE THREAD

**Issue by hoanp-techvify** [aws/amazon-chime-sdk-js#2288]
Hi chime team, i have problem and want you help me, when i close tap or browser, i want to call a api to save time out of attendee, i have read document at https://aws.github.io/amazon-chime-sdk-js/#stopping-a-session => Use case 27. Leave a session. i call api when sessionStatusCode === MeetingSessionStatusCode.Left and it not work , api not called, please help me with this problem. [15 minutes ago](https://github.com/aws/amazon-chime-sdk-js/issues/2288#event-6782205158)

**Comment by hoanp-techvify** [comment]
, when i close tap or browser, i want to call a api to save time out of attendee, i have read document at https://aws.github.io/amazon-chime-sdk-js/#stopping-a-session => Use case 27. Leave a session. i call api when sessionStatusCode === MeetingSessionStatusCode.Left and it not work , api not called, please help me with this problem.

**Comment by devalevenkatesh** [comment]
Hi @hoanp-techvify ,

Thanks for reporting the issue. If you want to achieve something on tab / browser close there are below options from browser itself:
1. Use [`navigator.sendBeacon`](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/sendBeacon).
2. Use browser's [`beforeunload`](https://developer.mozilla.org/en-US/docs/Web/API/Window/beforeunload_event) event.
3. Use [`pagevisibility`](https://developer.mozilla.org/en-US/docs/Web/API/Page_Visibility_API).

> `unload` event is not recommended. Check [MDN docs](https://developer.mozilla.org/en-US/docs/Web/API/Window/unload_event) for the same.

So if you make the API call as part browser close / tab close then it is not guaranteed that the browser will successfully make the API call hence in such cases `navigator.sendBeacon` can be used. You can check [InMemoryJSONEventBuffer](https://github.com/aws/amazon-chime-sdk-js/blob/main/src/eventbuffer/InMemoryJSONEventBuffer.ts) as it uses `beacon` API and `pagevisibility` to make `fetch` POST APIs. Note that it does not leave meeting but makes an API call.

**Comment by devalevenkatesh** [comment]
Closing this issue due to no-acitivity, please feel free to open this or a new issue if need be. Thank you for interest in Amazon Chime SDK for JavaScript library.
