### ISSUE TITLE
Share canvas area

### ISSUE THREAD

**Issue by AndrzejSala** [aws/amazon-chime-sdk-js#2289]
### What are you trying to do?
Hi,
I'm trying to build a new call functionality inside my app.
Basically there are 2 requirements:
- 2 users can talk to each other
- 1 user is able to create a drawing canvas, and 2 user see the progress on canvas in realtime.

Regarding 1 req it's clear for me how to implement it, 
but regarding 2 I'm not sure how to do it.
Do you have any experience in this area or have any ideas? Does Chime provide any ready to use methods / components for it?

What do you think about using [HTMLCanvasElement.captureStream()](https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/captureStream) in order to get video from canvas and send it to the second user through the Chime?

**Comment by devalevenkatesh** [comment]
Hi @AndrzejSala ,

Thanks for creating this issue. Well there are no direct APIs to achieve the canvas drawing but there are a couple that can help towards a solution:
1. You can use the `await meetingSession.audioVideo.startContentShare(mediaStream)` to pass in the media stream returned by the `captureStream` API. Check [this](https://github.com/aws/amazon-chime-sdk-js/blob/main/guides/02_Content_Share.md) guide for more information on content share in Amazon Chime SDK for JavaScript.
2. You have to create the canvas on your own though and if you want to share the same canvas and have active multi-party access you can use [Amazon Chime SDK data messages](https://github.com/aws/amazon-chime-sdk-js/blob/main/guides/03_API_Overview.md#9-send-and-receive-data-messages-optional) to send the co-ordinates of the attendees and then display on a shared single canvas. I believe this is not your use case but providing if needed. You can also use the [Amazon Chime SDK messaging](https://docs.aws.amazon.com/chime-sdk/latest/dg/using-the-messaging-sdk.html) to achieve this.
3. We have a blog post on realtime-collaboration, linking it here in case it helps:
https://aws.amazon.com/blogs/business-productivity/real-time-collaboration-using-amazon-chime-sdk-messaging/

Please let us know if you have more questions.

**Comment by devalevenkatesh** [comment]
Closing this issue due to no-activity, please let us know if you need more information.

**Comment by AndrzejSala** [comment]
Thanks for your explanation @devalevenkatesh

Our team chooses the first solution as the simplest and most intuitive one.
So we have an initial implementation in which 1 user is drawing something on the canvas, and the second one is checking the drawing preview implemented using <ContentShare/>


When testing locally (both <Canvas/> and <ContentShare/> are on the same app instance) it works fine.
However, we encountered a big problem while testing different app instances. 

It looks like Chime is missing frames captured from Canvas.

Sometimes, the shared canvas looks laggy, and if Chime loses the last frame, I need to apply the change to the original Canvas to sync it with <ContentShare/>.

@devalevenkatesh @anuranduttaroy @ltrung 
Do you know how we can fix it?
Is it fixable from the config level, or do we need to change our implementation?

**Comment by ltrung** [comment]
What do you mean appInstances? Are you using the Chime SDK messaging?
For drawing that needs constant update, I would suggest to use the data message API instead (See https://aws.github.io/amazon-chime-sdk-js/classes/defaultrealtimecontroller.html#realtimesenddatamessage).

**Comment by AndrzejSala** [comment]
By different app instances, I mean the same app running on different devices.

Chime messaging is another option, however, I would like to stay with canvas media stream as it's more convenient for me and my canvas contain a lot of changes and it seems to me that I could easily exceed the message size limit.

Is there any config option that forces better deliverability of frames through content share?
