### ISSUE TITLE
Voice focus stops working after changing audio input device followed by unmute

### ISSUE THREAD

**Issue by cgandhi22** [aws/amazon-chime-sdk-js#2312]
### What happened and what did you expect to happen?

VoiceFocus stops working if user was muted and changed mic input from input 1 to input 2 followed by unmute. Issue is reproducible and tested in 3.2, 3.3 and 3.4 version of SDK.

### Have you reviewed our existing documentation?

- [X] GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [X] FAQs [page](https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html)
- [X] README [page](https://github.com/aws/amazon-chime-sdk-js#amazon-chime-sdk-for-javascript)
- [X] Feature-specific [guides](https://github.com/aws/amazon-chime-sdk-js#guides)

### Reproduction steps

repro steps:
1)Join meeting unmuted with webAudio and voiceFocus turned on.
2)Make sure at least one external headset/device with mic attached.
3)Mute your microphone(whatever is selected by default. Let's call it mic A).
4)Switch microphone to mic B.
5)Unmute after 4 and start talking and clapping.
Actual: Voice focus UI setting shows as selected but remote user can hear clapping sound.

### Amazon Chime SDK for JavaScript version

3.2

### What browsers are you seeing the problem on?

Verified in Chrome

### Browser version

Chrome 102.0.5005.115

### Meeting and Attendee ID Information.

Meeting ID: 2b2bb8c4-0f8b-4f53-8d51-2c2dff310706
Attendee ID: 988fbd15-3d9f-efc3-fd72-664544f6ba88

### Browser console logs

https://paste.amazon.com/show/cgandhi/1655760009.text

**Comment by LeviSklaroff** [comment]
Fix has been posted, details can be found in the PR: https://github.com/aws/amazon-chime-sdk-js/pull/2313
