### ISSUE TITLE
"subscribeToAttendeeIdPresence" callback is not called when an attendee leaves the meeting in client

### ISSUE THREAD

**Issue by tamilvendhank-helptap** [aws/amazon-chime-sdk-js#2314]
### What happened and what did you expect to happen?

I have 2 users. One user created a meeting. Other user joined to it.
As I do not know which client side JavaScript API to use to exit meeting for attendee, I simply called the destroy method on `DefaultMeetingSession` instance.
When I create `DefaultMeetingSession`, I could see that `subscribeToAttendeeIdPresence` callback is called with joined user details. But, when I destroy the `DefaultMeetingSession` instance, `subscribeToAttendeeIdPresence` callback is not getting called for the other user. 
The same way, when an attendee closes the browser tab or refreshes the browser tab, the other user do not get notified about the attendee who has left the meeting.

How can I reliably know that an attendee joined & **left** meeting in client side?

### Have you reviewed our existing documentation?

- [X] GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [X] FAQs [page](https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html)
- [X] README [page](https://github.com/aws/amazon-chime-sdk-js#amazon-chime-sdk-for-javascript)
- [X] Feature-specific [guides](https://github.com/aws/amazon-chime-sdk-js#guides)

### Reproduction steps

I do not know if this is reproducible or not for others. 
For me:
1. Create meeting from one user account.
2. Join the meeting from another user account.
3. Observe that the meeting owner gets notified about the joined user via `subscribeToAttendeeIdPresence` callback.
4. Observe that the meeting attendee gets notified about the owner via `subscribeToAttendeeIdPresence` callback.
5. Exit meeting for attendee by either closing the browser tab, refreshing the browser tab or destroying the `DefaultMeetingSession`.
6. Observe that for the owner, `subscribeToAttendeeIdPresence` callback is not called with left user details.

### Amazon Chime SDK for JavaScript version

3.1.0

### What browsers are you seeing the problem on?

Google Chrome

### Browser version

102.0.5005.115 (Official Build) (x86_64)

### Browser console logs

I do not have this information.

**Comment by michhyun1** [comment]
You can either [leave](https://github.com/aws/amazon-chime-sdk-js/blob/b4a1d2b6aea264a014920418d3d6f37507322e29/demos/browser/app/meetingV2/meetingV2.ts#L1398) the meeting, or [end the meeting](https://stackoverflow.com/questions/64739053/aws-chime-sdk-how-to-leave-a-meeting).

**Comment by tamilvendhank-helptap** [comment]
@michhyun1, thanks. `End the meeting` worked.
