### ISSUE TITLE
audio video issue

### ISSUE THREAD

**Issue by MoniShankar10** [aws/amazon-chime-sdk-js#2317]
### What happened and what did you expect to happen?

when someone joins from Mozzila Firefox browser, the attendee(user) can't turn ON/OFF the camera as well as audio(mute/unmute).
While in Google Chrome, it is working absolutley fine.

### Have you reviewed our existing documentation?

- [X] GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [X] FAQs [page](https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html)
- [X] README [page](https://github.com/aws/amazon-chime-sdk-js#amazon-chime-sdk-for-javascript)
- [X] Feature-specific [guides](https://github.com/aws/amazon-chime-sdk-js#guides)

### Reproduction steps

1. open mozzila firefox
2. join the scheduled meeting.
3. web came can't turn on/off.
4. audio(mute/unmute) button can't turn on/off.

### Amazon Chime SDK for JavaScript version

"amazon-chime-sdk-js": "^2.21.0",

### What browsers are you seeing the problem on?

Firefox Browser

### Browser version

Firefox Browser 101.0.1 (64-bit)

### Meeting and Attendee ID Information.

Meeting id-----> a03508ac-0301-4a91-9e3b-11d955c80706
Chime attende id---->0de6424e-7895-f5d9-b0ef-e7c9d9056a03

### Browser console logs

TypeError: 'camera' (value of 'name' member of PermissionDescriptor) is not a valid value for enumeration PermissionName.
    getPermissionStatusForCamera common-function.ts:8
    checkMicCamPermissions call-controls.component.ts:316
    __awaiter tslib.es6.js:76
    ZoneAwarePromise Angular
    __awaiter tslib.es6.js:72
    checkMicCamPermissions main.644f737570805ffdeb23.js:506
    ngOnInit call-controls.component.ts:537
    Angular 2

**Comment by MoniShankar10** [comment]
> @MoniShankar10 Thanks for reporting this issue. At this point it seems like some issue with browser behavior when you code tries to get permissions. I believe this error is coming from your app specific code and not from within the JS SDK:
> 
> ```
> TypeError: 'camera' (value of 'name' member of PermissionDescriptor) is not a valid value for enumeration PermissionName.
> ```
> 
> Few questions:
> 
>     1. Could you please provide entire browser console logs but not only the error one here?
> 
>     2. Your error seems to be coming from the [`Permissions.query`](https://developer.mozilla.org/en-US/docs/Web/API/Permissions/query) API. We do not use this in underlying JS SDK code base. Hence, could you please check if what you are doing is supported in firefox browser as well?
> 
>     3. The audio/video ON/OFF not working may be due to the permissions not working, so suggest checking point 2 which might affect the meeting audio-video itself.

Hi, 
Thanks for replying. 
Currently we are facing below error
**Firefox can’t establish a connection to the server at wss://signal.m3.as1.app.chime.aws/control/c6c8a903-6e9d-494b-82e3-d6b1cd6a0706?X-Chime-Control-Protocol-Version=3&X-Amzn-Chime-Send-Close-On-Error=1&X-Amzn-Version=2.31.0&X-Amzn-User-Agent=firefox-101. [DefaultWebSocketAdapter.js:12](webpack:///node_modules/amazon-chime-sdk-js/build/websocketadapter/DefaultWebSocketAdapter.js)
2022-06-22T15:37:40.868Z [ERROR] MyLogger - failed to connect**

Can you help us to understand why this error is occurring.

**Comment by sudhanshu-hytech** [comment]
@devalevenkatesh @michhyun1 @ltrung Kindly help us solve this issue

**Comment by devalevenkatesh** [comment]
At this point there appears to be no issue with audio-video specifically and the issue with permissions is clarified in an earlier comment, lets that the connection issue in #2315 and as applicable and re-open other issue once connection issue is resolved all duplicate issues seems like coming from erroring connection to Amazon Chime Media backend.

I will close this and update the #2315 more.
