### ISSUE TITLE
Chat - ReadMarkerTimestamp not populating

### ISSUE THREAD

**Issue by singulli1** [aws/amazon-chime-sdk-js#2318]
### What happened and what did you expect to happen?

I'd like to display channels with messages that are not read yet for the current user.  I thought I could do this when the current user first logs in by comparing the ReadMarkerTimestamp of the member on the channel to the LastMessageTimestamp on the channelSummary.

After calling listChannelMembershipsForAppInstanceUser using the current user as the ChimeBearer, in the response I'd expect ChannelMemberships[x].AppInstanceUserMembershipSummary.ReadMarkerTimestamp to reflect the last message a member read.

After sending several messages on the channel between the current user and another user, the  ReadMarkerTimestamp continues to be null. 

When does the ReadMarkerTimestamp for a member get updated?  Any help would be greatly appreciated. :)

### Have you reviewed our existing documentation?

- [X] GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [X] FAQs [page](https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html)
- [X] README [page](https://github.com/aws/amazon-chime-sdk-js#amazon-chime-sdk-for-javascript)
- [X] Feature-specific [guides](https://github.com/aws/amazon-chime-sdk-js#guides)

### Reproduction steps

See above

### Amazon Chime SDK for JavaScript version

2.24.0

### What browsers are you seeing the problem on?

na

### Browser version

na

### Browser console logs

na

**Comment by devalevenkatesh** [comment]
Tagging @daviwith for more help on this issue. I have labelled it as messaging related.

**Comment by garyzhon** [comment]
The client application calls [UpdateChannelReadMarker](https://docs.aws.amazon.com/chime-sdk/latest/APIReference/API_messaging-chime_UpdateChannelReadMarker.html) to mark that a user has read the messages in a channel. The Amazon Chime SDK server does not automatically update ReadMarkerTimestamp since the server cannot determine whether the user has actually read the channel messages.

**Comment by singulli1** [comment]
Thanks very much - makes sense.

FYI - I'm not sure this detail is in the demo app that I used: https://github.com/aws-samples/amazon-chime-sdk/tree/main/apps/chat or in the developer guide: https://docs.aws.amazon.com/chime-sdk/latest/dg/using-the-messaging-sdk.html.

**Comment by garyzhon** [comment]
Thanks for pointing this out. We will update our docs on this specific use case.
