### ISSUE TITLE
We are not get Attendee Video left of content share meeting events in chime media capture pipeline

### ISSUE THREAD

**Issue by AnkurSavaliya** [aws/amazon-chime-sdk-js#2325]
### What happened and what did you expect to happen?

We are not getting Attendee Video left of content share meeting events in the chime media capture pipeline.

We are getting event when someone start  Content share : `{"Timestamp":"2022-06-20T08:47:09.480+00:00","EventType":"AttendeeVideoJoined","EventParameters":{"AttendeeId":"8d62011d-50ad-addd-a2a5-79d0d5f42df9#content","MediaModality":"ContentShare"}}`

but we are not getting the event of stop content share. So I can't find when the attendee shares the screen or stops it.

### Have you reviewed our existing documentation?

- [x] GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [ ] FAQs [page](https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html)
- [ ] README [page](https://github.com/aws/amazon-chime-sdk-js#amazon-chime-sdk-for-javascript)
- [ ] Feature-specific [guides](https://github.com/aws/amazon-chime-sdk-js#guides)

### Reproduction steps

N/A

### Amazon Chime SDK for JavaScript version

N/A

### What browsers are you seeing the problem on?

N/A

### Browser version

N/A

### Meeting and Attendee ID Information.

N/A

### Browser console logs

N/A

**Comment by michhyun1** [comment]
Can you please confirm the Amazon Chime SDK for Javascript version that you are using? 
I'd suggest upgrading to the latest and then following this doc for guidance:
Please refer to the docs here: https://docs.aws.amazon.com/chime-sdk/latest/dg/using-events.html

**Comment by michhyun1** [comment]
Oops, sorry I didnt see this is for media capture meeting events.

**Comment by sinanliuAmazon** [comment]
Could you please share the media pipeline id?

**Comment by AnkurSavaliya** [comment]
@sinanliuAmazon  Issue with below pipeline Id : 
`d4183aee-1730-48e4-be72-69427a731bc8`
`0d07e517-3212-4cfd-8ff4-fbc10628d5f1`

**Comment by AnkurSavaliya** [comment]
@sinanliuAmazon Hi 
Can we get an update on this, why has this is happened?

**Comment by nehtambe** [comment]
Hi, did you mean 'CaptureEnded' event ? We looked into logs for above pipeline ID - `bb6f5e2a-b15a-4707-8f5c-93ac89535bcf`, didn’t see any error. It would be great if you can share the steps to reproduce the issue. Also, are you facing this issue intermittently or constantly ?

**Comment by AnkurSavaliya** [comment]
Hi,
yes, the 'CaptureEnded' event and also another event also not in the meetings events files. This issue facing intermittently.
I am sharing the last file of chime meeting events that are present in S3 buckets. 
`{"Timestamp":"2022-07-06T21:08:22.268+00:00","EventType":"AttendeeVideoLeft","EventParameters":{"AttendeeId":"d2d8da73-3edf-5229-4ee8-ef8c24666a17","MediaModality":"Video"}}
{"Timestamp":"2022-07-06T21:08:22.866+00:00","EventType":"ActiveSpeaker","EventParameters":{"AttendeeId":"6c8808db-bf1a-03d7-4b8c-d95f05a62482","MediaModality":""}}
{"Timestamp":"2022-07-06T21:08:22.946+00:00","EventType":"ActiveSpeaker","EventParameters":{"AttendeeId":"6c8808db-bf1a-03d7-4b8c-d95f05a62482","MediaModality":""}}
{"Timestamp":"2022-07-06T21:08:23.106+00:00","EventType":"ActiveSpeaker","EventParameters":{"AttendeeId":"6c8808db-bf1a-03d7-4b8c-d95f05a62482","MediaModality":""}}
{"Timestamp":"2022-07-06T21:08:23.268+00:00","EventType":"AttendeeVideoLeft","EventParameters":{"AttendeeId":"9bf1d572-99e5-7e7b-091a-a8592e2c641f","MediaModality":"Video"}}
{"Timestamp":"2022-07-06T21:08:23.387+00:00","EventType":"AttendeeVideoJoined","EventParameters":{"AttendeeId":"9bf1d572-99e5-7e7b-091a-a8592e2c641f","MediaModality":"Video"}}
{"Timestamp":"2022-07-06T21:08:24.626+00:00","EventType":"ActiveSpeaker","EventParameters":{"AttendeeId":"13609921-0823-ad70-7771-d4b61c1a4281","MediaModality":""}}
{"Timestamp":"2022-07-06T21:08:24.786+00:00","EventType":"ActiveSpeaker","EventParameters":{"AttendeeId":"13609921-0823-ad70-7771-d4b61c1a4281","MediaModality":""}}
{"Timestamp":"2022-07-06T21:08:25.106+00:00","EventType":"ActiveSpeaker","EventParameters":{"AttendeeId":"d2d8da73-3edf-5229-4ee8-ef8c24666a17","MediaModality":""}}
{"Timestamp":"2022-07-06T21:08:25.346+00:00","EventType":"ActiveSpeaker","EventParameters":{"AttendeeId":"d2d8da73-3edf-5229-4ee8-ef8c24666a17","MediaModality":""}}
{"Timestamp":"2022-07-06T21:08:25.426+00:00","EventType":"ActiveSpeaker","EventParameters":{"AttendeeId":"13609921-0823-ad70-7771-d4b61c1a4281","MediaModality":""}}
{"Timestamp":"2022-07-06T21:08:25.451+00:00","EventType":"AttendeeVideoJoined","EventParameters":{"AttendeeId":"d2d8da73-3edf-5229-4ee8-ef8c24666a17","MediaModality":"Video"}}
{"Timestamp":"2022-07-06T21:08:26.597+00:00","EventType":"AttendeeVideoJoined","EventParameters":{"AttendeeId":"13609921-0823-ad70-7771-d4b61c1a4281","MediaModality":"Video"}}
`

**Comment by yuqil-amzn** [comment]
Hi,
Our team has deploy the fix.
