### ISSUE TITLE
Downstream bandwidth utilization

### ISSUE THREAD

**Issue by massi-ang** [aws/amazon-chime-sdk-js#2328]
### What happened and what did you expect to happen?

Joining a meeting with the Desktop client from Mac OS: 
- 1 video
- 1 screen sharing with a static picture
BW use: ~3-5Mbps

After turning the video off I get the same BW usage

Using the Web Client on Chrome
BW use: ~1.5-3Mbps (same with video on or off)

Using Workspaces running Chime
BW use: ~400-500kbps

I would expect that turning off video would not send video over thus saving on bandwidth consumption, and also that the video algorithm used could be more efficient (as it can be with Workspaces). This matter on metered mobile connections. 

### Have you reviewed our existing documentation?

- [X] GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [X] FAQs [page](https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html)
- [X] README [page](https://github.com/aws/amazon-chime-sdk-js#amazon-chime-sdk-for-javascript)
- [X] Feature-specific [guides](https://github.com/aws/amazon-chime-sdk-js#guides)

### Reproduction steps

Join a meeting with video and screen sharing from a Mac
Check the BW usage (I use the monitoring page from my router)
Pause the video 
Check the BW usage

Repeat the same by joining the meeting from Chrome and from Chime Desktop running in Workspaces

### Amazon Chime SDK for JavaScript version

Chime Version #: 5.8.1109

### What browsers are you seeing the problem on?

Chrome

### Browser version

Version 102.0.5005.115 (Official Build) (x86_64)

### Browser console logs

Not relevant

**Comment by michhyun1** [comment]
@massi-ang This is the Amazon Chime SDK for Javascript, and you seem to be asking for the native desktop Chime application. Perhaps you might consider closing this ticket and instead send some diagnostic logs through the Chime app 
'Help' menu. You may also consider opening a support ticket for more support.
