### ISSUE TITLE
H264 issues on iOS devices workaround by switching to vp8

### ISSUE THREAD

**Issue by anner-emed** [aws/amazon-chime-sdk-js#2329]
### What happened and what did you expect to happen?

Hello,

Our team was seeing large amounts of issues with iOS and H264 after forcing to VP8 we seen no more reports from customers.
As a workaround we patched the SDK to force vp8 as codec to the detriment of energy usage.

Is there any other workaround / safari bug that drives this?

> through our own testing, on differing iPhone models ( but not exactly sure which, because we hadn't fingerprinted the devices in logs ), we were seeing errors with black video on both user side and proctor side, or in some cases even the browser crashing.  Many reports from our CS team with bad video in sessions and failures. Through trial and error and logs, came to the realization that it could be something related to the h264 codec ( unsure where exactly in the pipeline, but likely in hardware encoder/webrtc side of Safari ).  

Another comment from internal team:
> I think this is the same issue that we identified with you guys back when 15.1 and 15.2 came out. H.264 appears to still be broken in iOS 15.5.

is this the same as this?

https://github.com/aws/amazon-chime-sdk-js/issues/1059

>Video Frame Processor sends black or red images in Safari 15 due to a bug in canvas.captureStream ([Safari 15 bug](https://bugs.webkit.org/show_bug.cgi?id=230613)). For a temporary workaround, you can copy the output content in VideoFrameProcessor.process method to another canvas and use that canvas to render the output video as seen in https://github.com/aws/amazon-chime-sdk-js/issues/1758.

### Have you reviewed our existing documentation?

- [X] GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [X] FAQs [page](https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html)
- [X] README [page](https://github.com/aws/amazon-chime-sdk-js#amazon-chime-sdk-for-javascript)
- [X] Feature-specific [guides](https://github.com/aws/amazon-chime-sdk-js#guides)

### Reproduction steps

Setup chime video call between peers. (will add more technical details when i get a hold of the SME) 

### Amazon Chime SDK for JavaScript version

3.3.0

### What browsers are you seeing the problem on?

Safri

### Browser version

varies

### Browser console logs

Can't provide

**Comment by jonathan-emed** [comment]
@anner-emed please close this ticket.  Here is the replacement https://github.com/aws/amazon-chime-sdk-js/issues/2331
