### ISSUE TITLE
Camera does not turn off on Safari 

### ISSUE THREAD

**Issue by mpelzsherman** [aws/amazon-chime-sdk-js#2342]
### What happened and what did you expect to happen?

On MacOS Safari Version 15.5:

After turning on the camera using `startVideoInput`, the camera LED does not turn off after calling `stopVideoInput`.

The same code works fine on Google Chrome Version 102.0.5005.115 and Microsoft Edge 103.0.1264.37. The camera LED turns off properly.

### Have you reviewed our existing documentation?

- [X] GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [X] FAQs [page](https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html)
- [X] README [page](https://github.com/aws/amazon-chime-sdk-js#amazon-chime-sdk-for-javascript)
- [X] Feature-specific [guides](https://github.com/aws/amazon-chime-sdk-js#guides)

### Reproduction steps

1. Start a video stream using `startVideoInput`
2. Stop the video stream using `stopVideoInput`
3. Note that the camera LED does not turn off

### Amazon Chime SDK for JavaScript version

3.4.0

### What browsers are you seeing the problem on?

MacOS Safari

### Browser version

15.5

### Browser console logs

No info-level logs

**Comment by samchienGG** [comment]
I also have the same problem
my sdk version is 3.0.0
but camera LED does not turn off in Safari and Chrome

**Comment by samchienGG** [comment]
i should find my problem
I call navigator.mediaDevices.getUserMedia for the reason

**Comment by mpelzsherman** [comment]
Here's a bit more info: it looks like we are calling `startVideoInput` twice for the same device in our application.

This doesn't seem to be a problem on other browsers, but on Safari, it looks like it might be causing the camera LED to remain on after calling `stopVideoInput`. We are still investigating, but are we on the right track here?

I was thinking about adding some code to check if video was already started for the device. Not quite sure how to do that though, or if that's even possible.

**Comment by ltrung** [comment]
@mpelzsherman Sorry for looking into this late. I have tried to reproduce the issue using our [meeting demo app](https://github.com/aws/amazon-chime-sdk-js/tree/main/demos/browser) but did not see any issue. What I did was join a meeting then enable video then call `startVideoInput` from developer console with the same deviceId like you said. This will output in console "Reusing existing video device". Calling  `stopVideoInput` stopped the camera stream for me. 
Although my Safari version is 15.4. I will try to find someone in the team who has 15.5 to reproduce the issue.

**Comment by mpelzsherman** [comment]
@ltrung Thanks so much for looking into it! 

When you say "Calling stopVideoInput stopped the camera stream", did your Mac's LED turn off? Were you using the built-in Mac camera?

**Comment by ltrung** [comment]
@mpelzsherman Yes I used the builtin Mac camera and verified that the green line was off after calling `stopVideoInput`.

**Comment by ltrung** [comment]
My colleague tried in Safari 15.5 and does not have any issue either. Feel free to attach a client log and I can try to see if I can spot any irregularities.

**Comment by xuesichao** [comment]
Close the issue due to inactivity. Feel free to reopen it.
