### ISSUE TITLE
Not able to get Output device on Mozila browser

### ISSUE THREAD

**Issue by hytechpro-bikeshs** [aws/amazon-chime-sdk-js#2353]
### What happened and what did you expect to happen?
@devalevenkatesh @michhyun1 @ltrung
I am trying to run chime application on mozila, but not able to get output devices,
using these method
  this.audioInputDevicesChange.next(await this.meetingSession.audioVideo.listAudioInputDevices());
      this.audioOutputDevicesChange.next(await this.meetingSession.audioVideo.listAudioOutputDevices());
      this.videoInputDevicesChange.next(await this.meetingSession.audioVideo.listVideoInputDevices());
Inputdevice and video device is fine but no item return from output devices on mozila, even working on chrome
Please guide me

### Have you reviewed our existing documentation?

- [X] GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [X] FAQs [page](https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html)
- [X] README [page](https://github.com/aws/amazon-chime-sdk-js#amazon-chime-sdk-for-javascript)
- [X] Feature-specific [guides](https://github.com/aws/amazon-chime-sdk-js#guides)

### Reproduction steps

open chime meeting in mozila 

### Amazon Chime SDK for JavaScript version

2.21.0

### What browsers are you seeing the problem on?

Mozila firefox

### Browser version

102.0

### Browser console logs

No exceptions as such

**Comment by ltrung** [comment]
This is because Firefox does not support selecting output devices as documented in our FAQs https://github.com/aws/amazon-chime-sdk-js/blob/main/guides/07_FAQs.md#i-am-unable-to-select-an-audio-output-device-in-some-browsers-is-this-a-known-issue

**Comment by hytechpro-bikeshs** [comment]
Any alternate way to implement it on Mozilla or we can avoid using Mozilla for chime meetings.
@devalevenkatesh @michhyun1 @ltrung

**Comment by ltrung** [comment]
What is the blocker? In Firefox or Safari, they always use the same output as the mic input (so they determine the default speaker is). Other than that, you should be able to hear audio fine.
