### ISSUE TITLE
Media Capture Pipeline Configuration Issues

### ISSUE THREAD

**Issue by yaralahruthik** [aws/amazon-chime-sdk-js#2359]
### What happened and what did you expect to happen?

SelectedVideoStreams.ExternalUserIds is not being considered for AudioWithActiveSpeakerVideo. That is, even the ignored id's video is shown. But in the Video folder, those are not recorded.

Also, how do combine the audio and video if their durations do not match? Because if the user turns off their video, the video is not at all recorded while the audio is recorded.

In brief, I am trying to record the video of only certain users but with the audio of everyone. Any suggestions?

### Have you reviewed our existing documentation?

- [X] GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [x] FAQs [page](https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html)
- [X] README [page](https://github.com/aws/amazon-chime-sdk-js#amazon-chime-sdk-for-javascript)
- [X] Feature-specific [guides](https://github.com/aws/amazon-chime-sdk-js#guides)

### Reproduction steps

This is the configuration I am using.

`ChimeSdkMeetingConfiguration: {
      SourceConfiguration: {
        SelectedVideoStreams: {
          ExternalUserIds: arrayOfAttendeesExceptInterviewer,
        },
      },
      ArtifactsConfiguration: {
        Audio: {
          MuxType: 'AudioWithActiveSpeakerVideo',
        },
        Content: {
          State: 'Enabled',
          MuxType: 'ContentOnly',
        },
        Video: {
          State: 'Enabled',
        },
      },
    },`

### Amazon Chime SDK for JavaScript version

2.1171.0

### What browsers are you seeing the problem on?

Chrome

### Browser version

Version 103.0.5060.114 (Official Build) (arm64)

### Meeting and Attendee ID Information.

Meeting Id: 903cf06a-0607-4877-8e93-3edf61ab0706
Attendee Ids: e4130396-ff38-9b5f-5272-0898080d2e6f, 8aed8b8e-c3eb-0b26-a01e-ded5e1e41889

### Browser console logs

No logs

**Comment by nehtambe** [comment]
Hi, 
To record video of certain attendees and audio of everyone, you can pass "arrayOfAttendeesExceptInterviewer" under "ExternalUserIds" and MuxType as _AudioOnly_ under "Audio"
Also, you can find blog post which explains how to combine artifacts. 
https://aws.amazon.com/tw/blogs/business-productivity/amazon-chime-sdk-compositing-videos-from-media-capture-pipelines/

**Comment by yaralahruthik** [comment]
@nehtambe I did go through this, but the notice in the blog said that "to keep this concatenating sample simple, the code assumes camera is turned on consistantly when attendees enable, instead of turning camera on/off multiple times during media capture." How do I handle this state? Do I use the information in the meeting-events logs and add all the padding?

One approach our team used yesterday was to use the meeting events active speaker event type and calculate all the timelines where the user was speaking whom we wanted to exclude and replaced those parts of the audio video provided by Audio MUX type "AudioWithActiveSpeakerVideo" with an image. There are some edge cases but this seems to be working! Any thoughts?

**Comment by nehtambe** [comment]
Closing the ticket, please reopen or create a new one if you face any other questions.
