### ISSUE TITLE
Chat read receipts

### ISSUE THREAD

**Issue by swithuns** [aws/amazon-chime-sdk-js#2363]
### What are you trying to do?

I'm trying to set up chat with read receipts as in the user can tell that another user has read their message. 
I've already got set up the functionality to indicate to the user that there's been a message in a channel since they last read using the UpdateChannelReadMarker endpoint, but I can't seem to find anywhere in the documentation an endpoint that would allow me to make use of this updated value for other users. I would essentially want an array of AppInstanceUserMembershipSummary to access all channel members ReadMarkerTimeStamps. 

### How can the documentation be improved to help your use case?
Instructions on how to access something akin to the above.

### What documentation have you looked at so far?
SDK guides including the sdkfordotnet guide and the using the messaging sdk guide.

**Comment by garyzhon** [comment]
Hi swithun92,

Thank you for your interest in this feature. This feature is not currently available. Please do reach out through your AWS account team or contact us in AWS Console to submit a feature request. Much appreciated.

Cheers,
Gary

**Comment by yochum** [comment]
Closing this feature request as it does not directly pertain to the Chime SDK for JavaScript. Please do reach out through your AWS account team or contact us in AWS Console to submit a feature request.
