### ISSUE TITLE
Default Device is listed multiple numbers of time in device lists 

### ISSUE THREAD

**Issue by vijayghaghre** [aws/amazon-chime-sdk-js#2376]
### What happened and what did you expect to happen?

HI Team,

While working with sdk we have seen following methods default device is returned multiple number of times(with different label:
1. audioVideo.listAudioInputDevices()
2. audioVideo.listAudioOutputDevices()
3. audioVideo.listVideoInputDevices()
![Screenshot 2022-07-20 at 1 04 20 PM](https://user-images.githubusercontent.com/46016137/180725539-39ec64af-6515-4b99-9eb2-bc05bd428ef7.png)
![image001](https://user-images.githubusercontent.com/46016137/180725888-1e2f64ec-e2dc-4337-b214-e275ccae5f05.png)

Is it a bug or desired behaviour? If this is desired behaviour then can we filter these based on group_id parameter? 

### Have you reviewed our existing documentation?

- [X] GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [X] FAQs [page](https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html)
- [X] README [page](https://github.com/aws/amazon-chime-sdk-js#amazon-chime-sdk-for-javascript)
- [X] Feature-specific [guides](https://github.com/aws/amazon-chime-sdk-js#guides)

### Reproduction steps

1. Connect any audio or video devices
2. Open device panel/ see list of devices being returned from above methods

### Amazon Chime SDK for JavaScript version

2.31.0

### What browsers are you seeing the problem on?

It is not browser specific as we using sdk so we can see these in every browser.

### Browser version

All

### Browser console logs

1. Input Audio devices:

* 		deviceId: "default" groupId: "0677c5d8d5a712e21de82c8e14a7cc41a4dc2ef813ce9114aef0753002fc4c40" kind: "audioinput" label: "Default - Soundcore Liberty Air 2 (Bluetooth)"

* 		deviceId: "70a4c79c35e1c0f5361499a7b5570cbc9e1e26fea91e3a04c2d29cc5339525dd" groupId: "0677c5d8d5a712e21de82c8e14a7cc41a4dc2ef813ce9114aef0753002fc4c40" kind: "audioinput" label: "Soundcore Liberty Air 2 (Bluetooth)"

* 		deviceId: "eb6cf99b6ca7af91d8c06c480df0676a96571d4bf1a33542db42bb6e3f16421e" groupId: "13ebc173c533f614b064913452d6198d0c32954a1be7de875d412560c1f4307e" kind: "audioinput" label: "MacBook Pro Microphone (Built-in)"

* 		deviceId: "6de12ee9b260fcb6b7757c9f0f4b74e3bbee5d5d64fa4c6fbefcccb2ff684c84" groupId: "bd98c8d272ae8f4786d1c730e121408415e4ba0a62cc361b509a8ab4b799853f" kind: "audioinput" label: "Microsoft Teams Audio Device (Virtual)"

2. Output audio
* 		deviceId: "default" groupId: "5cfe9c641204be8a53e6934deccb46533861b8c79f00d5161b2e12e487ef956e" kind: "audiooutput" label: "Default - Soundcore Liberty Air 2 (Bluetooth)"

* 		deviceId: "ccaeded2dda25a53eb2de0689c296186691295394b5541dea7b36e86751c5470" groupId: "5cfe9c641204be8a53e6934deccb46533861b8c79f00d5161b2e12e487ef956e" kind: "audiooutput" label: "Soundcore Liberty Air 2 (Bluetooth)"

* 		deviceId: "6f9a4e82f8d2e5d1aa798f8fc110d2f664edebe8e75aa131aced560ae94787a0" groupId: "13ebc173c533f614b064913452d6198d0c32954a1be7de875d412560c1f4307e" kind: "audiooutput" label: "MacBook Pro Speakers (Built-in)"

* 		deviceId: "6de12ee9b260fcb6b7757c9f0f4b74e3bbee5d5d64fa4c6fbefcccb2ff684c84" groupId: "bd98c8d272ae8f4786d1c730e121408415e4ba0a62cc361b509a8ab4b799853f" kind: "audiooutput" label: "Microsoft Teams Audio Device (Virtual)"

3. Input video
* 		deviceId: "c2e0cebb1840e586df4210af2e4e0b3d1da82c6826f81e99c2e18bfc399dbe2d" groupId: "58d9c178011ef64f7a0db672b5fcdb6327f10ac07be5178c43885d92c31e542c" kind: "videoinput" label: "FaceTime HD Camera"

**Comment by devalevenkatesh** [comment]
Since this default browser behavior for Chrome, please let us know if you face any other issues.
