### ISSUE TITLE
After stopping screen share video is not visible

### ISSUE THREAD

**Issue by preeti-ti** [aws/amazon-chime-sdk-js#2377]
### What happened and what did you expect to happen?

Hi,
   I have made one video calling app by following this link https://aws.amazon.com/blogs/business-productivity/build-a-video-contact-center-with-amazon-connect-and-amazon-chime-sdk/.  I have added screenshare option in this app i am able to screen share but when i stop sharing my screen video is not visible. I have tried working with two video tiles also one for screenshare another for video still got the same. Please let me know where i am doing wrong.

### Have you reviewed our existing documentation?

- [X] GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [X] FAQs [page](https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html)
- [X] README [page](https://github.com/aws/amazon-chime-sdk-js#amazon-chime-sdk-for-javascript)
- [X] Feature-specific [guides](https://github.com/aws/amazon-chime-sdk-js#guides)

### Reproduction steps

share your screen in chime meeting and when you stopped sharing video is not visible.

### Amazon Chime SDK for JavaScript version

1.2.1

### What browsers are you seeing the problem on?

chrome

### Browser version

103.0.5060.134

### Meeting and Attendee ID Information.

Meeting ID - 7d6bc4d0-d396-4d85-945b-72f939040706
Agent ID - d82f3123-a16f-e844-a0cc-e81a4c4674f1
Customer ID - 9dd33296-6dcc-3ca0-8280-582c293ae6b6

### Browser console logs

[localhost-1658906476448.log](https://github.com/aws/amazon-chime-sdk-js/files/9196161/localhost-1658906476448.log)

**Comment by xuesichao** [comment]
Hi @preeti-ti!

From roster events, I see every thing is working as expected:
| Time                  | Attendee ID                              | Event                      |
| --------------------- | ---------------------------------------- | -------------------------- |
| 7/27/2022 12:17:27 AM | 9dd33296-6dcc-3ca0-8280-582c293ae6b6     | VideoStarted               |
| 7/27/2022 12:17:32 AM | d82f3123-a16f-e844-a0cc-e81a4c4674f1     | VideoViewingStarted        |
| 7/27/2022 12:17:33 AM | d82f3123-a16f-e844-a0cc-e81a4c4674f1     | VideoStarted               |
| 7/27/2022 12:17:33 AM | 9dd33296-6dcc-3ca0-8280-582c293ae6b6     | VideoViewingStarted        |
| 7/27/2022 12:17:54 AM | 9dd33296-6dcc-3ca0-8280-582c293ae6b6     | ContentVideoStarted        |
| 7/27/2022 12:17:55 AM | d82f3123-a16f-e844-a0cc-e81a4c4674f1     | ContentVideoViewingStarted |
| 7/27/2022 12:18:01 AM | 9dd33296-6dcc-3ca0-8280-582c293ae6b6     | ContentVideoEnded          |
| 7/27/2022 12:18:01 AM | d82f3123-a16f-e844-a0cc-e81a4c4674f1     | ContentVideoViewingEnded   |
| 7/27/2022 12:18:46 AM | 9dd33296-6dcc-3ca0-8280-582c293ae6b6     | VideoEnded                 |
| 7/27/2022 12:18:46 AM | 9dd33296-6dcc-3ca0-8280-582c293ae6b6     | VideoViewingEnded          |
| 7/27/2022 12:18:46 AM | 9dd33296-6dcc-3ca0-8280-582c293ae6b6     | VideoConnectionEnded       |
| 7/27/2022 12:18:46 AM | 9dd33296-6dcc-3ca0-8280-582c293ae6b6     | VoIPLeave                  |
| 7/27/2022 12:18:46 AM | d82f3123-a16f-e844-a0cc-e81a4c4674f1     | VideoViewingEnded          |
| 7/27/2022 12:18:54 AM | sdk-e6d8f61b-62a7-4880-9ed0-db9b68b13e7b | SdkConferenceEnded         |
| 7/27/2022 12:18:54 AM | d82f3123-a16f-e844-a0cc-e81a4c4674f1     | VideoEnded                 |
| 7/27/2022 12:18:54 AM | d82f3123-a16f-e844-a0cc-e81a4c4674f1     | VideoConnectionEnded       |
| 7/27/2022 12:18:54 AM | d82f3123-a16f-e844-a0cc-e81a4c4674f1     | VoIPLeave                  |

From the browser log, I observed following message:
```
// First attendee enabled video
2022-07-27T07:17:27.718Z [INFO] ChimeMeetingLogs - API/DefaultAudioVideoFacade/7d6bc4d0-d396-4d85-945b-72f939040706/9dd33296-6dcc-3ca0-8280-582c293ae6b6/bindVideoElement {"tileId":1,"videoElementId":""}

// second attende enabled video
2022-07-27T07:17:33.586Z [INFO] ChimeMeetingLogs - API/DefaultAudioVideoFacade/7d6bc4d0-d396-4d85-945b-72f939040706/9dd33296-6dcc-3ca0-8280-582c293ae6b6/bindVideoElement {"tileId":2,"videoElementId":""}

// Screen share started, the stream was bound to video tile 3
2022-07-27T07:17:54.427Z [INFO] ChimeMeetingLogs - API/DefaultAudioVideoFacade/7d6bc4d0-d396-4d85-945b-72f939040706/9dd33296-6dcc-3ca0-8280-582c293ae6b6/bindVideoElement {"tileId":3,"videoElementId":""}
Screen share started

// Screen share ended, video tile 3 was removed
​2022-07-27T07:18:01.464Z [INFO] ChimeMeetingLogs - serial group task AudioVideoClean/7d6bc4d0-d396-4d85-945b-72f939040706/9dd33296-6dcc-3ca0-8280-582c293ae6b6#content completed
​Tile with ID: 3 got removed
​Screen share stopped

// Meeting ended
**2022-07-27T07:18:46.242Z [INFO] ChimeMeetingLogs - received the ended event for tile=null id=97df2f9e-3480-4b16-9337-f8ff66a8e3cd streamId=3
​2022-07-27T07:18:46.242Z [INFO] ChimeMeetingLogs - video track ended, removing tile=null id=97df2f9e-3480-4b16-9337-f8ff66a8e3cd stream=null
​2022-07-27T07:18:46.242Z [WARN] ChimeMeetingLogs - no stream found for tile=null**
​Tile with ID: 1 got removed
​Tile with ID: 2 got removed
```

I didn't see content share feature in the [guide](https://aws.amazon.com/blogs/business-productivity/build-a-video-contact-center-with-amazon-connect-and-amazon-chime-sdk/) you are following. 
I feel like you may not handle the video tiles correctly, after adding the content share feature in your application.

>I have added screenshare option in this app i am able to screen share but when i stop sharing my screen video is not visible. I have tried working with two video tiles also one for screenshare another for video still got the same. Please let me know where i am doing wrong.

I have few questions regarding this statement:
1. Is camera video tile visible when someone shares the screen?
2. What does `my screen video is not visible` mean. Is it a blank video tile or even no video tile at all?

Also `v1.2.1` is pretty old and is deprecated. Could you try to use the latest version of JS SDK?

**Comment by preeti-ti** [comment]
Hi, 
   1- i didn't get your question. When someone shares the screen then another person is able to see the screen and his/her video also be visible in the down.
   2 - video is coming as blank video i guess tile itself is getting removed that's why it's showing as blank. 

I will try with latest version and let you know 

Thanks

**Comment by devalevenkatesh** [comment]
Resolving this issue as no further update, please free to reopen if you still have issue with content share. Request to also check our [browser meeting demo](https://github.com/aws/amazon-chime-sdk-js/tree/main/demos/browser) for reference.

As Sichao mentioned that demo is quite old and JS SDK is at 3.6.0 as of latest release. Request you to follow below sections for implementing the content share correctly:
1. https://aws.github.io/amazon-chime-sdk-js/modules/contentshare.html
2. https://aws.github.io/amazon-chime-sdk-js/index.html#screen-and-content-share
