### ISSUE TITLE
VideoGridLayout with paging

### ISSUE THREAD

**Issue by jaeho0522** [aws/amazon-chime-sdk-js#2378]
With SDK 3.0 supporting up to 25 video tiles, I have concerns about the quality and speed of displaying 25 video tiles in single page.
Is there anyway to make VideoGridLayout to have paging feature,
so that each page only display certain number of video tiles(say up to 16)?
Any help or comment will be greatly appreciated.

**Comment by xuesichao** [comment]
JS SDK supports paging feature, but there's no ready to use component for it. You need to implement it yourself. 
The basic idea is to use [`VideoPriorityBasedPolicy`](https://aws.github.io/amazon-chime-sdk-js/classes/videoprioritybasedpolicy.html). This allows you to subscribe to any video resource you want. For example if you have 25 video streams, and by default local attendee subscribe to all of them, so there will be 25 video tiles in the page. If you just subscribe to first 16 video sources, then there will be 16 video tiles in the page. And you can use CSS to modify the style/layout of the video tiles.

Check below resources for references:
- [Priority-Based Video Downlink Policy Guide](https://aws.github.io/amazon-chime-sdk-js/modules/prioritybased_downlink_policy.html)
- [Managing Video Quality for Different Video Layouts](https://aws.github.io/amazon-chime-sdk-js/modules/videolayout.html)
- [Our browser demo's paging implementation](https://github.com/aws/amazon-chime-sdk-js/blob/be0420b98e10f1a1ff088cad9fbc2151e1fe84a0/demos/browser/app/meetingV2/video/PaginationManager.ts)
    - PR #1830

**Comment by devalevenkatesh** [comment]
Closing this issue, please feel to re-open if you need further help. Here are two more demos to help you implement pagination with or without `VideoPriorityBasedPolicy`:
https://github.com/devalevenkatesh/test-amazon-chime-sdk-react-components/tree/main/pagination

Though the implementation was tailored to debug a memory issue, but the idea for pagination is the same.

**Comment by jaeho0522** [comment]
Thank you for your help.

I was not able to look into this issue due to other features.
I will consider your recommendations when I am able to address this issue.

Thanks again for your help.

Regards,


Jaeho Lee
CEO/Programmer

#202, Wonseong Bldg., 29, Seochojungang-ro 20-gil, Seocho-gu, Seoul, Republic of Korea
​Tel +82 2 6205 7370 Mobile +82 10 3720 6763​
Email ***@***.***



-----Original Message-----
