### ISSUE TITLE
Firefox does not show audio outputs

### ISSUE THREAD

**Issue by Mattwhooo** [aws/amazon-chime-sdk-js#238]
**Describe the bug**
The listAudioOutputDevices method is displaying different behavior on Firefox vs Chrome.  In Chrome I can see several audio output devices, but in Firefox I get an empty list.  This is in an application that is secured over https and microphone permissions have been granted for both browsers.  

**Platform**
 - MacOs 10.15.4: 
 - Browser: Firefox
 - Browser Version:  74.0
 - Amazon Chime SDK GitHub Commit:  1.2.1  pulled from NPM

**Comment by aburnson** [comment]
@Mattwhooo, Firefox does not presently support audio device output selection unless the user enables the experimental preference `media.setsinkid.enabled`. You can follow [Mozilla Bug 1498512](https://bugzilla.mozilla.org/show_bug.cgi?id=1498512) to track the release status of this feature. When this does eventually ship, audio output device selection should then work for the SDK.

**Comment by smarty192** [comment]
When I was testing this demo code in firefox, regardless of empty list, we were able to conduct meeting, what chime web sdk demo code is doing to overcome the issue?

**Comment by ltrung** [comment]
@smarty192 The current demo code does not do anything to allow selection of audio output device. All it does is if there is no output from listAudioOutputDevices then it will set an option "Device selection unavailable".
From our [FAQs](https://github.com/aws/amazon-chime-sdk-js/blob/master/guides/06_FAQs.md):
> I am unable to select audio output device in some browsers, is this a known issue?
   Firefox and Safari have known issues disallowing them from listing audio output devices on these browsers. While clients can continue the meeting using the default device, they will not be able to select devices in meetings.

**Comment by shivam145** [comment]
Agreed @ltrung please help me understand, as we dont have any audio output device id, how can we set the the default one to the html audio element, i went through the demo code, but didnot get any hint, am i missing something?

**Comment by ltrung** [comment]
@shivam145 you just need to call `bindAudioElement` and did not need to pass any deviceid, Firefox will just use the default device output (speaker or headset if you use headset)
