### ISSUE TITLE
IOS asks video/mic permissions always(Chrome, Safari)

### ISSUE THREAD

**Issue by tkulis** [aws/amazon-chime-sdk-js#2381]
### What happened and what did you expect to happen?

Hi there,

I do experience some problems with iPhone && Chime SDK(versions 2.27.0 && 3.6.0), but I cannot find any info about it.
So when I open a page where Chime is implemented and try to join a meeting and I do trigger query for devices(eg.):
`const audioInputDevices = await window.audioVideo.listAudioInputDevices();`

In Iphone I get this  pop up **"webiste.com would like to access the Mic..."** but on every reload/visit.
I did tried solutions from here [https://stackoverflow.com/questions/30047056/is-it-possible-to-check-if-the-user-has-a-camera-and-microphone-and-if-the-permi](url),  eg `navigator.mediaDevices.enumerateDevices()`, which should return something if access already was permitted, but somehow nothing works (on Iphone of course).
I would expected to see this dialog only once, and in subsequent visits not any more.

![image](https://user-images.githubusercontent.com/8543254/181442746-137e472c-ccd1-43e7-9180-296202534868.png)

Can someone help here please?

### Have you reviewed our existing documentation?

- [X] GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [X] FAQs [page](https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html)
- [X] README [page](https://github.com/aws/amazon-chime-sdk-js#amazon-chime-sdk-for-javascript)
- [X] Feature-specific [guides](https://github.com/aws/amazon-chime-sdk-js#guides)

### Reproduction steps

already explained in "What happend..."

### Amazon Chime SDK for JavaScript version

2.27.0, 3.6.0

### What browsers are you seeing the problem on?

Safari, Chrome

### Browser version

latest

### Browser console logs

no log

**Comment by LeviSklaroff** [comment]
From what I could find this is a browser setting on IPhone devices it will ask for permissions every time you access a site. If you check other sites that use mics and it should have the same behavior.

**Comment by devalevenkatesh** [comment]
Yes, you can also test the same on WebRTC official samples:
https://webrtc.github.io/samples/src/content/getusermedia/gum/

I tested on above sample using iPhone and its the same behavior. The iOS Chrome is actually a wrapper around Safari and hence the behavior is the same. Closing this issue, please feel free to re-open if you still you any questions.
