### ISSUE TITLE
AbortError: The operation was aborted in macOS Safari

### ISSUE THREAD

**Issue by milykh-clearscale** [aws/amazon-chime-sdk-js#2394]
### What happened and what did you expect to happen?

When any attendees tries to turn on the camera the error raised "AbortError: The operation was aborted". However, the video stream is available.

Hardware: MacBook Pro M1.
<img width="1720" alt="Screenshot 2022-08-08 at 15 59 32" src="https://user-images.githubusercontent.com/47162633/183428323-7a18fbe0-86d0-4fed-92fc-6c55df93eef2.png">

### Have you reviewed our existing documentation?

- [X] GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [X] FAQs [page](https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html)
- [X] README [page](https://github.com/aws/amazon-chime-sdk-js#amazon-chime-sdk-for-javascript)
- [X] Feature-specific [guides](https://github.com/aws/amazon-chime-sdk-js#guides)

### Reproduction steps

1. Deploy the lates demo app [https://github.com/aws/amazon-chime-sdk-js/tree/main/demos/serverless](serverless).
2. Join meeting with at least two attendees.
3. Any attendee turns on the camera.

### Amazon Chime SDK for JavaScript version

3.5.0

### What browsers are you seeing the problem on?

Safari

### Browser version

15.6 (17613.3.9.1.5)

### Browser console logs

[Console.txt](https://github.com/aws/amazon-chime-sdk-js/files/9281960/Console.txt)

**Comment by devalevenkatesh** [comment]
Thanks for reporting the error, I have a PR already open to fix this issue:
https://github.com/aws/amazon-chime-sdk-js/pull/2391

Webkit reported bug: https://bugs.webkit.org/show_bug.cgi?id=243519

**Comment by devalevenkatesh** [comment]
The fix is released in 3.7.0 now, resolving this issue, thank you for your patience!
