### ISSUE TITLE
Unable to select speaker device and microphone output in Safari

### ISSUE THREAD

**Issue by kodai305** [aws/amazon-chime-sdk-js#2395]
### What happened and what did you expect to happen?

I have a demo app, or a conference app that references it, that does not allow me to do the following

No speaker devices are found" on the device setting screen before joining a conference, and the device is not acquired.

The speaker device cannot be selected while participating in a conference.

Also, the microphone is behaving strangely. Specifically, audio cannot be acquired with the selected microphone when participating in a conference. This occurs especially when an external microphone is connected and multiple microphones can be selected.
It appears to be a bug, although it resolves itself after re-selecting the microphones several times.

### Have you reviewed our existing documentation?

- [X] GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [X] FAQs [page](https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html)
- [X] README [page](https://github.com/aws/amazon-chime-sdk-js#amazon-chime-sdk-for-javascript)
- [X] Feature-specific [guides](https://github.com/aws/amazon-chime-sdk-js#guides)

### Reproduction steps

Join a meeting in Safari

### Amazon Chime SDK for JavaScript version

2.30.1

### What browsers are you seeing the problem on?

Safari

### Browser version

15.5

### Browser console logs

I couldn't find a specific error log.

**Comment by devalevenkatesh** [comment]
This is a known browser behavior with Safari and Firefox as well. It is mentioned in our FAQ:
https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html#i-am-unable-to-select-an-audio-output-device-in-some-browsers-is-this-a-known-issue

Closing this issue now, this should be the same behavior if you try the WebRTC based official samples:
https://webrtc.github.io/samples/src/content/devices/input-output/
