### ISSUE TITLE
Expand NumberSelectionBehavior in CreateProxySession

### ISSUE THREAD

**Issue by danemauland** [aws/amazon-chime-sdk-js#2397]
# Community Note
* Please vote for this issue by adding a 👍 reaction to the issue. This will help the community and maintainers from the Amazon Chime SDK team to prioritize this request.
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request.

# Tell us about your request
## What do you want us to build?
I work at a managed marketplace. Our customers have one point of contact, but each supplier may have multiple points of contact. It would be very helpful for us if the NumberSelectionBehavior in the CreateProxySession action were expanded (or a new option added) where we could request that the assigned proxy phone number be the same as the proxy phone number for an existing proxy session/phone number combination. This would allow us to give the supplier only one phone number which everyone on that team could use to contact the customer.

Which Amazon Chime SDK or feature area is this request for?
A new feature idea for the [CreateProxySession](https://docs.aws.amazon.com/chime-sdk/latest/APIReference/API_CreateProxySession.html) action.

## How are you currently solving a problem?
Currently, each person on the supplier's team receives a separate phone number for the same customer. This often leads to confusion, since if a phone number is lost, they sometimes ask their colleague for it. The colleague then gives them their proxy phone number, which doesn't work.

**Comment by devalevenkatesh** [comment]
@danemauland thanks for reporting this issue, but the `CreateProxySession` API in coming from Amazon Chime SDK voice connector which the JS SDK does not relate to. Request you to please reachout to support for filing this feature request.

I am closing this issue now.
