### ISSUE TITLE
Using addVoiceFocus() in Safari, no audio is output from the microphone.

### ISSUE THREAD

**Issue by kodai305** [aws/amazon-chime-sdk-js#2403]
### What happened and what did you expect to happen?

The meeting application is implemented with reference to the Demo application.

To enable VoiceFocus functionality, we are implementing VoiceFocusProvider and useVoiceFocus.

An image of the implementation is below.

```
    try {
      let current = selectedDevice;
      if (typeof selectedDevice === 'string') {
        current = await addVoiceFocus(current);
      }
      await meetingManager.startAudioInputDevice(current as AudioInputDevice); }
    }
```

I can get the sound from the microphone in chrome with no problem, but in Safari I can't get the audio. addVoiceFocus is not supported in Safari?

### Have you reviewed our existing documentation?

- [X] GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [X] FAQs [page](https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html)
- [X] README [page](https://github.com/aws/amazon-chime-sdk-js#amazon-chime-sdk-for-javascript)
- [X] Feature-specific [guides](https://github.com/aws/amazon-chime-sdk-js#guides)

### Reproduction steps

Implement addVoiceFocus using the method described above and make it work in Safari

### Amazon Chime SDK for JavaScript version

3.6.0

### What browsers are you seeing the problem on?

Safari

### Browser version

15.5 (17613.2.7.1.8)

### Browser console logs

none error message

**Comment by xuesichao** [comment]
Hi @kodai305. I couldn't reproduce this issue using the [meeting demo of our React Component Library](https://github.com/aws-samples/amazon-chime-sdk/tree/main/apps/meeting) using Safari 15.5. In my testing, the voice focus is working well and the audio input/output is working well for both remote attendee and local attendee.

For your question:

>addVoiceFocus is not supported in Safari?

Amazon Voice Focus supports Safari browser.

Have you tried to reproduce the issue using the meeting demo above? If so, what's the result? and If not, could you please try?

To enable the Amazon Voice Focus, you can toggle it from the audio input control:
![image](https://user-images.githubusercontent.com/20471438/188967038-45e1c708-35fb-49ee-b429-68242d2ab4ca.png)

For the code you provide, I don't understand what's the propose of that, could you explain further so I can help you better?

For reference, in our `AudioInputVFControl` component, we have similar logic. Have you referred to this implementation for help?
https://github.com/aws/amazon-chime-sdk-component-library-react/blob/c2b804cb3b31e3e0a04538e3c1e3ccba7dab584b/src/components/sdk/MeetingControls/AudioInputVFControl.tsx#L175-L206

**Comment by kodai305** [comment]
We have confirmed that it works using the demo app. However, what we would like to achieve is to enable VoiceFocus by default instead of toggling it on when the microphone is selected.

That has not been achieved in Safari.
