### ISSUE TITLE
I'm finding a way to check the device, to check it can share screen. Do you know how to it ?

### ISSUE THREAD

**Issue by hoanp-techvify** [aws/amazon-chime-sdk-js#2406]
### What are you trying to do?

*For example: I'm trying to start a meeting session with audio.*

### How can the documentation be improved to help your use case?

*For example: Include a section on how to configure the meeting session.*

### What documentation have you looked at so far?

*For example: README.md, Amazon Chime SDK Developer Guide, etc.

**Comment by ltrung** [comment]
Sorry not sure the question is. Could you open a new issue and fill in the details?
