### ISSUE TITLE
Chime Messaging: WebSocket close: 4999 Failed to get messaging session endpoint URL

### ISSUE THREAD

**Issue by singulli1** [aws/amazon-chime-sdk-js#2408]
### What happened and what did you expect to happen?

After we applied update 3.7.0  we started getting the following errors:
[chatLog4.txt](https://github.com/aws/amazon-chime-sdk-js/files/9417758/chatLog4.txt)

Issue 2372 was supposed to fix, caused different errors.

### Have you reviewed our existing documentation?

- [X] GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [X] FAQs [page](https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html)
- [X] README [page](https://github.com/aws/amazon-chime-sdk-js#amazon-chime-sdk-for-javascript)
- [X] Feature-specific [guides](https://github.com/aws/amazon-chime-sdk-js#guides)

### Reproduction steps

see above

### Amazon Chime SDK for JavaScript version

3.7.0

### What browsers are you seeing the problem on?

all

### Browser version

all

### Browser console logs

see above

**Comment by ltrung** [comment]
@singulli1 Thanks for reporting. Could you let us know your aws_sdk_js version of the chime client you pass into `MessagingSessionConfiguration`?  Do you also pass in any `endpointURL` to `MessagingSessionConfiguration`?

**Comment by ltrung** [comment]
Seem like we are discussing in #2372 so I will reopen that one and close this one for now.
