### ISSUE TITLE
Composition API to allow vertical video tile aligning even when content share is not present

### ISSUE THREAD

**Issue by sarascoding** [aws/amazon-chime-sdk-js#2411]
# Community Note
* Please vote for this issue by adding a 👍 reaction to the issue. This will help the community and maintainers from the Amazon Chime SDK team to prioritize this request.
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request.
* Please go through the existing [issues](https://github.com/aws/amazon-chime-sdk-js/issues) to see if your request has already been recommended.
* Please do not use this template for bugs or support. Each individual repository has a PR template, documentation and resources for [troubleshooting](https://github.com/aws/amazon-chime-sdk-js#troubleshooting-and-support).
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.

# Tell us about your request
## What do you want us to build?

The new Chime composition API is great! The only thing is that it only allows you to have videos in a non configurable grid view unless you have content sharing enabled. 
I was wondering if there's a way to stack videos (if there's only 2 in total) vertically instead of horizontally and have them scaled in the same aspect ratio regardless of the browser they were streamed from.
 
Which Amazon Chime SDK or feature area is this request for?
[amazon-chime-sdk-js](https://github.com/aws/amazon-chime-sdk-js)

## Tell us about the problem you are trying to solve and why is it hard?
We want the video tiles to be arranged vertically with less background padding as possible to give the idea of the 2 video tiles in a session.

## How are you currently solving a problem?
Are there any workarounds or mitigations you have used? Why is it not working for you?

Right now we are trying to build our own composition & concatenation with ffmpeg for each video tile but we're having difficulties when the video stream is turned off for one attendee since we can't align the video to be a black screen when there's no stream at all for that attendee.

**Comment by tenge-amzn** [comment]
hi @sarascoding 
thanks for the feedback. we're currently investigating how to make the video compositing more customizable and flexible. 

Wondering if you have anything in mind about how you want to describe a customized layout through API?

**Comment by sarascoding** [comment]
Hi @tenge-amzn,
Thanks for replying. We're thinking of a layout where you can customize alignment, scale, start mode and pad so maybe something like:
`{
    "SourceType": "ChimeSdkMeeting",
    "SourceArn": "arn:aws:chime::<account-id>:meeting:<meeting-id>",
    "SinkType": "S3Bucket",
    "SinkArn": "arn:aws:s3:::tenge-recording-test",
    "ChimeSdkMeetingConfiguration": {
        "ArtifactsConfiguration": {
            "Audio": {
                "MuxType": "AudioWithCompositedVideo"
            },
            "Video": {
                "State": "Disabled",
                "MuxType": "VideoOnly"
            },
            "Content": {
                "State": "Disabled",
                "MuxType": "ContentOnly"
            },
            "CompositedVideo": {
                "Layout": "GridView",
                "Align":"Vertically"
                "Resolution": "FHD",
                "Scale":"640:480",
                "StartMode": "Black" 
                "Pad":"1280:480",
                "GridViewConfiguration": {
                    "ContentShareLayout": "OFF"
                }
            }
        },
        "SourceConfiguration": {
            "SelectedVideoStreams": { 
                "AttendeeIds": ["attendeeID1","attendeeID2"], 
                "ExternalUserIds": [ "string" ]
            }
        }
    }
}`

Where: 
**Align** - alignment for only video tiles in the grid view when content sharing is off (Vertically/Horizontally)
**Scale** - a single tile aspect ratio regardless of browser stream
**Pad** - final composite video aspect ratio
**ContentShareLayout** - OFF if not using content sharing
**StartMode** - background color which is by default black but we could customize it to another bg

**Comment by tenge-amzn** [comment]
Close for now. We will provide update once we have progress.
