### ISSUE TITLE
Trigger meetingFailed event

### ISSUE THREAD

**Issue by akinmaurice** [aws/amazon-chime-sdk-js#2414]
Is there a way for me to trigger the meetingFailed event here Trying to provide a UI for clients to interact with when this happens. Thanks

<img width="756" alt="Screenshot 2022-08-29 at 13 39 37" src="https://user-images.githubusercontent.com/10801323/187263976-82773744-e29a-4fa1-b7c0-b6199c311623.png">

**Comment by akinmaurice** [comment]
> Thanks for filing an issue @akinmaurice . Could you please let us know what do you mean by "trigger the meetingFailed here"?
> 
> You can implement the `eventDidReceive` method in your application where you should get the `meetingFailed` event. Once received you can enable a state in your app which shows the UI behavior.

i have implemented the eventDidReceive method, just curious to know if theres a click path to cause the meeting to fail, which will trigger the meetingFailed event.

**Comment by michhyun1** [comment]
You might be able to manually trigger some type of event from this [table](https://github.com/aws/amazon-chime-sdk-js/blob/6037e5c9a42c50e870acbd4b22351c955357d460/guides/06_Meeting_Events.md#meeting-error-messages:~:text=The%20Chime%20SDK%20for%20JavaScript%20also%20raises%20the%20meetingFailed%20event%20containing%20the%20meetingErrorMessage%20attribute%20if%20the%20meeting%20stops%20due%20to%20an%20error.%20The%20following%20table%20lists%20common%20error%20messages%20from%20a%20stopped%20meeting).

**Comment by michhyun1** [comment]
Maybe you can try to manually throw an error on a realtimeController api or something.

**Comment by michhyun1** [comment]
@akinmaurice did you need any more guidance on this?

**Comment by devalevenkatesh** [comment]
Closing this issue due to no further activity, please feel free to re-open as needed.
