### ISSUE TITLE
Video is not available on meeting start

### ISSUE THREAD

**Issue by mikhail-shekhtman** [aws/amazon-chime-sdk-js#2416]
### What happened:

On the start of the meeting remote and local video are not available. 
After toggling video off and on the local video shows up. 
After toggling video off and on on the remote side remote video also shows up.

### Expected behavior: 

Video is available from the start of the meeting.

### Have you reviewed our existing documentation?

- [X] GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [X] FAQs [page](https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html)
- [X] README [page](https://github.com/aws/amazon-chime-sdk-js#amazon-chime-sdk-for-javascript)
- [X] Feature-specific [guides](https://github.com/aws/amazon-chime-sdk-js#guides)

### Reproduction steps

I cannot reproduce issue consistently, I suspect that it is a bandwidth issue.

### Amazon Chime SDK for JavaScript version

"amazon-chime-sdk-js": "^2.6.2",

### What browsers are you seeing the problem on?

Chrome

### Browser version

Chrome 104.0.5112.101 (Official Build) (arm64)

### Meeting and Attendee ID Information.

please see the attached log.

In the log you can see start of the meeting where video is not available.

At 2022-08-28T16:29:48.453Z I have toggled off and back on the local video and it showed up.
A bit later I did the same with remote video on the remote client and it is also showed up.

 

### Browser console logs

[no-video-log-28_08_2022.log](https://github.com/aws/amazon-chime-sdk-js/files/9450846/no-video-log-28_08_2022.log)

**Comment by michhyun1** [comment]
Please provide more details on your environment. Are you using the JS SDK demo app or your own app? 

The demo app does not have the video turned on by default.

**Comment by mikhail-shekhtman** [comment]
> 

@michhyun1 this is happening in our own app. The video is turned on by default at the start of the meeting.

**Comment by michhyun1** [comment]
Have you chosen a video input device before starting the local video tile? Do you see the light indicator which indicates that the video camera is turned on and selected?

**Comment by michhyun1** [comment]
So this issue is not consistent? Meaning that sometimes you DO have the video on at the start of the meeting?
It seems as though the video input device is selected correctly in the logs - perhaps I'd look at where you are binding the video stream to the video element?

**Comment by mikhail-shekhtman** [comment]
@michhyun1 Video is showing up correctly most of the time, and we noticed this issue only recently without touching this part for over a year now.

**Comment by michhyun1** [comment]
If you haven't changed the verison of the JS SDK for over a year, I'd suggest upgrading to v3 of the JS SDK and see if the issue persists.

**Comment by devalevenkatesh** [comment]
Hi @mikhail-shekhtman, were you able to get around this issue. Generally, I have seen that builders start the meeting video right away as soon as they trigger `meetingSession.audioVideo.start()`, instead, I suggest waiting for the `audioVideoDidStart` callback to get triggered which indicates that the meeting session has successfully started and then start the local video tile.

I suggest doing the following steps and see whether they help:
```js
const localVideoElement = /* HTMLVideoElement object e.g. document.getElementById('video-local-element-id') */;
const remoteVideoElement = /* HTMLVideoElement object e.g. document.getElementById('video-remote-element-id') */;

// Make sure you have chosen your camera. In this use case, you will choose the first device.
const videoInputDevices = await meetingSession.audioVideo.listVideoInputDevices();

// The camera LED light will turn on indicating that it is now capturing.
// See the "Device" section for details.
await meetingSession.audioVideo.startVideoInput(videoInputDevices[0].deviceId);

const observer = {
  // videoTileDidUpdate is called whenever a new tile is created or tileState changes.
  videoTileDidUpdate: tileState => {
    // Ignore a tile without attendee ID and other attendee's tile.
    if (!tileState.boundAttendeeId) {
      return;
    }
    meetingSession.audioVideo.bindVideoElement(tileState.tileId, tileState.localTile ? localVideoElement : remoteVideoElement);
  }
  audioVideoDidStart: () => {
    console.log('Started');
    // Start the video here
    meetingSession.audioVideo.startLocalVideoTile();    
  }
};

meetingSession.audioVideo.addObserver(observer);
meetingSession.audioVideo.start();
```

**Comment by devalevenkatesh** [comment]
Hello, I am closing this issue due to in-activity. Please feel free to re-open if you need any help.

**Comment by mikhail-shekhtman** [comment]
@devalevenkatesh thank you for you detailed answer, I actually updated the library to the latest one and we stop seeing this behavior. 
Until couple of days ago. What is different this time, that it seems happen randomly to the meeting participant. Local video and remotes are not starting, sometimes all of them not starting. 
We have as angular web app as mobile react native application that uses both ios and android, and we are seeing this behavior at least in js sdk and ios sdk. 

All using latest version. And pretty much code you posted is the way we are using it.

Would you have any other suggestions why it might be happening?
