### ISSUE TITLE
Chime SDK Browser

### ISSUE THREAD

**Issue by maheshwari-siddharth** [aws/amazon-chime-sdk-js#2418]
### What happened and what did you expect to happen?

Hi 

We are importing a Chime SDK Browser and running it from npm start it works fine but as soon as we build and run the build it throws an error message which we are attaching as a picture
![Screenshot 2022-09-01 at 5 03 40 PM](https://user-images.githubusercontent.com/64456962/187905588-df2744ee-7df6-46f8-b1e5-7acce8248076.png)

Please advise some solution

Thanks
Siddharth Maheshwari

### Have you reviewed our existing documentation?

- [X] GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [X] FAQs [page](https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html)
- [X] README [page](https://github.com/aws/amazon-chime-sdk-js#amazon-chime-sdk-for-javascript)
- [X] Feature-specific [guides](https://github.com/aws/amazon-chime-sdk-js#guides)

### Reproduction steps

/environment/amazon-chime-sdk-js-main/demos/browser $ npm run build 

when you run the output in the browser and join the meeting it throws an error message.

### Amazon Chime SDK for JavaScript version

Release amazon-chime-sdk-3.7.0 

### What browsers are you seeing the problem on?

crome , safari 

### Browser version

latest in both case

### Browser console logs

Unexpected token '<', "<html>

<h"... is not valid JSON

**Comment by michhyun1** [comment]
Can you please add reproduction steps? Have you done `npm run start`?

**Comment by maheshwari-siddharth** [comment]
Hi Michhyun

first we did 

Step-1 npm install
Step-2 npm run Start 

Step-3 then in browser localhost:8080

from here it works fine 

but  when we run 

step- 4 npm run build  

Step-5 open    /environment/amazon-chime-sdk-js-main/demos/browser/dist/meetingv2.html

and when creating a meeting from the above  URL  it shows the below error message.

![Screenshot 2022-09-01 at 5 03 40 PM](https://user-images.githubusercontent.com/64456962/188061599-8c56d582-5f90-4475-a4cb-f6745548cff4.png)

 Thanks
Siddharth Maheshwari

**Comment by pathakkrunal** [comment]
Hello,

I am also facing same issue please suggest the solution.

Thank you
Krunal Pathak

**Comment by michhyun1** [comment]
Why are you loading the html file?

You should be on the localhost server `http://127.0.0.1:8080/` in order to join a meeting.

If you want to join with a second attendee, just create a new tab at `http://127.0.0.1:8080` and use the same meeting id. 

What is it you are trying to do? Why do you need step 4 and 5? The demo app is already up and running by step 3. The `npm run start` script runs `npm run build` as part of the script.

**Comment by maheshwari-siddharth** [comment]
Hi Michhyun

you are right if we do http://127.0.0.1:8080/ it works fine and we are able to do meetings

but we wanted this to integrate into our application or domain to run as a client, for which we are using /environment/amazon-chime-sdk-js-main/demos/browser/dist/meetingv2.html.  (it throws an error message mentioned before)

again our objective is to run the application on our domain ec2 server as a client.


we are running steps 4 and 5 because till step 3 it is not running from URL: /environment/amazon-chime-sdk-js-main/demos/browser/dist/meetingv2.html. although it works from http://127.0.0.1:8080.

Thanks
Siddharth Maheshwari

**Comment by michhyun1** [comment]
Have you tried deploying the serverless demo? Once you deploy it serverlesssly, can you use the output url in your EC2 instance?

**Comment by maheshwari-siddharth** [comment]
Hi michhyun

we had deployed the serverless which gives us an output but that output is something like this https://cdgnf0d.execute-api.xx.yyyy.zzzz.amazonaws.com/Prod/  although it works fine, however, we wanted this URL to be mapped with our domain name in ec2 instance. 

As we need two applications where one is able to create and join the meeting and another is just able to join the meeting so we kept a serverless one for creating and joining a meeting and another one (browser one) is able to just join the meeting only.

from the browser application, the whole idea is we need a client application where the client is just able to join the meeting not to create a meeting.

from the serverless application, the whole idea is we need a where the user is able to create as well as join the meeting.


Thanks
Siddharth Maheshwari

Thanks
Siddharth Maheshwari

**Comment by michhyun1** [comment]
Why do you need two separate applications for this? Is it possible to just have a different route for each use case? Maybe you might want to re-use the same "in-meeting" experience between the meeting owner and the attendees - if not, you can have it all in one application in different routes

**Comment by maheshwari-siddharth** [comment]
Hi Michhyun

the reason we need two separate applications one is for owners who can create meetings and join meetings, and second, we need attendees who can just join the meetings(attendees must not be able to create meetings).

how this is possible in one application, if we give the same URL to the owner and attendees then attendees would be able to create meetings also that we don't want.

we are not sure about the routeing system and how this can help us.

Thanks
Siddharth Maheshwari

**Comment by xuesichao** [comment]
Hi @maheshwari-siddharth , 

Meeting creation is controlled by [`CreateMeeting`](https://docs.aws.amazon.com/chime-sdk/latest/APIReference/API_CreateMeeting.html) API.
Attendee joining is controlled by [`CreateAttendee`](https://docs.aws.amazon.com/chime-sdk/latest/APIReference/API_CreateAttendee.html) API.

In you application you could let owner have the access to both API call, and let attendee only have access to [`CreateAttendee`](https://docs.aws.amazon.com/chime-sdk/latest/APIReference/API_CreateAttendee.html) API call. So they are not able to create a meeting.

**Comment by maheshwari-siddharth** [comment]
Hi xuesichao

Noted.

I just wanted to reconfirm, that you are advising us we keep one URL for creating meeting API and one for creating Attendee API.

Or 

is it possible to keep one URL and differentiate between Owner and Attendee if yes how that is possible?

Thanks
Siddharth Maheshwari

**Comment by xuesichao** [comment]
@maheshwari-siddharth Now you have two apps, let's say:
* `http://owner-app.com`
* `http://attendee-app.com`

Instead of having two apps, you could have one app with two sub-routes.
* `http://app.com/owner` 
* `http://app.com/attendee`

I assume you have a button or something to join the meeting.

For owner page, the click event of join button is:
* Checking if meeting has been created, if not create the meeting via [CreateMeeting](https://docs.aws.amazon.com/chime-sdk/latest/APIReference/API_CreateMeeting.html) API, if so reuse the `MeetingId`. Either way you get [`MeetingId`](https://docs.aws.amazon.com/chime-sdk/latest/APIReference/API_Meeting.html#chimesdk-Type-Meeting-MeetingId).
* Creating attendee by calling [CreateAttendee](https://docs.aws.amazon.com/chime-sdk/latest/APIReference/API_CreateAttendee.html) for meeting with Id `MeetingId`.
* Joining the meeting

For attendee page, click event of join button is:
* Creating attendee by calling [CreateAttendee](https://docs.aws.amazon.com/chime-sdk/latest/APIReference/API_CreateAttendee.html) for `MeetingId`
* Joining meeting.
* Throw error if `MeetingId` does not exist or has been ended.

Components rendered after joining the meeting can be the same according to your use cases.

Let us know if anything is missing.

**Comment by maheshwari-siddharth** [comment]
Thanks, xuesichao

I think you explained everything more or less.

just one last question what is the purpose of a browser Demo is it only for localhost system testing or it has some other purpose?

Thanks
Siddharth Maheshwari

**Comment by pathakkrunal** [comment]
Hi @xuesichao 
How to configure bellow setting

Instead of having two apps, you could have one app with two sub-routes.

http://app.com/owner
http://app.com/attendee

Thank you.

**Comment by xuesichao** [comment]
@maheshwari-siddharth 
>just one last question what is the purpose of a browser Demo is it only for localhost system testing or it has some other purpose?

1. show case all features we support
2. serve as a implementation reference for builders
3. we test this demo to cover functionality

**Comment by xuesichao** [comment]
Hi @pathakkrunal , this is a question for web application development. It has nothing to do with our SDK.

>How to configure bellow setting
>
>Instead of having two apps, you could have one app with two sub-routes.
>
>http://app.com/owner
>http://app.com/attendee

This is just an example. It depends how you design the routing/router in your web application.
