### ISSUE TITLE
chooseVideoInputQuality not working on android

### ISSUE THREAD

**Issue by oNguyenTienManh** [aws/amazon-chime-sdk-js#2419]
### What happened and what did you expect to happen?

```
await meetingSession.audioVideo.chooseVideoInputQuality(256, 144, 15);
await meetingSession.audioVideo.setVideoMaxBandwidthKbps(180);
```
=> 140p not work
```
await meetingSession.audioVideo.chooseVideoInputQuality(427, 240, 15);
await meetingSession.audioVideo.setVideoMaxBandwidthKbps(270);
```
=> 240p not work
```
await meetingSession.audioVideo.chooseVideoInputQuality(640, 360, 15);
await meetingSession.audioVideo.setVideoMaxBandwidthKbps(350);
```
=> 360p not work
```
await meetingSession.audioVideo.chooseVideoInputQuality(960, 540, 24);
await meetingSession.audioVideo.setVideoMaxBandwidthKbps(1000);
```
=> 540p not work
```
await meetingSession.audioVideo.chooseVideoInputQuality(1280, 720, 24);
await meetingSession.audioVideo.setVideoMaxBandwidthKbps(1400);
```
=> 720p work

expect 140p, 240p, 360p, 540p work

### Have you reviewed our existing documentation?

- [X] GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [X] FAQs [page](https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html)
- [X] README [page](https://github.com/aws/amazon-chime-sdk-js#amazon-chime-sdk-for-javascript)
- [X] Feature-specific [guides](https://github.com/aws/amazon-chime-sdk-js#guides)

### Reproduction steps

use chrome on android

User A: live on android
User B: After letting others join to watch the live, the screen went black and didn't show up

### Amazon Chime SDK for JavaScript version

v2.29.0

### What browsers are you seeing the problem on?

chrome

### Browser version

chrome on android

### Browser console logs

log on 720p with other resolutions no difference

**Comment by michhyun1** [comment]
https://aws.github.io/amazon-chime-sdk-js/interfaces/devicecontroller.html#choosevideoinputquality

"These settings take effect the next time a video input device is chosen." 

Did you choose a new video input device after changing the Input quality?

**Comment by devalevenkatesh** [comment]
Hi @oNguyenTienManh , please let us know if you need any further help on this. As Michael mentioned, the chosen quality should be in effect once you re-choose the video input and start the video device.

**Comment by devalevenkatesh** [comment]
Resolving this as we could see no further updates. Feel free to re-open if still an issue or you have any questions.
