### ISSUE TITLE
Choppy audio with Web Audio on Windows

### ISSUE THREAD

**Issue by justindarc** [aws/amazon-chime-sdk-js#2420]
### What happened and what did you expect to happen?

When joining a call with Web Audio/Voice Focus enabled on Windows, audio may become choppy when running on battery power.

### Have you reviewed our existing documentation?

- [X] GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [X] FAQs [page](https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html)
- [X] README [page](https://github.com/aws/amazon-chime-sdk-js#amazon-chime-sdk-for-javascript)
- [X] Feature-specific [guides](https://github.com/aws/amazon-chime-sdk-js#guides)

### Reproduction steps

1. Be on a Windows laptop connected to AC power
2. Join a call with Chime SDK with Web Audio and Voice Focus enabled
3. After joining the call, disconnect AC power and run on battery power
4. Other meeting participants will begin receiving "choppy audio" from you

### Amazon Chime SDK for JavaScript version

3.2.0

### What browsers are you seeing the problem on?

Chrome, Edge, Electron

### Browser version

105

### Browser console logs

No evidence of issue in logs.

**Comment by michhyun1** [comment]
Can we close this issue? @justindarc

**Comment by justindarc** [comment]
Yes, this was fixed with #2421
