### ISSUE TITLE
What testing tools do you use to test chime video conferencing sdk on slow or poor network conditions

### ISSUE THREAD

**Issue by singulli1** [aws/amazon-chime-sdk-js#2430]
### What are you trying to do?

We've built a video conferencing application using amazon-chime-sdk.
There are several scenarios where the application needs to adjust to quality, bandwidth, and connectivity changes:

https://github.com/aws/amazon-chime-sdk-js/blob/main/guides/04_Quality_Bandwidth_Connectivity.md
"Just as responsive web design allows a single web application to adapt to changing screen sizes, the audio-video component of your application can also be responsive to changing device and network conditions."

However, it has been proven difficult to find tools to simulate various network conditions on windows, specifically because most testing tools in the browser restrict tcp traffic only and not udp traffic used by the webRTC for video traffic.

Was wondering what tools AWS uses to simulate various traffic conditions and if they have any recommendations on how to test applications built using the amazon-chime-sdk-js.  For example - I'd like to simulate a slow internet connection and watch the application's VideoPriorityBasedPolicy reduce bandwidth in the video downlink.

### How can the documentation be improved to help your use case?

*For example: Include a section on how to configure the meeting session.*

### What documentation have you looked at so far?

*For example: README.md, Amazon Chime SDK Developer Guide, etc.

**Comment by xuesichao** [comment]
Hi @singulli1, we use MacBook Pro for development. And there's a plugin called "Network Link Conditioner" on macOS. This plugin can simulate packet loss and network bandwidth. Usually we use this to do testing. I don't know if there's any tools on windows equivalent. 

We also use Chrome's network throttling sometimes.

**Comment by singulli1** [comment]
Thanks for the info :)
