### ISSUE TITLE
I would like to assign the name of the participant to the recording file

### ISSUE THREAD

**Issue by kodai305** [aws/amazon-chime-sdk-js#2432]
# Community Note
* Please vote for this issue by adding a 👍 reaction to the issue. This will help the community and maintainers from the Amazon Chime SDK team to prioritize this request.
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request.
* Please go through the existing [issues](https://github.com/aws/amazon-chime-sdk-js/issues) to see if your request has already been recommended.
* Please do not use this template for bugs or support. Each individual repository has a PR template, documentation and resources for [troubleshooting](https://github.com/aws/amazon-chime-sdk-js#troubleshooting-and-support).
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.

# Tell us about your request

I am not sure where to raise the issue, so I will write here as well.
https://github.com/aws-samples/amazon-chime-media-capture-pipeline-demo/issues/31

I would like to include information in the recording file that shows who is speaking.
For example, I would like to have a video with the name labeled on the Video.
Is there any way to achieve this?

## What do you want us to build?
Which Amazon Chime SDK or feature area is this request for?
Such as: [amazon-chime-sdk-js](https://github.com/aws/amazon-chime-sdk-js), [amazon-chime-sdk-ios](https://github.com/aws/amazon-chime-sdk-ios), [amazon-chime-sdk-android](https://github.com/aws/amazon-chime-sdk-android), [amazon-chime-sdk-component-library-react](https://github.com/aws/amazon-chime-sdk-component-library-react), a new feature idea.

## Tell us about the problem you are trying to solve and why is it hard?
The more details you provide us, the better we will be able to help you.

## How are you currently solving a problem?
Are there any workarounds or mitigations you have used? Why is it not working for you?

## Additional context
Anything else we should know?

**Comment by xuesichao** [comment]
Forward the information on other issue (https://github.com/aws-samples/amazon-chime-media-capture-pipeline-demo/issues/31) here:

>Since there is no attendee information such as attendee name(or AttendeeId) in the Video displayed in the recording file, it is impossible to distinguish who is who in which Video data.
I thought that if I specified SourceConfiguration, it would show AttendeeId, etc., but it did not behave as expected.
>
>Is there any solution?
>If possible, I would also like to provide information on who has Video turned off.

**Comment by tenge-amzn** [comment]
Our team is working on new features to enhance the functionality of the recording.
For now, this is not supported.
