### ISSUE TITLE
Creating a replica meeting returns the same MeetingId as the primary

### ISSUE THREAD

**Issue by kelvin2200** [aws/amazon-chime-sdk-js#2433]
### What are you trying to do?

*I am trying to implement replicated meetings*

### How can the documentation be improved to help your use case?

The indications at https://docs.aws.amazon.com/chime-sdk/latest/dg/media-replication.html

say that:

You use the [CreateMeeting](https://docs.aws.amazon.com/chime/latest/APIReference/API_meeting-chime_CreateMeeting.html) or [CreateMeetingWithAttendees](https://docs.aws.amazon.com/chime/latest/APIReference/API_meeting-chime_CreateMeetingWithAttendees.html) APIs to create WebRTC media sessions. By default, the APIs create a primary session unless you specifically create a replica session.

You create a replica session by specifying the MeetingId of the primary session as the PrimaryMeetingId in the CreateMeeting or CreateMeetingWithAttendees API call.

Note
If you specify the MeetingId of a replica session as the PrimaryMeetingId, the API call will fail.

I am trying to create a replica meeting like so:

```javascript
import {Endpoint, ChimeSDKMeetings} from "aws-sdk"; // v2.1214.0 (latest i believe)

const endpoint = new Endpoint("https://service.chime.aws.amazon.com/console");
const chime = new ChimeSDKMeetings({region: "us-east-1", endpoint});

// ...

const replicaMeetingInfo = await chime
    .createMeetingWithAttendees({
        PrimaryMeetingId: primaryMeetingId, // exists and obtained internally
        MediaRegion: "eu-central-1",
        Attendees: [{ExternalUserId: participantId}],
        ClientRequestToken: "a fixed db uuid",
        ExternalMeetingId: uuid(),
    })
    .promise();
```

The call succeeds but the `replicaMeetingInfo.Meeting.MeetingId` is the same one as `primaryMeetingId` and the docs don't specify whether that is correct or not. My guess is that it's not as per this note:
`If you specify the MeetingId of a replica session as the PrimaryMeetingId, the API call will fail.` so it stands to reason they should be different for each replica you create.
...also because I seem to be able to connect to that "replica" with the created attendee, and I am able to broadcast my video without the need to be promoted.

What am I doing wrong?
Please help

### What documentation have you looked at so far?

All docs found on aws related to replicated media

**Comment by kelvin2200** [comment]
is there ANY example of how to create a replica meeting? anywhere?

**Comment by devalevenkatesh** [comment]
Hello thanks for filling the issue. I tested the replica and primary meeting creation with below steps and was able to get different `MeetingId`. I used the `chime-sdk-meetings` chime client to create the meetings.

1. Create the primary meeting:
```
aws chime-sdk-meetings create-meeting --media-region us-east-1 --external-meeting-id venky-meeting
```

Response:
```
{
    "Meeting": {
        "MeetingId": "a29223ca-6f61-4c20-b965-b631671d2713",
        "ExternalMeetingId": "venky-meeting",
        "MediaRegion": "us-east-1",
        "MediaPlacement": {
            ...
        },
        "TenantIds": [],
        "MeetingArn": "..."
    }
}
```

2. Provided above `MeetingId: a29223ca-6f61-4c20-b965-b631671d2713` for creating the replica meeting:
```
aws chime-sdk-meetings create-meeting --media-region us-east-1 --external-meeting-id venky-meeting-replica --primary-meeting-id a29223ca-6f61-4c20-b965-b631671d2713
```

Response:
```
{
    "Meeting": {
        "MeetingId": "51103807-f4db-499d-81af-2c10f7c82713",
        "ExternalMeetingId": "venky-meeting-replica",
        "MediaRegion": "us-east-1",
        "MediaPlacement": {
            ...
        },
        "PrimaryMeetingId": "a29223ca-6f61-4c20-b965-b631671d2713",
        "TenantIds": [],
        "MeetingArn": "..."
    }
}
```

Thus, you can check that the primary and replica meeting are different. I believe in your example you provided, you are using incorrect endpoint with `ChimeSDKMeetings` it seems. The "https://service.chime.aws.amazon.com/console" is not correct and you can use "https://meetings-chime.us-east-1.amazonaws.com" instead.

Reference: https://docs.aws.amazon.com/chime-sdk/latest/dg/meeting-namespace-migration.html

You can refer the Amazon Chime SDK for JavaScript [browser demo server](https://github.com/aws/amazon-chime-sdk-js/blob/main/demos/browser/server.js) to check the primary/replica implementation.

Please let us know if making the endpoint change works or you are still having issues.

**Comment by kelvin2200** [comment]
Thank you for the reply, and I am sorry for the 2 separate issues but I filed the first under "documentation", and a bug report after further investigation, to make sure I was not doing anything wrong.

I understand it may work from the cli, but I'm using the javascript lib `aws-sdk`.
MOST IMPORTANT, before filing the second issue, I tried various calls to different endpoints, and the JSON in the second issue is the response from a request MADE to the regional endpoint,
**NOT** to `https://service.chime.aws.amazon.com/console"`

```typescript
import {ChimeSDKMeetings} from "aws-sdk";
const defaultChimeRegion = "us-east-1";
const chimeRegional = new ChimeSDKMeetings({region: defaultChimeRegion});
chimeRegional.endpoint = new Endpoint(`https://meetings-chime.${defaultChimeRegion}.amazonaws.com`);
const createReplicaMeetingPayload: CreateMeetingWithAttendeesRequest = {
        PrimaryMeetingId: primaryMeetingInfo.Meeting.MeetingId, // actually obtained from the DB but is the primaryMeeting created above
        MediaRegion: defaultChimeRegion,
        Attendees: [{ExternalUserId: participantId}],
        ClientRequestToken: sessionId
        ExternalMeetingId: uuid(),
};
const replicaMeetingInfo = await chimeRegional
    .createMeetingWithAttendees(createReplicaMeetingPayload)
    .promise();
```

Could there be something wrong in the `ChimeSDKMeetings` class in the `aws-sdk` lib? because the issue is still there. I am still getting back the primary meeting id whenever I create a replica.

Also tried to use the `createMeeting` (without attendees) but the result is the same. Am I missing any params in the payload? Am I providing some params that should not be there?

Furthermore, is there a javascript example (the most basic one) on how to implement replicated meetings?

**Comment by kelvin2200** [comment]
So... I was able to get it working by omitting the `ClientRequestToken` in the request payload, and now it is returning a different meeting id, but that param seems to be mandatory so there is definitely something either in the `aws-sdk` lib, or the endpoint processing the request.

However, attendees created for the replica still seem to have audio/video `SendReceive` capabilities. Is that the expected result?

**Comment by devalevenkatesh** [comment]
Glad you figured it out, so the CreateMeeting documentation mentions providing different `ClientRequestToken` for different meetings.

Reference: The unique identifier for the client request. Use a different token for different meetings.

Feel free to open new issues if have any additional questions, thanks again for your patience.
