### ISSUE TITLE
API Overview feedback

### ISSUE THREAD

**Issue by Aarondorn2** [aws/amazon-chime-sdk-js#245]
### What are you trying to do?

Understand the API Overview

### How can the documentation be improved to help your use case?

First off, this document is awesome!  I've learned a lot and will hopefully be able to avoid future debugging!  Thank you so much.  I had a few clarifying questions:

- Section 5 describes some cautions / edge cases around "Real Time Callbacks".  Do these same principles apply to the Audio Video observer methods in section 3?  I'm trying to understand the difference between observers in section 3 and "Real Time Callbacks". (#230?)
- Does AudioVideo.Stop() clean up associated things or should we do those manually (things like removing the Audio Video observer, unsubscribing from Real Time Callbacks, unbinding elements) (maybe #214)
- Possibly a topic of it's own: I'm not currently implementing it, but if I was, I would be interested in understanding the Active Speaker policy.  Does it change rapidly (are my tiles going to keep rearranging), is it averaged over some time period, does it filter background noise, etc.  These things are hard to develop against since they require multiple people speaking in a single meeting and you can't achieve that with a single developer.  The DefaultActiveSpeakerPolicy spec helps a little, but descriptions would be great. (maybe #229)
- Does screenshare (<attendee-id>#content) count toward the max tile count of 16?

Two other general questions:
- With all of the security concerns around Zoom, it would be nice to have an overview of the data flow for Chime, as well as implemented security along the way; I expect to have to describe this to my company executives.  I assumed audio went through AWS servers to be mixed, but video was direct peer-to-peer WebRTC, although section 7c mentioned the "server will not send paused video streams", so I am not so sure. (maybe #220)
- My application has an arbitrary limit of 8 tiles.  I noticed that when a participant disables their video (I'm using `audioVideo.stopLocalVideoTile()`), the next time they enable it (`audioVideo.startLocalVideoTile()`), they have a new tile number.  Am I going to max out at 16 even if there are only 3-4 actively sharing video?  Should I be pausing their video instead? (maybe #212)

### What documentation have you looked at so far?

API Overview, README, examples, specs, etc.

**Comment by aburnson** [comment]
Here are some brief answers to some these questions. We will integrate these into the documentation before closing this issue.

- The cautions around real-time callbacks do not apply to the observers. For example, uncaught exceptions are not fatal to observers (though they should be avoided).
- The stop() method does not clean up observers. You can start and stop a session multiple times using the same observers. In other words observers are not tied to the lifecycle of the session.
- DefaultActiveSpeakerPolicy algorithm works as follows: as you speak, your active speaker score rises and simultaneously decreases the score of others. There are some adjustable weightings in the constructor to control how reactive it is. In general, the defaults do a reasonable job of identifying the active speaker, preventing short noises or interjections from switching the active speaker, but also allowing take over to be relatively quick.
- Content share does not count towards the max video tile limit. There may be up to two content shares irrespective of how many attendees are sharing their camera.
- Security model: opened a separate issue #248 for this.
- A tileId is a unique identifier representing a video stream. When you stop and start, it generates a new tileId. You can have tileIds exceeding 16; they merely identify a particular stream uniquely. When you start video it consumes a video publishing slot, when you stop video it releases that video publishing slot. Pausing does not affect video publishing slots; it allows a remote to choose to not receive a video stream (and thus not consume bandwidth and CPU for that stream).

**Comment by aburnson** [comment]
As part of #248 #272, we added a link in the README to [Understanding Security in the Amazon Chime Application and SDK](https://aws.amazon.com/blogs/business-productivity/understanding-security-in-the-amazon-chime-application-and-sdk/).

**Comment by anuranduttaroy** [comment]
Added these comments into the documentation.
