### ISSUE TITLE
Get the current number of meeting attendees

### ISSUE THREAD

**Issue by AndrzejSala** [aws/amazon-chime-sdk-js#2456]
### What are you trying to do?

My app allows for conducting 1:1 meetings and I would like to inform the first person that the call partner is connected to the meeting or he should wait a little bit for him.
My initial idea is to get from SDK info about the number of meeting attendees and if it's equal to 2, inform users that the call is ready.

How can I get this information from SDK? I didn't find info about that in SDK docs.

**Comment by jitt3** [comment]
@AndrzejSala, if you want to know when a new participant joins the call, you can use:
`audioVideo.realtimeSubscribeToAttendeeIdPresence(callback);`

So that you can update the number of participants in the meeting and show the proper message to the participants that are already on the call

**Comment by devalevenkatesh** [comment]
Yup thanks @jitt3 for the response and you are correct. @AndrzejSala could you please follow below README section on this:
https://github.com/aws/amazon-chime-sdk-js#attendees

**Comment by devalevenkatesh** [comment]
Resolving this issue, feel free to re-open if you have more questions.
