### ISSUE TITLE
Custom Simulcast uplink policy

### ISSUE THREAD

**Issue by anjalithoke** [aws/amazon-chime-sdk-js#2459]
I am using VideoPriorityBasedPolicy and DefaultSimulcastUplinkPolicy. When I use DefaultSimulcastUplinkPolicy, I am facing issue while getting the video input. So, I am trying to create custom uplink policy.But, I couldn't see any example or documentation related to custom uplink policy. Can you please suggest documentation related to it which I can refer?

**Comment by pracheth** [comment]
Hi @anjalithoke Can we get some more information on what issue you are facing using the default simulcast uplink policy?

**Comment by anjalithoke** [comment]
Hello,
   Ubuntu system having issues if we use simulcast policies. Like chime app doesn't get the video source and local video tile gets blank when we use policies. So, do you have examples related custom policies? I couldn't found related to it into the documentation.
________________________________

**Comment by hensmi-amazon** [comment]
Do you have logs and a meeting ID that we can look at? Also what do you mean by 'chime app', do you mean an application using Chime SDK?

Ubuntu browser support can be finicky and not fully supported. I'd recommend creating `if` branches in your code to remove simulcast usage for that platform. `VideoPriorityBasedPolicy` still will have positive impact even without simulcast.

**Comment by hensmi-amazon** [comment]
Please reopen if responding. Though my recommendation is to not use simulcast on ubuntu. We do not recommend trying to override uplink policies.
