### ISSUE TITLE
EventBridge descriptions

### ISSUE THREAD

**Issue by maletor** [aws/amazon-chime-sdk-js#2460]
https://docs.aws.amazon.com/chime-sdk/latest/dg/using-events.html

I'm trying to figure out the difference between:

* Amazon Chime SDK attendee is added
* Amazon Chime SDK attendee is authorized
* Amazon Chime SDK attendee joins a meeting
* Amazon Chime SDK attendee leaves a meeting
* Amazon Chime SDK attendee drops a meeting

Can you have an attendee that is added (created with CreateAttendee?) but not authorized? 

Will the SDK allow you to authorize after instantiation of MeetingSessionConfiguration? 

What is the difference between authorized and joined?

Perhaps so media readiness checks can happen.

Are the last 3 only for VOIP?

**Comment by devalevenkatesh** [comment]
Hello @maletor ,

Closing this issue feel free to reopen if you still have any questions.
