### ISSUE TITLE
All participants dropped from an active meeting

### ISSUE THREAD

**Issue by brynrichards** [aws/amazon-chime-sdk-js#2462]
### What happened and what did you expect to happen?

During a chime meeting with our customers in production, all users lost the ability to hear each other and be heard, refreshing of the browser and attempting to rejoin the chime meeting did not resolve the issue.

The eventbridge events from indicate that all attendees were dropped at the same time - chime:AttendeeDropped  messages were received for all participants.

It appears from the browser logs that signalling control was lost also, with retry attempts to the websocket unsucessful (see logs).   

### Have you reviewed our existing documentation?

- [X] GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [X] FAQs [page](https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html)
- [X] README [page](https://github.com/aws/amazon-chime-sdk-js#amazon-chime-sdk-for-javascript)
- [X] Feature-specific [guides](https://github.com/aws/amazon-chime-sdk-js#guides)

### Reproduction steps

Unknown, we have never seen this issue before.

### Amazon Chime SDK for JavaScript version

2.31.0

### What browsers are you seeing the problem on?

various

### Browser version

chrome 103

### Meeting and Attendee ID Information.

Meeting ID dea45c2e-7e4e-4a5e-b8c7-5c3aa8ab0706

Attendee IDs:
0b3d085f-ffca-210e-5b97-d70c7e6f40fa
edfae29c-7f64-4c5f-8ce3-16a524228977
aeb1316d-7af6-07d8-11e2-82c4c622e1a5
03a69304-84f2-7de3-d6d7-cfaa68555321
e8e177fd-a318-1bcf-4d37-a11d485321cc

Media and signalling region us-east-1

### Browser console logs

[chime-audio-dropped-log.txt](https://github.com/aws/amazon-chime-sdk-js/files/9684564/chime-audio-dropped-log.txt)

**Comment by pracheth** [comment]
Hi @brynrichards. Apologies for the experience. We discovered that this was caused by a server being wrongfully terminated due to a bug. The fix for the issue that affected the call above has been deployed through our pipeline.
