### ISSUE TITLE
Incorrect shared content video chunks are generated for shared screen in Media Capture Pipeline

### ISSUE THREAD

**Issue by yoshitsugu** [aws/amazon-chime-sdk-js#2465]
### What happened and what did you expect to happen?

I've created similar issue as #1943 
I found that sometimes shared screen video chunks have long durations (like 8 seconds)

### Have you reviewed our existing documentation?

- [X] GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [X] FAQs [page](https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html)
- [X] README [page](https://github.com/aws/amazon-chime-sdk-js#amazon-chime-sdk-for-javascript)
- [X] Feature-specific [guides](https://github.com/aws/amazon-chime-sdk-js#guides)

### Reproduction steps

Sorry but I cannot find out the reproduction step now.
Maybe sharing screen for a long time causes a issue, but I'm not sure.

### Amazon Chime SDK for JavaScript version

3.8.0

### What browsers are you seeing the problem on?

Chrome

### Browser version

106.0.5249.91

### Browser console logs

N / A

**Comment by MingcongQi** [comment]
could you share the meeting id and pipeline id. it will be better if you could share the content share chunks

**Comment by yoshitsugu** [comment]
@MingcongQi Thank you for replying.
Sorry but it was private meeting so I cannot share the chunk file here directly.
meeting_id : `061152bb-a6f3-4a2b-90ff-668654680706`  media_pipeline_id: `2b4094de-d476-4b2f-abeb-c38e92293a02`

**Comment by MingcongQi** [comment]
could you share the files name which have long durations

**Comment by yoshitsugu** [comment]
@MingcongQi the sample file name is `2022-09-14-04-03-23-241-4a1118de-ee29-e103-1db1-10239710d21d%23content.mp4`

**Comment by MingcongQi** [comment]
Sorry for the late reply. We did some modifications since last year. Did you still see the issue in your side? if it still exists, could you help share new media pipeline id, file name for us, thanks!

**Comment by yoshitsugu** [comment]
Thank you for your reply. We will be watching whether the problem still exists for a while.
By the way, I have left the project so  @bubweiser or @okayumoka will report the problem if we still have it.
I'll close the issue for now. thank you again.
