### ISSUE TITLE
Document Supported Browser Check

### ISSUE THREAD

**Issue by Aarondorn2** [aws/amazon-chime-sdk-js#247]
### What are you trying to do?
I am trying to display a message to the user when their browser is not supported.

### How can the documentation be improved to help your use case?
What is the recommended way to check browser support?  I'm currently checking that the browser supports webRTC (RTCPeerConnection, webkitRTCPeerConnection, mozRTCPeerConnection, RTCIceGatherer), but this is not comprehensive.  Some earlier versions of Edge pass this check but are still not supported.
In the API docs, I noticed there is a DefaultBrowserBehavior class with an isSupported() method; This isn't used in the demo - is this what I should be using?

### What documentation have you looked at so far?
README.md, Amazon Chime SDK Developer Guide, Getting Started, API Overview, code demos, API docs, etc.

**Comment by aburnson** [comment]
Yes, use the [DefaultBrowserBehavior.isSupported()](https://aws.github.io/amazon-chime-sdk-js/classes/defaultbrowserbehavior.html#issupported) method to check whether the browser is supported. To get a readable string of browsers that are supported use [DefaultBrowserBehavior.supportString()](https://aws.github.io/amazon-chime-sdk-js/classes/defaultbrowserbehavior.html#supportstring).

Agreed this should be in the documentation; leaving issue open until we find a place for this to live.

**Comment by Aarondorn2** [comment]
Is it intentional that Crios (Chrome iOS) isn't supported?  I expected it to be, although re-reading the support string looks like it is explicitly not.  Here's the browser info from DefaultBrowserBehavior:
`{
   "hasChromiumWebRTC":false,
   "hasFirefoxWebRTC":false,
   "isSupported":false,
   "majorVersion":80,
   "name":"crios",
   "requiresBundlePolicy":"balanced",
   "requiresCheckForSdpConnectionAttributes":true,
   "requiresIceCandidateGatheringTimeoutWorkaround":false,
   "requiresPromiseBasedWebRTCGetStats":true,
   "requiresUnifiedPlan":false,
   "screenShareSendsOnlyKeyframes":false,
   "screenShareUnsupported":false,
   "version":"80.0.3987"
}`

**Comment by Aarondorn2** [comment]
same with firefox on iOS (Safari seems to be the only one supported):

```
{
   "hasChromiumWebRTC":false,
   "hasFirefoxWebRTC":false,
   "isSupported":false,
   "majorVersion":24,
   "name":"fxios",
   "requiresBundlePolicy":"balanced",
   "requiresCheckForSdpConnectionAttributes":true,
   "requiresIceCandidateGatheringTimeoutWorkaround":false,
   "requiresPromiseBasedWebRTCGetStats":true,
   "requiresUnifiedPlan":false,
   "screenShareSendsOnlyKeyframes":false,
   "screenShareUnsupported":false,
   "version":"24.1.0"
}
```

**Comment by vidya-mohan** [comment]
Hello @Aarondorn2 - yes we current do not support the JS SDK on mobile browsers such as Crios or Firefox/iOS. You can find the full list: https://docs.aws.amazon.com/chime/latest/dg/meetings-sdk.html#mtg-browsers

**Comment by Aarondorn2** [comment]
Thank you @vidya-mohan .  From that link, it looks like all mobile browsers are not supported.  Are there plans to add support? 

Previous versions of this SDK worked on most mobile browsers.

**Comment by vidya-mohan** [comment]
@Aarondorn2 we do have plans to add support for mobile browsers in our roadmap. https://docs.aws.amazon.com/chime/latest/dg/meetings-sdk.html#mtg-browsers tracks our current documentation and is also available from the Readme so let me know if you have the information you needed at present

**Comment by vidya-mohan** [comment]
We updated our ReadMe to point to the documentation as well so resolving it. Please reactivate if theres a pending action
