### ISSUE TITLE
adding recording feature to our chime sdk meeting project

### ISSUE THREAD

**Issue by jaeho0522** [aws/amazon-chime-sdk-js#2479]
I have found amazon-chime-sdk-recording-demo project and read through README file.
The demo deploys amazon-chime-sdk-js and pass the url to recording demo as meetingURL.

We have a chime sdk meeting project where I want to add a toggle button to start and stop recording the meeting session.
Our meeting project is not being deployed as this demo, 
what would be the meetingURL to pass to start the recording?

Please excuse if my question is too basic.

Thanks in advance.

**Comment by devalevenkatesh** [comment]
Thanks for reporting the question. I have labelled the appropriate team to help.

I believe the demo you are referring is now an outdated one and Amazon Chime SDK added media capture functional a while back. Suggest checking the JS SDKs meeting demo. It does similar recording based on a button toggle.
- https://github.com/aws/amazon-chime-sdk-js/tree/main/demos/browser
- https://aws.amazon.com/blogs/business-productivity/capture-amazon-chime-sdk-meetings-using-media-capture-pipelines/

Above links will help. Please let us know if you have further questions.

**Comment by jaeho0522** [comment]
Thanks for your help.
I was able to start and stop recording.
But i am having trouble with concatenating chunked video files with below error.
I am including 1) error message 2) role policy 3) lambda source

What is the problem and how can I correct it?

Thanks in advance.

-----------------------------------------------------------------------------------------------------
1) error message
ERROR	Invoke Error 	
{
    "errorType": "TypeError",
    "errorMessage": "chime.createMediaConcatenationPipeline is not a function",
    "stack": [
        "TypeError: chime.createMediaConcatenationPipeline is not a function",
        "    at Runtime.exports.handler (/var/task/index.js:79:40)",
        "    at processTicksAndRejections (internal/process/task_queues.js:95:5)"
    ]
}
-----------------------------------------------------------------------------------------------------

2) role policy
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "VisualEditor0",
            "Effect": "Allow",
            "Action": [
                "logs:CreateLogStream",
                "dynamodb:GetItem",
                "logs:PutLogEvents",
                "s3:GetBucketPolicy"
            ],
            "Resource": [
                "arn:aws:dynamodb:*:773892688251:table/*",
                "arn:aws:logs:ap-southeast-1:773892688251:log-group:/aws/lambda/singapore-env-korean-chime-capture-media:*",
                "arn:aws:s3:::*"
            ]
        },
        {
            "Sid": "VisualEditor1",
            "Effect": "Allow",
            "Action": "logs:CreateLogGroup",
            "Resource": "arn:aws:logs:ap-southeast-1:773892688251:*"
        },
        {
            "Sid": "VisualEditor2",
            "Effect": "Allow",
            "Action": [
                "chime:DeleteMediaCapturePipeline",
                "chime:CreateMediaConcatenationPipeline",
                "chime:CreateMediaCapturePipeline",
                "sts:GetCallerIdentity"
            ],
            "Resource": "*"
        }
    ]
}

-----------------------------------------------------------------------------------------------------
3) aws lambda handler👇
-----------------------------------------------------------------------------------------------------
const AWS = require('aws-sdk');
var ddb = new AWS.DynamoDB();

const chime = new AWS.Chime({ region: 'us-east-1' });
const sts = new AWS.STS({ region: 'us-east-1' });
const meetingTable = {};

const {
  MEETINGS_TABLE_NAME,
  CAPTURE_S3_DESTINATION,
  CONCAT_BUCKET_ARN,
} = process.env;

exports.handler = async(event) => {
    if (!CAPTURE_S3_DESTINATION) {
      console.warn("Cloud media capture not available");
      return response(500, 'application/json', JSON.stringify({}));
    }
    console.log(event.path);
    console.log(event['detail-type']);
    console.log(JSON.stringify(event));
    const query = event.queryStringParameters;
    let action;
    if(query && query.action) {
      console.log("action: " + query.action);
      action = query.action;
    }
   
    // start recording
    if (action == 'start'){
      let meeting = await getMeeting(query.title);
      if (!meeting) {
        return response(404, 'application/json', JSON.stringify({message: 'Meeting not found.'}));
      }
      const callerInfo = await sts.getCallerIdentity().promise();
      console.log("callerInfo: " + callerInfo.Account);
      console.log(`arn:aws:chime::${callerInfo.Account}:meeting:${meeting.Meeting.MeetingId}`);
      const pipelineInfo = await chime.createMediaCapturePipeline({
        SourceType: "ChimeSdkMeeting",
        SourceArn: `arn:aws:chime::${callerInfo.Account}:meeting:${meeting.Meeting.MeetingId}`,
        SinkType: "S3Bucket",
        SinkArn: CAPTURE_S3_DESTINATION,
        "ChimeSdkMeetingConfiguration": {
          "ArtifactsConfiguration": {
              "Audio": {
                  "MuxType": "AudioWithActiveSpeakerVideo"
              },
              "Video": {
                  "State": "Enabled",
                  "MuxType": "VideoOnly"
              },
              "Content": {
                  "State": "Disabled",
                  "MuxType": "ContentOnly"
              },
          }
      }
      }).promise();
      console.log(JSON.stringify(pipelineInfo));
      meetingTable[query.title] = pipelineInfo.MediaCapturePipeline;
      return response(201, 'application/json', JSON.stringify(pipelineInfo));
    }
    // end recording
    else if (action == 'end') {
      const pipelineInfo = meetingTable[query.title];
      console.log(JSON.stringify(pipelineInfo));
      await chime.deleteMediaCapturePipeline({
        MediaPipelineId: pipelineInfo.MediaPipelineId
      }).promise();
      meetingTable[query.title] = undefined;
      return response(200, 'application/json', JSON.stringify({}));    
    }
    // concatenate recording files
    else if (action == 'concat') {
      let meeting = await getMeeting(query.title);
      if (!meeting) {
        return response(404, 'application/json', JSON.stringify({message: 'Meeting not found.'}));
      }
      const pipelineInfo = await chime.createMediaConcatenationPipeline({
        Sinks: [
          {
            S3BucketSinkConfiguration: { Destination: CONCAT_BUCKET_ARN },
            Type: 'S3Bucket',
          },
        ],
        Sources: [
          {
            MediaCapturePipelineSourceConfiguration: {
              ChimeSdkMeetingConfiguration: {
                ArtifactsConfiguration: {
                  Audio: { State: 'Enabled' },
                  CompositedVideo: { State: 'Enabled' },
                  Content: { State: 'Disabled' },
                  DataChannel: { State: 'Enabled' },
                  MeetingEvents: { State: 'Enabled' },
                  TranscriptionMessages: { State: 'Enabled' },
                  Video: { State: 'Disabled' },
                },
              },
              MediaPipelineArn: meetingTable[query.title].MediaPipelineArn,
            },
            Type: 'MediaCapturePipeline',
          },
        ],
      }).promise();
      console.log(JSON.stringify(pipelineInfo));
    }else {
      return response(404, 'text/html', '404 Not Found');
    }
   
};

// Retrieves the meeting from the table by the meeting title
async function getMeeting(title) {
  const result = await ddb.getItem({
   
    TableName: MEETINGS_TABLE_NAME,
    Key: {
      'Title': {
        S: title
      },
    },
  }).promise();
  return result.Item ? JSON.parse(result.Item.Data.S) : null;
}

function response(statusCode, contentType, body) {
  return {
    statusCode: statusCode,
    headers: { 'Content-Type': contentType, 'Access-Control-Allow-Origin': '*' },
    body: body
  };
}
------------------------------------------------------------------------------------

**Comment by tenge-amzn** [comment]
```
const chime = new AWS.Chime({ region: 'us-east-1' });
```

This namespace does not support concatenation. You need ChimeSDKMediaPipelines namespace.
https://docs.aws.amazon.com/chime-sdk/latest/dg/migrate-pipelines.html
