### ISSUE TITLE
Disconnecting PSTN call from conference does not work

### ISSUE THREAD

**Issue by LukasSmrcka** [aws/amazon-chime-sdk-js#2482]
### What happened and what did you expect to happen?

Assume the scenario when you have connected a PSTN usere to the video conference through voice connector. When PSTN user  hangs up the call then other participants see his/her attendee object stuck in the conference. The attendee object of the PSTN user is removed only after inactivity timeout (5 mins from the real hang up or so).  

When the PSTN user leaves the conference by ending his phone call and the related attendee object is still stuck there then any new participant that join the conference still see the stuck attendee object. This points at some AWS Chime backend issue

It is also possible to observe in voice connector logs SIP BYE message when PSTN attendee is hangs up and after that 200 OK from the voice connector

### Have you reviewed our existing documentation?

- [X] GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [X] FAQs [page](https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html)
- [X] README [page](https://github.com/aws/amazon-chime-sdk-js#amazon-chime-sdk-for-javascript)
- [X] Feature-specific [guides](https://github.com/aws/amazon-chime-sdk-js#guides)

### Reproduction steps

1. Create a vide conference with any number of attendees
2. Dial in with PSTN user through voice connector
3. Hang up the call
4. Observe the stuck attendee

### Amazon Chime SDK for JavaScript version

3.6.0

### What browsers are you seeing the problem on?

Any

### Browser version

Any

### Meeting and Attendee ID Information.

chime-meeting-id: 172ea7a0-38f6-440f-947a-28060cb52713

### Browser console logs

Even with enabled debug for chime SDK logs there was no sign that the attendee left

**Comment by devalevenkatesh** [comment]
This issue is not related to Amazon Chime SDK for JavaScript.

I suggest reaching out to AWS support so that the ticket is routed correctly. Meanwhile, suggest checking whether you:
1. Have a PSTN lambda handling and sending Hangup action to disconnect other attendee from the call?
2. I believe the lambda should handle hangup and implicitly it wont be done. I may be wrong though.

https://docs.aws.amazon.com/chime-sdk/latest/dg/hangup.html
