### ISSUE TITLE
Webhook for attendee presence status

### ISSUE THREAD

**Issue by kelvin2200** [aws/amazon-chime-sdk-js#2488]
### What happened and what did you expect to happen?

I was wondering if there's a sort of mechanism (preferably a webhook) that would call a specific URL on our backend telling us when a user joined a meeting, dropped or left.

I know we can subscribe each individual attendee to `audioVideo.realtimeSubscribeToAttendeeIdPresence`, the problem is we have to execute a DB update for events like `joined/left/dropped`.

One way of doing it would be by adding a `shadow` attendee via some headless chromium/puppeteer, that catches all these events and performs the necessary updates, but that is soooo much overhead.

If there are no webhooks, is there something else we could use to get that information realtime?

### Have you reviewed our existing documentation?

- [X] GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [X] FAQs [page](https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html)
- [X] README [page](https://github.com/aws/amazon-chime-sdk-js#amazon-chime-sdk-for-javascript)
- [X] Feature-specific [guides](https://github.com/aws/amazon-chime-sdk-js#guides)

### Reproduction steps

none

### Amazon Chime SDK for JavaScript version

latest

### What browsers are you seeing the problem on?

all

### Browser version

all

### Browser console logs

none needed

**Comment by devalevenkatesh** [comment]
Thanks @kelvin2200 for reporting this issue. Amazon Chime SDK publishes server side meeting events such as `chime:AttendeeLeft`, `chime:AttendeeJoined` and so on.

Could you please below links and let us know if you have any further questions:
1. https://docs.aws.amazon.com/chime-sdk/latest/dg/mtgs-sdk-notifications.html
2. https://docs.aws.amazon.com/chime-sdk/latest/dg/using-events.html

**Comment by kelvin2200** [comment]
Thank you for your reply @devalevenkatesh.
I did stumble upon the second link in my research, never got to the first.

I guess we try that and see if it meets our needs.
Just as a sidenote, and I'm not complaining but that whole EventBridge seems soooo much overhead for something as simple as a webhook mechanism of what we need. Not to mention the latency it adds... but, we'll make do.
Again, thank you very much, and I will keep this thread updated once we get it working. It may serve as a guideline for other users needing this.

**Comment by hensmi-amazon** [comment]
Closing due to age
