### ISSUE TITLE
Meeting becomes unresponsive after sometime.

### ISSUE THREAD

**Issue by Yadukrish** [aws/amazon-chime-sdk-js#2493]
### What happened and what did you expect to happen?

Suddenly an ongoing meeting freezes, becomes un responsive, not able to hear audio or not able to turn on video and not receiving volume/mute/unmute/active speaker state.
Getting this error log from sdk.
<img width="620" alt="image" src="https://user-images.githubusercontent.com/40061489/200489212-51edf521-f029-40cf-9c30-6f3d231499d3.png">

### Have you reviewed our existing documentation?

- [X] GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [X] FAQs [page](https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html)
- [X] README [page](https://github.com/aws/amazon-chime-sdk-js#amazon-chime-sdk-for-javascript)
- [X] Feature-specific [guides](https://github.com/aws/amazon-chime-sdk-js#guides)

### Reproduction steps

* Start a meeting with multiple attendees
* After sometime issue appears

### Amazon Chime SDK for JavaScript version

3.8.0

### What browsers are you seeing the problem on?

Chrome

### Browser version

Version 107.0.5304.88 (Official Build) (64-bit)

### Browser console logs

VM598 react_devtools_backend.js:4026 2022-11-08T06:04:21.865Z [ERROR] ChimeMeetingLogs - realtime error: TypeError: Cannot set properties of undefined (setting 'callStatus'): TypeError: Cannot set properties of undefined (setting 'callStatus')
overrideMethod @ VM598 react_devtools_backend.js:4026
VM598 react_devtools_backend.js:4026 2022-11-08T06:04:21.870Z [ERROR] ChimeMeetingLogs - session will not be reconnected
overrideMethod @ VM598 react_devtools_backend.js:4026
VM598 react_devtools_backend.js:4026 2022-11-08T06:04:21.873Z [ERROR] ChimeMeetingLogs - failed with status code RealtimeApiFailed and error: Cannot set properties of undefined (setting 'callStatus')
overrideMethod @ VM598 react_devtools_backend.js:4026

**Comment by devalevenkatesh** [comment]
Thanks @Yadukrish for reporting the issue. The `RealtimeApiFailed` error is a terminal one and will be thrown due to a runtime error occurred in your provided callback.
```
Cannot set properties of undefined (setting 'callStatus')
```

This above error is coming from your callback provided to Amazon Chime SDK for JavaScript realtime callback. If mid meeting, the `RealtimeApiFailed` error is thrown that means your code ran into an issue, after this error, the meeting will be disconnected completely and wont be retried.

You would need to check your callback and fix the runtime error.

**Comment by Yadukrish** [comment]
Thanks @devalevenkatesh . I have searched my whole code and sdk repo for any codes with "callStatus", not able to find any. Can you share any info about where this issue can occur in code, or which callback to change. @devalevenkatesh

**Comment by devalevenkatesh** [comment]
Can you provide snippets where you use JS SDK realtime APIs.

The APIs will be any from mentioned in the RealtimeController facade:

https://github.com/aws/amazon-chime-sdk-js/blob/main/src/realtimecontroller/RealtimeControllerFacade.ts

**Comment by Yadukrish** [comment]
Thanks for the assistance, issue resolved.
