### ISSUE TITLE
Meeting Error Status Codes, their root cause and whether they are retriable

### ISSUE THREAD

**Issue by sskrishnaswamy** [aws/amazon-chime-sdk-js#2497]
We are using amazon-chime-sdk-js v2.30.0 in our Angular application. We are capturing the Meeting Error Status Codes when the meeting fails and we have a requirement to display a proper user-friendly error messages to the end users which will enable them to take the remedial action. We are unable to understand the root cause for some of the Meeting Error Status codes and if they are fatal or retriable errors. 

Meeting Error Status Codes:

1. AudioAuthenticationRejected
2. AudioDisconnectAudio
3. AudioDisconnected
4. AudioInternalServerError
5. AudioServiceUnavailable
6. AudioVideoWasRemovedFromPrimaryMeeting
7. ICEGatheringTimeoutWorkaround
8. IncompatibleSDP
9. RealtimeApiFailed
10. SignalingInternalServerError
11. SignalingRequestFailed
12. SignalingBadRequest
13. TaskFailed
14. ConnectionHealthReconnect
15. NoAttendeePresent

Can you please provide the root cause / explanation of the scenario in which these errors may occur?

**Comment by LeviSklaroff** [comment]
Documentation on these error codes can be found here https://aws.github.io/amazon-chime-sdk-js/enums/meetingsessionstatuscode.html with details on what went wrong.

**Comment by sskrishnaswamy** [comment]
@LeviSklaroff We have gone through the above mentioned documentation already, but the explanation given was not clear enough. Can you please provide more clarity on the root cause and mention if these errors are retriable or fatal? It will be helpful if the clarity of the documentation is improved.

**Comment by yochum** [comment]
Hi @sskrishnaswamy - Thanks for your feedback. We are preparing updated docs that should help to clarify the topics you've raised. We will be in touch with you.

**Comment by yochum** [comment]
Hi @sskrishnaswamy - We've published an update to the documentation for `MeetingSessionStatus` codes that you will find here. This includes an intro outlining general usage, details for each status code and how to use the `MeetingSessionStatus.isTerminal` value: https://aws.github.io/amazon-chime-sdk-js/enums/meetingsessionstatuscode.html

Related is an update to the FAQ entry to how to handle `audioVideoDidStop` events:
https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html#what-should-my-application-do-in-response-to-the-status-codes-in-audiovideodidstop

You may browse a few other related changes to identify sources of such status codes in the commit merged here:
https://github.com/aws/amazon-chime-sdk-js/commit/8327f36d3a70d57b3d3f2a19f53c250bd423a9ec

**Comment by albrich-me** [comment]
In the case notes there is also a .pdf which seems to address their concerns directly.

**Comment by ltrung** [comment]
Close the issue for now. Feel free to reopen or create a new issue if you have other issues.
