### ISSUE TITLE
ScreenShare does not work in Safari 16.2

### ISSUE THREAD

**Issue by blueguava** [aws/amazon-chime-sdk-js#2508]
### What happened and what did you expect to happen?

On-screen share, Safari does not let the user decide which screen/tab to display but shares the current one directly. It worked before!
https://www.dropbox.com/s/a5ky2fihgbqs6a0/Screen%20Recording%202022-12-01%20at%2013.12.58.mov?dl=0

### Have you reviewed our existing documentation?

- [X] GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [X] FAQs [page](https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html)
- [X] README [page](https://github.com/aws/amazon-chime-sdk-js#amazon-chime-sdk-for-javascript)
- [X] Feature-specific [guides](https://github.com/aws/amazon-chime-sdk-js#guides)

### Reproduction steps

Try to share the content on Safari, and the expected popup is not coming.

I reproduced it here too.

https://52wbup79vd.execute-api.us-east-1.amazonaws.com/Prod/?m=Blue+Guava#

### Amazon Chime SDK for JavaScript version

amazon-chime-sdk-component-library-react: 3.2.0, amazon-chime-sdk-js: 3.5.0

### What browsers are you seeing the problem on?

Safari

### Browser version

16.2

### Browser console logs

N/A

**Comment by akshay-prabhu-github** [comment]
As of today, safari does not support a screen picker as part of their webrtc support. They only allow to share the displays. They do not support screen sharing of windows or application. 

Reference: https://bugs.webkit.org/show_bug.cgi?id=186294
```
Eric Carlson 2018-06-05 13:50:37 PDT

getDisplayMedia is implemented (for displays only, not window, or application) on macOS behind the ScreenCapture runtime flag (off by default).
```
