### ISSUE TITLE
Unable to use Screenshare

### ISSUE THREAD

**Issue by newclouds** [aws/amazon-chime-sdk-js#252]
we have downloaded this package and tested.
Screen share was creating duplicate windows. we are unable to use this feature to implement the same in our applications.
with the downloaded package code same issue is exist and also tested it in our application as well
Can you please help us to complete it.

Please refer the attached screen

![image](https://user-images.githubusercontent.com/18283896/78644141-0ffea280-78d3-11ea-9ac4-ec381ac88ff0.png)

**Comment by ltrung** [comment]
Sorry, could you clarify what you issue you run into? From the screenshot it looks like you share your current screen.

**Comment by newclouds** [comment]
![image](https://user-images.githubusercontent.com/18283896/78850389-b4e4c100-7a34-11ea-80b2-18c014966244.png)

In the attached screen shot we are getting duplicate windows, inside screen share video another screens are coming.
Thanks

**Comment by simmkyu** [comment]
It seems that you have shared your entire screen that will include the demo page itself and the bottom bar. Chime SDK relies on a browser's screen share API, so it cannot exclude the bottom bar from the shared screen. Instead, try sharing a specific window e.g. "Application Window" in the Chrome screen picker dialog.

![chrome-picker](https://user-images.githubusercontent.com/36240708/78946466-a53a9c00-7a77-11ea-881d-9395204f27fa.jpg)

**Comment by newclouds** [comment]
If i want to share entire screen instead of single app, is there any possibility?

**Comment by simmkyu** [comment]
I think you can add an external monitor to your computer and choose it in the browser's screen picker. If you choose your primary screen, the screen share will include the taskbar (Windows) and the dock (macOS).

**Comment by simmkyu** [comment]
Please reopen if you still encounter the issue when sharing an external monitor.

**Comment by senthilnathan27** [comment]
> I think you can add an external monitor to your computer and choose it in the browser's screen picker. If you choose your primary screen, the screen share will include the taskbar (Windows) and the dock (macOS).

do you have another solution for it?
