### ISSUE TITLE
createMediaConcatenationPipeline error

### ISSUE THREAD

**Issue by jaeho0522** [aws/amazon-chime-sdk-js#2525]
I having problem concatenating video chunk files.

I looked at below document and demo project and followed video recording.
https://github.com/aws/amazon-chime-sdk-js/tree/main/demos/browser
https://aws.amazon.com/blogs/business-productivity/capture-amazon-chime-sdk-meetings-using-media-capture-pipelines/

But when I tried to concatenate recorded video chunk files,
I get following error message

1. error message
ERROR Invoke Error
{
"errorType": "TypeError",
"errorMessage": "chime.createMediaConcatenationPipeline is not a function",
"stack": [
"TypeError: chime.createMediaConcatenationPipeline is not a function",
" at Runtime.exports.handler (/var/task/index.js:79:40)",
" at processTicksAndRejections (internal/process/task_queues.js:95:5)"
]
}

-----------------

Here is my source code for begin recording, stop recording and concatenating video files.

Please help.

Thanks in advance.

------------------
2. role policy
{
"Version": "2012-10-17",
"Statement": [
{
"Sid": "VisualEditor0",
"Effect": "Allow",
"Action": [
"logs:CreateLogStream",
"dynamodb:GetItem",
"logs:PutLogEvents",
"s3:GetBucketPolicy"
],
"Resource": [
"arn:aws:dynamodb::773892688251:table/",
"arn:aws:logs:ap-southeast-1:773892688251:log-group:/aws/lambda/singapore-env-korean-chime-capture-media:",
"arn:aws:s3:::"
]
},
{
"Sid": "VisualEditor1",
"Effect": "Allow",
"Action": "logs:CreateLogGroup",
"Resource": "arn:aws:logs:ap-southeast-1:773892688251:"
},
{
"Sid": "VisualEditor2",
"Effect": "Allow",
"Action": [
"chime:DeleteMediaCapturePipeline",
"chime:CreateMediaConcatenationPipeline",
"chime:CreateMediaCapturePipeline",
"sts:GetCallerIdentity"
],
"Resource": ""
}
]
}

-----------------
3. aws lambda handler

Thanks for your help.
I was able to start and stop recording.
But i am having trouble with concatenating chunked video files with below error.
I am including 1) error message 2) role policy 3) lambda source

What is the problem and how can I correct it?

Thanks in advance.

error message
ERROR Invoke Error
{
"errorType": "TypeError",
"errorMessage": "chime.createMediaConcatenationPipeline is not a function",
"stack": [
"TypeError: chime.createMediaConcatenationPipeline is not a function",
" at Runtime.exports.handler (/var/task/index.js:79:40)",
" at processTicksAndRejections (internal/process/task_queues.js:95:5)"
]
}
role policy
{
"Version": "2012-10-17",
"Statement": [
{
"Sid": "VisualEditor0",
"Effect": "Allow",
"Action": [
"logs:CreateLogStream",
"dynamodb:GetItem",
"logs:PutLogEvents",
"s3:GetBucketPolicy"
],
"Resource": [
"arn:aws:dynamodb::773892688251:table/",
"arn:aws:logs:ap-southeast-1:773892688251:log-group:/aws/lambda/singapore-env-korean-chime-capture-media:",
"arn:aws:s3:::"
]
},
{
"Sid": "VisualEditor1",
"Effect": "Allow",
"Action": "logs:CreateLogGroup",
"Resource": "arn:aws:logs:ap-southeast-1:773892688251:"
},
{
"Sid": "VisualEditor2",
"Effect": "Allow",
"Action": [
"chime:DeleteMediaCapturePipeline",
"chime:CreateMediaConcatenationPipeline",
"chime:CreateMediaCapturePipeline",
"sts:GetCallerIdentity"
],
"Resource": ""
}
]
}
aws lambda handler👇
const AWS = require('aws-sdk');
var ddb = new AWS.DynamoDB();

const chime = new AWS.Chime({ region: 'us-east-1' });
const sts = new AWS.STS({ region: 'us-east-1' });
const meetingTable = {};

const {
MEETINGS_TABLE_NAME,
CAPTURE_S3_DESTINATION,
CONCAT_BUCKET_ARN,
} = process.env;

exports.handler = async(event) => {
if (!CAPTURE_S3_DESTINATION) {
console.warn("Cloud media capture not available");
return response(500, 'application/json', JSON.stringify({}));
}
console.log(event.path);
console.log(event['detail-type']);
console.log(JSON.stringify(event));
const query = event.queryStringParameters;
let action;
if(query && query.action) {
console.log("action: " + query.action);
action = query.action;
}

// start recording
if (action == 'start'){
  let meeting = await getMeeting(query.title);
  if (!meeting) {
    return response(404, 'application/json', JSON.stringify({message: 'Meeting not found.'}));
  }
  const callerInfo = await sts.getCallerIdentity().promise();
  console.log("callerInfo: " + callerInfo.Account);
  console.log(`arn:aws:chime::${callerInfo.Account}:meeting:${meeting.Meeting.MeetingId}`);
  const pipelineInfo = await chime.createMediaCapturePipeline({
    SourceType: "ChimeSdkMeeting",
    SourceArn: `arn:aws:chime::${callerInfo.Account}:meeting:${meeting.Meeting.MeetingId}`,
    SinkType: "S3Bucket",
    SinkArn: CAPTURE_S3_DESTINATION,
    "ChimeSdkMeetingConfiguration": {
      "ArtifactsConfiguration": {
          "Audio": {
              "MuxType": "AudioWithActiveSpeakerVideo"
          },
          "Video": {
              "State": "Enabled",
              "MuxType": "VideoOnly"
          },
          "Content": {
              "State": "Disabled",
              "MuxType": "ContentOnly"
          },
      }
  }
  }).promise();
  console.log(JSON.stringify(pipelineInfo));
  meetingTable[query.title] = pipelineInfo.MediaCapturePipeline;
  return response(201, 'application/json', JSON.stringify(pipelineInfo));
}
// end recording
else if (action == 'end') {
  const pipelineInfo = meetingTable[query.title];
  console.log(JSON.stringify(pipelineInfo));
  await chime.deleteMediaCapturePipeline({
    MediaPipelineId: pipelineInfo.MediaPipelineId
  }).promise();
  meetingTable[query.title] = undefined;
  return response(200, 'application/json', JSON.stringify({}));    
}
// concatenate recording files
else if (action == 'concat') {
  let meeting = await getMeeting(query.title);
  if (!meeting) {
    return response(404, 'application/json', JSON.stringify({message: 'Meeting not found.'}));
  }
  const pipelineInfo = await chime.createMediaConcatenationPipeline({
    Sinks: [
      {
        S3BucketSinkConfiguration: { Destination: CONCAT_BUCKET_ARN },
        Type: 'S3Bucket',
      },
    ],
    Sources: [
      {
        MediaCapturePipelineSourceConfiguration: {
          ChimeSdkMeetingConfiguration: {
            ArtifactsConfiguration: {
              Audio: { State: 'Enabled' },
              CompositedVideo: { State: 'Enabled' },
              Content: { State: 'Disabled' },
              DataChannel: { State: 'Enabled' },
              MeetingEvents: { State: 'Enabled' },
              TranscriptionMessages: { State: 'Enabled' },
              Video: { State: 'Disabled' },
            },
          },
          MediaPipelineArn: meetingTable[query.title].MediaPipelineArn,
        },
        Type: 'MediaCapturePipeline',
      },
    ],
  }).promise();
  console.log(JSON.stringify(pipelineInfo));
}else {
  return response(404, 'text/html', '404 Not Found');
}
};

// Retrieves the meeting from the table by the meeting title
async function getMeeting(title) {
const result = await ddb.getItem({

TableName: MEETINGS_TABLE_NAME,
Key: {
  'Title': {
    S: title
  },
},
}).promise();
return result.Item ? JSON.parse(result.Item.Data.S) : null;
}

function response(statusCode, contentType, body) {
return {
statusCode: statusCode,
headers: { 'Content-Type': contentType, 'Access-Control-Allow-Origin': '*' },
body: body
};
}

**Comment by xuesichao** [comment]
Hi @jaeho0522 , I'm not sure but from your code it seems you are using wrong client.

```js
const AWS = require('aws-sdk');
const chime = new AWS.Chime({ region: 'us-east-1' });
const pipelineInfo = await chime.createMediaConcatenationPipeline({...});
```

And [`createMediaConcatenationPipeline`](https://docs.aws.amazon.com/chime-sdk/latest/APIReference/API_media-pipelines-chime_CreateMediaConcatenationPipeline.html) API is published under `Amazon Chime SDK Media Pipelines`.

Try this:
```js
const AWS = require('aws-sdk');
const chimeSDKMediaPipelines = new AWS.ChimeSDKMediaPipelines({region: 'us-east-1'});
const pipelineInfo = chimeSDKMediaPipelines.createMediaConcatenationPipeline({...});
```

I also tagged the corresponding service team to check this question.

**Comment by jaeho0522** [comment]
Thanks for your help.

**Comment by jaeho0522** [comment]
Thanks for your help.
By using chimeSDKMediaPipelines.createMediaConcatenationPipeline,
my error message is resolved.

**Comment by kazinayem2011** [comment]
> ```js
> ChimeSDKMediaPipelines
> ```

@xuesichao Please help.

Where should I get **MediaPipelineArn**?

The object I get from **createMediaCapturePipeline** is:

`{
MediaPipelineId: '0794b981-81c4-4e19-b71a-91389cbdba94',
SourceType: 'ChimeSdkMeeting',
SourceArn: 'arn:aws:chime::534678543881:meeting:bf14896e-2baf-43d5-bc20-ab7c9be70706',
Status: 'Initializing',
SinkType: 'S3Bucket',
SinkArn: 'arn:aws:s3:::demomediacapturebucket2',
CreatedTimestamp: '2023-03-08T07:23:46.520Z',
UpdatedTimestamp: '2023-03-08T07:23:46.609Z',
ChimeSdkMeetingConfiguration: {
    ArtifactsConfiguration: { Audio: [Object], Video: [Object], Content: [Object] }
  }
}
`

**Comment by kazinayem2011** [comment]
> Hi @jaeho0522 , I'm not sure but from your code it seems you are using wrong client.
> 
> ```js
> const AWS = require('aws-sdk');
> const chime = new AWS.Chime({ region: 'us-east-1' });
> const pipelineInfo = await chime.createMediaConcatenationPipeline({...});
> ```
> 
> And [`createMediaConcatenationPipeline`](https://docs.aws.amazon.com/chime-sdk/latest/APIReference/API_media-pipelines-chime_CreateMediaConcatenationPipeline.html) API is published under `Amazon Chime SDK Media Pipelines`.
> 
> Try this:
> 
> ```js
> const AWS = require('aws-sdk');
> const chimeSDKMediaPipelines = new AWS.ChimeSDKMediaPipelines({region: 'us-east-1'});
> const pipelineInfo = chimeSDKMediaPipelines.createMediaConcatenationPipeline({...});
> ```
> 
> I also tagged the corresponding service team to check this question.

Please help: 

I am not getting **MediaPipelineArn** from **createMediaConcatenationPipeline** response. What's the reason?

**Comment by xuesichao** [comment]
According to our [documentation](https://docs.aws.amazon.com/chime-sdk/latest/APIReference/API_media-pipelines-chime_CreateMediaConcatenationPipeline.html), there should be a `MediaPipelineArn` in `createMediaConcatenationPipeline` response.

Also from our API interface I do see there's a such property in the response:
```js
  export interface CreateMediaConcatenationPipelineResponse {
    /**
     * A media concatenation pipeline object, the ID, source type, MediaPipelineARN, and sink of a media concatenation pipeline object.
     */
    MediaConcatenationPipeline?: MediaConcatenationPipeline;
  }

  export interface MediaConcatenationPipeline {
    /**
     * The ID of the media pipeline being concatenated.
     */
    MediaPipelineId?: GuidString;
    /**
     * The ARN of the media pipeline that you specify in the SourceConfiguration object.
     */
    MediaPipelineArn?: AmazonResourceName;
    /**
     * The data sources being concatnated.
     */
    Sources?: ConcatenationSourceList;
    /**
     * The data sinks of the concatenation pipeline.
     */
    Sinks?: ConcatenationSinkList;
    /**
     * The status of the concatenation pipeline.
     */
    Status?: MediaPipelineStatus;
    /**
     * The time at which the concatenation pipeline was created.
     */
    CreatedTimestamp?: Iso8601Timestamp;
    /**
     * The time at which the concatenation pipeline was last updated.
     */
    UpdatedTimestamp?: Iso8601Timestamp;
  }
```

Could you open a new issue for this if you still have the issue. @kazinayem2011

**Comment by kazinayem2011** [comment]
> 

Thanks. Still having the issue. Opening an issue.
