### ISSUE TITLE
About create media concatenation pipeline after recording end and empty attendeeid of active speaker in meeting events

### ISSUE THREAD

**Issue by austinpan** [aws/amazon-chime-sdk-js#2528]
### What happened and what did you expect to happen?

We use aws/aws-sdk-php: 3.240 to called the createMediaConcatenationPipeline after a recording is ended. 
But no files are generated by this function.
Then we do the next steps.
1. Use listMediaPipelines to list all active pipelines and found the concatenation pipeline is still exist. 
2. Use deleteMediaPipeline to delete these active pipeline but it seems not work.

Is it we can't call createMediaConcatenationPipeline after a recording is ended?

The Second question is that we found some empty AttendeeId Active Speaker records in the meeting-events. And can't find the attendee info from meeting-events.
Is there something we missing?
Here are some records:
{"Timestamp":"2022-12-18T06:11:45.284+00:00","EventType":"ActiveSpeaker","EventParameters":{"AttendeeId":"95c160f8-a3a4-074d-d094-6c31bd09807d","MediaModality":""}}
{"Timestamp":"2022-12-18T06:11:58.364+00:00","EventType":"ActiveSpeaker","EventParameters":{"AttendeeId":"","MediaModality":""}}
{"Timestamp":"2022-12-18T06:11:59.444+00:00","EventType":"ActiveSpeaker","EventParameters":{"AttendeeId":"95c160f8-a3a4-074d-d094-6c31bd09807d","MediaModality":""}}
{"Timestamp":"2022-12-18T06:14:43.764+00:00","EventType":"ActiveSpeaker","EventParameters":{"AttendeeId":"","MediaModality":""}}

Thanks for your help.

### Have you reviewed our existing documentation?

- [X] GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [X] FAQs [page](https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html)
- [X] README [page](https://github.com/aws/amazon-chime-sdk-js#amazon-chime-sdk-for-javascript)
- [X] Feature-specific [guides](https://github.com/aws/amazon-chime-sdk-js#guides)

### Reproduction steps

First Question
1. After the chime media recording pipeline is ended
2. call createMediaConcatenationPipeline api
3. get active pipelines by listMediaPipelines
4. use deleteMediaPipeline but can't work

Second Question can found records in meeting-events

### Amazon Chime SDK for JavaScript version

3.6.0

### What browsers are you seeing the problem on?

chrome

### Browser version

108.0.5359.124

### Browser console logs

no browser logs

**Comment by MingcongQi** [comment]
1. You can  call createMediaConcatenationPipeline after a recording is ended.
2. Could you send the meeting id and media pipeline id for us?

**Comment by austinpan** [comment]
1. OK, will try more times.
2.1 meeting id: 14275ed2-4a7f-4d17-b96c-f8fa91702954, media pipeline id: 1629a375-9fd8-4ed3-866c-300f433b9785
2.2. meeting id: 14275ed2-4a7f-4d17-b96c-f8fa91702954, media pipeline id: 06146e6e-65b5-4644-a261-88108b5399f4

Thanks for your help.

**Comment by MingcongQi** [comment]
1. 95c160f8-a3a4-074d-d094-6c31bd09807d was your meeting attendee, you could get it from creating attendee response
2.  if active speaker event attendee id was "". there was no active speaker.
3.  The capture pipeline `1629a375-9fd8-4ed3-866c-300f433b9785` and `06146e6e-65b5-4644-a261-88108b5399f4` were deleted successfully. Did you receive any error code?
