### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'getVideoTracks')

### ISSUE THREAD

**Issue by kennyvallejodev** [aws/amazon-chime-sdk-js#2535]
### What happened and what did you expect to happen?

We start receiving some logs of some of our users having a crash issue (not that common and is not easy to repro. but all the errors share the same stacktrace.

```
TypeError: Cannot read properties of null (reading 'getVideoTracks')
  at t.default.audioVideoDidStart (../../../src/contentsharecontroller/DefaultContentShareController.ts:158:44)
  at <anonymous> (../../../src/audiovideocontroller/DefaultAudioVideoController.ts:738:54)
  at r.map (../../../src/utils/Types.ts:68:21)
  at <anonymous> (../../../src/audiovideocontroller/DefaultAudioVideoController.ts:738:45)
  at <anonymous> (../../../src/audiovideocontroller/DefaultAudioVideoController.ts:271:11)
```

I expect to the library not throwing an unhandled error.
Looking at the code looks like on the same file but on a few lines later, you guys are doing some checking in case the mediaStream actually exist (having in mind that can be optional).

https://github.com/aws/amazon-chime-sdk-js/blob/main/src/contentsharecontroller/DefaultContentShareController.ts#L193

Probably a tiny fix is just adding a optional chaining to the mediaStream?

### Have you reviewed our existing documentation?

- [X] GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [X] FAQs [page](https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html)
- [X] README [page](https://github.com/aws/amazon-chime-sdk-js#amazon-chime-sdk-for-javascript)
- [X] Feature-specific [guides](https://github.com/aws/amazon-chime-sdk-js#guides)

### Reproduction steps

We don't know actually a proper reproduction step. 

### Amazon Chime SDK for JavaScript version

3.6.0

### What browsers are you seeing the problem on?

Chrome, Electron

### Browser version

Chrome 108

### Browser console logs

```
TypeError: Cannot read properties of null (reading 'getVideoTracks')
  at t.default.audioVideoDidStart (../../../src/contentsharecontroller/DefaultContentShareController.ts:158:44)
  at <anonymous> (../../../src/audiovideocontroller/DefaultAudioVideoController.ts:738:54)
  at r.map (../../../src/utils/Types.ts:68:21)
  at <anonymous> (../../../src/audiovideocontroller/DefaultAudioVideoController.ts:738:45)
  at <anonymous> (../../../src/audiovideocontroller/DefaultAudioVideoController.ts:271:11)
```

**Comment by ltrung** [comment]
@kennyvallejodev Thanks for reporting. I guess our assumption is for screen share to have media stream so we did not handle the case where the stream did not exist.
Could you provide us more info on how you do content share? Do you call `startContentShareFromScreenCapture` or `startContentShare` with media stream? 
Is there any chance you pass a null media stream to those API?

**Comment by kennyvallejodev** [comment]
Looking at my code base, there's one use case where i'm not checking if the `stream` exists or not before passing it to the `startContentShare`. 

So there's a chance that probably there is where the issue is happening.

Will add a check before `startContentShare` and review if the issue still happens.

but anyway, should check for `mediaStream` to exist before doing that validation. 
Chime already do that on https://github.com/aws/amazon-chime-sdk-js/blob/main/src/contentsharecontroller/DefaultContentShareController.ts#L193

**Comment by ltrung** [comment]
So we already check whether the stream exists in `startContentShare` as you can see in https://github.com/aws/amazon-chime-sdk-js/blob/main/src/contentsharecontroller/DefaultContentShareController.ts#L75. So I wonder whether the stream becomes null somehow during the time the content attendee joins the meeting.
Do you have any logic to cleanup/ reset the stream in your application?

**Comment by kennyvallejodev** [comment]
Let me confirm the cleanup logic that we have and i'll get back to you!

**Comment by kennyvallejodev** [comment]
I actually test the different ways to start and stop a screenshare and i didn't get the error not even once. 

so looks like its a border case, but i don't know what is the source of the problem to maintain the stream so audioVideoDidStart gets invoked but the stream is null 🥲

**Comment by kennyvallejodev** [comment]
will mark this issue as resolved at least for now.

<3.

Thx @ltrung for all your work.
