### ISSUE TITLE
npm ERR! peer react@"^17.0.1" from amazon-chime-sdk-component-library-react@3.4.0

### ISSUE THREAD

**Issue by shalini-cpu** [aws/amazon-chime-sdk-js#2541]
Hi Team,
I am working on a project with node and react version 18.2.0. 

I am trying to install 

npm install --save amazon-chime-sdk-component-library-react amazon-chime-sdk-js 

Getting this error:

npm ERR! peer react@"^17.0.1" from amazon-chime-sdk-component-library-react@3.4.0

Could you please suggest some solution?

**Comment by ltrung** [comment]
@shalini-cpu The `amazon-chime-sdk-component-library` requires React 17 as peer dependency so it just means you lacks the dependency.
