### ISSUE TITLE
Camera Led Remains On after finishing a meeting

### ISSUE THREAD

**Issue by jitt3** [aws/amazon-chime-sdk-js#2548]
### What happened and what did you expect to happen?

We are building a meetings application, and we have two main screens.

1 . In the meeting preview modal, where we show a camera and microphone preview
 in this view, we added a dummy meeting session information. that information allowed to open and use the camera preview
Unfortunately, after closing the modal, the camera led remains turned on even though we release the stream

2 . the main meeting view, where you can interact with other participants
Something similar happens here; we have a hangup button which is the one that closes the meeting for the current attendee. The result after closing the meeting is the same(the camera led remains on)

The above issues happen only in the Safari browser.

### Have you reviewed our existing documentation?

- [X] GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [X] FAQs [page](https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html)
- [X] README [page](https://github.com/aws/amazon-chime-sdk-js#amazon-chime-sdk-for-javascript)
- [X] Feature-specific [guides](https://github.com/aws/amazon-chime-sdk-js#guides)

### Reproduction steps

-Start a new meeting
-Then Close the meeting
- The camera led remains on

### Amazon Chime SDK for JavaScript version

3.9.0

### What browsers are you seeing the problem on?

Safari

### Browser version

Version 15.3 (17612.4.9.1.8)

### Meeting and Attendee ID Information.

meetingId: 62cf45f4-67e6-4a83-a181-1783d8930706
AttendeeId:1947893e-03ad-1825-b669-8a9ffcfd5009

### Browser console logs

 
[Meeting.txt](https://github.com/aws/amazon-chime-sdk-js/files/10452221/Meeting.txt)

**Comment by ltrung** [comment]
@jitt3 I tried to reproduce your provided steps with our [demo](https://github.com/aws/amazon-chime-sdk-js/tree/main/demos/browser/app/meetingV2) but did not see any issue in both the preview and during the meeting (Safari 16.2 Monterey). 
Can you see if you can reproduce it with our demo in your system?

**Comment by devalevenkatesh** [comment]
I am resolving this issue, please feel free to re-open if still an issue.
