### ISSUE TITLE
Simulcast causes freezing video

### ISSUE THREAD

**Issue by Kedyn** [aws/amazon-chime-sdk-js#2550]
### What happened and what did you expect to happen?

Enabling simulcast causes videos to freeze.

Similar to #2374, which was resolved by #2452, or #2374.

When simulcast is enabled and three or more users are present on a meeting, after one leaves at least one of the videos freezes.

I was not only able to reproduce this on our own app, but also on the demo.

Toggling video input from any of the users on the meeting stops any video from being frozen.

### Have you reviewed our existing documentation?

- [X] GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [X] FAQs [page](https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html)
- [X] README [page](https://github.com/aws/amazon-chime-sdk-js#amazon-chime-sdk-for-javascript)
- [X] Feature-specific [guides](https://github.com/aws/amazon-chime-sdk-js#guides)

### Reproduction steps

- Join with user A
- Join with user B
- Join with user C
- Leave with user C
- See A or B paused, or both

### Amazon Chime SDK for JavaScript version

3.10.0

### What browsers are you seeing the problem on?

Chrome

### Browser version

109.0.5414.75

### Browser console logs

2023-01-20T20:29:59.783Z [INFO] HuddleMeetingLogger - bwe: attendee: 27b2560b-f2f9-f825-5a56-31b284f3e2d5 group: 1 has simulcast and can upgrade avgBitrate: 88 target: 1200 targetTotalBitrate: 2118.933
ConsoleLogger.js:93 2023-01-20T20:29:59.783Z [INFO] HuddleMeetingLogger - One or more video streams are not receiving expected amounts of data [{"expectedAverageBitrateKbps":88.011,"receivedAverageBitrateKbps":0,"attendeeId":"27b2560b-f2f9-f825-5a56-31b284f3e2d5"}]

**Comment by hensmi-amazon** [comment]
Thanks for the report, unfortunately an unrelated change caused issues with simulcast layer switching (which occurs from 2->3) that we were not able to catch. I have fixed the issue and it will be pushed by around a week. I will update this SIM after that occurs.

**Comment by SohanChoudhury** [comment]
Any update here?

**Comment by hensmi-amazon** [comment]
Sorry for the delay. This change has completed deployment.
