### ISSUE TITLE
VoiceFocus high CPU warning cause crash

### ISSUE THREAD

**Issue by haofiltered** [aws/amazon-chime-sdk-js#2557]
### What happened and what did you expect to happen?

With the VoiceFocus feature turned on, many of our users have experienced "kick out" experience during the chime meeting. 

Here is what happened, after the meeting runs for 20 minutes-ish, the user will start getting the high CPU usage warning, and soon the page will be frozen, and the user will get kicked out from the meeting, and they will need to refresh or rejoin the meeting.

<img width="519" alt="image" src="https://user-images.githubusercontent.com/28816747/214411601-8c0e657f-b2f6-4eb1-8533-68b1d722a3ce.png">

### Have you reviewed our existing documentation?

- [X] GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [X] FAQs [page](https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html)
- [X] README [page](https://github.com/aws/amazon-chime-sdk-js#amazon-chime-sdk-for-javascript)
- [X] Feature-specific [guides](https://github.com/aws/amazon-chime-sdk-js#guides)

### Reproduction steps

Join a chime meeting with VoiceFocus on, keep talking for 20 to 30 minutes ish, there should be some console warning about high CPU usage. Keep talking and eventually, the page will be crashed. 

Using external headphones could help reproduce the issue.

### Amazon Chime SDK for JavaScript version

3.10.0

### What browsers are you seeing the problem on?

Chrome

### Browser version

109.0.0.0

### Meeting and Attendee ID Information.

MeetingId: `54f1f086-8817-4541-b0c3-a724f3ab0706`

AttendeeId 1: `db1f1520-9cc5-4705-6150-e261ebe1236d`
AttendeeId 2: `c0537b4c-7846-0abf-1933-5e06247788b3`

I can provide more MeetingIds and AttendeeIds, let me know if you need.

### Browser console logs

Not available

**Comment by michhyun1** [comment]
@haofiltered I would double check the Task Manager on your browser. Open it and see if you might have multiple worker threads spawning when you enable Voice Focus. If so, you might want to follow this: https://aws.github.io/amazon-chime-sdk-js/modules/amazonvoice_focus.html#destroying-amazon-voice-focus-worker-thread-from-your-application

**Comment by haofiltered** [comment]
@michhyun1 Thank you for the info, that wasn't the case in our application. 
And I think we've found the root cause of the crash, it's not relevant to VoiceFocus. VoiceFocus does give us a lot of high CPU warnings, but it is not the root cause of the crash. 

With that being said, I am closing this issue now, thank you for your help!
