### ISSUE TITLE
Problem recording meeting when there are only two meeting attendees

### ISSUE THREAD

**Issue by Dorumuk** [aws/amazon-chime-sdk-js#2567]
Hi,  I am having strange problem recording meeting session.
The problem occurs when there are only two meeting attendees.

I'm using chimeSDKMediaPipelines.createMediaCapturePipeline api for meeting recording.

When there are 2 attendees in a meeting, and if one attendee starts video recording with createMediaConcatenationPipeline api,
the video of second attendee freezes.
When this happens, recorded chunked media files are all black video without any error messages.
However, the sound is saved without problems.

If there are 3 or more meeting attendees, recording works fine without any problem.

I am including configuration of pipeline creation below.
```
const chimeSDKMediaPipelines = new AWS.ChimeSDKMediaPipelines({ region: 'us-east-1' });
...
const pipelineInfo = await chimeSDKMediaPipelines.createMediaCapturePipeline({
    SourceType: "ChimeSdkMeeting",
    SourceArn: `arn:aws:chime::${callerInfo.Account}:meeting:${meeting.Meeting.MeetingId}`,
    SinkType: "S3Bucket",
    SinkArn: `${CAPTURE_S3_DESTINATION}/${meeting.Meeting.MeetingId}` + `/${captureIndex + 1}`,
    ChimeSdkMeetingConfiguration: {
      ArtifactsConfiguration: {
          Audio: { MuxType: 'AudioWithCompositedVideo' },
          Video: {
              State: "Disabled",
              MuxType: "VideoOnly"
          },
          Content: {
              State: "Disabled",
              MuxType: "ContentOnly"
          },
          CompositedVideo: {
            Layout: "GridView",
            Resolution: "FHD",
            GridViewConfiguration: {
              ContentShareLayout: "PresenterOnly",
              PresenterOnlyConfiguration: {
                PresenterPosition: "BottomRight"
              }
            }
          }
      }
  }
}).promise();

```
The dependencies are:
```
"dependencies": {
    "aws-sdk": "^2.1279.0"
  }
```

2) Browsers experiencing issues
chrome

3) browser version
Version 109.0.5414.120 (Official Build) (x86_64)

4) Meeting Information
MediaPipelineId: "a669500c-90e1-4f7d-b74e-9fe5f7c18b43"
Meeting ID: 8dab630d-68d9-4afc-be9c-8878a1e70706

Thanks in advance

**Comment by yuqil-amzn** [comment]
Hi,
Could you elaborate your steps. Correct me if I am wrong, the steps are as follow:
1. Create media capture with PresenterOnly mode.
2. Two attendee join the meeting.
3. The second attendee's video is freeze?

Also is this issue reproducible?

Thanks

**Comment by Dorumuk** [comment]
Hi,
Thanks for your help.

1. Create a media capture with PresenterOnly mode.
2. Two attendees join the meeting.
3. Both attendees have problems.
- In first attendee's screen, local video tile works, but the second attendee's video tile is frozen.
- In Second attendee's screen, local video tile works, but the first attendee's video tile is frozen.
So for both attendee's screen, local video tile works, but other attendee's video tile is frozen.
4. Delete Media Capture, all videos will work fine again.


Yes, this problem is reproducible.
It occurs every time media capture is created.

I tried following steps to narrow down the problem.
1. Create a media capture with PresenterOnly mode.
2. Two attendees join the meeting.
3. The problem occurs again.
4. After the first attendee attempts to share the screen 2 or 3 times, second attendee's video tile within the first attendee's screen is lowered and unfreeze.
5. If I end the recording by removing the media capture, the second attendee's video tile inside the first attendee's screen is frozen again.
6. And turn off and turn on your own video to unfreeze.

**Comment by yuqil-amzn** [comment]
Hi,
Thanks for your info. To clarify, you create a meeting, and start capture with PresenterOnly Mode. Then two attendee join but turn on video but didn't start screen share. From first attendee's screen, only himself is moving, the other attendee video is freezing. Is my understanding correct? 
Also, if you were using capture, are you checking the composited-video folder in your bucket? What do you mean by "local video tile works"?

**Comment by Dorumuk** [comment]
Yes, From first attendee's screen, only himself is moving, the other attendee video is freezing

Yes I checked the composited-video folder.

By “local video tile works”, I meant “only himself is moving”

**Comment by Dorumuk** [comment]
Since February 5, 2023, suddenly the issue has disappeared.
I'll close the issue for now.
