### ISSUE TITLE
Immediately reconnect client with servers once attendee suddenly dropped out due to signaling snaps

### ISSUE THREAD

**Issue by rixiang-dev** [aws/amazon-chime-sdk-js#2568]
# Community Note
* Please vote for this issue by adding a 👍 reaction to the issue. This will help the community and maintainers from the Amazon Chime SDK team to prioritize this request.
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request.
* Please go through the existing [issues](https://github.com/aws/amazon-chime-sdk-js/issues) to see if your request has already been recommended.
* Please do not use this template for bugs or support. Each individual repository has a PR template, documentation and resources for [troubleshooting](https://github.com/aws/amazon-chime-sdk-js#troubleshooting-and-support).
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.

# Tell us about your request
Sometimes attendees would be suddenly dropped out (e.g. signaling snaps such as websocket closure with status code 1006). But according to _ReconnectionHealthPolicy_, clients have to wait for 25 seconds (by [default config](https://github.com/aws/amazon-chime-sdk-js/blob/main/src/connectionhealthpolicy/ConnectionHealthPolicyConfiguration.ts#L8)) to trigger condition _noPacketsReceivedRecently_ (note condition _missedPongsRecently_ isn't triggered in such cases). We should just immediately try reconnecting with server to remove unnecessary idle waiting time.

## What do you want us to build?
Which Amazon Chime SDK or feature area is this request for?
[amazon-chime-sdk-js](https://github.com/aws/amazon-chime-sdk-js)

## Tell us about the problem you are trying to solve and why is it hard?
See request for problem. This led to bad user experience while it could be greatly improved relatively easily. 

## How are you currently solving a problem?
Are there any workarounds or mitigations you have used? Why is it not working for you?

## Additional context
Anything else we should know?

**Comment by hensmi-amazon** [comment]
Resolving this as it was an internal request. Will be available in next release.
