### ISSUE TITLE
Feature request: Ability to use the websocket for custom events

### ISSUE THREAD

**Issue by matiboy** [aws/amazon-chime-sdk-js#257]
### What are you trying to do?

I'm trying to send custom data and socket events between attendees. 

### How can the documentation be improved to help your use case?

I couldn't find feature request in issues, so posting this as a "documentation" issue. Unless this feature exists and I couldn't find it in the docs.

Since Chime already takes care of building a trustworthy websocket for the video/audio/content sharing streams and we can easily identify the attendees, it would be practical to be able to send websocket events between the attendees, piggybacking on the existing connection.

This could allow features like students raising hand, etc...

### What documentation have you looked at so far?

README.md, Amazon Chime SDK Developer Guide, [articles](https://aws.amazon.com/blogs/business-productivity/building-a-virtual-classroom-application-using-the-amazon-chime-sdk/)

**Comment by aburnson** [comment]
Thanks for the feature request. We have received similar requests before, and we can see how it would be valuable to leverage the existing signaling connection for sending custom events. We will update this issue when we have more information.

**Comment by vidya-mohan** [comment]
@matiboy we have released https://aws.github.io/amazon-chime-sdk-js/modules/apioverview.html#9-send-and-receive-data-messages-optional to Github

**Comment by matiboy** [comment]
Much appreciated. Will try using it (meanwhile had moved to GraphQL subscriptions).
