### ISSUE TITLE
Some of the chime meeting recording cut off

### ISSUE THREAD

**Issue by AnkurSavaliya** [aws/amazon-chime-sdk-js#2575]
Hi, 

I record a 6-hour meeting and when the meeting ended I started the media concatenation pipeline, media concatenation pipeline was completed successfully, but when I watch the recorded meeting then only the 3-hour recording concatenate, and also some of the parts of the meeting were missing,
So I checked the S3 bucket where all chunks are available and I see that all meeting chunks are available, So I manually combine these chunks using FFMPEG and I am able to generate full meeting recordings.

So Why does using a media concatenation pipeline not generate a full recording?

here are the Media concatenation pipeline Id and Media capture pipeline Id : 
`Media Capture Pipeline Id				Media concatenation pipeline`
`e6cd805a-d795-429f-8bb5-34f3bd3cc26f			01abdfdf-7ccd-4630-9250-e5176b72f0a2`
`4b256da4-e45b-40d1-a9fd-2d2e60a94f3c			5a97e635-5ab4-4a07-8494-02d269bf6ad3`
`33ad8dde-2e7e-43a3-a51d-0eae7e61074e			4b88a4a4-b0af-43b0-8a98-0a131025bcc1`

**Comment by sinanliuAmazon** [comment]
Hi, thanks for reporting the issue. We are reverting a bad change, will keep you posted when the fix is deployed.

**Comment by AnkurSavaliya** [comment]
Hey

Any update on this because it causes many issues for me?
