### ISSUE TITLE
Device label trigger is not running with a device controller

### ISSUE THREAD

**Issue by ldai1** [aws/amazon-chime-sdk-js#2577]
### What happened and what did you expect to happen?

```
 deviceController = new DefaultDeviceController(logger)

 deviceController.setDeviceLabelTrigger(async () => 
    await navigator.mediaDevices.getUserMedia({ audio: true, video: true })
  );
```

With above implementation, no device label trigger is running. no pop-up for browser privacy configuration.

### Have you reviewed our existing documentation?

- [X] GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [X] FAQs [page](https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html)
- [X] README [page](https://github.com/aws/amazon-chime-sdk-js#amazon-chime-sdk-for-javascript)
- [X] Feature-specific [guides](https://github.com/aws/amazon-chime-sdk-js#guides)

### Reproduction steps

```
 deviceController = new DefaultDeviceController(logger)

 deviceController.setDeviceLabelTrigger(async () => 
    await navigator.mediaDevices.getUserMedia({ audio: true, video: true })
  );
```

With above implementation, no device label trigger is running. no pop-up for browser privacy configuration.

### Amazon Chime SDK for JavaScript version

3.0

### What browsers are you seeing the problem on?

Chrome

### Browser version

 109.0.5414.119

### Browser console logs

Meeting not started. no backend api call.

**Comment by xuesichao** [comment]
Hi @ldai1 , SDK uses `deviceLabelTrigger` to call `getUserMedia` browser API to request permission for audio and video. `setDeviceLabelTrigger` API is a setter method that only sets the [`constraints`](https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getUserMedia) that SDK uses to call `getUserMedia` API, it will not trigger the `deviceLabelTrigger` itself. 

To trigger `deviceLabelTrigger`, you'll need to call `listAudioInputDevices`, `listVideoInputDevices` or `listAudioOutputDevices`.

**Comment by ldai1** [comment]
I did call listVideoInputDevices after the setDeviceLabelTrigger call, but somehow it didn't pop up the permission window on chrome, it did pop up on Firefox

**Comment by ldai1** [comment]
Issue resolved. Like you mentioned, it won't trigger again if the setting was chosen already in previous calls. Thanks for the help. Resolve the issue.

**Comment by devalevenkatesh** [comment]
Per previous comment resolving this issue, thanks!
