### ISSUE TITLE
addContentShareObserver for remote sessions

### ISSUE THREAD

**Issue by mpelzsherman** [aws/amazon-chime-sdk-js#2578]
### What are you trying to do?

I'm trying to trigger events when a remote user starts or stops sharing their screen.

### How can the documentation be improved to help your use case?

Include an example of how to do this. The current example shows how to use addContentShareObserver to add a callback, but that only fires when the local user starts and stops sharing their screen.

### What documentation have you looked at so far?

https://aws.github.io/amazon-chime-sdk-js/

Thanks in advance!

**Comment by devalevenkatesh** [comment]
Thanks for reporting the issue. 

For the remote side content share start/stop events, you could listen to `videoTileDidUpdate` observer. This observer will notify on all video tile state changes along with a video tile state. The state has `isContent`, `localTile` which you can rely on to check whether the tile update is for content.

We do the same in our demo [here](https://github.com/aws/amazon-chime-sdk-js/blob/main/demos/browser/app/meetingV2/video/VideoTileCollection.ts#L154-L206).

Example remote side content start update on the local client side:
```
video tile updated: {
  "tileId": 1,
  "localTile": false,
  "localTileStarted": false,
  "isContent": true,
  "active": true,
  "paused": false,
  "poorConnection": false,
  "boundAttendeeId": "<attendeeId>#content",
  "boundExternalUserId": "<something>#slbvndsi",
  "boundVideoStream": {},
  "boundVideoElement": {},
  "nameplate": null,
  "videoElementCSSWidthPixels": 0,
  "videoElementCSSHeightPixels": 0,
  "devicePixelRatio": 1,
  "videoElementPhysicalWidthPixels": 0,
  "videoElementPhysicalHeightPixels": 0,
  "streamId": 3
}
```

I am resolving this for now, please feel free to re-open if you have more questions.

**Comment by mpelzsherman** [comment]
Thanks @devalevenkatesh .

I'm not sure if it's due to something in our code base, but when I put a `console.log `at the top of our `videoTileDidUpdate` and log the tileState, `videoTileDidUpdate` is not being fired when a remote user stops sharing their screen. `videoTileDidUpdate` is triggered multiple times when screen sharing starts, which makes it a bit tricky to use it as a substitute for `contentShareDidStop/Start` for local events.

I don't see code in the demo link you provided that clearly explains how to use `videoTileDidUpdate` to "capture" remote screen share start/stop events. If this could be clarified, that would be awesome. Thanks again!
