### ISSUE TITLE
Using JavaScript SDK other than in an SPA

### ISSUE THREAD

**Issue by timanderson** [aws/amazon-chime-sdk-js#2583]
I am not sure there is good documentation on using the SDK other than in an SPA. The only solution I see is singlejs which is a sample and which currently seems to be broken (I have tried upgrading to the latest 3.10 but the rollup seems to create a JavaScript file without the ChimeSDK global variable).

**Comment by timanderson** [comment]
Have found the fix (with help!) for singlejs.

**Comment by devalevenkatesh** [comment]
`singlejs` sample is fixed now: https://github.com/aws-samples/amazon-chime-sdk/tree/main/utils/singlejs

Thanks for reporting the issue, resolving now.
