### ISSUE TITLE
startAudioInput with a new default device does not actually connect new device

### ISSUE THREAD

**Issue by wbugenis** [aws/amazon-chime-sdk-js#2584]
### What happened and what did you expect to happen?

After joining a session and running `audioVideo.startAudioInput` with my laptop microphone, which is my fallback default device, then turning on my Bluetooth headset, my actual default device, running startAudioInput again with the newly connected default device seems to connect the headset successfully, according to `audioVideo.deviceController.activeDevices.audio` but my laptop microphone is still the device that's actually sending audio. The above default device connection flow occurs automatically when a new device is connected, from the DeviceChangeObserver. I always use the entire device object, not just the deviceId, for startAudioInput.

It seems that the MediaStream of the active audio device is not being properly closed and recreated, as running `audioVideo.deviceController.activeDevices.audio.stream.getTracks()` shows that even though a new stream was created, the device of the new mediastream is still my laptop microphone, even though the rest of the device info above the stream all matches my headset.

I've tried running audioVideo.stopAudioInput() before connecting the new device, but it seems to have no effect.

Is there something else I should be doing in between connecting a new device to actually disconnect my previous device, and connect to my new one? Is there a better way to check your active audio device/MediaStream aside from digging into DeviceController.activeDevices?

I've attached a screenshot in the Browser Logs below to log out the devices that are being connected, and the active devices listed by the DeviceController.

Let me know if I can clarify anything, thanks.

### Have you reviewed our existing documentation?

- [X] GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [X] FAQs [page](https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html)
- [X] README [page](https://github.com/aws/amazon-chime-sdk-js#amazon-chime-sdk-for-javascript)
- [X] Feature-specific [guides](https://github.com/aws/amazon-chime-sdk-js#guides)

### Reproduction steps

On MacOS, connect a Bluetooth microphone to your computer and set it as your default device, then turn it off so your default device falls back to the laptop's built in microphone. Connect to a session and startAudioInput using this microphone.
Turn on your Bluetooth device so your mac connects and automatically switches to this device as your default, triggering your deviceChangeObserver to run audioVideo.startAudioInput with your new device. The newly connected device should show as your now active device, but your audio input will still be coming from your laptop microphone.

### Amazon Chime SDK for JavaScript version

3.10.0

### What browsers are you seeing the problem on?

Chrome

### Browser version

109.0.5414.119

### Browser console logs

Below is a screenshot of some logs I hope will better illustrate the issue, I've logged the device object that is used as the argument `audioVideo.startAudioInput,` followed by the value of `audioVideo.deviceController.activeDevices.audio` and `audioVideo.deviceController.activeDevices.audio?.stream.getTracks()[0]` for the current device, and then the same two values after running audioVideo.startAudioInput with the new device listed at the top of the screenshot.

Note the groupId of the new device listed at the top matches the groupId of the active device at the bottom, which is my Steelseries Arctis 9X headset, but the stream's device label is my Macbook Pro Microphone.

![image](https://user-images.githubusercontent.com/6378179/218608636-dc9ef39e-f2ec-43eb-9aef-9c1ccf08cfc2.png)

**Comment by blundercode** [comment]
I have also encountered this and am looking for a solution.

**Comment by michhyun1** [comment]
Can you also manually call chooseAudioInput to see if that works after you plug in the bluetooth device?

**Comment by wbugenis** [comment]
While I am using the Chime device change observers, I use the browser's navigator to get the devices to feed into the device setter methods. 
I was able to resolve this issue in two ways - when using the voice focus transformer, passing in the whole device object instead of just the deviceId would successfully switch between default devices (I hadn't mentioned the voice focus in my original issue, but just FYI)
When not using the voice focus transformer, I would run this method after running startAudioInput, which would eventually switch to the proper device within the 20 iteration limit here.
````
  async ensureDeviceChosen(device, iteration = 0) {
    if (this.audioVideo.deviceController.activeDevices?.audio?.stream.getTracks()[0].label !== device.label) {
      if (iteration > 20) {
        console.log("Failed to switch to new default device, please select the non-default version in the toolbar.");
        return;
      }

      console.log(`Chose device ${device.label}, but ${this.audioVideo.deviceController.activeDevices?.audio?.stream.getTracks()[0].label} is still in use, retrying`);
      console.log(`Default device not connected, attempt ${iteration + 1}`, device);
      iteration += 1;

      await this.audioVideo.stopAudioInput();

      setTimeout(async () => {
        await this.audioVideo.startAudioInput(device);
        this.ensureDeviceChosen(device, iteration);
      }, 1500)
    }
```

I'm suspicious this is actually just a Chome issue when using devices where the ID is just "default", I've been working with other video conferencing SDKs recently that have the same issues when a new default device connects, the label of the default device will update, but the browser will stay connected to the original default device.

**Comment by xuesichao** [comment]
Hi @wbugenis , I'm not able to reproduce this issue using our [meetingV2 demo](https://github.com/aws/amazon-chime-sdk-js/tree/main/demos/browser).
My steps:
1. Disconnect any bluetooth audio input devices from my laptop.
2. Join the meeting using laptop microphone
3. Verify the audio input device is laptop microphone and confirm it works.
4. Connect to AirPods
5. Verify the audio input and audio out put device are auto switched to AirPods and confirm it works.

Could you please try to reproduce the issue using our [meetingV2 demo](https://github.com/aws/amazon-chime-sdk-js/tree/main/demos/browser)?

And we handle this device change event in our demo here:
https://github.com/aws/amazon-chime-sdk-js/blob/16e255078d5d46424261d880c158e7807895e4b1/demos/browser/app/meetingV2/meetingV2.ts#L1584-L1609

**Comment by wbugenis** [comment]
The demo seems to be working once I join the call as two users and listen, though the preview audio bar doesn't update in the pre-join device if your default device updates until you click a different device, fyi.

I think we can go ahead and close this, I guess it's something on my end.

One last question, if you don't mind - do you know of anything that would cause the issue I'm having here, for example, would something keep a hold on my previously selected default device? Or is there something that runs as part of Chime's  device list methods that I'm losing because I'm grabbing my device list from the browser's built in navigator methods instead?

Thanks for your help!

**Comment by brycepj** [comment]
We frequently get reports of identical behavior, but with audio output.

**Comment by andreaCosm** [comment]
I'm stumped on this. I am unable to get the mic to properly connect, calling `startAudioInput` throws no errors and the `AudioInputControl` from the React library shows the correct mic selected. However, if I unmute it does not work until I select another microphone and come back. `prefDeviceId` is a device ID saved from a previous session to allow users to reconnect using the same device. `foundPrefDevice` is being found in the list. 

```
const audioInputDevices = await meetingManager?.audioVideo?.listAudioInputDevices();
const foundPrefDevice = audioInputDevices.find(d => d.deviceId === prefDeviceId);
await meetingManager.meetingSession?.audioVideo.startAudioInput(foundPrefDevice.deviceId);
```

also doesn't work with: 

`meetingManager.startAudioInputDevice(foundPrefDevice.deviceId);`

What am I doing wrong here?
