### ISSUE TITLE
changed localhost to ip address then camera and microphone is not working

### ISSUE THREAD

**Issue by NaveenVinayakS** [aws/amazon-chime-sdk-js#2587]
### What happened and what did you expect to happen?

when i tried to run this code using 'npm run start' inside demo/browser i got code executed and its being runing in localhost . 127.0.0.1:8080. but when i changed this '127.0.0.1' to my system ip address in 'server.js'  and i run the code my camera and microphone is not working. 

Kindly help me in solving this issues . I am python guy so kindly help me in this

### Have you reviewed our existing documentation?

- [X] GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [X] FAQs [page](https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html)
- [X] README [page](https://github.com/aws/amazon-chime-sdk-js#amazon-chime-sdk-for-javascript)
- [X] Feature-specific [guides](https://github.com/aws/amazon-chime-sdk-js#guides)

### Reproduction steps

when i tried to run this code using 'npm run start' inside demo/browser i got code executed and its being runing in localhost . 127.0.0.1:8080. but when i changed this '127.0.0.1' to my system ip address in 'server.js'  and i run the code my camera and microphone is not working. 

Kindly help me in solving this issues . I am python guy so kindly help me in this

### Amazon Chime SDK for JavaScript version

16

### What browsers are you seeing the problem on?

chrome

### Browser version

Version 110.0.5481.100 (Official Build) (64-bit)

### Browser console logs

WebSocket connection to 'wss://signal.m2.ao1.app.chime.aws/control/64291927-2073-4930-b561-3546cb272713?X-Chime-Control-Protocol-Version=3&X-Amzn-Chime-Send-Close-On-Error=1&X-Amzn-Version=3.12.0&X-Amzn-User-Agent=chrome-110' failed: 
create @ VM5:2

**Comment by devalevenkatesh** [comment]
I think for running locally you  have to use `localhost:8080` or `127.0.0.1:8080`, when changing host to your system IP, there may be errors around creating meeting and attendee itself before even joining the meeting.

You have to open your IP and port access to allow access for node js server to listen correctly to incoming requests. This is more on networking side I believe. Unfortunately, we wont be able to help here, but, I will suggest to check the serverless deployment and then run the hosted demo.

- https://github.com/aws/amazon-chime-sdk-js/tree/main/demos/serverless

Closing this issue now. Feel free to re-open if you need help with the SDK itself or whether the local demo running or serverless demo deployment is running into issues.
