### ISSUE TITLE
Support WebCodecs API

### ISSUE THREAD

**Issue by gunta** [aws/amazon-chime-sdk-js#2588]
# Tell us about your request
## What do you want us to build?
Add support for WebCodecs API.

## Additional context
Now that Safari 16.4 is supporting it, there is gonna be enough market share.
https://developer.apple.com/documentation/safari-release-notes/safari-16_4-release-notes

**Comment by hensmi-amazon** [comment]
I'm not sure what you mean by support. Please re-open if you have a more clear feature request.
