### ISSUE TITLE
Support AV1 on iOS 16.4

### ISSUE THREAD

**Issue by gunta** [aws/amazon-chime-sdk-js#2589]
## What do you want us to build?
AV1 support for iOS 16.4

## Additional context
[iOS 16.4 is adding support for AV1](https://developer.apple.com/documentation/safari-release-notes/safari-16_4-release-notes), and there may be huge gains to be made.

**Comment by gunta** [comment]
iOS 16.4 has been released. As a customer we would love if you can prioritize AV1 support.

https://webkit.org/blog/13966/webkit-features-in-safari-16-4/

**Comment by hensmi-amazon** [comment]
AV1 (and VP9!) is now available via `setVideoCodecSendPreferences`
