### ISSUE TITLE
Missing AttendeeJoined event

### ISSUE THREAD

**Issue by samchienGG** [aws/amazon-chime-sdk-js#2593]
### What are you trying to do?
I use CloudWatch to watch the record of the customer entering and leaving the meeting. I found that there is no record of entering and leaving the meeting on a certain customer (ss8561585), but he is indeed in the meeting. Is this possible? What could be the cause of not receiving this event
---
| time | detail.eventType | detail.externalUserId | detail.externalMeetingId | detail.meetingId | detail.attendeeId |
| --- | --- | --- | --- | --- | --- |
| 2023-02-07T11:51:40Z | chime:MeetingStarted |  | 63dc7822495f565af4004c9a | 77f56d8d-1ce3-4699-a903-95acd89b0706 |  |
| 2023-02-07T11:51:41Z | chime:AttendeeAdded | ONEWT00099 | 63dc7822495f565af4004c9a | 77f56d8d-1ce3-4699-a903-95acd89b0706 | d2aacee9-12c9-3cba-1b20-1a2c341d6fe7 |
| 2023-02-07T11:51:49Z | chime:AttendeeAuthorized | ONEWT00099 | 63dc7822495f565af4004c9a | 77f56d8d-1ce3-4699-a903-95acd89b0706 | d2aacee9-12c9-3cba-1b20-1a2c341d6fe7 |
| 2023-02-07T11:51:50Z | chime:AttendeeJoined | ONEWT00099 | 63dc7822495f565af4004c9a | 77f56d8d-1ce3-4699-a903-95acd89b0706 | d2aacee9-12c9-3cba-1b20-1a2c341d6fe7 |
| 2023-02-07T11:54:48Z | chime:AttendeeAdded | ONEWT00095 | 63dc7822495f565af4004c9a | 77f56d8d-1ce3-4699-a903-95acd89b0706 | a458f719-774e-6dec-9aa3-b11eb547e990 |
| 2023-02-07T11:54:58Z | chime:AttendeeAuthorized | ONEWT00095 | 63dc7822495f565af4004c9a | 77f56d8d-1ce3-4699-a903-95acd89b0706 | a458f719-774e-6dec-9aa3-b11eb547e990 |
| 2023-02-07T11:55:00Z | chime:AttendeeJoined | ONEWT00095 | 63dc7822495f565af4004c9a | 77f56d8d-1ce3-4699-a903-95acd89b0706 | a458f719-774e-6dec-9aa3-b11eb547e990 |
| 2023-02-07T11:58:29Z | chime:AttendeeAdded | ss8561585 | 63dc7822495f565af4004c9a | 77f56d8d-1ce3-4699-a903-95acd89b0706 | e4bbd466-1ffe-9ac3-3a2c-9ce10463c431 |
| 2023-02-07T11:58:44Z | chime:AttendeeAuthorized | ss8561585 | 63dc7822495f565af4004c9a | 77f56d8d-1ce3-4699-a903-95acd89b0706 | e4bbd466-1ffe-9ac3-3a2c-9ce10463c431 |
| 2023-02-07T11:58:47Z | chime:AttendeeVideoStarted | ss8561585 | 63dc7822495f565af4004c9a | 77f56d8d-1ce3-4699-a903-95acd89b0706 | e4bbd466-1ffe-9ac3-3a2c-9ce10463c431 |
| 2023-02-07T11:58:48Z | chime:AttendeeVideoStopped | ss8561585 | 63dc7822495f565af4004c9a | 77f56d8d-1ce3-4699-a903-95acd89b0706 | e4bbd466-1ffe-9ac3-3a2c-9ce10463c431 |
| 2023-02-07T11:58:58Z | chime:AttendeeAdded | ff267497f79c4d22aec52b9cac3c0242 | 63dc7822495f565af4004c9a | 77f56d8d-1ce3-4699-a903-95acd89b0706 | 0424a77c-846e-9a9c-2a50-a922865f3774 |
| 2023-02-07T11:59:02Z | chime:AttendeeAuthorized | ff267497f79c4d22aec52b9cac3c0242 | 63dc7822495f565af4004c9a | 77f56d8d-1ce3-4699-a903-95acd89b0706 | 0424a77c-846e-9a9c-2a50-a922865f3774 |
| 2023-02-07T11:59:05Z | chime:AttendeeJoined | ff267497f79c4d22aec52b9cac3c0242 | 63dc7822495f565af4004c9a | 77f56d8d-1ce3-4699-a903-95acd89b0706 | 0424a77c-846e-9a9c-2a50-a922865f3774 |
| 2023-02-07T12:04:46Z | chime:AttendeeLeft | ONEWT00095 | 63dc7822495f565af4004c9a | 77f56d8d-1ce3-4699-a903-95acd89b0706 | a458f719-774e-6dec-9aa3-b11eb547e990 |
| 2023-02-07T12:15:13Z | chime:AttendeeLeft | ONEWT00099 | 63dc7822495f565af4004c9a | 77f56d8d-1ce3-4699-a903-95acd89b0706 | d2aacee9-12c9-3cba-1b20-1a2c341d6fe7 |
| 2023-02-07T12:17:58Z | chime:AttendeeDropped | ff267497f79c4d22aec52b9cac3c0242 | 63dc7822495f565af4004c9a | 77f56d8d-1ce3-4699-a903-95acd89b0706 | 0424a77c-846e-9a9c-2a50-a922865f3774 |
| 2023-02-07T12:23:42Z | chime:MeetingEnded |  | 63dc7822495f565af4004c9a | 77f56d8d-1ce3-4699-a903-95acd89b0706 |  |
---

### How can the documentation be improved to help your use case?

*For example: Include a section on how to configure the meeting session.*

### What documentation have you looked at so far?
https://docs.aws.amazon.com/chime-sdk/latest/dg/using-events.html

**Comment by xuesichao** [comment]
Hi @samchienGG, sorry for late reply. It is expected to receive the `AttendeeJoined` event. Our team is debugging this issue.

**Comment by xuesichao** [comment]
@samchienGG I see we published `AttendeeJoinedConference` event for attendee `ss8561585 (e4bbd466-1ffe-9ac3-3a2c-9ce10463c431)`. Could you check the CloudWatch log again? Sometimes there might be a delay.

```
| Time              | Attendee                                      | Event                         |
| ----------------- | --------------------------------------------- | ----------------------------- |
| 02/07/23 03:58:29 | VoIP 3 (e4bbd466-1ffe-9ac3-3a2c-9ce10463c431) | SdkAttendeeAdded              |
| 02/07/23 03:58:44 | VoIP 3 (e4bbd466-1ffe-9ac3-3a2c-9ce10463c431) | AttendeeJoinedConference      |
| 02/07/23 03:58:44 | VoIP 3 (e4bbd466-1ffe-9ac3-3a2c-9ce10463c431) | VideoConnectionStarted        |
| 02/07/23 03:58:47 | VoIP 3 (e4bbd466-1ffe-9ac3-3a2c-9ce10463c431) | VideoStarted                  |
| 02/07/23 03:58:47 | VoIP 3 (e4bbd466-1ffe-9ac3-3a2c-9ce10463c431) | VideoConnectionServiceChanged |
```

**Comment by devalevenkatesh** [comment]
Closing this issue due to no further response, please feel free to re-open if you have further information.
