### ISSUE TITLE
IN chime SDK  Broadcast Media to IVS show playback URL undefined

### ISSUE THREAD

**Issue by maheshwari-siddharth** [aws/amazon-chime-sdk-js#2599]
We are facing issue while click Broadcast Media to IVS although it is creating a IVS channel but it doesn't show the playback URL.

![image](https://user-images.githubusercontent.com/64456962/222137958-24644776-a716-423c-ac7f-9d67ecda9cdb.png)

Please advise 

Siddharth Maheshwari

**Comment by LeviSklaroff** [comment]
Could you please provide the browser console logs and any errors that might be occuring.

**Comment by maheshwari-siddharth** [comment]
we are facing below error in browser console

https://xxx.execute-api.us-east-1.amazonaws.com/Prod/startLiveConnector?title=dddddddd Failed to load resource: the server responded with a status of 502 ()

here is a complete log of browser console

https://www.dropbox.com/s/atx9khj1wf7sf5f/after%20broadcast%20to%20IVS%20click.png?dl=0

Please advise

**Comment by pathakkrunal** [comment]
Hi @LeviSklaroff 
I am facing same issue.

please advice, 
thank you

**Comment by yuqiaoliang** [comment]
Hi,
The issue that you are not able to see the playback url is because the live connector pipeline is not created correctly. Please follow this [API Reference](https://docs.aws.amazon.com/chime-sdk/latest/APIReference/API_media-pipelines-chime_CreateMediaLiveConnectorPipeline.html) to create live connector pipeline.

Thanks

**Comment by pathakkrunal** [comment]
Hi @yuqil-amzn 

I have followed bellow link 
https://github.com/aws/amazon-chime-sdk-js/tree/main/demos/serverless

I have not changed any code on it 
I am beginner can you please tell me file name where to change the code

Thank you

**Comment by yuqil-amzn** [comment]
playback URL is part of the ivs createChannel response. From the screenshot you provided, ivs failed to create the channel and thus you see playback url undefined. Could you share more logs to us so that we can further investigate?

**Comment by maheshwari-siddharth** [comment]
It is creating a channel in IVS but it doesn't show the URL in chime meeting and error is playback URL is undefined.

which log you are asking and where we can find that log

please advise.

**Comment by yuqil-amzn** [comment]
If you were using Chrome, you can find the log by opening developer tool -> console tab.

**Comment by maheshwari-siddharth** [comment]
below is a Logs 

INIT_START Runtime Version: nodejs:14.v29	Runtime Version ARN: arn:aws:lambda:us-east-1::runtime:be6b7a67cb4533b2e602f284c4e4105815581b5879c71929b33e71c124b81d

START RequestId: d27072fe-cab5-4712-a6aa-3b3b27134a Version: $LATEST

END RequestId: d27072fe-cab5-4712-a6aa-3b3b27134a

REPORT RequestId: d27072fe-cab5-4712-a6aa-3b3b27134a	Duration: 717.24 ms	Billed Duration: 718 ms	Memory Size: 128 MB	Max Memory Used: 84 MB	Init Duration: 646.13 ms	

Thanks
