### ISSUE TITLE
Upcoming changes to ExternalMeetingId and ExternalUserId

### ISSUE THREAD

**Issue by dnnejo** [aws/amazon-chime-sdk-js#2601]
There are two upcoming changes in the Amazon Chime SDK that may affect your application:

1. We are changing the values you can use for `ExternalMeetingId` and `ExternalUserId`
2. We are changing the `ExternalUserId` values used by media pipelines.

### Change 1
We are adding pattern matching to validate the values used for `ExternalMeetingId` and `ExternalUserId`.

An `ExternalMeetingId` is a builder-defined value associated with an Amazon Chime SDK meeting.  The value is specified when the meeting is created with one of the following APIs:

* [`CreateMeeting`](https://docs.aws.amazon.com/chime-sdk/latest/APIReference/API_meeting-chime_CreateMeeting.html) [1]
* [`CreateMeetingWithAttendees`](https://docs.aws.amazon.com/chime-sdk/latest/APIReference/API_meeting-chime_CreateMeetingWithAttendees.html) [2]

An `ExternalUserId` is a builder-defined value associated with an Amazon Chime SDK meeting attendee.  The value is specified when the attendee is created with one of the following APIs:

* [`CreateAttendee`](https://docs.aws.amazon.com/chime-sdk/latest/APIReference/API_meeting-chime_CreateAttendee.html) [3]
* [`BatchCreateAttendee`](https://docs.aws.amazon.com/chime-sdk/latest/APIReference/API_meeting-chime_BatchCreateAttendee.html) [4]
* [`CreateMeetingWithAttendees`](https://docs.aws.amazon.com/chime-sdk/latest/APIReference/API_meeting-chime_CreateMeetingWithAttendees.html) [2]

The allowed values for `ExternalMeetingId` and `ExternalUserId` are changing to only include values that meet all of the following criteria:

1. Length Constraints: Minimum length of 2. Maximum length of 64.
2. Pattern: `[-_&@+=,(){}\[\]\/«».:|'"#a-zA-Z0-9À-ÿ\s]*`
3. Values that begin with `aws:` are reserved.  You can't configure a value that uses this prefix (case insensitive).

To align with the updated criteria, you should review your code and update the values for `ExternalMeetingId` and `ExternalUserId`.

We plan to make the change active for existing customers on **March 30, 2023**. However, we will confirm that you have updated your application before applying the change to API calls from your AWS account.

### Change 2
We are changing the `ExternalUserId` values used by media pipelines.

Media pipelines send the contents of a meeting to another AWS service.  A media pipeline joins the meeting as an attendee.  The service will automatically create the attendee for the media pipeline when one of the following APIs is called:

* [`CreateMediaCapturePipeline`](https://docs.aws.amazon.com/chime-sdk/latest/APIReference/API_media-pipelines-chime_CreateMediaCapturePipeline.html) [5]
* [`CreateMediaLiveConnectorPipeline`](https://docs.aws.amazon.com/chime-sdk/latest/APIReference/API_media-pipelines-chime_CreateMediaLiveConnectorPipeline.html) [6]

The media pipeline attendees are changing to use `ExternalUserId` values beginning with `aws:`.  

To align with the updated values, you should review your code and update any logic that refers to the value of `ExternalUserId` for a media pipeline.

This change will become active on **March 30, 2023**.

If you have any questions or concerns, please contact AWS Support [7].

[1] https://docs.aws.amazon.com/chime-sdk/latest/APIReference/API_meeting-chime_CreateMeeting.html
[2] https://docs.aws.amazon.com/chime-sdk/latest/APIReference/API_meeting-chime_CreateMeetingWithAttendees.html
[3] https://docs.aws.amazon.com/chime-sdk/latest/APIReference/API_meeting-chime_CreateAttendee.html
[4] https://docs.aws.amazon.com/chime-sdk/latest/APIReference/API_meeting-chime_BatchCreateAttendee.html
[5] https://docs.aws.amazon.com/chime-sdk/latest/APIReference/API_media-pipelines-chime_CreateMediaCapturePipeline.html
[6] https://docs.aws.amazon.com/chime-sdk/latest/APIReference/API_media-pipelines-chime_CreateMediaLiveConnectorPipeline.html
[7] https://aws.amazon.com/support

**Comment by dnnejo** [comment]
These changes are now in effect for all customers.

**Comment by tkulis** [comment]
ok I see that is falling for balkan names, so we need to strip the names here?
Really?
![image](https://github.com/aws/amazon-chime-sdk-js/assets/8543254/16daf1ed-df5a-4e26-9539-aec03f10643c)

![image](https://github.com/aws/amazon-chime-sdk-js/assets/8543254/7d8f996f-8409-456f-8c3c-677cb30652c9)
