### ISSUE TITLE
Chime SDK browser demo

### ISSUE THREAD

**Issue by maheshwari-siddharth** [aws/amazon-chime-sdk-js#2604]
We are facing chime SDKs browser demo when we run from localhost  below is a browser console error

**POST http://localhost/amazon-chime-sdk-js-main/demos/browser/dist/meetingV2.html/join?title=text&name=Krunal&region=ap-south-1&ns_es=false 404 (Not Found)**

we are using below demo

 https://github.com/aws/amazon-chime-sdk-js/tree/main/demos/browser 

Thanks

**Comment by timanderson** [comment]
Did you follow all the directions in the readme? For example it runs by default on port 8080.

**Comment by maheshwari-siddharth** [comment]
Yes it works on IP address with 8080 port when NPM is start but when we build it doesn't run from through meetingv2.html in that case how we can install on ec2 instance 

Thanks

**Comment by ltrung** [comment]
@maheshwari-siddharth Can you put more details on your use case? 
The demo is only supported to run either locally (with port 8080) in your computer or through [Lambda serverless](https://github.com/aws/amazon-chime-sdk-js/tree/main/demos/serverless). We have not setup one for running in EC2 but I assume you have to expose port 8080 public in your EC2 and have a dns that routes to your EC2 link.

**Comment by devalevenkatesh** [comment]
Resolving this issue due to no update, please feel free to re-open as needed.
