### ISSUE TITLE
createMediaCapturePipeline does not return MediaPipelineArn

### ISSUE THREAD

**Issue by kazinayem2011** [aws/amazon-chime-sdk-js#2605]
> ChimeSDKMediaPipelines
> ```

@xuesichao Please help.
**createMediaConcatenationPipeline** requires **MediaPipelineArn**
Where should I get **MediaPipelineArn**? Using aws-sdk version: 2.1216.0

The object I get from **createMediaCapturePipeline** is:

`{
MediaPipelineId: '0794b981-81c4-4e19-b71a-91389cbdba94',
SourceType: 'ChimeSdkMeeting',
SourceArn: 'arn:aws:chime::[Account_ID]:meeting:bf14896e-2baf-43d5-bc20-ab7c9be70706',
Status: 'Initializing',
SinkType: 'S3Bucket',
SinkArn: 'arn:aws:s3:::[BUCKET_NAME]',
CreatedTimestamp: '2023-03-08T07:23:46.520Z',
UpdatedTimestamp: '2023-03-08T07:23:46.609Z',
ChimeSdkMeetingConfiguration: {
    ArtifactsConfiguration: { Audio: [Object], Video: [Object], Content: [Object] }
  }
}
`

Here is the response object from SDK. No **MediaPipelineArn** resides here.

<img width="840" alt="Screenshot 2023-03-09 at 10 09 41 AM" src="https://user-images.githubusercontent.com/19172630/223915126-a3999cee-58ef-4d6a-8aee-389393a9bc23.png">

_Originally posted by @kazinayem2011 in https://github.com/aws/amazon-chime-sdk-js/issues/2525#issuecomment-1459668608_

**Comment by nehtambe** [comment]
@kazinayem2011 'MediaPipelineArn'  is added in new namespace https://docs.aws.amazon.com/chime-sdk/latest/APIReference/API_media-pipelines-chime_MediaCapturePipeline.html 
It's not present in old namespace "Chime" https://docs.aws.amazon.com/chime/latest/APIReference/API_CreateMediaCapturePipeline.html

Can you switch to using Amazon Chime SDK.

**Comment by kazinayem2011** [comment]
> @kazinayem2011 'MediaPipelineArn' is added in new namespace https://docs.aws.amazon.com/chime-sdk/latest/APIReference/API_media-pipelines-chime_MediaCapturePipeline.html It's not present in old namespace "Chime" https://docs.aws.amazon.com/chime/latest/APIReference/API_CreateMediaCapturePipeline.html
> 
> Can you switch to using Amazon Chime SDK.

you mean to use MediaCapturePipeline replacing createMediaCapturePipeline?

**Comment by nehtambe** [comment]
Yes, correct, use the new "ChimeSdkMediaPipelines". You can follow more details on this page - https://docs.aws.amazon.com/chime-sdk/latest/dg/migrate-pipelines.html, about migrating from "Chime" to "ChimeSdkMediaPipelines".

**Comment by anuranduttaroy** [comment]
Closing this issue since the query was answered in the previous comment. @kazinayem2011 feel free to re-open the issue if you have more questions about the same.
