### ISSUE TITLE
Chime SDK Javascript Audio Output not working on amazon android app

### ISSUE THREAD

**Issue by gothtime518** [aws/amazon-chime-sdk-js#2607]
not sure if it is a known issue. We are amazon internal team and trying to build an application to be used in amazon android app. However the audio is not working(can not hear others in amazon android app). The audio is working fine on IOS device and other android browsers(chrome/edge). But not working on Amazon android app(the camera was working fine, only audio output not working). Can someone help us it is blocking our development for days. Thanks!

**Comment by michhyun1** [comment]
Please open a support ticket within AWS support for Chime SDK/Mobile SDK depending on your use case.

**Comment by michhyun1** [comment]
Can you clarify if the use case is for Chime SDK or the android mobile sdk(https://github.com/aws/amazon-chime-sdk-android)

**Comment by michhyun1** [comment]
If you are building a browser app, can you verify the browser you are using? Make sure it is a [supported browser.](https://docs.aws.amazon.com/chime/latest/ug/chime-requirements.html)
