### ISSUE TITLE
Unable to override meetingSessionConfiguration

### ISSUE THREAD

**Issue by shriyajuneja** [aws/amazon-chime-sdk-js#2612]
### What happened and what did you expect to happen?

I'm trying to override reconnectionTimeoutMs, and connectionTimeoutMs in meetingSessionConfiguration. Its mentioned in FAQs that these properties are configurable - https://github.com/aws/amazon-chime-sdk-js/blob/main/guides/07_FAQs.md#what-is-the-timeout-for-connect-and-reconnect-and-where-can-i-configure-the-value 
But these values are not read by constructor from createMeetingResponse (ref: https://github.com/aws/amazon-chime-sdk-js/blob/main/src/meetingsession/MeetingSessionConfiguration.ts#L52)

I would also like to confirm if its fine to change reconnectionTimeoutMs and connectionTimeoutMs  to 30 seconds and 5 seconds respectively.

### Have you reviewed our existing documentation?

- [X] GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [X] FAQs [page](https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html)
- [X] README [page](https://github.com/aws/amazon-chime-sdk-js#amazon-chime-sdk-for-javascript)
- [X] Feature-specific [guides](https://github.com/aws/amazon-chime-sdk-js#guides)

### Reproduction steps

```
 const meetingSessionConfiguration = new MeetingSessionConfiguration(
        { ...meetingInfo, connectionTimeoutMs: 5000, reconnectTimeoutMs: 30000 },
        attendeeInfo
      );
```

### Amazon Chime SDK for JavaScript version

3.10.0

### What browsers are you seeing the problem on?

Chrome

### Browser version

111

### Meeting and Attendee ID Information.

meetingId: "8fe55145-76d6-4159-b303-a9c945be0706"
participantId: "4ed43aab-f0f6-c363-3e1f-746c844c69b5"

### Browser console logs

NA

**Comment by xuesichao** [comment]
Hi @shriyajuneja , yes those properties are not in `MeetingSessionConfiguration`'s constructor.
You can overwrite properties in this way:
```js
const configuration = new MeetingSessionConfiguration(createMeetingResponse, createAttendeeResponse);
configuration.connectionTimeoutMs = 5 * 1000;
configuration.reconnectTimeoutMs = 30 * 1000;

const meetingSession = new DefaultMeetingSession(
  configuration,
  logger,
  deviceController,
  eventReporter // Optional
);
```

A 30 s reconnect timeout and a 5 s connection timeout seem reasonable to me. If you find they are too strict for your users, you can always set them longer.

**Comment by shriyajuneja** [comment]
works, thanks!
