### ISSUE TITLE
Send message to a specific attendee

### ISSUE THREAD

**Issue by kazinayem2011** [aws/amazon-chime-sdk-js#2614]
I am trying to send a notification to a specific attendee(not to all attendees).
I already used **realtimeSendDataMessage** which sends messages to all attendees using a Topic.

Another query is to **chat** privately with the attendee **individually**. Already explored messaging SDK which is very complex integrating with the meeting app. Could you please guide me on this?

Note: I am trying to make a meeting app with a **private** chat(not group chat) feature with attendees using chime SDK JS and Vue JS.

Stuck on this.

**Comment by dpwspoon** [comment]
This blog talks about buildings meetings SDK into a messaging application: https://aws.amazon.com/blogs/business-productivity/build-meeting-features-into-your-amazon-chime-sdk-messaging-application/.

You are sort of doing the opposite; i.e. adding messaging to existing meetings app.  To familiarize your self with SDK I would suggest looking at the getting started: https://docs.aws.amazon.com/chime-sdk/latest/dg/getting-started.html.  That should familiarize yourself with the concepts.

The difference between meetings and messaging is that meetings don't have a consistent identity (i.e. attendee is different for same user in every meeting).  For messaging/chat there is a concept of an app instance user that can be long lived.

If you want long lived identities I would probably follow the blog post above and related demos.  If instead you want to stick with the meeting concept of identity being per a meeting, I think you would want to do the following at a high level (lots of possible alternatives in details of implementation): 

1) Create an AppInstance and optionally AppInstanceAdmin (see getting started guide for details).
2) On creation of meeting create an app instance user for each attendee.  Note expiration settings as a parameter of CreateUser; use these to automatically clean up users at reasonable time.  (https://docs.aws.amazon.com/chime-sdk/latest/APIReference/API_identity-chime_CreateAppInstanceUser.html)
3) When giving the meeting join token to the users also return IAM creds to the users with MessagingSDK permissions. (See permissions in messaging getting started.  This might be a call to STS assume role).
4) Have AppInstanceUsers connect to get realtime updates.  (See connect in messaging getting started)
5) On API call to your system or via permissions in IAM creds [CreateChannel](https://docs.aws.amazon.com/chime-sdk/latest/APIReference/API_messaging-chime_CreateChannel.html) with subset of users for private chats.  Again note expiration settings as a parameter to auto clean these up after reasonable time.  Also not the members field on the API to add all members at once.  If you do it on an API call you implement you will likely use the AppInstanceAdmin to create the channel.  If you have the end users create the channel you will need a way to share which AppInstanceUsers match to which attendee id's in the meeting, for this probably just create the app instance users with the same attendee id.

**Comment by kazinayem2011** [comment]
> 

Please give some references on how to integrate the front-end using JS like aws-chime-sdk-js

**Comment by dpwspoon** [comment]
This demo gives you a real time connection to send messages on (using aws-chime-sdk-js): https://github.com/aws/amazon-chime-sdk-js/tree/main/demos/browser/app/messagingSession

This javascript library gives you access to the REST APIs: https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-chime-sdk-messaging/

This blog outlines your different options to get credentials to clients to make the API calls up above (https://aws.amazon.com/blogs/business-productivity/integrate-your-identity-provider-with-amazon-chime-sdk-messaging/)

**Comment by kazinayem2011** [comment]
> This demo gives you a real time connection to send messages on (using aws-chime-sdk-js): https://github.com/aws/amazon-chime-sdk-js/tree/main/demos/browser/app/messagingSession
> 

getting error **Messaging Session failed to resolve endpoint: TypeError: t.endpoint is not a function**
Another question: userArn means **attendeeId** and sessionId means **JoinToken** when creating attendee??

**Comment by kazinayem2011** [comment]
> 

@dpwspoon Stuck on this. Help will be appreciated.

**Comment by kazinayem2011** [comment]
> > This demo gives you a real time connection to send messages on (using aws-chime-sdk-js): https://github.com/aws/amazon-chime-sdk-js/tree/main/demos/browser/app/messagingSession
> 
> Using
> 
> ```
> "@aws-sdk/client-chime-sdk-messaging": "^3.47.0",
>     "amazon-chime-sdk-js": "3.13.0",
>     "aws-sdk": "^2.1348.0",
> ```
> 
> getting error **Messaging Session failed to resolve endpoint: TypeError: t.endpoint is not a function** and I**NFO] SDK - WebSocket close: 4999 Failed to get messaging session endpoint URL**
> 
> So, What is **endpointURL** to **undefined** which I found inside **this.configuration = new MessagingSessionConfiguration(this.userArn, this.sessionId, undefined, chime);**
> 
> And getting response from **MessagingSessionConfiguration** is below and here **endpointUrl** is also undefined:
> 
> `{ "userArn": "3744cdb2-84fc-6b25-6410-aa11f3bbe38f", "messagingSessionId": "Mzc0NGNkYjItODRmYy02YjI1LTY0MTAtYWExMWYzYmJlMzhmOjFhMGE2ZjhkLWEwZDAtNDkzNi1iNDcyLTJmNTQyYWE5NmRlNw", "endpointUrl": undefined, "chimeClient": { "middlewareStack": {}, "config": { "apiVersion": "2021-05-15", "disableHostPrefix": false, "logger": {}, "serviceId": "Chime SDK Messaging", "runtime": "browser", "requestHandler": { "configProvider": {} }, "defaultSigningName": "chime", "tls": true, "isCustomEndpoint": false, "systemClockOffset": 0, "signingEscapePath": true } }, "reconnectTimeoutMs": 10000, "reconnectFixedWaitMs": 0, "reconnectShortBackoffMs": 1000, "reconnectLongBackoffMs": 5000, "prefetchOn": "connect", "prefetchSortBy": "unread" }`
> 
> Another question: userArn means **attendeeId** and sessionId means **JoinToken** when creating attendee??

> 

I solved the issue using **AppInstanceUser** as **userArn** but I had to create it additionally. 

Now another question arises. How to send messages? Should I have to use a channel?? Demo shows only receiving message.

**Comment by kazinayem2011** [comment]
> 

Ah! You guys are so busy! :)

**Comment by dpwspoon** [comment]
> So far I understood, AppInstanceUser is related to the channel messages. This means I have to make private chat using channel. Am I correct? If not, What kind of message does messagingSession receive? Is it a channel message or others(if any)?

You are correct,  The Messaging Session is not tied to the Meeting SDK messages.

**Comment by dpwspoon** [comment]
Closing this for now.  Let us know if anything we can help with
