### ISSUE TITLE
Video and screen share does not work in Amazon chime

### ISSUE THREAD

**Issue by KK890** [aws/amazon-chime-sdk-js#2620]
It works in Webapp but not in Desktop Chime app
Chime Version :4.39.20018.0

**Comment by devalevenkatesh** [comment]
The Amazon Chime SDK for JavaScript (this repo) enables builders to build their own audio-video, screen sharing enabled applications. Amazon Chime app is a different application and not related to this repo. Could you please report your issue here: https://answers.chime.aws/?

Closing this now.
