### ISSUE TITLE
How to get the meeting usage details for each meeting during and at the end of the meeting?

### ISSUE THREAD

**Issue by hkmsadek** [aws/amazon-chime-sdk-js#2626]
I am trying to figure out how can we get the usage metrics using api or in dashboard. We need to charge our customers for using this features and for this we need to know and show them how many attendee-minutes they have used. How can we get it?

**Comment by devalevenkatesh** [comment]
You can implement Amazon Chime SDK server side meeting events mechanism to understand the usage. Linking few helpful resources around that:
- https://aws.amazon.com/blogs/business-productivity/server-side-logging-and-monitoring-of-amazon-chime-sdk-events/
- https://docs.aws.amazon.com/chime-sdk/latest/dg/using-events.html
- This is client based: https://aws.amazon.com/blogs/business-productivity/monitoring-and-troubleshooting-with-amazon-chime-sdk-meeting-events/


Please let us know if you have further questions.

**Comment by ltrung** [comment]
We also have usage metrics and service metrics https://docs.aws.amazon.com/chime-sdk/latest/dg/usage-metrics.html but they only have call counts right now. 
For now, you would have to manually calculate it using event bridge (the time difference between attendee joins and leaves).
