### ISSUE TITLE
Return specific errors for TaskFailed errors

### ISSUE THREAD

**Issue by simmkyu** [aws/amazon-chime-sdk-js#263]
Chime SDK throws a general error `TaskFailed` when [MeetingSessionStatusCode](https://github.com/aws/amazon-chime-sdk-js/blob/master/src/meetingsession/MeetingSessionStatusCode.ts) doesn't have a corresponding status. Since the release, we observed that SDK had stopped the session with `TaskFailed` in the following cases:
- A task in [src/task](https://github.com/aws/amazon-chime-sdk-js/tree/master/src/task) has an uncaught error
  e.g. `Cannot read property '__property_name__' of undefined`.
- The connection is timed out after 15 seconds (default).
- SDK fails to reconnect the session after multiple retries.

We should add new status codes for these common cases.

**Comment by kaaaren** [comment]
Fix https://github.com/aws/amazon-chime-sdk-js/pull/581 is merged, closing this issue
