### ISSUE TITLE
Meeting Creation using Reactjs

### ISSUE THREAD

**Issue by NaveenVinayakS** [aws/amazon-chime-sdk-js#2650]
### What happened and what did you expect to happen?

i am trying to build chime SDK using React js but i am not able to create meeting using react js, which is done in nodejs, can some one help me in this.

### Have you reviewed our existing documentation?

- [X] GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [X] FAQs [page](https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html)
- [X] README [page](https://github.com/aws/amazon-chime-sdk-js#amazon-chime-sdk-for-javascript)
- [X] Feature-specific [guides](https://github.com/aws/amazon-chime-sdk-js#guides)

### Reproduction steps

i am trying to build chime SDK using React js but i am not able to create meeting using react js, which is done in nodejs, can some one help me in this

### Amazon Chime SDK for JavaScript version

main

### What browsers are you seeing the problem on?

chrome

### Browser version

112.0.5615.138

### Browser console logs

LOG

**Comment by xuesichao** [comment]
@NaveenVinayakS Could you provide us more details of why you are not able to create meeting? 
And for react development we have [Amazon Chime SDK React Components Library](https://github.com/aws/amazon-chime-sdk-component-library-react) which makes it easier for building a react application. Here's a demo application that is built with this component library:https://github.com/aws-samples/amazon-chime-sdk/tree/main/apps/meeting

**Comment by ltrung** [comment]
Close due to inactivity but feel free to reopen and provide an error message or logs that you have
