### ISSUE TITLE
Node v20 compatibility

### ISSUE THREAD

**Issue by everscending** [aws/amazon-chime-sdk-js#2654]
# Community Note
* Please vote for this issue by adding a 👍 reaction to the issue. This will help the community and maintainers from the Amazon Chime SDK team to prioritize this request.
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request.
* Please go through the existing [issues](https://github.com/aws/amazon-chime-sdk-js/issues) to see if your request has already been recommended.
* Please do not use this template for bugs or support. Each individual repository has a PR template, documentation and resources for [troubleshooting](https://github.com/aws/amazon-chime-sdk-js#troubleshooting-and-support).
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.

# Tell us about your request

After upgrading to Node v20 and run npm ci in my project, I get the following errors indicating Node v20 is not supported by either amazon-chime-sdk-js or amazon-chime-component-library-react packages.  My request is to make these SDKs compatible w Node v20.  Is this on the roadmap yet? Thanks

npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'amazon-chime-sdk-component-library-react@3.6.0',
npm WARN EBADENGINE   required: { node: '^12 || ^14 || ^15 || ^16 || ^18', npm: '^6 || ^7 || ^8' },
npm WARN EBADENGINE   current: { node: 'v20.0.0', npm: '9.6.4' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'amazon-chime-sdk-js@3.13.0',
npm WARN EBADENGINE   required: {
npm WARN EBADENGINE     node: '^12 || ^14 || ^15 || ^16 || ^18 || ^19',
npm WARN EBADENGINE     npm: '^6 || ^7 || ^8 || ^9'
npm WARN EBADENGINE   },
npm WARN EBADENGINE   current: { node: 'v20.0.0', npm: '9.6.4' }
npm WARN EBADENGINE }

**Comment by j0d0nn** [comment]
PR #2827 should have closed this, @ltrung .

**Comment by ziyiz-amzn** [comment]
This bug has been fixed in version v3.20.0. Please reopen or submit a support case if this is still an issue.
