### ISSUE TITLE
Need help to creating chatbot in Amazon chime

### ISSUE THREAD

**Issue by NeethithevanR** [aws/amazon-chime-sdk-js#2657]
I have used Bot framework composer (Version: 2.1.2) dotnet to build my bot. I have implemented chatbot in few channels(Teams, Skype, Slack, Webex, etc). Now I want to implement a chatbot in Amazon Chime channel. As per the documentation I read, we can implement Amazon chime chatbot using a direct line branding (https://learn.microsoft.com/en-us/azure/bot-service/bot-service-channel-directline).

1. Is it the only possible way to create Amazon chime chatbot? 
2. Is there any other alternative available to implement the Amazon chime chatbot? (Please share me the documentation link.)

  **Important Note:** I don't use the Azure Bot Service to deploy my bot in Azure. I deploy and run my bot in my host as a dotnet service

**Comment by devalevenkatesh** [comment]
Thanks for the issue, this repo provides Amazon Chime SDK for JavaScript to build real-time audio, video and content sharing applications (similar to Amazon Chime app, but, it is not related to Amazon Chime app). It is different from the Amazon Chime application. I am linking few links that can help:
1. https://docs.aws.amazon.com/chime/index.html
2. https://docs.aws.amazon.com/chime/latest/ag/chat-bots.html
3. https://aws.amazon.com/blogs/business-productivity/build-custom-chat-bots-for-amazon-chime/ (Blog post that walks through creating a custom chat bot to integrate with Amazon Chime app.
4. https://answers.chime.aws/

I am closing this issue now, and you would have to go through AWS support or link 4 above for more information. If I got it wrong and you are trying to achieve it using Amazon Chime SDK for JavaScript, please feel free to re-open this issue with further questions.
