### ISSUE TITLE
Mobile video Black Tile issue

### ISSUE THREAD

**Issue by jumcclure** [aws/amazon-chime-sdk-js#2662]
### What happened and what did you expect to happen?

We are experiencing a problem where a black video tile appears in video meetings under the following circumstances:

1. when multiple participants join the meeting with their video turned on.
2. when someone leaves the meeting. 
3. pin the video of the person you want.  
4. choose to hide self-video view.

### Have you reviewed our existing documentation?

- [X] GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [X] FAQs [page](https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html)
- [X] README [page](https://github.com/aws/amazon-chime-sdk-js#amazon-chime-sdk-for-javascript)
- [X] Feature-specific [guides](https://github.com/aws/amazon-chime-sdk-js#guides)

### Reproduction steps

1. The screen re-rendered multiple times
2. SDK re-initialized all the videos and re-rendered them again.
3. Occasionally, black tiles appeared, app eventually crashed with the error message "unable to find node bind video." 
5. If other participants left, black tiles appeared

### Amazon Chime SDK for JavaScript version

Mobile SDK Android v0.17.10 / IOS v0.22.7

### What browsers are you seeing the problem on?

Mobile apps - android and IOS

### Browser version

Mobile apps - android and IOS

### Browser console logs

[chime_video_black_tile_logs_with_screenshots.zip](https://github.com/aws/amazon-chime-sdk-js/files/11490166/chime_video_black_tile_logs_with_screenshots.zip)

**Comment by devalevenkatesh** [comment]
Thanks for reporting the issue, this repo is actually for Amazon Chime SDK for JavaScript, for Android and iOS could you open the same issue?
https://github.com/aws/amazon-chime-sdk-android
https://github.com/aws/amazon-chime-sdk-ios
