### ISSUE TITLE
Incoming audio dropped for a few seconds, incoming audio/video desync or low volume

### ISSUE THREAD

**Issue by kelvin2200** [aws/amazon-chime-sdk-js#2664]
### What happened and what did you expect to happen?

We've had a lot of feedback from users lately that their audio drops for a few seconds in the meeting, and that there's a notable desync between incoming audio/video streams. Also a lot of users complain about the volume of incoming streams that seems to be very low on some occasions (we have autoGain enabled)

We've gathered some meeting id's.
Any information you could provide us would be helpful

### Have you reviewed our existing documentation?

- [X] GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [X] FAQs [page](https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html)
- [X] README [page](https://github.com/aws/amazon-chime-sdk-js#amazon-chime-sdk-for-javascript)
- [X] Feature-specific [guides](https://github.com/aws/amazon-chime-sdk-js#guides)

### Reproduction steps

Hard to reproduce

### Amazon Chime SDK for JavaScript version

3.13.0

### What browsers are you seeing the problem on?

Chrome

### Browser version

all

### Meeting and Attendee ID Information.

Meetings with audio delay
meetingId: fb98fc09-d891-46a5-9b1f-97a0f1b17979 - 23 May, 01:10PM(GMT+3)
meetingId: 055571e8-e569-4834-9d24-01ff0a8d7979 - 22May, 12:00(GMT+3)

Incoming sound dropped
meetingId: d50cfde4-84a7-47f3-ad35-90a9228a7979 12:30 PM (GMT+3) 
meetingId: 9ff1470b-c16f-4327-844d-0415c44d7979 - 24May - 7:00PM (GMT+3)
meetingId: 8e5746f5-96c8-486f-b514-d33934c27979 (25th may)

Meetings where audio streams had very low volume
meetingId: 704ccc72-ad8d-47b7-a315-6c40eba77979 - 23 May 2:35 PM (GMT+3)
meetingId: cb75ea6a-9f5b-475c-b753-e52b74297979 - 28 April 1:00 PM (GMT+3)

### Browser console logs

the logs don't show any errors

**Comment by michhyun1** [comment]
@kelvin2200 thanks for this issue.

Is this reproducible? I see some audio drop events on the meeting id:

meetingId: d50cfde4-84a7-47f3-ad35-90a9228a7979 12:30 PM (GMT+3)

Might need some browser logs if you can provide them - make sure they dont contain any confidential information

**Comment by majid20222** [comment]
Hi,

Facing similar issue on our side in which client has reported multiple times that audio signals drop and sometimes participant is not being heard by other participant. It was not reproduceable as it is sporadic and cannot provide browser logs. This issue need to be looked into.

Device on which Issue is reported: Windows 11

**Comment by ltrung** [comment]
Closing as this issue has been opened for a long time. @majid20222 please open a new one.
