### ISSUE TITLE
Active Speaker Meeting Event without attendee

### ISSUE THREAD

**Issue by swapnil0504** [aws/amazon-chime-sdk-js#2665]
### What happened and what did you expect to happen?

I am expecting that whenever I'm getting active speaker event in that I will get attendee id.

### Have you reviewed our existing documentation?

- [X] GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [X] FAQs [page](https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html)
- [X] README [page](https://github.com/aws/amazon-chime-sdk-js#amazon-chime-sdk-for-javascript)
- [X] Feature-specific [guides](https://github.com/aws/amazon-chime-sdk-js#guides)

### Reproduction steps

I'm using "amazon-chime-sdk-component-library-react: 3.2.0" and "amazon-chime-sdk-js : 3.5.0", to create chime meeting and capture chime events, later on I'm creating playback using ffmpeg.

In most of the playback I have noticed that some times I get blank screen but there is audio, after reviewing I have figured out that in ActiveSpeaker event sometimes I'am not getting attendee id.

How can I fix this any advise ?

### Amazon Chime SDK for JavaScript version

amazon-chime-sdk-js: 3.5.0

### What browsers are you seeing the problem on?

Chrome and Firefox

### Browser version

All

### Meeting and Attendee ID Information.

**Chime Meeting id:**

ed3d4d40-50ef-4ab4-8d98-7fe98c720706

**Events:**
`{"Timestamp":"2023-05-24T09:42:35.964+00:00","EventType":"ActiveSpeaker","EventParameters":{"AttendeeId":"","MediaModality":""}}`

`{"Timestamp":"2023-05-24T10:11:50.524+00:00","EventType":"ActiveSpeaker","EventParameters":{"AttendeeId":"","MediaModality":""}}`

### Browser console logs

NONE

**Comment by Kick933** [comment]
This is happening for me as well.

**Comment by swapnil0504** [comment]
NA

**Comment by telegu** [comment]
is fixed?
I have some event as you described, after the empty active speaker the attendee left
```
{"Timestamp":"2023-09-11T09:11:01.114+00:00","EventType":"ActiveSpeaker","EventParameters":{"AttendeeId":"","MediaModality":""}}
{"Timestamp":"2023-09-11T09:11:01.114+00:00","EventType":"AttendeeLeft","EventParameters":{"AttendeeId":"xxxxxxxxxxxx,"MediaModality":""}}
```
