### ISSUE TITLE
Is there a way to increase the FPS of the recording captured by the media capture pipeline

### ISSUE THREAD

**Issue by paul365** [aws/amazon-chime-sdk-js#2666]
### What are you trying to do?
Currently, recordings from media capture pipelines are at 15 fps. We would like to know if it is possible to increase it. Also, note we are using simulcast.

### How can the documentation be improved to help your use case?

Include a section on how the recording's fps is determined. And if possible, show how to change or configure it.

### What documentation have you looked at so far?

README.md, Amazon Chime SDK Developer Guide, Amazon Chime SDK FAQs, etc.

**Comment by sinanliuAmazon** [comment]
15 fps is a constant value, currently there's no option to configure this value.
