### ISSUE TITLE
Video helpdesk demo: After deleting API via API Gateway console, unable to redeploy

### ISSUE THREAD

**Issue by terrisgit** [aws/amazon-chime-sdk-js#267]
I was using the video helpdesk demo and decided to delete the API from the gateway overnight to avoid any potential security issues and AWS charges. Then I followed the readme exactly but I can no longer get the demo to add the API to the gateway. I tried multiple strategies for over an hour and gave up.

**Comment by aburnson** [comment]
@terrisgit since the API Gateway is part of a CloudFormation stack, try deleting the CloudFormation stack, which will clean up all associated resources. Then redeploy. This information is missing from README. We will get this added.

**Comment by anuranduttaroy** [comment]
Updated the README with cleanup instructions.
