### ISSUE TITLE
Camera switch not working on IOS devices 

### ISSUE THREAD

**Issue by dinuone** [aws/amazon-chime-sdk-js#2670]
```

 videoInputDevices.forEach(mediaDeviceInfo => {
   this.mediaDeviceList.push({id:mediaDeviceInfo.deviceId,label:mediaDeviceInfo.label})
    console.log(`Audio Input Device ID: ${mediaDeviceInfo.deviceId} Microphone: ${mediaDeviceInfo.label}`);
});
```

when I try to loop videoinputDevices its work on pc and android mobile but when i try to join meeting on IOS device we cant join into meeting

**Comment by michhyun1** [comment]
@dinuone  We would appreciate if you can provide more information.

Why do you need to loop through the videoInputDevices? 

And why is this related to joining a meeting? 

The more context you can provide, the easier it is for us to help!

**Comment by dinuone** [comment]
bcz i want access front and back camera that's why I loop though videoinputdevices. then i pass the selected device into this setinput function
 ```
async setInput(videoID,meetingSession){
      try{
        if(!videoID){
          this.showError =true
          this.msg = '"No video input detected."'
        }

        if (videoID) {
          const videoInputDevices = await meetingSession.audioVideo.listVideoInputDevices();
          if (videoInputDevices.length) {
            const defaultVideoId = videoInputDevices[0].deviceId;
            await meetingSession.audioVideo.startVideoInput(
                videoID === "default" ? defaultVideoId : videoID
            );
          }
        }
      }catch (err){
        this.showError =true
        this.msg = err
      }

    },
```

**Comment by michhyun1** [comment]
Okay - what is the issue? How does this prevent you from joining a meeting?

Also, have you checked out our [react component library](https://github.com/aws/amazon-chime-sdk-component-library-react)? We have components that can abstract out this logic for you.

Also, you can also check out the [JS SDK sample demo](https://github.com/aws/amazon-chime-sdk-js/tree/main/demos/browser) if you need some guidance on selecting a video input device.
