### ISSUE TITLE
Need more information on MeetingFailed error message

### ISSUE THREAD

**Issue by shriei2i** [aws/amazon-chime-sdk-js#2671]
### What are you trying to do?

We are capturing the errors that the end users are facing in the Cloudwatch and display them a user friendly error messages. But we could see certain errors that our users are facing does not have a clear explanation in the Chime SDK error documentation. Can you please provide the explanation for the below error:

meetingFailed:
serial group task AudioVideoUpdate/27564be1-a0b7-4371-9ae5-2c01df0a2713/e9324dd9-b2c6-6967-6d62-c2e6f7fa7d44 was canceled due to subtask AudioVideoUpdate/27564be1-a0b7-4371-9ae5-2c01df0a2713/e9324dd9-b2c6-6967-6d62-c2e6f7fa7d44/Timeout15000ms error: serial group task AudioVideoUpdate/27564be1-a0b7-4371-9ae5-2c01df0a2713/e9324dd9-b2c6-6967-6d62-c2e6f7fa7d44/Timeout15000ms/UpdateSession was canceled due to subtask AudioVideoUpdate/27564be1-a0b7-4371-9ae5-2c01df0a2713/e9324dd9-b2c6-6967-6d62-c2e6f7fa7d44/Timeout15000ms/UpdateSession/SetRemoteDescriptionTask error: AudioVideoUpdate/27564be1-a0b7-4371-9ae5-2c01df0a2713/e9324dd9-b2c6-6967-6d62-c2e6f7fa7d44/Timeout15000ms/UpdateSession/SetRemoteDescriptionTask got canceled while waiting for the ICE connection state

### How can the documentation be improved to help your use case?

It will be helpful if we understand the scenarios in which this error is thrown so that we will be able to form a user friendly error message for this error.

### What documentation have you looked at so far?

We are referring to the below Chime SDK documentations so far:
https://aws.github.io/amazon-chime-sdk-js/enums/meetingsessionstatuscode.html
https://aws.github.io/amazon-chime-sdk-js/modules/meetingevents.html#meeting-error-messages

**Comment by michhyun1** [comment]
There is an internal support ticket tracking this issue, so I'll go ahead and close this issue. Please track the internal support ticket. Thanks!
