### ISSUE TITLE
Meeting volume control on devices without SinkId

### ISSUE THREAD

**Issue by chuckntaylor** [aws/amazon-chime-sdk-js#2672]
### What are you trying to do?
Adjust the output (speaker) volume of the meeting on devices which do not support sinkId. While in many cases, the volume can be adjusted by modifying the volume of a bound audio element, this is not the case on devices that do not support sinkId - like iPhone or iPad.

In my particular application, the Chime SDK is being used within a game. As such, there are times where the players need to listen closely to other things going on in the game when trying to solve a puzzle, and being able to adjust the meeting volume is the ideal solution.

### How can the documentation be improved to help your use case?
IF it is at all possible to adjust the volume on a device without sinkId support, it would be great to know. I understand it may not be possible - even that would be good to know.

### What documentation have you looked at so far?
Amazon Chime SDK Developer Guide, GitHub issues - namely #1391

**Comment by hensmi-amazon** [comment]
That seems like a viable fix! We do something similar in our demo for testing audio input volume reduction. I'm not sure why it wouldn't work if `setSinkId` is available though...maybe is an unrelated issue.

Closing unless there are any followup questions.
