### ISSUE TITLE
Change Front & back camera on IOS devices

### ISSUE THREAD

**Issue by dinuone** [aws/amazon-chime-sdk-js#2673]
### What happened and what did you expect to happen?

camera changing is not work on ios devices. when we add camera changing code line then we can't join to the meeting on ios device. 

### Have you reviewed our existing documentation?

- [X] GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [X] FAQs [page](https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html)
- [X] README [page](https://github.com/aws/amazon-chime-sdk-js#amazon-chime-sdk-for-javascript)
- [X] Feature-specific [guides](https://github.com/aws/amazon-chime-sdk-js#guides)

### Reproduction steps

.

### Amazon Chime SDK for JavaScript version

3.8.0

### What browsers are you seeing the problem on?

Safari

### Browser version

16.5

### Browser console logs

we cannot see any browser logs in mobile device is there anyway to get console logs to our UI?

**Comment by michhyun1** [comment]
@dinuone We could use a lot more context.

It seems like you are having issues joining a meeting - have you checked out the [js sdk sample demo?](https://github.com/aws/amazon-chime-sdk-js/tree/main/demos/browser)

Joining a meeting and changing your camera should be two separate things, not sure how one impacts the other. Please clarify your use case and your workflow

**Comment by dinuone** [comment]
I found the issue when we trying to get list of audio output that return all of audio outputs. its work on android and pc but when we use IPhone then its return null so that is the issue

**Comment by michhyun1** [comment]
great - let us know if you have any other issues. Will close now
