### ISSUE TITLE
How to switch between front and back cameras?

### ISSUE THREAD

**Issue by dinuone** [aws/amazon-chime-sdk-js#2681]
currently I'm doing like this

```
async setInput(videoID,meetingSession){
      if (videoID) {
        const videoInputDevices = await meetingSession.audioVideo.listVideoInputDevices();
        if (videoInputDevices.length) {
          const defaultVideoId = videoInputDevices[0].deviceId;
          await meetingSession.audioVideo.startVideoInput(
              videoID === "default" ? defaultVideoId : videoID
          );
        }
      }

    },
```

I'm get the list of input video devices and pass the device id into this set input function. so now I need to Switch cameras between front and back without display the list of input video devices. I need to toggle button to do that

**Comment by xuesichao** [comment]
You could use the the `facingMode` attribute of the constraints of `getUserMedia` call.
https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getUserMedia#front_and_back_camera

The following will prefer the front camera (if one is available) over the rear one:

```
getUserMedia({
  video: { facingMode: "user" },
});
Copy to ClipboardCopy to Clipboard
```
To require the rear camera, use:
```
getUserMedia({
  video: {
    facingMode: { exact: "environment" },
  },
});
```
