### ISSUE TITLE
How to get remote participant audio track and local participant audio track?

### ISSUE THREAD

**Issue by dinuone** [aws/amazon-chime-sdk-js#2684]

**Comment by xuesichao** [comment]
Hi @dinuone , our [`startAudioInput` API](https://aws.github.io/amazon-chime-sdk-js/classes/defaultdevicecontroller.html#startaudioinput) returns the stream of requested device. So you can get local participant audio track in this way:
```
const mediaStream = await meetingSession.audioVideo.startAudioInput(audioInputDeviceInfo.deviceId);
```

But SDK does not have any API to get remote audio track at this time.
