### ISSUE TITLE
Media Capture Pipeline unreliable when multiple video streams are recorded in a meeting

### ISSUE THREAD

**Issue by Manuel-AWS** [aws/amazon-chime-sdk-js#2704]
### What happened and what did you expect to happen?

There is an issue when multiple video streams are recorded in a meeting.

The workaround temporarily suggested by AWS is to use composited video for the recording as per this blog post:
https://aws.amazon.com/blogs/business-productivity/capture-amazon-chime-sdk-meetings-using-media-capture-pipelines/

Such workaround does not allow to capture all attendees' video when content is shared. It only captures a maximum of 4. Additionally, this is not useful when the use case requires the individual video streams, for example when required for a custom way to compose them and to add content from outside of the meeting.

That means we currently have zero ways to reliably record all attendees in our meetings, which is one of the core features of our application.

### Have you reviewed our existing documentation?

- [X] GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [X] FAQs [page](https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html)
- [X] README [page](https://github.com/aws/amazon-chime-sdk-js#amazon-chime-sdk-for-javascript)
- [X] Feature-specific [guides](https://github.com/aws/amazon-chime-sdk-js#guides)

### Reproduction steps

Attempt to use Media Capture Pipeline to record multiple video streams in a Chime SDK video conference call.

### Amazon Chime SDK for JavaScript version

3.15.0

### What browsers are you seeing the problem on?

n/a

### Browser version

n/a

### Browser console logs

n/a

**Comment by anuranduttaroy** [comment]
Hey @Manuel-AWS, could you elaborate a bit on the issue that you are noticing when multiple video streams are recorded using Amazon Chime SDK Media Capture Pipelines?
