### ISSUE TITLE
Attendee could not hear one person in the meeting but other attendees could

### ISSUE THREAD

**Issue by evangeline** [aws/amazon-chime-sdk-js#2706]
### What happened and what did you expect to happen?

We had an unusual, one-off case where an attendee was unable to hear one specific person, even though everyone else in the meeting could. As we understand it Chime mixes all audio into one single track, so this is highly unexpected.

### Have you reviewed our existing documentation?

- [X] GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [X] FAQs [page](https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html)
- [X] README [page](https://github.com/aws/amazon-chime-sdk-js#amazon-chime-sdk-for-javascript)
- [X] Feature-specific [guides](https://github.com/aws/amazon-chime-sdk-js#guides)

### Reproduction steps

Unable to repro, this has only happened once in our internal tests.

### Amazon Chime SDK for JavaScript version

3.14.1

### What browsers are you seeing the problem on?

Chrome 

### Browser version

114.0.0.0

### Meeting and Attendee ID Information.

Meeting ID: `492c2601-6f44-46bd-b5b3-9f416f282713`
Attendee ID who was unable to hear one person in the meeting: `f63cb712-959a-b944-d702-34305a2be3b9`
Attendee ID of person who could not be heard: `f28e17fc-a974-470a-d6e8-a32d8a6e60d6`

### Browser console logs

I'm unable to paste our internal logs here but the issue happened just before 2023-07-11T18:24:22.024Z

**Comment by xuesichao** [comment]
@evangeline Since you opened an AWS support ticket for the same issue, I'll close this GitHub issue. Your issue has been sent to our media team for further debugging. Thanks for your patience.
