### ISSUE TITLE
Unable to catch failed websocket connections

### ISSUE THREAD

**Issue by kelvin2200** [aws/amazon-chime-sdk-js#2720]
### What happened and what did you expect to happen?

Certain clients are behind custom firewall and/or antivirus configurations. Usually when this is the case, and the Chime endpoints require whitelisting, the first thing that fails (among others) is the connection to the chime signaling service. While there are hacks and workarounds to catch that error in the browser, it would be nice for the SDK to have a listener we can use to detect that specific scenario and show the user a custom message.

Maybe such a listener can be added and we haven't yet found out how. Please correct me if I am wrong.

### Have you reviewed our existing documentation?

- [X] GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [X] FAQs [page](https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html)
- [X] README [page](https://github.com/aws/amazon-chime-sdk-js#amazon-chime-sdk-for-javascript)
- [X] Feature-specific [guides](https://github.com/aws/amazon-chime-sdk-js#guides)

### Reproduction steps

add these 2 entries to:
`/etc/hosts` (linux)
`127.0.0.1 signal.m2.ec1.app.chime.aws
127.0.0.1 data.svc.ue1.ingest.chime.aws`

and start a meeting

### Amazon Chime SDK for JavaScript version

3.15.0

### What browsers are you seeing the problem on?

all

### Browser version

all

### Browser console logs

[WARN] - Chime: stopped pinging (WebSocketFailed)
[WARN] - Chime: will retry due to status code TaskFailed and error: serial group task AudioVideoStart/8bcbfa41-73d5-468e-9658-a3ae158d7979/d9cbd654-f27e-b7d2-ae94-5670c2a2c690 was canceled due to subtask AudioVideoStart/8bcbfa41-73d5-468e-9658-a3ae158d7979/d9cbd654-f27e-b7d2-ae94-5670c2a2c690/Timeout15000ms error: serial group task AudioVideoStart/8bcbfa41-73d5-468e-9658-a3ae158d7979/d9cbd654-f27e-b7d2-ae94-5670c2a2c690/Timeout15000ms/Peer was canceled due to subtask AudioVideoStart/8bcbfa41-73d5-468e-9658-a3ae158d7979/d9cbd654-f27e-b7d2-ae94-5670c2a2c690/Timeout15000ms/Peer/SubscribeAndReceiveSubscribeAckTask (once) error: serial group task Signaling was canceled due to subtask Signaling/Timeout15000ms (once) error: WebSocket connection failed

WebSocket connection to 'wss://signal.m2.ec1.app.chime.aws/control/8bcbfa41-73d5-468e-9658-a3ae158d7979?X-Chime-Control-Protocol-Version=3&X-Amzn-Chime-Send-Close-On-Error=1&X-Amzn-Version=3.14.1&X-Amzn-User-Agent=chrome-114' failed: 
create @ DefaultWebSocketAdapter.ts:15
serviceConnectionRequestQueue @ DefaultSignalingClient.ts:374
21:35:45.053 ConsoleLogger.ts:79 2023-07-27T18:35:45.053Z [ERROR] Chime - failed to connect

**Comment by kelvin2200** [comment]
@michhyun1 OK, we know about the audiovideoObserver, and client metrics, but:

1. a user may **not have a video device at all**
2. the observers will behave the same way when having a poor connection and there is packet loss

what would be needed is something that says specifically that the client cannot connect to the WS

**Comment by michhyun1** [comment]
I think the closet thing we have to that is https://aws.amazon.com/blogs/business-productivity/monitoring-and-troubleshooting-with-amazon-chime-sdk-meeting-events/

We throw a TaskFailed meeting event when we are unable to connect to the WS. 

however, taskFailed can mean multiple things, not just WS connection failure. I'm not 100% sure if there might be some metadata within a meeting event that shows whether or not it was caused due to the opensignalingtask failing as opposed to some other task failing.

**Comment by lvillacin** [comment]
Hi! As I understand from the above conversation it seems that there isn't a sure-fire way to identify if WS is blocked.

@kelvin2200 would you be able to provide some help/guidance on how to whitelist the aws chime sdk in a network?

I found this article but a little unsure on the steps we have to partake in: https://docs.aws.amazon.com/chime-sdk/latest/dg/network-config.html#media-signaling

We don't handle the network configuration and frankly am a bit unfamiliar and was wondering what we can provide to the network team so a little push in the right direction would be extremely helpful.

Thank you!

**Comment by ltrung** [comment]
@lvillacin There is a guide on the networking setup here https://github.com/aws/amazon-chime-sdk-js/blob/main/guides/07_FAQs.md#networking

Sorry for the late reply.
To detect fail to connect in JS SDK,  you can listen to `audioVideoDidStartConnecting(reconnecting: boolean)` or ` audioVideoDidStop` in [AudioVideoObserver](https://github.com/aws/amazon-chime-sdk-js/blob/main/src/audiovideoobserver/AudioVideoObserver.ts#L12).
In React component library you can listen to the [meeting Status hook](https://github.com/aws/amazon-chime-sdk-component-library-react/blob/main/src/hooks/sdk/useMeetingStatus.tsx) for Reconnecting and Failed.
