### ISSUE TITLE
When does billing actually start?

### ISSUE THREAD

**Issue by arashster** [aws/amazon-chime-sdk-js#2722]
Given the SDK documentation FAQ, it mentions "Billing starts when the attendee joins the meeting and leaves the meeting"

What API call in the JS frontend does that translate to?
Is it meetingSession.audioVideo.start(); ?

**Comment by simmkyu** [comment]
Yes, `meetingSession.audioVideo.start` allows an attendee to join your Chime SDK meeting, and `meetingSession.audioVideo.stop` allows them to leave the meeting.

**Comment by arashster** [comment]
Hi, so just to confirm, calling `meetingSession.audioVideo.start` starts billing, and calling `meetingSession.audioVideo.stop` will stop billing?

**Comment by simmkyu** [comment]
Yes, however, it does depend on the number of attendees in a meeting. If there are additional attendees who connect to the meeting after one attendee leaves with the `meetingSession.audioVideo.stop` API, billing will continue.

Please review the **WebRTC Media Billing & Pricing** section in the [Amazon Chime SDK - FAQs](https://aws.amazon.com/chime/chime-sdk/faq/) and the [Amazon Chime SDK Pricing](https://aws.amazon.com/chime/chime-sdk/pricing/).
