### ISSUE TITLE
Cannot query nearest media region for a specific IP

### ISSUE THREAD

**Issue by kelvin2200** [aws/amazon-chime-sdk-js#2733]
### What happened and what did you expect to happen?

As stated in the docs, a simple GET to `https://nearest-media-region.l.chime.aws` will return the nearest media region where you should create your meeting, but there are cases where that request cannot be made client-sided.

...and there is no query param that can be provided (at least not that I know of) to do smth like
`https://nearest-media-region.l.chime.aws/?ip=0.0.0.0`

For situations where this request cannot be made client-sided, the backend would handle it, but it would need to pass the client's IP to the aws endpoint.

Is there any possible way to do that?

### Have you reviewed our existing documentation?

- [X] GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [X] FAQs [page](https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html)
- [X] README [page](https://github.com/aws/amazon-chime-sdk-js#amazon-chime-sdk-for-javascript)
- [X] Feature-specific [guides](https://github.com/aws/amazon-chime-sdk-js#guides)

### Reproduction steps

none needed

### Amazon Chime SDK for JavaScript version

latest

### What browsers are you seeing the problem on?

All

### Browser version

all

### Browser console logs

none needed

**Comment by simmkyu** [comment]
It is not possible to pass an IP address to the nearest region endpoint.

**Comment by hensmi-amazon** [comment]
The service behind `https://nearest-media-region.l.chime.aws` is dynamically determining the closes region using AWS infrastructure. It is not doing IP lookups, hence it is not possible to find the closest location knowing simply the IP of a client, unfortunately.

You could utilize something like MaxMind for IP lookup, but it is not something that the Chime SDK will provide for a service. I'm curious, could you expand on why `https://nearest-media-region.l.chime.aws` cannot be called by a client?

**Comment by kelvin2200** [comment]
There are scheduling scenarios, where one attendee with (certain) privileges creates a meeting setup and the meeting itself is started automatically at a later point in time on a different region, either because the user's region changed or because it is started by a user in another region... It turns into scenarios where all potential attendees have to make that client request because it is hard to determine which one actually creates/starts the chime meeting. It would be much easier to make that determination on the backend, plus we would only make a single request to the nearest media region api.

**Comment by kelvin2200** [comment]
@hensmi-amazon thank you for your response

**Comment by hensmi-amazon** [comment]
It is not likely to be rate limited as the requests would be spread out across end-users.

Thanks for the explanation, I understand that the need to pick a central region and the timing required to create meetings is a bit clunky; unfortunately I do not think there is currently any ongoing improvements for the time being in that department. I will keep this issue open as a feature request for improvements to the ease of picking meeting regions.

**Comment by kelvin2200** [comment]
Thank you for the insight, I will keep track of this

**Comment by kelvin2200** [comment]
@hensmi-amazon I'm back with a slightly different problem.
I don't know if this is the proper place to file it, or if I should open a different issue.

It turns out that requests to the nearest media region endpoint from certain IP's return an undefined region.

One such case we've discovered are requests made from Mauritius.

Having the possibility to pass an IP param in this case would also aid in troubleshooting.

This was particularly hard to find out given we weren't looking for it...

**Comment by yochum** [comment]
Closing this issue as it does not directly pertain to the Chime SDK for JavaScript. Please do reach out through your AWS account team or contact us in AWS Console for further help on this topic. Much appreciated.
