### ISSUE TITLE
no transition found from NotConnected with Update

### ISSUE THREAD

**Issue by andreisergiu98** [aws/amazon-chime-sdk-js#2734]
### What happened and what did you expect to happen?

Hello!

We are seeing this warning "no transition found from NotConnected with Update" raised for a lot of attendees in our meetings.

This [issue](https://github.com/aws/amazon-chime-sdk-js/issues/410) says that the warning is raised if you start the local video tile before audiovideo is connected.

But this shouldn't be the case for us.

We are publishing the tile after the MeetingStatus provided by https://github.com/aws/amazon-chime-sdk-component-library-react is connected as seen below:

```tsx

    if (meetingStatus !== MeetingStatus.Succeeded) {
        return null;
    }

    return (
        <>
            <AudioInputStreamController />
            <VideoInputStreamController />
            <MeetingController />
            <ChimeEvents />
        </>
    );
```

So to my understanding there is either:
- a race condition in our app since the render is asynchronous (chime disconnects right before we start the tile)
- a race condition in the chime sdk
- the `useMeetingStatus` from the react sdk is too eager with the connected status

### Have you reviewed our existing documentation?

- [X] GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [X] FAQs [page](https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html)
- [X] README [page](https://github.com/aws/amazon-chime-sdk-js#amazon-chime-sdk-for-javascript)
- [X] Feature-specific [guides](https://github.com/aws/amazon-chime-sdk-js#guides)

### Reproduction steps

- Use react
- Connect to a meeting
- Wait for useMeetingStatus to be connected
- Start a video tile

### Amazon Chime SDK for JavaScript version

3.14.1

### What browsers are you seeing the problem on?

any

### Browser version

any

### Browser console logs

We don't have any for now, since debugging is disabled in production.

**Comment by simmkyu** [comment]
From the [MeetingManager code](https://github.com/aws/amazon-chime-sdk-component-library-react/blob/main/src/providers/MeetingProvider/MeetingManager.ts#L240-L246), the Chime SDK React Component Library listens to the `audioVideoDidStart` observer event from the Chime SDK for JavaScript and then changes the meeting status to `MeetingStatus.Succeeded`.

```js
  audioVideoDidStart = (): void => {
    console.log(
      '[MeetingManager audioVideoDidStart] Meeting started successfully'
    );
    this.meetingStatus = MeetingStatus.Succeeded;
    this.publishMeetingStatus();
  };
```

Therefore, the SDK should not produce the `no transition found from NotConnected with Update` message when you initiate video after receiving the `MeetingStatus.Succeeded`.



## Testing

For an experiment, I've added this code snippet into the [Chime SDK React Component Library Demo](https://github.com/aws-samples/amazon-chime-sdk/blob/61fc5ec2fe9f4319df8b6fcf0d0e15fbf92a1d30/apps/meeting/src/views/Meeting/index.tsx#L25 
).

```js
  const { toggleVideo, isVideoEnabled } = useLocalVideo();
  const meetingStatus = useMeetingStatus();
  if (meetingStatus === MeetingStatus.Succeeded && !isVideoEnabled) {
    toggleVideo();
  }
```

The SDK transitions as follows:

```
2023-08-18T23:28:29.573Z [INFO] ChimeComponentLibraryReactDemo - transitioning from NotConnected to Connecting with Connect
2023-08-18T23:28:30.069Z [INFO] ChimeComponentLibraryReactDemo - transitioning from Connecting to Connected with FinishConnecting
2023-08-18T23:28:30.170Z [INFO] ChimeComponentLibraryReactDemo - transitioning from Connected to Updating with Update
2023-08-18T23:28:30.267Z [INFO] ChimeComponentLibraryReactDemo - transitioning from Updating to Connected with FinishUpdating
2023-08-18T23:28:30.269Z [INFO] ChimeComponentLibraryReactDemo - transitioning from Connected to Updating with Update
2023-08-18T23:28:30.315Z [INFO] ChimeComponentLibraryReactDemo - transitioning from Updating to Connected with FinishUpdating
```

This experiment starts a video immediately after `MeetingStatus.Succeeded`. However, the `no transition found from NotConnected with Update` message also occurs when the attendee tries to start a video after the meeting has ended. 

Could you please confirm if it's possible to enable the video after the meeting has ended? Also, the Chime SDK INFO-level browser logs would be helpful in troubleshooting any potential race conditions.

**Comment by andreisergiu98** [comment]
Hi @simmkyu!

I digged a little deeper and it seems the warning is not raised by `startLocalVideoTile` but by `audioVideo.setContentShareVideoCodecPreferences?.([VideoCodecCapability.vp8()]);`. Which we call immediately after `MeetingStatus.Succeeded`.

**Comment by simmkyu** [comment]
I confirm that calling the `meetingSession.audioVideo.setContentShareVideoCodecPreferences` API initiates the update action. The SDK triggers this action to update audio/video subscriptions in several scenarios, including but not limited to:
- When an attendee joins or leaves.
- When an attendee toggles a video.
- When the video preferences are set.

https://github.com/aws/amazon-chime-sdk-js/blob/53d35c034530208a0580cb734134888db2bbdf40/src/audiovideocontroller/DefaultAudioVideoController.ts#L1554-L1558

You can ignore this warning message for the time being. The `meetingSession.audioVideo.setContentShareVideoCodecPreferences` should work whether it's called prior to or during the session.

**Comment by simmkyu** [comment]
Merged the fix. In the upcoming version 3.17.0, the SDK will no longer display a warning message in the console when `meetingSession.audioVideo.setContentShareVideoCodecPreferences` is invoked prior to the start of the session.
