### ISSUE TITLE
Version 3.16.0

### ISSUE THREAD

**Issue by shriyajuneja** [aws/amazon-chime-sdk-js#2738]
### What happened and what did you expect to happen?

Hi, I noticed that the repository version has been bumped to 3.16.0 but it is not available on npm. Could this version be published, or could you update us with an estimated time to publish this. We're awaiting the protobufjs upgrade from 6.11.3 to 7.2.4 from quite some time due to security reasons.

### Have you reviewed our existing documentation?

- [X] GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [X] FAQs [page](https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html)
- [X] README [page](https://github.com/aws/amazon-chime-sdk-js#amazon-chime-sdk-for-javascript)
- [X] Feature-specific [guides](https://github.com/aws/amazon-chime-sdk-js#guides)

### Reproduction steps

NA

### Amazon Chime SDK for JavaScript version

NA

### What browsers are you seeing the problem on?

NA

### Browser version

NA

### Browser console logs

 NA

**Comment by xuesichao** [comment]
Hi @shriyajuneja , we are working on the release, you should see it soon.
