### ISSUE TITLE
Missing MeetingHostId on event chime:MeetingStarted

### ISSUE THREAD

**Issue by josephharkins** [aws/amazon-chime-sdk-js#2741]
### What happened and what did you expect to happen?

Hi team Chime SDK, apologies if this is the incorrect place to make this report and please redirect me if so.

- I use events from Chime, caught by EventBridge to trigger a Lambda function which updates my database
- The event contains the information I need to record except MeetingHostId which I am passing when using CreateMeetingCommand

Is this intended or am I missing something? It feels like an oversight not to include this in the event data.

Thank you very much.

### Have you reviewed our existing documentation?

- [x] GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [X] FAQs [page](https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html)
- [X] README [page](https://github.com/aws/amazon-chime-sdk-js#amazon-chime-sdk-for-javascript)
- [X] Feature-specific [guides](https://github.com/aws/amazon-chime-sdk-js#guides)

### Reproduction steps

Use EventBridge to record and send chime:MeetingStarted events to Lambda function.

### Amazon Chime SDK for JavaScript version

3.395.0

### What browsers are you seeing the problem on?

n/a

### Browser version

n/a

### Browser console logs

n/a

**Comment by ashleyqu** [comment]
MeetingHostId is not a part of chime:MeetingStarted event: https://docs.aws.amazon.com/chime-sdk/latest/dg/using-events.html.

**Comment by josephharkins** [comment]
> MeetingHostId is not a part of chime:MeetingStarted event: https://docs.aws.amazon.com/chime-sdk/latest/dg/using-events.html.

Yes, indeed. That is my feedback, that it should come with that event :)
