### ISSUE TITLE
When will chime sdk/media capture pipelines be fully support in other regions

### ISSUE THREAD

**Issue by dmoughabghab** [aws/amazon-chime-sdk-js#2762]
I apologize that this was the best place I could find to ask this.

We are developing a web app using chime sdk in ap-southeast-2 region and recording the meeting in the region of ap-southeast-2 is very important to us.

After doing a lot of digging around I found that there is no mention of a planned rollout of the new media capture pipelines to the rest of the world. Is this something that's happening and do we have a timeline?

**Comment by avinashmidathada** [comment]
Hello, we do support meeting capture in ap-southeast-2. You can create your meetings in ap-southeast-2 and use any control plane region (for eg. ap-southeast-1) of media pipeline to start the recording. You just need to ensure that the S3 bucket (`SinkArn` in the API) that's used for storing the recorded artifacts belongs to the same region as the meeting that is to be captured.

You can find the full list of supported regions for media pipelines [here](https://docs.aws.amazon.com/chime-sdk/latest/dg/sdk-available-regions.html#sdk-media-pipelines)
