### ISSUE TITLE
How to properly test SignalStrength for remote attendees

### ISSUE THREAD

**Issue by SmejiaA** [aws/amazon-chime-sdk-js#2765]
### What are you trying to do?

*I have a host with two remote attendees. The idea is to let them know (by displaying a signal strength poor icon on the tile) when one or more attendees are facing connectivity issues. So far, almost all the time the returned value for Signal Strengrh is 1.*

### How can the documentation be improved to help your use case?

*I would like to know all the different ways to test Signal Strength properly. Any Link conditioner tools?, multiple Desktops?, throttling?, etc.*

### What documentation have you looked at so far?

*[Add documentation for Signal Strength](https://github.com/aws/amazon-chime-sdk-js/issues/1322), [Events for monitoring local attendee downlink](https://aws.github.io/amazon-chime-sdk-js/modules/qualitybandwidth_connectivity.html#events-for-monitoring-local-attendee-downlink), [Events for monitoring remote attendee uplink](https://aws.github.io/amazon-chime-sdk-js/modules/qualitybandwidth_connectivity.html#events-for-monitoring-remote-attendee-uplink), [Metrics exposed directly from the WebRTC peer connection](https://aws.github.io/amazon-chime-sdk-js/modules/qualitybandwidth_connectivity.html#metrics-exposed-directly-from-the-webrtc-peer-connection).

**Comment by amancvent** [comment]
@SmejiaA Did you find a way to test this ? I used Network Link Conditioner in Mac on Chrome to slow down the overall network strength but the value of Signal Strength is always 1 even if the I reduce it down to Edge.

**Comment by SmejiaA** [comment]
Unfortunately I did not, but I also found a very useful Throttle tool to simulate different network speeds (hope it can help you):

[Thorttle](https://www.sitespeed.io/documentation/throttle/)
