### ISSUE TITLE
The Camera LED can't be turned off

### ISSUE THREAD

**Issue by simmkyu** [aws/amazon-chime-sdk-js#278]
**Important:** Please attach INFO-level logs with timestamps to the report from *before* the session started up until the point at which the unexpected behavior occured. For multi-participant calls, attach a log file for each participant if possible.

**Meeting and attendee IDs:**
List the meeting and attendee IDs that the attached logs apply to.
N/A

**Timeline**
Outline the main actions the user performed and when:
N/A (See below)

**Describe the bug**
Describe the bug and the timestamp at which it happened relative to the timestamp in the log file.

Repro step 1:
1. Open the browser demo app.
  https://github.com/aws/amazon-chime-sdk-js/tree/master/demos/browser
2. Type meeting ID and name. Click "Continue."
3. Immediately click "Join" in the device page before seeing your preview video.
4. LED light is turned on. You can't turn it off by calling stop methods.
   ```
   stopVideoPreviewForVideoInput()
   chooseVideoInputDevice(null)
   ```

Repro step 2:
1. Open meetingV2.ts
   https://github.com/aws/amazon-chime-sdk-js/blob/ae80650701b8691d1ad490ef1cb6a94bc0d195ac/demos/browser/app/meetingV2/meetingV2.ts#L1012
2.  Remove `await` from the first `chooseVideoInputDevice` call. Then, call `chooseVideoInputDevice()` after starting the video preview.
    ```
        this.audioVideo.chooseVideoInputDevice(device);
        if (showPreview) {
          this.audioVideo.startVideoPreviewForVideoInput(document.getElementById(
            'video-preview'
          ) as HTMLVideoElement);
        }
        await this.audioVideo.chooseVideoInputDevice(device);
    ```
3. Open the demo app and join the meeting. LED will be on permanently until closing a browser tab or window.

**Screenshots**
If applicable, add screenshots to help explain the problem.

**Platform**
 - OS: macOS 10.14.6
 - Browser: Chrome
 - Browser Version: 80.0.3987.163
 - Amazon Chime SDK GitHub Commit: f8c345b95472cc2aea26e7e399ca72f3523900d2

**Comment by RossWilliams** [comment]
Could I summarise the issue as saying if you have multiple media streams for a track, the tracks cannot be stopped? Is this due to internal state tracking within the sdk, or a web platform issue?

**Comment by simmkyu** [comment]
> Could I summarise the issue as saying if you have multiple media streams for a track, the tracks cannot be stopped? Is this due to internal state tracking within the sdk, or a web platform issue?

I haven't had a chance to investigate this LED issue yet, but I think the repro step 2 is due to the internal state within the SDK.

When calling `chooseVideoInputDevice`, SDK releases a previous video stream first and then sets a new device. If you call `chooseVideoInputDevice` before a previous `chooseVideoInputDevice` execution ends, SDK might lose a reference to the previous stream, failing to release it.
https://github.com/aws/amazon-chime-sdk-js/blob/a8eac1cc2ac7fe66f3a72ef2c9aa04da761beb41/src/devicecontroller/DefaultDeviceController.ts#L464

**Comment by tbrand** [comment]
same here

**Comment by tbrand** [comment]
It seems this happens on SPA project. Vue for my case.
Switch pages by `window.location = ...` solves for me as a workaround.

**Comment by haxxxton** [comment]
Just adding to this conversation based off @simmkyu's investigations. We experienced video needing to be turned off and back on again when we fired `chooseVideoInputDevice` too close to one another (ie. not waiting for the first to finish before calling it again). This would get things into a state where they believed the video was working, but you'd get no video stream bound to the local video tile

**Comment by simmkyu** [comment]
We have fixed two LED problems. Please review the description in https://github.com/aws/amazon-chime-sdk-js/pull/435
