### ISSUE TITLE
Synchronized Pausing Between Two Peers

### ISSUE THREAD

**Issue by JDSeiler** [aws/amazon-chime-sdk-js#2785]
Hello, I'm trying to do something quite unusual and I wanted to ask if there's an idiomatic way to do this with the existing Chime JavaScript API before I explore other options.

**What I'm Trying to Do**
In my situation, there are two attendees in a single meeting. One attendee (which I'll call the broadcaster) streams video and has a local preview of their stream, while the other attendee is a spectator. I'd like the spectator to be able to "pause" the stream such that *both* the spectator's view *and* and broadcaster's preview are showing the same image.

I know that I can use the [pauseVideoTile](https://aws.github.io/amazon-chime-sdk-js/interfaces/audiovideofacade.html#pausevideotile) to stop the pause on the spectator side, but the difficulty is getting the broadcaster preview and spectator view synchronized, since the spectator is "in the past" relative to the broadcaster. If I simply call [stopVideoInput](https://aws.github.io/amazon-chime-sdk-js/interfaces/audiovideofacade.html#stopvideoinput) on the broadcaster side, it causes the video stream on the spectator side to go blank (as you'd expect). 

Is there a way I can stop streaming on the broadcaster side, such that the spectator will continue consuming whatever video was already on the wire, and then freeze on the last frame of video sent by the broadcaster?

**Comment by ltrung** [comment]
Sorry for replying late. You can use [DataMessage](https://github.com/aws/amazon-chime-sdk-js/blob/main/guides/03_API_Overview.md#9-send-and-receive-data-messages-optional) to send a message to the broadcaster side to pause the video stream from the broadcaster side instead.
Closing for now but feel free to reopen if you still need help.
