### ISSUE TITLE
Chime SDK Javascript Audio Output not working 

### ISSUE THREAD

**Issue by ilocks** [aws/amazon-chime-sdk-js#2786]
I am developing videocall using Amazon chime sdk-js.
video/audio works normally in the Android app.
However, the video appears in the PC browser (Chrome), but there is no sound.

The problem is that sound coming from the app cannot be heard in the web browser.

The version is being developed as v3 or higher for both app and web.

**Comment by brycepj** [comment]
I think this may be your issue: https://github.com/aws/amazon-chime-sdk-js/issues/2566

**Comment by michhyun1** [comment]
Resolving this in favor of the other issue - feel free to create a new issue if need be.
