### ISSUE TITLE
Unable to use Screenshare when using demo code with one participant only

### ISSUE THREAD

**Issue by senthilnathan27** [aws/amazon-chime-sdk-js#2790]
### What happened and what did you expect to happen?

Screen share was creating duplicate windows. we are unable to use this feature to implement the same in our applications. and also please support screen share in mobile browsers also

![image](https://github.com/aws/amazon-chime-sdk-js/assets/76081785/7892aa9e-13c3-4c0b-85c5-907b0c37b5a7)
![image](https://github.com/aws/amazon-chime-sdk-js/assets/76081785/abb24cc2-078e-48b1-b062-06985a69dff8)

### Have you reviewed our existing documentation?

- [X] GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [X] FAQs [page](https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html)
- [X] README [page](https://github.com/aws/amazon-chime-sdk-js#amazon-chime-sdk-for-javascript)
- [X] Feature-specific [guides](https://github.com/aws/amazon-chime-sdk-js#guides)

### Reproduction steps

1, clone amazon-chime-sdk-js app
2, navigate to demo/browser folder and run the meetingV2
3, start meeting and screen share in entire screen mode

### Amazon Chime SDK for JavaScript version

^3.15.0

### What browsers are you seeing the problem on?

Google Chrome 

### Browser version

116.0

### Browser console logs

2023-10-26T13:54:32.758Z [INFO] SDK - processed remote description is >>>v=0
o=- 0 0 IN IP4 127.0.0.1
s=-
t=0 0
a=group:BUNDLE 0 1
a=extmap-allow-mixed
a=msid-semantic: WMS *
m=audio 17093 UDP/TLS/RTP/SAVPF 111
c=IN IP4 3.110.152.182
a=rtcp:17093 IN IP4 3.110.152.182
a=candidate:Ha033d58 1 udp 1694498815 10.3.61.88 17093 typ host generation 0
a=candidate:Ha033d58 2 udp 1694498815 10.3.61.88 17093 typ host generation 0
a=ice-ufrag:3277d1c92ef0ab06781d3e095174b5a2
a=ice-pwd:036596c6456eed093b6275477aaf7d01
a=fingerprint:sha-256 99:FE:EE:BE:F0:BF:E7:00:F7:FC:EE:EC:2A:F1:F3:6E:85:8C:8D:0A:56:80:DD:8D:40:2B:FC:E0:C2:6B:D9:B1
a=setup:passive
a=mid:0
a=extmap:2 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=sendrecv
a=msid:audio audio
a=rtcp-mux
a=rtcp-rsize
a=rtpmap:111 opus/48000/2
a=rtcp-fb:111 transport-cc
a=fmtp:111 minptime=10;useinbandfec=1
a=ssrc:1365343602 cname:GqWAadS9bXE4lWlO
m=video 9 UDP/TLS/RTP/SAVPF 96 97 106 107
c=IN IP4 0.0.0.0
a=rtcp:9 IN IP4 0.0.0.0
a=ice-ufrag:3277d1c92ef0ab06781d3e095174b5a2
a=ice-pwd:036596c6456eed093b6275477aaf7d01
a=fingerprint:sha-256 99:FE:EE:BE:F0:BF:E7:00:F7:FC:EE:EC:2A:F1:F3:6E:85:8C:8D:0A:56:80:DD:8D:40:2B:FC:E0:C2:6B:D9:B1
a=setup:passive
a=mid:1
a=inactive
a=msid:inactive inactive
a=rtcp-mux
a=rtcp-rsize
a=rtpmap:96 VP8/90000
a=rtcp-fb:96 transport-cc
a=rtcp-fb:96 ccm fir
a=rtcp-fb:96 nack
a=rtcp-fb:96 goog-remb
a=rtcp-fb:96 nack pli
a=rtpmap:97 rtx/90000
a=fmtp:97 apt=96
a=rtpmap:106 H264/90000
a=rtcp-fb:106 transport-cc
a=rtcp-fb:106 ccm fir
a=rtcp-fb:106 nack
a=rtcp-fb:106 goog-remb
a=rtcp-fb:106 nack pli
a=fmtp:106 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42e01f
a=rtpmap:107 rtx/90000
a=fmtp:107 apt=106
a=ssrc:2830628808 cname:inactive
<<<

**Comment by ltrung** [comment]
Screen capture web browser API https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getDisplayMedia is not supported in mobile so until then our library would not be able to support it.
If you need screen share in mobile, you can refer to our mobile SDK https://github.com/aws/amazon-chime-sdk-ios https://github.com/aws/amazon-chime-sdk-android.
The infinity mirror is expected if you share your screen or window.
