### ISSUE TITLE
Request for Support for Promise-based getStats Method in 'amazon-chime-sdk-js'

### ISSUE THREAD

**Issue by narisettiashok** [aws/amazon-chime-sdk-js#2792]
### What happened and what did you expect to happen?

I am currently using 'amazon-chime-sdk-js' version 1.20.2, and I've encountered a compatibility issue with the WebRTC statistics retrieval process. The library is still using the deprecated callback-based 'getStats' method, which is no longer supported in latest chrome browser. This has led to an error message: "Uncaught (in promise) DOMException: Failed to execute 'getStats' on 'RTCPeerConnection': The callback-based getStats() method is no longer supported. I have tested in Brave browser but i did not reporduce this error.

### Have you reviewed our existing documentation?

- [X] GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [X] FAQs [page](https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html)
- [X] README [page](https://github.com/aws/amazon-chime-sdk-js#amazon-chime-sdk-for-javascript)
- [X] Feature-specific [guides](https://github.com/aws/amazon-chime-sdk-js#guides)

### Reproduction steps

Start meeting, check in console log of browser.

### Amazon Chime SDK for JavaScript version

1.20.2

### What browsers are you seeing the problem on?

Google Chrome

### Browser version

Version 118.0.5993.117 (Official Build) (64-bit)

### Meeting and Attendee ID Information.

For all meetings facing this issue.

### Browser console logs

Uncaught (in promise) DOMException: Failed to execute 'getStats' on 'RTCPeerConnection': The callback-based getStats() method is no longer supported. at push../node_modules/amazon-chime-sdk-js/build/statscollector/DefaultStatsCollector.js.DefaultStatsCollector.getStatsWrapper

**Comment by pracheth** [comment]
Promise based getStats support was added in 3.0.0 (refer [CHANGELOG](https://github.com/aws/amazon-chime-sdk-js/blob/hotfix/CHANGELOG.md#300---2022-03-30))

Upgrading to at least 3.0.0 (or the latest version of 3.18.2 if possible) should help you out.

**Comment by narisettiashok** [comment]
> Promise based getStats support was added in 3.0.0 (refer [CHANGELOG](https://github.com/aws/amazon-chime-sdk-js/blob/hotfix/CHANGELOG.md#300---2022-03-30))
> 
> Upgrading to at least 3.0.0 (or the latest version of 3.18.2 if possible) should help you out. Note that 1.20.2 is a deprecated version which is almost 3 years old now.

Ok. Thank you.
