### ISSUE TITLE
Video resolution not matching configuration

### ISSUE THREAD

**Issue by dbish** [aws/amazon-chime-sdk-js#2804]
### What happened and what did you expect to happen?

We have set video resolution to the following
`
meetingSession.audioVideo.chooseVideoInputQuality(960, 540, 15);

meetingSession.audioVideo.startVideoInput(videoDevice);
`

However, 99% of the time, the recorded video looks very low resolution (checking the media pipeline and playing back the video). I know there is some dynamic resolution stuff that goes on behind the scenes but even when we record 1 camera (see meeting ID: 7e3b8077-fdb3-4114-90af-43f01e2c6404) on what is a decent office internet connection, setting the resolution higher doesn't seem to actually do anything since Chime is doing somehting on the backend.

Here's a screenshot, I don't think that resolution looks right.

<img width="1194" alt="Screenshot 2023-11-20 at 14 19 30" src="https://github.com/aws/amazon-chime-sdk-js/assets/1166295/3fd15dd5-55e5-458f-b515-e5b67d0f25d8">

Also, if we set any higher resolution then this, the resulting recording seems to actually drop in resolution.

What are we doing wrong? Thanks.

### Have you reviewed our existing documentation?

- [X] GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [X] FAQs [page](https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html)
- [X] README [page](https://github.com/aws/amazon-chime-sdk-js#amazon-chime-sdk-for-javascript)
- [X] Feature-specific [guides](https://github.com/aws/amazon-chime-sdk-js#guides)

### Reproduction steps

Set resolution for the video: meetingSession.audioVideo.chooseVideoInputQuality(960, 540, 15);

Create a media capture pipeline with following config:

                ChimeSdkMeetingConfiguration={
                    "ArtifactsConfiguration": {
                        "Audio": {"MuxType": "AudioWithActiveSpeakerVideo"},
                        "Video": {"State": "Enabled", "MuxType": "VideoOnly"},
                        "Content": {"State": "Disabled"},
                    }
                }
                
 Check the S3 files and see the resolution is not what you expect.

### Amazon Chime SDK for JavaScript version

3.14

### What browsers are you seeing the problem on?

Chrome

### Browser version

Version 119.0.6045.159

### Meeting and Attendee ID Information.

meeting ID: 7e3b8077-fdb3-4114-90af-43f01e2c6404, only one attendee 

### Browser console logs

this is about hte final resolution in replay

**Comment by shi-su** [comment]
I checked the meeting, the encoding resolution started at 180p (this is expected at the beginning and it will adapt as it have more info about the network). 6 seconds after the video was turned on, the resolution switched up to 270p, and then 360p 4 seconds later. It took another 4 seconds for the video to end up at 540p and stayed at 540p for the rest of the meeting (only 3 seconds though). The eventual bitrate was about 1400 kbps. The metrics does show resolution is configured properly and all behavior looks expected. Just that it takes a bit for resolution to adapt to network and the meeting was very short that the 540p resolution lasted for a very limited period of time.
