### ISSUE TITLE
Not able start media capture 

### ISSUE THREAD

**Issue by pragadeeshNIS** [aws/amazon-chime-sdk-js#2831]
### What happened and what did you expect to happen?

I am using mobile SDK along with the serverless demo. I am unable to start the media capture as it throws "unauthorized" error. 

URL to start media capture 
`https://XXXXXXX.execute-api.ap-southeast-1.amazonaws.com/Prod/start_capture?title=XXXXXX`

### Have you reviewed our existing documentation?

- [X] GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [X] FAQs [page](https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html)
- [X] README [page](https://github.com/aws/amazon-chime-sdk-js#amazon-chime-sdk-for-javascript)
- [X] Feature-specific [guides](https://github.com/aws/amazon-chime-sdk-js#guides)

### Reproduction steps

- Create meeting
- start media capture 
- throws unauthorized error

### Amazon Chime SDK for JavaScript version

latest

### What browsers are you seeing the problem on?

Android

### Browser version

9.0

### Meeting and Attendee ID Information.

nil

### Browser console logs

no information

**Comment by pragadeeshNIS** [comment]
This is the exact error I get when I call the API from an Android device

API : `https://XXXXXXX.execute-api.ap-southeast-1.amazonaws.com/Prod/start_capture?title=XXXXXX`

Response : `HttpResponse(data={"message":"Missing Authentication Token"}, httpException=HttpException(errorCode=403, errorReason=))`

**Comment by MingcongQi** [comment]
HI,
How do you call the API and pass the authentication role?
could you help post your codes here? Here is the demo to create the media capture `https://github.com/aws/amazon-chime-sdk-js/blob/main/demos/serverless/src/handlers.js#L433`

**Comment by pragadeeshNIS** [comment]
I resolved the issue I was calling the wrong URL
wrong URL: https://XXXXXXX.execute-api.ap-southeast-1.amazonaws.com/Prod/**start_capture**?title=XXXXXX
correct URL: https://XXXXXXX.execute-api.ap-southeast-1.amazonaws.com/Prod/**startCapture**?title=XXXXXX
