### ISSUE TITLE
Any Event for when call End or refresh the page

### ISSUE THREAD

**Issue by koni-a** [aws/amazon-chime-sdk-js#284]
Hi Team,

can u help us with, how to get notified when the call ends and refresh the page?

**Comment by simmkyu** [comment]
The [Stopping a session](https://github.com/aws/amazon-chime-sdk-js#stopping-a-session) section has examples of two end events: `Left` and `AudioCallEnded`.

Chime SDK does not refresh the page. You can refresh or redirect the page when you receive `MeetingSessionStatusCode.AudioCallEnded` in the `audioVideoDidStop` method. Please see https://github.com/aws/amazon-chime-sdk-js#stopping-a-session for details.
