### ISSUE TITLE
Composed video created using Concatenation Pipeline is missing the last video chunk

### ISSUE THREAD

**Issue by AmraniOmar** [aws/amazon-chime-sdk-js#2847]
### What happened and what did you expect to happen?

I'm experiencing an issue where the concatenated composed video is missing the last composed video chunk.
I tried a couple of times and it's always the last chunk missing from the concatenated video.

### Have you reviewed our existing documentation?

- [X] GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [X] FAQs [page](https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html)
- [X] README [page](https://github.com/aws/amazon-chime-sdk-js#amazon-chime-sdk-for-javascript)
- [X] Feature-specific [guides](https://github.com/aws/amazon-chime-sdk-js#guides)

### Reproduction steps

1- Start a meeting
2- Start a media capture pipeline
3- Start media concatenation pipeline (In my case, I trigger this after the meeting end event)

### Amazon Chime SDK for JavaScript version

v3

### What browsers are you seeing the problem on?

3.20.0

### Browser version

121.0.6167.184

### Meeting and Attendee ID Information.

Meeting ID: ff20409e-59b0-4b3b-916a-5fa0de707979
Capture pipeline id: 02fa6bf4-ff6b-4918-a001-038a534da34f
Concatenation pipeline id: e17db857-e9be-44dc-97c1-febbd1f4df23

### Browser console logs

NA

**Comment by nehatambe** [comment]
Hello Omar, we are investigating the pipelines provided above, will update as soon as we have more details. Thank you!

**Comment by nehatambe** [comment]
@AmraniOmar We have fixed the issue. Please let us know if you see any issues.

**Comment by AmraniOmar** [comment]
Thank you so much for the update @nehatambe  🙌
