### ISSUE TITLE
SDK Does not Pass the Typechecker

### ISSUE THREAD

**Issue by dairyisscary** [aws/amazon-chime-sdk-js#2848]
### What happened and what did you expect to happen?

The file `node_modules/amazon-chime-sdk-js/build/signalingprotocol/SignalingProtocol.d.ts` does not pass typescript typechecker. I have elided the output but there are 22 instances of this same error:
```
node_modules/amazon-chime-sdk-js/build/signalingprotocol/SignalingProtocol.d.ts:7:26 - error TS2709: Cannot use namespace 'Long' as a type.

7     timestampMs: (number|Long);
                           ~~~~

node_modules/amazon-chime-sdk-js/build/signalingprotocol/SignalingProtocol.d.ts:89:33 - error TS2709: Cannot use namespace 'Long' as a type.

89     public timestampMs: (number|Long);
                                   ~~~~
```

Versions:
```
yarn why -R long
   └─ amazon-chime-sdk-js@npm:3.20.0 (via npm:^3.20.0)
      └─ protobufjs@npm:7.2.6 (via npm:^7.2.4)
         └─ long@npm:5.2.3 (via npm:^5.0.0)

yarn info typescript
└─ typescript@patch:typescript@npm%3A5.3.3#optional!builtin<compat/typescript>::version=5.3.3&hash=e012d7
   ├─ Version: 5.3.3
```
`skipLibCheck` is false in my project

I did a manual patch of `SignalingProtocol.d.ts` to change and it seems to compile
```diff
-import Long = require("long");
+import type Long from "long";
```

### Have you reviewed our existing documentation?

- [X] GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [X] FAQs [page](https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html)
- [X] README [page](https://github.com/aws/amazon-chime-sdk-js#amazon-chime-sdk-for-javascript)
- [X] Feature-specific [guides](https://github.com/aws/amazon-chime-sdk-js#guides)

### Reproduction steps

`yarn run tsc` as a downstream project that checks libs with `"skipLibCheck": false` in one's `tsconfig.json`

### Amazon Chime SDK for JavaScript version

posted above

### What browsers are you seeing the problem on?

n/a

### Browser version

n/a

### Browser console logs

n/a

**Comment by ltrung** [comment]
What typescript version are you using?

**Comment by dairyisscary** [comment]
As specificed in the original ticket, this was produced in typescript version 5.3.3, though it still appears to be the case in 5.4.x.

I have made a minmalist reproduction with a replit here: https://replit.com/@dairyisscary/Aws-sdk-reproduction?v=1#tsconfig.json

i think that some combination of the `tsconfig.json` configuration options `module`, `moduleResolution` and of course, `skipLibCheck: false` are what make this particular line `import Long = require("long");` mean something that won't typecheck.

**Comment by ltrung** [comment]
We currently support typescript version 4+ https://github.com/aws/amazon-chime-sdk-js/blob/main/package.json#L99. There are a lot of breaking changes with typescript type def in version 5.
