### ISSUE TITLE
TypeError: Converting circular structure to JSON -> starting at object with constructor 'DefaultDeviceController'

### ISSUE THREAD

**Issue by bizready** [aws/amazon-chime-sdk-js#285]
**Describe the bug**
Server-side Meeting and Attendee resources created and received by the client code. While creating MeetingSession object I get a circular reference issue in the Client SDK codebase.

**Platform**
 - OS: Mac Pro
 - Browser: Chrome
 - Browser Version: 80.0.3987.163
 - Amazon Chime SDK GitHub Commit: "amazon-chime-sdk-js": "^1.2.1"

My client code (using Quasar/Vue):
```
const logger = new ConsoleLogger('MyLogger', LogLevel.INFO);
const deviceController = new DefaultDeviceController(logger);

const data = .... has meeting resource response from server

this.meetingSession = new DefaultMeetingSession(
      new MeetingSessionConfiguration(
        data.joinMeeting.Meeting,
        data.joinMeeting.Attendee
      ),
      logger,
      deviceController
);
```
Error:
```
TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'DefaultDeviceController'
    |     property 'boundAudioVideoController' -> object with constructor 'DefaultAudioVideoController'
    --- property '_mediaStreamBroker' closes the circle"
```
SDK code traced: 
Source: [DefaultMeetingSession.ts](https://github.com/aws/amazon-chime-sdk-js/blob/master/src/meetingsession/DefaultMeetingSession.ts#L49)
At line [#49](https://github.com/aws/amazon-chime-sdk-js/blob/8a2342f230181717a3abfe153c377a8e5ec497c4/src/meetingsession/DefaultMeetingSession.ts#L49) audioVideoController object has reference to deviceController object.
At line [#63](https://github.com/aws/amazon-chime-sdk-js/blob/8a2342f230181717a3abfe153c377a8e5ec497c4/src/meetingsession/DefaultMeetingSession.ts#L63) deviceConroller binds to audioVideoController

**Comment by ltrung** [comment]
Do you have full stack trace showing where that error is thrown?

**Comment by bizready** [comment]
I was trying to re-create the scenario and looks issue is happening in different scenarios. I was trying to print the content of meetingSession object on the screen with html <pre> tag. Once I removed the pre tag, the issue is not happening.
