### ISSUE TITLE
Serverless Demo fails to deploy due to Node version

### ISSUE THREAD

**Issue by ngl-aws** [aws/amazon-chime-sdk-js#2850]
### What happened and what did you expect to happen?

Tried to deploy the Serverless demo. Deploy fails due to NodeJS 14.x runtime being used for Lambdas in demo/serverless/template.yml

### Have you reviewed our existing documentation?

- [X] GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [X] FAQs [page](https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html)
- [X] README [page](https://github.com/aws/amazon-chime-sdk-js#amazon-chime-sdk-for-javascript)
- [X] Feature-specific [guides](https://github.com/aws/amazon-chime-sdk-js#guides)

### Reproduction steps

As per Serverless demo instructions:

npm run deploy -- -r us-east-1 -b <bucket-name> -s <stack-name> -a meeting

Console log:

Cloudformation Event Log:

2024-03-04 18:34:35 UTC+1100	ChimeSdkBrowserEventIngestionLogStreamLambda	
CREATE_FAILED
	Resource handler returned message: "The runtime parameter of nodejs14.x is no longer supported for creating or updating AWS Lambda functions. We recommend you use the new runtime (nodejs20.x) while creating or updating functions. (Service: Lambda, Status Code: 400, Request ID: 9dae994b-3230-444a-a673-7649e7279dac)" (RequestToken: c13298eb-2e67-e578-a32c-644072666ccc, HandlerErrorCode: InvalidRequest)
2024-03-04 18:34:35 UTC+1100	ChimeSdkBrowserLogsLambda	
CREATE_FAILED
	Resource handler returned message: "The runtime parameter of nodejs14.x is no longer supported for creating or updating AWS Lambda functions. We recommend you use the new runtime (nodejs20.x) while creating or updating functions. (Service: Lambda, Status Code: 400, Request ID: 6bb51214-9780-465f-ac0c-3c93195d3522)" (RequestToken: fd033836-23a5-8e08-98f7-b86c7ae3e707, HandlerErrorCode: InvalidRequest)
2024-03-04 18:34:35 UTC+1100	ChimeSQSQueueLambda	
CREATE_FAILED
	Resource handler returned message: "The runtime parameter of nodejs14.x is no longer supported for creating or updating AWS Lambda functions. We recommend you use the new runtime (nodejs20.x) while creating or updating functions. (Service: Lambda, Status Code: 400, Request ID: 7454ad38-97c8-481f-b51c-4b6d0979b805)" (RequestToken: 512eca64-b01d-4013-80f3-45566b997ffc, HandlerErrorCode: InvalidRequest)
2024-03-04 18:34:35 UTC+1100	ChimeSdkBrowserCreateBrowserEventLogStreamLambda	
CREATE_FAILED
	Resource handler returned message: "The runtime parameter of nodejs14.x is no longer supported for creating or updating AWS Lambda functions. We recommend you use the new runtime (nodejs20.x) while creating or updating functions. (Service: Lambda, Status Code: 400, Request ID: 3d0c304f-7b3d-4679-829e-e4e10797fd43)" (RequestToken: 4d81d735-98e7-4723-edbb-ebe2c158f435, HandlerErrorCode: InvalidRequest)
2024-03-04 18:34:35 UTC+1100	ChimeSdkAudioFileLambda	
CREATE_FAILED
	Resource handler returned message: "The runtime parameter of nodejs14.x is no longer supported for creating or updating AWS Lambda functions. We recommend you use the new runtime (nodejs20.x) while creating or updating functions. (Service: Lambda, Status Code: 400, Request ID: 3c289de8-9747-4ebc-a68b-cae763cbfe49)" (RequestToken: 7c59dc26-3fbd-ea32-99d2-2380677ac4d6, HandlerErrorCode: InvalidRequest)
2024-03-04 18:34:35 UTC+1100	ChimeSdkBrowserMeetingEventLogsLambda	
CREATE_FAILED
	Resource handler returned message: "The runtime parameter of nodejs14.x is no longer supported for creating or updating AWS Lambda functions. We recommend you use the new runtime (nodejs20.x) while creating or updating functions. (Service: Lambda, Status Code: 400, Request ID: 835054b5-d739-4006-999b-80397d5d42a7)" (RequestToken: 6d75f358-2811-18ca-810f-f534cdd7e849, HandlerErrorCode: InvalidRequest)
2024-03-04 18:34:35 UTC+1100	ChimeSdkBrowserCreateLogStreamLambda	
CREATE_FAILED
	Resource handler returned message: "The runtime parameter of nodejs14.x is no longer supported for creating or updating AWS Lambda functions. We recommend you use the new runtime (nodejs20.x) while creating or updating functions. (Service: Lambda, Status Code: 400, Request ID: a7e09d4a-4a3f-4eab-8565-64e0516e25e8)" (RequestToken: 999589a7-e2e2-e4cc-cf17-44a34f76e0e5, HandlerErrorCode: InvalidRequest)
2024-03-04 18:34:35 UTC+1100	ChimeSdkStereoAudioFileLambda	
CREATE_FAILED
	Resource handler returned message: "The runtime parameter of nodejs14.x is no longer supported for creating or updating AWS Lambda functions. We recommend you use the new runtime (nodejs20.x) while creating or updating functions. (Service: Lambda, Status Code: 400, Request ID: eef8ae43-c121-4a6f-8b83-508591ffabe8)" (RequestToken: 9c68a185-edd3-c643-a341-c69e797ab965, HandlerErrorCode: InvalidRequest)

![Screenshot 2024-03-04 at 18 37 17](https://github.com/aws/amazon-chime-sdk-js/assets/64940065/611e1155-e295-4ba5-a26d-f8a4714ddbcc)

### Amazon Chime SDK for JavaScript version

3.21.0

### What browsers are you seeing the problem on?

N/A

### Browser version

N/A

### Browser console logs

N/A

**Comment by xuesichao** [comment]
Closing this one as of: https://github.com/aws/amazon-chime-sdk-js/pull/2851
