### ISSUE TITLE
Audio out of sync in composed video created using the concatenation pipeline

### ISSUE THREAD

**Issue by AmraniOmar** [aws/amazon-chime-sdk-js#2854]
### What happened and what did you expect to happen?

The composed video generated using the media concatenation pipeline has an out of sync audio. The composed video chunks look good and the issue seems to only occur during concatenation.

I tried to concatenate the chunks manually using ffmpeg and it worked as expected.

### Have you reviewed our existing documentation?

- [X] GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [X] FAQs [page](https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html)
- [X] README [page](https://github.com/aws/amazon-chime-sdk-js#amazon-chime-sdk-for-javascript)
- [X] Feature-specific [guides](https://github.com/aws/amazon-chime-sdk-js#guides)

### Reproduction steps

1- Start a meeting
2- Start a media capture pipeline
3- Stop the media capture pipeline
3- Upon meeting completion, start a media concatenation pipeline

### Amazon Chime SDK for JavaScript version

3.19.0

### What browsers are you seeing the problem on?

Chrome

### Browser version

122.0.6261.112

### Meeting and Attendee ID Information.

meeting_id: f802796f-8001-4004-9725-e4b7474d7979
media_capture_pipeline_id: 955fcde2-1475-404e-8bee-671870f52db9
media_concatenation_pipeline_id: c3df4f0f-cd20-4172-8f2b-ae06fba87bc7

### Browser console logs

NA

**Comment by MingcongQi** [comment]
All mentioned pipelines stopped successfully.
I did a test with exact same capture and concatenation pipeline configurations, the audio and video were sync.
Is the issue still happening? if yes, could you request AWS support case and we can exchange more information from support case.
