### ISSUE TITLE
Live transcription `IdentifyLanguage` not working

### ISSUE THREAD

**Issue by haow-abc** [aws/amazon-chime-sdk-js#2861]
### What happened and what did you expect to happen?

I am trying to use Chime live transcription feature, but having an issue with enabling `IdentifyLanguage`.
Everything works fine if I specific `LanguageCode: 'en-US'`, but when I do:
```
const transcribeResponse = await meetingClient.send(
                new StartMeetingTranscriptionCommand({
                    MeetingId: meetingId,
                    TranscriptionConfiguration: {
                        EngineTranscribeSettings: {
                            IdentifyLanguage: true,
                            PreferredLanguage: 'en-US'
                        }
                    }
                })
            );
```
I got a success message on the server side: `transcribeResponse {"$metadata":{"httpStatusCode":200,"requestId":"b20b7f6e-07a1-4da4-a26e-86c89f7a3a5b","attempts":1,"totalRetryDelay":0}}`

However, on the frontend, I got this error message:
<img width="960" alt="image" src="https://github.com/aws/amazon-chime-sdk-js/assets/28816747/a6f7472d-da3f-4f1e-badb-5dcba1dd156f">

Based on the documentation, seems like I don't need to specific `LanguageCode ` when `IdentifyLanguage ` is set to `true`:
<img width="1589" alt="image" src="https://github.com/aws/amazon-chime-sdk-js/assets/28816747/f09dba75-4afd-43aa-ae8a-ef1a9bcf9276">

Any idea about why this happens? Am I missing something? Thank you for helping in advance.

### Have you reviewed our existing documentation?

- [X] GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [X] FAQs [page](https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html)
- [X] README [page](https://github.com/aws/amazon-chime-sdk-js#amazon-chime-sdk-for-javascript)
- [X] Feature-specific [guides](https://github.com/aws/amazon-chime-sdk-js#guides)

### Reproduction steps

Server-side code:
```
const transcribeResponse = await meetingClient.send(
                new StartMeetingTranscriptionCommand({
                    MeetingId: meetingId,
                    TranscriptionConfiguration: {
                        EngineTranscribeSettings: {
                            // LanguageCode: 'en-US'
                            IdentifyLanguage: true,
                            PreferredLanguage: 'en-US'
                        }
                    }
                })
            );
```

Client-side code:
```
audioVideo.transcriptionController?.subscribeToTranscriptEvent((transcriptEvent) => {
            console.log('transcriptEvent', transcriptEvent);
            // do something with transcriptEvent
        });
```

### Amazon Chime SDK for JavaScript version

3.535.0

### What browsers are you seeing the problem on?

Chrome 

### Browser version

122.0.6261.129

### Browser console logs

skip

**Comment by pracheth** [comment]
It looks like there is a difference in documentation between AWS Chime SDK and AWS Transcribe.

AWS Chime SDK: https://docs.aws.amazon.com/chime/latest/APIReference/API_EngineTranscribeSettings.html#chime-Type-EngineTranscribeSettings-LanguageOptions

AWS Transcribe: https://docs.aws.amazon.com/transcribe/latest/APIReference/API_streaming_StartStreamTranscription.html#API_streaming_StartStreamTranscription_RequestParameters

In the AWS Transcribe one it says
```
IdentifyLanguage 
        Enables automatic language identification for your transcription.

        If you include IdentifyLanguage, you must include a list of language codes, using LanguageOptions, that you think may be present in your audio stream.

        You can also include a preferred language using PreferredLanguage. Adding a preferred language can help Amazon Transcribe identify the language faster than if you omit this parameter.
```

Does it work if you add the LanguageCode?

**Comment by haow-abc** [comment]
@pracheth 
I am no longer involved with this project, so you'll need to test and verify this on your end. I believe I tried various combinations before, but none of them worked.

**Comment by michhyun1** [comment]
I'll close this ticket for now - as the documentation is clear what is needed. Please create a new ticket if you need.
