### ISSUE TITLE
getFloatTimeDomainData function undefined on ios Devices for Audio preview 

### ISSUE THREAD

**Issue by JannikSt** [aws/amazon-chime-sdk-js#287]
**Describe the bug**
As demonstrated in the browser demo app, we utilize the getFloatTimeDomainData function to show the audio input preview in our current webapp when the user selects their devices. This works fine on Android and on the supported desktop browsers. Unfortunately, the function remains undefined on ios devices, thus no inputaudiopreview can be shown. 

Is there something I'm missing here? 

I appreciate your help. 

**Logs** 
[...] 
[Info] 2020-04-20T13:50:01.427Z [INFO] SDK - API/DefaultAudioVideoFacade/232d5f5c-3539-4859-8c33-fbab2443caca/43c9d898-7795-4cba-890b-26b26b3d016a/createAnalyserNodeForAudioInput

[Info] 2020-04-20T13:50:01.429Z [INFO] SDK - requesting new audio device with constraint [object Object] 

[Info] 2020-04-20T13:50:01.430Z [INFO] SDK - API/DefaultAudioVideoFacade/232d5f5c-3539-4859-8c33-fbab2443caca/43c9d898-7795-4cba-890b-26b26b3d016a/chooseAudioInputDevice "523A254EE29807796C70E38C5F678C1340494703"
[Info] 2020-04-20T13:50:02.510Z [INFO] SDK - got audio device for constraints {"audio":{"deviceId":{"exact":"523A254EE29807796C70E38C5F678C1340494703"},"echoCancellation":true,"googEchoCancellation":true,"googAutoGainControl":true,"googNoiseSuppression":true,"googHighpassFilter":true,"googNoiseSuppression2":true,"googEchoCancellation2":true,"googAutoGainControl2":true}} 

[Info] 2020-04-20T13:50:02.511Z [INFO] SDK - checking whether existing audio device can be reused 

[Info] 2020-04-20T13:50:02.511Z [INFO] SDK - reusing existing audio device 

[Info] 2020-04-20T13:50:02.512Z [INFO] SDK - cannot replace audio track due to: no active meeting and peer connection 

[Info] 2020-04-20T13:50:02.512Z [INFO] SDK - API/DefaultDeviceController/chooseAudioInputDevice "523A254EE29807796C70E38C5F678C1340494703" -> "PermissionGrantedByUser" 

[Info] 2020-04-20T13:50:02.873Z [INFO] SDK - API/DefaultDeviceController/createAnalyserNodeForAudioInput 

[Info] 2020-04-20T13:50:02.873Z [INFO] SDK - API/DefaultAudioVideoFacade/232d5f5c-3539-4859-8c33-fbab2443caca/43c9d898-7795-4cba-890b-26b26b3d016a/createAnalyserNodeForAudioInput 

[Info] 2020-04-20T13:50:02.876Z [INFO] SDK - requesting new video device with constraint [object Object] 

[Info] 2020-04-20T13:50:02.876Z [INFO] SDK - API/DefaultAudioVideoFacade/232d5f5c-3539-4859-8c33-fbab2443caca/43c9d898-7795-4cba-890b-26b26b3d016a/chooseVideoInputDevice "B1CF3C284A56AD14E5FD1E8892B3CE877A2FD0EA" 

[Error] TypeError: audioPreviewNode.getFloatTimeDomainData is not a function. (In 'analyserNode.getFloatTimeDomainData(data)', 'analyserNode.getFloatTimeDomainData' is undefined)
	(anonymous function) (meeting.ts:1782)

**Platform**
 - OS: ios
 - Browser: Safari 13.0.5
 - Amazon Chime SDK: Version 1.2.31

**Comment by JannikSt** [comment]
As a short update: We assume that it used to work on ios before we upgraded the Chime SDK Version from 1.2.2 to 1.2.31.  
I hope that this might help.

**Comment by henrikheubl** [comment]
+1

**Comment by aburnson** [comment]
@JannikSt @henrikheubi

We have updated the meeting demo code to use `getByteTimeDomainData` which is supported on iOS Safari:
https://github.com/aws/amazon-chime-sdk-js/blob/master/demos/browser/app/meetingV2/meetingV2.ts#L955

So you can do something like:

```
this.setAudioPreviewPercent(0); // reset preview to 0
const analyserNode = this.audioVideo.createAnalyserNodeForAudioInput();
if (!analyserNode) {
  return;
}
const data = new Uint8Array(analyserNode.fftSize);
let frameIndex = 0;
this.analyserNodeCallback = () => {
  if (frameIndex === 0) {
    analyserNode.getByteTimeDomainData(data);
    const lowest = 0.01;
    let max = lowest;
    for (const f of data) {
      max = Math.max(max, (f - 128) / 128);
    }
    let normalized = (Math.log(lowest) - Math.log(max)) / Math.log(lowest);
    let percent = Math.min(Math.max(normalized * 100, 0), 100);
    this.setAudioPreviewPercent(percent); // update preview to percentage
  }
  frameIndex = (frameIndex + 1) % 2;
  requestAnimationFrame(this.analyserNodeCallback);
};
requestAnimationFrame(this.analyserNodeCallback);
```

**Comment by JannikSt** [comment]
Awesome @aburnson - this worked 💯
