### ISSUE TITLE
Screen share not working as expected in Firefox and Safari

### ISSUE THREAD

**Issue by virajhk** [aws/amazon-chime-sdk-js#2871]
### What happened and what did you expect to happen?

When a user tries to share screen on Firefox and Safari, the presenter sees that the screen is being shared, but the receiver doesn't see anything being presented. Presenter also sees the following error in console:

```
[ERROR] ChimeComponentLibraryReactDemo - error during state Connected with action FinishUpdating: TypeError: this.meetingSessionContext.videoCaptureAndEncodeParameter is undefined
```

Upon clicking stop sharing, nothing happens and the presenter's screen is stuck in sharing mode until the browser window is refreshed.

Attaching a video for reference:

https://github.com/aws/amazon-chime-sdk-js/assets/4435293/ad1c7bb4-1ff6-4311-a6b4-b8f87b905adb

Note: Screen sharing works perfectly in Chrome.

### Have you reviewed our existing documentation?

- [X] GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [X] FAQs [page](https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html)
- [X] README [page](https://github.com/aws/amazon-chime-sdk-js#amazon-chime-sdk-for-javascript)
- [X] Feature-specific [guides](https://github.com/aws/amazon-chime-sdk-js#guides)

### Reproduction steps

Try sharing screen on Firefox/Safari and notice that the presenter is able to see that the screen is being shared, but the receiver doesn't see anything. Also, upon trying to stop sharing, notice that contentShareDidStop callback doesn't get triggered when it's added as an observer in `audioVideo.addContentShareObserver`.

### Amazon Chime SDK for JavaScript version

3.17.0

### What browsers are you seeing the problem on?

Firefox and Safari

### Browser version

Firefox - 124.0.2 (64-bit), Safari - 17.2.1 (19617.1.17.11.12)

### Browser console logs

```
[ERROR] ChimeComponentLibraryReactDemo - error during state Connected with action FinishUpdating: TypeError: this.meetingSessionContext.videoCaptureAndEncodeParameter is undefined
```

**Comment by paulocastellano** [comment]
+1

**Comment by hensmi-amazon** [comment]
Is this only in the React components library?

**Comment by ltrung** [comment]
Can you attach the full browser log to us or cut us a support ticket?

**Comment by xd6** [comment]
We're seeing this issue with Firefox build 126. I found it was due to this screen share simulcasting (https://github.com/aws/amazon-chime-sdk-js/blob/main/src/audiovideocontroller/DefaultAudioVideoController.ts#L1140). When I removed this call `meetingSession.audioVideo.enableSimulcastForContentShare(true)` it fixed the issue on Firefox.

**Comment by hensmi-amazon** [comment]
I don't think we support simulcast for camera or screen share on Firefox at this time. You should gate usage of that function with a check on the browser.

**Comment by hensmi-amazon** [comment]
Please reopen if the issue is not when using simulcast on firefox or safari.
