### ISSUE TITLE
Latest Chime SDK(Messaging) is not compatible with old app instance arns

### ISSUE THREAD

**Issue by VibinGowtham** [aws/amazon-chime-sdk-js#2872]
### What happened and what did you expect to happen?

After migrating from `"aws-sdk": "^2.1377.0"` to `"@aws-sdk/client-chime": "^3.503.1"`, I've encountered an issue regarding the listing of old appInstanceArns when using the **ListAppInstances** API. It appears that the previously created appInstanceArns are not being displayed, unlike the ones generated with` "@aws-sdk/client-chime": "^3.503.1"`. Is this expected behaviour? If so, what steps can we take to preserve the old appInstance channels and messages and continue operations on them? Any guidance on this matter would be greatly appreciated. Thank you.

### Have you reviewed our existing documentation?

- [X] GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [X] FAQs [page](https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html)
- [X] README [page](https://github.com/aws/amazon-chime-sdk-js#amazon-chime-sdk-for-javascript)
- [X] Feature-specific [guides](https://github.com/aws/amazon-chime-sdk-js#guides)

### Reproduction steps

1. Create an appInstanceArn using  `"aws-sdk": "^2.1377.0"`
2. Once created, Update the sdk to ``"@aws-sdk/client-chime": "^3.503.1"`` and use **ListAppInstances** API call to list the instances
3. Despite having previously created an **AppInstanceArn**, the list appears empty.

### Amazon Chime SDK for JavaScript version

"@aws-sdk/client-chime": "^3.503.1"

### What browsers are you seeing the problem on?

-

### Browser version

-

### Meeting and Attendee ID Information.

-

### Browser console logs

-

**Comment by brayoh** [comment]
Any updates on this issue?

**Comment by ltrung** [comment]
@VibinGowtham For messaging, I think you would want to use [@aws-sdk/client-chime-sdk-messaging](https://www.npmjs.com/package/@aws-sdk/client-chime-sdk-messaging)

**Comment by ltrung** [comment]
Also what is your region ? just double check if you use correct regional endpoint.

**Comment by VibinGowtham** [comment]
Hi @ltrung, It seems like we have to use a combination of @aws-sdk/client-chime-sdk-identity and @aws-sdk/client-chime-sdk-messaging to make it work. For example, Use identity client for **createAppInstanceUser** API and messaging client for **listChannelMembershipsForAppInstanceUser** API.

**Comment by gmiti-amazon** [comment]
Yes, that understanding is correct. chime-sdk-identity and chime-sdk-messaging clients should be used. Let us know if additional assistance is needed.
