### ISSUE TITLE
Real time access to attendee presence 

### ISSUE THREAD

**Issue by majid20222** [aws/amazon-chime-sdk-js#2886]
**Problem Statement**

I aim to display a list of active participants in the active Chime meeting on the dashboard within my application, even if a participant with the dashboard is not present in the meeting but the meeting has other participants.

I've utilized realtimeSubscribeToAttendeeIdPresence, but it seems to be only available when the meeting is active for that specific participant. However, I wish to display the list of active participants in that active Chime meeting when that specific participant leaves the meeting and returns to their dashboard. Is there a way to achieve this? Your prompt response will be greatly appreciated.

**Documentation Reviewed**
[Amazon Chime SDK JS Documentation - Attendees](https://aws.github.io/amazon-chime-sdk-js/#attendees)

**Additional Information**
I'm using amazon-chime-sdk-js version 3.21.1 in Angular 15.

**Comment by hensmi-amazon** [comment]
The only way i think this would be possible would be to listen to join, leave, and dropped events (https://docs.aws.amazon.com/chime-sdk/latest/dg/using-events.html) in an AWS Lambda or something of that sort, saving those (e.g. in a DB), and making them available to your application.
