### ISSUE TITLE
Expose API to query support H.264 on JS SDK

### ISSUE THREAD

**Issue by vidya-mohan** [aws/amazon-chime-sdk-js#289]
Video doesn't render for web applications build on the Chime JS on certain mobile devices such as Huawei.  We see a slate such as the following:

![image](https://user-images.githubusercontent.com/55210968/79787924-aa5fdc80-82fc-11ea-9ee6-726989cf6f0e.png)

At present we are currently not supporting a website built with Amazon Chime SDK for JavaScript on a mobile browser (https://docs.aws.amazon.com/chime/latest/dg/meetings-sdk.html#mtg-browsers has the list of browsers officially supported).

Chime uses H.264 for video encoding and decoding to achieve hardware acceleration for better video performance. There are some devices which do not natively support H.264 because of licensing. Currently devices with Qualcom chipset with Android API higher than Kitkat Version 19 or Exynos chipset with Android API level higher than Lollipop Version 21 support it.

This issue is to track exposing an API in JS SDK that would add support in Browser behavior for H.264 in the browser so applications can gracefully show a WARNing or error message.

**Comment by vidya-mohan** [comment]
https://github.com/aws/amazon-chime-sdk-js/pull/290

**Comment by aburnson** [comment]
The presence of H.264 support in WebRTC is now detectable like this:

```
const browserBehavior = new DefaultBrowserBehavior();
const supportsH264 = (await browserBehavior.supportedVideoCodecs()).includes('H264');
```

**Comment by yixial-amzn** [comment]
Could you please retry chrome browser on your Huawei phone? We recently made
fixes to allow Android  Chrome browser to receive H.264 even when the Android device cannot encode h.264.

**Comment by tunnelWithAC** [comment]
Hi, 

I am getting this issue on my Huawei Nova 3i, I am using Google Chrome v83.0.4103.106.
I am using v1.9.0 of the aws-chime-sdk-js.

Any advice would be much appreciated.

Thanks,
Conall
