### ISSUE TITLE
Unable to join meetings

### ISSUE THREAD

**Issue by DeanoAus** [aws/amazon-chime-sdk-js#2908]
### What happened and what did you expect to happen?

We use AWS Chime integrated into Salesforce to provide virtual care sessions for medical and mental health services. Our members access these sessions via a digital experience site on both mobile phones and PCs. This system has been running successfully in production for many months. However, this functionality has stopped working within the last 72 hours without any changes being made to our environment. As of today, none of our providers have been able to complete video therapy sessions, even with members who have previously used our services successfully.

We are observing this in the dev console:

`chimeSettings.js:1 Uncaught (in promise) TypeError: this.deviceController.startVideoInput is not a function
    at q.startVideoPreview (chimeSettings.js:1:6030)
    at a.loadScript.then.escape (chimeSettings.js:1:5793)
beaconLib.BeaconLibrary.js:41 Object
`

### Have you reviewed our existing documentation?

- [X] GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [X] FAQs [page](https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html)
- [X] README [page](https://github.com/aws/amazon-chime-sdk-js#amazon-chime-sdk-for-javascript)
- [X] Feature-specific [guides](https://github.com/aws/amazon-chime-sdk-js#guides)

### Reproduction steps

Unsure how you can reproduce this, but it's impacting our entire org.

### Amazon Chime SDK for JavaScript version

Don't know?

### What browsers are you seeing the problem on?

All.

### Browser version

All.

### Browser console logs

chimeSettings.js:1 Uncaught (in promise) TypeError: this.deviceController.startVideoInput is not a function
    at q.startVideoPreview (chimeSettings.js:1:6030)
    at a.loadScript.then.escape (chimeSettings.js:1:5793)
beaconLib.BeaconLibrary.js:41 Object

**Comment by michhyun1** [comment]
Can you verify that there have been no changes or deployments within the last 72 hours? 

You'll need to verify the version of the Chime SDK that you are using and verify that the Chime SDK dependency was not changed recently in your application and then deployed. 

We haven't had a release since May 16.

**Comment by DeanoAus** [comment]
Interesting set of developments over the last few days. Thanks for your reply, @michhyun1. 

Saleforce pushed a global update and forcing use of SDK 3.x. Unfortunately for us, our digital experience sites were making calls to a function in 2.x which was no longer available in 3.x. 

This resulted in that error and callers unable to join rooms. SF needed to push another update overnight to resolve this, unsure of the details involved in it.

**Comment by michhyun1** [comment]
https://docs.aws.amazon.com/chime-sdk/latest/dg/migrate-from-chm-namespace.html

Are you referring to this?

**Comment by hensmi-amazon** [comment]
I believe they mean https://github.com/aws/amazon-chime-sdk-js/blob/main/guides/17_Migration_to_3_0.md. @DeanoAus is there any further action needed by Chime SDK here?

**Comment by DeanoAus** [comment]
Heya, sorry - no further action required. I ended up meeting with some SF devs in San Fran who needed to deploy a further change to fix this.

Thanks @hensmi-amazon
