### ISSUE TITLE
Expected DeviceChangeObserver Callbacks not triggered when revoking device permissions from browser

### ISSUE THREAD

**Issue by mattcarnovale-streem** [aws/amazon-chime-sdk-js#2912]
### What happened and what did you expect to happen?

When a user revokes permissions to their camera or microphone using the browser settings, we expect the `videoInputStreamEnded` and `audioInputStreamEnded` callbacks offered through the `DeviceChangeObserver` to be invoked. We were able to assert this behavior using the Chrome browser on a Macbook Pro and Android mobile device (Galaxy S20 FE). However, it was observed that the same callbacks were not being invoked under the same conditions as well as with Safari when using an iPhone (iPhone 13 mini & iPhone 12). 

As a reference, here are the browser settings being used to revoke device permissions:
![image](https://github.com/aws/amazon-chime-sdk-js/assets/91098684/e2559fa9-890d-44b3-9da9-840cc05365cb)

### Have you reviewed our existing documentation?

- [X] GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [X] FAQs [page](https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html)
- [X] README [page](https://github.com/aws/amazon-chime-sdk-js#amazon-chime-sdk-for-javascript)
- [X] Feature-specific [guides](https://github.com/aws/amazon-chime-sdk-js#guides)

### Reproduction steps

Using an iPhone device:

* Allow permissions to camera and microphone when joining a Chime meeting
* Revoke permissions to either the camera or microphone while in the meeting
* Observe that the `videoInputStreamEnded` and `audioInputStreamEnded` callbacks are not invoked

### Amazon Chime SDK for JavaScript version

3.521.0

### What browsers are you seeing the problem on?

Chrome, Safari

### Browser version

Chrome: 126.0.6478.54, Safari: iOS 17.5.1

### Browser console logs

Both logs are recording start of meeting, revoking camera and then revoking microphone.

Chrome:
![Screenshot 2024-06-21 at 2 41 16 PM](https://github.com/aws/amazon-chime-sdk-js/assets/91098684/0b687a3d-d943-4fc0-9a55-fc47dc5af125)

Safari:
![image (16)](https://github.com/aws/amazon-chime-sdk-js/assets/91098684/2cee7028-2e9b-4291-8903-304657f657f9)

**Comment by michhyun1** [comment]
Thats interesting - it could be a webkit specific implementation. 

This is where we call that observer function:
https://github.com/aws/amazon-chime-sdk-js/blob/90baf9995f10fc86c1c39b91e0c2ea926138fd82/src/devicecontroller/DefaultDeviceController.ts#L1215-L1224

On the `ended` event for that media stream track. Its possible that Safari doesnt trigger that event when the permissions are turned off, however, the docs mention here that the `ended` event should be called when permissions are revoked. https://developer.mozilla.org/en-US/docs/Web/API/MediaStreamTrack/ended_event#:~:text=The%20user%20revoked%20the%20permissions%20needed%20for%20the%20data%20to%20be%20sent.

**Comment by michhyun1** [comment]
Also - what does the screen shot show? MAybe I'm misisng it but is the `videoInputStreamEnded` callback function printing something in the Chrome screenshot?

**Comment by mattcarnovale-streem** [comment]
> Also - what does the screen shot show? MAybe I'm misisng it but is the `videoInputStreamEnded` callback function printing something in the Chrome screenshot?

Oh, sorry if the screenshot was misleading (and way larger than I thought it would be). There was a lot of confusion when communicating what exactly was meant by "browser device settings" and how to revoke the permissions to trigger the expected callback, so I included a screenshot of the controls I was using when testing with Chrome.

**Comment by michhyun1** [comment]
I was talking about the chrome/safari logs screenshot haha - what is the log that is expected to be printed on `videoInputStreamEnded`?

**Comment by mattcarnovale-streem** [comment]
Ohh, those screenshots 😆 Got it!

So here are the logs when using my laptop and the Chrome browser:

Upon denying the camera permissions: 
![Screenshot 2024-06-25 at 1 25 39 PM](https://github.com/aws/amazon-chime-sdk-js/assets/91098684/8162d7a8-17a5-4930-b009-9c7a4309c865)

Upon denying the microphone permissions:
![Screenshot 2024-06-25 at 1 26 58 PM](https://github.com/aws/amazon-chime-sdk-js/assets/91098684/abaa5ff7-0bc2-4a6a-a580-b4fa21439ea0)

The last `INFO` and `WARN` log coming from `sdk-chime-video` are coming from our `videoInputStreamEnded` callback implementation. We aren't see these logs or that `WARN` from `chime-sdk-js` when revoking the device permission on an iPhone.

**Comment by michhyun1** [comment]
I've submitted a bug for webkit, I'm not sure why that event is not fired https://bugs.webkit.org/show_bug.cgi?id=275918

**Comment by xuesichao** [comment]
It seems once you grant permission to Safari, it only has pause/resume option. Not like Chrome where you can deny it. For Safari, the `ended` callback is not invoked in such case.

You could verify this behavior by using below code pen:
https://codepen.io/xuesichao/pen/abrrLzN

I also share the code here:
```js
if (navigator.mediaDevices && navigator.mediaDevices.getUserMedia) {
  const constraints = {
    audio: true,
    video: true
  };

  navigator.mediaDevices.getUserMedia(constraints)
    .then((stream) => {
      console.log('Media stream obtained successfully:', stream);

      // Create a container div for the overlay
      const overlayContainer = document.createElement('div');
      overlayContainer.style.position = 'absolute';
      overlayContainer.style.top = '10px';
      overlayContainer.style.left = '10px';
      overlayContainer.style.backgroundColor = 'rgba(0, 0, 0, 0.7)';
      overlayContainer.style.padding = '10px';
      overlayContainer.style.borderRadius = '5px';
      overlayContainer.style.display = 'flex';
      overlayContainer.style.flexDirection = 'column';
      overlayContainer.style.alignItems = 'flex-start';
      document.body.appendChild(overlayContainer);

      // Create and attach the video element to the container
      const videoElement = document.createElement('video');
      videoElement.srcObject = stream;
      videoElement.autoplay = true;
      videoElement.style.width = '300px';
      videoElement.style.borderRadius = '5px';
      overlayContainer.appendChild(videoElement);

      // Create and attach the message element to the container
      const messageElement = document.createElement('p');
      messageElement.style.color = 'white';
      messageElement.style.marginTop = '10px';
      overlayContainer.appendChild(messageElement);

      // Add event listeners for ended events
      stream.getTracks().forEach((track) => {
        track.addEventListener('ended', () => {
          const message = `Track ended: ${track.kind}`;
          console.log(message);
          messageElement.textContent += message + '\n';
        });
      });
    })
    .catch((error) => {
      console.error('Error accessing media devices:', error);

      // Display error message in the document
      const overlayContainer = document.createElement('div');
      overlayContainer.style.position = 'absolute';
      overlayContainer.style.top = '10px';
      overlayContainer.style.left = '10px';
      overlayContainer.style.backgroundColor = 'rgba(255, 0, 0, 0.7)';
      overlayContainer.style.padding = '10px';
      overlayContainer.style.borderRadius = '5px';
      document.body.appendChild(overlayContainer);

      const errorMessage = document.createElement('p');
      errorMessage.style.color = 'white';
      errorMessage.textContent = `Error accessing media devices: ${error.message}`;
      overlayContainer.appendChild(errorMessage);
    });
} else {
  console.error('getUserMedia is not supported in this browser.');

  // Display a message if getUserMedia is not supported
  const overlayContainer = document.createElement('div');
  overlayContainer.style.position = 'absolute';
  overlayContainer.style.top = '10px';
  overlayContainer.style.left = '10px';
  overlayContainer.style.backgroundColor = 'rgba(255, 0, 0, 0.7)';
  overlayContainer.style.padding = '10px';
  overlayContainer.style.borderRadius = '5px';
  document.body.appendChild(overlayContainer);

  const notSupportedMessage = document.createElement('p');
  notSupportedMessage.style.color = 'white';
  notSupportedMessage.textContent = 'getUserMedia is not supported in this browser.';
  overlayContainer.appendChild(notSupportedMessage);
}

```

**Comment by mattcarnovale-streem** [comment]
I see, so the documentation should probably be updated to indicate this is not supported in Safari as a result of the behavior you've verified. Shouldn't it?

Was this issue closed because a bug was submitted for webkit? The comment above doesn't address the fact that the callback is not triggerd when using Chrome with an iPhone which is part of the issue reported.

**Comment by xuesichao** [comment]
I closed this issue because it's a browser behavior. The mediaStreamTrack is not ended when revoking the permission using iOS Safari and iOS Chrome, and that's why the `DeviceChangeObserver` is not triggered. This is browser behavior.

>The comment above doesn't address the fact that the callback is not triggerd when using Chrome with an iPhone which is part of the issue reported.

iOS Chrome also does not support this feature, as it uses the same WebKit engine as iOS Safari. You can verify this behavior using the provided CodePen example.

@mattcarnovale-streem Could you elaborate your use case a bit more regarding the need of revoking the device permission? Browser has limited support regarding device permission check.

**Comment by eric-carlson** [comment]
What API does Chime call when a user revokes permissions? IOW, what is supposed to stop the track?

**Comment by xuesichao** [comment]
>What API does Chime call when a user revokes permissions? IOW, what is supposed to stop the track?

Hi @eric-carlson, the "revoke permission" mentioned in this issue is human/manual operation using Safari browser UI, Chime SDK is not related.

The flow is:
1. Chime SDK calls `getUserMedia` to request audio input and audio output device permission. 
2. A user uses Safari browser UI to revoke/disable camera and microphone permission.
3. Since the permission is revoked, user expects the media stream track returned by `getUserMedia` fires [`ended`](https://developer.mozilla.org/en-US/docs/Web/API/MediaStreamTrack/ended_event) event.
  - Chrome and Firefox does fire the event but Safari does not

**Comment by mattcarnovale-streem** [comment]
> @mattcarnovale-streem Could you elaborate your use case a bit more regarding the need of revoking the device permission? Browser has limited support regarding device permission check.

@xuesichao Thanks for explaining this a little further! We were hoping we'd be able to use the event to prompt or update the UI to communicate when a user has revoked permissions or used the browser settings to turn off their device. We're able to do this for other scenarios like when the user mute/unmutes or backgrounds the browser, but in this case the screen just goes black. It was also observed that when using the world-facing/environment camera it switches devices (it sort of looks like an aspect ratio change) when the user turns the device back on using this setting during the meeting, so it seems like the video is not restarting properly in this case.
