### ISSUE TITLE
Memory leak on meetingSession.audioVideo.start()

### ISSUE THREAD

**Issue by NirmalmaheshSubramani** [aws/amazon-chime-sdk-js#2916]
### What happened and what did you expect to happen?

I am using amazon-chime-sdk-js to create voice meetings. As soon as I call **meetingSession.audioVideo.start();** It is creating the DedicatedWorkerGlobalScope in the JS Heap memory.

This Heap object is not cleaned up and keep on added for every new invocation of meetingSession.audioVideo.start().

<img width="1178" alt="image" src="https://github.com/aws/amazon-chime-sdk-js/assets/155656500/ee9e09fa-9214-4bc3-8db3-92aec86b5cb3">

### Have you reviewed our existing documentation?

- [X] GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [ ] FAQs [page](https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html)
- [ ] README [page](https://github.com/aws/amazon-chime-sdk-js#amazon-chime-sdk-for-javascript)
- [ ] Feature-specific [guides](https://github.com/aws/amazon-chime-sdk-js#guides)

### Reproduction steps

  const startMeeting = async () => {
    if (!service.meetingSession) {
      console.warn('DEBUG: Meeting session not found');
      return;
    }
    service.meetingSession.audioVideo.start();
  };

### Amazon Chime SDK for JavaScript version

3.19.0

### What browsers are you seeing the problem on?

Chrome

### Browser version

Version 126.0.6478.63 (Official Build) (arm64)

### Browser console logs

NA

**Comment by NirmalmaheshSubramani** [comment]
Noticed there is an existing bug in the amazon-chime-sdk-ios for the same issue

https://github.com/aws/amazon-chime-sdk-ios/issues/570

**Comment by xuesichao** [comment]
Hi @NirmalmaheshSubramani , I couldn't reproduce this issue using our meetingV2 browser demo. Could you give it a try there?
