### ISSUE TITLE
issue with running build-layer

### ISSUE THREAD

**Issue by BHAWANA-SHUKLA** [aws/amazon-chime-sdk-js#292]
i am facing following error

> video-help-desk@0.1.0 build-layer E:\amazon-chime-sdk-js\demos\videohelpdesk
> ./create-layer

'.' is not recognized as an internal or external command

**Comment by aburnson** [comment]
> E:\amazon-chime-sdk-js\demos\videohelpdesk ./create-layer

Have you tried following the steps here: https://github.com/aws/amazon-chime-sdk-js/tree/master/demos/videohelpdesk ?

This demo is intended to be run from a Cloud9 environment and depends on having a Unix-based shell.
