### ISSUE TITLE
Problem in using Transcription

### ISSUE THREAD

**Issue by testcarter** [aws/amazon-chime-sdk-js#2925]
### What happened and what did you expect to happen?

I want to know that in the Amazon Chime SDK demo, if we want to enable the live transcription feature, do we just need to click on a button? I am unable to do so. Why is this happening?
Please provide me with the solution. Do I need to set up something in AWS for this or will it work as is? What is the issue, please explain.

### Have you reviewed our existing documentation?

- [X] GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [X] FAQs [page](https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html)
- [X] README [page](https://github.com/aws/amazon-chime-sdk-js#amazon-chime-sdk-for-javascript)
- [X] Feature-specific [guides](https://github.com/aws/amazon-chime-sdk-js#guides)

### Reproduction steps

in all browsers

### Amazon Chime SDK for JavaScript version

na

### What browsers are you seeing the problem on?

na

### Browser version

na

### Meeting and Attendee ID Information.

I want to know that in the Amazon Chime SDK demo, if we want to enable the live transcription feature, do we just need to click on a button? I am unable to do so. Why is this happening?
Please provide me with the solution. Do I need to set up something in AWS for this or will it work as is? What is the issue, please explain.

### Browser console logs

I want to know that in the Amazon Chime SDK demo, if we want to enable the live transcription feature, do we just need to click on a button? I am unable to do so. Why is this happening?
Please provide me with the solution. Do I need to set up something in AWS for this or will it work as is? What is the issue, please explain.

**Comment by jhu82** [comment]
Hi, 

To setup transcription, you can follow the demo steps here - https://github.com/aws-samples/amazon-chime-media-capture-pipeline-demo
