### ISSUE TITLE
iPhone: switches camera after browser is backgrounded

### ISSUE THREAD

**Issue by nathan-wright-streem** [aws/amazon-chime-sdk-js#2930]
### What happened and what did you expect to happen?

I have an iPhone 14 with iOS 17.5.1.  The following steps cause the camera to be switched using the sample app:

1. start meeting 
2. turn on camera and choose `Back Dual Wide Camera`
3. background the browser
4. bring browser back to foreground

The camera will be switched to `Back Ultra Wide Camera`

Here is what is looks like prior to backgrounding:

![prior_to_background_dual_wide](https://github.com/user-attachments/assets/2017618d-dbd1-47db-ac1e-1d0a23db5ffa)

Here is after foregrounding again:
![after_background_ultra_wide](https://github.com/user-attachments/assets/91a60beb-da34-41c0-a91e-b3ea908c67e3)

This is also reproducible if you take a call with Call Notifications set to Banner.  After the call ends, you can see the camera switch.

### Have you reviewed our existing documentation?

- [X] GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [X] FAQs [page](https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html)
- [X] README [page](https://github.com/aws/amazon-chime-sdk-js#amazon-chime-sdk-for-javascript)
- [X] Feature-specific [guides](https://github.com/aws/amazon-chime-sdk-js#guides)

### Reproduction steps

1. start meeting 
2. turn on camera and choose `Back Dual Wide Camera`
3. background the browser
4. bring browser back to foreground

The camera will be switched to `Back Ultra Wide Camera`

See description for screenshot.  I have reproduced this on Safari and Chrome.

### Amazon Chime SDK for JavaScript version

3.23.0

### What browsers are you seeing the problem on?

Safari, Chrome

### Browser version

Safari 17.5.1, Chrome 127.0.6533.77

### Meeting and Attendee ID Information.

meeting: 8e72f398-ec1c-41a6-8087-2a8a40022713
attendee: 1e265567-bb38-da64-8da7-74dde369f6df

### Browser console logs

[iphone_camera_switch_console_logs.txt](https://github.com/user-attachments/files/16531321/iphone_camera_switch_console_logs.txt)

**Comment by michhyun1** [comment]
```
start meeting
turn on camera and choose Back Dual Wide Camera
background the browser
bring browser back to foreground
```

When you turn on your camera on step 2 - did you choose the default device or some other device. Also, can you confirm which is the `default` device? It could be that the logic is to select the `default` device once the app is no longer backgrounded.

**Comment by nathan-wright-streem** [comment]
Yes, the Dual Wide is the default device and it switches to the Ultra Wide.

**Comment by michhyun1** [comment]
Can you confirm which device is the default device by logging the result of `enumerateDevices` API before and after the device is backgrounded. Thanks

**Comment by nathan-wright-streem** [comment]
> It could be that the logic is to select the default device once the app is no longer backgrounded.

Do you mean logic in the Chime SDK or in the Serverless demo?  I'm not familiar enough with either code base to answer the question, but I've seen this problem in the application we are developing where there is currently no logic in place to handle `visibilitychange`.

I will try to log out the result of `enumerateDevices` later today.

**Comment by michhyun1** [comment]
Yes, I dont think we implement the visibilitychange listener in the demo app - feel free to add it yourself and implement your own custom behavior. 

You could implement it in such a way that when visibility is dropped - you can turn off the video. And once visibility comes back, you can choose the default device.

**Comment by nathan-wright-streem** [comment]
When you receive a call with call notification set to Banner mode on an iPhone, it does not trigger the `visibilitychange` event, but it does switch cameras.

**Comment by nathan-wright-streem** [comment]
I added the following to the meeting V2 [here](https://github.com/aws/amazon-chime-sdk-js/blob/279b234820559ca7f35d66a1b9fc769d84a14793/demos/browser/app/meetingV2/meetingV2.ts#L1925):

```
document.addEventListener('visibilitychange', () => { 
      this.log(`Page visibility change to ${document.visibilityState}`);

      this.audioVideo.listVideoInputDevices(true).then(devices => { 
        devices?.forEach(device => { 
          this.log(`Visibility Change: Video input devices: ${JSON.stringify(device)}`);
        });
      });
    });
```

Here are the log entries when reproducing:

```
[Log] [DEMO] Page visibility change to hidden (Prod, line 2)
[Log] [DEMO] Visibility Change: Video input devices: {"deviceId":"B33FF9E0E164E7BA300A9F481B1F7A5EF0CCF9D4","kind":"videoinput","label":"Front Camera","groupId":"78EBE146F6369E031AF0EDB1B11EF7EF50313C4B"} (Prod, line 2)
[Log] [DEMO] Visibility Change: Video input devices: {"deviceId":"1EED7C13B34013F855A77CD6024E88EFCF748746","kind":"videoinput","label":"Back Dual Wide Camera","groupId":"AF110DBAF26B4783777D2F089CDD5AD204128063"} (Prod, line 2)
[Log] [DEMO] Visibility Change: Video input devices: {"deviceId":"C458158E2BC2FDFE773BE32AC52D2EF5EB0FBE64","kind":"videoinput","label":"Back Ultra Wide Camera","groupId":"5A601A458AD0A66E894B2A711CD4EE495D75D626"} (Prod, line 2)
[Log] [DEMO] Visibility Change: Video input devices: {"deviceId":"1A0DE792CF89A0C3416A7E289A504097F62FC78B","kind":"videoinput","label":"Back Camera","groupId":"7C11BF5907DCC3FE68A1BBDB9B0DCC4DCEEED85F"} (Prod, line 2)
[Log] [DEMO] Page visibility change to visible (Prod, line 2)
[Log] [DEMO] Visibility Change: Video input devices: {"deviceId":"B33FF9E0E164E7BA300A9F481B1F7A5EF0CCF9D4","kind":"videoinput","label":"Front Camera","groupId":"78EBE146F6369E031AF0EDB1B11EF7EF50313C4B"} (Prod, line 2)
[Log] [DEMO] Visibility Change: Video input devices: {"deviceId":"1EED7C13B34013F855A77CD6024E88EFCF748746","kind":"videoinput","label":"Back Dual Wide Camera","groupId":"AF110DBAF26B4783777D2F089CDD5AD204128063"} (Prod, line 2)
[Log] [DEMO] Visibility Change: Video input devices: {"deviceId":"C458158E2BC2FDFE773BE32AC52D2EF5EB0FBE64","kind":"videoinput","label":"Back Ultra Wide Camera","groupId":"5A601A458AD0A66E894B2A711CD4EE495D75D626"} (Prod, line 2)
[Log] [DEMO] Visibility Change: Video input devices: {"deviceId":"1A0DE792CF89A0C3416A7E289A504097F62FC78B","kind":"videoinput","label":"Back Camera","groupId":"7C11BF5907DCC3FE68A1BBDB9B0DCC4DCEEED85F"} (Prod, line 2)
```

None of these are labeled as default either before or after backgrounding.

**Comment by ltrung** [comment]
@nathan-wright-streem Thank you for helping reproduce the issue. I have been also able to reproduce the issue with the WebRTC sample demo in my iphone 14 https://webrtc.github.io/samples/src/content/devices/input-output/ following the steps you provided. 
You can see with the sample that the camera is switched to `Back Ultra Wide` even though the Id is still for `Back Dual Wide` and thus this is a browser/iOS bug and is not related to our SDK (the library itself or the demo does not do any logic to select camera when switching to foreground/background.
I would suggest to submit the issue to Apple.

**Comment by ltrung** [comment]
In the mean time, if you may need to use visibilityChange to reselect the camera once the app becomes visible again. However, that would cause a bit of flashing between camera switching and is not an ideal experience.

**Comment by ltrung** [comment]
@nathan-wright-streem to clarify, do you mean if you receive a call notification (unrelated to your website) in iphone the web browser will become background and foreground again (when users reject the call) the visibility event does not trigger?

**Comment by nathan-wright-streem** [comment]
Yes, @ltrung .  The visibility event is not triggered.  (I am guessing IOS does not consider it backgrounding / foregrounding because it really just displays a banner across the top of the screen.)

![IncomingCall](https://github.com/user-attachments/assets/ea4b857e-54a5-4337-b196-ef649f2862a6)

**Comment by georgezy-amzn** [comment]
Hi @nathan-wright-streem,

With further test, this behaviour happens only if choosing "Back Triple Camera"/"Back Dual Wide Camera". If choose "Back Dual Camera"/"Back Camera", it will NOT switch to "Back Ultra Wide Camera". As a workaround you may want to consider use "Back Dual Camera"/"Back Camera" instead, and remove "Back Triple Camera"/"Back Dual Wide Camera" in your list so that users will not be able to select them.

**Comment by ltrung** [comment]
@nathan-wright-streem I think this is the bug report for this issue https://bugs.webkit.org/show_bug.cgi?id=262416 for webkit. I would recommend to post your issue there too.

In the latest comment, there is a workaround suggest which is to use zoom: false. Can you try that?
Something like
```
await navigator.mediaDevices.getUserMedia({video: { zoom: false, deviceId: <your cameraId> }})
```

**Comment by nathan-wright-streem** [comment]
Thanks @ltrung  and @georgezy-amzn .  The webkit bug does sound very similar. 

I will try these workarounds.
