### ISSUE TITLE
microphone is not enabling when unmuting microphone in ionic angular mobile application?

### ISSUE THREAD

**Issue by idb-umangtyagi** [aws/amazon-chime-sdk-js#2933]
microphone is not enabling when unmuting microphone in ionic angular mobile application?

**Comment by yochum** [comment]
Please submit using the bug report form to ensure all necessary details are provided:
https://github.com/aws/amazon-chime-sdk-js/issues/new?assignees=&labels=&projects=&template=bug-report.yaml
