### ISSUE TITLE
Getting 403 ForbiddenException when creating media capture pipeline

### ISSUE THREAD

**Issue by euro-bYte** [aws/amazon-chime-sdk-js#2935]
### What happened and what did you expect to happen?

When running `createMediaCapturePipeline` our logs show an error occurs:

```
"message": "Insufficient permission to access S3 bucket: pqcast-mediacapture-pipeline-sink-dev"
```

Full message:
![Screen Shot 2024-08-15 at 1 35 09 PM](https://github.com/user-attachments/assets/c0be0fa3-4844-4025-b837-d9c8f9d5ec87)

When running the pipeline locally - it works, but when deployed to AWS it doesn't 

Here is a brief overview of our setup:
we use AWS EKS for our backend and make the call to `createMediaCapturePipeline` as follows:

```ts
  public async createMediaCapturePipeline(meetingId: string): Promise<MediaCapturePipeline> {
    logger.info({
      name: 'AwsChimeService#createMediaCapturePipeline',
      msg: 'Creating Media Capture Pipeline',
      meetingId,
      MEDIA_CAPTURE_PIPELINE_SINK
    })
  
    let createPipelineResponse: CreateMediaCapturePipelineCommandOutput
    try {
      createPipelineResponse = await this.chimeMediaPipelines.createMediaCapturePipeline({
        SourceArn: getChimeSourceArn(meetingId),
        SourceType: 'ChimeSdkMeeting',
        SinkType: 'S3Bucket',
        SinkArn: MEDIA_CAPTURE_PIPELINE_SINK,
        ChimeSdkMeetingConfiguration: {
          ArtifactsConfiguration: {
            Audio: {
              MuxType: AudioMuxType.AudioOnly,
            },
            Video: {
              State: "Enabled",
              MuxType: "VideoOnly",
            },
            Content: {
              State: "Enabled",
              MuxType: "ContentOnly",
            },
          }
        }
      })
    } catch (err) {
      logger.error({ name: 'AwsChimeService', msg: 'Error while creating Chime Media Capture Pipeline', err })
      throw new Error('Unable to create Chime Media Capture Pipeline')
    }

    if (!createPipelineResponse.MediaCapturePipeline) {
      throw new Error('Media Capture Pipeline is not defined')
    }

    return createPipelineResponse.MediaCapturePipeline
  }
```

Our buckets have the correct policies attached based on the documentation.

I also created a custom role and policy, but I don't know how to get the service `mediapipelines.chime.amazonaws.com` to use it so it can access S3 properly.

Can anyone provide a solution to fix this? 

### Have you reviewed our existing documentation?

- [X] GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [X] FAQs [page](https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html)
- [X] README [page](https://github.com/aws/amazon-chime-sdk-js#amazon-chime-sdk-for-javascript)
- [X] Feature-specific [guides](https://github.com/aws/amazon-chime-sdk-js#guides)

### Reproduction steps

Just follow the documentation [here](https://docs.aws.amazon.com/chime-sdk/latest/dg/create-pipeline.html) and deploy to AWS using EKS using a fargate pod.
 

### Amazon Chime SDK for JavaScript version

3.485.0

### What browsers are you seeing the problem on?

chrome

### Browser version

Version 127.0.6533.100

### Browser console logs

![Screen Shot 2024-08-15 at 1 35 09 PM](https://github.com/user-attachments/assets/42893228-03e7-4990-b7d6-35cf3cdd1345)

**Comment by niborkar** [comment]
Have you followed this doc to ensure you have the required S3 permissions- https://docs.aws.amazon.com/chime-sdk/latest/dg/create-s3-bucket.html

**Comment by euro-bYte** [comment]
I was able to figure it out It required specific S2 Get permissions to work

**Comment by saewitz** [comment]
@euro-bYte we are getting the same error, can you please share how you resolved it?

**Comment by euro-bYte** [comment]
@saewitz Sorry for the late reply - what we had to do is make sure the roles that would be used to make the request to the buckets would need to have the permissions to those buckets and the following actions:

```JSON
"Action": [
                "s3:GetBucketPolicy",
                "s3:PutObject",
                "s3:PutObjectAcl",
                "s3:GetObject",
                "s3:ListBucket"
            ]
```
