### ISSUE TITLE
Enhance start Method to Support Immediate Retrieval of Remote Video Sources

### ISSUE THREAD

**Issue by funayamateppei** [aws/amazon-chime-sdk-js#2939]
# Community Note
* Please vote for this issue by adding a 👍 reaction to the issue. This will help the community and maintainers from the Amazon Chime SDK team to prioritize this request.
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request.
* Please go through the existing [issues](https://github.com/aws/amazon-chime-sdk-js/issues) to see if your request has already been recommended.
* Please do not use this template for bugs or support. Each individual repository has a PR template, documentation and resources for [troubleshooting](https://github.com/aws/amazon-chime-sdk-js#troubleshooting-and-support).
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.

# Tell us about your request
## What do you want us to build?
The request is for the [amazon-chime-sdk-js](https://github.com/aws/amazon-chime-sdk-js) package.

## Tell us about the problem you are trying to solve and why is it hard?
When attempting to retrieve the list of participants immediately after connecting to a call using `start` and then calling `getRemoteVideoSources`, an empty array is returned despite participants being present. It seems that the `start` method does not return an instance that can retrieve the list of participants right after the call connection.

It would be helpful if `start` could return an instance that allows retrieving the list of participants immediately. Alternatively, is there a method to retrieve the list of participants right when the call is connected?

Additionally, it would be helpful if the `start` method were asynchronous. Currently, we have to work around this by using `setTimeout` to wait for one second before attempting to retrieve the list of participants.

## How are you currently solving a problem?
Currently, there is no effective workaround as the `getRemoteVideoSources` method returns an empty array immediately after connecting to a call. We are using `setTimeout` to wait for one second before calling `getRemoteVideoSources`, but this is not an ideal solution.

## Additional context
```ts
const meetingConfig = new MeetingSessionConfiguration(sessionResponse.meeting, sessionResponse.attendee)
const meetingSession = new DefaultMeetingSession(meetingConfig, logger, deviceController)
meetingSession.audioVideo.start()

const videoSources = meetingSession.audioVideo.getRemoteVideoSources()
console.log(videoSources) // []
```
This code uses setTimeout to wait for one second before calling getRemoteVideoSources to retrieve the list of participants, as the method returns an empty array immediately after the call connection, despite participants being present.
```ts
setTimeout(() => {
  const videoSources = meetingSession.audioVideo.getRemoteVideoSources()
  console.log(videoSources)
}, 1000);
```

**Comment by ltrung** [comment]
start process is designed to be async and cannot return results until connection established with backend.
Instead of using setTimeout, please use `audioVideoDidStart` event to know when the meeting connects and you can use that function. See https://github.com/aws/amazon-chime-sdk-js/blob/main/README.md#starting-a-session.
