### ISSUE TITLE
Understanding how realtimeSubscribeToLocalSignalStrengthChange works

### ISSUE THREAD

**Issue by euro-bYte** [aws/amazon-chime-sdk-js#2945]
### What are you trying to do?

I am trying to get signal strength changes from `realtimeSubscribeToLocalSignalStrengthChange` and use that value to update the client

### How can the documentation be improved to help your use case?

I don't know what the value ranges are from bad to good - I keep getting a value of 1. Is it between 0 and 1 or only 1 and 0

### What documentation have you looked at so far?

- [AWS SDK for JavaScript v3](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- https://aws.github.io/amazon-chime-sdk-js/interfaces/audiovideofacade.html#realtimesubscribetolocalsignalstrengthchange

**Comment by ltrung** [comment]
Here is the doc for this [realtimeSubscribeToLocalSignalStrengthChange](https://aws.github.io/amazon-chime-sdk-js/interfaces/audiovideofacade.html#realtimesubscribetolocalsignalstrengthchange)
It is to track the audio signal of the local attendee. 
Most of the time you would want to use [realtimeSubscribeToVolumeIndicator](https://aws.github.io/amazon-chime-sdk-js/interfaces/audiovideofacade.html#realtimesubscribetovolumeindicator)] to monitor attendee's volume
