### ISSUE TITLE
Add support for device and network connectivity check to chime media server

### ISSUE THREAD

**Issue by vidya-mohan** [aws/amazon-chime-sdk-js#295]
### What are you trying to do?
Add support much like the way the Chime applications do it in https://app.chime.aws/check to test device and network connectivity that developers can invoke for simple checks. 

### How can the documentation be improved to help your use case?
Preferably expose and API that would log this.

### What documentation have you looked at so far?

*For example: README.md, Amazon Chime SDK Developer Guide, etc.

**Comment by peternijssen** [comment]
This would really be helpful. Are there already some parts that can be used?

**Comment by vidya-mohan** [comment]
@peternijssen this is now launched in https://www.npmjs.com/package/amazon-chime-sdk-js - 1.17.0! https://github.com/aws/amazon-chime-sdk-js#meeting-readiness-checker has documentation

**Comment by peternijssen** [comment]
Awesome work guys. Thanks!

**Comment by vidya-mohan** [comment]
Right now you cant @hungnguyen1412 - we do create a meeting as those URls are not something you can take a dependency on - they are particular to a region and ephemeral. The point of that check is to do end to end connectivity not local checks.  For bandwidth - that can change over the course of a session and may not be useful check prior to joining a meeting unlike other checks so please add details on why this is valuable. You can use the right policies and observers to manage your meeting experience as highlighted in .

For feature requests, please add details and the justification using the community request template when creating a new issue
