### ISSUE TITLE
AudioRedWorker guaranteed to leak after terminating a call

### ISSUE THREAD

**Issue by issacgerges** [aws/amazon-chime-sdk-js#2956]
### What happened and what did you expect to happen?

When terminating a call when `audioRed` was enabled, the `this.audioRedWorker` reference is cleaned up, but the worker isn't explicitly terminated. This means the worker will live on for the length of the session, retaining some memory

![image](https://github.com/user-attachments/assets/00922655-fdac-4be9-a8d3-805ed76d96ce)

The following should call `this.audoRedWorker.terminate()` before removing the reference via `this.audioRedWorker = null;`

https://github.com/aws/amazon-chime-sdk-js/blob/b4e0280f2183c0256c5a1d42a70b4b6c7fcf93e8/src/transceivercontroller/DefaultTransceiverController.ts#L630-L645

### Have you reviewed our existing documentation?

- [X] GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [X] FAQs [page](https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html)
- [X] README [page](https://github.com/aws/amazon-chime-sdk-js#amazon-chime-sdk-for-javascript)
- [X] Feature-specific [guides](https://github.com/aws/amazon-chime-sdk-js#guides)

### Reproduction steps

Create a call with `audioRed` enabled and end it and see the worker global scopes retained

### Amazon Chime SDK for JavaScript version

3.23.0

### What browsers are you seeing the problem on?

Chromium

### Browser version

128.0.6613.120

### Browser console logs

n/a

**Comment by hensmi-amazon** [comment]
Made change recommended in https://github.com/aws/amazon-chime-sdk-js/pull/2960, thanks!

**Comment by ltrung** [comment]
Fix has been merged. Closing for now.
