### ISSUE TITLE
Show a demo sample how applications can find the best media region to connect to from an endpoint

### ISSUE THREAD

**Issue by vidya-mohan** [aws/amazon-chime-sdk-js#297]
### What are you trying to do?
When creating a meeting, there is an option to specify the media region. Chime has atleast 14 regions, how do the application find the best media region to connect to from an endpoint

### How can the documentation be improved to help your use case?
Currently the Github documentation does not have this documented. The blog https://aws.amazon.com/blogs/business-productivity/building-a-meeting-application-using-the-amazon-chime-sdk/ does have this blurb:

_"A media region that is closer to your users can be specified to minimize latency. Your application should identify the best region to host the meeting before calling the CreateMeeting API. Regions with media services include ap-northeast-1, ap-southeast-1, ap-southeast-2, ca-central-1, eu-central-1, eu-north-1, eu-west-1, eu-west-2, eu-west-3, sa-east-1, us-east-1, us-east-2, us-west-1, and us-west-2. You can use https://l.chime.aws to return the region closest to the user."_

### What documentation have you looked at so far?
README.md, Amazon Chime SDK Developer Guide, etc.

**Comment by RidipDe** [comment]
PR: https://github.com/aws/amazon-chime-sdk-js/pull/363
Documentation: https://docs.aws.amazon.com/chime/latest/dg/chime-sdk-meetings-regions.html
