### ISSUE TITLE
media concate pipeline status is still showing `InProgress`

### ISSUE THREAD

**Issue by AnkurSavaliya** [aws/amazon-chime-sdk-js#2970]
### What happened and what did you expect to happen?

Please check why my media concate pipeline status still shows `InProgress`?

`{ "MediaPipeline": { "MediaConcatenationPipeline": { "MediaPipelineId": "72da8927-66d8-49b8-84ca-896c700c36c8", "MediaPipelineArn": "arn:aws:chime:us-east-1:AcountId:media-pipeline/72da8927-66d8-49b8-84ca-896c700c36c8", "Sources": [Object ], "Sinks": [Object ], "Status": "InProgress", "CreatedTimestamp": "2024-10-16T06:35:02.028000+00:00", "UpdatedTimestamp": "2024-10-16T06:35:22.277000+00:00" } } } `

### Have you reviewed our existing documentation?

- [X] GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [X] FAQs [page](https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html)
- [X] README [page](https://github.com/aws/amazon-chime-sdk-js#amazon-chime-sdk-for-javascript)
- [X] Feature-specific [guides](https://github.com/aws/amazon-chime-sdk-js#guides)

### Reproduction steps

NA

### Amazon Chime SDK for JavaScript version

3.7.0

### What browsers are you seeing the problem on?

NA

### Browser version

NA

### Meeting and Attendee ID Information.

`{ "MediaPipeline": { "MediaConcatenationPipeline": { "MediaPipelineId": "72da8927-66d8-49b8-84ca-896c700c36c8", "MediaPipelineArn": "arn:aws:chime:us-east-1:AcountId:media-pipeline/72da8927-66d8-49b8-84ca-896c700c36c8", "Sources": [Object ], "Sinks": [Object ], "Status": "InProgress", "CreatedTimestamp": "2024-10-16T06:35:02.028000+00:00", "UpdatedTimestamp": "2024-10-16T06:35:22.277000+00:00" } } } `

### Browser console logs

NA

**Comment by rixiang-dev** [comment]
The reported concatenation pipeline eventually failed after six-hour time-out, with unknown root cause not clear yet. Could you create an AWS support case on this issue? We would like to get your captured media artifacts to try locally reproducing the issue.

**Comment by vicky-bril** [comment]
@rixiang-dev , Thank you for looking into this. I have filed an AWS support case, here is the support case ID- 173070401600925.
