### ISSUE TITLE
User-defined DataMessage callback errors should not be fatal

### ISSUE THREAD

**Issue by schontz** [aws/amazon-chime-sdk-js#2974]
### What happened and what did you expect to happen?

1. `subscribeToTranscriptEvent` callback received unexpected data and threw an error
2. **Actual:** The meeting died (fatal error)
3. **Expected:** The meeting does not die

### Have you reviewed our existing documentation?

- [X] GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [X] FAQs [page](https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html)
- [X] README [page](https://github.com/aws/amazon-chime-sdk-js#amazon-chime-sdk-for-javascript)
- [X] Feature-specific [guides](https://github.com/aws/amazon-chime-sdk-js#guides)

### Reproduction steps

Something like this:

```
subscribeToTranscriptEvent(() => {
  throw new Error('bad callback');
});
```

### Amazon Chime SDK for JavaScript version

main

### What browsers are you seeing the problem on?

Chome

### Browser version

lateset

### Browser console logs

Nothing is logged to the console, because the error is swallowed up. It does exist in the logger because fatal errors are logged there.

**Comment by ltrung** [comment]
I think it is expected that realtimeAPI throw fatal error though

**Comment by ltrung** [comment]
Closing as the PR has been merged.
