### ISSUE TITLE
videoTileWasRemoved is not getting called

### ISSUE THREAD

**Issue by prashanthacharyam** [aws/amazon-chime-sdk-js#298]
**Describe the bug**
From a reactjs app.
**startLocalVideoTile** was called by clicking a button. 
**videoTileDidUpdate** gets called
Local video is displayed. 
**stopLocalVideoTile** was called by clicking a button.
**videoTileDidUpdate** gets called
But **videoTileWasRemoved** is not called.

Same issue on demos/browser on master branch of this repo.

**Platform**
 - OS: Mac OS Mojave 
 - Browser: Chrome 
 - Browser Version:  81
 - Amazon Chime SDK GitHub Commit:  1.3.0

**Comment by simmkyu** [comment]
When you call `stopLocalVideoTile`, only `videoTileDidUpdate` will be called. Chime SDK is reusing the same local tile object when you restart it by calling `startLocalVideoTile`.

`videoTileWasRemoved` gets invoked when you call `removeLocalVideoTile`. Chime SDK will remove the local video tile.

Please review the "Stop sharing your video" example in:
https://github.com/aws/amazon-chime-sdk-js#video

**Comment by prashanthacharyam** [comment]
When a remote user clicks on stopLocalVideoTile does then **videoTileWasRemoved** would be called?

**Comment by simmkyu** [comment]
> When a remote user clicks on stopLocalVideoTile does then **videoTileWasRemoved** would be called?

Yes, when a remote user calls `stopLocalVideoTile`, `videoTileWasRemoved` will be invoked in other users' SDK sessions. A [`MediaStreamTrack`](https://developer.mozilla.org/en-US/docs/Web/API/MediaStreamTrack) for this remote user is getting removed.

I just found one issue with `removeLocalVideoTile` (https://github.com/aws/amazon-chime-sdk-js/issues/304). When a remote attendee calls `removeLocalVideoTile`, other attendees should receive `videoTileWasRemoved`. In the current version, `videoTileWasRemoved` doesn't get called. Please use `stopLocalVideoTile` until #304 gets fixed.

**Comment by simmkyu** [comment]
I'll close this issue as `videoTileWasRemoved` gets called when you call `removeLocalVideoTile` ( *Stop sharing your video* in https://github.com/aws/amazon-chime-sdk-js#video). We'll keep https://github.com/aws/amazon-chime-sdk-js/issues/304 open for a bug when a remote attendee calls `removeLocalVideoTile`.
