### ISSUE TITLE
when sharing screen in ionic angular mobile app "TypeError: navigator.mediaDevices.getDisplayMedia is not a function" error is coming

### ISSUE THREAD

**Issue by idb-umangtyagi** [aws/amazon-chime-sdk-js#2990]
### What happened and what did you expect to happen?

when calling this.meetingSession.audioVideo.startContentShareFromScreenCapture() for sharing screen in ionic angular mobile app, "TypeError: navigator.mediaDevices.getDisplayMedia is not a function" error is coming.

### Have you reviewed our existing documentation?

- [X] GitHub [issues](https://github.com/aws/amazon-chime-sdk-js/issues)
- [X] FAQs [page](https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html)
- [X] README [page](https://github.com/aws/amazon-chime-sdk-js#amazon-chime-sdk-for-javascript)
- [X] Feature-specific [guides](https://github.com/aws/amazon-chime-sdk-js#guides)

### Reproduction steps

when calling this.meetingSession.audioVideo.startContentShareFromScreenCapture() for sharing screen in ionic angular mobile app, "TypeError: navigator.mediaDevices.getDisplayMedia is not a function" error is coming.

### Amazon Chime SDK for JavaScript version

3.22.0

### What browsers are you seeing the problem on?

it's an andriod app with ionic angular

### Browser version

it's an andriod app with ionic angular

### Meeting and Attendee ID Information.

meetingId 7cddae98-ac17-4c10-bb7d-452e566e2713
attendeeId f68e7deb-c2a2-42a7-7a2e-46b4b07079d0

### Browser console logs

TypeError: navigator.mediaDevices.getDisplayMedia is not a function

**Comment by hensmi-amazon** [comment]
[getDisplayMedia](https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getDisplayMedia) is a WebAPI implemented by the browser. Mobile browsers currently do not support screen share, and thus do not implement that function. There is no workaround we currently can supply.
