### ISSUE TITLE
Handle CreateMeeting and CreateAttendee API responses starting with a lowercase first letter

### ISSUE THREAD

**Issue by simmkyu** [aws/amazon-chime-sdk-js#305]
**Describe the bug**
Describe the bug and the timestamp at which it happened relative to the timestamp in the log file.

```
// You need responses from server-side Chime API. See below for details.
const meetingResponse = /* The response from the CreateMeeting API action */;
const attendeeResponse = /* The response from the CreateAttendee or BatchCreateAttendee API action */;
const configuration = new MeetingSessionConfiguration(meetingResponse, attendeeResponse);
```

[`MeetingSessionConfiguration`](https://github.com/aws/amazon-chime-sdk-js/blob/master/src/meetingsession/MeetingSessionConfiguration.ts#L113) takes in responses of `CreateMeeting` and `CreateAttendee` API actions in JSON format. In JSON response, all names start with an uppercase letter.
See [API_CreateMeeting](https://docs.aws.amazon.com/chime/latest/APIReference/API_CreateMeeting.html) and [API_CreateAttendee](https://docs.aws.amazon.com/chime/latest/APIReference/API_CreateAttendee.html).

However, *AWS SDK for Java* returns responses with a lowercase first letter. To mitigate the issue, please use the following example to create a `MeetingSessionConfiguration` object.

```
const meetingResponse = /* The CreateMeeting response from AWS SDK for Java */;
const attendeeResponse = /* The CreateAttendee response from AWS SDK for Java */ 
const configuration = new MeetingSessionConfiguration({
  "Meeting": {
     "MeetingId": meetingResponse.meeting.meetingId,
     "MediaPlacement": {
       "AudioHostUrl": meetingResponse.meeting.mediaPlacement.audioHostUrl,
       "ScreenDataUrl": meetingResponse.meeting.mediaPlacement.screenDataUrl,
       "ScreenSharingUrl": meetingResponse.meeting.mediaPlacement.screenSharingUrl,
       "ScreenViewingUrl": meetingResponse.meeting.mediaPlacement.screenViewingUrl,
       "SignalingUrl": meetingResponse.meeting.mediaPlacement.signalingUrl,
       "TurnControlUrl": meetingResponse.meeting.mediaPlacement.turnControlUrl,
     }
   }
  }
}, {
  "Attendee": {
    "ExternalUserId": attendeeResponse.attendee.externalUserId,
    "AttendeeId": attendeeResponse.attendee.attendeeId,
    "JoinToken": attendeeResponse.attendee.joinToken
  }
});
```

**Comment by rohitranjan1991** [comment]
any update on this guys ?

**Comment by EvanKnowles** [comment]
Not sure this is a minor issue - we can't create meetings because of this?

**Comment by RidipDe** [comment]
Java SDK doesn't return responses as JSON. It is returned as structured Java objects as mentioned in the public documentation https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/services/chime/model/CreateMeetingResponse.html

The Chime service sends a JSON response with upper-case starting keys as per the [API documentation](https://docs.aws.amazon.com/chime/latest/APIReference/API_CreateMeeting.html). 
The Java SDK is then deserializing that into a structured response object which might have method names that start with lower-case characters. 

Is it possible that you are probably then serializing that object back into JSON - thus giving you properties starting with lower case ?

**Comment by RidipDe** [comment]
PR to resolve such an issue has been merged with master. We made AWS SDK for Java camelCased meeting-attendee response compatible with Chime SDK for JavaScript, closing the ticket. 
https://github.com/aws/amazon-chime-sdk-js/pull/701
