### ISSUE TITLE
Do not mirror localTile when input device is rear facing

### ISSUE THREAD

**Issue by mikeantonelli** [aws/amazon-chime-sdk-js#311]
**Meeting and attendee IDs:**
n/a

**Timeline**

* Connect to a Meeting as an Attendee
* Select front-facing input device - point input device at text, verify it can be read in the localTile
* Select rear-facing input device - point input device at text, observe it is backwards in the localTile

Note: Other users in the call see the correct orientation for both input devices.

**Describe the bug**
When running the Chime SDK on a device with both front and rear facing cameras, the rear facing camera should not be flipped in the same way that the front facing camera is. 

I believe that `MediaTrackSettings#facingMode` should be used to determine the orientation (e.g. `user` vs `environment`) to determine whether or not to apply the `transform` styles to the `localTile`.

* https://github.com/aws/amazon-chime-sdk-js/blob/amazon-chime-sdk-js%401.4.0/src/videotile/DefaultVideoTile.ts#L26
* https://developer.mozilla.org/en-US/docs/Web/API/MediaTrackSettings/facingMode

**Screenshots**
![IMG_2844](https://user-images.githubusercontent.com/1079605/80637023-f5c46a00-8a23-11ea-82d9-831182e604bf.jpg)

**Platform**
 - OS: iOS 13.4.1
 - Browser: Mobile Safari
 - Browser Version: 13
 - Amazon Chime SDK GitHub Commit: https://github.com/aws/amazon-chime-sdk-js/releases/tag/amazon-chime-sdk-js%401.4.0

**Comment by aburnson** [comment]
Thanks for reporting this. Fixed in #313.
