### ISSUE TITLE
Confirguration issue with react native@0.62 

### ISSUE THREAD

**Issue by vishnuwebdev** [aws/amazon-chime-sdk-js#318]
I am following the steps of given documentation in this repositry. I have try to create object of AWS but it's giving me an error my Code is below :
....
const AWS = require('aws-sdk');

.... 
componentDidMount(){
	try{
		let aws = new AWS.Chime({ region: 'us-east-1' })
	}catch(e){
		console.log(e);
	}      	
}

......

![image](https://user-images.githubusercontent.com/26281991/80705403-faf8e600-8b03-11ea-900a-cee52b50feed.png)

and error response 
![image](https://user-images.githubusercontent.com/26281991/80705116-7b6b1700-8b03-11ea-9a84-96b2b0e9cddf.png)

i am using React native class component.

There is no React Native Documentation given for this repositry so i am using the given read.me Instruction.

Please help me out this issue or give the suggestion for implementing aws-chime-sdk in react native 
step by step

**Comment by vishnuwebdev** [comment]
But i am using react native so i have to implement it here. 
So how i use in React Native or give me react native guide link of aws chime sdk

**Comment by shamoons** [comment]
Still need a server to create the actual meeting it seems

**Comment by vishnuwebdev** [comment]
ok but could you suggest the react native setup link for this chime sdk for react native.
It's looks bit cunfusing

**Comment by aburnson** [comment]
To use the Amazon Chime SDK with React Native you would need to use the [Amazon Chime SDK for iOS](https://github.com/aws/amazon-chime-sdk-ios) and [Amazon Chime SDK for Android](https://github.com/aws/amazon-chime-sdk-android) libraries. Using React Native is not supported with the Amazon Chime SDK for JavaScript which requires either a real browser or Electron.

**Comment by TagMango** [comment]
@vishnuwebdev https://github.com/aws-samples/amazon-chime-react-native-demo

**Comment by vaibhav11504561** [comment]
@vishnuwebdev https://github.com/aws-samples/amazon-chime-react-native-demo
