### ISSUE TITLE
Local video playback freezes when stopping/starting video on Safari

### ISSUE THREAD

**Issue by jeffmerten** [aws/amazon-chime-sdk-js#319]
**Meeting and attendee IDs:**
N/A

**Timeline**
Outline the main actions the user performed and when:
• Open meetingV2 example.
• Go through settings and into video conference and enable the video so you see your own playback.
• Disable the video feed
• Re-enable the video feed

You'll see the video tile for your own playback, but now it's frozen.

**Describe the bug**
Our application has a video toggle button that lets our users turn off and on their video. When this is toggled off we call `stopLocalVideoTile()` and `chooseVideoInputDevice(null)`. When it is toggled on we call `chooseVideoInputDevice(deviceId)` and then `startLocalVideoTile()` after the promise has been resolved.

The latter appears to resume the video playback for us but causes the video playback to freeze. This only happens on safari and mobile safari. We also haven't seen any warn or error logs logged from inside amazon-chime-sdk-js.

It appears this can also be reproduced in the meetingV2 example.

**Screenshots**
N/A

**Platform**
 - OS: MacOS
 - Browser: Safari
 - Browser Version: 13.0.5
 - Amazon Chime SDK GitHub Commit: d658830a1f1d151c12a9fb89e371984bea3f9ebf (April 29th, 2020)

**Comment by bizready** [comment]
I have a similar issue. I can toggle on/off video and LED provides confirmation of on/off but I do not see Video display on the tile.

**Comment by dinesh-cm** [comment]
We do have the same issue for our users opening the meeting URL in iOS browser.

**Comment by ltrung** [comment]
Thank you for reporting. The issue has been fixed in this commit https://github.com/aws/amazon-chime-sdk-js/commit/d3964b8631baed7b23167a686b1063648c764995
@bizready and @dinesh-cm, I think they maybe different issues. Could you open a new issue?
