### ISSUE TITLE
Publishing data to meetingSession

### ISSUE THREAD

**Issue by eliavm** [aws/amazon-chime-sdk-js#323]
Is it possible for a participant to send data to other participants via meetingSession or any other object? I see the option to publish video/audio but no other types of data like strings/objects.

**Comment by matiboy** [comment]
@eliavm This might be similar to my feature request #257 which has been released few days back and is documented [here](https://aws.github.io/amazon-chime-sdk-js/modules/apioverview.html#9-send-and-receive-data-messages-optional)

I've yet to try it myself though

**Comment by ltrung** [comment]
We recently release data message APIs for this use case (available starting from NPM 1.6.0).
