### ISSUE TITLE
Audio not working (Quasar/VueJS)

### ISSUE THREAD

**Issue by bizready** [aws/amazon-chime-sdk-js#327]
**Meeting and attendee IDs:**
Meeting ID: 784275b5-5e0d-4b75-aabd-887cc76dc316
Attendee ID: a016e066-caa6-4a1a-97d7-6c61bec62b60

**Timeline**
US EAST May 02, 2020, at 12:19pm

**Describe the bug**
After having trouble in Chime to my Quasar/VueJS app, I am staring step by step. I am trying to prove "Use case 5" in the Readme. The goal is to hear audio so that I know it is working, but I am not hearing anything.
 
**Platform**
 - OS: Mac
 - Browser: Chrome
 - Amazon Chime SDK: npmjs version 1.4.0

Below is my setup:
App Platform: VuejS based Javascript 

I have below HTML segments in my page:
```
<audio id="meeting-audio" style="display:none"></audio>
```

```
<div id="tile-area">
          <div id="tile-0" style="display:none">
            <video id="video-0"></video>
            <div id="nameplate-0"></div>
          </div>
          <div id="tile-1" style="display:none">
            <video id="video-1"></video>
            <div id="nameplate-1"></div>
          </div>
        </div>
```

In page mount() I have following code segments:
```const logger = new ConsoleLogger('MyLogger', LogLevel.ERROR);
 const deviceController = new DefaultDeviceController(logger);
let data = //get meeting data from the server
let meetingSession = await new DefaultMeetingSession(
      new MeetingSessionConfiguration(
        data.joinMeeting.Meeting,
        data.joinMeeting.Attendee
      ),
      logger,
      deviceController
    );
```

```this.audioVideo = await meetingSession.audioVideo;
 const listAudioInputDevices = await this.audioVideo.listAudioInputDevices();//2 items in chrome, 1 item in safari??
 const listAudioOutputDevices = await this.audioVideo.listAudioOutputDevices();//3 items in chrome, 0 item in safari??
const listVideoInputDevices = await this.audioVideo.listVideoInputDevices();//1 item in chrome, 1 item in safari
```

selected 1st item for audio input and output. I also trying various permutations and nothing worked.

```await this.audioVideo.chooseAudioInputDevice(
      listAudioInputDevices[0].deviceId
    );
await this.audioVideo.chooseAudioOutputDevice(
      listAudioOutputDevices[0].deviceId
    );
const videoElement = document.getElementById('video-0');
let audioElement = document.getElementById('meeting-audio');
 this.audioVideo.bindAudioElement(audioElement);
const observer = {
      audioVideoDidStart: () => {
        console.log('Started');
      }
    };
```

```this.audioVideo.addObserver(observer);
 this.audioVideo.start();
```

I was expecting an audio working when I start the page, but NO. Should the audio be working? As I stated I tried other permutation and combinations of audio input and output as well.

Further, I have button on-page to mute/unmute audio that calls following on toggle. It is not helping in my testing or troubleshoot:

> audioMuteUnmute() {
>       if (this.isAudioMute) {
>         this.isAudioMute = false;
>         this.audioVideo.realtimeUnmuteLocalAudio();
>       } else {
>         this.isAudioMute = true;
>         this.audioVideo.realtimeMuteLocalAudio();
>       }
> }

 
Am I missing anything in terms of my expectation to hear audio as per [Use case 5](https://github.com/aws/amazon-chime-sdk-js#starting-a-session) or it is known issue in VueJS based code?

**Comment by eliavm** [comment]
`const listAudioOutputDevices = await this.audioVideo.listAudioOutputDevices();//3 items in chrome, 0 item in safari??`

Same here. Maybe there's a bug in Safari?

**Comment by eliavm** [comment]
May be related to this: https://bugs.webkit.org/show_bug.cgi?id=179415

Is there a different way to connect audio stream on Safari?

**Comment by bizready** [comment]
I think the safari issue is SDK related then. In my case, I am not able to get audio working in chrome itself. I am using Quasar/VueJS based client Javascript integration with Chime JS SDK.

**Comment by Axe129** [comment]
@bizready Are you getting any console errors? I had this problem when I ran on Angular. But, I was getting a console error - 

![image](https://user-images.githubusercontent.com/12937657/81798789-0f8aa480-952e-11ea-9774-b202ceec2aae.png)

Setting   ` var global = global || window;` fixed the issue.

**Comment by bizready** [comment]
@Axe129 - no I am not getting global not defined error

**Comment by aburnson** [comment]
Just to confirm what you are expecting, how are you testing? Are you joining two different attendees to the same meeting in the manner as described in original post and still not hearing any audio?

**Comment by bizready** [comment]
I am joining as two different attendees in my local but using 2 different browsers. It is an issue related to safari as noted by @eliavm. Once I changed my browser it works.
