### ISSUE TITLE
Safari audio stops sending after entering the background

### ISSUE THREAD

**Issue by justindarc** [aws/amazon-chime-sdk-js#33]
**Describe the bug**
After backgrounding Safari, the microphone audio stops sending to other participants on the call. To background Safari, the window either needs to be minimized to the dock or the user needs to switch to another desktop on macOS. Simply bringing another window to the foreground is not sufficient to trigger this issue.

**Platform**
 - OS: macOS Mojave 10.14.6
 - Browser: Safari
 - Browser Version: 13.0.4 (14608.4.9.1.4)
 - Amazon Chime SDK GitHub Commit: 64a5787

**Comment by justindarc** [comment]
NOTE: This issue may be related to https://github.com/socketio/socket.io/issues/2924. WebSockets are throttled when Safari is backgrounded for power savings, so there may be additional similar behavior around other APIs as well. PR #29 addresses the issue where the WebSocket is disconnected and reconnected when backgrounding Safari which causes the user to be dropped and re-added to the call. However, this issue where audio stops sending still happens even with that fix applied.

**Comment by aburnson** [comment]
Fixed by disabling WebAudio in https://github.com/aws/amazon-chime-sdk-js/pull/37
