### ISSUE TITLE
Unable to Trigger connectionDidBecomePoor Observer

### ISSUE THREAD

**Issue by efortney** [aws/amazon-chime-sdk-js#335]
**Meeting and attendee IDs:**
N/A

**Timeline**
* Opened V2 demo
* Started a conference
* Placed 2 users into the conference.
* Disabled network, waited for 2ish minutes to see `connection is poor` logged to the console. 

**Describe the bug**
After several minutes with no Network whatsoever, I was still unable to see the expected console log that is fired by the V2 Demo application. I also tried throttling and disabling my network with Chrome dev tools.

**Screenshots**
N/A

**Platform**
 - OS: Mac OS 10.14.6
 - Browser: Chrome
 - Browser Version: Version 81.0.4044.129 (Official Build) (64-bit)
 - Amazon Chime SDK GitHub Commit: f10e1375c8bb46e14d5407519e1f9265b0690707

[**Network Log**](https://github.com/aws/amazon-chime-sdk-js/files/4577352/localhost-1588616016467.log)

**Comment by XHatan** [comment]
Hey, @efortney 
Thanks for reporting this. Could you try using network limiting tools such as Network Link Conditioner and limit your uplink/downlink bandwidth instead of dropping off network  to see if it's triggered ?
could you also provide your info level SDK logs ?

**Comment by XHatan** [comment]
In addition, https://github.com/aws/amazon-chime-sdk-js/blob/5db1dbb616213a7d54a945eceb752dc90b319c43/src/task/MonitorTask.ts#L235 we fired "connectionDidSuggestStopVideo" when there are videos instead of "connectionDidBecomePoor" ? Is this callback being fired ?

**Comment by efortney** [comment]
> In addition,
> 
> https://github.com/aws/amazon-chime-sdk-js/blob/5db1dbb616213a7d54a945eceb752dc90b319c43/src/task/MonitorTask.ts#L235
> 
> we fired "connectionDidSuggestStopVideo" when there are videos instead of "connectionDidBecomePoor" ? Is this callback being fired ?

I do see this being fired in the logs. So we should only expect to see connectionDidBecomePoor fired if the user is Audio only?

**Comment by XHatan** [comment]
In the current behavior, "connectionDidBecomePoor " is only fired when the user is not using video (send or receive) in the meeting.

**Comment by XHatan** [comment]
Hi, @efortney 
Does the above answer the question ? Could I resolve this issue ?

**Comment by efortney** [comment]
@XHatan you are good to resolve this, thanks for the fast replies!
