### ISSUE TITLE
Serverless Demo Issue (Windows)

### ISSUE THREAD

**Issue by tejasb09** [aws/amazon-chime-sdk-js#340]
I am new to Chime and am am trying to setup the serverless demo .

I am seeing several exceptions in command prompt:

../../../../../../node_modules/@types/jest/index.d.ts:35:13 - error TS2403: Subsequent variable declarations must have the same type.  Variable 'beforeEach' must be of type 'HookFunction', but here has type 'Lifecycle'.

followed by:

Found 7 errors.

npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! amazon-chime-sdk-js@1.4.15 build: `npm install && node script/barrelize.js && tsc && npm run copy`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the amazon-chime-sdk-js@1.4.15 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\TejasBelhe\AppData\Roaming\npm-cache\_logs\2020-05-06T03_51_39_435Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! amazon-chime-sdk-js-demos@0.1.0 deps: `cd ../.. && npm install && npm run build`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the amazon-chime-sdk-js-demos@0.1.0 deps script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\TejasBelhe\AppData\Roaming\npm-cache\_logs\2020-05-06T03_51_39_496Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! amazon-chime-sdk-js-demos@0.1.0 start: `npm run deps && npm install && npm install aws-sdk && npm run start:fast`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the amazon-chime-sdk-js-demos@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:

Any advise would be really helpful !

Regards,

**Comment by aburnson** [comment]
It appears there may be a Windows-specific build issue here. Will need further investigation.

**Comment by eugenegodun** [comment]
Have similar issues on the Mac. Looks like `awesome-typescript-loader` is watching `node_modules`

![image](https://user-images.githubusercontent.com/26645888/83508607-c58f4180-a48f-11ea-8347-527d4368f282.png)

**Comment by nicklera1** [comment]
Hi all,

I have just tried running `serverless` deployment on Windows 10 via PowerShell after checkingout latest commit and I did't observe any issues with building, running it locally or running serverless deployment on latest commit. 
I believe, that after latest rounds for dependencies updates issues are no longer there for windows.  I will resolve this ticket but feel free to reopen if you see any issues. 
Thanks
![win example](https://user-images.githubusercontent.com/20075335/93533030-fe480f00-f8f6-11ea-9df8-38c41a0b30c0.png)
