### ISSUE TITLE
Typo MeetingNotificaionsEvent

### ISSUE THREAD

**Issue by lawrencepit** [aws/amazon-chime-sdk-js#341]
In demos/serverless/template.yaml and demos/device/serverless/template.yaml there's a typo: `MeetingNotificaionsEvent`

**Comment by cljazouli** [comment]
Good catch @lawrencepit 👍 ! 
I have a fix for it in https://github.com/aws/amazon-chime-sdk-js/pull/447

**Comment by RidipDe** [comment]
Thanks @lawrencepit and @cljazouli 
PR https://github.com/aws/amazon-chime-sdk-js/pull/452 will fix the issue
