### ISSUE TITLE
Does the MeetingsNotificationsConfiguration only support SQS queues in us-east-1 ?

### ISSUE THREAD

**Issue by lawrencepit** [aws/amazon-chime-sdk-js#342]
### What are you trying to do?

Receive SQS messages from Chime in an SQS queue defined in eu-west-1.

Note that we create meetings in region eu-west-1:

https://docs.aws.amazon.com/chime/latest/APIReference/API_CreateMeeting.html#chime-CreateMeeting-request-MediaRegion

We would prefer to receive notifications in eu-west-1 as all our workers run in that region, nothing in us-east-1.

### How can the documentation be improved to help your use case?

There only documentation I found was:

https://docs.aws.amazon.com/chime/latest/APIReference/API_CreateMeeting.html#chime-CreateMeeting-request-NotificationsConfiguration

### What documentation have you looked at so far?

README.md, Amazon Chime SDK Developer Guide, all source code of amazon-chime-sdk-js

**Comment by asnyatkov** [comment]
This is correct, we currently support SNS topics or SQS queues located in us-east-1 region only.  We will update our documentation to make that limitation clear.

**Comment by rubenfonseca** [comment]
Just lost 2 days pulling our hair trying to understand why we were not receiving events either via SQS, SNS, or EventBridge... It's not documented anywhere that it doesn't work outside us-east-1... Thanks for this comment though!

**Comment by lawrencepit** [comment]
@rubenfonseca: fwiw, we decided to use SNS instead of SQS, as that allows to have the workers in different regions. So the SNS topic is defined in us-east-1, and our workers in different regions are subscribed to that topic.

**Comment by aburnson** [comment]
From: https://docs.aws.amazon.com/chime/latest/APIReference/API_MeetingNotificationConfiguration.html

> The Amazon Chime SDK supports resource targets located in the US East (N. Virginia) AWS Region (us-east-1).

**Comment by asnyatkov** [comment]
@lawrencepit @rubenfonseca We updated documentation about notifications, please take a look: https://docs.aws.amazon.com/chime/latest/dg/mtgs-sdk-notifications.html

**Comment by lawrencepit** [comment]
The note about supporting only the us-east-1 region for SNS and SQS also applies to EventBridge.

> We recommend sending Amazon Chime SDK event notifications to EventBridge
> ...
> You can use the CreateMeeting API in the Amazon Chime API Reference to send Amazon Chime SDK meeting event notifications to one Amazon SQS queue and one Amazon SNS topic per meeting. This can help reduce notification latency.

Is this implying that when EventBridge is used, that that has notification latency? Why is EventBridge recommended?

**Comment by asnyatkov** [comment]
We recommend EventBridge because it's easy to setup, and it also gives you routing flexibility. However, the data has to travel through more hops and the delivery latency is slightly higher than direct post to SQS queue or SNS topic.

**Comment by mcxemic** [comment]
Is it related only for topics/queues in us-east-1 or also for meetings **not** in us-east-1 region?

**Comment by ltrung** [comment]
Updated our FAQs to mention that event bridge is only supported in us-east-1 right now (even for meeting not in us-east-1).

**Comment by dimabory** [comment]
> Updated our FAQs to mention that event bridge is only supported in us-east-1 right now (even for meeting not in us-east-1).

Hi @ltrung. I don't see any mentions in [FAQs](https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html) that event bridge is only supported in us-east-1. Did you miss adding this explanation?
