### ISSUE TITLE
Clipping noise on iOS Safari

### ISSUE THREAD

**Issue by gsig123** [aws/amazon-chime-sdk-js#344]
**Meeting and attendee IDs:**
I've tried a bunch of meetings with different meeting IDs and attendee IDs 🤷‍♂️ 

**Timeline**
Outline the main actions the user performed and when:

* Attendee A joins a meeting in a browser on a Mac
* Attendee B joins a meeting in a browser on a iPhone (iOS 13)
* Both attendees hear clipping noises on a regular interval.

**Describe the bug**
Clipping noise on a regular interval when one of the attendees is on iOS 13 Safari. Does not happen if all attendees are connecting from Macs. 

**Screenshots**
NA

**Platform**
 - OS: iOS 13
 - Browser: Safari
 - Browser Version: 
 - Amazon Chime SDK GitHub Commit: Package version 1.4

**Comment by stopdropandrew** [comment]
I experienced something similar, turned out I was calling `audioVideo.bindAudioElement` more than once, and I experienced clipping on each subsequent call.

**Comment by stopdropandrew** [comment]
Just ran into this as well. It's easy to reproduce just using the audio output "Test" button in the serverless demo.

**Comment by simmkyu** [comment]
@gsig123 Which iPhone device have you experienced this clipping noise issue?

**Comment by jpr-c8** [comment]
We are experiencing the same issue on our application using Chime JS SDK 1.11.0. Running mobile browser tests, the sound is good/normal with users on a Pixel 2 (Chrome), Pixel 4 (Chrome), iPhone 11 Pro Max with iOS 14.0 Beta (Safari), and iPhone 7 Plus
with iOS 13.1.3 (Safari).

As soon as a colleague using an iPhone XR iOS 13.6 (Safari) joins the meeting, the popping noises start.

**Comment by simmkyu** [comment]
In iPhone X devices, using AudioContext-based API causes the clicking noise. Specifically, the noise occurs when creating an instance of AudioContext and continues even after closing or not using any APIs.

The workaround is not to use AudioContext-based APIs in iPhone X devices.

* Creating an analyzer node for the current audio input
    * [createAnalyserNodeForAudioInput](https://aws.github.io/amazon-chime-sdk-js/classes/defaultdevicecontroller.html#createanalysernodeforaudioinput)
* Creating an empty audio device for joining without audio and generating a constant tone
    * [createEmptyAudioDevice](https://aws.github.io/amazon-chime-sdk-js/classes/defaultdevicecontroller.html#createemptyaudiodevice)
    * [chooseAudioInputDevice with the "null" device](https://aws.github.io/amazon-chime-sdk-js/classes/defaultdevicecontroller.html#chooseaudioinputdevice) (SDK internally chooses the `null` device when a device is disconnected. In this case, the clicking noise will occur even if you don't call this API. We'll look into if we can avoid this call.)
* Mixing an audio stream into the primary audio stream
    * [mixIntoAudioInput](https://aws.github.io/amazon-chime-sdk-js/classes/defaultdevicecontroller.html#mixintoaudioinput)
* Enabling web audio
    * [enableWebAudio](https://aws.github.io/amazon-chime-sdk-js/classes/defaultdevicecontroller.html#enablewebaudio)


The clicking noise also occurs in other WebRTC and AudioContext-based applications but with different repro steps. 

We added our findings in this related WebKit bug: https://bugs.webkit.org/show_bug.cgi?id=204625#c6
We’ll keep watching this bug report and investigating if any specific SDK setup collides with AudioContext.
