### ISSUE TITLE
Screen sharing audio

### ISSUE THREAD

**Issue by andyh6969** [aws/amazon-chime-sdk-js#350]
Why can't audio below be set to **true** in screen sharing. This causes a 'share audio' box to be displayed in Chrome so you can share your computer audio along with video?

Or make it optional so it can be enabled on demand.

_private screenCaptureDisplayMediaConstraints(
    sourceId?: string,
    frameRate?: number
  ): MediaStreamConstraints {
    return {
      **audio: false,**
      video: {
        ...(!sourceId && {
          frameRate: {
            max: frameRate ? frameRate : ContentShareMediaStreamBroker.defaultFrameRate,
          },
        }),
        
Checkbox to which I refer shown in image. Not present otherwise.

![8f6adb47-e60b-44db-86b6-af796fcef3b2](https://user-images.githubusercontent.com/26925702/81350885-e2b43880-90ba-11ea-8df6-0fe6e09c79de.jpg)

**Comment by aburnson** [comment]
Recent versions of Chrome now support sharing audio as part of the screen share. Other browsers may reject the getDisplayMedia promise if you ask for audio but the browser doesn't support it. We will need to add a [browser behavior](https://github.com/aws/amazon-chime-sdk-js/blob/master/src/browserbehavior/BrowserBehavior.ts) flag to control whether the audio option is set or not.

**Comment by aburnson** [comment]
Fixed by #352
