### ISSUE TITLE
Documentation: explain how to efficiently ignore realtime volume properties that are not needed

### ISSUE THREAD

**Issue by mfharding** [aws/amazon-chime-sdk-js#351]
Hi, 

I am a big fan of chime and the SDK. I have been trying to implement a signal strength indicator, however it is currently part of the volume indicator. This updates a little to fast for my needs.

It would be awesome if the there was a slower updating observer only for signal strength. This would inherently make sense since signal strength is independent of volume. This could be used to trigger UI changes in my app.

**Comment by edwardbc** [comment]
+1, I was just looking the docs on how to throttle this call, as I'm only interested in checking `muted` changes.

**Comment by aburnson** [comment]
The realtime volume and signal strength updates are only called when there is a change in value. To clarify are you seeing duplicate updates with the same attendee and value? Or is the rate too high even with it calling the callback for changes only.

**Comment by aburnson** [comment]
> +1, I was just looking the docs on how to throttle this call, as I'm only interested in checking `muted` changes.

Each of the values in the callback will be set to null unless they have changed. To track just mute, you could do something like:

```typescript
meetingSession.audioVideo.realtimeSubscribeToVolumeIndicator(
  attendeeIdToSubscribeTo,
  (attendeeId, volume, muted, signalStrength) => {
    if (muted === null) {
      // no mute update - return
      return;
    }

    // mute has changed, update UI
  }
);
```

Likewise to update only on signal strength changes:

```typescript
meetingSession.audioVideo.realtimeSubscribeToVolumeIndicator(
  attendeeIdToSubscribeTo,
  (attendeeId, volume, muted, signalStrength) => {
    if (signalStrength === null) {
      // no signalStrength update - return
      return;
    }

    // signalStrength has changed, update UI
  }
);
```

**Comment by mfharding** [comment]
Can this please be added to the documentation. Additionally is it possible to decrease the rate that this function fires if we only observe one item. For 50 person meetings, this JS calculation is causing issues, since volume is so quickly changing.

**Comment by aburnson** [comment]
> Can this please be added to the documentation.

Yes, tracking this issue against the documentation label now.

> Additionally is it possible to decrease the rate that this function fires if we only observe one item. For 50 person meetings, this JS calculation is causing issues, since volume is so quickly changing.

Even in a meeting with many attendees, the handler should still only be getting volume events for the volumes that are changing. As long as most of those attendees are on mute, the overall number of volume events should average the same regardless of meeting size. Is the handler receiving volume events for attendees that have unchanging volume? What is the approximate total number of volume callbacks it is receiving per second?

If the handler returns early as in the above code, there should be negligible overhead from the callback.

If the application is built with Angular, then there is a [known issue/workaround](https://aws.github.io/amazon-chime-sdk-js/modules/apioverview.html#5-build-a-roster-of-participants-using-the-real-time-api) with respect to the real-time volume callbacks:

> If you are using Angular, ensure that all calls to the SDK are run outside of the Angular zone. Otherwise, the real-time messages received via the signaling channel and their real-time callbacks may cause the DOM to thrash with updates and degrade performance.

**Comment by davidlygagnon** [comment]
Thanks - I was wondering the same while looking at `realtimeVolumeIndicatorCallback`.

**Comment by devalevenkatesh** [comment]
Updated the README with Use case 11. Subscribe to mute or signal strength changes of a specific attendee. You can use this to build UI for only mute or only signal strength changes.

**Comment by SSTPIERRE2** [comment]
Hello, it appears our volume indicator callback is running twice per event, or we are getting a duplicate event each time.
![image](https://user-images.githubusercontent.com/19779234/133829845-78c8e22a-4546-42de-ae7a-6cbafed8502c.png)

1. In the screenshot notice the callback runs with the same exact args twice each time, is there anything we can do about this in our React application? 
2. The callback is called faster than state updates can occur - might anyone know how folks generally handle that in their React-based chime applications?

We are on version "amazon-chime-sdk-js": "2.15.0" -- thanks for any tips
