### ISSUE TITLE
TypeError: undefined is not an object (evaluating 'navigator.mediaDevices.addEventListener')

### ISSUE THREAD

**Issue by bizready** [aws/amazon-chime-sdk-js#353]
When loading meeting page on iOS webview, I get following error

<img width="1019" alt="Screen Shot 2020-05-08 at 11 10 50 PM" src="https://user-images.githubusercontent.com/63766875/81462565-810ad180-9181-11ea-9d50-6fc4da193250.png">

**Platform**
 - OS: iOS Webview
 - Browser: Safari

**Comment by vidya-mohan** [comment]
@bizready - thanks for reporting:
Safari embedded web view does not support WebRTC https://forums.developer.apple.com/thread/88052

In the interim you can use the Amazon Chime SDK for iOS to build a native application
https://github.com/aws/amazon-chime-sdk-ios

**Comment by bizready** [comment]
Thanks and I hope Apple will take action on webRTC on the embedded web view. It is unfortunate to see that the requested feature exists in their pending list for a while.
