### ISSUE TITLE
VideoTileDidUpdate and VideoTileState change for local tile vs remote tile

### ISSUE THREAD

**Issue by bizready** [aws/amazon-chime-sdk-js#354]
I am trying on to see my local as well as remove video tiles. I am testing the scenario using two users on different browsers. I can only see users' local video tile on both browsers and not remote user video tile. I have a similar code setup like the demo but not exact.  With my debug effort, I always get [tileState.localTile](https://github.com/aws/amazon-chime-sdk-js/blob/6485f0009a2596a19b3a5f770143fa8f802157cd/demos/browser/app/meetingV2/meetingV2.ts#L1190) as TRUE. hence, remote tile never gets added to the list.

So, I am trying to understand `VideoTileState` in terms of when does `VideoTileState.localTile` the value set to either TRUE or FALSE?. What makes `VideoTileState.localTile` FALSE to that tile is added to the list.

I read and experimented about `VideoTileDidUpdate` but could not find much information regarding the VideoTileState changes in terms of local and remote. Any help or pointer would be great.

**Comment by XHatan** [comment]
Hi @bizready 

I could explain with words, but I think pointing you to the code might be clearer. 
As you noticed, `videoTileDidUpdate` comes from two places, local video (camera driven), remote video (WebRTC driven).
When https://github.com/aws/amazon-chime-sdk-js/blob/master/src/audiovideofacade/DefaultAudioVideoFacade.ts#L76 is called, camera is turned on and JS SDK initiated WebRTC negotiation with server. videoTileDidUpdate will be fired for local tile.

Other attendees in the meeting will be notified by server and they will negotiate with server to subscribe to new video streams. When negotiation is finished, Browser WebRTC who is listening to "track event" might be notified here https://github.com/aws/amazon-chime-sdk-js/blob/master/src/task/CreatePeerConnectionTask.ts#L120
new remote track will be bound with an tile and videoTileDidUpdate will be fired.

Does that clarify the usage ?

**Comment by aburnson** [comment]
We should add some information in the [video use case](https://github.com/aws/amazon-chime-sdk-js#video) on how to differentiate between local tiles. It's sort of implied in that code sample, but the local video tile also needs to be bound in order to see it.

**Comment by bizready** [comment]
Thanks @XHatan and @aburnson. Adding info regarding tile based on local and remote would help.

**Comment by ltrung** [comment]
Updated local tile in README.
