### ISSUE TITLE
Firefox: Not Loading Speakers List

### ISSUE THREAD

**Issue by koni-a** [aws/amazon-chime-sdk-js#358]
Hi Team,

In Firefox Browser Speakers are Not Loading.

![image](https://user-images.githubusercontent.com/56219917/81554555-a4619680-93a4-11ea-8907-06155ac9028f.png)

Can you please help to resolve.

**Comment by edwardbc** [comment]
This is a Firefox browser limitation. See here
https://github.com/aws/amazon-chime-sdk-js/issues/238#issuecomment-608694946
