### ISSUE TITLE
An accessor cannot be declared in an ambient context.

### ISSUE THREAD

**Issue by SuhailBt** [aws/amazon-chime-sdk-js#359]
Below is the list of errors in am getting on compilation of my angular project after import (
import {
    ConsoleLogger,
    DefaultDeviceController,
    DefaultMeetingSession,
    LogLevel,
    MeetingSessionConfiguration
  } from 'amazon-chime-sdk-js';)

ERROR in node_modules/amazon-chime-sdk-js/build/audiovideocontroller/DefaultAudioVideoController.d.ts(31,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/amazon-chime-sdk-js/build/audiovideocontroller/DefaultAudioVideoController.d.ts(32,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/amazon-chime-sdk-js/build/audiovideocontroller/DefaultAudioVideoController.d.ts(33,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/amazon-chime-sdk-js/build/audiovideocontroller/DefaultAudioVideoController.d.ts(34,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/amazon-chime-sdk-js/build/audiovideocontroller/DefaultAudioVideoController.d.ts(35,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/amazon-chime-sdk-js/build/audiovideocontroller/DefaultAudioVideoController.d.ts(36,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/amazon-chime-sdk-js/build/audiovideocontroller/DefaultAudioVideoController.d.ts(37,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/amazon-chime-sdk-js/build/audiovideocontroller/DefaultAudioVideoController.d.ts(38,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/amazon-chime-sdk-js/build/contentsharecontroller/ContentShareMediaStreamBroker.d.ts(9,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/amazon-chime-sdk-js/build/contentsharecontroller/ContentShareMediaStreamBroker.d.ts(10,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/amazon-chime-sdk-js/build/domwebsocket/DefaultDOMWebSocket.d.ts(5,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/amazon-chime-sdk-js/build/domwebsocket/DefaultDOMWebSocket.d.ts(6,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/amazon-chime-sdk-js/build/domwebsocket/DefaultDOMWebSocket.d.ts(7,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/amazon-chime-sdk-js/build/domwebsocket/DefaultDOMWebSocket.d.ts(8,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/amazon-chime-sdk-js/build/domwebsocket/DefaultDOMWebSocket.d.ts(9,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/amazon-chime-sdk-js/build/domwebsocket/DefaultDOMWebSocket.d.ts(10,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/amazon-chime-sdk-js/build/domwebsocket/DefaultDOMWebSocket.d.ts(11,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/amazon-chime-sdk-js/build/domwebsocket/DefaultDOMWebSocket.d.ts(12,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/amazon-chime-sdk-js/build/domwebsocket/DefaultDOMWebSocket.d.ts(13,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/amazon-chime-sdk-js/build/mediarecording/WebMMediaRecording.d.ts(20,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/amazon-chime-sdk-js/build/meetingsession/DefaultMeetingSession.d.ts(24,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/amazon-chime-sdk-js/build/meetingsession/DefaultMeetingSession.d.ts(25,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/amazon-chime-sdk-js/build/meetingsession/DefaultMeetingSession.d.ts(26,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/amazon-chime-sdk-js/build/meetingsession/DefaultMeetingSession.d.ts(27,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/amazon-chime-sdk-js/build/meetingsession/DefaultMeetingSession.d.ts(28,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/amazon-chime-sdk-js/build/meetingsession/DefaultMeetingSession.d.ts(29,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/amazon-chime-sdk-js/build/meetingsession/DefaultMeetingSession.d.ts(30,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/amazon-chime-sdk-js/build/meetingsession/MeetingSessionURLs.d.ts(33,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/amazon-chime-sdk-js/build/meetingsession/MeetingSessionURLs.d.ts(37,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/amazon-chime-sdk-js/build/meetingsession/MeetingSessionURLs.d.ts(41,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/amazon-chime-sdk-js/build/meetingsession/MeetingSessionURLs.d.ts(45,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/amazon-chime-sdk-js/build/meetingsession/MeetingSessionURLs.d.ts(49,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/amazon-chime-sdk-js/build/meetingsession/MeetingSessionURLs.d.ts(53,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/amazon-chime-sdk-js/build/meetingsession/MeetingSessionURLs.d.ts(57,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/amazon-chime-sdk-js/build/meetingsession/MeetingSessionURLs.d.ts(61,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/amazon-chime-sdk-js/build/meetingsession/MeetingSessionURLs.d.ts(65,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/amazon-chime-sdk-js/build/meetingsession/MeetingSessionURLs.d.ts(69,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/amazon-chime-sdk-js/build/meetingsession/MeetingSessionURLs.d.ts(73,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/amazon-chime-sdk-js/build/meetingsession/MeetingSessionURLs.d.ts(77,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/amazon-chime-sdk-js/build/promisedwebsocket/DefaultPromisedWebSocket.d.ts(7,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/amazon-chime-sdk-js/build/screenmessagedetail/ProtocolScreenMessageDetail.d.ts(6,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/amazon-chime-sdk-js/build/screenviewing/session/ScreenViewingSessionConnectionRequest.d.ts(10,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/amazon-chime-sdk-js/build/transceivercontroller/DefaultTransceiverController.d.ts(17,30): error TS2304: Cannot find name 'RTCRtpTransceiver'.
node_modules/amazon-chime-sdk-js/build/transceivercontroller/DefaultTransceiverController.d.ts(18,30): error TS2304: Cannot find name 'RTCRtpTransceiver'.
node_modules/amazon-chime-sdk-js/build/transceivercontroller/TransceiverController.d.ts(51,30): error TS2304: Cannot find name 'RTCRtpTransceiver'.
node_modules/amazon-chime-sdk-js/build/transceivercontroller/TransceiverController.d.ts(55,30): error TS2304: Cannot find name 'RTCRtpTransceiver'.
node_modules/amazon-chime-sdk-js/build/versioning/Versioning.d.ts(7,16): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/amazon-chime-sdk-js/build/versioning/Versioning.d.ts(11,16): error TS1086: An accessor cannot be declared in an ambient context.

The verions that I am using for my project
		"@angular/animations": "^6.1.0",
		"@angular/cdk": "^6.4.0",
		"@angular/common": "^6.1.0",
		"@angular/compiler": "^6.1.0",
		"@angular/fire": "^5.1.3",
		"@angular/forms": "^6.1.0",
		"@angular/http": "^6.1.0",
		"@angular/platform-browser": "^6.1.0",
		"@angular/platform-browser-dynamic": "^6.1.0",
		"@angular/platform-server": "^6.1.0",
		"@angular/pwa": "^0.10.4",
		"@angular/router": "^6.1.0",
		"@kolkov/angular-editor": "^0.13.1",
		"@ng-bootstrap/ng-bootstrap": "^2.2.0",
		"amazon-chime-sdk-js": "^1.5.0",

	"@angular-devkit/build-angular": "^0.7.0",
		"@angular/cli": "^6.0.8",
		"@angular/compiler-cli": "^6.1.0",

**Comment by ltrung** [comment]
These seem like a typescript error. Could you let us know what typescript version are you using as well as your ts config?

**Comment by shumuid** [comment]
I'm having the exact same issue.

**Comment by SuhailBt** [comment]
Resolved it by upgrading typescript version (3.8). Thanks anyways.

> These seem like a typescript error. Could you let us know what typescript version are you using as well as your ts config?

**Comment by SuhailBt** [comment]
> I'm having the exact same issue.

Try upgrading yhe typescript version
