### ISSUE TITLE
Demo Browser/MeetingV2 or Meeting

### ISSUE THREAD

**Issue by ssarath** [aws/amazon-chime-sdk-js#364]
**Meeting and attendee IDs:**
List the meeting and attendee IDs that the attached logs apply to.
 "MeetingId": "c363d36f-d6a6-40ef-88f9-83257f393dea",
 "AttendeeId": "afa0a534-2a6c-4ab4-b3bb-1fbcfb7d94a4",

**Timeline**
After running npm start:fast ,
able to acess the meeting page from firefox webbowser
After entering the meeting id , name and selecting the region as singapore, then  continue/join button  getting an error navigator.mediaDevices is undefined .

**Describe the bug**
When Join meeting getting the following error.
Unable to find meeting

There was an issue finding that meeting. The meeting may have already ended, or your authorization may have expired.
navigator.mediaDevices is undefined .

**Platform**
 - OS: Ubuntu 18.04 LTE 
 - Browser:  Firefox 
 - Browser Version: 76.0.1
 - Amazon Chime SDK GitHub Commit: 1.5.1

**Comment by ltrung** [comment]
Thanks for reporting @ssarath, could you upload the console log for us to debug?

**Comment by ssarath** [comment]
This works after changing the connection type from http to https and after including key and certificate files  in the browser/server.js .

**Comment by BitCanny** [comment]
Can you elaborate what is this key and certificate files and where to find them? I am trying the broadcast feature and get the following
Unable to find meeting
There was an issue finding that meeting. The meeting may have already ended, or your authorization may have expired.

Cannot read properties of undefined (reading 'Meeting')

**Comment by ltrung** [comment]
@BitCanny Can you open a separate issue? Could you also clarify what broadcast feature you are trying.

**Comment by misterharshil** [comment]
@BitCanny @ltrung @ssarath  Kinda having the same issue - Can u guys help please?

**Comment by ltrung** [comment]
@misterharshil Can you open a new issue with detailed description of what the issue you encountered is? This issue is closed.

**Comment by SharjeelAhmad84** [comment]
facing same issue. no resolution yet. Need to extend 5 minutes expiration window. Is there any solution for that?
