### ISSUE TITLE
Firefox: Not Updating Video when video share

### ISSUE THREAD

**Issue by koni-a** [aws/amazon-chime-sdk-js#365]
Hi,

Firefox video tile is not updating when other users sharing the video.

can you please help to resolve this issue.

Thanks in Advance

**Comment by vidya-mohan** [comment]
@koni-a there is an ongoing issue on Firefox 76: https://github.com/aws/amazon-chime-sdk-js/issues/347 . 

What version are you using? Please add details such as logs + browser information much like the template

**Comment by vidya-mohan** [comment]
This is the bug template that would help in investigation: https://github.com/aws/amazon-chime-sdk-js/blob/master/.github/ISSUE_TEMPLATE/bug-report.md

**Comment by vidya-mohan** [comment]
Please reactivate with a bug template and details if https://github.com/aws/amazon-chime-sdk-js/issues/347 is not your issue
