### ISSUE TITLE
Mobile Safari Backgrounding With Active Camera

### ISSUE THREAD

**Issue by mikeantonelli** [aws/amazon-chime-sdk-js#372]
**Meeting and attendee IDs:**
n/a

**Timeline**

* Join a meeting as an attendee on any browser - attendee-1
* Join the same meeting as an attendee on Mobile Safari - attendee-2
* As attendee-1, observe live video tile of attendee-2 
* Background Mobile Safari, ensure audio communication is still active
* As attendee-1, observe black video tile of attendee-2 

**Describe the bug**
Expected behavior during backgrounding is identical to a user disabling their own camera. Doing so would cause all life cycle events to fire such that other attendees could display placeholder views, or take other actions.

I believe that you can use Page Visibility APIs to:

* If camera is active when hidden, disable it
* If camera was previously active prior to being hidden, and it becomes visible, enable it

https://developer.mozilla.org/en-US/docs/Web/API/Document/onvisibilitychange
```
function handleVisibilityChange() {
  if (document.hidden) {
    pauseSimulation();
  } else  {
    startSimulation();
  }
}

document.addEventListener("visibilitychange", handleVisibilityChange, false);
```

**Screenshots**
n/a

**Platform**
 - OS: iOS 13.3
 - Browser: Mobile Safari 
 - Browser Version: 13
 - Amazon Chime SDK GitHub Commit: 1.5.0

**Comment by ltrung** [comment]
@mikeantonelli I tried to follow the steps you listed with the meetingV2 demo using my Ipad for attendee-2. For me both attendee-1 and 3 see a black video tile of attendee-2's video when mobile safari is in background and see video again once safari comes back to foreground. But you mention that attendee-3 does not see any (black) video tile from attendee-2. Is that correct?

Black video tile when the mobile browser is in the background is an expected behavior.

**Comment by mikeantonelli** [comment]
Thanks @ltrung - I misunderstood an internal issue report. The missing tile for attendee-3 is observed on Android. The behavior you have described is what we are seeing on iOS. I will update the workflow above, and log a different issue for Android. 

> Black video tile when the mobile browser is in the background is an expected behavior.

Does this mean you are classifying this as a feature request as opposed to a bug? Automatically starting/stopping video based on visibility would be great for the sdk to handle, but I can't quite tell if you're saying it's out-of-scope or not intended behavior.

**Comment by ltrung** [comment]
Yes, black video tile indicates the video stream is pause (which makes sense when mobile browsers are in background) so this is not a bug. I will update the label to enhancement instead.
