### ISSUE TITLE
Blank Video Tile for Backgrounded Android User

### ISSUE THREAD

**Issue by mikeantonelli** [aws/amazon-chime-sdk-js#377]
**Meeting and attendee IDs:**
n/a

**Timeline**
* Join a meeting as an attendee on any browser - attendee-1
* Join the same meeting as an attendee on Mobile Safari - attendee-2
* Join the same meeting as an attendee on Android (Chrome) - attendee-3
* As attendee-1, observe live video tile of both attendee-2 and attendee-3
* Background attendee-2 Mobile Safari, ensure audio communication is still active
* As attendee-1, observe black video tile of attendee-2
* Background attendee-3 Android, ensure audio communication is still active
* As attendee-1, observe frozen video tile of attendee-3
* Join the same meeting as an attendee on any browser - attendee-4
* As attendee-4, observe black video tile of attendee-2, and blank video tile of attendee-3

**Describe the bug**
There seems to be different behavior between mobile platforms. One displays a black tile, the other displays a frozen tile with the last transmitted frame. Also, when attendee-4 joins the meeting, backgrounded users display differently.  

Note, attendee-4 can hear attendee-3, but there is no tile visible. Attendee-1 can also hear attendee-3, but there is a placeholder frozen tile. When attendee-3 foregrounds, the video tile becomes active for all attendees. 

I mentioned in #372 that I think stopVideo could be called on backgrounding, and startVideo could be called on foregrounding, to ensure that state for all attendees is properly reflected regardless of whether they were in the meeting when backgrounding occurred (attendee-1), or they joined after backgrounding occurred (attendee-4). 

**Screenshots**
n/a

**Platform**
 - OS: Android 10 (Pixel 2)
 - Browser: Chrome
 - Browser Version: --
 - Amazon Chime SDK GitHub Commit: 1.5.0

**Comment by ltrung** [comment]
@mikeantonelli So I think the reason attendee-4 observers blank video tile of attendee-3 is because in Android, the video track is muted and only shows the last frame, which is blank as no previous frame is played for attendee-4.
Could you add an event handler for mute and unmute events of the video stream track to show a black screen or placeholder in this case?

**Comment by devalevenkatesh** [comment]
Closing this issue as it documented now in our FAQ as a default browser behavior.

https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html#i-notice-that-if-i-turn-on-camera-and-put-the-browsers-in-background-others-in-the-meeting-will-see-black-tile-in-safarichromefirefox-in-ios-and-frozen-tile-in-chrome-in-android-is-this-a-known-issue

Please feel free to re-open if you have more questions.
