### ISSUE TITLE
How to get the current video input quality ?

### ISSUE THREAD

**Issue by rlebosse** [aws/amazon-chime-sdk-js#380]
I saw in the `browser` demo that we could change the video input quality via the `AudioVideoFacade` method :

```js
audioVideo.chooseVideoInputQuality(width, height, frameRate, maxBandwidthKbps)
```

Is there a way to get the current video input quality (current width, height, frameRate, maxBandwidthKbps) ?

**Comment by XHatan** [comment]
Hi, @rlebosse 
are you interested in the resolution, frame rate of the video being sent ?

**Comment by aburnson** [comment]
We can add a method to the `AudioVideoFacade` to return the current settings.

**Comment by rlebosse** [comment]
That would be great, thanks !
