### ISSUE TITLE
Video shown in the Video tag tile is in vertical position

### ISSUE THREAD

**Issue by tutysathish** [aws/amazon-chime-sdk-js#382]
While testing chime SDK in web and mobile platform, the video shared by the mobile user is shown in vertical with a small width view even though the tile width of the video tag is large.

Please refer the screenshot, 

Help us to resolve this issue.
![github](https://user-images.githubusercontent.com/8270840/82094332-779dde00-971a-11ea-92bf-3d2551cbe1ec.png)

**Comment by aburnson** [comment]
By default the browser demo seeks to maximize the amount of content surface area shown without cropping the video and throwing away content. However, if this is not the layout you want and you want tiles to always be filled to a certain aspect ratio, then you can set the [object-fit](https://developer.mozilla.org/en-US/docs/Web/CSS/object-fit) property of the video element to `cover` to ensure that the maximum amount of element area contains content.
