### ISSUE TITLE
realtimeSendDataMessage is not a function

### ISSUE THREAD

**Issue by barrazastark** [aws/amazon-chime-sdk-js#386]
Hi people im trying to share messages between the session by calling
`meetingSession.audioVideo.realtimeSendDataMessage('topic', dat)` but im getting that is not a function, any idea ? same happens with `realtimeSubscribeToReceiveDataMessage` doc in
https://aws.github.io/amazon-chime-sdk-js/interfaces/audiovideofacade.html#realtimesubscribetoreceivedatamessage

**Comment by ltrung** [comment]
Hi @barrazastark, this is a new feature that we just pushed out last week. Do you have the latest code? Please update to NPM 1.6.2 to access this feature.

**Comment by barrazastark** [comment]
Hi @ltrung thanks that helped me a lot, anyways it would be good if you guys include documentation of how to use `realtimeSubscribeToReceiveDataMessage` better, or be more obvios how to parse the data sended, good job.

**Comment by russliu270** [comment]
Hi @ltrung , any updated documentation on how to implement realtimeSubscribeToReceiveDataMessage()? any sample code you can point me to? 
thanks!

**Comment by abhimanusharma** [comment]
@ltrung I am getting message only on my local system and not on system of other user. I implemented it as it is given in 
https://github.com/aws/amazon-chime-sdk-js/blob/master/demos/browser/app/meetingV2/meetingV2.ts

@barrazastark Can you help me out with this?

**Comment by ltrung** [comment]
@abhimanusharma @russliu270 Can you guys open a new issue? This has been closed so we may miss your questions here.
