### ISSUE TITLE
Clearer Changelog

### ISSUE THREAD

**Issue by peternijssen** [aws/amazon-chime-sdk-js#394]
### What are you trying to do?
I am trying to understand bugfixes and features released within the SDK. However, changes to the demo applications, dependency updates etc are all in the same changelog which I am not interested in.

### How can the documentation be improved to help your use case?
Making a distinction between new options and fixes for people who already built something based on the SDK and your own internal changes.

### What documentation have you looked at so far?
Changelog, developer guide, etc.

**Comment by ltrung** [comment]
#894 has removed the requirements to have CHANGELOG update for internal changes to demo and tests.
