### ISSUE TITLE
node_modules folder is missing in project

### ISSUE THREAD

**Issue by terramagix** [aws/amazon-chime-sdk-js#397]
**Important:** Please attach INFO-level logs with timestamps to the report from *before* the session started up until the point at which the unexpected behavior occured. For multi-participant calls, attach a log file for each participant if possible.

**Meeting and attendee IDs:**
List the meeting and attendee IDs that the attached logs apply to.

**Timeline**
Outline the main actions the user performed and when:

* <timestamp> <action>
* <timestamp> <action>

**Describe the bug**
Describe the bug and the timestamp at which it happened relative to the timestamp in the log file.

**Screenshots**
If applicable, add screenshots to help explain the problem.

**Platform**
 - OS: 
 - Browser: 
 - Browser Version: 
 - Amazon Chime SDK GitHub Commit:

**Comment by ltrung** [comment]
@terramagix Can you clarify what issue are you having and fill in the details?

**Comment by terramagix** [comment]
As node_modules folder is missing in project, we cant run the project locally. Earlier, there used to be node_modules folder in SDK project. Is it removed for any purpose?

**Comment by terramagix** [comment]
sorry, I missed it. got the modules after running the code. Closing the issue. Thanks for your quick response.
