### ISSUE TITLE
Attendee joining late receiving DataMessages

### ISSUE THREAD

**Issue by barrazastark** [aws/amazon-chime-sdk-js#399]
### What are you trying to do?

im trying to receive messages on a topic when a attendee joins later

### How can the documentation be improved to help your use case?

i need to know if there is something that im missing for that, this is my code example:
meetingSession.audioVideo.realtimeSubscribeToReceiveDataMessage("SET_HOST", data => {
  const { id } = data.json();
  // doSomething
});

### What documentation have you looked at so far?

https://aws.github.io/amazon-chime-sdk-js/interfaces/audiovideofacade.html#realtimeunsubscribefromreceivedatamessage

**Comment by aburnson** [comment]
@barrazastark as described in the [API Overview](https://aws.github.io/amazon-chime-sdk-js/modules/apioverview.html#9-send-and-receive-data-messages-optional) guide, when sending a message with [realtimeSendDataMessage](https://aws.github.io/amazon-chime-sdk-js/interfaces/audiovideofacade.html#realtimesenddatamessage) there is an optional third parameter that allows you to specify the lifetime of the message in milliseconds. Messages with the lifetime parameter set are buffered on the server and will be sent to attendees upon join. Up to 1024 messages can be buffered with a maximum lifetime of 5 minutes (300000 ms).
