### ISSUE TITLE
Does Chime SDK supports PSTN Calls?

### ISSUE THREAD

**Issue by sowjanyanarra** [aws/amazon-chime-sdk-js#404]
We are integrating Chime communications with our Web application, and able to make  video calls using the Amazon chime SDK.

In the same way, we would like to integrate chime PSTN calling in web application. Our requirement is to call the user phone numbers directly from chime.
We have created a voice connector in AWS chime account and provisioned phone numbers for our Amazon Chime Voice Connector.

In chime SDK Demo application, I did not find any method that supports PSTN calls. Could you please point us to any documents that explain the process of integration?

Also we are able to get SIP URI by entering meeting ID and Voice connector ID in demo application. Could you explain how we can use that SIP URI to make calls.

**Comment by vidya-mohan** [comment]
@sowjanyanarra , you can use the guidance in https://docs.aws.amazon.com/chime/latest/dg/mtgs-sdk-cvc.html and join Chime SDk meetings via Sip Invites. There is no direct support in the JS SDK for this. Hope this helps!

**Comment by kalyanidz** [comment]
@sowjanyanarra 
We also want to do the same in our application. Were you able to do this?
