### ISSUE TITLE
Chime SDK errors reference

### ISSUE THREAD

**Issue by skwny** [aws/amazon-chime-sdk-js#405]
Where is the documentation for errors when using amazon-chime-sdk-js? I would like to know what errors to expect, such as when the 16 attendees are publishing video, and a 17th attendee attempts to do so.

**Comment by aburnson** [comment]
Various errors that can occur during session connection are defined on the [MeetingSessionStatusCode](https://aws.github.io/amazon-chime-sdk-js/enums/meetingsessionstatuscode.html) which is the result of the [audioVideoDidStop](https://aws.github.io/amazon-chime-sdk-js/interfaces/audiovideoobserver.html#audiovideodidstop) observer method.

You can find out whether video availability (the ability to publish video, for example) has changed using the [videoAvailabilityDidChange](https://aws.github.io/amazon-chime-sdk-js/interfaces/audiovideoobserver.html#videoavailabilitydidchange) observer method and looking at the [canStartLocalVideo](https://aws.github.io/amazon-chime-sdk-js/classes/meetingsessionvideoavailability.html#canstartlocalvideo) field. If you attempt to `startLocalVideo` despite not having an available slot, then the local tile will be automatically removed after it is created.

These could be better explained in the documentation, so leaving this issue open to add the above into the API Overview and Use Cases guides.

**Comment by ltrung** [comment]
We already mentioned this
