### ISSUE TITLE
Firefox Video Tile Issues

### ISSUE THREAD

**Issue by edwardbc** [aws/amazon-chime-sdk-js#411]
**Scenario 1 : Tile Errors and Freeze**

Timeline:
* UserA joins as first user with Chrome and starts video
* UserB joins as second user with Firefox 76 and starts video.
* UserA turns video tile off and on several times.

On UserB's Firefox console an error is thrown and tiles might freeze sometimes, either immediately or when UserA leaves the meeting. 

Error thrown on Firefox:
```
ERROR: TypeError: this.removeTrackRemovedEventListeners[track.id] is not a function
```

Source of error:
https://github.com/aws/amazon-chime-sdk-js/blob/5a9d8d0a6b6c0809c7a856a1e3da89b1706dfdb0/src/task/CreatePeerConnectionTask.ts#L263

Logs

[FirefoxUser-debug.log](https://github.com/aws/amazon-chime-sdk-js/files/4677789/FirefoxUser-debug.log)
[ChromeUser-debug.log](https://github.com/aws/amazon-chime-sdk-js/files/4677788/ChromeUser-debug.log)

**Scenario 2 : Duplicate Tiles**

Timeline:
* UserA joins as first user with Chrome and starts video
* UserB joins as second user with Chrome and starts video
* User C joins as third user with Firefox and starts video

Bug: Four videos tiles will be displayed on Firefox, one of Chrome's would be duplicated. 

Note: Also happens if UserA shares video and screen and then Firefox joins, one of Chrome's streams would be duplicated , either Video or Content.

*Sample*
I've provided a sample app to replicate both issues, tested with latest version of the SDK (1.7.0) and with one and two machines:

https://github.com/edwardbc/Amazon-Chime-SDK-Firefox-Test

**Platform**
 - OS: Mac
 - Browser: Firefox 
 - Browser Version: 76 (Scenario 1) , Any (Scenario 2)
 - Amazon Chime SDK GitHub Commit: 1.7.0  `812f3b238f4e1e86f65a8f07c65c6eba459f09b3`

**Comment by rachinkapoor** [comment]
Here is another scenario:

**Timeline**
1. UserA joins as first user with Chrome and starts video
2. UserB joins as second user with Firefox 76 and starts video.
3. UserB revokes video permission

Bug:
Two video tiles displayed on both firefox and chrome. UserB's tile is frozen on both browsers.

**Log on Firefox:**
```
2020-05-25T19:48:41.382Z [WARN] 0 - video input device which was active is no longer available, resetting to null device
```
No log on chrome.

**Screenshots**
If applicable, add screenshots to help explain the problem.

**UserB's Platform**
 - OS: macOS Catalina 10.15.3
 - Browser: Firefox
 - Browser Version: 76.0.1
 - Amazon Chime SDK GitHub Commit: `812f3b238f4e1e86f65a8f07c65c6eba459f09b3` (v1.7.0)

**UserA's Platform**
 - OS: macOS Catalina 10.15.3
 - Browser: Chrome
 - Browser Version: 83.0.4103.61 (Official Build) (64-bit)
 - Amazon Chime SDK GitHub Commit: `812f3b238f4e1e86f65a8f07c65c6eba459f09b3` (v1.7.0)

**Comment by rachinkapoor** [comment]
If it helps, the above scenario is also reproducible on amazon chime application.

**Comment by alochbau-amzn** [comment]
The set of changes in #417 is to address the problem @rachinkapoor was seeing.

I have a handle on the problem described in scenario 1 and working on coming up with the best solution.

**Comment by alochbau-amzn** [comment]
The proper fix for this issue requires changes in our infrastructure as well as client side changes.  The infrastructure changes are in the process of being deployed and will take some days to be fully deployed.  Once those changes are fully deployed the client side changes will be merged to master.

Sorry for the wait.

**Comment by edwardbc** [comment]
Thanks!
