### ISSUE TITLE
Communication services like Video, audio and speaker are not working on Mobile/Mac Safari version 13.0.X

### ISSUE THREAD

**Issue by parthoadmin** [aws/amazon-chime-sdk-js#412]
**Meeting and attendee IDs:**
Not Applicable

**Timeline**

* Join a meeting as an attendee on any browser(ideally Chrome) - attendee-1
* Here attendee-1, observe live video tile and mic working on chrome
* Join the same meeting as an attendee on Mobile/Mac Safari 13.0.x  (ideally Safari 13.0.3 Please see screenshot 2 below)- attendee-2
* After Attendee-2 joins the meeting, he won't see any communication services working. Although it gives an option for selecting the Camera or Mic. (Here web page appears a blank screen with a camera, mic, speaker, and roster buttons. Please see screenshot 1 below)

**Describe the bug**
Users using Safari 13.0.X, were not able to use any communication services like video, mic, and speaker whereas it works on Safari >=13.1. Please refer to the screenshots below.

**Screenshots**

![Screen Shot 2020-05-25 at 11 07 34 AM](https://user-images.githubusercontent.com/50339846/82826856-e64a0c80-9e7b-11ea-8fb7-6f2bb4e2b25d.png)

![Screen Shot 2020-05-25 at 11 29 14 AM](https://user-images.githubusercontent.com/50339846/82826869-eba75700-9e7b-11ea-9a43-0cd26ead602c.png)

**Platform**
 - OS: MacOS Catalina 10.15.1

![Screen Shot 2020-05-25 at 11 40 40 AM](https://user-images.githubusercontent.com/50339846/82827245-9ae42e00-9e7c-11ea-823e-b467ad5bf1b1.png)

 - Browser: Safari 
 - Browser Version: 13.0.3
 - Amazon Chime SDK GitHub Commit: e2cc714025494a426f2744dcfa12734fbb9e5f8f

**Comment by ltrung** [comment]
Do you have any log available? We did a quick test with Safari 13 and Catalina but did not find any issue. 
Also could you verify that your microphone is enabled for Safari (Preferences -> Websites -> Microphone)?

**Comment by vidya-mohan** [comment]
parthoadmin@ are you still hitting this issue? Could you please respond to ltrung@ question above

**Comment by vidya-mohan** [comment]
Resolving with no response
