### ISSUE TITLE
Default Video Controls are rotated on self video

### ISSUE THREAD

**Issue by rachinkapoor** [aws/amazon-chime-sdk-js#413]
**Scenario 1 : Default Video Controls are inverted.**
As self preview tiles use style `transform: rotateY(180deg);`, everything is rotated by 180 degrees. This includes the video tag controls.

**Timeline**

* Join a meeting and turn on your camera (give required permissions)
* On your tile, right click and select show controls.

**Screenshots**
<img width="419" alt="Screen Shot 2020-05-26 at 1 00 54 AM" src="https://user-images.githubusercontent.com/17060141/82839543-55ac1480-9eed-11ea-8e52-38677e256757.png">

**Platform**
 - OS: macOS Catalina 10.15.3
 - Browser: Google Chrome
 - Browser Version: Version 83.0.4103.61 (Official Build) (64-bit)
 - Amazon Chime SDK GitHub Commit: `812f3b238f4e1e86f65a8f07c65c6eba459f09b3` (v1.7.0)

**Comment by ltrung** [comment]
@rachinkapoor We intentionally remove the 'controls' attribute here https://github.com/aws/amazon-chime-sdk-js/blob/master/src/videotile/DefaultVideoTile.ts#L33. Does your app need video controls?
Also just to clarify, but is the bug just that the video controls are rotated for self video or do you also not want the self video to be rotated?

**Comment by aburnson** [comment]
Closing as the SDK intentionally modifies CSS properties of the video element to provide the mirror effect on local video tile for front-facing cameras and removes unnecessary controls. The issue with the controls being horizontally flipped if the user re-enables controls is a display issue specific to the browser. Feel free to re-open if you think there is something the SDK can do better in this area for your use case.
