### ISSUE TITLE
 I can't complete the connection in a meeting

### ISSUE THREAD

**Issue by albertodam** [aws/amazon-chime-sdk-js#416]
**Describe issue:** I want connect from app angular at localhost. But when i call  this.meetingSession.audioVideo.start(); try join and never result it's okay.
![image](https://user-images.githubusercontent.com/11647193/82920406-85076380-9f77-11ea-9ecb-909e0f57d71e.png)

I searched info for this issue but i dont found nothing. I followed main readme of this repo step by step

NodeJS create meet and return info correctly to angular app.

**Comment by ltrung** [comment]
Hi @albertodam, Could you provide more details on how your app is setup and the steps that you have done?

**Comment by albertodam** [comment]
![image](https://user-images.githubusercontent.com/11647193/82935743-d7537f00-9f8d-11ea-9075-00eb55b001c3.png)

![image](https://user-images.githubusercontent.com/11647193/82935774-e803f500-9f8d-11ea-9119-af089e6bcde9.png)

![image](https://user-images.githubusercontent.com/11647193/82935800-f4884d80-9f8d-11ea-9af5-4ee7e770e180.png)

**Comment by albertodam** [comment]
Inspecting the logger i can see the next error

`JoinAndReceiveIndexTask error: JoinAndReceiveIndexTask got canceled while waiting for 
SdkIndexFrame`

**Comment by ltrung** [comment]
@albertodam Can you upload the full log?
Also a couple of things I noticed from your code:
- ChooseAudioInput seems to be missing.
- startLocalVideoTile should be call after audioVideo.start() succeeds
These probably do not cause the above error but it would cause other issues when you successfully create a meeting.

**Comment by albertodam** [comment]
Thanks for answering. I took into account the two things you were telling me. The problem was that I was trying to create a web component with angular and there were configuration errors. He decided to create a separate angular project instead of trying to create the web component. Thank you!

**Comment by mangalagiri** [comment]
Hi ltrung and albertodam

Please provide document or resource on angular with amazon chime. 

Madhu

**Comment by mangalagiri** [comment]
Hi albertodam,

Could you please help on integration node js (localhost 3001 )server code in angular.

Madhu

**Comment by albertodam** [comment]
I have two separate projects, in the project I only have a post method where I create the meet.

In the angular project I have the chime library integrated.

I don't know exactly what you need.
