### ISSUE TITLE
Video tiles missing when changing meetings

### ISSUE THREAD

**Issue by andyh6969** [aws/amazon-chime-sdk-js#418]
**Meeting and attendee IDs:**

Meeting ID: 77696028-7053-4df1-8308-8d034ea87302 - 
Attendee ID: 54f55636-d202-4685-8b33-f6b366028b71

**Describe the bug**
If you are in one meeting, then switch to another meeting. Then the second meeting does not get the video tiles.

We have a an app that is /meeting/1 then you manually change url (so force page reload) to meeting/2. when you initally go into meeting/2 then you do not get any video tiles.

You also do not get any roster updates for the new meeting.

Refreshing the page again causes the issue to resolve. 

I have attached Console logs. 1-bad shows inital load. 2-good is after another refresh.

[2nd-good-load.txt](https://github.com/aws/amazon-chime-sdk-js/files/4685192/2nd-good-load.txt)
[1st-bad-load.txt](https://github.com/aws/amazon-chime-sdk-js/files/4685193/1st-bad-load.txt)

**Platform**
 - OS: Windows
 - Browser:  Chrome
 - Browser Version:  83.0.4103.61 (Official Build) (64-bit)
 - Amazon Chime SDK GitHub Commit: 1.7.0

**Comment by aburnson** [comment]
In the first example, it appears that `bindVideoElement` is never called which is why no video tiles are shown.

In the second example, `bindVideoElement` is called, for example:

```
ConsoleLogger.js:69 2020-05-26T21:58:51.249Z [INFO] ChimeMeetingLogs - API/DefaultAudioVideoFacade/77696028-7053-4df1-8308-8d034ea87302/54f55636-d202-4685-8b33-f6b366028b71/bindVideoElement {"tileId":1,"videoElementId":"video-0"}
ConsoleLogger.js:69 2020-05-26T21:58:51.255Z [INFO] ChimeMeetingLogs - API/DefaultAudioVideoFacade/77696028-7053-4df1-8308-8d034ea87302/54f55636-d202-4685-8b33-f6b366028b71/bindVideoElement {"tileId":1,"videoElementId":"video-0"}
```

You may want to check what would be causing the first one to not call `bindVideoElement` where as the second one does. The SDK itself is stateless; it does not carry over any state between page reloads and so should behave the same the first and second times. Perhaps there is a difference in the way your application is initializing depending on whether resources are cached or not that could be causing different behavior or a race condition?

**Comment by andyh6969** [comment]
The reason that the bindVideoElement never runs is when the tile updates come through on `videoTileDidUpdate()` they look like this:

`[videoTileDidUpdate]  video tile did update:
 { "tileId": 1,  
"localTile": false, 
 "localTileStarted": false, 
 "isContent": false,  
"active": false,  
"paused": false,  
"poorConnection": false,  
"boundAttendeeId": null, 
 "boundExternalUserId": null, 
 "boundVideoStream": null,
  "boundVideoElement": null, 
 "nameplate": null,  
"videoStreamContentWidth": null,  
"videoStreamContentHeight": null,  
"videoElementCSSWidthPixels": null,  
"videoElementCSSHeightPixels": null,  
"devicePixelRatio": 0.8999999761581421, 
 "videoElementPhysicalWidthPixels": null,  
"videoElementPhysicalHeightPixels": null,  
"streamId": null}`

We see the same empty update every time there is a tile update, so it is signalling the updates but they are always empty.

**Comment by aburnson** [comment]
I see, yes that is odd that it has a null `boundAttendeeId`.

**Comment by andyh6969** [comment]
This is reproducable and I think its related to issues #443 and #427. It is like the user is authenticated to the call but there was an authenication error so you get notifications but don't get all the information.

**Comment by andyh6969** [comment]
I did some more digging into this. The tile add never fires as the presence change is not detected in 
src/task/CreatePeerConnectionTask.ts in bindExternalIdToRemoteTile()

` this.context.realtimeController.realtimeSubscribeToAttendeeIdPresence(handler);`

You get the remote video track event, but the issue is with the presence handler not triggering the add.

**Comment by andyh6969** [comment]
If you trace this back to `handleSignalingClientEvent()` in `ListenForVolumeInicatorsTask.ts` then in the failed cases you never recive the event type 18 (AUDIO_STREAM_ID_INFO). Which results in the presence update never firing.

**Comment by andyh6969** [comment]
This has been fixed now and can no longer recreate.
