### ISSUE TITLE
How many meetings can be running simultaneously

### ISSUE THREAD

**Issue by jitt3** [aws/amazon-chime-sdk-js#419]
Hi everyone.
I'm just creating a meeting app, a couple if questions came up: How many instances of chime can be started at the same.  e.g.: a user clicks upon  a "start meeting" button  and that action fires the creation of 2 instances of amazonChime object. 
The reason I am asking this, is just because I want to extend the capability of only 16 videotiles in a meeting, to 32.

thanks in advance.

**Comment by ldttmt** [comment]
The current default concurrent meeting one aws account can have is 250. You can check your limit via AWS Service Quotas.

**Comment by jitt3** [comment]
> The current default concurrent meeting one aws account can have is 250. You can check your limit via AWS Service Quotas.

Yeah you are totally right, but what I am trying to do is to have more than 16 attendees presenting theirs cameras

**Comment by vidya-mohan** [comment]
Chime SDK currently support upto 16 video streams only in a single meeting though there can be upto 250 participants in a call. You can find these in AWS Service Quotas as @ldttmt mentioned
