### ISSUE TITLE
no audio when sharing a video stream using startContentShare

### ISSUE THREAD

**Issue by devcodeash** [aws/amazon-chime-sdk-js#420]
`
const videoElement = document.getElementById('video-element-id');
const inputElement = document.getElementById('input-element-id')

inputElement.addEventListener('change', async () => {
  const file = inputElement.files[0];
  const url = URL.createObjectURL(file);
  videoElement.src = url;
  await videoElement.play();

  const mediaSream = videoElement.captureStream();
  await meetingSession.audioVideo.startContentShare(mediaSream);
  inputElement.value = '';
});
`

when i do this, video is visible to other attendees but no audio is coming.
can hear audio only from microphone
does this audio from the stream mix with audio input automatically or we have to do it manually, if manual how
thanks in advance

**Comment by henlamk** [comment]
have you found a solution for this case? 
I am facing the same issue

**Comment by devcodeash** [comment]
> have you found a solution for this case?
> I am facing the same issue

Not yet but their demo app works fine [https://github.com/aws/amazon-chime-sdk-js/tree/master/demos/browser](Meeting App)

**Comment by jienco** [comment]
I have the same issue with `startContentShare(mediaSream)` where the audio can only be heard in the browser of the one sharing, but remote attendees cannot hear the audio of the content shared. My mediaStream is also coming from a video element capture where I loaded a local MP4 file. Does anyone know how to make this work?

**Comment by jienco** [comment]
I found the solution: I needed to await playback of the video and capture of the stream before starting share:

```typescript
    const file: File = event.target.files[0];
    const URL = window.URL || window.webkitURL;
    const src = URL.createObjectURL(file);
    videoElement.src = src;
    videoElement.load();

    await videoElement.play();

    const mediaStream = await videoElement.captureStream();
    await meetingSession.audioVideo.startContentShare(mediaStream);
```
