### ISSUE TITLE
Can i rebind video data?

### ISSUE THREAD

**Issue by rusicsemenov** [aws/amazon-chime-sdk-js#421]
### What are you trying to do?

I try dynamic change view my page, and after change view video data is lost. Can i rebind all video on page?

**Comment by ltrung** [comment]
Yes, you should be able to do that. Do you run into any issue with that?

**Comment by rusicsemenov** [comment]
Thanks fo ansver.

I create vue aplication, and views, after click vue rebuild page gfom grid to other view with slider. I am try `meetingSession.audioVideo.stop();` and `meetingSession.audioVideo.start();`. But video dont bind again. What the comand for rebind viedo? Do you have comand `meetingSession.audioVideo.restart()` or reload?

mb `meetingSession.audioVideo.getAllVideoTiles()` and bind from tileState?

**Comment by rusicsemenov** [comment]
I can rebind with `meetingSession.audioVideo.getAllVideoTiles()` and after use `meetingSession.audioVideo.bindVideoElement`
