### ISSUE TITLE
Handle Audio Input Permissions Revoked

### ISSUE THREAD

**Issue by mikeantonelli** [aws/amazon-chime-sdk-js#422]
**Meeting and attendee IDs:**
n/a

**Timeline**
1. Join a meeting, granting permissions to an audio input device
2. Use the browser to revoke audio device permissions

*Note: this can also occur when the peripheral is battery powered and the battery dies, or a bluetooth device when bluetooth is disabled. This occurred initially when my bluetooth headphones died. 

**Describe the bug**
The following warning is logged:
```
audio input device which was active is no longer available, resetting to null device
```

I believe this is another case similar to #417 and should be handled in a similar fashion to video.

**Screenshots**

**Platform**
 - OS: macOS
 - Browser: Firefox 
 - Browser Version: 76.0.1 
 - Amazon Chime SDK GitHub Commit: 1.7.0

**Comment by RidipDe** [comment]
When audio input permissions are revoked, it does not affect the currently active session. The permissions goes into effect when the website is refreshed / reloaded. It does not affect the active session.

For the log statement “audio input device which was active is no longer available, resetting to null device” which we encounter when the peripheral is battery powered and the battery dies, or a bluetooth device when bluetooth is disabled, you can implement the DeviceChangeObserver methods as shown in the case 4 https://github.com/aws/amazon-chime-sdk-js#device

**Comment by RidipDe** [comment]
Closing the ticket for now, feel free to open it if the problem still exists

**Comment by ltrung** [comment]
@mikeantonelli We have added new device observer event that you can subscribed and listened to when the ended event happend to audio or video input. Please re-open if you have new questions.
