### ISSUE TITLE
Unable to local video preview on mobile devices after a webRTC session started.

### ISSUE THREAD

**Issue by tatsuya-nagashima** [aws/amazon-chime-sdk-js#429]
**Timeline**
* Join a meeting on mobile browser.
* Start local video preview for the attendee.  
   (Execute deviceController.startVideoPreviewForVideoInput function.)
   At this point, the local tile is displaying the video from the built-in camera.
* Start a chime webRTC session. (Start meetingSession.audioVideo.Observer)
* Then, the local tile turns to the black video tile.

**Describe the bug**
Example code is following.

```
attendeeJoinFunc(){};

//Display the local video tile.
await deviceController.chooseVideoInputDevice(videoInput.value);
deviceController.startVideoPreviewForVideoInput(document.getElementById("video-preview"));
  
// Start the chime webRTC session
meetingSession.audioVideo.start();
meetingSession.audioVideo.startLocalVideoTile();
 ```

**Screenshots**
If applicable, add screenshots to help explain the problem.

**Platform**
 - OS: iOS 13.4.1 (iPhone8)
 - Browser: Safari 
 - Browser Version: 13.1

**Comment by aburnson** [comment]
Are you calling `stopVideoPreviewForVideoInput` after [startVideoPreviewForVideoInput](https://aws.github.io/amazon-chime-sdk-js/interfaces/audiovideofacade.html#startvideopreviewforvideoinput)? The preview is not meant to be used during the meeting session.

**Comment by tatsuya-nagashima** [comment]
Not calling stopVideoPreviewForVideoInput after startVideoPreviewForVideoInput.
Because I need to check the my built-in camera video which transmitting to other attendees during the meeting session. 

Here is an example of the mobile device UI. The left side is a local preview area that displaying the built-in camera video (What video you are transmitting). The right side is a webRTC preview area that displaying the meeting video. My requirement is to watch both during the meeting session.
However, in my environment, built-in camera video (local preview area) turned to a black tile If the meeting session started. Are there any way to preview both of built-in camera video and webRTC video at the same time? 
![IMG_6811](https://user-images.githubusercontent.com/19338476/83540124-db097780-a532-11ea-833c-cfe12bce4feb.PNG)

**Comment by aburnson** [comment]
When you call `audioVideo.startLocalVideoTile()` you will receive the tile id for that video tile, which can then be bound to a video element during the `videoTileDidUpdate` callback with `audioVideo.bindVideoElement()` just like a remote video tile. The video preview API would only be used for checking the camera before joining the meeting.

**Comment by tatsuya-nagashima** [comment]
Thanks, I understood. But then I have another question. Why can audioVideo.startLocalVideoTile() be used during a meeting on a PC?  In the case of PC, audioVideo.startLocalVideoTile() did not turn the black tile even during the meeting, and it continued to display the built-in camera video.

**Comment by narender016** [comment]
![16250531991047250424828558485483](https://user-images.githubusercontent.com/65656990/123954468-0ecd0000-d9c6-11eb-9c78-f8c82da2fce0.jpg)
Sometimes I got this error when session is started
And then start sharing vidwo

**Comment by michhyun1** [comment]
@narender016 if you could create a new issue instead, that would be much appreciated. Thanks. Please include logs and more details if you can. Thanks.
