### ISSUE TITLE
Access attendee tags

### ISSUE THREAD

**Issue by skwny** [aws/amazon-chime-sdk-js#430]
### What are you trying to do?
Access the tags on each attendee. I can add these when calling CreateAttendee, but I haven't seen how to access them via the SDK.

### How can the documentation be improved to help your use case?
Provide example of how to access meeting attendee tags.

### What documentation have you looked at so far?
README.md, Amazon Chime SDK Developer Guide

**Comment by aburnson** [comment]
Attendee tags are not accessible via the Amazon Chime SDK for JavaScript. You can access attendee tags via the [ListAttendeeTags](https://docs.aws.amazon.com/chime/latest/APIReference/API_ListAttendeeTags.html) action from the Chime service API.
