### ISSUE TITLE
Allow Chime meeting ID to be provided by the client

### ISSUE THREAD

**Issue by skwny** [aws/amazon-chime-sdk-js#431]
Feature request.

Since Chime uses auto-end logic, the meeting ID (which clients must know to join a meeting) may go stale before it begins, requiring the meeting to be created at just the right time. Thus, I have to use an approach where I persist chime meeting IDs, and if the meeting closes automatically, I must update the meeting ID each time a new one is created. 

It would be much easier to simply use the unique id I already possess (which I assign to pre-planned meetings) to create the meeting with. This way I always know what meeting to create/join, without having to persist Chime meeting IDs.

**Comment by aburnson** [comment]
@skwny thanks for your request. The Chime SDK does not define PIN or meeting ID management and intentionally leaves it up to you to build that logic into your server application as fits your use case. As for managing auto-end we recommend that you create the meeting right before the first attendee joins as a find-or-create operation in your server application.

Closing this issue as it does not appear there is any action we can take in the context of the JavaScript client SDK at the moment, but we have taken your feedback about the complications you are experiencing with auto-end.
