### ISSUE TITLE
WebSocket closed when calling realTimeSendDataMessage

### ISSUE THREAD

**Issue by utkarshkoushik** [aws/amazon-chime-sdk-js#433]
When I call the realTimeSendDataMessage I get a message in my console as -->
notifying event: WebSocketClosed
And then the user reconnects to the meeting and his message is not displayed to other users

**Platform**
 - OS: Windows
 - Browser: Chrome
 - Browser Version: 83.0.4103.61
 - Amazon Chime SDK GitHub Commit: fa0245a

**Comment by aburnson** [comment]
Just curious, what topic name and payload size are you using for the data message? It sounds like there may be some missing client-side validation in the SDK and so a non-legal message is arriving at the server and the server is thus hanging up the connection.

**Comment by utkarshkoushik** [comment]
@aburnson Thanks a lot for your help. Actually I found the mistake. I used a variable to store the topic name and ReactJS was not allowing me to access that variable inside the function in which I was calling realTimeSendDataMessage. I just changed that. Now it's working perfectly.
