### ISSUE TITLE
How to use MediaRecording

### ISSUE THREAD

**Issue by barrazastark** [aws/amazon-chime-sdk-js#434]
### What are you trying to do?
I want to make an example of media recording

*For example: I'm trying to start a meeting session with audio and video and then record any screen.*

### How can the documentation be improved to help your use case?

*For example: Include a section on how to use and configure this: *
https://github.com/aws/amazon-chime-sdk-js/blob/master/src/mediarecording/WebMMediaRecording.ts

**Comment by aburnson** [comment]
The `mediarecording` component is internal and not intended to be used for this purpose. Where do you want to record your screen to? To a file? Or do you want it to be broadcast to the other attendees? For the latter you can use [content share](https://github.com/aws/amazon-chime-sdk-js#screen-and-content-share).

**Comment by barrazastark** [comment]
ok, thanks @aburnson
