### ISSUE TITLE
Using chime with no camera throws error while fetching devices

### ISSUE THREAD

**Issue by Ardenexal** [aws/amazon-chime-sdk-js#436]
**Important:** Please attach INFO-level logs with timestamps to the report from *before* the session started up until the point at which the unexpected behavior occured. For multi-participant calls, attach a log file for each participant if possible.

**Meeting and attendee IDs:**
N/A

**Timeline**
- User does not have a camera attached to their computer but wants to join the session audio-only
- when running listAudioInputDevices it will trigger the `deviceLabelTrigger ` from the `DefaultDeviceController` but the browser will throw a `DOMException requested device not found` because the `deviceLabelTrigger` is requesting both video and audio.

**Describe the bug**
The issue is with always requesting both the camera and microphone permissions even when there is no camera. The user should be able to join with a microphone only so there should be a way to request the permissions for only audio if no camera exists so that the user can still join the session.
**Screenshots**
If applicable, add screenshots to help explain the problem.

**Platform**
 - OS: Windows
 - Browser: Chrome
 - Browser Version: 82
 - Amazon Chime SDK GitHub Commit:  812f3b2

**Comment by aburnson** [comment]
See this section in the docs on overriding the default device label trigger if you would like to customize its behavior:
https://aws.github.io/amazon-chime-sdk-js/modules/apioverview.html#2a-configure-the-device-label-trigger-optional

The SDK's default device label trigger could do a better job of detecting that there are no video devices and not requesting video during the device label trigger.

**Comment by Ardenexal** [comment]
Thanks that worked this is what I ended up doing if it helps anyone

```ts
const devices = await navigator.mediaDevices.enumerateDevices();
    // filter to only video inputs
    const videoList = devices.filter(value => {
      return value.kind === 'videoinput';
    });
    
    // if there are no video inputs then don't attempt to request permission for it
    if (videoList.length === 0) {
      this.deviceController.setDeviceLabelTrigger(() => {
        return navigator.mediaDevices.getUserMedia({ audio: true, video: false });
      });
    }
```

**Comment by abhimanusharma** [comment]
@Ardenexal 
What's this.deviceController? How are you using it inside chime meeting?

**Comment by Ardenexal** [comment]
this.deviceController is just the audioVideo.deviceController assigned to a variable
