### ISSUE TITLE
Couple inquiries about iOS devices

### ISSUE THREAD

**Issue by cjeremylin** [aws/amazon-chime-sdk-js#438]
### What are you trying to do?

We are trying to implement a web-based application for iOS and android devices client. But encountered some issue as following: 

1. Constructor of DefaultDeviceController cannot run on iOS Chrome/Firefox.

=> We got errors: 
`TypeError: undefined is not an object (evaluating 'navigator.mediaDevices.addEventListener')
` 

2. Client cannot receive stream if chooseVideoInputDevice and chooseAudioInputDevice in MediaSession.AudioVideo class if set null as parameter on iOS Safari. 

=> Scenario: We wants to let user who is the only one speaker (teacher) in the meeting can enable video and audio, and the rest of users (students) only view the video stream from speaker. Is it possible to let those students don't need to approve the device permission and only allow it when speaker starting to enable camera? Not sure why the client can not receive the video from speaker if we set the null in chooseVideoInputDevice / chooseAudioInputDevice

3. Does the demo/browser can support that web application was bind on other network interface (i.g., 192.168.x.x)? 

=> We noticed it would be some error when I replace the host from '127.0.0.1' to '192.168.x.x' in `server.js`. We got errors:

`Unable to find meeting
There was an issue finding that meeting. The meeting may have already ended, or your authorization may have expired.`

We also looked into the network request keep sending POST to /logs with following payload:

`{"meetingId":"4a01061c-bce5-482b-9a50-bb0362a688c0","attendeeId":"c159b1b5-83a4-4ea4-887b-d97e79720d3e","appName":"SDK","logs":[{"sequenceNumber":0,"message":"DefaultDeviceController video dimension 960 x 540","timestampMs":1591106917350,"logLevel":"INFO"}]}`

After searching code [snippet](https://github.com/aws/amazon-chime-sdk-js/blob/0910e823144cfbbdcfa7223c7b7ffa5201adf799/demos/browser/app/meeting/meeting.ts#L562), we found that if the host is not 'localhost' or '127.0.0.1'. It would send log out. We also found that there is a remote_credentials.js in asw-sdk/credentials/ package. Does this restriction lead to we can not run on other NIC. Because we want to let this demo/browser can run on our LAN and accessible by iOS and Android devices in the same LAN via wifi. 

### How can the documentation be improved to help your use case?

I understand that the mobile support documentation still need to be updated in the nearly feature from this [thread](https://github.com/aws/amazon-chime-sdk-js/issues/426#issuecomment-636231974). But hope can get some help for the preceding inquires. Thanks. 

### What documentation have you looked at so far?

README.md 
[API Overview ](https://aws.github.io/amazon-chime-sdk-js/modules/apioverview.html)

**Comment by ltrung** [comment]
1) Chrome/Firefox on iOS do not currently support WebRTC so they would not work with Chime JS SDK.
2) Could you give more details? Is there any error when the client could not receive video? I tried it out in the demo app with blocked permission to both video and mic as well as setting them to None and I could still see remove video.
Also our [broadcast demo](https://github.com/aws-samples/amazon-chime-meeting-broadcast-demo) seems like a good candidate for your scenarios.
3) So the demo app tries to log the logs to CloudWatch if it does not run in local host. Could you edit that code to include your IP 192.168.x.x? 
Alternatively, you can use the serverless demo which deploys the same demo to the cloud.

**Comment by cjeremylin** [comment]
Hi, 

Thanks for quickly response. For second issue. Please see the following [sample code function.txt](https://github.com/aws/amazon-chime-sdk-js/files/4747211/sample.code.function.txt). The line 12 comment 
`// if set null on iOS Safari will trigger can't play video/audio issue`
Should I not to set null before a meetingSession.audioVideo.start()?

This code snippet works well on MacOS/Windows/Android, except iOS safari. We also did not see any error message, it just did not show the video on iOS safari. 

If you need more information, please let me know, thanks.

**Comment by simmkyu** [comment]
> second issue. Please see the following [sample code function.txt](https://github.com/aws/amazon-chime-sdk-js/files/4747211/sample.code.function.txt). The line 12 comment
> `// if set null on iOS Safari will trigger can't play video/audio issue`
> Should I not to set null before a meetingSession.audioVideo.start()?
> 
> This code snippet works well on MacOS/Windows/Android, except iOS safari. We also did not see any error message, it just did not show the video on iOS safari.

@cjeremylin We have an open issue that in iOS, no attendee shows up when joining a meeting with the `null` audio device.
https://github.com/aws/amazon-chime-sdk-js/issues/474

If a user hasn't explicitly chosen the audio device, Chime SDK creates an empty audio device using the Audio Context API and joins a meeting. In iOS, SDK can't join a meeting unless a user has allowed the microphone permission before.
