### ISSUE TITLE
Selecting None option in preview mode for Mic/Video then cannot able join the meeting

### ISSUE THREAD

**Issue by prakash-partho** [aws/amazon-chime-sdk-js#448]
**Important:** 
![Image #11 2](https://user-images.githubusercontent.com/49286997/83716549-d71e4800-a64d-11ea-906a-0cb7e2c923bc.png)

**Meeting and attendee IDs:**
attendee 1 or attendee2

**Describe the bug**
After joining the meeting using the  Meeting ID and Name on web client user is navigated to the permissions view page and after accepting the permissions user is presented with microphone, video and speaker selection items in preview mode. Here if user chooses None and clicks on join meeting he will then sometimes hemight joined the meeting but cannot see other attendees and other attendees also cannot see him, and sometimes his video/audio is not visible to other attendees. I have observed some errors in the console, and screenshot is pasted above for reference.

**Platform**
 - OS: Mac
 - Browser: Chrome/Safari
 - Browser Version: Safari - 13.1.1
                                 Chrome - 83.0.4103.97
 - Amazon Chime SDK GitHub Commit:  version 1.7.0

**Comment by RidipDe** [comment]
Can you try re-producing the issue ?
I tried to re-produce this issue a couple of times, but could not. Worked fine for me.
