### ISSUE TITLE
Can't join meeting with already 8 attendees with video

### ISSUE THREAD

**Issue by rlebosse** [aws/amazon-chime-sdk-js#449]
Hello, 

I'm facing this issue :
* I've joined a meeting with 8 different attendees, each one has started its local video (with `audioVideo.startLocalVideoTile`)
* If I try to join the meeting with a new attendee (attendee number 9), with ou without local video, he is not able to join the meeting

I tried running another test :
* 7 attendees joined the meeting with local video
* Attendee number 8 join the meeting without local video
* Attendee number 9 was able to join the meeting
* But as soon as I enabled local video with attendee number 8, attendee number 9 was disconnected from the meeting

Did I miss something here ? Is this a bug or is there an explanation or a workaround ?

I'm using :
* Chrome 83
* macOS 10.15.5

Thanks in advance !

**Comment by rlebosse** [comment]
I've been able to reproduce the issue with demos/browser : https://github.com/aws/amazon-chime-sdk-js/tree/master/demos/browser

**Comment by RidipDe** [comment]
Are all the attendees joining from the same system for testing purpose ?

**Comment by RidipDe** [comment]
Can you please let us know if the 7 other attendees are remote users - each joining from separate systems or are they joining from the same machine (for testing purpose) ?

**Comment by rlebosse** [comment]
* The 7 first attendees are on the same computer (Ubuntu 18.0, Google Chrome)
* Attendees 8 and 9 (those who are encountering some problems) are on another computer (macOS 10.15.5, Google Chrome)

**Comment by XHatan** [comment]
Hi
thanks for reporting the issues
we are deploying a fix in backend, could you try again and let us know if the issue is resolved ?

**Comment by andyh6969** [comment]
I magaged to get 10 on reliably this morning so it appears to be resolved. Thanks

**Comment by XHatan** [comment]
thanks @andyh6969 we do support up to 16 video tiles

@rlebosse please let me know if the issue is resolved for you as well.
