### ISSUE TITLE
Chime + Sentry = memory leak

### ISSUE THREAD

**Issue by gkio** [aws/amazon-chime-sdk-js#450]
In react web app using redux + redux-saga using chime generates huge memory leak with sentry enabled
```
"raven-for-redux": "^1.4.0",
"raven-js": "^3.27.2",
```
**Screenshots**
Left is with Sentry and the right without
<img width="1126" alt="Screenshot 2020-06-04 at 10 53 50 AM" src="https://user-images.githubusercontent.com/14029476/83746591-f924c400-a667-11ea-93cd-f204a54613d9.png">

**Platform**
 - OS: Any
 - Browser: Safari 
 - Browser Version: 13.0.5 
 - Amazon Chime SDK GitHub Commit: "amazon-chime-sdk-js": "^1.6.2",

**Comment by ltrung** [comment]
Since the issue only happens with Sentry enabled, it seems to suggest the issue is with Sentry itself. Is there any information to indicate that the memory leak is from SDK?

**Comment by ellismarte** [comment]
@gkio did you figure this out?

**Comment by gkio** [comment]
@ellismarte yes it was problem with sentry version i updated to the latest one and now its ok

**Comment by ellismarte** [comment]
@gkio ok great. Ill give that a shot. thanks
