### ISSUE TITLE
Connection Errors, and State

### ISSUE THREAD

**Issue by keean** [aws/amazon-chime-sdk-js#451]
I am trying to build a client using the Chime-SDK. It is important that the client is resilient. I am having problems with the following scenarios:

1. Starting a connection attempt whilst offline or poor wifi (simulated by turning of wifi on my laptop), and trying to cancel by calling audioVideo.stop() results in a strange state where the camera light is on, but there is no video. 

2. Trying to audioVideo(stop) whilst offline seems to also leave the camera on and you cannot connect again.

3. If you get an expired meeting object from the server, it tries to connect with it.

I cant find a model of the SDK state machine in the documentation. The states it can be in, what transitions different calls to the SDK make, and where if is safe to call certain SDK functions.

After calling "audioVideo.start", when is it safe to call "audioVideo.stop" (and vice versa), what happens if something goes wrong when connecting, what state is it left in etc. How do a 'reset' the SDK after a failure.

**Comment by yusufali2205** [comment]
I'm working on similar issue to reconnect automatically if initial connection fails because of expired meeting object. To stop your camera try this:

```
audioVideo.stopLocalVideoTile();
audioVideo.chooseVideoInputDevice(null);
audioVideo.stop();
```

I've started some discussion here: https://github.com/aws/amazon-chime-sdk-js/issues/457

**Comment by ltrung** [comment]
>I cant find a model of the SDK state machine in the documentation. The states it can be in, what transitions different calls to the SDK make, and where if is safe to call certain SDK functions.
We do not have a documentation about this. Ideally, if something goes wrong, the SDK should throw back error code for clients to handle.

To clarify:
1) For the first case, you try to call audioVideo.start() while offline then try to call audioVideo.stop(). Is that correct? If so, when do you call startLocalVideoTile? 
2) For the second case, you use audioVideo.start() successfully then turn off wifi, then call audioVideo.stop() and after that audioVideo.start() fails. Is that correct? 

Is there any error message for these two cases? Any log would be helpful. You could also try to reproduce the issue with our demo app and see if these issues are reproducible.
