### ISSUE TITLE
demos/browser - npm run start not working on ec2 instance(linux)

### ISSUE THREAD

**Issue by dsuraj72** [aws/amazon-chime-sdk-js#453]
**Describe the bug**
I took a clone of the project & was able to run the example browser code on my local machine. However i'm facing an issue with ec2 deployment. Currently I'm unable to run/deploy the demo/browser example on one of the ec2 server(linux). node & npm versions are up to date.

**Screenshots**
Have attached couple of screenshots
[error log.txt](https://github.com/aws/amazon-chime-sdk-js/files/4734775/error.log.txt)
.
![Screenshot 2020-06-05 at 1 24 15 PM](https://user-images.githubusercontent.com/14140865/83851986-c09ced00-a730-11ea-921c-6f105f0ea812.png)

**Comment by ekpono** [comment]
I am having the same error in both my local machine and EC2 Instance

**Comment by RidipDe** [comment]
Can you please try ire-nstalling nodejs and npm:

For Node.js: 
    sudo apt-get update
    sudo apt-get install nodejs

For npm:
    sudo apt-get install npm

After these commands, pls verify using the command:
    nodejs -v

**Comment by ekpono** [comment]
I have upgraded my node and npm. Still getting the same exact error.

**Comment by simmkyu** [comment]
`npm run start` worked for me in my EC2 instance.

<img width="1648" alt="Screen Shot 2020-06-15 at 10 52 53 AM" src="https://user-images.githubusercontent.com/36240708/84690681-ba103180-aef7-11ea-9ea0-04f9057a467a.png">

For testing, I used "Amazon Linux 2 AMI (HVM), SSD Volume Type" and followed this instruction to set up Node 14.4.0 (NPM will be installed automatically):
https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/setting-up-node-on-ec2-instance.html

Could you try again after following this developer guide?

**Comment by kaldown** [comment]
@simmkyu no, it doesn't work even with commands from a screen you've provided

**Comment by kaldown** [comment]
`nvm use 14` solved the problem. While tutorial never mentioned this
