### ISSUE TITLE
subscriptioncheck failed

### ISSUE THREAD

**Issue by tryel** [aws/amazon-chime-sdk-js#454]
I add in the main page meeting title, name and then click on "Continue button" but I have this error:

![Schermata a 2020-06-05 10-29-56](https://user-images.githubusercontent.com/6014018/83854949-b1f60c00-a717-11ea-9eb2-c241805b3080.png)

Already check if IAM user credentials are correct.

**Comment by RidipDe** [comment]
It seems to be an Authentication issue. If you are sure with the credentials and still getting this error message, we request you to open an AWS support ticket and someone from the support team can look into your account.
