### ISSUE TITLE
setSinkId leads to promise error

### ISSUE THREAD

**Issue by mikalai-churakou** [aws/amazon-chime-sdk-js#455]
During the going chime meeting I perform disabling of current bluetooth speaker device and want to proceed with other, for example built in default. With help of chime js sdk our app calls meetingSession.audioVideo.chooseAudioOutputDevice(deviceId) with valid deviceId of connected device and as result inside sdk's method bindAudioMix we have error on line: this.audioElement.setSinkId(newSinkId);
and sink id is not updated for audio element. As result device switching does not work. On current web page i gave permission for usage of audio and video on browser.

**Comment by RidipDe** [comment]
Have a PR out to resolve this issue https://github.com/aws/amazon-chime-sdk-js/issues/522

**Comment by vidya-mohan** [comment]
Fix out in 1.11.0 https://www.npmjs.com/package/amazon-chime-sdk-js
