### ISSUE TITLE
audioVideoDidStop is not called for AudioJoinedFromAnotherDevice

### ISSUE THREAD

**Issue by simmkyu** [aws/amazon-chime-sdk-js#457]
**Important:** Please attach INFO-level logs with timestamps to the report from *before* the session started up until the point at which the unexpected behavior occured. For multi-participant calls, attach a log file for each participant if possible.

**Meeting and attendee IDs:**
List the meeting and attendee IDs that the attached logs apply to.
N/A

**Timeline**
Outline the main actions the user performed and when:
N/A

**Describe the bug**
Describe the bug and the timestamp at which it happened relative to the timestamp in the log file.

When the meeting session is connected, SDK keeps receiving singaling frames over WebSocket from the Chime backend. If SDK receives a frame with an error or an audio status, SDK might stop the session and call [the `AudioVideoObserver.audioVideoDidStop()` observer method](https://github.com/aws/amazon-chime-sdk-js/blob/master/src/audiovideoobserver/AudioVideoObserver.ts#L26) with a meeting status code. Using this meeting status code, a customer can display a specific error message and handle it accordingly.

For example, if SDK receives a frame with the 301 audio status code, SDK stops the session and calls `AudioVideoObserver.audioVideoDidStop()` with [the `AudioJoinedFromAnotherDevice` meeting status code](https://github.com/aws/amazon-chime-sdk-js/blob/master/src/meetingsession/MeetingSessionStatusCode.ts#L18).

We received bug reports that customers didn't receive `AudioVideoObserver.audioVideoDidStop()` when `AudioJoinedFromAnotherDevice` happened.

**Screenshots**
If applicable, add screenshots to help explain the problem.

**Platform**
 - OS: macOS and Windows
 - Browser: Chrome and FF
 - Browser Version: All supported versions
 - Amazon Chime SDK GitHub Commit: c610e1222af3c60cdadac193d7aba3e6afdc0e5a

**Comment by yusufali2205** [comment]
`AudioVideoObserver.audioVideoDidStop()` isn't received also in the case when meeting fails to start because the meeting is already deleted.

**Comment by simmkyu** [comment]
> We received bug reports that customers didn't receive AudioVideoObserver.audioVideoDidStop() when AudioJoinedFromAnotherDevice happened.

In the SDK browser demo, I confirmed that [`AudioVideoObserver.audioVideoDidStop`](https://github.com/aws/amazon-chime-sdk-js/blob/dc98c59d65330cae6d789c12dc987ed46867ac75/src/audiovideoobserver/AudioVideoObserver.ts#L26) was called with [`MeetingSessionStatusCode.AudioJoinedFromAnotherDevice`](https://github.com/aws/amazon-chime-sdk-js/blob/dc98c59d65330cae6d789c12dc987ed46867ac75/src/meetingsession/MeetingSessionStatusCode.ts#L18) when reusing the same join token.

1. In Device A, an attendee starts a meeting using the `CreateAttendee` response from your server application. Note that this response includes the join token.
2. In Device B, an attendee uses the same `CreateAttendee` response to start a meeting.
3. In Device A, [`AudioVideoObserver.audioVideoDidStop`](https://github.com/aws/amazon-chime-sdk-js/blob/dc98c59d65330cae6d789c12dc987ed46867ac75/src/audiovideoobserver/AudioVideoObserver.ts#L26) will be called with [`MeetingSessionStatusCode.AudioJoinedFromAnotherDevice`](https://github.com/aws/amazon-chime-sdk-js/blob/dc98c59d65330cae6d789c12dc987ed46867ac75/src/meetingsession/MeetingSessionStatusCode.ts#L18).
    .
    ```
    import { MeetingSessionStatusCode } from 'amazon-chime-sdk-js';

    const observer = {
      audioVideoDidStop: sessionStatus => {
        const sessionStatusCode = sessionStatus.statusCode();
        if (sessionStatusCode === MeetingSessionStatusCode.AudioJoinedFromAnotherDevice) {
          // Called!
        }
      }
    };

    meetingSession.audioVideo.addObserver(observer);
    ```

**Comment by simmkyu** [comment]
I'll resolve this issue as `AudioVideoObserver.audioVideoDidStop()` is called with `AudioJoinedFromAnotherDevice`. Please open a new issue with logs and/or repro steps if `AudioVideoObserver.audioVideoDidStop()` is not getting called for reusing the join token.

> AudioVideoObserver.audioVideoDidStop() isn't received also in the case when meeting fails to start because the meeting is already deleted.

We'll track another `audioVideoDidStop` issue in https://github.com/aws/amazon-chime-sdk-js/issues/483. I confirmed that SDK attempted to reconnect the session multiple times when joining a finished meeting. I think we should stop it immediately so a customer can handle this gracefully.
