### ISSUE TITLE
Error creating DefaultDeviceController if not localhost in development environemnt

### ISSUE THREAD

**Issue by walfen** [aws/amazon-chime-sdk-js#459]
**Describe the bug**
There is an error when creating the DefaultDeviceController if the domain is not localhost on development environment:
- localhost:3000 works 
- 192.168.0.227:3000 fails

Logs:
```
2020-06-06T05:17:30.786Z [INFO] SDK - DefaultDeviceController video dimension 960 x 540
VideoComponent.tsx:31 TypeError: Cannot read property 'addEventListener' of undefined
    at new DefaultDeviceController (DefaultDeviceController.ts:59)
    at VideoService.connect (VideoService.ts:38)
    at async VideoComponent.init (VideoComponent.tsx:55)
    at async VideoComponent.componentDidMount (VideoComponent.tsx:29)
```
Code:
```
// get meeting and attendee from backend api
const meetingResponse = await videoApi.getMeeting();
const attendeeResponse = await videoApi.getAttendee(meetingResponse.Meeting.MeetingId, chatId);

// create meeting session configuration
const configuration = new MeetingSessionConfiguration(meetingResponse.Meeting, attendeeResponse.Attendee);

// create meeting session
const logger = new ConsoleLogger('SDK', LogLevel.DEBUG);
const deviceController = new DefaultDeviceController(logger); // it fails here
```

**Platform**
 - OS: Windows 10
 - Browser: Chrome
 - Browser Version: 83.0.4103.61
 - Amazon Chime SDK GitHub Commit: 1.7.0

**Comment by simmkyu** [comment]
I guess that `192.168.0.227:3000` is not under HTTPS. In a non-HTTPS host, modern browsers don't allow users to access your microphone and camera. A hostname `localhost` is excluded, so `http://localhost:3000` was working. Please try again after deploying your web app to HTTPS. We will track this media device issue in https://github.com/aws/amazon-chime-sdk-js/issues/456 for imporving documentation and [the BrowserBehavior component](https://github.com/aws/amazon-chime-sdk-js/blob/master/src/browserbehavior/BrowserBehavior.ts).
