### ISSUE TITLE
 node: command not found

### ISSUE THREAD

**Issue by ekpono** [aws/amazon-chime-sdk-js#460]
I have cloned the repository both in my machine and my EC2 instance. 
I keep getting the same error

`git clone https://github.com/aws/amazon-chime-sdk-js.git
 cd amazon-chime-sdk-js/
 cd demos/browser
`
When I run
`
npm run start
`

I get NPM error

**Comment by ekpono** [comment]
<img width="1440" alt="Screen Shot 2020-06-07 at 11 58 30 AM" src="https://user-images.githubusercontent.com/35940495/83967200-4c408600-a8b7-11ea-8780-30677eb02c81.png">

**Comment by RidipDe** [comment]
Can you please try re-installing nodejs and npm:

For Node.js:
sudo apt-get update
sudo apt-get install nodejs

For npm:
sudo apt-get install npm

After these commands, pls verify using the command:
nodejs -v

**Comment by simmkyu** [comment]
To run the SDK browser demo, you'll need Node (10 or higher) and NPM (6.11 or higher) installed on your host. Please try again after installing Node and NPM.

https://github.com/aws/amazon-chime-sdk-js/tree/master/demos/browser#prerequisites

**Comment by simmkyu** [comment]
`npm run start` in the browser demo worked okay for me in EC2. I used "Amazon Linux 2 AMI (HVM), SSD Volume Type" for testing.

<img width="1648" alt="Screen Shot 2020-06-15 at 10 52 53 AM" src="https://user-images.githubusercontent.com/36240708/84689961-9d272e80-aef6-11ea-9528-19fa8fff44f6.png">

The error in your screenshot shows that `node` is not available. Please try again after installing `node`. I followed this instruction for setting up node (npm will automatically be installed):
https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/setting-up-node-on-ec2-instance.html
