### ISSUE TITLE
Demo application fails with Cannot read property 'addEventListener' of undefined

### ISSUE THREAD

**Issue by averri** [aws/amazon-chime-sdk-js#461]
**Important:** Please attach INFO-level logs with timestamps to the report from *before* the session started up until the point at which the unexpected behavior occured. For multi-participant calls, attach a log file for each participant if possible.

**Meeting and attendee IDs:**
Please see the logs below.
```
2020-06-07T19:01:12.674Z POST /logs END
2020-06-07T19:01:31.184Z POST /join?title=1234&name=alex&region=eu-west-1 BEGIN
2020-06-07T19:01:37.643Z {
  "JoinInfo": {
    "Meeting": {
      "Meeting": {
        "MeetingId": "4cf6157d-df3a-46e2-adc2-e3a0ef2fef77",
        "ExternalMeetingId": "1234",
        "MediaPlacement": {
          "AudioHostUrl": "bfd463a327152f9a6a0bd4569ee2bf5a.k.m2.ew1.app.chime.aws:3478",
          "AudioFallbackUrl": "wss://haxrp.m2.ew1.app.chime.aws:443/calls/4cf6157d-df3a-46e2-adc2-e3a0ef2fef77",
          "ScreenDataUrl": "wss://bitpw.m2.ew1.app.chime.aws:443/v2/screen/4cf6157d-df3a-46e2-adc2-e3a0ef2fef77",
          "ScreenSharingUrl": "wss://bitpw.m2.ew1.app.chime.aws:443/v2/screen/4cf6157d-df3a-46e2-adc2-e3a0ef2fef77",
          "ScreenViewingUrl": "wss://bitpw.m2.ew1.app.chime.aws:443/ws/connect?passcode=null&viewer_uuid=null&X-BitHub-Call-Id=4cf6157d-df3a-46e2-adc2-e3a0ef2fef77",
          "SignalingUrl": "wss://signal.m2.ew1.app.chime.aws/control/4cf6157d-df3a-46e2-adc2-e3a0ef2fef77",
          "TurnControlUrl": "https://ccp.cp.ue1.app.chime.aws/v2/turn_sessions"
        },
        "MediaRegion": "eu-west-1"
      }
    },
    "Attendee": {
      "Attendee": {
        "ExternalUserId": "066f49bf#alex",
        "AttendeeId": "f04c760c-191c-4539-84c5-3f6846e95baa",
        "JoinToken": "ZjA0Yzc2MGMtMTkxYy00NTM5LTg0YzUtM2Y2ODQ2ZTk1YmFhOjE0OTYyOWRiLWNlMDMtNGY0My05ZjIyLWYxMDRlN2I5OTVlMA"
      }
    }
  }
}
2020-06-07T19:01:37.644Z POST /join?title=1234&name=alex&region=eu-west-1 END
2020-06-07T19:01:39.024Z POST /logs BEGIN
2020-06-07T19:01:39.024Z POST /logs END
2020-06-07T19:01:40.174Z POST /logs BEGIN
2020-06-07T19:01:40.174Z POST /logs END
```

**Timeline**
1. Considering the demo app provided at https://github.com/aws/amazon-chime-sdk-js/tree/master/demos/browser
2. Chechout the code and run the demo application with  `npm run start` on your own domain on internet (I have tested the demo at AWS EC2).
3. Access `http://server:port`, give a meeting id, user name, select location and join the meeting.

**Describe the bug**
It's not possible to connect to the meeting on the internet. The demo application fails with the message `Cannot read property 'addEventListener' of undefined`. I'm able to run the same demo application on my local network.

**Screenshots**
![image](https://user-images.githubusercontent.com/1898447/83975970-d821d480-a8ee-11ea-9968-e542d89cf617.png)

**Platform**
 - OS: Ubuntu 18
 - Browser:  Chrome
 - Browser Version: 80/81
 - Amazon Chime SDK GitHub Commit: 109dc75c2eb391a1fa97d73bea1f33bedea500ea

**Comment by RidipDe** [comment]
Duplicate issue : https://github.com/aws/amazon-chime-sdk-js/issues/456
Closing this issue
