### ISSUE TITLE
Retrieve meeting duration from backend

### ISSUE THREAD

**Issue by walfen** [aws/amazon-chime-sdk-js#462]
### What are you trying to do?

 I'm trying to retrive the duration of meetings from backend.

### How can the documentation be improved to help your use case?

*Is it possible to retrieve the duration of the meetings from the backend? Is it possible to be notified when a meeting is finished on backend side?*

### What documentation have you looked at so far?

README.md, Amazon Chime SDK Developer Guide and several video tutorials.

**Comment by JannikSt** [comment]
Hi @walfen 
events such as meeting start and meeting end can be retrieved using eventBridge: 
https://docs.aws.amazon.com/chime/latest/ag/automating-chime-with-cloudwatch-events.html

**Comment by simmkyu** [comment]
Thanks for your answer, @JannikSt. Yes, [Automating Amazon Chime with EventBridge](https://docs.aws.amazon.com/chime/latest/ag/automating-chime-with-cloudwatch-events.html#sdk-events) has examples of receiving SDK events in the backend. You might use the `chime:MeetingStarted` event and the `chime:MeetingEnded` event to track the life cycle of your meeting.

For testing, you can try out the serverless demo with the `--event-bridge` option.
- https://github.com/aws/amazon-chime-sdk-js/tree/master/demos/serverless

```
npm run deploy -- -r us-east-1 -b <my-bucket> -s <my-stack-name> -a meeting --event-bridge
```

You'll receive the SDK events in the following function (AWS Lambda function):
https://github.com/aws/amazon-chime-sdk-js/blob/master/demos/serverless/src/handlers.js#L141

**Comment by satyajit98300** [comment]
@walfen @simmkyu It would be great if u help me with it.
I am new to eventbridge. not able to understand from code. Please help me to understand how should i use event bridge track the meeting total duration

**Comment by abhimanusharma** [comment]
@simmkyu Is there any application of this serverless application? I don't see how one can implement this in live events happening in real time.
