### ISSUE TITLE
demo on angular 

### ISSUE THREAD

**Issue by mangalagiri** [aws/amazon-chime-sdk-js#466]
### What are you trying to do?

*For example: I'm trying to start a meeting session with audio.*

### How can the documentation be improved to help your use case?

*For example: Include a section on how to configure the meeting session.*

### What documentation have you looked at so far?

*For example: README.md, Amazon Chime SDK Developer Guide, etc.

**Comment by RidipDe** [comment]
Hope https://github.com/aws/amazon-chime-sdk-js/issues/226 help. Let us know otherwise

**Comment by mangalagiri** [comment]
I'm trying to start a meeting session with video call in angular.

i had  amazon chime account key's etc... Done example on node JS amazon chime and working fine.

Now the requirement with angular. 
  
I was struck at communication between service js and component and passing value(meetingResponse, attendeeResponse) in angular.

and which place amazon keys integration need to integrate in application.

please find below code
-------service Js file.

const AWS = require('aws-sdk');
const { v4: uuid } = require('uuid');
 
// You must use "us-east-1" as the region for Chime API and set the endpoint.
const chime = new AWS.Chime({ region: 'us-east-1' });
chime.endpoint = new AWS.Endpoint('https://service.chime.aws.amazon.com/console');
 
const meetingResponse = await chime.createMeeting({
  ClientRequestToken: uuid(),
  MediaRegion: 'us-west-2' // Specify the region in which to create the meeting.
}).promise();
 
const attendeeResponse = await chime.createAttendee({
  MeetingId: meetingResponse.Meeting.MeetingId,
  ExternalUserId: uuid() // Link the attendee to an identity managed by your application.
}).promise();



-----------------------------------------Component

import { Component, OnInit } from '@angular/core';
import {
  ConsoleLogger,
  DefaultDeviceController,
  DefaultMeetingSession,
  LogLevel,
  MeetingSessionConfiguration
} from 'amazon-chime-sdk-js';
 
const logger = new ConsoleLogger('MyLogger', LogLevel.INFO);
const deviceController = new DefaultDeviceController(logger); 
 
// You need responses from server-side Chime API. See below for details.
const meetingResponse =""; /* The response from the CreateMeeting API action */
const attendeeResponse =""; /* The response from the CreateAttendee or BatchCreateAttendee API action */
const configuration = new MeetingSessionConfiguration(meetingResponse, attendeeResponse);
 
// In the usage examples below, you will use this meetingSession object.
const meetingSession = new DefaultMeetingSession(
  configuration,
  logger,
  deviceController
);
@Component({
  selector: 'app-infosharevideocall',
  templateUrl: './infosharevideocall.component.html',
  styleUrls: ['./infosharevideocall.component.scss']
})
export class InfosharevideocallComponent implements OnInit {

  constructor() { }

  ngOnInit() {
  }

}

**Comment by mangalagiri** [comment]
By server js file code, will fixed it
