### ISSUE TITLE
Prevent attendee that already joined to join again from a different device

### ISSUE THREAD

**Issue by Estefyrf** [aws/amazon-chime-sdk-js#478]
### What are you trying to do?

I'm trying to prevent an attendee that already joined to join again from a different device and get a message in the second device to indicate the cause for not being able to join (Attendee already joined)

### How can the documentation be improved to help your use case?

I'm not sure if it is possible to achieve this behavior or is a feature that needs to be added, didn't find anything in the documentation about it.

### What documentation have you looked at so far?

README.md, Amazon Chime SDK API overview, etc.

**Comment by simmkyu** [comment]
No, Chime SDK doesn't prevent a new attendee from reusing the same join token. If you join a meeting using the same join token, SDK will stop a previous attendee using the token.

---

Here's an example.

1. In Device A, an attendee starts a meeting using the `CreateAttendee` response from your server application. Note that this response includes the join token.
2. In Device B, an attendee uses the same `CreateAttendee` response to start a meeting.
3. In Device A, [AudioVideoObserver.audioVideoDidStop](https://github.com/aws/amazon-chime-sdk-js/blob/dc98c59d65330cae6d789c12dc987ed46867ac75/src/audiovideoobserver/AudioVideoObserver.ts#L26) will be called with [`MeetingSessionStatusCode.AudioJoinedFromAnotherDevice`](https://github.com/aws/amazon-chime-sdk-js/blob/dc98c59d65330cae6d789c12dc987ed46867ac75/src/meetingsession/MeetingSessionStatusCode.ts#L18).

    ```
    import { MeetingSessionStatusCode } from 'amazon-chime-sdk-js';

    const observer = {
      audioVideoDidStop: sessionStatus => {
        const sessionStatusCode = sessionStatus.statusCode();
        if (sessionStatusCode === MeetingSessionStatusCode.AudioJoinedFromAnotherDevice) {
          // Called!
        }
      }
    };

    meetingSession.audioVideo.addObserver(observer);
    ```

**Comment by chipcop106** [comment]
> No, Chime SDK doesn't prevent a new attendee from reusing the same join token. However, a previous attendee who has been using the token will be removed from the meeting.
> 
> Here's an example.
> 
> 1. In Device A, an attendee starts a meeting using the `CreateAttendee` response from your server application. Note that this response includes the join token.
> 2. In Device B, an attendee uses the same `CreateAttendee` response to start a meeting.
> 3. In Device A, [AudioVideoObserver.audioVideoDidStop](https://github.com/aws/amazon-chime-sdk-js/blob/dc98c59d65330cae6d789c12dc987ed46867ac75/src/audiovideoobserver/AudioVideoObserver.ts#L26) will be called with [`MeetingSessionStatusCode.AudioJoinedFromAnotherDevice`](https://github.com/aws/amazon-chime-sdk-js/blob/dc98c59d65330cae6d789c12dc987ed46867ac75/src/meetingsession/MeetingSessionStatusCode.ts#L18).
>    ```
>    import { MeetingSessionStatusCode } from 'amazon-chime-sdk-js';
>    
>    const observer = {
>      audioVideoDidStop: sessionStatus => {
>        const sessionStatusCode = sessionStatus.statusCode();
>        if (sessionStatusCode === MeetingSessionStatusCode.AudioJoinedFromAnotherDevice) {
>          // Called!
>        }
>      }
>    };
>    
>    meetingSession.audioVideo.addObserver(observer);
>    ```

How to handle it using react-native-chime-sdk?

**Comment by MacDinhThanh** [comment]
> > No, Chime SDK doesn't prevent a new attendee from reusing the same join token. However, a previous attendee who has been using the token will be removed from the meeting.
> > Here's an example.
> > 
> > 1. In Device A, an attendee starts a meeting using the `CreateAttendee` response from your server application. Note that this response includes the join token.
> > 2. In Device B, an attendee uses the same `CreateAttendee` response to start a meeting.
> > 3. In Device A, [AudioVideoObserver.audioVideoDidStop](https://github.com/aws/amazon-chime-sdk-js/blob/dc98c59d65330cae6d789c12dc987ed46867ac75/src/audiovideoobserver/AudioVideoObserver.ts#L26) will be called with [`MeetingSessionStatusCode.AudioJoinedFromAnotherDevice`](https://github.com/aws/amazon-chime-sdk-js/blob/dc98c59d65330cae6d789c12dc987ed46867ac75/src/meetingsession/MeetingSessionStatusCode.ts#L18).
> >    ```
> >    import { MeetingSessionStatusCode } from 'amazon-chime-sdk-js';
> >    
> >    const observer = {
> >      audioVideoDidStop: sessionStatus => {
> >        const sessionStatusCode = sessionStatus.statusCode();
> >        if (sessionStatusCode === MeetingSessionStatusCode.AudioJoinedFromAnotherDevice) {
> >          // Called!
> >        }
> >      }
> >    };
> >    
> >    meetingSession.audioVideo.addObserver(observer);
> >    ```
> 
> How to handle it using react-native-chime-sdk?

Done
