### ISSUE TITLE
Video and audio not displaying in angular application 

### ISSUE THREAD

**Issue by mangalagiri** [aws/amazon-chime-sdk-js#482]
### What are you trying to do?
here is the html code and attached console screenshot
![No](https://user-images.githubusercontent.com/18577663/84706089-1156e600-af7a-11ea-9c34-01f7cf419844.jpg)

<video id="video-preview" style="width:100%; height: 500px"></video>
<audio id="audio-preview"></audio>

### How can the documentation be improved to help your use case?

*For example: Include a section on how to configure the meeting session.*

### What documentation have you looked at so far?

*For example: README.md, Amazon Chime SDK Developer Guide, etc.

**Comment by simmkyu** [comment]
This message indicates that the meeting has started.
`[INFO] SDK - transitioning from Connecting to Connected with FinishConnecting`

Please make sure to:
1. Choose audio and video devices
  https://github.com/aws/amazon-chime-sdk-js#device
2. Bind an audio element `<audio>`
  https://github.com/aws/amazon-chime-sdk-js#starting-a-session
3. Bind a video tile object to a video element `<video>`
  https://github.com/aws/amazon-chime-sdk-js#video

Also, ensure that `<audio>` and `<video>` in your Angular components are not removed from the website during the meeting session.
