### ISSUE TITLE
Demo Meeting App: AWS Authorization Failed

### ISSUE THREAD

**Issue by rzfortes** [aws/amazon-chime-sdk-js#487]
### What are you trying to do?

I'm trying to run the demo browser meeting/meeting v2 in local environment. I'm using Windows. 
Upon running the command, npm run start --app=meeting or npm run start --app=meetingV2, both app returns the error:

![image](https://user-images.githubusercontent.com/22534337/84842384-8cea8d00-b077-11ea-9355-1fd98f1d21b9.png)

### How can the documentation be improved to help your use case?

Can you please include a step-by-step section on how to setup the demo browser in local environment? Thank you

### What documentation have you looked at so far?

README.md, Amazon Chime SDK Developer Guide

**Comment by anuranduttaroy** [comment]
Since this is an authorization failure, it sounds like you may not have the AWS credentials set up in your local environment. Can you try configuring the correct AWS credentials and see if it works?

**Comment by HRK44** [comment]
I faced the same issue, credentials were correct but I needed to add Chime specific authorizations to the AWS user.

**Comment by araju57** [comment]
if credentials configured correct, restarting server file worked for me.
