### ISSUE TITLE
Issue related speaker  tile placement

### ISSUE THREAD

**Issue by SuhailBt** [aws/amazon-chime-sdk-js#488]
During Video call, the Speaker Tile is not scaling up to the size of the container.

Expectation is for the Speaker tile to fit the container size.

I tried to maximize using the DEMO code provided in GIT and the speaker tile is going out of the Laptop screen window.

Below are the methods I am using from demo code

  layoutVideoTilesActiveSpeaker(visibleTileIndices: number[], activeTileId: number): void {
    const tileArea = document.getElementById('tile-area') as HTMLDivElement;
    const width = tileArea.clientWidth;
    c

const height = tileArea.clientHeight;
    const widthToHeightAspectRatio = 16 / 9;
    const maximumRelativeHeightOfOthers = 0.3;
    const activeWidth = width;
    const activeHeight = width / widthToHeightAspectRatio;
    const othersCount = visibleTileIndices ? visibleTileIndices.length - 1 : 0;
    let othersWidth = width / othersCount;
    let othersHeight = width / widthToHeightAspectRatio;
    if (othersHeight / activeHeight > maximumRelativeHeightOfOthers) {
      othersHeight = activeHeight * maximumRelativeHeightOfOthers;
      othersWidth = othersHeight * widthToHeightAspectRatio;
    }
    if (othersCount === 0) {
      othersHeight = 0;
    }
    const totalHeight = activeHeight + othersHeight;
    const othersTotalWidth = othersWidth * othersCount;
    const othersXOffset = width / 2 - othersTotalWidth / 2;
    const activeYOffset = height / 2 - totalHeight / 2;
    const othersYOffset = activeYOffset + activeHeight;

    let othersIndex = 0;
    for (let i = 0; i < visibleTileIndices.length; i++) {
      const tileIndex = visibleTileIndices[i];
      const tileId = this.tileIndexToTileId[tileIndex];
      let x = 0,
        y = 0,
        w = 0,
        h = 0;
      if (tileId === activeTileId) {
        x = 0;
        y = activeYOffset;
        w = activeWidth;
        h = activeHeight;
      } else {
        x = othersXOffset + othersIndex * othersWidth;
        y = othersYOffset;
        w = othersWidth;
        h = othersHeight;
        othersIndex += 1;
      }
      this.updateTilePlacement(tileIndex, x, y, w, h);
    }
  }

  updateTilePlacement(tileIndex: number, x: number, y: number, w: number, h: number): void {
    const tile = document.getElementById(`tile-${tileIndex}`) as HTMLDivElement;
    if (this.isContentTile(tileIndex)) {
      tile.classList.remove('video-tile');
      tile.classList.add('content-share-tile');
    } else {
      tile.classList.remove('content-share-tile');
      tile.classList.add('video-tile');
    }
    const insetWidthSize = 4;
    const insetHeightSize = insetWidthSize / (16 / 9);
    tile.style.position = 'absolute';
    tile.style.left = `${x + insetWidthSize}px`;
    tile.style.top = `${y + insetHeightSize}px`;
    tile.style.width = `${w - insetWidthSize * 2}px`;
    tile.style.height = `${h - insetHeightSize * 2}px`;
    tile.style.margin = '0';
    tile.style.padding = '0';
    tile.style.visibility = 'visible';
    const video = document.getElementById(`video-${tileIndex}`) as HTMLDivElement;
    if (video && tileIndex != 16) {
      video.style.position = 'absolute';
      video.style.left = '0';
      video.style.top = '0';
      video.style.width = `${w}px`;
      video.style.height = `${h}px`;
      video.style.margin = '0';
      video.style.padding = '0';
      video.style.borderRadius = '8px';
    }
    const nameplate = document.getElementById(`nameplate-${tileIndex}`) as HTMLDivElement;
    const nameplateSize = 24;
    const nameplatePadding = 10;
    nameplate.style.position = 'absolute';
    nameplate.style.left = '0px';
    nameplate.style.top = `${h - nameplateSize - nameplatePadding}px`;
    nameplate.style.height = `${nameplateSize}px`;
    nameplate.style.width = `${w}px`;
    nameplate.style.margin = '0';
    nameplate.style.padding = '0';
    nameplate.style.paddingLeft = `${nameplatePadding}px`;
    nameplate.style.color = '#fff';
    nameplate.style.backgroundColor = 'rgba(0,0,0,0)';
    nameplate.style.textShadow = '0px 0px 5px black';
    nameplate.style.letterSpacing = '0.1em';
    nameplate.style.fontSize = `${nameplateSize - 11}px`;

    let button = document.getElementById(`video-pause-${tileIndex}`) as HTMLButtonElement;

    button.style.position = 'absolute';
    button.style.display = 'inline-block';
    button.style.right = '0px';
    button.style.top = `${h - nameplateSize - nameplatePadding}px`;
    button.style.height = `${nameplateSize}px`;
    button.style.margin = '0';
    button.style.padding = '0';
    button.style.border = 'none';
    button.style.paddingRight = `${nameplatePadding}px`;
    button.style.color = '#fff';
    button.style.backgroundColor = 'rgba(0,0,0,0)';
    button.style.textShadow = '0px 0px 5px black';
    button.style.letterSpacing = '0.1em';
    button.style.fontSize = `${nameplateSize - 11}px`;
  }

**Comment by davejlane** [comment]
Hello @SuhailBt,

It might be useful to get some more information from your project here. I see that you've used some of the demo code, but it will be really helpful to focus on the computed CSS for both your videoTile and the its' parent element. One of the things that is interesting is that `position: absolute` is being used, which will take the element out of the document flow and therefore ignore the parent elements' dimensions. The following CSS should work to fill any parent element with a child element. (The values being used for the parent element width and height are arbitrary; the child element will match these values):

```
.parent {
  width: 80vw;
  height: 100vh;
}

.child {
  height: 100%;
  width: 100%;
}
```

Can you get the computed values of your videoTile and parent element CSS? You should be able to get these values from your browsers developer tools. If you can post that information here we can have a better idea of your issue. Thanks!

**Comment by SuhailBt** [comment]
> .parent {
>   width: 80vw;
>   height: 100vh;
> }
> 
> .child {
>   height: 100%;
>   width: 100%;
> }

**Comment by SuhailBt** [comment]
> Hello @SuhailBt,
> 
> It might be useful to get some more information from your project here. I see that you've used some of the demo code, but it will be really helpful to focus on the computed CSS for both your videoTile and the its' parent element. One of the things that is interesting is that `position: absolute` is being used, which will take the element out of the document flow and therefore ignore the parent elements' dimensions. The following CSS should work to fill any parent element with a child element. (The values being used for the parent element width and height are arbitrary; the child element will match these values):
> 
> ```
> .parent {
>   width: 80vw;
>   height: 100vh;
> }
> 
> .child {
>   height: 100%;
>   width: 100%;
> }
> ```
> 
> Can you get the computed values of your videoTile and parent element CSS? You should be able to get these values from your browsers developer tools. If you can post that information here we can have a better idea of your issue. Thanks!

Hi  @davejlane 

Regarding my project, I am using bootstarp classes as col-9 and trying to fit the speaker video tile into it. Below I am sharibg the screenshot of my html code and the css
![Screenshot from 2020-07-07 17-11-30](https://user-images.githubusercontent.com/65166275/86777688-18ec4500-c077-11ea-9527-fc911faef543.png)
![Screenshot from 2020-07-07 17-11-01](https://user-images.githubusercontent.com/65166275/86777701-1d186280-c077-11ea-8844-46791f37ffcb.png)
![Screenshot from 2020-07-07 17-10-56](https://user-images.githubusercontent.com/65166275/86777718-20abe980-c077-11ea-95e6-99d75c404db3.png)


 that is being used.
This is the html code I am using to render my video tiles
 <div class="row">
        <div class="" style="" [ngClass]="{'col-10': showRoster === false,
        'col-9': showRoster === true}">
            <div id="tile-area" class="w-100 h-100">
                <div id="tile-0" style="display:none">
                    <video id="video-0" class="w-100 h-100"></video>
                    <div id="nameplate-0"></div>
                    <button id="video-pause-0">Pause</button>
                </div>
                <div id="tile-1" style="display:none">
                    <video id="video-1" class="w-100 h-100"></video>
                    <div id="nameplate-1"></div>
                    <button id="video-pause-1">Pause</button>
                </div>
     </div>
</div>

**Comment by kaaaren** [comment]
Hello @SuhailBt,
Have you tried what @davejlane advised earlier to set the positions of a parent element with its child element? You can also try set the video element with such style:

```
{
position: absolute;
top: 0;
left: 0;
bottom: 0;
right: 0;
}
```

Thanks!

**Comment by SuhailBt** [comment]
@kaaaren: Thanks for your response. Will get back to you regarding the working status ASAP.

**Comment by SuhailBt** [comment]
Hi @kaaaren 
I tried the above mention solution but unfortunately it is not working for me. I believe the problem is when we are applying css dynamically in updateTilePlacement() method. You see that is applied for all the videos tiles of the  attendees that get added to the meeting and video cells are updated accordingly. When I am trying to use 
    const width = tileArea.clientWidth;
    const height = tileArea.clientHeight;
The top of speaker tile is going out of the viewport. So i guess we need some changes in updateTilePlacement() so that all the tiles for all the attendees that join the meeting would get updated accordingly.

**Comment by SuhailBt** [comment]
const height = tileArea.clientHeight;      output for this is 0 (zero) in layoutVideoTilesActiveSpeaker() method. I believe that is causing the top for tile-area to be negative. Not sure why is it 0 (zero). Need help with that

**Comment by kaaaren** [comment]
Hi, can you provide more detail on how you test it? From the screenshot it looks like the local video tile is going out from the window and there is no other active video tiles. I tried to apply your code snippet and css style from the screenshots you attached above to the demo app meetingV2 and I don't have issue viewing the local video tile. 

For `const height = tileArea.clientHeight;` and height is 0. It'll be helpful to check the CSS for both the videoTile and the its parent element. Can you check the inner height of tileArea and its parent height? Note that the height of `tile-area` is `h-100` and set to auto `height: auto !important;` in StyleV2.scss file.

We have this [FAQ answer](https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html#how-can-i-create-a-video-tile-layout-for-my-application) for setting video tile layout that can be helpful to set the video tile in your application. We also have some other demo apps built on top of Chime JS SDK that use the CSS approach for styling that can be helpful, check out the [classroom demo](https://github.com/aws-samples/amazon-chime-sdk-classroom-demo) and [React meeting demo](https://github.com/aws/amazon-chime-sdk-component-library-react/tree/master/demo/meeting).

**Comment by p-foucht** [comment]
Hi SuhailBt,

We've changed the implementation to use CSS Grid instead of JS for laying out tiles. They now have responsive aspect ratios so that videos take up more of the parent's space. If needed, you can adjust the CSS as needed to get the design/layout you're after
