### ISSUE TITLE
Listener when chime has ended the session 

### ISSUE THREAD

**Issue by gkio** [aws/amazon-chime-sdk-js#491]
Hello i am interested is there any option how to listen when chime session has been ended to run a callback i dont want to use it on client side
```
import { MeetingSessionStatusCode } from 'amazon-chime-sdk-js';

const observer = {
  audioVideoDidStop: sessionStatus => {
    const sessionStatusCode = sessionStatus.statusCode();
    if (sessionStatusCode === MeetingSessionStatusCode.AudioCallEnded) {
      /*
        - You (or someone else) have called the DeleteMeeting API action in your server application.
        - No audio connections are present in the meeting for more than five minutes.
        - Fewer than two audio connections are present in the meeting for more than 30 minutes.
        - Screen share viewer connections are inactive for more than 30 minutes.
        - The meeting time exceeds 24 hours.
        See https://docs.aws.amazon.com/chime/latest/dg/mtgs-sdk-mtgs.html for details.
      */
      console.log('The session has ended');
    } else {
      console.log('Stopped with a session status code: ', sessionStatusCode);
    }
  }
};

meetingSession.audioVideo.addObserver(observer);
```

something like 
```
createMeeting({}, function onEnd() => {
console.log('Meeting has been ended')
})
```

**Comment by slootjes** [comment]
You could use EventBridge for this: https://docs.aws.amazon.com/chime/latest/ag/automating-chime-with-cloudwatch-events.html#events-sdk

**Comment by anuranduttaroy** [comment]
Yes, [Automating Amazon Chime with EventBridge](https://docs.aws.amazon.com/chime/latest/ag/automating-chime-with-cloudwatch-events.html#sdk-events) has examples of receiving SDK events in the backend. You might use the `chime:MeetingEnded` event to track the life cycle of your meeting.

For testing, you can try out the serverless demo with the `--event-bridge` option.

* https://github.com/aws/amazon-chime-sdk-js/tree/master/demos/serverless
```
npm run deploy -- -r us-east-1 -b <my-bucket> -s <my-stack-name> -a meeting --event-bridge
```

You'll receive the SDK events in the following function (AWS Lambda function):
https://github.com/aws/amazon-chime-sdk-js/blob/master/demos/serverless/src/handlers.js#L141
