### ISSUE TITLE
Audio not working | Android Chrome

### ISSUE THREAD

**Issue by gsig123** [aws/amazon-chime-sdk-js#497]
**Meeting and attendee IDs:**
NA

**Timeline**

- Attendee A creates a meeting from a desktop browser
- Attendee A joins the meeting
- Attendee B joins a meeting on an Android device in Google Chrome
- Attendee A can't hear anything from Attendee B. Attendee B can't hear any audio from Attendee A. 

**Describe the bug**
Audio (input / output) doesn't work on an Android device in Google Chrome. The user is asked for the microphone permission and the device selection seems to succeed.

**Screenshots**
NA

**Platform**
 - OS: Android
 - Browser: Google Chrome
 - Browser Version: NA
 - Amazon Chime SDK GitHub Commit: Version 1.9

**Comment by vidya-mohan** [comment]
@gsig123 what is the version of Chrome being used (would help if you can share the device)? Are there any logs you can share?

Can you reproduce this in our demo application - https://github.com/aws/amazon-chime-sdk-js/tree/master/demos/browser?
