### ISSUE TITLE
Client join via Firefox 68  could not view any videos on demo app

### ISSUE THREAD

**Issue by XHatan** [aws/amazon-chime-sdk-js#499]
**Important:** Please attach INFO-level logs with timestamps to the report from *before* the session started up until the point at which the unexpected behavior occured. For multi-participant calls, attach a log file for each participant if possible.

**Meeting and attendee IDs:**
List the meeting and attendee IDs that the attached logs apply to.

Meeting ID: b74f2b72-bf79-434b-bd52-998b0d34bfc1 
Attendee ID: be329e22-3492-46ce-b055-bbd37d96788d (this attendee could not see any videos in a three-video meeting)

**Timeline**
Outline the main actions the user performed and when:

* <timestamp> <action>
* <timestamp> <action>

**Describe the bug**
Describe the bug and the timestamp at which it happened relative to the timestamp in the log file.

**Screenshots**
If applicable, add screenshots to help explain the problem.

**Platform**
 - OS:  OSX 
 - Browser: Firefox 
 - Browser Version:  68
 - Amazon Chime SDK GitHub Commit:  
https://github.com/aws/amazon-chime-sdk-js/commit/f071010f0fc2d7ac11c0fdcd6ef6ab451183c167

**Comment by vidya-mohan** [comment]
Mitigation is to upgrade to a recent version of FF

**Comment by cgandhi22** [comment]
It is happening with FF 68.0esr

**Comment by XHatan** [comment]
A fix has been merged, the issue is due to multi-codec support (VP8 and H264) we pushed out in server 
but for reference https://bugzilla.mozilla.org/show_bug.cgi?id=1333879 Firefox <69 does not handle multi-codec support, 
the workaround https://github.com/aws/amazon-chime-sdk-js/pull/501 solves the problem. @vidya-mohan we should probably document this
