### ISSUE TITLE
Stopping video preview also makes local video tile black

### ISSUE THREAD

**Issue by rlebosse** [aws/amazon-chime-sdk-js#502]
When I call `audioVideo.stopVideoPreviewForVideoInput(videoPreviewEl)`, it stops the video preview but also the "real" local video.

* In my DOM, there are 2 `<video>` elements : one for displaying my local video (up and running thanks to `audioVideo.startLocalVideoTile()` and `audioVideo.bindVideoElement(videoLocalTileId, videoLocalEl)`) and one for the video preview (in order to be able to pick the video settings before)
* When I call `audioVideo.startVideoPreviewForVideoInput(videoPreviewEl)` everything is fine, I have my 2 `<video>` elements (**videoPreviewEl** and **videoLocalEl**) working
* But as soon as I call `audioVideo.stopVideoPreviewForVideoInput(videoPreviewEl)`, the **videoLocalEl** goes black and stops displaying the local video.

**Platform**
 - OS: macOS 10.15.5
 - Browser: Google Chrome
 - Browser Version: 83.0.4103.106
 - Amazon Chime SDK GitHub Commit: version 1.9.0

**Comment by anuranduttaroy** [comment]
Can you provide some more information about the issue.

* Please attach **INFO-level logs** with timestamps to the report from *before* the session started up until the point at which the unexpected behavior occurred. For multi-participant calls, attach a log file for each participant if possible.

* **Meeting and attendee IDs**: List the meeting and attendee IDs that the attached logs apply to.

* **Screenshots**: If applicable, add screenshots to help explain the problem.

**Comment by rlebosse** [comment]
I have made a branch showing up the problem in the browser demo.

In the session in progress page, I added :
* A `<video>` element that is used to display video preview
* A "preview on" button that is used to start video preview in the above `<video>` element
* A "preview off" button that is used to stop video preview in the above `<video>` element

You can find the code here :
* The branch : https://github.com/rlebosse/amazon-chime-sdk-js/tree/turn-off-preview-during-session
* There is just one commit : https://github.com/rlebosse/amazon-chime-sdk-js/commit/2e889140a1ef07ec846dcd6dbdae7f41cb6bc87b

To reproduce the problem :
* Start the session normally

![Capture d’écran 2020-06-25 à 11 13 13](https://user-images.githubusercontent.com/2794137/85691526-de78c480-b6d4-11ea-9476-031028b3103c.png)

* Toggle on Camera

![Capture d’écran 2020-06-25 à 11 13 42](https://user-images.githubusercontent.com/2794137/85691592-ef293a80-b6d4-11ea-9f49-5f6bf3e26a04.png)

* Then click on the button "preview on" (local video and video preview are both working)

![Capture d’écran 2020-06-25 à 11 14 04](https://user-images.githubusercontent.com/2794137/85691657-fd775680-b6d4-11ea-9003-5281d44e3db6.png)

* Then click on the button "preview off" (local video goes black)

![Capture d’écran 2020-06-25 à 11 14 29](https://user-images.githubusercontent.com/2794137/85691714-0a944580-b6d5-11ea-89db-caae0dace34e.png)

**Comment by rlebosse** [comment]
My use case is that the session is started with the camera off, but I want to see what the video preview will be before I start the camera.

**Comment by ltrung** [comment]
@rlebosse, this happens because stopVideoPreviewForVideoInput will terminate the current active camera stream https://github.com/aws/amazon-chime-sdk-js/blob/master/src/devicecontroller/DefaultDeviceController.ts#L172. If this is needed for your use case, one way to workaround this is to use 2 different DefaultDeviceController with one is specific for preview.

**Comment by rlebosse** [comment]
The workaround works great, thanks @ltrung
