### ISSUE TITLE
Request to update script for SingleJS

### ISSUE THREAD

**Issue by 76kennyboss** [aws/amazon-chime-sdk-js#508]
### What are you trying to do?
I'm using the SingleJS demo to generate a single JS that can be embedded right into my application.
Current version doesn't support the recent H264 fallback.

**Comment by ltrung** [comment]
Are you referring to this commit https://github.com/aws/amazon-chime-sdk-js/commit/8e5802c04031ac62a2c5c5fe75af5bb4ffbf12d0 ? If so, it is already available in the latest NPM push 1.10.0
