### ISSUE TITLE
Need information : meaning of "present audio connection" + can we join a session with audio muted ?

### ISSUE THREAD

**Issue by rlebosse** [aws/amazon-chime-sdk-js#511]
I ran into the conditions that make a Meeting to be closed automatically :

![Image Pasted at 2020-6-24 18-05](https://user-images.githubusercontent.com/2794137/85695868-b9865080-b6d8-11ea-8d11-330cca1c763c.png)

I was wondering what was the real sense of a **"present audio connection"** ?

If I join a Meeting, start the session (after binding my <audio> element in the DOM) and then mute the local audio (with `audioVideo.realtimeMuteLocalAudio()`, do I still count as a "present audio connection" ?

Moreover, before starting the session, is it possible to mute myself before in order to join the session as muted (and then be able to toggle unmute/muted when I want it) ?

Thanks in advance for you answers and your great work !

**Comment by ltrung** [comment]
A "present audio connection" is referring to an attendee with an audio connection so you can join the meeting and mute your local audio and it still counts as a "present audio connection.
You should be able to mute your self before starting the session and should still be able to join a meeting and receive attendee presence event.

**Comment by rlebosse** [comment]
Thank you for these informations @ltrung !
