### ISSUE TITLE
realtimeSetCanUnmuteLocalAudio allows unmuting for attendees

### ISSUE THREAD

**Issue by prashanthacharyam** [aws/amazon-chime-sdk-js#512]
**Describe the bug**
Calling realtimeSetCanUnmuteLocalAudio only disallows unmuting on the caller instance. Other attendees can mute/unmute . I am not sure if this is the intended behaviour.

**Platform**
 - OS: mac os
 - Browser: Chrome
 - Amazon Chime SDK GitHub Commit: 1.10.0

**Comment by ltrung** [comment]
Yes this is the intended behavior. We currently do not support remote attendees. However, you can use [Chime SDK Data Messages](https://aws.github.io/amazon-chime-sdk-js/modules/apioverview.html#9-send-and-receive-data-messages-optional) to send a message containing the attendee or attendees that should mute, and clients can mute themselves when they receive those messages.
