### ISSUE TITLE
Unable to switch audio input using Firefox

### ISSUE THREAD

**Issue by johanderuijter** [aws/amazon-chime-sdk-js#524]
**Meeting and attendee IDs:**
MeetingId: fc4b8560-98a2-4b58-8355-1709028d5e32
AttendeeId: 8fa32a34-c6ea-4324-9ee5-e53772e9564c

**Timeline**
Outline the main actions the user performed and when:

* 2020-06-29T14:34:11.349Z Join meeting
* 2020-06-29T14:34:21.503Z Switch audio input

**Describe the bug**
It is no longer possible to change audio input using firefox. It gives an error along the lines of `[ERROR] SDK - failed to get audio device for constraints {...}: Concurrent mic process limit.` (see logs attached below for full error)

This was tested using the browser demo present in this repository using the current master(`4c1ea4ad3ff17bfcea346b13327074c306abdaa4`) and going back using tagged commits. The earliest tag where this no longer worked appears to be `1.8.0`. It starts working again in `1.7.0`.

**Platform**
 - OS: `MacOs 10.15.5`
 - Browser: `Firefox Developer Edition`
 - Browser Version: `78.0b9 (64-bit)`
 - Amazon Chime SDK GitHub Commit: `4c1ea4ad3ff17bfcea346b13327074c306abdaa4` (current master)

**Logs**
[chime-sdk-log-master.txt](https://github.com/aws/amazon-chime-sdk-js/files/4846139/chime-sdk-log-master.txt)

**Comment by ltrung** [comment]
This issue should have been fixed by #527
