### ISSUE TITLE
Content sharing is being received by the sharer

### ISSUE THREAD

**Issue by XHatan** [aws/amazon-chime-sdk-js#526]
**Important:** Please attach INFO-level logs with timestamps to the report from *before* the session started up until the point at which the unexpected behavior occured. For multi-participant calls, attach a log file for each participant if possible.

**Meeting and attendee IDs:**
List the meeting and attendee IDs that the attached logs apply to.

Did not have a specific meeting/attendee id as this is reproducible on demo 

**Timeline**
Outline the main actions the user performed and when:

* <timestamp> <action>
* <timestamp> <action>

**Describe the bug**
Describe the bug and the timestamp at which it happened relative to the timestamp in the log file.

Content sharing is echoed back to the sharer. We should filter out stream in DefaultVideoStreamIndex 

**Screenshots**
If applicable, add screenshots to help explain the problem.

**Platform**
 - OS: 
 - Browser: 
 - Browser Version: 
 - Amazon Chime SDK GitHub Commit:

**Comment by michielvv** [comment]
Is this the reason why the presenter can no longer see a preview of what he is sharing?   I thought it was quite useful to be able to see if you are actually sharing what you intended to share.
