### ISSUE TITLE
Cannot add tags to a meeting

### ISSUE THREAD

**Issue by bangersandflash** [aws/amazon-chime-sdk-js#532]
I can't seem to add tags to a meeting either when creating it or once it has been created.

If I pass the Tags parameter to chime.createMeeting if throws the following error:
_UnexpectedParameter: Unexpected key 'Tags' found in params_

If I try to add tags after the meeting has been created like this:
```
let tagParams = {
        MeetingId:meeting.Meeting.MeetingId,
        Tags:[
            {
                Key:"foo",
                Value:"bar"
            }
        ]
    }
    await chime.tagMeeting(tagParams).promise()
```

It results in this error:
```
{
  "errorType": "TypeError",
  "errorMessage": "chime.tagMeeting is not a function",
  "trace": [
    "TypeError: chime.tagMeeting is not a function",
    "    at Runtime.exports.handler (/var/task/index.js:36:17)"
  ]
}
```

I'm calling this from a lambda function using Nodejs 12.x and I can successfully call other methods like createMeeting and listAttendees. It's just tagging that seems to be an issue. Calling listTags throws a similar TypeError. Any ideas?

**Comment by ltrung** [comment]
What is your aws sdk version? It seems to be out of date.

**Comment by bangersandflash** [comment]
Thanks @ltrung 

I'm using the aws-sdk that is included by default with lambda as I assumed this is the latest version. Is there a way to specifically require the latest version of aws-sdk in lambda?

Below is my lambda code:
```
const AWS = require('aws-sdk');

const chime = new AWS.Chime(
    {
        region: 'us-east-1',
        accessKeyId: 'xxx,
        secretAccessKey: 'xxx'
    }
);
chime.endpoint = new AWS.Endpoint('https://service.chime.aws.amazon.com/console');


exports.handler = async (event) => {
    let token = "_" + String(new Date().getTime())
   
    let meeting = await chime.createMeeting({
                ClientRequestToken: token
            }).promise();
    
    let tagParams = {
        MeetingId:meeting.Meeting.MeetingId,
        Tags:[
            {
                Key:"foo",
                Value:"bar"
            }
        ]
    }
    
    await chime.tagMeeting(tagParams).promise()
    
    
    console.log(meeting)
    let tags = await chime.listTags({MeetingId:meeting.Meeting.MeetingId}).promise();
    console.log("tags:", tags)


    const response = {
        statusCode: 200,
        body: JSON.stringify(meeting)
    };
    return response;
};
```

**Comment by bangersandflash** [comment]
I believe this issue sits with the aws-sdk, not the amazon-chime-sdk-js so I've posted an issue there instead.
https://github.com/aws/aws-sdk-js/issues/3334
