### ISSUE TITLE
Two different users from a meeting session have the same tileId

### ISSUE THREAD

**Issue by oluwajuwon** [aws/amazon-chime-sdk-js#533]
### What are you trying to do?

I'm building a video conferencing app with ReactJs and I'm trying to display the videos of the different users in the meeting.

I've been able to successfully bind and display just the `local attendee`, but I noticed that when I start the session for a new `remote attendee` it either doesn't show the current attendee on the `remote attendee's` page or it doesn't show both users. 

Also when i log the `tileState` on both ends, I notice that both users have the same `tileId`, isn't the SDK somehow handling the distribution of the `tileId` for attendees of a meeting session?

### How can the documentation be improved to help your use case?

Include a detailed section on how the video tile states are updated, and how the SDK helps to handle the updates.
Include an explanation to the methods used in building with the SDK, many fo the methods don't have descriptions such 
- bindVideoElement : the `tileId` passed to it, can it be any number?
- addObserver: what exactly does this do?

and a lot more methods

### What documentation have you looked at so far?

- README.md
- Amazon Chime SDK Developer Guide
- The interfaces document

**Comment by ltrung** [comment]
Hi, did you try to use startLocalVideoTile to start the video for attendee? Then you can bindVideoElement inside videoTileDidUpdate as show in the meeting demo https://github.com/aws/amazon-chime-sdk-js/blob/master/demos/browser/app/meetingV2/meetingV2.ts#L1360

addObserver is to receive audio and video events. For example, audioVideoDidStart event let you know when the audio-video session finishes connecting. You can find more details [here](https://aws.github.io/amazon-chime-sdk-js/modules/apioverview.html)

**Comment by oluwajuwon** [comment]
Hi, I did that and i can see the local user, I'm also using the demo as reference. Although when I join session with another user, I can see the previous user that joined, but i can't see the new attendee, and I noticed that they have the same `tileId`. Also, when I'm binding the element with the `bindVideoElement`, can i use a random number or i have to use the tileId generated by the `VideoTileState`?

**Comment by aburnson** [comment]
The `tileId` is assigned by the SDK, so you don't need to create it yourself, and you should use the `tileId` from the `VideoTileState` from the `videoTileDidUpdate` callback. (startLocalVideoTile also returns a `tileId` as well.) Are you seeing that the local tile and remote tile both have the same `tileId`?

**Comment by oluwajuwon** [comment]
So I re-implemented it based on what you @aburnson said about the SDK assigning the `tileIds`, so I literally gave the SDK full control to handle the manipulation of the video tiles. The fault was from my end because I wasn't handling the display of the videos properly in the `videoTileDidUpdate` callback. It works fine now.

Although, I noticed something else, when I trigger `stopLocalVideoTile`, it stops it quite alright, but when i trigger `startLocalVideoTile`, the video doesn't still turn up until I trigger `stopLocalVideoTile` and `startLocalVideoTile` one more time, then the video shows up. Is `stopLocalVideoTile` an asynchronous method?

**Comment by vidya-mohan** [comment]
stopLocalVideoTile is not an async function as it turns off sending the local video stream immediately. However the videoTileDidUpdate will come back with a notification only after the round trip to the server is done (with VideoTileState.active as false)

Hope that helps!
