### ISSUE TITLE
AudioContext release or close

### ISSUE THREAD

**Issue by bizready** [aws/amazon-chime-sdk-js#537]
I am getting the following errors in log in to the Android environment.

[ERROR] MyLogger - connection failed with status code: TaskFailed
[ERROR] MyLogger - failed to get audio device for constraints null: Failed to construct 'AudioContext': The number of hardware contexts provided (6) is greater than or equal to the maximum bound (6).
[ERROR] MyLogger - unable to acquire audio device

Looks like I need to release or close AudioContext at the end.

What method or function I should call as I do not access 'AudioContext' directly in the code?

**Platform**
 - OS:  Android

**Comment by aburnson** [comment]
Would it be possible to provide INFO-level logs for the whole session as well as the browser version and device where you experience this issue (particularly interested in the logs that start with "API/")? It sounds like there may be some WebAudio contexts that are leaking and this device/browser has a hard cap on the number of contexts that can be used simultaneously.

**Comment by simmkyu** [comment]
We pushed https://github.com/aws/amazon-chime-sdk-js/pull/563 to use a single instance of AudioContext per browser tab. The next version of "amazon-chime-sdk-js" in NPM will include this fix (1.12.0).

Some browsers and particular versions have an implementation-defined maximum number of AudioContexts. Before #563, you could reproduce the bug by choosing the `null` device multiple times. After #563, Chime SDK is reusing the AudioContext object throughout the session.
