### ISSUE TITLE
iOS Safari. Unable to get audio output device 

### ISSUE THREAD

**Issue by 76kennyboss** [aws/amazon-chime-sdk-js#544]
So I read from https://aws.amazon.com/about-aws/whats-new/2020/06/amazon-chime-sdk-supports-audio-and-video-calling-from-mobile-browsers/ that the Javascript SDK now officially supports iOS Safari.

I followed the instructions on SingleJS Demo page. First changing the version for "amazon-chime-sdk-js" in package.json from `^1.0.0 ` to `^1.11.0`, and then `npm i rollup` to add the rollup dependency, finally running `npm run bundle` to build the 2 files, (.js and .js.map)

I am able to get audio and video to-fro from desktop to desktop with no hitch.

But when connecting from iPhone to desktop, I am unable to get audio out on iPhone Safari (iPhone SE, and iPhone 8 both running iOS13.5.1). The other video and audio streams works ok.

Below is my code to initialise the devices (audio in/out and video in)
`

      var audioInputDevices= await instance.meetingSession.audioVideo.listAudioInputDevices();
      if(audioInputDevices.length== 0) { console.log("AUDIO INPUT NOT AVAILABLE"); }
      else {
        var audioInputDeviceInfo= audioInputDevices[0];
        await instance.meetingSession.audioVideo.chooseAudioInputDevice(audioInputDeviceInfo.deviceId);
      }
      
      var audioOutputDevices= await instance.meetingSession.audioVideo.listAudioOutputDevices();
      if(audioOutputDevices.length== 0) { console.log("AUDIO OUTPUT NOT AVAILABLE"); }
      else { 
        var audioOutputDeviceInfo= audioOutputDevices[0];
        await instance.meetingSession.audioVideo.chooseAudioOutputDevice(audioOutputDeviceInfo.deviceId);
        instance.meetingSession.audioVideo.bindAudioElement(document.getElementById("audioOutput"));
      }

      var videoInputDevices= await instance.meetingSession.audioVideo.listVideoInputDevices();
      if(videoInputDevices.length== 0) { console.log("VIDEO INPUT NOT AVAILABLE"); }
      else {
        var videoInputDeviceInfo= videoInputDevices[0];
        await instance.meetingSession.audioVideo.chooseVideoInputDevice(videoInputDeviceInfo.deviceId);
      }
`

But I am always getting the "AUDIO OUTPUT NOT AVAILABLE" for iPhone devices.
Am I missing anything?

**Comment by RidipDe** [comment]
Can you please confirm which browser on your desktop you used to test the app on?
Safari on MAC as well as iOS has a know limitation which prevents us from listing the audio output devices

https://github.com/aws/amazon-chime-sdk-js/blob/master/guides/06_FAQs.md#i-am-unable-to-select-audio-output-device-in-some-browsers-is-this-a-known-issue

**Comment by 76kennyboss** [comment]
Hello RidipDe, 

Am unable to get audio out on iPhone for the following combinations:
1. Chrome on Desktop connecting to iPhone Javascript
2. iPhone ObjC SDK connecting to iPhone Javascript

**Comment by 76kennyboss** [comment]
Strangely, I think I was able to get audio out from iPhone Javascript a couple of weeks back.
iPhone ObjC SDK <> iPhone Javascript.
Am not sure what changed.

**Comment by RidipDe** [comment]
Hi @76kennyboss 

> 1. Chrome on Desktop connecting to iPhone Javascript
Do you mean that you have an active meeting session with one attendee on a desktop chrome browser and the other attendee joined from the iPhone Safari?

> 2. iPhone ObjC SDK connecting to iPhone Javascript
Do you mean that you have an active meeting session with both attendees joining from the different iPhone Safari browsers?

**Comment by RidipDe** [comment]
> Strangely, I think I was able to get audio out from iPhone Javascript a couple of weeks back.
Were you running it on Safari or other browsers like Chrome/Firefox/Opera on your iPhone when you were able to list the audio output devices ?

**Comment by 76kennyboss** [comment]
> `Chrome on Desktop connecting to iPhone Javascript`

> Do you mean that you have an active meeting session with one attendee on a desktop chrome browser and the other attendee joined from the iPhone Safari?

iPhone Safari first, then Desktop Chrome browser joined subsequently

> `iPhone ObjC SDK connecting to iPhone Javascript`

> Do you mean that you have an active meeting session with both attendees joining from the different iPhone Safari browsers?

iPhone Safari first, then iPhone ObjC SDK joined in subsequently

**Comment by 76kennyboss** [comment]
> `Strangely, I think I was able to get audio out from iPhone Javascript a couple of weeks back.`

> Were you running it on Safari or other browsers like Chrome/Firefox/Opera on your iPhone when you were able to list the audio output devices ?

Was running it on iPhone Safari. Again iPhone Safari first, then iPhone ObjC SDK joined in subsequently. Audio and Video works both ways a couple of weeks back. Not sure what changed. I will reload my old codes and do an investigation

**Comment by 76kennyboss** [comment]
I am sorry. Error originates from my own codes. I am able to get audio output from iOS Javascript on the old codes, even though I am still getting "**AUDIO OUTPUT NOT AVAILABLE**" .

**Comment by 76kennyboss** [comment]
```
var audioOutputDevices= await instance.meetingSession.audioVideo.listAudioOutputDevices();
if(audioOutputDevices.length== 0) { console.log("AUDIO OUTPUT NOT AVAILABLE"); }
else { 
    var audioOutputDeviceInfo= audioOutputDevices[0];
    await instance.meetingSession.audioVideo.chooseAudioOutputDevice(audioOutputDeviceInfo.deviceId);
  }
instance.meetingSession.audioVideo.bindAudioElement(document.getElementById("audioOutput"));
```
