### ISSUE TITLE
After reconnect video tile blank

### ISSUE THREAD

**Issue by rohit0337** [aws/amazon-chime-sdk-js#554]
hello 

user A joins the meeting
User B join the meeting
both share video and B also share screen
Case 1.User B lost the connection after re connection user B can not able so see user A video only blank tile  
Case 2. Screen share screen is freeze for user A and after User B Re connection Screen also freeze
case 3 . If user B Refresh the meeting url and rejoin User A has now two tiles with user B name in one he can see users video other tile is blank

Os->Ubuntu
browser->chrome

**Comment by vidya-mohan** [comment]
@rohit0337 there is not much information on this issue. Please use our bug template https://github.com/aws/amazon-chime-sdk-js/issues/new?assignees=&labels=bug&template=bug-report.md&title= . You can also search existing issues to see if someone has reported it
