### ISSUE TITLE
Video stream tiles do not update for attendee with low bandwidth internet

### ISSUE THREAD

**Issue by ankit-maheshwari** [aws/amazon-chime-sdk-js#562]
**Describe the bug**
If an attendee is connected over low bandwidth, the video tiles of remote attendees multiply or do not refresh when the attendee connection with low bandwidth refreshed.

**Platform**
 - OS: Windows/ Mac
 - Browser: Chrome/ Firefox
 - Browser Version: Latest
 - Amazon Chime SDK GitHub Commit: 1.7.0

**Comment by simmkyu** [comment]
I added a comment in https://github.com/aws/amazon-chime-sdk-js/issues/561#issuecomment-660388731 for repro steps. Two issues happen due to the same cause: poor Internet connection. I'll close this issue and track it in #561. Please feel free to reopen if you have different repro cases.
