### ISSUE TITLE
Credential scope error when using a different MediaRegion

### ISSUE THREAD

**Issue by SamKosky** [aws/amazon-chime-sdk-js#567]
**Describe the bug**
I'm attempting to run the [serverless](https://github.com/aws/amazon-chime-sdk-js/tree/master/demos/serverless) demo in the `ap-southeast-2` region. Whenever I try to create a meeting from a client, the `ChimeSdkJoinLambda` returns the errorMessage `Credential should be scoped to a valid region, not 'ap-southeast-2'.`

It's my understanding that the Chime SDK should now [support multiple regions](https://docs.aws.amazon.com/chime/latest/dg/chime-sdk-meetings-regions.html). All of my resources have been created in the `ap-southeast-2` region, so I feel like the Chime service is not issuing credentials according to the region specified when instantiating the instance. I would like to be able to specify a different region (e.g. `new AWS.Chime({ region: 'ap-southeast-2' })`) but it doesn't appear to be supported.

**Lambda CloudWatch Logs**
The request for creating a new meeting:
```
2020-07-19T07:13:39.696Z	45820e76-8d75-4f9e-9f99-67327db86ccc	INFO	Creating new meeting: 
{
    "ClientRequestToken": "aa9d0089-fdb6-48a1-891d-57cff1e8160c",
    "MediaRegion": "ap-southeast-2",
    "NotificationsConfiguration": {
        "SqsQueueArn": "arn:aws:sqs:ap-southeast-2:XXXXXXXXXXXX:chime-demo-MeetingNotificationsQueue-1APD2E35U8ATT"
    },
    "ExternalMeetingId": "test"
}
```
And the exception returned from calling `chime.createMeeting(request)`:
```
2020-07-19T07:13:40.761Z	45820e76-8d75-4f9e-9f99-67327db86ccc	ERROR	Invoke Error 	
{
    "errorType": "InvalidSignatureException",
    "errorMessage": "Credential should be scoped to a valid region, not 'ap-southeast-2'. ",
    "code": "InvalidSignatureException",
    "message": "Credential should be scoped to a valid region, not 'ap-southeast-2'. ",
    "time": "2020-07-19T07:13:40.760Z",
    "requestId": "41dec8ee-8a0b-4f6e-bda8-aa83dbe72f2e",
    "statusCode": 403,
    "retryable": false,
    "retryDelay": 21.13688713260815,
    "stack": [
        "InvalidSignatureException: Credential should be scoped to a valid region, not 'ap-southeast-2'. ",
        "    at Object.extractError (/var/task/aws-sdk/lib/protocol/json.js:51:27)",
        "    at Request.extractError (/var/task/aws-sdk/lib/protocol/rest_json.js:55:8)",
        "    at Request.callListeners (/var/task/aws-sdk/lib/sequential_executor.js:106:20)",
        "    at Request.emit (/var/task/aws-sdk/lib/sequential_executor.js:78:10)",
        "    at Request.emit (/var/task/aws-sdk/lib/request.js:683:14)",
        "    at Request.transition (/var/task/aws-sdk/lib/request.js:22:10)",
        "    at AcceptorStateMachine.runTo (/var/task/aws-sdk/lib/state_machine.js:14:12)",
        "    at /var/task/aws-sdk/lib/state_machine.js:26:10",
        "    at Request.<anonymous> (/var/task/aws-sdk/lib/request.js:38:9)",
        "    at Request.<anonymous> (/var/task/aws-sdk/lib/request.js:685:12)"
    ]
}
```

**Steps to reproduce**
 - Deploy serverless demo with region set to `ap-southeast-2`
 - Update Runtime property on Lambda functions in `template.yaml` from `nodejs10.x` to `nodejs12.x`
 - Instantiate Chime in `src/handlers.js` using region `ap-southeast-2`. e.g. `const chime = new AWS.Chime({ region: 'ap-southeast-2' })`

**Comment by simmkyu** [comment]
> Instantiate Chime in src/handlers.js using region ap-southeast-2. e.g. const chime = new AWS.Chime({ region: 'ap-southeast-2' })

The region for the `AWS.Chime` constructor is different from the media region. Chime API (control plane) requires the `us-east-1` region.

When you create a meeting, you can pass the media region as the MediaRegion parameter. Here's an example from [Getting responses from your server application](https://github.com/aws/amazon-chime-sdk-js#getting-responses-from-your-server-application):

```
// You must use "us-east-1" as the region for Chime API and set the endpoint.
const chime = new AWS.Chime({ region: 'us-east-1' });
chime.endpoint = new AWS.Endpoint('https://service.chime.aws.amazon.com/console');

// Specify the region in which to create the meeting.
const meetingResponse = await chime.createMeeting({
  ClientRequestToken: uuid(),
  MediaRegion: 'us-west-2'
}).promise();
```

**Comment by SamKosky** [comment]
Thanks @simmkyu, I knew it was something simple!
