### ISSUE TITLE
videoTileDidUpdate observer not executed for local 

### ISSUE THREAD

**Issue by Osuka42g** [aws/amazon-chime-sdk-js#569]
**Timeline**
Outline the main actions the user performed and when:
- User A, B and C are in a meeting
- User A activates screen share, and selects to share all screen.
- User B and C receive the tileState update; A doesn't.

**Describe the bug**
When activating screenShare feature, all attendees trigger this observable with the tileState; all attendees but the one who activated (local). This makes not possible to add a local title for screenShare.

I'm pretty sure this was working before, and A was receiving the expected tileState update.

```javascript
videoTileDidUpdate: tileState => {
        console.log("videoTileDidUpdate observer, tileState:", tileState);
}
```

**Screenshot**
![image](https://user-images.githubusercontent.com/5117006/87901601-20b7cc00-ca1d-11ea-8f11-78f0db4f9ba9.png)

**Platform**
 - OS: MacOS 10.15.1
 - Browser: Chrome, Firefox Developer Edition
 - Browser Version: Chrome 83.0.4103.116, Firefox 79.0b9
 - Amazon Chime SDK GitHub Commit: tested in 1.11.0 and 1.12.0

**Comment by jackpmastrangelo** [comment]
Seeing the same behavior as of this morning. The participant sharing their screen never receives a content share tileState. This is new behavior.

**Comment by barrazastark** [comment]
Seeing the same

**Comment by alexisllamas** [comment]
I'm having the same issue

**Comment by fangzhoulu-hiretual** [comment]
We are experiencing the same issue since last Friday, July 17. 

And seems contentShareDidStart is not called, either.

**Comment by ltrung** [comment]
We recently have a backend change so that we no longer send content share video back to the sharer to save on bandwidth (See issue #526). As a result, videoTileDidUpdate would not fire for the sharer anymore (although contentShareDidStart should).
PR #576 will return a media stream from screen capture which allows you to bind it to a video element.

**Comment by Osuka42g** [comment]
Awesome. Thanks @ltrung !

**Comment by fangzhoulu-hiretual** [comment]
Thanks @ltrung . Could you please verify if contentShareDidStart or contentShareDidStop will be fired? They are not fired in my side when I start or stop sharing screen.

**Comment by ltrung** [comment]
@fangzhoulu-hiretual I verified with our demo app that ContentShareDidStart and contentShareDidStop fire before my fix also. So if it does not for you, please open up a new issue.

**Comment by kkateq** [comment]
Thank you @ltrung! 

According to a new guide the `startContentShareFromScreenCapture` should return a media stream, that should be bound to the video element, however, it always returns `undefined`. Both `contentShareDidStart` and `contentShareDidStop` are fired correctly. Is there anything that could possibly be wrong?

**Comment by ltrung** [comment]
@kkateq Hi, I just try that in our demo app by modifying this line https://github.com/aws/amazon-chime-sdk-js/blob/master/demos/browser/app/meetingV2/meetingV2.ts#L1274 to:
```
const stream = await this.audioVideo.startContentShareFromScreenCapture();
```
and be able to see the return media stream which is not undefined.
Do you see any error throw in console?

**Comment by ltrung** [comment]
> Thank you @ltrung!
> 
> According to a new guide the `startContentShareFromScreenCapture` should return a media stream, that should be bound to the video element, however, it always returns `undefined`. Both `contentShareDidStart` and `contentShareDidStop` are fired correctly. Is there anything that could possibly be wrong?

If you use NPM then the change is not available yet.

**Comment by kkateq** [comment]
@ltrung right, I checked and it works in the demo app, but I am using the NPM package, so I'll wait until it's available. Thank you!

**Comment by ltrung** [comment]
We have reverted back the server change and will think of a better way to do this in a less disruptive manner.
