### ISSUE TITLE
Show other attendee's web camera content

### ISSUE THREAD

**Issue by AramAnd** [aws/amazon-chime-sdk-js#571]
### What are you trying to do?

I'm trying to start a meeting session where I want to show the web camera content of the users. The question is how can i subscribe to the attendee join and leave (maybe videoTileDidUpdate or something else) and show it's web camera content. Please see below how the process work on my end

1, Logged user start the meeting by creating meeting and then creating attendee.
2. After that  I create observer and append to audioVideo
`
 const videoElement: any = document.getElementById('chime');
 videoElement.autoplay = true;

const videoInputDevices = await meetingSession.audioVideo.listVideoInputDevices();
await meetingSession.audioVideo.chooseVideoInputDevice(videoInputDevices[0].deviceId);
// // The camera LED light will turn on indicating that it is now capturing.
// // See the "Device" section for details.
const observer = {
     // videoTileDidUpdate is called whenever a new tile is created or tileState changes.
      videoTileDidUpdate: tileState => {
        // Ignore a tile without attendee ID and other attendee's tile.
        if (!tileState.boundAttendeeId) {
          return;
        }
        if (tileState.localTile) {
          return;
        }
        meetingSession.audioVideo.bindVideoElement(tileState.tileId, videoElement);
      }
    };
    meetingSession.audioVideo.addObserver(observer);
    meetingSession.audioVideo.startLocalVideoTile();
    meetingSession.audioVideo.start();
`
3. Then the other user gets notification where i am doing the same thing.

### Question/Request
The issue is that i want to show the other user's web camera content in the logged user view.

### What documentation have you looked at so far?

I have looked at the UseCases in the GitHub but was unable to understand how can i make this happen.

**Comment by simmkyu** [comment]
> The question is how can i subscribe to the attendee join and leave (maybe videoTileDidUpdate or something else) and show it's web camera content.

If you want to build a roster displaying a list of present attendees, please follow the "Attendees" section that uses `realtimeSubscribeToAttendeeIdPresence` and `realtimeSubscribeToVolumeIndicator` APIs.
https://github.com/aws/amazon-chime-sdk-js#attendees

For showing other attedee's videos, you must implement `videoTileDidUpdate` in which you bind the given tile object to the target video element. Here's a 1-on-1 video call example based on your code:

```
const videoInputDevices = await meetingSession.audioVideo.listVideoInputDevices();
await meetingSession.audioVideo.chooseVideoInputDevice(videoInputDevices[0].deviceId);

const observer = {
  audioVideoDidStart: () => {
    // Start your video this the meeting starts
    meetingSession.audioVideo.startLocalVideoTile();
  },
  videoTileDidUpdate: tileState => {
    // Ignore a tile without attendee ID and a content/screen share.
    if (!tileState.boundAttendeeId || tileState.isContent) {
      return;
    }

    // Choose the right video element in your web application
    let videoElement;
    if (tileState.localTile) {
      videoElement = document.getElementById('my-video');
    } else {
      videoElement = document.getElementById('remote-attendee-video');
    }

    // Bind the given tile state to the target video element
    meetingSession.audioVideo.bindVideoElement(tileState.tileId, videoElement);
  }
};
meetingSession.audioVideo.addObserver(observer);
meetingSession.audioVideo.start();
```

If you need to show more than one remote attendee's videos, please review [Use case 15](https://github.com/aws/amazon-chime-sdk-js#video) for an example on how to bind multiple remote videos.

**Comment by AramAnd** [comment]
@simmkyu thank you for the reply. This is very helpful. Just to confirm the last piece. This is my code which user starts the meeting and this is the place where i want to show the videos of the 2 users. (ignore the return for the localTile)
`
const videoInputDevices = await meetingSession.audioVideo.listVideoInputDevices();
    await meetingSession.audioVideo.chooseVideoInputDevice(videoInputDevices[0].deviceId);

    const observer = {
      audioVideoDidStart: () => {
        // Start your video this the meeting starts
        meetingSession.audioVideo.startLocalVideoTile();
      },
      videoTileDidUpdate: tileState => {
        // Ignore a tile without attendee ID and a content/screen share.
        if (!tileState.boundAttendeeId || tileState.isContent) {
          return;
        }

        // Choose the right video element in your web application
        let videoElement;
        if (tileState.localTile) {
          console.log('is local attendeee')
          // videoElement = document.getElementById('my-video');
          return;
        } else {
          console.log('another attendeee')
          videoElement = document.getElementById('remote-attendee-video');
        }

        // Bind the given tile state to the target video element
        meetingSession.audioVideo.bindVideoElement(tileState.tileId, videoElement);
      }
    };
    meetingSession.audioVideo.addObserver(observer);
    meetingSession.audioVideo.start();
`

and this is my other code where the second user connects to the existing meeting (sending request to create attendee only)

`
const videoInputDevices = await meetingSession.audioVideo.listVideoInputDevices();
await meetingSession.audioVideo.chooseVideoInputDevice(videoInputDevices[0].deviceId);
// The camera LED light will turn on indicating that it is now capturing.
// See the "Device" section for details.
 meetingSession.audioVideo.startLocalVideoTile();
`

So when the second user connects, i do not get any in **videoTileDidUpdate** as other attendee. Could you please let me know what i am doing wrong ?

**Comment by AramAnd** [comment]
@simmkyu NVM, i figoure it out, it seems like that i was missing **meetingSession.audioVideo.start();** for the second piece.

Although, I have another question, how can i share the audio as well, from the second user to the first user ?

**Comment by simmkyu** [comment]
For the audio, choose your microphone and speaker ([Use case 2](https://github.com/aws/amazon-chime-sdk-js#device)).

```
const audioInputDeviceInfo = /* An array item from meetingSession.audioVideo.listAudioInputDevices */;
await meetingSession.audioVideo.chooseAudioInputDevice(audioInputDeviceInfo.deviceId);

const audioOutputDeviceInfo = /* An array item from meetingSession.audioVideo.listAudioOutputDevices */;
await meetingSession.audioVideo.chooseAudioOutputDevice(audioOutputDeviceInfo.deviceId);
```

Then, bind an audio element and start a meeting ([Use case 5](https://github.com/aws/amazon-chime-sdk-js#starting-a-session)). You need a single `<audio>` element in your web application to hear other attendee's voice.

```
const audioElement = /* HTMLAudioElement object e.g. document.getElementById('audio-element-id') */;
meetingSession.audioVideo.bindAudioElement(audioElement);
meetingSession.audioVideo.start();
```

Now, if two attendees join the same meeting and talk, they should be hear each other.

**Comment by AramAnd** [comment]
yup worked @simmkyu thank you !

**Comment by ankitaivd** [comment]
When i use stopLocalVideoTile() for video off. It is working. But when i want start again the video that time (using .startLocalVideoTile() ) that time video is start properly for that user but other attendees can see 2 window that user ( one is for video off and one is for video on).
Please help me on that. 
![screenshot](https://github.com/aws/amazon-chime-sdk-js/assets/95675906/5f47aeaa-f4cc-446b-988e-64b4b18a3606)
I attached a screenshot for that.
