### ISSUE TITLE
Could audioVideo.start() and audioVideo.stop() return Promises?

### ISSUE THREAD

**Issue by jackpmastrangelo** [aws/amazon-chime-sdk-js#573]
I was wondering if it was possible to make start() and stop() return promises instead of being void? It would make it easier to manage race conditions when rapidly starting & stopping meetings.

**Comment by simmkyu** [comment]
One reason for returning a non-promise was that the user could get the failure reason in one place ([`AudioVideoObserver. audioVideoDidStop(sessionStatus)`](https://github.com/aws/amazon-chime-sdk-js/blob/e1006454744ca2bbe0ece20231b1aa3ff64c1b7a/src/audiovideoobserver/AudioVideoObserver.ts#L26)) and act accordingly. If `start()` and `stop()` return promises, the user will also need to handle rejected cases.

Here's an example. Assume the user attempts to stop the meeting before getting started.

```
meetingSession.audioVideo.addObserver({
  audioVideoDidStop: sessionStatus => {
    // e.g. You stopped a meeting, or someone else ended a meeting later
    console.log('Stopped with a session status code: ', sessionStatusCode);
  }
});

meetingSession.audioVideo.start();
meetingSession.audioVideo.stop();
```

With the promise pattern, you should've handled rejected cases too.

```
meetingSession.audioVideo.addObserver({
  audioVideoDidStop: sessionStatus => {
    // e.g., Handle the case when someone else has ended a meeting
    console.log('Stopped with a session status code: ', sessionStatusCode);
  }
});

try {
  await meetingSession.audioVideo.start();
} catch (error) {
  // Handle the failure either stopped by yourself or other errors
}

try {
  await meetingSession.audioVideo.stop();
} catch (error) {
  // Handle the stop failure too
}
```

Internally, SDK enqueues start, stop, and a few other actions and attempts to run them based on priorities.

**Comment by simmkyu** [comment]
Please review the comment above and use [AudioVideoObserver](https://github.com/aws/amazon-chime-sdk-js/blob/master/src/audiovideoobserver/AudioVideoObserver.ts) to handle race conditions with multiple start/stop calls.
