### ISSUE TITLE
startContentShareFromScreenCapture return undefined

### ISSUE THREAD

**Issue by rusicsemenov** [aws/amazon-chime-sdk-js#582]
Hello. i want to display the content share stream for the sharer. But new version amazon-chime-sdk-js@1.13.0, when i start share sreen startContentShareFromScreenCapture, always return undefined. videoTileDidUpdate don't called now. How i can show shared content?

**Comment by ebernacchia** [comment]
I have the same problem. videoTileDidUpdate is not been called whe share own content

**Comment by ltrung** [comment]
PR #576 to return media stream from startContentShareFromScreenCapture is not available in NPM 1.13.0, We will push out NPM 1.14.0 which will contain this change.

**Comment by ltrung** [comment]
npm 1.14.0 is now available and the media stream should be returned from startContentShareFromScreenCapture.
