### ISSUE TITLE
Test sound and DefaultAudioMixController

### ISSUE THREAD

**Issue by rusicsemenov** [aws/amazon-chime-sdk-js#583]
Hello in last three version shime-sdk DefaultAudioMixController cannot correct use audio device.

If i don't bind device hear sound, but if i am bind device ` audioMixController.bindAudioDevice({ deviceId: sinkId }); ` no hear sound.

![image](https://user-images.githubusercontent.com/20163858/88375133-afbd3f00-cda3-11ea-8b8c-b145b8b248b0.png)

This happen in Chrome and FF. Opera is still work perfect.

**Comment by RidipDe** [comment]
Can you please confirm the following:
1) I assume sinkId is a variable that you created. But what did you assign to sinkId ?
2) Has the audioElement and audioStream is set as well ?

It will also be great if you can provide us with the repro steps.

**Comment by rusicsemenov** [comment]
Yes of course.
1. I get `sinkId` from `meetingSession.audioVideo.listAudioOutputDevices()` diviiceID, or if user don't chouse any device, `sinkId` is _String_ `default`;
![image](https://user-images.githubusercontent.com/20163858/88473422-e622c780-cf25-11ea-9a5a-a8a167b78540.png)

2. `audioStream`  is empty, i check in Chrome and Opera: `audioStream: null` but in the Mozilla i have the sount and i see audioStream. 
![image](https://user-images.githubusercontent.com/20163858/88473511-01da9d80-cf27-11ea-99bb-9b6ec88d526c.png)

After that i check `destinationStream` stream have content but cant bind ro audioMixController. 
![image](https://user-images.githubusercontent.com/20163858/88473582-b07ede00-cf27-11ea-807d-5b68ce50ff3d.png)

![image](https://user-images.githubusercontent.com/20163858/88473587-bffe2700-cf27-11ea-977f-d1abff71f307.png)

`bindAudioStream`  cant bind MediaStream, i check in Chrome and Opera

**Comment by rusicsemenov** [comment]
Update, i check the `DefaultAudioMixController.js` file, an get sothing intresting, in  `DefaultAudioMixController.prototype.bindAudioMix` function you rebind audioStream `this.audioStream = existingStream;` but `existingStream` is not defined.

Anyway _a.labal: 2 all time.
![image](https://user-images.githubusercontent.com/20163858/88474008-a363ee00-cf2b-11ea-942f-c64b9c0131c3.png)

**Comment by RidipDe** [comment]
The variable 'existingStream' is defined here:
https://github.com/aws/amazon-chime-sdk-js/blob/master/src/audiomixcontroller/DefaultAudioMixController.ts#L60
For chromium browsers we observed that we had to nullify the srcObject and then set the sinkId and then reassign the stream back to the audioElement srcObject.
Here is the complete description https://github.com/aws/amazon-chime-sdk-js/pull/522

**Comment by rusicsemenov** [comment]
Maybe you are right. But i use rebuild chime on vue, and for test sound user your class from https://github.com/aws/amazon-chime-sdk-js/blob/master/demos/browser/app/meeting/meeting.ts#L66.

For now i found solution for my, 
![image](https://user-images.githubusercontent.com/20163858/88647075-5a986a80-d0ce-11ea-9c82-33a28e17ce32.png)

Why is that: 
Are `bindAudioDevice` and `bindAudioStream` called at the same time, they both rebind audio device.

After delay `bindAudioStream` have information about sinkId, and now sound test working is perfect.

**Comment by RidipDe** [comment]
PR https://github.com/aws/amazon-chime-sdk-js/pull/589 should solve the issue in the chromium based browsers
