### ISSUE TITLE
Is there any timelines for Windows SDK for chime?

### ISSUE THREAD

**Issue by ankit-maheshwari** [aws/amazon-chime-sdk-js#590]
I just wanted to know that is there any timelines/ plans for Windows SDK for the chime. Hence we can make features like annotations, remote control available for the Windows users.

**Comment by vidya-mohan** [comment]
@ankit-maheshwari Thank you for the interest in our SDK. Could you please reach out via https://pages.awscloud.com/GLOBAL-aware-GC-Amazon-Chime-SDK-2020-reg.html with more details?
