### ISSUE TITLE
Log Level of "stopped pinging (WebSocketClosed) / (WebSocketClosing)" 

### ISSUE THREAD

**Issue by efortney** [aws/amazon-chime-sdk-js#591]
Hi, I have a question regarding the log level for "stopped pinging (WebSocketClosed) / (WebSocketClosing)" We are seeing this log each time that a user clicks our hang-up button and leaves the call, or leaves by closing the window as a warning. Is this log something that could be a candidate for moving to info level, or is it indicative of an actual issue with the way the user is leaving the call?

**Comment by ltrung** [comment]
Thank you for pointing that out. I have submitted #597 to change the log level of that message.

**Comment by ltrung** [comment]
PR #597 has been merged. Close this issue.
