### ISSUE TITLE
MediaDeviceInfo is not defined

### ISSUE THREAD

**Issue by rusicsemenov** [aws/amazon-chime-sdk-js#596]
Hello, when i open site from http protocol i received error. I know about https, but i want catch this error for show message.  I am use trycatch but still get same error.

![image](https://user-images.githubusercontent.com/20163858/88972447-3ac79900-d2be-11ea-8ec6-a427e7567ef5.png)
![image](https://user-images.githubusercontent.com/20163858/88972533-63e82980-d2be-11ea-8348-046dd5023a5d.png)

Thanks

**Comment by ltrung** [comment]
To show error message, could you check for the existence of mediaDevices from navigator?
```
if (!navigator.mediaDevices || !navigator.mediaDevices.enumerateDevices) {
  console.log("Media devices are not avaialble");
  return;
}
```

**Comment by rusicsemenov** [comment]
Yes, thanks @ltrung i tried that, but some devices on Android or IOS return the false, while in the meeting work perfect. Ok i will chack that again, i don't chech before `navigator.mediaDevices.enumerateDevices`.

**Comment by rusicsemenov** [comment]
And one more question about this: if camera or mic is blocked, script continues work. How i can catch blocked device? Maybe logger can return error and information except console?

**Comment by ltrung** [comment]
When you say "camera is blocked", do you mean users do not give permission? If so, chooseVideoInputDevice and chooseAudioInputDevice should return [PermissionDeniedByUser](https://github.com/aws/amazon-chime-sdk-js/blob/master/src/devicecontroller/DevicePermission.ts#L16).

**Comment by rusicsemenov** [comment]
Yes if user do not give permission.
What do you mean? After init `meetingSession` i need choose device for test permission? Something like that?
```
this.videoInputDevices = videoInputDevices.map((el) => {
    return {
        label: el.label,
        deviceId: el.deviceId,
    };
});

this.videoInputDevice =
    this.videoInputDevices && this.videoInputDevices.length > 0
        ? this.videoInputDevices[0].deviceId
        : undefined;

await meetingSession.audioVideo.chooseVideoInputDevice(
    this.videoInputDevice.deviceId
);
```

If so, i got error, and only if i use trycatch, i can stop script. I thought`listAudioInputDevices` or `listVideo InputDevices` can return something information about permition.

**Comment by ltrung** [comment]
If users do not give permission, listVideoInputDevices will return a list of devices but with no device labels and chooseVideoInputDevice will return PermissionDeniedByUser. listVideoInputDevices calls [enumerateDevices](https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/enumerateDevices) which still return a list of devices with no permission.

If you want to catch it with chooseVideoInputDevice, you can do something like
```
const result = await meetingSession.audioVideo.chooseVideoInputDevice(
    this.videoInputDevice.deviceId
);
if (result === PermissionDeniedByUser) {
  //Display error message
}
```
