### ISSUE TITLE
Possible bug, "Missed Pongs Recently" returning false after 2 consecutive misses

### ISSUE THREAD

**Issue by efortney** [aws/amazon-chime-sdk-js#598]
**Meeting and attendee IDs:**
List the meeting and attendee IDs that the attached logs apply to.
N/A
**Timeline**
Outline the main actions the user performed and when:
N/A

*I can attach a log file to a private support ticket if needed*

**Describe the bug**
I'm seeing a confusing status regarding the logging around missed pongs. My understanding is that the health logger should set `missedPongsRecently` as true if there are 2 or more pongs missed in succession. [Upper Limit for pong config](https://github.com/aws/amazon-chime-sdk-js/blob/c607861b70feacde2865d7200416ea99f9b301f9/src/connectionhealthpolicy/ConnectionHealthPolicyConfiguration.ts#L24) We have had a few Chime sessions where a user's internet connection would be poor, causing them to miss 2 or more pongs in succession. The Chime SDK emits the following log as a warning `reconnection recommended due to: no packets received: ${noPacketsReceivedRecently}, missed pongs: ${missedPongsRecently}, bad audio delay: ${hasBadAudioDelay}` ([code](https://github.com/aws/amazon-chime-sdk-js/blob/c607861b70feacde2865d7200416ea99f9b301f9/src/connectionhealthpolicy/ReconnectionHealthPolicy.ts#L60)) with the value for missedPongsRecently as false. 
**Screenshots**

example of consecutive logs where the issue occurs
<img width="890" alt="Screen Shot 2020-07-31 at 2 55 00 PM" src="https://user-images.githubusercontent.com/30159800/89072319-ef54cf80-d33d-11ea-9905-fbc0991b2642.png">
<img width="548" alt="Screen Shot 2020-07-31 at 2 55 07 PM" src="https://user-images.githubusercontent.com/30159800/89072322-efed6600-d33d-11ea-8118-e53cac80e1d0.png">

**Platform*
 - OS: Windows 10
 - Browser: 
 - Browser Version: 
 - Amazon Chime SDK GitHub Commit: https://github.com/aws/amazon-chime-sdk-js/commit/c607861b70feacde2865d7200416ea99f9b301f9

**Comment by ltrung** [comment]
@efortney , could you double check the SDK version you are using c607861 since it is very old? The current [missed pong threshold](https://github.com/aws/amazon-chime-sdk-js/blob/master/src/connectionhealthpolicy/ConnectionHealthPolicyConfiguration.ts) is 4 and not 2.
