### ISSUE TITLE
Want to ask how can we mute all the attendees from except the person who is hosting the meeting

### ISSUE THREAD

**Issue by himanshu136** [aws/amazon-chime-sdk-js#601]
**Important:** Please attach INFO-level logs with timestamps to the report from *before* the session started up until the point at which the unexpected behavior occured. For multi-participant calls, attach a log file for each participant if possible.

**Meeting and attendee IDs:**
List the meeting and attendee IDs that the attached logs apply to.

**Timeline**
Outline the main actions the user performed and when:

* <timestamp> <action>
* <timestamp> <action>

**Describe the bug**
Describe the bug and the timestamp at which it happened relative to the timestamp in the log file.

**Screenshots**
If applicable, add screenshots to help explain the problem.

**Platform**
 - OS: 
 - Browser: 
 - Browser Version: 
 - Amazon Chime SDK GitHub Commit:

**Comment by ltrung** [comment]
@himanshu136, Currently we have 2 APIs realtimeMuteLocalAudio to mute local audio for an attendee and trealtimeSetCanUnmuteLocalAudio to prevent attendee from unmute themselves (Please see Case 8 and 9 in the README).

If you want to mute all attendees except the presenter, you can create a wrapper method that use [realtimeSendDataMessage](https://github.com/aws/amazon-chime-sdk-js/blob/master/src/audiovideofacade/DefaultAudioVideoFacade.ts#L259) to send messages to all clients to mute themselves using [realtimeMuteLocalAudio](https://github.com/aws/amazon-chime-sdk-js/blob/master/src/audiovideofacade/DefaultAudioVideoFacade.ts#L204).

**Comment by himanshu136** [comment]
As a presenter he cannot mute all those people in behalf of them by introducing a button muteAll? This is manually sending the message to mute them?

**Comment by vidya-mohan** [comment]
yes thats right -your application can listen to this message and mute locally
