### ISSUE TITLE
Users at locations far from AWS region have no audio

### ISSUE THREAD

**Issue by andyh6969** [aws/amazon-chime-sdk-js#602]
Hi,

If we (in the UK) start a call with people in New Zeland routed via London (eu-west-2), we find the people in NZ have no Audio (send or receieve) and do not appear on the Roster. They do however have video.

If we reverse it and host the call in Sydney, Aus (ap-southeast-2) then we find the opposite to be true. The people in NZ are fine but we can not send or recieve audio on UK clients.

**Comment by ltrung** [comment]
@andyh6969, could you give us the meeting Id and console logs for both meeting so we can investigate?

**Comment by andyh6969** [comment]
Meeting id of London hosted meetign where NZ had no audio: f485033b-6f0a-48cc-94d9-f2eeb9b08aeb
Meeting id of Sydney hosted meeting where UK clients had no audio: 2e0a5e9e-b2e9-4a05-879e-d9da9c499c3e

I don't have console.logs of those meetings saved. We will try and recreate again and send them.

**Comment by ltrung** [comment]
Just want to clarify but the meeting in the log that you attached is in US-West-1 (N. California) and not in UK or Australia. Is it the correct log?

**Comment by ltrung** [comment]
Also if you host the meeting in us-west-1 or us-west-2, do you encounter any issue?

**Comment by andyh6969** [comment]
This was form another call where tried us-west-1 as we had another (NZ to UK) call but some people in UK could not get on (that is this log). We moved it to us-east-1 and it worked for everyone.
