### ISSUE TITLE
can't get updated react state value in observer

### ISSUE THREAD

**Issue by dipras** [aws/amazon-chime-sdk-js#607]
when i want to get react state value in videoTIleWasRemoved, it's return value that i declare at first time. i already checked the value using console log outside observer and the value is same as when i set the state

**Comment by ltrung** [comment]
@dipras Is there any chance you could share your code snippet? It would help us troubleshoot the issue.
You can also refer to our react component library implementation of videoTileWasRemoved here https://github.com/aws/amazon-chime-sdk-component-library-react/blob/master/src/hooks/sdk/useAttendeeStatus.tsx#L75 or our class room demo https://github.com/aws-samples/amazon-chime-sdk-classroom-demo/blob/65abe03ea8ade6ab3db203b5c1a04313cd0be8a0/app/components/ContentVideo.tsx#L61
