### ISSUE TITLE
Amazon Chime SDK supports android and IOS with Ionic Framework?

### ISSUE THREAD

**Issue by sidharth-sid** [aws/amazon-chime-sdk-js#608]
Hi @vidya-mohan 
Our team was interested in the amazon chime video meeting services and wanted to use it in our application.
We have a hybrid application where we have the web app in angular js and the android and Ios builds are created using the ionic-Cordova framework. We were able to see the demos in the web but were worried about Chime SDK support in the ionic framework.

Can you give a brief about the current available support?
Saw a few other Github issues related to this.
https://github.com/aws-samples/amazon-chime-react-native-demo/issues

@codeslinger @weichenhamzn

_Originally posted by @sidharth-sid in https://github.com/aws/amazon-chime-sdk-js/issues/127#issuecomment-670514839_

**Comment by hiteshranaut** [comment]
Hey we have our android and ios applicaiton using ionic and right now using different solution for video calling. but our clients want to move to chime. is it possible. I check there is no plugin for cordova right now.

Question is can we implement Chime in ionic app?

**Comment by tnedev** [comment]
Need ionic/cordova SDK too!

**Comment by arttioz** [comment]
I also need IONIC/Cordova Chime SDK too!

**Comment by vidya-mohan** [comment]
JS SDK supports 'ios-webview' now. https://aws.amazon.com/about-aws/whats-new/2021/05/wkwebview-now-supported-with-amazon-chime-sdk-for-javascript/
