### ISSUE TITLE
Long video stream startup time on Firefox

### ISSUE THREAD

**Issue by irothschild** [aws/amazon-chime-sdk-js#609]
**Logs**
[firefox-79.txt](https://github.com/aws/amazon-chime-sdk-js/files/5043729/firefox-79.txt)
[chrome-83.txt](https://github.com/aws/amazon-chime-sdk-js/files/5043728/chrome-83.txt)

**Meeting and attendee IDs:**
Meeting: 68bfe5e6-e9fa-4126-b042-cb6e4d8e8727
Attendees: 
Firefox: 906b4998-cdd6-4ad4-bc01-6c940aca9a36
Chrome: d7ac7a83-eb93-4892-abc5-7a76b607aa08

**Timeline**
Join a meeting using demo meetingV2 with one attendee on Chrome and one on Firefox. 
Turn on Firefox camera and wait for video to show up on Chrome browser.

**Describe the bug**

In a new meeting, video from Firefox takes many seconds, often from 5 to 12 seconds, to appear on another browser (other browser can be Chrome, Firefox, etc. with the same delay)

Video from Chrome to Chrome (or Safari) most often appears within about 2-4 seconds.

**Platform**
 - OS: OS X
 - Browser: Firefox
 - Browser Version: 79 (also happened with 78)
 - Amazon Chime SDK GitHub Commit: d24ed4284bf5aa2e8a284c85dd3d9bbbef08fe4b

**Comment by simmkyu** [comment]
From the attached [firefox-79.txt](https://github.com/aws/amazon-chime-sdk-js/files/5043729/firefox-79.txt):
```
2020-08-07T21:16:07.230Z [INFO] SDK - AudioVideoUpdate/68bfe5e6-e9fa-4126-b042-cb6e4d8e8727/906b4998-cdd6-4ad4-bc01-6c940aca9a36/Timeout15000ms/UpdateSession/FinishGatheringICECandidatesTask took 7635 ms ConsoleLogger.ts:69:25
```

In Firefox 79, `FinishGatheringICECandidatesTask` took over 7 seconds, while, in Chrome, it took less 0.2 seconds. This task is waiting for the WebRTC peer connection's gathering state of being complete. You can read the details here:
https://developer.mozilla.org/en-US/docs/Web/API/RTCPeerConnection/icecandidate_event

---

### Using the nearest media region

When you create a meeting in your server application, you can pass the `MediaRegion` parameter to place your meeting in a specific region. Please review this FAQ question: https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html#which-media-regions-is-the-amazon-chime-sdk-available-in-how-do-i-choose-the-best-media-region-to-place-my-meetings

1. In your client application, find the nearest media region of your computer. The SDK demo has an example:
  https://github.com/aws/amazon-chime-sdk-js/blob/06b9535ce1a0b8c42961e78d859f8f5eb139d2a6/demos/browser/app/meetingV2/meetingV2.ts#L527-L537

    Try opening https://nearest-media-region.l.chime.aws in your browser. You will get the nearest region as a response.

2. Pass this region to your server application.

3. In your server application, create a meeting with this region. You need to pass the `MediaRegion` parameter.
   https://github.com/aws/amazon-chime-sdk-js/blob/06b9535ce1a0b8c42961e78d859f8f5eb139d2a6/demos/serverless/src/handlers.js#L46-L63


Could you let us know if using the nearest media region reduces the startup time in Firefox?

**Comment by irothschild** [comment]
I updated to latest commit (06b9535ce1a0b8c42961e78d859f8f5eb139d2a6) and ran meetingV2 demo.

Tried in the 2 closest regions (`us-east-1` and `us-east-2`) with very similar results with Firefox FinishGatheringICECandidatesTask taking over 11 seconds and Chrome taking much less than a second. Both Firefox and Chrome are running on the same client machine.

One thing I noticed is that this delay happens when I start video immediately after entering the room. If I wait 20 seconds after entering the room and then start the video, it connects the video quickly (it shows up in under 2 seconds) and FinishGatheringICECandidatesTask takes 2ms (on Firefox.)

**Comment by anuranduttaroy** [comment]
@irothschild I was able to reproduce this issue and am still investigating why the ICE Gathering event takes long in Firefox. I also noticed it does not happen sometimes on machines without VPN. Could you confirm if you are using any kind of VPN on the machines you are seeing this issue?

**Comment by irothschild** [comment]
@anuranduttaroy I am not using a VPN.

**Comment by ticamacho** [comment]
Any updates on this issue? 

I'm experiencing the same thing, and looking at the WebRTC internals from Firefox there are a lot of timeouts being raised.

**Comment by anuranduttaroy** [comment]
This issue should be fixed. Please feel free to re-open if you still see the issue.
