### ISSUE TITLE
[serverless] CloudFormation stack fails to deploy due to SQSPolicy

### ISSUE THREAD

**Issue by koxon** [aws/amazon-chime-sdk-js#610]
**Important:** Please attach INFO-level logs with timestamps to the report from *before* the session started up until the point at which the unexpected behavior occured. For multi-participant calls, attach a log file for each participant if possible.

**Describe the bug**

When running the following command in `demos/serverless` it starts deploying my stack but it fails as follow:

AWS::Lambda::EventSourceMapping:
Resource of type 'AWS::Lambda::EventSourceMapping' with identifier 'aa8d1a5a-eb6a-48ad-aba6-0cf815e2bc9f' did not stabilize.

**which then makes this fail:**

AWS::Lambda::EventSourceMapping : 
Cannot delete the event source mapping because it is in use. (Service: Lambda, Status Code: 400, Request ID: 20036b24-f79b-4e9a-aa44-d7ffcca245a8, Extended Request ID: null)

The stack doesn't want to be DELETED afterwards and I need to ignore that SQSPolicy resource in order to delete the stack.

I have proper IAM role and no conflicting resources

**Comment by simmkyu** [comment]
I think this commit has caused SQS-related failure: https://github.com/aws/amazon-chime-sdk-js/commit/c610e1222af3c60cdadac193d7aba3e6afdc0e5a

In this commit, we have fixed a typo in the SQS resource name of the Lambda event source in the CloudFormation template. Specifically, if you have deployed the serverless demo before this commit, you will get the error when redeploying it using the same stack name.

Sorry for the inconvenience. We'll be more careful when modifying the CF template, even if it's for the demo. Please reopen the issue if you still see the bug with a new stack name.

**Comment by GildedHonour** [comment]
I have the same bug @simmkyu
