### ISSUE TITLE
audio quality is very poor. Tons of noise mixed

### ISSUE THREAD

**Issue by farhaddeilami** [aws/amazon-chime-sdk-js#611]
Describe the bug

When setup audio environment, volume is very low.
2.So I've reinitialized AVAUDIOSESSION when I start video call. So I can get loud volume.
But it's quality is too bad. very noisy sound.
To Reproduce

I'm using previous demo version.
It has problem in video rendering mode. so I updated SDK but did not change previous demo module.
Video problem is solved but audio problem I've got.
In previous demo, you initialized audio and video environment in global thread.
if failed in audio device initialize, it's session is closed.
currently this module are working but volume is very low.
Expected behavior
video device does not initialized correctly.
-initial part
DispatchQueue.global(qos: .background).async {
self.currentMeetingSession = DefaultMeetingSession(
configuration: meetingSessionConfig, logger: self.logger)
self.setupAudioEnv()
self.setupVideoEnv()
self.currentMeetingSession?.audioVideo.startRemoteVideo()
}

-setup audio part.
func setupAudioEnv() {
do {
try AVAudioSession.sharedInstance().setCategory(AVAudioSession.Category.playAndRecord, options:
AVAudioSession.CategoryOptions.allowBluetooth)
self.setupSubscriptionToAttendeeChangeHandler()
try self.currentMeetingSession?.audioVideo.start(callKitEnabled: false)
} catch PermissionError.audioPermissionError {
let audioPermission = AVAudioSession.sharedInstance().recordPermission
if audioPermission == .denied {
self.logger.error(msg: "User did not grant audio permission, it should redirect to Settings")
} else {
AVAudioSession.sharedInstance().requestRecordPermission { granted in
if granted {
self.setupAudioEnv()
} else {
self.logger.error(msg: "User did not grant audio permission")
}
}
}
} catch {
self.logger.error(msg: "Error starting the Meeting: (error.localizedDescription)")
self.leaveMeeting()
}
}

I guess main problem is in AVAudioSession.CategoryOptions.allowBluetooth
I've reinitialed this AVAudioSession.CategoryOptions.allBluetooth, .defaultToSpeaker.

Logs
If applicable, add logs from console to help explain your problem.

Screenshots

Test environment Info (please complete the following information):

Version AmazonChimeSDK: [e.g. 0.4.0]
Version AmazonChimeSDKMedia: [e.g. 0.4.0]
Additional context

**Comment by RidipDe** [comment]
Thanks for writing.
As mentioned in the documentation https://aws.amazon.com/chime/chime-sdk/faq/ the Amazon Chime SDK for iOS is supported for applications on iOS 10 and above
Also he latest version of the Chime SDK is 1.15.0
