### ISSUE TITLE
React Native Webview on Android : no sound received from the others

### ISSUE THREAD

**Issue by rlebosse** [aws/amazon-chime-sdk-js#615]
I've developed an Android mobile app with React Native and a WebView that displays a webapp that uses `amazon-chime-sdk-js`.

Almost everything works fine :
* Join the meeting : OK
* See the other attendees : OK
* See the other attendees video : OK
* Other attendees can see my video : OK
* Other attendees can hear me : OK

But :
* I can't hear other attendees : there is not sound to be heard in the mobile app

Can you help me ?
Thanks in advance !

**Platform**
 - OS: Android 10
 - Browser: Android webview with https://github.com/react-native-community/react-native-webview (version 7.5.1)
 - Amazon Chime SDK GitHub Commit: version 1.12.0
 - React Native version : 0.61.5

**Comment by RidipDe** [comment]
Thank you writing.
As mentioned https://aws.amazon.com/chime/chime-sdk/faq/, we officially support only Google Chrome (version 78 and newer) for Android devices

**Comment by amirvatani** [comment]
@rlebosse we are going to implement an audio confrance application using web view & amazon chime , but there is two problem :
 1- we can not access microphone in web view 
 2- some devices built in browser does not support amazon chime 
Please help
