### ISSUE TITLE
Does the browser receive all video streams or only the binded ones ?

### ISSUE THREAD

**Issue by rlebosse** [aws/amazon-chime-sdk-js#616]
### What are you trying to do?

Let's say I joined a Meeting :

* with already 8 attendees
* the 8 attendees have started their local video
* in my browser, I only take the first 4 of them to be displayed (with `bindVideoElement()`)
* at this point, do my browser receive only the 4 streams of the videos I'm displaying ?

* then I change my mind, and want to display the other 4 videos (I unbind the previous 4 with `unbindVideoElement()` and bind the new 4 with `bindVideoElement()`)
* will my browser keep receiving the previous 4 videos streams or only the new 4 video streams ?

I'm trying to figure this out in Chrome through the chrome://webrtc-internals tool, but I have the impression that previous binded video streams keep coming in.

Thanks in advance for you answsers !

### How can the documentation be improved to help your use case?

*For example: Include a section on how to configure the meeting session.*

### What documentation have you looked at so far?

*For example: README.md, Amazon Chime SDK Developer Guide, etc.

**Comment by RidipDe** [comment]
The default behavior is that we subscribe to all of them unless the developers choose not to bindVideoElement.
Inorder to override this default behavior we need to set the videoDownlinkBandwidthPolicy and videoUplinkBandwidthPolicy in the meeting session config

**Comment by rlebosse** [comment]
@RidipDe : thanks for your answer !

But is there a `videoDownlinkBandwidthPolicy` that is provided so I can only subscribe to the video streams I want (only the ones currently binded with `bindVideoElement ?
