### ISSUE TITLE
iOS to iOS video call is showing as black screen with audio.

### ISSUE THREAD

**Issue by exihuatl** [aws/amazon-chime-sdk-js#620]
Hello, we have an issue with iOS to iOS connection in our application. We are constantly seeing video as black screen. Audio is working fine.

To reproduce this issue you can clone and start our application locally. https://github.com/kiwijobs/meet.

**Comment by RidipDe** [comment]
Were you able to reproduce the issue using our demo app?
If so, can you please provide us with the repro steps. Also please provide us with the device model, iOS version and browser being used.

**Comment by simmkyu** [comment]
I just tried running [the Chime SDK serverless demo](https://github.com/aws/amazon-chime-sdk-js/tree/master/demos/serverless) in two iOS devices and joining the same meeting. Two attendees can view each other without any issue.

#### Attendee 1: iOS 1 (iPhone 11 Pro - iOS 13.6.1)
<img src="https://user-images.githubusercontent.com/36240708/91240328-90913480-e6f6-11ea-9d87-68063c77032f.png" width="300">

#### Attendee 2: iOS 2 (iPhone XS - iOS 13.6)
<img src="https://user-images.githubusercontent.com/36240708/91240321-8c651700-e6f6-11ea-88a4-6c598a430775.png" width="300">

---

1. Could you share the INFO-level logs? Please use the "Bug report" template that will ask some basic information, e.g. browser version.
  https://github.com/aws/amazon-chime-sdk-js/issues/new/choose
  (We are seeing the 404 page when opening https://github.com/kiwijobs/meet)

2. Could you try deploying our [Chime SDK serverless demo](https://github.com/aws/amazon-chime-sdk-js/tree/master/demos/serverless) and check whether the problem still occurs in your iOS device?
