### ISSUE TITLE
Unable to connect to call on Safari

### ISSUE THREAD

**Issue by ceremonious** [aws/amazon-chime-sdk-js#621]
[ChimeLogs.txt](https://github.com/aws/amazon-chime-sdk-js/files/5068299/ChimeLogs.txt)

**Timeline**
Outline the main actions the user performed and when:

- User attempts to join the Chime meeting
- The task fails and the user is unable to join the meeting

**Describe the bug**

This is the warning I'm seeing when trying to join the call: 

`will retry due to status code TaskFailed and error: serial group task AudioVideoStart/84d1bbcb-49a8-4352-8cf9-24cb08c772ef/140dca19-14f0-446b-879b-114e9ab37f8e was canceled due to subtask AudioVideoStart/84d1bbcb-49a8-4352-8cf9-24cb08c772ef/140dca19-14f0-446b-879b-114e9ab37f8e/Timeout15000ms error: serial group task AudioVideoStart/84d1bbcb-49a8-4352-8cf9-24cb08c772ef/140dca19-14f0-446b-879b-114e9ab37f8e/Timeout15000ms/Media was canceled due to subtask AudioVideoStart/84d1bbcb-49a8-4352-8cf9-24cb08c772ef/140dca19-14f0-446b-879b-114e9ab37f8e/Timeout15000ms/Media/Peer error: serial group task AudioVideoStart/84d1bbcb-49a8-4352-8cf9-24cb08c772ef/140dca19-14f0-446b-879b-114e9ab37f8e/Timeout15000ms/Media/Peer was canceled due to subtask AudioVideoStart/84d1bbcb-49a8-4352-8cf9-24cb08c772ef/140dca19-14f0-446b-879b-114e9ab37f8e/Timeout15000ms/Media/Peer/AttachMediaInputTask error: Attempted to assign to readonly property.`

It seems like the problem might be that the browser is unable to find an audio output device. When I run navigator.mediaDevices.enumerateDevices() in my Safari console, I only see an audioinput device and a videoinput device. Any reason why Safari would be unable to access audio output devices? When I run the same command in Chrome, I see an audiooutput device as well.

**Platform**
 - OS: macOS Mojave
 - Browser: Safari
 - Browser Version: 12
 - Amazon Chime SDK GitHub Commit: 1.14.0

**Comment by RidipDe** [comment]
Thats a limitation with the Safari browser. Thats the expected behavior of the webRTC framework on Safari browser - it does not allow us to choose the audio output device.
You can try out the demo on the webRTC page https://webrtc.github.io/samples/src/content/devices/input-output/

**Comment by ceremonious** [comment]
So does that mean it's currently impossible for any WebRTC-based application to support Safari?

**Comment by RidipDe** [comment]
The safari browser does not let you choose another audio output device. However you should be able to join the meeting with the default audio output device. The limitation should not stop you from joining the meeting.
Are you able to reproduce the same issue on your safari browser using the Chime JS SDK demo app ? 
Can you please provide us with the repro steps on our demo app.

**Comment by ceremonious** [comment]
How do I join the meeting with the default audio output device? What do I pass in to meetingSession.audioVideo.chooseAudioOutputDevice?

**Comment by Ardenexal** [comment]
@ceremonious it should be automatic. It will use the system audio output by default. the chooseAudioOutputDevice is only needed if you want to change it from the default. behind the scenes it uses setSinkId to do this which you can search on canIUse https://caniuse.com/#search=setSinkId for browser compatibility

**Comment by RidipDe** [comment]
Thats correct, chooseAudioOutputDevice() is used to change the audio output device by changing the sinkId using the setSinkId(). Under the hood the safari browser chooses the default available audio device to be used as the only audio device.
