### ISSUE TITLE
No local audio output when chooseAudioInputDevice is called twice with different args

### ISSUE THREAD

**Issue by EpicPi** [aws/amazon-chime-sdk-js#623]
The code below is a contrived example of what was happening in our app.

```
const av = this.meetingSession.audioVideo;
await av.chooseAudioInputDevice(this.props.micDevice);  
av.start();  
av.chooseAudioInputDevice(this.props.micDevice.deviceId);
```

This results in no local audio being produced from the mic.
Removing the 4th line, making the 2nd and 4th lines the same, swapping the 2nd and the 4th line all mitigate the bug.

**Platform**
 - OS: Ubuntu, Mac, and Windows 
 - Browser: Chrome
 - Browser Version: 84
 - Amazon Chime SDK GitHub Commit: npm 1.15.0

**Comment by RidipDe** [comment]
can you please describe the what is the type of this.props.micDevice
this.props.micDevice.deviceId I assume is a 'String'

chooseAudioInputDevice takes parameters of type string | MediaTrackConstraints | MediaStream | null

Can you please provide us with a repro steps on our demo app.

**Comment by simmkyu** [comment]
I tried to reproduce the bug by calling the `chooseAudioInputDevice()` API twice before and after `start()`. When joining a meeting with this code in two browser tabs, both attendees can hear each other without an issue.

```
const audioInputDeviceInfo = (await meetingSession.audioVideo.listAudioInputDevices())[0];
await meetingSession.audioVideo.chooseAudioInputDevice(
  audioInputDeviceInfo.deviceId
);
meetingSession.audioVideo.bindAudioElement(new Audio()); // Not included in your code
meetingSession.audioVideo.start();
meetingSession.audioVideo.chooseAudioInputDevice(
  audioInputDeviceInfo.deviceId
);
```

#### Calling `chooseAudioInputDevice()` twice
`chooseAudioInputDevice()` in Chime SDK is using the `getUserMedia()` Web API to get the microphone: https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getUserMedia

`getUserMedia()` is a promise-based library that is not cancelable. To avoid race conditions, we recommend calling `chooseAudioInputDevice()` once at a time. (I don't think this is an issue though as you have used `await` on the first call.)

#### Passing the device ID to `chooseAudioInputDevice()`

As @RidipDe pointed, `chooseAudioInputDevice` takes in four types of parameters. In our documentation, we suggest using the device ID from `audioVideo.listAudioInputDevices`.
- `string`: the device ID (the device ID from `audioVideo.listAudioInputDevices`. See [the usage example](https://github.com/aws/amazon-chime-sdk-js#device)))
- `MediaTrackConstraints`: the `MediaStreamConstraints ` constraint ([See MDN web docs](https://developer.mozilla.org/en-US/docs/Web/API/MediaStreamConstraints))
- `MediaStream`: the MediaStream object ([See MDN web doc](https://developer.mozilla.org/en-US/docs/Web/API/MediaStream))
- `null`: no device to join a meeting without an audio input device

In your code, you are passing two different data types. Could you make sure that you are passing the device ID from `audioVideo.listAudioInputDevices`? (See [the usage example](https://github.com/aws/amazon-chime-sdk-js#device))).
```
await av.chooseAudioInputDevice(this.props.micDevice); 
av.chooseAudioInputDevice(this.props.micDevice.deviceId);
```

#### Setting the audio output

Your code is missing the audio output setup to hear other attendee's voice. Make sure to call `bindAudioElement` with an audio element before starting a meeting. See [the usage example](https://github.com/aws/amazon-chime-sdk-js#starting-a-session).

```
const audioElement = /* HTMLAudioElement object e.g. document.getElementById('audio-element-id') */;
meetingSession.audioVideo.bindAudioElement(audioElement);
```
