### ISSUE TITLE
The AudioContext was not allowed to start.

### ISSUE THREAD

**Issue by shawnlah** [aws/amazon-chime-sdk-js#624]
Currently we are building a video conferencing app using Chime, Amplify, graphql, and Vuejs. Some of the conference attendees are not required to have audio and video inputs.

<ins>**Problem**</ins>
Chrome/83.0.4103.97 throws a warning `The AudioContext was not allowed to start. It must be resumed (or created) after a user gesture on the page.`. This causes `meetingSession.audioVideo.realtimeSubscribeToAttendeeIdPresence(callback)` to not execute the callback (attendee ID and external user ID isn't provided), which means roster isn't being updated.

<ins>**How to reproduce**</ins>
1) Create a meeting session.
2) Set up audio output and bind audio. We don't set up audio and video inputs for some attendees as they are not needed.
3) Call `audioVideo.start()` to start the session.
3) Set up `realtimeSubscribeToAttendeeIdPresence(callback)` to watch for roster changes.
4) Start the application and refresh the page.

<ins>**Solution**</ins>
Execute `.resume()` on the audio context. Unfortunately, Chime doesn't expose the audio context.

When the application starts initially, everything works fine and roster is updated. On page refresh however, Chrome throws the `AudioContext` warning when `audioVideo.start()` is called. This doesn't affect `audioVideo.addObserver()` and `audioVideo.addContentShareObserver()`, but it does affect `realtimeSubscribeToAttendeeIdPresence`, these 3 methods are called after starting the session. No other errors or warning are thrown as well. Any advice on how to solve this?

**Comment by RidipDe** [comment]
Can you please provide us with the minimal repro to encounter the issue ?

**Comment by RidipDe** [comment]
We tried this in out demo app:
1) User A creates and joins a meeting

```
app.audioVideo.audioMixController.audioDevice
```
MediaDeviceInfo {deviceId: "default", groupId: "cf1bc3d14e35934951cce5f697306df2da42ffdd6de4d47c0d742adec01c2de1", kind: "audiooutput", label: "Default - MacBook Pro Speakers (Built-in)"}
```
app.audioVideo.audioMixController.audioElement
```
<audio id=​"meeting-audio" style=​"display:​none" autoplay>​</audio>​
app.audioVideo.audioMixController.audioStream
MediaStream {id: "audio", active: true, onaddtrack: null, onremovetrack: null, onactive: null, …}
```
app.audioVideo.start()
app.audioVideo.realtimeSubscribeToAttendeeIdPresence(() => {})
```

2) User B joins the same meeting that user A created.

We see user A and B in both the meeting roaster.


How often do you encounter this issue? Is it observed on any chrome version or the specific build that you provided?

Can you please provide us with the minimal repro using the demo app (eg. like above) to encounter the issue ?
