### ISSUE TITLE
Limit for active speaker list detection

### ISSUE THREAD

**Issue by elioscordo** [aws/amazon-chime-sdk-js#630]
### What are you trying to do?

I am trying to set up a large meeting where the most active speakers are displayed

### How can the documentation be improved to help your use case?

Is the active speaker detector able to support 250 attendees?
has that been tested?
https://aws.github.io/amazon-chime-sdk-js/modules/apioverview.html#5d-subscribe-to-an-active-speaker-detector-optional

### What documentation have you looked at so far?

Documentation is great!

**Comment by rachinkapoor** [comment]
Hello,
Could you also explain the optional arguments that can be provided in the constructor of `DefaultActiveSpeakerPolicy`?

I mean could you define these arguments like what do they mean and how do these impact the score calculated by `DefaultActiveSpeakerPolicy` :
* `speakerWeight`
* `cutoffThreshold`
* `silenceThreshold`
* `takeoverRate`

**Comment by devalevenkatesh** [comment]
Hello,

The constructor [documentation](https://aws.github.io/amazon-chime-sdk-js/classes/defaultactivespeakerpolicy.html) is updated now.

Also this [reply](https://github.com/aws/amazon-chime-sdk-js/issues/630#issuecomment-678582387) shares more information on `DefaultActiveSpeakerPolicy`.

The code for calculating score in the policy is [here](https://github.com/aws/amazon-chime-sdk-js/blob/master/src/activespeakerpolicy/DefaultActiveSpeakerPolicy.ts#L49). 

Closing this issue now. Please create an issue if you have any problems with `DefaultActiveSpeakerPolicy`.
