### ISSUE TITLE
startVideoPreviewForVideoInput and ios + safari issue

### ISSUE THREAD

**Issue by rusicsemenov** [aws/amazon-chime-sdk-js#631]
Hello, on ios + safari, when i use startVideoPreviewForVideoInput block is empty. 
```
meetingSession.audioVideo.startVideoPreviewForVideoInput(
     videoElement
);
```
In windows + chrome all work perfect, but on ios grt empty element.

If i try start video `meetingSession.audioVideo.startLocalVideoTile();` video work, i cant bind preview video.

Ipad and Iphone / IOS 13.6

**Comment by rusicsemenov** [comment]
Thanks, safari has permission to use the camera. I think i have some issue this `video` block, when i change tab and go back, i see video screen 1ms. 
But only in preview block. I will write when I find a solution.

**Comment by turkus** [comment]
> I just ran [the SDK demo](https://github.com/aws/amazon-chime-sdk-js/tree/master/demos/serverless) on my iPhone 11 Pro (iOS 13.6) and had no issue viewing the video preview in the `<video>` passed to `startVideoPreviewForVideoInput()`.
> 
> ![0cRewdhw](https://user-images.githubusercontent.com/36240708/90944478-e3f04380-e3d3-11ea-946e-ccfc42802502.png)
> 
> * Make sure that you have allowed a camera. Showing the video preview requires user permission. You can open iOS Settings => Safari => Camera and ensure that "CAMERA ACCESS ON ALL WEBSITES" is not set to "Deny."
> 
> <img alt="" width="300" src="https://user-images.githubusercontent.com/36240708/90944137-f0739c80-e3d1-11ea-9d0b-af6961ab242a.png">
> 
> * Check if your `<video>` element has the non-zero width and heigh. Chime SDK doesn't automatically set the width and height of the  element.
> * Make sure you are not calling `startVideoPreviewForVideoInput()` and `startLocalVideoTile()` simultaneously. The video preview might disappear. (Both desktop and iOS Safari have limitations when using a video camera. For example, if you enable a video in two Safari browsers tab, one video will go black.)
> 
> If you still can't see the video preview, please try [the SDK demo](https://github.com/aws/amazon-chime-sdk-js/tree/master/demos/serverless) in your iOS 13.6 and provide us with the results. If not working, please provide us with the commit/version and platform information, e.g., device version like iPhone 11 Pro.

That saves me. Especially the fact, we cannot run both preview and video tile. I think it should be placed in the docs or examples as an info.

**Comment by ltrung** [comment]
Updated in the FAQs for the video limitation in Safari.
