### ISSUE TITLE
Technical issues

### ISSUE THREAD

**Issue by hamzeh010** [aws/amazon-chime-sdk-js#643]
I worked on video conferencing software for the students to interact with the teacher online streaming.

Questions: 

Can we customize this project https://github.com/aws/amazon-chime-sdk-js/tree/master/demos/browser/app/meetingV2 to view teacher online video and his screen for all students?

Can we reserve a fixed tile for the teacher students online video , to preview the teacher cam only for each student?

**Comment by anuranduttaroy** [comment]
Hey @hamzeh010, did you get a chance to look at the [Amazon Chime SDK Classroom Demo](https://github.com/aws-samples/amazon-chime-sdk-classroom-demo)

This demo caters to the specific use-case that you mentioned.

**Comment by hamzeh010** [comment]
My company need a website not a web application.
But can you help me to know if we can customize  this [](https://github.com/aws/amazon-chime-sdk-js/tree/master/demos/browser/app/meetingV2) to view teacher online video and his screen for all students.
thank you @anuranduttaroy .

**Comment by vidya-mohan** [comment]
@hamzeh010 you can customize https://github.com/aws/amazon-chime-sdk-js/tree/master/demos/browser/app/meetingV2  for your purposes

**Comment by hamzeh010** [comment]
@vidya-mohan can i reserve a static tile for the teacher ?

**Comment by hamzeh010** [comment]
or where is the teacher video here [?``](

> [url](url
<img width="1427" alt="Screen Shot 2020-09-03 at 6 09 00 PM" src="https://user-images.githubusercontent.com/11952506/92133079-a3032080-ee10-11ea-9e17-481a1d86467b.png">
)

)

**Comment by ltrung** [comment]
> @vidya-mohan can i reserve a static tile for the teacher ?
> or where is the tileOrganizer video here [?``](
> 
> > [url](url
> 
> <img alt="Screen Shot 2020-09-03 at 6 09 00 PM" width="1427" src="https://user-images.githubusercontent.com/11952506/92133079-a3032080-ee10-11ea-9e17-481a1d86467b.png">
> )
> 
> )

The tile organizer is implemented in the [demo](https://github.com/aws/amazon-chime-sdk-js/blob/master/demos/browser/app/meetingV2/meetingV2.ts#L38) and is not an API in the SDK.
For video layout, SDK does not have any helper API so the logic is up to the application. 
If you use React, you could also refer to our React component library to build your website https://github.com/aws/amazon-chime-sdk-component-library-react

**Comment by vidya-mohan** [comment]
Resolving as @ltrung responded
