### ISSUE TITLE
Chime throws error on meeting ended

### ISSUE THREAD

**Issue by ReneS1991** [aws/amazon-chime-sdk-js#648]
### Description

When Attendee A ends a meeting, Attendee B gets redirected etc by using the `audioVideoDidStop` observer but no matter what the following 2 errors end up in the console:

![image](https://user-images.githubusercontent.com/17007821/91998807-fa838c80-ed3b-11ea-8e2f-db7ab951b943.png)

What is the reason for these 2 errors always popping up? And, is there a way to prevent these 2 errors? Because we have a third-party error logger hooked into the Chime logger these 2 errors are being spammed a lot in our system. If there is no way to silence/remove these 2 errors we have to ignore them in the third-party logger.

### Documentation research

The problem for us started after we updated the SDK to 1.12.x due to the following commit:

https://github.com/aws/amazon-chime-sdk-js/commit/681dbd9c0cdf87f65fad2d5c706389afe9ff222c

I checked if the way we 'leave' the meeting with Attendee B was causing it, but I couldn't find any way to prevent the errors from popping up. Calling the `audioVideo.stop()` inside the `audioVideoDidStop` doesn't change a thing and doesn't seem to be required because the demos don't call it either. All the demos simply redirect Attendee B to a different page, which we do as well.

**Comment by ltrung** [comment]
@ReneS1991 Could you clarify what you mean by Attendee A ends a meeting?

**Comment by ReneS1991** [comment]
@ltrung Yes. So imagine you have a meeting with 2 attendees:
- Attendee A
- Attendee B
Both are connected to the meeting and can see and talk with each other. At some point, the meeting is over, and "Attendee A" decides to click the 'end meeting' button of our application, which does a `meetingSession.audioVideo.stop()` and does a call to one of our PHP endpoints which then deletes the meeting by calling the `deleteMeeting` on the Chime API: https://docs.aws.amazon.com/chime/latest/APIReference/API_DeleteMeeting.html

Now, when this happens, the disconnect gets triggered for Attendee B in the `audioVideoDidStop()` observer where we handle his disconnect from the meeting because we get a `AudioCallEnded` meetingStatus, which is fine. However, even though we 'catch' it in that observer, the 2 errors mentioned in the first post still are being thrown by Chime.

I hope this example clarifies it.

**Comment by ltrung** [comment]
Unfortunately, since the error is thrown not from the observer, you would not be able to catch it.
