### ISSUE TITLE
listAudioOutputDevices returning empty array in firefox on MacOS and Windows

### ISSUE THREAD

**Issue by smarty192** [aws/amazon-chime-sdk-js#657]
````
this.audioInputDevices = await this.audioVideo?.listAudioInputDevices();
this.audioOutputDevices = await this.audioVideo?.listAudioOutputDevices();
this.videoInputDevices = await this.audioVideo?.listVideoInputDevices();

await this.audioVideo?.chooseAudioInputDevice(
        this.audioInputDevices[0].deviceId
);
await this.audioVideo?.chooseAudioOutputDevice(
        this.audioOutputDevices[0].deviceId
);
await this.audioVideo?.chooseVideoInputDevice(
        this.videoInputDevices[0].deviceId
);
````
Above code is working perfectly fine in chrome on Mac and windows, but when I am running same code in firefox, I am getting listAudioOutputDevices() as empty array. So after joining meeting, I am not able to hear, what other person is speaking!

**Comment by aburnson** [comment]
https://aws.github.io/amazon-chime-sdk-js/modules/apioverview.html#2e-configure-the-audio-output-device-optional

`listAudioOutputDevices` will only return devices for browsers that support setSinkId. Firefox does not presently support audio output device selection by default.

https://caniuse.com/#search=setSinkId

https://bugzilla.mozilla.org/show_bug.cgi?id=1498512

**Comment by smarty192** [comment]
Though listAudioOutputDevices() is returning empty array, I passed null to chooseAudioOutputDevice() method and it worked so I am able to hear what person on another end is speaking!
