### ISSUE TITLE
Delayed MediaDevice permissions not being applied on Chromium browsers

### ISSUE THREAD

**Issue by NPCGundlach** [aws/amazon-chime-sdk-js#659]
In the video conference app I'm working on we want to let users communicate via Chat, without neccessarily having to turn on their microphone/camera, but having the option to do so if they want. To not scare them away immediately with unprompted permission requests, I set the DeviceLabelTrigger to immediately reject at the start of the app. Upon clicking on the button to activate microphone or camera, the trigger is replaced respectively (I've seen by now that this doesn't matter).  
This works fine in Firefox, but I've noticed that it's not working in Chromium-browsers when the user hasn't given permission for the camera/microphone to work.  

The reason for this is that in Chromium-browsers sometime between v80 and v85 the function `navigator.mediaDevices.enumerateDevices()` was changed to return placeholder `MediaDeviceInfo`-objects when the web application doesn't have the permissions to access the microphone/camera.

Example:  
```JSON
[
  {
    "deviceId":"",
    "kind":"audioinput",
    "label":"",
    "groupId":"a5c52ea4edd24d3aa201dc0db47b7e9638cbf8c41d61cd9e5380aff0825e5d4f"
  },
  {
    "deviceId":"",
    "kind":"videoinput",
    "label":"",
    "groupId":"54853ddcd1e5146ff3b0e254e5edc13c31257ad8c23c15c600756ec0a466fa6d"
  },
  {
    "deviceId":"",
    "kind":"audiooutput",
    "label":"",
    "groupId":"ce451c5f7697de3eec7a1f81dff135d58a009eb140ac1ad078693b4faba5a28e"
  }
]
```

Firefox instead provides `MediaDeviceInfo`-objects with deviceIds.  
When the user clicks the microphone/camera button in Firefox, the browser requests permission, probably in the `choose<mediakind>InputDevice()`-function, while in Chromium-browsers this simply fails.

Manually calling `navigator.MediaDevices.getUserMedia({audio:true, video:true}).then(...)` also doesn't update chime's cached MediaDevices.

A possible fix would be to update or empty the MediaDeviceInfoCache when permissions are obtained or when the function `setDeviceLabelTrigger` is called.

I've also noticed that DeviceChangeObserver isn't triggered when permissions are given delayed.

**Log**
[localhost-1599224188100.log](https://github.com/aws/amazon-chime-sdk-js/files/5174947/localhost-1599224188100.log)

**Meeting and attendee IDs:**
AttendeeID: a6ed6db1-6e6a-41c6-9d3a-a5ae110dbb88
MeetingID: - (not in the logs)

**Timeline**
* 12:56:13: User clicks on button to activate video
* 12:56:13: Activating video fails due to missing permissions

**Describe the bug**
see above

**Platform**
 - OS: Windows 10
 - Browser: Chromium 87.0.4255.0, Microsoft Edge 85.0.564.44
 - Amazon Chime SDK GitHub Commit: 3f174fb6c53c6b6ad2d6816fd6fa21d9b60ae58a (likely, version from the npm repository: 1.16.0)

**Comment by vidya-mohan** [comment]
@NPCGundlach - have you seen this demo : https://github.com/aws/amazon-chime-sdk-component-library-react/tree/master/demo/chat ?

**Comment by santimendoza** [comment]
> @NPCGundlach - have you seen this demo : https://github.com/aws/amazon-chime-sdk-component-library-react/tree/master/demo/chat ?

That link is broken

**Comment by vidya-mohan** [comment]
Since then its moved to https://github.com/aws-samples/amazon-chime-sdk/tree/main/apps/chat

**Comment by santimendoza** [comment]
I'm having this issue in chrome. Can you point out what's important about that demo? Didn't found anything useful related to the issue in this ticket.
