### ISSUE TITLE
The stopVideoPreviewForVideoInput function stops video streaming, but not turns off users camera device.

### ISSUE THREAD

**Issue by VladimirKaroyan** [aws/amazon-chime-sdk-js#660]
**Timeline**

* 09/04/2020 13:30 UTC TimeZone

**Describe the bug**

After trying to stop video preview with `this.audioVideo.stopVideoPreviewForVideoInput` function, video stream stopping, but the user's camera the camera continues to engage, and the light for the camera continues to be turned on.

**Code for disabling video preview with select input value change**

    const videoInput = document.getElementById('video-input') as HTMLSelectElement;
    $('#video-input-state').on('change', async () => {
      const isVideoEnabled: boolean = $('#video-input-state').val() === 'on';
      if (isVideoEnabled) {
        await this.openVideoInputFromSelection(
          videoInput.value,
          true
        );
        this.audioVideo.startVideoPreviewForVideoInput(document.getElementById(
          'video-preview'
        ) as HTMLVideoElement);
      } else {
        this.audioVideo.stopVideoPreviewForVideoInput(document.getElementById(
          'video-preview'
        ) as HTMLVideoElement);
      }
    });

**Screenshots**
![image (3)](https://user-images.githubusercontent.com/37017173/92246497-e4f69a00-eed6-11ea-9cc1-653eeff3bf49.png)
![image](https://user-images.githubusercontent.com/37017173/92247335-23408900-eed8-11ea-84c6-80fce4b968c9.png)

**Platform**
 - OS: Windows 10 Home, OS Build: 19041.450
 - Browser: Google Chrome
 - Browser Version: Version 85.0.4183.83 (Official Build) (64-bit)

**Comment by devalevenkatesh** [comment]
Hello @VladimirKaroyan,

Sorry for the delay in answering your question.

I checked our [meeting demo app](https://github.com/aws/amazon-chime-sdk-js/tree/master/demos/browser) and found that calling `audioVideo.stopVideoPreviewForVideoInput(document.getElementById('video-preview'))` stops the light as well as the video stream. You are seeing the video icon as Chrome is showing you that you have granted video device permission to the Chrome browser when requested. It does not mean that your camera is accessing the video stream itself. 

You can check [this comment](https://github.com/aws/amazon-chime-sdk-js/issues/833#issuecomment-726106525) from one of the user who also had a similar question. Hope this helps you. I am closing this issue now. Feel free to open if you still face the same issue.
