### ISSUE TITLE
The `startAudioPreview` function was called 3 times, which creating additional load for CPU on the server and client-side

### ISSUE THREAD

**Issue by VladimirKaroyan** [aws/amazon-chime-sdk-js#662]
**Timeline**
Outline the main actions the user performed and when:

* 09/04/2020 14:10 UTC TimeZone

**Describe the bug**

The `startAudioPreview` function was called 3 times, which creates 3 calls to the `audioVideo.createAnalyserNodeForAudioInput` function and creating 3 `analyserNodeCallback`'s for listening to the user's microphone frequency, increasing the performance of the app, and creating additional load for CPU on the server and client-side.

The function was calling from `switchToFlow(flow: string): void` for the first time.

    switchToFlow(flow: string): void {
      this.analyserNodeCallback = () => {
      };
      Array.from(document.getElementsByClassName('flow')).map(
        e => ((e as HTMLDivElement).style.display = 'none')
      );
      (document.getElementById(flow) as HTMLDivElement).style.display = 'block';
      if (flow === 'flow-devices' || flow === 'flow-meeting') {
        this.startAudioPreview();
      }
      this.currentFlow = flow;
    }

For the second and the third time it was called from the `openAudioInputFromSelection(): Promise<void>` async function.

    async openAudioInputFromSelection(): Promise<void> {
      const audioInput = document.getElementById('audio-input') as HTMLSelectElement;
      await this.audioVideo.chooseAudioInputDevice(
        this.audioInputSelectionToDevice(audioInput.value)
      );
      this.startAudioPreview();
    }

All `ConsoleLogger` class logs and core `setAudioPreviewPercent` function's `arguments.callee.caller` log you can see on the screenshot attached to the issue.

The `ConsoleLogger` class was set to the `LogLevel.DEBUG` and all console log output with messages you can see at the txt file attached below.

[localhost-1599230473646.log](https://github.com/aws/amazon-chime-sdk-js/files/5175507/localhost-1599230473646.log)

**Screenshots**
![Screenshot_1](https://user-images.githubusercontent.com/37017173/92249612-6cdea300-eedb-11ea-8580-d0336d7e0a0d.png)

**Platform**
 - OS: Windows 10 Home, OS Build: 19041.450
 - Browser: Google Chrome
 - Browser Version: Version 85.0.4183.83 (Official Build) (64-bit)
 - ConsoleLogger Level: LogLevel.DEBUG (0)

**Comment by ltrung** [comment]
@VladimirKaroyan Thanks for pointing that out. I have tried to remove unnecessary startAudioPreview in #698. However, just want to point out that those extra startAudioPreview calls do not introduce more analyzer node because [createAnalyserNodeForAudioInput](https://github.com/aws/amazon-chime-sdk-js/blob/master/src/devicecontroller/DefaultDeviceController.ts#L134) will return early if there is no audio input specified yet (i.e., there is no analyzer node created for the first 2 calls).
