### ISSUE TITLE
SDK - Call me feature

### ISSUE THREAD

**Issue by themandibleclaw** [aws/amazon-chime-sdk-js#666]
Hi,

Is it possible to leverage the "Cal Me" feature (https://answers.chime.aws/questions/724/can-amazon-chime-call-my-phone-for-my-meeting-audi.html) via the SDK ?

**Comment by vidya-mohan** [comment]
@themandibleclaw thank you for the interest in the SDK. We dont have support for this feature at present

**Comment by themandibleclaw** [comment]
Thank you Viday, Appreciated you getting back to me

**Comment by Roritharr** [comment]
Is this feature on any roadmap?
