### ISSUE TITLE
Feature request: server-side media recording

### ISSUE THREAD

**Issue by kevinmcconnell** [aws/amazon-chime-sdk-js#668]
I understand this is not currently supported, but it would be great if there was a way to access raw media files from a meeting via the server-side API.

For context, I work on an application that organises video calls between multiple participants.  After each call, I need to generate a video recording of that meeting, with the participants arranged according to some particular business logic.  Currently I use Twilio's "Programmable Video" product to do this, because it has a feature where I can access all the raw media streams from a call.  I can take these audio & video files and composite them together to make a final video file.

I would like to be able to do this with Chime, but the lack of access to the recordings makes this difficult.  I've seen the example of using a headless browser to access the meeting client-side, but this seems a lot less robust than if I could fetch the media streams directly.

Ideally I would like to set a parameter on the meeting that would cause it to copy the media files from each participant to an S3 bucket so that I could retrieve them after the call was over.

Is there anything like this on the roadmap?

**Comment by RidipDe** [comment]
Hi @kevinmcconnell
Thank you for the feedback and the suggestion May we request you open a ticket with the customer support as mentioned in our [FAQ](https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html#i-have-a-question-not-addressed-in-this-faq-what-is-my-next-step)

**Comment by kevinmcconnell** [comment]
@RidipDe will do, thanks :+1:
