### ISSUE TITLE
Video element transform style gets cleared

### ISSUE THREAD

**Issue by irothschild** [aws/amazon-chime-sdk-js#669]
**Describe the bug**

When I set custom css style `transform` on a video element, the chime sdk removes it when it binds a stream to the element.

 - Amazon Chime SDK GitHub Commit: f7c145a9f68157677e10a4d3389f8bb251085e02

**Comment by michhyun1** [comment]
It looks like we force the transform style to rotateY(180) if it is a front facing camera or do nothing if its using the rear camera of a mobile device or if the facingMode property is not available like in the case of a computer. 
https://github.com/aws/amazon-chime-sdk-js/blob/7c24d357c44f17f755e023c438aa1120873f75c8/src/videotile/DefaultVideoTile.ts#L22-L30

This is done on purpose, and I think an easy solution you could implement would be to wrap your video element in a div and apply the transformation to the containing div.

**Comment by irothschild** [comment]
There are a few possible workarounds but I think your SDK should manage the webRTC etc. and leave the decisions on how things are displayed to the SDK users.
