### ISSUE TITLE
interface MediaDeviceInfo is assigned to variable

### ISSUE THREAD

**Issue by MangoBird** [aws/amazon-chime-sdk-js#674]
I'm getting error 'MediaDeviceInfo is not defined' from official browser demo app sporadically. I found typescript interface MediaDeviceInfo(which doesn't exists after compiled) is assigned to const variable doesNotHaveAccessToMediaDevices in private method updateDeviceInfoCacheFromBrowser of DefaultDeviceController class.

**Comment by ltrung** [comment]
@MangoBird  Could you clarify on what browser do you encounter this issue or do you see it in all browsers? MediaDeviceInfo does not exist usually indicate a browser we do not support.

**Comment by MangoBird** [comment]
@ltrung The browser was Chrome but I don't think the issue is browser related. The issue is with Typescript interface being assigned to a variable which is a grammatical mistake.

DefaultDeviceController.ts
line 411: const doesNotHaveAccessToMediaDevices = !MediaDeviceInfo;   <-- MediaDeviceInfo is not defined at runtime

**Comment by ltrung** [comment]
Yes, `MediaDeviceInfo` is represetend as a TypeScript interface, but we don’t actually assign the interface to a variable. We convert it to a boolean and then assign.
Could you double check whether you use https and not http?

**Comment by MangoBird** [comment]
It's a local environment so I use http for demo application.

@ltrung  Are you saying !MediaDivceInfo is typecasted by an exclamation mark or Is there some build process that swaps all typescript interface into boolean value? 

If you mean the former, it doesn't work because while exclamation can typecast the type undefined to a boolean value, but cannot typecast unrecognizable series of string which MediaDeviceInfo is after typescript code is compiled to javascript.

If you mean the latter, it would work but that's not what I get from demo application after compilation. MediaDeviceInfo remains in the compiled code base as it is not some boolean value.

**Comment by MangoBird** [comment]
Oh my bad. I found that MediaDeviceInfo is defined in the web api. Sorry. I thought it was only typescript Interface that you guys defined. Thank you for your time.

**Comment by MangoBird** [comment]
@ltrung I was thinking about this and I think typecasting MediaDeviceInfo into boolean value to handle the case where the browser doesn't support MediaDeviceInfo API is the wrong way to handle such case as it would throw an error instead of returning true(for the reason I mentioned as a former case above). I think the correct way would be using typeof keyword as demonstrated below.

![스크린샷 2020-09-19 오전 10 15 07](https://user-images.githubusercontent.com/16538875/93655928-995cf800-fa61-11ea-9b4a-a400ff8eebd1.png)

**Comment by ltrung** [comment]
@MangoBird Thanks. I have incorporated your suggestions in #900
