### ISSUE TITLE
Documentation request for constructor of DefaultActiveSpeakerPolicy

### ISSUE THREAD

**Issue by rachinkapoor** [aws/amazon-chime-sdk-js#675]
### What are you trying to do?
I am trying to customize DefaultActiveSpeakerPolicy.

### How can the documentation be improved to help your use case?
Could you also explain the optional arguments that can be provided in the constructor of DefaultActiveSpeakerPolicy?

I mean could you define these arguments?
What do they mean and how do these impact the score calculated by DefaultActiveSpeakerPolicy?

speakerWeight
cutoffThreshold
silenceThreshold
takeoverRate

### What documentation have you looked at so far?
Use Case #11 - https://aws.github.io/amazon-chime-sdk-js/index.html
https://aws.github.io/amazon-chime-sdk-js/modules/apioverview.html
https://aws.github.io/amazon-chime-sdk-js/classes/defaultactivespeakerpolicy.html

**Comment by devalevenkatesh** [comment]
Hello,

The constructor [documentation](https://aws.github.io/amazon-chime-sdk-js/classes/defaultactivespeakerpolicy.html) is updated now.

Also this [reply](https://github.com/aws/amazon-chime-sdk-js/issues/630#issuecomment-678582387) shares more information on `DefaultActiveSpeakerPolicy`.

The code for calculating score in the policy is [here](https://github.com/aws/amazon-chime-sdk-js/blob/master/src/activespeakerpolicy/DefaultActiveSpeakerPolicy.ts#L49). 

Closing this issue now. Please create an issue if you have any problems with `DefaultActiveSpeakerPolicy`.
