### ISSUE TITLE
Meeting reconnects first participant when another participant join same meeting from same machine in safari

### ISSUE THREAD

**Issue by katayal** [aws/amazon-chime-sdk-js#68]
**Important:** Please attach INFO-level logs with timestamps to the report from *before* the session started up until the point at which the unexpected behavior occured. For multi-participant calls, attach a log file for each participant if possible.

**Meeting and attendee IDs:**
List the meeting and attendee IDs that the attached logs apply to.
Conference id : cd9c6f8a-d1d2-4832-8cc6-24cb4ab948ae

**Timeline**
Outline the main actions the user performed and when:

* Join a meeting in safari
* Join the same meeting in another tab or on a different instance of safari on same machine.
* Both the participants will appear on the roster of second tab.
* After few seconds the first participant will drop from the meeting

**Describe the bug**
Describe the bug and the timestamp at which it happened relative to the timestamp in the log file.
[Warning] 2020-01-10T03:09:36.800Z [WARN] SDK - reconnection recommended due to: no packets received: true, missed pongs: false, bad audio delay: false

**Screenshots**
If applicable, add screenshots to help explain the problem.

**Platform**
 - OS: MAX
 - Browser: Safari  
 - Browser Version: 13.0.4
 - Amazon Chime SDK GitHub Commit: [976132711fa5d55783fb1d9f29a7e5240e1dc9ce]([url](url))
[safari_bu_logs_latest.log](https://github.com/aws/amazon-chime-sdk-js/files/4047602/safari_bu_logs_latest.log)

**Comment by XHatan** [comment]
Safari doesn't allow access to audio from multiple tabs of same or different windows at the same time.  Currently, meeting session relies on the flow of audio data as one factor of connection health. It's browser limitation and we don't have a good workaround around it.

**Comment by vidya-mohan** [comment]
Resolving as Won't Fix as the browser doesnt support it
