### ISSUE TITLE
extra info store in roaster

### ISSUE THREAD

**Issue by rohit0337** [aws/amazon-chime-sdk-js#685]
hello 
i am trying to implement moderation in meet and for organiser i am  in roaster add one  more key ishost 1 and 0 and identify accordingly but when new user join meeting its not getting is host value for other users how i can save  ishost values  like mute status,signal,and like name. which already in the roster. is there any way to do that.

**Comment by RidipDe** [comment]
The roster is a user/builder defined variable as we can see in the [meeting demo app](https://github.com/aws/amazon-chime-sdk-js/blob/master/demos/browser/app/meetingV2/meetingV2.ts#L732)

You can add any additional data in the line https://github.com/aws/amazon-chime-sdk-js/blob/master/demos/browser/app/meetingV2/meetingV2.ts#L760 as per the requirement and manage the variables as per need.
