### ISSUE TITLE
Sending emojis via chat during a video interview.

### ISSUE THREAD

**Issue by dhirajshrotri** [aws/amazon-chime-sdk-js#691]
I wanted to add emoji support to the default chat implementation and I wanted to know if this can be achieved. I plan on using an external emoji picker component to implement this and would get an emoji object from the picker component. I am not sure if the emoji object can be send via the `realtimeSendDataMessage` method. Or would I have to extend the method in some way to achieve this?

**Comment by ltrung** [comment]
As long as the emoji can be encoded in text, that should work. Let us know if you run into any issue.
