### ISSUE TITLE
Catching rejected promise: Unhandled Rejection subtask error

### ISSUE THREAD

**Issue by schontz** [aws/amazon-chime-sdk-js#694]
**Describe the bug**
When the WebSocket dies (e.g. computer goes to sleep and then restarts at a later time) I get the following error (webpack dev mode):

`
Unhandled Rejection (Error): serial group task AudioVideoStart/83d63887-1ef0-4558-a76f-60bfeba26205/3cf225eb-dbdc-2969-ab16-76ddfff9d665/Timeout15000ms/Media/Setup/Signaling was canceled due to subtask AudioVideoStart/83d63887-1ef0-4558-a76f-60bfeba26205/3cf225eb-dbdc-2969-ab16-76ddfff9d665/Timeout15000ms/Media/Setup/Signaling/OpenSignalingConnectionTask error: WebSocket connection failed
`

I do not know what method is the source, so I cannot catch this promise rejection.

**Platform**
 - OS: Mac OS 10.15.6
 - Browser: Chrome
 - Browser Version: 85.0.4183.102
 - Amazon Chime SDK GitHub Commit: v. 1.16.0

**Comment by ltrung** [comment]
Unfortunately, the error do not come from any SDK public methods so you would not be able to catch it.

**Comment by schontz** [comment]
I do not want to catch the error, I just don't want it to bubble up. Since it isn't caught, webpack displays a verbose error message on my web page in dev mode.
