### ISSUE TITLE
HOW TO DETECT ATTENDEE VIDEO STATE

### ISSUE THREAD

**Issue by ekpono** [aws/amazon-chime-sdk-js#703]
I'm creating a video experience and I would like to know when an attendee's video camera is off.

**Comment by ltrung** [comment]
You can subscribe to [videoTileWasRemoved](https://aws.github.io/amazon-chime-sdk-js/interfaces/audiovideoobserver.html#videotilewasremoved) event which would be triggered when a remote attendee turns off their video. The event gives you the tileId. If you want to know which attendee it is from, you would have to main your own mapping between tile Id and external attendee id in the client application.

**Comment by ekpono** [comment]
Thanks. i thought there was an API that takes care of this
