### ISSUE TITLE
[MeetingReadinessChecker] checkVideoConnectivity always results in VideoNotSent on Firefox

### ISSUE THREAD

**Issue by johanderuijter** [aws/amazon-chime-sdk-js#705]
**Meeting and attendee IDs:**
MeetingId: `86854eff-5387-4dc9-bf91-adc32334665a`
AttendeeId: `5b1eaa12-634c-e129-4109-1ff8c3e6f1dc`

**Timeline**
The whole thing is over in less then a minute while it runs the following code:
```js
const [videoInputInfo] = await meetingSession.audioVideo.listVideoInputDevices();

const videoInputFeedback = await meetingReadinessChecker.checkVideoInput(videoInputInfo.deviceId);
console.log(`Video input feedback result: ${CheckVideoInputFeedback[videoInputFeedback]}`);
// > Video input feedback result: Succeeded

const videoConnectivityFeedback = await meetingReadinessChecker.checkVideoConnectivity(videoInputInfo.deviceId);
console.log(`Video connectivity feedback result: ${CheckVideoConnectivityFeedback[videoConnectivityFeedback]}`);
// > Video connectivity feedback result: VideoNotSent
```

**Describe the bug**
The checkVideoConnectivity method of the MeetingReadinessChecker always results in VideoNotSent on Firefox. The code runs in both chrome and safari.

**Platform**
 - OS: `MacOS 10.15.6`
 - Browser: `Firefox`
 - Browser Version: `80.0.1 `
 - Amazon Chime SDK GitHub Commit: `1.17.2`

**Logs**
[MeetingReadinessChecker - Firefox - Info logs.txt](https://github.com/aws/amazon-chime-sdk-js/files/5260426/MeetingReadinessChecker.-.Firefox.-.Info.logs.txt)

**Comment by ltrung** [comment]
From the log, it seems when the local video is started, it takes 10s to finish ICE Gathering. This seems like the same as #609 
```
2020-09-22T09:25:23.208Z [INFO] MeetingReadinessChecker - running task AudioVideoUpdate/86854eff-5387-4dc9-bf91-adc32334665a/5b1eaa12-634c-e129-4109-1ff8c3e6f1dc/Timeout15000ms/UpdateSession/FinishGatheringICECandidatesTask
...
2020-09-22T09:25:34.182Z [INFO] MeetingReadinessChecker - done gathering ice candidates
2020-09-22T09:25:34.183Z [INFO] MeetingReadinessChecker - AudioVideoUpdate/86854eff-5387-4dc9-bf91-adc32334665a/5b1eaa12-634c-e129-4109-1ff8c3e6f1dc/Timeout15000ms/UpdateSession/FinishGatheringICECandidatesTask took 10975 ms
```

**Comment by ltrung** [comment]
@johanderuijter  As a temporary workaround, could you try to specify a longer timeout using the https://aws.github.io/amazon-chime-sdk-js/classes/meetingreadinesscheckerconfiguration.html#timeoutms that will be available in the next NPM package.

**Comment by anuranduttaroy** [comment]
This issue should be fixed. Feel free to re-open if you still see the issue.
