### ISSUE TITLE
Meeting disconnect

### ISSUE THREAD

**Issue by Xarno** [aws/amazon-chime-sdk-js#707]
**Describe the bug**
I have observed this error multiple times in one chime meeting room. I can not pinpoint it any further. As a result all attendies got disconnected and had to reload the page.

SDK - failed with status code RealtimeApiFailed and error: this._id is undefined ConsoleLogger.ts:72:16
    log ConsoleLogger.ts:72
    error ConsoleLogger.ts:44
    handleMeetingSessionStatus DefaultAudioVideoController.ts:692
    realtimeFatalErrorCallback MonitorTask.ts:357
    wrap DefaultRealtimeController.ts:516
    realtimeSetAttendeeIdPresence DefaultRealtimeController.ts:73
    sendRealtimeUpdatesForAudioStreamIdInfo DefaultVolumeIndicatorAdapter.ts:76
    handleSignalingClientEvent ListenForVolumeIndicatorsTask.ts:45
    sendEvent DefaultSignalingClient.ts:313
    receiveMessage DefaultSignalingClient.ts:251
    setUpEventListeners DefaultSignalingClient.ts:327
    (Async: EventListener.handleEvent)
    addEventListener DefaultWebSocketAdapter.ts:41
    setUpEventListeners DefaultSignalingClient.ts:323
    serviceConnectionRequestQueue DefaultSignalingClient.ts:286
    closeConnection DefaultSignalingClient.ts:177
    openConnection DefaultSignalingClient.ts:64

SDK - realtime error: TypeError: this._id is undefined:
log ConsoleLogger.ts:72
    error ConsoleLogger.ts:44
    realtimeFatalErrorCallback MonitorTask.ts:356
    wrap DefaultRealtimeController.ts:516
    realtimeSetAttendeeIdPresence DefaultRealtimeController.ts:73
    sendRealtimeUpdatesForAudioStreamIdInfo DefaultVolumeIndicatorAdapter.ts:76
    handleSignalingClientEvent ListenForVolumeIndicatorsTask.ts:45
    sendEvent DefaultSignalingClient.ts:313
    receiveMessage DefaultSignalingClient.ts:251
    setUpEventListeners DefaultSignalingClient.ts:327
    (Async: EventListener.handleEvent)
    addEventListener DefaultWebSocketAdapter.ts:41
    setUpEventListeners DefaultSignalingClient.ts:323
    serviceConnectionRequestQueue DefaultSignalingClient.ts:286
    closeConnection DefaultSignalingClient.ts:177
    openConnection DefaultSignalingClient.ts:64
    run OpenSignalingConnectionTask.ts:32

**Platform**
 - OS: Mac OS, but happend for all attendees
 - Browser: Firefox, but happend for all attendees
 - Browser Version: 80.0.1
 - Amazon Chime SDK GitHub Commit:    "amazon-chime-sdk-js": "^1.17.2"

**Comment by ltrung** [comment]
The code errors out from realtimeFatalErrorCallback indicates that the error comes from the callback you pass to realtimeSubscribeToAttendeeIdPresence. Could you check your code?

**Comment by schontz** [comment]
I am having a similar issue, and my code matches use case 10:

```ts
    const baseAttendeeId = new DefaultModality(attendeeId).base();
```

I assume the error is because `attendeeId` is undefined. Either the sample needs to be updated, or `DefaultModality` needs to have better error handling. A simple fix would be to update

https://github.com/aws/amazon-chime-sdk-js/blob/f10e1375c8bb46e14d5407519e1f9265b0690707/src/modality/DefaultModality.ts#L12

to:

```js
   constructor(private _id = '') {}
```

That will prevent `this._id` from being `undefined`, which breaks the class.

**Comment by devalevenkatesh** [comment]
Please check [this PR](https://github.com/aws/amazon-chime-sdk-js/pull/824) which fixed the mentioned issue. The PR also has a brief explanation on why would this issue happen.

Closing the issue, since fix is already merged and released.
