### ISSUE TITLE
AttendeeLeft event sometimes seen when reconnecting. Should be AttendeeDropped event.

### ISSUE THREAD

**Issue by dylonChime** [aws/amazon-chime-sdk-js#727]
**Describe the bug**
AttendeeLeft event sometimes seen when reconnecting. Should be AttendeeDropped event every time when reconnecting. This can be fixed by routing an audio session id to the backend audio server.

**Comment by devalevenkatesh** [comment]
Checked with @dylonChime, we can close this one.
