### ISSUE TITLE
Can i stop all audio broadcasts?

### ISSUE THREAD

**Issue by rusicsemenov** [aws/amazon-chime-sdk-js#734]
Hello, i have issue with audio stream. Sometimes when user leave meeting, i still hear him. Can i stop all active audio stream by one command? Or can i kick user from meeting?

I can get all active tiles by `meetingSession.audioVideo.getAllVideoTiles()` but how a can kick somebody from meeting?

**Comment by anuranduttaroy** [comment]
Hey @rusicsemenov, I see 2 questions here. 

**Q1: Can i stop all active audio stream by one command?**

If you mean `Remote Mute` by stop all active audio streams, then the answer is No. This feature is currently not supported server-side by the SDK. There is an open issue for the same: https://github.com/aws/amazon-chime-sdk-js/issues/237

Read more (FAQ): [Does the SDK support remote mute where one attendee can mute another?](https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html#does-the-sdk-support-remote-mute-where-one-attendee-can-mute-another)

However, in this comment (https://github.com/aws/amazon-chime-sdk-js/issues/237#issuecomment-612202974), @simmkyu gave an example how remote mute is enabled in one of the demo applications which uses [amazon-chime-sdk-js](https://github.com/aws/amazon-chime-sdk-js)


**Q2: how a can kick somebody from meeting?**
Currently, the [amazon-chime-sdk-js](https://github.com/aws/amazon-chime-sdk-js) does not support kicking an attendee out from a meeting. 

Again, the builder can implement this using the data message feature. Similar to the comment here https://github.com/aws/amazon-chime-sdk-js/issues/688#issuecomment-693701864 where @RidipDe explains how to use Data Messages to turn ON/OFF remote video, builders can use it to send out a message with the attendee-id and the app can handle it by kicking out the attendee whose attendee-id matches with it.

**Comment by p-foucht** [comment]
Resolving - feel free to re-open if necessary
