### ISSUE TITLE
Solution to allow more attendee video streams not displayed all at once 

### ISSUE THREAD

**Issue by francisco-campas** [aws/amazon-chime-sdk-js#737]
### What are you trying to do?
We are looking into a solution to allow more than 16 attendees to share video input.  While we only intend to display 12 tiles at once and paginate through them as needed, we still need to exceed the number of allowed video streams.

Given the constraints of a maximum of 16 simultaneous video streams, could it be possible to allow more streams service-side or with some custom logic?  I found a [proposed solution](https://medium.com/@dannadori/amazon-chime-sdk-with-over-16-video-sessions-749fc192ab38) that involves creating multiple meetings to delegate video sessions as they appear on the UI.  

1. **Are there any known complications when connecting users to multiple meetings at a time?**
2. **Is the Chime SDK maximum video streams a service-side limit or only in place due to client-side limitations?**

Any input or other possible direction is appreciated. Thanks.

### How can the documentation be improved to help your use case? 
N/A. Documentation is clear.

### What documentation have you looked at so far?
- https://github.com/aws/amazon-chime-sdk-js/issues
- Amazon Chime SDK Developer Guide
- https://github.com/aws-samples/amazon-chime-meeting-broadcast-demo
- https://aws.amazon.com/blogs/opensource/how-to-deploy-a-live-events-solution-built-with-the-amazon-chime-sdk/
- https://aws.amazon.com/chime/chime-sdk/features/

**Comment by devalevenkatesh** [comment]
Just to add you can also come via the AWS support channel to discuss your app specific use case.

**Comment by devalevenkatesh** [comment]
We recently released a guide on managing video layout and looks like your use case fits it:
https://aws.github.io/amazon-chime-sdk-js/modules/videolayout.html

Could you please check once and see if it help with your use case.

**Comment by dnnejo** [comment]
You can now have up to 100 people with webcam video active, and each client select up to 25 to display.
https://aws.amazon.com/about-aws/whats-new/2022/06/amazon-chime-sdk-supports-100-webcam-video-streams/

If this does not satisfy your use case, do reopen.
