### ISSUE TITLE
Meeting ends if Screen share viewer connections are inactive for more than 30 minutes.

### ISSUE THREAD

**Issue by masaka222** [aws/amazon-chime-sdk-js#739]
**Describe the bug**
Just read in the Documentation that DeleteMeeting API get's triggered if "Screen share viewer connections are inactive for more than 30 minutes".

Is this correct? I think that there can be situations where Screen sharing can be inactive for more than that. 
For example if the presenter is a teacher and explains a specific slide for some time and also gives time for the students to make questions or solve a problem.

**Documentation**
https://docs.aws.amazon.com/chime/latest/dg/mtgs-sdk-mtgs.html

**Comment by ltrung** [comment]
@masaka222 The screenshare in the doc refers to the [legacy screenshare](https://github.com/aws/amazon-chime-sdk-js/tree/master/src/screenshareviewfacade). Content share should not trigger meeting end if there is audio in the call.

**Comment by masaka222** [comment]
@ltrung Thanks for the clarification!

**Comment by devalevenkatesh** [comment]
We are closing on this issue, please feel free to re-open if content share is not working for you or you have more questions. 

Also you can check information about using content share in the README below:
https://github.com/aws/amazon-chime-sdk-js#screen-and-content-share
