### ISSUE TITLE
Add more info on DataMessage throttling

### ISSUE THREAD

**Issue by yousefamar** [aws/amazon-chime-sdk-js#754]
### What are you trying to do?

I'm trying to decide if certain metadata should be sent through `realtimeSendDataMessage` or out-of-band, but don't know if it's feasible as there is no info on the nature of throttling.

### How can the documentation be improved to help your use case?

Give a hard number as to how frequent "too many" is.

### What documentation have you looked at so far?

All I could find is this:

> If you send too many messages at once, your messages may be returned to you with the throttled flag set. If you continue to exceed the throttle limit, then the server may hang up the connection.

**Comment by anuranduttaroy** [comment]
Hey @yousefamar, the current throttling limits for Data Messages is `Rate:100 Burst:200`. I will update the API doc with this number.

**Comment by yousefamar** [comment]
Thanks, is that 100 messages per second per attendee? And what does Burst mean and for how long can that be sustained?

**Comment by anuranduttaroy** [comment]
Amazon Chime uses the token bucket algorithm (https://en.wikipedia.org/wiki/Token_bucket) to implement throttling. With this algorithm, there is bucket that holds a specific number of tokens. The number of tokens in the bucket represents your throttling limit at any given second.

The burst rate is the initial number of tokens in the bucket and the maximum number of tokens in the bucket. The sustained rate is the number of tokens replenished each second. 

The data message rate limit is applied to all data messages in a single meeting. e.g 100 data messages / second / meeting.

**Comment by anuranduttaroy** [comment]
Feel free to re-open if you have more questions.

**Comment by ahnytae** [comment]
@anuranduttaroy  Hi,
Why is realtimeSendDataMessage limited to 2KB?

I want to send more than 2KB of data.
Is there anything bad about exceeding 2KB?

**Comment by ahnytae** [comment]
> Feel free to re-open if you have more questions.

@anuranduttaroy 
Hi,
Why is realtimeSendDataMessage limited to 2KB?

I want to send more than 2KB of data.
Is there anything bad about exceeding 2KB?
