### ISSUE TITLE
Mic Control and echo issue in Mac

### ISSUE THREAD

**Issue by sidharth-sid** [aws/amazon-chime-sdk-js#756]
"Input Mic on/off toggle appears in all browsers in Mac machine which comes in the window and in system active task pane (as shown in the image attached) which causes echo and centralized Mic control issue"
Is there anything we can configure to prevent this from showing in the Mac device/browsers?

![image](https://user-images.githubusercontent.com/43243364/95091158-ba9d3400-0743-11eb-87ce-6d8ae94dfd10.png)

**Platform**
 - OS: 
 - Browser: Safari, Chrome
 - Browser Version: Latest

@vidya-mohan

**Comment by vidya-mohan** [comment]
@sidharth-sid - is this still an issue? please reopen if so.
