### ISSUE TITLE
CORS Issue with turn_session

### ISSUE THREAD

**Issue by mmmaxi** [aws/amazon-chime-sdk-js#768]
From time to time we have the issue that requests to the chime.aws service are blocked due to CORS issues. 

Access to fetch at 'https://ccp.cp.ue1.app.chime.aws/v2/turn_sessions?X-Amzn-Version=1.17.1&X-Amzn-User-Agent=edge-chromium-83' from origin 'https://xxxx' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

**Platform**
 - This seems to happen on several platforms.

**Comment by anuranduttaroy** [comment]
We have recently changes the way we vend TURN Credentials. It was merged in npm version 1.19.0 as part of this PR: https://github.com/aws/amazon-chime-sdk-js/pull/712

Could you try updating to [amazon-chime-sdk-js](https://www.npmjs.com/package/amazon-chime-sdk-js) version 1.19.0 and see if this issue still exists?

**Comment by p-foucht** [comment]
Closing, feel free to re-open if necessary
