### ISSUE TITLE
Change bandwidth on the fly

### ISSUE THREAD

**Issue by MaxQuantumCake** [aws/amazon-chime-sdk-js#777]
Hi,

It would be great to be able to change the bandwidth in real-time according to different situations.

Currently, it is necessary to stop and then restart the local video by calling the `chooseVideoInputQuality function`. The rendering at the end-user level is not very good.

Could you get some inspiration from this example based on the WebRTC online API : [here](https://webrtc.github.io/samples/src/content/peerconnection/bandwidth/)

Best regards,

MQC

**Comment by XHatan** [comment]
Hi, MQC

```chooseVideoInputQuality```  changes bitrates on the fly https://github.com/aws/amazon-chime-sdk-js/blame/master/guides/04_Quality_Bandwidth_Connectivity.md#L73.  Does it not work for you ?

**Comment by MaxQuantumCake** [comment]
Hi XHatan,

Thank you for your answer. `chooseVideoInputQuality` is the function I was talking about in my first comment. From what I understand, it is necessary to stop the video, configure the new settings and restart the video. It causes the interruption of the video stream, which I don't want for the user experience. Am I right?

In the URL I gave you previously, the bandwidth changes on the fly, without interruption of the video track, which is, in my opinion, more suitable for a videoconferencing solution.
