### ISSUE TITLE
Improve CHANGELOG conflict handling

### ISSUE THREAD

**Issue by rnewman** [aws/amazon-chime-sdk-js#780]
Having a CHANGELOG is great. However, having a CHANGELOG change in every commit means that essentially every change results in a merge/rebase conflict. That's painful for developers and costly in CI time.

We should find a way to minimize this cost. I'm not proposing a particular solution — perhaps we should only require CHANGELOG entries for code changes that builders will care about (not for scripts or tests), because there's a super great change log accessible by running `git log`, or we should synthesize a changelog by grepping for metadata in commit messages — but this is definitely a rough edge to fix.

@Pfoucht FYI.

**Comment by rnewman** [comment]
btw, my concrete suggestion, now that Peyton and I talked about it:

* Add optional CHANGELOG metadata to commit messages.
* Write a tool to take a commit range and generate a CHANGELOG.
* Run this on each release, committing the results. Now the CHANGELOG is guaranteed to match the changes in the release!
* Customers can run the tool to get a customized log of everything that happened since they last upgraded.

**Comment by ltrung** [comment]
#894 has removed CHANGELOG requirements for demo and test changes. We will work on improving handling CHANGELOG conflict.
