### ISSUE TITLE
Feature Request - virtual background and noise suppression 

### ISSUE THREAD

**Issue by cjeremylin** [aws/amazon-chime-sdk-js#783]
Hi Team, 

Do we have any plan or road map for these two feature which has been announced in Chime and bring them into Chime SDK ? 

Thank you.

**Comment by SohanChoudhury** [comment]
Any update on this? Coming up on 2 months.

**Comment by CrystalMethod** [comment]
Please have a look at #911. With this coming you're able to do any client side media processing like virtual backgrounds.

**Comment by ltrung** [comment]
As @CrystalMethod mentioned, you can use video processor API introduced in #953 to add client media processing for virtual background. Voice Focus API added in v2.0. 
Please checkout  [Voice Focus](https://github.com/aws/amazon-chime-sdk-js/blob/master/guides/09_Amazon_Voice_Focus.md) and [Video Processing](https://github.com/aws/amazon-chime-sdk-js/blob/master/guides/10_Video_Processor.md) guides.
