### ISSUE TITLE
Speaker dropdown list only has "Device Selection unavailable" in firefox [Meeting Readiness Checker]

### ISSUE THREAD

**Issue by stanggt3** [aws/amazon-chime-sdk-js#784]
In Firefox, the speaker dropdown list only ever has a value of Device Selection unavailable.

If you proceed with the checker, you can hear the sound as expected.

![image](https://user-images.githubusercontent.com/4763946/96161250-06d73980-0ee5-11eb-9d26-3debd2c9d4ce.png)

**Platform**
OS: Windows 10
Browser: Firefox
Browser Version: 80.0.2
Amazon Chime SDK Version: Latest build #781

**Comment by p-foucht** [comment]
Hi @stanggt3 

This is a known issue -- Firefox does not support speaker device selection, but the actual audio output will still work normally. [See this page for details](https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html#i-am-unable-to-select-an-audio-output-device-in-some-browsers-is-this-a-known-issue)

**Comment by p-foucht** [comment]
Closing as this is expected behavior, feel free to reopen if necessary
