### ISSUE TITLE
Chime remove meeting auto

### ISSUE THREAD

**Issue by Cheban1996** [aws/amazon-chime-sdk-js#786]
After create meeting
```
 meeting_data = chime.create_meeting(
            ClientRequestToken=str(uuid4()),
            MediaRegion=MeetingRoom.region,
            ExternalMeetingId=name[0:64]
)
``` 
After  that time I make create attende, and get next error:
`[ErrorDetail(string='An error occurred (NotFoundException) when calling the CreateAttendee operation: Meeting <db8e0e76-0ba0-46f5-8fda-69d102f8be45> not found', code='invalid')]`

**Comment by p-foucht** [comment]
So you are successfully calling create_meeting and the meeting data returns is as expected?

Are you calling createAttendee right after, or at a later time? There are some auto-end policies that could affect be ending your createAttendee call, [(details here)](https://docs.aws.amazon.com/chime/latest/dg/mtgs-sdk-mtgs.html). Could you add a bit more detail about how you're calling `createAttendee`?

**Comment by devalevenkatesh** [comment]
Hello @Cheban1996 ,

We are closing this issue. Please feel free to re-open if you are still facing this issue.
