### ISSUE TITLE
Is there any way to get event of remote video has stopped sending data ?

### ISSUE THREAD

**Issue by vibhakchosla** [aws/amazon-chime-sdk-js#787]
We have implemented chime sdk in web and android client. when i starts my local video using android sdk on low bandwidth, i can get remote user video on my web client initially and after some time on my web client the video tile becomes blank.

on web client `videoNotReceivingEnoughData` observer i am getting `receivedAverageBitrateKbps` 0.

So, is there any way to get to notify remote user video is not sending tracks so that i can hide video element instead of displaying blank video tile. and display video again when i start get video streams for that user.

**Comment by p-foucht** [comment]
Hi @vibhakchosla,

While there is not an inverse API of `videoNotReceivingEnoughData`, you could use the [`metricsDidReceive`](https://aws.github.io/amazon-chime-sdk-js/interfaces/audiovideoobserver.html#metricsdidreceive) listener to accomplish this. You would need to track/compare the previous metrics with the incoming metrics for each attendee

**Comment by vibhakchosla** [comment]
Thanks for reply!!!
what exactly should i compare from `metricsDidReceive` to check video is comming or not ?

**Comment by p-foucht** [comment]
I believe you would want to be comparing the `bytesReceived`data

You can reference how the SDK determines to fire the `videoNotReceivingEnoughData` by [checking out this method](https://github.com/aws/amazon-chime-sdk-js/blob/1fff9b7050c63daf0935ee048df5f10f4efbb4ca/src/task/MonitorTask.ts#L214-L232). You would need to do something similar, but also add the logic for when videos have gone from "notEnoughData" to "enoughData"
