### ISSUE TITLE
video tile are automatically removed and return joined after sometimes later

### ISSUE THREAD

**Issue by ajith4ab** [aws/amazon-chime-sdk-js#789]
` 

    audioVideoDidStart() {
        this.log('session started');

    }

    audioVideoDidStop(sessionStatus) {
        this.log(`session stopped from ${JSON.stringify(sessionStatus)}`);
        if (sessionStatus.statusCode() === MeetingSessionStatusCode.AudioCallEnded) {
        
        }
    }

    videoTileDidUpdate(tileState) {
        this.log(`video tile updated: ${JSON.stringify(tileState, null, '  ')}`);
        if (!tileState.boundAttendeeId) {
            return;
        }
        if (tileState.localTile && tileState.boundVideoStream) {
            
        } else if (tileState.boundVideoStream) {
           
        };
    }

    videoTileWasRemoved = tileId => {
        console.log("disconnected", tileId)
       
    }`

**Comment by p-foucht** [comment]
Could you provide a bit more detail on what is happening? 

It would also help if you could provide info level logs, as well as confirm if you see the same behavior in the demo application within this repo.

**Comment by anuranduttaroy** [comment]
@ajith4ab feel free to re-open if this is still an issue.
