### ISSUE TITLE
No Chat Documentation For React App

### ISSUE THREAD

**Issue by pawanlakhera77** [aws/amazon-chime-sdk-js#790]
I 'm trying to implement the Amazon chime using the Amazon Chime React SDK Library. I got success in creating and joining the Meeting.
I think the Chime React SDK documentation is incomplete. There is no documentation or components for the Chat functionality.
Moreover if I want to implement some amazon chime js sdk function in react App is that possible and how ?

I am following this link : https://github.com/aws/amazon-chime-sdk-component-library-react

**Comment by p-foucht** [comment]
Closing this in favor of the [ticket filed in the React repo](https://github.com/aws/amazon-chime-sdk-component-library-react/issues/244)
