### ISSUE TITLE
AttendeeId undefined causes fatal RealtimeApiFailed for all other Attendees

### ISSUE THREAD

**Issue by afgiel** [aws/amazon-chime-sdk-js#793]
**Describe the bug**
One meeting attendee connecting/reconnecting can crash the meeting for all other attendees by causing an error within the realtime api attendee presence callback. 

**Meeting and attendee IDs:**
Meeting ID: `d76c912b-4e1f-40ab-98a7-cfb84ef8b15d`
Attendees: `517eb3b1-e22f-0cf5-f8fb-646cf40fa435` (**Attendee A**) & `590bf7f4-c3b1-abbf-2147-2f3f5ab2c419` (**Attendee B**) 

**Timeline**
Our application allows for connecting and disconnecting from the Chime meeting. While testing this flow, both Attendees A & B were connecting, disconnecting, and reconnecting. 

At some point in this testing, Attendee A reconnected, and simulatenously Attendee B was disconnected with the following error:
```
index.js:1 2020-10-19T18:10:03.336Z [ERROR] ChimeLogger - realtime error: TypeError: Cannot read property 'split' of undefined: TypeError: Cannot read property 'split' of undefined
    at DefaultModality.base (http://localhost:3000/static/js/0.chunk.js:98524:21)
    at http://localhost:3000/static/js/0.chunk.js:90349:70
    at http://localhost:3000/static/js/0.chunk.js:100055:11
    at DefaultRealtimeController.wrap (http://localhost:3000/static/js/0.chunk.js:100636:7)
    at DefaultRealtimeController.realtimeSetAttendeeIdPresence (http://localhost:3000/static/js/0.chunk.js:100045:10)
    at DefaultVolumeIndicatorAdapter.sendRealtimeUpdatesForAudioStreamIdInfo (http://localhost:3000/static/js/0.chunk.js:128235:37)
    at ListenForVolumeIndicatorsTask.handleSignalingClientEvent (http://localhost:3000/static/js/0.chunk.js:118105:43)
    at DefaultSignalingClient.sendEvent (http://localhost:3000/static/js/0.chunk.js:105649:18)
    at DefaultSignalingClient.receiveMessage (http://localhost:3000/static/js/0.chunk.js:105584:12)
    at WebSocket.<anonymous> (http://localhost:3000/static/js/0.chunk.js:105677:13)
    at WebSocket.sentryWrapped (http://localhost:3000/static/js/0.chunk.js:45908:17)
```

it's clear from this stack trace that this flow is causing a condition by which a stream `attendeeId` is undefined, `ReceiveVideoStreamIndexTask.handleIndexFrame` is triggered, [the modality is checked](https://github.com/aws/amazon-chime-sdk-js/blob/master/src/task/ReceiveVideoStreamIndexTask.ts#L65), and the realtime callback ultimately crashes within `DefaultModality.base`. This was confirmed via simple console log within the `realtimeSubscribeToAttendeeIdPresence`, logging `attendeeId: undefined`. 

I have created Pastebin links of more verbose/descriptive logs for [Attendee A here](https://pastebin.com/ipitViik) and [Attendee B here](https://pastebin.com/DpUfZe0j)

**Platform**
 - OS: OSX 10.14.6
 - Browser: Chrome
 - Browser Version:  86.0.4240.80
 - Amazon Chime SDK GitHub Commit: `dd77b0deadd3221e1c0e75cea2d63da3843dd977` (`v1.19.0`)

**Comment by devalevenkatesh** [comment]
Hello @afgiel ,

Thanks for your investigation on this issue as well as the PR to mitigate it. We will try to re-produce this issue and figure out what and where should be the most correct fix. 

A probable cause may be the clearing out of the `attendeeId` when certain JOIN / LEAVE events occur. It would be helpful if you could provide what testing steps you carried that ran into this issue.

As part of this issue we may also need to fix the `DefaultModality.base()` method to try avoiding the `undefined` scenario, but since it is dependent on the main issue of `attendeeId` being set to `undefined` we need to fix that first. Thanks again.

**Comment by afgiel** [comment]
thank you, @devalevenkatesh. 

to reproduce this issue I was rapidly joining/leaving/rejoining the meeting, which supports your hypothesis of `attendeeId` being cleared on join/leave events.

**Comment by devalevenkatesh** [comment]
Thanks for your help, we have merged #824 with a fix. Closing this issue now.

**Comment by Leeaandrob** [comment]
@devalevenkatesh is continuing happening the same problem using version 2.9.0.

![image](https://user-images.githubusercontent.com/5758136/118260827-289f9b80-b489-11eb-886a-bd28a9228d98.png)

**Comment by devalevenkatesh** [comment]
Hello @Leeaandrob, thanks for reporting the issue here. It looks the reason was different for the closed issue. We would appreciate if you could create a new one for the issue you are facing with our issue format.
