### ISSUE TITLE
Support for Samsung Browsers

### ISSUE THREAD

**Issue by vidya-mohan** [aws/amazon-chime-sdk-js#802]
Currently Samsung is not officially supported: https://docs.aws.amazon.com/chime/latest/dg/meetings-sdk.html#mtg-browsers

This issue tracks official support for samsung browsers.

**Comment by tarunkolla** [comment]
Any update on when we can expect this to be released?

**Comment by devalevenkatesh** [comment]
Hello @tarunkolla ,

We have released [amazon-chime-sdk-js](https://www.npmjs.com/package/amazon-chime-sdk-js)  v2.3.0 to NPM now with the Samsung Internet browser support. 

Please checkout our [FAQs](https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html#i-am-not-able-to-join-an-amazon-chime-sdk-meeting-from-an-android-11-device-running-chromium-83-based-browsers-such-as-samsung-internet-version-13-or-chrome-version-83-is-this-a-known-issue) and feel free to report any issues you face.
