### ISSUE TITLE
Audio is not hear to attendees when video shared through screen share

### ISSUE THREAD

**Issue by riteshsc** [aws/amazon-chime-sdk-js#803]
Hi,

I am using demo meeting application. When i am sharing the screen and show the video from my screen(desktop) then other attendees can able to see the video but not able to hear sound of played video from headset. But during that if i talk then they are able to here me.

Can you please help to resolve this issue.

**Comment by devalevenkatesh** [comment]
Hello @riteshsc ,

You can select screen share via browser tab to share audio in Chrome and chromium based Edge browser. These browsers will show you a check box for sharing audio with screen share (browser tab).

Please let us know if this helps your use case.

**Comment by riteshsc** [comment]
Hi, Can you please add screenshot of setting(check box for sharing audio with screen share) on chrome/Edge. Actually I have tried to search it, but not found settings.
Thanks in Advance!

**Comment by devalevenkatesh** [comment]
Hello @riteshsc ,

Sorry for not providing the screenshot in the last comment. Attaching here.
![share audio screenshot from chrome tab](https://user-images.githubusercontent.com/61809205/97203226-c5128280-1771-11eb-958f-62ffed674993.png)

**Comment by devalevenkatesh** [comment]
Please let us know if you need more information. Closing this issue now since not much can be done further. Request you to re-open if you need more help on this or file a new issue if you face a different problem.

**Comment by riteshsc** [comment]
Hi, When I have checked then option of "share audio" checkbox is not displayed.
