### ISSUE TITLE
I can't change output audio device.

### ISSUE THREAD

**Issue by ktarasov-clearscale** [aws/amazon-chime-sdk-js#808]
I've got a list of devices with `audioVideo.listAudioOutputDevices()`. It's not empty.
I can change the input audio device (microphone). 
But I can't change the output audio device with `audioVideo.chooseAudioOutputDevice(deviceId)`.
It is not working.
I can see in logs that chime switches the device. But no output sound.
```
ConsoleLogger.js:69 2020-10-23T09:09:24.369Z [INFO] sfm-chime-logger - API/DefaultAudioVideoFacade/6bbde525-3ee1-4122-a213-11496d812dc0/a3c4d1fb-cd1e-e339-2833-de6a2a6f5075/chooseAudioOutputDevice "2ce319b6d10ec4d27fee3bab0c9143c1437cbeb1060b554477321767ac405808"
```
Meanwhile, changing the device in system settings works well.

I tried to use `DefaultAudioMixController` and bind it to the same `deviceId`:
`audioMixController.bindAudioDevice({ deviceId });`
Audio output works well in that case.
The device switching works.

Is there a way to change audio output in a browser?
Or I can do it using system settings only.

---
Platform is: 
Chrome 78.0.3904.70 (64-bit) on Ubuntu 16.08.
Same in Firefox 82.0 (64 bit).

**Comment by devalevenkatesh** [comment]
Yes, you can change the audio output devices in the browser.

Can you once check our [demo meeting app](https://github.com/aws/amazon-chime-sdk-js/tree/master/demos/browser) and run the default meetingV2 app (instructions are in README). When in meeting we do have an option for user to change the audio output which provides a dropdown HTML select menu of available audio output devices to choose.

Upon the audio output selection change [here](https://github.com/aws/amazon-chime-sdk-js/blob/master/demos/browser/app/meetingV2/meetingV2.ts#L361) we call a method internal to demo [openAudioOutputFromSelection](https://github.com/aws/amazon-chime-sdk-js/blob/d5e9d4d2658283a3bf87da4b20b8b57a7fcf9dfb/demos/browser/app/meetingV2/meetingV2.ts#L1231)
which calls `audioVideo.chooseAudioOutputDevice` with the currently selected audio output device value and then we use `audioVideo.bindAudioElement` to bind the HTML audio element.

Request you to try this approach and let us know if it works for you.

**Comment by ktarasov-clearscale** [comment]
@devalevenkatesh, thank you for your explanations. Seems everything works properly now. 

I expected `chooseAudioOutputDevice()` should do the magic and switch the output audio. But this is not enough. You should re-bind the audio as well.

Noticed that `bindAudioElement` method in the example is [not async](https://github.com/aws/amazon-chime-sdk-js/blob/d5e9d4d2658283a3bf87da4b20b8b57a7fcf9dfb/src/audiomixcontroller/DefaultAudioMixController.ts#L14) though.
Need to [remove](https://github.com/aws/amazon-chime-sdk-js/blob/d5e9d4d2658283a3bf87da4b20b8b57a7fcf9dfb/demos/browser/app/meetingV2/meetingV2.ts#L1235) `await`.

Don't know if it is possible locally...
- Connect two headsets.
- Open two tabs and join to the same meeting on each tab.
- Set up a user1 (on a first tab) uses headset1 and user2 uses headset2.

Result:
- You can use only a single headset in a moment (second is muted).
Desirable: 
- You can use both headsets.

**Comment by anuranduttaroy** [comment]
Hey @ktarasov-clearscale, with the [amazon-chime-sdk-js](https://www.npmjs.com/package/amazon-chime-sdk-js/v/2.0.0) release 2.0.0, we have made the `bindAudioElement()` API async. Read more about this here [Migration from SDK v1 to SDK v2](https://aws.github.io/amazon-chime-sdk-js/modules/migrationto_2_0.html#update-bindaudioelement-bindaudiostream-and-bindaudiodevice-to-return-promiseltvoidgt-instead-of-boolean)

**Comment by p-foucht** [comment]
Closing since the issue was addressed and the ticket has been inactive
