### ISSUE TITLE
Session not starting on safari

### ISSUE THREAD

**Issue by sanjayng007** [aws/amazon-chime-sdk-js#809]
**What are you trying to do?**
Start a meeting session on Safari
the session is not getting started on safari, **Works fine on Chrome, Firefox, Edge**

**Describe the bug**
whenever I try to start a meeting session on safari it keeps on waiting then throws the following error

`failed with status code TaskFailed and error: serial group task AudioVideoStart/391f52c9-22c2-47f2-a0a4-270ecf353ef8/755afba8-6162-f9d4-c49e-7a96f063c0ed was canceled due to subtask AudioVideoStart/391f52c9-22c2-47f2-a0a4-270ecf353ef8/755afba8-6162-f9d4-c49e-7a96f063c0ed/Timeout15000ms error: serial group task AudioVideoStart/391f52c9-22c2-47f2-a0a4-270ecf353ef8/755afba8-6162-f9d4-c49e-7a96f063c0ed/Timeout15000ms/Media was canceled due to subtask AudioVideoStart/391f52c9-22c2-47f2-a0a4-270ecf353ef8/755afba8-6162-f9d4-c49e-7a96f063c0ed/Timeout15000ms/Media/Peer error: serial group task AudioVideoStart/391f52c9-22c2-47f2-a0a4-270ecf353ef8/755afba8-6162-f9d4-c49e-7a96f063c0ed/Timeout15000ms/Media/Peer was canceled due to subtask AudioVideoStart/391f52c9-22c2-47f2-a0a4-270ecf353ef8/755afba8-6162-f9d4-c49e-7a96f063c0ed/Timeout15000ms/Media/Peer/FinishGatheringICECandidatesTask error: canceling AudioVideoStart/391f52c9-22c2-47f2-a0a4-270ecf353ef8/755afba8-6162-f9d4-c49e-7a96f063c0ed/Timeout15000ms/Media/Peer/FinishGatheringICECandidatesTask`

**Platform**
 - OS: macOS Mojave
 - Browser: Safari
 - Browser Version:  12.1.1
 - app is in Angular 8.3.20

**Debug Logs**
[safari_log.log](https://github.com/aws/amazon-chime-sdk-js/files/5429658/safari_log.log)

**Comment by anuranduttaroy** [comment]
Looking at the logs, it seems like the `FinishGatheringICECandidatesTask` is timing out. Could you try out the [serverless demo app](https://github.com/aws/amazon-chime-sdk-js/tree/master/demos/serverless) with the same setup i.e OS: macOS Mojave, Browser: Safari & Browser Version: 12.1.1 to see if it fails there as well?

The instructions to deploy the serverless app is given here: https://github.com/aws/amazon-chime-sdk-js/tree/master/demos/serverless#meeting-app

**Comment by sanjayng007** [comment]
I tried the serverless demo it's working on the same system,
so apparently I am making some mistake, but the error being thrown is taking me know-where can you provide me with some info about the error like what can be the possible reasons for this error so that I can look in that direction.

**Comment by sanjayng007** [comment]
my code for starting the session

`async initConference() {
    try {
      /**
       * setup logger
       */
      this.logger = new ConsoleLogger('Conference', LogLevel.ERROR);
      this.deviceController = new DefaultDeviceController(this.logger);

      /**
       * get meeting and attendee object from service
       */
      this.meetingMeta = this.conference.metaData.meeting.aws_meeting_details as AwsMeetingDetails;
      this.attendeeMeta = this.conference.metaData.meeting.participant.access.aws_attendee_details as AwsAttendeeDetails;

      /**
       * create meeting config
       */
      this.configuration = new MeetingSessionConfiguration(this.meetingMeta, this.attendeeMeta);

      /**
       * create meeting session
       */
      this.createMeetingSession();
      this.cdr.detectChanges();

      /**
       * fetch media devices list
       */
      await this.controlPanel.getAVDevices();

      /**
       * initialize av
       */
      await this.controlPanel.initializeAudio();// bindAudioElement => chooseAudioInputDevice(first device)
      await this.controlPanel.initializeVideo();//  chooseVideoInputDevice (first device)

      /**
       * bind event listener to meeting
       */
      this.gridComp.setAudioVideoObserver(); // audioVideo.addObserver
      this.gridComp.setAttendeeObserver(); // audioVideo.addObserver
      this.gridComp.setContentShareObserver(); // audioVideo.addContentShareObserver
      this.meetingSession.audioVideo.addObserver(this.closeObserver); // audioVideo.addObserver

      this.meetingSession.audioVideo.start();

    } catch (error) {
      console.error(error);
      this.router.navigate(['meeting']);
    }
  }

createMeetingSession() {
    this.meetingSession = new DefaultMeetingSession(this.configuration, this.logger, this.deviceController);
 }
`

**Comment by sanjayng007** [comment]
Below is the code that I am using to start the session
`
async initConference() {
    try {
      /**
       * setup logger
       */
      this.logger = new ConsoleLogger('Conference', LogLevel.ERROR);
      this.deviceController = new DefaultDeviceController(this.logger);

      /**
       * get meeting and attendee object from service
       */
      this.meetingMeta = this.conference.metaData.meeting.aws_meeting_details as AwsMeetingDetails;
      this.attendeeMeta = this.conference.metaData.meeting.participant.access.aws_attendee_details as AwsAttendeeDetails;

      /**
       * create meeting config
       */
      this.configuration = new MeetingSessionConfiguration(this.meetingMeta, this.attendeeMeta);

      /**
       * create meeting session
       */
      this.createMeetingSession();
      this.cdr.detectChanges();

      /**
       * fetch media devices list
       */
      await this.controlPanel.getAVDevices();

      /**
       * initialize av
       */
      await this.controlPanel.initializeAudio();// bindAudioElement => chooseAudioInputDevice(first device)
      await this.controlPanel.initializeVideo();//  chooseVideoInputDevice (first device)

      /**
       * bind event listener to meeting
       */
      this.gridComp.setAudioVideoObserver(); // audioVideo.addObserver
      this.gridComp.setAttendeeObserver(); // audioVideo.addObserver
      this.gridComp.setContentShareObserver(); // audioVideo.addContentShareObserver
      this.meetingSession.audioVideo.addObserver(this.closeObserver); // audioVideo.addObserver

      this.meetingSession.audioVideo.start();

    } catch (error) {
      console.error(error);
      this.router.navigate(['meeting']);
    }
  }

createMeetingSession() {
    this.meetingSession = new DefaultMeetingSession(this.configuration, this.logger, this.deviceController);
 }
`

**Comment by sanjayng007** [comment]
below is the code that i am using to start session
![image](https://user-images.githubusercontent.com/17921952/97218398-a4d4d900-17ee-11eb-92a0-bf1016942134.png)
![image](https://user-images.githubusercontent.com/17921952/97218424-af8f6e00-17ee-11eb-9beb-890882ef3795.png)

**Comment by sanjayng007** [comment]
Below is the code that i am using to start session

![image](https://user-images.githubusercontent.com/17921952/97218613-ebc2ce80-17ee-11eb-85e5-b6630cd1e6ca.png)
![image](https://user-images.githubusercontent.com/17921952/97218631-f1201900-17ee-11eb-9f24-ef1e98a19197.png)

**Comment by devalevenkatesh** [comment]
Hello @sanjayng007 ,

The above code should work do not see any problem. I am not sure what your `this.controlPanel` or `this.gridComp` is doing exactly so cannot see why this is not working. 

Since you said the deployed demo app is working, can you go through SDK's [demo app](https://github.com/aws/amazon-chime-sdk-js/tree/master/demos/browser). This demo app is the one that is deployed. Also check the `meetingV2` version specifically. 

Further, if it is running as expected on the same config as you tried with the serverless one, then request you to check [initializeMeetingSession](https://github.com/aws/amazon-chime-sdk-js/blob/master/demos/browser/app/meetingV2/meetingV2.ts#L688) which initializes the meeting session in the demo app.

> Note: You may also try upgrading Safari / Mac to latest version and see if the issue still persists. I am on macOS Catalina with Safari version: Version 14.0 and did not observer this issue with the SDK demo app.

Let us know if this helps you.

**Comment by sanjayng007** [comment]
Hi @devalevenkatesh for your reference I am attaching the code from `this.controlPanel` or `this.gridComp` 

**this.controlPanel.getAVDevices**
![image](https://user-images.githubusercontent.com/17921952/97302213-c2ea1a00-187e-11eb-9d27-0564cdc5ed40.png)

**this.controlPanel.initializeAudio** (you can assume that this will only execute `audioVideo.bindAudioElement`)
![image](https://user-images.githubusercontent.com/17921952/97303092-f2e5ed00-187f-11eb-93aa-eb8a081baeca.png)


**this.controlPanel.initializeVideo**  (you can assume this code is doing nothing at this moment)
![image](https://user-images.githubusercontent.com/17921952/97302984-ca5df300-187f-11eb-9511-0df74bd3c4b8.png)

I think observers are irrelevant (as the meeting itself is not getting started) but still below is the code

**this.gridComp.setAudioVideoObserver**
![image](https://user-images.githubusercontent.com/17921952/97303399-5cfe9200-1880-11eb-9cb7-8df469192de9.png)

**this.gridComp.setAttendeeObserver**
![image](https://user-images.githubusercontent.com/17921952/97303483-743d7f80-1880-11eb-9703-f5765ef7f676.png)

**this.gridComp.setContentShareObserver**
![image](https://user-images.githubusercontent.com/17921952/97303603-9f27d380-1880-11eb-923a-ecd5a710f2fd.png)

**Comment by sanjayng007** [comment]
@devalevenkatesh tested on safari 14, working there
