### ISSUE TITLE
No audio output devices on iOS & Mac OS

### ISSUE THREAD

**Issue by k-ahn** [aws/amazon-chime-sdk-js#811]
iOS Version: 13.6
Mac OS Version: 10.13.6
SDK Version: "amazon-chime-sdk-js": "^1.20.2",

I've built a React JS app using the SDK that works on Chrome but isn't working on iOS or Mac OS. The first issue is that no audio output devices are detected. Audio input devices are detected and working. I've also a different issue with video, but one issue at a time ...

My code is:

```
const availableAudioOutputDevices = await session.audioVideo.listAudioOutputDevices()
console.log('AOD ', availableAudioOutputDevices)
const audioOutputDeviceId = availableAudioOutputDevices[0].deviceId
```
The console log writes an empty array and then, as expected, no object to connect.

```
[Log] AOD  – [] (0) (main.1975cc73.chunk.js, line 1)
[Log] TypeError: undefined is not an object (evaluating 'a[0].deviceId') — Meet.js:153 (main.1975cc73.chunk.js, line 1)
```

I've tested this on iOS and Mac OS - exactly the same behaviour. I don't use the Mac OS to code and hence can't run the demo browser. I don't believe i can connect to the demo app remotely?

**Comment by devalevenkatesh** [comment]
Hello @k-ahn ,

I think we have faced issues with both Safari and Firefox around audio-output device selection. We have also some know issues around video in Safari. Request you to please check our below FAQ's:
- [I am unable to select an audio output device in some browsers, is this a known issue?](https://github.com/aws/amazon-chime-sdk-js/blob/master/guides/06_FAQs.md#i-am-unable-to-select-an-audio-output-device-in-some-browsers-is-this-a-known-issue)
- [My video disappears in Safari browsers, is this a known issue?](https://github.com/aws/amazon-chime-sdk-js/blob/master/guides/06_FAQs.md#my-video-disappears-in-safari-browsers-is-this-a-known-issue)

Further we also have a react component library which may be helpful if you want to develop react application:
https://github.com/aws/amazon-chime-sdk-component-library-react

**Comment by k-ahn** [comment]
Thanks for the reply @devalevenkatesh 

Regarding the audio, the FAQ states "_While clients can continue the meeting using the default device, they will not be able to select devices in meetings_". I am unclear how i select the default device as i would have expected the above code did exactly that (which it does in chrome)?

**Comment by k-ahn** [comment]
On further investigation the audio output is working, even though it can't be selected in the same way as video and input audio. 

Thankyou

**Comment by christiansaavedra** [comment]
Has this been solved?

**Comment by michhyun1** [comment]
@christiansaavedra unfortunately not - [we cannot currently select audio outputs on ](https://github.com/aws/amazon-chime-sdk-js/blob/master/guides/07_FAQs.md#i-am-unable-to-select-an-audio-output-device-in-some-browsers-is-this-a-known-issue)

**Comment by mdebusschere2** [comment]
This behavior seems to have continued, we still can not enumerate audio output devices on IOS and Chrome.
Out tests on Safari worked though.
We had other issues with IoS and Chrome - video and audio did not actual start streaming despite no errors.
Forcing a user to respond to an Alert appears to have resolved the issue on a couple of tests.

userAgent=Mozilla/5.0 (iPhone; CPU iPhone OS 15_3_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.3 Mobile/15E148 Safari/604.1

**Comment by michhyun1** [comment]
@mdebusschere2 This ticket is already closed - can I ask that you create a new issue and please give us more context into your issue. The more detailed you are, the more we can help. Thanks
