### ISSUE TITLE
How to properly detect when camera/microphone fails

### ISSUE THREAD

**Issue by Juanpaie** [aws/amazon-chime-sdk-js#818]
**What are you trying to do?**
I want to detect when the cam/mic fails in the following cases:
* When using macOS 10.14+ and the browser doesn't have the proper permissions under system preferences.
* When cam/mic fails due to the OS (Windows/Mac) not detecting it.

What's the proper way to catch this errors?

**Screenshots**
This is the generated log when cam/mic fails.
![Captura de Pantalla 2020-10-27 a la(s) 16 27 04](https://user-images.githubusercontent.com/1341310/97370574-e90abc80-1874-11eb-8f39-f48fe840423f.png)

**Platform**
 - OS: macOS Catalina
 - Browser: Chrome
 - Browser Version: 86.0.4240.111
 - Amazon Chime SDK GitHub Commit: 1.20.2

**Comment by bradmanAWS** [comment]
Hi @Juanpaie, the browser should be prompting the user for camera and microphone permissions unless they are blocked by the settings in the browser. Can you confirm you have allowed the permissions in the browser?

**Comment by Juanpaie** [comment]
Yes @bradmanAWS, consider cam/mic permissions are already allowed in the browser.

At this moment, [DevicePermissions](https://aws.github.io/amazon-chime-sdk-js/enums/devicepermission.html) returns `PermissionDeniedByBrowser: = 3` when:

- Permissions are blocked by browser settings.
- Permissions are denied by system (macOS 10.14+ or Windows).

We need a new error code for example `PermissionDeniedBySystem: = 5` to distinguish when permissions are denied properly by the system.

**Comment by anuranduttaroy** [comment]
Hey @Juanpaie, with the [amazon-chime-sdk-js release 2.0.0](https://www.npmjs.com/package/amazon-chime-sdk-js/v/2.0.0) we introduced [`GetUserMediaError`](https://aws.github.io/amazon-chime-sdk-js/modules/migrationto_2_0.html#introducing-the-getusermediaerror-type) type. Here are the list of new ErrorTypes

- GetUserMediaError
    - NotFoundError
    - NotReadableError
    - OverconstrainedError
    - PermissionDeniedError
    - TypeError

With this, you would be able to distinguish the failures that might happen while calling [`chooseAudioInputDevice`](https://aws.github.io/amazon-chime-sdk-js/interfaces/devicecontroller.html#chooseaudioinputdevice) and [`chooseVideoInputDevice`](https://aws.github.io/amazon-chime-sdk-js/interfaces/devicecontroller.html#choosevideoinputdevice) APIs in the `DeviceController`. 

Here is an example how you can use these new error types.

```typescript
try {
  await this.audiovideo.chooseAudioInputDevice(device);
} catch (e) {
  if (e instanceof PermissionDeniedError) {
    console.error('Permission denied', e);
  } elseif (e instanceof NotReadableError) {
    console.error('Not Readable', e);
  }
}
```

Feel free to re-open if you still have question.
