### ISSUE TITLE
mic audio output playing in 2 meetings

### ISSUE THREAD

**Issue by arscottd** [aws/amazon-chime-sdk-js#819]
**Important:** Please attach INFO-level logs with timestamps to the report from *before* the session started up until the point at which the unexpected behavior occurred. For multi-participant calls, attach a log file for each participant if possible.

**Meeting and attendee IDs:**
List the meeting and attendee IDs that the attached logs apply to.

meeting-1 (our id 146106536)
VPaaS conference ID c6ef3851-5237-4da5-8528-43fa4460aace, 
participant ID 852046ec-144b-f1a2-5459-61780f135420

meeting-2 (719279568)
VPaaS conference ID 9284fd37-0d1d-4e76-a952-3576bda9e23e, 
participant ID 7a61e7d0-46e8-0e12-c230-bdaf0730f4fe

**Timeline**
Outline the main actions the user performed and when:

* <timestamp> <action>
* <timestamp> <action>

**Describe the bug**
I have an incident where Michael's microphone output is playing in 2 meetings. In this case, Michael entered meeting 1 and immediately exited then successfully entered meeting 2.  Users in both meeting-1 and meeting-2 could hear Michael speak. Michael could only see and hear meeting-2.

**Screenshots**
If applicable, add screenshots to help explain the problem.

**Platform**
 - OS: Electron v8.3.1 on win10
 - Browser: chromeum
 - Browser Version: 
 - Amazon Chime SDK GitHub Commit: 1.17.2

From our log, we have a join, followed 1.5s later by an end
and it looks like chime SDK refused the `Disconnect` request.
```
      "2020-10-21T19:30:41.710Z INFO App [[av.service.join]] \"146106536\"",
      "2020-10-21T19:30:41.713Z INFO App [[AVClient.joinCall()]]- conferenceId=64e967cb-a35b-4184-92fb-d163b2f8ed50 user=9c4ccbe6-585b-4dc4-9096-d0ee15c54c0c ",

      "2020-10-21T19:30:42.981Z INFO App [meet.component.displayAVSetupModal] Leaving meeting, closing modal "
      "2020-10-21T19:30:43.241Z INFO App [meet.component.endCall()] "

       "2020-10-21T19:30:43.270Z INFO App [[AVClient.hangup()]] ",
       "2020-10-21T19:30:43.270Z INFO VPaaS chime-adapter.endSession - Screen share stopped ",
       "2020-10-21T19:30:43.271Z WARNING VPaaS no transition found from NotConnected with Disconnect ",

      "2020-10-21T19:30:52.367Z INFO App [[av.service.join]] \"719279568\"",
      "2020-10-21T19:30:52.369Z INFO App [[AVClient.joinCall()]]- conferenceId=df5efbab-23b7-4260-905a-f58060d2d9b1 user=9c4ccbe6-585b-4dc4-9096-d0ee15c54c0c ",

```

Chime's state table is in
src/sessionstatecontroller/DefaultSessionStateController.ts

There is a comment in here src/sessionstatecontroller/SessionStateController.ts
implying that this early stop request should be deferred

> /**
>    * Performs the state transition action and if the transition is possible calls
>    * the work function. If the transition is not currently possible, but could
>    * become possible after the next transition then the action may be deferred.
>    * For example, while in the Connecting state, if Stop is called this action
>    * will be deferred until the Connected state is reached.
>    */
>

**Comment by bradmanAWS** [comment]
Hi @arscottd, can you include all the logs for this issue?

**Comment by arscottd** [comment]
@bradmanAWS I would rather not expose my customer's log on this public site. Is there another way I can send them to you?

The root cause seems to be
"2020-10-21T19:30:43.271Z WARNING VPaaS no transition found from NotConnected with Disconnect ",

where chime sdk did not do the session close request. I don't believe that there was any event sent back to our code advising that the close was not happening.

**Comment by bradmanAWS** [comment]
Ok, thanks @arscottd it seems like this may be related to #706. We are investigating this issue.

**Comment by vidya-mohan** [comment]
@arscottd you could come through the AWS Support Portal for sensitive cases
