### ISSUE TITLE
Possibly Chrome bug causing video source frame rate drop by half after in meeting for a while

### ISSUE THREAD

**Issue by XHatan** [aws/amazon-chime-sdk-js#821]
**Important:** Please attach INFO-level logs with timestamps to the report from *before* the session started up until the point at which the unexpected behavior occured. For multi-participant calls, attach a log file for each participant if possible.

**Meeting and attendee IDs:**
List the meeting and attendee IDs that the attached logs apply to.

<img width="1087" alt="Screen Shot 2020-10-28 at 5 44 12 PM" src="https://user-images.githubusercontent.com/46945302/97511857-52f29700-1945-11eb-8f9d-3c4da96b2da4.png">

**Timeline**
Outline the main actions the user performed and when:

* <timestamp> <action>
* <timestamp> <action>

**Describe the bug**
Describe the bug and the timestamp at which it happened relative to the timestamp in the log file.

**Screenshots**
If applicable, add screenshots to help explain the problem.

**Platform**
 - OS: Catalina
 - Browser:  Chrome
 - Browser Version:  86
 - Amazon Chime SDK GitHub Commit:

**Comment by XHatan** [comment]
I haven't found a workaround for this yet. 
This seems to me likely a Macbook and Chrome issue. 
I could not reproduce this with Firefox, haven't tried with safari.

**Comment by bradmanAWS** [comment]
Hi, @XHatan can you please send the logs for this issue?

**Comment by stopdropandrew** [comment]
It appears to be a Chrome bug related to a specific camera on newer Macbook Pros. The only device id that it occurs on in my testing is 0x05ac:8514. Workaround is to request getUserMedia with no specified frame rate. It also does not happen immediately, but typically within 10-20 minutes.

**Comment by XHatan** [comment]
Thanks. @stopdropandrew do you find the chrome bug in crbug.com ? 
I find a way to reproduce this instantly with another camera application + chrome

**Comment by stopdropandrew** [comment]
Have not seen the bug on crbug.

**Comment by XHatan** [comment]
we haven't seen it for a long time. I think Chrome fixed the issue.
