### ISSUE TITLE
Unsubscribe Volume Indicator when audioVideo.stop() is called

### ISSUE THREAD

**Issue by peili** [aws/amazon-chime-sdk-js#822]
The documentation provides a way to unsubscribe from a volume indicator.
https://github.com/aws/amazon-chime-sdk-js/blob/master/guides/03_API_Overview.md#5b-subscribe-to-volume-indicators

To unsubscribe from an attendee’s volume indicator, call meetingSession.audioVideo.realtimeUnsubscribeFromVolumeIndicator(attendeeId).

**Question:** meetingSession.audioVideo.stop() does it automatically cleanup & unsubscribe such listeners? Or do we explicitly need to call it for each attendee to unsubscribe?

**Comment by vidya-mohan** [comment]
That you for the interest in our SDK. meetingSession.audioVideo.stop() should be sufficient
