### ISSUE TITLE
Trouble rendering videos for both meeting creator and attendees

### ISSUE THREAD

**Issue by RalphLincoln** [aws/amazon-chime-sdk-js#862]
While rendering the videos for the meeting, the creator of the meeting can see everyone coming into the meeting. But the attendee can see anyone until some else joins the meeting after the attendee.

this is how am rendering all attendee videos.
`  ```
```
this.displayAttendeeVideoContent = async (session) => {
            const videoElement0 = document.getElementById('attendee-video-element0')
            const videoElement1 = document.getElementById('attendee-video-element1')
            const videoElement2 = document.getElementById('attendee-video-element2')
            const videoElement3 = document.getElementById('attendee-video-element3')
            const videoElement4 = document.getElementById('attendee-video-element4')
            const videoElement5 = document.getElementById('attendee-video-element5')
            const videoElement6 = document.getElementById('attendee-video-element6')
            const videoElement7 = document.getElementById('attendee-video-element7')
            const videoElement8 = document.getElementById('attendee-video-element8')
            const videoElement9 = document.getElementById('attendee-video-element9')
            const videoElement10 = document.getElementById('attendee-video-element10')
            const videoElement11 = document.getElementById('attendee-video-element11')
            const videoElement12 = document.getElementById('attendee-video-element12')
            const videoElement13 = document.getElementById('attendee-video-element13')
            const videoElement14 = document.getElementById('attendee-video-element14')
            const videoElement15 = document.getElementById('attendee-video-element15')
            const videoElement16 = document.getElementById('attendee-video-element16')
            const videoElement17 = document.getElementById('attendee-video-element17')
            const videoElement18 = document.getElementById('attendee-video-element18')
            const videoElement19 = document.getElementById('attendee-video-element19')
            const videoElement20 = document.getElementById('attendee-video-element20')
```

            const videoElements = [videoElement0, videoElement1, videoElement2, videoElement3, videoElement4, videoElement5, videoElement6,
                videoElement7, videoElement8, videoElement9, videoElement10, videoElement11, videoElement12, videoElement13,
                videoElement14, videoElement15, videoElement16, videoElement17, videoElement18, videoElement19, videoElement20]
            const indexMap = {};

            const acquireVideoElement = tileId => {
                for (let i = 0; i < 20; i += 1) {
                    if (indexMap[i] === tileId) {
                        return videoElements[i];
                }
            }
                for (let i = 0; i < 20; i += 1) {
                    if (!indexMap.hasOwnProperty(i)) {
                        indexMap[i] = tileId;
                            return videoElements[i];
                }
            }
            throw new Error('no video element is available');
            };

            const releaseVideoElement = tileId => {
                for (let i = 0; i < 20; i += 1) {
                    if (indexMap[i] === tileId) {
                        delete indexMap[i];
                            return;
                }
            }
            return videoElements;
            };
            const observer = {
                videoTileDidUpdate: tileState => {

                    this.props.session.audioVideo.bindVideoElement(tileState.tileId, acquireVideoElement(tileState.tileId));

                    if (!tileState.boundAttendeeId || tileState.localTile || tileState.isContent) {
                    // return;
                }
            },
                videoTileWasRemoved: tileId => {
                    releaseVideoElement(tileId);
                }
            };
            this.props.session.audioVideo.addObserver(observer);
            // this.props.session.audioVideo.start();
            this.props.session.audioVideo.startLocalVideoTile();
        }`
```

**Comment by RidipDe** [comment]
Hi @RalphLincoln 
The Chime JS SDK supports up to 16 video participants in a meeting.
Tiles are populated on a first come first served basis. If there are 16 attendees sharing and one turns off video, a new attendee can turn on their video and join.

More information can be found in the [FAQ section](https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html)

**Comment by RalphLincoln** [comment]
Ok.....the issue, when I create the meeting, as my attendees are coming into the meeting they don't see anyone but themself until someone joins the meeting after them. But I since am the first to join the meeting, I can see them all.

**Comment by devalevenkatesh** [comment]
From your code it looks like you are following the video use case 16 from the JS SDK readme. Have you checked out our [meeting demo app](https://github.com/aws/amazon-chime-sdk-js/tree/master/demos/browser) implementation? We also have a similar implementation separated in the [DemoTileOrganizer](https://github.com/aws/amazon-chime-sdk-js/blob/master/demos/browser/app/meetingV2/meetingV2.ts#L66) class. Request you to check our implementation and follow the [`videoTileDidUpdate`](https://github.com/aws/amazon-chime-sdk-js/blob/master/demos/browser/app/meetingV2/meetingV2.ts#L2187) and [`videoTileWasRemoved`](https://github.com/aws/amazon-chime-sdk-js/blob/master/demos/browser/app/meetingV2/meetingV2.ts#L2220) methods. The implementation may solve your issue.

Please reach out if you still face the issue.

**Comment by RalphLincoln** [comment]
Good Day,
Thanks for the reply. I came across another sample on github, It works good. But while rendering the video, only two videos can be render. Once a third video comes up, the other disappears. Can only render 2 videos simultaneously · Issue #9 · aws-samples/amazon-chime-sdk-smart-video-sending-demo

| 
| 
| 
|  |  |

 |

 |
| 
|  | 
Can only render 2 videos simultaneously · Issue #9 · aws-samples/amazon-...

const acquireTileIndex = (tileId: number): number => { for (let index = 0; index < MAX_REMOTE_VIDEOS; index++) {...
 |

 |

 |




    On Thursday, December 31, 2020, 01:26:21 AM GMT+1, Venkatesh Devale <notifications@github.com> wrote:  
 
 


From your code it looks like you are following the video use case 16 from the JS SDK readme. Have you checked out our meeting demo app implementation? We also have a similar implementation separated in the DemoTileOrganizer class. Request you to check our implementation and follow the videoTileDidUpdate and videoTileWasRemoved methods. The implementation may solve your issue.

Please reach out if you still face the issue.

**Comment by RalphLincoln** [comment]
So basically, after the first two attendee render their video, any other attendee rendering their video will take out the video of the first attendee
    On Thursday, December 31, 2020, 02:52:54 AM GMT+1, Ikenna Alaneme <ialaneme@yahoo.com> wrote:  
 
  Good Day,
Thanks for the reply. I came across another sample on github, It works good. But while rendering the video, only two videos can be render. Once a third video comes up, the other disappears. Can only render 2 videos simultaneously · Issue #9 · aws-samples/amazon-chime-sdk-smart-video-sending-demo

| 
| 
| 
|  |  |

 |

 |
| 
|  | 
Can only render 2 videos simultaneously · Issue #9 · aws-samples/amazon-...

const acquireTileIndex = (tileId: number): number => { for (let index = 0; index < MAX_REMOTE_VIDEOS; index++) {...
 |

 |

 |




    On Thursday, December 31, 2020, 01:26:21 AM GMT+1, Venkatesh Devale <notifications@github.com> wrote:  
 
 


From your code it looks like you are following the video use case 16 from the JS SDK readme. Have you checked out our meeting demo app implementation? We also have a similar implementation separated in the DemoTileOrganizer class. Request you to check our implementation and follow the videoTileDidUpdate and videoTileWasRemoved methods. The implementation may solve your issue.

Please reach out if you still face the issue.
