### ISSUE TITLE
ReferenceError: MediaDeviceInfo is not defined (Chrome Browser)

### ISSUE THREAD

**Issue by nchandupatla** [aws/amazon-chime-sdk-js#863]
I'm using ReactJS chime sdk to create/join a meeting. Things working well when tested in local but when we deploy them to production (S3 static hosting) we are seeing below issues with mediaDevices. Please help us resolve this issue.

2020-11-16T15:03:04.354Z [ERROR] SDK - navigator.mediaDevices is not supported
Uncaught (in promise) ReferenceError: MediaDeviceInfo is not defined
    at e.<anonymous> (DefaultDeviceController.ts:446)
    at 2.548db705.chunk.js:2
    at Object.next (2.548db705.chunk.js:2)
    at 2.548db705.chunk.js:2
    at new Promise (<anonymous>)
    at r (2.548db705.chunk.js:2)
    at e.updateDeviceInfoCacheFromBrowser (2.548db705.chunk.js:2)
    at e.<anonymous> (DefaultDeviceController.ts:439)
    at 2.548db705.chunk.js:2
    at Object.next (2.548db705.chunk.js:2)

If it helps, I'm adding my react components changes to create/join a meeting.

`const MeetingManager = () => {
  const meetingManager = useMeetingManager();
   const joinMeeting = async () => {
    // Fetch the meeting and attendee data from your server
    const response = await fetch(
      "https://xxxxx.execute-api.us-east-1.amazonaws.com/Prod/join?title=newmeetingv4&name=" +
        uuid() +
        "&region=us-east-1",
      {
        method: "POST",
        headers: new Headers(),
      }
    );
    const data = await response.json();
    const joinData = {
      meetingInfo: data.JoinInfo.Meeting.Meeting,
      attendeeInfo: data.JoinInfo.Attendee.Attendee,
    };
    // Use the join API to create a meeting session
    await meetingManager.join(joinData);

    const audioInputs = await meetingManager.audioVideo.listAudioInputDevices();
    const audioOutputs = await meetingManager.audioVideo.listAudioOutputDevices();
    const videoInputs = await meetingManager.audioVideo.listVideoInputDevices();

    // An array of MediaDeviceInfo objects
    audioInputs.forEach((mediaDeviceInfo) => {
      console.log(
        `Device ID: ${mediaDeviceInfo.deviceId} Microphone: ${mediaDeviceInfo.label}`
      );
    });

    await meetingManager.audioVideo.chooseAudioInputDevice(
      audioInputs[0].deviceId
    );
    await meetingManager.audioVideo.chooseAudioOutputDevice(
      audioOutputs[0].deviceId
    );
    await meetingManager.audioVideo.chooseVideoInputDevice(
      videoInputs[0].deviceId
    );

    if (!navigator.mediaDevices || !navigator.mediaDevices.enumerateDevices) {
      console.log("mediaDevices() not supported.");
      return;
    }

    // List cameras and microphones.

    navigator.mediaDevices
      .enumerateDevices()
      .then(function (devices) {
        console.log("mediaDevices() ***********");
        devices.forEach(function (device) {
          console.log(
            "mediaDevices: " +
              device.kind +
              ": " +
              device.label +
              " id = " +
              device.deviceId
          );
        });
      })
      .catch(function (err) {
        console.log("mediaDevices err: " + err.name + ": " + err.message);
      });
    const deviceChangeObserver = {
      audioInputsChanged: (freshAudioInputDeviceList) => {
        // An array of MediaDeviceInfo objects
        freshAudioInputDeviceList.forEach((mediaDeviceInfo) => {
          console.log(
            `Device ID: ${mediaDeviceInfo.deviceId} Microphone: ${mediaDeviceInfo.label}`
          );
        });
      },
      audioOutputsChanged: (freshAudioOutputDeviceList) => {
        console.log("Audio outputs updated: ", freshAudioOutputDeviceList);
      },
      videoInputsChanged: (freshVideoInputDeviceList) => {
        console.log("Video inputs updated: ", freshVideoInputDeviceList);
      },
    };
    meetingManager.audioVideo.addDeviceChangeObserver(deviceChangeObserver);
    const videoDidStartObserver = {
      audioVideoDidStart: () => {
        console.log("Started");
      },
      audioVideoDidStop: (sessionStatus) => {
        // See the "Stopping a session" section for details.
        console.log(
          "Stopped with a session status code: ",
          sessionStatus.statusCode()
        );
      },
      audioVideoDidStartConnecting: (reconnecting) => {
        if (reconnecting) {
          // e.g. the WiFi connection is dropped.
          console.log("Attempting to reconnect");
        }
      },
    };
    meetingManager.audioVideo.addObserver(videoDidStartObserver);
    // At this point you can let users setup their devices, or start the session immediately
    meetingManager.audioVideo.start();
    alert("joined successfully!!!");
  };
  return (
    <div className="container">
      <div className="col-md-8">
        <div className="row">
          <button onClick={joinMeeting}>JOIN</button>
        </div>
      </div>
    </div>
  );
};`

**Comment by ltrung** [comment]
MediaDeviceInfo is only available in secure context. Could you double check whether you use http or https?

**Comment by akazorg** [comment]
Hey @nchandupatla, are you using http? https? it will fail if using http.

**Comment by vidya-mohan** [comment]
Reference: https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html#my-clients-are-unable-to-join-the-meeting-and-i-see-navigatormediadevices-is-undefined-what-could-be-the-reason
