### ISSUE TITLE
Heavy Lag after delay in selecting audio Input, audio output and video input device

### ISSUE THREAD

**Issue by RalphLincoln** [aws/amazon-chime-sdk-js#866]
When trying to select my audio and video device, if I make a delay of 6 secs, there's serious lag and sometimes I can't transition to the in-meeting screen.

Here are the logs.......

``20-11-17T08:22:52.416Z [INFO] Chime Logs - API/DefaultAudioVideoFacade/2b9a0e27-c1bf-4b5e-8195-34744a49dba4/04738067-afbb-a700-9cf7-a8d2f00f8608/listAudioInputDevices null -> [{"deviceId":"default","kind":"audioinput","label":"Default - Jack Mic (Realtek(R) Audio)","groupId":"a996f90e7b3e0ff72b915a82d2aaee8489a236106b3f5b5481667ec152be75b1"},{"deviceId":"communications","kind":"audioinput","label":"Communications - Jack Mic (Realtek(R) Audio)","groupId":"a996f90e7b3e0ff72b915a82d2aaee8489a236106b3f5b5481667ec152be75b1"},{"deviceId":"4c2eba62e960b8f28bf3487334c5c746d5ae57ff45b8c3619e3d21a0779e921f","kind":"audioinput","label":"Jack Mic (Realtek(R) Audio)","groupId":"a996f90e7b3e0ff72b915a82d2aaee8489a236106b3f5b5481667ec152be75b1"},{"deviceId":"a339f8eeeb8a05fdf194abf2e81cd07056945c7c2347865485e5ed93e3649e80","kind":"audioinput","label":"Microphone Array (Realtek(R) Audio)","groupId":"a996f90e7b3e0ff72b915a82d2aaee8489a236106b3f5b5481667ec152be75b1"}]
ConsoleLogger.ts:81 2020-11-17T08:22:52.424Z [INFO] Chime Logs - API/DefaultDeviceController/listAudioOutputDevices null -> [{"deviceId":"default","kind":"audiooutput","label":"Default - Speakers/Headphones (Realtek(R) Audio)","groupId":"a996f90e7b3e0ff72b915a82d2aaee8489a236106b3f5b5481667ec152be75b1"},{"deviceId":"communications","kind":"audiooutput","label":"Communications - Speakers/Headphones (Realtek(R) Audio)","groupId":"a996f90e7b3e0ff72b915a82d2aaee8489a236106b3f5b5481667ec152be75b1"},{"deviceId":"c4c236cf47e793b83fe5b56db6e2e4ed48232fd8091b7b2bb1938375c3faefe6","kind":"audiooutput","label":"Speakers/Headphones (Realtek(R) Audio)","groupId":"a996f90e7b3e0ff72b915a82d2aaee8489a236106b3f5b5481667ec152be75b1"}]
ConsoleLogger.ts:81 2020-11-17T08:22:52.425Z [INFO] Chime Logs - API/DefaultAudioVideoFacade/2b9a0e27-c1bf-4b5e-8195-34744a49dba4/04738067-afbb-a700-9cf7-a8d2f00f8608/listAudioOutputDevices null -> [{"deviceId":"default","kind":"audiooutput","label":"Default - Speakers/Headphones (Realtek(R) Audio)","groupId":"a996f90e7b3e0ff72b915a82d2aaee8489a236106b3f5b5481667ec152be75b1"},{"deviceId":"communications","kind":"audiooutput","label":"Communications - Speakers/Headphones (Realtek(R) Audio)","groupId":"a996f90e7b3e0ff72b915a82d2aaee8489a236106b3f5b5481667ec152be75b1"},{"deviceId":"c4c236cf47e793b83fe5b56db6e2e4ed48232fd8091b7b2bb1938375c3faefe6","kind":"audiooutput","label":"Speakers/Headphones (Realtek(R) Audio)","groupId":"a996f90e7b3e0ff72b915a82d2aaee8489a236106b3f5b5481667ec152be75b1"}]
ConsoleLogger.ts:81 2020-11-17T08:22:52.430Z [INFO] Chime Logs - API/DefaultDeviceController/listVideoInputDevices null -> [{"deviceId":"dc66b8415e50b5c7fc5bbe46938703fef32409b5ca4a87ca9f84811dc9e44c9d","kind":"videoinput","label":"Integrated Webcam (0bda:5539)","groupId":"27d1b305502c9338c787faef39fe5cb2ec0deecb7b6e4a6ab05bf6dcc6d82733"}]
ConsoleLogger.ts:81 2020-11-17T08:22:52.430Z [INFO] Chime Logs - API/DefaultAudioVideoFacade/2b9a0e27-c1bf-4b5e-8195-34744a49dba4/04738067-afbb-a700-9cf7-a8d2f00f8608/listVideoInputDevices null -> [{"deviceId":"dc66b8415e50b5c7fc5bbe46938703fef32409b5ca4a87ca9f84811dc9e44c9d","kind":"videoinput","label":"Integrated Webcam (0bda:5539)","groupId":"27d1b305502c9338c787faef39fe5cb2ec0deecb7b6e4a6ab05bf6dcc6d82733"}]
ConsoleLogger.ts:81 2020-11-17T08:22:52.437Z [INFO] Chime Logs - API/DefaultDeviceController/listAudioInputDevices null -> [{"deviceId":"default","kind":"audioinput","label":"Default - Jack Mic (Realtek(R) Audio)","groupId":"a996f90e7b3e0ff72b915a82d2aaee8489a236106b3f5b5481667ec152be75b1"},{"deviceId":"communications","kind":"audioinput","label":"Communications - Jack Mic (Realtek(R) Audio)","groupId":"a996f90e7b3e0ff72b915a82d2aaee8489a236106b3f5b5481667ec152be75b1"},{"deviceId":"4c2eba62e960b8f28bf3487334c5c746d5ae57ff45b8c3619e3d21a0779e921f","kind":"audioinput","label":"Jack Mic (Realtek(R) Audio)","groupId":"a996f90e7b3e0ff72b915a82d2aaee8489a236106b3f5b5481667ec152be75b1"},{"deviceId":"a339f8eeeb8a05fdf194abf2e81cd07056945c7c2347865485e5ed93e3649e80","kind":"audioinput","label":"Microphone Array (Realtek(R) Audio)","groupId":"a996f90e7b3e0ff72b915a82d2aaee8489a236106b3f5b5481667ec152be75b1"}]
ConsoleLogger.ts:81 2020-11-17T08:22:52.437Z [INFO] Chime Logs - API/DefaultAudioVideoFacade/2b9a0e27-c1bf-4b5e-8195-34744a49dba4/04738067-afbb-a700-9cf7-a8d2f00f8608/listAudioInputDevices null -> [{"deviceId":"default","kind":"audioinput","label":"Default - Jack Mic (Realtek(R) Audio)","groupId":"a996f90e7b3e0ff72b915a82d2aaee8489a236106b3f5b5481667ec152be75b1"},{"deviceId":"communications","kind":"audioinput","label":"Communications - Jack Mic (Realtek(R) Audio)","groupId":"a996f90e7b3e0ff72b915a82d2aaee8489a236106b3f5b5481667ec152be75b1"},{"deviceId":"4c2eba62e960b8f28bf3487334c5c746d5ae57ff45b8c3619e3d21a0779e921f","kind":"audioinput","label":"Jack Mic (Realtek(R) Audio)","groupId":"a996f90e7b3e0ff72b915a82d2aaee8489a236106b3f5b5481667ec152be75b1"},{"deviceId":"a339f8eeeb8a05fdf194abf2e81cd07056945c7c2347865485e5ed93e3649e80","kind":"audioinput","label":"Microphone Array (Realtek(R) Audio)","groupId":"a996f90e7b3e0ff72b915a82d2aaee8489a236106b3f5b5481667ec152be75b1"}]
ConsoleLogger.ts:81 2020-11-17T08:22:52.440Z [INFO] Chime Logs - API/DefaultDeviceController/listAudioOutputDevices null -> [{"deviceId":"default","kind":"audiooutput","label":"Default - Speakers/Headphones (Realtek(R) Audio)","groupId":"a996f90e7b3e0ff72b915a82d2aaee8489a236106b3f5b5481667ec152be75b1"},{"deviceId":"communications","kind":"audiooutput","label":"Communications - Speakers/Headphones (Realtek(R) Audio)","groupId":"a996f90e7b3e0ff72b915a82d2aaee8489a236106b3f5b5481667ec152be75b1"},{"deviceId":"c4c236cf47e793b83fe5b56db6e2e4ed48232fd8091b7b2bb1938375c3faefe6","kind":"audiooutput","label":"Speakers/Headphones (Realtek(R) Audio)","groupId":"a996f90e7b3e0ff72b915a82d2aaee8489a236106b3f5b5481667ec152be75b1"}]
ConsoleLogger.ts:81 2020-11-17T08:22:52.440Z [INFO] Chime Logs - API/DefaultAudioVideoFacade/2b9a0e27-c1bf-4b5e-8195-34744a49dba4/04738067-afbb-a700-9cf7-a8d2f00f8608/listAudioOutputDevices null -> [{"deviceId":"default","kind":"audiooutput","label":"Default - Speakers/Headphones (Realtek(R) Audio)","groupId":"a996f90e7b3e0ff72b915a82d2aaee8489a236106b3f5b5481667ec152be75b1"},{"deviceId":"communications","kind":"audiooutput","label":"Communications - Speakers/Headphones (Realtek(R) Audio)","groupId":"a996f90e7b3e0ff72b915a82d2aaee8489a236106b3f5b5481667ec152be75b1"},{"deviceId":"c4c236cf47e793b83fe5b56db6e2e4ed48232fd8091b7b2bb1938375c3faefe6","kind":"audiooutput","label":"Speakers/Headphones (Realtek(R) Audio)","groupId":"a996f90e7b3e0ff72b915a82d2aaee8489a236106b3f5b5481667ec152be75b1"}]
ConsoleLogger.ts:81 2020-11-17T08:22:52.442Z [INFO] Chime Logs - API/DefaultDeviceController/listVideoInputDevices null -> [{"deviceId":"dc66b8415e50b5c7fc5bbe46938703fef32409b5ca4a87ca9f84811dc9e44c9d","kind":"videoinput","label":"Integrated Webcam (0bda:5539)","groupId":"27d1b305502c9338c787faef39fe5cb2ec0deecb7b6e4a6ab05bf6dcc6d82733"}]
ConsoleLogger.ts:81 2020-11-17T08:22:52.443Z [INFO] Chime Logs - API/DefaultAudioVideoFacade/2b9a0e27-c1bf-4b5e-8195-34744a49dba4/04738067-afbb-a700-9cf7-a8d2f00f8608/listVideoInputDevices null -> [{"deviceId":"dc66b8415e50b5c7fc5bbe46938703fef32409b5ca4a87ca9f84811dc9e44c9d","kind":"videoinput","label":"Integrated Webcam (0bda:5539)","groupId":"27d1b305502c9338c787faef39fe5cb2ec0deecb7b6e4a6ab05bf6dcc6d82733"}]``

This is my code...

``
   ` // THIS WILL RETURN A ARRAY OF AUDIO OUTPUT ELEMENT
    audioOutput = async () => {
        const audioOutputDevices = await this.props.session.audioVideo.listAudioOutputDevices();
            return this.setState({
                audioOutputs: audioOutputDevices
            })
    }
`

    // THIS WILL RETURN A ARRAY OF AUDIO INPUT ELEMENT
    audioInput = async () => {
        const audioInputDevices = await this.props.session.audioVideo.listAudioInputDevices();
            return this.setState({
                audioInputs: audioInputDevices
            })
    }

    // THIS WILL RETURN A ARRAY OF VIDEO OUTPUT ELEMENT
    videoInput = async () => {
        const videoInputDevices = await this.props.session.audioVideo.listVideoInputDevices();
            return this.setState({
                videoInputs: videoInputDevices
            })
    }

    <p className='title-text font-weight-bold'>Microphone</p>
                                <div className='form-group typ'>
                                    <select value={audioInputForm} onChange={this.handleAudioInput} className='form-control'>
                                        <option value='Microphone'>Choose Microphone</option>
                                        {
                                            audioInputs.map(audioInput => <option key={audioInput.deviceId} value={audioInput.deviceId}>{audioInput.label}</option>)
                                        }
                                    </select>
                                </div>

                                <p className='title-text font-weight-bold'>Camera</p>
                                <div className='form-group ty'>
                                    <select value={videoInputForm} onChange={this.handleVideoInput} className='form-control'>
                                        <option value='camera'>Choose Camera</option>
                                        {
                                            videoInputs.map(videoInput => <option key={videoInput.deviceId} value={videoInput.deviceId}>{videoInput.label}</option>)
                                        }
                                    </select>
                                </div>

                                <div className='form-group typ'>
                                    <select value={videoQualityForm} onChange={this.handleVideoQuality} className='form-control'>
                                        <option value='choose quality settings'>Choose quality Settings</option>
                                        <option value='360p'>360p (nHD) @ 15 fps (600 Kbps max)</option>
                                        <option value='540p'>540p (qHD) @ 15 fps (1.4 Mbps max)</option>
                                        <option value='720p'>720p (HD) @ 15 fps (1.4 Mbps max)</option>
                                    </select>
                                </div>

                                <p className='title-text font-weight-bold'>Speaker</p>
                                <div className='form-group typ'>
                                    <select value={audioOutputForm} onChange={this.handleAudioOutput} className='form-control'>
                                        <option value='Speaker'>Choose Speaker</option>
                                        {
                                            audioOutputs.map(audioOutput => <option key={audioOutput.deviceId} value={audioOutput.deviceId}>{audioOutput.label}</option>)
                                        }
                                    </select>
                                </div>
``

**Comment by p-foucht** [comment]
Hi @RalphLincoln 

"if I make a delay of 6 secs, there's serious lag and sometimes I can't transition to the in-meeting screen."

Can you expand a bit on this? Are the `chooseaudioinputdevice` or `choosevideoinputdevice` calls taking several seconds to run, or where exactly is the delay coming from? It's hard to troubleshoot without seeing your change handler

The logs don't seem to show any calls to the chooseXdevice APIs, so could you upload the full logs as well?
