### ISSUE TITLE
How can the multiple attendees added and how can they join the same meeting

### ISSUE THREAD

**Issue by RawiShankar** [aws/amazon-chime-sdk-js#871]
### What are you trying to do?

*For example: I'm trying to start a meeting session with audio.*

### How can the documentation be improved to help your use case?

*For example: Include a section on how to configure the meeting session.*

### What documentation have you looked at so far?

*For example: README.md, Amazon Chime SDK Developer Guide, etc.

**Comment by RawiShankar** [comment]
I'm new to this chime, I'm using Java as backend server and using react as front end application. I've created meeting object and attendee object.  When I open the client application I am able to see my video, But how some external attendee can add to that meeting. Please let me know, as I am new to this.

**Comment by vidya-mohan** [comment]
@RawiShankar please take a look @ https://github.com/aws/amazon-chime-sdk-component-library-react which has  react components that will help bootstrap your application quickly. There is also a built in demo app.
