### ISSUE TITLE
Audio does not stop immediately

### ISSUE THREAD

**Issue by rlebosse** [aws/amazon-chime-sdk-js#872]
I implemented in my webapp a **STOP** button to quickly leave an Amazon Chime Meeting i'm connected too.

Here's what I do when user clicks on the button :

```js
deviceController.chooseAudioInputDevice(null)
deviceController.chooseVideoInputDevice(null)
audioVideo.stop()
```

Unfortunately, it takes some time to stop hearing the other attendees in the Meeting, around **1.5 seconds**. That's quite a long time.

Is this a bug ? Or is there a way to stop the audio stream quicker ?

Thanks in advance for you help,
rlebosse

**Platform**
 - OS: macOS 10.15.7
 - Browser: Google Chrome 87
 - Amazon Chime SDK GitHub Commit: version 1.21.0

**Comment by richnew10** [comment]
One quick solution is to call `audioVideo.unbindAudioElement()` to disconnect the output audio.

**Comment by rlebosse** [comment]
Thanks @richnew10, i'll try it out !

**Comment by vidya-mohan** [comment]
rlebosse@ thanks for your interest in our SDK!
