### ISSUE TITLE
Android chrome is not supported

### ISSUE THREAD

**Issue by davidpene** [aws/amazon-chime-sdk-js#890]
### What are you trying to do?

*Start a meet using an android browser*

### How can the documentation be improved to help your use case?

*Documentation states that android chrome is supported but setSinkId is not supported, so cannot choose audio device*

### What documentation have you looked at so far?

<img width="1026" alt="Screen Shot 2020-11-21 at 10 48 23 AM" src="https://user-images.githubusercontent.com/14010084/99853222-6f51be80-2be7-11eb-9952-b86c4c40b032.png">
<img width="862" alt="Screen Shot 2020-11-21 at 10 47 30 AM" src="https://user-images.githubusercontent.com/14010084/99853227-72e54580-2be7-11eb-91e5-d118abeb4a7c.png">

**Comment by davidpene** [comment]
Documentation should note features that have certain limitations.
This includes:
- Choosing audio output
- WebAudio (background noise suppression)

**Comment by stanggt3** [comment]
Also having this problem. Chrome was working fine in the past. This is a breaking change

**Comment by vidya-mohan** [comment]
@davidpene @landaveCalrissian - thanks you for the interest in the SDK - we currently have limitations documented in our FAQs https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html . For eg. for setSInkId 0 https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html#i-am-getting-cannot-select-audio-output-device-this-browser-does-not-support-setsinkid-error-on-the-browser-console-is-this-a-known-issue linked from our ReadMe. Please let us know if you have addition questions

**Comment by davidpene** [comment]
Hi @vidya-mohan, after some digging I did end up finding the github issue you linked. The FAQ's look new, which is a nice addition!

If it's ok, it would be good to keep this issue alive since people seem to be finding this before they find the documentation you've linked. Cheers 😄

**Comment by Leeaandrob** [comment]
Chrome Android is not appearing the video on the latest release, is it an issue?

**Comment by vidya-mohan** [comment]
@Leeaandrob - thanks for the interest - which version are you seeing issues on and have you already filed a Github issue for it with details? Additionally have you searched through our issues database, https://github.com/aws/amazon-chime-sdk-js/issues/1059 or https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html?

This ticket is tracking a different issue on documentation.
