### ISSUE TITLE
API: deleteMeeting always returns HTTP 200

### ISSUE THREAD

**Issue by chris-makaio** [aws/amazon-chime-sdk-js#895]
Sorry for not following the issue template but it doesn't apply here - there's not logging required.

These are the package versions:
>     "amazon-chime-sdk-js": "^1.20.0",
>     "aws-sdk": "^2.731.0",

It seems that deleteMeeting always returns HTTP 200 / OK, these work when IMHO they shouldn't:
- delete a meeting which already has been deleted
- delete a meeting with any ID (as long it's a guid) succeeds, even if the specified ID doesn't even exist

**Comment by asnyatkov** [comment]
Hi Chris, DeleteMeeting functions as designed. The API is idempotent and treats non-existing meetings as "already ended".

**Comment by vidya-mohan** [comment]
@chris-makaio Thank you for the interest in our SDK - let us know if we helped clarify your question on the SDK. Your observations of the DeleteMeeting meets with our design guidance of Idempotency.

**Comment by chris-makaio** [comment]
Thanks @asnyatkov @vidya-mohan 
Maybe it‘s worth mentioning in the docs, though
