### ISSUE TITLE
API: listMeetings returns deleted meetings

### ISSUE THREAD

**Issue by chris-makaio** [aws/amazon-chime-sdk-js#896]
related to #895 

ATM listMeetings returns meetings even if they have been deleted. Not too bad, but where's no way to check if the meeting is active other than calling getMeeting, which will return an error (NotFound, that's fine). Calls to listMeetings thereafter will correctly return the list w/o the previously requested (and deleted) meeting.

BTW, doc says listMeetings should only return **active** meetings:

```
/**
 * Lists up to 100 active Amazon Chime SDK meetings. (...)
 */
listMeetings(callback?: (err: AWSError, data: Chime.Types.ListMeetingsResponse) => void): Request<Chime.Types.ListMeetingsResponse, AWSError>;
```

(Sorry for posting two issues right from the start. Let me say that coming from Zoom API / Webclient I really LOVE Chime SDK)

**Comment by asnyatkov** [comment]
Hi Chris, could you open AWS support ticket for this?

**Comment by chris-makaio** [comment]
@asnyatkov we don‘t have a paid support plan so I can‘t open a technical issue case

**Comment by chris-makaio** [comment]
@asnyatkov just to be sure: we have a simple hotfix for this issue (after deletion, get meeting, catch NotFound error, call listMeetings). I just thought it makes sense to share this issue so maybe you can look into it for everybody else

**Comment by asnyatkov** [comment]
Ok, makes sense. We're working on a fix.

**Comment by bradmanAWS** [comment]
Hi @chris-makaio this issue should be resolved and I am closing this ticket. Please reopen if you have any issues.
