### ISSUE TITLE
Need a Chime log to indicate that signalling has negotiated WebRTC over TCP

### ISSUE THREAD

**Issue by tthorpe-git** [aws/amazon-chime-sdk-js#904]
Although most of our video meetings using Chime see video media carried over UDP, we have an issue where our network set-up is causing signalling negotiation to fallback to carry video media for some meetings over TCP, which is not supportable. It took us a while to figure out that this is happening, partly because there was no logged indication from Chime that this fallback to TCP is happening. 

I have captured the Chime logs for 2 video sessions, each included as an excel spreadsheet in the uploaded compressed tar file 'chime_logs.tar.gz'.

1. video media carried over UDP: graylog-udp-mary-faulkner.bournemouth-sso-ui-only-longer-period-2020-11-19T09_25_00.000Z-2020-11-19T09_55_00.000Z

2. video media carried over TCP: graylog-tcp-andy-grice-clay.wolverhampton-sso-ui-only-longer-period-2020-11-19T14_10_00.000Z-2020-11-19T14_36_00.000Z

In each file, there are a mixture of Chime logs & our own 'wrapper' service logs; the former are identifiable by the '[BROWSER-CONDUCT]' tag.
In each case, the user has actually started multiple video meetings - look for "Staff Entered Landing Page Accessed" log for the start of each new cycle.
In each case, 2 people attended the meeting, who we call 'conductor' (in a DWP office) & 'attendee' (UK citizen on the public internet), but I have only uploaded those logs for the conductor side of each meeting, as this is the side that is sometimes negotiating to carry the video media traffic over TCP, due to the route from that particular DWP office to the Chime UDP servers, through the DWP network, being blocked for some reason.

[chime_logs.tar.gz](https://github.com/aws/amazon-chime-sdk-js/files/5601245/chime_logs.tar.gz)

Meeting and attendee IDs: 

Video media carried over UDP:
meeting id: 2d10ea9f-3a6a-4271-a0f2-70265db8e1f0
attendee id: f9c35b5a-6f06-d70c-40f3-61aa1ebfaed1

Video media carried over TCP:
meeting id: a030f62c-4ed3-4386-94e2-9aae58461822
attendee id: 64bad67e-9dd6-50e4-d332-be4fc2e53556

**Timeline**

Video media carried over UDP:
* 2020-11-19 09:34:15 DWP staff member enters DWP's own meeting code
* 2020-11-19 09:34:21 Signalling begins
* 2020-11-19 09:34:27 Video meeting begins

Video media carried over TCP:
* 2020-11-19 14:12:51 DWP staff member enters DWP's own meeting code
* 2020-11-19 14:12:56 Signalling begins
* 2020-11-19 14:13:02 Video meeting begins

**Describe the bug**
The Chime logs do not tell us that the signalling has negotiated WebRTC over TCP - we need to see this. Will also be good to see why the fallback to TCP has happened.

**Platform**
 - OS: W10
 - Browser: edge-chromium 85 
 - Browser Version: (85.0.564)
 - Amazon Chime SDK GitHub Commit:

**Comment by tthorpe-git** [comment]
Amazon Chime SDK versions we are using: 
amazon-chime-sdk-js: 1.19.0
software.amazon.awssdk: 2.15.9

**Comment by anuranduttaroy** [comment]
Hey @tthorpe-git, currently, there is nothing in the SDK INFO logs that would indicate whether the connection has fallen back to TCP. The ICE Candidate which is printed out here in the [CreatePeerConnectionTask](https://github.com/aws/amazon-chime-sdk-js/blob/master/src/task/CreatePeerConnectionTask.ts#L55) looks like this

```
peer connection ice candidate: candidate:3557301317 1 udp 8341107 10.4.31.22 62273 typ relay raddr 0.0.0.0 rport 0 generation 0 ufrag WLiO network-id 1 network-cost 10
```

which does not give the `relayProtocol` information.

After using Chrome's [webrtc-internals](chrome://webrtc-internals) tool, we noticed this

In the case of **UDP**, the local-candidate looks like this [relayProtocol = `udp`]

```
Statistics RTCIceCandidate
timestamp	12/10/2020, 4:52:02 PM
transportId	RTCTransport_audio_1
isRemote	false
networkType	wifi
ip		<ip-address>
port		<port-number>
protoco		udp
relayProtocol	udp
candidateType	relay
priority	41885439
deleted		false
```

In the case of **TCP**, the local-candidate looks like this  [relayProtocol = `tls`]

```
Statistics RTCIceCandidate
timestamp	12/10/2020, 4:41:33 PM
transportId	RTCTransport_audio_1
isRemote	false
networkType	wifi
ip		<ip-address>
port		<port-number>
protocol	udp
relayProtocol	tls
candidateType	relay
priority	8331007
deleted	false
```


Here is something you could do in your app to get this information.

```
  async getRelayProtocol() {
    const rawStats = await this.audioVideo.getRTCPeerConnectionStats();
    if (rawStats) {
      rawStats.forEach(report => {
        if (report.type === 'local-candidate') {
          this.log(`Local webrtc ice candidate stats: ${JSON.stringify(report)}`);
          let relayProtcol = report.relayProtocol;
          if (relayProtcol === 'udp') {
            this.log(`Connection using ${relayProtcol} protocol`);
          } else {
            this.log(`Connection fell back to ${relayProtcol} protocol`);
          }
        }
      });
    }
  }
```

Let me know if this works for you !!

**Comment by anuranduttaroy** [comment]
The above commit added the logging functionality to the serverless demo app to print out the below lines when clicked on the  WebRTC stats button.

<img width="655" alt="Screen Shot 2020-12-18 at 10 49 30 AM" src="https://user-images.githubusercontent.com/4708896/102650023-10686200-411f-11eb-9316-1cf6118a1027.png">

```
Connection using UDP protocol
```

or

```
Connection fell back to TLS protocol
```

Let me know if this resolves your issue?

**Comment by pooja-malhotra-digital** [comment]
Thanks @anuranduttaroy. It is working for me.
