### ISSUE TITLE
Need a Chime configurable option to prevent signalling fallback of carrying WebRTC over TCP

### ISSUE THREAD

**Issue by tthorpe-git** [aws/amazon-chime-sdk-js#905]
This is linked to bug report #904: "Need a Chime log to indicate that signalling has negotiated WebRTC over TCP".

So please refer to that bug report for: logs, meeting/attendee ids, timeline. 

Describe the bug
In our case, fallback to carrying video media over TCP causes the video traffic to be routed through our network (out to the Chime servers) in an unsupportable way, which we have no way of preventing; this will cause real problems for our network. So we need Chime to include an option to turn-off the possibility of carrying video media over TCP, such that if the UDP route is not available then signalling negotiation will NOT attempt to fallback to TCP, thus fail & the video meeting will not start.

Platform

OS: W10
Browser: edge-chromium 85
Browser Version: (85.0.564)
Amazon Chime SDK GitHub Commit:

**Comment by tthorpe-git** [comment]
Amazon Chime SDK versions we are using: 
amazon-chime-sdk-js: 1.19.0
software.amazon.awssdk: 2.15.9

**Comment by anuranduttaroy** [comment]
There is the [`urlRewriter`](https://github.com/aws/amazon-chime-sdk-js/blob/7a73e038bdea14c6339041e53d50d5d0de069d43/src/meetingsession/MeetingSessionURLs.ts#L127-L129) which you can use in this case. We used the URL Rewriter to get rid of the TCP fallback URL [here](https://github.com/aws/amazon-chime-sdk-js/blob/7a73e038bdea14c6339041e53d50d5d0de069d43/src/meetingreadinesschecker/DefaultMeetingReadinessChecker.ts#L359-L361). This is how we do the UDP connectivity test by getting rid of the TCP URL.

You can do something like this: In the serverless demo, you can update the URL Rewriter [here](https://github.com/aws/amazon-chime-sdk-js/blob/master/demos/browser/app/meetingV2/meetingV2.ts#L961) and do something like this

```
configuration.enableSimulcastForUnifiedPlanChromiumBasedBrowsers = this.enableSimulcast;
configuration.urls.urlRewriter = (uri: string) => {
      if (uri.includes('transport=tcp')) {
            return '';
      }
      return uri;
};
this.meetingSession = new DefaultMeetingSession(configuration, logger, deviceController);
```

Let me know if this works.

**Comment by tthorpe-git** [comment]
Thanks for your recommendation Anuran. I have passed this on to my dev team; will let you know if/when they confirm that we will use it. Tim

**Comment by pooja-malhotra-digital** [comment]
Hello Anuran,
I tried the suggestion by you above. These were the changes made - 

` const deviceController = new DefaultDeviceController(this.logger);
    configuration.enableWebAudio = this.enableWebAudio;
    configuration.urls.urlRewriter = (uri: string) => {
      if (uri.includes('transport=tcp')) {
        return '';
      }
      return uri;
    };
    this.meetingSession = new DefaultMeetingSession(configuration, this.logger, deviceController);
    this.audioVideo = this.meetingSession.audioVideo;`

After this change, the video stopped working for me. In console error is `Error: Cannot read property 'includes' of undefined`. Any suggestion how to resolve this?

**Comment by anuranduttaroy** [comment]
> Hello Anuran,
> I tried the suggestion by you above. These were the changes made -
> 
> ` const deviceController = new DefaultDeviceController(this.logger); configuration.enableWebAudio = this.enableWebAudio; configuration.urls.urlRewriter = (uri: string) => { if (uri.includes('transport=tcp')) { return ''; } return uri; }; this.meetingSession = new DefaultMeetingSession(configuration, this.logger, deviceController); this.audioVideo = this.meetingSession.audioVideo;`
> 
> After this change, the video stopped working for me. In console error is `Error: Cannot read property 'includes' of undefined`. Any suggestion how to resolve this?

Weird. I tried the same code snippet before I suggested it here and it works for me. Let me see what's happening here. Does your Error call stack indicate from which line of code that error is thrown?

**Comment by anuranduttaroy** [comment]
Hey @pooja-malhotra-digital did you get a chance to find the line of code where this issue is seen? You can give us the INFO level logs too and I can help you find the issue.

**Comment by tthorpe-git** [comment]
Including Pooja….

**Comment by pooja-malhotra-digital** [comment]
Hello @anuranduttaroy,

Apologies for delay. The `if` check was throwing the error. I managed to resolve it now by  - 

` 
configuration.urls.urlRewriter = (uri: string) => {
      if (uri && uri.includes('transport=tcp')) {
        return '';
      }
      return uri;
    };
`

**Comment by devalevenkatesh** [comment]
Looks like this issue can be resolved now since the solution provided by @anuranduttaroy worked. Please feel free to re-open if you face any issue.
