### ISSUE TITLE
getMeeting() function

### ISSUE THREAD

**Issue by scredii** [aws/amazon-chime-sdk-js#906]
### What are you trying to do?

Join an existing meeting session

### How can the documentation be improved to help your use case?

Include a section on how to join an existing meeting session (chime.getMeeting())

### What documentation have you looked at so far?

README.md

thanks

**Comment by bradmanAWS** [comment]
Hi @scredii, can you provide more details about where you are having trouble? Also, you can run around demo browser meeting application and use that code as an example.

**Comment by scredii** [comment]
it might save time to mention how to join an existing room directly in the readme
