### ISSUE TITLE
bindToAudioVideoController causes unhandled rejection on devices without setSinkId

### ISSUE THREAD

**Issue by BenV** [aws/amazon-chime-sdk-js#907]
`DefaultDeviceController.bindToAudioVideoController` calls `bindAudioOutput` which is now async and will throw an error if the device does not support `setSinkId`. I don't believe we can catch this error as it is being thrown from a private method using an async scheduler. This error gets logged to our error reporting service and also causes issues in development with react. 

This is the problematic line from what I can tell: https://github.com/aws/amazon-chime-sdk-js/blob/59bf60c30c8450451d9d1e36ec30a5b67e787607/src/devicecontroller/DefaultDeviceController.ts#L402

Adding a `.catch` to that line allows me to set up my meeting without issue, although I'm not sure if there should be any sort of internal error handling for a rejection there. 

Thanks!

**Platform**
 - OS: Mac OS 11
 - Browser: Safari
 - Browser Version: 14.0.1

**Comment by aarnoldaas** [comment]
We have same issue

**Comment by adambyer** [comment]
This is happening me for me in Firefox as well.

- Mac OS 10.15.7
- Firefox 83

**Comment by evandroguedes** [comment]
Same issue here.

Mac OS 10.15.7
Safari 13.1.3
Firefox 84.0b4

iOS 14.2
Safari

**Comment by michhyun1** [comment]
There has been a fix for this: https://github.com/aws/amazon-chime-sdk-js/pull/913, which is planning on going out on our next release.

**Comment by BenV** [comment]
The fix in the latest version is working fine for me, so I'm going to close this issue. Thanks for the quick response!
