### ISSUE TITLE
globalThis is not defined

### ISSUE THREAD

**Issue by rlebosse** [aws/amazon-chime-sdk-js#908]
When importing code from `amazon-chime-sdk-js`, I have a blocking error when I am using a browser that does not support `globalThis`.

I run into the following error : `globalThis is not defined`

**Platform**
 - Browser: Edge 18 / IE 11 / Chrome 67
 - Amazon Chime SDK version : 2.1.0

**Comment by rlebosse** [comment]
I submitted the following PR to fix the problem : https://github.com/aws/amazon-chime-sdk-js/pull/909

**Comment by richnew10** [comment]
Fixed by #910; please reopen if needed.
