### ISSUE TITLE
Video not working for Lenovo Tab

### ISSUE THREAD

**Issue by koushikAsl** [aws/amazon-chime-sdk-js#914]
I am initiating a meeting from a laptop and a tablet is attending the meeting

Facing same issue when using the demo from **'amazon-chime-sdk-js/demos/browser/'**.

**Issue Description**
The meeting is successfully getting created but there is no video from the tablet device
The audio works fine though.

**Timeline**
This occurs after the session has been successfully connected and the user is waiting for the other device's video 

**Device Info**

############### Lenovo Tab ############### 
Tablet Model :- Lenovo Tab P10
Chrome Version : 86.0.4240.198
Operating System : Andrioi 9, Lenevo TP-XL Bulid/PKQ1 190319.001
AWS Chome SDK For Javascript : amazon-chime-sdk-js@2.1.0
###############Lenovo Tab ############### 

############### Laptop ############### 
Chrome Version : 86.0.4240.198 
Operating System : Windows 10
AWS Chome SDK For Javascript : amazon-chime-sdk-js@2.1.0
###############Laptop HP ############### 

**Meeting Info**
Meeting Id : 9b401375-91a3-4cc0-90c7-3496b2db162d
Attendee Id : e05369ba-52d9-e1a4-eded-4d084e6593e3

**Logs**
[meeting-info-logs-for-labtop_from(laptop)_attendee(tablet).txt](https://github.com/aws/amazon-chime-sdk-js/files/5621598/meeting-info-logs-for-labtop_from.laptop._attendee.tablet.txt)

**Screenshots**
![lap](https://user-images.githubusercontent.com/71490414/100723962-5ebff600-33e8-11eb-9bfc-65ab605a8c4a.png)
![tab](https://user-images.githubusercontent.com/71490414/100723967-5ff12300-33e8-11eb-8355-23940f791ce3.png)

**EDIT**
Upon further investigation, we found this error ( from the tablet)

{"meetingId":"c5761ed1-9364-4cf6-939f-84f844f77c22","attendeeId":"3033235e-a8ff-33c6-eb21-705df6fa6c4a","appName":"MyAWSChimeSdk","logs":[{"sequenceNumber":0,"message":"failed to get video device for constraints {\"video\":{\"deviceId\":{\"exact\":\"a09763447bb2048874ef7bcbaf84af373f8d2354a92a1f84fe96f42b1c01ce82\"},\"width\":960,\"height\":540,\"frameRate\":15}}: Could not start video source","timestampMs":1606811194557,"logLevel":3}]} 

Attaching this log
[error_log.txt](https://github.com/aws/amazon-chime-sdk-js/files/5621667/error_log.txt)

**EDIT 2**
I have checked and applied fix from https://github.com/aws/amazon-chime-sdk-js/issues/423
Still not working
Updated logs
[meeting-logs.txt](https://github.com/aws/amazon-chime-sdk-js/files/5622137/meeting-logs.txt)

**Comment by XHatan** [comment]
Hey, thanks for reporting this

From the screenshot of Lenovo tab, the self video on the Lenovo tab is working right ?

**Comment by XHatan** [comment]
@koushikAsl Hey, did you figure out the issue, does this work for you now ?

**Comment by koushikAsl** [comment]
The self video is also not working.
The issue remains with AWS chime SDK

Note:  I have tried with a sample code using WEBRTC and I was able to use the camera.

**Comment by RidipDe** [comment]
Can you please provide us with the logs from the tablet and the laptop after running the JS SDK demo app and reproing the above mentioned scenario?

**Comment by devalevenkatesh** [comment]
In the EDIT#2, I checked the logs attached there. You were able to successfully get the video device for requested video constraints. Feel free to re-open this issue if not solved yet.
