### ISSUE TITLE
Meeting ending due to inactivity

### ISSUE THREAD

**Issue by henlamk** [aws/amazon-chime-sdk-js#915]
I am aware of the meeting being ended after 40-ish minutes, if there is only one participant. 
However, in our use case we need the meeting to stay alive. 

Is there a way of preventing this automatic meeting ending mechanism?

**Comment by bradmanAWS** [comment]
Hi @henlamk, this auto end policy is not configurable. This policy is in place to protect users from being overcharged for meetings that are not being used. The only way to have meetings not end is to keep at least 2 attendees in the meeting. I am closing this issue, but feel free to reopen if you have further questions.
