### ISSUE TITLE
 How do I set up a server?

### ISSUE THREAD

**Issue by eunki7** [aws/amazon-chime-sdk-js#916]
Hello.

I am using aws m2.large server.

I want to test 16 video tiles using chime sdk javascript.

I am curious if the test is possible after setting meetingV2 + NGINX + SSL.

I am curious if there are any values ​​that need to be set separately in the nginx server.

Thank you for your kind answer.

**Comment by CrystalMethod** [comment]
Hi. Why don't you run this demo locally? Your m2.lange only serves some static resources (js,html,...). Why do you need this instance? Chime SDK is a client SDK and is running in your browser.

**Comment by bradmanAWS** [comment]
Hi @eunki7 I'm closing this issue until we hear back. Please reopen if needed.
