### ISSUE TITLE
import error on 2.1.0 version 

### ISSUE THREAD

**Issue by juicycool92** [aws/amazon-chime-sdk-js#918]
**Important:** Please attach INFO-level logs with timestamps to the report from *before* the session started up until the point at which the unexpected behavior occured. For multi-participant calls, attach a log file for each participant if possible.

**Meeting and attendee IDs:**
List the meeting and attendee IDs that the attached logs apply to.

cant reach to start meeting...

**Timeline**
Outline the main actions the user performed and when:

when it load on web, immediately got error.
  
**Describe the bug**
Describe the bug and the timestamp at which it happened relative to the timestamp in the log file.

im running Node.js 12 LTS
on Windows and WSL2 Ubuntu 20.04 version both,
install amazon-chime-sdk-js 2.1.0 version, and following order on readme,

first, install babel for run node with es6+,
second, import module by
```
import {
    ConsoleLogger,
    DefaultDeviceController,
    DefaultMeetingSession,
    LogLevel,
    MeetingSessionConfiguration,
  } from 'amazon-chime-sdk-js';
```

third, i got this error
```
Uncaught ReferenceError: exports is not defined
    at eval (AttachMediaInputTask.ts?25c2:3)
    at Module../node_modules/amazon-chime-sdk-js/build/task/AttachMediaInputTask.js (app.js:2812)
    at __webpack_require__ (app.js:790)
    at fn (app.js:101)
    at eval (index.ts?6f37:8)
    at Object../node_modules/amazon-chime-sdk-js/build/index.js (app.js:2008)
    at __webpack_require__ (app.js:790)
    at fn (app.js:101)
    at eval (aws.js?b007:3)
```

**Screenshots**
If applicable, add screenshots to help explain the problem.
![image](https://user-images.githubusercontent.com/12273678/100869337-46cb9d80-34e0-11eb-991d-4ec492046289.png)
![image](https://user-images.githubusercontent.com/12273678/100869436-64006c00-34e0-11eb-89eb-55a891fab432.png)

![image](https://user-images.githubusercontent.com/12273678/100869406-5c40c780-34e0-11eb-81a4-539c7e389eaf.png)

**Platform**
 - OS: Windows10, WSL2 Ubuntu20.04
 - Browser: Chrome 
 - Browser Version: latest
 - Amazon Chime SDK GitHub Commit: 2.1.0(master)

**Comment by bradmanAWS** [comment]
Hi @juicycool92, 

Sorry to hear about this issue. It could be related to this change here: https://github.com/aws/amazon-chime-sdk-js/commit/3cf694cc59e83784669f54a0e26c8fc43a2005cb
In V2, we changed the “target” in TS config from “es5" to “ES2015” (ES6).

Also, you can check out our "browser" meeting demo configuration here:
- https://github.com/aws/amazon-chime-sdk-js/blob/master/demos/browser/tsconfig.json
- https://github.com/aws/amazon-chime-sdk-js/blob/master/demos/browser/webpack.config.js

**Comment by juicycool92** [comment]
> Hi @juicycool92,
> 
> Sorry to hear about this issue. It could be related to this change here: [3cf694c](https://github.com/aws/amazon-chime-sdk-js/commit/3cf694cc59e83784669f54a0e26c8fc43a2005cb)
> In V2, we changed the “target” in TS config from “es5" to “ES2015” (ES6).
> 
> Also, you can check out our "browser" meeting demo configuration here:
> 
> * https://github.com/aws/amazon-chime-sdk-js/blob/master/demos/browser/tsconfig.json
> * https://github.com/aws/amazon-chime-sdk-js/blob/master/demos/browser/webpack.config.js

Thankyou for kind support! its works :>

**Comment by Aeramor** [comment]
Sorry, what was the solution to this? Running into the same problem when upgrading from 1.20.2 -> 2.2.0 in yarn package.json

**Comment by abaransy** [comment]
> Sorry, what was the solution to this? Running into the same problem when upgrading from 1.20.2 -> 2.2.0 in yarn package.json
> 
> adding below fixed it for me
> 
> ```
>       [
>         "@babel/plugin-transform-modules-commonjs",
>         {
>           "allowTopLevelThis": true
>         }
>       ],``` 
> ```

Nice

**Comment by anmol-rodi** [comment]
@bradmanAWS I am also facing the same issue and have tried all the resolutions given in other comments but still not working.

**Comment by MohdIrfan12** [comment]
> @bradmanAWS I am also facing the same issue and have tried all the resolutions given in other comments but still not working.

@bradmanAWS @chime-sdk-js-bot can you please help us here we are in the process of deploying our code and due to this issue we aren’t able to

**Comment by ltrung** [comment]
@anmol-rodi @MohdIrfan12 Can you open a new issues as this issue is too long ago.

**Comment by MohdIrfan12** [comment]
> @anmol-rodi @MohdIrfan12 Can you open a new issues as this issue is too long ago.

Here it is-
https://github.com/aws/amazon-chime-sdk-js/issues/918
