### ISSUE TITLE
Meeting Id is coming as duplicate while deployed on cloud Front

### ISSUE THREAD

**Issue by RawiShankar** [aws/amazon-chime-sdk-js#925]
**Important:** I am using java as backend server and react as front end server. I deployed the application into cloud Front, as it requires https for the meeting to happen. After three meetings, the cache is storing in cloud Front and Iam getting duplicate meeting IDs, even though the server is giving unique responses. I haven't given any SSL certificates so I have connected my server to cloud Front. Can any one help me what is causing this issue.

**Platform**
 - OS: Windows
 - Browser:  Chrome
 - Browser Version:  Version 86.0.4240.198 (Official Build) (64-bit)

**Comment by vidya-mohan** [comment]
@RawiShankar - please take a look at the demos linked form our Readme - like this serverless demo and use it as a template https://github.com/aws/amazon-chime-sdk-js/blob/master/README.md#examples for your application or compare against your implementation. We have a example using React based components: https://github.com/aws/amazon-chime-sdk-component-library-react/tree/master/demo/meeting
