### ISSUE TITLE
How to get the audio content of the meeting and the content of the shared screen ？

### ISSUE THREAD

**Issue by seasar992** [aws/amazon-chime-sdk-js#931]
Thank you for your contribution

I want to complete a project that records the content of the meeting in real time, such as converting voice into text, and scanning the content of the shared screen
How to get the audio content of the meeting and the content of the shared screen so that the AI server can process these content?

Now I can only get the various URLs of MediaPlacement in the response. I have tried to read the URL directly with OPENCV, but it cannot be read normally.

please help me.
Best regards

**Comment by bradmanAWS** [comment]
Hi @seasar992, I'm not sure I understand your use case, but if you are looking for sharing a meeting in realtime, it sounds like you need to stream the meeting. Have you seen the AWS live events demo? https://github.com/aws-samples/amazon-chime-live-events

Let me know if this is the sort of solution you are looking for.

**Comment by seasar992** [comment]
@bradmanAWS Thank you for your answer
I just want to process video of the meeting on the ai server, such as converting voice to text and performing face authentication for attendees
I tried to investigate the AWS live events demo, but did not find a solution

How can I get the video stream without a browser?

Best regards

**Comment by p-foucht** [comment]
I'm not sure this is totally possible without a browser. Within a browser, you could check this [Video Processsing API](https://github.com/aws/amazon-chime-sdk-js/blob/019111db5482c8e6c19b36f3edfc0fcf1be4e9a2/guides/10_Video_Processor.md) out

Alternatively you could look into something like Electron and process buffers using native APIs, but it's not something we have tried before

**Comment by p-foucht** [comment]
Closing -- feel free to reopen if necessary
