### ISSUE TITLE
How to stop/start audio/video for specific attendee(s) in a meeting?

### ISSUE THREAD

**Issue by killmenot** [aws/amazon-chime-sdk-js#933]
Hi,

### What are you trying to do?

I'm trying to create groups in a meeting where several users can see/hear each other in context of group only.
Example: users in a meeting - 1,2,3,4,5,6,7,8
users in groups [1,2,3], [4,5,6], [7,8]
user 1 can see/hear only user 2/3...

**Comment by bradmanAWS** [comment]
Hi @killmenot this feature is not currently supported by the Amazon Chime SDK. I'll pass this along to the team as a feature request to look into.

**Comment by p-foucht** [comment]
Meeting audio is [centrally mixed](https://docs.aws.amazon.com/chime/latest/dg/meetings-sdk.html), so unfortunately there is no way to split out the individual attendee's audio to create groups in this regard. Each group would need to be its own individual meeting.

Closing, but feel free to reopen or leave additional comments/questions if needed
