### ISSUE TITLE
Video inspection and manipulation - how to use?

### ISSUE THREAD

**Issue by Axe129** [aws/amazon-chime-sdk-js#939]
### What are you trying to do?

I'm trying to use video inspection and manipulation for adding extra content such as filters and text to the video

### How can the documentation be improved to help your use case?

It would be great if there's a section which explains how to integrate the video inspection feature in an existing chime application. The documentation currently only highlights the classes and interfaces that can be used for doing the task but it does not really explain where to add them in the existing code. A working demo would also be very useful.

### What documentation have you looked at so far?

I've looked at https://docs.aws.amazon.com/chime/latest/dg/video-inspect.html

**Comment by CrystalMethod** [comment]
The related pull request #911 was closed without merging. And the latest SDK does not contain these classes either. I am not sure what the current status is.

**Comment by CrystalMethod** [comment]
#953 - not yet released but merge into and available in master.

**Comment by devalevenkatesh** [comment]
We released the video processing APIs in [v2.3.0](https://www.npmjs.com/package/amazon-chime-sdk-js/v/2.3.0). Checkout the [video processing APIs guide](https://github.com/aws/amazon-chime-sdk-js/blob/master/guides/10_Video_Processor.md). Closing this issue.
