### ISSUE TITLE
Can't properly unsubscribe

### ISSUE THREAD

**Issue by jrowny** [aws/amazon-chime-sdk-js#942]
realtimeSubscribeToVolumeIndicator accepts attendeeId and a listener
realtimeUnsubscribeToVolumeIndicator ONLY accepts attendeeId without the listener..

This means calling realtimeUnsubscribe on an attendeeId will unsub EVERY single listener even if you didn't want it to. This is particularly problematic in react, if I have two attendee nodes and the re-render in a different order, they will step on each others toes.

Given this code from the official react component library:

 ````
useEffect(() => {
    if (!audioVideo || !attendeeId) {
      return;
    }
    audioVideo.realtimeSubscribeToVolumeIndicator(attendeeId, (_, volume) => {
      if (bgEl) {
        bgEl.style.transform = `scaleY(${volume})`;
      }
    });
    return () => audioVideo.realtimeUnsubscribeFromVolumeIndicator(attendeeId); 
  }, [attendeeId, audioVideo, bgEl]);
````

Re-rendering this in a different order will cause one or more to be incorrectly unsubscribed.

My proposed solution is to use what other eventEmitters use and allow us to pass the same listener into the unsubscribe.

**Comment by 64json** [comment]
https://github.com/aws/amazon-chime-sdk-js/issues/673 might stem from this issue as well.

**Comment by jrowny** [comment]
That looks to be the same issue. It also breaks things in the chime react component library as well because the hooks there call unsubscribe anytime they are unmounted. Simply including one of those hooks or components will break it.

**Comment by jrowny** [comment]
Btw, my workaround for this was to create a wrapper class that extends event emitter and implements a proper on/off implementation.

**Comment by bradmanAWS** [comment]
@jrowny Sorry for the delay. The fix for this was just released in 2.4. You can now unsubscribe from specific callbacks instead of just all. Please reopen this issue if you experience any problems.

**Comment by jrowny** [comment]
So I updated the SDK, react component lib and changed my code to:

```useEffect(() => {
    if (!audioVideo || !attendeeId) {
      return;
    }
    const callback = (
      _: string,
      volume: number | null
    ) => {
      setVolume(volume || 0);
    };
    audioVideo.realtimeSubscribeToVolumeIndicator(attendeeId, callback);
    return () => {
      audioVideo.realtimeUnsubscribeFromVolumeIndicator(attendeeId, callback);
    }
  }, [attendeeId, audioVideo]);```

which is more or less copied from the react lib source for MicActivity and this is what I see whenever unsubscribe is attempted:

<img width="1241" alt="Screen Shot 2021-02-01 at 12 07 39 PM" src="https://user-images.githubusercontent.com/367710/106492613-1f646300-6486-11eb-86c9-9048dbef215a.png">

from console logs it seems like `this.state.volumeIndicatorCallbacks[attendeeId]` is null, but before the component dismounts it does work.

**Comment by jrowny** [comment]
@bradmanAWS I don't appear to have permissions to reopen this issue, but it's a bit of a blocker for me.

**Comment by jrowny** [comment]
@bradmanAWS I found the root cause. If you call unsubscribe without a callback, it deletes the whole callback collection. The react lib has not updated to include this and `useAttendeeAudioStatus` calls unsubscribe with no callbacks.

For now, I can implement my own mute listener and remove `useAttendeeAudioStatus` until the react library updates to 2.0.

I will close this issue again. Thanks.

**Comment by bradmanAWS** [comment]
@jrowny you are correct. A fix will be included in the next component library release, releasing soon. Thanks!

**Comment by arty-name** [comment]
I think I have seen the same issue just now, `this.state.volumeIndicatorCallbacks[attendeeId] is undefined`. In any case it stems from `attendeeId` not being present in `volumeIndicatorCallbacks`. Would it make sense to put some guard in there, for example simply return if there are no callbacks for this `attendeeId`? 

Otherwise the calling code would always have to wrap this call in try/catch, since it can’t really do any check to prevent this.

What do you think, @bradmanAWS?

**Comment by jrowny** [comment]
I would get rid of the single argument call altogether, but it would kill backwards compatibility if anyone was relying on being able to unsubscribe from all.
