### ISSUE TITLE
No audio during video conference call on IOS device

### ISSUE THREAD

**Issue by prakashkleo** [aws/amazon-chime-sdk-js#947]
**Meeting and attendee IDs:**
Attendee Id: "865d3a80-3942-21d0-2c37-354708a7ec3c"
Meeting Id: "81c5979c-6393-4cd5-ac53-a279a6034bce"

**Timeline**
Outline the main actions the user performed and when:
December-14-2020 18:35 IST(Asia/Calcutta)   Call Initiated
December-14-2020 18:45 IST(Asia/Calcutta)   Call Terminated

**Describe the bug**
Initiated a call using Chime SDK for JS in React.js on Safari browser on Iphone. Both parties are able to see video however no sound is audible on either side. Tried with multiple Iphone devices but same issue occurs on all, This works fine in  Chrome browser on Android device and Windows PC.

**Screenshots**
![ScreenSho_cleaned](https://user-images.githubusercontent.com/52522308/102087866-2389e200-3e40-11eb-9bf4-7b72c2e31852.JPG)

**Platform**
 - OS: IOS 14.1 (Iphone 8+)
 - Browser: Safari
 - Browser Version: 14

**Comment by p-foucht** [comment]
Few questions that would help us troubleshoot
- Do you have an audio element that you have bound? [(See here)](https://aws.github.io/amazon-chime-sdk-js/#starting-a-session)
- Are you selecting an audio input device?
- Is this something you can reproduce with the repo demo?
- Can you provide info level logs of the meeting?

**Comment by prakashkleo** [comment]
- We have an audio element bound in the code as shown below:
   `await mSession.audioVideo.addObserver(observer);
    let audioElement = document.getElementById('speaker');
   await mSession.audioVideo.bindAudioElement(audioElement);
   await mSession.audioVideo.start();`

- Yes, We have a form for selecting audio input device. By default in our code it picks the default input device and then we can switch to another input device. 
- Actually the issue is only on iphone so I need to find a way to run the demo on it's Safari browser. Probably need to deploy it on our server to access it from phone. I will try that if the attached logs does not help.
- I have attached the info level log of the call. It has the log from the time the call was initiated and we also tried muting/unmuting the audio during the call.
[chimeLog121820201517.txt](https://github.com/aws/amazon-chime-sdk-js/files/5739493/chimeLog121820201517.txt)
Please let me know if there is anything in the log that points to actual issue. Thanks!

**Comment by p-foucht** [comment]
Hmm, from looking at the logs I don't seem to see any calls to `chooseAudioInputDevice`, are you sure that your application code is selecting an audio input device?

I see the calls for bindAudioElement and chooseVideoInputDevice, but no audio input.

**Comment by prakashkleo** [comment]
I checked the code. In that we have the code to chooseAudioInputDevice as shown below. 
`const startMeeting = (mJson, aJson) => {
        console.log('start!');
        const logger = new ConsoleLogger('MyLogger', LogLevel.INFO);
        const deviceController = new DefaultDeviceController(logger);
        const configuration = new MeetingSessionConfiguration(mJson, aJson);
        const meetingSession = new DefaultMeetingSession(
            configuration,
            logger,
            deviceController
        );

        setMeetingSession(meetingSession);
        setAudioDefaults(meetingSession)
    };

    const setAudioDefaults = async (mSession) => {
        const audioInputDevices = await mSession.audioVideo.listAudioInputDevices();
        const audioOutputDevices = await mSession.audioVideo.listAudioOutputDevices();
        console.log(audioOutputDevices);
        if(audioOutputDevices.length>0){
            await mSession.audioVideo.chooseAudioInputDevice(audioInputDevices[0].deviceId);
            await mSession.audioVideo.chooseAudioOutputDevice(audioOutputDevices[0].deviceId);
        }
        startListening(mSession);
    }`

I also checked the Info logs by opening our web app on the Chrome web browser on Windows PC and in that I am able to find chooseAudioInputDevice. Could there be an issue in getting the audio input device on Safari browser and hence the code to chooseAudioInputDevice does not get executed? I could not find any errors in Console log.

**Comment by p-foucht** [comment]
Audio output devices requires the browser to support `setSinkId` ([support listed here](https://caniuse.com/?search=setsinkid) and [Chime's related documentation here](https://aws.github.io/amazon-chime-sdk-js/modules/faqs.html#i-am-unable-to-select-an-audio-output-device-in-some-browsers-is-this-a-known-issue)
), which Safari does not. The check for audioOutputDevices.length will always fail and skip over your `chooseAudioInputDevice` call

Instead, you should check for `audioInputDevices.length` separately and then call `chooseAudioInputDevice`

**Comment by p-foucht** [comment]
Close this, but if the above suggestion doesn't address your issue feel free to reopen
