### ISSUE TITLE
Ability to set or override used codec

### ISSUE THREAD

**Issue by rgardien** [aws/amazon-chime-sdk-js#963]
Google Chrome has some issues with using VP9 and H264, so I am looking for a way to use VP8 as the codec. However, I seem to am unable to, which makes me unable to use Chime for my use-case (relay it to another peer for consumption, see Chrome bug https://bugs.chromium.org/p/chromium/issues/detail?id=1140576).

Is there, or is it possible to, override or set the preferred codec?

**Comment by p-foucht** [comment]
Hi @rgardien -- unfortunately this is something that the Chime SDK currently supports

Closing, feel free to reopen if needed or if you have additional comments/questions

**Comment by vidya-mohan** [comment]
Reopening the issue as feature request

**Comment by hensmi-amazon** [comment]
This is possible, see https://github.com/aws/amazon-chime-sdk-js/blob/main/guides/19_Video_Codecs.md
