### ISSUE TITLE
Recording local video with audio

### ISSUE THREAD

**Issue by adambyer** [aws/amazon-chime-sdk-js#973]
Hi. I am trying to record the local users video and audio using `MediaRecorder` with `tileState.boundVideoStream` but this only seems to include the video (no audio stream). I also tried capturing the stream directly from the audio element bound to the device controller but didn't have any luck with that either.

Is there a way to capture (for recording) both the video and audio streams? This works in OpenTok and OpenVidu (which I'm hoping to replace with Chime) because both video and audio are in the `MediaStream` object.

Thanks.

**Comment by p-foucht** [comment]
Chime mixes all attendee audio into a single stream, so attendee's don't have their own audio stream to record. If you wanted to solely record the local user's audio, you would probably need to record the input audio itself and not the returned audio from Chime. Could you provide some details to help us better understand your use case?

**Comment by adambyer** [comment]
Hi @p-foucht. Thanks for the follow-up. I need to be able to record each attendee (audio and video) into a seperate file. This is a feature supported by other providers that I've used such as OpenTok, OpenVidu, and Twilio. They handle the recording on the backend and then upload the files to S3 or allow you to download them, so `MediaRecorder` is not needed. But I was looking into `MediaRecorder` since Chime doesn't offer recording.

Regarding your suggestion... will I be able to capture the audio input separately while the mic is in use by Chime? I haven't tried that but it seems like that wouldn't be possible.

In my app, there's only one attendee with sound at a time, so if I could even get access to the mixed audio stream that would probably work for me. I've tried using [captureStream](https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/captureStream) on the audio element, but I'm not getting audio for the local user.

**Comment by richnew10** [comment]
The local user's audio is not included in the mixed audio stream — that would give an unpleasant echo experience.

The easiest way to get audio for the local user is to handle device selection yourself, passing a stream to `chooseAudioInputDevice`, and record from that stream in the usual way.

If you prefer to work a little more idiomatically with the device controller, you could also implement a simple `AudioTransformDevice` that records its input stream.

You might need to apply some care to handle muting correctly. In theory you can indeed grab a second input stream for the same device and record that, but muting makes that a little more tricky.

**Comment by adambyer** [comment]
Thanks @richnew10. That's working great.

I need to record both audio and video together as one stream, though. I have that working by creating the `MediaStream` with both audio and video, and then just normally passing the device ids to `chooseVideoInputDevice` and `chooseAudioInputDevice`. 

At first I tried passing the `MediaStream` I created to those methods but that caused feedback and audio/video out of sync (which makes sense I guess). I was trying to avoid having those methods create streams.

Is there any way I can avoid having the additional streams created by `chooseVideoInputDevice` and `chooseAudioInputDevice` when ids are passed in? It seems like in my case that's just wasted resources. Ideally I'd create one `MediaStream` that could be used for recording as well as for the Chime session. Or maybe I'm overthinking it... I'm not really sure how much of a hit on resources those extra streams would cause.

**Comment by richnew10** [comment]
@adambyer: 

Chime manages the audio and video streams independently, for several reasons: they are transmitted separately, can be disabled and replaced separately, and transforms (like Amazon Voice Focus) can 'wrap' streams prior to them being sent to the conference.

You can probably figure out a scheme where you `clone` your combined `MediaStream` twice, removing the audio tracks from one clone and the video track from another, and then choosing each as appropriate. 

I don't know if there's any value to doing so, and I encourage you to do some coarse-grained measurement and assessment if you try: intuition is not a reliable guide when it comes to browser media, and you might find that the browser is already reusing appropriate resources under the hood.

**Comment by adambyer** [comment]
That makes sense. Thanks again @richnew10!

**Comment by adambyer** [comment]
Quick related follow-up question. Where could I put in a feature request for Chime SDK to support native recording of individual streams? There doesn't seem to be a Chime category in the forums. Recording individual streams is supported by other video conferencing providers such as Twilio, OpenTok, OpenVidu, etc and would be a great addition to Chime SDK for me since I am trying to transition away from OpenTok. They provide REST endpoints to start/stop recording for the meeting and recordings can be individual streams or combined and when the videos are ready they automatically upload them to your personal S3 bucket.

Thanks.

**Comment by richnew10** [comment]
This is a perfectly fine place, @adambyer!

If you have an AWS account manager, you can also provide feature requests to them, but the service teams do pay attention to these issues.

**Comment by vidya-mohan** [comment]
@adambyer could you try out https://github.com/aws/amazon-chime-sdk-js/pull/1281 and share your feedback?

**Comment by adambyer** [comment]
Hi @vidya-mohan. Thanks for the follow-up. I actually have a solution using MediaRecorder, but what I was hoping for was the ability to have streams recorded by the video server, instead of on the front-end. Recording on the video server and uploading those recordings to S3 is what other video conferencing services support. Doing it on the front-end is working ok for me, but it takes up resources unnecessarily and I've also had to do quite a lot of work on the back-end to be able to pass the recorded data, save files, etc, which also significantly increases infrastructure costs/issues.

Chime SDK is great and I prefer it over OpenTok, Twilio, etc... but that's one thing they have that would be awesome to also have in Chime SDK.

Thanks.

**Comment by dinuone** [comment]
is there any way to get local audio media stream and remote participant audio stream?
