### ISSUE TITLE
bind multiple video element to VideoTile

### ISSUE THREAD

**Issue by asc0910** [aws/amazon-chime-sdk-js#976]
I want to show a remote video in the menu and main contents
But in the CreatePeerConnectionTasks.ts it creates only one video tile and if only one video element can be bounded to a video tile
![screenshot_02](https://user-images.githubusercontent.com/34391183/103092663-f359f480-4632-11eb-9410-fc3f81691941.png)
![screenshot_03](https://user-images.githubusercontent.com/34391183/103092767-46cc4280-4633-11eb-8cf1-b9fb9b70c49f.png)

For example, local video does not show properly when I bind multiple video elements to the local video tile.
Please let me know how to show multiple videos with a stream.

**Comment by p-foucht** [comment]
Hi @asc0910 

I'm not sure Chime has APIs to support this, but you might consider looking into the `MediaStream.clone` API

https://developer.mozilla.org/en-US/docs/Web/API/MediaStream/clone

**Comment by michhyun1** [comment]
I think what you may want to try is to just call addVideoTile, which will create a new tile and its tileState. Then you could bind the newly created video tile to the videoElement by calling bindVideoElement(*newTileId*, *videoElement*). Once its bound to that videoElement, you'd have to attach a media stream to the srcObject of the videoElement and update the boundVideoStream of the tileState to point to that same stream. This isn't exactly a use case we support, but I think you could do something like this to achieve a similar effect.

**Comment by p-foucht** [comment]
You will need to manually manage that video and delete/stop it when the stream stops, but here's a quick code snippet of what it might look like using the `MediaStream.clone` API. I ran a quick test and it seemed to work fine

```
videoTileDidUpdate(tileState) {
  // ...

  if (tileState.boundVideoStream) {
    const clonedStream = tileState.boundVideoStream.clone();
    myVideoThumbnail.srcObject = clonedStream;
    myVideoThumbnail.play();
  }
}
```

Closing this issue, but if you run into issues please reopen/post here
