### ISSUE TITLE
Content share with audio

### ISSUE THREAD

**Issue by jkelting** [aws/amazon-chime-sdk-js#986]
When I share my entire screen with audio I get accoustic feedback. This happens for everyone in the meeting. Is this happening only for me or is it a known issue? When I share a tab of my browser with audio it works fine. Unfortunatly I cant share the audio of an application window, since the checkbox to share the audio is missing. Is the missing checkbox intended?

**Screenshots**
One screenshot shows the missing checkbox for content share of an application window
<img width="459" alt="application_window" src="https://user-images.githubusercontent.com/68275770/103699318-0d84c280-4fa3-11eb-94fc-d8edecc68813.png">
<img width="461" alt="entire_screen" src="https://user-images.githubusercontent.com/68275770/103699322-0eb5ef80-4fa3-11eb-975e-59b470c3d348.png">

**Platform**
 - Windows 10, IOS (Iphone 11)
 - Browser: Safari, Chrome & Edge 
- Chime SDK JS 2.1.0 & 1.17.2

Best regards
Jan-Philipp Kelting

**Comment by richnew10** [comment]
I can repro this on macOS when sharing a Chrome tab (which is the only place you can share audio).

**Comment by jkelting** [comment]
Well as you can see in the second screenshot, I can also share audio when I schre my entire screen. That when I the acoustic feedback.

**Comment by richnew10** [comment]
Where you get the audio from is platform-dependent. On Windows I believe you can only share audio when you share the entire screen. On macOS you can only share audio from a Chrome tab. 

The bug is the same; thanks for reporting!

**Comment by jkelting** [comment]
Okay, got it. Just to maybe help a little and be really clear. On Windows you have two options to share audio. And one of them works (Chrome Tab).

**Comment by richnew10** [comment]
v2.4 includes a change that might fix this issue. Could you please test, @jkelting?

**Comment by jkelting** [comment]
Works on my machine. Thanks for the update. I will ask somone with a mac to also do a test.
Thanks again!

**Comment by michhyun1** [comment]
Closing this issue, as it looks as though the fix has been released. Please reopen if necessary. Thanks

**Comment by paul365** [comment]
Hello, I am able to reproduce this at v2.29.0. Echo when sharing the **entire screen with system audio**. Not experienced when sharing tab audio.

**Comment by g8z** [comment]
> Where you get the audio from is platform-dependent. On Windows I believe you can share audio when you share the entire screen. On macOS you can only share audio from a Chrome tab.
> 
> The bug is the same; thanks for reporting!

What is the status of a fix for this issue? It's really adversely affecting us.
