### ISSUE TITLE
videoAvailabilityDidChange doesn't get fired sometimes when there are 16 people with video

### ISSUE THREAD

**Issue by abhijeet-toptal** [aws/amazon-chime-sdk-js#989]
**Timeline**
Outline the main actions the user performed and when:

* 16 people joined the call and have their videos turned on.
* 17th person joined the call (lets call him Foo) and obviously videoAvailabilityDidChange didn't fire, and hence 17th person can't start their local video.
* One of the initial 16 people turned off their camera or left the call.
* videoAvailabilityDidChange didn't fire for Foo. But should have, so he can start his local video.

**Describe the bug**
videoAvailabilityDidChange didn't fire properly.

**Platform**
 - OS: All
 - Browser: All 
 - Browser Version: All 
 - Amazon Chime SDK GitHub Commit: 2.3.0

**Comment by RidipDe** [comment]
Can you please confirm that [this](https://github.com/aws/amazon-chime-sdk-js/blob/master/guides/07_FAQs.md#what-happens-to-the-subsequent-participants-who-try-to-turn-on-the-local-video-while-16-participants-have-already-turned-on-the-local-video) behavior is what you do not observe ?

You also mentioned sometimes, how frequently do you observe this issue? Between the 3rd & 4th steps, did Foo try to turn on the video manually (after 16th person turned off the camera) ?

Can you please confirm the Browser/OS ?

**Comment by abhijeet-toptal** [comment]
@RidipDe Let me try to explain the issue in a bit more detail:
1. A joins, we show the local tile to the person A in preview mode.
2. videoAvailabilityDidChange got fired for A, and then we turn off the preview mode for local tile and start local video tile.
3. B joins, and we do the same, first show the local tile in preview mode.
4. videoAvailabilityDidChange got fired for B, and then we turn off the preview mode for local tile and start local video tile.
5. A and B can see each other, everything is fine.
6. C, D, E, F....P(16th person) joins in the same way, and everything is just perfectly fine, they can see each other. videoAvailabilityDidChange was fired for all of them. All of them have their local video turned on.
7. Q joins (17th person) and have their local tile in preview mode, just like A-P, but videoAvailabilityDidChange didn't fire, which is expected.
8. D drops the call(or turn off their camera), then videoAvailabilityDidChange should fire for person Q, but it doesn't.
9. D joins back(or turn their camera on), videoAvailabilityDidChange was fired.

Ideal behavior should be:
When D drops the call or turn off their camera, videoAvailabilityDidChange should have fired for person Q, but it doesn't.

**Comment by RidipDe** [comment]
I tried the steps mentioned above, but was not able to reproduce it at my end. 
Can you please confirm, how often you are encountering the issue?

**Comment by abhijeet-toptal** [comment]
Pretty often, 9 out of 10 times. And by the way, how do you simulate 16 people in the meeting room?
I have to hire people to help me test the cases every time.

**Comment by abhijeet-toptal** [comment]
@RidipDe Any updates on this?

**Comment by abhijeet-toptal** [comment]
@RidipDe any updates?

**Comment by vidya-mohan** [comment]
@abhijeet-toptal - apologies for the delay in response. Thank you for the detailed steps!

We are having trouble reproducing the issue - can you share meeting ids and attendee ids with timestamps or logs? Did you see videoSendDidBecomeUnavailable file after the 16th attendee turns their video on?

We performed the simulation manually using different browsers/tabs and also programmatically using an internal tool which is not on Github.

**Comment by abhijeet-toptal** [comment]
ok our flow is bit different than yours(meetingV2)

| Your example  | Our app |
| ------------- | ------------- |
| Show preview before joining  | Same  |
| Local video is turned off by default and user has to click on camera button | Local video is turned on when there's an event videoAvailabilityDidChange  with canStartLocalVideo as true  |

Now when there are already 16 people in the room, obviously for 17th person, videoAvailabilityDidChange didn't fire. So 17th person didn't start their local video.

When one of the initial 16 people leaves or turn off their camera, then videoAvailabilityDidChange  with canStartLocalVideo as true should be fired for 17th person. But that is not happening. 17th person has to manually toggle the camera.

**Comment by nicklera1** [comment]
@abhijeet-toptal 
We retried to reproduce the issue mentioned above using your repro steps - but could not repro it. 
PFA video of the same.

Browser used: Chrome
OS: MAC 10.14
Application used: JS SDK Demo App

At a high level, the timestamp in the video for our test/observations are as follows:
0:00 - 2:10 -> 16 users joined and turned on videos.
2:12 -> 17th user joins 
2:47 -> One of the first 16 users turns off the video
2:48 -> User number 17 was able to see "video Availability change: canStartLocalVideo" set to true i.e. videoAvailabilityDidChange got triggered [unlike step # 8 in the repro step]
2:49 -> 17th user turns on the video. For all the users in the meeting, "video Availability change: canStartLocalVideo" was then set to false 

https://user-images.githubusercontent.com/20075335/105759807-bd47b300-5f05-11eb-8565-86d8382414e9.mp4



As requested before, can you please confirm the browser you have seen the issue specifically on?
Also, were you able to repro the issue using the JS SDK Demo app? even thought our flow differ the `videoAvailabilityDidChange` event is the same.  In our JS SDK Demo app within dev console you can filter by `[DEMO] video availability changed:` as seen in the video as well.

**Comment by vidya-mohan** [comment]
Resolving as no response. Please cut a new issue or reactivate as needed
