### ISSUE TITLE
Audio garbled on mobile

### ISSUE THREAD

**Issue by ellismarte** [aws/amazon-chime-sdk-js#991]
Does anyone know why audio would be garbled on mobile? It doesn't always happen.

**Comment by RidipDe** [comment]
HI ellismarte,
Can you please let us know what you mean by 'audio would be garbled' - do you mean audio is distorted on mobile devices?

Can you please let us know the device, browser, JS SDK version, OS version you are running it on?
Also please provide us with the repro steps.

**Comment by masaka222** [comment]
I have also encountered this issue. The audio became too "robotic" and I couldn't understand what was going on in the meeting. It happened many times on mobile devices but not always so it's not very easy to reproduce. For me, it was while using safari on an iphone 11 pro with iOS 14, and the JS SDK v1.14.0

**Comment by ellismarte** [comment]
> I have also encountered this issue. The audio became too "robotic" and I couldn't understand what was going on in the meeting. It happened many times on mobile devices but not always so it's not very easy to reproduce. For me, it was while using safari on an iphone 11 pro with iOS 14, and the JS SDK v1.14.0

Yeah my current hunch is it might havve something to do with IOS 14. Looking into it now. Please let me know if you find anything.

**Comment by ellismarte** [comment]
@masaka222 hey what version of chime are you using? I wonder if its because I haven't updated to the most recent version 2.*.*

**Comment by masaka222** [comment]
> @masaka222 hey what version of chime are you using? I wonder if its because I haven't updated to the most recent version 2._._

I updated to version 2 but happened again yesterday so... (only for a minute thought and then it went back to normal again)

**Comment by ellismarte** [comment]
for people wondering what we are talking about here's a video https://ellis-public.s3-us-west-2.amazonaws.com/Image+from+iOS.MP4v

**Comment by ellismarte** [comment]
I
