### ISSUE TITLE
Remove an attendee by their attendee id

### ISSUE THREAD

**Issue by mutaimwiti** [aws/amazon-chime-sdk-js#993]
### What are you trying to do?

*How can I remove an attendee by their attendee id*

### How can the documentation be improved to help your use case?

*For example: Include a section on how to remove an attendee by their attendee id.*

### What documentation have you looked at so far?

*README.md*

**Comment by RidipDe** [comment]
Is the intention to remove the attendee from the active meeting?
There can be two ways to achieve that:

1. The admin can send a message using the data channel like 'leave <attendee id>' and the clients can keep continuously keep listening to such message. The client whose attendee id matches with the <attendee id> sent on the data channel can perform the [leave()](https://github.com/aws/amazon-chime-sdk-js/blob/master/demos/browser/app/meetingV2/meetingV2.ts#L1158) operation.

2. Calling the [DeleteAttendee()](https://docs.aws.amazon.com/chime/latest/APIReference/API_DeleteAttendee.html) API which takes meeting Id and attendee Id as the parameters.

Hope that helps.

**Comment by mutaimwiti** [comment]
Thank you! That helps

**Comment by RidipDe** [comment]
Great!!
Closing the ticket. Please feel to reopen if you have additional questions.
