### ISSUE TITLE
Content share video element should be muted

### ISSUE THREAD

**Issue by richnew10** [aws/amazon-chime-sdk-js#994]
See #986.

The observation on macOS is that the shared tab appears in the content share video element, and that element has audio. It should not, otherwise the customer will hear entirely local echo.

**Comment by richnew10** [comment]
This is turning out to be a little tricky. I can get it working fine for shared tab audio, but the injected-content approach is doubled. Trying to set `muted` on the `content-share-video` element stops it from working at all (!), and the main video element no longer respects the muted flag.

**Comment by RidipDe** [comment]
PR Merged to master https://github.com/aws/amazon-chime-sdk-js/pull/996

**Comment by richnew10** [comment]
Fixed in 2.4.
