### ISSUE TITLE
AWS Chime SDK User without camera/mic disconnects - api error

### ISSUE THREAD

**Issue by kkostenko-dev** [aws/amazon-chime-sdk-js#997]
**Describe the bug**
We use AWS Chime SDK npm packe
We connect several users - OK
We connect user without camera/mic - OK
User without camera/mic disconnects - NOT OK. Causes conference error, where all users are disconnected.  We receive API Error.
 RealtimeApiFailed = 18,
https://github.com/aws/amazon-chime-sdk-js/blob/7a73e038bdea14c6339041e53d50d5d0de069d43/src/meetingsession/MeetingSessionStatusCode.ts#L117

I will add some logs for investigation when I will get them

**Comment by RidipDe** [comment]
It will be great if you can provide us with more information and use the template to elaborate on the issue.

**Comment by kkostenko-dev** [comment]
Important: Please attach INFO-level logs with timestamps to the report from before the session started up until the point at which the unexpected behavior occured. For multi-participant calls, attach a log file for each participant if possible.

[Logs INFO level](https://docs.google.com/document/d/1wfBfLW_hlsiNp8SPDpZUs_92uVGEVeERgDe4yY0c758/edit?usp=sharing)

Meeting and attendee IDs:
List the meeting and attendee IDs that the attached logs apply to.

Meeting ID: 6d19504f-3cc5-4862-83f0-8f67156ac678
Attendee ID: 2d08147e-f6ca-890c-2a2d-9e0fd2edbe2f,  6b797a80-1c74-3644-b1a9-ede2d098c65a
Timeline
Outline the main actions the user performed and when:

ConsoleLogger.ts:75 2021-01-12T09:42:02.055Z [WARN] MyLogger - no transition found from Disconnecting with Update
ConsoleLogger.ts:81 2021-01-12T09:42:02.056Z [INFO] MyLogger - AudioVideoClean/6d19504f-3cc5-4862-83f0-8f67156ac678/6b797a80-1c74-3644-b1a9-ede2d098c65a/Timeout15000ms/CleanStoppedSessionTask took 70 ms
ConsoleLogger.ts:81 2021-01-12T09:42:02.057Z [INFO] MyLogger - timeout task AudioVideoClean/6d19504f-3cc5-4862-83f0-8f67156ac678/6b797a80-1c74-3644-b1a9-ede2d098c65a/Timeout15000ms completed
ConsoleLogger.ts:81 2021-01-12T09:42:02.057Z [INFO] MyLogger - AudioVideoClean/6d19504f-3cc5-4862-83f0-8f67156ac678/6b797a80-1c74-3644-b1a9-ede2d098c65a/Timeout15000ms took 72 ms
ConsoleLogger.ts:81 2021-01-12T09:42:02.057Z [INFO] MyLogger - serial group task AudioVideoClean/6d19504f-3cc5-4862-83f0-8f67156ac678/6b797a80-1c74-3644-b1a9-ede2d098c65a completed subtask AudioVideoClean/6d19504f-3cc5-4862-83f0-8f67156ac678/6b797a80-1c74-3644-b1a9-ede2d098c65a/Timeout15000ms
ConsoleLogger.ts:81 2021-01-12T09:42:02.057Z [INFO] MyLogger - serial group task AudioVideoClean/6d19504f-3cc5-4862-83f0-8f67156ac678/6b797a80-1c74-3644-b1a9-ede2d098c65a completed
ConsoleLogger.ts:81 2021-01-12T09:42:02.057Z [INFO] MyLogger - AudioVideoClean/6d19504f-3cc5-4862-83f0-8f67156ac678/6b797a80-1c74-3644-b1a9-ede2d098c65a took 73 ms
ConsoleLogger.ts:81 2021-01-12T09:42:02.057Z [INFO] MyLogger - transitioning from Disconnecting to NotConnected with FinishDisconnecting
ConsoleLogger.ts:81 2021-01-12T09:42:02.070Z [INFO] MyLogger - API/DefaultAudioVideoFacade/6d19504f-3cc5-4862-83f0-8f67156ac678/6b797a80-1c74-3644-b1a9-ede2d098c65a/getAllVideoTiles
index.tsx:223 ---------------------- sessionStatus --------------------
index.tsx:224 sessionStatus MeetingSessionStatus�{_statusCode: 18}


A demo app's bug causes Chime SDK to stop the session because SDK does not catch an error in its real-time callback.

Steps to reproduce

Attendee A joins a meeting with video and audio.
Attendee B joins the same meeting with muted audio and video.
Attendee B refresh page or leave meeting.
Chime videoMeeting interrups with _statusCode: 18.

If a user with audio and video everything is ok.
Screenshots
If applicable, add screenshots to help explain the problem.

[Video](https://drive.google.com/file/d/1AXNMcneGF_CiG9EjG2usGJgnUH27N1On/view?usp=sharing)

Platform
OS: Windows 10
Browser: Chrome
Browser Version 87.0.4280.141
Amazon Chime SDK GitHub Commit: amazon-chime-sdk-js: 2.3.0

**Comment by cupuyc** [comment]
Hello AWS Chime Team.
Could we have a suggestions on how to move forward with the described issue. 
Maybe hints of why `RealtimeApiFailed` could happen.

**Comment by kkostenko-dev** [comment]
We have found a problem from our side. So this issue can be closed.

**Comment by RidipDe** [comment]
Thanks for letting us know. Closing the issue for now!!

**Comment by ellismarte** [comment]
> We have found a problem from our side. So this issue can be closed.

@kkostenko-dev hey can you talk about what the fix was? im also seeing this error
